=  Anypoint Studio功能
:keywords: anypoint, studio, eclipse, visual editor, xml editor

MuleSoft基于Eclipse的集成开发环境Anypoint Studio为建立，调试和测试Mule应用程序等提供了丰富的功能。


== 基本功能

*  link:/anypoint-studio/v/5/importing-and-exporting-in-studio[导入和导出项目]
*  link:/anypoint-studio/v/5/keyboard-shortcuts-in-studio[键盘快捷键]
*  link:/anypoint-studio/v/5/changing-runtimes-in-studio[改变骡子运行时间]

[TIP]
有关如何使用Visual编辑器和XML编辑器创建Mule应用程序的基本概述，请参阅本节的 link:/anypoint-studio/v/5/[母文件]。

元数据可视化。== 

在设计时通过 link:/anypoint-studio/v/5/datasense[DataSense]接触*metadata*。通过点击流中的任何元素，您可以 link:/anypoint-studio/v/5/using-the-datasense-explorer[看到]描述该元素的期望输入和输出的元数据，并使用Studio已知的所有内容作为推断该元素的上下文。



== 强大的数据映射

通过 link:/anypoint-studio/v/5/using-dataweave-in-studio[*转换消息*]组件处理复杂的数据映射和转换，利用强大的 link:/mule-user-guide/v/3.7/dataweave[DataWeave]语言。该组件允许您通过简单的拖放可视化界面或通过在DataWeave中编码以释放所有语言的潜力来创建转换。


== 调试和测试

=== 嵌入式服务器

Anypoint Studio带有嵌入式测试服务器，可以在不离开IDE的情况下轻松部署应用程序。

[NOTE]
请注意，此服务器不适用于生产部署，因为适用于正常运行时间限制。


=== 可视化调试器

使用 link:/anypoint-studio/v/5/studio-visual-debugger[Studio可视化调试器]运行您的应用程序，通过在您的流程中进行转换以找到问题的根源来放置断点和查看数据。


使用MUnit进行单元测试=== 

使用 link:/munit/v/1.1.1/using-munit-in-anypoint-studio[MUnit]自动为您的应用程序创建和运行单元测试。这样，您可以确定，您对应用程序所做的任何更改都不会使其制动或改变其行为。

==  RAML支持

link:https://raml.org/[肾错构瘤]是一种用于通过非常简单的语法定义API的广泛使用的标准，类似于YAML。

* 您可以使用平台为 link:/api-manager[API管理器]和 link:/anypoint-studio/v/5/api-sync-reference[保持同步]在Anypoint Platform中管理的API导入RAML文件。

* 在使用RAML文件时，您还可以查看嵌入式交互式API控制台，该控制台可以使用RAML中介绍的资源和方法自动构建。

==  APIKit

* 根据 link:https://raml.org/[* *肾错构瘤]或*WSDL*文件，您可以使用 link:/apikit/[APIkit]为Mule应用程序的所有后端流自动构建脚手架，以及异常处理流动。你所要做的就是用操作来填充这些。




== 高级功能

*  link:/anypoint-studio/v/5/starting-the-runtime-in-cluster-mode-in-studio[在Studio中以集群模式启动运行时]
*  link:/anypoint-studio/v/5/adding-source-attachments-to-studio[将源附件添加到Studio]



== 另请参阅

*  link:/getting-started/build-a-hello-world-application[在Anypoint Studio中构建应用程序]。
*  link:/anypoint-studio/v/6/setting-up-your-development-environment[设置你的开发环境]




