= 硬件和软件要求
:keywords: mule, requirements, os, jdk, installation, jre

本页列出了运行MuleSoft产品的硬件，操作系统，Java和其他要求。


==  Anypoint Studio

有关最新的软件更改，请参阅 link:/release-notes/anypoint-studio[Anypoint Studio发行说明]。

[%header%autowidth.spread]
|===
2 + | *Hardware Requirements:*
|
一个| * 4GB的可用内存
*  2GHz CPU
*  10GB可用硬盘空间
2 + | *Software Requirements:*
| *Java Environments*
一个|
*  Oracle JDK 1.8
*  Oracle JDK 1.7.0（推荐： link:http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jdk-7u80-oth-JPR[JDK 1.7.0_79 / 80]） -  *Note*：如果您在新MacOS计算机上安装Anypoint Studio，则还需要安装 link:https://support.apple.com/kb/DL1572[JRE 1.6]

| *Operating Systems*

2015年6月和更新的|：

*  MacOS 10.10.0
*  Windows（32位和64位）Windows 7，Windows 8，Windows 10
*  RHEL 7.0
*  Ubuntu Desktop 16.04
|===

注：对于具有4 GB RAM（操作系统允许的最大值）的Windows 32位，运行其他应用程序时有时会出现内存不足的情况。


作为Eclipse插件的==  Anypoint Studio

[%header%autowidth.spread]
|===
2 + | *Hardware Requirements:*
|
一个| * 3GB的RAM
*  2GHz CPU
*  4GB可用硬盘空间

2 + | *Software Requirements:*

| *Eclipse*

适用于Java开发人员或Java EE开发人员的| * Eclipse 4.4.2
在Eclipse 4.4.2之上运行的*  Spring Tool Suite（STS）版本

| *Java Runtime Environments*

一个| * Studio 2015年6月和更新：Oracle JDK 1.7或Oracle JDK 1.8

*  Studio 2015年3月：Oracle JDK 1.7

| *Operating Systems*

一个| * Windows（32或64位）Windows 7，Windows 8
*  Mac OS（32位或64位）
*  Linux（32位或64位）
|===

获取有关安装 link:/anypoint-studio/v/6/studio-in-eclipse[Studio作为Eclipse插件]的更多信息。
