= 更新Studio，Mule和组件
:keywords: mule, esb, studio, anypoint studio, update sites, updates, extensions, plug-ins, plugins, download

Anypoint Studio中的更新站点用于更新或安装Studio，Mule，连接器或其他有用的开发工具。了解如何从Studio访问和查找更新网站。

[NOTE]
为了使用Studio安装最新的运行时，您必须访问*Anypoint Studio Update Site*。


== 访问更新站点

要在Studio中访问更新网站：

. 转到*Help*> *Install New Software*。
. 从*Work with*字段旁边的下拉菜单中选择其中一个更新网站。
. 如果您没有看到所需的网站，请点击*Add*手动添加。

*Note*：以下列出的网址均不可通过网络浏览器访问。仅在Anypoint Studio *Work with*字段中使用它们。

[WARNING]
====
在继续之前验证您的Studio版本，因为从错误的更新站点安装更新可能会导致错误。

要检查您的Anypoint Studio版本，请转到*Anypoint Studio*> *About Anypoint Studio*。
====

==  Anypoint Studio更新站点

Anypoint Studio应用程序和组件，Mule运行时，SAP连接器和RAML编辑器的更新。

`+http://studio.mulesoft.org/r5/updates+`

*Updates:*

*  DataWeave和DataMapper
*  SAP连接器
*  Mule运行时间3.8.n EE。对于以前的版本，请参阅 link:#mule-versions[演播室的骡子运行时间]

[[mule-versions]]
Studio更新站点的==  Mule运行时

较老的Mule Runtime CE和EE版本

`+http://studio.mulesoft.org/r5/studio-runtimes/+`

==  Anypoint连接器更新站点

适用于Studio安装的所有社区，标准，选择和Premium Anypoint连接器。连接器名称附加了它们支持的最小运行时间。

`+http://repository.mulesoft.org/connectors/releases/3.5.0+`

==  APIkit更新站点

`+http://studio.mulesoft.org/r5/apikit+`

*Provides:*

用于Mule 3.8.0之前安装的*  APIkit Studio插件更新
*  RAML API编辑器更新

详细了解 link:/apikit[APIkit]。

==  API网关更新站点

用于Mule 3.8.0之前安装的API网关运行时更新

`+http://studio.mulesoft.org/r5/api-gateway/+`

Mule 3.8.0将API网关运行时和APIkit与核心Mule运行时统一起来。

==  Anypoint企业安全更新站点

`+http://security-update-site-1.6.s3.amazonaws.com+`
规定：

*  Mule安全模块扩展：
**  CRC-32
** 加密的属性占位符
** 加密
**  OAuth 2提供商
** 安全筛选器
** 签名
*  Anypoint Studio属性文件编辑器

*Note*：您需要Enterprise许可证才能运行包含 link:/mule-user-guide/v/3.8/anypoint-enterprise-security[Anypoint企业安全]功能的应用程序。

== 任意点DevKit更新站点

Anypoint连接器DevKit Studio模块。


`+http://studio.mulesoft.org/r5/devkit+`

==  Anypoint Studio Eclipse插件更新站点

Anypoint Studio的Eclipse插件版本
详细了解如何安装 link:/anypoint-studio/v/6/studio-in-eclipse[Anypoint Studio作为Eclipse插件]。

`+http://download.eclipse.org/eclipse/updates/4.4+`

==  MUnit更新站点

用于测试Mule应用程序的 link:/munit/v/1.3.0/[MUnit]框架

`+http://studio.mulesoft.org/r5/munit+`

== 允许连接通过防火墙更新站点

[WARNING]
====
*Are you behind a firewall?*

如果您位于具有防火墙限制的网络中，则可能会发现Studio更新站点被阻止，您无法下载扩展。配置您的防火墙，以便允许以下网站允许Studio连接到上述更新网站：

允许在防火墙上：

*  `+http://studio.mulesoft.org/+`

*  `+http://repository.mulesoft.org/connectors/releases/+`

*  `+http://download.eclipse.org/technology/m2e/releases+`

*  `+http://download.eclipse.org/eclipse/updates+`

*  `+http://subclipse.tigris.org/+`

*  `+http://findbugs.cs.umd.edu/eclipse/+`

====
