= 配置Mule Hazelcast服务器
:keywords:pcf, hazelcast, clusters, pivotal cloud foundry,

如果您打算将您的Mule应用程序部署到PCF中的群集，则仅需要执行此步骤。有关将应用程序部署为群集的好处的说明，请参阅 link:/mule-user-guide/v/3.8/mule-high-availability-ha-clusters#the-benefits-of-clustering[Mule高可用性集群]。

如果您没有配置Hazelcast群集，则必须使用MuleSoft提供的Mule Hazelcast服务器配置一个群集。

安装群集后，请记下群集节点IP和端口以及群集组名称和密码。您将需要此信息将Mule运行时实例绑定到群集。

===  Hazelcast作为PCF用户提供的服务

为了让Mule应用程序能够采用群集配置，您必须在PCF中为Hazelcast群集中的每个节点创建一个用户提供的服务，您将连接到您的Mule应用程序。你可以通过下面的命令来做到这一点：

[source]
----
cf cups HAZELCAST_NODE_NAME -p ‘{“host”:”HAZELCAST_NODE_IP”,"port":"HAZELCAST_NODE_PORT","clusterId":"HAZELCAST_CLUSTER_GROUP_NAME","clusterPassword":"HAZELCAST_CLUSTER_GROUP_PASSWORD"}'
----

在上面的命令中，替换以下占位符：

*  `HAZELCAST_NODE_NAME`：您正在定义的群集中的Hazelcast节点的逻辑名称。它必须以hazelcast开头。
*  `HAZELCAST_NODE_IP`：IP连接到Hazelcast节点
*  `HAZELCAST_NODE_PORT`：连接到Hazelcast节点的端口
*  `HAZELCAST_CLUSTER_GROUP_NAME`：在Hazelcast群集配置中设置的群组名称
*  `HAZELCAST_CLUSTER_GROUP_PASSWORD`：在Hazelcast群集配置中设置的群组密码

例如：

[source]
----
cf cups hazelcast_dev_node1 -p '{"host":"172.16.12.61","port":"5701","clusterId":"dev","clusterPassword":"dev-pass"}'
----

[NOTE]
在 link:/anypoint-platform-pcf/v/1.5/pcf-workflow[为PCF配置Anypoint Platform]时设置此选项是可选步骤。如果您计划将您的应用程序部署到PCF上的群集，则需要使用它。


Mule Hazelcast服务器是适用于Mule Runtime需求的 link:https://hazelcast.org/[hazelcast]分配的定制。

这个自定义实现根本不会改变Hazelcast行为。它只是设置了所需的基本配置
Mule Runtime加上使用log4j进行日志记录的默认配置。

== 要求

唯一的要求是安装JDK 1.8并正确设置JAVA_HOME环境变量

== 安装

。安装：
* 将分发解压缩到您的工作目录中
* 执行`bin/start.sh`（在Linux中）或`bin.start.bat`（在Windows中）

这将使用位于`conf/hazelcast.xml`文件中的默认配置启动Hazelcast服务器节点。

== 配置

===  Log4j配置

要配置log4j，只需自定义位于`conf/log4.xml`中的log4j配置文件。

===  Hazelcast配置

要自定义Hazelcast配置，只需修改位于conf / hazelcast.xml中的文件
http://docs.hazelcast.org/docs/3.6.2/manual/html-single/[榛子文件]指令。考虑到正在使用的Hazelcast版本是3.6.2。

正确的配置需要：

* 更改默认组名和组密码。这些值用于使用Hazelcast定义一个群集。所有具有相同组名/密码的节点都将创建一个集群
* 配置网络参数以实现群集节点之间的正确通信
