= 迁移到任意平台私有云版本1.5.2

[WARNING]
在迁移过程中，每个节点都可能会因迁移而停机。任何当前登录的用户都将被注销。在输入用户名和密码之前，用户可能需要刷新登录页面。

== 先决条件

在迁移之前，请确保您已经完成并满足以下先决条件：

* 按照 link:backup-and-disaster-recovery[关于备份和恢复]中所述执行系统备份。

* 确保您的环境满足 link:system-requirements[关于最低系统要求]中描述的所有系统和网络要求

* 启用TCP端口`5973`，`3022`，`7373`节点以启用与数据库集群的通信。

* 确保您有权在启动迁移工具的节点上运行`sudo`命令。

* 确保`kubectl`命令在您执行迁移的节点中可用。要验证是否安装了`kubectl`，请运行以下命令：
+
----
$ sudo gravity enter
$ kubectl
----

== 执行升级

. 从您的客户支持代表获取安装人员。

. 使用`ssh`登录到群集的其中一个节点。
+
从单个节点执行这些过程会更新整个平台。

. 解压缩gzip压缩文件。
+
----
tar -xvf anypoint-1.5.2-installer.tar.gz
----

. 转到`anypoint-1.5.2`目录，然后运行上传脚本。
+
----
sudo ./upload
----
+
此命令将平台更新为当前版本并重新启动群集中的每个群集。
+
----
$ sudo ./upload
sudo: ./upload: command not found
[centos@ip-172-31-0-97 ~]$ cd 1.5.2/
[centos@ip-172-31-0-97 1.5.2]$ sudo ./upload
/etc/container-environment: line 19: --exec-opt: command not found
new app package gravitational.io/anypoint:1.5.2-rc.2 has been uploaded to the local site
-> update gravity binary on all nodes
daemonset "gravity-binary-update" created
configmap "gravity-binary-update" created
-> clean up gravity binary update resources
daemonset "gravity-binary-update" deleted
configmap "gravity-binary-update" deleted
-> migrate db and restart gravity site pods
pod "gravity-site-ks4tm" deleted
pod "gravity-site-oemta" deleted
pod "gravity-site-ss6nx" deleted
-> wait until gravity site is running
time="2017-04-04T22:05:21Z" level=info msg="setting state dir as /var/lib/gravity/local" file="gravity/main.go:1209" func=main.newLocalEnvironment 
time="2017-04-04T22:05:21Z" level=debug msg="got search paths: [/var/lib/gravity assets/local]" file="process/cfg.go:25" func=process.ReadConfig 
time="2017-04-04T22:05:21Z" level=debug msg="look up configs in /var/lib/gravity" file="process/cfg.go:35" func=process.ReadConfig 
time="2017-04-04T22:05:21Z" level=debug msg="/var/lib/gravity/gravity.yaml not found in search path" file="process/cfg.go:32" func=process.ReadConfig 
time="2017-04-04T22:05:21Z" level=debug msg="look up configs in assets/local" file="process/cfg.go:35" func=process.ReadConfig 
time="2017-04-04T22:05:21Z" level=debug msg="assets/local/gravity.yaml not found in search path" file="process/cfg.go:32" func=process.ReadConfig 
time="2017-04-04T22:05:21Z" level=info msg="BOLT: readonly /var/lib/gravity/local/gravity.db" file="keyval/bolt.go:122" func=keyval.newBolt 
time="2017-04-04T22:05:21Z" level=debug msg="\nERROR REPORT:\nOriginal Error: *trace.AlreadyExistsError database is already using new system account\nStack Trace:\n\t/gopath/src/github.com/gravitational/gravity/tool/gravity/migratetools.go:62 main.newMigrator\n\t/gopath/src/github.com/gravitational/gravity/tool/gravity/migratetools.go:17 main.migrate\n\t/gopath/src/github.com/gravitational/gravity/tool/gravity/main.go:858 main.run\n\t/gopath/src/github.com/gravitational/gravity/tool/gravity/main.go:55 main.main\n\t/go/src/runtime/proc.go:192 runtime.main\n\t/go/src/runtime/asm_amd64.s:2087 runtime.goexit\nUser Message: database is already using new system account\n" file="gravity/migratetools.go:21" func=main.migrate 
----
+
根据您的网络配置，此命令可能需要一段时间才能完成。等到命令完成后再继续下一步。

. 通过输入以下命令确保`gravity`组件的所有实例都在运行：
+
----
$ sudo gravity enter
$ kubectl get pods --namespace=kube-system
----
+
此命令显示与以下内容类似的输出：
+
----
NAME                  READY     STATUS    RESTARTS   AGE
bandwagon             1/1       Running   0          2h
bandwagon-mulesoft    1/1       Running   0          2h
grafana-pxsmy         1/1       Running   0          2h
gravity-site-35wti    1/2       Running   0          5m
gravity-site-asjda    2/2       Running   0          5m
gravity-site-xm3vd    1/2       Running   0          4m
heapster-gv4zl        1/1       Running   0          2h
influxdb-r3foe        1/1       Running   0          2h
kube-dns-v18-97jb8    3/3       Running   0          2h
kube-dns-v18-lntzw    3/3       Running   0          2h
kube-dns-v18-wvrgi    3/3       Running   0          2h
log-collector-8kovo   1/1       Running   0          2h
log-forwarder-9lpxk   1/1       Running   1          2h
log-forwarder-eiaom   1/1       Running   1          2h
log-forwarder-q536l   1/1       Running   1          2h
----
+
[WARNING]
在继续下一步之前，确保每个`gravity-site-*`实例都在运行。

. 登录Ops中心，然后点击**Updates**标签。

. 点击**Update to this version**更新Anypoint Platform。

== 另请参阅

*  link:system-requirements[关于最低系统要求]
*  link:managing-via-the-ops-center[使用Ops Center管理Anypoint平台私有云版]
