= 支持身份验证
:keywords: devkit, authentication, basic authentication, connection management framework, http basic, oauth

您的服务可能会强制执行某种身份验证，以便应用程序代表用户与您的服务对话。

*Note*：DevKit允许您使用多个`@ConnectionStrategy`注释为连接器创建多个身份验证方法。

在客户端，许多Mule应用程序需要管理到同一目标的多个连接 - 例如，代表数千用户与应用程序交互的应用程序开发人员需要有效地管理可能存在的许多连接在任何特定的时刻。

在DevKit中，连接管理和认证支持密切相关。虽然通用连接管理框架可用于大多数协议，但OAuth认证处理连接管理的方式不同。如果您对OAuth不熟悉，请参阅 link:http://www.cubrid.org/blog/dev-platform/dancing-with-oauth-understanding-how-authorization-works/[与OAuth共舞：了解身份验证的工作原理]，这是一个广泛引用且可访问的概述，介绍不同风格的OAuth的工作方式。

== 先决条件

本文档假定您已经 link:/anypoint-connector-devkit/v/3.8/creating-a-java-sdk-based-connector[创建一个连接器项目]至少具有一些基本功能，现在已准备好在您的连接器上实施身份验证。

== 使用连接管理框架进行基本身份验证

Anypoint DevKit通过在`@Connector`级别应用`@ConnectionManagement`注释，可以轻松地向连接器添加用户名和密码连接管理身份验证功能。使用基本用户名和密码认证（最常见）的连接管理可以轻松地推广到其他非OAuth协议，如SAML，Kerberos，LDAP，NTLM或创建自定义连接。

这个框架提供了以下好处，连接器开发人员的工作量很小：

*  *Transparent Multi-tenancy*  -  Mule应用程序可以打开许多连接到单个目标，使用不同的凭据代表许多用户同时连接。
*  *Connection Pooling*  - 自动管理连接器类的实例池，以有效地管理连接资源。
*  *Exceptions*  - 自动使例外连接失效并根据需要重新连接的功能。

有关更多信息，请参阅 link:/anypoint-connector-devkit/v/3.8/connection-management[连接管理]指南。

==  HTTP基本认证

DevKit按照 link:https://www.ietf.org/rfc/rfc2617.txt[RFC-2617]中的描述为HTTP身份验证提供支持。您可以在您的`@Connector`类中将HTTP身份验证实现为`@ConnectionStrategy`，并且DevKit透明地管理您的请求的身份验证。

有关更多信息，请参阅 link:/anypoint-connector-devkit/v/3.8/http-basic-authentication[HTTP基本认证]指南。

==  OAuth V1

Anypoint DevKit使得连接器上的OAuth V1的实现非常简单。只需在您的`@Connector`类中实现OAuth V1，DevKit就可以管理目标服务的所有请求。

有关更多信息，请参阅 link:/anypoint-connector-devkit/v/3.8/oauth-v1[OAuth V1]指南。

==  OAuth V2

DevKit对OAuth V2的支持包括其自己的连接管理支持形式。在您的`@Connector`类中实现OAuth2，并且DevKit透明地管理多个连接，包括维护与目标服务的多个连接的访问​​令牌。

有关更多信息，请参阅 link:/anypoint-connector-devkit/v/3.8/oauth-v2[OAuth V2]指南。

使用其他身份验证方案的== 连接管理

Anypoint DevKit使连​​接管理框架可用，为多个同时连接提供凭证管理，汇集连接实例以实现高效的连接重用，并提供自动化处理以使失去的连接失效并在需要时重新连接。

link:/anypoint-connector-devkit/v/3.8/connection-management[连接管理]描述了如何使用对`@Connector`类方法的注释将连接管理应用于连接器。该示例描述了使用基本用户名/密码认证的注释，但同样的方法也适用于其他方法。

您还可以将连接管理应用于根本不使用身份验证的连接器。有关在没有身份验证的连接器中实现连接管理的详细信息，请参阅 link:/anypoint-connector-devkit/v/3.8/creating-a-connector-for-a-soap-service-via-cxf-client[通过CXF客户端示例连接到SOAP服务]。

== 另请参阅

*  link:/anypoint-connector-devkit/v/3.8/connection-management[连接管理]（用户名和密码认证）
*  link:/anypoint-connector-devkit/v/3.8/http-basic-authentication[HTTP基本认证]
*  link:/anypoint-connector-devkit/v/3.8/oauth-v1[OAuth V1]
*  link:/anypoint-connector-devkit/v/3.8/oauth-v2[OAuth V2]
* 返回到 link:/anypoint-connector-devkit/v/3.8/anypoint-connector-development[Anypoint连接器开发]
