=  HTTP基本认证 - 已弃用
:keywords: devkit, authentication, http basic

本页讨论了DevKit对HTTP基本认证的支持，以及如何实现使用HTTP认证 link:https://www.ietf.org/rfc/rfc2617.txt[RFC-2617]的连接器对您的API进行认证。

HTTP基本身份验证是用于强制对Web资源进行访问控制的最简单技术。它使用静态的标准HTTP头，这意味着不需要握手就可以完成预期。

== 先决条件

本文假设您熟悉 link:/anypoint-connector-devkit/v/3.8[Anypoint连接器DevKit]，并且准备好在您的连接器上实施身份验证。它假定您熟悉各种 link:/anypoint-connector-devkit/v/3.8/authentication-methods[认证方法]，并且您正在使用HTTP基本身份验证来对您的API进行身份验证。

==  @ HttpBasicAuth注释

要在连接器上实现HTTP基本身份验证，您需要创建一个新类并使用@HttpBasicAuth对其进行注释。

下表介绍了`@HttpBasicAuth`批注的所有参数。

[%header,cols="4*a"]
|===
|参数 |描述 |是否必需？ |默认值
| *friendlyName*  |定义将在弹出的连接器配置中显示的名称。 |✓ |
| *configElementName*  |定义要在mule应用中使用的配置的名称。 |   | config
| *headerName*  |包含在Base64中编码的用户名和密码的标头名称 |   |授权
| *prefix*  |在将用户名和密码编码到Base64之前使用前缀。 |   |基本
|===

== 将@HttpBasicAuth添加到@Connector类

[source,java, linenums]
----
@Connector(name = "connector")
public class MyConnector
{
   @Config
   private HttpBasicAuthStrategy strategy;

   @Processor
   @Restcall(uri = "https://someuri.com/api/method", method = HttpMethod.POST)
   public abstract String method(@RestPostParam("parameter")String param);
}

@HttpBasicAuth(configElementName="http-ba-config", friendlyName="HTTP Basic Auth")
public class HttpBasicAuthStrategy
{
   @Configurable
   @BasicAuthUsername
   private String username;

   @Configurable
   @BasicAuthPassword
   private String password;
}
----

===  @ HttpBasicAuth必需的类属性

您的策略类需要`@Configurable`实例属性，以允许用户在使用连接器时指定其用户名和密码，如上所示：

*  `@BasicAuthUsername`拥有用户名
*  `@BasicAuthPassword`保存密码

*Important*：确保这些实例变量具有公共getter和setter（未显示）。

===  @ HttpBasicAuth仅适用于@Restcall @Processor（已弃用）

由于HTTP基本验证是HTTP用户代理的一种方法，它在使用静态标准HTTP头进行请求时提供用户名和密码。您只能将此身份验证方法用于REST调用操作。

== 另请参阅

link:/anypoint-connector-devkit/v/3.8/authentication[认证]
