= 打包发布的连接器
:keywords: devkit, connector, packaging, documenting use cases, readme

当您的连接器准备好向广大用户发布时，请采取以下额外步骤以确保用户成功：

* 为您的连接器创建许可协议。
* 查看使用 link:/release-notes/anypoint-connector-devkit-3.9.x-release-notes[DevKit 3.9]构建连接器并打包两套连接器徽标图标以支持旧版和新版Studio界面的优点。
* 开发端到端的演练以说明如何使用连接器执行常见用例。
* 使用Maven创建一个压缩文件进行分发。

== 先决条件

本文假定您有：

* 开发您的连接器
* 记录连接器准备发布。有关记录连接器的更多信息在下一节中提供。
* 完成测试，如 link:/anypoint-connector-devkit/v/3.8/developing-devkit-connector-tests[开发DevKit连接器测试]中所述。

== 在打包之前记录用例

在打包和释放连接器之前，我们建议您有效地记录连接器。有用的文档可以帮助减少支持和培训成本，并提高客户满意度。

文档提示：

*  *Readme*  - 提供客户可以随时访问的自述文件。最好的自述文件会在安装过程中自动出现，例如安装向导的一部分。自述文件需要包含安装信息并解释客户在安装连接器之前需要先安装或配置的所有必需软件。
*  *Use Cases*：解释客户使用连接器的原因，时间和方式。对于每个用例，请提供解释示例。
*  *Release Notes*：确保您的连接器具有版本，并帮助客户了解各版本之间的变化。我们建议您列出新功能，已知问题以及修复了哪些问题。
*  *APIDoc*：生成利用Javadoc的 link:/anypoint-connector-devkit/v/3.8/connector-reference-documentation[连接器参考文档]，运行从连接器根文件夹运行的简单Maven命令。

== 应用许可协议和标题

打包连接器之前，您可以自定义许可协议的内容，以反映您的条款和连接器许可证所需的措辞。当打包连接器的用户将其安装到Studio中时，将向用户提供许可协议。

在构建过程中，Maven首先在与`pom.xml`文件相同的目录中搜索`LICENSE.md`文件。

如果找不到该文件，Maven将执行以下步骤来查找许可协议：

.  Maven检查与`pom.xml`文件位于同一目录中的`LICENSE.txt`文件。
. 如果`pom.xml`文件包含*Licenses*部分（如 link:http://maven.apache.org/pom.html#Licenses[Maven文档]中所述），则DevKit会尝试从许可证的URL下载文本，然后保存下载的内容作为新的`LICENSE.md`文件。
. 如果上述步骤未找到许可证文本，则构建失败。

除了全局许可证文件之外，DevKit还要求您的源文件还包含许可证标题。要将许可证标头应用于项目中的每个源文件，请在项目根目录下的命令控制台中运行以下命令，该命令包含连接器项目的`pom.xml`文件：

[source]
----
mvn license:format
----

该命令遍历整个项目，并将`LICENSE_HEADER.txt`文件中定义的许可证标头应用于每个源文件。这包括Java文件，SQL脚本，XML文件等。

== 将连接器安装到本地Maven Repo中

运行以下命令，将带有更新许可证信息的连接器安装到本地Maven存储库中。

[IMPORTANT]
在运行此Maven安装命令之前运行`mvn license:format`，因为在安装之前Maven首先验证许可证标题：

[source]
----
mvn clean install
----

[NOTE]
====
要启用详细日志记录，请使用：

`mvn clean install -Ddevkit.verbose.logging=true`
====

使用Maven的== 包装连接器

您可以使用以下Maven命令打包连接器，以便随时随地安装。这会在`.zip`文件中创建一个"update site"，您可以使用该文件在Anypoint Studio中安装连接器。手动。此更新站点包含使用Mule应用程序内部连接器（调色板，XSD，源文件等的图标）所需的所有内容。因此，在打包之前，源文件必须具有许可证标题，这一点很重要。

*Note*：打包连接器不检查源文件中的许可证标题。要打包连接器，请在根文件夹中运行以下命令：

[source]
----
mvn clean package
----

在连接器的`/target`文件夹中找到打包的连接器，以便在Studio中安装并使连接器可用。


== 可选 - 认证和发布连接器

MuleSoft的程序认证并发布通过Anypoint Exchange分发的第三方连接器。有关此计划的更多信息，请转到 link:/anypoint-connector-devkit/v/3.8/connector-certification-program-guidelines[连接器认证计划指南]。


== 可选 - 将连接器上传到Exchange

如果您的连接器已经通过MuleSoft认证，您可以将连接器发布到公共可用的Anypoint Exchange上，并使其可从Exchange访问，以便下载到Anypoint Studio中。 Anypoint Studio通过涵盖所有版​​本连接器的*Feature ID*来识别每个连接器。为了通过 link:/anypoint-exchange[Anypoint Exchange]公开您的连接器，Anypoint Exchange会提示您提供几个必填字段：功能ID，连接器版本号和更新站点URL。


[NOTE]
====
在Anypoint Studio 6.0.1及更高版本中，功能ID不是必填字段。如果未提供Studio可以安装连接器，但Exchange将无法区分连接器的状态。因此，即使您已安装最新版本，您也将始终在Exchange中看到它旁边的*Install*按钮。

此外，您不需要提供完整版本号。遵循上面的示例，您可以仅提供2.0.1作为连接器版本，Studio将尽最大努力根据此提供的版本查找确切的版本。
====

从Exchange，点击*Add Item*> *Connector*并在*Versions*下输入连接器工件详细信息之前填写表单。按照以下步骤完成发布过程。

. 解压本地创建的包含连接器更新站点的文件。
. 在提取的文件夹中，查找`content.xml`文件并使用文本编辑器打开它。
. 在此文件中，搜索符合以下模式的字符串：`id=’org.mule.tooling.ui.extension.<connector name>.feature.group’`。整个值就是连接器的*Feature ID*。作为一个更具体的例子，您的功能ID可以是`’org.mule.tooling.ui.extension.cloudhub.3.6.0.feature.group’`
. 提供版本字符串，例如`version='1.0.0.201606211519'`，其中的内容为*Connector version*。连接器的用户只能看到短版本号。例如，如果您提供的版本号是`2.0.1.201606101417`，则只能看到`2.0.1`。 （完整版本号仅在编辑Exchange中的条目时显示。）
. 输入连接器工作所需的最小Mule运行时版本。
. 为您的连接器提供*Update Site URL*，并完成Anypoint Exchange上连接器条目的任何其他必要字段，例如指向文档网站的链接。

== 可选 - 更改模块的Studio类别

如果您的扩展程序没有真正限定为连接器，也就是说，它应该理解为属于Anypoint Studio中不同类别的扩展，请将`@Category`注释添加到连接器类中，指定可用的类别之一工作室。你不能定义你自己的类别。

以下是如何在`xyz-Connector.java`文件中添加注释：

[source,java,linenums]
----
@Connector(name = "myext", schemaVersion = "3.4", friendlyName="mine", minMuleVersion="3.5", description="An extension that allows you to extend xyz and perform every xyz operation")
@Category(name = "org.mule.tooling.category.core", description = "Components")
public class MyExtension
{
  ...

----

其他可用类别必须使用以下之一进行定义：

[source,java,linenums]
----
import org.mule.api.annotations.Category;

// Endpoint
@Category(name = "org.mule.tooling.category.endpoints", description = "Endpoints")

// Scope
@Category(name = "org.mule.tooling.category.scopes", description = "Scopes")

// Component
@Category(name = "org.mule.tooling.category.core", description = "Components")

// Transformer
@Category(name = "org.mule.tooling.category.transformers", description = "Transformers")

// Filters
@Category(name = "org.mule.tooling.category.filters", description = "Filters")

// Flow Control
@Category(name = "org.mule.tooling.category.flowControl", description = "Flow Control")

// Error Handling
@Category(name = "org.mule.tooling.ui.modules.core.exceptions", description = "Error Handling")

// Cloud Connectors
@Category(name = "org.mule.tooling.category.cloudconnector", description = "Cloud Connectors")

// Miscellaneous
@Category(name = "org.mule.tooling.ui.modules.core.miscellaneous", description = "Miscellaneous")

// Security
@Category(name = "org.mule.tooling.category.security", description = "Security")
----


== 另请参阅

*  https://www.anypoint.mulesoft.com/exchange/ [Anypoint Exchange]

