=  MuleSoft文档
:keywords: platform, arm, rest, soa, saas, api, proxy, design, develop, anypoint platform, studio, mule, devkit, studio, connectors, auth, exchange, api design, apikit, raml, application network, anypoint, arm, rest, soa, saas, api, proxy

MuleSoft提供的Anypoint Platform可帮助您的组织创建集成和API，简化了连接多个数据源的任务。


[[what-is]]
== 什么是Anypoint平台？

Anypoint Platform是MuleSoft的*integration application and API suite*。它包含一个独特的工具集，使组织能够创建，集成，建模，构建和部署服务，API和Mule应用程序。

Anypoint Platform工具主要通过浏览器访问，但也有命令行工具和API。通过该平台，可以在整个生命周期中控制集成应用程序和API的大部分方面。


== 设置Anypoint平台

按照以下步骤获取Anypoint Platform帐户并设置您的工作站。

*  link:https://anypoint.mulesoft.com/login/#/signup?apintent=exchange[创建一个Anypoint平台帐户]。
* 考虑 link:/mule-user-guide/v/3.8/hardware-and-software-requirements[MuleSoft硬件和软件要求]
* 为了开发Mule应用程序或API设计，请根据 link:#getting-started-dev[开发人员工具包]设置您的工作站。
* 要管理和部署Mule应用，请参阅 link:#getting-started-deploy[部署工具包]。
* 要设置平台权限或监控已部署的资产，请参阅 link:#getting-started-manage[管理员工具包]。



[[getting-started-dev]]
== 开发人员工具包

在获得对Anypoint平台的访问权之后，您就可以与开发与Mule的集成开发了几步。

.  link:/anypoint-studio/v/6/download-and-launch-anypoint-studio[下载并安装Anypoint Studio]。 Studio附带一个测试Mule服务器。
. 如果您是API开发人员，请确保您阅读可从Anypoint Platform访问的 link:/api-manager/[API管理器]，以设计，发布和管理API。
. 检查Anypoint Exchange中的模板，连接器等，您可以在其中查找和发布开发人员资源。您也可以使用Exchange发布专用存储库。

[NOTE]
如果您在Studio以外的Mule工作，或者您拥有企业许可证，请参阅如何 link:/mule-user-guide/v/3.8/configuring-maven-to-work-with-mule-esb[配置Maven]正确管理Mule应用程序使用的依赖关系。

[[getting-started-deploy]]
== 部署工具包

对于*API deployment*，请参阅可从Anypoint Platform访问的 link:/api-manager[API管理器]。

对于*Mule application deployment*，请参阅 link:/runtime-manager/deployment-strategies[部署策略]。本文档解释了标准的应用程序到运行时部署工作流程和工具。


请参阅如何通过Anypoint Platform将应用程序部署到 link:/getting-started/deploy-to-cloudhub[CloudHub]或 link:/getting-started/deploy-to-server[本地Mule运行时实例]的说明。


[[getting-started-manage]]
== 管理员工具包

如果您是管理员，请通过 link:/access-management[访问管理控制台]提供对组织的Anypoint Platform实例的访问权限。

link:/access-management/external-identity[设置外部身份]使用您组织的外部联合身份系统来管理用户和客户端。

要管理Mule应用和服务器，请使用 link:/runtime-manager/[运行时管理器]，这是用于在任何地方将应用部署到Mule的平台工具。

有关API，请参阅 link:/api-manager[API管理器]和 link:/api-manager/[Anypoint分析]。


== 为文档做出贡献

MuleSoft欢迎来自社区的文档贡献。作出贡献：

. 点击任意页面顶部的*Edit on GitHub*。
+
出现GitHub上的源页面。
+
. 点击*Edit this file*，然后使用 link:https://en.wikipedia.org/wiki/Lightweight_markup_language[asciidoc标记语言]进行更改。
. 接受 link:http://www.mulesoft.org/legal/contributor-agreement.html[贡献者的协议]，以便我们确认您的贡献。

有关进行捐助的更多信息，请参阅 link:https://github.com/mulesoft/mulesoft-docs/blob/master/README.adoc[README.adoc文件]。通过改进MuleSoft文档，您在社区中的积极影响受到赞赏和认可。

== 归档文档

有关不再支持或已达到其使用寿命的产品版本的文档，请访问https://docs.archive.mulesoft.com/。

== 另请参阅

*  *NEXT STEP:* link:/getting-started/[入门]为您提供API和Mule应用生命周期的概述。
*  link:/api-manager/designing-your-api[设计一个API]
*  link:/anypoint-studio/v/6/basic-studio-tutorial[基本工作室教程]
*  link:https://anypoint.mulesoft.com/login/#/signin?apintent=exchange[登录Anypoint平台]
