= 数据网关故障排除
:keywords: data gateway, salesforce, sap, oracle, db2, odata, mysql, sqlserver

== 权利支持

您的Anypoint Platform帐户必须拥有必要的权利才能访问Salesforce中的DataGateway Designer。如果您无法访问设计师，请确保您与MuleSoft的合同包含这些权利。如果没有，请联系您的MuleSoft客户团队。
如果您拥有试用帐户，请记住，此试用许可证会在特定时间段后过期。一旦此试用期到期，您也无法访问DataGateway Designer。

==  Salesforce组织匹配

如果您通过Anypoint Platform使用数据网关，则必须将您的Anypoint Platform帐户链接到与所用资源位于同一Salesforce组织的Salesforce帐户。这意味着，如果您为存在于Salesforce组织"A"中的资源创建数据网关，则这些资源不可用于同一Anypoint Platform组织中的其他用户，该组织尝试使用Salesforce组织中的Salesforce用户访问这些数据网关"B"。

== 已知问题

* 在下列情况下网关创建可能失败：

**  相关Salesforce组织在 link:https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/platform_connect_about.html[Salesforce Connect]内没有任何可用外部数据源许可证。
**  相关的Anypoint帐户没有空闲工作人员（大小为1 vCore）。

* 由于此应用程序的后台中发生的配置量较大，网关创建和部署最多可能需要2分钟的时间。加载消息在整个过程中持续存在。

* 由于Salesforce API中存在已知问题，可以通过转到设置>开发>外部数据源，选择已发布的数据源并单击验证和同步（在Salesforce中）来解决任何发布或同步问题。

* 由于环境中的所有对象现在都是通过单个OData API发布的，因此在给定环境中，数据网关中不得有重复的对象名称。

* 为了使用最新的数据映射修补程序，必须创建新的数据网关以替换使用blob，double和datetime字段的旧数据网关。

* 使用连接字符串设置DB2，Oracle或MySQL DataGateway时，Cloud Extender被禁用。 Cloud Extender需要定义的初始主机和端口来打开隧道，并且这些不能从连接字符串安全地派生。连接字符串可以与公共数据库一起使用，也可以通过VPC使用。

* 尝试创建新的数据网关"Error: A message body reader for java.lang.class.org.mule.cs.model.Client, and java type class org.mule.cs.model.Client, and MIME media type text/plain; charset=utf-8 was not found"时显示以下错误消息

**  用户属于拥有正确权限的业务组，但数据网关正在主组织级别中寻找权限，而用户没有权限。因此，返回401并且不能创建数据网关。解决方法是为用户分配主组织内任何给定环境的"DataGateway Administrator"权限，这将允许用户在业务组和现有环境中创建数据网关。

=== 的Salesforce

* 除非您完成 link:/anypoint-data-gateway/installing-anypoint-data-gateway[安装后步骤]，否则安装后产品不会运行。

* 由于Salesforce API中存在已知问题，您可以通过转至*Setup*> *Develop*> *External Data sources*轻松解决任何发布或同步问题，选择发布的数据源并单击*Validate and Sync*（在Salesforce中）。

* 如果您向Salesforce发布超过100个对象，则为其他网关创建单独的环境，因为Salesforce每个端点只允许100个对象。

* 必须通过左侧导航栏中的Salesforce链接重新发布任何已发布的DataGateway（v1.4.0之前），以确保它使用新的单一OData API。

=== 的Oracle

* 如果Oracle Data Gateway无法检索表，请确保该模式全部为大写。

===  DB2

* 由于DB2数据库中存在限制，在具有blob字段的表上使用`$skip`和`$top`运算符进行查询失败。使用$ select过滤所有blob字段。

== 另请参阅
