= 测试API
:keywords: unit testing, api, implement, test, raml, mule
：imagesdir：./_images
：NOINDEX：

您可以使用Anypoint Studio来更改和测试API。 MUnit可以为您的应用程序创建一个单元测试套件。

////
2/14/2018  - 隐藏的东西，今天没有意义。 DOCS-1910

假设您根据前一节中的说明设置了JSONPlaceholder RAML定义，您可以在Anypoint Platform上为示例JSONPlaceholder API创建一个Studio项目。您使用API​​kit来处理由RAML支持的现有API。

. 单击File> New> Mule Project创建项目，并在新项目向导中设置字段值：
+
* 输入项目的任意名称，例如`myproject`。
* 选择一个Mule运行时版本，例如Mule 3.8.0 EE。
* 选中Add APIkit Components。
* 在API定义中，浏览并选择Anypoint Platform。
+
出现API浏览API管理器对话框。
+
. 点击添加凭证。
+
Anypoint平台登录对话框出现。
+
. 输入您的用户名和密码，然后点击登录。
+
您的Anypoint Platform组织中的API的名称和版本（例如企业组织）即会出现。
+
. 选择您想在Studio中使用的API：本示例中的占位符API。点击确定并完成。
+
`placeholder.xml`文件出现在Package Explorer的`src/main/app`文件夹中。 `api-main`流显示在画布的顶部并包含APIkit路由器。在主要流程下面，还有其他由RAML定义的流程，其中一个用于RAML规范中定义的每个资源/方法配对。不要重命名这些流程。
+
注意Mule调色板中的API Sync视图。在此视图中，您可以将您的更改与Anypoint Platform同步，并将所有更新从Anypoint Platform下载到您的Studio实例。
+
项目创建过程还添加了一个参考异常策略来处理所有可能的错误。
+
. 从上下文菜单中选择运行项目> myproject。
+
画布下方的控制台显示构建和部署项目的输出。 “APIkit控制台”选项卡包含与以前在API Designer中使用的模型相同的API操作模型。

使用模拟服务来模拟对API的调用。

////

== 使用MUnit进行单元测试

_unit test_包含验证单个_unit的code_按预期工作。使用MUnit确保应用程序的核心功能按照您的预期运行。 MUnit是Mule应用程序测试框架，允许您为您的集成和API构建自动化测试。我们建议将MUnit集成到您的持续部署环境中。

在这个特定的例子中，您将重点关注根据您的RAML规范验证APIKit路由器配置返回的状态和有效负载。

稍后，您可以选择在部署应用程序之前自动运行每个测试，以确保应用程序根据您的设计工作。

如下所示安装MUnit后，使用其集成的自动测试创建器为基于RAML的应用程序构建必要的测试。


== 安装MUnit

MUnit与Studio 5.4.0及更高版本捆绑在一起。如果您正在运行较旧的Studio版本，则首先需要安装MUnit。使用MUnit，您可以像在Studio中设计Mule应用程序一样设计测试。您可以根据APIKit路由器使用的RAML定义自动生成测试套件。在这种情况下，MUnit会为您在Mule应用程序中创建的每个流创建一个测试，目的是验证每个流的预期_http状态code_和_response payload_。

. 转到帮助>安装新软件...
. 点击添加...
. 设置以下属性：
+
* 以`MUnit Update Site`命名
* 到`+http://studio.mulesoft.org/beta/r5/munit+`的位置
+
. 检查Muit的Munit和Munit工具，然后单击下一步完成安装。
. 安装后，重新启动Anypoint Studio。


== 生成MUnit测试套件

要生成测试套件：

. 停止从Studio运行的任何Mule应用程序。
. 右键单击APIKit路由器> MUnit>为RAML创建placeholder.xml套件。

MUnit为您的应用程序中的每个流创建一个测试，并返回一个MUnit测试套件。

== 执行测试

定义测试的目的很重要。这个自动测试验证由暴露的APIKit端点返回的有效负载和http响应代码。您测试以下事情：

*  `GET`请求收到`200`状态码响应。
* 此响应的有效载荷是您期望的。

要测试此应用程序，请右键单击_Test Suite_工作区中的任何空白区域，然后选择运行MUnit Suite。

每个测试的结果都显示在Anypoint Studio的MUnit视图中。

== 另请参阅

*  link:/getting-started/sync-api-apisync[同步一个API]
*  link:/mule-user-guide/v/3.8/reference-exception-strategy[参考例外策略]
*  link:/apikit/apikit-basic-anatomy[APIkit路由器]
*  link:/munit/v/1.2.0/[MUnit]
*  link:/munit/v/1.2.0/munit-suite[MUnit测试套件]。
