=  Anypoint平台入门
:keywords: getting started, how to, platform, mule, api
：NOINDEX：

欢迎使用入门部分，在这里您可以熟悉最流行的Anypoint Platform工具，这些工具支持您使用API​​和集成应用程序所做的一切。本节中的文档可帮助您构建可重复使用的代码来管理数字资产的集成。整合数字资产的关键是 link:https://www.mulesoft.com/lp/whitepaper/api/api-led-connectivity[以API为主导的方法]。

[TIP]
如果您事先了解API，您可能想了解MuleSoft的旗舰集成平台 link:/mule-user-guide/v/3.8/[骡子运行时间]。 API可以以多种方式与Mule应用程序一起工作。尝试 link:/apikit/[APIkit]或创建一个 link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[公共开发者门户]，以便对组织中的API和其他资产进行自定义访问。

==  API入门

. 找出 link:/getting-started/design-an-api[如何设计一个API]。
. 设计API后，请学习 link:/getting-started/implement-and-test[如何实现和测试API]。
. 要将API引入您的组织或更多受众群体，请参阅 link:/getting-started/sync-api-apisync[如何将API同步到平台]。

== 开始使用Mule应用程序

有关Mule应用程序开发的文档需要熟悉 link:/anypoint-studio/v/6/index[Anypoint Studio]。确保已安装并使用 link:/anypoint-studio/v/6/basic-studio-tutorial[基本工作室教程]熟悉它。

[NOTE]
安装 link:/anypoint-studio/v/6/setting-up-your-development-environment[Anypoint Studio硬件和软件要求]。浏览 link:/anypoint-exchange[Anypoint Exchange]获取所需集成的资源或示例。您可以从浏览器或Anypoint Studio内部访问Exchange，以检索任何MuleSoft和合作伙伴支持的 link:/mule-user-guide/v/3.8/anypoint-connectors[连接器]，以帮助您锁定SaaS应用程序（如ServiceNow和Salesforce）或通用数据结构（如数据库，文件和对象库）。

.  link:/getting-started/build-a-hello-world-application[如何创建一个Mule应用程序]
. 尝试一下您发现的 link:/getting-started/anypoint-connector[Anypoint连接器教程]，Mule应用程序可以以更高的效率完成您已经对SaaS应用程序执行的任何操作。本教程以Twitter服务为例，但您可以插入您选择的另一个连接器。
在一个Mule应用程序中，能够根据消息的内容将消息路由到不同的地方是很重要的。了解如何与 link:/getting-started/mule-message[如何使用骡讯息]中的Mule消息互动，并了解 link:/mule-user-guide/v/3.8/mule-message-structure[Mule 3.x消息结构]。
. 详细了解如何根据 link:/getting-started/content-based-routing[如何根据内容路由Mule消息]中的Mule消息内容进行路由。

[TIP]
link:/mule-user-guide/v/3.8/dataweave[DataWeave]是一个重要的工具，可以让您将复杂的数据转换组织到您的Mule应用程序中，以快速转换Mule消息有效载荷并将其映射到其他数据结构。

=== 部署入门

. 使用运行时管理器 link:/runtime-manager/deploying-to-your-own-servers[部署到您自己的服务器]。
+
[NOTE]
Runtime Manager更灵活，因为它允许在内部或云中对应用进行 link:/runtime-manager/managing-servers[混合动力]管理。
+
. 将应用部署到 link:/getting-started/deploy-to-cloudhub[部署到CloudHub教程]中的CloudHub用户界面中的MuleSoft云服务。

深入研究更多策略，从Mule运行时的 link:/mule-user-guide/v/3.8/installing[安装和部署]文档开始，控制Mule应用程序的运行和管理方式。

== 资源

*  link:/anypoint-exchange/[Anypoint Exchange]
*  link:/mule-user-guide/v/3.8/[骡子运行时间]
*  link:/anypoint-studio/v/6/index[Anypoint Studio]
*  link:/api-manager/[API管理器]
*  link:/runtime-manager/cloudhub[CloudHub]
*  link:/runtime-manager/[运行时管理器]
* 访问任何MuleSoft产品的发布历史记录 link:/release-notes/[发行说明]。
*  link:https://anypoint.mulesoft.com/login/[登录Anypoint平台]
