=  Mule编码惯例

作为团队开发的最佳实践，Mule使用编码约定来确保代码的整洁和一致，并且开发人员能够保持高效的生产力。

== 编码约定

一般来说，Mule遵循 link:http://checkstyle.sourceforge.net[Checkstyle的]惯例。有关更多详细信息，请参阅此示例 link:http://www.mulesoft.org/docs/checkstyle.xml[checkstyle.xml配置文件]。

===  JavaDoc评论

根据以下示例，请包括`JavadocType`和`JavadocMethod`，并附带`JavadocStyle`。我们强烈建议包括`PackageHtml`。 +

[source, xml, linenums]
----
<!-- http://checkstyle.sf.net/config_javadoc.html -->
<module name="JavadocMethod"/>
<module name="JavadocType"/>
<module name="JavadocVariable"/>
----

=== 命名类

按照下面的示例，包含所有标准命名约定。 `AbstractClassName`（强制使用Abstract前缀或Factory后缀）和`ConstantName`（强制执行所有CAPS）可能被排除。

[source, xml, linenums]
----
<!-- http://checkstyle.sf.net/config_naming.html -->
<module name="LocalFinalVariableName"/>
<module name="LocalVariableName"/>
<module name="MethodName"/>
<module name="PackageName"/>
<module name="ParameterName"/>
<module name="StaticVariableName"/>
<module name="TypeName"/>
<module name="MemberName"/>
<!-- <module name="ConstantName"/> -->
----

=== 导入Clases

根据以下示例，请包括`AvoidStarImport`。虽然它使Java文件变长，但它提供了关于类及其用法的明确信息。此外，包括`IllegalImport`，`RedundantImport`和`UnusedImports`。

[source, xml, linenums]
----
<!-- http://checkstyle.sf.net/config_import.html -->
<module name="AvoidStarImport"/>
<module name="IllegalImport"/>
<module name="RedundantImport"/>
<module name="UnusedImports"/>
----

=== 文件大小

包含methodLength检查以确保文件包含不超过2000行，并且方法不包含多于7个参数。

[source, xml, linenums]
----
<!-- http://checkstyle.sf.net/config_sizes.html -->
<module name="FileLength"/>
<module name="ParameterNumber"/>
----

=== 空白

按照以下示例，将`tabWidth`属性设置为4。

[source, xml, linenums]
----
<!-- http://checkstyle.sf.net/config_whitespace.html -->
<module name="EmptyForIteratorPad"/>
<module name="NoWhitespaceAfter"/>
<module name="NoWhitespaceBefore"/>
<module name="OperatorWrap"/>
<module name="TabCharacter"/>
<module name="WhitespaceAfter"/>
<module name="WhitespaceAround"/>
----

=== 修饰符顺序

要避免在接口和注释上使用多余的修饰符，请按照以下示例中的Java语言规范的顺序进行操作。

[source, xml, linenums]
----
<!-- http://checkstyle.sf.net/config_modifiers.html -->
<module name="ModifierOrder"/>
<module name="RedundantModifier"/>
----

=== 阻止检查

根据以下示例，确保应用块检查，以便不存在空白块，并且所有块都包含在花括号内。

[source, xml, linenums]
----
<\!-\- [http://checkstyle.sf.net/config_blocks.html] \-->
<module name="AvoidNestedBlocks"/>
<module name="EmptyBlock"/>
<module name="NeedBraces"/>
<module name="LeftCurly">
 <property name="option" value="nl"/>
</module>
<module name="RightCurly">
 <property name="option" value="alone"/>
</module>
----

=== 编码

根据以下示例，确保您的项目符合这些通用编码约定。

[source, xml, linenums]
----
<\!-\- [http://checkstyle.sf.net/config_coding.html] \-->
<module name="AvoidInlineConditionals"/>
<module name="DoubleCheckedLocking"/>
<module name="EmptyStatement"/>
<module name="EqualsHashCode"/>
<module name="HiddenField"/>
<module name="IllegalInstantiation"/>
<module name="InnerAssignment"/>
<module name="MagicNumber"/>
<module name="MissingSwitchDefault"/>
<module name="RedundantThrows"/>
<module name="SimplifyBooleanExpression"/>
<module name="SimplifyBooleanReturn"/>
----

=== 设计

根据以下示例，确保您的项目执行封装并遵守标准编码设计。

[source, xml, linenums]
----
<\!-\- [http://checkstyle.sf.net/config_design.html] \-->
<module name="DesignForExtension"/>
<module name="FinalClass"/>
<module name="HideUtilityClassConstructor"/>
<module name="InterfaceIsType"/>
<module name="VisibilityModifier"/>
----

=== 其他

根据下面的例子，确保你的项目符合这些杂项编码惯例。

[source, xml, linenums]
----
<\!-\- [http://checkstyle.sf.net/config_misc.html] \-->
<module name="TodoComment"/>
<module name="UpperEll"/>
<module name="Translation"/> <\!-\- to the Checker \-->
----

== 源文件头

确保所有源文件都包含以下标题。

[source, code, linenums]
----
/*
 *
 * --------------------------------------------------------------------------
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
----

== 的软件包

[%header,cols="34,33,33"]
|===
| {公约{1}}示例 |注意
|表示软件包的名称应该全部小写。 | org.mule.application  | Sun为Java核心软件包使用的软件包命名约定。代表域名的初始包名称必须为小写。
|软件包名称应该是单数而不是复数。 | org.mule.transformer，org.mule.transport  | 
|'org.mule.api'包树应该用于组成API / SPI的所有接口。 | org.mule.api.lifecycle.Callable  | 
|===

=== 接口/类

[%header,cols="34,33,33"]
|===
| {公约{1}}示例 |注意
|表示类型的名称必须是名词，并以大写开头的混合大小写。 | EsbMessage，OrderService  | Java开发社区中的惯例以及Sun使用的类型命名约定用于Java核心软件包。
|接口和类名应避免缩写，描述性和驼峰式。 |接口OrderService +
  NOT：interface OrderServ  | 
|抽象类应以“Abstract”为前缀。 |类AbstractOrderService实现OrderService +
  NOT类OrderServiceAbs实现OrderService  | 
|异常类名称后缀为'Exception' | EngineFailureException扩展了Exception +
  NOT：EngineFailure扩展异常 | 
|理想情况下，接口实现应该在上下文中有意义的前缀。例如'Simple'，'Generic'是可能的。 | GenericLifeCycleManager，SingletonObjectFactory  | 
|默认的接口实现可以用'Default'作为前缀。 |类DefaultOrderService实现了OrderService +
  NOT：class OrderServiceImpl实现OrderService  |为界面方法提供默认行为的接口创建一个简单的类实现并不罕见。 Sun为Java库采用了默认为这些类添加前缀的约定。
|测试类应加后缀'TestCase' | LoanBrokerESBTestCase  | 
|===

=== 方法/变量

[%header,cols="34,33,33"]
|===
| {公约{1}}示例 |注意
|变量名必须以小写开头的混合形式。 |消息，newOrder  | Java开发社区中的常见做法以及Sun为Java使用的变量的命名约定核心包。使变量易于与类型区分，并有效解决潜在的命名冲突，如声明Line行中的;
|表示常量（最终变量）的名称必须全部使用下划线来分隔单词。 | MAX_ITERATIONS，COLOR_RED  | Java开发社区中的惯例以及Sun使用的命名约定用于Java核心软件包。
|表示方法的名称必须是动词，并以小写开头的混合大小写 | getName（），computeTotalWidth（） | Java开发社区中的惯例以及命名约定Sun用于Java核心软件包和JavaBean规范。这与变量名称相同，但Java中的方法已经通过它们的特定形式与变量区分开来。
|缩写和首字母缩写词在用作名称时不应为大写。 | exportHtmlSource（）; +
 不是：exportHTMLSource（）; +
  openDvdPlayer（）; +
  NOT：openDVDPlayer（）;  |对于基本名称使用全部大写将与上面给出的命名约定产生冲突。这种类型的变量必须被命名为dVD，hTML等，这显然是不可读的。上面的例子说明了另一个问题;当名字连接到另一个时，可读性被严重降低;首字母缩写之后的单词并不像它应该那样突出。
|下划线和其他特殊字符不应用于变量名称，方法名称或类名称 |私有字符串名称; +
 非私人字符串名称_;  |私人成员变量经常被赋予一个下划线'_'前缀来表示它的私有成员状态。由于Java编辑通过颜色编码知道变量的状态，所以Mule不使用这种约定。
|泛型变量应该与其类型具有相同的名称。 | void setTopic（Topic topic）+
  NOT：void setTopic（Topic value）+
  NOT：void setTopic（Topic aTopic）+
  NOT：void setTopic（Topic t）+
  void connect（数据库数据库）+
  NOT：void connect（Database db）+
  NOT：void connect（Database oracleDB） |通过减少使用的术语和名称的数量来降低复杂性。也可以很容易地推导出给定变量名称的类型。如果由于某种原因，这个惯例似乎不适合，这是一个强烈的迹象表明，类型名称被严重选择。 +
 +
 非通用变量有一个角色。这些变量通常可以通过组合角色和类型来命名：+
 指向起点，中点; +
 名称loginName;
|所有名称均应使用英文书写。 |   |英语是Mule开发的首选语言。
|必须在直接访问属性的地方使用术语get / set。 | employee.getName（）; +
  employee.setName（名称）; +
  matrix.getElement（2，4）; +
  matrix.setElement（2，4，value）;  | Java社区中的常见做法以及Sun用于Java核心软件包和JavaBean规范的惯例。
|'是'前缀应该用于布尔变量和方法。 | isSet，isVisible，isFinished，isFound，isOpen  |这是Sun使用的布尔方法和变量的命名约定用于Java核心软件包和JavaBean规范。使用is前缀解决了选择诸如状态或标志的错误布尔名称的常见问题。 isStatus或isFlag根本不适合，程序员被迫选择更有意义的名称。
|必须避免取反布尔变量名称。 |布尔isError; +
 不是：isNoError +
 布尔isFound; +
  NOT：isNotFound  |使用逻辑非运算符并产生双重否定时会出现问题。它不是立即显而易见的！isNotError的含义。
|关联常量（最终变量）应该以公共类型名称作为前缀。 | final int COLOR_RED = 1; final int COLOR_GREEN = 2; final int COLOR_BLUE = 3;  |这表示常量属于一起，常量表示什么概念。
|===

== 进口

通常，不要包含明星进口，并确保按字母顺序对所有进口进行分类，并按照每个组的升序进行排序。

[source, code, linenums]
----
org.mule
<blank Line>
com
<blank Line>
java
<blank Line>
javax
<blank Line>
<all other import sorted alphabetically>
----


