= 使用Maven

[WARNING]
请注意，此页面适用于*contributing to the Mule source code*的开发人员。如果您正在寻找关于如何使用Maven来处理Mule应用程序的文档，请访问 link:/mule-user-guide/v/3.4/mule-and-maven[骡子和Maven]。

http://maven.apache.org/[Maven的]是一个项目管理实用程序，您可以使用它开发Mule中的项目。尽管强烈建议，但Maven并不是严格需要在Mule中开发应用程序。但是，要修改或添加Mule源代码，我们坚持使用Maven来保持源代码项目的层次结构是完整的。

您可以使用Maven快速设置和配置您的Mule ESB项目。为了帮助您快速提高工作效率，Mule提供了五个创建模板文件的原型，其中包括所有必需的Java样板内容以及注释中的详细实现说明：

* 使用 link:/mule-user-guide/v/3.4/creating-project-archetypes[项目原型]创建一个Mule应用程序
* 使用 link:/mule-user-guide/v/3.4/creating-module-archetypes[模块原型]创建新模块，例如XML或脚本支持
* 使用 link:/mule-user-guide/v/3.4/transport-archetype[运输原型]创建新的传输，例如JMS
* 使用 link:/mule-user-guide/v/3.4/creating-example-archetypes[示例原型]创建新示例以帮助其他用户快速启动并运行
* 使用 link:/mule-user-guide/v/3.4/creating-catalog-archetypes[目录原型]创建新的配置模式目录及其模式

请注意，如果您在已创建的现有项目或模块上运行原型，它会_updates_而不是创建一个新的项目文件。例如，如果某个项目包含File和VM传输，并且现在您希望它包含File和JMS传输，则可以重新运行指定相同项目名称的项目原型。当您指定要在项目中使用的传输时，原型会更新您的项目文件，添加JMS名称空间并删除VM。访问 http://maven.apache.org/guides/index.html[Maven文档]了解有关Maven的更多详细信息。

[WARNING]
*Maven default local repository location on Windows* +
 +
在Windows中，Maven将库存储在主目录中的.m2存储库中。例如，`C:\Documents and Settings\<username>\.m2\repository`。由于RMI测试在目录名称包含空格的情况下失败，因此您必须将Maven本地资源库移动到名称为_does not_include空格的目录，例如`%M2_HOME%/conf`或`%USERPROFILE%/.m2`

==  Mule源代码子项目

Mule源代码项目整齐地组织成子项目的层次结构。 （子项目有时被称为"modules,"，但为了避免与Mule模块混淆，我们使用"sub-projects"。）每个子项目通常会生成一个Maven工件，通常是一个JAR文件。 Mule构建使用中间项目对象模型（POM）将常见的子项目组合在一起。这些中间子项目是源代码的`mule`文件夹的子文件夹，并在下表中进行了描述。

[%header,cols="2*"]
|===
|子项目 |说明
| buildtools  |工具来构建Mule，脚本和checkstyle配置
| core  | Mule的核心API和功能是所有传输所需的
|个发行版 |构建各种发行版（请参阅下面的<<Distributions>>部分以获取更多详细信息）
|例子 |的例子与全骡分布
支持Mule的|模块 |非传输扩展，例如XML处理，Spring extras或脚本支持
|测试可以作为Mule构建的一部分运行的集成测试。 |
Mule的|工具 |工具，例如运输和项目Maven原型
|传输诸如JMS，VM和TCP传输的Mule传输。 |
|===

== 构建Mule

下表列出了执行构建Mule的共同目标。

[%autowidth.spread]
|================
| `mvn clean`  |从目标目录清除任何构建的工件或中间文件（例如`.class`）
_Default_：`target`
| `mvn install`  |将工件安装到本地存储库+中
_Default_：`~/.m2/repository`
| `mvn test`  |为此子项目运行任何单元测试
默认情况下，Maven为每个构建运行每个项目的所有单元测试，这取决于项目，可能需要很长时间才能完成。如果你愿意，你可以跳过使用这个命令的测试。
|================

=== 分布

将Mule包装进行分销时，所有分销和相关资源都位于`distributions`子项目中。

出于性能考虑，默认情况下，该分配是从项目的顶级目录构建的*not*。您可以从自己的目录构建发行版，也可以通过向您的Maven命令行添加`-Pdistributions`来启用`distributions`配置文件。

下表提供了每种类型分布的简要说明。

[%autowidth.spread]
|=========
| {键入{1}}子项目 |说明 |宽度
|完全独立服务器 | `/distributions/server/full`  |将Mule作为独立服务器应用程序进行打包。包括所有传输，附加功能和所有依赖项。包括用于从本地操作系统启动/停止/重新启动Mule的 http://wrapper.tanukisoftware.org[Java服务包装器]。 |重量级
|自定义独立服务器 | `/distributions/server/custom`  |将Mule作为独立的服务器应用程序进行包装 - 无任何依赖关系。如果用户的项目是基于Maven的，那么这个发行版可以很容易地提供它所依赖的确切的库，因为m2的传递依赖关系的智能解析。   |轻量级
| JCA资源适配器 | `/distributions/jca`  |将Mule打包为与JCA兼容的资源适配器，以部署到J2EE应用程序服务器中。包括所有传输，附加功能和所有依赖项。 |重量级
|嵌入式（合成）JAR文件 | `/distribution/embedded`  |将Mule包装为包含所有Mule类的单个JAR文件，包括所有传输和额外内容。当将Mule嵌入到另一个应用程序中时，或者将Mule与非基于Maven的构建一起使用时，此分布很有用。请注意，当您使用此方法时，您将负责提供任何所需的Mule依赖关系，如下一节所述。 |轻量级
|=========

=== 依赖

与所有Maven项目一样，您必须将依赖关系添加到您的Mule应用程序的`.pom`文件中。

如果使用Mule ESB企业版，则必须添加您在应用程序代码中使用的企业功能的依赖关系。以下列出了Mule ESB企业版依赖项。

[source, xml, linenums]
----
<dependency>
    <groupId>com.mulesoft.muleesb</gropuId>
    <artifactId>mule-core-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-batch-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-boot-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-bti-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-cache-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-cluster-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-multi-tx-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-plugin-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-saml-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-spring-config-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-throttling-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-tracking-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-xa-tx-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-ftp-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-jdbc-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-jms-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-jms</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-msmq-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-wmq-ee</artifactId>
    <version>${version}</version>
</dependency>
----

==  Maven故障排除

本节介绍使用Maven可能遇到的一些问题以及如何解决或解决这些问题。

[%header,cols="34,33,33"]
|===
| {问题{1}}说明 |解
|无法检索文件 |您位于防火墙后面，并收到错误消息，指出无法从中央存储库检索`org.mule.tools`的存储库元数据。 |检查Maven `settings.xml`文件中的代理设置，以确认它们配置正确。
| OutOfMemory错误 |尝试完整构建Mule时遇到`OutOfMemoryError`异常。 |增加PermGen空间大小的最大堆*and*。为此，请在您的shell中导出`MAVEN_OPTS`变量，或将该变量添加到原始mvn脚本中。使用以下内容：+
`MAVEN_OPTS=-Xmx512m -XX:MaxPermSize=256m`
|构建速度缓慢 |  -   |如果您知道您的下载是最新的，则可以使用以下命令使用脱机选项：+
`mvn -o`
|冲突的传递依赖关系 | m2中的传递依赖关系有时是强大和有问题的。例如，许多版本存在冲突的库版本或者当您的类路径中存在不需要的库时。 |使用调试选项以树形格式显示有效的类路径，以便查看每个库的来源：+
`mvn -x`
|运行特定项目的目标 |默认情况下，Maven为项目和其层次结构中的所有子项目执行目标。 |如果您想运行目标只有特定项目（而不是其子项），可以使用非递归选项：+
`mvn -N`
|调试测试失败 |默认的Maven测试运行器Surefire将所有报告输出为一组XML文本和文本文件。任何测试失败详细信息和堆栈跟踪都会写入这些文件而不是控制台，因此打开文件以查找问题可能会很耗时。 |您可以通过添加以下选项临时将输出重定向到控制台： +
`mvn -Dsurefire.useFile=false`此选项跳过文本报告的创建，但仍然使XML报告可用于工具转换。
|===
