= 跟踪场景
:keywords: Anypoint b2b Anypoint Partner Manager concepts

本节标识Anypoint Partner Manager（APM）用于跟踪B2B交换的情景。假定APM的基本知识;请参阅 link:/anypoint-b2b/anypoint-partner-manager[Anypoint合作伙伴经理]了解更多信息。


== 重新显示不完整的交易

在 link:/anypoint-b2b/monitor-b2b-transactions[B2B交易页面]上，Transactions视图包含一个表，其中每一行对应一个事务。第一列显示交易完成状态，如下所示：

绿色选中标记::表示完整的交易。
红色感叹号（*!*）::表示事务有一个或多个错误导致完成。

在识别并修复阻止交易完成的错误原因后，可以使用APM重新运行交易。

可能的错误包括：

* 服务器关闭
* 相关性（例如，地图或代码元素）已更改
* 所需数据不存在

注意：只有在解决问题或导致错误的问题后重播交易。

有关详情，请参阅 link:/anypoint-b2b/transaction-monitoring[交易监控]中的"Transactions View"。

== 重放交易

. 单击与要重播的交易相对应的行。
+
注意：要使交易重复播放，第二个（重播状态）列必须为空白或包含灰色部分圆，但不得包含蓝色部分圆。
+
顶部栏中出现一个蓝色*Replay*按钮。
+
. 点击蓝色的*Replay*按钮
+
该按钮变得不可点击，并且该交易正在重播的消息出现在其位置上。
+
交易完成后，蓝色重播圈会出现在您重放的交易的重播状态栏中。
+
. 要查看重播的事务是成功还是失败，请单击重播的事务。
+
. 在交易明细窗格中，出现*view replays*的链接。
+
这会自动按*Transaction ID*过滤网格，以便仅显示原始事务重放的事务。
+
如果重放的事务再次失败，请重复此过程直到重播完成。
+
您可以通过单击“重播状态”列中出现蓝色重播圆圈的任何事务的“事务处理详细信息”窗格中的链接，查看从给定原始事务处理中重放的所有事务的列表。
+
一旦重播成功，重播交易旁会出现一个绿色检查。
如果您需要继续重播交易，则可以使用与以前相同的重播按钮来完成此操作，但在继续之前您会收到警告并发出警告。这是为了防止不必要的重播发生。

== 常见错误

如果您看到类似性质的非典型错误数量，则可以同时查看所有这些错误。

link:/anypoint-b2b/transaction-monitoring[交易监控]顶部的*Dashboard*提供给定时间范围内发生的事件的摘要（默认为当天），包括在该时间段内检测到的错误数量。

== 查看仪表板中的错误信息

. 将鼠标悬停在错误饼图的不同片段上，查看发生了哪些类型的错误。
. 要查看给定错误类型的信息，请单击其中一个片。
+
出现错误视图，仅显示您悬停的错误类型。
+
这使您能够在这些错误中寻找一种模式，以便于解决错误。当交易失败时这很有用。但您无法仅通过查看交易本身来确定解决方案。
+
右上角的导航按钮可让您查看与这些错误相关联的交易。

== 运输问题识别

如果您注意到您从单一类型的传输中获取大量错误，则可以使用过滤器与 link:/anypoint-b2b/transaction-monitoring[交易监控]上的传输视图结合对传输进行排序。该过滤器允许您查看给定的传输类型，并查看失败和成功之间的差异。

您可以在右侧的传输详细信息窗格中找到其他相关信息。在详细信息窗格中，您可以看到通过上角的导航按钮涉及传输的个人交易发生了什么。

这使您可以在整个周期内跟踪交易，并在必要时通过重播按钮重播它们。

由于一致的导航有助于查找模式和纠正错误，因此许多滤镜从视图中持续存在。这允许您查找跨数据类型的共同点。

当合作伙伴需要记录时，== 

通常，合作伙伴需要与交易，传输或文档相关的特定信息。以下说明访问和使用该信息的方式。

== 查找传输

. 在 link:/anypoint-b2b/monitor-b2b-transactions[B2B交易页面]的*View Dropdown List*上选择*Transmissions*。
+
显示传输视图。
+
. 在*Transmission ID*过滤器中输入合作伙伴ID。
+
传输详细信息窗格中填充了可能与合作伙伴请求相关的信息。
+
. 要复制长字符串以供合作伙伴使用，请点击字符串右侧的*copy*按钮。
+
附加的相关信息可以使用这种视图呈现的各种过滤器和排序方式找到。
+
注意：您始终可以使用*Clear Filters*按钮返回完整视图。
+
如果您需要了解有关传输的更多信息或其在更大范围内的存在位置，则可以单击右上角的*Transaction*按钮以查看上下文中的传输。

== 查找文档

. 在 link:/anypoint-b2b/monitor-b2b-transactions[B2B交易页面]的*View Dropdown List*上选择*Documents*。
+
文档视图出现。
. 在*Document ID*过滤器中，输入合作伙伴为您提供的文档ID。
+
文档详细信息窗格中填充了可能与合作伙伴请求相关的信息。
+
要复制合作伙伴使用的长字符串，请点击字符串右侧的*copy*按钮。
+
附加的相关信息可以使用这种视图呈现的各种过滤器和排序方式找到。
+
注意：您始终可以使用*Clear Filters*按钮返回完整视图。
+
如果您需要了解有关文档的更多信息，或查看它适合放大图片的位置，则可以单击右上角的*Transaction*按钮以在上下文中查看文档。
