= 执行其他安装任务

本主题介绍安装Anypoint Platform Private Cloud Edition后可能需要执行的其他安装步骤。

== 配置备份和还原

安装Anypoint Platform私有云版后，您必须确保您已将系统配置为执行定期备份。您必须安排备份至少每天运行一次。但是，MuleSoft建议您的备份至少每小时运行一次。

有关更多信息，请参阅 link:backup-and-disaster-recovery[关于备份和恢复]。

== 配置日志转发

[NOTE]
本节涉及从Anypoint Platform本身转发日志数据。有关如何从平台上运行的Mule服务器和应用程序转发日志数据的说明，请参阅 link:/runtime-manager/sending-data-from-arm-to-external-analytics-software[将运行时管理器中的数据发送到外部分析软件]。


Anypoint Platform使用`rsyslog`来处理日志记录。要将这些日志转发到远程主机，您必须在Ops Center中进行配置。

有关如何在Ops Center上执行此操作的详细步骤，请参阅 link:/anypoint-private-cloud/v/1.6/managing-via-the-ops-center#configure-log-forwarding[配置日志转发]。


[NOTE]
您必须将日志转发到像Splunk这样的第三方日志解决方案。不支持将数据发送到基于云的日志解决方案，如Splunk Cloud。


== 设置SMTP

为了处理运行时管理器和API管理器的电子邮件警报，您必须在网络上配置SMTP服务器。您必须从“访问管理”面板将本地安装的Anypoint Platform引导至此服务器。

== 提供平台IP或域名

您需要提供将您的Anypoint Platform实例暴露给本地网络的DNS或IP，这对于Mule运行时能够与其进行通信是必需的。您可以通过访问*Access Management*部分轻松完成此操作。


==  SSL证书

为了使用Anypoint Platform，您必须提供SSL凭证。您可以通过Anypoint Platform UI上传证书。每台连接到平台的机器都必须信任该证书。


== 使用第三方认证

您可以让您的用户通过各种第三方认证工具登录到Anypoint Platform。请参阅 link:/access-management/external-identity[外部身份]了解如何在每个可用选项上进行配置。您可以使用 link:/access-management/managing-users#configure-ldap[LDAP]， link:/access-management/managing-api-clients#ping-federate[ping联邦]， link:/access-management/managing-users#instructions-for-saml-configuration[SAML]或 link:/access-management/managing-api-clients#openam[OpenAM]。在此版本的平台上，您的所有用户必须通过外部身份（在您通过安装向导注册的管理员除外）在平台上注册。

== 添加自定义免责声明消息

您可以将自定义消息添加到登录页面，以便组织中的所有用户每次登录时都会看到。

== 安装后

现在您的安装已完成，您的平台已准备好可以使用。在您的外部身份服务中注册的用户应该可以访问您的Anypoint平台 link:/access-management/organization[组织]。作为管理员，您现在可以向这些用户添加 link:/access-management/roles[角色]。您也可以启动 link:/runtime-manager/managing-servers[注册服务器]，然后您可以 link:/runtime-manager/deploying-to-your-own-servers[部署给他们]等。

组织的开发人员通过 link:/anypoint-studio/v/6/index[Anypoint Studio] IDE创建Mule应用程序应设置其编辑器，以便与您本地安装的Anypoint Platform（而不是默认的云Anypoint Platform）进行交互。请参阅 link:/anypoint-studio/v/6/setting-up-your-development-environment#enable-on-premises-setup[启用本地安装]。

有关如何向平台群集添加或删除服务器的指示信息以及安装后可能需要执行的其他更改，请参阅 link:/anypoint-private-cloud/v/1.6/managing-via-the-ops-center[通过Ops中心进行管理]。
