= 安装Demo Bundle

如果您将MULE_HOME [环境变量]设置为较老的Mule ESB安装，则此演示包中包含的脚本将启动旧的Mule实例，而不是此包中的新Mule实例。为防止发生这种情况，请在启动Mule服务器之前清空每个新控制台中的变量。

== 在Windows中清空MULE_HOME：

$ MULE_HOME =
$ export MULE_HOME

要在*Mac*或*Linux*中清空MULE_HOME：
c：/ set MULE_HOME =

== 在步骤4中运行脚本

.  *Windows*：打开*Console*。
+
*Mac*：打开*Terminal*应用程序（应用程序>实用程序>终端）。
+
. 访问您下载恶魔束的目录和文件夹，然后指示您的系统执行脚本。
+
例如，对于*Windows*，键入`/user/aaron/downloads/mule-ha-bundle-3.3.1/bin/startServer1.bat`
+
例如，对于*Mac*或*Linux*，键入`user/aaron/downloads/mule-ha-bundlle-3.3.1/bin/startServer1.sh`
+
. 等待您的系统完成脚本执行。例如，当它完成`startServer1`脚本的执行时，Mule会显示一个读取`Mule is up and kicking (every 500ms)`的通知。

确保在不同的控制台中运行每个脚本，并在运行演示时保持每个控制台处于打开状态。

== 安装演示软件包

. 确保您已在计算机上安装了 http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK6]。
. 下载 http://s3.amazonaws.com/MuleEE/mule-ha-bundle-3.3.1.zip[* Mule HA Demo Bundle *]
. 在您的本地驱动器上，浏览包含您新下载的`mule-ha-bundle-3.3.1.zip`文件的文件夹。如果您的系统尚未解压文件，请立即解压缩。
. 演示包在`mule-ha-bundle-3.3.1/bin`文件夹中包含六个脚本。打开您的*Console*（PC）或您的*Terminal*应用程序（Mac），然后按照列出的顺序逐个执行以下脚本。
..  `clean`  - 清除集群环境以清除以前安装的任何演示软件包。
..  `install`  - 设置集群环境
+
* 创建两个Mule来组成一个群集
* 创建第三个Mule服务器来运行Mule管理控制台
* 创建WidgetUI Web应用程序以将加载应用于群集
* 下载运行WidgetUI应用程序所需的播放框架

..  `startServer1`  - 启动第一个Mule服务器
..  `startServer2`  - 启动第二个Mule服务器
..  `startMmc`  - 启动Mule管理控制台服务器（这可能需要几分钟时间）
..  `startWidgetUI`  - 启动Widget UI Web应用程序


在*production environment*中，各种集群组件将分布在多台机器上，以最大限度地减少单点硬件或其他故障可能导致整个系统崩溃的变化。

出于演示目的，我们在本例中的单个本地驱动器上安装并运行所有群集组件。


[cols="2*",frame=none,grid=none]
|===
| > | link:/mule-user-guide/v/3.3/2-creating-a-cluster[Next：创建群集>>]
|===
