= 目击故障转移

要观察Mule群集如何处理节点故障并继续处理消息，请将大量处理负载应用于群集，然后手动终止群集中两个节点之一。

在开始之前，请阅读本过程中的所有步骤。为了在Mule集群中见证故障转移，您必须准备好在处理过程中快速杀死一台服务器。

. 确保您的屏幕上打开了以下窗口：
.. 在`+http://localhost:8080/widgetUI/+`处显示WidgetUI的浏览器窗口或选项卡
.. 在`+http://localhost:8085/mmc#dashboard+`处显示Mule管理控制台的浏览器窗口或选项卡
.. 显示集群中正在运行的服务器之一的终端或控制台窗口（在本例中为*server1*）。
. 在WidgetUI中，单击*Reset All*重置用户界面中的统计信息。 （重置不会删除Web应用程序发送到群集演示应用程序的所有消息，它只会重置Web应用程序上的统计信息。）
. 在WidgetUI中，在*Number of widgets to send*字段中输入`1000`，然后按*enter*。
. 观察一下WidgetUI中窗格中动态变化的数据。 *Application*窗格中的红色数字表示在cluster-demo-app的流中通过端点移动的消息的数量。
. 快速访问您的*Terminal*或*Console*窗口，然后按*Control+C TWICE*强制立即停止服务器。
+
这模拟了集群中一个节点的故障。
+
. 返回WidgetUI观察集群 - 现在只有一个工作节点 - 因为它继续处理消息，直到它完成所有1000个请求。处理完1000个小部件后的群集活动是：`server 1`在处理过程中被终止。
+
在*Time to Complete Processing Widget*窗格中，最右侧图表中的图表显示集群中两台服务器都处理的小部件数量。在这种情况下，因为我们在处理期间杀死了两台服务器中的一台，所以此特定的图表显示为平坦的; `server 2`执行了大部分小部件处理。
+
. 访问您的Mule管理控制台，单击服务器选项卡，然后单击您的群集的名称以打开群集详细信息屏幕。在“节点控制”窗格中，注意您所杀的服务器的非活动状态，如红色圆圈图标所示（请参阅下图中的服务器A）。
+
. 要再次启动停止的服务器，请访问您的终端或控制台，然后再次执行startServer1脚本。

[cols="2*",frame=none,grid=none]
|===
| > | link:/mule-user-guide/v/3.3/6-troubleshooting-and-next-steps[Next：故障排除和后续步骤]
|===
