= 引导注册表
:keywords: registry, anypoint, studio, esb

Mule ESB提供了一种机制，可以在加载模块或传输时立即将对象添加到Mule注册表中。这对于注册共享转换器或表达式评估器很有用。

使用此机制添加到注册表的所有对象都必须具有默认构造函数。他们可以实现注入接口，如 http://www.mulesoft.org/docs/site/current/apidocs/org/mule/api/context/MuleContextAware.html[org.mule.MuleContextAware]和生命周期接口，如 http://www.mulesoft.org/docs/site/current/apidocs/org/mule/api/lifecycle/Initialisable.html[org.mule.api.lifecycle.Initialisable]。

== 指定要引导的对象

要使用引导机制将对象加载到Mule注册表中，请在属性文件`registry-bootstrap.properties`中指定对象，然后将其存储在传输或模块的META-INF目录中。例如：

[source, code, linenums]
----
src/main/resources/META-INF/services/org/mule/config/registry-bootstrap.properties
----

`registry-bootstrap.properties`文件中的每个条目都是一个简单的键/值对，用于定义对象：

[%header%autowidth.spread]
|===
^ | *registry-bootstrap.properties*

一个| [源代码，亚麻布]
----
myobject=org.foo.MyObject
----
|===

如果此文件位于模块或传输的META-INF目录中，那么在加载该模块或传输时，Mule会向本地注册表中注册一个带有“myobject”键的`org.foo.MyObject`的实例。

如果要确保对象在本地注册表中获得唯一ID，则可以使用`object.n`作为密钥，其中`n`是一个序列号：

[%header%autowidth.spread]
|===
^ | *registry-bootstrap.properties*

一个| [源代码，亚麻布]
----
object.1=org.foo.MyObject
object.2=org.bar.MyObject
----
|===

== 添加变形金刚

添加变压器时，您还可以将变压器的`returnClass`和`name`定义为参数：

[%header%autowidth.spread]
|===
^ | *registry-bootstrap.properties*

一个| [源代码，亚麻布]
----
transformer.1=org.mule.transport.jms.transformers.JMSMessageToObject,returnClass=byte[]
transformer.2=org.mule.transport.jms.transformers.JMSMessageToObject,returnClass=java.lang.String, name=JMSMessageToString
transformer.3=org.mule.transport.jms.transformers.JMSMessageToObject,returnClass=java.util.Hashtable)
----
|===

请注意，用于变压器的密钥必须是`transformer.n`，其中`n`是一个序列号。

如果未指定转换器名称，Mule将自动生成名称为JMSMessageToXXX，其中XXX是返回类名称，如JMSMessageToString。如果未指定`returnClass`，则将使用转换器中的默认值。
