= 选择您的开发环境

[TIP]
====
对于所有新的Mule应用程序开发，MuleSoft建议强大灵活的"two-way" Studio开发环境，该开发环境现已完全集成到Mule ESB中。

使用复杂的*graphical interface*，开发人员可以将方便的图标拖放到Mule应用程序的原型上。他们可以通过图形属性窗格立即配置这些应用程序流程，配置有上下文相关帮助，验证选项列表和其他自动完成辅助工具。

强大的*XML editor*为开发人员提供了通过剪切和粘贴整个Mule文档中找到的代码示例来组装或调整其Mule应用程序的选项 - 或者通过手动输入XML代码并使用内置的自动完成工具，如果他们希望。

无论您选择图形还是基于代码的开发，您都可以使用基于图形和基于代码的接口*_both_*，这些接口在整个开发过程中保持同步。

此外，Studio还集成了Maven，Github和SubVersion。
====

本节介绍如何以及为什么选择Mule ESB 3的特定开发环境。

==  Eclipse和Mule IDE

MuleSoft构建了Mule IDE作为Eclipse插件。您需要受支持的Eclipse版本才能安装并运行Mule IDE。

从http://www.eclipse.org/downloads/下载最新版本的Eclipse并安装它（Mule IDE将与Eclipse 3.4或更高版本的现有安装配合使用）。建议使用Eclipse Java EE Developers软件包，但如果符合您的需求，则可以安装Java Developers软件包。

Eclipse的受支持版本：

*  Eclipse版本3.4（Ganymede）
*  Eclipse版本3.5（伽利略）
*  Eclipse版本3.6（Helios）

== 的Maven

Maven是一个配置管理工具，在使用Mule进行开发时非常有用。这是一个Apache项目，不包含在任何Mule发行版中。它基于原型架构，您可以为特定项目，传输和其他工件生成原型。 Maven知道从互联网存储库获取软件的位置，因此如果您使用特定的软件安装依赖性对其进行配置，则它会自动为您检索软件并根据您指定应该运行的方式对其进行配置。

Maven并非严格需要开发使用Mule，但它可以使Mule的开发更加简单和直接，并且推荐使用。
