= 配置安全性

Mule ESB允许您使用特定于传输的或通用的身份验证方法通过端点对请求进行身份验证。它还允许您控制组件的方法级别授权。安全管理器负责基于一个或多个安全提供者对请求进行身份验证。所有安全性均可通过 http://www.mulesoft.org/docs/site/current/apidocs/org/mule/api/security/package-summary.html[Mule安全API]插入，因此您可以轻松插入自定义实施。

有关可以为安全管理器配置的元素的信息，请参阅 link:/mule-user-guide/v/3.4/security-manager-configuration-reference[安全管理器配置参考]。以下各节提供了有关配置不同类型安全管理器的信息的链接。

[NOTE]
====
*新的Anypoint企业安全功能

除了本页介绍的安全功能之外，Mule还提供了六项新的安全功能：

*  Mule安全令牌服务（STS）Oauth 2.0提供程序
*  Mule凭证库
*  Mule消息加密处理器
*  Mule数字签名处理器
*  Mule滤波器处理器
*  Mule CRC32处理器

有关这些功能的更多信息以及下载它们的说明，请参阅 link:/mule-user-guide/v/3.4/anypoint-enterprise-security[Anypoint企业安全]。
====

==  Spring Security 3.0

Spring Security是Acegi的下一个版本，提供了许多认证和授权提供程序，如JAAS，LDAP，CAS（耶鲁中心认证服务）和DAO。以下主题将帮助您开始使用Spring Security保护流量：

*  link:/mule-user-guide/v/3.4/configuring-the-spring-security-manager[配置Spring Security Manager]
*  link:/mule-user-guide/v/3.4/component-authorization-using-spring-security[使用Spring Security的组件授权]
*  link:/mule-user-guide/v/3.4/setting-up-ldap-provider-for-spring-security[为Spring Security设置LDAP提供程序]

==  WS-Security和SAML

WS-Security是将安全性应用于Web服务的标准协议。它包含有关如何通过XML签名和二进制安全令牌（如X.509证书和Kerberos票证）以及加密标头强制执行SOAP消息中的完整性和机密性的规范。它通过在应用层而不是传输层工作来确保端到端的安全性。 Mule为WS-Security提供以下资源：

*  link:/mule-user-guide/v/3.4/enabling-ws-security[启用WS-Security]  - 介绍如何使用WS-Security保护您的CXF SOAP端点。
*  link:/mule-user-guide/v/3.4/saml-module[SAML模块]  -  Mule现在支持SAML标准来交换系统间的安全信息。该模块在2.2.3版本的Mule企业版中提供

== 其他安全集成

Mule还支持以下安全技术：

*  link:/mule-user-guide/v/3.4/encryption-strategies[加密策略]  - 通过加密来保护您的邮件。
*  link:/mule-user-guide/v/3.4/pgp-security[PGP安全]  - 通过使用PGP加密来保护您的邮件。
*  link:/mule-user-guide/v/3.4/jaas-security[Jaas安全]
