= 从启动控制Mule

本主题描述如何使用Java服务包装器控制Mule ESB 3，并将参数传递给JVM以控制Mule。

== 了解Java服务包装器

当您运行`mule`命令时，它会在`MULE_HOME/bin`目录中启动`mule.bat`或`mule.sh`脚本。这些脚本调用Java Service Wrapper（http://wrapper.tanukisoftware.org），它从您的操作系统控制JVM并启动Mule。 Wrapper可以处理系统信号，并提供JVM和底层操作系统之间更好的交互。它还提供了许多可以在Wrapper网站上阅读的高级选项和功能。

Java Service Wrapper允许您将Mule作为UNIX守护程序运行，并且可以将Mule安装（或删除）为Windows NT服务。

== 将附加参数传递给JVM以控制Mule

包装提供了多个属性，您可以按照 http://wrapper.tanukisoftware.org/doc/english/properties.html[这里]所述进行设置。如果您想将其他参数传递给运行Mule的JVM，可以将`wrapper.java.additional.n`条目添加到Mule安装目录下的`/conf`目录中的`wrapper.conf`文件，或者您可以传递在命令行添加`-M`开关。

例如，要设置Mule的编码，您可以将`wrapper.java.additional.1=-Dmule.encoding=ISO-8859-1`添加到Wrapper配置文件，或者您可以在命令行中将`-M-Dmule.encoding=ISO-8859-1`添加到Mule脚本。请注意，如果您将`wrapper.java.additional.n`条目添加到配置文件中，则必须将`n`的每个实例更改为连续的数字，否则Java将不会正确分析这些属性。

== 将其他参数传递给包装器

要从命令行控制Wrapper的行为，请在启动Mule时使用-W开关。

例如，要设置Wrapper使用的日志文件，您可以将`wrapper.logfile=/my/log/file.log`添加到Wrapper配置文件，或者您可以在命令行中将`-Wwrapper.logfile=/my/log/file.log`添加到Mule脚本。
