= 下载Mule ESB 3

*此信息当前为Mule 3.3，但下载和安装选项已经更改。有关安装的信息，请参阅当前版本的Mule文档。

本节介绍如何下载Mule ESB 3。

== 了解哪种Mule ESB 3分布最适合您

有三种类型的Mule分布。您选择的分销取决于您的业务需求和当前的发展阶段。

*  **MuleSoft supported release (Mule Enterprise)**：由MuleSoft创建的Mule最新，经过完全测试的版本，其中包含社区版本中未提供的高级功能。 Mule Enterprise提供技术支持，维护补丁和MuleSoft知识库的访问权限，适用于开发，预生产和生产环境。您可以下载并安装Mule Enterprise http://www.mulesoft.com/mule-esb-enterprise-trial-download[这里]的30天试用版。
*  *Latest stable community release*：Mule的最新稳定版社区版本。社区版本在发布之前会经历多次社区QA迭代。如果您正在使用社区版本并遇到无法解决的重大问题，您可以考虑使用MuleSoft的高级支持来考虑Mule Enterprise。你可以在这里下载社区版本。
*  *Snapshot release*：根据最新的代码库（"the bleeding edge"）构建的最新Mule发行版。快照版本可能不稳定，因此它们仅适用于开发环境，而不适用于生产环境。此外，快照版本不包含任何文档。您可以在这里下载最新的快照版本。

您也可以查看源代码并自己构建Mule。有关如何查看Mule源代码的完整信息

== 从下载服务器获取Mule

. 下载Mule。
. 点击您要下载的版本旁边的链接。使用`.zip`链接在Windows上进行安装，并使用`.tar.gz`链接在Linux / UNIX上进行安装。最新版本位于页面的顶部。
{/ 0}在Linux / UNIX上，如果您希望通过shell而不是浏览器进行下载，或者需要在没有X-Windows的情况下下载到远程计算机，则可以使用下载工具下载发行版。例如，要使用`wget`下载Mule 3.1.2快照，您应该在一行中输入以下命令：
+
[source, code, linenums]
----
wget http://snapshots.dist.codehaus.org/mule/org/mule/distributions/mule-standalone/3.1.2-SNAPSHOT/mule-standalone-3.1.2-SNAPSHOT.tar.gz
----
