= 加强你的骡子安装

*  <<Hardening Checklist>>
*  <<Hardening in Layers>>
*  <<More Information>>

与安全性不同，硬化是指为了将应用程序从开发应用到生产而必须执行的步骤。这些都是开发完成后必须跳过的环节，以便在IT空间中部署某些东西。

通常情况下，IT组织已经可以控制将开放端口保持在最低限度，限制对管理应用程序的访问，最大限度地减少应用程序数量和其他内务管理。当然，用于配置Mule的文件应该与任何配置文件一样安全。

== 强化清单

这里列出了你可以采取的简单步骤来开始强化Mule安装本身：

* 将Mule作为非特权用户运行
* 安装Mule即服务
* 确保将Mule配置为在适当的位置写入日志或临时文件。配置日志，密码和密钥库文件
* 在某些情况下，您需要在Mule上配置用户名，密码和密钥仓库。通常，这些设置可在外部使用，以便dev / ops可以更改这些设置。
* 管理密钥库文件中的证书
* 使用单独的属性文件来存储用户名和密码，并使用文件系统权限对其进行保护

== 关于将Mule作为非特权用户运行

在Xnix上，您可以像任何用户一样运行mule，但需要注意以下事项：

* 您需要将日志写入日志目录
* 没有root用户，您将无法使用1024以下的端口

在Windows上，您需要在管理员用户组中运行Mule

图层中的== 强化

就其性质而言，Mule可以位于各种配置中。也就是说，建议的硬化方法包括从操作系统开始逐层硬化，然后进行堆栈处理。互联网安全中心（CIS）发布配置基准，这些配置基准被全面或部分广泛用作系统强化指南。 Mule TCat Server还提供了 link:https://blogs.mulesoft.com/dev/mule-dev/is-your-tomcat-secure/[安全选项]。

商业配置管理和完整性管理工具可以帮助您自动管理CIS基准。另外，Mule文档包含大量关于 link:/mule-user-guide/v/3.4/configuring-security[配置安全性]的信息。如果您的应用程序处理敏感数据，请考虑使用SSL（HTTPS）来保护它。

在网络安全方面，安全专家建议使用具有默认拒绝规则集和例外的良好状态检查网络防火墙，仅用于合理的业务需求。此外，任何面向互联网的服务器都属于DMZ，在防火墙上具有强大的默认拒绝出口规则以防止数据泄露。 Furhermore，您可以使用网络IDS / IPS来监视和防止已知的攻击。将数据库放在内部网络上 - 而不是DMZ  - 也将有助于加强您的安装。

确保您的软件开发人员熟悉安全的Web应用程序编码技术。至少，他们应该熟悉最佳做法，以避免常见的网络应用陷阱，例如 http://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project[OWASP的前10名]中列出的陷阱。
