= 安装连接器

== 安装连接器

除了Mule Studio的开箱即用版本之外，您还可以下载更多*Anypoint Connectors*，并使用它们连接到第三方API。如果您想添加到您的Mule Studio连接器目录，可以从*MuleStudio Connectors Update Site*下载更多内容。如果您不使用Mule Studio，则可以将相应的Maven依赖项安装到您的`*pom.xml*`文件中。

===  Mule Studio

. 在*Mule Studio*的`*Help*`菜单下，选择`*Install New Software*`。

. 在*Install*向导的**Work with:**字段中，使用下拉菜单选择`MuleStudio Cloud Connectors Update Site`。
. 展开*Community*和/或*Standard*的节点以查看可供下载的连接器。
. 选中一个或多个连接器旁边的复选框，选择要使用的复选框，然后点击*Next*。

. 在向导的*Install Details*屏幕中查看您的选择，然后点击*Next*。
. 在*Review Licenses*屏幕中选择*I accept the terms of the license agreements*，然后点击*Finish*。
. 点击*Restart Now*完成安装。

.  Mule重新启动Studio，在调色板中显示新的连接器。

=== 的Maven

有关安装说明和可添加到`pom.xml`文件以将连接器安装为Maven依赖项（建议）的可复制粘贴代码，请参阅连接器站点链接的特定于连接器的说明。

== 卸载连接器


===  Mule Studio

. 在*Mule Studio*的`Mule Studio`菜单下，选择`About Mule Studio`。

. 在*About Mule Studio*面板中，点击*Installation Details*，以显示您在Mule Studio实例上安装的连接器的列表。

. 在*Installed Software*标签中，选择您想要卸载的订单项，然后点击*Uninstall…*。要卸载多个项目，请点击选择第一个行项目，然后在点击其他行项目时按住`CRTL`键（PC）或`command`键（Mac）。
. 点击*Finish*以卸载您选择的项目。

=== 的Maven

要卸载连接器，请从您的`pom.xml`文件中移除该连接器的Maven依赖项。

== 依赖

===  Mule Studio

当您为流添加连接器时，Studio会自动将其所有依赖项（包括`.jar`文件）添加到您项目的 http://en.wikipedia.org/wiki/Classpath_(Java)[类路径]。 Mule将每个连接器的依赖项作为Eclipse用户库进行管理。因为Studio会将连接器的依赖项添加到项目的类路径中，所以您可以在Mule Studio实例的其他项目中引用连接器类。

有关在Studio中管理用户库的更多信息，请参阅 link:/mule-user-guide/v/3.3/deploying-studio-applications[部署Studio应用程序]。

==== 禁用连接器依赖项的自动加载

完成以下过程以防止Studio自动将连接器的依赖项添加到项目的类路径中。

. 在主导航栏的*Mule Studio*菜单下，选择*Preferences*。
. 在*Preferences*面板的左侧导航栏中，选择*Mule Studio*。
. 点击复选框取消选择*Add Cloud Connector dependencies automatically to the project class path*。

. 点击*OK*保存您的更改。

==== 手动添加连接器依赖项

完成以下过程以手动将连接器依赖项添加到Studio中的项目类路径。

. 在*Package Explorer*窗格中，右键单击您的项目名称，然后选择*Build Path*> *Add Libraries*。
. 在*Add Libraries*向导中，选择*Mule Cloud Connector Dependencies,*，然后点击*Next*。

. 选中与您希望添加到项目的类路径中的连接器依赖项关联的框。

. 点击*Finish*添加依赖关系。

=== 的Maven

如果您要将连接器安装为Maven依赖项，请确保为每个连接器完成以下三个步骤：

. 要使任何连接器模块可用于Mavenized Mule应用程序，请首先将以下储存库添加到您的`pom.xml`文件中：
+
[source, xml, linenums]
----
<repositories>
    <repository>
        <id>mulesoft-releases</id>
        <name>MuleSoft Repository</name>
        <url>https://repository.mulesoft.org/releases/</url>
        <layout>default</layout>
    </repository>
    <repository>
        <id>mulesoft-snapshots</id>
        <name>MuleSoft Snapshot Repository</name>
        <url>https://repository.mulesoft.org/snapshots/</url>
        <layout>default</layout>
    </repository>
</repositories>
----
+
. 然后将该模块作为依赖添加到您的项目中，将`insert-artifactId-here`替换为您要添加的特定模块的artifactId，并用此模块的版本替换RELEASE。
+
[source, xml, linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>insert-artifactId-here</artifactId>
    <version>RELEASE</version>
</dependency>
----
+
. 如果您计划在Mule应用程序中使用此模块，则需要将其添加到打包过程中。因此，将包含流和Java代码的最终zip文件也将包含此模块及其依赖项。为此模块的Mule-Maven插件的配置添加一个特殊的包含，将`insert-artifactId-here`替换为您要添加的特定模块的artifactId。
+
[source, xml, linenums]
----
<plugin>
    <groupId>org.mule.tools</groupId>
    <artifactId>maven-mule-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <excludeMuleDependencies>false</excludeMuleDependencies>
        <inclusions>
            <inclusion>
                <groupId>org.mule.modules</groupId>
                <artifactId>insert-artifactId-here</artifactId>
            </inclusion>
        </inclusions>
    </configuration>
</plugin>
----

== 另请参阅

*  link:/mule-user-guide/v/3.7/anypoint-connectors[Anypoint连接器]。
*  link:/anypoint-connector-devkit/v/3.3/mule-devkit[的devkit]。
