=  JBoss事务管理器参考
:keywords: mule, esb, studio, jboss, bpms

该模块使Mule能够使用JBoss事务管理器（以前的Arjuna）来配置 link:/mule-user-guide/v/3.7/xa-transactions[XA交易]。开发人员可以配置每个Mule实例的一个Transaction Manger。有关更多信息，请参阅 http://www.jboss.org/jbosstm/[JBoss事务]。

== 配置

要在Mule中配置JBoss事务管理器的实例，请将此元素添加到您的Mule XML配置文件中。您可以在事务管理器上配置任意属性，并将其传递给基础事务管理器。例如：

[source, xml, linenums]
----
<jbossts:transaction-manager>
    <property key="test" value="TEST"/>
</jbossts:transaction-manager>
----

然后，您可以在支持XA事务的端点上声明XA事务，所有这些事务将由JBoss事务管理器进行管理。 Mule自动生成事务管理器XA节点ID。要自己指定ID，请添加以下属性：

[source, xml, linenums]
----
<jbossts:transaction-manager>
    <properties>
        <spring:entry key="com.arjuna.ats.arjuna.xa.nodeIdentifier" value="SomeUserNodeId"/>
    </properties>
</jbossts:transaction-manager>
----

==  JBoss事务管理器的附加属性

您可以为JBoss事务管理器配置许多属性。这些可配置的属性详细 http://docs.jboss.org/jbosstm/docs/4.2.3/javadoc/jts/com/arjuna/ats/arjuna/common/Environment.html[在环境类中]。

以下是一个演示如何配置与事务超时相关的属性的示例。

=== 配置事务超时属性

有两个属性与JBoss事务的超时有关。 （请注意，超时属性的信息来自 http://docs.jboss.org/jbosstm/docs/4.2.3/manuals/html/core/ProgrammersGuide.html#_Toc22872822[这里]）。

*  com.arjuna.ats.arjuna.coordinator.defaultTimeout
** 此defaultTimeout属性定义为此经理创建的每个事务的超时期限。在超时值过期之前尚未终止的事务会自动回滚。默认值是60秒。
*  com.arjuna.ats.arjuna.coordinator.txReaperTimeout
**  JBossTS使用一个单独的收割线程来监视所有本地创建的事务并强制它们在超时过后回滚。为了防止这个收割线程消耗应用程序时间，它只能定期运行。默认情况下，收割线程设置为每120000毫秒监视本地事务。您可以通过设置txReaperTimeout属性来覆盖此默认值。请注意，如果defaultTimeout属性值小于txReaperTimeout属性值，则收割者线程将每隔defaultTimeout秒检查一次事务。

[source, xml, linenums]
----
<jbossts:transaction-manager >
    <property key="com.arjuna.ats.arjuna.coordinator.defaultTimeout" value="47" /><!-- this is in seconds -->
    <property key="com.arjuna.ats.arjuna.coordinator.txReaperTimeout" value="108000"/><!-- this is in milliseconds -->
</jbossts:transaction-manager>
----
