= 调解 - 将业务逻辑与消息分离
:keywords: mediation, business logic, message

Mule ESB的许多优点之一是它可以处理通过各种协议发送的消息。例如，发票可能始终采用XML格式，但在一种情况下它可能通过HTTP到达，而在另一个情况下可能通过HTTP发送到另一个JMS消息，具体取决于哪个应用程序创建了发票。如果一个组件只处理业务逻辑并处理数据，而不处理消息本身，它如何知道如何读取消息可能到达的各种格式？

答案是组件不知道如何阅读消息，因为默认情况下为*components are completely shielded from the message format*。相反，_transport_携带消息，_transformers_根据需要将消息的有效负载（例如发票）更改为组件在将消息传递给组件之前可以读取的格式。例如，如果通过HTTP发送XML发票，则HTTP传输将其转换为Mule消息，变换器根据需要随时更改它（例如从XML到Java对象），并且流将消息引导至每个组件需要处理它。消息的所有传输，转换和路由对组件都是完全透明的。此解耦是_service mediation_。


变形金刚是交换数据的关键，因为它们允许Mule将数据转换为另一个组件或应用程序可以理解的格式。最重要的是，{{0​​}}。消息及其数据只是根据需要发送消息的目标组件或应用程序进行转换，而不是强制将每条消息转换为单个通用数据协议（如XML）和特定的消息格式。 Mule还通过集成模式实现消息内容的丰富化，使您可以在处理过程中检索附加数据并将其附加到消息中。

可以启用多种类型的传输来处理不同的通道，例如通过同步HTTP端点发送消息，然后在客户数据组件已处理异步JMS消息后将其转发。传输层的这种分离使得整个企业都可以重用服务，而不管所做的传统技术决策如何，并且可以根据服务级别协议或围绕可靠性或性能方面的问题来制定不同的协议选择。

调解还意味着政策合规性可以分层到服务之外的架构中。记录，审计和安全监控都可以在不对现有代码进行任何修改的情况下执行。甚至可以根据谁在调用服务或发生了什么路由来应用策略实施。

将业务逻辑与消息的发送和转换分开，可以极大地灵活设置架构，并且使定制业务逻辑变得更简单，而无需担心消息可能到达的各种格式。如果需要，您的组件可以处理消息的原始数据，但不是必需的。
