=  Mule Studio Essentials

Mule Studio是一个基于Eclipse的集成开发环境。它提供了两种开发环境，可用于创建Mule应用程序：

. 可视化拖放式编辑器。
. 一个XML编辑器

无论您在一个编辑器中开发或配置的内容都反映在另一个编辑器中。同一工具，不同的编辑器。

==  Mule ESB和Mule Studio之间的关系是什么？

*Mule ESB*是企业服务总线的核心应用程序。您可以在不使用Mule Studio（又称Mule ESB Standalone或Mule ESB Runtime）的情况下安装和使用Mule ESB，并通过独立的外部集成开发环境（IDE）（如IntelliJ，Eclipse）与其交互 - 构建并运行集成应用程序和Web服务或JDeveloper。

*Mule Studio*是您可以用来访问Mule ESB功能的图形用户界面。您可以使用Studio，Everyman的可视化集成开发环境，而不是在IDE中编写XML代码来创建Mule应用程序。使用Studio（又名Mule ESB Designtime）将元素拖放到位以快速建模，配置应用程序，然后在本地或云中部署应用程序。

=== 甲。模型

可视化编辑器使开发人员能够在构图画布上安排构建块，以创建Mule流，从而形成Mule应用程序的基础。只需在画布上拖放构建块即可创建一系列促进Mule消息处理的事件。

=== 乙。配置

可视化编辑器提供对话框来配置构建块。对话框接受简单的英文条目，而不是格式化的XML，因此开发人员在配置每个构建块时不必打扰XML语法。

已经习惯使用XML的开发人员可能更喜欢使用XML编辑器通过将XML语句直接写入XML配置文件来设置配置细节。 Studio通过提供语法指导（针对自动完成的建议）并提供列出XML属性的可用选项的下拉菜单，从而使XML编码更加轻松。

=== ℃。调试

Studio包含一个调试器来运行Mule应用程序并观察源代码并在执行期间检查变量。在应用程序中设置断点，然后让Mule开始工作。

===  d。部署

在本地部署新的Studio应用程序以进行测试，或在外部部署以使其在生产环境中运行。开发人员还可以将Studio应用程序部署到 link:/mule-management-console/v/3.3[Mule管理控制台]中的应用程序存储库或部署到 link:/mule-user-guide/v/3.3/deploying-studio-applications[CloudHub]。

== 如何使用可视化编辑器

Studio的可视化编辑器分为四个象限：

.  *Package Explorer*
.  *Canvas*
.  *Outline*
.  *Console*

*Package Explorer*以树形格式显示项目文件夹和文件。点击展开或收缩Mule项目文件夹并检查组成Mule项目的文件。

*Canvas*提供了一个便于将Studio组件安排到Mule流中的空间。画布右边的*Palette*显示一个Mule构建块的列表，oyu可以点击并拖动到画布上来构建应用程序。在画布的底部，Studio提供了三个选项卡，提供了与应用程序接口的不同方式。

*  *Message Flow*：便于将Studio组件安排到Mule流中的拖放界面。
*  *Global Elements*：用于为Mule构建块创建或编辑可重用配置的界面。
*  *Configuration XML*：XML编辑器界面显示与消息流画布上排列的构建块对应的XML语句。

*Outline*显示整个画布的小型化概览，以及在画布窗格中滚动显示的方框光标。这提供了完整的Mule应用程序的高级鸟瞰图，因为它超出了画布的边界。

*Console*显示在您创建或运行您的Mule应用程序时Studio报告的事件和问题（如果有的话）的列表。 *JavaDoc*和*Decelarations*标签显示与您代码相关的其他信息类别。

使用Mule Studio在画布上排列建立块以创建流量，这些流量一起构成一个应用程序来处理消息。

困惑？让我们分解它：

=== 构建模块

构建模块是与Mule捆绑在一起的预先打包的业务逻辑单元。顾名思义，它是一个块（实际上是一块代码），你可以用其他块来组织一个结构。在这种情况下，你正在安排积木来形成骡子流。

取决于它们在骡流中的功能，构建块可分为三类：

[%header,cols="10s,65,20"]
|===
| {键入{1}}功能 |示例
|消息处理器 |过滤，更改，路由或验证消息 |有效负载过滤器，选择流控制，电子邮件到字符串转换器
|消息源 |也称为*Inbound Endpoints*将消息接收到流中并触发消息处理（技术上来说，接收消息而不是处理它们的消息源不具备消息处理器的资格） 。 | HTTP端点，Ajax端点
|组件 |预打包或客户编码，集成特定功能（自定义代码可以开发为Java类，Spring bean或Ruby，JavaScript，Groovy或Python脚本）。 |记录器，Echo，Java
|===

要安排构建块以形成流，只需将它们从调色板拖放到画布上即可。

在将构建基块安排到流程中之后，必须单独配置每个构建基块。双击构建块以打开其*Properties*窗格，然后提供配置字段的值。 Studio将所有配置保存在应用程序的XML文件中。要查看流的XML版本，请点击画布下方的*Configuration XML*标签。

=== 流

流程驻留在每个Mule应用程序的核心，编排消息处理，并且有时触发其他流程。通常，消息源会收到一条消息，这会触发主消息处理流程。流中的每个构件都会评估或处理消息，直到消息已经通过流中的所有构件块。

有关流量类型和行为变化的更多信息，请参阅 link:/mule-user-guide/v/3.3/mule-application-architecture[Mule应用程序架构]。

=== 应用

应用程序是一起工作来处理消息的流的集合。简单的应用程序由单个消息处理器组成，但复杂的应用程序可能包含多个流程。在Mule Studio的背景下，术语“应用程序”和“项目”可以互换使用。

=== 消息

消息是Mule应用程序处理的功能数据单元或数据包。例如，提交给Mule购买履行应用程序的每个客户订单都有资格作为消息。每条消息都包含一个头和一个有效载荷，后者可能包含XML，JSON，文件，流，映射，Java对象或任何其他类型的数据。

==  XML编辑器提示和技巧

由于Mule Studio利用Eclipse IDE，Configuration XML编辑器合并了许多Eclipse提供的功能。以下是使用Mule Studio的XML编辑器的便捷提示和技巧列表。

=== 显示属性选项

. 双击选择元素的属性，例如`HTTP endpoint`元素的主机属性。
. 按*Ctrl+space bar*打开您可以为元素配置的建议属性列表（请参阅下文）。
. 使用向上和向下滚动箭头浏览建议。
. 当您突出显示您要使用的属性时，请按enter键将其插入到XML配置中

=== 建议元素

. 输入元素的左括号（<），然后按*Ctrl+space bar*。
. 认识到您正在输入新元素，Studio会列出该特定情况的所有可能元素。
. 使用向上和向下滚动箭头浏览建议。
. 当您突出显示要使用的元素时，请按Enter将其插入到XML配置中。

[cols="1*a",frame=none,grid=none]
|===
> |
====  link:/mule-user-guide/v/3.3/basic-studio-tutorial[Next：基础教程>>]
|===
