= 将Mule与Web Services一起使用

Mule ESB允许使用Web服务的不同集成方案：

* 使用现有的Web服务
* 构建Web服务并将它们公开给其他应用程序
*  link:/mule-user-guide/v/3.3/proxying-web-services[创建现有Web服务的代理/网关]（例如，向现有Web服务添加安全性）

在这里，我们更深入地探讨这些场景中存在哪些选项，并指导您参考其他文档资源和示例。

==  CXF模块概述

在解释使用Mule ESB可以完成的不同Web服务场景之前，重要的是要明白它所依赖的主要技术是 http://cxf.apache.org/[Apache CXF]。 Apache CXF是一个开源服务框架，可帮助您使用前端编程API（如JAX-WS和JAX-RS）构建和开发服务。 Mule ESB现在捆绑提供Web服务集成的 link:/mule-user-guide/v/3.3/cxf-module-reference[CXF模块]，以消耗现有的Web服务并构建新的服务。

[TIP]
从最新版本的Mule ESB开始，推荐使用 link:/mule-user-guide/v/3.3/cxf-module-configuration-reference[CXF模块]来处理Web服务。

== 使用Web服务

如果调用现有的Web服务，通​​常会构建一个Web服务客户端来执行调用。如果您曾经体验过这一点，您会理解它需要一些代码生成 - 您可以通过Apache CXF http://cxf.apache.org/docs/how-do-i-develop-a-client.html[这里]了解不同的方法来完成此操作）。

借助Mule ESB，您可以简化Web服务的使用方式，但主要是在调用服务（例如安全性）时可以使用很多功能，并处理和处理结果，例如转换和使用导致复杂的流程。

Mule ESB提供了不同的方法来使用Web服务：

.  <<Generate and use a client from a WSDL>>
.  <<Use a Client Based on the Interface of a JAX-WS Service>>
. 使用基于"simple"前端Web服务接口的客户端
.  <<Use the JAX-WS Java Client API>>

=== 从WSDL生成并使用客户端

当您需要使用第三方Web服务或其他您没有Web服务代码的情况下，这是一种很好的方法。

以这种方式使用Web服务时，请执行以下操作：

. 使用来自CXF的WSDL to Java工具或 http://cxf.apache.org/docs/maven-cxf-codegen-plugin-wsdl-to-java.html[Maven插件]生成CXF客户端。
. 使用`<cxf:jaxws-client>`组件在Mule配置XML文件中配置客户端。
. 在Mule配置XML文件中配置一个终端，该终端将作为请求服务的传输（通常是HTTP）。

有关更多信息，可以查看 link:/mule-user-guide/v/3.3/consuming-web-services-with-cxf[使用CXF消费Web服务]文档。

=== 使用基于JAX-WS服务接口的客户端

如果您可以访问用于构建Web服务的代码，则可以为您的JAX-WS服务构建客户端，而无需从WSDL生成客户端。

要以这种方式使用Web服务，请执行以下操作：

. 在本地复制您的服务接口和所有数据对象。
. 使用`<cxf:jaxws-client>`组件在Mule配置XML文件中配置客户端。
. 在Mule配置XML文件中配置一个终端，该终端将作为请求服务的传输（通常是HTTP）。

有关更多信息，请阅读 link:/mule-user-guide/v/3.3/consuming-web-services-with-cxf[使用CXF消费Web服务]文档。

=== 使用基于"Simple"前端Web服务接口的客户端

如果您没有使用JAX-WS服务，那么您的服务接口和本地所有数据对象都有副本，并且服务非常简单，您可以考虑为您的简单前端基服务构建客户端，而不生成客户端来自WSDL。

为了以这种方式使用Web服务，请执行以下操作：

. 在本地复制您的服务接口和所有数据对象。
. 使用`cxf:simple-client>`组件在Mule配置XML文件中配置客户端。
. 在Mule配置XML文件中配置一个终端，该终端将作为请求服务的传输（通常是HTTP）。

有关更多信息，请阅读 link:/mule-user-guide/v/3.3/consuming-web-services-with-cxf[使用CXF消费Web服务]文档。

=== 使用JAX-WS Java客户端API

您还可以使用Web服务客户端API与Mule配置以外的Web服务进行通信。这意味着你可以从你的Java类中调用可以在Mule ESB中使用的服务。

像以前一样，根据您是使用WSDL还是通过"code-first"方法构建您的服务，有两种方法可以使用CXF客户端：

*  link:/mule-user-guide/v/3.3/consuming-web-services-with-cxf[使用JAX-WS客户端API]。
*  link:/mule-user-guide/v/3.3/consuming-web-services-with-cxf[构建客户端代理]。

== 公开Web服务

Mule ESB可用于托管您自己的Web服务。以同样的方式，您可以使用Mule ESB的Web服务，您也可以构建并公开它们。这里有三种不同的方式来做到这一点：

.  <<Create a JAX-WS Service>>。
.  <<Create a WSDL First JAX-WS Service>>。
.  <<Create a Simple Front-End Web Service>>。

=== 创建一个JAX-WS服务

JAX-WS规范是一系列API和注释，可帮助您构建Web服务。要以这种方式构建和公开Web服务，您需要完成以下任务：

. 编写一个表示Web服务的Java类（使用`@WebService`注释）以公开其方法，以便可以远程调用它们。
. 配置将接受对Web服务的请求的端点（通常是HTTP入站端点）。
. 使用`<cxf:jaxws-service>`组件在Mule配置XML文件中配置服务。

有关更多信息，请阅读 link:/mule-user-guide/v/3.3/building-web-services-with-cxf[创建一个JAX-WS服务]文档。

=== 创建一个WSDL第一个JAX-WS服务

这是您首先定义WSDL然后编写Web服务的地方。要以这种方式构建Web服务并在Mule中配置它，您应该：

. 使用CXF中的 http://cxf.apache.org/docs/wsdl-to-java.html[WSDL到Java]工具或 http://cxf.apache.org/docs/maven-cxf-codegen-plugin-wsdl-to-java.html[Maven插件]从WSDL生成Web服务接口。
. 编写实现您的服务接口的服务实现类。
. 配置将接受对Web服务的请求的端点，通常是HTTP入站端点。
. 使用`<cxf:jaxws-service>`组件在Mule XML配置文件中配置服务。

有关更多信息，请阅读 link:/mule-user-guide/v/3.3/building-web-services-with-cxf[创建一个WSDL第一个JAX-WS服务]文档。

=== 创建一个简单的前端Web服务

如果您想从现有的POJO创建简单的Web服务，这是最好的方法。通过这种方式，您不需要使用注释，并且尽管不需要编写接口，但建议使用该接口，因为它会使Web服务易于使用。要以这种方式构建Web服务并在Mule中配置它，请执行以下操作：

. 使用现有的简单Java类（POJO）或编写一个新类。
. 配置将接受对Web服务的请求的端点（通常是HTTP入站端点）。
. 使用`<cxf:jaxws-service>`组件在Mule配置XML文件中配置服务。

有关更多信息，请阅读 link:/mule-user-guide/v/3.3/building-web-services-with-cxf[创建一个简单的前端Web服务]文档。

== 代理Web服务

使用Mule ESB作为Web服务代理是您在以下情况下可能需要使用的功能：

* 您需要为现有的第三方Web服务添加安全性（您没有代码或拥有基础架构）。
* 您需要添加或删除HTTP标头。
* 您需要验证或转换Web服务的输入或输出。
* 您可能需要转换SOAP信封。
* 您可能想要利用CXF Web服务标准支持来使用WS-Security，WS-Addressing或强制实施WS-Policy断言。
* 引入自定义错误处理。

还有很多其他场景可能需要考虑代理Web服务。

你有两种类型的代理：

*  link:/mule-user-guide/v/3.3/proxying-web-services-with-cxf[服务器端代理]
*  link:/mule-user-guide/v/3.3/proxying-web-services-with-cxf[客户端代理]

===  Web服务代理模式

对于简单用例，您可以考虑使用 link:/mule-user-guide/v/3.3/web-service-proxy-pattern[Web服务代理模式]，特别是在您不需要完成大量消息处理时。从Mule，您可以使用 link:/mule-user-guide/v/3.3/using-mule-configuration-patterns[使用Mule配置模式]配置（使用次要XML配置）特定的集成功能。

== 参考

有关更多信息和完整文档，请阅读以下内容：

*  link:/mule-user-guide/v/3.3/cxf-module-reference[CXF模块参考]
*  link:/mule-user-guide/v/3.3/supported-web-service-standards[支持的Web服务标准]
*  link:/mule-user-guide/v/3.3/web-service-proxy-pattern[Web服务代理模式]
* 示例
**  link:/mule-user-guide/v/3.3/echo-example[回声示例]
**  link:/mule-user-guide/v/3.3/bookstore-example[书店例子]
