= 关于配置构建器

此配置构建器负责根据您提供的配置文件创建运行时使用的配置。 Mule ESB提供了两个标准配置构建器，或者您可以创建自己的。

==  SpringXmlConfigurationBuilder

用于配置Mule的默认配置生成器是SpringXmlConfigurationBuilder。此配置构建器使用Spring基于一个或多个利用自定义Mule命名空间的XML文件来配置Mule。有关更多信息，请参阅 link:/mule-user-guide/v/3.2/about-the-xml-configuration-file[关于XML配置文件]。

==  ScriptConfigurationBuilder

此配置构建器允许JSR-223投诉脚本引擎（如Groovy或Jython）配置Mule。有关更多信息，请参阅 link:/mule-user-guide/v/3.2/scripting-module-reference[脚本模块参考]。

== 自定义配置生成器

通过实现具有方法`configure`的[ConfigurationBuilder]接口，您可以轻松创建自己的定制配置生成器。通常，您调用`configue(MuleContext muleContext.getRegistry())`来访问Mule的内部注册表，其中包含配置信息，并注册服务和其他元素。

在大多数情况下，您会希望从AbstractResourceConfigurationBuilder继承，这将使命令行中指定的任何配置文件在名为`configResources`的实例变量中可用。

== 指定配置生成器

AutoConfigurationBuilder是默认的配置生成器。如果您想使用其他配置构建器，则可以在应用程序的 link:/mule-user-guide/v/3.2/deployment-descriptor[部署描述符]中指定它。

当以编程方式启动Mule时，您还可以将配置生成器指定为MuleContextFactory的参数：

[source, code, linenums]
----
MuleContext context = new DefaultMuleContextFactory().createMuleContext(new ScriptConfigurationBuilder("mule-config.groovy"));
context.start();
----
