将业务逻辑添加到流中= 

在这个例子中，我们向您展示了如何使用组件将自定义逻辑插入到您的Mule流中。我们创建了一个Java Hello组件，它接收输入名称并打招呼，说明您的代码如何与流进行交互。 Mule中的 link:/mule-user-guide/v/3.2/configuring-components[零件]仅仅是一个POJO（Plain Old Java Object），它实现了它接收的数据的一些逻辑，并且通常返回数据传递给流中的下一个步骤。您可以使用Java或其他语言编写组件，例如Groovy，Ruby，Python，Scala，Closure或JavaScript。

== 您将学习什么

* 如何在Mule Studio中创建Java组件
* 如何在流程中配置组件
*  Mule知道调用组件时要调用什么方法

观看视频
视频:: 74cfWpz0fic [YouTube的]

看到这个例子在Mule Studio中构建和运行

10分钟

=== 先决条件

本示例向 link:/mule-user-guide/v/3.2/configuring-an-endpoint[配置端点]示例中创建的现有“核心概念”项目添加新流程。

=== 构建示例

首先，让我们创建我们的自定义Java组件。对于那些熟悉Eclipse的人来说，在Studio中创建Java类的过程相同。在_src / main / java_文件夹中创建一个包，并将其命名为_org.mule.examples.hello_。

2.现在通过右键单击刚创建的包创建一个新的Java类。

3.这将打开一个有很多选项的对话框，你需要做的就是给这个类命名_HelloComponent_。

4.该类已创建，因此我们将向其添加一个称为_sayHello_的单一方法。这个方法只有一个String参数。

我们准备好创造新的流程。右键单击项目树并选择New  - > Mule Message Flow。出现New Mule Flow对话框时，输入_hello_作为名称，然后单击完成。


6.现在将一个HTTP端点和一个组件从调色板拖到画布上。双击该组件以打开其属性对话框并将显示名称设置为_Hello_。

7.双击HTTP端点编辑其属性。将主机设置为_localhost_，并将端口设置为_8082_。这个连接器的端口是8082而不是前面的例子中的8081。这是因为我们将这个流程添加到了我们现有的项目中，并且在启动时会同时加载_echo_和_hello_流程;如果两个流都在相同的端口上侦听，则会发生端口冲突。

8.接下来，双击组件以编辑其属性。在_Display name_字段中，输入_Hello_。在_Class name_字段中，输入_org.mule.examples.hello.HelloComponent_。

9.在同一对话框中，单击组件属性对话框中的文档选项卡，并给组件一个描述。点击确定。


== 运行示例

10.要运行该示例，请右键单击项目树中的流程_hello.mflow_，选择Run As ..  - > Mule Application。随着应用程序启动，您将在控制台窗口中看到日志信息。

11.在浏览器窗口中转到`+http://localhost:8082/Fred+`。

由于我们从浏览器发出HTTP GET请求，因此URL的路径成为Mule内部的消息负载，因此HelloComponent接收"/Fred"。

== 摘要

* 您创建了Java组件（POJO）并将其插入到Flow中。
*  Java组件通过HTTP请求被调用。
* 组件不需要知道有关数据来自何处或发生在何处的任何信息。 Mule将端点和组件分开。

=== 关于方法调用

在Mule中，在组件上调用的方法称为_EntryPoint_。 Mule在端点接收数据时调用_EntryPoint_方法，使用_EntryPointResolvers_来确定要调用哪个EntryPoint方法。根据收到的数据类型和组件上的方法，解析器会有所不同。解析器可以基于注释，界面，预定义或动态数据。在这个例子中，Mule使用了一个动态的解析器，因为请求是一个单一的字符串，_sayHello_方法接受了一个字符串。 Mule将解析器与该方法的参数数据进行匹配。

== 参考

*  link:/mule-user-guide/v/3.2/configuring-components[Mule组件]
*  link:/mule-user-guide/v/3.2/configuring-java-components[配置Java组件]
*  link:/mule-user-guide/v/3.2/developing-components[EntryPoint解析器]

'''''
