= 兼容性

用户在许多不同的操作系统上运行Mule并结合各种消息传递平台和应用程序服务器。

== 平台与MuleSoft兼容

本节介绍与当前版本的Mule ESB兼容的平台软件。

如果您使用其他平台成功运行Mule，请发送邮件至：documentation@mulesoft.com [让我们知道]。

=== 操作系统兼容性

MuleSoft用来验证当前版本的操作系统包括：

* 以下Windows版本的32位和64位版本：XP，2003,2008和7
*  Mac OS 10.6
*  Linux RHEL的以下64位版本：5.3,6.1和7.1
*  Ubuntu Server 11.04（64位）
*  HP-UX 11i V3

另外，Mule社区的成员已经报告称Mule具有以下操作系统的成功部署：

*  Windows：2000和Vista
*  Linux：Debian和SUSE
* 的Solaris
*  AIX

=== 应用程序服务器兼容性

用户已经报告成功部署MuleSoft ESB：

* 的Tomcat
*  Tcat服务器
* 的JBoss
* 的WebSphere
* 的WebLogic
* 的Geronimo
* 码头。

=== 邮件平台兼容性

MuleSoft与任何供应商的JMS兼容。

此外，用户通过Active MQ，Open MQ，Rabbit MQ，Mule MQ，TIBCO EMS，TIBCO Rendezvous，Oracle AQ和IBM WebSphere MQ报告了成功的集成。

=== 爪哇

用户已经报告了Oracle（Sun），JRockit，IBM和OpenJDK的JVM的成功。

如下所述，您还必须安装JDK6。

== 设置你的骡子环境

在安装和运行Mule之前，您必须在您的系统上安装以下软件：

=== 爪哇

安装以下版本的 http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java开发工具包]之一：

* 标准版1.6.0_26（也称为JDK SE 6 Update 26）或更新版本
* 企业版1.6u3（JDK EE 6 Update 3）或更新版本

按照屏幕上显示的说明运行安装程序。

有关更多详情，请咨询： link:/mule-user-guide/v/3.2/installing-and-endorsing-the-jdk[安装和认证JDK]

===  Maven（可选但推荐）

. 从 http://maven.apache.org/[Maven网站]下载Maven发行版并将其解压缩到任何文件夹（例如，`C:\Apache`）。 MuleSoft ESB 3.2用户应该使用Maven 3。
. 创建一个Maven存储库目录，路径中没有空格，例如Windows上的`c:\.m2\repository`。 （如果Windows资源管理器不允许您创建.m2文件夹名称，请改为在控制台窗口中使用`mkdir`命令。）
. 打开Maven `conf`目录中的`settings.xml`文件（例如`c:\apache-maven-3.0.3\conf`）并指定存储库目录。例如：

[source, xml, linenums]
----
<localRepository>c:/.m2/repository</localRepository>
----

确保此条目未在此文件中注释掉。
