使用Acegi的= 组件授权

[CAUTION]
*Deprecated Module* +
Acegi模块已弃用。改为升级到Spring Security模块，这是一种直接替代方案。从Mule 3.2开始，Acegi模块从分配中移除。


本页介绍如何在组件上配置方法级授权，以便具有不同角色的用户只能调用某些服务方法。

== 保护服务组件

为了保护MethodInvocations，开发人员必须将正确配置的`MethodSecurityInterceptor`添加到应用程序上下文中。需要安全的bean被链接到拦截器中。这个链接使用Spring的`ProxyFactoryBean`或`BeanNameAutoProxyCreator`完成。另外，Acegi安全提供了一个`MethodDefinitionSourceAdvisor`，您可以使用它`DefaultAdvisorAutoProxyCreator`将安全拦截器自动链接到针对`MethodSecurityInterceptor`定义的任何bean前面。

除了`daoAuthenticationProvider`和`inMemoryDaoImpl` bean（请参阅 link:/mule-user-guide/v/3.2/configuring-security[配置安全性]），还必须配置以下bean：

*  `MethodSecurityInterceptor`
*  `AuthenticationManager`
*  `AccessDecisionManager`
*  `AutoProxyCreator`
*  `RoleVoter`

===  MethodSecurityInterceptor

`MethodSecurityInterceptor`配置为对以下内容的引用：

*  `AuthenticationManager`
*  `AccessDecisionManager`

以下是用于拦截对具有接口`myComponentIfc`的组件方法的调用的安全拦截器，该接口定义了两种方法：`delete`和`writeSomething`。角色在这些方法上设置，如下面的属性`objectDefinitionSource`所示。

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:acegi="http://www.mulesoft.org/schema/mule/acegi"
      xmlns:https="http://www.mulesoft.org/schema/mule/https"
      xmlns:http="http://www.mulesoft.org/schema/mule/http"
      xsi:schemaLocation="
          http://www.mulesoft.org/schema/mule/acegi http://www.mulesoft.org/schema/mule/acegi/3.1/mule-acegi.xsd
          http://www.mulesoft.org/schema/mule/https http://www.mulesoft.org/schema/mule/https/3.1/mule-https.xsd
          http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/3.1/mule-http.xsd
          http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.1/mule.xsd">
...
  <bean id="myComponentSecurity" class="org.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor">
    <property name="authenticationManager" ref="authenticationManager"/>
    <property name="accessDecisionManager" ref="accessDecisionManager"/>
    <property name="objectDefinitionSource">
          <value>
                com.foo.myComponentIfc.delete=ROLE_ADMIN
                com.foo.myComponentIfc.writeSomething=ROLE_ANONYMOUS
          </value>
    </property>
  </bean>
</mule>
----

===  AuthenticationManager

AuthenticationManager负责通过一系列`AuthenticationProvider`对象传递请求。

[source, xml, linenums]
----
<bean id="authenticationManager" class='org.acegisecurity.providers.ProviderManager'>
      <property name= "providers">
            <list>
                 <ref local="daoAuthenticationProvider"/>
            </list>
      </property>
</bean>
----

===  AccessDecisionManager

该bean指定如果用户具有`objectDefinitionSource`中指定的任何一个角色，则可以访问受保护的方法。

[source, xml, linenums]
----
<bean id="accessDecisionManager" class='org.acegisecurity.vote.AffirmativeBased'>
      <property name="decisionVoters">
            <list>
                  <ref bean="roleVoter"/>
            </list>
      </property>
</bean>
----

===  AutoProxyCreator

这个bean为受保护的bean定义了一个代理。当一个应用程序向Spring请求一个`myComponent` bean时，它会代替这个代理。

[source, xml, linenums]
----
<bean id="autoProxyCreator" class="org.springframework.aop.framework.autoproxy.BeanNameAutoProxyCreator">
    <property name="interceptorNames">
        <list>
            <value>myComponentSecurity</value>
        </list>
    </property>
    <property name="beanNames">
        <list>
            <value>myComponent</value>
        </list>
    </property>
    <property name='proxyTargetClass' value="true"/>
</bean>
----

使用`BeanNameAutoProxyCreator`为安全性创建所需的代理时，配置必须包含设置为`true`的属性`proxyTargetClass`。否则，传递给`MethodSecurityInterceptor.invoke`的方法是代理的调用者，而不是代理的目标。

===  RoleVoter

如果`ConfigAttribute`以`ROLE_`开头，则`RoleVoter`类将投票。 `RoleVoter`在比较以及`ROLE_`前缀时区分大小写。

* 如果`GrantedAuthority`返回字符串表示形式（通过`getAuthority()`方法），它将投票授予访问权限，该表达式完全等于一个或多个`ConfigAttributes`，以{ {4}}。
* 如果任何以`ROLE_`开头的`ConfigAttribute`都没有完全匹配，`RoleVoter`将投票拒绝访问。
* 如果`ConfigAttribute`没有以`ROLE_`开头，则投票者将弃权。

[source, xml, linenums]
----
<bean id="roleVoter" class="org.acegisecurity.vote.RoleVoter"/>
----

== 设置安全提供程序的安全属性

您可以在`securityProperties`地图中向安全提供商添加任何其他属性。例如，可以使用此映射将Acegi的默认安全策略更改为以下之一：

*  `MODE_THREADLOCAL`，它允许在当前线程上设置身份验证（这是Acegi使用的默认策略）
*  `MODE_INHERITABLETHREADLOCAL`，它允许从父线程继承身份验证
*  `MODE_GLOBAL`，它允许在所有线程上设置身份验证

=== 保护异步系统中的组件

使用Acegi的安全策略在使用异步系统时特别有用，因为我们必须在安全提供程序上添加一个属性，以便在多个线程上设置身份验证。

在这种情况下，我们将使用`MODE_GLOBAL`，如下例所示。

[source, xml, linenums]
----
<acegi:security-manager>
    <acegi:delegate-security-provider name="memory-dao" delegate-ref="daoAuthenticationProvider">
        <acegi:security-property name="securityMode" value="MODE_GLOBAL"/>
    </acegi:delegate-security-provider>
</acegi:security-manager>
----
