= 使用Mule Cloud Connect连接SaaS，社交媒体和电子商务

== 什么是Mule Cloud Connect？

Mule Cloud Connect是一款功能强大，轻量级的工具集，可与Mule ESB结合使用多种SaaS，社交媒体和电子商务服务。由于每个云连接器都是独立的，因此除了云连接器本身之外，您不需要安装任何其他设备。每个Mule Cloud Connector都包含一个Mule特定模式，它提供代码完成和内联文档。

过去，使用特定的 link:/mule-user-guide/v/3.2/transports-reference[运输]将Mule连接到这些服务始终是可能的。 Mule Cloud Connect在这些服务之上创建一个图层，以进一步简化这些服务的使用。

与Flow一起使用时，用户可以创建可跨多个服务的编排，并利用Mule提供的所有功能。这包括使用Mule路由，异常处理，异步执行能力的能力 - 仅举几例。

== 开始使用Mule Cloud Connect

要查找有关如何安装和使用每个云连接器的文档，请参阅 link:/mule-user-guide/v/3.2/studio-cloud-connectors[骡子工作室]。您还可以通过阅读 link:/mule-user-guide/v/3.2/integrating-with-cloud-connect[与Cloud Connect集成]了解云连接器有用的一些场景。

一旦安装Cloud Connect就像Mule中的其他功能一样使用。例如：

[cols="1*a"]
|===
^ | Salesforce Query
|
[source, xml]
----
<salesforce:query query="SELECT Id, Name FROM Account WHERE Name = 'Sandy'"/>
----
|===

这将使用SalesForce连接器以指定的查询调用SalesForce的查询API。这将从SalesForce返回一个可以轻松引用的查询结果。

== 何时使用Mule Cloud Connect

Cloud Connect为 link:/mule-user-guide/v/3.2/transports-reference[骡子运输]提供了另一种类型的连接器。传输通常代表通信协议，而Cloud Connect更适合将Mule连接到Mule已经支持的基础协议之上的应用程序API。

[TIP]
*Application API*  - 应用程序API允许您在特定应用程序内创建，查询或修改数据和服务。一些流行的例子包括Twitter，Facebook，LinkedIn，亚马逊网络服务，谷歌和SalesForce。今天，大多数应用程序API通常通过REST或SOAP Web服务公开。

== 可用的云连接器

可以使用https://www.anypoint.mulesoft.com/exchange/?type=connector [可用连接器]的分类列表，并且每个连接器的文档都提供了您需要知道的与Mule成功使用连接器的所有信息。这包括如何以及在何处下载连接器，如何获取服务密钥的详细信息以及如何在Mule流中包含和使用云服务操作的信息。

如果某个连接器不适用于您希望连接的云服务，请考虑使用我们易于遵循 link:/anypoint-connector-devkit/v/3.2/your-first-cloud-connector[如何构建云连接器]的指南创建您自己的连接器。本分步指南包含了一些示例和工具，可帮助您加快创建云连接器项目的速度。

