= 创建目录原型

link:/mule-user-guide/v/3.2/pattern-based-configuration[配置模式]是简化配置特定活动和重复活动的元素。 Mule带有一些涵盖通用场景的 link:/mule-user-guide/v/3.2/using-mule-configuration-patterns[准备好的模式]。

您可以创建自己的配置模式，甚至可以根据需要构建适合模式的目录。这些目录的好处很多。事实上，在准备使用的配置元素中封装一些专有技术可以提高开发团队的工作效率，减少错误风险并促进良好实践的应用。

== 实施概述

专用的Mule模块为您的模式提供最佳主机，因为它提供了所有必要的基础结构，以支持模式将基于的自定义XML配置元素。

配置模式实际上由核心类，构建器和两个与配置相关的类组成。这些全部都依赖于现有的抽象类来完成大部分行为。

在这些类的基础上，还需要特定的XML模式元素。这些模式元素允许模式在任何Mule配置文件中使用。

由于手工创建所有这些工件可能很乏味，所以最好的方法是使用我们创建的Maven原型来自动生成大部分模式。

[WARNING]
模式目录原型在Mule 3.0.1及以上版本中可用。

== 使用Maven

接下来的部分将介绍如何配置和使用Maven原型，以便它自动生成模式的大部分内容。

== 配置Maven

在开始之前，将以下内容添加到文件`settings.xml`（通常在您的Maven `conf`或`$HOME/.m2`目录中），以便Maven允许您执行Mule插件。

*settings.xml*

[source, xml, linenums]
----
<settings>
    <pluginGroups>
        <pluginGroup>org.mule.tools</pluginGroup>
    </pluginGroups>
    ...
</settings>
----

== 创建新的模式目录

[WARNING]
模式目录实际上是一个常规的Mule模块。如果您已有一个现有模块（最有可能是使用[模块原型]创建的），并且很高兴存储您的模式，则可以直接进入下一节。

首先，打开命令shell并切换到您想要创建模块的目录。

[source, code, linenums]
----
 > cd yourDir
----

接下来，您将执行原型并生成模块以便稍后托管目录。如果这是您第一次运行此命令，Maven将为您下载原型。

[source, code, linenums]
----
> mvn mule-module-archetype:create -DartifactId=xxx -DmuleVersion=3.1.0
----

至少，你传入这些系统参数：

*  `artifactId`：项目的简称（如'myApp'）。这必须是小写字母，不能有空格，句点，连字符等。
*  `muleVersion`：您要使用的Mule项目原型的版本。这也将是用于生成的工件的默认Mule版本。

[NOTE]
====
*Running the archetype*

Maven默认使用原型的最新版本。如果你想为早期版本的Mule创建一个模块，这可能会导致问题。在这种情况下，运行mule-module-archetype，指定插件的完整版本，如下所示：

[source, code, linenums]
----
mvn org.mule.tools:mule-catalog-archetype:3.1.0:create ...
----
====

[NOTE]
*artifactId* +
 +
artifactId可以包含下划线或连字符等字符。但是，插件会将名称转换为适用于Java的可用表单。例如，如果将参数指定为*-DartifactId=My#Awesome-Mule_Project*，则将在该名称的目录中创建项目，但项目名称为*MyAwesomeMuleProject*，包名称为*.myawesomemuleproject*

模块原型将 link:/mule-user-guide/v/3.2/creating-module-archetypes[问各种问题]，然后生成文件。您也可以通过在命令行中输入所有参数，在没有用户提示的情况下使用此插件。有关可以传入的参数的完整列表，请参阅命令行选项。

在回答所有问题后，原型会使用您指定的模块名称创建一个目录，其中包含用Maven构建的POM文件，该文件是一个Mule配置文件（`src\main\resources\mule-config.xml`），其中包含传输和模块的名称空间指定并使用您指定的程序包路径创建您的第一个服务的占位符元素和`src\main\java`下的`package.html`文件。最后，它会在`src\test`下创建一些模板文件，以帮助您开始为模块创建单元测试。将在项目的根目录中创建一个新的`MULE-README.txt`文件，以解释创建了哪些文件。

== 创建新模式

首先，打开命令shell并切换到模式目录的根目录。

[source, code, linenums]
----
> cd yourPatternCatalog
----

接下来，您将执行原型并生成配置模式。如果这是您第一次运行此命令，Maven将为您下载原型。

[source, code, linenums]
----
> mvn mule-catalog-archetype:new-pattern -DmuleVersion=3.1.0
----

至少，你传入这个系统参数：

*  `muleVersion`：您要使用的Mule项目原型的版本。这也将是用于生成的工件的默认Mule版本。


[NOTE]
====
*Running the archetype*

Maven默认使用原型的最新版本。如果你想为早期版本的Mule创建一个模块，这可能会导致问题。在这种情况下，运行mule-module-archetype，指定插件的完整版本，如下所示：

[source, code, linenums]
----
mvn org.mule.tools:mule-catalog-archetype:3.1.0:new-pattern ...
----
====

插件会询问各种问题，然后生成文件。

在回答所有问题后，原型将创建上述所有类。它还会创建一个以您的模式命名的TODO文件（如：my-pattern.todo），其中包含有关如何完成模式实现的信息。

== 问题解释

该插件会提示您回答有关您正在创建的模式的几个问题。

==== 您是否在创建新模块（而不是更新现有模块）？

如果您正在创建一个全新的Mule模块，请在此处选择“是”。然后向导会问你想创建什么资源。如果要更新现有模块，请选择否，并参阅更新现有模块以获取更多信息。以下问题会问你是否正在创建一个新模块。

==== 新模式应该使用哪个XML标签名称？

该名称将用于您的XML配置。用破折号（ - ）作为分隔符通常都是小写。

==== 新模式的完全限定类名是什么？

所有脚手架类和它们的包名都将从核心模式类的完全限定名称中推断出来。您不得以默认包为目标。

==== 这种模式的类型是什么？

这指定了您的模式在其配置中允许的灵活程度。

*  *mp*：该模式是一个纯粹的消息处理器，设计用于其他消息处理器旁边的流程中。它不支持像端点或路由器这样的入站消息源。
*  *ms*：模式接收来自任何类型消息源的消息，如端点或路由器。
*  *si*：该模式接收来自单个入站端点的消息。它可以选择配置入站变压器。 link:/mule-user-guide/v/3.2/simple-service-pattern[简单的服务]模式属于这种类型。
*  *siso*：模式接收来自单个入站端点的消息并分派到单个出站端点。 link:/mule-user-guide/v/3.2/bridge-pattern[桥]， link:/mule-user-guide/v/3.2/validator-pattern[验证器]和 link:/mule-user-guide/v/3.2/proxying-web-services[Web服务代理]模式属于这种类型。

== 示例控制台输出

[source, code, linenums]
----
********************************************************************************

What XML tag name should be used for the new pattern?

(Prefer lower-case and use dashes as separators, like: my-pattern)
                                                                 [default: null]
********************************************************************************
my-pattern

[INFO] patternFQCN:
********************************************************************************

What is the fully qualified class name of the new pattern?

(For example: com.acme.pattern.MyPattern
 Note that supporting classes will be created in: com.acme.pattern.builder and com.acme.pattern.config)
                                                                 [default: null]
********************************************************************************
com.acme.pattern.MyPattern

[INFO] patternType:
********************************************************************************

What will be the type of this pattern? [mp] or [ms] or [si] or [siso]

(Details of each type:
 mp:   the pattern is a pure message processor designed to be used within a flow alongside other message processors
 ms:   the pattern receives messages from any kind of message source, like endpoints or routers
 si:   the pattern receives messages from a single inbound endpoint
 siso: the pattern receives messages from a single inbound endpoint and dispatches to a single outbound endpoint)
                                                                   [default: mp]
********************************************************************************
siso
----
