= 创建示例原型

Mule提供了Maven原型，您可以将其用作Mule项目的代码模板。这些模板包含一组实施说明和"todo"指针，可帮助您快速入门。 Mule示例原型将帮助您在几秒钟内生成量身定制的样板项目。

按照以下说明为新的Mule示例创建模板文件，其中包括评论中所有必需的Java样板和详细的实施说明。

== 配置Maven

将以下内容添加到文件`settings.xml`（通常在您的Maven `conf`或`$HOME/.m2`目录中），以便Maven允许您执行Mule插件。

[%header,cols="1*a"]
|===
^ |的settings.xml
|
[source, xml, linenums]
----
<settings>
    <pluginGroups>
        <pluginGroup>org.mule.tools</pluginGroup>
    </pluginGroups>
    ...
</settings>
----
|===

== 使用原型

首先，打开命令shell并切换到您想要创建示例项目的目录。

[source, code, linenums]
----
 > cd yourDir
----

接下来，您将执行原型并生成代码。如果这是您第一次运行此命令，Maven将为您下载原型。

[source, code, linenums]
----
> mvn mule-example-archetype:create -DartifactId=xxx -DmuleVersion=2.2.0
----

至少，你传入两个系统参数：

*  `artifactId`：项目的简称（如'myExample'）。这必须是小写字母，不能有空格，句点，连字符等。
*  `muleVersion`：您要使用的Mule项目原型的版本。这也将是用于生成的工件的默认Mule版本。

[NOTE]
====
*Running the archetype*

Maven默认使用原型的最新版本。如果您想为较早版本的Mule创建示例，这可能会导致问题。在这种情况下，运行mule-example-archetype，指定插件的完整版本，如下所示：

[source]
----
mvn org.mule.tools:mule-example-archetype:2.1.2:create ...
----
====

[NOTE]
*artifactId* +
 +
从Mule 2.2开始，artifactId可以包含下划线或连字符等字符。但是，插件会将名称转换为适用于Java的可用表单。例如，如果将参数指定为**-DartifactId=My#Awesome-Mule_Project**，则将在该名称的目录中创建项目，但项目名称为*MyAwesomeMuleProject*，包名称为*.myawesomemuleproject*

插件会询问各种问题（如下所述），然后生成文件。您也可以通过在命令行中输入所有参数，在没有用户提示的情况下使用此插件。

在回答所有问题后，原型将使用您指定的示例项目名称创建一个目录，其中包含用Maven构建的POM文件，这是一个Mule配置文件（`conf\mule-config.xml`），其中包含传输和模块的名称空间您指定并使用您指定的包路径创建了第一个服务的占位符元素和`src\main\java`下的`package.html`文件。它还会在需要分发给用户的`dist`文件夹中创建文件，包括用于运行该示例的自述文件和批处理文件。最后，它会在`src\test`下创建一些模板文件，以帮助您开始为示例创建单元测试。将在项目的根目录中创建一个新的`MULE-README.txt`文件，以解释创建了哪些文件。

== 问题解释

该插件会提示您回答有关您正在创建的示例的几个问题。这些可能会根据您选择的选项而有所不同。输出示例如下所示。

==== 提供该示例所做的说明：

您应该提供关于该示例的准确描述，以及关于您可以或不可以使用它的任何高级详细信息。该文本将用于需要描述示例的地方。

==== 此示例针对哪个版本的Mule？

您希望用于您的示例的Mule版本。这将默认为通过命令行传入的原型版本。

==== 您希望在此项目中包含哪些Mule传输？

本例中计划使用的传输列表（如HTTP和VM）的逗号分隔列表。这会将这些传输的命名空间添加到配置文件中。

==== 你想在这个项目中包含哪些Mule模块？

您计划在本示例中使用的模块（如XML和脚本）的逗号分隔列表。这将这些模块的名称空间添加到配置文件中。

== 示例控制台输出

注意：在下面的示例中，MuleForge托管不再存在。在MuleForge提示符处输入*n*。

[source, code, linenums]
----
[INFO] description:
********************************************************************************

Provide a description of what the example does:

[default:]
********************************************************************************

[INFO] muleVersion:
********************************************************************************

Which version of Mule is this example targeted at?

[default: 2.2.0]
********************************************************************************

[INFO] forgeProject:
********************************************************************************

Will This project be hosted on MuleForge? [y] or [n]

[default: y]
********************************************************************************

[INFO] transports:
********************************************************************************

Which Mule transports do you want to include in this project?
(options: axis,cxf,ejb,file,ftp,http,https,imap,imaps,jbpm,jdbc,
          jetty,jms,multicast,pop3,pop3s,quartz,rmi,servlet,smtp,
          smtps,servlet,ssl,tls,stdio,tcp,udp,vm,xmpp):

[default: cxf,file,http,jdbc,jms,stdio,vm]

********************************************************************************

[INFO] modules:
********************************************************************************

Which Mule modules do you want to include in this project?

(options: bulders,client,jaas,jbossts,management,ognl,pgp,scripting,
          spring-extras,sxc,xml):

[default: client,management,scripting,sxc,xml]

********************************************************************************
----


== 命令行选项

默认情况下，此插件以交互模式运行，但可以使用以下选项以“无声”模式运行它：

[source, code, linenums]
----
-DinteractiveMode=false
----

以下选项可以传入：

[%header,cols="20a,40a,40a"]
|===
|姓名 |示例 |默认值
|的groupId  |  - 。DgroupId = org.mule.examplexxx  | org.mule.example <artifactId>
| {forgeProject {1}}  -  DforgeProject = N  |ÿ
| {packagepath的{1}}  -  DpackagePath =组织/骡/示例 |无
| {运输{1}}  -  Dtransports = HTTP，VM  | CXF，文件，HTTP，JDBC，JMS标准输入输出，VM
| {muleVersion {1}}  -  DmuleVersion2.2.0  |无
| {的packageName {1}}  -  DpackageName = MYPKG  |无
|描述 |  -  Ddescription = "some text"  |无
| {模块{1}}  -  Dmodules = XML，脚本 |客户，管理，脚本，SXC，XML
|的basedir  |  -  Dbasedir = /项目/骡/工具 | <current dir>
| {包{1}}  -  Dpackage =组织/骡/示例/ MYPKG  |无
|的artifactId  |  -  DartifactId = myMuleExample  |骡应用 -  <artifactId>
|版本 |  -  Dversion = 2.2-SNAPSHOT  | <muleVersion>
|===
