= 部署方案

有几种方法可以部署Mule ESB。本页介绍了各种方法。

[%header,cols="10,10,50,10,10,10"]
|===
|部署模式 |容器 |专业人员 |缺点 | HA  | MMC
|独立 | Mule ESB  | Mule部署模型，运行多个应用程序，热部署，最小资源需求，易于安装 |必须将Mule配置到您的环境中{ 4}} Mule HA支持 |支持
嵌入式WAR  |应用服务器 |运行多个应用程序，webapp中包含的所有依赖项，使用Web应用程序部署模型 |每个Web应用程序运行自己的mule实例，增加webapp的大小 |使用App Server HA  |支持*
|嵌入式Java  | Java App / IDE  |不需要外部容器 |不支持热部署 |支持{{5}
|===

*当Mule嵌入其他容器时，管理控制台无法执行自动发现或服务器重新启动。

== 在独立模式下运行Mule

推荐的方法是从命令提示符下单独运行Mule ESB，作为服务或守护程序或从脚本运行。这是最简单的体系结构，因此可以减少发生错误的点数。它通常最适合于性能，因为它减少了层数并消除了应用程序服务器对整体解决方案固有的性能影响。借助Mule 3，您现在还可以在Mule实例中并排运行多个应用程序，并使用新的部署模型可以支持实时部署和热重新部署应用程序。最后，独立模式完全支持 link:/mule-user-guide/v/3.2/mule-high-availability[骡子高可用性]模块和 link:/mule-management-console/v/3.2[骡子管理控制台]。

有关运行Mule独立版的更多信息，请参阅 link:/mule-user-guide/v/3.2/mule-deployment-model[Mule部署模型]。

== 将Mule嵌入到Java应用程序或Web应用程序中

您可以从Java应用程序启动或停止Mule，或将其嵌入到Webapp（例如JSP或Servlet）中。有关详情，请参阅 link:/mule-user-guide/v/3.2/embedding-mule-in-a-java-application-or-webapp[将Mule嵌入到Java应用程序或Web应用程序中]。以下是关于特定应用程序服务器

*  Geronimo： http://geronimo.apache.org[Geronimo的]应用程序服务器使用ActiveMQ作为其默认JMS提供程序。有关详情，请参阅 link:/mule-user-guide/v/3.2/activemq-integration[ActiveMQ集成]。
*  link:/mule-user-guide/v/3.2/deploying-mule-to-jboss[JBoss的]
*  link:/mule-user-guide/v/3.2/deploying-mule-to-weblogic[的WebLogic]
*  link:/mule-user-guide/v/3.2/deploying-mule-to-websphere[的WebSphere]
*  link:/mule-user-guide/v/3.2/deploying-mule-as-a-service-to-tomcat[Tomcat的]

有关如何在某些应用程序服务器中支持Mule热部署的详细信息，请参阅 link:/mule-user-guide/v/3.2/application-server-based-hot-deployment[基于应用服务器的热部署]。

请注意，当您嵌入Mule时，不支持Mule部署模型和Mule HA高可用性。此外，因为应用程序服务器需要控制Mule，所以Mule管理控制台的控制/管理功能会减少。监控功能正常工作，但不支持服务器重启。

== 使用Spring

Mule与Spring完全集成，允许您利用Spring的许多功能，包括对JNDI和EJB会话bean的支持。您还可以使用Spring远程访问从外部应用程序访问Mule。有关详情，请参阅 link:/mule-user-guide/v/3.2/using-mule-with-spring[春天使用骡子]。
