= 将Mule作为服务部署到Tomcat

本页介绍如何在Apache Tomcat中将Mule作为服务安装，并设置Mule应用程序进行热部署。有关热部署Mule应用程序的更多信息，请参阅 link:/mule-user-guide/v/3.2/application-server-based-hot-deployment[基于应用服务器的热部署]。

== 在Tomcat中安装Mule

要在Tomcat中安装Mule，以便可以热部署您的Mule应用程序，请执行以下步骤：

.  http://tomcat.apache.org/download-60.cgi[下载]并按照标准安装说明从Apache网站安装Apache Tomcat 6。
. 在Tomcat主目录中，将以下行添加到`conf/server.xml`文件：+
`<Listener className="org.mule.module.tomcat.MuleTomcatListener" />`
. 将其所有子目录*except* `/boot`的Mule `lib`文件夹的内容复制到Tomcat主目录下的`mule-libs/`目录（如有必要，创建一个目录） 。你不需要压扁目录。
. 将`mule-module-tomcat-<version>.jar`文件复制到Tomcat主目录下的`mule-libs/mule/`目录（如果它尚未存在）。
. 将以下库从您的Mule `lib/boot/`目录复制到您的Tomcat `mule-libs/opt/`目录中：
*  `jcl104-over-slf4j-1.5.0.jar`
*  `log4j-1.2.14.jar`
*  `slf4j-api-1.5.0.jar`
*  `slf4j-log4j12-1.5.0.jar`
. 在Tomcat `conf/catalina.properties`文件中，将以下内容添加到`common.loader`（以逗号将其与现有值分开）：+
`${catalina.home}/mule-libs/user/*.jar,${catalina.home}/mule-libs/mule/*.jar,${catalina.home}/mule-libs/opt/*.jar`

== 复制Mule应用程序文件

将配置文件和自定义Java类打包到WAR文件（请参阅 link:/mule-user-guide/v/3.2/application-server-based-hot-deployment[基于应用服务器的热部署]）后，将您的Mule应用程序WAR文件复制到Tomcat `/webapps`目录。

== 热部署Mule应用程序

在将Mule应用程序的WAR文件复制到Tomcat `/webapps`目录后，Tomcat将对其进行部署。如果您需要更改Web应用程序中的配置文件或Java文件，只需修改Tomcat `/webapps`目录下展开目录中的文件，然后触摸`web.xml`文件（或者您可以简单地添加和删​​除文件中的空间，然后保存它）以触发Tomcat重新部署应用程序。或者，您可以修改源文件，将它们重新打包为WAR，然后将新WAR放入`/webapps`目录以触发Tomcat重新部署应用程序。
