= 将Mule部署到WebSphere

本页描述如何将Mule ESB部署到WebSphere Application Server 6.1。

== 将您的Mule应用程序准备为Web应用程序

在将Mule应用程序部署到WebSphere之前，您必须将其准备为Web应用程序。这涉及到为您的Mule应用程序创建一个`web.xml`文件，然后创建所有支持文件的WAR文件。

=== 创建web.xml文件

`web.xml`文件通过指定Mule配置文件和用于在WebSphere容器中启动Mule的其他选项来将Mule应用程序配置为Web应用程序。它应该是这样的：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app id="WebApp_ID" version"2.4">
  <!--Mule configuration (Mule format)-->
  <context-param>
    <param-name>org.mule.config</param-name>
    <param-value>mule-config.xml</param-value>
  </context-param>
  <listener>
    <listener-class>org.mule.config.builders.MuleXmlBuilderContextListener</listener-class>
  </listener>
  <servlet>
    <servlet-name>muleServlet</servlet-name>
    <servlet-class>org.mule.transport.servlet.MuleReceiverServlet</servlet-class>
    <load-on-startup>100</load-on-startup>
  </servlet>
  <!--Mule configuration ends-->
</web-app>
----

=== 创建WAR文件

WAR文件必须包含`web.xml`文件以及Mule应用程序的配置文件，库和属性文件。要创建WAR文件，可以在Mule应用程序的根目录中使用JAR命令：

[source, code, linenums]
----
jar -cvf muleApp.war
----

运行该命令的目录结构应如下所示：

[source, code, linenums]
----
META-INF
  maven
WEB-INF
  classes
    mule-config.xml
    log4J.properties
  lib
    mule jars
  web.xml
----

== 在WebSphere中创建和运行Mule配置文件

在部署Mule应用程序之前，您必须在WebSphere中为Mule创建配置文件。以下是在Windows中使用Profile Management Tool的说明，但UNIX服务器的步骤相似。

. 从Windows开始菜单中，从WebSphere程序组（例如*Start > IBM WebSphere > Application Server v6.1 > Profile Management Tool*）启动Profile Management Tool。
. 配置文件管理向导启动后，点击*Next*。
. 选择*Application server*并点击*Next*。
. 选择*Advanced profile creation*并点击*Next*。
. 选择*Deploy the application console*，清除所有其他复选框，然后点击*Next*。
. 指定配置文件名称，如"MuleProfile"，并指定要保存配置文件的目录。我们建议您指定一个与配置文件同名的目录。保持其他选项未被选中，然后点击*Next*。
. 如果要为此配置文件启用安全性，请输入用户名和密码。否则，清除复选框。点击*Next*。
. 保留所有默认端口值（或更改您的环境中的任何必需项），然后点击*Next*。
. 清除该复选框以将配置文件作为Windows服务运行（在UNIX上，清除作为守护程序运行的选项），然后单击*Next*。
. 不选中Web服务器定义选项，然后点击*Next*。
. 点击*Create*。该配置文件是从WebSphere Start菜单创建并可用的。
. 运行配置文件。例如，选择*Start > IBM WebSphere > Application Server v6.1 > Profiles > MuleProfile > Start the server*。

== 部署Mule应用程序

您现在已准备好部署您的Mule应用程序。

. 运行Mule配置文件后，打开WebSphere管理控制台。
. 在左侧的导航栏上，点击*Applications*，然后点击*Install New Application*。
. 对于路径，浏览到上面创建的Mule WAR文件的位置。
. 对于上下文根，键入一个唯一的根，例如"Mule"。
. 在每个屏幕上点击*Next*，然后点击*Finish*。保存您的设置。
. 转到企业应用程序，选择`muleApp.war`，然后点击*Start*。

您的Mule应用程序作为WebSphere中的嵌入式Web应用程序启动。要验证它是否正确部署，请检查`MuleProfile/logs/server1/SystemOut.log`文件。
