=  Drools模块参考

== 介绍

=== 业务规则

在许多应用程序中，业务逻辑的变化比其他应用程序代码更频繁。规则引擎执行已从应用程序的其余部分外化的业务规则。业务逻辑的这种外化使得应用程序更适合于改变，甚至可以允许非技术人员在没有开发人员干预的情况下更新业务逻辑。

规则引擎引入了很多术语，这些术语可能会让不熟悉业务规则"world"的用户感到困惑：

*Facts*存储在*working memory*中（类似于内存数据库）。 A *fact*是一段数据，例如"age = 40"，或者在面向对象的规则引擎中，它可能是一个具有属性的Java对象。

*Rules*在*knowledge base*中定义。 *rule*由条件（通常取决于工作内存中的事实）和条件为真时执行的动作组成（类似于"if-then"语句）。规则执行的行为可能会改变工作记忆中的事实，从而导致其他规则触发。

=== 复杂事件处理

复杂事件处理（CEP）是指通过业务规则分析多个事件的流或云以检测这些事件内的复杂模式或关系的应用程序，通常是实时的。

=== 注意事项

如果您的Mule应用程序的业务逻辑相对简单，那么您最好使用Mule的编排功能（如 link:/mule-user-guide/v/3.2/message-sources-and-message-processors[流量，路由器和自定义组件]）来实现它。

但是，在下列情况下，您可能会考虑使用规则来为您的业务逻辑建模：

* 在程序定义时，业务逻辑过于复杂或过于耗时
* 业务逻辑包含很多if-then-else语句
* 业务逻辑经常更改
* 业务逻辑需要由不能（或不应该）访问应用程序本身（重新编译/重新部署它）的人维护，

您也可以考虑将业务逻辑建模为 link:/mule-user-guide/v/3.2/bpm-module-reference[处理]，具体取决于涉及的算法的性质。

===  Drools的

http://www.jboss.org/drools[Drools的]是一个开源 http://www.jboss.org/drools/drools-expert.html[规则引擎]，它也提供 http://www.jboss.org/drools/drools-fusion.html[复杂的事件处理]。

该模块提供了Mule与Java规则引擎（即Drools）之间的集成。

== 命名空间和语法

XML名称空间：

[source, xml, linenums]
----
xmlns:bpm "http://www.mulesoft.org/schema/mule/bpm"
----

XML架构位置：

[source, code, linenums]
----
http://www.mulesoft.org/schema/mule/bpm/3.2/mule-bpm.xsd
----

句法：

[source, xml, linenums]
----
<bpm:drools />

<bpm:rules rulesDefinition="myRules.drl" />
----

== 特点

* 传入的Mule信息在Drools的工作记忆中被认为是新的事实。
* 规则触发可以生成Mule消息。
* 在CEP模式下，Mule消息可以作为事件流接收，并用于触发复杂的操作，如时间推理和模式检测。

要查看带有Mule的Drools，请查看 link:/mule-user-guide/v/3.2/cep-example[CEP示例]（在完整的Mule发行版中可用）。

[NOTE]
Drools库与Mule发行版捆绑在一起。截至Mule 3.2，Drools 5.0是最新的支持版本。

== 用法

按如下所示为一般BPM模块导入XML模式：

[%header,cols="1*a"]
|===
^ |导入架构
|
[source, xml, linenums]
----
xmlns:bpm="http://www.mulesoft.org/schema/mule/bpm"
xsi:schemaLocation="http://www.mulesoft.org/schema/mule/bpm  http://www.mulesoft.org/schema/mule/bpm/3.2/mule-bpm.xsd"
----
|===

[NOTE]
由于它们密切相关，因此BPM命名空间/模式在Drools模块和 link:/mule-user-guide/v/3.2/bpm-module-reference[BPM模块]之间共享。

将Drools声明为与Mule一起使用的规则引擎：

[%header,cols="1*a"]
|===
^ |声明Drools作为规则引擎
|
[source, xml, linenums]
----
<bpm:drools />
----
|===

[NOTE]
就像 link:/mule-user-guide/v/3.2/bpm-module-reference[BPM]一样，Mule中的规则集成基于可插入的接口，因此可以使用任何实现此接口的Java规则引擎来代替Drools。然而，目前唯一可用的这种实现是Drools。

将规则添加到您的Mule应用程序中，通常（但不一定）在入站端点之前：

[%header,cols="1*a"]
|===
^ |规则元素
|
[source, xml, linenums]
----
<bpm:rules rulesDefinition="myRules.drl" />
----
|===

创建一个规则定义文件并（可选）从它生成Mule消息：

[%header,cols="1*a"]
|===
^ |规则定义文件
|
[source, code, linenums]
----
global org.mule.module.bpm.MessageService mule;

...cut...

rule "sudden drop"
when
    $st : StockTick( $dt : delta >= $threshold )
then
    mule.generateMessage("alerts", "Some alert message", null, MessageExchangePattern.ONE_WAY);
end
----
|===

=== 配置示例

[%header,cols="1*a"]
|===
^ |基本配置
|
[source, xml, linenums]
----
<mule ... xmlns:bpm="http://www.mulesoft.org/schema/mule/bpm"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/bpm
    http://www.mulesoft.org/schema/mule/bpm/3.2/mule-bpm.xsd" ...>

    <bpm:drools />

    <flow name="RulesInput">
        <jms:inbound-endpoint queue="input.queue" /> ❶
        <bpm:rules rulesDefinition="myRules.drl" /> ❷
    </flow>
</mule>
----
|===

这是一个简单的配置，队列（❶）上的传入JMS消息作为事实插入Drools工作内存（❷）。

[%header,cols="1*a"]
|===
^ | CEP配置
|
[source, xml, linenums]
----
<mule ... xmlns:bpm="http://www.mulesoft.org/schema/mule/bpm"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/bpm
    http://www.mulesoft.org/schema/mule/bpm/3.2/mule-bpm.xsd" ...>

    <spring:bean name="companies" class="org.mule.example.cep.CompanyRegistry" factory-method="getCompanies" /> ❷

    <bpm:drools />

    <flow name="processStockTicks">
        <inbound-endpoint ref="stockTick" />
        <bpm:rules rulesDefinition="broker.drl"
         cepMode="true" ❸ entryPoint="StockTick stream" ❹
         initialFacts-ref="companies" ❶ />
    </flow>
</mule>
----
|===

这里启动时会将一组初始事实（❶）插入工作内存中。 Collection由Spring bean的工厂方法提供（❷）。 Drools设置为CEP模式（❸），这意味着消息将作为事件流插入而不是事实。事件流的入口点也被指定（❹）。

== 参考

=== 配置参考

== 规则

由Drools等规则引擎支持的服务。

<rules...>的{​​{0}}属性

[%header,cols="10,10,10,10,60",width=90%]
|===
| {名称{1}}输入 |必 |缺省 |说明
| rulesEngine-ref  |字符串 |否 |   |对基础规则引擎的引用。
| rulesDefinition  |字符串 |是 |   |包含规则定义的资源。这将用于将规则集部署到规则引擎。
| initialFacts-ref  |字符串 |否 |   |引用启动时要声明的一组初始事实。
| cepMode  |布尔 |否 |   |我们是否使用CEP（复杂事件处理）的知识库？ （默认= false）
| entryPoint  |字符串 |否 |   |事件流的入口点（由CEP使用）。
|===

<rules...>的{​​{0}}子元素

[%header,cols="15,15,70",width=10%]
|===
| {名称{1}}基数 |说明
|===

===  XML架构

完成 http://www.mulesoft.org/docs/site/current3/schemadocs/namespaces/http_www_mulesoft_org_schema_mule_bpm/namespace-overview.html[模式参考文档]。

=== 的Maven

如果您使用Maven构建应用程序，请使用以下groupId / artifactIds来包含必要的模块：

[source, xml, linenums]
----
<dependency>
  <groupId>org.mule.modules</groupId>
  <artifactId>mule-module-bpm</artifactId>
</dependency>
<dependency>
  <groupId>org.mule.modules</groupId>
  <artifactId>mule-module-drools</artifactId>
</dependency>
----
