= 端点 - 将所有内容连接在一起

_Endpoints_是配置元素，它们是将所有服务连接在一起的关键。您可以在流程中指定端点以告诉Mule ESB要使用哪个传输，发送消息的位置以及组件应该接收哪些消息。端点的主要部分是指示要使用的传输的地址，位置（特定于传输的资源）以及任何其他参数。

[WARNING]
地址可以表示为统一资源标识符（ http://en.wikipedia.org/wiki/Uniform_Resource_Identifier[URI]）或特定于模式的XML配置

例如，如果流入站端点的地址是http://myfirm.com/mule，则HTTP传输将调度已发送到该URL的任何消息。如果入站端点指定file：// myserver / files /，则正在监视该目录的File transport会将在该目录中创建的所有新文件分派给流。

根据您指定的消息传递风格，Mule可能会或可能不会生成响应，以通过入站端点发送回发件人。 Mule支持多种[消息交换模式]，每个传输都有一个默认模式，除非您另有指定，否则它将遵循默认模式。作为结果，Mule通常会返回消息处理的最终结果;但是也可以指定响应处理来控制返回的内容。

出站端点也可以被指定以指示消息将接下来的位置。例如，在处理HTTP请求之后，您可能希望将结果放在JMS队列中。

流可以使用许多不同的传输接收消息。对于流将使用的每种传输类型，您必须指定一个或多个单独的端点。例如，如果您希望其中一个流处理在HTTP和JMS通道中传入的消息，则至少应指定一个入站HTTP端点和至少一个入站JMS端点。 Mule将这些端点注册到流中，并且传输在运行时使用此注册表信息来配置它自己并确定发送和接收消息的位置。

Mule还支持动态端点，允许从消息内容构建目的地。这允许路由滑动模式，其中消息指示Mule在哪里路由它。

该流程还可以包括进一步指定要发送或接收哪些消息的过滤器。例如，您可以指定该组件仅接收特定作者的RSS消息。为您的服务指定过滤器，路由器和端点只需要编辑XML配置。您不必编写任何Java代码。某些路由器也是动态的，可以根据消息内容或外部数据源（如文件或数据库）更改行为。如前所述，您的组件代码与通过Mule配置处理的消息传递和路由完全分离。

总之，Mule提供了一种简单轻便的方法来编写对数据执行某些操作的组件，而无需担心数据的发送者或接收者，数据的格式或用于发送/接收数据的技术。尽管许多代理和集成技术提供了连接到不同数据源的能力，但他们通常需要额外的编码才能使消息按照您想要的方式行事，并将数据传递到您想要的地方。 Mule允许您快速开发服务组件，然后通过简单的XML配置而不是编写Java代码来改变它们的行为方式。
