=  IMAP传输参考

== 介绍

IMAP传输可用于使用`javax.mail` API从IMAP收件箱接收邮件。 IMAPS传输使用SSL / TLS进行安全连接。

使用IMAP传输提供了一种与IMAP服务器交互的简单方法，无需编写自己的IMAP客户端。它允许您以指定的频率登录到IMAP服务器，从服务器提取消息，根据电子邮件主题选择过滤它们，并将它们转换为可在应用程序中使用的标准Java对象。

TLS / SSL连接代表实体进行，实体可以是匿名的或由证书标识。密钥库提供识别建立连接的实体所需的证书和相关私钥。此外，连接到可信系统。受信任系统的公共证书存储在信任库中，该信任库用于验证与远程系统建立的连接是否与期望的身份匹配。

== 命名空间和语法

XML名称空间：

[source, xml, linenums]
----
xmlns:imap "http://www.mulesoft.org/schema/mule/imap"xmlns:imaps "http://www.mulesoft.org/schema/mule/imaps"
----

XML模式位置：

[source, code, linenums]
----
http://www.mulesoft.org/schema/mule/imap http://www.mulesoft.org/schema/mule/imap/3.2/mule-imap.xsdhttp://www.mulesoft.org/schema/mule/imaps http://www.mulesoft.org/schema/mule/imaps/3.2/mule-imaps.xsd
----

连接器语法：

[source, xml, linenums]
----
<imap:connector name="imapConnector" backupEnabled="true" backupFolder="backup" checkFrequency="90000"                 deleteReadMessages="false" mailboxFolder="INBOX" moveToFolder="PROCESSED"/><imaps:connector name="imapsConnector" backupEnabled="true" backupFolder="backup" checkFrequency="90000"                  deleteReadMessages="false" mailboxFolder="INBOX" moveToFolder="PROCESSED"/>  <imaps:tls-client path="clientKeystore" storePassword="mulepassword" />   <imaps:tls-trust-store path="greenmail-truststore" storePassword="password" /> </imaps:connector>
----

端点语法：
你可以用两种不同的方式定义你的端点：

. 前缀端点：

[source, xml, linenums]
----
<imap:inbound-endpoint user="bob" password="password" host="localhost" port="65433"/> <imaps:inbound-endpoint user="bob" password="password" host="localhost" port="65433"/>
----

. 没有前缀的URI：

[source, xml, linenums]
----
<inbound-endpoint address="imap://bob:password@localhost:65433"/><inbound-endpoint address="imaps://bob:password@localhost:65433"/>
----

有关更多信息，请参阅下面的部分。

== 特点

* 简单配置入站端点的电子邮件访问：包括验证信息和检查频率
* 自动处理电子邮件附件
* 将邮件自动备份到指定的文件夹
* 自动删除已读消息
* 轻松配置安全性

== 用法

如果您想在您的配置中包含IMAP电子邮件传输，那么这些是您需要定义的命名空间：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?><mule xmlns="http://www.mulesoft.org/schema/mule/core"       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"       xmlns:spring="http://www.springframework.org/schema/beans"       xmlns:imap="http://www.mulesoft.org/schema/mule/imap"       xsi:schemaLocation="       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.2/mule.xsd       http://www.mulesoft.org/schema/mule/imap http://www.mulesoft.org/schema/mule/imap/3.2/mule-imap.xsd">...
----

对于安全版本，您可以使用以下内容：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?><mule xmlns="http://www.mulesoft.org/schema/mule/core"       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"       xmlns:spring="http://www.springframework.org/schema/beans"       xmlns:imaps="http://www.mulesoft.org/schema/mule/imaps"       xsi:schemaLocation="       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.2/mule.xsd       http://www.mulesoft.org/schema/mule/imaps http://www.mulesoft.org/schema/mule/imaps/3.2/mule-imaps.xsd">...
----

然后您需要按照以下所述配置连接器和端点。

=== 配置示例

假设你有一个企业，并想通过电子邮件附件接受订单。收到电子邮件后，您需要保存订单附件，以便在您的订单履行流程中收到附件。以下Mule配置会检查电子邮件的电子邮件框，并将附件保存到本地磁盘，以便从单独的执行过程中获取它们：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?><mule xmlns="{{0}}.dat"> ❹                        <expression-transformer>                            <return-argument expression="payload.inputStream" evaluator="groovy" /> ❺                        </expression-transformer>                    </file:outbound-endpoint>                                    </list-message-splitter-router>                            </outbound>        </service>    </model></mule>
----

内置变压器被声明为❶并获取电子邮件附件列表。然后将这个转换器应用到定义的pop3入站端点。然后我们定义一个列表列表 - 消息分离器 - 路由器❸，它遍历所有的电子邮件附件。接下来，我们定义一个文件出站端点，它将附件写入'./received'目录，并将日期戳记作为文件名❹。一个简单的groovy表达式获取附件的inputStream来写入文件。

这是一个基于流的版本：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?><mule xmlns="{{0}}.dat"> ❹                <expression-transformer>                    <return-argument expression="payload.inputStream" evaluator="groovy" /> ❺                </expression-transformer>            </file:outbound-endpoint>                            </flow></mule>
----

以下是相同配置的安全版本：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?><mule xmlns="{{0}}.dat"> ❺                        <expression-transformer>                            <return-argument expression="payload.inputStream" evaluator="groovy" /> ❻                        </expression-transformer>                    </file:outbound-endpoint>                                    </list-message-splitter-router>                            </outbound>        </service>    </model></mule>
----

IMAPS连接器具有客户端和服务器密钥库信息❶。内置变压器被声明为❷并获取电子邮件附件列表。然后将该变压器应用于入站端点❸。然后我们定义一个列表列表 - 消息分离器 - 路由器❹，它遍历所有的电子邮件附件。接下来，我们定义一个文件出站端点，它将附件写入'./received'目录，并将日期戳记作为文件名❺。一个简单的groovy表达式获取附件的inputStream来写入文件。

== 配置参考

=== 连接器

IMAP连接器支持所有 link:/mule-user-guide/v/3.2/configuring-a-transport[常见的连接器属性和属性]和以下附加属性：

[%header,cols="10,70,10,10"]
|===
| {属性{1}}说明 |缺省 |必
| backupEnabled  |是否将副本保存到备份文件夹 | False  |否
| backupFolder  |消息在读取后移动的文件夹。 |   |否
| checkFrequency  |到服务器的轮询连接之间的周期（ms）。 | 60000  |是
| mailboxFolder  |用于检查电子邮件的远程文件夹。 | INBOX  |否
| deleteReadMessages  |是否在服务器下载完成后从服务器中删除消息。如果设置为false，则将消息设置为defaultProcessMessageAction属性值。 | true  |否
| moveToFolder  |远程文件夹将邮件移动到已读取的位置。建议在使用此选项时将'deleteReadMessages'设置为false。
 当使用诸如GMail之类的公共电子邮件服务时，这非常有用，因为标记邮件的删除操作不起作用。请改为@ moveToFolder = Gmail / Trash。 |   |否
| defaultProcessMessageAction  |如果deleteReadMessages属性设置为false，则执行该操作。有效值包括：答案，删除，草稿，标记，最近，看到，用户和无 | SEEN  |否
|===

对于安全版本，还需要以下元素：

[%header,cols="2*"]
|===
|元素 |说明
| tls-client a |
使用以下属性配置客户端密钥存储区：

* 路径：包含用于标识的公钥和私钥的密钥库的位置（如果可能，则解析相对于当前类路径和文件系统的位置）
*  storePassword：用于保护密钥库的密码
* 类：使用的密钥库类型（Java类名称）

| tls-trust-store a |
配置信任库。属性是：

* 路径：包含可信服务器的公用证书的信任存储的位置（如果可能，将解析相对于当前类路径和文件系统的位置）
*  storePassword：用于保护信任存储的密码

|===

例如：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?><mule xmlns="http://www.mulesoft.org/schema/mule/core"       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"       xmlns:spring="http://www.springframework.org/schema/beans"       xmlns:imap="http://www.mulesoft.org/schema/mule/imap"       xsi:schemaLocation="       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.2/mule.xsd       http://www.mulesoft.org/schema/mule/imap http://www.mulesoft.org/schema/mule/imap/3.2/mule-imap.xsd">    <imap:connector name="imapConnector" backupEnabled="true" backupFolder="backup" checkFrequency="90000"                     deleteReadMessages="false" mailboxFolder="INBOX" moveToFolder="PROCESSED"/>...
----

安全版本：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?><mule xmlns="http://www.mulesoft.org/schema/mule/core"       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"       xmlns:spring="http://www.springframework.org/schema/beans"       xmlns:imaps="http://www.mulesoft.org/schema/mule/imaps"       xsi:schemaLocation="       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.2/mule.xsd       http://www.mulesoft.org/schema/mule/imaps http://www.mulesoft.org/schema/mule/imaps/3.2/mule-imaps.xsd">    <imaps:connector name="imapsConnector" backupEnabled="true" backupFolder="backup" checkFrequency="90000"                      deleteReadMessages="false" mailboxFolder="INBOX" moveToFolder="PROCESSED"/>      <imaps:tls-client path="clientKeystore" storePassword="mulepassword" />       <imaps:tls-trust-store path="greenmail-truststore" storePassword="password" />     </imaps:connector>...
----

=== 端点

IMAP和IMAPS端点包含有关连接到IMAP邮箱的详细信息。您 link:/mule-user-guide/v/3.2/configuring-endpoints[配置端点]与其他运输方式一样，具有以下附加属性：

* 用户：邮箱所有者的用户名
* 密码：用户的密码
* 主机：IMAP服务器的名称或IP地址，例如www.mulesoft.com，localhost或127.0.0.1
* 端口：IMAP服务器的端口号。

例如：

[source, xml, linenums]
----
<imap:inbound-endpoint user="bob" password="password" host="localhost" port="65433"/>
----

安全版本：

[source, xml, linenums]
----
<imaps:inbound-endpoint user="bob" password="password" host="localhost" port="65433"/>
----

您还可以使用URI语法定义端点：

[source, xml, linenums]
----
<inbound-endpoint address="imap://bob:password@localhost:65433"/><inbound-endpoint address="imaps://bob:password@localhost:65433"/>
----

这将使用密码`password`登录到端口65433上的`localhost`上的`bob`邮箱。您也可以使用URI指定端点设置，但上述语法更易于阅读。

[source, code, linenums]
----
xslt: Read http://www.mulesoft.org/xslt/mule/schemadoc/3.1/individual-transport-or-module-wiki.xsl error because of: java.io.IOException: Server returned HTTP response code: 401 for URL: http://svn.codehaus.org/mule/branches/mule-3.1.x/tools/schemadocs/src/main/resources/xslt//individual-transport-or-module-wiki.xsl
----

这里是你如何在你的Mule配置文件中定义变压器：

[source, xml, linenums]
----
<email:bytes-to-mime-transformer encoding="" ignoreBadInput="" mimeType="" name="" returnClass="" xsi:type=""/><email:email-to-string-transformer encoding="" ignoreBadInput="" mimeType="" name="" returnClass="" xsi:type=""/><email:mime-to-bytes-transformer encoding="" ignoreBadInput="" mimeType="" name="" returnClass="" xsi:type=""/><email:object-to-mime-transformer encoding="" ignoreBadInput="" mimeType="" name="" returnClass="" useInboundAttachments="true" useOutboundAttachments="true"/>{Note}Need to explain attributes somewhere; can we pull them in from xsd?{Note}<email:string-to-email-transformer encoding="" ignoreBadInput="" mimeType="" name="" returnClass="" xsi:type=""/>
----

每个变压器都支持所有常见的变压器属性和属性：

[source, code, linenums]
----
xslt: Read http://www.mulesource.org/xslt/mule/schemadoc/3.0/single-element-wiki.xsl error because of: java.io.IOException: Server returned HTTP response code: 401 for URL: http://svn.codehaus.org/mule/branches/mule-3.1.x/tools/schemadocs/src/main/resources/xslt//single-element-wiki.xsl
----

对象到MIME变换器具有以下属性：

[%header,cols="3*",width=10%]
|===
|属性 |描述 |默认值
| useInboundAttachments  |是否将输入消息中的入站附件转换为MIME部分。 | true
| useOutboundAttachments  |是否将输入消息中的出站附件转换为MIME部分。 | true
|===

要使用这些转换器，请确保在您的mule配置中包含“email”命名空间。

=== 过滤器

可以在端点上设置过滤器来过滤掉任何不需要的消息。电子邮件传输提供了几个过滤器，可以直接使用或扩展以实现自定义过滤规则。

[%header,cols="2*"]
|===
| {过滤{1}}说明
| org.mule.providers.email.filters.AbstractMailFilter  |必须由任何其他邮件过滤器扩展的基本过滤器实现。
| org.mule.providers.email.filters.MailSubjectRegExFilter  |将正则表达式应用于邮件主题。
|===

这是您在Mule配置中定义MailSubjectRegExFilter的方法：

[source, xml, linenums]
----
<message-property-filter pattern="to=barney@mule.org"/>
----

'pattern'属性是一个正则表达式模式。这被定义为java.util.regex.Pattern。

==  Maven模块

电子邮件传输由mule-transport-email模块执行。您可以在传输/电子邮件中找到电子邮件传输的来源。

如果您使用maven构建您的应用程序，请使用以下依赖项片段将电子邮件传输包含在您的项目中：

[source, xml, linenums]
----
<dependency>  <groupId>org.mule.transports</groupId>  <artifactId>mule-transport-email</artifactId></dependency>
----

=  Mule-Maven依赖关系

如果您从源代码构建Mule ESB或在您的Maven项目中包含Mule构件，可能需要将“mule-deps”存储库添加到Maven配置中。此存储库包含第三方二进制文件，这些二进制文件可能不在任何其他公共Maven存储库中。

要将“mule-deps”存储库添加到Maven项目中，请将以下内容添加到您的pom.xml中：

[source, xml, linenums]
----
<repositories>    <repository>        <id>mule-deps</id>        <name>Mule Dependencies</name>        <url>http://dist.codehaus.org/mule/dependencies/maven2</url>        <snapshots>            <enabled>false</enabled>        </snapshots>    </repository></repositories>
----

= 限制

以下已知的限制会影响电子邮件传输：

*  http://www.mulesoft.org/jira/browse/BL-362[重试策略不适用于电子邮件传输]
*  http://www.mulesoft.org/jira/browse/BL-126[电子邮件传输不支持超时]
*  http://www.mulesoft.org/jira/browse/MULE-3662[无法将同一对象发送给不同的电子邮件用户]
*  http://www.mulesoft.org/jira/browse/MULE-1252[MailSubjectRegExFilter无法处理带有附件的邮件]

[TIP]
====
*Escape Your Credentials* +

如果您使用URI风格的端点并且包含用户名和密码，请转义任何对URI不合法的字符。只允许使用字母，数字，"-"，"_"，"."和"+"。例如，如果用户名是`user@myco.com`，则应将其输入为`user%40myco.com`。
====
