=  JBoss事务管理器参考

== 交易经理

要在Mule中配置JBoss事务管理器的实例，请将此元素添加到您的Mule XML配置文件中。您可以在事务管理器上配置任意属性，并将其传递给基础事务管理器。例如：

[source, xml, linenums]
----
<jbossts:transaction-manager>   <property key="test" value="TEST"/></jbossts:transaction-manager>
----

然后，您可以在支持XA事务的端点上声明XA事务，所有这些事务将由JBoss事务管理器进行管理。

Mule自动生成事务管理器XA节点ID。要自己指定ID，请添加以下属性：

[source, xml, linenums]
----
<jbossts:transaction-manager>   <properties>      <spring:entry key="com.arjuna.ats.arjuna.xa.nodeIdentifier" value="SomeUserNodeId"/>   </properties></jbossts:transaction-manager>
----

<transaction-manager...>的{​​{0}}属性

[%header,cols="5*",width=10%]
|===
| {名称{1}}输入 |必 |缺省 |说明
|===

<transaction-manager...>的{​​{0}}子元素

[%header,cols="3*",width=10%]
|===
| {名称{1}}基数 |说明
|===

==  JBoss事务管理器的附加属性

您可以为JBoss事务管理器配置许多属性。这些可配置的属性详细 http://docs.jboss.org/jbosstm/docs/4.2.3/javadoc/jts/com/arjuna/ats/arjuna/common/Environment.html[在环境类中]。

以下是一个演示如何配置与事务超时相关的属性的示例。

=== 配置事务超时属性

有两个属性与JBoss事务的超时有关。 （请注意，超时属性的信息来自 http://docs.jboss.org/jbosstm/docs/4.2.3/manuals/html/core/ProgrammersGuide.html#_Toc22872822[这里]）。

*  `com.arjuna.ats.arjuna.coordinator.defaultTimeout`
** 此`defaultTimeout`属性定义为此经理创建的每个事务的超时期限。在超时值过期之前尚未终止的事务会自动回滚。默认值是60秒。
*  `com.arjuna.ats.arjuna.coordinator.txReaperTimeout`
**  JBossTS使用一个单独的收割线程来监视所有本地创建的事务并强制它们在超时过后回滚。为了防止这个收割线程消耗应用程序时间，它只能定期运行。默认情况下，收割线程设置为每120000毫秒监视本地事务。您可以通过设置`txReaperTimeout`属性来覆盖此默认值。注意：如果`defaultTimeout`属性值小于`txReaperTimeout`属性值，则收割者线程每`defaultTimeout`秒检查一次事务。

[source, xml, linenums]
----
<jbossts:transaction-manager >    <property key="com.arjuna.ats.arjuna.coordinator.defaultTimeout" value="47" /><!-- this is in seconds -->    <property key="com.arjuna.ats.arjuna.coordinator.txReaperTimeout" value="108000"/><!-- this is in milliseconds --></jbossts:transaction-manager>
----

*Note*：下面的代码示例中显示的`xa-transaction`标记中的`timeout`参数对于JBoss事务而言将被忽略，因为这些事务在`jbossts:transaction-manager`中全局配置。请注意，此代码显示的是一条直通线，表示您应该*ignore*该参数。

[source, xml, linenums]
----
<xa-transaction action="ALWAYS_BEGIN" timeout="60000"/>
----

== 架构

* 架构：http://www.mulesoft.org/schema/mule/jbossts/3.2/mule-jbossts.xsd
* 架构结构：http：//www.mulesoft.org/docs/site/3.3.0/schemadocs/schemas/mule-jbossts_xsd/schema-overview.html
