=  JDBC传输示例

本页介绍了您可以运行Mule Enterprise JDBC传输的示例。这些示例旨在与Oracle和Sybase数据库一起使用。

== 安装JDBC示例

Mule Enterprise JDBC示例位于$ MULE_HOME / examples / jdbc的安装位置。

. 在$ MULE_HOME / examples / jdbc / scripts中，您可以找到两个目录，一个用于Oracle，另一个用于Sybase。
. 运行tables.ddl脚本（位于后面提到的目录中）在数据库中创建必要的表。
. 运行位于后面提到的目录中的procs.ddl脚本）在数据库中创建必要的存储过程。
. 将数据库驱动程序复制到$ MULE_HOME / lib / user目录。
. 将预先构建的应用程序存档（mule-example-jdbc.zip）复制到应用程序文件夹（$ MULE_HOME / apps）。
. 开始骡子。
. 编辑apps / mule-example-jdbc / classes / db.properties文件以设置数据库连接配置。 +
注意：如果您需要更改db.properties中的某些内容，请重新启动mule或仅"touch $MULE_HOME/apps/mule-example-jdbc/mule-config.xml"（在UN * X中）。

== 运行该示例

要访问网络服务，请在浏览器中输入`+http://localhost:8084/services/jdbc+`。

你会看到一排按钮发送命令，一个响应窗口和一个上传的mules列表。

=== 从CSV输入插入数据

点击"Load CSV data"。

您将看到一个XML输出，显示上传的mules上的信息。

如果您尝试多次点击该按钮，则会收到由主键违规造成的异常。

=== 从数据库中检索计数

点击"Retrieve mules"

您将看到包含存储在数据库表中的mules的XML输出。

=== 克隆对象

点击"Clone mules"。

克隆过程后您会看到骡子的数量。

请尝试再次点击"Clone mules"，查看数量增长情况。

验证点击"Retrieve mules"的人口增长情况。

=== 擦除数据库中的数据

无需按照此顺序执行此步骤。

点击"Cleanup Mules"。

您将收到确认命令已发送。

确认点击"Retrieve mules"不再有骡子。

== 另请参阅

*  link:/mule-user-guide/v/3.2/jdbc-transport-reference[JDBC传输参考]
