= 贷款代理示例

这个Mule ESB示例应用程序演示了Web服务集成中基于内容的路由的强大功能。

根据“企业集成模式：设计，构建和部署消息传递解决方案”（Hohpe，Woolf，2004）第9章中介绍的贷款代理示例，该应用程序可最大限度地减少借款人获得贷款最佳利率的工作。

Loan Broker公开了一个Web服务，用于处理最终用户对银行利率报价的请求。最终用户从Web浏览器提交包含以下内容的请求：

* 借款人的名字
贷款额* 
还款期限为贷款的* 
* 借款人的社会安全号码（SSN）+


Mule ESB的Loan Broker应用程序访问其他Web服务来处理请求，然后响应最终用户。答复确定了最低报价的银行名称和利率。

Loan Broker Web服务使用四个元素来最大化其处理效率：

*  *Choice Flow Controls*根据内容路由邮件
*  *Transformers*来转换消息有效载荷的数据格式
*  *Message Enrichers*添加到消息负载而不是更改
*  *Foreach*迭代地同步处理消息有效载荷
*  *Dynamic Endpoints*根据消息的有效载荷向不同的银行发送请求

这个例子可以帮助你做出明智的决定，在Mule应用程序中使用上面列出的四个元素。要更多地了解Mule ESB整合服务和系统的能力，请访问Mule [示例]并查看其他应用程序的实际运行情况。

== 假设

本文档假定您熟悉Mule ESB和Mule Studio界面。为了增加对Studio的熟悉度，请考虑完成一个或多个Mule Studio教程。

本文档在Mule ESB的图形用户界面（GUI）*Mule Studio*的上下文中描述了示例的细节。在适当的情况下，XML配置在可扩展部分的Studio界面屏幕截图之后。

== 设置

就像这个贷款代理示例一样，您可以直接在*Mule Studio*或*Mule Standalone*（没有Studio的Mule ESB）中创建模板应用程序。您可以调整这些基于用例的模板的配置，以在Mule中创建您自己的自定义应用程序。

按照以下过程创建，然后在Mule ESB中运行贷款代理应用程序。

. 完成[示例和练习]中的过程以创建，然后在[Mule Studio]中运行贷款代理模板，或者在[Mule Standalone]（没有Studio的Mule ESB）中运行贷款代理示例。
. 打开您的Web浏览器。
. 在您的浏览器的地址栏中输入`+http://localhost:11081?name=Muley&amount=20000&term=48&ssn=1234+`，然后按*enter*以引发Loan Broker应用程序的响应（如下所示）。
. 在浏览器的地址栏中，用`5000`替换`amount`，然后按*enter*以从应用程序中引发新的响应（如下所示）。

== 它是如何工作的

贷款经纪人应用程序由多个[流和子流]组成。这些流程集成了Web服务来处理最终用户对银行利率报价的请求。

以下部分提供贷款经纪人在处理最终用户请求时所采取行动的逐流描述。

在Mule Studio中，双击[building block]打开其*Properties Panel*，然后检查其配置细节。或者，单击*Configuration XML*选项卡检查应用程序的XML配置文件。

=== 贷款代理同步流程

作为Loan Broker应用程序的主要流程，此流程可协调数据收集以产生最终用户响应。

[source,xml,linenums]
----
<flow name="loan-broker-sync" doc:name="loan-broker-sync" doc:description="            The main loanbroker flow that:            i) Receives a customer request            ii) Performs a lookup of the customer credit profile using a component binding            iii) Determines the bank that should be used to request quotes            iv) Sends the request to the selected banks and aggregates responses            v) Selects the lowest quote from the list of quotes            vi) Returns the response to the client        ">        <description>            The main loanbroker flow that:            i) Receives a customer request            ii) Performs a lookup of the customer credit profile using a component binding            iii) Determines the bank that should be used to request quotes            iv) Sends the request to the selected banks and aggregates responses            v) Selects the lowest quote from the list of quotes            vi) Returns the response to the client        </description>        <{{0}} == null || payload['ssn'] == null || payload['amount'] == null || payload['term']==null)">                <processor-chain>                    <expression-component doc:name="create customer request">import org.mule.example.loanbroker.message.CustomerQuoteRequest; import org.mule.example.loanbroker.model.Customer; payload = new CustomerQuoteRequest(new Customer(payload['name'], Integer.parseInt(payload['ssn'])), Integer.parseInt(payload['amount']), Integer.parseInt(payload['term']));</expression-component>                    <enricher source="#[payload]" target="#[flowVars['creditProfile']]" doc:name="Enrich with creditProfile">                        <flow-ref name="lookupCustomerCreditProfile" doc:name="lookupCustomerCreditProfile"/>                    </enricher>                    <enricher source="#[payload]" target="#[flowVars['banks']]" doc:name="Enrich with banks">                        <flow-ref name="lookupBanks" doc:name="lookupBanks"/>                    </enricher>                    <set-variable variableName="quotes" value="#[new java.util.LinkedList()]" doc:name="create empty quotes"/>                    <foreach collection="#[flowVars['banks']]" doc:name="Foreach">                        <enricher target="#[quotes.add($)]" doc:name="Message Enricher">                            <flow-ref name="lookupLoanQuote" doc:name="lookupLoanQuote"/>                        </enricher>                    </foreach>                    <flow-ref name="findLowestLoanQuote" doc:name="findLowestLoanQuote"/>                    <object-to-string-transformer doc:name="Object to String"/>                </processor-chain>            </when>            <otherwise>                <expression-component doc:name="set error message">payload="Error: incomplete request"</expression-component>            </otherwise>        </choice>        <catch-exception-strategy doc:name="Catch Exception Strategy">            <set-payload value="Error processing loan request" doc:name="Set error message"/>        </catch-exception-strategy>    </flow>
----

此流程中的请求 - 响应 link:/mule-user-guide/v/3.2/http-endpoint-reference[* HTTP入站端点*]接收最终用户请求。由于它具有双向消息交换模式，因此此HTTP端点负责接收和返回消息。

*Two-Way vs. One-Way*

请注意，HTTP端点具有*two-way message exchange pattern*（如左下方的小双箭头图标所示）。由于它必须响应请求者，因此本示例中的HTTP端点具有请求 - 响应消息交换模式。

如果HTTP端点只需要将信息输入到应用程序中，则需要*one-way message exchange pattern*（下方，右边）。

接下来，*Body to Parameter Map Transformer*将消息有效载荷的数据格式从 http://en.wikipedia.org/wiki/HTTP_body_data[HTTP正文数据]转换为Java http://en.wikipedia.org/wiki/Associative_array[地图]。 Loan Broker应用程序仅处理Java消息有效内容。

然后，Mule使用基于内容的路由器来引导消息进行进一步处理。根据其有效负载内容， link:/mule-user-guide/v/3.2/choice-flow-control-reference[*选择流量控制*]将每条消息路由到两个处理路径之一。

* 如果消息有效载荷包含完整请求（即借款人的姓名和SSN以及贷款金额和期限），则选择流控制将消息传递给`create customer request` [{{2 }}]。
* 如果消息有效负载是不完整的请求，则选择流控制将消息传递给`set error message`表达式组件。该组件将消息的有效负载设置为`Error: incomplete request`。穆勒不再进一步处理信息。相反，它会通过错误消息响应最终用户。

`create customer request`组件使用表达式从消息负载中提取数据。它使用这些数据创建一个具有三个值的新Java对象：

.  `Customer`，它标识借款人的名称和SSN
. 一个`Integer`，标识贷款金额
. 第二个`Integer`，标识贷款还款期限

[source,xml,linenums]
----
<expression-component doc:name="create customer request">import org.mule.example.loanbroker.message.CustomerQuoteRequest; import org.mule.example.loanbroker.model.Customer; payload = new CustomerQuoteRequest(new Customer(payload['name'], Integer.parseInt(payload['ssn'])), Integer.parseInt(payload['amount']), Integer.parseInt(payload['term']));</expression-component>
----

在其有效载荷中使用新的`CustomerQuoteRequest`对象时，消息遇到其第一个[*Message Enricher*]。在整个流程中，Mule _enriches_带有数据的消息而不是改变有效载荷内容。通过丰富消息，Mule保留有效内容，以便应用程序中的其他元素可以访问原始数据。

`Enrich with creditProfile`浓缩器仅包含一个 link:/mule-user-guide/v/3.2/flow-ref-component-reference[*流量参考组件*]。这种类型的组件调用应用程序中的其他流或子流来获取数据，然后将数据添加到消息中。在这种情况下，`lookupCustomerCreditProfile`组件要求LookupCustomerCreditProfile子流访问外部Web服务以获取借款人的信用评分。穆勒用信用评分丰富了信息，然后将信息传递给流中的下一个丰富者。

与其前身一样，`Enrich with Banks`浓缩器使用流参考组件来调用子流并获取数据。在这种情况下，Mule使用LookupBanks子流的结果将一个 http://en.wikipedia.org/wiki/List_(abstract_data_type)[名单]个银行添加到邮件有效负载中，而不是添加信用评分。

然后，Mule使用*Variable Transformer*创建一个空的列表变量。 Mule将用它从银行提取的引号填充这个空的`quotes`列表变量。如果要填写空白列表，则接下来的消息会遇到[*Foreach Scope*]。这个迭代处理器逐个获取数据来填充列表中的每个项目。

为了获取这些数据，流参考组件首先调用LookupLoanQuote子流从银行获取报价。然后，消息富集器将该引用添加到列表变量中。 Foreach继续援引，然后进行充实，直到它从银行名单上的每家银行获得了一份报价。然后，Foreach将消息传递给流中的下一个 link:/mule-user-guide/v/3.2/mule-studio-essentials[*消息处理器*]。

通过一个例子来说明foreach的行为，想象一下包含以下内容的消息负载：

* 一个空的`quotes`列表变量
* 一个`banks`变量列出了Mule必须要求报价的两家银行：MuliNational Bank和IndustrialGrowth Bank

Foreach处理消息负载如下：

.  Foreach会咨询`banks`列表变量，以了解它应该向MuliNational发送其第一个请求。
.  Foreach调用LookupLoanQuote子流。
.  LookupLoanQuote子流程会调用`getLoanQuote` Web服务以获取MultiNational的利率报价。
.  LookupLoanQuote子流提供对贷款代理同步流程的Web服务响应。
. 消息richher将来自MultiNational的利率报价插入到`quotes`列表变量中。
.  Foreach咨询`banks`列表变量，以了解它应该向IndustrialGrowth发送第二个请求。
.  Foreach调用LookupLoanQuote子流。
.  LookupLoanQuote子流程将调用`getLoanQuote` Web服务以获取IndustrialGrowth的利率报价。
.  LookupLoanQuote子流提供对贷款代理同步流程的Web服务响应。
。消息richher将来自IndustrialGrown的利率报价插入到`quotes`列表变量中。
.Foreach咨询`banks`列表变量以在列表中找到更多项目。它将消息传递给下一个消息处理器，该消息现在与包含两个利率报价的列表一起传递。请参阅下表以获取消息内容的前后比较。

消息内容在迭代处理之前与迭代处理之后的消息内容相同：

*  `banks`列表变量：
*  www.multinational.com/loans/quotes
*  www.industrialgrowth.com/loans/quotes

迭代处理后的消息内容：

`quote`列表变量：

*  6.99
*  6.84

此流程中倒数第二个消息处理器在应用程序中引用另一个子流程。 `findLowestLoanQuote`子流程确定列表中哪个报价最低，然后将结果记录在消息有效负载中。

最后，*Object to String Transformer*将消息有效载荷的数据格式从Java转换为字符串。 HTTP端点将响应发送给最终用户。

请注意，贷款代理同步流程还包含一个[*Catch Exception Strategy*]。这个流程不是使用Mule的 link:/mule-user-guide/v/3.2/error-handling[默认的例外策略]，而是使用定制的异常策略来处理错误。如果流中发生错误，则异常策略的*Set Payload Transformer*会在有效负载上设置错误消息。应用程序将此错误消息发送给`Error processing loan request`作为对最终用户的响应。

===  LookupCustomerCreditProfile子流

根据贷款经纪人同步流程的需求进行调用，此子流程获取并记录借款人在信息有效负载中的信用评分。

[source,xml,linenums]
----
<sub-flow name="lookupCustomerCreditProfile" doc:name="lookupCustomerCreditProfile" doc:description="            Returns the customer credit profile obtained form the Credit Agency        ">        <description>            Returns the customer credit profile obtained form the Credit Agency        </description>        <set-payload value="#[payload.customer]" doc:name="customer"/>        <processor-chain doc:name="Processor Chain">            <cxf:jaxws-client serviceClass="org.mule.example.loanbroker.creditagency.CreditAgencyService" operation="getCreditProfile" doc:name="getCreditProfile"/>            <{{0}}" doc:name="creditProfile"/>    </sub-flow>
----


为了获得信用评分，`customer`转换器将有效载荷设置为`Customer`，如`create customer request`表达式转换器所定义。 （回想一下`Customer`变量包含借用者的名称和SSN。）Mule向`getCreditProfile` SOAP Web服务发送一个请求。 HTTP端点将Web服务的响应插入到子流中。

Mule利用 http://cxf.apache.org[Apache的CXF框架]来构建Web服务。包装 link:/mule-user-guide/v/3.2/soap-component-reference[* SOAP组件*]和HTTP出站端点的处理器链是CXF要求。它确保Mule在记录处理结果之前完成所有处理活动。

最后，在此流程中， link:/mule-user-guide/v/3.2/logger-component-reference[*记录器组件*]将消息有效载荷上的Web服务响应的有效内容记录为`Credit Profile`。

===  LookupBanks子流

贷款经纪人应用程序可以防止所有银行泄露所有贷款报价请求。例如，一家迎合首映客户的银行会因为信用不良的借款人收到一笔小额贷款的报价而被拒绝。为了防止对银行Web服务的这种令人不快的调用，贷款代理应用程序使用*LookupBanks*子流。

[source,xml,linenums]
----
<sub-flow name="lookupBanks" doc:name="lookupBanks" doc:description="            Returns the list of banks to contact and returns it as a flow variable 'banks'        ">        <description>            Returns the list of banks to contact and returns it as a flow variable 'banks'        </description>        <choice doc:name="Choice">            <when expression="payload.getLoanAmount() &gt;= 20000">                <expression-component doc:name="Bank1, Bank2">payload=[new java.net.URI(' http://localhost:10080/mule/TheBank1'), new java.net.URI('http://localhost:20080/mule/TheBank2')]</expression-component>            </when>            <when expression="payload.getLoanAmount() &gt;= 10000 || payload.getLoanAmount() &lt;= 19999">                <expression-component doc:name="Bank3, Bank4">payload=[new java.net.URI('http://localhost:30080/mule/TheBank3'), new java.net.URI('http://localhost:40080/mule/TheBank4')]</expression-component>            </when>            <otherwise>                <expression-component doc:name="Bank5">payload=[new java.net.URI(' http://localhost:50080/mule/TheBank5')]</expression-component>            </otherwise>        </choice>        <logger level="INFO" message="Banks to contact: #[payload]" doc:name="banks"/>    </sub-flow>
----


Mule首先使用选择流量控制来检查有效负载中的`amount`，然后根据贷款的大小路由消息。

* 如果贷款超过20,000美元，流量控制会将消息路由到第一个表达式组件，标记为`Bank 1, Bank 2`。
* 如果贷款超过$ 10,000，流量控制会将消息路由到第二个表达式组件，标记为`Bank 3, Bank 4`。
* 如果不是这样（即贷款为$ 10,000或更少），流量控制会将消息路由到标记为`Bank 5`的第三个表达式组件。

[source,xml,linenums]
----
<choice doc:name="Choice">            <when expression="payload.getLoanAmount() &gt;= 20000">                <expression-component doc:name="Bank1, Bank2">payload=[new java.net.URI(' http://localhost:10080/mule/TheBank1'), new java.net.URI('http://localhost:20080/mule/TheBank2')]</expression-component>            </when>            <when expression="payload.getLoanAmount() &gt;= 10000 || payload.getLoanAmount() &lt;= 19999">                <expression-component doc:name="Bank3, Bank4">payload=[new java.net.URI('http://localhost:30080/mule/TheBank3'), new java.net.URI('http://localhost:40080/mule/TheBank4')]</expression-component>            </when>            <otherwise>                <expression-component doc:name="Bank5">payload=[new java.net.URI('http://localhost:50080/mule/TheBank5')]</expression-component>            </otherwise>        </choice>
----

请注意，选择流控件将消息引导至评估为true的第一个表达式。例如，它仅向`Bank 1, Bank 2`组件提供一笔$ 30,000的贷款报价请求。

此子流中的每个表达式组件都包含愿意提供利率报价的银行的URI。例如，传递到`Bank 3, Bank 4`组件的消息作为有效负载添加了银行3和4的URI。`banks`记录器组件记录要向其发送请求的适当银行列表。

===  LookupLoanQuote子流

这会向银行的Web服务发送报价请求。

[source,xml,linenums]
----
<sub-flow name="lookupLoanQuote" doc:name="lookupLoanQuote" doc:description="            Returns a loanQuote from a given bank's URI        ">        <description>            Returns a loanQuote from a given bank's URI        </description>        <set-variable variableName="bankUri" value="#[payload]" doc:name="bankUri"/>        <expression-component doc:name="create LoanBrokerLoanRequest">            import org.mule.example.loanbroker.message.LoanBrokerQuoteRequest;            LoanBrokerQuoteRequest bqr = new LoanBrokerQuoteRequest();            bqr.setCreditProfile(flowVars['creditProfile']);            payload = bqr;        </expression-component>        <processor-chain doc:name="Processor Chain">            <cxf:jaxws-client serviceClass="org.mule.example.loanbroker.bank.BankService" operation="getLoanQuote" doc:name="getLoanQuote"/>            <{{0}}.getHost()]:#[flowVars['bankUri'].getPort()]#[flowVars['bankUri'].getPath()]" doc:name="HTTP"/>        </processor-chain>        <logger message="LoanQuote from #[flowVars['bankUri']]: #[payload]" level="INFO" doc:name="quote"/>    </sub-flow>
----


首先，变量转换器将Mule消息负载（银行的URI）存储为名为`bankUri`的变量。 （回想一下，这个子流从Loan-broker-sync流中的foreach中一次接收一个请求，每个请求的有效载荷是一个银行的URI。）

`create LoanBrokerLoanRequest`组件使用表达式从消息负载中提取借用者的信用配置文件（由`creditProfile`记录器在LookupCustomerCreditProfile流中记录）。它使用数据创建发送到`getLoanQuote` Web服务的请求。 +
Mule使用SOAP组件（配置为JAXWS客户端）将请求发送到银行的Web服务。 HTTP出站端点根据消息有效载荷中的银行URI动态确定发送请求的位置。它从银行的Web服务接收响应，并将响应负载推送到`quote`记录器进行记录。

===  FindLowestLoanRequest子流

这个简单的子流程使用表达式组件来确定引号列表中的哪个项目提供最低的利率。记录器记录结果。

[source,xml,linenums]
----
<sub-flow name="findLowestLoanQuote" doc:name="findLowestLoanQuote" doc:description="            Returns the loan quote with the lowest interest rate        ">        <description>            Returns the loan quote with the lowest interest rate        </description>        <set-variable variableName="lowestQuote" value = "#[null]" doc:name="Variable"/>        <expression-component doc:name="Expression">            <![CDATA[            import org.mule.example.loanbroker.model.LoanQuote;            for (Object current : (List) flowVars['quotes'])            {                LoanQuote loanQuote = (LoanQuote) current;                if (flowVars['lowestQuote'] == null)                {                    flowVars['lowestQuote'] = loanQuote;                }                else if (loanQuote.getInterestRate() < flowVars['lowestQuote'].getInterestRate())                {                    flowVars['lowestQuote'] = loanQuote;                }            }            payload = flowVars['lowestQuote'];            ]]>        </expression-component>        <logger level="INFO" message="Lowest loan quote: #[payload]" doc:name="lowestQuote"/>    </sub-flow>
----

组件中的表达式将列表中项目的`getInterestRate`相互比较，以确定哪个项目最低。

[source,java]
----
import org.mule.example.loanbroker.model.LoanQuote;            for (Object current : (List) flowVars['quotes'])            {                LoanQuote loanQuote = (LoanQuote) current;                if (flowVars['lowestQuote'] == null)                {                    flowVars['lowestQuote'] = loanQuote;                }                else if (loanQuote.getInterestRate() < flowVars['lowestQuote'].getInterestRate())                {                    flowVars['lowestQuote'] = loanQuote;                }            }            payload = flowVars['lowestQuote'];
----

=== 模拟流程

贷款经纪人申请中剩余的六笔资金是“模拟资金流”。它们充当外部Web服务，五个合法流和子流调用其请求数据。

每个流程包含：

* 请求 - 响应HTTP端点和SOAP组件来接收请求
*  a link:/mule-user-guide/v/3.2/java-component-reference[* Java组件*]，它产生随机数据以模拟Web服务处理。

您不需要将这些流程包含在您的定制应用程序中;它们仅存在于贷款经纪人示例中以支持功能性示例。


