= 关于模型

_model_是一组服务。模型管理Mule ESB实例托管的服务组件的运行时行为。这些组件被调用和处理的方式都被封装在当前的Mule模型中。

== 配置模型

要配置模型，请将`<model>`元素添加到您的Mule配置文件中。然后在模型中添加服务。有关配置详细信息，请参阅 link:/mule-user-guide/v/3.2/model-configuration-reference[模型配置参考]。

== 模型接口

每个Mule模型都实现了`Model`接口。该接口表示Mule服务器的行为，并与以下对象配合使用。有关字段和方法的完整列表，请参阅模型界面 http://www.mulesoft.org/docs/site/current/apidocs/org/mule/api/model/Model.html[org.mule.api.model.Model]。另请参阅 http://www.mulesoft.org/docs/site/current/apidocs/org/mule/model/AbstractModel.html[org.mule.model.AbstractModel]，它是一个实现此接口的抽象类，是所有模型的父类。

[%header,cols="10a,90a"]
|===
| {对象{1}}说明
|名称 |引用模型名称并设置为`<model>`元素中的属性的字符串。如果未给出名称，则自动生成唯一值。
| ExceptionListener  |用于整个模型的异常策略。异常策略用于处理组件正在处理消息时发生的任何异常。有关例外策略的更多信息，请参阅 link:/mule-user-guide/v/3.2/error-handling[错误处理]。
| EntryPointResolverSet  |一组实现`EntryPointResolver`接口的类。这些将用于在收到消息时确定任何托管组件的入口点。您可以使用`<abstract-entry-point-resolver>`元素配置入口点解析器，或使用`<abstract-entry-point-resolver-set>`元素配置入口点解析器。有关入口点解析程序的更多信息，请参阅 link:/mule-user-guide/v/3.2/developing-components[开发组件]。
| LifecycleAdapterFactory  |模型用于创建生命周期适配器，这些适配器将Mule生命周期事件转换为组件注册的消息所理解的消息。您在`<component>`元素上配置lifecyle适配器，而不是在模型本身上。有关生命周期适配器的更多信息，请参阅 link:/mule-user-guide/v/3.2/developing-components[开发组件]。
|===
