= 模型配置参考

此页面提供有关为模型配置的元素的详细信息。其中一些信息直接从`mule.xsd`中提取并被缓存。如果信息看起来已过时，请刷新页面。有关模型的更多信息，请参阅 link:/mule-user-guide/v/3.2/models[楷模]。

http://www.mulesoft.org/docs/site/3.3.0/schemadocs/schemas/mule_xsd/elements/model.html[模型元素的架构参考文档。]

== 模型

一组服务的容器，为其包含的所有服务提供基本设置和处理。

<model...>的{​​{0}}属性

[%header,cols="10,10,10,10,60"]
|===
| {名称{1}}输入 |必 |缺省 |说明
|名称 |名称 |否 |   |用于识别此模型的名称。
|继承 |布尔值 |否 |   |如果为true，则此模型元素是具有相同名称的以前模型元素的扩展。
|===

<model...>的{​​{0}}子元素

[%header,cols="10,10,80"]
|===
| {名称{1}}基数 |说明
| abstract-exception-strategy  | 0..1  |异常策略元素的占位符。例外策略定义了Mule应该如何对错误做出反应。
| abstract-service  | 0 .. *  |服务元素的占位符。服务将消息路由与组件（通常是POJO）结合在一起。
|抽象入口点解析器集合 | 0..1  |入口点解析器集合元素的占位符。这些组合了一组入口点解析器，依次尝试它们直到成功。
|抽象入口点解析器 | 0..1  |入口点解析器元素的占位符。入口点解析器通过选择要调用的方法来定义如何将有效载荷传递给Java代码。
| abstract-queue-profile  | 0..1  |队列配置文件的占位符，用于控制消息如何排队。
|===

== 队列配置文件

指定内部Mule队列的属性。内部队列用于对由Mule管理的每个组件的消息进行排队。

<queue-profile...>的{​​{0}}属性

[%header,cols="10,10,10,10,60"]
|===
| {名称{1}}输入 |必 |缺省 |说明
| maxOutstandingMessages  |整数 |否 |   |定义可以排队的最大消息数。
|===

<queue-profile...>的{​​{0}}子元素

[%header,cols="10,10,80"]
|===
| {名称{1}}基数 |说明
|抽象队列商店 | 0..1  |用于存储队列元素的队列存储。如果未指定，则这将是默认的内存中队列存储。队列存储元素的占位符。
|===

== 例外策略

请参阅 link:/mule-user-guide/v/3.2/exception-strategy-configuration-reference[例外策略配置参考]。

== 服务

请参阅 link:/mule-user-guide/v/3.2/service-configuration-reference[服务配置参考]。

== 入口点解析器

请参阅 link:/mule-user-guide/v/3.2/entry-point-resolver-configuration-reference[入口点解析器配置参考]。
