=  MQL参考指南

== 概述

MQL表达式遵循以下结构：

[source, code, linenums]
----
from object as o  join ...  where ...   select new {     property = object_expression  }
----

如果只希望转换对象，则可以使用省略from，join和where语句的快捷方式符号：

[source, code, linenums]
----
select new {  property = object_expression}
----

==  Where子句

where子句允许您过滤掉对象。例如：

[source, code, linenums]
----
from people where age > 21 and (firstName = 'Joe' or firstName = 'Jane')
----

* 支持以下比较器：=，<, >，！=，如。
* 像对左手对象中的右手词执行不区分大小写的搜索。
* 子句的优先级由圆括号决定。
* 个人where子句的左侧和右侧可以是任何<<Object Expressions>>。
* 您可以使用和不使用"as"标识符来引用所选对象上的属性。例如，这两个表达式是等价的：

[source, code, linenums]
----
from people as p where age > 21from people as p where p.age > 21
----

== 加入子句

连接子句允许您连接来自其他数据源的数据并将其选中。它遵循以下形式：

[source, code, linenums]
----
join object_expression as variable on condition async(threads)|sync
----

[%header,cols="10,90"]
|===
| {条{1}}说明
|表达式 |任何<<Object Expressions>>。
|变量 |将连接结果放入的变量的名称
|条件 |是否加入数据的条件。返回布尔值的MVEL表达式。 on子句是可选的
| async / sync  |是否异步执行连接。如果是异步的，将创建一个执行器来加入数据。执行者可以选择使用Query.setExecutor方法指定。线程的数量也可以被指定为async语句的一部分，例如异步（5）。 "sync"指定联接应该同步发生。默认情况下它是异步（10）。
|===

例：

[source, code, linenums]
----
from users as u join twitter.getTweetCount(u.twitterId) as tweetCount on u.twitterId  select new {     name = u.name,     tweetCount = tweetCount  }
----

== 选择新对象

select语句为查询的每个对象创建一个新对象。如果不存在select语句，则返回原始查询对象。 equals语句的左边是创建的属性的名称。右侧是任何<<Object Expressions>>。

=== 选择地图

您可以使用`select new`创建具有不同属性的新Map对象。

[source, code, linenums]
----
from users as u select new {   name = u.firstName + ' ' + u.lastName }
----

=== 选择POJO

您可以实例化POJO的实例并使用`select new(className)`语法在它们上设置属性：

[source, code, linenums]
----
from users as u select new(com.mulesoft.examples.UserSummary) {   name = u.firstName + ' ' + u.lastName }
----

=== 选择子对象

您还可以创建子关系，例如：

[source, code, linenums]
----
from users as u select new {   name = u.name,   address = new {     address1 = u.address1,     address2 = u.address2,     state = u.state,     city = u.city   } }
----

这将产生地址字段的子对象，该地址字段由address1，address2，state和city属性组成。

== 对象表达式

对象表达式是MVEL语法的一个子集。支持的MVEL语法片段包括：

* 值测试
* 数组，列表和地图
* 属性导航
* 功能
* 字符串和数字

例子包括：

[source, code, linenums]
----
object.propertyobject.function()object[index]object 'foo'123nullx + yx
----

