=  Mule查询语言

MQL是一款适用于Java和Mule的LINQ启发式查询语言。有了它，您可以*filter, join and transform data from Mule messages, cloud connectors, and Spring beans*以非常简洁的代码。通过Mule中的`<mql:query-service>`支持，您可以立即将该查询转换为REST服务。 MQL目前处于测试阶段。

以下是一些快速示例：

[%header,cols="2*"]
|===
| {描述{1}}查询
|过滤数据a |

[source, code, linenums]
----
from userManager.users   where division = ‘Sales’ and     (email like ‘mulesoft.com’ or email like ‘mulesource.com’)
----

查询userManager.getUsers（）并返回所有处于销售状态且具有包含"mulesoft.com"或"mulesource.com"的电子邮件的用户

|将数据转换为Map / POJO a |

[source, code, linenums]
----
from userManager.users as u select new {  href = 'http://localhost/users/' + u.id,  name = u.firstName + ' ' + u.lastName,  division = u.division}
----

查询userManager.getUsers（）并创建具有href，name和division属性的新对象。该对象默认为`Map`，但也可以通过在select语句中使用`new(com.foo.UserSummary)`等语法来实现POJO。

|从Salesforce加入数据a |

[source, code, linenums]
----
from userManager.users as user  join salesforce.query('SELECT Company, MobilePhone                          FROM Lead                          WHERE Email = \'' + user.email + '\'', 1)    as sfuser  select new {    name = user.name,    email = user.email,    company = sfuser[0].?Company,    mobilePhone = sfuser[0].?MobilePhone  }
----

查询userManager.getUsers（）并为每个用户调用SalesForce云连接器，以根据用户的电子邮件地址检索用户信息。在select语句中，我们基于本地数据（名称和电子邮件）和SalesForce数据（公司和移动电话）创建一个新对象。

|即时REST服务|

[source, xml, linenums]
----
<mql:query-service name="UsersService"   address="http://localhost:9002/mulesoft-users"  query="from userManager.users as u where email like 'mulesoft.com'"/>
----

在执行指定查询的指定地址上创建REST服务。数据以JSON格式返回。

|将Mule消息转换为|

[source, xml, linenums]
----
<mql:transform query="select new { name = u.name, email = u.email}"/>
----

接收Mule消息有效负载（POJO或JSON数据）并将其转换为新对象（PO​​JO或JSON）。如果有效负载是集合，它将转换每个单独的对象。如果有效负载是单个对象，它将返回一个单独的变换对象。

|===

== 用例

[%header,cols="10,90"]
|===
| {名称{1}}说明
| link:/mule-user-guide/v/3.2/mql-query-java-objects[查询Java对象]  |查询本地POJO并将它们转换为不同的对象。
| link:/mule-user-guide/v/3.2/mql-merge-datasets[合并数据集]  |在本例中，请参阅如何从Twitter和Yammer获取活动流并将它们合并为一种通用格式。
| link:/mule-user-guide/v/3.2/mql-enrich-data[丰富数据]  |在本例中，本地数据充满了来自SalesForce的数据
| link:/mule-user-guide/v/3.2/mql-service-versioning[服务版本控制]  |为您的服务轻松处理两种不同的数据格式（1.0版和2.0版）。
|===

== 资源

*  link:/mule-user-guide/v/3.2/mql-download[下载]
*  link:/mule-user-guide/v/3.2/mql-mule-integration[骡子融合]
*  link:/mule-user-guide/v/3.2/mql-spring-integration[Spring集成]
*  link:/mule-user-guide/v/3.2/mql-reference-guide[语法指南]
*  link:/mule-user-guide/v/3.2/mql-roadmap[路线图]
