=  Mule对象商店

*object store*是用于在Mule中存储对象的抽象。通过使用对象存储，Mule可与任何特定的商店实现分离，从而允许您选择或切换所需的实现。

Mule在以下方面使用对象存储：

* 服务。对于 link:/mule-user-guide/v/3.2/configuring-queues[SEDA队列]，入站和服务组件之间。
*  VM传输。仅限于单向端点。使用单向端点时，消息通过队列传递到相应的入站端点。
* 需要持久化的各种过滤器，路由器和其他消息处理器。
*  *Mule 3.2*流程。通过排队异步处理策略。有关排队异步处理策略的更多信息，请参阅 link:/mule-user-guide/v/3.2/flow-processing-strategies[流程处理策略]。
*  *Mule 3.2*群集。 Mule使用群集的对象存储。群集对象存储位于共享内存网格中

== 对象商店可用于Mule

Mule提供了两种类型的默认对象存储：

* 默认的内存中存储。这是默认存储所有非永久性数据的地方。 Mule在内存中创建一个默认的内存中存储。但是，对于群集，Mule会在共享内存网格中创建默认的内存中存储。

* 默认持久存储。这是所有持久数据默认存储的地方。 Mule在文件系统中创建一个默认持久性存储。但是，对于群集，Mule会在共享内存网格中创建默认持久性存储。

在大多数情况下，默认的对象存储将满足您的需求。在这些情况下，不需要配置。但是，您可以为消息持久性指定队列存储（队列存储是队列的对象存储）。对于服务的SEDA队列，您可以通过在<queue-profile>元素中指定适当的子元素来指定要使用的队列存储。下表中列出了可用的队列存储及其各自的元素：

[%header,cols="10,80,10"]
|===
|队列商店 |描述 |元素
| queue-store  |引用全局队列存储 | <queue-store>
|默认的内存中队列商店 |默认的内存商店。 | <default-in-memory-queue-store>
|默认的persistent-queue-store  |基于文件的商店。对于群集，它是默认的内存存储。 | <default-persistent-queue-store>
|简单内存队列存储 |始终是内存存储。 | <simple-in-memory queue-store>
|文件队列商店 |始终是基于文件的商店。 | <file-queue-store>
|===

例如，您可以按如下方式为服务的SEDA队列请求一个基于文件的存储：

[source, xml, linenums]
----
<service name="serviceExplicitObjectStore">    ...    <queue-profile>        <file-queue-store/>    </queue-profile></service>
----

您还可以通过在`<queue-profile>`元素中指定`<custom-queue-store>`子元素来显式配置用于服务的SEDA队列的自定义对象库，如以下示例所示：

[source, xml, linenums]
----
<service name="serviceCustomObjectStore">    ...    <queue-profile>        <custom-queue-store class="..."/>    </queue-profile></service>
----

您可以为流指定队列存储，即流是否使用排队异步处理策略。您可以在流程的全局处理策略中的适当子元素中指定队列存储。这是一个例子：

[source, xml, linenums]
----
<queued-asynchronous-processing-strategy name="customStoreQueueStrategy">    <file-queue-store/></queued-asynchronous-processing-strategy><flow name="asynchronousFlow" processingStrategy="customStoreQueueStrategy">  <vm:inbound-endpoint path="input" exchange-pattern="one-way"/>  <vm:outbound-endpoint path="output" exchange-pattern="one-way"/></flow>
----
