= 对象作用域

== 确定Mule容器如何处理对象

范围（也称为基数）描述了如何在Mule容器中创建和管理对象。

== 三个范围

Mule中定义了三个对象作用域：

* 单例 - 只为所有请求创建一个对象
* 原型 - 为每个请求或每次从注册中心请求对象时创建一个新对象
* 池化 - 仅适用于组件对象，但这些存储在池中，以确保一次只有一个线程将访问对象。

关于对象范围的== 规则

Singleton对象必须是线程安全的，因为多个线程将访问同一个对象。因此，写入时需要保护任何成员变量，以确保一次只有一个线程更改数据。

给定原型范围的对象是为对象上的每个请求创建的，因此对象不需要是线程安全的，因为只有一个线程访问它。但是，该对象必须是无状态的，因为任何成员变量只会在请求的整个生命周期中存在。

池中的对象是线程安全的，因为Mule会保证一次只有一个线程访问该对象。由于会创建多个实例，因此联合对象不能轻松维护对象本身的状态。汇集原型的优势在于，创建对象并为其收到的每条消息创建新实例都会很昂贵，这会降低应用程序的速度。

通过XML配置Mule时使用Spring将XML转换为定义Mule实例如何运行的对象。 Mule中的所有顶级对象都是单件，包括服务，模型，连接器，端点，代理，安全管理器，事务管理器。具有原型范围的唯一对象是Transformer（这是因为变换器可以在不同的上下文中使用，并可能在不同的线程中同时使用）。

组件（您的服务使用的POJO对象）可以是单例，原型或合并。

== 示例

=== 汇集

[source, xml, linenums]
----
<pooled-component class="com.foo.Bar"/>
----

=== 的Singleton

[source, xml, linenums]
----
<component >     <singleton-object class="com.foo.Bar"/></component>
----

=== 原型

[source, xml, linenums]
----
<component >     <prototype-object class="com.foo.Bar"></component><!—or short form --><component class="com.foo.Bar"/>
----

===  Spring范围

你也可以引用Spring作为一个组件，其中对象的范围由Spring定义 - 

[source, xml, linenums]
----
<component >     <spring-object ref="myBean"></component>
----
