= 从管理控制台运行示例

您可以从Mule ESB管理控制台运行示例应用程序。以下是查找示例的一般说明，将它们部署到Mule ESB服务器并运行它们。

== 找到示例

Mule服务器软件包中包含的示例应用程序位于examples文件夹中的Mule安装文件夹下。打开示例文件夹，您应该看到一组文件夹，如hello，loanbroker-simple，stockquote等。

例如，假设您将服务器软件包安装在mule-esb文件夹中。打开此安装文件夹，然后打开示例文件夹。你应该看到一组文件夹。

示例中的每个文件夹都包含特定示例应用程序所需的所有文件，以及一个包含特定指令的README.txt文件以运行该示例。

要运行示例，请将包含所有应用程序组件的存档（.zip）文件部署到服务器。除非在示例的自述文件中另有说明，否则这些示例已构建好并可以部署和运行。对于hello示例，这是mule-example-hello-3.2.0-SNAPSHOT.zip文件。

请注意，其他示例文件夹包含与hello应用程序文件夹相似的一组文件。

== 将示例部署到服务器

以下是如何部署示例。

单击控制台窗口中的“应用程序”选项卡以打开“所有部署”窗口。

您可以添加已经加载到服务器存储库的应用程序，也可以上传新的应用程序。

单击“从存储库添加”按钮，然后选择应用程序，从存储库部署应用程序。

如果您正在上传新示例，请为部署创建一个名称，以便以后可以识别它。

* 在“部署名称”字段中，输入名称，例如HelloExample。 （请参见下图。请注意，上传应用程序按钮以及用于选择部署服务器的下拉箭头。）
* 点击上传新应用程序按钮。
* 打开一个对话框，通过它可以浏览到应用程序文件。
* 使用浏览对话框找到安装Mule服务器和控制台的文件夹，然后浏览到\ examples \ hello文件夹。选择hello应用程序jar文件：mule-example-hello-3.2.0-SNAPSHOT.zip。
* 展开对话框下半部分的“高级选项”以进一步指定工作区文件夹，应用程序的名称（如您希望它在服务器上部署时显示在控制台中）以及应用程序版本号。在本例中，工作区文件夹是/ Applications，部署名称是helloApp，版本号更改为3.2-1。
* 点击添加完成上传。

接下来，指定您希望部署应用程序的一个或多个服务器。

使用服务器下方的下拉列表选择要部署的服务器。该列表包括已注册的服务器和服务器组。

请注意，您可以一次部署多个应用程序，也可以将这些应用程序部署到一台或多台服务器。单击应用程序右侧的红色X以从部署中删除该应用程序。单击服务器名称右侧的红色X将该服务器从部署列表中删除。

单击部署将hello应用程序部署到服务器。

您应该在屏幕的上半部分看到一条状态消息，指出正在进行部署。完成后，状态字段将指示部署是否成功。

如果发生错误，请单击重新部署按钮以再次尝试。

当您单击“部署”按钮时，应用程序也会保存在服务器存储库中。

任何时候，您都可以单击Repository节点并查看有关此部署的信息。您还可以单击“部署”节点并返回到“所有部署”屏幕以查看所有部署的列表。从所有部署中，您可以选择特定的部署，然后编辑，取消部署，重新部署或删除它们。

== 运行已部署的应用程序

根据每个示例的说明，通过另一个浏览器窗口或选项卡运行部署的Hello应用程序。
