= 脚本模块参考

[ <<Component>> ] [ <<Script>> ] [ <<Script>> ] [ <<Script>> ] [ <<Script>> ] [ <<Script Context Bindings>> ] [ <<Transformer>> ] [ <<Groovy refreshable>> ] [ <<Lang>> ]

脚本模块为在Mule中使用脚本语言提供了便利。任何支持 http://www.jcp.org/en/jsr/detail?id=223[JSR-223]的脚本语言都可以在Mule中使用。脚本可以用作服务组件或变换器的实现。此外，脚本可用于表达式评估，这意味着可以使用当前消息的脚本评估来控制消息路由。你甚至可以从脚本配置Mule实例。

== 元器件

定义由符合JSR-223的脚本引擎（如Groovy，JavaScript或Ruby）支持的脚本组件。脚本允许您直接将脚本嵌入到XML配置中，或者使用Spring的动态语言支持引用脚本：http://static.springframework.org/spring/docs/2.5.x/reference/dynamic-language.html。

<component...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| script-ref  |字符串 |否 |   |对脚本对象bean的引用，即`<script:script ...>`定义。
|===

<component...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|脚本 | 0..1  |脚本由符合JSR-223的脚本引擎执行，如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell。
| java-interface-binding  | 0 .. *  |绑定将Mule端点与注入的Java接口相关联（这就像使用Spring注入bean一样，而不是调用一个消息发送给端点的bean上的方法）。脚本绑定仅适用于基于Java的脚本语言。目前，由于有这么多的脚本语言，因此语言不支持Java绑定，所以没有验证。
|===

以下示例演示如何使用内嵌脚本配置Groovy脚本组件：

[source, xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:script="http://www.mulesoft.org/schema/mule/scripting"
      xmlns:vm="http://www.mulesoft.org/schema/mule/vm"
      xsi:schemaLocation="
       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.2/mule.xsd
       http://www.mulesoft.org/schema/mule/scripting
       http://www.mulesoft.org/schema/mule/scripting/3.2/mule-scripting.xsd
       http://www.mulesoft.org/schema/mule/vm http://www.mulesoft.org/schema/mule/vm/3.2/mule-vm.xsd">

    <vm:connector name="vmConnector"/>

    <script:script name="myScript" engine="groovy">
        return "$payload Received"
    </script:script>

    <model>
        <service name="inlineScript">
            <inbound>
                <inbound-endpoint address="vm://in1"/>
            </inbound>
            <script:component>
                <script:script engine="groovy">
                    return "$payload Received"
                </script:script>
            </script:component>
            <outbound>
                <pass-through-router>
                    <outbound-endpoint address="vm://out1"/>
                </pass-through-router>
            </outbound>
        </service>
...
----

以下示例演示如何使用绑定编排消息流。该示例调用两个不同的服务并将结果传递给出站路由器。

[source, xml, linenums]
----
<service name="scriptWithBindings">
            <inbound>
                <inbound-endpoint ref="client_request"/>
            </inbound>
            <script:component>
                <script:script engine="groovy">
                    msg = CalloutService.doSomething(payload)
                    return CalloutService.doSomethingElse(msg)
                </script:script>
                <script:java-interface-binding interface="org.mule.components.script.CalloutService" method="doSomething">
                    <outbound-endpoint ref="callout_1" synchronous="true"/>
                </script:java-interface-binding>
                <script:java-interface-binding interface="org.mule.components.script.CalloutService" method="doSomethingElse">
                    <outbound-endpoint ref="callout_2" synchronous="true"/>
                </script:java-interface-binding>
            </script:component>
            <outbound>
                <pass-through-router>
                    <outbound-endpoint ref="client_response"/>
                </pass-through-router>
            </outbound>
        </service>

        <service name="Callout1">
            <inbound>
                <inbound-endpoint ref="callout_1"/>
            </inbound>
            <test:component appendString=" Received by #[mule:context.serviceName]"/>
        </service>

        <service name="Callout2">
            <inbound>
                <inbound-endpoint ref="callout_2"/>
            </inbound>
            <test:component appendString=" Received by #[mule:context.serviceName]"/>
        </service>
----

== 脚本

一个由JSR-223兼容脚本引擎（如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell）执行的脚本。

<script...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|姓名 |字符串 |否 |   |用于标识此脚本对象的名称。当你想从一个组件或变换器引用这个脚本对象时使用它。
|引擎 |字符串 |否 |   |正在使用的脚本引擎的名称。所有支持JSR-223的脚本语言都有一个脚本引擎名称，例如groovy，ruby，python等。如果未设置此值，但配置了脚本文件，则Mule将尝试根据脚本加载正确的脚本引擎文件的扩展名。
|文件 |字符串 |否 |   |为此对象加载的脚本文件。该文件可以位于类路径或本地文件系统上。
|===

<script...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
| text  | 0..1  |用于在XML中嵌入脚本代码。这对简单的脚本来说很有用，因为你只是在嘲笑一个快速应用程序。
|===

== 脚本

表示可用作服务或变换器组件的脚本。脚本文本可以从脚本文件中提取，也可以嵌入到此元素中。脚本可以通过任何符合JSR-223的脚本引擎执行，例如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell。

<script...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|姓名 |字符串 |否 |   |用于标识此脚本对象的名称。当你想从一个组件或变换器引用这个脚本对象时使用它。
|引擎 |字符串 |否 |   |正在使用的脚本引擎的名称。所有支持JSR-223的脚本语言都有一个脚本引擎名称，例如groovy，ruby，python等。如果未设置此值，但配置了脚本文件，则Mule将尝试根据脚本加载正确的脚本引擎文件的扩展名。
|文件 |字符串 |否 |   |为此对象加载的脚本文件。该文件可以位于类路径或本地文件系统上。
|===

<script...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
| text  | 0..1  |用于在XML中嵌入脚本代码。这对简单的脚本来说很有用，因为你只是在嘲笑一个快速应用程序。
|===

== 脚本

一个由JSR-223兼容脚本引擎（如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell）执行的脚本。

<script...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|姓名 |字符串 |否 |   |用于标识此脚本对象的名称。当你想从一个组件或变换器引用这个脚本对象时使用它。
|引擎 |字符串 |否 |   |正在使用的脚本引擎的名称。所有支持JSR-223的脚本语言都有一个脚本引擎名称，例如groovy，ruby，python等。如果未设置此值，但配置了脚本文件，则Mule将尝试根据脚本加载正确的脚本引擎文件的扩展名。
|文件 |字符串 |否 |   |为此对象加载的脚本文件。该文件可以位于类路径或本地文件系统上。
|===

<script...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
| text  | 0..1  |用于在XML中嵌入脚本代码。这对简单的脚本来说很有用，因为你只是在嘲笑一个快速应用程序。
|===

== 脚本

一个由JSR-223兼容脚本引擎（如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell）执行的脚本。

<script...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|姓名 |字符串 |否 |   |用于标识此脚本对象的名称。当你想从一个组件或变换器引用这个脚本对象时使用它。
|引擎 |字符串 |否 |   |正在使用的脚本引擎的名称。所有支持JSR-223的脚本语言都有一个脚本引擎名称，例如groovy，ruby，python等。如果未设置此值，但配置了脚本文件，则Mule将尝试根据脚本加载正确的脚本引擎文件的扩展名。
|文件 |字符串 |否 |   |为此对象加载的脚本文件。该文件可以位于类路径或本地文件系统上。
|===

<script...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
| text  | 0..1  |用于在XML中嵌入脚本代码。这对简单的脚本来说很有用，因为你只是在嘲笑一个快速应用程序。
|===

== 脚本上下文绑定

在Mule中运行时，脚本在脚本上下文中有许多可用的对象：

[%header,cols="2*"]
|===
| {名称{1}}说明
| `log`  |可用于写入Mule日志文件的记录器。
| `muleContext`  |对MuleContext对象的引用。
| `registry`  | Mule注册表的简便快捷方式（否则可通过`muleContext.registry`获取）。
| `eventContext`  |对事件上下文的引用。这使您可以从脚本程序中派发事件。
| `message`  |当前消息。
| `originalPayload`  |在进行任何转换之前，当前消息的有效载荷。
| `payload`  |如果服务上配置了变换器，则转换当前消息的有效载荷。否则，这与`originalPayload`的值相同。
| `src`  |与`payload`相同，保持向后兼容。
| `service`  |对当前服务对象的引用。
| `id`  |当前消息ID。
| `result` a |
可以写入脚本结果的占位符对象。通常最好从脚本中返回一个值，除非脚本方法没有返回值。

[WARNING]
 您的脚本需要返回null，您必须设置result = null，而不是简单地返回null
|消息属性 |任何消息属性都可以用作脚本的变量。
|===

== 变压器

运行脚本以对当前消息执行转换。

<transformer...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|===

<transformer...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|脚本 | 0..1  |脚本由符合JSR-223的脚本引擎执行，如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell。
|===

以Groovy为例，以下变换器配置将逗号分隔的一串值转换为`java.util.List`。

[source, xml, linenums]
----
<script:transformer name="stringReplaceWithParams">
        <script:script engine="groovy">
            <property key="oldStr" value="l"/>
            <property key="newStr" value="x"/>
            <script:text>
                return payload.toString().replaceAll("$oldStr", "$newStr")
            </script:text>
        </script:script>
    </script:transformer>
----

==  Groovy可刷新

组件对象的包装器，允许在运行时重新加载底层对象。这使得可以在不重新启动的情况下热部署新的组件逻辑。

<groovy-refreshable...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|名称 |字符串 |是 |   |此可刷新groovy bean包装的名称。
| refreshableBean-ref  |字符串 |否 |   |对此组件使用的`groovy.lang.Groovy`对象的引用。
| methodName  |字符串 |否 |   |接收到对象的消息时调用的入口点方法。
|===

<groovy-refreshable...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|===

== 郎

该元素允许嵌入http://www.springframework.org/schema/lang名称空间。在这个元素中，开发人员可以包含Spring `lang`名称空间。

<lang...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|===

<lang...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|===
