内存（VM）传输参考中的= 

== 介绍

In Memory传输可用于Mule link:/mule-user-guide/v/3.2/using-flows-for-service-orchestration[流动]和/或 link:/mule-user-guide/v/3.2/using-mule-services[服务]之间的JVM内部通信。此传输默认使用内存队列，但可以选择配置为使用持久队列。

== 命名空间和语法

XML名称空间：

[source, xml]
----
xmlns:vm "http://www.mulesoft.org/schema/mule/vm"
----

XML模式位置：

[source, code, linenums]
----
http://www.mulesoft.org/schema/mule/vm
http://www.mulesoft.org/schema/mule/vm/3.2/mule-vm.xsd
----

连接器语法：

具有持久队列的VM：

[source, xml, linenums]
----
<vm:connector name="persistent">
    <vm:queue-profile persistent="true" maxOutstandingMessages="500"/>
</vm:connector>
----

具有内存中队列的VM（或者没有队列，用于请求响应端点）：

[source, xml]
----
<vm:connector name="memory" />
----

端点语法：

. 前缀端点：
+

[source, xml]
----
<vm:outbound-endpoint path="out"/>
----

. 没有前缀的URI：
+

[source, xml]
----
<outbound-endpoint address="vm://out">
----

== 变压器

VM传输没有特定的转换器。

== 注意事项

VM传输通常用于实现由多个服务组成的复杂集成。 Mule 3的改进在很多情况下避免了对VM的需求。 +
由于在大多数Mule元素中引入了MessageProcessor，因此可以在不将服务捆绑在一起的情况下完成更复杂的集成。您可以使用 http://www.mulesoft.org/docs/site/3.3.0/schemadocs/schemas/mule_xsd/elements/flow-ref.html[流量参考]直接引用另一个流程，而不需要中间的传输。

VM在某些情况下仍然有用。例如，假设解决方案的大多数部分都是本地的，但有些需要进行解耦以进行测试，或者因为需要将某些部分设置为远程。

[WARNING]
*WARNING* +
Mule实例中的每个应用程序都有自己的唯一一组VM端点。因此，VM传输不能用于不同Mule应用程序之间的通信。

== 特点

内存（VM）传输具有两种操作模式：一种用于_request-response_，另一种用于_one-way_端点。

*_request-response:_*

使用_request-response_端点时，消息直接从出站虚拟机端点传递到正在侦听相同路径的入站虚拟机端点。此交货被阻止并发生在同一个线程中。如果在监听此路径的相同Mule应用程序中没有入站_request-response_ vm端点，则从出站端点分派消息失败。

*_one-way:_*

使用_one-way_端点时，消息通过队列传递到相应的入站端点。这种交付是非阻塞的。如果在同一个Mule应用程序中侦听此路径中没有入站_one-way_端点，则尽管分派消息成功，但消息仍保留在队列中。默认情况下，此队列在内存中，但也可以配置使用文件系统作为其持久性机制的持久队列。

[WARNING]
*NOTE* +
您不能从请求 - 响应端点向单向端点发送消息或以其他方式发送消息。这会导致发送失败，或者邮件停留在队列中，永远不会到达预期的目的地。

== 用法

要使用VM端点：

. 将MULE VM名称空间添加到您的配置中：
* 使用xmlns定义VM前缀：vm = "http://www.mulesoft.org/schema/mule/vm"
* 使用http://www.mulesoft.org/schema/mule/vm定义架构位置http://www.mulesoft.org/schema/mule/vm/3.2/mule-vm.xsd
. （可选）为VM端点定义一个或多个连接器。
* 创建一个VM连接器：
+
[source, xml]
----
<vm:connector name="vmConnector"/>
----

+
如果没有创建，则所有VM端点使用默认连接器。
. 创建VM端点。
* 邮件在入站端点上收到。
* 邮件被发送到出站端点。
* 这两种端点都由一个路径名来标识。

=== 命名空间声明

要使用VM传输，您必须在Mule配置文件的标头中声明VM名称空间。例如：

*VM Transport Namespace Declaration*

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:vm="http://www.mulesoft.org/schema/mule/vm"
      xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.2/mule.xsd
               http://www.mulesoft.org/schema/mule/vm http://www.mulesoft.org/schema/mule/vm/3.2/mule-vm.xsd">
----

=== 连接器配置

VM连接器的配置是可选的。配置连接器允许您配置允许使用持久性的 http://www.mulesoft.org/docs/site/3.3.0/schemadocs/schemas/mule_xsd/elements/queue-profile.html[队列配置文件]。您还可以设置最大队列大小。

=== 端点

link:/mule-user-guide/v/3.2/configuring-endpoints[端点]配置为与所有传输一样。

VM传输特定的端点使用VM名称空间进行配置并使用_path_属性。例如：

[source, xml]
----
<vm:outbound-endpoint path="out" exchange-pattern="one-way"/>
----

如果您需要从 http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/module/client/MuleClient.html[Mule客户端]调用VM端点，请使用 link:/mule-user-guide/v/3.2/mule-endpoint-uris[端点URI]。 VM的端点URI格式如下所示：

[source]
----
vm://path
----

=== 使用事务

_one-way_ VM队列可以参与分布式 link:/mule-user-guide/v/3.2/transaction-management[XA交易]。要使VM端点处于事务处理状态，请使用类似于以下的配置：

[source, xml, linenums]
----
<flow>
  <vm:inbound-endpoint address="vm://dispatchInQueue">
    <vm:transaction action="BEGIN_OR_JOIN"/>
  </vm:inbound-endpoint>
</flow>
----

使用XA需要您将事务管理器添加到您的配置中。有关更多信息，请参阅 link:/mule-user-guide/v/3.2/transaction-management[交易管理]。

=== 事务性入站VM队列

入站虚拟机端点支持完全事务流。例如，以下配置会创建一个VM队列（因为入站端点是单向的），并且同步和事务处理从该队列读取的消息：

[source, xml, linenums]
----
<flow name="transactionalVM">
    <vm:inbound-endpoint path="orders" exchange-pattern="one-way">
        <vm:transaction action="ALWAYS_BEGIN"/>
    </vm:inbound-endpoint>
    <component class="com/mycomany.ProcessOrder"/>
</flow>
----

XA交易也受到支持：

[source, xml, linenums]
----
<flow name="transactionalVM">
    <vm:inbound-endpoint path="orders" exchange-pattern="one-way">
        <xa-transaction action="ALWAYS_BEGIN"/>
    </vm:inbound-endpoint>
    <component class="com/mycomany.ProcessOrder"/>
    <jms:outbound-endpoint ref="processedOrders">
        <xa-transaction action="ALWAYS_JOIN"/>
    </jms:outbound-endpoint>
</flow>
----

== 示例配置

*Example usage of VM endpoints*

[source, xml, linenums]
----
<vm:connector name="vmConnector"> ❶

<vm:connector name="persistentVmConnector" queueTimeout="1000"> ❷
   <queue-profile maxOutstandingMessages="100" persistent="true"/> ❸
</vm:connector>

<flow>
    <vm:inbound-endpoint path="in" exchange-pattern="request-response" connector-ref="vmConnector" /> ❹
    <component class="org.mule.CompoenntClass"/>
    <vm:inbound-endpoint path="in" connector-ref="persistentVmConnector" /> ❺
</flow>
----

第一个连接器❶使用默认连接器配置。 +
第二个连接器❷配置队列配置文件和queueTimeout。

该流程使用两个VM端点，入站端点❹使用_request-response_交换模式。出站端点❺使用_one-way_端点以及配置了持久性的备用连接器。

== 配置参考

=== 元素列表

==  VM传输

VM传输用于Mule管理的组件之间的VM内部通信。传输提供了配置VM瞬态或持久队列的选项。

== 连接器

<connector...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| queueTimeout  | positiveInteger  |否 |   |用于异步端点的队列的超时设置
|===

<connector...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
| queueProfile  | {0..1 {3}}弃用。改用"<queue-profile>"。
| queue-profile  | 0..1  |配置此连接器队列的属性（请参阅 link:/mule-user-guide/v/3.2/configuring-queues[配置队列]）。
|===

== 入站端点

此连接器接收来自传输的消息的端点。

<inbound-endpoint...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|路径 |字符串 |否 |   |队列路径，例如dispatchInQueue来创建地址vm：// dispatchInQueue。
|===

无<inbound-endpoint...>的子元素



== 出站端点

此连接器发送消息的端点。

<outbound-endpoint...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|路径 |字符串 |否 |   |队列路径，例如dispatchInQueue来创建地址vm：// dispatchInQueue。
|===

无<outbound-endpoint...>的子元素



== 端点

通过引用端点名称，可用于在配置中的其他位置构建入站或出站端点的端点"template"。

<endpoint...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|路径 |字符串 |否 |   |队列路径，例如dispatchInQueue来创建地址vm：// dispatchInQueue。
|===

无<endpoint...>的子元素



== 事务

事务元素配置一个事务。事务处理允许将一系列操作分组在一起，以便在出现故障时将它们回滚。有关更多信息，请参阅 link:/mule-user-guide/v/3.2/transaction-management[交易管理]。

无<transaction...>的子元素


== 架构

VM模块的模式显示 http://www.mulesoft.org/schema/mule/vm/3.2/mule-vm.xsd[这里]。其结构是 http://www.mulesoft.org/docs/site/3.3.0/schemadocs/schemas/mule-vm_xsd/schema-overview.html[这里]。

==  Javadoc API参考

这个模块的Javadoc可以在这里找到： http://www.mulesoft.org/docs/site/current/apidocs/org/mule/transport/vm/package-summary.html[VM]

== 的Maven

内存传输可以包含以下依赖项：

[source, xml, linenums]
----
<dependency>
  <groupId>org.mule.transports</groupId>
  <artifactId>mule-transport-vm</artifactId>
</dependency>
----

== 最佳实践

确保入站请求 - 响应端点与出站请求 - 响应端点配对，并且入站单向端点与出站单向端点配对。
