=  WebSphere MQ示例
:keywords: websphere mq, example

*_Enterprise Edition_*

WebSphere MQ示例演示如何使用Mule的 link:/mule-user-guide/v/3.2/mule-wmq-transport-reference[传输WebSphere MQ]向WebSphere MQ发送和接收事务消息。这个例子在Mule企业版中可用。

=== 先决条件

在运行示例之前，请确保以下内容：

* 安装Mule企业3.1或更高版本。
* 安装WebSphere MQ 6或7。
* 您可以使用WebSphere MQ客户端JAR。

=== 安装示例

. 将您的WebSphere MQ客户端JAR复制到您的`$MULE_HOME/lib/user`目录。
. 确保您的WebSphere MQ安装具有名为"in"和+的队列
"out"创建。
. 将示例的zip文件复制到$ MULE_HOME / apps目录中。
. 启动Mule并等待它安装示例。您可能会看到一些例外情况，因为WMQ尚未配置。我们将在下一步中这样做。
. 现在您需要在`$MULE_HOME/apps/mule-example-wmq/classes/wmq.properties`中编辑以下属性以反映您的WebSphere MQ安装：
+
[source,java, linenums]
----
wmq.host=wmq.port=wmq.queue.manager=wmq.username=wmq.password=
----

. 重新启动Mule。

=== 运行示例

在这部分示例中，我们将演示基本用法，发送短信并使用Mule从WMQ中检索它们。

.  mule启动后，请在浏览器中打开以下网址：`+http://localhost:8086/services/wmqExample+`。
. 系统会提示您输入文本以向WebSphere MQ发送消息。您的输入将通过AJAX / WMQ传输到"in"队列，您将收到确认消息已提交。尝试输入一些文字并点击"Send"。
. 发送到"in"队列的消息将被处理，并在通过"out"队列和WMQ / AJAX将其发回给您之前引入有意的15秒延迟。收到邮件时将收到通知，其内容将添加到表格中。
. 开始在文本框中输入几条消息，然后点击"Send"，通过AJAX / WMQ将它们提交给Mule。经过15秒的故意延迟后，这些信息将被发回给您。
