= 编写示例

本文档将介绍使用新格式创建示例的过程。

== 创建代码

我们使用Mule Studio创建核心概念示例，代码存储在GitHub中：

https://github.com/mulesoft/core-concept-examples

我无法找到与Mule Studio和GitHub一起工作的集成方式，因此我采取的方法如下：

. 将GitHub存储库检入本地目录，即_ / projects / github_。您不能在同一位置使用MuleStudio（Eclipse）工作区。
. 在Mule Studio中，创建一个新的工作空间来处理这些示例。转到_File  - >切换工作区 - >其他_
. 您可以将现有的示例项目导入到此工作区中，转到_File  - > Import  - > Mule Project_。
. 要创建一个新示例，请转到_File  - > New  - > Mule Project_
. 将项目的名称设置为正在创建的示例的名称，将所有字母缩写为小写，并使用短划线“ - ”而不是空格。点击下一步_
. 使流程名称与项目名称相同，然后单击_下一步（不要单击完成）
通过取消选中“使用默认位置”，然后在与GitHub存储库的本地副本相同的目录中创建项目，例如_ / projects / github / core-concept-examples / new-例_

. 点击_Finish_
. 在MuleStudio中创建示例。当你准备好提交一些东西给GitHub时，打开一个命令shell
. 进入GitHub本地仓库目录并运行'git add new-example'
. 然后运行'git commit -a -m "initial commit"
. 您可以使用'git commit'命令继续进行本地更改并提交到本地存储库
. 代码完成后，执行'git push'将新示例推送到远程存储库

== 创建示例页面

要创建一个新的示例页面：

. 在页面的右下角，选择_编辑 - >新建 - > Page_
. 为页面提供一个描述性名称，该名称将在导航中使用
. 新页面屏幕顶部有一个名为"Select a page template to start from"的链接，请点击此链接。
. 选择"Example Page"
. 您可以开始在模板上填写内容，但我发现点击底部的"Insert Variables"并直接开始编辑页面会更加轻松。

=== 示例头

每个示例都有一个需要一些信息的标题部分。格式化包含在汇合宏中，其格式如下所示：

----
{example-header:mf-name=introduction-to-endpoints|timing=15|image=echo-flow-100.png|screencast-link=ScreenCasts#introduction to endpoints}
----

您只需添加以下字段：

. 图像 - 示例的左手图像。此图片不应超过100x170像素。如果这个例子是一个大流量，只显示它的一部分。
.  mf-name  - 弃用。
. 计时 - 以分钟为单位运行整个示例的时间
.  ion-link  - 在iON上运行的示例的URL，这是可选的
.  screencast-link  - 这是可选的。如果您创建截屏视频，则应将视频上传到YouTube（请联系Ross以获取要上传的帐户）并将其嵌入到页面中。在屏幕录像上方添加一个{anchor}宏，用于直接链接到该屏幕录像。

=== 内容

. 介绍应该从用户的角度而不是Mule的角度来编写。最多只能引入一个或两个概念。
. 您将学习的部分应该是2-4个总结关键学习要点的要点
. 先决条件 - 如果此示例基于先前的基础构建，则oyu需要链接到前一个（或基础）示例。如果不是，您可以使用{include：Prerequisites}来嵌入页面。
. 构建示例 - 您可以在其中包含逐步指导用户需要自己创建示例的步骤
. 运行示例 - 本节详细介绍如何运行示例，通常很短，不需要为每个步骤添加屏幕截图，除非当前示例发生了某些变化（即在iON或Maven上运行）
. 刚刚发生的事情部分是对用户做出的突出显示所执行操作中未明确的任何内容的回顾（即向流中添加入站端点创建HTTP服务器或解释实际获得的hello组件的方式调用）。
. 参考资料 - 应包含来自帖子其他部分的内容的所有链接以及可能对读者有用的任何其他链接


=== 接下来的步骤

在可能的情况下，我们的示例应该相互构建，为用户创造一条路径。我创建了一个宏，用于在底部生成导航按钮以在路径中移动。你需要传递3页，上一页，索引和下一页：

----
h2. Next Steps{flow-nav:previous=Foo|index=Home|next=Adding Message Processors to a Flow}
----

这些是示例空间中其他示例的页面名称。如果没有"previous"（因为您处于路径的开始处）或没有"next"，请将这些参数保留。 "index"参数指向示例跟踪的着陆页。

=== 屏幕截图

应该为每一个新步骤添加屏幕截图。如果您正在构建示例 - 例如 link:/mule-user-guide/v/3.2/adding-business-logic-to-a-flow[向业务流添加业务逻辑]这样的核心概念示例 - 请不要为先前已涵盖的步骤添加屏幕截图，除非详细信息以某种方式更改。

要添加屏幕截图，您需要将其封装在一个div中以使其具有一致的格式：

----
{div:class=screenshot}!studio-file-new-project.png!{div}
----

在您编写页面时，您不会在页面上附加屏幕截图。我发现首先编写内容并留下图像的占位符，然后将图像附加到页面并编辑任何占位符以引用正确的图像更容易。

截图和任何其他图像都附加到页面上。要做到这一点，请进入右下角的编辑菜单并选择"Attachments"。

使用附件时，我发现在我正在编辑的示例页面的单独窗口中打开附件页面会更容易，以便我可以轻松剪切和粘贴文件名并上传我可能错过的所有屏幕截图。


=== 页面组织

确保您的示例年龄是正确父级的子页面，即示例组的着陆页。如果你需要移动页面的方式做到这一点，是去右下角的菜单，选择_View  - >其他页面 - > Site Map_。这会显示一棵树，您可以在树中拖放页面并设置页面的顺序。
