= 选择SDK版本
:keywords: mule, sdk, create, new, project, getting, started, version

// TODO：这是1.1，不是1.0

开发人员倾向于使用给定产品的最新版本。 Mule SDK不应该如此。选择用于扩展Mule模块的SDK版本时，您应该：

* 确定您需要的功能。
* 选择包含您所需功能的最低版本。

接下来的部分解释了原因。

== 扩展API

当您使用SDK进行开发时，您确实在使用API​​，即扩展API。无论何时使用任何SDK注释注释字段或方法，或者当您实现任何接口时，都只需使用此扩展API的一部分。您发货的模块只包含您的代码。它不包含任何将模块与Mule运行时内部桥接的代码。由于`Extensions API`，运行时间会弥合这种差距。

== 最小Mule版本

每个版本的Mule Runtime都支持`Extensions API`的一个特定版本，以及支持它的所有版本

例如，假设两者都是正确的：

*  Mule `4.1`附带SDK版本`1.1`。
*  Mule `4.2`附带SDK版本`1.2`。

Mule `4.2`将完全支持使用SDK版本`1.2`，`1.1`和`1.0`开发的任何模块。如果Mule `4.3`引入了SDK 1.3，则它也将支持`1.2`和`1.1`，等等。

这个概念适用于两种方式：

* 任何Mule Runtime版本都将支持之前发布的所有SDK版本，因此在Mule `4.1`中运行的模块应该可以在任何Mule 4.x（`x >= 1`）中运行。
* 如果一个模块是使用SDK `1.2`构建的，那么它只能在支持该SDK版本的运行时中使用。在这个例子中，这个模块在Mule `4.1`中不起作用。

== 确定您的必需功能

您不应该瞄准使用最新的SDK版本，因为您的模块只能与最新的Mule Runtime兼容。相反，您应该使用包含您需要的所有功能的最旧版本，例如：

* 如果您要创建仅需要连接性和基本DataSense的简单连接器，则应使用版本`1.0`。
* 如果您还需要使用`PollingSource`接口，请使用SDK 1.1，该SDK引入了对`PollingSource`的支持。只有支持该功能的运行时才能运行你的模块。

对于任何新的SDK功能，文档都包含其介绍的版本。如果没有指定特定的版本，该功能自第一版以来一直存在。

[TIP]
建议的方法是使用版本`1.0.0`启动您的所有项目，并在您面对特定功能需求时升级版本。

遵循这些指导方针将使您的模块与更多的Mule Runtime版本兼容，以便更多人能够使用您的模块。如果您确实需要新版本的功能，那么您没有理由使用新版本。


== 如果SDK中存在Bug，该怎么办？

`Extensions API`是一个API，它的实现驻留在Mule Runtime中，因此大多数与SDK相关的错误修复将在Mule Runtime的修补程序版本和服务包中发布，而不是通过新的SDK版本。

在某些情况下，如果问题出现在API定义中，SDK的修补程序版本将可用（例如，`1.1.2`）。您应该始终选择更高的错误修复版本。例如，在`1.0.0`和`1.0.4`之间，您应该选择`1.0.4`。

请注意，上面提到的版本号代表的示例不一定代表任何现有版本或补丁。

== 更改版本

SDK `version`在`parent`元素内的模块项目的`pom.xml`文件中指定。

[source, xml, linenums]
----
<parent>
  <groupId>org.mule.extensions</groupId>
  <artifactId>mule-modules-parent</artifactId>
  <version>1.0.0</version>
</parent>
----

要更改为其他版本，只需更改父版。
