= 外部库
:keywords: mule, SDK, library, dependency, external, jar, maven

连接器和模块有时依赖于不能使用的外部库
由于授权，版本控制，自定义库等，将其封装在连接器内部。

数据库连接器是一个例子，您可以使用相同的基本代码来处理多个不同的驱动程序和同一驱动程序的多个版本。此问题的解决方案是要求数据库连接器的用户标识要用于其所要连接的数据库的JDBC驱动程序。

== 用法

声明连接器或模块需要外部库才能工作
在Mule应用中，您需要注释您的`@Extension`，<<configs#, Configuration>>，
或带有`@ExternalLib`注释的<<connections#, ConnectionProvider>>类
并提供有助于Mule App开发人员理解的属性
配置这些库。

提示：为了帮助用户更轻松地配置库，强烈建议您填写注释提供的所有属性，例如：
+
[source, java, linenums]
----
@ExternalLib(name = "MySQL JDBC Driver",
description = "A JDBC driver that supports connection to the MySQL Database",
nameRegexpMatcher = "(.*)\\.jar",
requiredClassName = "com.mysql.jdbc.Driver",
coordinates = "mysql:mysql-connector-java:5.1.44")
public class MySqlConnectionProvider implements ConnectionProvider<Connection> {
  //
}
----
+
请注意，连接器可能需要多个外部库。 `@ExternalLib`
注释可根据需要多次使用。

=== 属性

[%header%autowidth.spread]
|===
| 属性 | 必 | 输入 | 说明
|  `name`  |  true  | 字符串 | 要在界面中显示的友好名称。
|  `description`  |  false  | 字符串 | 外部库的简短描述。
|  `nameRegexpMatcher`  |  false  | 字符串 | 用于匹配名称的正则表达式
的库文件，并验证用户指定的库是否正确。
|  `requiredClassName`  |  false  | 字符串 |  _（仅适用于Java库）_
`Class`将出现在外部库中。这将用于验证用户指定的库是否是正确的库。
|  `type`  | 真 | 枚举|
*  `NATIVE`：本机库依赖项
*  `JAR`：JAR文件相关性
*  `DEPENDENCY`：外部依赖关系（例如，如果您正在使用Maven，则获得的依赖关系在`pom.xml`中指定）
|  `coordinates`  |  false  | 字符串 |  Maven协调建议，指出可找到所需库的位置。他们应该遵循Maven的惯例`groupId:artifactId:packaging:classifier:version`。
|  `optional`  |  false  | 布尔值 | 指示连接器或模块是否需要该库工作。
|===



// TODO @estebanwasing将增加一个例子来说明这一点
