[[_output_metadata]]
= 输出元数据

输出元数据是组件结果的类型分辨率。
每个组件可以为有效负载和属性提供静态或动态元数据，
彼此隔离。

== 声明一个OutputTypeResolver和AttributesTypeResolver

`OutputTypeResolver`和`AttributesTypeResolver`实现都处理请求
根据{{​​1}}提供的信息解析`MetadataType`
最重要的是，使用`MetadataKey`来识别`MetadataType`是什么
由应用开发人员提供。

`OutputTypeResolver<T>`和`AttributesTypeResolver<T>`接口使用通用`T`进行参数化，
必须匹配`MetadataKeyId`参数的类型。
目前，您应该为泛型使用`String`类型，因为它是
最常见的`MetadataKeyId`类型。后来，这个文档重新讨论了这个通用类型，并详细解释了类型应该如何
更改为与`String`不同的内容。

[source,java,linenums]
----
public class OutputEntityResolver
  implements OutputTypeResolver<String>, AttributesTypeResolver<String>  {

  @Override
  public String getCategoryName() {
    return "Records";
  }

  @Override
  public String getResolverName() {
    return "OutputEntityResolver";
  }

  @Override
  public MetadataType getOutputType(MetadataContext context, String key)
      throws MetadataResolvingException, ConnectionException {
    switch (key) {
      case "Author_id":
        return context.getTypeLoader().load(AuthorResult.class);
      case "BookList_id":
        return context.getTypeLoader().load(BookListResult.class);
      case "Book_id":
        return context.getTypeLoader().load(BookResult.class);
      default:
        throw new MetadataResolvingException("Unknown key:" + key, INVALID_METADATA_KEY);
    }
  }

  @Override
  public MetadataType getAttributesType(MetadataContext context, String key)
      throws MetadataResolvingException, ConnectionException {

    if ("Book_id".equals(key)){
      return context.getTypeLoader().load(BookAttributes.class);
    }

    // Only Books have Attributes information
    return context.getTypeBuilder().nullType().build();
  }

}
----

上面的示例仅使用`MetadataContext`来获取`TypeLoader`
用于描述基于Java类的`MetadataType`，
但您也可以使用提供的配置和连接元素。

== 使用OutputTypeResolver

既然我们有`TypesKeysResolver`和`OutputTypeResolver`，我们可以添加输出
DataSense支持我们的运营和资源。
与`TypesKeysResolver`一起使用`OutputTypeResolver`的主要限制是两者
必须属于相同的`category`，因此我们可以保证由{}提供的`MetadataKey`
`TypesKeysResolver`可以通过`OutputTypeResolver`解析为`MetadataType`：

=== 为结果负载添加DataSense

[source,java,linenums]
----
public class FetchOperations {

  @OutputResolver(output = OutputEntityResolver.class)
  public Map<String,Object> get(@Connection MyConnection connection,
                                @MetadataKeyId(EntityKeysResolver.class) String entityKind){

    return connection.getClient().fetch(entityKind);
  }

}
----

这里，输出的`MetadataType`是基于`entityKind`动态解析的
正在提取，因此如果使用我们提供的`Author_id`键配置`entityKind`
`EntityKeysResolver`，那么`OutputEntityResolver`将与该`MetadataKey`一起被调用
`get`操作的输出将被解析为`AuthorResult` ObjectType。

源可以使用相同的输出类型分辨率来描述对象的`MetadataType`
派往流程，其声明非常类似：

[source,java,linenums]
----
@MetadataScope(keysResolver = EntityKeysResolver.class,
               outputResolver = OutputEntityResolver.class)
public class ListenerSource extends Source<Map<String, Object>, Void>  {

  @MetadataKeyId
  @Parameter
  public String type;

  @Connection
  private ConnectionProvider<MetadataConnection> connection;

  @Override
  public void onStart(SourceCallback<Map<String, Object>, Void> sourceCallback) throws MuleException {
    //...
  }

  @Override
  public void onStop() {
    //...
  }

}
----

源和操作都具有相同的生命周期来解决输出类型。
第一步是配置`MetadataKeyId`，然后按顺序使用该键调用{{1}
解析生成的实体`MetadataType`。

=== 为结果属性添加DataSense

组件的完整输出不仅是有效负载，而是`Result<Payload, Attributes>`，
在动态元数据解决方案中也考虑到了这一点。

当操作或源输出具有动态属性结构时，
我们可以通过声明来解析它的MetadataType
`AttributesTypeResolver`（已在`OutputTypeResolver.java`的示例中实现）
然后在Operation或Source声明中添加对它的引用。

在这个例子中，我们的`Book`实体可以分为书的内容和属性
书，每个都有自己的结构。这种分工是为了让应用程序开发人员更好地理解
并使用操作的结果，考虑数据（这是有效载荷中的书的内容）
以及表征有效载荷特征的元数据（书的属性）：

[source,java,linenums]
----
public class FetchOperationsWithAttributes {

  @OutputResolver(output = OutputEntityResolver.class,
                  attributes = OutputEntityResolver.class)
  public Result<Object, Object> get(@Connection MyConnection connection,
                                                @MetadataKeyId(EntityKeysResolver.class) String entityKind){

    if ("Book_id".equals(entityKind)){
      Book book = (Book)connection.getClient().fetch(entityKind);
      return Result.<Object, Object>builder()
                   .output(book.content())
                   .attributes(book.attributes())
                   .build();
    }

    return return Result.<Object, Object>builder()
                 .output(connection.getClient().fetch(entityKind))
                 .build();
  }

}
----

对于来源，与用于有效载荷的声明相似的声明添加
一个`attributesResolver`参考：

[source,java,linenums]
----
@MetadataScope(keysResolver = EntityKeysResolver.class,
               outputResolver = OutputEntityResolver.class,
               attributesResolver = OutputEntityResolver.class)
public class ListenerSource extends Source<Map<String, Object>, Object>  {

  @MetadataKeyId
  @Parameter
  public String type;

  //...

}
----

== 用用户定义的MetadataKey输出元数据

用户定义的MetadataKeys也适用于组件的输出。
回顾一下查询的情况，我们没有预定义的一组可能的MetadataKeys，
而是具有一个参数，其值表征输出类型或结构。

例如，在我们的数据库连接器中，我们有`select`操作，
其输出取决于要查询的实体：

[source,java,linenums]
----

  @OutputResolver(output = SelectMetadataResolver.class)
  public List<Map<String, Object>> select(@MetadataKeyId String sql, @Config DbConnector connector){
    // ...
  }

----

将`SelectMetadataResolver`声明为：

[source,java,linenums]
----
public class SelectMetadataResolver extends BaseDbMetadataResolver implements OutputTypeResolver<String> {

  @Override
  public String getCategoryName() {
    return "DbCategory";
  }

  @Override
  public String getResolverName() {
    return "SelectResolver";
  }

  @Override
  public MetadataType getOutputType(MetadataContext context, String query)
      throws MetadataResolvingException, ConnectionException {

    if (isEmpty(query)) {
      throw new MetadataResolvingException("No Metadata available for an empty query", FailureCode.INVALID_METADATA_KEY);
    }

    ResultSetMetaData statementMetaData = getStatementMetadata(context, parseQuery(query));
    if (statementMetaData == null) {
      throw new MetadataResolvingException(format("Driver did not return metadata for the provided SQL: [%s]", query),
                                           FailureCode.INVALID_METADATA_KEY);
    }

    ObjectTypeBuilder record = context.getTypeBuilder().objectType();

    Map<String, MetadataType> recordModels = resolveRecordModels(statementMetaData);
    recordModels.entrySet()
                .forEach(e -> record.addField().key(e.getKey()).value(e.getValue()));

    return record.build();
  }
}

----

== 列出元数据自动包装

在`select`示例中，我们可以看到该操作返回`List<Map<String, Object>`，
这是合理的，因为选择查询的结果是多个记录条目，
但在`SelectMetadataResolver`中，我们没有在`getOutputType`中描述ArrayType
方法，而是返回的MetadataType表示一个`record`结构。 +
这是为什么？

那么，既然我们已经知道Operation正在返回一个ArrayType（List，PagingProvider等），
您作为开发人员只需描述数组的`generic`类型。输出和属性
TypeResolvers总是解析元素的元数据类型
collection_而不是_collection_类型本身。
这将允许您更好地重用MetadataType解析器并减少所需的代码量。

考虑到已解析的属性也将是_elements_的属性
集合，并且_not_操作的`List`输出的属性。

== 解决没有MetadataKey的动态输出元数据

就像我们看到的输入一样，操作的输出可以被解决
没有特定的`MetadataKey`，它是受配置或连接影响的动态类型
的组件。 +
同样，为了声明无钥匙解析器，我们只需跳过`MetadataKeyId`参数
并忽略TypeResolvers中的MetadataKey：

[source,java,linenums]
----
public class UserTypeResolver implements OutputTypeResolver, AttributesTypeResolver  {

  @Override
  public String getCategoryName() {
    return "User";
  }

  @Override
  public MetadataType getOutputType(MetadataContext context, Object key)
      throws MetadataResolvingException, ConnectionException {

    // The `key` parameter will be `null` if the fetch is performed
    // as a `KeyLess` Metadata resolution. We'll just ignore it.
    String schema = getUserSchema(context);
    return new JsonTypeLoader(schema).load("http://demo.user")
            .orElseThrow(() -> new MetadataResolvingException("No Metadata is available for the User",
                                                              FailureCode.NO_DYNAMIC_TYPE_AVAILABLE));
  }

  @Override
  public MetadataType getAttributesType(MetadataContext context, Object key)
      throws MetadataResolvingException, ConnectionException {

    // The `key` parameter will be `null` if the fetch is performed
    // as a `KeyLess` Metadata resolution. We'll just ignore it.
    String schema = getUserSchema(context);
    return new JsonTypeLoader(schema).load("http://demo.attributes")
            .orElseThrow(() -> new MetadataResolvingException("No Metadata is available for the User Attributes",
                                                              FailureCode.NO_DYNAMIC_TYPE_AVAILABLE));
  }

  private String getUserSchema(MetadataContext context) throws MetadataResolvingException, ConnectionException {
    return context.<DemoConnection>getConnection()
      .orElseThrow(() -> new MetadataResolvingException("A connection is required to resolve Metadata but none was provided",
                                                        FailureCode.INVALID_CONFIGURATION))
      .describeUser();
  }
}
----

[source,java,linenums]
----
public class UserOperations {

  @OutputResolver(output = UserTypeResolver.class, attributes=UserTypeResolver.class)
  public Result<Map<String,Object>, Object> getUser(@Connection DemoConnection connection){
    User user = connection.getUser();

    return Result.<Map<String,Object>, Object>.builder()
                 .output(user.personalInfo())
                 .attributes(user.accountInfo())
                 .build().

  }

}
----


// TODO多级
