= 消息源的生命周期
:keywords: mule, sdk, sources, listener, triggers, lifecycle

与生命周期与拥有Flow的生命周期相关的操作不同，可以启动或停止源
分别通过运行时管理器。

为了支持这一点，`Source`类迫使您实施两种方法`onStart()`和`onStop()`

== 在开始

我们来看一下来自VM连接器的示例，以了解`onStart()`方法的实际外观：

[source, java, linenums]
----
@Override
public void onStart(SourceCallback<Serializable, VMMessageAttributes> sourceCallback) throws MuleException {

}
----

在这种方法中，您必须初始化所有需要的资源（例如线程，调度程序，连接等）以生成消息。如果出现异常或错误
条件被发现试图做到这一点，那么你必须：

* 释放您需要分配的资源
* 用有意义的消息抛出异常

如果源代码无法启动，那么包含它的应用程序也会启动。

[TIP]
所有通过`@Parameter`注释定义的源参数值在此时已经解析并可用。

===  SourceCallback

该方法接收一个SourceCallback对象。 `SourceCallback`可以说是Source的最重要部分，因为它是
几乎涉及到源代码功能的每个方面。我们将详细说明`SourceCallback`的用途和责任
随着本文档的进展，但简而言之，`SourceCallback`是源代码与运行时间通信的用途。它用于：

* 将消息推入流中
* 沟通连接问题并触发重新连接
* 在Source的推送阶段之间传递状态到响应处理部分

由于`SourceCallback`扮演着如此重要的角色，因此提供的实例始终可用非常重要。取决于你的来源
复杂性和代码组织，您可以通过简单地将其作为方法参数来实现。更复杂的来源可能需要保留一个参考
通过实例字段。如果您决定这样做，那么您需要确保在`onStop()`方法执行时清除引用

== 停止

该方法将由运行时调用，以使源停止生成消息。 *This method should not fail*。在停止过程中发现的任何异常应该是
记录并正确处理，但在调用此方法后，源必须：

* 停止生成消息
* 释放任何分配的资源
* 能够重新启动

== 下一步

*  <<sources-config-connection#, Obtain configuration and connections from a Message source>>
