= 解决常见问题
:keywords: tcat, problems, workarounds, issues

如果遇到问题，请查看Tcat Server的以下常见问题和解决方法。

无法与Tcat服务器通信== 

当服务器注册时，它们使用特定的IP地址进行注册。如果您正在使用无线连接的便携式计算机上进行测试，并且您从一个位置移动到另一个位置，则您的IP地址可能会更改，并且服务器不再能够与Tcat服务器通信。

=== 解决方法

在这种情况下，您必须取消注册并重新注册具有当前IP地址的服务器。

== 主屏幕不显示

如果您在Windows 2008上运行Internet Explorer 7，则可以登录到Tcat Server，但不会显示主屏幕。

=== 解决方法

要解决此问题，请选择“文件”>“将此站点添加到...”>“受信任的站点”。

== 部署中断

如果在部署包时导航到另一个选项卡，则部署会中断。

=== 解决方法

要解决此问题，请在导航到其他位置之前等待部署软件包。

== 监控和诊断画面消失

如果您在Mozilla Firefox上增加字体大小，监视和诊断屏幕将消失。

=== 解决方法

将字体大小设置为默认值。

==  Firefox中的文件名括号

如果您不止一次下载安装程序，Firefox会将括号附加到文件名，这会在尝试运行安装程序时导致问题。

=== 解决方法

如果您必须再次下载安装程序，请先删除原始文件，以便Firefox保留原始名称

{/ 0}} SSL / TLS握手异常

使用Tomcat 5.5和Tcat的APR连接器故障

TCS服务器管理控制台内的限制可能会导致"javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake"等错误，在某些情况下，它不能与SSL / TLS连接器配对。

=== 的变通办法

* 在防火墙阻止来自公共Internet的端口上配置HTTP（非SSL）连接器，但不能从控制台配置Tomcat服务器。
* 在防火墙阻止来自公共互联网的端口上配置AJP（非SSL）连接器，但不能从控制台配置Tomcat服务器。

==  Tcat无法在Windows上启动

Windows上的Tcat Server服务无法启动

=== 解决方法

解决方案：打开终端窗口并导航到Tcat服务器安装/ bin目录。输入tcatserver6w并检查Java选项卡下的内容。确保JAVA_HOME和JRE_HOME都指向正确的路径
