= 创建自定义政策
:keywords: tcat, custom, policies

Tcat Server允许您通过Galaxy API构建自己的自定义策略。这些可以作为类路径上的JAR安装，也可以通过自定义脚本安装。 JAR需要更多的开销，但允许您更轻松地测试和编译您的策略。

Tcat Server中的所有策略都是通过实现`Policy`接口创建的。该界面允许您在项目存储在存储库之前审批项目。

此页面将引导您使用可在`custom-policy`目录下的示例分布中找到的示例处理自定义策略。

== 撰写政策

以下是一个总是失败的简单政策：

[source, code, linenums]
----
import java.util.Arrays;
import java.util.Collection;
 
import org.mule.galaxy.Item;
import org.mule.galaxy.Registry;
import org.mule.galaxy.policy.ApprovalMessage;
import org.mule.galaxy.policy.Policy;
 
/**
 * A policy that always fails.
 */
public class AlwaysFailPolicy implements Policy {
 
    public static final String ID = "ALWAYS_FAIL";
 
    public boolean applies(Item item) {
        return true;
    }
 
    public String getDescription() {
        return "A policy which always fails";
    }
 
    /**
     * A unique, unchanging ID for this policy.
     */
    public String getId() {
        return ID;
    }
 
    /**
     * The display name in the UI.
     */
    public String getName() {
        return "Always fail policy";
    }
 
    public Collection<ApprovalMessage> isApproved(Item item) {
        // Return an approval message that indicates that this policy failed
        // and gives a reason why.
        return Arrays.asList(new ApprovalMessage("The policy failed for this item!", false));
    }
 
    public void setRegistry(Registry registry) {
    }
}
----

`isApproved()`方法返回单个ApprovalMessage的集合。此ApprovalMessage为用户提供了一个理由，说明为什么策略失败，以及为什么该项目不允许转换到新的生命周期阶段或被添加到存储库。

`applies`方法控制此策略是否适用于存储库中的特定项目。这通常用于控制此策略适用的工件类型或其适用的项目类型（Entry，Artifact，EntryVersion或ArtifactVersion）。

== 配置Tcat服务器以使用策略

策略通过简单的Spring beans文件在Tcat Server内部注册。文件必须命名为`META-INF/galaxy-applicationContext.xml`并位于类路径中。 Tcat Server通过这些Spring bean查找任何策略。要注册上述政策，您可以将以下内容添加到其中一个文件中：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">
 
  <bean class="org.mule.galaxy.example.policy.AlwaysFailPolicy"/>
 
</beans>
----

== 制定政策

要构建策略，您必须在您的类路径中包含`galaxy-core` JAR。定制策略示例提供了一个Maven POM为您构建JAR。要构建该示例，请在命令提示符处键入以下命令：

[source, code, linenums]
----
cd custom-policy
mvn install
----

您现在有一个位于`custom-policy/target/galaxy-custom-policy-VERSION.jar`的JAR，其中VERSION是您正在使用的Tcat Server的版本。

== 安装自定义策略

要使用自定义策略，只需将上一步中创建的JAR复制到Tcat服务器控制台webapp的`WEB-INF/lib`目录即可。

link:/tcat-server/v/7.1.0/scripting-examples[<<上一页：*脚本示例*]

link:/tcat-server/v/7.1.0/maven-publishing-plug-in[Next：* Maven Publishing Plug-in * >>]
