= 安装Tcat服务器
:keywords: tcat, install, server

本节包含所有受支持的Tcat服务器方案的说明。

[NOTE]
link:mailto:tcat-install@mulesoft.com[您可以通过电邮向MuleSoft发送Tcat评论或问题。]

== 先决条件

=== 操作系统要求

Tcat Server已在以下操作系统上进行测试：

*  Windows：XP，Server 2003，Vista，Server 2008，Windows 7
*  Linux：RHEL 4＆5，CentOS 4＆5，Oracle 5，Fedora 6到13，Ubuntu 9.x和10.x，SUSE 10和11，openSUSE 10和11
*  Mac OS X：10.5.8和10.6
*  Solaris：所有支持Java运行时的版本，服务器重新启动都在Solaris 10和11上受支持
*  Java 1.6高达1.7。目前不支持Java 1.8。

===  Java运行时要求

您可以下载带或不带捆绑JRE的Tcat Server。如果您安装捆绑JRE附带的安装程序包，则不需要安装任何其他Java运行库。如果您改为安装没有捆绑JRE的安装程序包，则必须安装单独的Java运行时（JDK或JRE，或者其中一种）。启动时，Tcat Server使用JAVA_HOME或JRE_HOME环境变量指向的Java运行时。如果这些环境变量都不指向Java运行时，则Tcat Server会自动使用捆绑的JRE。检查服务器上的JAVA_HOME和JRE_HOME变量的值，因为其中一个或两者都可能已指向已安装的Java运行时。 Tcat Server首先尝试使用JAVA_HOME，如果未找到Java运行时，则Tcat接下来尝试JRE_HOME。

如果您正在安装并使用自己的JDK或JRE（而不是使用捆绑的JRE），请确保您已安装JDK或JRE 1.5.x或新安装并且您的JAVA_HOME或JRE_HOME环境变量已正确设置。例如，在Windows上，从控制面板中选择系统实用程序，单击高级选项卡，然后单击*Environment Variables*，然后添加JAVA_HOME或JRE_HOME系统变量。

经测试和推荐的Java运行时==== 

MuleSoft建议为Tcat Server或更新版本推出最新的Oracle / Sun Hotspot 1.6.0 JDK或JRE，但也测试了IBM J9 1.6.0和Oracle JRockit 1.6.0 JVM以及更新版本。

Tcat Server可以运行在两个或更多不同的Java VM中：

.  Tcat服务器控制台运行于Tomcat 6.0及更新的版本，需要Java 1.6.0及更新版本（也称为"Java 6"）。 Java 1.5.0运行时不起作用。
.  Tcat服务器代理可以在任何Tomcat 5.5或更新版本中运行，并且JRE / JDK需要Java 1.5.0或更新版本，这意味着Java 1.6运行时同时受支持和推荐。

以下是我们测试过的一些Java运行时，并且已知可以与Tcat Server一起使用：

{/ 0}} Oracle / Sun热点版本1.5.0 JDK或JRE和更新（除非如下所述）
{/ 0}} Oracle / Sun热点版本1.6.0_04和更新的JDK或JRE
{/ 0}} Oracle / JRockit 1.6.0_20版和更新的JDK（Tcat v6.4.1和更早的控制台日志选项卡显示零日志）
在Ubuntu 10.04 Linux上，*  OpenJDK版本1.6.0_18 openjdk-6-jdk "(IcedTea6 1.8) (6b18-1.8-0ubuntu1)"
在Linux上，*  OpenJDK版本1.6.0_0-2b12
*  IBM J9版本1.6.0或更新版本的JDK或JRE（这适用于Tcat Server v6.4.2及更新版本）
*  Apple JDK 1.6.0，所有版本

以下是我们测试的一些已知的*not*工作的JDK，它们不受支持：

{/ 0}} Oracle / Sun JDK或JRE版本1.6.0_03或更早版本（由于JAXB，1.6.0以上的任何1.6.0 Oracle / Sun Hotspot JVM将不起作用）
*  IBM J9 1.5.0 JDK和JRE（由于缺少对自签名HTTPS客户端证书的支持）
*  Linux上的OpenJDK版本低于1.6.0_0-2b12（容易出现JVM崩溃和其他JVM故障）
*  GNU GCJ或GIJ，所有版本

[WARNING]
较早的Linux发行版本倾向于包含已知不运行Tcat Server的不兼容的Java运行时。 Tcat服务器与这些Java运行时不兼容，包括所有版本的GCJ，任何版本低于版本6的IcedTea以及版本低于版本1.6.0.0-b17的OpenJDK版本，尽管版本1.6.0_0-2b12已经过测试。

==== 红帽企业Linux / CentOS / Fedora

在64位安装中安装Tcat Server之前，必须先安装32位兼容性库及其所有依赖项。对于RHEL，CentOS和Fedora的大多数版本，您可以像这样通过yum来安装它们：

[source, code, linenums]
----
$ sudo -s
# yum install compat-libstdc++-33.i586 gtk+.i586 gtk2.i586
# exit
----

或者，对于这些发行版的一些更新版本，请这样做：

[source, code, linenums]
----
$ sudo -s
# yum install compat-libstdc++-33.i686 gtk+.i686 gtk2.i686
# exit
----

然后，您可以继续通过安装程序可执行文件安装Tcat Server。

====  Ubuntu Linux

在64位安装Ubuntu上安装Tcat Server之前，您必须安装32位兼容性库及其所有依赖项。你可以像这样通过apt-get来安装它们：

[source, code, linenums]
----
$ sudo -s
# sudo apt-get install ia32-libs
# exit
----

然后，您可以继续通过安装程序可执行文件安装Tcat Server。

====  OpenSUSE Linux

在64位OpenSUSE 11安装中安装Tcat Server之前，您必须安装32位版本的GTK2及其所有依赖项。您可以使用yast来安装它们，如下所示：

[source, code, linenums]
----
$ sudo -s
# yast -i gtk2-32bit
# exit
----

然后，您可以继续通过安装程序可执行文件安装Tcat Server。

== 快速入门安装

link:/tcat-server/v/7.1.0/quickstart[快速开始]部分包含所有支持的操作系统的说明，并说明了一些基本配置，以帮助您开始使用Tcat Server。本节的其余部分包含有关特殊用例和操作系统特定配置的说明。

== 升级安装

要升级Tcat Server 6.2版的现有安装，请按照以下说明进行操作。

[TIP]
如果您要从以前的版本进行升级，请参阅 link:/tcat-server/v/7.1.0/upgrading-to-r4[升级到R4]。

== 自动安装

Tcat服务器安装程序可用于Windows，Linux，Solaris和Mac OS X.这些安装程序允许您安装Tomcat，Tcat服务器代理，Tcat服务器管理控制台，并分别安装预配置版本的Tomcat，为您节省一些手动脚步。

== 无头安装

本节介绍如何以"headless"（纯文本）模式安装Tcat Server。当您以无头模式安装Tcat时，Tcat安装程序在shell中向您询问有关安装目录，服务器端口等的问题。只有在您回答了shell中的所有安装问题后，安装程序才开始安装。如果您需要自动执行设置，本节还介绍如何执行无头非交互式安装。

在Windows上，运行此命令以无头模式安装Tcat Server：

[source, code, linenums]
----
C:\> start /wait tcat-installer-6.4.3-windows-64bit.exe -c
----

在Linux和Solaris上，运行以下命令以无头模式安装Tcat Server：

[source, code, linenums]
----
# sh tcat-installer-6.4.3-*.sh -c
----

安装程序在shell中的交互如下所示：

[source, code, linenums]
----
# sh tcat-installer-6*.sh -c
Unpacking JRE ...
Preparing JRE ...
Starting Installer ...
This installs Tcat Server 6 on your computer.
OK [o, Enter], Cancel [c]
 
Read the following License Agreement. You must accept the terms of this agreement before continuing with the installation.
...
 
I accept the agreement
Yes [1], No [2]
1
Which type of installation should be performed?
Standard installation [1, Enter]
Custom installation [2]
1
Where should Tcat Server 6 be installed?
[/opt/TcatServer6]
----

通过`-c`参数，安装程序会要求您在文本模式提示中选择您的选择。如果您不想接受所有默认设置，包括安装管理控制台并使用所有默认端口号，请改为使用`-q`参数：

[source, code, linenums]
----
# sh tcat-installer-6.4.3-*.sh -q
----

或者，将响应反馈给安装程序，以便它不需要询问任何内容：

[source, code, linenums]
----
# sh tcat-installer-6.4.3-*.sh -q -varfile response.varfile
----

我们首次运行安装程序时，会在`.install4j`目录内生成response.varfile。 varfile的内容与简单的Java属性文件的格式相同：

[source, code, linenums]
----
# less /opt/TcatServer6/.install4j/response.varfile
 
#install4j response file for Tcat Server 6 R4 P1
#Fri Sept 27 16:51:39 GMT-08:00 2010
tcatServiceName=tcat6
secureAgentPort$Long=51443
tomcatHttpPort$Long=8080
tomcatHttpsPort$Long=8443
tomcatShutdownPort$Long=8005
tomcatAjpPort$Long=8009
sys.installationDir=/opt/TcatServer6
sys.programGroup.linkDir=/usr/local/bin
sys.programGroup.name=Tcat Server 6 [tcat6]
sys.programGroup.enabled$Boolean=false
sys.programGroup.allUsers$Boolean=true
sys.languageId=en
sys.installationTypeId=39
sys.component.37$Boolean=true
sys.component.51$Boolean=true
sys.component.52$Boolean=true
sys.component.53$Boolean=true
sys.component.54$Boolean=true
----

如果您需要Install4J关于安装的调试信息，您也可以在安装程序命令行上传递`-Dinstall4j.debug=true`和`-Dinstall4j.detailStdout=true`。在Windows上，您可能还想通过`-q -console` *as the first and second arguments*，否则您可能无法在shell中获得输出。之后阅读`TcatServer6/.install4j/installation.log`。

== 将Tcat服务器功能添加到现有的Apache Tomcat安装

您也可以 link:/tcat-server/v/7.1.0/add-tcat-server-capabilities-to-an-existing-tomcat-install[将Tcat Server添加到现有的Apache Tomcat安装中。]

== 在一台计算机上安装多个Tcat服务器

您也可以 link:/tcat-server/v/7.1.0/installing-multiple-tcat-instances-on-a-single-machine[在一台机器上安装多个Tcat服务器]。

*NOTE*如果您通过虚拟专用网络（VPN）连接到您的网络，请在运行Tcat Server之前断开连接。注册完所有Tcat服务器实例后，可以再次连接到VPN。

== 安装选项

本节包含一些用于定制安装的过程。

=== 使Webapps目录的内容不可写

默认情况下，管理控制台允许用户编辑注册到它的任何Tcat Server实例上的文件。

该属性在`webapps/agent/WEB-INF/`目录中的`spring-services.xml`文件中设置：下面是相关的代码片段：

[source, xml, linenums]
----
<property name="writeExcludes">
  <list>
    <value>lib/catalina*.jar</value>
    <value>**/tomcat*.jar</value>
    <value>conf/tcat-overrides.conf</value>
    <!-- block the webapps directory -->
    <!-- <value>webapps/**</value> -->
  </list>
</property>
----

要禁用此功能：

. 取消注释上面代码片段中显示的最后一个元素
  这
+
[source, xml, linenums]
----
<!-- <value>webapps/**</value> -->
----
+
有了这个：
+
[source, xml, linenums]
----
<value>webapps/**</value>
----
+
. 保存文件。
. 重新启动Tcat服务器实例。

=== 重命名Linux上的tcat6服务

您可能希望重命名您的Tcat Server的初始化脚本，因为您要在单个操作系统中安装多个Tcat Server副本，并且需要防止初始化脚本命名冲突，或者因为要使用init脚本一个不同的名字。 Tcat服务器支持重命名服务。

首先，确保关闭了您要重命名其服务的Tcat / Tomcat实例：

[source, code, linenums]
----
$ sudo service tcat6 stop
----

或者，如果您正在使用股票Tomcat包初始化脚本：

[source, code, linenums]
----
$ sudo service tomcat6 stop
----

切换到root shell：

[source, code, linenums]
----
$ sudo -s
----

将新服务名称设置为环境变量，并将目录的绝对路径设置为要更改服务名称的Tcat服务器安装：

[source, code, linenums]
----
# export NEW_SERVICE_NAME=t1
# export TCAT_HOME=/opt/TcatServer6
----

接下来，将init脚本符号链接重命名为新的服务名称（复制并粘贴这些命令 - 不要键入它们）：

[source, code, linenums]
----
# mv /etc/init.d/tcat6 /etc/init.d/$NEW_SERVICE_NAME 2>/dev/null
# mv $TCAT_HOME/bin/tcat6 $TCAT_HOME/bin/$NEW_SERVICE_NAME 2>/dev/null
# mv $TCAT_HOME/conf/Catalina/localhost/tcat6 $TCAT_HOME/conf/Catalina/localhost/$NEW_SERVICE_NAME
----

如果上述任何"tcat6"文件不存在，那是因为您只安装了Tcat Server的代理程序webapp，这没关系。在代理解压其服务脚本之前，您必须将代理与控制台配对。

并且，在用于JVM启动环境的Tcat / Tomcat实例环境文件中，更改服务名称设置（复制并粘贴此命令 - 不要输入）：

[source, code, linenums]
----
# sed -i.bak -e "s/\-Dtcat\.service\=[Installation^ ]* /-Dtcat.service=$NEW_SERVICE_NAME /g" \
    $TCAT_HOME/conf/Catalina/localhost/tcat-env.conf
----

从根shell退出。

[source, code, linenums]
----
# exit
----

如果要更改服务以在单个操作系统中安装两个或更多Tcat Server安装，则还应确保Tomcat的{{}}中的端口号不会发生冲突，并且还确保Tcat服务器代理安全端口号每个Tcat Server实例都是唯一的（复制并粘贴这些命令 - 不要键入它们）：

[source, code, linenums]
----
# export NEW_AGENT_SECURE_PORT=51444
# sed -i.bak -e "s/^securePort=.*/securePort=$NEW_AGENT_SECURE_PORT/g" \
    $TCAT_HOME/webapps/agent/WEB-INF/agent.properties
----

然后检查agent.properties文件以确保设置是正确的。

默认的代理安全端口是51443。

您现在已完成重命名该服务。您现在可以使用您选择的服务名称来启动，停止或重新启动Tcat Server：

[source, code, linenums]
----
$ sudo service t1 start
----

== 启动和停止Tcat服务器

本节介绍在Windows，Linux和Solaris上启动和停止Tcat Server的最简单方法，每个附加选项，<<Starting and Stopping on Mac OS X>>的说明以及<<Starting the Administration Console>>的说明。

[WARNING]
如果要使用标准的Tomcat `catalina`或`startup`命令启动Tomcat，则在使用Tcat Server命令重新启动Tomcat之前，在Tcat Server控制台中设置的任何环境变量都不会生效。因此，要在Tcat Server控制台中设置环境变量时获得最佳结果，应始终使用下面描述的Tcat Server命令启动Tomcat。


=== 在Windows和Linux上启动和停止

要启动Tcat Server，请导航至`bin`目录并在提示符处输入以下内容：

[source, code, linenums]
----
tcat6 start
----

或者将`tcat6`作为`bin`目录的路径的前缀以从其他目录运行该命令。要启动管理控制台，请参阅下文。

要停止Tcat服务器，只需关闭命令窗口，或使用：

[source, code, linenums]
----
tcat6 stop
----

您也可以重新启动服务器：

[source, code, linenums]
----
tcat6 restart
----

并获取服务器的状态和进程ID：

[source, code, linenums]
----
tcat6 status
----

Windows上的==== 附加选项

如果您通过安装程序安装了Tcat Server，则可以从Windows“开始”菜单中的Tcat Server 6组中选择*Start Tcat Server*和*Stop Tcat Server*。

要启动管理控制台，请参阅下文。

Linux上的==== 附加选项

* 如果您通过安装程序安装为非root用户，则可以使用图形桌面应用程序菜单启动，停止或重新启动服务器。
* 如果您通过安装程序以root身份安装，则可以使用init脚本：

[source, code, linenums]
----
service tcat6 start
----

* 如果服务命令不可用，请改用以下命令：

[source, code, linenums]
----
/etc/init.d/tcat6 start
----

* 如果您使用ZIP文件而非安装程序进行安装，并且拥有root权限，请按照以下说明完成安装。

=== 在Solaris 10和11上启动和停止

默认情况下，作为Solaris服务管理框架（SMF）的一部分，Tcat Server在Solaris 10及更新版本上安装后自动启动。或者，不使用SMF，您也可以直接调用名为"`tcat6`"的Tcat Server的初始化脚本。如果您以root权限安装Tcat，您可以在Tcat的bin /目录或`/etc/init.d/tcat6`路径中调用`tcat6`脚本。默认情况下，您应该使用SMF，但如果您没有足够的权限来使用SMF，则`tcat6`初始化脚本有效。对于任何单个Tcat服务器安装，您应该选择调用SMF或`tcat6`初始化脚本，而不是两者。

使用SMF，您可以查询服务来检查其当前状态，如下所示：

[source, code, linenums]
----
sudo svcs -l tcat6
----

或者，如果你不使用SMF，你可以像这样查询Tcat的状态：

[source, code, linenums]
----
/opt/TcatServer6/bin/tcat6 status
----

要停止Tcat服务器，请禁用其SMF服务：

[source, code, linenums]
----
sudo svcadm disable tcat6
----

或者，如果你不使用SMF，你可能会停止这样的Tcat服务器：

[source, code, linenums]
----
/opt/TcatServer6/bin/tcat6 stop
----

要从禁用状态启动Tcat Server，请运行：

[source, code, linenums]
----
sudo svcadm enable tcat6
----

或者，如果您不使用SMF，则可以像这样启动Tcat Server：

[source, code, linenums]
----
/opt/TcatServer6/bin/tcat6 start
----

您也可以通过SMF像这样重新启动服务器：

[source, code, linenums]
----
sudo svcadm restart tcat6
----

或者，如果您不使用SMF，则可以像这样重新启动Tcat Server：

[source, code, linenums]
----
/opt/TcatServer6/bin/tcat6 restart
----

Solaris上的==== 附加选项

* 如果您的shell用户在运行安装程序时没有root权限，则安装程序无法添加`tomcat` shell用户，安装程序也不能安装Tcat Server SMF服务。这是可以的，并且是Solaris上完全支持的用例。您用来运行Tcat安装程序的用户是Tcat JVM运行的用户，您应该通过`tcat6`初始化脚本在命令行上重新启动|，重新启动TCS服务器|。如上面<<Starting and Stopping on Solaris 10 and 11>>部分所述。
* 还支持在Solaris区域内安装Tcat Server。安装程序不知道它正在安装在非全局区域中，并且安装与在全局区域中安装它的工作方式相同。如果您在区域中拥有root权限，但该区域不允许您使用SMF，则安装程序可能无法安装SMF服务，但安装不会失败 - 它会成功并在没有SMF服务的情况下完成安装。您可以通过`tcat6`初始化脚本在命令行上运行不带SMF的Tcat服务器，如上面<<Starting and Stopping on Solaris 10 and 11>>部分所述。默认情况下，Solaris 10和11允许SMF在非全局区域内用作root用户。如果您的非全局区域中没有root权限，则在此区域内安装Tcat与在没有root权限的全局区域中安装Tcat相同。
* 如果您通过安装程序以超级用户身份进行安装，则可以调用init脚本启动|停止|重新启动|状态：

[source, code, linenums]
----
/etc/init.d/tcat6 status
----

==== 通过Linux上的Zip文件安装Tcat服务器

以下是从zip文件在Linux发行版上安装Tcat Server的步骤：

.  sudo -s
.  cd / opt
. 解压缩TcatServer-6.4.3.zip
+
[source, code, linenums]
----
# export TCAT_HOME=/opt/TcatServer6
----
+
. 如果您希望将Tcat Server安装到不同的文件系统位置，推荐使用自动安装程序。先尝试将其安装到/ opt / TcatServer6中。
+
[source, code, linenums]
----
# groupadd tomcat
# useradd -c "Tcat JVM user" -g tomcat -s /bin/bash -r -M -d $TCAT_HOME/temp tomcat
----
+
如果'tomcat'用户已经存在，请改为：
+
[source, code, linenums]
----
# finger tomcat > ~/tomcat-user-settings.txt
# usermod -s /bin/bash -d $TCAT_HOME/temp tomcat
----
+
. 无论如何，继续：
+
[source, code, linenums]
----
# ln -s $TCAT_HOME/conf/Catalina/localhost/tcat6-linux.sh /etc/init.d/tcat6
# ln -s $TCAT_HOME/conf/Catalina/localhost/tcat6-linux.sh $TCAT_HOME/bin/tcat6
# ln -s $TCAT_HOME/conf/Catalina/localhost/tcat6-linux.sh $TCAT_HOME/conf/Catalina/localhost/tcat6
# chmod 770 $TCAT_HOME/conf/Catalina/localhost/*.sh
# chmod 660 $TCAT_HOME/conf/Catalina/localhost/*.conf
# cp $TCAT_HOME/conf/Catalina/localhost/tcat-env-linux.conf $TCAT_HOME/conf/Catalina/localhost/tcat-env.conf
# chown -R tomcat:tomcat $TCAT_HOME
----
+
. 在Red Hat，CentOS和Fedora Linux发行版中，使用chkconfig命令在重新启动时启动Tcat：
+
[source, code, linenums]
----
# chkconfig tcat6 on
----
+
在其他Linux发行版（如Debian和Ubuntu）上，您可能也是这样做的：
+
[source, code, linenums]
----
# update-rc.d tcat6 defaults
----
+
. 编辑您的Tcat服务器的环境文件，将JAVA_HOME的值设置为指向您的Java JDK：
+
[source, code, linenums]
----
$TCAT_HOME/conf/Catalina/localhost/tcat-env.conf
----
+
如果您没有JDK，而是使用JRE，请设置JRE_HOME的值而不是JAVA_HOME。确保只设置其中一个环境变量，而不是两个。
+
. 启动Tcat服务器，如下所示：
+
[source, code, linenums]
----
# service tcat6 start
----
+
要么：
+
[source, code, linenums]
----
# /etc/init.d/tcat6 start
----

要启动管理控制台，请参阅
<<Starting the Administration Console>>。

=== 在Mac OS X上启动和停止

导航到Tomcat `bin`目录，并在终端提示符处输入以下命令：

[source, code, linenums]
----
startup.sh
----

要停止Tcat服务器实例，请输入以下命令：

[source, code, linenums]
----
shutdown.sh
----

=== 启动管理控制台

要运行管理控制台，请输入`+ http://localhost:8080/console+`` in your web browser, replacing `+localhost:8080+` with the correct server name and port where the console is deployed. You can now select and register one or more of the unregistered servers, adding them to server groups as needed. For more details, see link:/tcat-server/v/7.1.0/working-with-servers[使用服务器]。

== 修改JAVA_OPTS

有几个理由来修改你的JAVA_OPTS环境变量：

* 您希望启用JMX，以便获取有关连接器和服务器状态的更多详细信息，例如`-Dcom.sun.management.jmxremote`
* 您需要增加内存设置，因为您要安装安装程序中提供的所有组件，例如`-Xmx512M -XX:PermSize=64M  -XX:MaxPermSize=128M`
* 您需要修改安全端口，例如`-Dtcat.securePort=51444`

安装Tcat服务器后，您可以使用Tcat服务器控制台修改JAVA_OPTS，可以通过 link:/tcat-server/v/7.1.0/monitoring-a-server[修改服务器的环境变量]在每台服务器上手动设置选项，或者如果您拥有管理权限，可以在 link:/tcat-server/v/7.1.0/working-with-server-profiles[服务器配置]中设置在多个Tcat服务器实例中使用。

== 实施自定义重新启动策略

您现在可以指定自定义重启策略。这些控制着多个服务器如何重新启动。例如，以下是一个脚本，指定重新启动每个服务器之间应该有30秒钟的时间：

[source, code, linenums]
----
import com.mulesoft.common.server.restart.StaggeredRestartStrategy;
 
def serverManager = applicationContext.getBean("serverManager");
serverManager.setRestartStrategy(new StaggeredRestartStrategy(30000))
"Restart strategy installed"
----

用户还可以指定自定义重启策略。例如：

[source, code, linenums]
----
import com.mulesoft.common.server.restart.RestartStrategy;
 
def strategy = { serverManager, serverIds ->
  for (String id : serverIds) {
     println "Restarting ${id}"
     serverManager.restartServerNow(id);
   }
} as RestartStrategy
 
def serverManager = applicationContext.getBean("serverManager");
serverManager.setRestartStrategy(strategy)
"Restart strategy installed"
----

== 卸载Tcat服务器

要卸载Tcat服务器：

* 如果您通过安装程序在Windows上安装了Tcat Server，请从Windows开始菜单中选择*Uninstall Tcat Server*。
* 如果您在同一个目录中手动安装了Tcat Server和Tomcat，并且想要删除这两个程序，只需删除整个文件夹即可。
* 如果您在现有Tomcat安装上手动安装Tcat Server，请从`webapps`目录中删除控制台，代理webapps及其文件夹。

link:/tcat-server/v/7.1.0/quick-start[<<上一页：*快速入门*]
