= 管理存储库
:keywords: tcat, repository, manage, artifacts, workspace

Repository选项卡允许您添加和删除*artifacts*，例如配置文件和应用程序，并管理工作区。 *workspace*是存储工件的存储库中的一个位置。您可以将所有工件上载到默认的“应用程序”工作区，也可以创建新的工作区来组织工件。

== 查看存储库内容

当您首次查看“存储库”选项卡时，它将显示顶级工作空间，包括默认工作空间应用程序。单击一个工作区以查看它包含的工件和子工作区。您可以使用左侧的导航树浏览工作空间级别并选择要使用的工作空间。

== 修改工件或工作区

当您单击工件或工作区时，其详细信息将显示在四个选项卡上：

* 项目选项卡显示此工件内的任何工件，例如工作空间内的应用程序或应用程序内的版本。
* “信息”选项卡显示名称，类型，元数据（如默认版本或主生命周期）以及此工件的注释。通过添加元数据，您可以为未来版本中可用于搜索工件的属性指定值。添加注释允许您在查看对象时输入供您自己参考的自由格式文本。
* “策略”选项卡显示在工件生命周期的各个阶段设置的所有策略
* 安全选项卡允许您控制对此工件的访问

== 添加工作区

当您想要创建工件的逻辑分组时，可以添加一个工作空间。随着存储库中工件的数量增加，这很有用。您可以在工作区内创建工作区来进一步组织您的应用程序。

要添加工作区：

. 在“存储库”选项卡上，导航到要添加新工作空间的工作空间，或者保留在默认视图中将其添加到根级别。
. 点击*New Workspace*。
. 输入此工作区的唯一名称，然后单击*Add*。工作区名称应该是有意义的，也是唯一的。例如，创建服务器配置文件时，可能需要创建一个名为ServerProfiles的父级工作区，然后在其下创建名为Production，LinuxDevelopment等的工作区。

工作区现在显示在左侧的导航树中，视图将更改以显示新工作区的内容。您现在已准备好将工件添加到此工作区。

== 添加应用程序和其他工件

您可以将工件添加到存储库，例如应用程序，配置文件或要部署到多个Tomcat服务器的任何其他类型的文件。以下步骤描述了如何手动将工件添加到存储库。您还可以在 link:/tcat-server/v/7.1.0/deploying-applications[创建一个包]时向存储库添加工件，或者可以使用 link:/tcat-server/v/7.1.0/maven-publishing-plug-in[Maven Publishing Plug-in]在每次构建应用程序时将应用程序上载到存储库。

添加工件：

. 在“存储库”选项卡上，导航到要添加工件的工作空间。
. 点击*New Artifact*。
. 浏览到该文件的位置并选择它，或者在文件框中输入完整的路径名称。
. 在名称字段中，输入此文件的唯一名称。只要在此工作区内唯一，您就可以使用与文件名相同的名称。
. 在版本字段中，如果这是您第一次上传此文件，请保留*1*;如果此文件的早期版本已存在，请输入更高的数字。拥有多个版本的文件可以在需要时轻松回滚到以前的版本。
. 点击*Add*。

== 订阅更改通知

Tcat Server提供了对其存储库进行更改的RSS源。您可以订阅此订阅源，以通知有关特定工件或工作空间中所有工件的更改。要订阅，请点击工件或工作区，然后点击*Feed*，然后指定您的浏览器提供的用于订阅此提要的选项。如果您只想订阅评论更改，请点击评论旁边的Atom订阅源图标。

== 删除工件或工作区

[IMPORTANT]
当您删除工作区时，其所有工件也会被删除。

要删除工件或工作区，请在“存储库”选项卡上选择它，然后单击*Delete*。

link:/tcat-server/v/7.1.0/troubleshooting[<<上一页：*故障排除*]

link:/tcat-server/v/7.1.0/managing-users-and-groups[下一步：*管理用户和角色* >>]
