= 监控应用程序
:keywords: tcat, monitor, applications, sessions, attributes, jsp, resources, jndi

查看服务器上的应用程序列表（在管理控制台中，单击服务器选项卡，单击服务器名称，然后单击应用程序选项卡）时，可以通过单击其名称查看有关特定应用程序的更多详细信息。 Summary选项卡显示有关应用程序和统计图表的运行时信息。您可以单击左侧导航栏中的其中一个侧面选项卡，以查看更多信息，如以下各节中所述。

== 摘要

摘要选项卡提供有关应用程序的运行时信息，例如servlet的数量，上下文属性和请求。它还显示图表，显示请求的历史数量和平均响应时间。您可以单击图表将其展开，然后您可以单击任何蓝色数字以显示更详细的信息。例如，单击servlet的数量将显示Servlets选项卡。您可以使用选项卡顶部的按钮在浏览器窗口中转到应用程序（即使它位于远程服务器上），停止应用程序，重新加载应用程序或从服务器取消部署应用程序。您还可以估算会话大小。

== 会话

“会话”选项卡显示此应用程序的当前会话。您可以单击会话名称以查看更多详细信息，包括会话属性，以及访问用于销毁会话的选项。您也可以点击IP地址来执行WHOIS查询并显示其来源的详细信息。要估算会话的大小，请点击*Estimate Size*。要隐藏大小列，请点击*Hide Size*。

== 属性

Attributes选项卡显示此应用程序的servlet上下文属性。如果您想要从servlet上下文中删除属性，只需单击该属性旁边的垃圾桶图标即可。

== 的JSP

JSP选项卡列出了使用此应用程序部署的JSP。如果有的没有被预编译，你可以选择它们并从这个选项卡编译它们。要查看JSP的源代码，请单击其名称。然后，您可以单击*View Generated Servlet*查看此JSP的自动生成的servlet代码，或单击*View JSP*返回JSP代码。您也可以在查看代码的同时编译JSP。

== 资源

资源选项卡列出应用程序引用的JNDI资源。 “类型”列显示资源的类型，如果它是数据源，它还会显示URL，池中的最大连接数，繁忙连接数（不能重新使用）以及建立的连接数（可以是重复使用）。 “链接到”列指示此资源是否是全局定义资源上的链接（即，在由多个应用程序共享的上下文之外定义的资源）。 “身份验证”列指示资源身份验证是由容器代表应用程序（用户名和密码在资源定义中指定）还是由应用程序本身以编程方式处理。

有关在Tomcat中使用JNDI资源的信息，请参阅Apache站点上的 link:https://tomcat.apache.org/tomcat-7.0-doc/jndi-resources-howto.html[JNDI资源操作]。

== 上下文描述符

上下文描述符选项卡显示应用程序的`context.xml`文件的内容。您可以点击下载链接下载文件，该文件被重命名为应用程序名称。

== 部署描述符

部署描述符选项卡显示应用程序的`web.xml`文件的内容。您可以点击下载链接下载文件。

== 的Servlet

Servlets选项卡显示此应用程序中的servlet列表。对于每个servlet，该表显示servlet的上下文路径，它实现的servlet类，当前是否可用，是否在启动时加载（如果是，加载顺序），加载所需的时间（以毫秒为单位）向此servlet请求至此为止，此servlet处理请求的总时间，错误数量，花费在单个请求上的最短和最长时间以及servlet是否为多线程。您可以点击*Servlet Mappings*查看URL和处理它们的servlet之间的映射，然后单击*Servlets*返回查看servlet列表。

== 过滤器

Filters选项卡显示此应用程序使用的过滤器列表。对于每个过滤器，表格都会显示过滤器名称，实现类别和描述（如果可用）。您可以单击*Filter Mappings*查看针对不同URL调用的过滤器，哪些servlet实现过滤器（如果未由应用程序指定），哪种类型的调度程序应用过滤器以及过滤器类。点击*Filter Definitions*返回查看过滤器列表。

== 参数

“参数”选项卡显示用于初始化上下文的参数列表。通常，这些来自应用程序的`WEB-INF\web.xml`文件。

link:/tcat-server/v/7.1.0/monitoring-a-server[<<上一页：*监控服务器*]

link:/tcat-server/v/7.1.0/troubleshooting[下一步：*故障排除* >>]
