= 监控服务器
:keywords: tcat, monitor, server, environment, variables, summary, memory

本页介绍系统管理员如何使用MuleSoft Tcat Server来监控服务器的运行状况，查看哪些应用程序已启动，哪些已关闭，并确定内存使用情况。要查看服务器详细信息，请单击服务器选项卡上的服务器名称。 “服务器详细信息”屏幕显示几个不同选项卡上的信息，这些信息将在以下各节中介绍。

在查看服务器详细信息的任何时候，您都可以单击窗口顶部的*Restart Server*以重新启动该服务器。如果您不想再监视服务器，请点击*Unregister Server*。

== 查看和编辑服务器摘要

摘要选项卡提供服务器的概述，包括其状态（如果正在运行，则显示绿灯，如果停止，则显示红灯），其所属的组，已部署到的组以及其环境变量（见下文）。

要修改汇总详情，请点击*Edit Server Info*，进行更改，然后点击*Save*。要将服务器添加到组，请从下拉列表中选择它并单击*Add*。要从组中删除服务器，请单击组名称旁边的红色X.

== 使用服务器环境变量

默认情况下，只有通过Tcat Server为服务器设置的变量显示在服务器的摘要选项卡上。要显示服务器上的所有环境变量，请单击*more*链接。完整的变量列表出现在下面的滚动列表中。

要管理服务器上的环境变量，请单击*Edit Server Info*，然后执行以下一项或多项操作：

* 要添加环境变量，请输入变量的名称及其值，然后单击*Add*。在您输入时，会出现匹配的变量名称，允许您从列表中选择一个。
* 要更改现有变量，请单击其名称或值框并根据需要进行编辑。
* 要删除变量，请单击其值旁边的红色X.

完成更改后，请点击*Save*。要恢复您的更改，请点击*Cancel*。

如果更改环境变量，请单击*Restart Server*重新启动服务器，并使更改生效。

[WARNING]
如果使用Tcat Server对变量进行更改，我们建议您*not*对Tcat Server以外的变量进行进一步更改。否则，这些变量会失去同步，因为当Tomcat启动时，它们会从JVM中被引入到Tcat服务器中，并与您在Tcat服务器控制台中设置的任何内容相结合。因此，如果您必须在Tcat Server之外进行更改，则还需要在Tcat Server之外手动重新启动Tomcat。然后，这些变量将在JVM中更新并被拉入Tcat服务器，并且您在Tcat服务器控制台中显式设置的任何内容都优先于外部设置的内容。

== 使用服务器配置文件

“文件”选项卡显示服务器上的文件和文件夹。您可以查看和编辑任何基于文本的（非二进制）文件，重新部署它，然后重新启动服务器。

要查看文件，只需单击它的名称即可。如果您要修改文件，请点击*Edit*，在出现的编辑器中进行更改，然后点击窗口底部的*Save*。如果您犯了错误，您可以点击*Reset*将编辑器窗口重置为文件中的原始文本。要取消您的更改而不保存并关闭编辑器窗口，请点击*Cancel*。

要将新文件添加到服务器，请执行以下操作：

. 在文件选项卡中，点击*New File*。
. 输入您想要为此文件显示的名称。
. 指定文件（您可以点击*Browse*从文件系统中选择它）并点击*Upload*。

要上传文件的新版本，请点击其名称进行查看，点击*Upload New File*，指定文件的更新版本，然后点击*Upload*。

要删除文件，请点击其名称进行查看，然后点击*Delete*。

== 查看已部署的应用程序

“应用程序”选项卡显示已部署到此服务器的应用程序的列表。 “状态”列显示每个应用程序当前是正在运行还是已停止。您可以通过点击状态在*running*和*down*之间切换来停止或重新启动应用程序。

您可以通过单击任何列标题对应用程序列表进行排序。例如，您可以单击“状态”列标题，以便所有停止的应用程序在表格顶部组合在一起。

到 link:/tcat-server/v/7.1.0/monitoring-applications[查看关于应用程序的更多细节]，点击应用程序名称。

以下是对这些列的描述：

[%header,cols="2*a"]
|===
| {列{1}}说明
|名称 |应用程序文件夹的名称。
|状态 |应用程序正在运行还是已关闭（已停止）。
|描述 | WAR文件中指定的应用程序描述。
|请求次数 |每个应用程序处理的请求总数。
| Sess。 |每个应用程序的会话总数。会话是应用程序与特定客户端之间的连接，例如通过Web浏览器访问应用程序的用户。每个会话都可以处理多个请求。会话在客户端终止会话或会话超时时关闭。
| S.ATTR  |会话属性的总数。会话属性存储有关客户端的信息。
| C.ATTR  |此应用程序设置的ServletContext属性的总数。 ServletContext属性由同一应用程序中的所有servlet共享。
| SESS。超时 |如果在该时间段内没有任何活动，会话将自动关闭的时间间隔。
| JSP  |单击该图标将显示该应用程序中所有JSP的列表。您可以单击特定的JSP来查看其代码。您也可以编译一个或多个JSP。
| JDBC使用 |显示每个应用程序对JDBC资源的最大连接使用情况。您可以单击此列中的栏来查看该应用程序的JDBC资源。
| CLSTRED。？ |应用程序是否可分发并部署在群集中。
| SER。？ |是否所有会话属性都实现`java.io.Serializable`。
|===

== 查看日志文件

日志选项卡显示Tomcat为每个应用程序和Tomcat实例本身生成的日志。请注意，所有日志都会在每天午夜之前翻转。

该表显示日志类型，如JDK或Log4J，文件名，文件大小，上次修改的时间戳以及用于创建日志的类。单击日志文件名称查看其内容，或单击下载图标以在本地保存文件。查看日志文件内容时，可以使用缩放按钮使字体变大或变小，您可以调整换行，并且可以清除日志文件。日志在写入时更新;要暂停它，请点击*Pause Tailing*。要继续实时观看，请点击*Resume Tailing*。要返回到日志列表，请点击*Back to log files list*。

有关Tcat Server生成的日志的详细信息，请参阅 link:/tcat-server/v/7.1.0/working-with-logs[使用日志]。

== 查看主题

“线程”选项卡允许您查看JVM中正在运行的线程。显示的信息取决于服务器的JVM是否安装了JMX代理或基于线程类。线程类视图显示不太详细的信息，所以如果你需要更多的细节，你应该考虑安装一个JMX代理。要使用Tomcat启用JMX代理，请按照 link:/tcat-server/v/7.1.0/installation[安装]中所述将-Dcom.sun.management.jmxremote选项添加到CATALINA_OPTS设置。

===  JVM代理信息

[%header,cols="2*a"]
|===
| {列{1}}说明
| ID  |此线程的唯一标识符。只要应用程序创建线程，该值就由JVM分配。
|名称 |线程名称。该值由应用程序分配。
| EXEC。 POINT  |执行线程的代码中的关键点。如果可用，将显示课程名称和行号。
|状态 |当前的 http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.State.html[线程的状态]。
| IN.NATIVE  |此线程是否在本机代码中执行。
| SUSP。 |该线程是否被挂起（即线程上调用了`Thread.suspend()`）。
| WC  | http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/management/ThreadInfo.html#getWaitedCount()[等待计数]。这是线程等待的次数。
| BC  | http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/management/ThreadInfo.html#getBlockedCount()[阻止计数]。这是线程被阻止进入监视器的次数。通常，当线程在尝试输入`synchronized()`块时必须等待时才会发生这种情况。
|===

=== 线程类信息

[%header,cols="2*a"]
|===
| {列{1}}说明
|名称 |线程名称。该值由应用程序分配。
| P  |此线程的优先级。数字越高，其优先级高于其他线程，并且从CPU获得的时间越多。
| APP  |此线程所属的应用程序。
| CLASS LOADER  |此线程的上下文类加载器。单击该类以查看该线程可以访问的类路径。
| GROUP  |此线程所属的线程组。
| THREAD CLASS  |生成此线程的类实现。
| RUNNABLE CLASS  |由此线程执行的类。
| D  |线程是否是守护进程。
| I  |线程是否被中断。
|===

== 查看系统信息

“系统信息”选项卡显示有关安装了Tcat服务器的计算机的信息。

内存利用率栏一目了然地显示服务器上正在使用多少内存。要释放由应用程序不再使用的对象占用的内存，请单击*Force Garbage Collection*。该链接运行`System.gc()`，建议JVM执行垃圾收集。或者，您可以在“内存使用率”页面上单击"Advise GC"（也运行`System.gc()`）或"Advise Finalization"（运行`System.runFinalization()`以建议在对象上运行终止方法）。这些选项只能在开发或测试环境中调用，因为它们可能导致应用程序执行时暂停，并可能导致JVM冻结。

要查看有关内存使用情况的更多特定信息，请单击屏幕右侧垂直菜单栏中的*Memory Utilization*。屏幕现在显示不同缓存和空间的内存使用情况，并允许您为每个缓存显示图表。

此选项卡的其余部分显示有关此服务器上安装的操作系统和Tomcat容器的信息。要显示有关操作系统的更多特定信息（包括可用RAM和历史使用情况图表），请单击屏幕右侧垂直菜单栏中的*OS Information*。

要查看系统属性，例如Java主目录和Tomcat的基本目录和主目录（catalina.base和catalina.home），请单击垂直菜单栏中的*System Properties*。

最后，如果您的JVM由Java服务包装器控制，则可以单击*Wrapper Control*查看有关包装器的信息，包括其Java PID，是否启用调试以及其所有属性的值。

== 查看连接器

“状态”选项卡允许您查看用于将客户端请求连接到应用程序的连接器的状态。连接器根据它们使用的端口和协议分成组。每个组都显示信息，例如该组中可用和繁忙线程的总数。它还显示每个连接器的信息，包括远程IP地址，当前阶段和请求的URL。

“连接器”选项卡显示的图表显示了所有可用连接器的流量信息。 Feed是实时的，并且图表每30秒自动更新一次。您可以通过单击该组的标题面板来切换连接器组的可见性。

link:/tcat-server/v/7.1.0/deploying-applications[<<上一页：*部署应用程序*]

link:/tcat-server/v/7.1.0/monitoring-applications[下一步：*监视应用程序* >>]
