= 将Tcat安装从非Linux操作系统移到Linux
:keywords: tcat, linux, migrate, jvm

本页讨论如何将已安装的Tcat Server安装目录树从运行Linux以外的操作系统的服务器移动到运行Linux的另一台服务器。此信息适用于以下Linux发行版：Red Hat，CentOS，Fedora，Ubuntu，Debian，Debian变体和SUSE变体。

通过简单的Tcat服务器安装，从库存Tcat服务器安装中没有多少变化，并且Web应用程序是Tcat {0}}树的一部分，您可以递归地将该Tcat安装树复制到Linux机器。然后按照以下步骤操作（您需要成为root用户）：

. 如果您在没有Tcat附带的Java运行时上运行Tcat，请在目标Linux服务器上安装相同的Java品牌和版本运行时。最好在目标机器上使用_exactly_相同的Java版本，就像您在原始机器上那样。
. 在更改其他任何内容之前，取消注册您从Tcat控制台移动的服务器。
. 关闭您即将移动的实例。
. 递归地将所有文件复制到目标Linux机器上。最好在复制安装树的过程中，尝试保留文件所有权，组和权限。
. 确保您创建（或验证是否存在）要运行Tcat JVM的用户和组。我们建议您使用您在前一台机器上使用的相同用户和组名。
. 确保所有者和文件组对您要在Linux上运行的用户有意义。通常，我们将它作为用户'tomcat'运行，其中组可以是'tomcat'或'root'。您可能想要使用这些命令更改所有者ID和组ID：
+
[source, code, linenums]
----
# cd /opt/TcatServer6# find . -uid 46 -exec chown tomcat {} \;# find . -gid 5000 -exec chgrp tomcat {} \;
----
+
. 如果您具有root /管理员权限，请将Linux初始化脚本符号链接到位，如下所示：
+
[source, code, linenums]
----
# ln -s /opt/TcatServer6/bin/tcat6 /etc/init.d/tcat6
----
+
. 您应该告诉Linux在重启时启动tcat6服务。
 在Red Hat，CentOS，Fedora和SUSE / openSUSE上：
+
[source, code, linenums]
----
# chkconfig tcat6 --level 2345 on
----
+
在Ubuntu，Debian和Debian变体上：
+
[source, code, linenums]
----
# update-rc.d tcat6 defaults
----
+
. 编辑您的Tcat的`conf/Catalina/localhost/tcat-env.conf`文件（如果有的话），并确保所有路径和设置对Linux有效。如果这证明太困难了，您可以选择删除或移动该文件。
. 确保配置其他后端机器以允许与目标Linux服务器进行通信。这包括已部署的Web应用程序必须连接到或与之通信的任何后端机器或服务器，例如SMTP服务器，数据库服务器和消息传递服务器。
. 确保`webapps/agent/WEB-INF/truststore.jks`文件不存在。如果存在，请删除它。
. 删除或移动`logs/`目录中的日志文件，以便Tcat在目标Linux机器上写入新的日志。
. 此时，Tcat应该在Linux上正常运行。 link:/tcat-server/v/7.1.0/installation[尝试启动它]。查看日志文件并确认没有意外的异常。
. 从Tcat控制台注册服务器实例。
. 尝试从Tcat控制台触发服务器重启 - 这应该会成功。

而已。 Tcat安装现在被迁移到Linux服务器机器上。
