=  Tcat服务器概述
:keywords: tcat, server, tomcat

本页面介绍了Tcat服务器并描述了底层技术。有关更多信息，请参阅 link:https://www.mulesoft.com/tcat/understanding-apache-tomcat#tcat[Tcat资源]。

==  Tcat服务器有哪些新功能？

请参阅 link:/tcat-server/v/7.1.0/release-notes[发行说明]获取最新版本信息。

== 什么是Tcat服务器？

来自MuleSoft的Tcat Server提供了一个强大的企业解决方案，用于在Apache Tomcat中开发，部署，管理，集成和排除Web应用程序的故障。它包含一个或多个Apache Tomcat实例和一个管理控制台。

Tcat Server使Tomcat功能更强大，使用更简单：

* 通过管理控制台Web应用程序，您可以监视和控制多台服务器上的所有Tomcat（和Tcat Server）实例。与Tomcat的本地管理器应用程序不同，Tcat Server控制台允许您快速设置所有服务器上的用户和角色，而无需分别编辑每个实例中的XML文件
* 从控制台而不是本地实例轻松部署和查看远程和本地应用程序
* 监控应用程序和您部署它们的服务器的运行状况
* 在一台机器上安装多个实例
* 将Tcat服务器实例作为Windows服务运行
* 远程重启（OS X除外）
* 使用管理外壳组件运行自定义groovy脚本，挂接到部署事件并自动重新启动

Tcat Server可以免费试用并在开发中使用，因此您可以在上线之前对概念和测试部署进行全面验证。当您准备投入生产时，您只需从MuleSoft购买一个订阅，只需支付一小部分重量级应用服务器的费用即可。

== 关于Tomcat

Tomcat是 link:http://www.apache.org[Apache软件基金会]开发的非常流行的Web服务器和servlet容器。与Apache Web服务器（它是HTTP Web服务器的C实现）不同，Tomcat是用Java编写的。 Tomcat是免费的，用于全球任务关键型环境。如果您使用Java编写Web应用程序，Tomcat是部署和管理它们的最佳选择。

以下是可用于帮助您了解Tomcat的一些资源：

*  http://tomcat.apache.org/tomcat-7.0-doc/index.html[Tomcat 7]
*  http://tomcat.apache.org/tomcat-6.0-doc/index.html[雄猫6]
*  http://wiki.apache.org/tomcat/GettingStarted[Apache的Tomcat入门指南]
O'Reilly发布的*  http://oreilly.com/catalog/9780596101060/[Tomcat：权威指南]

link:/tcat-server/v/7.1.0[<<上一页：*首页*]

link:/tcat-server/v/7.1.0/quick-start[下一步：*快速启动* >>]
