= 服务器配置文件
:keywords: tcat, server, profile, environment, settings

Tcat Server支持名为*server profiles*的功能，该功能提供了将文件更改和环境变量设置更改应用于一个或多个Tcat或Tomcat安装的自动方式，以及管理和存储这些更改的中心点。

服务器配置文件的主要用途包括：

*  *Tomcat configuration management*：
+
集中管理和部署一组Tomcat配置更改，包括需要存储在Tomcat安装树中的任何服务器配置文件和脚本。例如，您可能希望将server.xml和catalina.properties文件一起分发给多个Tomcat安装，并且每次修改这些文件时自动应用这些更改。
*  *Server startup environment settings*：
+
集中设置和应用服务器环境变量设置的一致，自动化和可重复的机制，包括在JAVA_OPTS环境变量中设置JVM启动开关和系统属性。
*  *Miscellaneous file deployment*：
+
任何不属于Web应用程序且不属于Tomcat但必须部署到服务器上的文件可以使用Tcat Server控制台进行集中管理和存储，并使用服务器配置文件部署到Tcat或Tomcat安装目录树中。例如，如果您的web应用程序使用内置于Tomcat中的容器管理的数据库连接池，请将JDBC驱动程序放入Tomcat的lib目录中，该目录位于webapps之外。

Tcat Server实现了将Web应用程序文件部署，重新部署和取消部署到一台或多台服务器的机制，但是当您需要将一致的Tomcat配置更改分发到一台或多台服务器时，可以使用服务器配置文件。在某些情况下，您可能需要将Web应用程序上下文配置与Web应用程序文件分开，在这种情况下，您可以使用服务器配置文件来部署配置更改。

您可以使用服务器配置文件环境变量将其添加到每个服务器已有的任何值的开头或结尾。例如，您可以应用添加额外配置文件的服务器配置文件，并且还将系统属性定义添加到服务器的JAVA_OPTS环境变量的末尾。

== 如何使用服务器配置文件

您可以按照以下步骤创建新的服务器配置文件并将其应用于您的服务器：

*Step 1*：创建一个工作区来保存您的服务器配置文件的文件和目录：

. 单击顶级“存储库”选项卡。
. 点击*Profiles*工作区链接，导航到服务器配置文件工作区。
. 单击新建工作区按钮并为您的服务器配置文件输入工作区名称。这个名称可以是任何自由形式的文本名称，但它应该很短并且清楚地传达服务器配置文件的名称。
. 将任何文件和目录上传到您的服务器配置文件的工作区中，以将其添加到您的服务器配置文件中。放置在工作区根目录中的文件将写入Tomcat安装的根目录（CATALINA_BASE）。因此，例如，如果您希望包含JDBC驱动程序jar文件以便将其安装到Tomcat的lib /目录中，请在服务器配置文件工作区的根目录中创建一个`lib`目录，然后将JDBC驱动程序jar上载到lib目录。

*Step 2*：创建一个服务器配置文件，为其命名，然后选择您在步骤1中创建的工作区：

. 点击顶级的管理标签。
. 点击左侧的服务器配置文件链接（在管理标题下）。
. 点击新建。这带来了新的服务器配置文件表单。
. 为您的服务器配置文件输入一个名称 - 这应该是您在应用和显示服务器配置文件时想在Tcat控制台中显示的简短名称。此外，请输入描述服务器配置文件目标的描述，以及有关其内容的重要信息和注释，例如其包含的软件版本，可能应用的Tomcat版本，操作系统意味着支持，等等。
. 选择包含您的服务器配置文件的文件和目录的工作空间。
. 随时单击表单底部的保存按钮以保存您的服务器配置文件。

*Step 3*：在服务器配置文件中设置任何环境变量值。并非每个服务器配置文件都需要环境变量设置，但如果您的设置是这样的，则可以设置它们

. 点击添加变量按钮。
. 通过单击环境变量的名称字段输入环境变量的名称（没有前面的美元符号或百分号）。
. 输入环境变量的值，请记住，将服务器配置文件应用到服务器时，服务器可能已经具有此变量集。您可能需要在服务器配置文件的环境变量值中引用服务器的现有值（否则将使用服务器配置文件的值，并且服务器自己的值会丢失）。例如，可以将JAVA_OPTS设置为将JVM启动开关添加到JAVA_OPTS现有值的末尾，值为"${JAVA_OPTS} -Xmx2048m"。
. 点击底部的保存按钮，保存您的服务器配置文件。

*Step 4*：将您的服务器配置文件应用于您的服务器：

. 导航至顶级服务器标签，然后点击左侧的*All*链接。这会向您显示所有服务器的列表。
. 选择您希望应用新服务器配置文件的每个服务器。您可能首先仅将其应用于一台服务器，然后再对其进行测试，但稍后可以在此屏幕上同时将其应用于两台或更多台服务器。
. 点击右上角的设置配置文件按钮。这将拉下控制台所具有的服务器配置文件列表。
. 选择新的服务器配置文件，并将其远程应用于您选择的每台服务器。某些服务器配置文件需要重新启动服务器JVM才能使更改生效。例如，如果添加环境变量设置，或者添加了Tomcat必须在JVM启动时找到并加载的内容。如果是这样，只要准备好使服务器配置文件生效，请单击重新启动按钮以重新启动受影响的服务器。在不重新启动JVM的情况下，服务器配置文件中的文件和更改已存储在每台服务器上，因此只要下次加载并使用这些文件，这些更改就会启动。
. 要查看哪个服务器配置文件适用于服务器，请选择该服务器，然后单击其“设置”选项卡。您也可以编辑服务器的设置并在其中选择服务器配置文件。

== 环境变量

服务器具有环境变量设置，服务器配置文件可以具有环境变量设置。当Tcat Server将服务器配置文件应用于服务器时，服务器配置文件的环境变量设置将合并到服务器的环境变量设置中。合并的完成使得可以在服务器级别覆盖服务器配置文件的值，以便可以将服务器配置文件应用于许多服务器，并在其中一台服务器上具有不同的环境变量值。下表显示了Tcat Server在应用服务器配置文件时如何合并环境变量和值：

[%header,cols="3*a",width=80%]
|===
|服务器配置文件环境变量设置 |服务器环境变量设置 |合并设置
|（未定义） | MY_VAR =一两个 | MY_VAR =一两
| = MY_VAR {3 {1}}（未定义） | = MY_VAR 3
| MY_VAR =三个 | MY_VAR =一个两个 | MY_VAR =一个二
| MY_VAR = $ {MY_VAR}三个 | MY_VAR =一个两个 | MY_VAR =一个二三个
| MY_VAR =三位$ {MY_VAR}  | MY_VAR =一位两位 | MY_VAR =三位一位二位
|===

服务器的环境变量设置优先，但服务器配置文件的值可能会引用服务器的值并将其包含到自己的值中。

除了支持引用服务器的同变量值外，您还可以引用其他环境变量，JVM系统属性，并有条件地在服务器配置文件的环境变量值中设置值。这使服务器配置文件更具可编程性和多平台性，并允许您创建适用于不同服务器操作系统的服务器配置文件，其中每个操作系统都需要依赖于操作系统的不同设置。

下表显示了Tcat服务器支持的环境变量值引用的一些示例（从版本6.4.2开始）：

[%header,cols="2*a"]
|===
|服务器配置文件环境变量设置 |说明
| $ {java.io.tmpdir}  |将此引用替换为服务器的系统属性值。
| $ {USER}  |将此引用替换为当前的USER环境变量值。
| $ {myVariablefoo}  |将此引用替换为名为"myVariable"的系统属性，或者替换为具有该名称的环境变量（如果有）或可选的默认值{{ 1}}，如果两者都没有定义。
| $ {os.name = Linuxfoo}  |如果os.name系统属性设置为"Linux"，则将此引用替换为"foo"，否则将引用替换为零长度字符串。如果未设置系统属性，则还会检查环境变量，并将任何值用于条件。
| $ {myProp！= myValfoo}  |如果myProp系统属性*not*设置为"myVal"，则将此引用替换为"foo"，否则请检查环境名为"myProp"的变量。如果发现条件为false，则用零长度字符串替换该引用。
| $ {shell：myVariable}  |将此引用转换为格式化为服务器操作系统shell的shell引用，然后将其写入tcat-env.conf文件。例如，非Windows操作系统上的$ {myVariable}和Windows上的％myVariable％。
|===

支持的条件运算符

[%header,cols="2*a",width=90%]
|===
| {算{1}}说明
|=或{== {1}}等于
|！=  |不等于
|  -  sw  |以开头
|  -  ew  |结束
|===

在条件中，Tcat Server还支持"NULL"的条件右侧值，即Java null。

BASH变量值替换语法"${FOO//bar/baz}"或"${FOO//gone/}"不会被处理/替换（除非系统属性名称或环境变量名称与整个事物匹配！），而是不加修改地返回， BASH shell可以稍后解释它。

环境变量引用和条件的合并和处理发生在将服务器配置文件应用于服务器时。当环境变量设置保存到服务器的tcat-env.conf文件中时，所有环境变量设置都将被格式化为服务器的本机外壳，并且这样做时，任何文件系统路径也都会被转换为外壳的本机格式。这与条件值一起使服务器配置文件环境变量设置成为多平台。

==  server.xml XML实体包含和catalina.properties引用

如果您需要通过多个Tomcat安装来管理server.xml配置，并且希望在每次安装时保持配置一致，则可以使用服务器配置文件。使用简单的Tomcat配置，您可以在所有服务器上使用相同的server.xml文件，因此您可以创建一个仅包含conf / server.xml文件的服务器配置文件，并且您可以在控制台的存储库中编辑server.xml并在每次需要更改时重新将服务器配置文件重新发布到您的服务器。

但是，在server.xml中配置更复杂的配置时，您将无法将同一个server.xml文件复制到所有服务器，因为XML配置设置的某些部分是特定于计算机的。在这种情况下，您可以将配置的特定机器部分分成一个单独的文件，该文件包含在server.xml中。您可以通过以下两种方式之一将其分开，具体取决于您需要的内容（仅限以下{{0}））：

* 您可以将您的server.xml文件视为特定于计算机的文件，并只插入您为所有服务器配置相同的配置部分。在这种情况下，您的服务器配置文件将包含一个文件，该文件具有server.xml配置的片段，而该配置文件不是特定于计算机的。
* 您可以将您的server.xml文件视为与所有服务器相​​同，并且所有计算机特定的配置片段或值都会从其他文件中包含。在这种情况下，您的服务器配置文件将包含conf / server.xml，并且您将拥有包含在机器特定配置中的server.xml中包含的其他配置文件。

有两种主要方法可以将机器特定的内容从server.xml中分离出来（您可以使用其中的一种或两种）：使用XML实体包括加载包含server.xml配置的一部分的单独文件以及使用catalina。属性来存储属性值，然后在server.xml属性值中引用它们。

以下是如何在Tomcat的server.xml中包含文件。在任何<?xml>声明行（这是可选的）之后，编辑您的server.xml，并在文件的最顶端，放入以下DOCTYPE声明来定义文件实体：

[source,xml, linenums]
----
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE server-xml [
  <!ENTITY connector1-config SYSTEM "connector1-config.xml">
]>
----

此标记表示此文档的名称为"server-xml"，我们正在定义一个名为"connector1-config"的新实体，XML分析器可在名为"connector1-config.xml"的文件中找到该实体。只要解析器接受你使用的字符，你就可以为你的实体命名。我建议只使用字母数字字符和短划线，以保持简单。事实证明，如果不指定文件的绝对路径，解析器会在与包含该文件的文件相同的目录中查找该文件，因此解析器将查找Tomcat的conf /目录。

但是，我们还没有使用我们在server.xml顶部定义的连接器XML实体。在我们希望解析器插入连接器的XML的文件中，我们只需要像这样写"@connector1-config;"：

[source,xml, linenums]
----
<Server ...>
    <Service ...>

        <!-- See conf/connector1-config.xml for this connector's config. -->
        &connector1-config;

    </Service>
</Server>
----

然后，创建conf / connector1-config.xml文件，并在其中放置`<Connector>`元素的配置。这样，连接器的配置就在一个单独的文件中。您的服务器配置文件可能会捆绑这些文件中的任何一个，并且可以轻松地自动更新配置的一部分，使其在多台服务器中保持一致。

另一种分离机器特定配置的方法是在`conf/catalina.properties`文件中定义属性，然后使用对server.xml文件中属性的引用。例如，您可以编辑catalina.properties并在文件末尾添加以下行：

[source, code, linenums]
----
tomcatHttpPort=8080
----

然后，在server.xml中，可以将它作为一个变量在Tomcat启动时插入，如下所示：

[source,xml, linenums]
----
<Server ...>
    <Service ...>

     <Connector port="${tomcatHttpPort}" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />

    </Service>
</Server>
----

同样，服务器配置文件可以包含catalina.properties文件或模板server.xml文件，然后服务器配置文件可以配置server.xml中的选择值，或者配置必须存在并且在所有服务器上保持一致的较大配置结构。

== 导入和导出服务器配置文件

您可以将您自己的服务器配置文件从Tcat服务器控制台导出到一个zip文件中以进行备份或与其他Tcat服务器控制台共享。在控制台中导航到服务器配置文件的页面，然后单击“导出”按钮。将您的服务器配置文件保存到本地硬盘上。您可以重命名该文件，它是一个简单的zip文件。最终文件名应包含服务器配置文件的名称（与控制台中显示的名称相匹配）以及服务器配置文件的版本号，以便人们可以使用zip文件名来区分同一服务器配置文件的不同修订版。

您也可以从文件导入服务器配置文件，以利用其他位置创建的自动化Tomcat配置。只需导航到最高级别的管理选项卡，然后单击左侧的服务器配置文件，然后单击从文件导入或从URL导入按钮。
