=  Tcat Server 6 R2发行说明

此页面描述了Tcat Server 6 R2中的更改，并包含此版本中的已知和已解决的问题。

== 新功能

此版本包含以下新功能：

*  *Server Profiles*：您现在可以使用服务器配置文件同时在多个Tomcat实例上设置环境变量和配置文件。有关更多信息，请参阅 link:/tcat-server/v/7.1.0/working-with-server-profiles[使用服务器配置文件]。
*  *Remote Server Restart*：您现在可以重新启动您使用Tcat Server管理的任何Tomcat实例。有关更多信息，请参阅 link:/tcat-server/v/7.1.0/working-with-servers[使用服务器]。
*  *Remote File Monitoring*：新的“文件”选项卡允许您查看和管理使用Tcat Server管理的任何服务器上的文件。有关更多信息，请参阅 link:/tcat-server/v/7.1.0/monitoring-a-server[监视服务器]。

== 已知问题

本节介绍此版本中的已知问题以及如何解决每个问题。

* 在Windows上安装Tcat Server时，无论您在安装程序中输入什么“开始”菜单组名称，开始菜单项都始终安装在组"Tcat Server 6"中。因此，如果您在同一台计算机上安装了多个Tcat Server实例，则只能使用这些“开始”菜单项来启动和停止安装的最后一个实例。要解决此问题，请使用命令提示符下的`bin`目录中的`tcat6 start`命令启动其他实例。
* 如果您通过VPN连接到网络，则Tcat Server不会自动检测未注册的服务器。要解决此问题，请在启动Tcat Server之前断开与VPN的连接，或手动添加服务器。
* 服务器注册时，它们将使用特定的IP地址进行注册。如果您正在使用无线连接的笔记本电脑上进行测试，并且您从一个位置移动到另一个位置，则您的IP地址可能会更改，并且服务器无法再与Tcat服务器通信。在这种情况下，您必须取消注册并重新注册具有当前IP地址的服务器。
* 如果您在Windows 2008上运行Internet Explorer 7，则可以登录到Tcat Server，但主屏幕不会显示。要解决此问题，请选择*File > Add this site to... > Trusted Sites*。
* 如果您在部署软件包时导航到另一个选项卡，则会中断部署。要解决此问题，请在导航到其他位置之前等待部署软件包。
* 如果您在Mozilla Firefox上增加字体大小，监视和诊断屏幕将消失。要解决此问题，请将字体大小设置为默认值。
* 查看应用程序的详细信息时，Sessions子选项卡上的会话搜索链接目前无法正常运行。
* 如果您不止一次下载安装程序，Firefox会将括号附加到文件名，这会在尝试运行安装程序时导致问题。如果您必须再次下载安装程序，请先删除原始文件，以便Firefox保留原始名称。
