= 故障处理
:keywords: tcat, troubleshoot, memory usage, applications, console

本页面介绍常见问题以及如何排除故障。

== 哪些工具可用于疑难解答？

您可以使用Tcat Server来检查内存使用情况，查看会话中的哪些对象以及它们的大小，查看部署描述符，查看线程以及查看JSP及其生成的代码。您可以通过单击“服务器”选项卡上的服务器并浏览显示服务器详细信息的选项卡来查看这些详细信息。要查看服务器上特定应用程序的详细信息，请在查看服务器详细信息时单击“应用程序”选项卡，然后单击应用程序名称。

有关更多信息，请参阅 link:/tcat-server/v/7.1.0/monitoring-a-server[监视服务器]和 link:/tcat-server/v/7.1.0/monitoring-applications[监测应用]。

== 问题：我的应用程序不再被认可

当服务器注册时，它们使用特定的IP地址进行注册。如果您正在使用无线连接的便携式计算机上进行测试，并且您从一个位置移动到另一个位置，则IP地址可能会更改，并且服务器无法与Tcat服务器通信。在这种情况下，您必须取消注册并重新注册具有当前IP地址的服务器。

== 问题：我的控制台不可用，我无法注销其服务器

要手动取消注册服务器，您必须删除其`webapps\agent\WEB-INF\truststore.jks`文件。然后服务器再次变为可用于在另一个控制台中注册。

== 问题：我的新安装的Tcat服务器实例正在运行，但它未显示在控制台的未注册组中

如果您连接到虚拟专用网络（VPN），则可能会干扰控制台中显示的新Tcat Server实例。断开与VPN的连接，重新启动Tcat Server实例，然后重试。您可以通过在浏览器中输入`http://<hostOrIPAddress>:<port>/agent`验证您的Tcat服务器代理是否正在运行，例如http：// localhost：8080 / agent（如果它位于本地计算机上）。如果您收到一条指示代理状态的消息，它正在运行。

在注册服务器之后，您可以重新连接到您的VPN。

== 问题：我的新安装的Tcat服务器实例正在运行并显示在控制台的未注册组中，但我无法注册

如果您的Tomcat安装中的`conf\server.xml`文件中没有设置HTTP连接器端口，则可能会发生这种情况，例如，如果您只是使用AJP端口通过HTTPD进行连接。您必须配置HTTP连接器端口，以便Tomcat可以与Tcat服务器通信。

== 问题：增加了字体大小和屏幕变白

如果您使用的是Firefox，并且使用加号（+）键按下Ctrl键以增加屏幕的放大倍数，则某些屏幕可能会变为空白。要解决此问题，请按Ctrl +减号键（ - ）缩小。

== 问题：我想在查看特定服务器的详细信息时更改可以从“文件”选项卡编辑哪些文件

“文件”选项卡可让您访问本地服务器上的文件以及远程服务器。要限制或启用对特定服务器上的目录的写入访问权限，请修改该服务器上的`agent/WEB-INF/spring-services.xml`文件，并从`accessControlFileService` Bean的`writeExcludes`属性中添加或删除目录。

link:/tcat-server/v/7.1.0/monitoring-applications[<<上一页：*监控应用程序*]

link:/tcat-server/v/7.1.0/managing-the-repository[下一步：*管理知识库* >>]
