= 从Tcat Server 6 R1升级到Tcat Server 6 R2
:keywords: tcat, upgrade, server, r1 to r2

此页面为正在从先前版本的Tcat Server 6升级到R2版本的用户提供重要信息。在整个此页面中，您的Tomcat安装目录称为`CATALINA_HOME`。有关此版本中更改内容的信息，请参阅 link:/tcat-server/v/7.1.0/release-notes-tcat-6-r2[发行说明Tcat 6 R2]。

== 通过安装程序升级

R2安装程序会自动升级您的Tcat安装。它会在安装目录中安装新的控制台和新代理WAR。它会将以前的控制台和代理备份到`CATALINA_HOME/tcat-backup-DATE`中，以防您需要回滚到以前的安装。

通常，安装程序不需要额外的步骤。但是，如果您使用LDAP或EC2插件，则必须按本页末尾所述执行一些手动步骤。

== 手动升级

要使用R2安装ZIP文件进行手动升级，请执行以下步骤。

. 停止Tomcat或Tcat Server实例。
. 将现有的Tomcat安装目录复制到备份文件。例如，在UNIX上，输入：
+
[source, code, linenums]
----
$ cp -a CATALINA_HOME CATALINA_HOME.bak
----
+
. 解压缩R2安装ZIP文件。例如，在UNIX上，输入：
+
[source, code, linenums]
----
$ unzip TcatServer-6.2.0.zip
----
+
. 将新代理，控制台和脚本复制到Tomcat安装目录。例如：
+
[source, code, linenums]
----
$ cd TcatServer-6.2.0
$ cp webapps/* CATALINA_HOME/webapps/
$ rm -rf CATALINA_HOME/webapps/console CATALINA_HOME/webapps/agent
$ mkdir -p CATALINA_HOME/webapps/console CATALINA_HOME/webapps/agent
$ unzip webapps/console.war -d CATALINA_HOME/webapps/console
$ unzip webapps/agent.war -d CATALINA_HOME/webapps/agent
$ cp CATALINA_HOME.bak/webapps/agent/WEB-INF/agent.properties CATALINA_HOME/webapps/agent/WEB-INF/
$ cp CATALINA_HOME.bak/webapps/agent/WEB-INF/truststore.jks CATALINA_HOME/webapps/agent/WEB-INF/
$ mkdir -p CATALINA_HOME/conf/Catalina/localhost
$ cp conf/Catalina/localhost/tcat* CATALINA_HOME/conf/Catalina/localhost
$ cp bin/tcat* CATALINA_HOME/bin
$ cp bin/catalina.sh CATALINA_HOME/bin
----
+
. 如果您的原始安装在`CATALINA_HOME`目录的根目录以外的任何位置创建了名为`galaxy-data`的目录，请立即将其移至您的`CATALINA_HOME`目录的根目录。例如：
+
[source, code, linenums]
----
$ mv CATALINA_HOME/bin/galaxy-data CATALINA_HOME/galaxy-data
----
+
. 清除您的`work`和`temp`目录。例如：
+
[source, code, linenums]
----
$ rm -rf CATALINA_HOME/temp/* CATALINA_HOME/work/*
----
+
. 将原始安装中的以下配置文件与新版本中的配置文件进行比较：`server.xml`，`conf/catalina.properties`，`conf/web.xml`，`conf/context.xml`，`conf/tomcat-users.xml` ，和`conf/logging.properties`。如果有差异，您应该考虑是否应该将这些更改合并到您的安装中。例如，要比较UNIX上的`server.xml`：
+
[source, code, linenums]
----
$ diff -u conf/server.xml CATALINA_HOME/server.xml
----
+
. 为运行时树设置正确的所有权和组（您必须拥有超级用户权限才能执行此步骤）。例如：
+
[source, code, linenums]
----
# chown -R tomcat:tomcat CATALINA_HOME
----
+
. 如果您使用的是LDAP或Amazon EC2插件，请参阅以下有关如何完成升级的说明。

您现在已准备好启动您的Tcat服务器。

==  LDAP升级

要将先前的LDAP配置文件从备份迁移到新的Tcat Server安装，必须将LDAP配置文件复制到新的安装中，然后将LDAP JAR复制到控制台Web应用程序。

=== 复制LDAP配置文件

如果您使用安装程序进行升级，则可以通过将`tcat-backup-DATE/console/WEB-INF/classes/ldap.xml`复制到`CATALINA_HOME/webapps/console/WEB-INF/classes`目录来恢复配置。例如，在UNIX上，输入：

[source, code, linenums]
----
$ cd CATALINA_HOME
$ cp tcat-backup-DATE/console/WEB-INF/classes/ldap.xml webapps/console/WEB-INF/classes
----

如果您手动升级，则可以通过将`webapps/console/WEB-INF/classes/ldap.xml`从备份文件复制到`CATALINA_HOME/webapps/console/WEB-INF/classes`目录来恢复配置。例如，在UNIX上，输入：

[source, code, linenums]
----
$ cd CATALINA_HOME
$ cp CATALINA_HOME.bak/webapps/console/WEB-INF/classes/ldap.xml webapps/console/WEB-INF/classes
----

=== 将LDAP JAR复制到控制台Webapp中

您必须按照 link:/tcat-server/v/7.1.0/integrating-with-ldap[通过LDAP启用身份验证]中所述将新的LDAP JAR安装到控制台webapp中。

==  Amazon EC2插件升级

Tcat R1的Amazon EC2插件与R2不兼容。您必须下载新版本的插件并按照 link:/tcat-server/v/7.1.0/deploying-to-amazon-ec2[亚马逊EC2说明]进行安装。
