= 升级到Tcat Server 6 R4
:keywords: tcat, upgrade, r4

如果您安装了较旧版本的Tcat Server，则新安装程序会保留已保存的所有配对服务器，新Web应用程序，用户角色，服务器配置文件和环境变量。

如果您使用R3之前的Tcat Server 6版本，则需要遵循升级路径 link:/tcat-server/v/7.1.0/upgrading-to-6.3[R3先]。

[WARNING]
====
*NOTE*

Tcat Server 6.4.5控制台不能与旧版Tcat的代理向后兼容。
这意味着您必须在启动新的Tcat服务器控制台之前将每个代理Web应用程序升级到6.4.5版本或更新版本。这样做不需要中断来自Tcat或Tomcat服务器实例的常规Web服务。

按着这些次序：

. 将任何webapps / agent / WEB-INF / truststore.jks文件复制到备份位置。
. 删除webapps / agent.war文件。
. 等待约十秒钟，代理自动取消部署。
. 将新的agent.war复制到您的webapps /目录以部署新副本。
. 将备份的truststore.jks移回到webapps / agent / WEB-INF目录中。
====

从https://www.mulesoft.com/tcat/download下载适用于Windows（.exe），Linux和Solaris（.sh）或Mac OS（.dmg）的Tcat服务器安装程序。

== 运行安装程序

. 运行安装程序
. 指向现有的应用程序安装目录
. 安装程序会保留您的所有现有设置。

[WARNING]
====
*NOTE*

升级Tcat服务器并重新登录到Web浏览器中的*before*到Tcat服务器控制台后，请确保您*clear your browser's file cache*。在不清除浏览器缓存的情况下，控制台Web应用程序无故障运行，但旧版本的Tcat控制台代码仍驻留在Web浏览器中，与控制台的新服务器端不匹配，这会在Tcat控制台中导致错误日志和网络浏览器中的不稳定行为。
====

== 安装程序的功能

Tcat Server 6 R4安装程序执行以下任务：

. 备份代理Web应用程序（将Web应用程序/代理复制到tcat-backup / agent）并解包新的应用程序
. 备份控制台Web应用程序（将webapp / console复制到tcat-backup / console）并解压缩新的
. 备份conf目录树中的所有用户修改的Tomcat配置文件（将conf复制到tcat-backup / conf）
. 保留定义代理监听哪个端口的旧agent.properties
. 保留提供与代理关联的安全设置的代理truststore.jks

安装程序完成升级后，将conf目录中的新Tcat服务器配置文件与tcat-backup / conf中的旧配置文件进行比较，以确定要将哪些更改结转到新的Tcat服务器配置中。

link:/tcat-server/v/7.1.0/installation[<<上一页：*安装*]

link:/tcat-server/v/7.1.0/installing-multiple-tcat-instances-on-a-single-machine[Next：*单机上的多个实例* >>]
