= 升级到Tcat Server 6 R2 P1
:keywords: tcat, upgrade, r2 p1

此页面为从Tcat Server 6 R2升级到R2 P1版本的用户提供重要信息。在整个此页面中，您的Tomcat安装目录称为`CATALINA_HOME`。有关此版本中更改内容的信息，请参阅 link:/tcat-server/v/7.1.0/release-notes-tcat-6-r2[发行说明Tcat 6 R2]。

== 通过安装程序升级

R2 P1安装程序会自动升级您的Tcat安装。它会在安装目录中安装新的控制台和新代理WAR。它会将以前的控制台和代理备份到`CATALINA_HOME/tcat-backup-DATE`中，以防您需要回滚到以前的安装。

首先，停止Tomcat或Tcat Server实例。

在运行安装程序之前，请备份您的配置文件，如下所示：

[source, code, linenums]
----
# cp $CATALINA_HOME/conf/server.xml ~/
# cp $CATALINA_HOME/conf/tomcat-users.xml ~/
# cp $CATALINA_HOME/conf/catalina.policy ~/
# cp $CATALINA_HOME/conf/catalina.properties ~/
# cp $CATALINA_HOME/conf/context.xml ~/
# cp $CATALINA_HOME/conf/logging.properties ~/
# cp $CATALINA_HOME/conf/web.xml ~/
----

然后，您可以运行安装程序，并在现有的Tcat Server安装上安装新的Tcat Server版本。

安装程序完成安装Tcat Server之后，可能需要使用先前配置文件中的先前配置设置。

如果您尚未修改conf /目录中的配置文件，请从这个新版本的Tcat Server重新开始库存配置文件，在这种情况下，您不需要执行如下所示的配置文件复制。

通常，如果您手动修改了任何配置文件，则应该使用差异和合并工具来检查备份配置文件和库存Tcat Server 6 R2 P1副本之间的差异，并仔细地将更改合并到新的副本。

以下是您可以遵循的程序：

. 从备份的文件恢复以前的配置：
+
[source, code, linenums]
----
# cp ~/tomcat-users.xml $CATALINA_HOME/conf/tomcat-users.xml
# cp ~/context.xml $CATALINA_HOME/conf/context.xml
# cp ~/catalina.properties $CATALINA_HOME/conf/catalina.properties
# cp ~/logging.properties $CATALINA_HOME/conf/logging.properties
----
+
. 确保您的`conf/catalina.properties`有一个common.loader定义，如下所示：
+
[source, code, linenums]
----
common.loader=${catalina.base}/lib,${catalina.base}/lib/*.jar,${catalina.home}/lib,${catalina.h
----
+
. 将备份的`server.xml`复制到位：
+
[source, code, linenums]
----
# cp ~/server.xml $CATALINA_HOME/conf/server.xml
----
+
. 编辑您的server.xml以将此`<Listener>`包含在server.xml顶部附近的侦听器元素中（侦听器元素在文件中列出的顺序无关紧要）：
+
[source, xml, linenums]
----
<!-- Prevent memory leaks due to use of particular java/javax APIs-->
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
----
+
. 使用差异工具合并来自备份的`catalina.policy`和`web.xml`文件的任何更改。
. 修改/编辑您的所有代理Web应用程序中的`agent.properties`文件，以便报告其版本号为"6.2.1"。在非Windows操作系统上，可以使用以下sed命令来执行此操作：
+

[source, code, linenums]
----
# sed -i.bak -e 's/6\.2\.0/6.2.1/g' $CATALINA_HOME/webapps/agent/WEB-INF/agent.properties
----
+
. 启动您的Tomcat或Tcat服务器实例。
. 清除您的Web浏览器缓存，并登录到Tcat服务器控制台。登录后，在页脚中查找"Copyright 2015 MuleSoft, Inc."。如果您仍然看到较早的一年，则很可能您的Web浏览器的缓存仍显示控制台Web应用程序的旧版本。

如果您使用的是LDAP或EC2插件，则必须执行本页末尾所述的手动步骤。

== 手动升级

要使用R2 P1安装ZIP文件手动升级，请执行以下步骤。

. 停止Tomcat或Tcat Server实例。
. 将现有的Tomcat安装目录复制到备份文件。例如，在非Windows操作系统上，键入：
+
[source, code, linenums]
----
# cp -a $CATALINA_HOME $CATALINA_HOME.bak
----
+
. 从您的`webapps/`目录中删除以前版本的Tcat Server控制台和代理webapps：
+
[source, code, linenums]
----
# cd $CATALINA_HOME/webapps
# rm -r console console.war agent agent.war
----
+
. 将R2 P1安装ZIP文件解压缩到您现有的Tcat Server安装中。例如，在非Windows操作系统上，键入：
+
[source, code, linenums]
----
# cd /opt
# unzip ~/TcatServer-6.2.1.zip
----
+
. 如果您尚未修改conf /目录中的配置文件，则应该从此新版本的Tcat Server重新开始库存配置文件，在这种情况下，您不需要执行配置文件复制如下所示。
+
通常，如果您手动修改了任何配置文件，则应该使用差异和合并工具来检查备份配置文件和库存Tcat Server 6 R2 P1副本之间的差异，并仔细地将更改合并到新的副本，你使用。
+
以下是您可以遵循的程序：
从备份的文件恢复以前的配置：
+
[source, code, linenums]
----
# cp ~/tomcat-users.xml $CATALINA_HOME/conf/tomcat-users.xml
# cp ~/context.xml $CATALINA_HOME/conf/context.xml
# cp ~/catalina.properties $CATALINA_HOME/conf/catalina.properties
# cp ~/logging.properties $CATALINA_HOME/conf/logging.properties
----
+
. 确保您的`conf/catalina.properties`有一个common.loader定义，如下所示：
+
[source, code, linenums]
----
common.loader=${catalina.base}/lib,${catalina.base}/lib/*.jar,${catalina.home}/lib,${catalina.home}/lib/*.jar
----
+
. 将备份的`server.xml`复制到位：
+
[source, code, linenums]
----
# cp ~/server.xml $CATALINA_HOME/conf/server.xml
----
+
. 编辑您的server.xml以将此`<Listener>`包含在server.xml顶部附近的侦听器元素中（侦听器元素在文件中列出的顺序无关紧要）：
+
[source, xml, linenums]
----
<!-- Prevent memory leaks due to use of particular java/javax APIs-->
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
----
+
. 使用差异工具合并来自备份的`catalina.policy`和`web.xml`文件的任何更改。
. 在您的所有代理Web应用程序中修改/编辑您的agent.properties文件，以便报告其版本号为"6.2.1"。在非Windows操作系统上，可以使用以下sed命令来执行此操作：
+
[source, code, linenums]
----
# sed -i.bak -e 's/6\.2\.0/6.2.1/g' $CATALINA_HOME/webapps/agent/WEB-INF/agent.properties
----
+
. 将您的代理商的`truststore.jks`文件复制到新安装中：
+
[source, code, linenums]
----
$ cp $CATALINA_HOME.bak/webapps/agent/WEB-INF/truststore.jks CATALINA_HOME/webapps/agent/WEB-INF/
----
+
. 修改/编辑您的所有代理Web应用程序中的`agent.properties`文件，以便报告其版本号为"6.2.1"。在非Windows操作系统上，可以使用以下sed命令来执行此操作：
+
[source, code, linenums]
----
# sed -i.bak -e 's/6\.2\.0/6.2.1/g' $CATALINA_HOME/webapps/agent/WEB-INF/agent.properties
----
+
. 如果您的原始安装在`CATALINA_HOME`目录的根目录以外的任何位置创建了名为`galaxy-data`的目录，请立即将其移至您的`CATALINA_HOME`目录的根目录。例如：
+
[source, code, linenums]
----
$ mv $CATALINA_HOME/bin/galaxy-data $CATALINA_HOME/galaxy-data
----
+
. 清除您的`work`和`temp`目录。例如：
+
[source, code, linenums]
----
$ rm -rf $CATALINA_HOME/temp/* $CATALINA_HOME/work/*
----
+
. 为运行时树设置正确的所有权和组（您必须拥有超级用户权限才能执行此步骤）。例如：
+
[source, code, linenums]
----
# chown -R tomcat:tomcat $CATALINA_HOME
----
+
. 启动您的Tomcat或Tcat服务器实例。
. 清除您的Web浏览器缓存，并登录到Tcat服务器控制台。登录后，在页脚中查找"Copyright 2015 MuleSoft, Inc."。如果您仍然看到较早的一年，则很可能您的Web浏览器的缓存仍显示控制台Web应用程序的旧版本。

如果您使用的是LDAP或Amazon EC2插件，请参阅以下有关如何完成升级的说明。

==  LDAP升级

要将先前的LDAP配置文件从备份迁移到新的Tcat Server安装，必须将LDAP配置文件复制到新的安装中，然后将LDAP JAR复制到控制台Web应用程序。

=== 复制LDAP配置文件

如果您使用安装程序进行升级，则可以通过将`tcat-backup-DATE/console/WEB-INF/classes/ldap.xml`复制到`CATALINA_HOME/webapps/console/WEB-INF/classes`目录来恢复配置。例如，在UNIX上，输入：

[source, code, linenums]
----
$ cd $CATALINA_HOME
$ cp tcat-backup-DATE/console/WEB-INF/classes/ldap.xml webapps/console/WEB-INF/classes
----

如果您手动升级，则可以通过将`webapps/console/WEB-INF/classes/ldap.xml`从备份文件复制到`CATALINA_HOME/webapps/console/WEB-INF/classes`目录来恢复配置。例如，在UNIX上，输入：

[source, code, linenums]
----
$ cd $CATALINA_HOME
$ cp $CATALINA_HOME.bak/webapps/console/WEB-INF/classes/ldap.xml webapps/console/WEB-INF/classes
----

=== 将LDAP JAR复制到控制台Webapp中

您必须按照 link:/tcat-server/v/7.1.0/integrating-with-ldap[通过LDAP启用身份验证]中所述将新的LDAP JAR安装到控制台webapp中。

==  Amazon EC2插件升级

Tcat R1的Amazon EC2插件与R2不兼容。您必须下载新版本的插件并按照 link:/tcat-server/v/7.1.0/deploying-to-amazon-ec2[亚马逊EC2说明]进行安装。
