= 使用HTTP AtomPub API
:keywords: tcat, http, atompub, api

Tcat Server为其大部分集成API利用简单但强大的Atom发布协议。它是一个基于_collections_和_entries_概念的基于RESTful HTTP的API。 AtomPub集合可以存储任何东西。 Tcat Server API使用Atom条目来表示Tcat Server注册表（存储库）内的工件。通过Atom发布协议，可以创建，更新和删除新项目。

== 重要的供稿网址

Tcat Server包含以下供稿：

[%header,cols="2*a",width=90%]
|===
| {饲料{1}} URL
|根工作区列表和搜索 | {{[+ http：// host / api / registry +]}}
|工作区列表 | {{[+ http：// host / api / registry / +]`+

<workspacePath>}}
|子工作区 | {{[+ http：// host / api / registry / +] +

<workspacePath>;工作空间}}
|工件版本 | {{[+ http：// host / api / registry / +] +

<workspacePath> / <item>;历史}}
| {评论{1}} {{[+ HTTP：//主机/ API /评论+]

}}
|===

作为Atom条目的== 个工件

上面列出的每个提要都包含一系列代表存储库内部工件的Atom条目。一个神器可能看起来像这样：

[source, xml, linenums]
----
<entry>
  <link href="/api/registry/Default%20Workspace/hello.wsdl;atom" rel="edit" />
  <id>urn:galaxy:artifact:local$720ea69f-14ac-44ac-8171-1e4de567a098</id>
  <title type="text">hello.wsdl</title>
  <updated>2008-10-31T21:16:16.272Z</updated>
  <author>
    <name>Galaxy</name>
  </author>
  <summary type="xhtml">This is a description of the WSDL</summary>

  <artifact-info xmlns="http://galaxy.mule.org/1.0"
                 mediaType="application/xml"
                 documentType="{http://schemas.xmlsoap.org/wsdl/}definitions"
                 created="2008-10-31T21:16:16.272Z" name="hello.wsdl" />

  <version xmlns="http://galaxy.mule.org/1.0"
           label="0.1"
           enabled="true"
           default="true"
           created="2008-10-31T21:16:16.272Z" />

  <metadata xmlns="http://galaxy.mule.org/1.0" id="versioned">
    <property name="wsdl.binding.dependencies" locked="true" visible="true">
      <value>{http://mule.org/hello_world}HelloWorldBinding</value>
    </property>
    <property name="wsdl.binding" locked="true" visible="true">
      <value>HelloWorldBinding</value>
    </property>
    <property name="wsdl.service" locked="true" visible="true">
      <value>HelloWorldService</value>
    </property>
    <property name="wsdl.targetNamespace" locked="true" visible="true" value="http://mule.org/hello_world" />
    <lifecycle property="primary.lifecycle" name="Default" phase="Created">
      <next-phases>Developed</next-phases>
      <previous-phases />
    </lifecycle>
    <property name="wsdl.endpoint" locked="true" visible="true">
      <value>SoapPort</value>
    </property>
    <property name="wsdl.portType.dependencies" locked="true" visible="true">
      <value>{http://mule.org/hello_world}HelloWorld</value>
    </property>
  </metadata>

  <metadata xmlns="http://galaxy.mule.org/1.0" id="global" />

  <collection xmlns="http://www.w3.org/2007/app" id="versions" href="/api/hello.wsdl;history">
    <atom:title xmlns:atom="http://www.w3.org/2005/Atom" type="text">Artifact Versions</atom:title>
  </collection>

  <content type="application/xml" src="/api/registry/Default%20Workspace/hello.wsdl" />
  <link href="/api/registry/Default%20Workspace/hello.wsdl" rel="edit-media" />
</entry>
----

通过这个Atom条目，需要注意一些重要的事情：

* 具有`id="versions"`属性的`<collection>`元素提供了指向工件版本历史记录的链接。
* 要查看实际的工件，请使用`<content>`元素中提供的链接。
* 摘要将映射到工件上的描述字段。
*  `<metadata>`部分表示与此工件关联的元数据。
** 带`global` ID的`<metadata>`表示与工件的所有版本关联的元数据。
** 带有`versioned` ID的`<metadata>`表示与此特定版本关联的元数据。
** 生命周期属性由`<lifecycle>`元素表示。
** 如果属性是多值属性，则会有子元素`<value>`。如果它是单值的，将会有`value`属性。
** 如果该属性的`locked`属性设置为true，则该属性已由索引创建，并且只有通过索引才能被修改。

== 工件历史记录供稿

可以通过将`;history`附加到其网址来查看商品的历史记录。例如，如果这是工件URL：

[source, code, linenums]
----
http://localhost:9002/api/registry/Services/hello.wsdl
----

历史URL是：

[source, code, linenums]
----
http://localhost:9002/api/registry/Services/hello.wsdl;history
----

历史URL将返回包含每个工件版本的Atom条目的提要，如上一节中所述。

== 使用库

要在您的Java应用程序中使用AtomPub API，我们建议使用 link:http://incubator.apache.org/abdera/[Apache Abdera框架]。其他工具（如`wget`）也可以使用。要获得更直观的指导，请查看lnk： http://www.xucia.com/#RestTest[RestTest] FireFox插件。

有关使用Abdera的更深入示例，请参阅AtomPub API示例。

== 工件操作

下表总结了可以在AtomPub API上执行的操作。

[%header,cols="4*"]
|===
| HTTP动词 |网址 |数据 |说明
| GET  | / api / registry  |无 |获取存储库中的所有工件
| GET  | / api / registry / WORKSPACE  |无 |获取工作区内工件和工作区的Atom订阅源
| GET  | / api / registry / WORKSPACE; atom  |无 |获取工作空间的Atom条目表示
| GET  | / api / registry / WORKSPACE / ARTIFACT  |无 |获取工件
| POST  | / api / registry / WORKSPACE  |一件神器 |添加一个新的神器。详情请参阅下文。
| POST  | / api / registry / WORKSPACE;工作区 |工作区Atom条目 |创建新的工作区。详情请参阅下文。
| PUT  | / api / registry / WORKSPACE / ARTIFACT  |工件 |添加工件的新版本。详情请参阅下文。
| PUT  | / api / registry / WORKSPACE / ITEM;原子 |工件的原子表示 |更新注册表中工件的元数据
|删除 | / api / registry / WORKSPACE  |工件或工作空间 |删除工件或工作空间
|===

== 浏览存储库

本节介绍如何通过查询参数或URL编码浏览存储库。

=== 查询存储库

您可以使用查询参数扩展URL以搜索存储库。以下是一些示例查询。

==== 选择所有XML模式构件

*Query*：

[source, code, linenums]
----
select artifact where documentType = {http://www.w3.org/2001/XMLSchema}schema
----

*URL*：

[source, code, linenums]
----
http://localhost:8080/api/registry?q=select%20artifact%20where%20documentType%20=%20%7Bhttp://www.w3.org/2001/
XMLSchema%7Dschema
----

==== 选择所有JAR构件

*Query*：

[source, code, linenums]
----
select artifact where contentType = 'application/java-archive'
----

*URL*：

[source, code, linenums]
----
http://localhost:8080/api/registry?q=select%20artifact%20where%contentType%20=%20'application/java-archive
----

=== 网址编码

如果您为客户端代码使用 http://incubator.apache.org/abdera[阿布德拉]，则方便的`org.apache.abdera.i18n.text.UrlEncoding`类具有可以为您执行此操作的编码方法：

[source, code, linenums]
----
import org.apache.abdera.i18n.text.UrlEncoding;
import org.apache.abdera.i18n.text.CharUtils.Profile;

String encodedQuery = UrlEncoding.encode("select artifact where ...", Profile.PATH.filter());
----

*Note*：如果您使用的是Abdera 0.3.0，则必须使用`EncodingUtil.sanitize()`方法。

有关哪些字符必须进行网址编码的参考信息，请参阅 link:http://www.blooberry.com/indexdot/html/topics/urlencoding.htm[这一页]。

将查询中的任何这些字符替换为适当的编码字符。例如，如果您编码的是"select artifact"，则可以用`%20`替换空格，因为这是空格字符的URL编码表示形式。

== 添加工件

当您添加工件时，您必须提供指定工作空间和工件版本的其他HTTP标头：

*  "X-Artifact-Version"：您正在发布的工件的版本标签。
*  "Slug"标题：用于确定存储库中工件的名称。

一个典型的HTTP POST看起来像这样：

[source, code, linenums]
----
POST /api/registry/WORKSPACE HTTP/1.0
Authorization: Basic YWRtaW46YWRtaW4=
Host: localhost:8080
Content-Type: text/plain
X-Artifact-Version: 1.0
Slug: test.txt
----

以下是使用`wget`的示例：

[source, code, linenums]
----
$ wget --post-file=YOURFILE --http-user=admin --http-password=admin -S \
--header="X-Artifact-Version: 0.1" \
--header="Slug: ARTIFACT_NAME"
http://localhost:8080/api/registry/Default%20Workspace
----

=== 添加新的工件版本

添加新的工件版本与添加新的工件非常相似，但以下情况除外：

* 使用PUT动词
* 使用存储库中工件的URL
* 指定X-Artifact-Version标头

例如：

[source, code, linenums]
----
PUT /api/registry/WORKSPACE/ARTIFACT HTTP/1.0
Authorization: Basic YWRtaW46YWRtaW4=
Host: localhost:8080
Content-Type: text/plain
X-Artifact-Version: 0.2

... data ...
----

== 添加工作区

要添加工作区，请将表示工作区的Atom条目发布到父级工作区。例如：

[source, code, linenums]
----
POST /api/registry/Default%20Workspace;workspaces HTTP/1.0
Authorization: Basic YWRtaW46YWRtaW4=
Host: localhost:8080
Content-Type: application/atom+xml;type=entry

<entry xmlns="http://www.w3.org/2005/Atom">
  <title type="text">MyNewWorkspace</title>
  <updated>2015-08-10T01:12:38.758Z</updated>
  <author>
    <name>Ignored</name>
  </author>
  <id>urn:uuid:8D931B8E837772B5521204074758762</id>
  <content type="text"></content>
</entry>
----

这会在父级工作空间"Default Workspace"中创建一个名为"MyNewWorkspace"的新工作空间。

要添加顶级工作区，请将POST添加到`/api/registry`。此工作空间在`/api/registry;workspaces`中列出。

== 编辑工件的元数据

要编辑工件的元数据，请将新的Atom条目表示放入工件URL。您可以更新工件的描述，元数据和生命周期信息。

例如，您可以使用此HTTP请求来更新工件的描述：

[source, code, linenums]
----
PUT /api/registry/Default%20Workspace/hello.wsdl;atom HTTP/1.0
Authorization: Basic YWRtaW46YWRtaW4=
Host: localhost:8080
Content-Type: application/atom+xml;type=entry

<entry xmlns="http://www.w3.org/2005/Atom">
  <link href="/api/registry/Default%20Workspace/hello_world.wsdl;atom?version=0.2" rel="edit" />
  <id>urn:galaxy:artifact:50d245b3-8855-4d4d-83f6-2351ae0b23b6:0.2</id>
  <title type="text">hello_world.wsdl Version 0.2</title>
  <updated>2015-08-10T00:57:07.116Z</updated>
  <author>
    <name>Galaxy</name>
  </author>
  <summary type="xhtml">
    This  becomes your new artifact description.
  </summary>
  <content type="application/xml" src="/api/registry/Default%20Workspace/hello_world.wsdl?version=0.2" />
  <link href="/api/registry/Default%20Workspace/hello_world.wsdl?version=0.2" rel="edit-media" />
</entry>
----

*Note*：您必须将其放到Atom表示形式，这意味着您必须将`;atom`附加到URL。

要编辑工件的元数据，您需要在您的Atom条目中包含一个`<metadata>`元素。此元素内的任何`<property>`元素都会被修改。在以下示例中，属性`favoriteSauce`被添加到工件，其值为`ketchup`。

[source,xml, linenums]
----
<entry>
...
<metadata id="versioned" xmlns="http://galaxy.mule.org/1.0">
  <property name="favoriteSauce" value="ketchup"/>
</metadata>
...
</entry>
----
任何不存在的元数据属性都不会被删除。要删除元数据属性，请删除所有值属性和子元素：

[source,xml, linenums]
----
<metadata id="versioned" xmlns="http://galaxy.mule.org/1.0">
  <property name="propertyToDelete" />
</metadata>
----

link:/tcat-server/v/7.1.0/scripting-examples[<<上一页：*脚本示例*]

Next：*AtomPub API Example* >>
