= 将Cloudcat与Amazon EC2配合使用
:keywords: tcat, cloudcat, amazon, ec2, gogrid, mysql


MuleSoft Cloudcat是云中的企业级Apache Tomcat。 Cloudcat是完全支持的虚拟映像（Amazon EC2 AMI），可让您将Tomcat应用程序部署到云中。 Cloudcat在Ubuntu Linux上包含一个预配置的MySQL数据库的Apache Tomcat。

如果您使用MuleSoft Tcat Server，则可以使用Tcat Server控制台管理您的Cloudcat实例。 Cloudcat用户可以获得无限的电子邮件支持。


[TIP]
====
*Ready to get started?*
只要确保您符合先决条件，然后按照以下四个简单步骤操作即可！
====


如果您想使用GoGrid而不是Amazon EC2，请参阅 link:/tcat-server/v/7.1.0/using-cloudcat-with-gogrid[在GoGrid中使用Cloudcat]。如果您想使用EC2插件将自己的Tomcat版本作为AMI上传到EC2，请参阅 link:/tcat-server/v/7.1.0/deploying-to-amazon-ec2[部署到Amazon EC2]。


== 先决条件

在Amazon EC2上使用Cloudcat之前，您必须满足以下先决条件：

*  Ubuntu命令的基本知识。
* 亚马逊EC2安全组。
亚马逊EC2帐户* 。
* 如果您手动打开端口而不是安全组，请下载EC2工具。

== 购买Cloudcat订阅

如果您尚未购买Cloudcat订阅，请执行以下操作：

. 购买Cloudcat订购 link:https://aws-portal.amazon.com/gp/aws/user/subscription/index.html?offeringCode=8667D160[这里]。如果出现提示，请输入您的凭证和付款信息并完成购买。
. 在注册页面上输入您的信息，然后点击*Register*。

== 创建一个Cloudcat实例

要使用Cloudcat，您需要根据购买的Cloudcat AMI创建一个新实例。您将输入以下AMI ID之一，具体取决于您希望为实例使用多少内存：

*  32位AMI：`ami-adf01cc4`
*  64位AMI：`ami-61f71b08`

例如，您可以使用AWS管理控制台创建实例，如下所示：

. 启动 link:https://console.aws.amazon.com/ec2/home[AWS管理控制台]以创建一个或多个新实例。
. 在控制台中，点击左侧导航窗格中的*AMIs*，然后在文本框中输入AMI ID，然后按*Enter*。
. 选择AMI并点击*Launch*。
. 按照向导中的说明创建您的实例。当被要求指定一个安全组时，您可以选择一个现有的组（例如默认），或者为Cloudcat创建一个新的安全组，以打开您的HTTP和TCP端口（默认为8080和51443）。然后，您可以使用此安全组创建所有Cloudcat实例，并自动为所有这些端口打开所需的端口。请注意，您可以通过修改`server.xml`文件并重新启动Tomcat来更改实例上Tomcat的默认HTTP和TCP端口。在这种情况下，您必须打开新端口而不是默认端口。

完成向导中的指示后，将创建实例，这可能需要几分钟的时间。然后，Tomcat将从该实例的`/opt/tomcat`开始。您现在已准备好将应用程序部署到您的Cloudcat实例中的Tomcat。如果您想使用Tcat Server来管理您的实例并部署您的应用程序，请参阅下一节。

== 使用Tcat服务器管理Cloudcat实例

Cloudcat包括Tcat服务器代理，因此您可以将Cloudcat实例与您的Tcat服务器实例配对，并通过Tcat服务器控制台进行管理。

要启用对Tcat服务器的访问：

使用以下语法将.  SSH登录到您的远程Cloudcat实例：`ssh -i <your private key> ubuntu@ec2-<public address>`其中`<your private key>`是您为EC2帐户设置的私钥，`<public address>`是实例的地址。在Amazon控制台中，当您单击实例时，公共地址将显示在底部窗格中。
. 如果您的远程Tomcat服务器实例已停止（它在创建实例时自动启动），请立即通过输入以下命令启动它：`sudo /etc/init.d/tomcat start`
. 如果未通过安全组打开HTTP和TCP端口，则必须通过输入以下命令在远程实例上手动打开它们：`$ ec2-authorize -p <port> <securityGroup>`其中`<securityGroup>`是您在创建实例时指定的组。

要注册远程Tomcat：

. 启动您的本地Tcat服务器实例和控制台。
. 在控制台的服务器选项卡上，点击*New Server*。
. 为服务器指定一个唯一的名称，输入网址`+http://<public address>:8080/agent+`（用实例的公开地址替换`<public address>`），然后点击*Register*。

您现在已准备好从本地Tcat服务器控制台管理Cloudcat实例。有关更多信息，请参阅 link:/tcat-server/v/7.1.0/monitoring-a-server[监视服务器]。

== 将Tomcat应用程序部署到Cloudcat

在设置Cloudcat之后，您可以开始在云中部署Tomcat应用程序。您可以手动将当前应用程序部署到Cloudcat，只需从本地Tomcat服务器复制应用程序WAR文件并将它们粘贴到EC2或GoGrid上的Cloudcat实例的webapps目录中即可，或者可以使用Tcat Server控制台执行部署和组态。有关使用Tcat Server进行部署的更多信息，请参阅 link:/tcat-server/v/7.1.0/deploying-applications[部署应用程序]。

请注意，您的Web应用程序可能需要特定配置，包括配置MySQL驱动程序。您可以使用Tcat Server中的服务器配置文件在Cloudcat实例上进行配置更改。有关详情，请参阅 link:/tcat-server/v/7.1.0/working-with-server-profiles[使用服务器配置文件]。

将Web应用程序部署到Cloudcat实例后，手动或通过Tcat Server控制台重新启动Cloudcat，然后在云中测试您的应用程序。

== 获取对Cloudcat的支持

您的订阅包括通过电子邮件的无限支持要请求支持，请将您的查询发送到tcat-install@mulesoft.com，支持代表将与您联系。
