= 在GoGrid中使用Cloudcat
:keywords: tcat, cloudcat, gogrid

MuleSoft Cloudcat是云中的企业级Apache Tomcat。 Cloudcat是一个完全支持的虚拟映像，允许您将Tomcat应用程序部署到云中。 Cloudcat在Ubuntu Linux上包含一个预配置的MySQL数据库的Apache Tomcat。

如果您使用MuleSoft Tcat Server，则可以使用Tcat Server控制台管理您的Cloudcat实例。 Cloudcat用户可以获得无限的电子邮件支持。

[TIP]
====
*Ready to get started?*
只要确保你符合先决条件，然后按照以下六个简单的步骤！
====

== 先决条件

在GoGrid上开始使用Cloudcat之前，您必须满足以下先决条件：

*  Ubuntu命令的基本知识
* 使用GoGrid的基本知识
GoGrid帐户* 

== 创建一个Cloudcat实例

要使用Cloudcat，可以根据可用的32位或62位图像创建一个新实例，具体取决于您希望为实例使用多少内存。

要创建实例：

. 登录GoGrid。
. 单击**Add > Image Sandbox**，导航到Cloudcat映像（可以在名称框中键入Cloudcat以快速找到它们），然后选择要使用的映像。
. 输入您正在创建的实例的名称和说明，然后选择您要使用的公共IP地址。您可以开始输入IP地址，并会显示分配给您帐户的有效地址列表。
. 点击*Save*。 GoGrid创建实例（这可能需要几分钟）。准备就绪后，实例顶部的点会从琥珀色变为红色。
. 通过右键单击实例并选择*Start*来启动实例。实例准备就绪后，其点将变为绿色。 Tomcat在实例上的`/opt/tomcat`中自动启动。
. 选择*Tools > Passwords*并记下为此实例分配给root用户的密码GoGrid。使用SSH访问实例时，您将需要此密码。

您现在已准备好将应用程序部署到您的Cloudcat实例中的Tomcat。如果您想使用Tcat Server来管理您的实例并部署您的应用程序，请参阅下一节。

== 使用Tcat服务器管理Cloudcat实例

Cloudcat包括Tcat服务器代理，因此您可以将Cloudcat实例与您的Tcat服务器实例配对，并通过Tcat服务器控制台进行管理。

要启用对Tcat服务器的访问：

. 在您的控制台中，使用命令`ssh root@<public address>`，其中`<public address>`是您为该实例指定的公共IP地址，然后在出现提示时输入密码。
. 输入以下命令打开端口51443：

[source, code, linenums]
----
iptables -I INPUT 1 -i eth0 -p tcp -m tcp --dport 51443 -j ACCEPT
----

要注册远程Tomcat：

. 启动您的本地Tcat服务器实例和控制台。
. 在控制台的服务器选项卡上，点击*New Server*。
. 为服务器指定一个唯一的名称，输入网址`+http://<public address>:8080/agent+`（用实例的公开地址替换`<public address>`），然后点击*Register*。

您现在已准备好从本地Tcat服务器控制台管理Cloudcat实例。有关更多信息，请参阅 link:/tcat-server/v/7.1.0/monitoring-a-server[监视服务器]。

== 将Tomcat应用程序部署到Cloudcat

在设置Cloudcat之后，您可以开始在云中部署Tomcat应用程序。您可以手动将当前应用程序部署到Cloudcat，只需从本地Tomcat服务器复制应用程序WAR文件并将它们粘贴到EC2或GoGrid上的Cloudcat实例的webapps目录中即可，或者可以使用Tcat Server控制台执行部署和组态。

请注意，您的Web应用程序可能需要特定配置，包括配置MySQL驱动程序。您可以使用Tcat Server中的服务器配置文件在Cloudcat实例上进行配置更改。

将Web应用程序部署到Cloudcat实例后，手动或通过Tcat Server控制台重新启动Cloudcat，然后在云中测试您的应用程序。

== 获取对Cloudcat的支持

您的订阅包括通过电子邮件的无限支持要请求支持，请将您的查询发送到tcat-install@mulesoft.com，支持代表将与您联系。
