= 使用日志
:keywords: tcat, logs

单击服务器选项卡，然后单击日志选项卡以显示由Tomcat为每个应用程序和Tomcat实例本身生成的日志。

*Note*：日志每天午夜翻转。

该表显示以下内容：

* 日志类型（例如，JDK或Log4J）
* 文件名
* 文件大小
* 上次修改的时间戳
用于创建日志的* 类

单击日志文件名称查看其内容，或单击下载图标以在本地保存文件。查看日志文件内容时，请使用缩放按钮使字体变大或变小。您还可以调整换行并清除日志文件。

*Note*：日志在写入时更新。要暂停更新，请点击*Pause Tailing*。要继续实时观看，请点击*Resume Tailing*。要返回到日志列表，请点击*Back to log files list*。

== 监控Tcat服务器日志

您可以通过查看服务器选项卡上的服务器详细信息，然后单击日志选项卡来监视Tcat服务器实例的日志。

以下是Tomcat为Tcat Server生成的日志：

[%header,cols="2*a"]
|===
|此文件...  |记录与......有关的事件
| `tcat-agent-app.log`  |运行Tcat服务器代理，例如启动Quartz调度程序和加载bean定义。
| `tcat-agent-exec-output.YYYY-MM-DD.log`  |代理产生的命令和进程的输出。包括STDOUT，STDERR和关于何时执行命令以及哪个shell帐户的信息。 （从Tcat Server 6 R2开始）
| `tcat-agent-sys.YYYY-MM-DD.log`  |在容器中运行Tcat Server代理，例如初始化servlet。
| `tcat-console-app.log`  |运行Tcat Server控制台应用程序，如索引，加载插件和启动存储库。
| `tcat-console-sys.YYYY-MM-DD.log`  |在容器中运行Tcat Server控制台，例如初始化servlet。
| `tcat-file-audit.log`  |服务器上的文件API操作（有关详细信息，请参阅<<File Audit Log>>）。 （从Tcat Server 6 R2开始）
| `tcat-shell-scripts.log`  |服务器上的脚本活动（详情见下文）。
| `mule-ibeans.log`  | Mule iBeans活动。
|===

有关登录Tomcat的信息，请参阅 http://wiki.apache.org/tomcat/FAQ/Logging#Q1[Apache日志记录常见问题]。

== 文件审计日志

（从Tcat Server 6 R2开始）列出的其中一个日志是文件审核日志`tcat-file-audit.log`，它记录服务器上的每个文件API操作。此日志中的条目以TOMCAT_FILE_AUDIT为前缀。例如，以下条目表明在该服务器上的文件上调用了`list()`和`download()`方法：

[source, code, linenums]
----
[10-21 17:20:56] INFO  TOMCAT_FILE_AUDIT [http-51443-1]: list() |
C:\projects\galaxy-ee\trunk\tcat\provision\target\catalina-9003\.
[10-21 17:21:05] INFO  TOMCAT_FILE_AUDIT [http-51443-1]: download() |
C:\projects\galaxy-ee\trunk\tcat\provision\target\catalina-9003\.\webapps\agent\WEB-INF\agent.properties
----

==  Shell脚本日志

日志选项卡还显示Tcat Server管理控制台中任何 link:/tcat-server/v/7.1.0/automating-tasks[您创建的脚本]的shell脚本日志（`tcat-shell-scripts.log`）。 shell脚本日志的默认日志记录级别是INFO，您可以在`webapps/console/WEB-INF/classes/log4j.properties`文件中修改该日志级别。您可以修改`admin.shell.script`类别以更改所有管理控制台shell脚本的日志记录输出，或修改单个脚本的输出，修改`admin.shell.script.[<scriptName>]`类别，其中以`[<scriptName>]`为名称用方括号包围的脚本包含任何由反斜杠（例如`admin.shell.script.[My\ Script]`）转义的空格。

*Note:*如果您在admin shell中输入脚本并在保存脚本之前单击*Evaluate*，则该脚本的日志记录类别为`admin.shell.script.[$shell]`。

link:/tcat-server/v/7.1.0/scheduling-the-usage-statistics-script[<<上一页：*调度使用情况统计脚本*]

link:/tcat-server/v/7.1.0/automating-tasks[下一步：*自动执行任务* >>]
