= 使用服务器配置文件
:keywords: tcat, server, profiles

_server profile_是一组可以一次发布到多个服务器的环境变量和文件。您可以使用该配置文件覆盖Tomcat实例上操作系统，用户和应用程序的变量。您还可以从存储库添加文件，例如配置文件（如`server.xml`）。添加文件时，可以在指定的工作区中添加所有文件。有关将工作区和文件添加到存储库的信息，请参阅 link:/tcat-server/v/7.1.0/managing-the-repository[管理存储库]。

*To create or edit a profile:*

. 在管理选项卡上，点击*Server Profiles*，然后点击*New*。
. 为配置文件输入一个唯一的名称，也可以输入描述。
. 单击工作区框并选择包含要添加到此配置文件的文件的工作区（有关添加工作区和文件的说明，请参阅 link:/tcat-server/v/7.1.0/managing-the-repository[管理存储库]）。
. 对于工作区中的每个文件，指定要使用的版本，或保留选中的默认"Use Latest"。
. 要从此配置文件中删除文件，请选择*none*工作区。
. 要向配置文件添加环境变量，请单击*New Variable*，然后双击占位符名称和值并输入正确的信息。
. 要从配置文件中删除环境变量，请在表格中选择它并点击*Remove Variable*。
. 准备好保存配置文件并将其设置和文件发布到所有已设置为使用此配置文件的服务器时，请点击*Save*。要恢复您的更改，请点击*Cancel*。

如果服务器配置文件包含影响Tomcat启动的任何环境变量，则现在应该重新启动使用该配置文件的Tomcat实例，方法是在服务器选项卡上选择它们并单击*Restart*。

[WARNING]
====
如果您在Tcat Server之外更改环境变量并希望它们在Tomcat实例上生效，则必须在Tcat Server外手动重新启动Tomcat，因为Tcat Server使用当前JVM的环境变量以及Tcat Server中指定的环境变量来重新启动Tomcat 。
====

要将配置文件应用于一台或多台服务器，请在服务器选项卡上选择服务器，然后单击*Set Profile*。您还可以在编辑服务器的详细信息时设置配置文件。有关更多信息，请参阅 link:/tcat-server/v/7.1.0/working-with-servers[使用服务器]。

要删除配置文件，请在“服务器配置文件”屏幕上选择它，然后单击*Delete*。即使删除配置文件后，使用该配置文件的服务器上的环境变量和文件也将保持不变。

link:/tcat-server/v/7.1.0/integrating-with-ldap[<<上一页：*通过LDAP启用身份验证*]

link:/tcat-server/v/7.1.0/creating-remote-workspaces[Next：*创建远程工作区* >>]
