= 为外部数据库配置MMC  - 快速参考

＃*_Enterprise Edition_*＃

＃*_MMC Versions 3.4.2 and Later_*＃

== 概述

在MMC 3.4.2及以上版本中，配置MMC以将数据存储在外部数据库中已经大大简化。

该过程涉及两套基本任务。

在数据库服务器上：

* 创建数据库和模式
* 定义数据库用户名，权限和密码

在MMC上：

* 修改配置文件`web.xml`，告诉MMC使用您所需的数据库而不是MMC的默认数据库
* 修改所选外部数据库的配置文件以设置连接到数据库的参数

要了解如何为MMC配置每个数据库服务器，请参阅支持的服务器的相关页面：

*  link:/mule-management-console/v/3.7/persisting-mmc-data-to-postgresql[PostgreSQL的]
*  link:/mule-management-console/v/3.7/persisting-mmc-data-to-oracle[神谕]
*  link:/mule-management-console/v/3.7/persisting-mmc-data-to-mysql[MySQL的]
*  link:/mule-management-console/v/3.7/persisting-mmc-data-to-ms-sql-server[MS-SQL Server]

要了解如何为每个支持的数据库服务器配置MMC，请参阅下面的部分。

[NOTE]
MMC的某些发行版可能包含其他数据库引擎的空配置文件，但不支持这些文件。只有上面列出的数据库服务器才支持外部数据持久性。

== 配置MMC

在修改MMC配置文件之前，请确保MMC未运行。

=== 下载外部数据库的驱动程序

要在外部数据库上保存数据，您需要为选定的数据库服务器下载并安装数据库驱动程序。每个数据库引擎（以上链接）的文档页面都包含有关驱动程序安装的完整详细信息，包括来自数据库服务器供应商的下载链接。

=== 为环境或跟踪数据定义外部数据库

==== 配置文件：<MMC_HOME> / WEB-INF / web.xml

该文件包含一个名为`spring.profiles.active`的部分，如下所示。

[source, xml, linenums]
----
<context-param>
    <param-name>spring.profiles.active</param-name>
    <param-value>tracking-h2,env-derby</param-value>
</context-param>
----

正如您在上面的代码中看到的那样，MMC在内部使用的默认数据库是*H2*用于跟踪数据，*Derby*用于存储环境数据。要在外部数据库中存储跟踪或环境数据，您必须根据以下列表修改`spring.profiles.active`部分。

跟踪数据（商业活动）的===== 值

*  `tracking-h2`（默认）
*  `tracking-mysql`
*  `tracking-oracle`
*  `tracking-mssql`
*  `tracking-postgres`

环境数据的===== 值

*  `env-derby`（默认）
*  `env-mysql`
*  `env-oracle`
*  `env-msssql`
*  `env-postgres`

例如，如果您要在*Postgres*数据库上存储跟踪信息，并且在*Oracle*数据库上存储环境信息，则该部分会这样。

[source, xml, linenums]
----
<context-param>
    <param-name>spring.profiles.active</param-name>
    <param-value>tracking-postgres,env-oracle</param-value>
</context-param>
----

=== 为数据库连接定义参数

<MMC_HOME> / WEB-INF / classes / META-INF /数据库中的==== 配置文件

上面标题中指定的目录包含名称格式为：`<type of data>-<database name>.properties`的配置文件，其中：

[%header%autowidth.spread]
|===
| {串{1}}描述 |示例
用于环境数据的| `<type of data>`  | `mmc`，用于交易数据的`tracking-persistence`  | `tracking-persistence`
要使用的数据库服务器的| `<database name>`  |名称 | `postgres`
|===

例如，文件`mmc-oracle.properties`存储用于连接到存储环境数据的Oracle数据库的属性;文件`tracking-persistence-postgres.properties`存储用于连接到存储跟踪数据的Postgres数据库的属性等。

这些文件定义了连接到数据库的参数，包括：驱动程序，用户，密码，主机，端口等。

完整的文件列表

[source, code, linenums]
----
mmc-derby.properties
mmc-mssql.properties
mmc-mysql.properties
mmc-oracle.properties
mmc-postgres.properties
tracking-persistence-h2.properties
tracking-persistence-mssql.properties
tracking-persistence-mysql.properties
tracking-persistence-oracle.properties
tracking-persistence-postgres.properties
----

每个文件都包含下表中列出的参数，以及其他可能的附加参数，具体取决于每个数据库服务器。

在下表中，标有*Modify*的列标记了您需要根据您的设置修改哪些参数 - 例如，您必须用您自己的数据库用户替换`env.username`的值。

环境数据库配置文件的==== 参数

[%header%autowidth,width=60%]
|===
| {参数{1}}说明 |修改
| `env.driver`  |用于连接数据库的驱动程序 | 
| `env.script`  |用于在目标数据库中创建表的脚本 | 
| `env.username`  |数据库用户 | X
| `env.password`  |数据库用户的密码 | X
| `env.host`  |数据库服务器正在侦听的主机名或IP地址 | X
| `env.port`  |数据库服务器正在侦听的端口 | X
用于连接数据库的| `env.url`  |网址 | 
| `env.dbschema`  |数据库的名称 | X
| `env.servicename`  | *(Oracle.)*用于连接到外部数据库的服务名称 | X
|===

跟踪数据库配置文件的==== 参数

[%header%autowidth.spread]
|===
| {参数{1}}说明
外部数据库的| `mmc.tracking.db.platform`  | SQL服务器
| `mmc.tracking.db.driver`  |用于连接数据库的驱动程序
| `mmc.tracking.db.host`  |数据库服务器正在侦听的主机名或IP地址
| `mmc.tracking.db.port`  |数据库服务器正在侦听的端口
用于连接到数据库的| `mmc.tracking.db.url`  | URL
| `mmc.tracking.db.username`  |数据库用户
| `mmc.tracking.db.password`  |数据库用户的密码
| `mmc.tracking.db.dbname`  |数据库的名称
| `mmc.max.events.exception.details.length`  | Business Events异常中将存储在跟踪数据库中的字符数。默认值是8000;允许的最大值是261120。
|===

所有这些文件都包含带有帮助信息的注释，如下面的示例中所示。

=== 完成示例mmc-oracle.properties

[source, code, linenums]
----
env.driver=oracle.jdbc.driver.OracleDriver
env.script=oracle
env.username=mmc_status
#If you want to encrypt your password, set the value to ENC("encodedPassword").
#For encoding your password open a console and cd into the MMC install directory, cd encrypt folder
#and issue the command ./encrypt.sh input="mmc123" password=DEFAULTPASS
#where password refers to the encryption key to use and input is the value you want to encrypt.
#DEFAULTPASS is the default value set by MMC, refer to MMC docs at www.mulesoft.com for information on how
#to change that configuration value.
#env.password=ENC("HZe9CewttfG/PlAJSL8+KA==")
env.password=mmc123
env.host=localhost
env.port=1521
env.url=jdbc:oracle:thin:${env.username}/${env.password}@${env.host}:${env.port}/${env.servicename}
env.servicename=XEXDB
----

根据需要修改配置文件后，MMC将配置为将数据存储在指定的外部数据库上。启动MMC以检查您的新配置。

== 另请参阅

* 了解如何为您的数据库服务器配置MMC：+
**  link:/mule-management-console/v/3.7/persisting-mmc-data-to-postgresql[PostgreSQL的]
**  link:/mule-management-console/v/3.7/persisting-mmc-data-to-oracle[神谕]
**  link:/mule-management-console/v/3.7/persisting-mmc-data-to-mysql[MySQL的]
**  link:/mule-management-console/v/3.7/persisting-mmc-data-to-ms-sql-server[MS-SQL Server]
