=  REST API参考：应用程序库

本文档以及组成 link:/mule-management-console/v/3.7/rest-api-reference[Mule管理控制台REST API参考指南“]的其他文档仅为技术参考。本文档不提供诸如说明，用例或方案的上下文信息。要理解本文档，您应该熟悉https://www.mulesoft.com/resources/esb/what-mule-esb[MULE ESB]，应用程序存储库和 link:/mule-management-console/v/3.7/rest-api-reference[REST API]。

[%header,cols="1s,1"]
|===
2 + |假设：
| {主机{1}}本地主机
| {端口{1}} 8585
|已部署的应用程序 | mmc.war
|用户/密码 |管理/管理
|===

有关本文档中使用的格式的详细说明，请参阅 link:/mule-management-console/v/3.7/rest-api-reference[内容组织和公约]。

*/api/repository*

[cols="34,33,33"]
|===
一个|
*POST*

 为|

====  UPLOAD

 为|

|===

将新的Mule应用程序上传到存储库中。

=====  MULTIPART_FORM_DATA

[%header,cols="4*"]
|===
|键 |键入 |摘要 |子项
|姓名 |字符串 |要上传的应用程序的名称。如果未提供，则将使用"Unnamed Application"  |  - 
|文件 |字符串 |要上传的实际文件。它必须是.zip文件 |  - 
|版本 |数组 |（可选）应用程序版本。如果未提供，MMC将使用以下格式设置时间戳：yyyyMMdd-HH：mm  |  - 
|===

===== 在Windows上使用CURL
请注意，该语法是一个示例。请务必用您自己的MMC主机名，端口号和mmc-console-3.7.3（通常是已部署的mmc .war文件的名称）的设置替换`+http://locahost:8585/mmc-console-3.7.3+`。

----
 curl --basic -u admin:admin -F file=@my-zipped-app.zip -F name=test-app -F version=2.0 --header "Content-Type: multipart/form-data" http://localhost:8585/mmc-console-3.7.3/api/repository   
----

===== 在Linux上使用CURL

----
 curl --basic -u admin:admin -F file=@my-zipped-app.zip -F name=test-app -F version=2.0 --header 'Content-Type: multipart/form-data' http://localhost:8585/mmc-console-3.7.3/api/repository   
----

=====  JSON

[%header,cols="4*"]
|===
|键 |键入 |摘要 |子项
| versionId  |字符串 |版本 |的ID  - 
| applicationId  |字符串 |应用程序的ID。多个版本可以具有相同的应用程序ID  |  - 
|===

[cols="2*"]
|===
| *200*  |操作成功
| *400*  |未经授权的用户
| *404*  |注册应用程序时出错：找不到项目
| *409*  |应用程序名称和版本已经存在
| *500*  |指定上传应用程序时上传/错误的有效文件
| *501*  |请求内容不受支持。例如：该应用程序不是一个zip文件
上传应用程序时出现策略错误。| *502*  |
|===

[cols="2*"]
|===
|从 | 3.2.2
|===

[cols="34,33,33"]
|===
一个|
*GET*

 为|

==== 列出所有

 为|

|===

列出MMC可用的应用程序。

===== 语法

===== 使用CURL
请注意，该语法是一个示例。请务必用您自己的MMC主机名，端口号和mmc-console-3.7.3（通常是已部署的mmc .war文件的名称）的设置替换`+http://locahost:8585/mmc-console-3.7.3+`。

----
 curl --basic -u admin:admin http://localhost:8585/mmc-console-3.7.3/api/repository  
----

=====  JSON

[%header,cols="4*"]
|===
|键 |键入 |摘要 |子项
|总计 |整数 |可用应用程序数量 |  - 
|数据 |数组 |可用应用程序列表 |  - 
|姓名 |字符串 |应用程序名称 |数据
| id  |字符串 |应用程序ID。请注意，一个应用程序可以有多个版本的 |数据
| href  |字符串 |与资源 |数据的完全链接
|版本 |数组 |相同应用程序的可用版本列表（应用程序按名称区分） |数据
|姓名 |字符串 |版本名称。默认情况下是时间戳，但可以是其他内容，如"1.0a"  |个版本
| id  |字符串 |应用程序版本ID  |版本
| parentPath  |字符串 |存储库 |版本上通用应用程序的路径
|===

[cols="2*"]
|===
| *200*  |操作成功
| *500*  |检索应用程序时出错信息/用户名和密码错误/未经授权的用户
| *501*  |找不到应用程序
|===

[cols="2*"]
|===
|从 | 3.2.2
|===

*/api/repository/\{applicationId}*

[cols="34,33,33"]
|===
一个|
*GET*

 为|

====  LIST

 为|

|===

列出具有相同指定应用程序ID的所有应用程序版本

===== 语法

[%header,cols="4*"]
|===
|键 |键入 |摘要 |子项
| applicationId  |字符串 |存储库上应用程序的ID。不要混淆版本ID。应用程序可以由一个或多个版本组成;每个版本都有自己的ID  |  - 
|===

===== 在Windows上使用CURL
请注意，该语法是一个示例。请务必用您自己的MMC主机名，端口号和mmc-console-3.7.3（通常是已部署的mmc .war文件的名称）的设置替换`+http://locahost:8585/mmc-console-3.7.3+`。

----
 curl --basic -u admin:admin http://localhost:8585/mmc-console-3.7.3/api/repository/local$43d80f90-b30b-4988-a83b-8172b649b11c  
----


===== 在Linux上使用CURL

----
 curl --basic -u admin:admin 'http://localhost:8585/mmc-console-3.7.3/api/repository/local$43d80f90-b30b-4988-a83b-8172b649b11c'  
----

=====  JSON

[%header,cols="4*"]
|===
|键 |键入 |摘要 |子项
|总计 |整数 |应用程序的可用版本数量 |  - 
|数据 |数组 |应用程序的可用版本列表 |  - 
|姓名 |字符串 |应用程序 |数据的版本
| id  |字符串 |版本 |数据的ID
| parentPath  |字符串 |存储库中应用程序的路径 |数据
|===

[cols="2*"]
|===
| *200*  |操作成功
| *500*  |检索应用程序时出错信息/用户名和密码错误/未经授权的用户
| *501*  |找不到应用程序
| *502*  |无效的应用程序ID。检查输入的ID不是版本ID
|===

[cols="2*"]
|===
|从 | 3.2.2
|===

[cols="34,33,33"]
|===
一个|
*DELETE*

 为|

====  REMOVE

 为|

|===

从存储库中删除应用程序及其所有相应的版本。

===== 语法

[%header,cols="4*"]
|===
|键 |键入 |摘要 |子项
| versionId  |字符串 |应用程序版本的标识。调用<<LIST ALL>>来获取它。 |  - 
|===

===== 在Windows上使用CURL
请注意，该语法是一个示例。请务必用您自己的MMC主机名，端口号和mmc-console-3.7.3（通常是已部署的mmc .war文件的名称）的设置替换`+http://locahost:8585/mmc-console-3.7.3+`。

----
 curl --basic -u admin:admin -X DELETE http://localhost:8585/mmc-console-3.7.3/api/repository/local$a89eb3d0-68b9-44a0-9f6b-712b0895f469  
----


===== 在Linux上使用CURL

----
 curl --basic -u admin:admin -X DELETE 'http://localhost:8585/mmc-console-3.7.3/api/repository/local$a89eb3d0-68b9-44a0-9f6b-712b0895f469'  
----


=====  JSON

[cols="2*"]
|===
| *200*  |操作成功
| *500*  |删除存储库应用程序时出错
| *501*  |找不到应用程序
| *502*  |删除应用程序时出现策略错误
|===

[cols="2*"]
|===
|从 | 3.2.2
|===
