= 疑难解答和后续步骤
:keywords: clusters, deploy

[TIP]
您现在可以通过运行时管理器UI轻松创建集群。请参阅 link:/runtime-manager/managing-servers#create-a-cluster[创建和管理集群]。

== 排除端口故障

*Mule HA Demo Bundle*在本地驱动器上使用以下端口：

Mule服务器1的*  7777
Mule服务器2的*  7778
用于Mule管理控制台的*  8585
WidgetUI Web应用程序的*  8080和61616

如果您当前将其中一个或多个端口用于其他用途，则可以更改WidgetUI Web应用程序和Mule服务器使用的端口。

=== 更改WidgetUI端口

在*Terminal*或*Console*中，在`cluster/widgetUI`文件夹中执行以下脚本：+
  `play run --http.port=YOUR_CUSTOM_PORT` +
 例如，执行`play run --http.port=8090`

=== 更改服务器的端口

在您的*Terminal*或*Console*中，使用以下系统属性执行`startServer`脚本：+
  `startServer1 -M-Dmule.mmc.bind.port=YOUR_CUSTOM_PORT` +
 例如，执行`startServer1 -M-Dmule.mmc.bind.port=7779`

== 对WidgetUI进行故障排除

如果*Time to Complete Processing of Widget*窗格未正确呈现，请刷新Web浏览器页面。

== 下一步

浏览我们的文档，了解更多关于Mule集群和高可用性的信息。

使用Mule管理控制台的Mule的*  link:https://www.mulesoft.com/platform/integration-manager[下载试用版]进行高可用性试验。 （下载**Runtime - Mule  Enterprise (with Management Tools)**。）
*  link:/mule-user-guide/v/3.8/installing-an-enterprise-license[安装企业许可证]开始使用Mule管理控制台管理生产中的群集。
* 有关Mule高可用性的更多信息，请参阅 link:/mule-user-guide/v/3.8/mule-high-availability-ha-clusters[骡子高可用性]文档。
* 有关Mule群集的更多信息，请参阅 link:/mule-management-console/v/3.8/configuring-mule-ha-clustering[骡HA集群]文档。
* 有关管理Mule群集的更多信息，请参阅 link:/mule-management-console/v/3.8/managing-mule-high-availability-ha-clusters[管理HA群集]文档。
* 有关使用REST API管理Mule群集的更多信息，请参阅 link:/mule-management-console/v/3.8/rest-api-reference[REST API参考]文档。
* 有关创建或解散群集的更多信息，请参阅 link:/mule-management-console/v/3.8/creating-or-disbanding-a-cluster[创建或解散群集]文档。

