=  Anypoint MQ连接器参考

https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[_Select_]

*Guide:* link:/mule-user-guide/v/3.8/anypoint-mq-connector[Anypoint MQ连接器]

== 关于全局元素属性

常规选项卡字段是：

[%header,cols="25s,75a"]
|===
| Studio字段 |说明
|名称 |配置名称。

*Required:*是+
*Default:*无
|客户端模式 |指定Anypoint MQ连接器是否使用改进的HTTP客户端（默认为SYNC）
或Mule运行时（MULE）提供的不推荐使用的HTTP客户端。改进的HTTP客户端可以
是同步还是异步。

可能的值：

*  `ASYNC`  - 要求MQ客户端使用异步HTTP客户端库。
*  `SYNC`（默认） - 要求MQ客户端使用同步HTTP客户端库。这个
建议使用MQ线程配置文件时使用值。
*  `MULE`（已弃用） - 用于与MQ通信的HTTP连接器是Grizzly
由Mule Runtime提供的库。

*Required:*否+
*Default:* `SYNC`
|提供商：+
使用提供商配置 |为当前应用程序设置由URL，客户端应用程序ID和客户端密码组成的提供程序配置。

*Required:*是+
*Default:*无
Anypoint平台中显示的|网址 |地区网址。

可能的值是：

** 美国东部（弗吉尼亚北部）：`+https://mq-us-east-1.anypoint.mulesoft.com/api/v1+`
** 美国西部（俄勒冈州）：`+https://mq-us-west-2.anypoint.mulesoft.com/api/v1+`
** 欧盟（爱尔兰）：`+https://mq-eu-west-1.anypoint.mulesoft.com/api/v1+`
** 亚太地区（新加坡）：`+https://mq-ap-southeast-1.anypoint.mulesoft.com/api/v1+`
** 亚太地区（悉尼）：`+https://mq-ap-southeast-2.anypoint.mulesoft.com/api/v1+`

FIFO队列可以驻留在美国东部，美国西部和欧盟爱尔兰。

*Required:*是+
*Default:*无

|客户端应用程序ID  |来自Anypoint Platform> MQ>客户端应用程序。单击该应用程序并复制客户端应用程序ID值。

*Required:*是+
*Default:*无
|客户端机密 |来自Anypoint平台> MQ>客户端应用程序。点击该应用程序并复制客户端密钥值。

*Required:*是+
*Default:*无
|使用全局提供程序配置 |为所有应用程序设置URL，客户端应用程序ID和客户端密钥。

*Required:*否+
*Default:*无
|基本设置：+
最多重新发送次数 |重新发送次数
以防万一消息失败。 -1表示Anypoint MQ无限制地重试。如果设置为默认值-1，则此参数不会出现在XML流中。

*Required:*否+
*Default:* -1
| [[am]]确认模式 |（Studio中的基本设置菜单）定义从消息中删除消息时如何确认Anypoint MQ消息。如果设置为默认值
AUTO的值，这个参数不会出现在XML流中。

可能的值是：

*  `AUTO`（默认） - 根据是否发生例外情况，确认或否定确认消息。有关更多信息，请参阅 link:/anypoint-mq/mq-ack-mode[确认模式]。
*  `MANUAL`  - 使用自定义ACK消息处理器确认消息。
*  `NONE`  - 消息在收到后立即得到确认和删除。

*Required:*否+
*Default:* `AUTO`
|确认超时 |（Studio中的基本设置菜单）当您从队列中取得Anypoint MQ消息时，代理将其置于运行状态，并且消息保持该状态，直到执行ACK（应用程序读取消息并且Anypoint MQ删除它）或达到确认超时。如果执行ACK，则消息从队列中移除，如果确认超时已到，则消息返回队列。如果设置为默认值
`0`的值，此参数不会出现在XML流中。

*Required:*否+
*Default:* `0`
|轮询时间 |（Studio中的基本设置菜单）等待预期消息的最长时间（以毫秒为单位）。如果设置为默认值`10000`（10秒），则此参数不会出现在XML流中。

*Required:*否+
*Default:* `10000`（10秒）
|线程配置文件设置+
|定义线程配置文件行为或
使用默认工作线程配置文件。请参阅 link:/mule-user-guide/v/3.8/tuning-performance[调整性能]。线程配置文件选项使您可以优化连接器的性能，以便与Anypoint MQ配合使用。
 
*Note:*设置线程配置文件字段后，保存您的项目，单击配置XML，更改名称
将配置文件语句以anypoint-mq开头，然后使用anypoint-mq：config块中的anypoint-mq：provider语句切换语句的顺序。位置可以是北弗吉尼亚州（美国东部1），爱尔兰（欧洲西部1），新加坡（ap-southeast-1），悉尼（ap-southeast-2）或俄勒冈州（us-west-2） ）。

此示例显示完成的语句可能如何显示：

[source,xml,linenums]
----
<anypoint-mq:config name="Anypoint_MQ_Configuration" doc:name="Anypoint MQ Configuration">
  <anypoint-mq:provider url="https://mq-us-east-1.anypoint.mulesoft.com/api/v1" clientId="ID" clientSecret="SECRET"/>
  <anypoint-mq:worker-threading-profile maxThreadsActive="42" maxThreadsIdle="42" threadTTL="4200" threadWaitTimeout="-1"/>
</anypoint-mq:config>
----

*Required:*否+
*Default:*无
|使用自定义工作线程配置文件 |请参阅 link:/mule-user-guide/v/3.8/tuning-performance[调整性能]。

*Required:*否+
*Default:*无
|最大活动线程数 |要使用的最大线程数。请参阅 link:/mule-user-guide/v/3.8/tuning-performance[调整性能]。

*Required:*否+
*Default:*无
|最大空闲线程数 |在池被销毁之前可以在池中的最大空闲或非活动线程数。请参阅 link:/mule-user-guide/v/3.8/tuning-performance[调整性能]。除非队列完全填满，否则线程池不会从最大空闲线程向最大活动线程增长。

*Required:*否+
*Default:*无
|线程TTL  |将线程时间转换为持续时间。

*Required:*否+
*Default:*无
|池用尽操作 |当最大池大小或队列大小有界时，此值确定如何处理传入任务。

可能的值是：

*  `WAIT`  - 等到线程变为可用;如果最小线程数为零，则不要使用此值，在这种情况下，线程可能永远不可用。
*  `DISCARD`  - 丢弃当前请求并返回。
*  `DISCARD_OLDEST`  - 扔掉最旧的请求并返回。
*  `ABORT`  - 抛出一个RuntimeException。
*  `RUN`  - 默认值;执行请求的线程会执行任务本身，这有助于防止锁定。

*Required:*否+
*Default:*无
|线程等待超时 |线程等待超时（以毫秒为单位）。

*Required:*否+
*Default:*无
|最大缓冲区大小 |最大缓冲区大小。

*Required:*否+
*Default:*无
|===

== 关于常用XML元素

[%header,cols="25s,75a"]
|===
| XML元素 |描述
| doc：name  |配置名称。

*Required:*是+
*Default:*无+
*XML Example:*

[source,xml]
----
<anypoint-mq:config name="Anypoint_MQ_Configuration" doc:name="Anypoint MQ Configuration">
----
| clientMode  |指定Anypoint MQ连接器是否使用改进的HTTP客户端（默认为SYNC）
或Mule运行时（MULE）提供的不推荐使用的HTTP客户端。改进的HTTP客户端可以
是同步还是异步。

可能的值：

*  `ASYNC`  - 要求MQ客户端使用异步HTTP客户端库。
*  `SYNC`（默认） - 要求MQ客户端使用同步HTTP客户端库。这个
建议使用MQ线程配置文件时使用值。
*  `MULE`（已弃用） - 用于与MQ通信的HTTP连接器是Grizzly
由Mule Runtime提供的库。

*Required:*否+
*Default:* `SYNC`
*XML Example:*

[source,xml]
----
<anypoint-mq:config name="Anypoint_MQ_Configuration" clientMode="SYNC" ... />
----
|供应商 |为当前应用程序设置由URL，客户端应用程序ID和客户端密钥组成的供应商配置。

*Required:*是+
*Default:*无+
*XML Example:*

[source,xml]
----
<anypoint-mq:provider url="..." clientId="..." clientSecret="..."/>
----
|网址 |在Anypoint Platform中显示的区域URL。

可能的值是：

** 美国东部（弗吉尼亚北部）：`+https://mq-us-east-1.anypoint.mulesoft.com/api/v1+`
** 美国西部（俄勒冈州）：`+https://mq-us-west-2.anypoint.mulesoft.com/api/v1+`
** 欧盟（爱尔兰）：`+https://mq-eu-west-1.anypoint.mulesoft.com/api/v1+`
** 亚太地区（新加坡）：`+https://mq-ap-southeast-1.anypoint.mulesoft.com/api/v1+`
** 亚太地区（悉尼）：`+https://mq-ap-southeast-2.anypoint.mulesoft.com/api/v1+`

FIFO队列可以驻留在美国东部，美国西部和欧盟爱尔兰。

*Required:*是+
*Default:*无

*XML Example:*

[source,xml]
----
<anypoint-mq:provider url="https://mq-us-east-1.anypoint.mulesoft.com/api/v1" .../>
----
| clientId  |从Anypoint平台> MQ>客户端应用程序。单击该应用程序并复制客户端应用程序ID值。

*Required:*是+
*Default:*无+
*XML Example:*

[source,xml]
----
<anypoint-mq:provider url="..." clientId="<id>" clientSecret="..."/>
----
| clientSecret  |从Anypoint平台> MQ>客户端应用程序。点击该应用程序并复制客户端密钥值。

*Required:*是+
*Default:*无+
*XML Example:*

[source,xml]
----
<anypoint-mq:provider url="..." clientId="..." clientSecret="<secret>"/>
----
| provider-ref  |为所有应用程序设置URL，客户端应用程序ID和客户端密钥。

*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<anypoint-mq:config name="..." doc:name="..." maxRedelivery="..." acknowledgementMode="..."
 acknowledgementTimeout="..." pollingTime="..." provider-ref="Provider_Settings">
----
| maxRedelivery  |重新传送的次数
以防万一消息失败。 -1表示Anypoint MQ无限制地重试。如果设置为默认值-1，则此参数不会出现在XML流中。

*Required:*否+
*Default:* -1 +
*XML Example:*

[source,xml]
----
<anypoint-mq:config name="..." doc:name="..." maxRedelivery="10" ... >
----
| acknowledgementMode  |定义从消息中删除消息时如何确认Anypoint MQ消息。如果设置为默认值
AUTO的值，这个参数不会出现在XML流中。

可能的值是：

*  `AUTO`（默认） - 根据是否发生例外情况，确认或否定确认消息。有关更多信息，请参阅 link:/anypoint-mq/mq-ack-mode[确认模式]。
*  `MANUAL`  - 使用自定义ACK消息处理器确认消息。
*  `NONE`  - 消息在收到后立即得到确认和删除。

*Required:*否+
*Default:* `AUTO` +
*XML Example:*

[source,xml]
----
<anypoint-mq:config ... acknowledgementMode="NONE" acknowledgementTimeout="42" ...>
----
| acknowledgementTimeout  |当您从队列中获取任意点MQ消息时，代理会将其置于运行状态，并且消息保持该状态，直到执行ACK（应用程序读取消息并且Anypoint MQ删除它），或者达到确认超时。如果执行ACK，则消息从队列中移除，如果确认超时已到，则消息返回队列。如果设置为默认值
`0`的值，此参数不会出现在XML流中。

*Required:*否+
*Default:* `0` +
*XML Example:*

[source,xml]
----
<anypoint-mq:config ... acknowledgementMode="NONE" acknowledgementTimeout="42" ...>
----
| pollingTime  |等待预期消息的最长时间（以毫秒为单位）。如果设置为默认值`10000`（10秒），则此参数不会出现在XML流中。

*Required:*否+
*Default:* `10000`（10秒）+
*XML Example:*

[source,xml]
----
<anypoint-mq:config name="..." doc:name="..." pollingTime="99000">
----
| worker-threading-profile  |定义线程配置文件行为或
 使用默认工作线程配置文件。请参阅 link:/mule-user-guide/v/3.8/tuning-performance[调整性能]。线程配置文件选项使您可以优化连接器的性能，以便与Anypoint MQ配合使用。
 
*Note:*配置完工作线程配置文件后，将语句的名称更改为以anypoint-mq开头，然后在anypoint-mq：config块中使用anypoint-mq：provider语句切换语句的顺序。

这个例子显示了完成的语句应该如何显示：

[source,xml,linenums]
----
<anypoint-mq:config name="Anypoint_MQ_Configuration" doc:name="Anypoint MQ Configuration">
  <anypoint-mq:provider url="https://mq-us-east-1.anypoint.mulesoft.com/api/v1" clientId="ID" clientSecret="SECRET"/>
  <anypoint-mq:worker-threading-profile maxThreadsActive="42" maxThreadsIdle="42" threadTTL="4200" threadWaitTimeout="-1"/>
</anypoint-mq:config>
----

*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<http:worker-threading-profile maxThreadsActive="..." maxThreadsIdle="..."
threadTTL="..." poolExhaustedAction="..." threadWaitTimeout="..."
maxBufferSize="..."/>
----
| maxThreadsActive  |要使用的最大线程数。请参阅 link:/mule-user-guide/v/3.8/tuning-performance[调整性能]。

*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<http:worker-threading-profile maxThreadsActive="42" maxThreadsIdle="42"
threadTTL="..." poolExhaustedAction="..." threadWaitTimeout="..."
maxBufferSize="..."/>
----
| maxThreadsIdle  |在池被销毁之前可以在池中的最大空闲或非活动线程数。请参阅 link:/mule-user-guide/v/3.8/tuning-performance[调整性能]。除非队列完全填满，否则线程池不会从最大空闲线程向最大活动线程增长。

*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<http:worker-threading-profile maxThreadsActive="42" maxThreadsIdle="42"
threadTTL="..." poolExhaustedAction="..." threadWaitTimeout="..."
maxBufferSize="..."/>
----
| threadTTL  |将线程时间以毫秒为单位生存。

*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<http:worker-threading-profile maxThreadsActive="..." maxThreadsIdle="..."
threadTTL="1000" poolExhaustedAction="..." threadWaitTimeout="..."
maxBufferSize="..."/>
----
| poolExhaustedAction  |当最大池大小或队列大小有界时，此值确定如何处理传入任务。

可能的值是：

*  `WAIT`  - 等到线程变为可用;如果最小线程数为零，则不要使用此值，在这种情况下，线程可能永远不可用。
*  `DISCARD`  - 丢弃当前请求并返回。
*  `DISCARD_OLDEST`  - 扔掉最旧的请求并返回。
*  `ABORT`  - 抛出一个RuntimeException。
*  `RUN`  - 默认值;执行请求的线程会执行任务本身，这有助于防止锁定。

*Required:*否+
*Default:* `RUN` +
*XML Example:*

[source,xml,linenums]
----
<http:worker-threading-profile maxThreadsActive="..." maxThreadsIdle="..."
threadTTL="..." poolExhaustedAction="DISCARD_OLDEST" threadWaitTimeout="..."
maxBufferSize="..."/>
----
| threadWaitTimeout  |以毫秒为单位的线程等待超时。

*Type:*长+
*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<http:worker-threading-profile maxThreadsActive="..." maxThreadsIdle="..."
threadTTL="..." poolExhaustedAction="..." threadWaitTimeout="1000"
maxBufferSize="..."/>
----
| maxBufferSize  |最大缓冲区大小。

*Type:*整数+
*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<http:worker-threading-profile maxThreadsActive="..." maxThreadsIdle="..."
threadTTL="..." poolExhaustedAction="..." threadWaitTimeout="..."
maxBufferSize="1000"/>
----
|===

== 关于基本的XML元素

[%header,cols="25s,75a"]
|===
| XML元素 |描述
| anypoint-mq：<operation>  |此连接器实例执行的操作。

可能的值：

*  `publish`  - 将消息发送到队列或消息交换。
*  `consume`  - 从队列中消费一条消息。
*  `ack`  - 确认一条消息，即接受消息并删除消息。
*  `nack`  - 否定确认消息，即不接受消息并将消息返回队列。

*Required:*是+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
    <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration" doc:name="Anypoint MQ"
    destination="MyQ" acknowledgementMode="NONE" acknowledgementTimeout="42" pollingTime="99000">
    </anypoint-mq:consume>
</flow>
----
|===

=== 关于Studio TLS / SSL和代理标签

TSL / SSL和代理选项卡与共享信息相同
link:/mule-user-guide/v/3.8/http-connector[HTTP连接器]。

=== 关于Studio预取标签

允许您在询问消息时一次设置要接收的消息数量。根据XML中的`Polling Time`（`pollingTime`）设置，响应可能包含的消息少于此数字。

当您向Anypoint MQ队列订阅流时，流池会定期轮询队列以查找消息。此操作可能非常耗时。为了避免延迟，引入了预取。这是一个放置在流和Anypoint MQ队列之间的组件，它定期轮询队列，但不处理池中的消息。您可以根据您的网站性能和用例需求更改这些值。

*Note:*只支持全局预取;但不支持MQ连接器配置（anypoint-mq：config）内的预取。

预取标签字段是：

[%header,cols="25s,75a"]
|===
|值 |说明
|获取大小 |要预取的消息数量。 *&#8224;*
|获取超时 |等待所需消息数量的最大持续时间（以毫秒为单位）。当这段时间过去后，响应会发送尽可能多的消息。
|频率 |预取队列不为空时执行检索操作的持续时间（以毫秒为单位）。
|获取重试尝试次数 |（v1.3.0及更高版本）出现错误时重试预取的次数。默认值是-1（无限）。
|获取重试等待时间 |（v1.3.0及更高版本）在重试之前发生预取错误后要等待的持续时间（以毫秒为单位）。
|===

*&#8224;* *Fetch Size Notes*：

* 为获得最佳性能，请将`Fetch Size`设置为10（最大值）并减少`Frequency`以增加轮询时间和每秒事务数（TPS）的结果出队。如果消息处理缓慢，则可以增加`Fetch Timeout`。例如，如果处理过程需要5秒钟，则将`Fetch Timeout`设置为至少两倍（10000毫秒）。
* 如果获取大小大于1，则同时请求多条消息。这会通过Mule流启动单独的消息，可能会同时发生，具体取决于Mule工作线程配置（有关线程配置信息，请参阅 link:/mule-user-guide/v/3.8/tuning-performance[调整性能]）。
* 抓取大小不保证消息并行处理，有些消息可能，其他消息不会。

除了这些与性能相关的参数外，正确配置xref：am [Acknowledgement Mode]（确认模式）非常重要。

预取默认值的等效XML为：

[source,xml]
----
<anypoint-mq:prefetch fetchSize="10" fetchTimeout="1000" frequency="5000"/>
----

== 关于基本设置

[%header,cols="25s,75a"]
|===
| Studio字段 |说明
|操作 |此连接器实例执行的操作。

可能的值：

*  `publish`  - 将消息发送到队列或消息交换。
*  `consume`  - 从队列中消费一条消息。
*  `ack`  - 确认一条消息，即接受消息并删除消息。
*  `nack`  - 否定确认消息，即不接受消息并将消息返回队列。

*Required:*是+
*Default:*无
|===

== 关于发布商设置

[%header,cols="25s,75a"]
|===
| Studio字段 |说明
|目标 |队列或消息交换名称。

*Required:*是+
*Default:*无
|消息ID  |要发布的消息的可选ID。当发布到FIFO队列时，
如果您指定自定义消息ID并且消息ID在多条消息中相同，则
具有相同消息ID的消息不能重新发送。对于应用程序（如消息需要只处理一次的事务用例），Anypoint MQ在消息发布到FIFO队列时支持一次消息传递。 FIFO队列支持消息的重复数据消除。例如，如果您重试在5分钟重复数据消除间隔内向FIFO队列发送具有相同消息ID的消息，则Anypoint MQ保证具有相同消息ID的消息将被订户检索和处理一次。在Anypoint Studio上构建需要此功能的应用程序时，可以在Anypoint MQ连接器内的发布者设置中设置消息ID。如果未明确设置消息标识，则MQ自动为发送到队列的每条消息生成唯一的消息标识。

*Required:*否+
*Default:*无
|发送出站属性 |发布时发送属性。

*Required:*是+
*Default:*已检查
|发送内容类型 |发布时发送内容类型。

*Required:*是+
*Default:*已检查
|属性 |为发布设置的可选属性内容。

*Required:*否+
*Default:*无
|值 |为发布设置的可选值内容。

*Required:*否+
*Default:*无
|===

== 关于消费者设置

[%header,cols="25s,75a"]
|===
| Studio字段 |说明
|目的地 |队列名称。

*Required:*是+
*Default:*无
|确认模式 |如果您使用
Anypoint MQ连接器作为消息处理器，操作是`MANUAL (default)`或`NONE`。如果MQ连接器用作入口点，则模式选项为`From configuration (Default)`，`AUTO`，`MANUAL`或`NONE`。
了解更多信息，
请参阅 link:/anypoint-mq/mq-ack-mode[Anypoint MQ确认模式]。 *Note:*该值覆盖全局元素属性基本设置中的*Acknowledgement Mode*字段。

*Required:*否+
如果连接器是消息处理器，则*Default:* MANUAL，
或者如果连接器是入口点，则从配置中获取
|确认超时 |直到确认模式的持续时间（以毫秒为单位）
超时。 *Note:*该值覆盖全局元素属性基本设置中的*Acknowledgement Timeout*字段。
|轮询时间 | MQ连接器轮询队列或消息交换的持续时间（以毫秒为单位）。 *Note:*该值覆盖全局元素属性基本设置中的*Polling Time*字段。默认值是10000毫秒（10秒）。
|重新连接等待时间 |在MQ尝试重新建立与MQ后端服务器的连接之前等待多长时间（以毫秒为单位）。默认值是3000毫秒（3秒）。
|重新连接尝试次数 | MQ应尝试重新建立与MQ后端服务器的连接的次数。 -1意味着永远尝试。
|===

== 关于订阅者设置

[%header,cols="25s,75a"]
|===
| Studio字段 |说明
|目的地 |队列名称。

*Required:*是+
*Default:*无
|确认模式 |将MQ连接器用作入口点时，模式选项为`From configuration (Default)`，`AUTO`，`MANUAL`或{{3} }。

*Notes:*

* 该值覆盖全局元素属性基本设置中的*Acknowledgement Mode*字段。
* 默认值自动确认发送到目标队列的每条消息。

*Required:*否+
*Default:*如果连接器是入口点，则从配置开始
|确认超时 |直到确认模式的持续时间（以毫秒为单位）
超时。 *Note:*该值覆盖全局元素属性基本设置中的*Acknowledgement Timeout*字段。
|轮询时间 | MQ连接器轮询队列中消息的持续时间（以毫秒为单位）。 *Note:*该值覆盖全局元素属性基本设置中的轮询时间字段。
|重新连接等待时间 |在MQ尝试重新建立与MQ后端服务器的连接之前等待多长时间（以毫秒为单位）。默认值是3000毫秒（3秒）。
|重新连接尝试次数 | MQ应尝试重新建立与MQ后端服务器的连接的次数。 -1意味着永远尝试。
|===

== 关于发布XML元素

[%header,cols="25s,75a"]
|===
| XML元素 |描述
|目的地 |队列或消息交换名称。

*Required:*是+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
    <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration"
     doc:name="Anypoint MQ" destination="MyQ"
     acknowledgementMode="NONE" acknowledgementTimeout="42"
     pollingTime="99000">
    </anypoint-mq:consume>
</flow>
----
| messageId  |要发布的消息的可选标识。当发布到FIFO队列时，
如果您指定自定义消息ID并且消息ID在多条消息中相同，则
具有相同消息ID的消息将不会被重新发送。对于应用程序（如消息需要只处理一次的事务用例），Anypoint MQ在消息发布到FIFO队列时支持一次消息传递。 FIFO队列支持消息的重复数据消除。例如，如果您重试在5分钟重复数据消除间隔内向FIFO队列发送具有相同消息ID的消息，则Anypoint MQ保证具有相同消息ID的消息将被订户检索和处理一次。在Anypoint Studio上构建需要此功能的应用程序时，可以在Anypoint MQ连接器内的发布者设置中设置消息ID。如果未明确设置消息标识，则MQ自动为发送到队列的每条消息生成唯一的消息标识。

*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
  <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
  <anypoint-mq:publish config-ref="Anypoint_MQ_Configuration" doc:name="Anypoint MQ" destination="QUEUEorMsgEx">
      <anypoint-mq:message-builder messageId="4254a4254b4254c4254"
       sendContentType="false" sendOutboundProperties="false">
          <anypoint-mq:properties>
              <anypoint-mq:property propertyName="THisisAProperty" value="4254"/>
          </anypoint-mq:properties>
      </anypoint-mq:message-builder>
  </anypoint-mq:publish>
</flow>
----
| sendOutboundProperties  |发布时发送属性。

*Required:*是+
*Default:*选中+
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
  <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
  <anypoint-mq:publish config-ref="Anypoint_MQ_Configuration" doc:name="Anypoint MQ"
  destination="QUEUEorMsgEx">
    <anypoint-mq:message-builder messageId="4254a4254b4254c4254" sendContentType="false"
       sendOutboundProperties="false">
     ...
    </anypoint-mq:message-builder>
  </anypoint-mq:publish>
</flow>
----
| sendContentType  |发布时发送内容类型。

*Required:*是+
*Default:*选中+
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
  <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
  <anypoint-mq:publish config-ref="Anypoint_MQ_Configuration" doc:name="Anypoint MQ"
  destination="QUEUEorMsgEx">
    <anypoint-mq:message-builder messageId="4254a4254b4254c4254" sendContentType="false"
       sendOutboundProperties="false">
     ...
    </anypoint-mq:message-builder>
  </anypoint-mq:publish>
</flow>
----
| propertyName  |要为发布设置的可选属性内容。

*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<anypoint-mq:properties>
    <anypoint-mq:property propertyName="THisisAProperty" value="4254"/>
</anypoint-mq:properties>
----
|值 |为发布设置的可选值内容。

*Required:*否+
*Default:*无+
*XML Example:*

源，XML，linenums]
----
<anypoint-mq:properties>
    <anypoint-mq:property propertyName="THisisAProperty" value="4254"/>
</anypoint-mq:properties>
----
|===

== 关于使用XML元素

[%header,cols="25s,75a"]
|===
| XML元素 |描述
|目的地 |队列或消息交换名称。

*Required:*是+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
    <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration"
     doc:name="Anypoint MQ" destination="MyQ"
     acknowledgementMode="NONE" acknowledgementTimeout="42"
     pollingTime="99000">
    </anypoint-mq:consume>
</flow>
----
| acknowledgementMode  |模式为`MANUAL (default)`或`NONE`。了解更多信息，
请参阅 link:/anypoint-mq/mq-ack-mode[Anypoint MQ确认模式]。

*Required:*否+
如果连接器是消息处理器，则*Default:* MANUAL，
或者如果连接器是入口点+，则从配置开始
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
    <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration" doc:name="Anypoint MQ"
     destination="ImaQ" acknowledgementMode="NONE" acknowledgementTimeout="42"
     pollingTime="99000">
    </anypoint-mq:consume>
</flow>
----
| acknowledgementTimeout  |直到确认模式的持续时间（以毫秒为单位）
超时。

*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
    <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration" doc:name="Anypoint MQ"
     destination="ImaQ" acknowledgementMode="NONE" acknowledgementTimeout="42"
     pollingTime="99000">
    </anypoint-mq:consume>
</flow>
|pollingTime |Duration in milliseconds that the MQ connector polls the queue or message exchange for messages.

*Required:* No +
*Default:* None +
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
     <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
     <anypoint-mq：consume config-ref = "Anypoint_MQ_Configuration" doc：name = "Anypoint MQ"
      destination = "ImaQ" acknowledgementMode = "NONE" acknowledgementTimeout = "42"
      pollingTime = "99000">
     </anypoint-mq:consume>
</flow>
| reconnectionWaitTime  |尝试重新连接到MQ后端服务器之前要等待的持续时间（以毫秒为单位）。

*Required:*否+
*Default:* 3000毫秒（3秒）+
*XML Example:*

[source,xml,linenums]
----
<flow name="mqAsEndpointFlow">
    <anypoint-mq:subscriber config-ref="Anypoint_MQ_Configuration" destination="Q1" 
    doc:name="Anypoint MQ" reconnectionAttempts="-1" reconnectionWaitTime="3000"/>
    <logger message="#[payload]" level="INFO" doc:name="Logger"/>
</flow>
----
| reconnectionAttempts  |尝试重新建立与MQ后端服务器的连接的次数。
-1默认值表示永久重试。

*Required:*否+
*Default:* -1 +
*XML Example:*

[source,xml,linenums]
----
<flow name="mqAsEndpointFlow">
    <anypoint-mq:subscriber config-ref="Anypoint_MQ_Configuration" destination="Q1" 
    doc:name="Anypoint MQ" reconnectionAttempts="-1" reconnectionWaitTime="3000"/>
    <logger message="#[payload]" level="INFO" doc:name="Logger"/>
</flow>
----
|===

== 关于订阅XML元素

[%header,cols="25s,75a"]
|===
| XML元素 |描述
|目的地 |队列名称。

*Required:*是+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
    <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration"
     doc:name="Anypoint MQ" destination="MyQ"
     acknowledgementMode="NONE" acknowledgementTimeout="42"
     pollingTime="99000">
    </anypoint-mq:consume>
</flow>
----
| acknowledgementMode  |模式选项为`From configuration (Default)`，`AUTO`，
`MANUAL`或`NONE`。了解更多信息，
请参阅 link:/anypoint-mq/mq-ack-mode[Anypoint MQ确认模式]。默认模式
自动确认发送到目标队列的每条消息。

*Required:*否+
如果连接器是消息处理器，则*Default:* MANUAL，
或者如果连接器是入口点+，则从配置开始
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
    <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration" doc:name="Anypoint MQ"
     destination="ImaQ" acknowledgementMode="NONE" acknowledgementTimeout="42"
     pollingTime="99000">
    </anypoint-mq:consume>
</flow>
----
| acknowledgementTimeout  |直到确认模式的持续时间（以毫秒为单位）
超时。

*Required:*否+
*Default:*无+
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
    <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration" doc:name="Anypoint MQ"
     destination="ImaQ" acknowledgementMode="NONE" acknowledgementTimeout="42"
     pollingTime="99000">
    </anypoint-mq:consume>
</flow>
|pollingTime |Duration in milliseconds that the MQ connector polls a queue for messages.

*Required:* No +
*Default:* None +
*XML Example:*

[source,xml,linenums]
----
<flow name="demoFlow">
     <http:listener config-ref="HTTP_Listener_Configuration" path="/" doc:name="HTTP"/>
     <anypoint-mq：consume config-ref = "Anypoint_MQ_Configuration" doc：name = "Anypoint MQ"
      destination = "ImaQ" acknowledgementMode = "NONE" acknowledgementTimeout = "42"
      pollingTime = "99000">
     </anypoint-mq:consume>
</flow>
| reconnectionWaitTime  |尝试重新连接到MQ后端服务器之前要等待的持续时间（以毫秒为单位）。

*Required:*否+
*Default:* 3000毫秒（3秒）+
*XML Example:*

[source,xml,linenums]
----
<flow name="mqAsEndpointFlow">
    <anypoint-mq:subscriber config-ref="Anypoint_MQ_Configuration" destination="Q1" 
    doc:name="Anypoint MQ" reconnectionAttempts="-1" reconnectionWaitTime="3000"/>
    <logger message="#[payload]" level="INFO" doc:name="Logger"/>
</flow>
----
| reconnectionAttempts  |尝试重新建立与MQ后端服务器的连接的次数。
-1默认值表示永久重试。

*Required:*否+
*Default:* -1 +
*XML Example:*

[source,xml,linenums]
----
<flow name="mqAsEndpointFlow">
    <anypoint-mq:subscriber config-ref="Anypoint_MQ_Configuration" destination="Q1" 
    doc:name="Anypoint MQ" reconnectionAttempts="-1" reconnectionWaitTime="3000"/>
    <logger message="#[payload]" level="INFO" doc:name="Logger"/>
</flow>
----
|===

== 另请参阅

*  link:/anypoint-mq/[Anypoint MQ文档]
