= 授权授予类型
:keywords: http, authentication, security, users, connectors, anypoint, studio, oauth

消费者可以通过四种方式获得授权以与OAuth服务提供商共舞。

.  <<Authorization Code>>

.  <<Implicit>>

.  <<Resource Owner Password Credentials>>

.  <<Client Credentials>>

下面的部分按照安全级别按降序提供每种授权授权的简要说明。有关OAuth角色和OAuth舞曲的详细信息，请参阅 link:/mule-user-guide/v/3.8/mule-secure-token-service[Mule安全令牌服务]文档。

== 授权码

对于服务提供商而言，此授权类型包含使用*authorization server*（负责确认和授予访问受保护资源的权限）和*resource server*（负责提供对受保护资源的访问权限）。尽管被描述为独立的服务器，但授权和资源实体实际上驻留在相同的Mule服务器上。消费者必须要求服务提供商请求受保护资源的权限，然后才能要求受保护的资源。

涉及授权代码授权类型的OAuth舞蹈按以下方式进行：

. 客户端应用程序想要使用由服务提供商托管的数据（受保护资源），因此会启动请求以将数据访问到服务提供商。

. 客户端应用程序调用服务提供商的授权服务器，提供其客户端ID以确认它是服务提供商的注册客户端。

. 客户端应用程序使用服务提供商提供的登录页面要求资源所有者使用访问凭据向服务提供商进行身份验证。

. 在确认客户端ID有效（即客户端应用程序先前已向服务提供商注册）并通过登录凭证对资源所有者进行身份验证之后，服务提供商将返回授权代码。

. 客户端应用程序再次调用授权服务器，提供其授权码，客户端ID（再次）以及客户端密码。

. 服务提供者返回一个令牌，在该令牌中指定范围。

. 客户端应用程序调用资源服务器，提供令牌，以请求受保护的资源（数据）。

. 服务提供商提供受保护的资源。

这种类型的授权授权是特别安全的，因为它对客户端进行了身份验证，并在不将该令牌暴露给未授权方（包括资源所有者）的情况下传输令牌。

== 隐

与授权代码一样，隐式授权类型涉及授权服务器和资源服务器。但是，服务提供商不是通过额外的步骤来通过授权代码和客户端密码来验证客户端应用程序，而是基于客户端ID来验证客户端，然后简单地将令牌移交给访问受保护的资源。

涉及隐式授予类型的O​​Auth舞蹈按以下方式进行：

. 客户端应用程序想要使用由服务提供商托管的数据（受保护资源），因此会启动请求以将数据访问到服务提供商。

. 客户端应用程序调用服务提供商的授权服务器，提供其客户端ID以确认它是服务提供商的注册客户端。

. 客户端应用程序使用服务提供商提供的登录页面要求资源所有者使用访问凭据向服务提供商进行身份验证。

. 在确认客户端ID有效（即客户端应用程序之前已向服务提供商注册）并通过登录凭证验证资源所有者之后，服务提供商将返回令牌。

. 客户端应用程序调用资源服务器，提供令牌，以请求受保护的资源（数据）。

. 服务提供商提供受保护的资源。

授权代码的简化版本，隐式授权类型优化了使用脚本语言（如Javascript）在浏览器中实现的客户端的性能。但是，此授予类型可能会将令牌暴露给资源所有者或资源所有者的用户代理。

== 资源所有者密码凭据

对于这种类型的授权，客户端应用程序只是要求资源所有者共享他们的服务提供者登录凭证。然后，客户端应用程序访问服务提供者并使用共享登录凭证登录资源所有者的帐户。服务提供商接受有效的登录凭据并授予客户端应用程序对资源所有者帐户的完全访问权限。在这种情况下，资源所有者必须相信客户端应用程序不会滥用其信任来共享对私人数据的访问。

涉及资源所有者密码凭证的OAuth舞曲如下所示：

. 资源所有者向客户端应用程序__提供访问凭据

. 客户端应用程序调用服务提供者，提供客户端ID以确认它是服务提供者的注册客户端，以及受保护资源的访问凭证，并请求令牌。

. 服务提供商对客户端应用程序进行身份验证并验证访问凭据，然后发出令牌。

. 客户端应用程序调用资源服务器，提供令牌，以请求受保护的资源（数据）。

. 服务提供商提供受保护的资源。

提供更短版本的OAuth Dance，这种类型的授权许可优化了性能，代价是共享安全访问凭证。

== 客户端凭证

对于这种类型的授权，客户端应用程序请求访问与特定资源所有者无关的数据。由于不涉及受保护的资源，因此服务提供商只能验证客户端是否有效。这种类型的OAuth交互有时被称为"two-legged OAuth"，因为它只涉及两个角色：服务提供商和客户端应用程序。其他三种授权类型涉及第三个角色，即资源所有者，因此有时称为"three-legged OAuth"。

涉及客户端凭证的OAuth舞蹈按以下方式进行：

. 客户端应用程序调用授权服务器，提供客户端ID以确认它是服务提供商的注册客户端。

. 在确认客户端ID有效（即客户端应用程序先前向服务提供商注册）后，服务提供商将返回一个令牌，指定范围。

. 客户端应用程序调用资源服务器，提供令牌以请求特定数据。

. 客户端应用程序检索数据。

通常，当客户端也是资源所有者时，此授权许可适用。
