=  Cassandra连接器操作参考

Cassandra连接器是使用Apache Cassandra 3.1的DataStax Java驱动程序实现的。该连接器暴露了javadoc中描述的多个操作。其中一些操作接受一些自定义普通Java对象（PO​​JO）作为输入参数，这是DataSense功能所需的。

== 添加新列

此操作的输入是：

* 参数：表名
* 可选密钥空间名称
* 有效负载：一个AlterColumnInput POJO
+
POJO具有以下领域：
+
** 要创建的列的名称
** 新列的数据类型

----
%dw 1.0
%output application/java
---
{
    "column": payload.column,
    "type": payload.type
} as :object {
    class : "com.mulesoft.mule.cassandradb.metadata.AlterColumnInput"
}
----

== 更改列类型

您需要连接到支持更改列类型的Cassandra数据库版本，如Cassandra连接器发行说明中所述。此操作将列的数据类型更改为由Cassandra查询语言（CQL）定义并显示在下表中的另一个有效且兼容的类型：

*Valid Type Changes for Non-clustering Columns*

[frame=none]
|===
|  *Change From*  |  *Change To*
|  ascii，bigint，boolean，decimal，double，float，inet，int，timestamp，timeuuid，uuid，varchar，varint  |  blob
|  {INT {1}} varint
|  {文本{1}} VARCHAR
|  {timeuuid {1}} UUID
|  {VARCHAR {1}}文本
|===

*Valid Type Changes for Clustering Columns*

[frame=none]
|===
|  *Change From*  |  *Change To*
|  {INT {1}} varint
|  {文本{1}} VARCHAR
|  {VARCHAR {1}}文本
|===

此操作的输入是：

* 参数：表名
* 可选密钥空间名称
* 有效负载：一个AlterColumnInput POJO
+
有效载荷中的POJO包含以下内容的字段：
+
** 列名称
** 该列的新数据类型

----
%dw 1.0
%output application/java
---
{
    "column": payload.column,
    "type": payload.type
} as :object {
    class : "com.mulesoft.mule.cassandradb.metadata.AlterColumnInput"
}
----

== 创建Keyspace

这个操作接受一个自定义的POJO CreateKeyspaceInput作为输入。

使用SimpleStrategy为此操作输入的是：

*  Keyspace的名字
* 复制因子
* 复制策略类

使用Transform Message组件传递参数以将负载转换为Java对象。

*SimpleStrategy DataWeave Code Example*

----
%dw 1.0
%output application/java
---
{
    "keyspaceName": payload.keyspaceName,
    "replicationFactor": payload.replicationFactor,
    "replicationStrategyClass": payload.replicationStrategyClass
} as :object {
    class : "com.mulesoft.mule.cassandradb.metadata.CreateKeyspaceInput"
}
----

使用NetworkTopologyStrategy输入参数为：

*  Keyspace名称
* 数据中心名称和复制值
* 复制策略类

*NetworkTopologyStrategy DataWeave Code Example*

----
%dw 1.0
%output application/java
---
{
  firstDataCenter: {
    name: payload.dcA,
    value: payload.repfactorA
  },
  nextDataCenter: {
    name: payload.dcB,
    value: payload.repfactorB
  },
  nextDataCenter: {
    name: payload.dcC,
    value: payload.repfactorC
  },
  keyspaceName: payload.keyspaceName,
  replicationStrategyClass: payload.replicationStrategyClass
} as :object {
    class : "com.mulesoft.mule.cassandradb.metadata.CreateKeyspaceInput"
}
----


== 创建表格

这个操作接受一个自定义的POJO CreateTableInput作为输入。

此操作的输入是：

* 列名称
* 表名
* 可选密钥空间名称

----
%dw 1.0
%output application/java
---
{
    "columns": payload.columns,
    "tableName": payload.tableName,
    "keyspaceName": payload.keyspaceName
} as :object {
    class : "com.mulesoft.mule.cassandradb.metadata.CreateTableInput"
}
----

在这个例子中，keyspaceName参数是可选的。如果您未提供此参数，则在运行应用程序时，将在`mule.app.properties`中指定的密钥空间中创建表。

== 删除列值

此操作的输入是：

* 参数：表名称作为参数
* 可选密钥空间名称
* 有效载荷：有`where`和`columns`两个记录的`Map<String, Object>`

与**Update**操作类似，`where`记录表示指定要更新的对象的主键的子句。 `columns`记录表示包含要清除的列名称的`List<String>`。

在获取更新的实体时调用此操作后，**Delete Columns Value**操作中指定的列的值为空。

您可以将集合存储在Cassandra的特定列中。在此操作中，您可以删除这些集合中的特定值而不删除整个集合。

传递给处理器的有效载荷具有以下结构：

----
%dw 1.0
%output application/java
---
{
    "columns":payload.columns,
    "where":payload.where
}
----

从列表中删除元素的HTTP请求如下所示：

----
{
    "where":
      {
        "id": [1]
      },
      "columns": ["top_places[0]"]
}
----

从地图中删除元素的HTTP请求如下所示：

----
{
    "where":
      {
        "id": [1,2]
      },
      "columns": ["mapColumnName['keyName']"]
}
----

== 删除行

此操作的输入是：

* 参数：表名
* 可选密钥空间名称
* 使用包含WHERE子句的关键字`where`和值`Map<String, Object>`的一条记录载入`Map<String, Object>`。

如果要从具有复合主键的表中删除行，请在`where`中指定一个包含列名称作为键和列值作为值的映射。您一次只能删除一行。

----
{
    "where":
      {
        "id": 2,
        "name": "name_to_delete"
      }
}
----

一个复合主键由多个列组成，其中一个是分区键。其他人正在聚集列。在此示例中，id是分区键，name是聚簇列。

如果要从具有简单主键的表中删除行，请在`where`中指定一个映射，其中包含一个条目，其中列名称为键，值列表为值。多行可以一次删除。

----
{
    "where":
      {
        "id": [2,3]
      }
}
----


一个简单的主键具有一个分区键的列。

== 删除列

此操作的输入是：

* 参数：表名
* 可选密钥空间名称
* 有效负载：列名称

== 放弃Keyspace

此操作接受表示密钥空间名称的String参数。

== 删除表

此操作的输入是：

* 表名
* 包含表的键空间

== 执行CQL查询

此操作的输入是：

* 一个自定义的POJO（CQLQueryInput）
+
代表查询的字符串。查询可以是参数化的或不是。
* 传递给参数化查询的可选参数列表。

=== 执行CQL查询示例

*Transform Message Payload*

----
%dw 1.0
%output application/java
---
{
    "cqlQuery": payload.cqlQuery,
    "parameters": payload.parameters
}
as :object {
    class : "com.mulesoft.mule.cassandradb.metadata.CQLQueryInput"
}
----

*HTTP Request to the `<execute-cql-query>` Processor*

----
{
"cqlQuery":"SELECT * FROM users WHERE id IN (?,?)",
"parameters":
    [2,3]
}
----

== 从Keyspace获取表名

此操作接受一个字符串参数，指定操作的密钥空间名称。处理器返回指定密钥空间中的表的列表。

== 插入

此操作的输入是：

* 参数：表名称作为参数
* 有效负载：表示要插入表中的实体的`Map<String, Object>`。
* 可选密钥空间名称

=== 插入示例

*Transform Message Payload*

----
%dw 1.0
%output application/java
---
{
    "id": payload.id,
    "name": payload.name,
    "other_property": payload.other_property
}
----

*Example of an HTTP request for the Insert Operation*

----
{
    "id":3,
    "name":"entity_name",
    "other_property":other_property_value
}
----

== 重命名列

此操作的参数是：

* 表名
* 旧列名称
* 新的列名称

== 选择

此操作的输入是：

* 表示查询的字符串
* 代表查询参数的可选的Object类型的列表。

您可以使用查询生成器构建查询。

== 更新

此操作的输入是：

* 参数：表名
* 可选密钥空间名称
* 有效负载：`Map<String, Object>`带有两个记录`where`和`columns`。
+
**  `where Map<String, Object>`
+
表示指定要更新的对象的主键的子句。
+
----
"where":
      {
        "id": 1,
        "name": "bestseller1"
      }
----
+
**  `columns Map<String, Object>`
+
表示包含列名称和要为该列设置的值的对。
+
----
"columns":
    {
    "name": "test value"
    }
----

当您使用转换消息组件为此操作设置负载时，您会看到设置负载所需的详细信息。

您可以选择要更新的列并指定WHERE子句。 `columns`部分包含为该操作选择的表中的所有列;而在`where`部分中，仅显示主键一部分的列。 CQL语法规定只能在WHERE子句中指定主键中的列。


== 另请参阅

*  link:/release-notes/cassandra-connector-release-notes[Cassandra连接器发行说明]
*  link:https://docs.datastax.com/en/developer/java-driver/3.1/manual/[用于Apache Cassandra的Datastax Java驱动程序]
*  link:https://cassandra.apache.org/doc/old/CQL-3.0.html[CQL文档]
