：toc：离开
：toc-title：连接器摘要
：toclevels：2
：最后更新标签!:
：文档信息：
：source-highlighter：coderay
：图标：字体


=  Mongo DB连接器API参考

+++
MongoDB是一个开源，高性能，无模式，面向文档的数据库，用于管理BSON文档的集合。
+++

*Additional Info*
[width="50", cols=".<60%,^40%" ]
|======================
| 需要Mule Enterprise许可证 |  是{
| 需要权利 |  否{
|  Mule版本 |  3.6.0或更高版本
|======================


==  CONFIGS
---
=== 配置
`<mongo:config>`


`Connection Management`



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
| 名称 |  Java类型 | 描述 | 默认值 | 必需
|姓名 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 此配置的名称。此名称可以稍后参考。 |  |  *x* {nbsp}
| 用户名 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++用于身份验证的用户名+++ {{5} } |  {} NBSP
| 密码 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++用于身份验证的密码。如果密码仅为空白或空白，连接器将不会使用认证，并且用户名也必须为空。+++  |    |  {nbsp}
| 数据库 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++数据库名称+++  |    |  *x* {} NBSP
| 主机 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++格式为<code>的MongoDB实例列表host：port </code>，用逗号分隔。
<p>
<pre>
例如：127.0.0.1:27017,192.168.1.2:27017
</pre> {+++ {1}}本地主机：27017  |  {} NBSP
|  connectionsPerHost  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++每个主机允许的连接数（每个主机的池大小）+++  |    |  {} NBSP
|  threadsAllowedToBlockForConnectionMultiplier  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++ MultiPlier for connectionsPerHost用于可阻塞的线程数+++  |    |  {} NBSP
|  maxWaitTime  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++来自池的连接的阻塞线程的最长等待时间以毫秒为单位。+++  |    |  {nbsp}
|  connectTimeout  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++连接超时（以毫秒为单位;这是为了建立套接字连接（打开）。 0为默认且无限。+++  |   30000  |  {nbsp}
|  socketTimeout  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++套接字超时。 0为默认且无限。+++  |    |  {nbsp}
|  ssl  |  +++布尔型+++  |  +++这用于启用SSL连接。它被默认禁用。+++  |   false  |  {nbsp}
|  {authenticationDatabase {3}} {+++ {0}}字符串</a> {+++ {4}} ++++++  |    |  { NBSP}
|======================
---
=== 连接字符串
`<mongo:config-connection-string>`


`Connection Management`



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
| 名称 |  Java类型 | 描述 | 默认值 | 必需
|姓名 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 此配置的名称。此名称可以稍后参考。 |  |  *x* {nbsp}
| 的connectionString  |  {+++ {0}}字符串</a> {+++ {5}} ++++++  |    |  { {2}} {} NBSP
|======================



== 处理器

---

=== 添加用户
`<mongo:add-user>`




+++
为这个数据库添加一个新用户
+++

====  XML示例
[source,xml]
----
<mongo:add-user config-ref="Mongo_DB__Configuration" newUsername="myUser" newPassword="myPassword"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
新用户名  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++用户名称+++  |   |  *x* {NBSP}




|
newPassword   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++将用于认证的密码+++  |   |  {{ 2}} {} NBSP


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++操作结果+++
|======================




---

=== 删除数据库
`<mongo:drop-database>`




+++
删除当前数据库
+++

====  XML示例
[source,xml]
----
<mongo:drop-database config-ref="Mongo_DB__Configuration"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP

|======================





---

=== 列出集合
`<mongo:list-collections>`




+++
列出此数据库可用集合的名称
+++

====  XML示例
[source,xml]
----
<mongo:list-collections config-ref="Mongo_DB__Configuration"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP

|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">可重用</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++此数据库中可用集合的名称列表+++
|======================




---

=== 存在集合
`<mongo:exists-collection>`




+++
答案，如果一个集合存在给定其名称
+++

====  XML示例
[source,xml]
----
<mongo:exists-collection config-ref="Mongo_DB__Configuration" collection="aColllection"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection+++ | #[有效载荷]  |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++布尔+++  |  +++如果集合存在+++
|======================




---

=== 删除集合
`<mongo:drop-collection>`




+++
删除一个集合及其包含的所有对象。如果集合不存在，则什么也不做。
+++

====  XML示例
[source,xml]
----
<mongo:drop-collection config-ref="Mongo_DB__Configuration" collection="aCollection"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection to drop+++ | #[有效载荷]  |  {nbsp}


|======================





---

=== 创建集合
`<mongo:create-collection>`




+++
创建一个新的集合。如果集合已经存在，则会抛出MongoException。
+++

====  XML示例
[source,xml]
----
<mongo:create-collection config-ref="Mongo_DB__Configuration" collection="aCollection" capped="true"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要创建的集合的名称+++  |   |  {{ 2}} {} NBSP




|
如果集合被封顶，则  |  +++布尔型+++  |  +++ +++  |  false  |  {nbsp}




|
maxObjects   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++新集合可以包含的最大文档数+++  |   { 5}} {} NBSP




|
大小  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++新集合的最大大小+++  |   |  {nbsp }


|======================





---

=== 插入文档
`<mongo:insert-document>`




+++
将文档插入到集合中，并在必要时设置其ID。
+++

====  XML示例
[source,xml]
----
<mongo:insert-document config-ref="Mongo_DB__Configuration" collection="Employees">
        </mongo:insert-document>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要插入给定文档的集合的名称+++ {{5} } |  *x* {} NBSP




|
文档  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>实例+++ {{ 6}}＃[有效载荷]  |  {} NBSP


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++刚刚插入的id +++
|======================




---

=== 插入文档
`<mongo:insert-documents>`




+++
在集合中插入文档列表，并在必要时设置其ID。
+++

====  XML示例
[source,xml]
----
<mongo:insert-documents config-ref="Mongo_DB__Configuration" collection="Employees">
        </mongo:insert-documents>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要插入给定文档的集合的名称+++ {{5} } |  *x* {} NBSP




|
文档  |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>>+++ | +++a <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a> of <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>.+++ | #[有效载荷]  |  {nbsp}




|
有序  |  +++布尔+++  |  +++指示写操作列表是有序的还是无序的。默认情况下，如果在处理其中一个写入操作期间发生错误，则MongoDB将返回而不处理列表中剩余的任何写入操作。+++  |  true  |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>，其运算结果为+++
|======================




---

=== 更新文档
`<mongo:update-documents>`




+++
更新与给定查询匹配的文档。如果未指定查询，则检索所有文档。如果参数multi设置为false，则只匹配第一个文档
它会被更新。否则，所有与之匹配的文档都会被更新。
+++

====  XML示例
[source,xml]
----
<mongo:update-documents config-ref="Mongo_DB__Configuration" collection="myCollection" query-ref="#[payload]">
        </mongo:update-documents>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要更新的集合的名称+++  |   |  {{ 2}} {} NBSP




|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++用于检测元素的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>查询对象更新。+++  |   |  {nbsp}




|
元素  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>强制对象将替换该文档与查询匹配+++  | ＃[有效载荷]  |  {nbsp}




|
多个  |  +++布尔+++  |  +++如果全部或仅匹配查询的第一个文档将被更新+++  |  true  |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">更新状态为+++的文档{{3}
|======================




---

=== 按功能更新文档
`<mongo:update-documents-by-function>`




+++
使用mongo函数更新文档。如果未指定查询，则检索所有文档。
<p/>
+++

====  XML示例
[source,xml]
----
<mongo:update-documents-by-function config-ref="Mongo_DB__Configuration" collection="myCollection" element-ref="#[payload]" upsert="true" function="$set">
        </mongo:update-documents-by-function>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要更新的集合的名称+++  |   |  {{ 2}} {} NBSP




|
函数  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++用于执行更新的函数+++  |   |  {{ 2}} {} NBSP




|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++用于检测元素的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>查询文档更新。+++  |   |  {nbsp}




|
元素  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>强制性文档将取代该文档与查询匹配+++  | ＃[有效载荷]  |  {nbsp}




|
upsert   |  +++布尔型+++  |  +++如果数据库应该创建该元素（如果该元素不存在），则为+++  |  false  |  {nbsp}




|
多个  |  +++布尔+++  |  +++如果全部或只是第一个匹配查询的文档将被更新。+++  |  true  |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">具有更新状态的文档</a> +++
|======================




---

=== 通过函数更新文档
`<mongo:update-documents-by-functions>`




+++
使用一个或多个mongo函数更新文档。如果未指定查询，则检索所有文档。如果有重复的操作员。只有最后一个会是
执行。
<p/>
+++




==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要更新的集合的名称+++  |   |  {{ 2}} {} NBSP




|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++用于检测元素的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>查询文档更新+++  |   |  {nbsp}




|
函数  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++用于执行更新的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>函数。例如<$set,{"key":123}> +++  | ＃[有效载荷]  |  {} NBSP




|
upsert   |  +++ boolean +++  |  +++数据库是否应该创建该元素（如果该元素不存在）+++  |  false  |  {nbsp}




|
多个  |  +++布尔+++  |  +++如果全部或仅匹配查询的第一个文档将被更新+++  |  true  |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">具有更新状态的文档</a> +++
|======================




---

=== 保存文档
`<mongo:save-document>`




+++
基于其对象_id插入或更新文档。
+++

====  XML示例
[source,xml]
----
<mongo:save-document config-ref="Mongo_DB__Configuration" collection="myCollection">
        </mongo:save-document>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++插入对象的集合+++  |   |  {{ 2}} {} NBSP




|
文档  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++要插入的强制性<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>文档。 +  | ＃[有效载荷]  |  {} NBSP


|======================





---

=== 删除文件
`<mongo:remove-documents>`




+++
删除与给定的可选查询匹配的所有文档。如果未指定查询，则会删除所有文档。不过，请注意，这通常较少
高性能，丢弃集合并再次创建它和它的索引
+++

====  XML示例
[source,xml]
----
<mongo:remove-documents config-ref="Mongo_DB__Configuration" collection="myCollection">
        </mongo:remove-documents>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++元素将被删除的集合+++  |   |  {{ 2}} {} NBSP




|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++可选<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>查询对象。与其匹配的文档将被删除。+++  | ＃[有效内容]  |  {nbsp}


|======================





---

=== 地图缩小对象
`<mongo:map-reduce-objects>`




+++
通过将一个提供的元素映射函数应用于每个元素，将每个元素转换为一个键值，将一个集合转换为聚合组的集合
对，按键对结果对进行分组，最后使用suppling'reduce'函数减少每个组中的值。
<p/>
每个提供的功能都使用JavaScript编码。
<p/>
请注意，编写这些函数的正确方式可能并不明显;请参考MongoDB文档编写它们。
+++

====  XML示例
[source,xml]
----
<mongo:map-reduce-objects config-ref="Mongo_DB__Configuration" collection="myCollection" mapFunction="myMapFunction" reduceFunction="myReduceFunction"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++映射和减少集合的名称+++  |   |  *x* {} NBSP




|
JavaScript编码映射函数+++  |   |  *x* {} {+} {+} } {} NBSP




|
JavaScript函数+++   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++ JavaScript编码减少函数+++  |   |  {{2} } {} NBSP




|
outputCollection   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++输出集合的名称以写入结果，替换以前的集合（如果存在）结果可能会大于16MB。如果未指定outputCollection，则计算在内存中执行并且不会持久化。+++  |   |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">可迭代</a> <<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>> +++  |  +++一个迭代器，用于检索<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">的结果集合Document { {4}} +++
|======================




---

=== 统计文件
`<mongo:count-documents>`




+++
计算与给定查询匹配的文档数量。如果没有查询通过，则返回集合中元素的数量
+++

====  XML示例
[source,xml]
----
<mongo:count-documents config-ref="Mongo_DB__Configuration" collection="myCollection" query-ref="dbObject"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++目标集合+++  |   |  *x* { NBSP}




|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/conversions/Bson.html"> Bson </a> +++  |  +++用于计数文档的可选<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>查询。只有匹配它的文档才会被计入。如果未指定，则会计算所有文档。+++  | ＃[有效负载]  |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ long +++  |  +++匹配查询+++的文档数量
|======================




---

=== 查找文档
`<mongo:find-documents>`




+++
查找与给定查询匹配的所有文档。如果未指定查询，则会检索集合的所有文档。如果没有指定字段对象，则所有字段都是
检索。
+++

====  XML示例
[source,xml]
----
<mongo:find-documents config-ref="Mongo_DB__Configuration" collection="myCollection" limit="5" numToSkip="10" query-ref="#[payload]" sortBy-ref="#[new org.bson.Document()]">
            <mongo:fields>
                <mongo:field>field1</mongo:field>
                <mongo:field>field2</mongo:field>
            </mongo:fields>
        </mongo:find-documents>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++目标集合+++  |   |  *x* { NBSP}




|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++可选<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>查询文档。如果未指定，则返回所有文档。+++  | ＃[有效负载]  |  {nbsp}




|
字段  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++将字段作为字面值传递的另一种方法List +++  |   |  {} NBSP




|
numToSkip   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++数量的文档skip（offset）+++  |   {{5} } {} NBSP




|
限制  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++文档返回限制+++  |   |  {nbsp}




|
sortBy   |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++表示用于对结果进行排序的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++ { {6}} |  {} NBSP


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">可重用</a> <<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>> +++  |  +++可迭代的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> + ++
|======================




---

=== 查找一个文档
`<mongo:find-one-document>`




+++
查找与给定查询匹配的第一个文档。如果没有人匹配给定的查询，则抛出MongoException
+++

====  XML示例
[source,xml]
----
<mongo:find-one-document config-ref="Mongo_DB__Configuration" collection="myCollection">
            <mongo:fields>
                <mongo:field>field1</mongo:field>
                <mongo:field>field2</mongo:field>
            </mongo:fields>
        </mongo:find-one-document>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++目标集合+++  |   |  *x* { NBSP}




|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++强制<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html"> Document </a>查询文档返回的对象匹配。+++  | ＃[有效载荷]  |  {} NBSP




|
字段  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++将字段作为字面值传递的另一种方法List +++  |   |  {} NBSP




|
failOnNotFound   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">布尔值</a> +++  |  +++指定是否在未找到对象时抛出异常。为了向后兼容，默认值为true。+++  |  true  |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
与查询匹配的| +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>。如果没有匹配并且failOnNotFound设置为false，则null将返回+++
|======================




---

=== 查找并更新文档
`<mongo:find-one-and-update-document>`




+++
查找并更新与给定查询匹配的第一个文档。当returnNew = true时，返回更新的文档而不是原始文档。
+++




==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++目标集合+++  |   |  *x* { NBSP}




|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++返回的对象匹配的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>查询。 +++  |   |  {} NBSP




|
元素  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>强制对象将替换该文档匹配查询+++  | ＃[有效载荷]  |  {nbsp}




|
字段  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++将字段作为字面值传递的另一种方法List +++  |   |  {} NBSP




|
returnNewDocument   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">布尔值</a> +++  |  +++标记以指定返回的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html"> Document </a>应该是更新的文件而不是原件。默认为false，修改前返回文档+++  |  false  |  {nbsp}




|
sortBy   |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++表示用于排序结果的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>。 +++  |   |  {} NBSP




|
删除  |  +++布尔+++  |  +++删除查询字段中指定的<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>。默认为false +++  |  false  |  {nbsp}




|
upsert   |  +++ boolean +++  |  +++数据库是否应该创建该元素（如果该元素不存在）+++  |  false  |  {nbsp}




|
bypassDocumentValidation   |  +++布尔+++  |  +++允许您更新不符合验证要求的文档。默认为false +++  |  false  |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
与查询匹配的| +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>。如果没有匹配，null将返回+++
|======================




---

=== 创建索引
`<mongo:create-index>`




+++
创建一个新的索引
+++

====  XML示例
[source,xml]
----
<mongo:create-index config-ref="Mongo_DB__Configuration" collection="myCollection" field="myField" order="DESC"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++索引创建集合的名称+++  |   {{6 }} *x* {} NBSP




|
字段  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++将被索引的字段的名称+++  |   |  *x* {} NBSP




|
顺序  |  +++ <a href="javadocs/org/mule/modules/mongo/api/IndexOrder.html"> IndexOrder </a> +++  |  +++索引顺序+++  |  ASC  |  {n}


|======================





---

=== 删除索引
`<mongo:drop-index>`




+++
丢弃现有的索引
+++

====  XML示例
[source,xml]
----
<mongo:drop-index config-ref="Mongo_DB__Configuration" collection="myCollection" index="myIndex"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++索引为+++  |   | 的集合的名称} *x* {} NBSP




|
索引  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要删除的索引的名称+++  |   |  {{ 2}} {} NBSP


|======================





---

=== 列出索引
`<mongo:list-indices>`




+++
列出集合中已有的索引
+++

====  XML示例
[source,xml]
----
<mongo:list-indices config-ref="Mongo_DB__Configuration" collection="myCollection"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
集合  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++集合的名称+++  |   |  {{2} } {} NBSP


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/Collection.html">收藏集</a> <<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>> +++  |  +++收集<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>指数信息+++
|======================




---

=== 从有效载荷创建文件
`<mongo:create-file-from-payload>`




+++
在数据库中创建一个新的GridFSFile，保存给定的内容，文件名，contentType和extraData，然后回答它。
+++

====  XML示例
[source,xml]
----
<mongo:create-file-from-payload config-ref="Mongo_DB__Configuration" filename="#[variable:filename]" metadata-ref="myDbObject"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
有效载荷  |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++the mandatory content of the new gridfs file. It may be a java.io.File, a byte[]或InputStream。+++  | ＃[有效载荷]  |  {nbsp}




|
文件名  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++新文件的强制名称+++  |   {{6} } *x* {} NBSP




|
元数据  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++新内容类型的可选<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>元数据+++  |   |  {} NBSP


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html"> GridFSFile </a> +++  |  +++新的GridFSFile <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html"> GridFSFile </a> +++
|======================




---

=== 查找文件
`<mongo:find-files>`




+++
列出与给定查询匹配的所有文件
+++

====  XML示例
[source,xml]
----
<mongo:find-files config-ref="Mongo_DB__Configuration" query-ref="myDbObject" />
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>查询+++  | ＃ [有效载荷]  |  {} NBSP


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">可迭代</a> <<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html"> GridFSFile </a>文件可迭代+++
|======================




---

=== 查找一个文件
`<mongo:find-one-file>`




+++
解决与给定查询匹配的第一个文件。如果没有对象匹配，则抛出MongoException。
+++

====  XML示例
[source,xml]
----
<mongo:find-one-file config-ref="Mongo_DB__Configuration" query-ref="myDbObject" />
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>强制查询+++  |  ＃[有效载荷]  |  {} NBSP


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html"> GridFSFile </a> +++  |  +++ a <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html"> GridFSFile </a> +++
|======================




---

=== 获取文件内容
`<mongo:get-file-content>`




+++
解答与给定查询匹配的第一个文件内容的输入流。如果没有对象匹配，则抛出MongoException。
+++

====  XML示例
[source,xml]
----
<mongo:get-file-content config-ref="Mongo_DB__Configuration" query-ref="myDbObject" />
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
fileId   |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/BsonObjectId.html"> BsonObjectId </a> +++  |  +++要删除文件的BsonObjectId +++  | ＃[payload] {{ 5}} {} NBSP


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html"> InputStream </a> +++  |  +++输入流到文件内容+++
|======================




---

=== 列出文件
`<mongo:list-files>`




+++
列出与给定查询匹配的所有文件，并按文件名对它们进行排序。如果未指定查询，则列出所有文件。
+++

====  XML示例
[source,xml]
----
<mongo:list-files config-ref="Mongo_DB__Configuration" query-ref="myDbObject"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
查询  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a>可选查询+++  |  ＃[有效载荷]  |  {} NBSP


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">可迭代</a> <<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>> +++  |  +++可迭代的<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html"> GridFSFile </a> + ++
|======================




---

=== 删除文件
`<mongo:remove-files>`




+++
删除与给定文件ID相匹配的文件。如果未指定文件标识，则删除所有文件
<p/>
+++

====  XML示例
[source,xml]
----
<mongo:remove-files config-ref="Mongo_DB__Configuration" query-ref="myDbObject"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
fileId   |  +++ <a href="https://api.mongodb.org/java/3.1/org/bson/BsonObjectId.html"> BsonObjectId </a> +++  |  +++要删除文件的BsonObjectId +++  | ＃[payload] {{ 5}} {} NBSP


|======================





---

=== 执行命令
`<mongo:execute-command>`




+++
在数据库上执行一个命令
<p/>
+++




==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
commandName   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++在数据库上执行的命令+++  |   |  {{ 2}} {} NBSP




|
commandValue   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++命令的值+++  |   |  {nbsp}


|======================

==== 返回
[cols=".^40%,.^60%", options="header"]
|======================
|返回Java类型 | 描述
| +++ <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">文档</a> +++  |  +++命令的结果+++
|======================




---

=== 转储
`<mongo:dump>`




+++
执行数据库转储到指定的输出目录。如果未提供输出目录，则使用默认/转储目录。
+++

====  XML示例
[source,xml]
----
<mongo:dump config-ref="Mongo_DB__Configuration" oplog="true"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
outputDirectory   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++输出目录路径，如果未提供输出目录，则假定默认/ dump目录为+++ { 4}}转储 |  {} NBSP




|
outputName   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++输出文件名，如果未指定，则使用数据库名称+++  |   { {5}} {} NBSP




|
zip   |  +++布尔+++  |  +++是否压缩创建的转储文件+++  |  false  |  {nbsp}




|
oplog   |  +++布尔型+++  |  +++时间点备份（需要oplog）+++  |  false  |  {nbsp}




|
线程  |  +++ int +++  |  +++执行转储的线程数量+++  |  5  |  {nbsp}


|======================





---

=== 增量转储
`<mongo:incremental-dump>`




+++
执行数据库的增量转储
<p/>
+++

====  XML示例
[source,xml]
----
<mongo:incremental-dump config-ref="Mongo_DB__Configuration" />
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
outputDirectory   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++输出目录路径，如果未提供输出目录，则假定默认/ dump目录为+++ { 4}}转储 |  {} NBSP




|
incrementalTimestampFile   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++文件，用于跟踪上次处理的时间戳，如果未提供任何文件，则会创建一个输出目录+++  |   |  {nbsp}


|======================





---

=== 恢复
`<mongo:restore>`




+++
从转储中获取输出并进行恢复。索引将在恢复时创建。它只会插入数据以进行还原，如果现有数据存在，则不会
被替换。
+++

====  XML示例
[source,xml]
----
<mongo:restore config-ref="Mongo_DB__Configuration" inputPath="dump/test.zip" oplogReplay="true"/>
----



==== 属性
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
inputPath   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++输入转储文件的路径，它可以是目录，zip文件或只是一个bson文件+++  | 转储 |  {nbsp}




|
drop   |  +++ boolean +++  |  +++是否在恢复之前删除现有集合+++  |  false  |  {nbsp}




|
oplogReplay   |  +++布尔型+++  |  +++重播oplog以进行时间点恢复+++  |  false  |  {nbsp}


|======================
