=  Mule安全令牌服务OAuth 2.0提供程序
:keywords: esb, security, oauth, authentication, oauth provider, token, private key, secret key, access key

以下Mule OAuth 2.0解决方案包括使用Mule安全令牌服务：

*  CloudHub API的身份验证
+
Mule安全令牌服务可以为CloudHub托管的API和应用程序提供解决方案。
+
服务器需要* 客户端应用身份验证
+
OAuth 2.0解决方案由连接器提供，例如HTTP或Salesforce连接器
+
* 身份验证以保护客户端的API
+
OAuth 2.0解决方案由API Manager策略提供。


CloudHub API的== 客户端身份验证

由于已知的 link:/runtime-manager/managing-application-data-with-object-stores#semantics-and-storage-limits[对象存储限制]，*CloudHub*上的*Mule OAuth 2.0 Secure Token Service*功能受到限制。

如果这些限制不会影响您的开发，则可以使用Cloudhub上的*Mule OAuth 2.0 Secure Token Service*。否则，请创建您自己的对象存储并将OAuth2模块配置为使用您的自定义对象存储而不是默认对象存储。
有关更多信息，请转到 link:http://www.mulesoft.com/support-login[MuleSoft客户门户]并打开一张票。

使用Mule安全令牌服务将Oauth 2.0应用于您的Web服务提供商，以便：

* 向Web服务的使用者授予对安全数据的有限访问权限
* 避免向最终用户披露Web服务使用者的访问凭证
* 有权随时撤销消费者对最终用户安全数据的访问权限

服务器需要== 客户端身份验证

在向需要身份验证的服务发送请求时，在您的客户端Mule应用中配置身份验证，例如 link:/mule-user-guide/v/3.8/authentication-in-http-requests#oauth2-authorization-code[OAuth2  - 授权码]中介绍的Github OAuth2服务器。

== 身份验证以保护来自客户端的API

如果您希望保护您的API或应用程序免受未经授权的访问请求，请使用API​​ Manager策略，例如OAuth 2.0访问令牌执行使用外部提供者策略。要公开受OAuth 2.0安全保护的Web服务，请参阅 link:/api-manager/building-an-external-oauth-2.0-provider-application[API管理器文档]。

有关Mule中的OAuth的更多信息，请参阅 link:/api-manager/aes-oauth-faq[关于OAuth 2.0]。

== 下一步

运行 link:/mule-user-guide/v/3.8/mule-sts-oauth-2.0-example-application[Mule STS OAuth 2.0示例应用程序]

