= 在Spring中使用Mule
:keywords: anypoint studio, studio, mule, spring

Mule利用Spring框架开发Java应用程序。

== 支持的Spring版本

*  Mule 3.8：Spring 4.1.9和Spring Security 4.0.4
*  Mule 3.7.5：Spring 4.1.9和Spring Security 4.0.4
*  Mule 3.7.0  -  3.7.4：Spring 4.1.6和Spring Security 4.0.1
*  Mule 3.6及更早版本：Spring 3.2和Spring Security 3.0

另请参阅： link:http://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-xml.html[Spring Security迁移3到4]

==  XML配置文件

配置Mule应用程序的方法是使用一个使用自定义Mule命名空间的XML文件。默认情况下，Spring配置生成器使用这个XML文件创建Mule工件，并将它们注册到Mule运行时实例。

使用Mule XML配置文件中的两个命名空间之一：

*  `+http://www.springframework.org/schema/beans+`
*  `+http://www.springframework.org/schema/beans/spring-beans-current.xsd+`

==  Spring应用程序上下文

Mule为您的应用程序创建和管理 link:/mule-user-guide/v/3.8/spring-application-contexts[Spring应用程序上下文]提供了多种选择。

[TIP]
构建Spring bean来定义Mule应用程序可以引用的组件行为。查看 link:/mule-user-guide/v/3.8/using-spring-beans-as-flow-components[使用Spring Beans作为流程组件]

==  Spring Bean定义配置文件

Mule的XML配置文件利用了Spring 4.1.6创建*bean definition profiles*的能力。您可以使用Spring bean定义配置文件为不同的目标环境注册不同的bean，而不是在所有目标环境中使用一个bean。有关更多信息，请参阅Spring Framework Reference中的 link:http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-definition-profiles[Bean定义配置文件]。

== 另请参阅

*  link:/mule-user-guide/v/3.8/about-the-xml-configuration-file[关于XML配置文件]
*  link:/mule-user-guide/v/3.8/about-configuration-builders[关于配置建造者]




