= 关于配置构建器

:keywords: configuration, deploy, mule

配置构建器负责根据您提供的配置文件创建在运行时使用的配置。 Mule运行时提供两个标准配置构建器，或者您可以创建自己的。

==  SpringXmlConfigurationBuilder

用于配置Mule的默认配置生成器是`SpringXmlConfigurationBuilder`。此配置构建器使用Spring基于一个或多个利用自定义Mule命名空间的XML文件来配置Mule运行时实例。有关更多信息，请参阅 link:/mule-user-guide/v/3.9/about-the-xml-configuration-file[关于XML配置文件]。

==  ScriptConfigurationBuilder

此配置构建器允许符合JSR-223的脚本引擎（如Groovy或Jython）配置Mule。有关更多信息，请参阅 link:/mule-user-guide/v/3.9/scripting-module-reference[脚本模块参考]。

== 自定义配置构建器

您可以通过实施 link:http://www.mulesoft.org/docs/site/3.8.0/apidocs/org/mule/api/config/ConfigurationBuilder.html[ConfigurationBuilder]接口来创建自己的自定义配置生成器，该接口具有`configure`方法。通常，您调用`configure(MuleContext muleContext.getRegistry())`来访问Mule的内部注册表，其中包含配置信息，并注册对象和其他元素。

在大多数情况下，你会想要从类继承
http://www.mulesoft.org/docs/site/3.8.0/apidocs/org/mule/config/builders/AbstractResourceConfigurationBuilder.html[AbstractResourceConfigurationBuilder]
，这将使命令行中指定的任何配置文件在名为`configResources`的实例变量中可用。

== 指定配置生成器

AutoConfigurationBuilder是默认的配置生成器。如果您想使用其他配置构建器，则可以在应用程序的 link:/mule-user-guide/v/3.9/mule-application-deployment-descriptor[部署描述符]中指定它。

您还可以在编程启动Mule时将配置生成器指定为MuleContextFactory的参数：

[source,java, linenums]
----
MuleContext context = new DefaultMuleContextFactory().createMuleContext(new ScriptConfigurationBuilder("mule-config.groovy"));
context.start();
----

