= 关于XML配置文件
:keywords: configuration, deploy, mule

所有Mule应用程序都有一个XML文件，用于指定组成应用程序的资源。 link:https://www.w3.org/TR/xmlschema-1/#xsi_schemaLocation[架构]定义在XML配置文件中引用的这些资源的可配置属性。这就是Mule应用程序如何验证和定义其功能组件及其配置。

[NOTE]
阅读下面关于XML配置文件中引用的Spring模式和Mule命名空间的更多信息。

==  XML架构

XML模式用于验证Mule应用程序中的功能组件。它们在标题中指定。

[source,xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance
        xmlns:jms="http://www.mulesoft.org/schema/mule/jms"
        xmlns:file="http://www.mulesoft.org/schema/mule/file"
        xsi:schemaLocation="
        http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/jms http://www.mulesoft.org/schema/mule/jms/current/mule-jms.xsd
        http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd">
----

一定要指定所有必要的模式文件。手动设置配置文件时，这可能非常耗时，但导入模式文件可以节省下列时间：

在您最喜爱的IDE中* 自动完成和特定于上下文的帮助
* 设计时配置验证
* 键入的属性

== 命名空间

每个Mule模块或传输都有自己的XML模式。当你导入一个模式时，它有它自己的名字空间。

要使用标准的Spring元素，请导入两个标准Spring命名空间之一：

*  http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd

*  http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
+
[TIP]
====
使用`spring-beans-current`指示您的应用程序使用Mule中提供的最新版本的Spring。当Spring发布新版本时，您不需要手动更新应用程序中的命名空间。
====

=== 默认命名空间

通常，您将Mule核心模式设置为配置文件的默认命名空间。这意味着任何没有前缀的XML元素都将来自Mule核心模式（`mule.xsd`）。要设置默认名称空间模式，请指定紧跟着Mule模式的URL后面的`xmlns`，不要使用您在前面示例中设置的冒号或名称空间前缀（例如，`xmlns`而不是`xmlns:jms` ）：

[source,xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd">
   ...config...
</mule>
----

==  Spring Bean配置文件定义

虽然你的配置文件似乎是Mule特定的，但它们实际上只是具有Mule特定 http://static.springsource.org/spring/docs/current/spring-framework-reference/html/[扩展]的Spring配置文件。这种方法允许你在Mule配置中使用Spring提供的任何东西，比如bean，工厂bean， http://blog.springsource.org/2011/02/11/spring-framework-3-1-m1-released/[bean配置文件定义]，资源加载器，EJB，JNDI，AOP，甚至与其他软件如Gigaspaces，JBoss Rules等的集成。 。

[source,xml, linenums]
----
xmlns:spring="http://www.springframework.org/schema/beans"
xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd"
...
    <spring:bean id="myBean" class="com.acme.CoolBean">
        <spring:property name="sessionFactory">
            <spring:ref local="mySessionFactory" />
        </spring:property>
        <spring:property name="configuration">
            <spring:value>my-config.xml</spring:value>
        </spring:property>
    </spring:bean>
----

== 合并配置文件

如果您有多个配置文件，则可以将它们导入到一个配置文件中，以便只需指定一个配置。例如：

[source,xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns=http://www.mulesoft.org/schema/mule/core ....>
  <spring:beans>
    <spring:import resource="mule-sub-config1.xml" />
    <spring:import resource="mule-sub-config2.xml" />
  </spring:beans>
...
----

== 另请参阅

*  link:/mule-user-guide/v/3.9/using-mule-with-spring[春天使用骡子]
* 了解Mule如何创建应用程序上下文。查看 link:/mule-user-guide/v/3.9/spring-application-contexts[Spring应用程序上下文]
