=  Anypoint MQ连接器
:keywords: mq, connector

https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[_Select_]

*Release Notes:* link:/release-notes/mq-connector-release-notes[Anypoint MQ连接器发行说明] +
*Reference:* link:/mule-user-guide/v/3.9/anypoint-mq-connector-reference[Anypoint MQ连接器参考] +
*Anypoint Exchange:* https://www.anypoint.mulesoft.com/exchange/org.mule.tooling.messaging/mule-module-anypoint-mq-ee-studio/[Anypoint MQ Connector]

Anypoint MQ连接器在Anypoint Studio中提供发布 - 订阅消息。 Anypoint MQ支持混合使用案例，从不同设备收集数据的IoT以及可用于设备应用程序的REST API。您还可以将Anypoint MQ与其他应用程序框架（如node.js）一起使用以与队列进行通信。

== 先决条件

要使用此连接器，您应该熟悉Anypoint Studio，Anypoint连接器和Mule流程。 Anypoint MQ连接器是免费的，但连接到Anypoint Platform中的服务需要许可证。

*Note:*如果没有Anypoint MQ许可证，您无法完成本文档中的配置信息。

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule Runtime  | 3.7.4及更高版本
| Anypoint Studio  | v5及更高版本
|===

== 安装此连接器

. 在Anypoint Studio中，点击Studio任务栏中的Exchange图标。
. 单击Anypoint Exchange中的登录并提供您的Anypoint Platform凭据。
. 在Exchange窗口中，搜索此连接器，然后单击安装。
. 按照提示安装连接器。

=== 从较旧版本更新

当发布连接器的更新版本时，Anypoint Studio会在Studio的右下角显示“更新可用”弹出窗口。点击弹出窗口并安装新版本。

== 使用Studio Visual Editor进行配置

. 在Studio中，单击文件>新建> Mule项目。
. 搜索"http"并将HTTP连接器拖到Studio画布上。单击HTTP连接器，然后单击连接器配置右侧的绿色加号。单击确定以接受默认设置。在HTTP属性窗口中，将路径设置为`/mq/{messageId}`。
. 搜索"mq"并将*Anypoint MQ*连接器拖到画布上。如果找不到此连接器，请返回
<<To Install This Connector>>并确保您安装了连接器。
. 单击连接器配置右侧的绿色加号。

全局元素属性窗口：

. 指定您希望MQ队列和交易所驻留的区域的URL。请参阅 link:/anypoint-mq/[MQ可用区域]。在此URL中替换区域名称：
+
`+https://REGION_NAME.anypoint.mulesoft.com/api/v1+`
+
. 在Anypoint Platform中，单击MQ>客户端应用程序。如果需要，创建一个客户端应用
. 将Anypoint平台> MQ>客户端应用程序>客户端应用程序ID值复制到Studio的客户端ID字段。
. 将客户端应用程序>客户端密钥值复制到Studio的客户端密钥字段。您可以忽略其他设置来测试连接器。
. 单击确定。

连接器属性：

. 单击“操作”字段并指定诸如“发布”或“使用”之类的操作。有关Ack和Nack操作的信息，请参阅 link:/anypoint-mq/mq-ack-mode[关于确认模式]。
. 如果使用发布或使用操作，请将*Destination*指定为您在Anypoint Platform中设置的队列或消息交换的名称。
. 对于发布操作，您可以将消息ID字段留空，或者如果要发布特定的消息标识，请指定消息标识。如果未设置消息标识，则MQ自动为发送到队列的每条消息生成唯一的消息标识。发布到FIFO队列时，如果指定了一个消息ID，并且消息ID在多个消息中相同，则具有相同消息ID的消息不会重新发送。

有关所有其他配置字段的列表，请参阅 link:/mule-user-guide/v/3.9/anypoint-mq-connector-reference[Anypoint MQ连接器参考]。

==  MQ模式和端点

如果您正在创建一个XML或独立应用程序，请将此依赖项添加到您的pom.xml文件中：

[source,xml,linenums]
----
<dependency>
  <groupId>org.mule.tooling.messaging</groupId>
  <artifactId>mule-module-anypoint-mq-ee-studio</artifactId>
  <version>1.2.0</version>
</dependency>
----

*Note:*如果您使用Anypoint Studio创建应用程序，那么当您安装MQ连接器时，将依赖于MQ
在pom.xml文件中为你更新。

Gradle，EBT和Ivy的其他依赖项在https://www.anypoint.mulesoft.com/exchange/org.mule.tooling.messaging/mule-module-anypoint-mq-ee-studio/中的Anypoint Exchange中列出。 [Anypoint MQ连接器]资产。单击依赖片段获取完整列表。

终点：

`+http://www.mulesoft.org/schema/mule/anypoint-mq+`

==  XML和独立配置

有关XML字段的列表，请参阅 link:/mule-user-guide/v/3.9/anypoint-mq-connector-reference[Anypoint MQ连接器参考]。

==  Anypoint MQ XML示例

本节提供了以下主题：

*  <<Example 1: MQ and DataWeave>>
*  <<Example 2: MQ and Object Store>>
*  <<About Common XML Elements>>

=== 示例1：MQ和DataWeave

以下示例说明了使用DataPoint的Anypoint MQ连接器进行转换
向JSON发送Mule消息：

[source,xml,linenums]
----
include::_sources/mq-studio.xml[]
----

=== 示例2：MQ和Object Store

以下示例显示了使用Anypoint MQ连接器进行使用
来自对象商店的信息。

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq"
    xmlns:objectstore="http://www.mulesoft.org/schema/mule/objectstore"
    xmlns:dw="http://www.mulesoft.org/schema/mule/ee/dw"
    xmlns:http="http://www.mulesoft.org/schema/mule/http"
    xmlns:tracking="http://www.mulesoft.org/schema/mule/ee/tracking"
    xmlns="http://www.mulesoft.org/schema/mule/core"
    xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:spring="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/objectstore http://www.mulesoft.org/schema/mule/objectstore/current/mule-objectstore.xsd
http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/dw http://www.mulesoft.org/schema/mule/ee/dw/current/dw.xsd
http://www.mulesoft.org/schema/mule/ee/tracking http://www.mulesoft.org/schema/mule/ee/tracking/current/mule-tracking-ee.xsd
http://www.mulesoft.org/schema/mule/anypoint-mq http://www.mulesoft.org/schema/mule/anypoint-mq/current/mule-anypoint-mq.xsd">

    <objectstore:config name="ObjectStore_Configuration" partition="employees" doc:name="ObjectStore: Configuration"/>
    <http:listener-config name="HTTP_Listener_Configuration" host="0.0.0.0" port="8081" doc:name="HTTP Listener Configuration"/>
    <anypoint-mq:config name="Anypoint_MQ_Configuration" doc:name="Anypoint MQ Configuration">
        <anypoint-mq:provider url="https://mq-us-east-1.anypoint.mulesoft.com/api/v1" clientId="<ID>" clientSecret="<SECRET>"/>
    </anypoint-mq:config>
    <flow name="objectstore-store-flow">
        <http:listener config-ref="HTTP_Listener_Configuration" path="/store" doc:name="HTTP"/>
        <objectstore:store config-ref="ObjectStore_Configuration" key="#[message.inboundProperties.'http.query.params'.key]" value-ref="#[message.inboundProperties.'http.query.params'.value]" doc:name="ObjectStore"/>
        <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration" destination="MyDemoQueue" doc:name="Anypoint MQ"/>
        <set-payload value= "OK" doc:name="Set Payload"/>
    </flow>
    <flow name="objectstore-retrieve-employee-flow">
        <http:listener config-ref="HTTP_Listener_Configuration" path="/retrieve" doc:name="HTTP"/>
        <objectstore:retrieve config-ref="ObjectStore_Configuration" key="#[message.inboundProperties.'http.query.params'.key]" doc:name="Retrieve"/>
        <logger message="Value: #[payload]" level="INFO" doc:name="Log"/>
        <set-payload value="Value : #[payload]" doc:name="Show"/>
    </flow>
</mule>
----

== 另请参阅

*  link:/mule-user-guide/v/3.9/anypoint-mq-connector-reference[Anypoint MQ连接器参考]
*  link:/anypoint-mq/[Anypoint MQ文档]
