= 将Mule配置为Windows服务
:keywords: anypoint, on premises, on premise, windows

[NOTE]
在Mule 3.8.0中，Tanuki包装器升级为新版本，意味着对包装器签名的证书进行了更改。有关解决兼容性问题的详细信息，请参阅 link:/release-notes/mule-3.8.0-release-notes#enterprise-edition-library-changes[关于Tanuki Wrapper升级的Mule 3.8.0发行说明]。

要将Mule安装为Windows服务，请键入：

[source]
----
mule install
----

要从服务器中删除Mule，请输入：

[source]
----
mule remove
----

将Mule作为服务安装后，您可以启动，停止并重新启动Mule：

[source]
----
mule [start|stop|restart]
----

*Note:*当Windows重新启动时，Mule服务停止与使用`mule stop`命令相同的方式。
唯一的情况是，如果Windows由于超时而终止进程，这可能会有所不同。

您也可以使用Windows `net`实用程序：

[source]
----
net [start|stop] mule
----

== 安装后将属性添加到wrapper.conf文件

将Mule作为Windows服务安装后定义的属性
在`wrapper.conf`文件中可以被`wrapper.additional.conf`文件中生成的属性覆盖。

有以下不同的行为：

*  <<Mule Community Edition Properties>>
*  <<Mule Enterprise Edition Properties>>

===  Mule社区版属性

在Mule CE：

. 添加新属性后，请重新安装或重新启动Windows服务。
. 添加属性并确保其索引大于`wrapper-additional.conf`文件中的最大索引。否则，您的财产可能会过度。
+
例如，如果wrapper-additional.conf具有以下属性：
+
`wrapper.java.additional.n=-Dproperty=value`
+
当n是最大索引时，应该在`wrapper.conf`文件中将您的属性添加到索引中：
+
`wrapper.java.additional.n+1=-DyourProperty=valueOfYourProperty`

===  Mule企业版属性

在Mule EE中：

. 默认情况下，您可以在安装Mule作为服务后添加20个额外的属性。
. 使用以下命令行参数配置您需要的额外属性的数量
当您安装服务时：
+
`-additionalJavaProperties=numberOfExtraProperties`
