=  DotNet连接器迁移指南
:keywords: dotnet connector, dotnet, dot net, microsoft, c#, c sharp, visual studio, visual basic

== 从.NET Connector版本1.0升级

由于技术限制，无法在单个Anypoint安装上并行运行使用.NET连接器版本1.x和版本2.x的应用程序。先前使用.NET连接器版本1.0应用程序托管应用程序的Anypoint Studio或Mule Server实例具有为1.0版连接器安装的支持文件。这些.NET支持文件必须通过下面解释的过程进行升级，然后.NET Connector版本2.0才能正常工作。

此外，如果使用.NET连接器版本1.x运行应用程序，则必须迁移所有应用程序以使用.NET Connector版本2.x，并配置承载这些应用程序的Anypoint安装以允许.NET Connector 2.x跑步。

为协助完成此迁移和升级过程，*{{0}}*工具可从MuleSoft网站下载。

=== 概述

该工具提供了以下功能：

*  确定Mule安装将支持哪个版本的.NET连接器

* 枚举在独立Mule实例上使用.NET连接器v1的所有已部署应用程序

* 升级指定Mule安装的.NET支持文件以允许.NET连接器版本2.0或更高版本运行

* 将一个或多个使用.NET连接器版本1.0的Mule应用程序迁移到2.0版（可以选择工作区根或项目目录，或者Mule Server运行时目录）

[WARNING]
====
除了针对Anypoint Studio实例运行迁移工具之外，还必须确保在Studio调板中看到.NET Connector可用之前安装了.NET connector 2.0插件。
====

=== 用法

*  *-analyze*命令标识是否必须升级Anypoint Studio或Mule服务器实例，以及是否有任何Mule应用程序使用.NET连接器版本1.0并且必须进行迁移。 +
`dotnet-connector-util -analyze c:\path\to\mule\or\studio\instance`

*  *-upgrade*命令删除.NET连接器1.0的支持文件，并配置Anypoint Studio或Mule Server实例来承载.NET连接器版本2.0支持文件。 +
`dotnet-connector-util -upgrade <path-to-mule-or-studio-installation>`

*  *-migrate*命令更新在指定的Mule服务器实例上运行的任何Mule应用程序（就地迁移）或指定工作空间目录中的Mule项目的全局元素配置，从而允许应用程序利用.NET连接器2.0。 +
`dotnet-connector-util -migrate <path-to-esb-server-or-workspace-or-app>`

=== 注意事项

将Anypoint Studio或Mule服务器实例配置为支持.NET连接器2.0后，将不再运行使用.NET连接器版本1.0的任何应用程序。当您尝试运行应用程序时，会显示如下所示的错误消息：

[source, code, linenums]
----
Can't initialize jni4net BridgeCan't load library:
C:\Tools\AnypointStudio\plugins\org.mule.tooling.server.3.5.2.ee_4.1.0.201410031231\mule\lib\user\dotnetconnector\1.1\jni4net.n.w64.v40-0.8.6.0.dll
ERROR 2015-01-05 16:25:23,613
[[dotnetdemo1].connector.http.mule.default.receiver.02]
org.mule.exception.DefaultMessagingExceptionStrategy:
********************************************************************************
Message               : Failed to invoke execute. Message payload is of type: String
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------
Exception stack is:
1. Can't  load library:
C:\Tools\AnypointStudio\plugins\ \mule\lib\user\dotnetconnector\1.1\jni4net.n.w64.v40-0.8.6.0.dll
 (java.lang.UnsatisfiedLinkError)
java.lang.ClassLoader:1854 (null)
 
2. Can't initialize jni4net Bridge (net.sf.jni4net.inj.INJException
net.sf.jni4net.CLRLoader:56 (null)
----

=== Errors when Running .NET Connector Version 2.0

If you see the following error when running an application that uses the .NET connector version 2.0, then the support files for the .NET connector 1.0 are still installed in the version of Anypoint Studio or Mule Server that you are running.

Follow the migration guidance in this document to overcome this issue:

[source, code, linenums]
----
java.lang.Exception: The Anypoint installation the application is running in is configured to allow the .NET Connector 1.x and this application references the .NET Connector 2.x. You must run the dotnet-version-selector utility to allow .NET Connector 2.x applications to run in this installation
 
at org.mule.modules.dotnet.jni.DotNetBridge.<clinit>(DotNetBridge.java:185)
at org.mule.modules.dotnet.DotNetConnector.<clinit>(DotNetConnector.java:80)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
----

