= 词汇
:keywords: glossary

以下词汇表有助于您理解MuleSoft术语。


Mule的许多术语与流行的 http://www.eaipatterns.com/[企业集成模式]书中的术语相同。这本书描述了Mule解决和记录Mule框架中使用的许多模式的问题。

== 甲

''''''
=== 代理

（另请参阅<<<Mule Agent>>和<<Runtime Manager Agent>>）一种服务，如Mule JMX代理，由Mule使用或与其关联，但不是Mule管理的服务组件。代理向<<Runtime Manager>>注册，并且与Mule实例具有相同的生命周期，因此您可以在Mule实例启动或停止时初始化和销毁​​资源。

===  Anypoint Exchange

完整的连接器，模板，示例和RAML API库。发现并使用由MuleSoft生态系统构建的经过验证的资产。或者，将资产添加到Anypoint Exchange的私人租户以便协作和共享内部最佳实践。有关更多信息，请参阅https://www.anypoint.mulesoft.com/exchange/[Anypoint Exchange]（站点）和 link:/anypoint-exchange/[Anypoint Exchange]文档。

===  Anypoint Studio

一个集成的开发环境，包含可视化和XML编辑器，用于设计，调试和测试Mule应用程序。使用可视化界面，您可以将连接器，记录器，决策项目，数据转换器等等拖放到设计画布上。浏览界面进行调试和测试。有关更多信息，请参阅 link:/anypoint-studio/v/6/[Anypoint Studio Essentials]或从https://mulesoft.com/platform/studio[Anypoint Studio]下载。

=== 任意平台

可以将MuleSoft提供的整套产品作为连贯性挑战的一致解决方案，也可以指https://anypoint.mulesoft.com [Anypoint Platform Portal]，其中有许多解决方案可用作Web应用程序。

===  Anypoint平台私有云版

已重命名为<<Anypoint Platform Private Cloud Edition>>。


===  Anypoint平台私有云版

Anypoint Platform的特殊包装可用于在您自己的本地服务器上运行。以前称为Anypoint Platform私有云版。通过使用它，您可以将整个基础架构保留在您自己的专用网络中。此实现在Docker和Kubernetes上运行，并且与Pivotal Cloud Foundry兼容。该包装包括 link:/runtime-manager[运行时管理器]， link:/api-manager[API管理器]和Exchange版本。


===  API设计器

用于设计，记录和测试API的基于Web的图形环境（请参阅 link:/getting-started/design-an-api[在API Designer中设计一个API]）

===  API管理器

Anypoint平台的一部分，允许您设计和管理您的API。它包含<<API Designer>>，它允许您为API编写一个<<RAML>>定义。它还包括监控使用情况指标的工具，应用<<policies>>并通过<<API Portal>>提供交互式文档

===  API门户

一个访问点，您可以在其中呈现设计的API以吸引用户。 link:/api-manager/tutorial-create-an-api-portal[API门户]

===  APIkit


一种声明式工具包，用于促进REST或SOAP API开发。它处理错误条件并设置状态码，并为RESTful调用或SOAP API请求生成流。有关更多信息，请参阅 link:/apikit/apikit-basic-anatomy[APIkit基本解剖学]。

=== 申请

任何通过Mule发送数据的程序。应用程序可以是Web应用程序，后台系统，应用程序服务器或其他Mule实例。

===  ARM

请参阅任意点xref：runtimemgr [运行时管理器]。


== 乙

''''''
=== 业务事件分析器

在Mule 3.2企业版中引入的业务事件分析器提供了可以查看Mule服务器上的业务事务和事件的功能。业务事件分析器功能可通过<<Management Console, management console's>>业务事件选项卡获取。


== ℃

''''''
=== 全面策略

用于"catch"任何未配置的路由器处理的消息的方法。如果没有找到当前消息的路由路径，则调用全部捕获策略。入站或出站端点可以与全方位策略相关联，以便可以将任何孤立消息路由到公共位置。

=== 链接路由器

一个出站路由器，可用于通过多个端点使用第一个调用的结果作为下一个输入的输入来发送消息。当您希望将同步请求 - 响应调用的结果（如Web服务调用）发送到JMS队列时，这非常有用。链路路由器向第一个端点发送同步消息并等待回复。该答复然后被路由到第二个端点。


=== 频道

在消息框架中发送消息的逻辑路径。通道连接服务以及本地网络或互联网上的不同Mule节点。 <<transport>>在特定频道上发送消息。

=== 连接器

一个独立的组件，允许您将Mule应用程序与其他外部应用程序（如SalesForce，CMIS和Twitter）的API集成。

[[cloudhub]]
===  CloudHub

集成平台即服务，可让您管理云中的应用程序。通过运行时管理器控制台将应用程序部署到云时，CloudHub将在后台使用。有关更多信息，请参阅 link:/runtime-manager/cloudhub[CloudHub]文档。

=== 簇

一组Mule实例，充当一个单元并可以作为一个单元进行管理。群集是由多个节点组成的虚拟服务器。您可以管理云中的 link:/runtime-manager/managing-servers#create-a-cluster[集群实例]。

=== 部件

POJO，Spring bean，Java bean或诸如Groovy，Ruby，Python或JavaScript的脚本，其中包含处理通过Mule传递的消息的业务逻辑。这些组件通常将整个消息 - 或仅仅是有效负载 - 作为输入。它们返回一个对象，该对象成为消息处理器链中下一个元素的消息负载。

组件可以执行以下操作之一：

 实现Callable接口
使用注释来表达组件方法被调用的方式。
 依靠Mule的运行时注入机制。
这些组件在构建于Spring之上的Mule容器中进行管理;这允许Spring用户利用Spring的DI，AOP，DAO等。

另请参阅：<<service component>>。

=== 配置生成器

知道如何解析给定配置文件的类。默认配置构建器是知道如何解析Mule XML配置文件的`org.mule.config.MuleXmlConfigurationBuilder`类。


=== 连接器

Mule <<transport>>的具体实例，其属性描述了如何使用该传输。连接器维护传输的配置和状态。所有使用具有相同传输的连接器的Mule <<endpoints>>都会继承连接器的属性。有关支持的连接器的信息，请参阅https://www.anypoint.mulesoft.com/exchange/?type=connector[Anypoint Exchange连接器]。



==  d

''''''

=== 的DataMapper

不赞成使用的组件，可通过简单的拖放界面将输入字段映射到输出字段。在最近的版本中，该功能由DataWeave执行。

===  DataSense

Anypoint Studio的一项功能，它使用消息元数据来促进应用程序设计。借助此功能，Anypoint Studio可主动获取数据类型和结构等信息，以规定如何在应用程序中准确映射或使用此数据。请参阅 link:/anypoint-studio/v/6/datasense[DataSense]。

===  DataWeave


DataWeave Language是一个简单而强大的工具，用于查询和转换Mule内部的数据。它可以通过拖拽一个属性到另一个属性来图形化地映射字段，就像您现在不赞成使用DataMapper一样，或者利用其强大的面向对象语言，这种语言专门用于快速编写变换，而不会影响可维护性。请参阅 link:/mule-user-guide/v/3.8/dataweave[DataWeave]。



== È

''''''
===  EE

请参阅Mule企业版（EE）。

=== 端点

用于接收或发送数据的通道。端点具有特定协议（如Jetty或JMS）以及一组用于配置过滤器，事务，转换等的元素。有两种类型的端点：入站或出站。入站端点接收数据并允许外部客户端调用流程。相反，出站端点用于将数据发布或发送到服务，应用程序或资源。端点在入站或出站路由器中配置。端点也可以全局定义，而不是在特定的路由器中定义。

=== 事件

指示流或事务内发生了某事的消息。事件映射到消息处理器和端点。

=== 交换模式

请参阅消息交换模式（MEP）。

=== 表达式

见骡子表达。


==  F到

''''''

=== 滤波器

服务编排中的构件块，用于确定将哪些消息路由到服务组件。您可以在入站路由器上设置过滤器，以过滤哪些服务组件可以接收的消息，或者您可以在出站路由器上设置过滤器，以指示在服务组件处理完消息后如何路由消息。另请参阅消息过滤器。


=== 流

一个简单但灵活的机制，使您可以通过Mule编排消息服务。与使用定义具有显式入站和出站阶段并允许有限灵活性的组件的服务相比，流程不定义任何内容并且是完全自由形式的。流程使您可以将任意数量的构建块定义为单个可重复的流程。


==  g ^

''''''

////
=== 网关

...


=== 网关运行时

...
////

== ħ

''''''

=== 混合部署

通过<<Runtime Manager>>的云控制台将Mule应用程序部署到运行<<Mule Runtime>>的本地服务器。这种模式是混合的，因为您的应用程序托管在本地，而管理它在云中。请参阅 link:/runtime-manager/deployment-strategies[部署策略]以更好地了解此部署方式和其他方式。

== 我

''''''

=== 入站路由器

服务编排中的构建块，用于确定服务组件如何接收消息。入站路由器包含一个指示消息来自何处的端点。


=== 拦截

服务编排中的构件块，用于拦截消息流到服务组件中。拦截器可用于触发或监视事件或中断消息流。

=== 接口

定义最终用户可访问的数据的API部分，并指定针对希望通过API提供的数据（GET，PUT等）的操作。
实质上，接口是暴露于世界的服务与需要暴露的内部资产之间的中介。接口指定包含或访问数据资源的资源。

== Ĵ

''''''

==  K和

''''''

==  L

''''''
////

=== 监听器

...



=== 负载均衡器

...

////

==  M

''''''



===  MEL

<<Mule Expression Language>>（MEL）。

===  MEP

<<message exchange pattern>>（MEP）。


=== 消息

可以在特定频道上的应用程序之间处理和发送的数据包。数据总是被包裹在一个消息中，然后由Mule传送。一条消息包含一个标题，其中包含有关消息的元数据（如发件人信息）以及包含实际数据的正文。

=== 消息分派器

连接器用于接收来自出站路由器的消息和路由指令并将消息发送到下一个服务组件的Java类。


=== 消息交换模式（MEP）

一个定义良好的交互模式，描述如何在Mule中处理消息请求以及对消息请求​​的潜在响应。

Mule支持各种消息类型，例如同步或请求响应，每种消息都有一个或多个相应的消息交换模式。

例如，在请求 - 响应消息传递风格中，交换模式可以是"in-out"。在这种模式中，流或服务组件接收来自入站端点的消息，处理或操作消息有效负载，并通过将消息有效负载递送到出站端点来完成。相比之下，单向消息传递风格的消息交换模式是"in-only"，这意味着在流或服务组件从入站端点接收消息后，它会将其置于SEDA队列中以供进一步处理。但是，没有返回响应最初的请求。

=== 消息过滤器

一个消息处理器，用于控制消息是否由过滤器处理。

=== 消息处理器

用于构建流程的基本构建块。消息处理器控制消息在流中的发送和接收方式。消息处理器可以按功能进行分类，例如执行某些逻辑的功能（<<service component>>），转换消息的功能（请参阅<<transformer>>）以及过滤消息的功能（请参阅<<filter>>）。

=== 消息接收器

<<connector>>用于读取传入数据的Java类，将其作为消息打包，并将其传递给服务组件的入站路由器。如果需要，消息接收器可以使用变压器来转换数据。

=== 骡

请参阅<<Mule Runtime>>。


===  Mule Agent

请参阅<<Runtime Manager Agent>>。

===  Mule社区版（CE）

Mule的开源版本免费提供。顾名思义，社区版是由社区开发，测试和维护的。


===  Mule企业版（EE）

骡子的企业版本，可用于30天的试用版下载。企业版包括MuleSoft的完整开发周期，测试，技术支持，维护版本和热修复以及管理和监控工具。如果您在关键任务环境中部署Mule，要确保始终拥有稳定，高质量的版本，并且需要用于管理和监控部署的其他工具，则应购买Mule企业版订阅。


=== 骡子的表情

Mule中的一个构造，它允许您从当前消息中提取信息或确定如何处理消息。表达式对路由器和过滤器非常有用，用于定义路由逻辑和过滤不需要的消息。 Mule表达式对于查询请求和响应有效载荷和头文件也很有用。


===  Mule表达式语言

轻量级的Mule特定表达式语言，您可以使用它来访问和评估Mule消息的有效内容，属性和变量中的数据。请参阅 link:/mule-user-guide/v/3.8/mule-expression-language-mel[骡子表达语言（MEL）]， link:/mule-user-guide/v/3.8/mule-expression-language-examples[Mule表达语言示例]和 link:/mule-user-guide/v/3.8/mule-expression-language-reference[Mule表达式语言参考]。

=== 骡子银河

（已过时）在Mule 1.x和Mule 2.x中，提供了Mule Service注册表功能。


===  Mule HQ

（已过时）在Mule企业版中，这是一种管理Mule部署以及SOA基础架构中的不同系统和服务的工具。 Mule HQ提供集成的日志，配置，服务器事件跟踪和分析。由管理控制台在Mule 2.2.2企业版中废弃。

===  Mule管理控制台

在Mule 2.2.2企业版中引入的管理控制台是一个监控和管理系统，提供有关企业中硬件，服务和应用程序的信息，包括CPU使用情况以及有关磁盘和网络设备的信息。管理控制台为您的基础架构中的所有资产（包括群集）提供远程管理，监控，修补和警报。您可以将YourKit分析器与管理控制台集成在一起，以提供更详细的信息级别，显示内存使用情况直至对象级别。管理控制台和YourKit分析器都包含在企业版的Mule中。

===  Mule经理

每个Mule服务器实例的主要组件。 Mule管理器管理Mule对象，包括连接器，端点和变压器。 Mule Manager构建这些对象并将它们提供给Mule模型中的服务组件。每个Mule实例都有一个Mule Manager和一个或多个Mule模型。

=== 骡讯息

通过一个或多个流通过应用程序的数据。 Mule消息由两个主要部分组成：

 邮件标题，其中包含有关邮件的元数据

 邮件有效内容，其中包含您的业务特定数据。

Mule消息嵌入在Mule消息对象中。一些Mule消息对象可能包含变量，附件和异常有效载荷。但是，由于附件和异常有效载荷不经常使用或操纵，因此本概览文档不包含有关它们的详细信息。请参阅 link:/mule-user-guide/v/3.8/mule-message-structure[Mule消息结构]。

===  Mule模型

承载服务组件并管理其运行时行为的服务容器。


===  Mule运行时间

MuleSoft Anypoint Platform的基于Java的集成运行时引擎，它使用分阶段事件驱动架构（SEDA）将消息排入队列，并在不同阶段处理它们。 Mule通常被称为Mule运行时或简称Mule。 Mule用于整合新旧系统和应用程序，并且按比例构建。


===  Mule服务注册表

面向服务的体系结构治理平台，允许您使用SOA治理，注册表和存储库功能（包括生命周期，依赖关系和工件管理）以及自动发现或服务和报告来控制您的基础架构。 Mule的企业版本包含一个服务部署存储库，可以在整个环境中轻松部署和迁移服务。


===  MMC

请参阅<<Mule Management Console>>。


==  L
''''''


== ö

''''''

=== 出站路由器

您在Mule配置文件中配置的Java类，用于确定服务组件如何分派消息。出站路由器可以包含一个端点以指示下一个消息应该放在哪里，或者如果没有配置端点，它会将完成的消息返回给发件人。


==  p

''''''

===  PCF

请参阅<<Pivotal Cloud Foundry>>。


===  Pivotal Cloud Foundry

云计算平台即服务（PaaS）由一家名为Pivotal的公司提供。 Anypoint平台与Pivotal Cloud Foundry集成，允许您将Mule应用程序部署到您自己的专用网络上动态创建的虚拟机。请参阅 link:/runtime-manager/deployment-strategies[部署策略]。


===  POJO

"plain old Java object,"的首字母缩略词POJO是一个简单的Java对象，而不是企业JavaBean。 Mule的一个优点是你的服务组件可以是简单的POJO，然后Mule将其作为服务包装并公开。

=== 政策

通过<<API Manager>>，您可以轻松地在您的API上应用运行时策略。这些执行通用操作，例如对请求进行速率限制或验证或API响应。 API Manager允许您通过UI启用一组预定义策略之一，或者创建您自己的自定义策略。请参阅 link:/api-manager/using-policies[关于政策]以获得更深入的了解。

==  Q

''''''
=== 队列

Mule用于在异步消息处理期间存储对象的结构。默认情况下，Mule将SEDA队列用于服务和VM传输。 SEDA队列还用于配置了排队异步处理策略的流。 SEDA队列使Mule能够将消息的接收者与处理消息的其他步骤分离。这些队列在Mule中启用异步处理，因为一旦接收者将消息放入SEDA队列中，它就可以立即返回并接受新的传入消息。另请参阅频道。


==   -  [R

''''''
===  RAML

RESTful API建模语言（RAML）提供了一种可用于定义API的规范语言。有关更多信息，请参阅http://raml.org/。

=== 可靠性模式

在Mule 3.2中引入的可靠性模式是一种设计，即使应用程序接收到来自非事务性传输（如HTTP）的消息，该应用程序也可为应用程序提供可靠的消息传递。可靠性模式将可靠的采集流程与应用程序逻辑流程结合起来。可靠的采集流程将可靠的消息从使用非事务性传输的入站端点传送到出站端点，出站端点可以是任何类型的事务端点，例如VM或JMS。应用程序逻辑流程将来自入站端点（使用事务传输）的消息传递给应用程序的业务逻辑。

=== 资源动作配对

在API中，这是定义最终用户可以访问的数据的API的接口部分，并且指定针对您希望通过API提供的数据的操作（GET，PUT等）。

=== 路由器

服务编排中的构建块，用于确定应用程序之间传输消息的位置和方式。

=== 运行时管理器

运行时管理器（也称为Anypoint Runtime Manager或"ARM"）是Anypoint Platform的主要功能之一。它是一个控制台，允许您部署和管理使用任何Mule运行时构建的应用程序，既可以向云中的服务器（目前由CloudHub处理）也可以在本地处理。您可以在Anypoint Platform中访问此控制台，也可以将其作为独立程序下载到本地服务器中运行。


=== 运行时管理器

运行时管理器代理是一个<<Agent>>，用于调节服务器上运行的<<Runtime Manager>>控制台和<<Mule Runtime>>实例之间的通信。请参阅 link:/runtime-manager/runtime-manager-agent[运行时管理器代理]。

=== 运行时管理器代理

RuntMule代理是Mule的一个插件扩展，它公开了Mule API。使用Mule代理，您可以通过调用来自外部系统的API来监控和控制您的Mule服务器，并且/或者让Mule将其自己的数据发布到外部系统。
该代理具有许多功能，例如控制应用程序，域和服务，列出和部署域和应用程序，以及发布Mule度量标准。
有关更多信息，请参阅 link:/runtime-manager/runtime-manager-agent[运行时管理器代理]文档。




== Š

''''''
===  SEDA

请参阅分步事件驱动体系结构（SEDA）。


=== 服务组件

包含用于以特定方式处理数据的业务逻辑的POJO，Spring bean，Java bean或Web服务。 Mule只管理服务组件，将其与配置设置捆绑在一起，并将其作为服务公开，并根据您在Mule配置文件中为服务指定的设置确保正确的信息传入和传出。在Mule的早期版本中，服务组件被称为通用消息对象，"UMO"仍然是当今Mule API中命名的一部分。


=== 服务编排

从消息源到其目的地的消息的协调。 Mule通过流执行服务编排。


=== 分阶段事件驱动架构（SEDA）

一个体系结构模型，其中应用程序包含由显式队列连接的事件驱动阶段网络。这种架构可以让服务有条件地加载，防止资源在需求超过服务容量时被过度使用。因此，SEDA提供了一种高效的基于事件的排队模型，可最大限度地提高性能和吞吐量。 SEDA是Mule中的默认处理模型。

== Ť

''''''
=== 交易

作为一个完整的单元必须成功或失败的消息交换 - 它不能保持在中间状态。 Mule支持JDBC事务，XA事务和JMS事务或消息确认。事务在端点上配置。

=== 变压器

服务编排中的构建块，用于将消息负载（数据）转换为不同类型的数据。所有这些转换也可以通过 link:/mule-user-guide/v/3.8/dataweave[DataWeave]执行。

=== 运输

在特定的消息传递协议（如FTP）上处理和传输消息的构造。几个连接器构建在传输上。

=== 运输提供商

请参阅<<transport>>。

==  U

''''''
=== 通用消息对象（UMO）

请参阅服务组件。


== 伏

''''''

////
=== 虚空领域

''''''

=== 虚拟私有云

...


===  VPC

...

////




==  W

''''''
=== 线路点击

将消息副本转发给另一个终端的路由器。它可以转发所有收到的消息的副本，也可以将其配置为使用过滤器，并仅发送这些消息的子集。此路由器不会阻止邮件传递到服务组件。

==  X

''''''
===  XA事务

一项交易，征集多个管理资源并提供有保证的可靠性。 Mule还支持非XA事务的多资源事务。这些交易没有保证的可靠性。

== ÿ

''''''

====  YAML

YAML是一种用于创建配置文件的流行语言，因为它易于阅读和编辑。几种Mule产品以这种格式公开文件。 YAML也是<<RAML>>的灵感来源。


== ž

''''''

