=  Hadoop HDFS连接器API参考

：最后更新标签!:
：文档信息：
：source-highlighter：coderay
：图标：字体

+++
Hadoop分布式文件系统（HDFS）连接器。
+++

*Additional Info*
[%header,width="50", cols=".<60%,^40%"]
|======================
| 需要Mule Enterprise许可证 |  是图标：star [] {nbsp}
| 需要权利 |  否图标：删除[] {nbsp}
|  Mule版本 |  3.6.0或更高版本
|======================


==  CONFIGS
---
===  Kerberos配置
`<hdfs:config-with-kerberos>`


`Connection Management`

+++
Kerberos身份验证配置。在这里，您可以配置"Kerberos Authentication"所需的属性，以建立与Hadoop分布式文件的连接
系统。
+++


==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
| 名称 |  Java类型 | 描述 | 默认值 | 必需
|姓名 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 此配置的名称。此名称可以稍后参考。 |  |  *x* {nbsp}
|  nameNodeUri  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要连接的文件系统的名称。它作为{FileSystem＃FS_DEFAULT_NAME_KEY}配置条目传递给HDFS客户端。它可以由configurationResources和configurationEntries中的值覆盖。+++  |    |  *x* {nbsp}
|  keytabPath  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++ <a href="https://web.mit.edu/kerberos/krb5-1.12/doc/basic/keytab_def.html"> keytab文件的路径{{3} }与用户名关联。它用于从中获取TGT
"Authorization server"。如果未提供，则会在本地kerberos缓存中查找与用户名关联的TGT。+++  |    |  {nbsp}
| 用户名 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++客户端进程的简单用户标识。它作为"hadoop.job.ugi"配置条目传递给HDFS客户端。它可以被configurationResources中的值覆盖
和配置条目。+++  |    |  {nbsp}
|  configurationResources  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++ A <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表{{ 4}}配置资源文件由HDFS客户端加载。在这里你可以提供额外的配置文件。 （例如core-site.xml）+++  |    |  {nbsp}
| 配置条目 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">地图</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++ A <a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">地图{ 4}}将由HDFS客户端使用。在这里，您可以提供其他配置条目作为键/值对。+++  |    |  {nbsp}
|======================
---
=== 简单配置
`<hdfs:config>`


`Connection Management`

+++
简单的认证配置。在这里，您可以配置"Simple Authentication"所需的属性，以建立与Hadoop分布式文件系统的连接。
+++


==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
| 名称 |  Java类型 | 描述 | 默认值 | 必需
|姓名 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 此配置的名称。此名称可以稍后参考。 |  |  *x* {nbsp}
|  nameNodeUri  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要连接的文件系统的名称。它作为{FileSystem＃FS_DEFAULT_NAME_KEY}配置条目传递给HDFS客户端。它可以由configurationResources和configurationEntries中的值覆盖。+++  |    |  *x* {nbsp}
| 用户名 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++客户端进程的简单用户标识。它作为"hadoop.job.ugi"配置条目传递给HDFS客户端。它可以被configurationResources中的值覆盖
和配置条目。+++  |    |  {nbsp}
|  configurationResources  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++ A <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表{{ 4}}配置资源文件由HDFS客户端加载。在这里你可以提供额外的配置文件。 （例如core-site.xml）+++  |    |  {nbsp}
| 配置条目 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">地图</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++ A <a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">地图{ 4}}将由HDFS客户端使用。在这里，您可以提供其他配置条目作为键/值对。+++  |    |  {nbsp}
|======================



== 处理器

---

=== 从路径中读取
`<hdfs:read-operation>`




+++
读取由其路径指定的文件的内容并将其流式传输到流的其余部分：
+++

====  XML示例
[source,xml]
----
<!-- Reading a file using with an operation rather than pooling with an endpoint -->
<hdfs:read-operation path="/tmp/test.dat" bufferSize="8192" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要读取的文件路径+++  |   {{6 }} *x* {} NBSP




|
bufferSize   |  +++ int +++  |  +++读取文件时使用的缓冲区大小+++  |  4096  |  {nbsp}


|======================

==== 返回
[%header,cols=".^40%,.^60%"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html"> InputStream </a> +++  |  +++执行剩余流程的结果+++
|======================




---

=== 获取路径元数据
`<hdfs:get-metadata>`




+++
获取路径的元数据，如HDFSConnector＃read（String，int，SourceCallback）中所述，并将其存储在流变量中。
<p>
这个流量变量是：
<ul>
<li> hdfs.path.exists  - 表示路径是否存在（true或false）</li>
<li> hdfs.content.summary  - 路径信息</li>的简历
<li> hdfs.file.checksum  - 文件的MD5摘要（如果它是一个文件并存在）</li>
<li> hdfs.file.status  - 包含有关文件状态信息的Hadoop对象（org.apache.hadoop.fs.FileStatus </li>
</ul>
+++

====  XML示例
[source,xml]
----
<!-- Store the meta-information of a path in flow variables -->
<hdfs:get-metadata path="/tmp/test.dat" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++必须检查其存在的路径+++  |   {{6 }} *x* {} NBSP




|======================





---

=== 写入路径
`<hdfs:write>`




+++
将当前的有效负载写入指定的路径，创建一个新文件或附加到现有的文件。
+++




==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要写入的文件路径+++  |   {{ 6}} *x* {} NBSP




|
权限  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++创建新文件时使用的文件系统权限，可以是八进制格式或符号格式（的umask）。+++  |  {700 {5}} {} NBSP




|
覆盖  |  +++布尔型+++  |  +++如果预先存在的文件应该被新内容覆盖。+++  |  true  |  {nbsp}




|
bufferSize   |  +++ int +++  |  +++附加到文件时使用的缓冲区大小。+++  |  4096  |  {nbsp}




|
复制  |  +++ int +++  |  +++阻止文件复制。+++  |  1  |  {nbsp}




|
blockSize   |  +++ long +++  |  +++附加到文件时使用的缓冲区大小。+++  |  1048576  |  {nbsp}




|
ownerUserName   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++文件的用户名所有者+++  |   {{5} } {} NBSP




|
ownerGroupName   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++文件的组所有者+++  |   {{5} } {} NBSP




|
有效载荷图标：envelope []  |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html">InputStream</a>+++ | +++the payload to write to the file.+++ | #[有效载荷]  |  {nbsp}


|======================





---

=== 追加到文件
`<hdfs:append>`




+++
将当前有效负载附加到位于指定路径的文件。 <b>注意：</b>默认情况下，Hadoop服务器禁用了附加选项。为了能够追加任何
数据到现有文件参考dfs.support.append配置参数
+++




==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要写入的文件路径+++  |   {{ 6}} *x* {} NBSP




|
bufferSize   |  +++ int +++  |  +++附加到文件时使用的缓冲区大小。+++  |  4096  |  {nbsp}




|
有效载荷图标：envelope []  |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html">InputStream</a>+++ | +++the payload to append to the file.+++ | #[有效载荷]  |  {nbsp}


|======================





---

=== 删除文件
`<hdfs:delete-file>`




+++
删除位于指定路径的文件或目录。
+++

====  XML示例
[source,xml]
----
<!-- Delete a file -->
<hdfs:delete-file path="/tmp/test.dat" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要删除的文件路径+++  |   {{6 }} *x* {} NBSP


|======================





---

=== 删除目录
`<hdfs:delete-directory>`




+++
删除位于指定路径的文件或目录。
+++

====  XML示例
[source,xml]
----
<!-- Delete a directory -->
<hdfs:delete-directory path="/tmp/my-dir" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要删除的目录路径+++  |   {{6 }} *x* {} NBSP


|======================





---

=== 制作目录
`<hdfs:make-directories>`




+++
使给定的文件和所有不存在的父母进入目录。具有Unix'mkdir -p'的语义。目录层次结构的存在不是错误。
+++




==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++创建。+++  |   {{6} } *x* {} NBSP




|
权限  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++创建目录时使用的文件系统权限，无论是八进制格式还是符号格式（umask ）。+++  |   |  {} NBSP


|======================





---

=== 重命名
`<hdfs:rename>`




+++
将路径目标重命名为路径目标。
+++

====  XML示例
[source,xml]
----
<!-- Rename any source directory or file to the provided target path -->
<hdfs:rename source="/tmp/my-dir" target="/tmp/new-dir" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
源  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要重命名的源路径+++  |   {{6} } *x* {} NBSP




|
目标  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++重命名后的目标新路径+++  |   {{6} } *x* {} NBSP


|======================

==== 返回
[%header,cols=".^40%,.^60%"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">布尔</a> +++  |  +++布尔如果重命名成功则返回true +++
|======================




---

=== 列出状态
`<hdfs:list-status>`




+++
如果路径是目录，则列出给定路径中文件/目录的状态
+++

====  XML示例
[source,xml]
----
<!-- List the statuses of the given path -->
<hdfs:list-status path="/tmp/my-dir" filter="^.*/2014/02/$" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++给定路径+++  |   |  *x* { NBSP}




|
过滤器  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++用户提供的路径过滤器+++  |   |  {nbsp}


|======================

==== 返回
[%header,cols=".^40%,.^60%"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <FileStatus> +++  |  +++ FileStatus给定路径中文件/目录的状态+++
|======================




---

=== 全局状态
`<hdfs:glob-status>`




+++
返回所有符合文件模式的文件，而不是校验和文件。结果按其名称排序。
+++

====  XML示例
[source,xml]
----
<!-- Return all the files that match file pattern, sorted by their names -->
<hdfs:glob-status pathPattern="/tmp/*/*" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
pathPattern   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++指定路径模式的正则表达式+++  |   {{6 }} *x* {} NBSP




|
过滤器  |  +++ PathFilter +++  |  +++用户提供的路径过滤器+++  |   |  {nbsp}


|======================

==== 返回
[%header,cols=".^40%,.^60%"]
|======================
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <FileStatus> +++  |  +++ FileStatus与路径模式匹配的路径数组++++
|======================




---

=== 从本地文件复制
`<hdfs:copy-from-local-file>`




+++
将本地磁盘上的源文件复制到给定目标路径上的FileSystem，如果应删除源，请设置deleteSource。
+++

====  XML示例
[source,xml]
----
<!-- Copy from source local disk to the target FileSystem -->
<hdfs:copy-from-local-file deleteSource="true" overwrite="false" source="/tmp/mulesoft/" target="/user/mulesoft/" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
deleteSource   |  +++布尔型+++  |  +++是否要删除源代码+++  |  false  |  {nbsp}




|
覆盖  |  +++布尔型+++  |  +++是否覆盖现有文件。+++  |  true  |  {nbsp}




|
源  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++本地磁盘上的源路径+++  |   {{6 }} *x* {} NBSP




|
目标  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++文件系统上的目标路径+++  |   {{6 }} *x* {} NBSP


|======================





---

=== 复制到本地文件
`<hdfs:copy-to-local-file>`




+++
将FileSystem上的源文件复制到给定目标路径上的本地磁盘上，如果应删除该源，则设置deleteSource。 useRawLocalFileSystem表示是否
使用RawLocalFileSystem，因为它是非CRC文件系统。
+++

====  XML示例
[source,xml]
----
<!-- Copy to source local disk from the target FileSystem -->
<hdfs:copy-to-local-file deleteSource="false" useRawLocalFileSystem="false" source="/tmp/mulesoft/" target="/user/mulesoft/" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
deleteSource   |  +++布尔型+++  |  +++是否要删除源代码+++  |  false  |  {nbsp}




|
useRawLocalFileSystem   |  +++布尔型+++  |  +++是否将RawLocalFileSystem用作本地文件系统+++  |  false  |  {nbsp}




|
源  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++文件系统上的源路径+++  |   {{6 }} *x* {} NBSP




|
目标  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++本地磁盘上的目标路径+++  |   {{6 }} *x* {} NBSP


|======================





---

=== 设置权限
`<hdfs:set-permission>`




+++
设置路径权限（即文件或目录）。
+++

====  XML示例
[source,xml]
----
<!-- Set permission of a path to change. -->
<hdfs:set-permission path="/tmp/my-dir" permission="511" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++文件或目录的路径设置权限。+++  |   |  *x* {} NBSP




|
权限  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++需要设置的文件系统权限+++  |   {{6 }} *x* {} NBSP


|======================





---

=== 设置所有者
`<hdfs:set-owner>`




+++
设置路径的所有者（即文件或目录）。参数username和groupname不能都为null。
+++

====  XML示例
[source,xml]
----
<!-- Set owner of a path to change. -->
<hdfs:set-owner path="/tmp/my-dir" ownername="mulesoft" groupname="supergroup" config-ref="hdfs-conf"/>
----



==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



|
路径  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++文件或目录的路径来设置所有者。+++  |   |  *x* {} NBSP




|
ownername   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++如果它为null，则原始用户名保持不变。+++  |   |  {} NBSP




|
groupname   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++如果它为null，则原始组名保持不变。+++  |   |  {} NBSP


|======================








== 来源

---

=== 从路径中读取
`<hdfs:read>`




+++
读取由其路径指定的文件的内容并将其流式传输到其余流，同时在以下入站属性中添加路径元数据：
<ul>
<li> HDFSConnector＃HDFS_PATH_EXISTS：如果路径存在，则设置为true的布尔值</li>
<li> HDFSConnector＃HDFS_CONTENT_SUMMARY：如果路径存在，则为ContentSummary的一个实例。</li>
<li> HDFSConnector＃HDFS_FILE_STATUS：如果路径存在，则为FileStatus的一个实例。</li>
<li> HDFSConnector＃HDFS_FILE_CHECKSUM：FileChecksum的一个实例，如果路径存在，是一个文件并且具有校验和。</li>
</ul>
+++




==== 属性
[%header,cols=".^20%,.^20%,.^35%,.^20%,^.^5%"]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP
| 路径 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要读取的文件路径+++ {{6 }} |  *x* {} NBSP
|  bufferSize  |  +++ int +++  |  +++读取文件时使用的缓冲区大小+++  |  4096  |  {nbsp}
|  sourceCallback  |  +++ SourceCallback +++  |  +++用于将事件传播到其余流的SourceCallback +++  |   |  *x* {} NBSP
|======================

==== 返回
[%header,cols=".^40%,.^60%"]
|======================
|返回Java类型 | 描述
| +++ +++空隙 |  ++++++
|======================
