=  MEL DataWeave函数
:keywords: mel, cheat, sheet

link:/mule-user-guide/v/3.9/mule-expression-language-mel[骡子表达语言（MEL）]包含两个函数，它们利用强大的 link:/mule-user-guide/v/3.9/dataweave[DataWeave]转换语言，非常适合执行复杂的数据转换。

Mule中支持Mule表达式语言的所有组件也支持用DataWeave Language编写的表达式。

[TIP]
通过为您的流添加*Transform Message Component*，DataWeave语言最容易使用，因为它提供了一个图形用户界面，可通过拖放界面构建自动映射，以及丰富的调试功能。有关更多详情，请参阅 link:/anypoint-studio/v/6/transform-message-component-concept-studio[关于变换消息组件]。

== 先决条件

本文假定您熟悉 link:/mule-user-guide/v/3.9/mule-expression-language-reference[骡子表达语言]和 link:/mule-user-guide/v/3.9/dataweave-language-introduction[DataWeave语言]。

==  DW函数

要调用以DataWeave语言编写的表达式，只需调用`dw()`函数，表达式将返回任何转换输出。

在这个函数中定义的DataWeave表达式就像在Transform Message元素中定义的那样工作，唯一的区别是输出返回到表达式的结果中，无论它在哪里。

[NOTE]
您在此函数中编写的DataWeave表达式必须包含在"quotation marks"中

例如，您可以定义一个自定义对象并使用有效载荷中的元素填充它：

[source,code]
----
dw("myobject:{id:payload.accountid, user:payload.user}")
----

可以在MEL表达式内的Logger中添加相同的表达式，以打印出其结果：

[source,code]
----
#[dw("myobject:{id:payload.accountid, user:payload.user}")]
----




该功能的完整属性参考：

[%header,cols="30a,70a"]
|===
| {属性{1}}说明
| DataWeave表达式 |实际执行的DataWeave表达式
|输出类型	| 变换输出的类型
|阅读器属性	| 对于CSV等输入，有时需要某些属性才能知道如何解析输入，请参阅 link:/anypoint-studio/v/6/input-output-structure-transformation-studio-task[定义变换的输入输出结构]
|编写器属性	| 对于CSV等输入，有时需要某些属性来编写输出，请参阅 link:/anypoint-studio/v/6/input-output-structure-transformation-studio-task[定义变换的输入输出结构]

|===

[NOTE]
只有版本 link:/release-notes/mule-3.8.2-release-notes[Mule Runtime 3.8.2发行说明]和更新版本支持阅读器和写入器属性。

以下是使用所有属性的更详细的示例：

[source,code]
----
#[dw(payload.script,'application/xml', ['payload': ['nullValueOn':'empty']], ['output': ['indent':'true']])]
----

在上面的例子中，第一个属性是一个简单的DW表达式，引用了有效载荷中的一个元素，第二个属性告诉DataWeave将其输出为“application / xml”，第三个属性包含一个带读取器属性的地图，第四个包含一个地图编写器属性。

reader和writer属性的映射应该遵循以下结构：

* 第一个键定义配置的目标，此键的值是另一个映射
* 在此映射中，列出要配置的功能的键值对

[source,code]
----
['output': ['indent':'true']]
----

[TIP]
请参阅 link:/mule-user-guide/v/3.9/dataweave-formats[DataWeave格式]，以获取可为读者和作者设置的所有不同属性的参考。可用选项取决于格式。

== 分割函数

`split()`函数运行用DataWeave语言编写的表达式，并返回一个迭代器，其结果可以一次由您的流处理一个索引处理。它至少需要两个参数：一个DataWeave表达式和所需的输出类型。这个函数可能相当于运行'dw（）'函数，然后向流中添加额外的步骤，例如 link:/mule-user-guide/v/3.9/foreach[Foreach范围]，但是它对资源的重要性不高。

[NOTE]
您在此函数中编写的DataWeave表达式必须包含在"quotation marks"中（单引号`'`或双引号`"`。split函数的结果还必须返回单个数组。

下面是您可以编写的最基本的DW表达式，但只要它返回可迭代列表，您也可以放入任何其他DW表达式。

[source,code]
----
split('payload','application/json')
----

可以在*Collection*字段的 link:/mule-user-guide/v/3.9/foreach[Foreach范围]中添加相同的表达式，以便使用此表达式将有效内容分析为单独处理的一组单独消息（一次一个）：

[source,xml,linenums]
----
<flow name="myFlow">
    <foreach collection="split('payload','application/json')" doc:name="For Each">
        <logger message="#[payload]" level="INFO" doc:name="Logger"/>
    </foreach>
</flow>
----




该函数具有以下属性：

[%header,cols="30a,70a"]
|===
| {属性{1}}说明
| DataWeave表达式 |实际执行的DataWeave表达式
|输出类型	| 变换输出的类型
|阅读器属性	| 对于CSV等输入，有时需要某些属性才能知道如何解析输入，请参阅 link:/anypoint-studio/v/6/input-output-structure-transformation-studio-task[定义变换的输入输出结构]
|编写器属性	| 对于CSV等输入，有时需要某些属性来编写输出，请参阅 link:/mule-user-guide/v/3.9/dataweave-language-introduction#output-directive[输出指令]
|===


== 另请参阅

*  link:/mule-user-guide/v/3.9/mule-expression-language-reference[Mule表达式语言参考]
*  link:/mule-user-guide/v/3.9/dataweave-language-introduction[DataWeave语言介绍]
