=  NetSuite连接器API参考


NetSuite连接器同步数据并自动化NetSuite和第三方应用程序之间的业务流程，无论是内部部署还是云中。
Connector使用SuiteTalk WSDL提供基于SOAP的集成，以便生成NetSuite业务对象，利用不同的身份验证级别并支持错误处理。


*Additional Info*
[width="50", cols=".<60%,^40%" ]
|======================
| 需要Mule企业许可证 |  是的
| 需要权利 |  否
|  Mule版本 |  3.5.0或更高版本
|======================


==  CONFIGS
---
=== 登录验证
`<netsuite:config-login-authentication>`


`Connection Management`



==== 属性
[%header%autowidth.spread]
|======================
| 名称 |  Java类型 | 描述 | 默认值 | 必需
|名称 | 字符串 | 此配置的名称。有了这个名称可以稍后参考。 |  |  *x*
| 电子邮件 | 字符串 |  NetSuite用户界面和SuiteTalk的登录电子邮件 |    |  *x*
| 密码 | 字符串 |  NetSuite用户界面和SuiteTalk  |    |  *x*的登录密码
| 帐户 | 字符串 |  NetSuite SuiteTalk Web服务帐户ID  |    |  *x*
|  roleId  | 字符串 | 用于在SuiteTalk中登录的角色ID，它确定处理器权限 |    |  *x*
|  applicationId  | 字符串 | 与要使用的集成记录相关的标识。集成记录在NetSuite环境中设置。 |    |  *x*
|  connectionTimeout  |  Long  | 指定客户端在超时前尝试建立连接的时间量（以毫秒为单位）。 0指定客户端将继续尝试无限打开连接。 |    | 
|  receiveTimeout  | 长 | 指定客户端在超时之前等待响应的时间量（以毫秒为单位）。 0指定客户端将无限期地等待。 |    | 
|  proxyHost  | 字符串 |  HTTP代理的主机名，例如localhost此字段还要求设置端口。 |    | 
|  proxyPort  | 整数 |  HTTP代理的端口号，例如3128.如果还指定了主机名，则必须指定端口号。 |    {{4} }
|  proxyUsername  | 字符串 | 每次向NetSuite发送请求时应提供给HTTP代理的用户名。此字段是可选的，因为用户可能想要通过未经身份验证的HTTP
代理。 |    | 
|  proxyPassword  | 字符串 | 每次向NetSuite发送请求时将提供给HTTP代理的密码。此字段是可选的，因为用户可能想要通过未经身份验证的HTTP
代理。 |    | 
| 端点 | 字符串 | 服务端点 |   https://webservices.na1.netsuite.com/services/NetSuitePort_2015_2  | 
|  {隔板{1}}字符串 | 
分隔符用于生成为自定义字段/记录提供更好支持所需的键。


如果定义自定义字段/记录的自定义的脚本ID包含分隔符默认字符，请设置一个新字符并重新生成元数据。
  |   __  | 
|======================
---
=== 请求级别身份验证
`<netsuite:config-request-level-authentication>`


`Connection Management`



==== 属性
[%header%autowidth.spread]
|======================
| 名称 |  Java类型 | 描述 | 默认值 | 必需
|名称 | 字符串 | 此配置的名称。有了这个名称可以稍后参考。 |  |  *x*
| 电子邮件 | 字符串 |  NetSuite用户界面和SuiteTalk的登录电子邮件 |    |  *x*
| 密码 | 字符串 |  NetSuite用户界面和SuiteTalk  |    |  *x*的登录密码
| 帐户 | 字符串 |  NetSuite SuiteTalk Web服务帐户ID  |    |  *x*
|  roleId  | 字符串 | 用于在SuiteTalk中登录的角色ID，它确定处理器权限 |    |  *x*
|  applicationId  | 字符串 | 与要使用的集成记录相关的标识。集成记录在NetSuite环境中设置。 |    |  *x*
|  connectionTimeout  |  Long  | 指定客户端在超时前尝试建立连接的时间量（以毫秒为单位）。 0指定客户端将继续尝试无限打开连接。 |    | 
|  receiveTimeout  | 长 | 指定客户端在超时之前等待响应的时间量（以毫秒为单位）。 0指定客户端将无限期地等待。 |    | 
|  proxyHost  | 字符串 |  HTTP代理的主机名，例如localhost此字段还要求设置端口。 |    | 
|  proxyPort  | 整数 |  HTTP代理的端口号，例如3128.如果还指定了主机名，则必须指定端口号。 |    {{4} }
|  proxyUsername  | 字符串 | 每次向NetSuite发送请求时应提供给HTTP代理的用户名。此字段是可选的，因为用户可能想要通过未经身份验证的HTTP
代理。 |    | 
|  proxyPassword  | 字符串 | 每次向NetSuite发送请求时将提供给HTTP代理的密码。此字段是可选的，因为用户可能想要通过未经身份验证的HTTP
代理。 |    | 
| 端点 | 字符串 | 服务端点 |   https://webservices.na1.netsuite.com/services/NetSuitePort_2015_2  | 
|  {隔板{1}}字符串 | 
分隔符用于生成为自定义字段/记录提供更好支持所需的键。


如果定义自定义字段/记录的自定义的脚本ID包含分隔符默认字符，请设置一个新字符并重新生成元数据。
  |   __  | 
|======================
---
=== 基于请求级别令牌的身份验证
`<netsuite:config-request-level-token-based-authentication>`


`Connection Management`



==== 属性
[%header%autowidth.spread]
|======================
| 名称 |  Java类型 | 描述 | 默认值 | 必需
|名称 | 字符串 | 此配置的名称。有了这个名称可以稍后参考。 |  |  *x*
|  consumerKey  | 字符串 | 使用基于令牌的认证集成记录的消费者键值 |    |  *x*
|  consumerSecret  | 字符串 | 使用基于令牌的验证集成记录的消费者秘密值 |    |  *x*
|  tokenId  | 字符串 | 表示在NetSuite环境 |    |  *x*中生成的用户和集成的唯一组合的标记ID
|  tokenSecret  | 字符串 | 用户/集成对 |    |  *x*的相应令牌机密
| 帐户 | 字符串 |  NetSuite SuiteTalk Web服务帐户ID。 |    |  *x*
|  connectionTimeout  |  Long  | 指定客户端在超时前尝试建立连接的时间量（以毫秒为单位）。 0指定客户端将继续尝试无限打开连接。 |    | 
|  receiveTimeout  | 长 | 指定客户端在超时之前等待响应的时间量（以毫秒为单位）。 0指定客户端将无限期地等待。 |    | 
|  signatureAlgorithm  |  SignatureAlgorithm  | 用于计算SHA哈希签名的算法 |   HMAC_SHA_1  | 
|  proxyHost  | 字符串 |  HTTP代理的主机名，例如localhost此字段还要求设置端口。 |    | 
|  proxyPort  | 整数 |  HTTP代理的端口号，例如3128.如果还指定了主机名，则必须指定端口号。 |    {{4} }
|  proxyUsername  | 字符串 | 每次向NetSuite发送请求时应提供给HTTP代理的用户名。此字段是可选的，因为用户可能想要通过未经身份验证的HTTP
代理。 |    | 
|  proxyPassword  | 字符串 | 每次向NetSuite发送请求时将提供给HTTP代理的密码。此字段是可选的，因为用户可能想要通过未经身份验证的HTTP
代理。 |    | 
| 端点 | 字符串 | 服务端点 |   https://webservices.na1.netsuite.com/services/NetSuitePort_2015_2  | 
|  {隔板{1}}字符串 | 
分隔符用于生成为自定义字段/记录提供更好支持所需的键。

如果定义自定义字段/记录的自定义的脚本ID包含分隔符默认字符，请设置一个新字符并重新生成元数据。
  |   __  | 
|======================
---
===  SSO登录验证
`<netsuite:config-sso-login-authentication>`


`Connection Management`



==== 属性
[%header%autowidth.spread]
|======================
| 名称 |  Java类型 | 描述 | 默认值 | 必需
|名称 | 字符串 | 此配置的名称。有了这个名称可以稍后参考。 |  |  *x*
|  partnerId  | 字符串 |  partnerId在启用SSO  |    |  *x*时与NetSuite达成一致
|  partnerAccount  | 字符串 |  NetSuite SuiteTalk Web服务帐户ID  |    |  *x*
|  companyId  | 字符串 | 公司在设置SSO映射时使用 |    |  *x*
|  userId  | 字符串 | 设置SSO映射时使用的userId  |    |  *x*
|  keyFile  | 字符串 | 用于将companyId和userId加密为认证令牌的私钥文件 |    |  *x*
|  applicationId  | 字符串 | 与要使用的集成记录相关的标识。集成记录在NetSuite环境中设置。 |    |  *x*
|  connectionTimeout  |  Long  | 指定客户端在超时前尝试建立连接的时间量（以毫秒为单位）。 0指定客户端将继续尝试无限打开连接。 |    | 
|  receiveTimeout  | 长 | 指定客户端在超时之前等待响应的时间量（以毫秒为单位）。 0指定客户端将无限期地等待。 |    | 
|  proxyHost  | 字符串 |  HTTP代理的主机名，例如localhost此字段还要求设置端口。 |    | 
|  proxyPort  | 整数 |  HTTP代理的端口号，例如3128.如果还指定了主机名，则必须指定端口号。 |    {{4} }
|  proxyUsername  | 字符串 | 每次向NetSuite发送请求时应提供给HTTP代理的用户名。此字段是可选的，因为用户可能想要通过未经身份验证的HTTP
代理。 |    | 
|  proxyPassword  | 字符串 | 每次向NetSuite发送请求时将提供给HTTP代理的密码。此字段是可选的，因为用户可能想要通过未经身份验证的HTTP
代理。 |    | 
| 端点 | 字符串 | 服务端点 |   https://webservices.na1.netsuite.com/services/NetSuitePort_2015_2  | 
|  {隔板{1}}字符串 | 
分隔符用于生成为自定义字段/记录提供更好支持所需的键。


如果定义自定义字段/记录的自定义的脚本ID包含分隔符默认字符，请设置一个新字符并重新生成元数据。
  |   __  | 
|======================



== 处理器

---

=== 附加记录
`<netsuite:attach-record>`






将来源或联系人记录（即附件）附加到另一个目的地记录


并非所有记录类型都支持作为来源，目的地或联系人。请咨询NetSuite文档。



====  XML示例
[source,xml]
----
<netsuite:attach-record config-ref="Netsuite">
    <netsuite:source internalId="#[flowVars.sourceId]" type="#[flowVars.sourceRecordType]"/>
    <netsuite:destination internalId="#[flowVars.destinationId]" type="#[flowVars.destinationRecordType]"/>
</netsuite:attach-record>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
源图标：envelope []  |  RecordRef  |  RecordRef的实例 | ＃[有效负载]  | 




|
目的地  |  RecordRef  |  RecordRef的一个实例 |   |  *x*




|
请联系  |  RecordRef  |  RecordRef的一个实例 |   | 




|
角色  |  RecordRef  |  RecordRef的一个实例 |   | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| WriteResponse  |  WriteResponse的一个实例
|======================




---

=== 删除记录
`<netsuite:delete-record>`






删除记录。并非所有记录都可以删​​除。请咨询NetSuite文档



====  XML示例
[source,xml]
----
<netsuite:delete config-ref="Netsuite">
	<netsuite:base-ref type="RECORD_REF" internalId="#[flowVars.id]">
		<netsuite:specific-fields>
			<netsuite:specific-field key="type"
				value-ref="#[flowVars.recordType]" />
		</netsuite:specific-fields>
	</netsuite:base-ref>
</netsuite:delete>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordRef icon：envelope []  |  RecordRef  |  RecordRef的一个实例 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| WriteResponse  | 操作的结果
|======================




---

=== 删除
`<netsuite:delete>`






删除记录。并非所有记录都可以删​​除。请咨询NetSuite文档



====  XML示例
[source,xml]
----
<netsuite:delete config-ref="Netsuite">
    <netsuite:base-ref type="RECORD_REF" internalId="#[flowVars.internalId]">
        <netsuite:specific-fields>
            <netsuite:specific-field key="type" value-ref="#[flowVars.recordType]"/>
        </netsuite:specific-fields>
    </netsuite:base-ref>
</netsuite:delete>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
baseRef图标：envelope []  |  BaseRefType  |  BaseRefType的实例 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| WriteResponse  |  WriteResponse的一个实例
|======================




---

=== 分离记录
`<netsuite:detach-record>`






从目标记录中分离源记录 - 即附件 - 。



====  XML示例
[source,xml]
----
<netsuite:detach-record config-ref="Netsuite">
    <netsuite:source internalId="#[flowVars.sourceId]" type="#[flowVars.sourceRecordType]"/>
    <netsuite:destination internalId="#[flowVars.destinationId]" type="#[flowVars.destinationRecordType]"/>
</netsuite:detach-record>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
源图标：envelope []  |  RecordRef  |  RecordRef的实例 | ＃[有效负载]  | 




|
目的地  |  RecordRef  |  RecordRef的一个实例 |   |  *x*




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| WriteResponse  |  DetachResponse对象
|======================




---

=== 获取预算汇率
`<netsuite:get-budget-exchange-rates>`






返回给定期间的预算汇率列表。






==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
period icon：envelope []  |  RecordRef  | 引用现有时段。 | ＃[有效载荷]  | 




|
fromSubsidiary   |  RecordRef  | 引用接收子公司 |   | 




|
toSubsidiary   |  RecordRef  | 引用原始子公司 |   | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetBudgetExchangeRateResult  |  GetBudgetExchangeRateResult的一个实例
|======================




---

=== 获得统一的汇率
`<netsuite:get-consolidated-exchange-rates>`






返回给定期间的综合汇率列表。



====  XML示例
[source,xml]
----
<netsuite:get-consolidated-exchange-rates config-ref="Netsuite">
    <netsuite:period externalId="106"/>
    <netsuite:from-subsidiary internalId="5689"/>
    <netsuite:to-subsidiary internalId="4898"/>
</netsuite:get-consolidated-exchange-rates>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
period icon：envelope []  |  RecordRef  | 引用现有时段。 | ＃[有效载荷]  | 




|
fromSubsidiary   |  RecordRef  | 引用接收子公司 |   | 




|
toSubsidiary   |  RecordRef  | 引用原始子公司 |   | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetConsolidatedExchangeRateResult  |  GetConsolidatedExchangeRateResult的一个实例
|======================




---

=== 获取自定义ID
`<netsuite:get-customization-ids>`






返回给定自定义类型的可用自定义ID。



====  XML示例
[source,xml]
----
<netsuite:get-customization-ids config-ref="Netsuite" type="#[flowVars.type]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
键入  |  GetCustomizationType  | 目标记录类型。 |   |  *x*




|
includeInactives   | 布尔值 | 如果还需要返回不活动的自定义设置。 |  false  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetCustomizationIdResult  |  CustomizationRef的列表
|======================




---

=== 获取已删除的记录
`<netsuite:get-deleted-records>`






返回给定记录类型和日期时间段的已删除记录列表。



====  XML示例
[source,xml]
----
<netsuite:get-deleted-records config-ref="Netsuite" type="EMPLOYEE">
    <netsuite:deleted-date operator="ON" searchValue="#[flowVars.todaysDate]"/>
</netsuite:get-deleted-records>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  link:http://docs.oracle.com/javase/7/docs/api/java/lang/String.html[串]  | 指定要使用的配置 |  | *x*



|
键入  |  http://mulesoft.github.io/mule-netsuite-connector/7.4.1/apidocs/javadocs/org/mule/module/netsuite/api/RecordTypeEnum.html[RecordTypeEnum]  | 要检索的目标已删除记录的类型 |   |  *x*




|
pageIndex   |  link:http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html[整数]  | 要检索的页码 |  1  | 




|
deletedDate icon：envelope []  |  SearchDateField  | 一个coreSearchDateField，您可以在其中定义预定义搜索日期值或所选日期以及搜索日期操作符。 | ＃ [有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetDeletedResult  | 与给定日期过滤表达式匹配的DeletedRecord列表
|======================




---

=== 获取记录
`<netsuite:get-records>`






该操作用于检索指定类型的所有记录的列表。


GetAllRecordType中列出了支持getAll操作的记录



====  XML示例
[source,xml]
----
<netsuite:get-records config-ref="Netsuite" type="#[flowVars.type]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  link:http://docs.oracle.com/javase/7/docs/api/java/lang/String.html[串]  | 指定要使用的配置 |  | *x*



|
键入  |  GetAllRecordType  | 目标记录类型 |   |  *x*




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetAllResult  | 记录列表
|======================




---

=== 获取列表
`<netsuite:get-list>`






此操作用于检索BaseRef对象列表中引用的对象列表。



====  XML示例
[source,xml]
----
<netsuite:get-list config-ref="Netsuite">
    <netsuite:references ref="#[flowVars.list]"/>
</netsuite:get-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  link:http://docs.oracle.com/javase/7/docs/api/java/lang/String.html[串]  | 指定要使用的配置 |  | *x*



|
引用图标：信封[]  |  link:http://docs.oracle.com/javase/7/docs/api/java/util/List.html[名单]  |  BaseRef子类的列表。检查BaseRef以获取子类的列表。 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| link:http://docs.oracle.com/javase/7/docs/api/java/util/List.html[名单] <ReadResponse>  | 记录的列表
|======================




---

=== 获取
`<netsuite:get>`






这用于通过提供标识该记录的唯一标识来检索记录。



====  XML示例
[source,xml]
----
<netsuite:get config-ref="Netsuite">
    <netsuite:base-ref type="RECORD_REF" internalId="#[flowVars.internalId]">
        <netsuite:specific-fields>
            <netsuite:specific-field key="type" value-ref="#[flowVars.recordType]"/>
        </netsuite:specific-fields>
    </netsuite:base-ref>
</netsuite:get>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
baseRef图标：envelope []  | http://mulesoft.github.io/mule-netsuite-connector/7.4.1/apidocs/javadocs/org/mule/module/netsuite/api/BaseRefType.html[BaseRefType]  |  BaseRefType  | 的一个实例＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|地图<String,Object>  | 表示您要检索的记录的地图。
|======================




---

=== 获取记录
`<netsuite:get-record>`



图标：云[]启用DataSense



这用于通过提供标识该记录的唯一标识来检索记录。



====  XML示例
[source,xml]
----
<netsuite:get-record config-ref="Netsuite" internalId="#[flowVars.internalId]" type="EMPLOYEE" />
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
键入图标：key []  | 字符串 | 要获取的记录类型。 |   |  *x*




|
internalId图标：envelope []  | 字符串 | 要获取的记录的internalId。您可以选择this或externalId。 | ＃[有效负载]  | 




|
externalId   | 字符串 | 要获取的记录的externalId。您可以选择this或internalId。 |   | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|地图<String,Object>  | 表示记录的地图。
|======================




---

=== 获取自定义记录
`<netsuite:get-custom-record>`



图标：云[]启用DataSense



这用于通过提供标识该记录的唯一标识来检索自定义记录。



====  XML示例
[source,xml]
----
<netsuite:get-custom-record config-ref="Netsuite" internalId="#[flowVars.internalId]" type="__customRecordType__myCustomRecord__123" />
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
键入图标：key []  | 字符串 | 要获取的记录类型。 |   |  *x*




|
internalId图标：envelope []  |字符串 | 要获取的记录的internalId。您可以选择this或externalId。 | ＃[有效负载]  | 




|
externalId   | 字符串 | 要获取的记录的externalId。您可以选择this或internalId。 |   | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|地图<String,Object>  | 表示记录的地图。
|======================




---

=== 获取物品可用性
`<netsuite:get-item-availability>`






返回给定项目记录参考的可用性。


如果启用了多地点清单功能，则此处理器将返回所有地点的结果。


对于没有可用项目的地点，结果中只会列出地点ID和姓名。



====  XML示例
[source,xml]
----
<netsuite:get-item-availability config-ref="Netsuite">
    <netsuite:record internalId="#[flowVars.internalId]" type="#[flowVars.recordType]"/>
</netsuite:get-item-availability>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
记录图标：envelope []  |  RecordRef  |  RecordRef的一个实例 | ＃[有效载荷]  | 




|
ifModifiedSince   | 日期 | 可选修改后的日期。如果设置，则仅返回截止指定日期记录的具有数量可用更改的项目。 |   | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetItemAvailabilityResult  |  GetItemAvailabilityResult的一个实例
|======================




---

=== 获取保存的搜索
`<netsuite:get-saved-search>`






检索给定记录类型的现有保存搜索列表。



====  XML示例
[source,xml]
----
<netsuite:get-saved-search config-ref="Netsuite" type="#[flowVars.recordType]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
搜索目标记录类型 |   |  *x*


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetSavedSearchResult  | 与可用保存的搜索对应的RecordRefs列表
|======================




---

=== 获取服务器时间
`<netsuite:get-server-time>`






返回服务器时间。



====  XML示例
[source,xml]
----
<netsuite:get-server-time config-ref="Netsuite"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*

|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|日期 | 服务器时间，作为日期
|======================




---

=== 更新被邀请者状态
`<netsuite:update-invitee-status>`






为给定事件设置新的邀请状态。



====  XML示例
[source,xml]
----
<netsuite:update-invitee-status config-ref="Netsuite" status="#[flowVars.status]">
    <netsuite:event-id internalId="#[flowVars.internalId]" type="#[flowVars.type]"/>
</netsuite:update-invitee-status>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |字符串 | 指定要使用的配置 |  | *x*



|
eventId图标：envelope []  |  RecordRef  | 目标事件ID  | ＃[有效负载]  | 




|
状态  |  CalendarEventAttendeeResponseEnum  | 设置 |   |  *x*的新状态




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| WriteResponse  |  WriteResponse的一个实例
|======================




---

=== 更新被邀请者状态列表
`<netsuite:update-invitee-status-list>`






为给定的事件设置多个新的邀请状态。



====  XML示例
[source,xml]
----
<netsuite:update-invitee-status-list config-ref="Netsuite">
    <netsuite:invitee-status-list ref="#[flowVars.list]"/>
</netsuite:update-invitee-status-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
inviteeStatusList图标：信封[]  | 列表<UpdateInviteeStatusReference>  |  UpdateInviteeStatusReference项目的列表。 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|列表<WriteResponse>  |  WriteResponse的一个实例
|======================




---

=== 添加记录对象
`<netsuite:add-record-objects>`






创建新记录。



====  XML示例
[source,xml]
----
<netsuite:add-record-objects config-ref="Netsuite">
    <netsuite:records ref="#[flowVars.records]"/>
</netsuite:add-record-objects>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
records icon：envelope []  | 列出 | 记录对象列表 | ＃[有效载荷]  | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|列表<WriteResponse>  |  WriteResponse列表
|======================




---

=== 添加记录
`<netsuite:add-record>`



图标：云[]启用DataSense



创建一个新的记录。


这些属性可以是与该字段相对应的pojos，也可以是表示该字段的映射。



====  XML示例
[source,xml]
----
<netsuite:add-record config-ref="Netsuite" recordType="#[flowVars.recordType]">
	<netsuite:attributes ref="#[flowVars.attributes]" />
</netsuite:add-record>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordType icon：key []  | 字符串 | 要添加的记录类型 |   |  *x*




|
属性图标：envelope []  | 映射<String,Object>  | 记录属性，作为字符串对象映射 | ＃[payload]  | 




|
偏好设定  | 偏好设定 | 请求的偏好设定 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| BaseRef  |  RecordRef或CustomRecordRef的一个实例，取决于类型
|======================




---

=== 添加列表
`<netsuite:add-list>`



图标：云[]启用DataSense



用于将一个或多个记录添加到系统中。


定义每个记录的属性可以是对应于该字段的POJO，也可以是表示它的映射。



====  XML示例
[source,xml]
----
<netsuite:add-list config-ref="Netsuite" recordType="#[flowVars.recordType]">
	<netsuite:records ref="#[flowVars.records]" />
</netsuite:add-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordType icon：key []  | 字符串 | 要添加的记录类型 |   |  *x*




|
记录图标：信封[]  | 列表<Map<String,Object>>  | 记录及其属性，作为字符串对象映射 | ＃[有效负载]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|列出<WriteResponse>  |  WriteResponse的列表
|======================




---

=== 更新列表
`<netsuite:update-list>`



图标：云[]启用DataSense



用于通过为每条记录更新字段提供新值来更新系统中的一个或多个现有记录。


要更新的记录通过提供的唯一标识符进行标识。



====  XML示例
[source,xml]
----
<netsuite:update-list config-ref="Netsuite" recordType="#[flowVars.recordType]">
    <netsuite:records ref="#[flowVars.records]"/>
</netsuite:update-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordType icon：key []  | 字符串 | 要添加的记录类型 |   |  *x*




|
记录图标：信封[]  | 列表<Map<String,Object>>  | 记录及其属性，作为字符串对象映射 | ＃[有效负载]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|列出<WriteResponse>  |  WriteResponse的列表
|======================




---

=== 更新记录列表
`<netsuite:update-records-list>`






用于通过提供记录列表来更新系统中的一个或多个现有记录。要更新的记录通过提供的唯一标识符进行标识。


注意：此调用不能与数据映射或数据传感一起使用，它被添加以允许用户在1次调用中添加任何类型的一批记录。



====  XML示例
[source,xml]
----
<netsuite:update-records-list config-ref="Netsuite">
    <netsuite:records ref="#[flowVars.recordRefList]"/>
</netsuite:update-records-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
records icon：envelope []  | 列表 | 记录及其属性。 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|列出<WriteResponse>  |  WriteResponse的列表
|======================




---

=== 删除列表
`<netsuite:delete-list>`






用于删除系统中的一个或多个记录。



====  XML示例
[source,xml]
----
<netsuite:delete-list config-ref="Netsuite">
	<netsuite:records ref="#[flowVars.records]" />
</netsuite:delete-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
记录图标：信封[]  | 列表<BaseRefType>  | 带有属性的记录，作为字符串对象映射 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|列表<WriteResponse>  | 已删除记录的记录参考列表
|======================




---

=== 删除记录列表
`<netsuite:delete-records-list>`






用于删除系统中的一个或多个记录。



====  XML示例
[source,xml]
----
<netsuite:delete-records-list config-ref="Netsuite">
  	<netsuite:records ref="#[flowVars.recordRefList]"/>
</netsuite:delete-records-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
records icon：envelope []  |  List <RecordRef>  | 要删除的RecordRef列表 | ＃[payload]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|列表<WriteResponse>  | 已删除记录的记录参考列表
|======================




---

=== 添加文件
`<netsuite:add-file>`






创建一个新的文件记录。


此处理器与addRecord类似，但是为简化本地内容传递而定制。



====  XML示例
[source,xml]
----
<netsuite:add-file config-ref="Netsuite" content-ref="#[flowVars.contentRef]" fileName="#[flowVars.fileName]">
	<netsuite:folder-id internalId="#[flowVars.folderId]" />
</netsuite:add-file>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
folderId图标：envelope []  |  RecordRef  | 文件夹记录的ID在其中添加此文件 | ＃[有效负载]  | 




|
属性  | 地图<String,Object>  | 附加文件属性 |   | 




|
内容  | 对象 | 要添加的文件记录的内容。它可以是String类型，字节数组，File或InputStream类型。如果它是输入流，则此处理器也会关闭它。 |   |  *x*




|
fileName   | 字符串 | 远程文件的名称 |   |  *x*




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| RecordRef  | 新记录的RecordRef
|======================




---

=== 更新记录
`<netsuite:update-record>`



图标：云[]启用DataSense



更新现有记录。


属性可以是对应于该字段的POJO或表示它的映射。



====  XML示例
[source,xml]
----
<netsuite:update-record config-ref="Netsuite" recordType="#[flowVars.recordType]">
	<netsuite:attributes ref="#[flowVars.attributes]" />
</netsuite:update-record>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordType icon：key []  | 字符串 | 要更新的目标记录类型 |   |  *x*




|
属性图标：envelope []  | 映射<String,Object>  | 记录属性，作为字符串对象映射，包括internalId或externalId属性。 | ＃[payload] {{ 4}}




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| BaseRef  |  RecordRef或CustomRecordRef的一个实例，取决于类型
|======================




---

===  Upsert记录
`<netsuite:upsert-record>`



图标：云[]启用DataSense



upsert操作用于添加新实例或更新NetSuite中的记录实例。


upsert操作与add和update操作类似，但可以在不首先确定NetSuite中是否存在记录的情况下运行upsert。记录是
由其外部ID和记录类型标识。如果系统中存在具有匹配的外部标识的指定类型的记录，则会进行更新。如果它不存在，a
新记录被创建。


由于此操作必须使用外部标识，因此只有支持外部标识字段的记录才支持upsert。


另外，该操作禁止传递内部ID值。



====  XML示例
[source,xml]
----
<netsuite:upsert-record config-ref="Netsuite" recordType="#[flowVars.recordType]">
	<netsuite:attributes ref="#[flowVars.attributes]" />
</netsuite:upsert-record>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordType icon：key []  | 字符串 | 要更新的目标记录类型 |   |  *x*




|
属性图标：envelope []  | 映射<String,Object>  | 记录属性，作为字符串对象映射 | ＃[payload]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| BaseRef  |  RecordRef或CustomRecordRef的一个实例，取决于类型
|======================




---

===  Upsert列表
`<netsuite:upsert-list>`



图标：云[]启用DataSense



upsertList操作用于在NetSuite中添加或更新记录类型的一个或多个实例。


upsertList操作与addList和updateList操作类似，但可以在不首先确定NetSuite中是否存在记录的情况下运行upsert。记录
由他们的外部ID和他们的记录类型来标识。如果系统中存在具有匹配的外部标识的指定类型的记录，则会进行更新。如果没有
存在，则创建新的记录。


由于此操作必须使用外部标识，因此只有支持外部标识字段的记录才支持upsertList。


另外，该操作禁止传递内部ID值。



====  XML示例
[source,xml]
----
<netsuite:upsert-list config-ref="Netsuite" recordType="#[flowVars.recordType]">
    <netsuite:records ref="#[flowVars.records]"/>
</netsuite:upsert-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordType icon：key []  | 字符串 | 要更新的目标记录类型 |   |  *x*




|
记录图标：信封[]  | 列表<Map<String,Object>>  | 记录属性，作为字符串对象映射 | ＃[有效负载]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|列表<WriteResponse>  | 带有对插入记录的引用的列表
|======================




---

=== 检查异步状态
`<netsuite:check-async-status>`






该操作检查特定异步作业是否已完成处理。



====  XML示例
[source,xml]
----
<netsuite:check-async-status config-ref="Netsuite" jobId="#[flowVars.jobId]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
jobId图标：信封[]  | 字符串 | 要检查的作业的ID。 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  | 给定作业的AsyncStatusResult
|======================




---

=== 异步搜索
`<netsuite:async-search>`



图标：云[]启用DataSense



等价于#search（String，SearchRecord，boolean，boolean，Integer）的异步请求


异步搜索与给定标准匹配的所有记录。请注意，由于操作的性质，这不支持只有第一个分页的分页
结果页面将被返回。


如果没有指定标准，则检索给定类型的所有记录。


在异步请求中，客户端应用程序向SuiteTalk平台发送一个请求，将其放置在处理队列中，并与其他处理队列异步处理
要求。请注意，每个投票期的所有可用作业都将连续处理。没有可用的工作的强制等待期。一旦工作完成
在Web服务响应中返回作业ID。您的客户端应用程序可以通过引用作业ID来检查请求的状态和结果。



====  XML示例
[source,xml]
----
<netsuite:async-search config-ref="Netsuite" searchRecord="#[flowVars.searchRecord]" criteria-ref="#[flowVars.criteriaRef]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
searchRecord icon：key []  | 字符串 | 搜索类型 -  SearchRecordTypeEnum  |   |  *x*




|
criteria icon：envelope []  |  SearchRecord  | 一个SearchRecord的实例，它定义组成搜索的属性。 | ＃[payload]  | 




|
bodyFieldsOnly   | 布尔值 | 默认为TRUE并指示记录的主体字段中的信息被返回 - 显着提高性能。关联列表或子列表中的任何字段都不会被返回。如果bodyFieldsOnly字段设置为FALSE，则返回与该记录相关联的所有字段。 |  true  | 




|
returnSearchColumns   | 布尔值 | 默认为TRUE，这意味着只有搜索列会在您的搜索中返回。 |  true  | 




|
pageSize   | 整数 | 每页最大结果数量 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  | 带有jobId的AsyncStatusResult，可用于检查作业的状态和结果。
|======================




---

=== 获取异步结果
`<netsuite:get-async-result>`






该操作返回已完成处理的作业结果。



====  XML示例
[source,xml]
----
<netsuite:get-async-result config-ref="Netsuite" jobId="#[flowVars.jobId]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
jobId图标：信封[]  | 字符串 | 作业的ID  | ＃[有效载荷]  | 




|
pageIndex   | 整数 | 异步结果 | 的页码1  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncResult  | 可找到记录的迭代
|======================




---

=== 初始化
`<netsuite:initialize>`






以相似的方式使用相关记录中的值填充交易行项目上的字段，空白文本框预填充到NetSuite UI中。



====  XML示例
[source,xml]
----
<netsuite:initialize config-ref="Netsuite">
    <netsuite:record type="#[flowVars.transactionRef]">
        <netsuite:reference type="#[flowVars.initializeRef]" internalId="#[flowVars.internalId]"/>
    </netsuite:record>
</netsuite:initialize>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
记录图标：envelope []  |  InitializeRecord  |  InitializeRecord的一个实例 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| ReadResponse  | 初始化的记录
|======================




---

=== 获取发布交易摘要
`<netsuite:get-posting-transaction-summary>`






用于检索帐户中实际数据的摘要。

<p/>

getPostingTransactionSummary操作允许您检索发布到帐户中总帐的实际数据的摘要。您可以使用可用
过滤器/字段来生成与您在运行财务报告时看到的报告类似的报告，例如试算表，资产负债表或损益表。



====  XML示例
[source,xml]
----
<netsuite:get-posting-transaction-summary config-ref="Netsuite">
    <netsuite:fields account="true" book="true" clazz="true" department="true" entity="true" item="true"
    	location="true" parentItem="true" period="true" subsidiary="true"/>
	    <netsuite:filters>
	        <netsuite:account ref="#[flowVars.accountRef]"/>
	    </netsuite:filters>
</netsuite:get-posting-transaction-summary>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
字段图标：信封[]  |  PostingTransactionSummaryField  | 指定您希望如何分组数据。 | ＃[有效载荷]  | 




|
过滤器  |  PostingTransactionSummaryFilter  | 指定您的过滤标准。 |   |  *x*




|
pageIndex   | 整数 | 指定要返回的页面。 |  1  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetPostingTransactionSummaryResult  | 包含指定字段的RecirdRef列表的GetPostingTransactionSummaryResult实例
|======================




---

=== 获取选择值
`<netsuite:get-select-value>`






用于检索给定recordRef字段的有效值，其中所引用的记录类型尚未在Web服务API中公开，或者登录角色没有
有权访问记录类型的实例。



====  XML示例
[source,xml]
----
<netsuite:get-select-value config-ref="Netsuite" page="#[flowVars.page]">
    <netsuite:field-descriptor field="#[flowVars.field]" recordType="#[flowVars.recordType]" sublist="#[flowVars.sublist]"/>
</netsuite:get-select-value>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
页面  |  int  | 对于跨越多个页面的选择值，使用此参数指定您的响应中要返回哪个页面。 |   |  *x*




|
fieldDescriptor icon：envelope []  |  GetSelectValueFieldDescription  | 用于指定包含选择值的字段的所有特征。例如，根据字段和要返回的值，您将为记录类型，子列表和字段指定名称或internalIds。您也可以指定筛选条件来优化响应中返回的选择选项。 | ＃[有效负载]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetSelectValueResult  | 与请求相关的GetSelectValueResult。
|======================




---

=== 获取当前费率
`<netsuite:get-current-rate>`






使用此操作获取两种货币之间的汇率。



====  XML示例
[source,xml]
----
<netsuite:get-current-rate config-ref="Netsuite">
    <netsuite:rate-filter>
        <netsuite:base-currency ref="#[flowVars.baseCurrencyRef]"/>
        <netsuite:from-currency ref="#[flowVars.fromCurrencyRef]"/>
    </netsuite:rate-filter>
</netsuite:get-current-rate>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
rateFilter icon：envelope []  |  CurrencyRateFilter  | 使用此过滤器过滤返回的货币汇率。 | ＃[有效负载]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetCurrencyRateResult  | 汇率。
|======================




---

=== 异步添加列表
`<netsuite:async-add-list>`



图标：云[]启用DataSense



一个等效于#addList的异步请求。


属性可以是对应于该字段的POJO或表示它的映射。


在异步请求中，客户端应用程序向SuiteTalk平台发送一个请求，将其放置在处理队列中，并与其他处理队列异步处理
要求。请注意，每个投票期的所有可用作业都将连续处理。没有可用的工作的强制等待期。一旦工作完成
在Web服务响应中返回作业ID。您的客户端应用程序可以通过引用作业ID来检查请求的状态和结果。


注意：异步请求JobIDs有效期为30天。



====  XML示例
[source,xml]
----
<netsuite:async-add-list config-ref="Netsuite" recordType="#[flowVars.recordType]">
    <netsuite:records-attributes ref="#[flowVars.records]"/>
</netsuite:async-add-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordType icon：key []  | 字符串 | 目标记录类型。 |   |  *x*




|
recordsAttributes icon：envelope []  | 列表<Map<String,Object>>  | 包含要添加的记录的属性的地图<String,Object>的列表。 | ＃有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  | 带有jobId的AsyncStatusResult，可用于检查作业的状态和结果。
|======================




---

=== 异步更新列表
`<netsuite:async-update-list>`



图标：云[]启用DataSense



与#updateList（String，List，Preferences）等效的异步请求。


在异步请求中，客户端应用程序向SuiteTalk平台发送一个请求，将其放置在处理队列中，并与其他处理队列异步处理
要求。请注意，每个投票期的所有可用作业都将连续处理。没有可用的工作的强制等待期。一旦工作完成
在Web服务响应中返回作业ID。您的客户端应用程序可以通过引用作业ID来检查请求的状态和结果。


注意：异步请求JobIDs有效期为30天。



====  XML示例
[source,xml]
----
<netsuite:async-update-list config-ref="Netsuite" recordType="#[flowVars.recordType]">
    <netsuite:records-attributes ref="#[flowVars.updatedRecords]"/>
</netsuite:async-update-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordType icon：key []  | 字符串 | 目标记录类型。 |   |  *x*




|
recordsAttributes图标：信封[]  | 列表<Map<String,Object>>  | 包含要更新记录的属性的地图<String,Object>的列表。 | ＃有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  | 带有jobId的结果AsyncStatusResult，可用于检查状态和结果。
|======================




---

=== 异步上传列表
`<netsuite:async-upsert-list>`



图标：云[]启用DataSense



与#upsertList（String，List，Preferences）等效的异步请求。


在异步请求中，客户端应用程序向SuiteTalk平台发送一个请求，将其放置在处理队列中，并与其他处理队列异步处理
要求。请注意，每个投票期的所有可用作业都将连续处理。没有可用的工作的强制等待期。一旦工作完成
在Web服务响应中返回作业ID。您的客户端应用程序可以通过引用作业ID来检查请求的状态和结果。


注意：异步请求JobIDs有效期为30天。



====  XML示例
[source,xml]
----
<netsuite:async-upsert-list config-ref="Netsuite" recordType="#[flowVars.recordType]">
    <netsuite:records-attributes ref="#[flowVars.records]"/>
</netsuite:async-upsert-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
recordType icon：key []  | 字符串 | 目标记录类型。 |   |  *x*




|
recordsAttributes icon：envelope []  | 列表<Map<String,Object>>  | 包含要插入或更新记录的属性的地图<String,Object>的列表。 |  ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  | 带有jobId的AsyncStatusResult，可用于检查作业的状态和结果。
|======================




---

=== 异步删除列表记录
`<netsuite:async-delete-list-records>`






与#deleteRecordsList（List，Preferences）等效的异步请求。


在异步请求中，客户端应用程序向SuiteTalk平台发送一个请求，将其放置在处理队列中，并与其他处理队列异步处理
要求。请注意，每个投票期的所有可用作业都将连续处理。没有可用的工作的强制等待期。一旦工作完成
在Web服务响应中返回作业ID。您的客户端应用程序可以通过引用作业ID来检查请求的状态和结果。


注意：异步请求JobIDs有效期为30天。



====  XML示例
[source,xml]
----
<netsuite:async-delete-list-records config-ref="Netsuite">
    <netsuite:records ref="#[flowVars.records]"/>
</netsuite:async-delete-list-records>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
records icon：envelope []  | 列表<RecordRef>  | 引用要删除的对象的RecordRef列表。 | ＃[payload]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  | 带有jobId的AsyncStatusResult，可用于检查作业的状态和结果。
|======================




---

=== 异步删除列表
`<netsuite:async-delete-list>`






与#deleteList（List，Preferences）等效的异步请求。


在异步请求中，客户端应用程序向SuiteTalk平台发送一个请求，将其放置在处理队列中，并与其他处理队列异步处理
要求。请注意，每个投票期的所有可用作业都将连续处理。没有可用的工作的强制等待期。一旦工作完成
在Web服务响应中返回作业ID。您的客户端应用程序可以通过引用作业ID来检查请求的状态和结果。


注意：异步请求JobIDs有效期为30天。



====  XML示例
[source,xml]
----
<netsuite:async-delete-list config-ref="Netsuite">
    <netsuite:records ref="#[flowVars.records]"/>
</netsuite:async-delete-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
records icon：envelope []  | 列表<BaseRefType>  | 引用要删除的对象的BaseRefType的列表。 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  | 带有jobId的AsyncStatusResult，可用于检查作业的状态和结果。
|======================




---

=== 异步获取列表记录
`<netsuite:async-get-list-records>`






与#getList（List，Preferences）等效的异步请求。


在异步请求中，客户端应用程序向SuiteTalk平台发送一个请求，将其放置在处理队列中，并与其他处理队列异步处理
要求。请注意，每个投票期的所有可用作业都将连续处理。没有可用的工作的强制等待期。一旦工作完成
在Web服务响应中返回作业ID。您的客户端应用程序可以通过引用作业ID来检查请求的状态和结果。


注意：异步请求JobIDs有效期为30天。



====  XML示例
[source,xml]
----
<netsuite:async-get-list-records config-ref="Netsuite">
    <netsuite:records ref="#[flowVars.records]"/>
</netsuite:async-get-list-records>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
记录图标：信封[]  | 列表<RecordRef>  | 引用要检索的对象的RecordRef列表。 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  | 带有jobId的AsyncStatusResult，可用于检查作业的状态和结果。
|======================




---

=== 异步获取列表
`<netsuite:async-get-list>`






与#getList（List，Preferences）等效的异步请求。


在异步请求中，客户端应用程序向SuiteTalk平台发送一个请求，将其放置在处理队列中，并与其他处理队列异步处理
要求。请注意，每个投票期的所有可用作业都将连续处理。没有可用的工作的强制等待期。一旦工作完成
在Web服务响应中返回作业ID。您的客户端应用程序可以通过引用作业ID来检查请求的状态和结果。


注意：异步请求JobIDs有效期为30天。



====  XML示例
[source,xml]
----
<netsuite:async-get-list config-ref="Netsuite">
    <netsuite:records ref="#[flowVars.records]"/>
</netsuite:async-get-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
记录图标：信封[]  | 列表<BaseRefType>  | 引用要检索的对象的RecordRef列表。 | ＃[有效载荷]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  | 带有jobId的AsyncStatusResult，可用于检查作业的状态和结果。
|======================




---

=== 异步初始化列表
`<netsuite:async-initialize-list>`





与#initializeList（List，Preferences）等效的异步请求。

在异步请求中，客户端应用程序向SuiteTalk平台发送一个请求，将其放置在处理队列中，并与其他处理队列异步处理
要求。请注意，每个投票期的所有可用作业都将连续处理。没有可用的工作的强制等待期。一旦工作完成
在Web服务响应中返回作业ID。您的客户端应用程序可以通过引用作业ID来检查请求的状态和结果。

注意：异步请求JobIDs有效期为30天。


====  XML示例
[source,xml]
----
<netsuite:async-initialize-list config-ref="Netsuite">
	<netsuite:initialize-record ref="#[flowVars.initializeRecordList]"/>
</netsuite:async-initialize-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
initializeRecord icon：envelope []  | 列表<InitializeRecord>  | 引用要初始化的对象的InitializeRecord列表。 | ＃[payload]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| AsyncStatusResult  |  Ab AsyncStatusResult，带有jobId，可用于检查作业的状态和结果。
|======================




---

=== 初始化列表
`<netsuite:initialize-list>`






用于通过使用相关记录中的值预填充事务处理行项目上的字段来模拟UI工作流程。



====  XML示例
[source,xml]
----
<netsuite:initialize-list config-ref="Netsuite">
    <netsuite:initialize-record ref="#[flowVars.initializeRecordList]"/>
</netsuite:initialize-list>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
initializeRecord图标：envelope []  | 列表<InitializeRecord>  | 要初始化的InitializeRecord的列表。 | ＃[payload]  | 




|
首选项  | 首选项 | 请求的首选项。 |   | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
|列表<ReadResponse>  | 包含每个初始化请求结果的列表。
|======================




---

=== 更改电子邮件
`<netsuite:change-email>`






用于更改帐户的电子邮件地址。



====  XML示例
[source,xml]
----
<netsuite:change-email config-ref="Netsuite" newEmail="#[flowVars.newEmail]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
newEmail图标：信封[]  | 字符串 | 新电子邮件的值。 | ＃[有效负载]  | 




|
justThisAccount   | 布尔 | 更新此帐户的电子邮件。 |  true  | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| SessionResponse  |  SessionResponse的一个实例。
|======================




---

=== 更改密码
`<netsuite:change-password>`






用于更改帐户的密码。



====  XML示例
[source,xml]
----
<netsuite:change-password config-ref="Netsuite" newPassword="#[flowVars.newPassword]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
newPassword图标：信封[]  | 字符串 | 新密码值 | ＃[有效负载]  | 




|
justThisAccount   | 布尔 | 将更改仅应用于此帐户。 |  true  | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| SessionResponse  |  SessionResponse的一个实例。
|======================




---

=== 获取数据中心网址
`<netsuite:get-data-center-urls>`






返回指定accountId的可访问数据中心URL。



====  XML示例
[source,xml]
----
<netsuite:get-data-center-urls config-ref="Netsuite" accountId="#[flowVars.account]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
accountId图标：信封[]  | 字符串 |  Netsuite帐户ID  | ＃[有效负载]  | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| GetDataCenterUrlsResult  | 请求包含状态和数据中心URL的结果。
|======================




---

=== 映射sso
`<netsuite:map-sso>`


用于自动化外部应用程序凭证和NetSuite用户凭据之间的映射。

此操作提供映射，而不是登录NetSuite。此操作不提供使用单一登录令牌登录的功能，无法配置伙伴
与入站单点登录功能，或与公/私钥交换协助。使用此操作意味着该帐户已设置入站单一登录
并有权访问生成令牌所需的关联合作伙伴ID和加密密钥。


====  XML示例
[source,xml]
----
<netsuite:map-sso config-ref="Netsuite" userAccount="#[flowVars.account]" userPartnerId="#[flowVars.partnerId]" authenticationToken="#[flowVars.token]" userEmail="#[flowVars.email]" userPassword="#[flowVars.password]">
    <netsuite:user-role internalId="#[flowVars.internalId]"/>
  </netsuite:map-sso>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
userAccount   | 字符串 | 帐户 |   |  *x*




|
userPartnerId   | 字符串 | 这是由NetSuite向合作伙伴提供的集成合作伙伴的联属ID。 |   |  *x*




|
authenticationToken   | 字符串 | 这是表示加密标记的字符串。 |   |  *x*




|
USEREMAIL   | 字符串 | 电子邮件 |   |  *x*




|
的userPassword   | 字符串 | 密码 |   |  *x*




|
userRole icon：envelope []  |  RecordRef  | 角色 | ＃[有效负载]  | 


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| SessionResponse  | 包含状态和wsRoleList元素的响应。 wsRoleList元素返回可供护照中指定的用户使用的角色列表。
|======================




---

=== 搜索
`<netsuite:search>`


icon：file-text []分页操作

图标：云[]启用DataSense



搜索操作用于根据一组标准对特定记录类型执行搜索。该处理器通过分页机制进行了增强。


搜索可以是基本，高级或加入搜索。有关所有可用搜索，请参阅SearchRecord。



====  XML示例
[source,xml]
----
<netsuite:search config-ref="Netsuite" searchRecord="#[flowVars.searchRecord]" fetchSize="#[flowVars.pageSize]" criteria-ref="#[flowVars.criteriaRef]"/>
----



==== 属性
[%header%autowidth.spread]
|======================
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  | 字符串 | 指定要使用的配置 |  | *x*



|
searchRecord icon：key []  | 字符串 | 搜索类型 -  SearchRecordTypeEnum  |   |  *x*




|
criteria icon：envelope []  |  SearchRecord  | 一个SearchRecord的实例，它定义组成搜索的属性。 | ＃[payload]  | 




|
bodyFieldsOnly   | 布尔值 | 默认为TRUE并指示记录的主体字段中的信息被返回 - 显着提高性能。关联列表或子列表中的任何字段都不会被返回。如果bodyFieldsOnly字段设置为FALSE，则返回与该记录相关联的所有字段。 |  true  | 




|
returnSearchColumns   | 布尔值 | 默认为TRUE，这意味着只有搜索列会在您的搜索中返回。 |  true  | 




|
pagingConfiguration   |  PagingConfiguration  | 页面大小 |   |  *x*


|======================

==== 返回
[%header%autowidth.spread]
|======================
|返回Java类型 | 描述
| ProviderAwarePagingDelegate <Map <String，Object， link:http://mulesoft.github.io/mule-netsuite-connector/7.6.0/apidocs/apidoc.html[NetSuiteConnector]  | 表示搜索条件结果的地图列表。
|======================
