= 使用Mule发布和使用API
:keywords: anypoint studio, apis

使用Mule应用程序，您可以发布和使用API​​。 Mule提供了不同的工具来促进以下用例：

*  REST API
*  SOAP API
* 公开API
* 使用API

本文档涉及编写代码作为API而不是Web Service与其他代码交互的代码。

== 发布SOAP API

Mule使用CXF框架为 link:/mule-user-guide/v/3.9/publishing-a-soap-api[发布SOAP API]提供支持，实施*{{1}}*。 Apache CXF是一个灵活的开源服务框架，可帮助您使用前端编程API（如JAX-WS）构建Web服务。

您可以在Mule应用程序中使用CXF以使用以下三种方式之一公开SOAP Web服务：

. 使用*proxy service pattern*构建一个WSDL优先API
. 使用*JAX-WS service pattern*构建采用JAXB数据绑定的标准JAX-WS批注的代码优先API
. 使用SOAP组件中的*simple service pattern*从POJO生成一个API

== 使用SOAP API

使用 link:/mule-user-guide/v/3.9/web-service-consumer[* Web服务消费者*]来使用任何SOAP API。这个Anypoint Connector提供了在你的Mule应用程序中使用Web服务的功能。通过使用API​​的WSDL中包含的信息，连接器使您能够配置一些细节，以建立从Mule应用程序中使用服务的连接。首先，确定Web服务的WSDL文件的位置，然后要求Web服务使用者从WSDL  - 主机，端口，地址配置自身。

也许一个连接器已经为您想要连接的API开发。如果是这样，请在Anypoint Exchange中查找并​​将其下载到Studio中。

== 发布REST API

您可以添加到Anypoint Studio实例的工具模块*APIkit*是一个开源的声明性工具包，专门用于实现API优先REST API实现。 APIkit通过自动化流程创建并提供用于快速测试和迭代的嵌入式控制台来强制实施良好的API实施并简化API开发。

link:/apikit/apikit-for-soap[用于SOAP的APIkit]有助于实现一个SOAP接口，使外部用户可以访问您的数据，然后将其与后端进程集成以充当API。

APIkit可以基于RAML（RESTful API Modeling Language）API定义创建API，如 link:/apikit/apikit-tutorial[APIkit教程]中所述。 APIkit使用HTTP端点生成Mule应用程序，异常策略以及后端钩子。此外，它还提供一个API控制台，为您的API公开自动生成的完全可测试的文档。

== 使用REST API

要使用Mule使用REST API，请使用以下技术之一：

*  link:/mule-user-guide/v/3.9/consuming-a-rest-api[配置HTTP连接器]向Mule应用发送请求，并接受来自API的响应。
* 使用 link:/anypoint-connector-devkit/v/3.8[Anypoint连接器DevKit]构建连接器以对API执行操作。

要使用HTTP连接器，请配置MEL表达式以将必要的信息传递给API。如果存在描述您要使用的API的 link:http://raml.org[肾错构瘤]文件，则可以在HTTP连接器中引用该文件以在设计时公开API的结构。这一行动使您无需研究要求中包含的内容以及期望的回复。如果您的API没有RAML文件，请注意您要调用的API的结构，包括任何身份验证要求，要访问的一个或多个资源的名称以及每种资源支持的方法。

如果某个API不存在，并且您计划重复使用该API，则可能需要考虑为此API编写RAML文件。如果您计划频繁使用API​​或者需要超越HTTPS或基本身份验证的安全性，那么构建您自己的连接器而不是配置HTTP端点是很有意义的。

