= 模式验证过滤器
:keywords: anypoint studio, schema, validation, filter, xsd

模式验证过滤器会接受XML输入并根据引用的XSD模式对其进行验证。

通常情况下，您可以将此过滤器放置在另一个消息处理器（如连接器）之前，以确定是否应处理传入消息或事件，从而允许消息只在满足过滤器验证并且包含XML被认为是有效的。

*Minimum Configuration:* XSD架构位置的路径。

模式验证过滤器使用JAXP库来根据模式验证消息。您必须在架构位置属性中提供架构或模式的路径，文件名和扩展名。

或者，您可以将架构语言设置为要使用的架构语言。如果未指定，则属性默认为 link:http://www.w3.org/2001/XMLSchema[XML架构]。

如果您希望在验证失败时获取异常和/或调用另一个流，则可以将模式验证筛选器封装在消息筛选器中，然后使用"onUnaccepted"和"throwOnUnaccepted"配置属性来确定行为。

基本示例== 

默认情况下，模式验证过滤器仅检查XML内容是否与引用的模式验证匹配，但不会将此内容向前传递到流的下一个元素

[source, xml, linenums]
----
<flow name="case11843-crFlow1" doc:name="case11843-crFlow1">
        <file:inbound-endpoint path="/File/" responseTimeout="10000" doc:name="File" />
        <file:file-to-string-transformer doc:name="File to String" />
        <mulexml:dom-to-xml-transformer doc:name="DOM to XML" />
        <mulexml:schema-validation-filter schemaLocations="OrderQuoteData.xsd" returnResult="true" name="OrderData_Schema_Validation"
        doc:name="Schema Validation" />
        <logger message="FILE OK: #[message.payload]" level="INFO" doc:name="Logger" />
    </flow> 
----

=== 完整代码

[source, xml, linenums]
----
<mule xmlns:json="http://www.mulesoft.org/schema/mule/json" xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:spring="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/json http://www.mulesoft.org/schema/mule/json/current/mule-json.xsd">
 
    <flow name="case11843-crFlow1" doc:name="case11843-crFlow1">
        <file:inbound-endpoint path="/File/" responseTimeout="10000" doc:name="File" />
        <file:file-to-string-transformer doc:name="File to String" />
        <mulexml:dom-to-xml-transformer doc:name="DOM to XML" />
        <mulexml:schema-validation-filter schemaLocations="OrderQuoteData.xsd" returnResult="true" name="OrderData_Schema_Validation"
        doc:name="Schema Validation" />
        <logger message="FILE OK: #[message.payload]" level="INFO" doc:name="Logger" />
    </flow>
</mule>
----

[WARNING]
请注意，在此示例中，即使文件的XML内容与XSD格式匹配，向前传递的有效内容也为空。验证内容是否正确后，它不会继续传递。

== 向前传递XML

要允许有效的XML通过过滤器，请在模式验证过滤器中将`returnResult`设置为false。通过这种方式，向前传递到流中下一个元素的消息的有效内容将保留XML内容。

[source, xml, linenums]
----
<flow name="case11843-crFlow1" doc:name="case11843-crFlow1">
  <file:inbound-endpoint path="/File/" responseTimeout="10000" doc:name="File" />
  <file:file-to-string-transformer doc:name="File to String" />
  <mulexml:dom-to-xml-transformer doc:name="DOM to XML" />
  <mulexml:schema-validation-filter schemaLocations="OrderQuoteData.xsd" returnResult="false" name="OrderData_Schema_Validation" doc:name="Schema Validation" />
  <logger message="FILE OK: #[message.payload]" level="INFO" doc:name="Logger" />
</flow> 
----

=== 完整代码

（折叠内容）

[source, xml, linenums]
----
<mule xmlns:json="http://www.mulesoft.org/schema/mule/json" xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:spring="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/json http://www.mulesoft.org/schema/mule/json/current/mule-json.xsd">
 
    <flow name="case11843-crFlow1" doc:name="case11843-crFlow1">
        <file:inbound-endpoint path="/File/" responseTimeout="10000" doc:name="File" />
        <file:file-to-string-transformer doc:name="File to String" />
        <mulexml:dom-to-xml-transformer doc:name="DOM to XML" />
        <mulexml:schema-validation-filter schemaLocations="OrderQuoteData.xsd" returnResult="false" name="OrderData_Schema_Validation"
        doc:name="Schema Validation" />
        <logger message="FILE OK: #[message.payload]" level="INFO" doc:name="Logger" />
    </flow>
</mule>
----

== 将验证器插入过滤器

默认情况下，当XML内容与XSD验证不匹配时，会引发异常。如果您想分别处理被拒绝的消息，则可以将模式验证程序创建为全局元素，然后从过滤器内引用它。然后，您可以利用过滤器的`onUnaccepted`或`throwOnUnaccepted`属性来在不满足过滤条件的情况下将消息处理指向不同的流，例如XML未经验证。

[source, xml, linenums]
----
<mulexml:schema-validation-filter schemaLocations="OrderQuoteData.xsd" returnResult="false" name="OrderData_Schema_Validation"
        doc:name="Schema Validation" />
 
    <flow name="case11843-crFlow1" doc:name="case11843-crFlow1">
        <file:inbound-endpoint path="/File/" responseTimeout="10000" doc:name="File" />
        <file:file-to-string-transformer doc:name="File to String" />
        <mulexml:dom-to-xml-transformer doc:name="DOM to XML" />
        <message-filter onUnaccepted="error_invalid_data" doc:name="Validate Order Xml" />
        <logger message="FILE OK: #[message.payload]" level="INFO" doc:name="Logger" />
    </flow>
 
    <flow name="error_invalid_data" doc:name="error_invalid_data">
        <logger message="ERROR: MESSAGE PAYLOAD: #[message.payload]" level="INFO" doc:name="Logger" />
    </flow>
----

=== 完整代码

[source, xml, linenums]
----
<mule xmlns:json="http://www.mulesoft.org/schema/mule/json" xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:spring="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/json http://www.mulesoft.org/schema/mule/json/current/mule-json.xsd">
 
    <mulexml:schema-validation-filter schemaLocations="OrderQuoteData.xsd" returnResult="false" name="OrderData_Schema_Validation"
        doc:name="Schema Validation" />
 
    <flow name="case11843-crFlow1" doc:name="case11843-crFlow1">
        <file:inbound-endpoint path="/File/" responseTimeout="10000" doc:name="File" />
        <file:file-to-string-transformer doc:name="File to String" />
        <mulexml:dom-to-xml-transformer doc:name="DOM to XML" />
        <message-filter onUnaccepted="error_invalid_data" doc:name="Validate Order Xml" />
        <logger message="FILE OK: #[message.payload]" level="INFO" doc:name="Logger" />
    </flow>
 
    <flow name="error_invalid_data" doc:name="error_invalid_data">
        <logger message="ERROR: MESSAGE PAYLOAD: #[message.payload]" level="INFO" doc:name="Logger" />
    </flow>
</mule>
----

在上面的示例中，当XML内容与XSD验证不匹配时，该消息将指向名为`error_invalid_data`的流。

请注意，由于全局元素中的`returnResult`属性设置为false，因此发送到其他流的被拒绝消息也包含XML内容。如果`returnResult`属性设置为true，则发送到此流的拒绝消息的有效内容将为空。

== 另请参阅

*  link:/mule-user-guide/v/3.9/filters-configuration-reference[过滤器配置参考]




