=  Oracle Siebel业务对象连接器API参考
:keywords: oracle, siebel, business, objects
：最后更新标签!:
：文档信息：
：source-highlighter：coderay
：图标：字体

+++
Oracle Siebel Java Data Beans连接器
+++

*Additional Info*
[%header%autowidth.spread]
|===
|  {要求{1}}是否必需？
| 需要Mule Enterprise许可证 |  是图标：star [] {nbsp}
| 需要权利 |  是图标：星形[] {nbsp}
|  Mule版本 |  3.5.0或更高版本
|===

== 配置
`<siebel:config>`


`Connection Management`



=== 属性

[%header%autowidth.spread]
|===
| 名称 |  Java类型 | 描述 | 默认值 | 必需
|姓名 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 此配置的名称。此名称可以稍后参考。 |  |  *x* {nbsp}
| 用户 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++ Siebel用户名+++  |    |  {{ 2}} {} NBSP
|  rsaEnabled  |  +++布尔型+++  |  +++ Siebel加密类型。确保您的服务器配置为支持RSA加密。默认情况下，它设置为false。+++  |   false  |  {nbsp}
| 密码 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++ Siebel密码+++  |    |  {{ 2}} {} NBSP
| 服务器 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++ Siebel服务器。服务器IP。+++  |    |  *x* {nbsp}
| 端口 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++ Siebel端口。用于连接的服务器端口。默认情况下它是2321。+++  |   2321  |  {nbsp}
| 服务器名称 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++ Siebel Enterprise服务器名称+++  |    |  *x* {} NBSP
|  objectManager  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++ Siebel对象管理器+++  |    |  { {2}} {} NBSP
| 语言 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++连接语言+++  |   ENU  |  { NBSP}
| 编码 |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++连接文件编码。它指定了Siebel客户端的字符编码。默认情况下，它是utf8。+++  |   utf8  |  {nbsp}
|  defaultViewModeBusComp  |  +++ int +++  |  +++用于DataSense目的的默认视图模式。默认情况下，它设置为'3'，这意味着它会遍历所有有效所有者的记录。+++  |   3  |  {nbsp}
|  dataSenseFilterQueryBusComp  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++用于过滤DataSense业务组件结果的查询+++ {{5 }} |  {} NBSP
|  defaultViewModeBusObjects  |  +++ int +++  |  +++用于Business Objects发现的默认视图模式。默认情况下，它设置为'3'，这意味着它会遍历所有有效所有者的记录。+++  |   3  |  {nbsp}
|  dataSenseFilterQueryBusObjects  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++过滤DataSense Business Objects结果的查询+++  |    {{ 6}} {} NBSP
|  dataSenseHierarchicalDiscovery  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">布尔值</a> +++  |  +++指示字段发现是否在业务组件中重新创建分层对象。默认情况下，它设置为false。+++  |   false  |  {nbsp}
|===



== 处理器

---

=== 查询业务组件
`<siebel:query-business-components>`



图标：云端[] {nbsp}启用DataSense

+++
根据给定的搜索规范或搜索表达式检索业务组件的列表
+++

====  XML示例
[source,xml,linenums]
----
<siebel:query-business-components config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action" records="">
        <siebel:fields-to-retrieve>
                    <siebel:fields-to-retrieve>Description</siebel:fields-to-retrieve>
                </siebel:fields-to-retrieve>
        <siebel:search-spec>
            <siebel:search-spec key="Description">Action1</siebel:search-spec>
        </siebel:search-spec>
    </siebel:query-business-components>
----

    
                                
==== 属性

[%header%autowidth.spread]
|===
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



| 
Siebel业务对象组件类型+++  |   | 业务对象组件类型图标：key []  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++ {{4} } *x* {} NBSP




| 
fieldsToRetrieve   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++要在查询中检索的字段列表+++  |   { {7}} *x* {} NBSP




| 
searchSpec   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">使用搜索值映射</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++映射作为查询中的过滤器+++ {{ 5}} |  {} NBSP




| 
搜索表达式  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 用于Siebel业务组件的+++搜索表达式+++  |   |  {n}




| 
sortSpec   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 用于Siebel业务组件的+++排序规范+++  |   |  {n}




| 
表示业务组件的可见性类型的视图模式  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++整数：0（SalesRepView）1（ManagerView）2 （PersonalView）3（AllView）4（NoneSetView）+++  |  3  |  {nbsp}




| 
记录  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++整数，表示查询返回的记录数。默认情况下，它会返回所有记录。+++  |   |  {nbsp}


|===

==== 返回

[%header%autowidth.spread]
|===
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>> +++  |  +++具有组件值的映射列表+++
|===




---

=== 查询加入业务组件

`<siebel:query-join-business-components>`




+++
允许检索两个不同的业务对象，并根据指定的条件加入它们
+++

====  XML示例
[source,xml,linenums]
----
<siebel:query-join-business-components config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Opportunity.Opportunity" businessObjectComponentTypeToJoin="Opportunity.Opportunity Product">
        <siebel:fields-to-retrieve>
            <siebel:fields-to-retrieve>Id</siebel:fields-to-retrieve>
            <siebel:fields-to-retrieve>name</siebel:fields-to-retrieve>
        </siebel:fields-to-retrieve>
        <siebel:fields-to-retrieve-to-join>
            <siebel:fields-to-retrieve-to-join>Id</siebel:fields-to-retrieve-to-join>
            <siebel:fields-to-retrieve-to-join>Name</siebel:fields-to-retrieve-to-join>
        </siebel:fields-to-retrieve-to-join>
        <siebel:join-condition>
            <siebel:join-condition key="Id">Oppty Id</siebel:join-condition>
        </siebel:join-condition>
    </siebel:query-join-business-components>
----

    
                                    
==== 属性

[%header%autowidth.spread]
|===
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



| 
businessObjectComponentType   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++ Siebel业务对象组件类型+++  |   |  {{2} } {} NBSP




| 
fieldsToRetrieve   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++要在查询中检索的字段列表+++  |   { {7}} *x* {} NBSP




| 
searchSpec   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">使用搜索值映射</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++映射作为查询中的过滤器+++ {{ 5}} |  {} NBSP




| 
搜索表达式  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 用于Siebel业务组件的+++搜索表达式+++  |   |  {n}




| 
businessObjectComponentTypeToJoin   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要加入的业务对象组件+++  |   |  {{2} } {} NBSP




| 
fieldsToRetrieveToJoin   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++字段以检索业务组件以加入+++  |   |  *x* {} NBSP




| 
joinCondition   |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++map containing the join condition for the business object. The structure is (key[object1中的字段]，value [object 2中的字段]）+++  |   |  *x* {nbsp}




| 
ViewMode   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++ Siebel业务组件视图模式+++  |  3  |  {nbsp}




| 
nrRecords   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++查询返回的记录数+++  |   |  {nbsp }


|===

==== 返回

[%header%autowidth.spread]
|===
|返回Java类型 | 描述
| +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>> +++  |  +++具有组件值的映射列表+++
|===




---

=== 创建业务组件
`<siebel:create-business-component>`



图标：云端[] {nbsp}启用DataSense

+++
创建一个新的业务组件
+++

====  XML示例
[source,xml,linenums]
----
<siebel:create-business-component config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action">
        <siebel:business-component-fields>
            <siebel:business-component-field key="Description">New Action</siebel:business-component-field>
        </siebel:business-component-fields>
    </siebel:create-business-component>
----

    
            
==== 属性

[%header%autowidth.spread]
|===
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



| 
Siebel业务对象组件类型+++  |   | 业务对象组件类型图标：key []  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++ {{4} } *x* {} NBSP




| 
businessComponentFields icon：envelope []  |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++map with the list of values to be added to the new component+++ | #[有效载荷]  |  {nbsp}


|===

==== 返回

[%header%autowidth.spread]
|===
|返回Java类型 | 描述
| +++ CreateResult +++  |  +++创建了业务组件id +++
|===




---

=== 更新业务组件

`<siebel:update-business-component>`



图标：云端[] {nbsp}启用DataSense

+++
从值映射更新Siebel业务组件
+++

====  XML示例
[source,xml,linenums]
----
<siebel:update-business-component config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action">
        <siebel:search-spec>
            <siebel:search-spec key="Id">1-EA-2223</siebel:search-spec>
        </siebel:search-spec>
        <siebel:business-component-fields>
            <siebel:business-component-field key="Description">New Action</siebel:business-component-field>
        </siebel:business-component-fields>
    </siebel:update-business-component>
----

    
                    
==== 属性

[%header%autowidth.spread]
|===
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



| 
Siebel业务对象组件类型+++  |   | 业务对象组件类型图标：key []  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++ {{4} } *x* {} NBSP




| 
searchSpec   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">地图</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++地图，其中包含搜索要更新的业务组件的规范+++ {{6} } |  *x* {} NBSP




| 
businessComponentFields icon：envelope []  |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++map with the list of values to be updated in the component+++ | #[有效载荷]  |  {nbsp}




| 
ViewMode   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++ Siebel业务组件视图模式+++  |  3  |  {nbsp}


|===

==== 返回

[%header%autowidth.spread]
|===
|返回Java类型 | 描述
| +++ UpdateResult +++  |  +++如果操作成功+++，则为true
|===




---

===  Upsert业务组件

`<siebel:upsert-business-component>`



图标：云端[] {nbsp}启用DataSense

+++
根据存在或不存在创建或更新业务组件。为了检查记录是否存在，它会将Siebel考虑到idfield列表。如果
列表为空，它将采用业务组件字段映射中的Id字段。
+++

====  XML示例

[source,xml,linenums]
----
<siebel:upsert-business-component config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action">
        <siebel:business-component-fields>
            <siebel:business-component-field key="Id">1-EA223</siebel:business-component-field>
            <siebel:business-component-field key="Description">New Action</siebel:business-component-field>
        </siebel:business-component-fields>
        <siebel:id-fields>
            <siebel:id-field>Description</siebel:id-field>
        </siebel:id-fields>
    </siebel:upsert-business-component>
----

    
                    
==== 属性

[%header%autowidth.spread]
|===
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



| 
Siebel业务对象组件类型+++  |   | 业务对象组件类型图标：key []  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++ {{4} } *x* {} NBSP




| 
businessComponentFields icon：envelope []  |  +++ <a href =“ http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++map with the list of values to be updated in the component+++ | #[有效载荷]  |  {nbsp}




| 
idFields   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">列表</a> <<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>> +++  |  +++作为要分析的记录的标识符的字段列表它应该创建或不是+++  |   |  {nbsp}




| 
ViewMode   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++ Siebel业务组件视图模式+++  |  3  |  {nbsp}


|===

==== 返回

[%header%autowidth.spread]
|===
|返回Java类型 | 描述
创建或更新的业务组件的| +++ UpsertResult +++  |  +++标识+++
|===




---

=== 删除业务组件

`<siebel:delete-business-component>`



图标：云端[] {nbsp}启用DataSense

+++
从Id中删除Siebel业务组件记录
+++

====  XML示例
[source,xml,linenums]
----
<siebel:delete-business-component config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action"
        businessComponentId="EJJ-11"/>
----

    
                
==== 属性

[%header%autowidth.spread]
|===
|名称 | Java类型 | 描述 | 默认值 | 必需
|  config-ref  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  | 指定要使用的配置 |  | *x* {} NBSP



| 
Siebel业务对象组件类型+++  |   | 业务对象组件类型图标：key []  |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++ {{4} } *x* {} NBSP




| 
businessComponentId   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">字符串</a> +++  |  +++要删除的业务组件的ID +++  |   |  { {2}} {} NBSP




| 
ViewMode   |  +++ <a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">整数</a> +++  |  +++ Siebel业务组件视图模式+++  |  3  |  {nbsp}


|===

==== 返回

[%header%autowidth.spread]
|===
|返回Java类型 | 描述
| +++布尔型+++  |  +++如果操作成功+++，则为true
|===

