= 从TLS 1.0迁移
:keywords: tls, trust, store, https, ssl, secure messages, encryption, trust store, key store, keystore, truststore

由于PCL合规性不再接受TLS 1.0，并且考虑到此协议版本的重大漏洞，我们强烈建议您迁移到TLS v1.1和更高版本。

自Studio 5.4.3以来，您可以编辑Studio和API网关运行时的TLS配置文件。

== 从Studio编辑运行时的TLS配置文件

从Studio安装文件夹中，导航到`plugins`目录。在那里，您需要找到服务器运行时和Studio版本的文件夹。 +
文件夹的名称应该遵循以下形式：

[source]
----
org.mule.tooling.server.3.7.3.ee_5.4.x.yyy.mm.dd
----

在其中，转至`mule` / `conf`目录并打开`tls-default.conf`文件以编辑您的TLS配置。 +
您可以在`enabledProtocols`字段中找到启用的配置协议。

如果需要，您还可以在与您的站点的安全策略对应的enabledCipherSuites中注释或取消注释行。

== 从Studio中编辑您的API网关的TLS配置文件

从Studio安装文件夹中，导航到`plugins`目录。在那里，您需要找到服务器的API Gateway和Studio版本的文件夹。 +
文件夹的名称应该遵循以下形式：

[source]
----
org.mule.tooling.apigateway.x.x.x_x.x.x.yyyymmdd
----

在其中，转至`mule` / `conf`目录并打开`tls-default.conf`文件以编辑您的TLS配置。 +
您可以在`enabledProtocols`字段中找到启用的配置协议。

如果需要，您还可以在与您的站点的安全策略对应的enabledCipherSuites中注释或取消注释行。

[NOTE]
--
如果您使用Mule运行时3.9或更高版本构建应用程序，并使用JDK 1.7，则不支持TLS 1.2。建议您将JDK更新到1.8以支持此安全协议。

如果由于任何原因您无法将JDK更新到1.8，那么您必须手动配置Mule 3.9以指向TLS V1.0。

MMC用户将需要下载MMC版本*V3.8 HF1*，该版本特别帮助Mule V3.8和JDK 1.7的用户指向TLS V1.0而不是V1.2，因此只需将MMC更新至此版本即可解决此问题。
--

== 另请参阅

* 详细了解维基百科中的 link:http://en.wikipedia.org/wiki/Transport_Layer_Security[TLS]
* 了解如何配置 link:/mule-user-guide/v/3.9/http-connector[HTTP连接器]
* 了解如何处理 link:/mule-user-guide/v/3.9/tls-configuration#global-tls-configuration[全局TLS配置]
