= 注释参考

本文档列出了以符号（@）开头的MuleSoft元素。有关注释的更多信息，请参阅 link:http://docs.oracle.com/javase/7/docs/api/index.html?java/lang/annotation/Annotation.html[java.lang.annotation.Annotation]。

*{{0}}*

[%header%autowidth.spread]
|===
| {注解{1}}说明
| `@Category` a | Anypoint Studio和doclet使用@Category注释来组织消息处理器。您可以在类定义级别（连接器或模块）上使用@Category注释来选择要在哪个类别中列出您的扩展：

[source, java, linenums]
----
@Connector(name = "ldap", schemaVersion = "3.5", 
  friendlyName="LDAP", minMuleVersion="3.5",
  description="The LDAP connector connects to a  
    LDAP server and performs LDAP operations")
@Category(name = "org.mule.tooling.category.core",  
  description = "Components")
  public class LDAPConnector
    {
      ...
    }
----

笔记：

* 您只能将连接器添加到其中一个现有的Studio类别中（这意味着您无法定义自己的类别）
*  @Category的名称和描述属性的值只能包含以下值：

** 终点：org.mule.tooling.category.endpoints
** 作用域：org.mule.tooling.category.scopes
** 组件：org.mule.tooling.category.core
** 变形金刚：org.mule.tooling.category.transformers
** 过滤器：org.mule.tooling.category.filters
** 流量控制：org.mule.tooling.category.flowControl
** 错误处理：org.mule.tooling.ui.modules.core.exceptions
** 云端连接器（DEFAULT）：org.mule.tooling.category.cloudconnector
** 其他：org.mule.tooling.ui.modules.core.miscellaneous
** 安全性：org.mule.tooling.category.security

您可以使用以下来指定允许的类别：

[source, java, linenums]
----
import org.mule.api.annotations.Category;
  
@Category(name = "org.mule.tooling.category.endpoints", description = "Endpoints")
@Category(name = "org.mule.tooling.category.scopes", description = "Scopes")
@Category(name = "org.mule.tooling.category.core", description = "Components")
@Category(name = "org.mule.tooling.category.transformers", description = "Transformers")
@Category(name = "org.mule.tooling.category.filters", description = "Filters")
@Category(name = "org.mule.tooling.category.flowControl", description = "Flow Control")
@Category(name = "org.mule.tooling.ui.modules.core.exceptions", description = "Error Handling")
@Category(name = "org.mule.tooling.category.cloudconnector", description = "Cloud Connectors")
@Category(name = "org.mule.tooling.ui.modules.core.miscellaneous", description = "Miscellaneous")
@Category(name = "org.mule.tooling.category.security", description = "Security")
----
| `@Configurable` a |将`@Connector`中的字段标记为可配置的。 `@Configurable`注释指示生成器通过XML语法或连接器配置对话框创建可为连接器的每个实例配置的属性。除`@Configurable`注释之外，您至少需要一个公共get和set函数。

[source, java, linenums]
----
@Configurable
 private String url;
  
 public String getUrl() {
      return url;
 }
  
 public void setUrl(String url) {
      this.url = url;
 }
----
| `@Connector` a |定义一个将其功能导出为Mule连接器的类。

此类级别注释将Java类标识为云连接器。

`@Connector`限制：

* 不能成为界面
* 必须是`public`
* 不能有类型化的参数（没有泛型）

[source, java, linenums]
----
@Connector(name = "hello", schemaVersion = "1.0", friendlyName = "Hello", minMuleVersion = "3.5")
public class HelloConnector {
  ...
}
----
| `@Expr` a |将`@Processor`方法中的参数绑定到表达式。

将参数绑定到表达式与`@Payload`类似，因为模块的用户将无法更改XML中的表达式或参数值。绑定是硬编码的，用户不能更改它。

以下示例将`myFlowVarXXX`参数映射到表达式`flowVars['xxx']`的结果：

[source, java, linenums]
----
@Processor       
 public String myProcessor(@Expr("flowVars['xxx']") 
   String myFlowVarXXX) {
     ...
   }
----
| `@ExpressionLanguage` a |定义了一个将其功能导出为Mule表达式语言的类。

有关哪些类型有效的`@ExpressionLanguage`限制：

* 不能成为界面
* 必须是`public`
* 不能有类型化的参数（没有泛型）

[source, java, linenums]
----
@ExpressionLanguage(name = "expr")
public class ExprExpressionLanguage {
    @ExpressionEvaluator
    public Object evaluate() {
}
----
| @ ExpressionEnricher a |将`@ExpressionLanguage`中的方法标记为负责基于表达式丰富mule消息。

以下示例显示了如何使用`@ExpressionEnricher`注释使用“map-payload”表达式语言在`enrich()`方法中设置有效内容（预期为映射）：

[source, java, linenums]
----
@ExpressionLanguage(name = "map-payload")
public class MapPayloadExpressionLanguage {
  
    @ExpressionEnricher
    public void enrich() {
}
----
| `@Filter` a |将`@Connector`中的方法标记为可以过滤消息的Mule流中的可调用方法。此方法中的每个参数都被用作Mule XML调用的属性。

通过将此注释添加到`@Connector`中的一个方法中，将创建一个过滤器，该过滤器可以从Mule流中用于基于此方法的实现过滤消息。

[source, java, linenums]
----
@Filter
    public boolean shouldFilter() throws Exception {
...
   }
----
| `@Ignore` a |忽略复杂对象内的一个字段。

[source, java, linenums]
----
public class MyComplexType
{
    private String color;
      
    @Ignore
    private String description;
}
  
@Processor
public void receiveAComplexType(MyComplexType myComplexType) { ... }
----
| `@Mime` a |定义一个将其功能导出为Mule模块的类。

类级注释`@Module`表示需要由DevKit注释处理工具处理Java类并将其视为Mule模块。

@ `Module`无法应用于：

* 接口
* 最终课程
* 参数化类
* 非公开课程

[source, java, linenums]
----
@Module(name="animal-search", schemaVersion="3.5.1")
public class AnimalSearchModule { ... }
----
| `@Ognl`  |（对象图导航语言）。 *Note*：@gnl在Mule版本3.6中不推荐使用，并且在版本4.0中被删除。
| `@Paged` a |将`@Connector`中的方法标记为返回分页结果集的操作。使用此接口注释的方法也必须使用`@Processor`进行注释，并且必须返回`@ProviderAwarePagingDelegate`的实例。

[source, java, linenums]
----
@Processor
@Paged
public ProviderAwarePagingDelegate paginationTestOperation (String ble, PagingConfiguration pagingConfiguration) throws WrongParameterConfiguredException { ... }
----
| `@Processor` a |将方法标记为连接器中的操作。 `@Processor`方法生成通用消息处理器

[source, java, linenums]
----
@Processor
    public String putInBarn(String animal) {
        return animal + " has been placed in the barn";
    }
----
| `@Source` a |将`@Connector`中的方法标记为可从Mule流中调用并能够生成Mule事件。

此注释将 link:http://mulesoft.github.io/mule-devkit/3.5.3/apidocs/index.html[模]中的方法标记为可从Mule流中调用，并且能够生成Mule事件。每个标记的方法都有一个`org.mule.api.source.MessageSource`生成。该方法必须接收SourceCallback作为其参数之一。只要它在那里，哪个参数是无关紧要的。

[source, java, linenums]
----
@Source
   public void subscribeTopic(String topic, 
     final SourceCallback callback) {
       getBayeuxClient().subscribe(topic, 
         new ClientSessionChannel.MessageListener() {
         @Override
           public void onMessage(ClientSessionChannel channel, 
             Message message) {
               try {
                 callback.process(message.getData());
               } catch (Exception e) {
                 LOGGER.error(e);
               }
             }
         });
     }
----
| `@Transformer` a |将方法标记为连接器上下文中的数据类型或数据格式的Transformer。

这个注释标识了一个变成Mule变换器的方法。

[source, java, linenums]
----
@Transformer(sourceTypes = { Object[].class })
public static List transformArrayToList(@Payload Object[] payload)
----
| `@TransformerResolver` a |查找符合注册表中的条件的转换器。该接口的实现使用传入的一些或全部信息来发现匹配的变压器。

在实现之前注册与注册表的接口的实现可以被获取。通常使用`registry-bootstrap.properties`完成。

[source, java, linenums]
----
@TransformerResolver
public static org.mule.api.transformer.Transformer  
  transformerResolver(DataType source, DataType result, 
  MuleContext muleContext) throws Exception {
    if(source.getType().equals(Book.class) && 
      result.getType().equals(String.class)) {
        BookToString bookToString = new BookToString();  
        muleContext.getRegistry().
          applyProcessorsAndLifecycle(bookToString);
        return bookToString;
   }
      return null;
}
----
|===

== 参数传递注释

[%header%autowidth.spread]
|===
| {注解{1}}说明
| `@Payload` a |标记参数以接收有效负载。

[source, java, linenums]
----
@Processor
public String setPayload(@Payload String payload) { ... }
----
| `@InboundHeaders` a |传入入站标头。

[source, java, linenums]
----
@Processor
public String getInboundHeaders(@InboundHeaders("myHeader") String myHeader) { ... }
----
| `@InvocationHeaders` a |传递调用标头。这可以是单个标题，逗号分隔的标题名称列表，用于捐赠所有标题的astrick "*"，或通配符表达式的逗号分隔列表。默认情况下，如果一个指定的头文件不存在，则抛出异常。但是，如果标题名称是使用"?"修补程序定义的，则标记为可选。

[source, java, linenums]
----
@Processor
public String getInvocationHeaders(@InvocationHeaders("myHeader") 
  String myHeader) { ... }
----
| `@OutboundHeaders` a |用于传递出站标题。

[source, java, linenums]
----
@Processor
public void outboundHeaders(@OutboundHeaders 
  Map<String, Object> outboundHeaders) { ... }
----
| `@SessionHeaders` a |标记传入一个或多个收到标头的方法参数。

此注释值可以定义单个标题，标题名称的逗号分隔列表，星号* to denote all headers, or a comma-seperated list of wildcard expressions such as `MULE_*，X  -  *`。默认情况下，如果当前消息中不存在已命名的标头，则会引发异常。但是，如果标题名称是使用"?"修补程序定义的，则标记为可选。

定义多个标题名称或使用通配符时，此参数可以是Map或List。如果使用Map，则会传递标题名称和值。如果使用List，则仅使用标题值。

如果定义了单个标题名称，则可以将标题类型用作参数类型，但也可以使用List或Map。

Inbound头部集合是不可变的，所以传入的头部Map或List也是不可变的。试图写入映射或列表结果的UnsupportedOperationException。
|===

== 连接管理

有关详情，请参阅 link:/anypoint-connector-devkit/v/3.5/basic-auth[基本认证]

[%header%autowidth.spread]
|===
| {注解{1}}说明
| `@Connect` a |将@Connector作用域内的方法标记为负责创建连接。

此方法可以有多个参数，并且可以包含注释，例如@ConnectionKey或@Password。 @Connect注释保证在调用任何消息处理器之前调用该方法。

限制：

* 参数不能是基本类型，例如int，bool，short等。
* 该方法的返回类型必须为空。

例：

[source, java, linenums]
----
@Connect
public void connect(@ConnectionKey String username, String password) throws ConnectionException { ... }
----
| `@ConnectionIdentifier` a |将@Connector中的方法标记为负责识别连接。

出于调试目的，连接器的连接管理器调用用@ConnectionIdentifier注解的方法。

此注释必须用于不带参数的非静态方法，并且必须返回包含连接标识符表示的字符串。

[source, java, linenums]
----
@ConnectionIdentifier
  public String connectionId() {
    return "001";
  }
----
| `@Disconnect` a |将@Connector中的方法标记为负责处理连接。由连接器的连接管理器调用。

此方法作为维护连接池的一部分进行调用。该池配置了最大空闲时间值。

当连接位于池中而不超过配置的时间时，则调用使用@Disconnect注释的方法，然后调用@Connect方法。另外，当在方法上使用@InvalidateConnectionOn注释来捕获异常时，同样会调用@Disconnect方法并进行后续的重新连接。

[source, java, linenums]
----
@Disconnect
public void disconnect() { ... }
----
| `@InvalidateConnectionOn` a |使用一种方法来捕获异常 - 反对使用@ReconnectOn。

[source, java, linenums]
----
@Processor
    @InvalidateConnectionOn(exception=AnimalException.class)
    public Animal getAnimal (String id ) { ... }
----
| `@ReconnectOn` a |用于使连接无效。您可以将此注释附加到使用@Processor注释的任何方法。如果Processor或Source引发与@ReconnectOn注释中指定的任何异常相匹配的异常，则连接将失效。

[source, java, linenums]
----
Processor
@ReconnectOn(exceptions = {InvalidSessionFault.class, PasswordChangedException.class})
public void myOperation(@Optional String source,
                        @Optional Object destination) throws InvalidSessionFault, PasswordChangedException, InvalidParameterException
{  ... }
----
| `@ValidateConnection` a |在每次调用由@Processor注解公开的操作之前验证连接。

[source, java, linenums]
----
@ValidateConnection
    public boolean isConnected() { ... }
----
|===

==  DataSense

有关信息，请参阅 link:/mule-user-guide/v/3.5/datasense[DataSense]， link:/anypoint-connector-devkit/v/3.5/adding-datasense[添加DataSense]和 link:/anypoint-connector-devkit/v/3.5/adding-datasense-query-language[添加DataSense查询语言]

[%header%autowidth.spread]
|===
| {注解{1}}说明
| `@MetaDataCategory` a |描述分组DataSense具体类，它返回任何类型的类型和描述。

用于注释一个类，该类将使用DataSense提供有关连接器的元数据的方法分组。

[source, java, linenums]
----
@MetaDataCategory
public class MyCategory {
----
| `@MetaDataKeyParam` a |将`@Processor`中的参数标记为元数据查找的关键字。

[source, java, linenums]
----
public Object create(@MetaDataKeyParam String entityType, @Default("#[payload]") Object entityData) {...} 
----
| `@MetaDataKeyRetriever` a |用于注释负责返回服务实体名称的方法。

鉴于此注释的功能，此Java方法的返回类型必须是`List<MetaDataKey>`。

从此方法返回的实体来自使用`@MetaDataRetriever`获得的详细说明之后的查询。

在`@Connector`上下文中或在`@MetaDataCategory`中使用此注释。

[source, java, linenums]
----
@MetaDataKeyRetriever
    public List<MetaDataKey> getMetaDataKeys() throws Exception {
----
| `@MetaDataOutputRetriever` a |对于给定的`@MetaDataKey`，将方法标记为输出场景`@MetaData`的描述。

[source, java, linenums]
----
@MetaDataOutputRetriever
    public MetaData getMetaDataOutputRestImplCategory(MetaDataKey key) throws Exception {
        checkProperConnectorInjection();
        return new DefaultMetaData(resolveOutputMetaDataModel(key));
----
| `@MetaDataRetriever` a |用`@MetaDataRetriever`注释的方法描述接收到的元数据关键参数的元数据。

使用`@MetaDataKeyRetriever`检索到的元数据键列表来检索每个实体类型的实体组成。

[source, java, linenums]
----
@MetaDataRetriever
public MetaData getMetadata(MetaDataKey key) {  }
----
| `@MetaDataScope` a |

[source, java, linenums]
----
@MetaDataScope(DefaultCategory.class)
@Connector(name = "my-connector", minMuleVersion = "3.5")
public class MyConnector {
...
}
----
| `@NoMetaData`  |标记`@Processor`以避免使用`@MetaDataRetriever`和`@MetaDataKeyRetriever`机制发现元数据。
| `@Query` a |支持通过DataSense查询语言（DSQL）轻松构建查询。在`@Connector`范围内定义`@Query`。

[source, java, linenums]
----
@Processor
public void setQuery(@Query DsglQuery query) {
...
}
----
| `@QueryPart`  |用于高级`@Query`方案。
| `@QueryTranslator` a |将DSQL查询转换为本地查询。

[source, java, linenums]
----
@QueryTranslator
public String toNativeQuery(DsqlQuery query){
    SimpleSyntaxVisitor visitor = new SimpleSyntaxVisitor();
    query.accept(visitor);
    return visitor.dsqlQuery();
}
----
|===

== 显示

[%header%autowidth.spread]
|===
| {注解{1}}说明
| `@FriendlyName` a |为注释元素提供简短的名称。如果未指定值，则从注释元素的名称中推断出该名称。

[source, java, linenums]
----
@FriendlyName("Consumer Key")
private String consumerKey;
 
 
// Alternate: Declare in a method’s arguments:
  public abstract String getByTypeAndName(
    @RestQueryParam("name") @FriendlyName("name") String uname)
            throws IOException;
----
| `@Password` a |将字段或方法参数标识为密码，或者更一般地将其作为包含无法显示为纯文本的数据的变量。

[source, java, linenums]
----
@Connect
public void connect(@ConnectionKey String username, 
  @Password String password)
        throws ConnectionException
----
| `@Path` a |将字段或方法参数标识为文件的路径。这会在Studio中显示一个窗口，从文件系统中选择一个文件。

[source, java, linenums]
----
@Configurable
    @Path
    String path;
----
| `@Placement` a |定义Anypoint Studio配置中可配置属性的位置。

[source, java, linenums]
----
@Configurable
@Placement(group = "Basic Settings", order = 1)
private String consumerKey;
----
| `@Summary` a |将显示信息添加到字段或参数。

[source, java, linenums]
----
@Processor
@Summary("This processor puts an animal in the barn")
public String putInBarn(String animal)
----
| `@Text` a |将参数标识为大型文本输入。此标记会为模式生成生成子元素而不是属性，但它也会在Anypoint Studio对话框生成中使用文本区域而不是文本字段。
|===

== 生命周期

您可以使用这些注释标记`org.mule.lifecycle`事件发生时的方法。

[%header%autowidth.spread]
|===
| {注解{1}}说明
| `@Start` a |在方法的`org.mule.lifecycle`中标记要启动的方法。可启动阶段。 *Note:* `start`是一个保留字，不能用作方法的名称。

[source, java, linenums]
----
@Start
public void mystart() {
    this.sessionId = serviceProvider.login(username, password);
}
----
| `@Stop` a |标记在方法`org.mule.lifecycle`期间停止的方法。可停止阶段。 *Note:* `stop`是一个保留字，不能用作方法的名称。

[source, java, linenums]
----
@Stop
public void mystop() {
    if ( this.sessionId != null ) {
        serviceProvider.logout(sessionId);
    }
}
----
| `@Initialise` a |在方法`org.mule.lifecycle`中标记要初始化的方法。初始化阶段。 *Note:* `initialise`是一个保留字，不能用作方法的名称。

[source, java, linenums]
----
@Initialise
public void initialize() {
    if ( this.sessionId != null ) {
        serviceProvider.initialise(sessionId);
    }
}
----
| `@Dispose` a |标记在方法`org.mule.lifecycle`中处理的方法。一次性使用阶段。 *Note:* `dispose`是一个保留字，不能用作方法的名称。

[source, java, linenums]
----
@Dispose
public void mydispose()  {
    if ( this.sessionId != null ) {
        serviceProvider.dispose(sessionId);
    }
}
----
|===

== 的OAuth

有关详情，请参阅 link:/anypoint-connector-devkit/v/3.5/oauth-v1[OAuth V1]或 link:/anypoint-connector-devkit/v/3.5/oauth-v2[OAuth V2]。

[%header%autowidth.spread]
|===
| {注解{1}}说明
| `@OAuth` a |为使用OAuth 1.0a协议进行身份验证的连接器进行注释。

[source, java, linenums]
----
@Connector(name = "myconnector", friendlyName = "MyConnector")
@OAuth(requestTokenUrl = "https://example.com/uas/oauth/requestToken",
accessTokenUrl = "https://example.com/uas/oauth/accessToken",
authorizationUrl = "https://example.com/uas/oauth/authorize")
public class MyConnector { ... }
----
| `@OAuth2` a |注释使用OAuth 2协议进行认证的连接器。

[source, java, linenums]
----
@Connector(name = "oauth2connector")
@OAuth2(authorizationUrl = "http://example.com", accessTokenUrl = "http://example.com")
public class MyConnector { ... }
----
| `@OAuthAccessToken` a |持有访问令牌。当调用`@Processor`方法时，如果资源所有者已授权使用者，则设置OAuth访问令牌;否则该方法不会被调用，并且资源所有者被重定向到授权URL。

[source, java, linenums]
----
@Processor
public Object accessProtectedResource(@OAuthAccessToken String accessToken, ...)
{ ... }
----

要么：

[source, java, linenums]
----
@OAuthAccessToken private String accessToken;
----
| `@OAuthAccessTokenIdentifier` a |将方法标记为负责识别访问令牌的用户。该方法由连接器的访问令牌管理器调用。该标识被用作存储访问令牌的关键。

[source, java, linenums]
----
@OAuthAccessTokenIdentifier
public String getUserId() {
return api.getUserId(myAccessToken);
}
----
| `@OAuthAccessTokenSecret` a |持有访问令牌密码。

[source, java, linenums]
----
@OAuthAccessTokenSecret private String accessTokenSecret;
----
| @ `OAuthAuthorizationParameter` a |附加授权参数以授权URL。

[source, java, linenums]
----
@OAuthAccessTokenSecret private String accessTokenSecret;
----
| `@OAuthAuthorizationParameter` a |追加授权参数以授权URL。

[source, java, linenums]
----
@OAuthAuthorizationParameter(name = "xxx", type = xxx, description = "xxx")
----
| `@OAuthCallbackParameter` a |标识表示服务OAuth响应中每个参数的模块属性。

[source, java, linenums]
----
@OAuthCallbackParameter(expression = "#[json:instance_url]")
private String instanceId;
----
| `@OAuthConsumerKey` a |持有OAuth使用者密钥。该字段必须包含由服务提供商提供并在OAuth规范中描述的OAuth使用者密钥。

[source, java, linenums]
----
@Configurable @OAuthConsumerKey private String consumerKey; 
----
| `@OAuthConsumerSecret` a |持有OAuth消费者密钥。该字段必须包含由服务提供商提供并在OAuth规范中描述的OAuth使用者密钥。

[source, java, linenums]
----
@Configurable @OAuthConsumerSecret private String consumerSecret; 
----
| `@OAuthInvalidateAccessTokenOn` a |标记一个自动刷新令牌的方法。

*Note*：此注释已被弃用。改用`@ReconnectOn`。

[source, java, linenums]
----
@Processor
@OAuthInvalidateAccessTokenOn(exception = RuntimeException.class)
public void processor() { ... }
----
| `@OAuthPostAuthorization` a |在OAuth内部标记一个方法，因为负责设置连接器_after_ OAuth完成。

[source, java, linenums]
----
@OAuthPostAuthorization
    public void postAuthorize() throws ConnectionException, MalformedURLException, AsyncApiException { ... }
----
| `@OAuthProtected` a |将连接器内的方法标记为需要OAuth访问令牌。当连接器未被授权时，这种方法无法执行。因此，迫使OAuth首先发生。

[source, java, linenums]
----
@OAuthProtected
@Processor
    public void logInfo() {
        logger.info(String.format("OAuthAccessToken=%s", getAccessToken()));
        logger.info(String.format("OAuthAccessTokenSecret=%s", getAccessTokenSecret()));
    }
----
| `@OAuthScope` a |表示对受保护资源的访问权限必须限制在范围内。用`@OAuthScope`注释的字段必须存在，并包含一个指示所需范围的字符串。

[source, java, linenums]
----
@Configurable
    @OAuthScope
    @Optional
    @Default("")
    private String scope; 
----
|===

== 参数

[%header%autowidth.spread]
|===
| {注解{1}}说明
| `@ConnectionKey` a |将连接方法内的参数标记为连接器查找的关键字的一部分。这只能用作`@Connect`方法的一部分。

[source, java, linenums]
----
@Connect(strategy=ConnectStrategy.SINGLE_INSTANCE)
    public void connect(@ConnectionKey String username, @Password String password)
        throws ConnectionException { … }
----
| `@Default` a |为`@Configurable`字段或`@Processer`或`@Source`参数指定默认值。

[source, java, linenums]
----
@Configurable
@Default("mule")
private String type;
----

要么：

[source, java, linenums]
----
@Processor
public abstract String listAnimals(@Default("mule") String type) throws IOException;
----
| `@Email`  |指定默认的电子邮件模式。
| `@ExceptionPayload` a |指定异常的有效负载。

[source, java, linenums]
----
@Processor
    public Object returnExceptionPayload(@ExceptionPayload Object payload) {
        return payload;
    }
----
| `@MetaDataStaticKey` a |定义注释值的具体MetaData类型。当应用于处理器时，它会影响（默认情况下）输出，否则会影响字段参数。

[source, java, linenums]
----
@Processor
    @MetaDataStaticKey(type = "CLIENT")
    public Map<String, Object> getClient(String id) {
        return createClientObject();
    }
----
| `@Optional` a |将`@Configurable`字段或`@Processor`或`@Source`参数标记为可选。

[source, java, linenums]
----
@Configurable
@Optional
String path;
----
| `@RefOnly` a |将`@Configurable`字段或`@Processor`或`@Source`参数标记为仅通过引用传递。
|===

== 休息

[%header%autowidth.spread]
|===
| {注解{1}}说明
| `@BinaryParam`  |指定有效负载是否为二进制类型。
| `@RestCall` a |指示调用时，处理器发出RESTful请求。

[source, java, linenums]
----
@Processor
@RestCall(uri = "{url}/list", method = org.mule.api.annotations.rest.HttpMethod.GET)
    public abstract String showAll() throws IOException; 
----
| `@RestExceptionOn` a |根据指定的条件抛出异常

[source, java, linenums]
----
@Processor
@RestCall(uri = "{url}/animals", method = HttpMethod.GET, exceptions = {@RestExceptionOn(expression="#[message.inboundProperties['http.status'] != 200]", exception = AnimalNotFoundException.class)})
    public abstract List<Animal> listAnimals(@RestQueryParam("type") String type) throws IOException; 
----
| `@RestHeaderParam` a |允许您在呼叫中插入自定义标题。

[source, java, linenums]
----
@Processor
@RestCall(uri = "{url}/create", method = org.mule.api.annotations.rest.HttpMethod.POST)
  public abstract String create( @RestHeaderParam("age") 
    int age)
throws IOException; 
----
| `@RestHtppClient` a |标记HttpClient模块的注释使用。这样，您可以避免创建多个客户端，并有机会执行自己的调用或配置HttpClient以满足特殊需求：

[source, java, linenums]
----
@RestHttpClient
HttpClient client = new HttpClient();
----
| `@RestPostParam` a |允许您在POST方法调用的主体中设置参数。

[source, java, linenums]
----
@Processor
    @RestCall(uri = "{url}/form", method = HttpMethod.POST)
    public abstract String addAnimal(@RestPostParam("type") String type) throws IOException; 
----
| `@RestQueryParam` a |指定URI查询参数，这些参数被附加到URI的路径后面，或＆符号。

[source, java, linenums]
----
@Processor
    @RestCall(uri = "{url}/listName", method = org.mule.api.annotations.rest.HttpMethod.GET)
    public abstract String getByType(
            @RestQueryParam("type") String type)
            throws IOException; 
----
| `@RestTimeout` a |为剩余呼叫指定一个超时时间。此注释可附加到`@RestCall`，以便为剩余呼叫选择性指定超时（以毫秒为单位）。如果其余调用超过指定的时间，则会抛出RuntimeException，除非为超时指定了异常。

[source, java, linenums]
----
@Processor
  @RestTimeout(timeout = 1, exception = TimeoutException.class)
  @RestCall(uri = "{url}/list/timeout", method = HttpMethod.GET)
  public abstract String listAnimalsTimeout() throws IOException; 
----
| `@RestUriParam` a |允许您插入URI参数。

[source, java, linenums]
----
@Processor
    @RestCall(uri = "{url}/create/{type}", method = org.mule.api.annotations.rest.HttpMethod.POST)
    public abstract String create(@RestUriParam("type") String type)  throws IOException; 
----
|===
