= 连接器测试框架
:keywords: connector testing framework, ctf, devkit, mule, esb, runtime

== 概述

连接器测试框架（CTF）的目的是在尽可能多的部署场景下执行功能测试。该框架运行Mule应用程序"externally"，不受DevKit版本和连接器开发的Mule运行时的限制。

使用来自连接器根文件夹的简单Maven命令，您可以在*local profile*，*embedded runtime*或*available CloudHub runtime*版本中指定的运行时对连接器执行测试。

[NOTE]
图书馆在CloudHub上进行更改的事实增加了Mule运行时版本与基于DevKit的连接器之间*incompatibility*的潜力。

== 部署配置文件配置

将所需的连接器应用程序部署详细信息作为参数传递给单个Maven命令，指定要测试连接器的环境。所有参数都应为小写。

如果您未指定`-Ddeploymentprofile`，则CTF在嵌入模式下默认运行。

=== 嵌入式模式

仅指定`mvn clean test`将在_embedded_模式下运行功能测试，具体取决于DevKit版本。您不需要有Mule服务器以此模式运行应用程序。

运行`mvn clean test `与运行相同：

----
mvn clean test -Ddeploymentprofile=embedded
----

本地模式=== 

在本地模式下运行CTF意味着从用户配置文件中加载Mule应用程序部署规范并远程运行测试。要使用本地配置文件的运行时测试连接器，可以在`/local`文件夹中设置参数`-Ddeploymentprofile` *must*。例如，该命令的结构如下所示：
// todo：/ local中的任何地方，还是必须是/ local / usr /？

----
mvn clean test -Ddeploymentprofile= -Dmuledirectory=/local/usr/mule_3.6.3
----


===  CloudHub模式

从DevKit 3.9.0开始，CTF支持CloudHub部署配置文件，允许您在更动态的环境中测试连接器，这是在传统独立环境中部署Mule应用程序的明显优势。除了指定`-Ddeploymentprofile=cloudhub`外，两个必需参数是您的CloudHub用户名`-Dcloudhubuser=`和`-Dcloudhubpassword=`。

----
mvn clean test -Ddeploymentprofile=cloudhub -Dcloudhubuser=<your_username> -Dcloudhubpassword=<your_password>
----

== 可选参数

在CloudHub上进行测试时，您可以指定要在其上运行连接器测试的Mule版本，以及您的实例的CloudHub URL和CloudHub工作人员类型。请参阅下面的示例，其中包含所有必需的_and_可选参数：


[%header%autowidth.spread]
|===
|可选参数|说明
| `muleversion` | 配置要在CloudHub上使用的Mule运行时
| `cloudhuburl` | 提供更改CloudHub实例的功能，默认情况下，CTF部署到http://anypoint.mulesoft.com/cloudhub/
| `cloudhubworkertype`  | 允许您为要生成的Mule应用程序配置所需数量的vCores。可用的选项是：
`micro`（0.1vCores），
`small`（0.2vCores），`medium`（1vCore），`large`（2vCores），`xlarge`（4vCores）
// todo：检查每个参数是否正确地打印在上面
| `cloudhubtimeout` | 允许您配置部署Mule应用程序的CloudHub实例的超时
// todo：检查以上描述的准确性
|===

示例CTF测试命令：
----
mvn clean test -Ddeploymentprofile=cloudhub -Dcloudhubuser=<your_username> -Dcloudhubpassword=<your_password>
-Dmuleversion=3.7.2
-DcloudhubURL=http://qa.anypointplatform.mulesoft.com/cloudhub
-Dcloudhubworkertype=small
----

////
// ==故障排除


如果你的测试失败了怎么办
调试日志记录以显示更多信息。


== 日志记录

//当连接器有一个业务逻辑异常
// TODO：描述Mule中的日志以及如何访问CloudHub中的日志
////
== 另请参阅
有关使用Runtime Manager的更多信息，请参阅 link:/runtime-manager/deploying-to-cloudhub[部署到CloudHub]， link:/runtime-manager/deploying-to-your-own-servers[部署到您自己的服务器]和 link:/runtime-manager/managing-servers[管理云和内部应用程序和服务器]
