= 操作MUnit Maven插件

本节专门介绍如何使用插件运行测试。

== 从Maven运行MUnit测试

[source,console]
在项目示例中运行MUnit测试
----
mvn clean test
----

== 运行特定的MUnit测试套件

您可以指示MUnit Maven Plugin仅运行属于特定测试套件的测试。

为此，我们使用属性`munit.test`。

[source,console]
运行特定的MUnit测试套件示例
----
mvn clean test -Dmunit.test=<regex-test-suite>
----

属性`munit.test`接受正则表达式。该表达式应用于MUnit测试套件文件的名称。正则表达式语言是Java实现。 +
该路径相对于src / test / munit。

以下是一个有效的例子：
[source,console]
----
mvn clean test -Dmunit.test=.*my-test.*
----

您可以通过将命名约定添加到MUnit测试套件来利用此功能。

== 运行特定的MUnit测试

就像你指示MUnit运行一个测试套件一样，你也可以告诉它在该测试套件中运行一个特定的测试。为此，我们再次使用属性`munit.test`，并添加一个：

[source,console]
----
mvn clean test -Dmunit.test=<regex-test-suite>#<regex-test-name>
----

添加是特殊字符`#`。在它的右边你应该输入测试名称。它也接受正则表达式。该表达式应用于MUnit Test的属性`name`。

以下是一个有效的例子：
[source,console]
----
mvn clean test -Dmunit.test=.*my-test.*#.*test-scenario-1.*
----

[TIP]
--
MUnit Test Suite中与正则表达式不匹配的测试被标记为*ignored*。
--

== 使用特定标记运行测试

您可以选择仅运行您在一个特定标记下分组的测试。

[source,console]
----
mvn clean test -Dmunit.tags=<munit-tag>
----

== 跳过所有测试

在构建应用程序时，您可能想要阻止测试运行。 MUnit使用与Maven相同的机制，因此如果您想跳过测试，可以使用参数`skipTests`。

[source,console]
。滑雪测试示例
----
mvn clean package -DskipTests
----

== 仅跳过MUnit测试

MUnit还附带了另一个仅阻止MUnit测试运行的属性。
同时允许任何其他测试（如JUnit测试）继续运行。

如果您只想跳过MUnit测试，则可以使用参数`skipMunitTests`。

[source,console]
.Skipping MUnit测试示例
----
mvn clean package -DskipMunitTests
----

提示：属性`skipMunitTests`仅适用于基于XML的MUnit测试。

== 另请参阅

*  link:/munit/v/2.0/faq-how-to-read-munit-test-results[FAQ：如何阅读MUnit测试结果]
