= 设置事件处理器
：版本信息：2.0和更新
:keywords: munit, testing, unit testing

Set Event Processor允许你定义一个Mule事件。 +
该消息处理器通常在MUnit测试开始时使用，以定义要发送到正在测试的流的第一条消息。

下面的例子显示了如何定义Mule消息的简单有效载荷：

[source,xml,linenums]
----
<munit:set-event cloneOriginalEvent="false">
  <munit:payload value="#['payload_value']" mediaType="text/plain" encoding="UTF-8"/>
</munit:set-event>
----

set-event具有cloneOriginalEvent属性。如果设置为true，它会克隆由代码生成的事件。 +
默认情况下，此属性的值为false。

Set Event处理器中的有效载荷元素具有以下属性：

[%header%autowidth.spread]
|===
|属性名称 |描述

| `value`
|定义有效负载消息的值。

| `encoding`
|定义消息的编码。该属性是可选的。

| `mediaType`
|定义消息的MIME类型。该属性是可选的。

|===

您还可以使用Set Event处理器来定义消息属性和事件变量：

[source,xml,linenums]
----
<munit:set-event cloneOriginalEvent="false">
  <munit:payload value="#['payload_value']" mediaType="text/plain" encoding="UTF-8"/>

  <munit:attributes value="attribute_value" />

	<munit:variables>
	  <munit:variable key="variable_key" value="variable_value" mediaType="text/plain" encoding="UTF-8"/>
	</munit:variables>
</munit:set-event>
----

所有属性都具有相同的一组属性：

[%header%autowidth.spread]
。属性消息处理器的属性
|===
|属性名称 |描述

| `key`
|设置属性的关键。

| `value`
|属性的内容。

| `encoding`
|定义消息的编码。该属性是可选的。

| `mediaType`
|定义消息的MIME类型。该属性是可选的。

|===

您可以根据您的测试需要为每个范围定义多个属性。

[WARNING]
--
如果您使用_same_键在同一范围内定义两个属性，请注意最终会覆盖另一个属性。
--

== 另请参阅

*  link:/munit/v/2.0/assertion-message-processor[关于声明该事件处理器]
*  link:/munit/v/2.0/fail-event-processor[关于失败事件处理器]
*  link:/munit/v/2.0/run-custom-event-processor[关于运行自定义事件处理器]
*  link:/munit/v/2.0/mock-message-processor[关于模拟事件处理器]
*  link:/munit/v/2.0/verify-message-processor[关于验证事件处理器]
