=  SLA层级参考
:keywords: sla, policy, deprecate, delete, define, edit

服务级别访问（SLA）层是您为API定义的用户访问类别。层定义与基于SLA的策略相结合，可确定在某个级别访问API是否需要您的批准。层定义还可以限制应用程序对API的请求数量。要强制执行SLA层，您需要应用基于SLA的速率限制或限制策略。

要为API版本定义SLA层或管理请求访问特定层的应用程序，您需要设置API URL。

您可以监控SLA性能，以确保您的API与批准用于API的SLA层一致。

== 定义一个层

当您定义一个层时，您可以命名层并定义限制，例如调用应用程序可以创建的请求数。您还可以指出是否应该自动批准此层级的应用程序访问请求或需要人工批准。

在API版本详细信息页面上的SLA层上，将显示SLA层定义的摘要，显示该层上注册了多少个应用程序以及其他信息，层名称，限制，状态和所需的审批类型。

您可以使用提供的控件编辑和删除层。

=== 分层的SLA

API Manager支持多种SLA限制。

您可以为单个SLA层设置多个吞吐量限制。名为_gold_的单个SLA层可将请求限制为每秒100次，并将请求限制为每天10,000次。此技术可确保在_gold_层上注册的应用程序不会超过每秒100个请求的突发限制。应用程序不会压倒API，注册的应用程序每天可获得预期的10,000个请求。在SLA上设置Visible标志隐藏了应用程序开发人员在注册时的第一个限制。如果您只定义一个限制，则无法隐藏它。

==== 响应标题

请求响应中包含三个标头，通知用户有关SLA限制和SLA允许的剩余容量。当此SLA强制执行限制请求吞吐量的多个策略时，一组标题会报告备用容量，仅参考最严格的策略。

例如，您的API的用户可能会收到包含这些标头的响应：
----
X-RateLimit-Limit: 20
X-RateLimit-Remaining: 14
X-RateLimit-Reset: 19100
----
在这种情况下，响应告诉用户在接下来的19100毫秒内，SLA允许只有14个请求被允许，在此时间窗口内设置为20。


== 强制一个层

要强制执行SLA层，您需要应用基于SLA的速率限制或限制策略。这些策略要求所有使用API​​的应用程序注册访问特定层，然后将其客户端凭据传递给API，以便Anypoint Platform能够识别它们，将它们与其合同层相关联，并强制执行吞吐量限制。

== 编辑层

如果您编辑已经批准使用该层的应用程序的层，则这些应用程序会立即保留到编辑层的条款中。因此，如果您更改吞吐量值而没有发出警告，则可能会给API用户带来不便。

如果您最初将该层设置为需要人工批准，并将其更改为允许自动批准，则API Manager将授予任何待批准的批准请求。

== 管理应用程序

为API定义SLA后，您可以通过Exchange门户批准或撤消应用开发者的访问请求。此操作将应用程序的使用绑定到SLA。如果开发人员请求在比您想要批准更高的SLA层访问您的API，则可以通过应用另一个SLA层来覆盖请求。

如果您为手动批准设置层，则当开发人员请求访问其应用程序时，会向您发送电子邮件通知。您可以查看API版本详细信息页面上的应用程序，并批准，拒绝或撤销请求。如果开发人员要求更改层次，则还可以查看更改请求并批准新层次的应用程序或拒绝更改请求。

== 弃用和删除层

将应用程序分配到SLA层后，您可以选择弃用层以阻止开发人员注册该层的新应用程序。您无法删除分配有应用程序的SLA层。

要弃用和删除一个层，首先创建一个新层，并通知应用程序所有者您创建的新层名称。接下来，撤销应用程序对现有已弃用层的访问权限。请应用程序所有者使用新层重新请求访问API。最后，在所有应用程序所有者注册一个新层并且您批准他们迁移到新层之后，您可以删除已弃用的层。

== 另请参阅

*  link:/anypoint-exchange/to-request-access[请求访问API]
*  link:/anypoint-exchange/about-portals[交换门户]
*  link:/api-manager/v/2.x/rate-limiting-and-throttling-sla-based-policies[限速和限制政策]
