=  OAuth 2.0访问令牌策略
:keywords: oauth, raml, token, validation, policy

要使用OAuth在Anypoint Platform中保护API，建议使用以下策略之一以及匹配的OAuth提供程序。

*  OpenAM OAuth令牌执行策略
Ping * 平台OAuth令牌执行策略
*  OpenID Connect访问令牌执行策略

您需要设置OpenAM，PingFederate或符合动态客户端注册的身份提供商以使用推荐的策略。如果由于某种原因，您不能使用推荐的提供商，请使用使用外部提供商政策的OAuth 2.0访问令牌实施。您必须使用Mule提供者。

没有任何令牌执行策略可以与Mule客户端应用程序一起访问Anypoint平台之外的受OAuth 2.0保护的资源。您需要为此配置HTTP请求者连接器。

您应用于Anypoint Platform中的API的授权实施策略连接到OpenAM授权服务器，PingFederate授权服务器，OpenID Connect令牌自检端点或自定义OAuth 2.0提供程序。

*Important:*要使用OAuth 2.0访问令牌实施使用外部提供商政策，您需要Mule OAuth 2.0提供商提供访问令牌。您无法使用任何其他OAuth 2.0提供商，例如Facebook，Google或Azure。

与其他API Manager执行的策略一样，API也需要在API Manager中注册才能应用和使用任何OAuth 2.0访问令牌策略。

== 先决条件

* 您是Anypoint Platform组织管理员，或者有权在环境中创建或管理API。
* 您可以使用OpenAM，OpenID Connect或PingFederate将您的Anypoint Platform组织设置为联合组织。请参阅以下链接。或者，您已经配置并运行了Mule OAuth 2.0提供程序。


== 另请参阅


*  link:/mule-user-guide/v/3.8/authentication-in-http-requests[HTTP请求者连接器]
*  link:/api-manager/v/2.x/aes-oauth-faq[OAuth 2.0提供商]
*  link:/api-manager/v/2.x/openam-oauth-token-enforcement-policy[OpenAM OAuth令牌执行]
*  link:/api-manager/v/2.x/openam-oauth-token-enforcement-policy[OpenID Connect OAuth令牌执行]
*  link:/api-manager/v/2.x/openam-oauth-token-enforcement-policy[PingFederate OAuth令牌执行]
*  link:/access-management/managing-api-clients[关于联合用户和OpenID Connect内省端点的客户端管理]


