=  HTTP策略转换扩展参考

在Mule 4.1.0及更高版本中，可以在策略中使用HTTP策略转换扩展。这个扩展简化了对HTTP请求和响应的修改
 通过不同的政策。

== 操作

- 添加标题

- 删除标题

- 设置响应

- 设置请求

=== 添加标题

该操作的工作方式取决于其与Mule消息的相关性：

* 相关：在HTTP侦听器和请求者的请求和响应中添加标头。
* 不相关：使用指定的标题创建新的请求/响应。

例如，如果指定的outputType为`response`，则操作和Mule消息不相关，但Mule消息包含HTTP请求。当该操作执行时，它将覆盖整个值，并使用指定的标题创建新的响应。如果Mule消息包含HTTP响应，它只是将头添加到请求中。

==== 参数

*  `outputType`
+
有效值为`response`，`request`，`requester-request`。定义属性的类型
 操作的回应。它的值取决于被调用的操作在哪里，如下所示：
+
** 从源策略中调用`execute-next`之前，`request`应该是值。
** 从源策略中调用`execute-next`之后，`response`应该是值。
** 从操作策略中，在`execute-next`被调用之前，`requester-request`应该是值。
** 从操作策略中，在`execute-next`被调用之后，`response`应该是值。
+
*  `headers`
+
一个DataWeave表达式，解析为要添加到当前消息属性的标题的映射
+
*Example*
+
----
<http-transform:add-headers outputType="response">
    <http-transform:headers>#[
        {
            'FirstHeader': 'FirstHeaderValue',
            'SecondHeader': 'SecondHeaderValue',
            'ThirdHeader': 'ThirdHeaderValue'
        }
    ]</http-transform:headers>
</http-transform:add-headers>
----

=== 删除标题

此操作将从HTTP侦听器和请求者的请求和响应中删除标头。返回的属性总是与输入属性的类型相同。此操作不区分大小写。

==== 参数

*  `headers`
+
数据编织表达式，解析为要删除的标题名称数组。
+
*Example*
+
----
<http-transform:remove-headers>
    <http-transform:headers>#[['FirstHeader', 'SecondHeader']]</http-transform:headers>
</http-transform:remove-headers>
----

=== 设置响应

该操作设置完整的HTTP响应。你使用这个操作的时候
策略阻止流程执行;因此，没有HTTP响应。

==== 参数

*  `statusCode`：表示响应的HTTP状态码的整数。

*  `reasonPhrase`：表示响应的HTTP原因短语的字符串。

*  `body`：HTTP响应的内容。

* 标头：解析为HTTP响应标头地图的DataWeave表达式
+
*Example*
+
----
<http-transform:set-response statusCode="203" reasonPhrase="policyReasonPhrase">
    <http-transform:body>#['policyPayload']</http-transform:body>
    <http-transform:headers>#[
        {
            'FirstHeader': 'FirstHeaderValue',
            'SecondHeader': 'SecondHeaderValue',
            'ThirdHeader': 'ThirdHeaderValue'
        }
    ]</http-transform:headers>
</http-transform:set-response>
----

=== 设置请求

此操作设置HTTP请求者执行的完整HTTP请求。

==== 参数

*  `requestPath`：发送HTTP请求的路径。

*  `body`：HTTP请求的内容。

*  `headers`：解析为HTTP请求标头地图的DataWeave表达式。

*  `uriParams`：解析为HTTP请求的URI参数映射的DataWeave表达式。

*  `queryParams`：解析为HTTP请求的查询参数映射的DataWeave表达式。
+
*Example*
+
----
<http-transform:set-requester-request requestPath="/backend/policy/{policyUriParam}">
    <http-transform:body>#['policyPayload']</http-transform:body>
    <http-transform:headers>#[
        {
            'FirstHeader': 'FirstHeaderValue',
            'SecondHeader': 'SecondHeaderValue',
            'ThirdHeader': 'ThirdHeaderValue'
        }
    ]</http-transform:headers>
    <http-transform:uri-params>#[
        {
            'FirstUriParam': 'FirstUriParamValue',
            'SecondUriParam': 'SecondUriParamValue'
        }
    ]</http-transform:uri-params>
    <http-transform:query-params>#[
        {
            'FirstQueryParam': 'FirstQueryParamValue',
            'SecondQueryParam': 'SecondQueryParamValue'
        }
    ]</http-transform:query-params>
</http-transform:set-requester-request>
----
