= 关于政策包装，范围和规模

一项政策包含以下内容：

* 一个YAML文件
+
定义策略的可配置参数。由UI呈现以显示策略的输入。
+
* 一个XML模板
+
包含策略的实施。
* 模板的POM
+
定义策略依赖关系。包装类型需要为`mule-policy`。
* 资源
+
或者，如果策略依赖于其他资源（如证书），则将资源定义为策略的一部分。
+
*  mule-artifact.json描述符
+
将分类符指定为`mule-policy`。

有关更多信息，请参阅标题策略。

== 政策范围

政策与应用程序和其他政策是分开的，但是有办法公开某项政策的信息。有关策略的身份验证信息可以在安全上下文主体对象中传播。

策略可以修改消息内容。在Mule 4.1.0和更高版本中，如果邮件在`source`策略中的`execute-next`之前被修改
或者在`operation`策略之后，这些修改默认情况下不会传播。启用这些修改的传播
您可以在每个策略中启用`propagateMessageTransformations`标志。

*Example*

----
<http-policy:proxy name="scope-payload">
    <http-policy:source propagateMessageTransformations="true">

        <http-policy:execute-next/>

    </http-policy:source>
    <http-policy:operation propagateMessageTransformations="true">

        <http-policy:execute-next/>

    </http-policy:operation>
</http-policy:proxy>
----

策略可以通过不定义`execute-next`或确保未到达（例如将其置于选项中）来避免流的执行。

在政策上设置的变量只有政策的范围。另外，流中定义的变量在策略中不可见。

== 策略大小

策略的大小取决于其相关性。 Mule Runtime第一次轮询政策时，需要更长时间才能获取它们。但是，检索策略后，它们会缓存在文件系统上。这确保了离线可用性，并减少了获取策略的延迟。

== 另请参阅

*  link:/api-manager/v/2.x/add-remove-headers-latest-task[添加请求/响应头，删除请求/响应头]
*  link:/api-manager/v/2.x/policies-4-concept[关于政策]
