= 关于MuleSoft连接器认证计划指南
:keywords: connector, certification, sdk, program guidelines

本文档涉及Mule 4的连接器认证。有关Mule 3认证，请参阅 link:https://docs.mulesoft.com/anypoint-connector-devkit/v/3.9/connector-certification-program-guidelines[DevKit文档]。

MuleSoft的连接器认证计划将指导您完成创建可供MuleSoft认证的企业级连接器的过程。通过认证后，该连接器便可通过Anypoint Exchange供客户和开发人员查找和使用。

== 开始之前

在开始认证计划之前，请考虑以下事项并确保您可以遵守这些要求：

* 连接器必须保持最新且安全，并且必须每年至少重新获得一次认证。
* 必须为企业版的MuleSoft软件或MuleSoft服务构建并分发连接器。
* 连接器的所有交易必须在客户和合作伙伴之间进行，而不是通过MuleSoft。
* 连接器必须是一个功能齐全，生产就绪的企业级应用程序和协议连接器。也就是说，它是连接Mule与外部系统的连接器。
* 代码必须准备好部署到持续集成环境中。代码应该可以从命令行编译而不需要导入私有存储库。证书应该单独提供，并且能够在编译时进行设置。另外，认证需要连接器的沙箱凭证。
* 连接器只能使用开源或由您拥有的第三方库。没有第三方，不可分发的图书馆被接受。
* 如果Anypoint Exchange上已经存在类似的连接器，如果它提供了优于现有连接器的附加功能，仍然可以提交连接器。

== 提供支持

合作伙伴或开发人员需要为Anypoint Exchange上的每个连接器提供完全支持。对于MuleSoft收到的支持查询，MuleSoft直接向客户提供商业合理水平的第一层电话，网络和/或电子邮件支持。 MuleSoft需要并解决与商业MuleSoft产品有关的任何问题。任何特定于合作伙伴连接器的问题都会升级到合作伙伴。

* 合作伙伴在一个工作日内响应MuleSoft升级的所有支持查询。
* 合作伙伴尽最大努力在五个工作日内为客户解决技术支持问题。

您的连接器的== 定价

合作伙伴或开发人员可自行决定是否免费或收取您的连接器。但是，所有连接器必须在Anypoint Studio内免费提供。虽然不是强制性的，但我们建议客户试用一下连接器进行设计和部署。

有关更多信息，请参阅下面的<<see_also, Custom Module License>>链接。

[%header,cols="20a,80a"]
|===
| {类别{1}}详细说明
| 免费 |连接器可通过Anypoint Exchange免费下载和使用给客户。
| 付费 |付费连接器可在设计时在Anypoint Studio中用于Mule应用程序。在部署中，连接器无法在没有许可证的情况下运行。客户需要直接从合作伙伴购买连接器，并且应该使用由MuleSoft提供的生成许可证密钥来管理付费连接器的使用。连接器的价格由合作伙伴决定。
|===

== 许可条款

在`LICENSE.md`的许可条款之前添加以下法律条款：
****
*About MuleSoft Certified Connectors*

MuleSoft认证连接器由MuleSoft的合作伙伴和开发人员社区开发。这些连接器已经由MuleSoft审查和认证。要购买连接器名称连接器（如果需要）或者获得帮助或支持，请直接在_Contact Information_上联系_Partner Name_。 MuleSoft放弃MuleSoft认证连接器的任何支持义务。

通过安装此连接器，您同意MuleSoft与该连接器的开发人员共享您的联系信息，以便您可以直接从开发人员那里获得关于它的更多信息。

_您自己的许可条款._
****

== 导出合规性

****
除非经美国法律授权，否则您不得使用或以其他方式导出或再出口从MuleSoft或您的资料（包括但不限于合作伙伴文档和合作伙伴连接器）收到的MuleSoft机密信息或MuleSoft文档。特别是，但不限于，MuleSoft机密信息，MuleSoft文档和您的资料不得出口或再出口（a）进入任何美国禁运国家或（b）美国财政部特别指定国民名单上的任何人或美国商务部否认个人名单或实体名单。
您声明并保证您不在任何此类国家或任何此类列表中。您同意您不会为了美国法律禁止的任何目的使用或再出口任何MuleSoft机密信息或MuleSoft文档及您的材料，包括但不限于开发，设计，制造或生产核，化学或生物武器。

您须自行负责确保您通过Anypoint Exchange向用户提供材料，并遵守相关司法辖区内有关技术出口和进口的所有法规。 （大写术语应与“认证连接器合作伙伴协议”中的定义相同。）
****

== 开发和认证

告诉MuleSoft关于你想开发的连接器，并通过联系mailto：isv@mulesoft.com [MuleSoft]来获得认证。 MuleSoft会与您联系并提供更多信息。

[[see_also]]
== 另请参阅

*  link:certification-guidelines-for-connectors[连接器认证技术指南]
*  link:license#custom-module-license[自定义模块许可]
*  https://forums.mulesoft.com [MuleSoft论坛]
*  mailto：isv@mulesoft.com [联系MuleSoft]
