=  Anypoint合作伙伴管理器API

:keywords: Anypoint Partner Manager API, Partner Manager Query Language, PMQL

客户通常希望与Anypoint Partner Manager（APM）进行交互，
以编程方式自动执行其处理任务。
APM有两种不同的客户可以调用的API：

*  *Trading Partner Management Service API*（TPM服务API） - 管理与合作伙伴相关的配置，例如文档定义。 +
*Download URL:*
https://anypoint.mulesoft.com/b2b/tpm/api/definition/api.raml +
*Experiment URL:* https://anypoint.mulesoft.com/b2b/tpm/api/console/index.html
*  *Tracker API*  - 使您可以访问运行时数据，如事务和业务文档。 +
*Download URL:*
https://anypoint.mulesoft.com/b2b/tracker/api/definition/api.raml +
*Experiment URL:*
https://anypoint.mulesoft.com/b2b/tracker/api/console/index.html

== 合作伙伴经理查询语言

具有_Searchable_特征的资源可以通过*q*查询参数进行查询
使用合作伙伴管理器查询语言（PMQL）。 PMQL是一种类似于SQL的语言
通过资源ID以外的字段搜索资源的能力。在深入语法之前，
这里有一些在PMQL中表达的查询的例子：

[source]
name =='AS2 Receive'

[source]
documentPropertyValue = like ='MuleSoft％'

[source]
processedAt''2016-04-29 00:00:00'and processedAt <='2016-04-29 00:00:01'

[source]
standard = in =（'X12'，'EDIFACT'）和（direction =='INBOUND'or messageType =='PO'）and processedAt> ='2016-01-01 00:00:00'

PMQL表达式由一个或多个比较组成，彼此之间通过逻辑运算符相关：

* 逻辑与：`and`
* 逻辑或：`or`

默认情况下，AND运算符优先，也就是说，
它在任何OR操作符之前被评估。
但是，可以使用括号表达式来改变优先级，
产生任何包含的表达式产量。

比较由选择器，运算符和参数组成：

[source]
比较=选择器，比较运算符，参数

==  PMQL选择器

选择器标识要过滤的资源表示的字段。有可能
任何不包含保留字符（见下文）或空格的非空Unicode字符串。

==  PMQL比较运算符

比较运算符可以是以下任何一种：

* 等于：`==`
* 不等于：`!=`
* 小于：`<`
* 小于或等于：`&lt;=`
* 大于运算符：`>`
* 大于或等于：`>=`
* 在：`=in=`
* 像：`=like=`

==  PMQL参数

参数可以是单个值，也可以是逗号分隔的多个值。
多个值只能用于支持类似参数类型的运算符
_IN_运算符。不包含任何保留字符或a的参数值
空格可以不加引号，其他参数必须用单引号或双引号括起来。
