= 查找表

Anypoint Partner Manager（APM）使您能够创建，填充和编辑_ link:https://docs.staging.modusbox.com/anypoint-b2b/glossary#sectl[查找表] _。查找表是通过关联值来促进事务处理的表格。例如，此页面显示如何创建将家庭伙伴产品代码与贸易伙伴产品代码关联的查找表。

== 创建查找表

您可以使用以下任一项创建查找表：

*  link:/anypoint-b2b/lookup-tables#creating-a-lookup-table[Anypoint Partner Manager用户界面]
*  link:/anypoint-b2b/anypoint-partner-manager-api[Anypoint Partner Manager API]。

本节介绍如何使用 link:https://curl.haxx.se/[卷曲]进行API调用以创建三列两键表。

=== 创建查找表

. 创建表格：
+
----
curl -X POST -d
'{
  "name": "ProductCodes"
 }' "https://anypoint.mulesoft.com/b2b/tpm/api/lookupTables?environmentId=yourEnvironmentId&apiKey=yourAPIKey"

----
+
该API返回一个表ID，您可以在后续调用中使用该表。

. 添加一个字段：
+
----

curl -X POST -d
'{
  "name": "InternalProductCode"
}' "http://anypoint.mulesoft.com/b2b/tpm/api/lookupTables/yourTableId/fields?environmentId=yourEnvironmentId&apiKey=yourAPIKey"
----
+
该API返回该字段的ID。

. 使用相同的语法添加两个字段：
+
----
curl -X POST -d
'{
  "name": "PartnerName"
}' "http://anypoint.mulesoft.com/b2b/tpm/api/lookupTables/yourTableId/fields?environmentId=yourEnvironmentId&apiKey=yourAPIKey"
----
+
----
curl -X POST -d
'{
  "name": "PartnerProductCode"
}' "http://anypoint.mulesoft.com/b2b/tpm/api/lookupTables/yourTableId/fields?environmentId=yourEnvironmentId&apiKey=yourAPIKey"
----
+
API会为每个字段返回ID。

. 添加密钥（入站和出站）
+
*Inbound*
+
入站密钥是第一个和第二个字段的唯一组合。
+
-----
curl -X POST -H
 '{
  "name": "InboundProductCodes",
  "fieldIds": [
      "fieldId1",
      "fieldId2"
        ]
 }' "http://anypoint.mulesoft.com/b2b/tpm/api/lookupTables/yourTableId/keys?environmentId=yourEnvironmentId&apiKey=yourAPIKey"
-----
+
*Outbound*
+
入站密钥是第二个和第三个字段的唯一组合。
+
-----
curl -X POST -H
 '{
  "name": "InboundProductCodes",
  "fieldIds": [
      "fieldId2",
      "fieldId3
        ]
 }' "http://anypoint.mulesoft.com/b2b/tpm/api/lookupTables/yourTableId/keys?environmentId=yourEnvironmentId&apiKey=yourAPIKey"
-----
. 使用Anypoint Partner Manager填充表格（请参阅<<Add a Row to a Table>>）。

. 查询API以合并表格数据：
+
----
curl -X GET -H  "http://anypoint.mulesoft.com/b2b/tpm/api/lookupTables/lookup?key=OutboundProductCodes&lookupTable=ProductCodes&fields=InternalProductCode:Int1001%26PartnerName:Beta&environmentId=yourEnvironmentId1&apiKey=yourAPIKey"
----
+
注意：要从Mule流中查询查找表，请参阅 link:/mule-user-guide/v/3.8/consuming-a-rest-api[使用REST API]。


== 使用查找表

在创建查找表后，您可以使用Anypoint Partner Manager用户界面来：

* 筛选现有表
* 向表中添加一行
* 编辑一个表格行
* 删除表格行

有关更多信息，请参阅 link:/anypoint-b2b/lookup-tables#working-with-a-lookup-table[使用查找表]。
