= 配置队列

队列是Mule在异步消息处理期间用来存储对象的结构。当消息在异步消息进程开始时进入接收者时，接收者将消息存储在队列中，直到它可以被线程池中的线程处理。一旦将消息放入队列中，接收方就可以立即返回并接受新的传入消息。接收者不必等待消息在接受新的传入消息之前进一步处理，所以实质上，队列启用Mule中的异步处理。

请注意，企业版Mule ESB的用户可以使用管理控制台来监控队列，并获得他们所包含消息数量的历史信息。有关详情，请参阅 link:/mule-management-console/v/3.4[使用Mule管理控制台]。

== 骡队如何使用队列

Mule使用排队/异步流和VM传输的队列。

=== 如何在VM传输中使用队列

默认情况下，Mule在使用VM传输的消息的异步处理中使用队列。 VM传输可用于流，其中所有消息处理都在运行Mule实例的JVM中完成。

当请求进入使用VM传输的流的接收器时，它们将存储在队列中，直到线程池中的线程可以接收并处理它们。接收器线程然后被释放回接收器线程池，以便它可以携带另一个传入消息。在队列中等待的每条消息都可以从线程池中分配一个不同的线程。

=== 非持久性和持久性队列

队列可以是非持久性的或持久性的。内存中维护一个非持久队列。当Mule为一个流使用一个非持久队列时，由于`stop()`命令进来或者Mule已经出于任何原因而开始关闭，流被暂停，流在处理停止之前处理队列中的所有消息订购。

相比之下，当Mule为一个流使用一个持久队列并且`stop()`命令进来时，Mule立即停止接受新消息。然后它会在关闭之前完成当前正在处理的所有消息的处理。 Mule不会开始处理队列中仍在等待的任何消息，因为这些消息的副本位于非易失性存储器中（例如，磁盘文件） - 消息可以在Mule重新启动并且流再次可用后处理。

[WARNING]
如果某个流正在使用非持久队列，并且在调用stop（）时该流暂停，则队列中等待处理的所有消息都将丢失。

您可以通过执行以下操作确保在Mule退出时保存所有消息：

* 实施持久SEDA队列。
* 指定支持Mule所有内部消息通道的持久性的传输。

为了进一步确保没有消息丢失，您可以设计Mule部署，以便所有事务都使用同步端点。根据定义，同步端点不使用队列。请注意，同步实现通常无法与排队解决方案的性能相匹配。

== 配置队列

您通过队列配置文件为VM传输配置队列。队列配置文件指定队列的行为方式。通常，您不需要配置队列配置文件的性能，因为默认配置通常就足够了，也就是说，队列不是瓶颈。 （性能通常受限于组件或其中一个端点）。由于其他原因，您仍然可能需要指定最大队列大小，或启用队列上的持久性（默认情况下禁用）。

您可以使用<queue-profile>元素配置队列配置文件。对于VM传输，您可以在连接器上指定<queue-profile>元素。

以下是<queue-profile>元素的属性：

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| `maxOutstandingMessages`  |整数 |否 |   |定义可以排队的最大消息数。
| `persistent`  |布尔值 |否 | false  |指定Mule消息是否持久保存到商店。首先，这用于将排队的消息保存到磁盘，以便在服务器出现故障并需要重新启动的情况下将服务器的内部状态镜像到磁盘上。
|===

根据您指定的持久属性值，Mule选择一个持久性策略用于队列。默认情况下，Mule使用两个持久性策略：

*  `MemoryPersistenceStrategy`，这是一种易变的，内存中的持久性策略。
*  `FilePersistenceStrategy`，它使用文件存储将消息保存到（非易失性）磁盘，因此即使Mule重新启动也会保留消息。

下表列出了在队列配置文件中设置`persistent`属性时使用的持久性策略：

[%header%autowidth.spread]
|===
|当您将*`persistent`*设置为。 。 。 |这是结果：
| `true`  | `FilePersistenceStrategy`
| `false`  | `MemoryPersistenceStrategy`
|===

目前，您不能将任何其他持久性策略配置为类型化Mule XML配置的一部分。但是，如果您需要不同的持久性策略（如持久保存到数据库而不是磁盘），则可以覆盖`mule-default-config.xml`中的缺省值。您可以通过在您自己的配置文件中重新定义`_muleQueueManager` bean来实现此目的。这种自定义持久性策略必须实现`QueuePersistenceStrategy`。

这里有些例子：

在使用VM传输的流上配置连接器。将可排队的最大消息数限制为100，并使队列保持持久状态：

[source, xml, linenums]
----
<vm:connector name="persistentVmConnector" queueTimeout="1000">
   <queue-profile maxOutstandingMessages="100" persistent="true"/>
</vm:connector>
 
<flow>
   <vm:inbound-endpoint ... />
   <component class="org.mule.ComponentClass"/>
   <vm:inbound-endpoint path="in" connector-ref="persistentVmConnector" />
</flow>
----

== 处理流程策略

处理策略决定Mule如何实现流的消息处理。其中一种策略是排队异步处理策略，实现SEDA队列以将流程的接收器与流程中的其他步骤分离。这意味着，当您为流指定排队异步处理策略时，将隐式地为流配置队列。有关更多详细信息，请参阅 link:/mule-user-guide/v/3.4/flow-processing-strategies[关于队列异步流处理策略]。

SEDA队列的== 对象存储

SEDA队列的存储不使用持久性策略。相反，SEDA队列现在使用对象存储来保存消息。 `<queue-profile>`元素中的`persistent`属性已被替换为`<queue-profile>`的子元素。子元素标识SEDA队列的对象存储。

默认情况下，Mule为SEDA队列使用内存中对象存储（对于群集，Mule在共享内存网格中创建默认的内存中存储）。 Mule提供了许多对象存储选择。这些如下：

*  queue-store：引用全局队列存储。
* 默认的in-memory-queue-store：默认的内存中存储。
* 默认的persistent-queue-store：基于文件的商店。对于群集，它是默认的内存中存储。
* 简单的内存中队列存储。始终是内存中的商店。
* 文件队列存储。始终是基于文件的商店。

在大多数情况下，默认的对象存储应该满足您的需求。但是，您可以指定要使用哪个对象存储。例如，您可能希望通过指定默认的持久队列存储来为队列启用持久性，并以此方式覆盖默认的内存队列存储。

有关更多详细信息，请参阅 link:/mule-user-guide/v/3.4/mule-object-stores[骡子对象商店]。
