= 配置属性

此页面描述配置属性，如属性占位符和系统属性。

== 属性占位符

你可以在你的Mule ESB配置中使用Ant风格的属性占位符。例如：

这些占位符的值可以以各种方式提供，如下面的部分所述。

== 全局属性

您可以使用`<global-property>`元素在Mule配置中设置一个占位符值，例如在另一个Mule配置文件中：

== 属性文件

要从文件加载属性，可以使用标准的Spring元素+
  `<context:property-placeholder>`：

`smtp.properties`的内容是：

要加载多个属性文件，请用逗号分隔它们：

== 消息属性

您可以使用占位符在消息属性（如标题）上执行逻辑。例如，如果您想评估邮件标题的内容类型部分，您可以将其指定为`#[message.inboundProperties['Content-Type']]`。通常，您使用消息属性占位符的表达式。有关更多信息，请参阅 link:/mule-user-guide/v/3.5/mule-expression-language-mel[Mule表达语言MEL]。

== 系统属性

占位符值可以来自JDK系统属性。如果你从命令行启动Mule，你可以如下指定属性：

或者如果您将Mule部署为Web应用程序，请编辑`conf/wrapper.conf`中的系统属性。当在一个容器中运行Mule时，从Mule 2.2.2开始，您还可以在`web.xml`文件中指定服务器标识，如下所示：

如果以编程方式启动Mule，则应在创建和启动Mule上下文之前指定属性，如下所示：

还有几个启动后不可变的系统属性。要设置这些，可以使用属性的set方法（例如系统ID的`setId`）自定义`MuleConfiguration`，创建一个`MuleContextBuilder`，将配置加载到构建器，然后从构建器创建上下文。

例如：

有关可用于设置系统属性的设置方法的信息，请参阅：

http://www.mulesoft.org/docs/site/current/apidocs/org/mule/config/DefaultMuleConfiguration.html[org.mule.config.DefaultMuleConfiguration]

有关配置构建器的信息，请参阅 link:/mule-user-guide/v/3.5/about-configuration-builders[关于配置建造者]。

== 环境变量

有几种访问环境变量的方法，但没有标准的方法。

== 另请参阅

* 在我们的 link:https://blogs.mulesoft.com/dev/mule-dev/mule-school-the-mulemessage-property-scopes-and-variables/[MuleSoft博客]中详细了解mule邮件及其属性。
