= 将Maven转换为Studio

您可能希望通过将 http://maven.apache.org/[Maven的]项目导入到Studio中来利用Studio的图形用户界面。

[WARNING]
*Important*：如果您使用Maven *studio:studio*目标，则无法使用*m2eclipse*插件，因为它会覆盖*studio:studio*目标。 Mule Studio使用*studio:studio*目标构建了Maven和Studio之间的导入和导出功能，覆盖了大多数用例。

== 将Maven项目导入Studio

要使用Studio的内置功能导入Maven项目，您必须拥有一个干净的Maven项目，其中没有Eclipse特定的文件。

. 在Studio中，转到*File > Import...*

. 选择*Maven-based Mule Project from pom.xml*，然后点击*Next*

. 导航到您希望导入的pom.xml文件的位置。 Mule自动填充项目名称，但可以调整它。

. 请确保选择您希望使用的运行时。如果要创建驻留在工作区中的项目副本，请选中*Copy project into workspace*框。

. 点击*Finish*

Mule Studio运行*studio:studio*目标将项目导入Studio。

== 故障处理

===  M2_REPO类路径变量错误

如果在Studio中打开Maven项目并遇到错误消息（如下图所示）后，可能需要设置*M2_REPO*类路径变量，或者如果已设置，则将其重新指向正确的存储库。

. 在Studio中，右键点击*Package Explorer*中的项目名称，然后选择*Properties*。

. 在*Properties*面板中，点击左侧菜单中的*Jave Build Path*，然后点击*Libraries*标签。

. 点击*Add Variable...*

. 在*New Variable Classpath Entry*面板中，点击*Configurable Variable...*按钮。
+
从类路径变量列表中选择`M2-REPO`项目，然后单击*Edit...*
+
[NOTE]
如果`M2_REPO`在类路径变量列表中不显示为项目，请单击*New...*创建此类路径变量。

. 更改*Path*字段的内容以指定您的Maven（`m2`）存储库的位置。

. 在每个打开的面板中点击*OK*以保存您的更改。

. 点击控制台中的*Problems*标签，确认错误不再列出，这意味着它们已被解决。

=== 缺少必需的存储库

如果遇到像这样的错误，则无法解析某些依赖项或工件。

`Failed to execute goal on project shcema-extractor-plugin: Could not resolve dependencies for project org.mule.tooling:schema-extractor-plugin:maven-plugin:1.0-SNAPSHOT...`

确保所需的插件存储库包含在您的pom文件中：

[source, xml, linenums]
----
<pluginRepositories>
        <pluginRepository>
            <id>mulesoft-release</id>
            <name>mulesoft release repository</name>
            <layout>default</layout>
            <url>http://repository.mulesoft.org/releases/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
  </pluginRepositories>
----

== 另请参阅

* 直接在Studio中了解如何 link:/mule-user-guide/v/3.4/mule-and-maven[构建新的Maven项目]
* 了解如何 link:/mule-user-guide/v/3.4/converting-studio-into-maven[“mavenize”现有的Studio项目]。
* 探索如何使用 link:/mule-user-guide/v/3.4/using-subversion-with-studio[Studio和Subversion]
