= 自定义消息处理器
:keywords: customize, custom components, custom message processors

您实现的接口或扩展的抽象类将取决于您希望自定义消息处理器执行的操作：

=== 观察消息

消息观察者不会改变消息，也不会确定接下来应该调用哪个消息处理器。实现消息观察者的最简单方法是扩展AbstractMessageObserver并实现抽象观察方法。

用法示例：日志记录，通知和统计信息等

=== 转变消息

任何MessageProcessor都可以根据需要改变消息。如果消息处理器只改变消息并且不关心确定消息流如何继续，那么实现MessageProcessor而不是InterceptingMessageProcoessor或MessageRouter接口是最有意义的。

用法示例：变形金刚

=== 截取消息流

有时您可能需要拦截消息流，以便通过包装下一个消息处理器或以特定方式调用下一个消息处理器来为流添加一定程度的间接。您可以使用InterceptingMessageProcessor，但实现拦截流的消息处理器的最简单方法是扩展AbstractInterceptingMessageProcessor。你仍然需要实现过程，但所有剩下的配件都是为你完成的，而当你想调用下一个MessageProcessor时，你只需要调用processNext。

示例用法：异常处理，事务和异步调用。

=== 过滤消息流

同样，我们可能想要通过上述任何一个原因截取消息流，您可能希望截获具有单一过滤目的的消息流，即确定是否应将特定消息持续到下一个消息处理器或不。您也可以为此实现扩展AbstractInterceptingMessageProcessor。如果验收标准可以通过使用过滤器来表示，那么您可以简单地使用MessageFilter。否则，可以扩展AbstractFilteringMessageProcessor并实现抽象接受方法。

示例用法：所有消息有效负载过滤器，幂等过滤器，安全过滤器

=== 路由消息

一个MessageRouter有多个可能的路由，并负责选择应该使用哪条路由来继续处理特定消息的消息。 MessageRouter接口允许添加（或删除）多个路由。

= 构建消息处理器

在Mule 3 API中有一个用于构建MessageProcessors的通用MessageProcessorBuilder接口，目前它仅在内部使用，但为了确保在正确的时间创建MessageProcessors，用户将几乎肯定需要在配置某些接口时实现此接口消息处理器。

链接消息处理器。= 

消息处理器的链接在您配置<flow>，端点或允许提供有序消息处理器列表的任何其他元素时发生在幕后。我们不是强制所有消息处理器实现InterceptingMessageProcessor以启用链接，而是允许不关心消息流的MessageProcessor实现简单地实现MessageProcessor，然后在创建链时调整它们以便在链中使用它们。
