= 入口点解析器配置参考

此页面提供有关为入口点解析器和入口点解析器组配置的元素的详细信息。这些信息直接从`mule.xsd`中提取并被缓存。如果信息看起来已过时，请刷新页面。

== 入口点解析器集

== 设置入口点解析器

一组可扩展的入口点解析器。这些决定了如何将消息传递给Java中的组件。依次尝试每个入口点解析器，直到成功将消息传递到组件。该元素可以在模型或组件上设置;模型值提供了单个组件值可以覆盖的默认值。

<entry-point-resolver-set...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|===

<entry-point-resolver-set...>的{​​{0}}子元素

|===
| {名称{1}}基数 |说明
|抽象入口点 - 解析器
| 0 .. *
|入口点解析器元素的占位符。入口点解析器通过选择要调用的方法来定义如何将有效载荷传递给Java代码。
|===

== 旧版入口点解析器集

一组可扩展的入口点解析器（它决定了如何将消息传递给Java中的一个组件）已经包含解析器来实现标准逻辑。这已经在默认情况下提供，并且仅在需要使用其他入口点解析器进行扩展时才明确需要。该元素可以在模型或组件上设置;模型值提供了单个组件值可以覆盖的默认值。

<legacy-entry-point-resolver-set...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}典型值 | {要求{3}} Defaul  |说明
|===

<legacy-entry-point-resolver-set...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|抽象入口点 - 解析器
| 0 .. *
|入口点解析器元素的占位符。入口点解析器通过选择要调用的方法来定义如何将有效载荷传递给Java代码。
|===

== 入口点解析器

== 可调用的入口点解析器

实现Callable接口的组件的入口点解析器。这将一个MuleEventContext传递给组件。该元素可以在模型或组件上设置;模型值提供了单个组件值可以覆盖的默认值。该元素也可以直接使用或作为一组解析器的一部分使用;依次使用一组中的解析器直到一个成功。

<callable-entry-point-resolver...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|===

<callable-entry-point-resolver...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|===

== 自定义入口点解析器

自定义入口点解析器。这允许用户提供的代码确定消息如何传递给Java中的组件。该元素可以在模型或组件上设置;模型值提供了单个组件值可以覆盖的默认值。该元素也可以直接使用或作为一组解析器的一部分使用;依次使用一组中的解析器直到一个成功。

<custom-entry-point-resolver...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|类
|类名
|是
|
| EntryPointResolver接口的实现。
|===

<custom-entry-point-resolver...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|弹簧：属性
| 0 .. *
|自定义配置的Spring样式属性元素。
|===

== 属性入口点解析器

使用消息属性来选择要调用的组件方法。该元素可以在模型或组件上设置;模型值提供了单个组件值可以覆盖的默认值。该元素也可以直接使用或作为一组解析器的一部分使用;依次使用一组中的解析器直到一个成功。

<property-entry-point-resolver...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| acceptVoidMethods
|布尔
|无
|
|解析器是否应该调用void方法。默认情况下，void方法不被视为消息传递的候选对象。
|属性
|名称（不含空格）
|无
|
|用于在组件上选择方法的消息属性的名称。
|===

<property-entry-point-resolver...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|===

== 方法入口点解析器

将消息传递给指定的方法。该元素可以在模型或组件上设置;模型值提供了单个组件值可以覆盖的默认值。该元素也可以直接使用或作为一组解析器的一部分使用;依次使用一组中的解析器直到一个成功。

<method-entry-point-resolver...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| acceptVoidMethods
|布尔
|无
|
|解析器是否应该调用void方法。默认情况下，void方法不被视为消息传递的候选对象。
|===

<method-entry-point-resolver...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|包括进入点
| 1 .. *
|可能的交付方式。
|===

== 反射入口点解析器

通过反射从组件生成候选方法列表。该元素可以在模型或组件上设置;模型值提供了单个组件值可以覆盖的默认值。该元素也可以直接使用或作为一组解析器的一部分使用;依次使用一组中的解析器直到一个成功。

<reflection-entry-point-resolver...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| acceptVoidMethods
|布尔
|无
|
|解析器是否应该调用void方法。默认情况下，void方法不被视为消息传递的候选对象。
|===

<reflection-entry-point-resolver...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|排除对象的方法
| 0..1
|如果指定，Java对象接口中的方法不包含在可以接收消息的可能方法列表中。
|排除-入口点
| 0 .. *
|显式排除接收消息的命名方法。
|===

== 数组入口点解析器

将消息传递给一个将单个数组作为参数的方法。该元素可以在模型或组件上设置;模型值提供了单个组件值可以覆盖的默认值。该元素也可以直接使用或作为一组解析器的一部分使用;依次使用一组中的解析器直到一个成功。

<array-entry-point-resolver...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| acceptVoidMethods
|布尔
|无
|
|解析器是否应该调用void方法。默认情况下，void方法不被视为消息传递的候选对象。
| enableDiscovery
|布尔
|无
|真
|如果未配置方法名称，则尝试根据入站消息类型发现要调用的方法。
|===

<array-entry-point-resolver...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|排除对象的方法
| 0..1
|如果指定，Java对象接口中的方法不包含在可以接收消息的可能方法列表中。
|排除-入口点
| 0 .. *
|显式排除接收消息的命名方法。
|包括进入点
| 0 .. *
|可能的交付方式。
|===

== 没有参数入口点解析器

调用不带参数的方法（消息不传递给组件）。

<no-arguments-entry-point-resolver...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| acceptVoidMethods
|布尔
|无
|
|解析器是否应该调用void方法。默认情况下，void方法不被视为消息传递的候选对象。
| enableDiscovery
|布尔
|无
|真
|如果未配置方法名称，则尝试根据入站消息类型发现要调用的方法。
|===

<no-arguments-entry-point-resolver...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|排除对象的方法
| 0..1
|如果指定，Java对象接口中的方法不包含在可以接收消息的可能方法列表中。
|排除-入口点
| 0 .. *
|显式排除接收消息的命名方法。
|包括进入点
| 0 .. *
|可能的交付方式。
|===

== 包含入口点

一种可能的交付方法。

<include-entry-point...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
|方法
|名
|无
|
|方法的名称。
|===

<include-entry-point...>的{​​{0}}子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
|===
