= 码头运输

Jetty传输通过嵌入轻量级Jetty服务器为通过HTTP公开应用程序提供支持。 link:/mule-user-guide/v/3.4/jetty-ssl-transport[Jetty SSL Transport]的工作方式与SSL相同。您只能使用此传输来定义入站端点。

这个运输的Javadoc可以在下面找到：

http://www.mulesoft.org/docs/site/current/apidocs/org/mule/transport/servlet/jetty/JettyHttpConnector.html[码头运输Javadoc]

该连接器允许Mule使用Jetty HTTP服务器通过HTTP公开Mule服务。为每个连接器实例创建一个Jetty服务器。一个连接器可以服务于许多端点。用户应该很少需要有多个Jetty连接器。 Jetty连接器可以使用Jetty XML配置文件进行配置，但对于大多数情况，默认配置已足够。

连接器的=== 属性

这些属性适用于可选的全局连接器jetty：connector。

[%header,cols="5*"]
|===
一个|
*Name*

 为|
*Type*

 为|
*Required*

 为|
*Default*

 为|
*Description*

|姓名 |字符串 |是 |码头 |流中可以引用的连接器的名称。
| configFile  |字符串 |否 |   |用于配置此连接器的Jetty配置文件的位置。
|接受者 |  int  |否 | 1  | 接受者线程的数量。
| resourceBase  |字符串 |否 |   |指定将从其提供文件的本地路径。本地路径直接映射到'serverUrl'上的路径。
| useContinuations  |布尔值 |否 |   |是否在高负载情况下使用延续来释放连接。
|文档：名称 |字符串 |仅适用于Studio配置 | Jetty  |连接器的描述性名称。在Mule独立配置中不需要。
|===

== 端点

Jetty端点的配置方式与 link:/mule-user-guide/v/3.4/https-transport-reference[HTTP端点]相同。请注意，Jetty传输只能用于入站端点。

例如：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns:jetty="http://www.mulesoft.org/schema/mule/jetty" xmlns:file="http://www.mulesoft.org/schema/mule/file" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:spring="http://www.springframework.org/schema/beans" version="EE-3.4.2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
http://www.mulesoft.org/schema/mule/jetty http://www.mulesoft.org/schema/mule/jetty/current/mule-jetty.xsd">
    <flow name="somethingFlow1" doc:name="somethingFlow1">
 
        <jetty:inbound-endpoint exchange-pattern="request-response" host="localhost" port="8081" doc:name="Jetty"/>
 
    </flow>
 
</mule>
----
