=  Mule和Maven

http://maven.apache.org/[Maven的]是一个项目管理实用程序，您可以使用它开发Mule中的项目。尽管强烈建议，但Maven并不是严格需要在Mule中开发应用程序。为了支持从事Maven集成项目的用户，Mule提供了内置的功能，以便为Studio项目提供Maven支持。

*  **Build and run a new Maven project in Studio.**如果您从头开始并且想要使用Maven构建项目，请先在Studio中创建一个基于Maven的新项目。您可以从命令行或直接在Studio中使用Maven运行项目。详情请参阅下面的内容。
*  **Convert a Maven project into Studio for import.**如果您已经有了想用Studio开发的Maven项目，请使用Studio中的内置功能使用`studio:studio`目标导入pom.xml文件。有关详细信息，请访问 link:/mule-user-guide/v/3.4/converting-studio-into-maven[将Maven转换为Studio]。
*  **Convert a Studio project into Maven for export.**如果您在Studio中构建了项目并希望将其转换为Maven项目以进行导出，则可以使用Studio中的内置支持来"Mavenize"该项目。有关详细信息，请访问 link:/mule-user-guide/v/3.4/converting-studio-into-maven[将Studio转换为Maven]。

== 在Studio中构建和运行Maven项目

您可以调整Studio偏好设置，以便Studio在创建项目时自动生成`pom.xml`文件。以下过程概述了在Studio中创建新的基于Maven的项目的步骤。

. 转到*Mule Studio*> *Preferences*（或Windows中的Windows>首选项）。
. 在*Preferences*面板中，点击展开*Mule Studio*，然后选择*Maven Settings*。
. 单击以选择*Enable Maven support in Mule Studio*和**Enable automatic maintenance of pom.xml**。 +
. 如果需要，调整本地驱动器上*Maven installation home directory*的文件路径，然后单击*OK*保存更改。
. 在*File*菜单下，选择*New*> *Mule Project*。
. 输入*Project Name*。
. 点击*Create POM file for project and maintain with Maven*。 Mule会自动填充三个字段，以便为您的项目创建一个`pom.xml`文件。 +
..  *Group ID*：Maven的公司或开发团队标识符
..  *Artifact ID*：您的Maven应用程序或项目标识符
..  *version*：Maven +的工件版本
 。根据需要调整上述字段的默认内容，然后点击*Finish*在Studio中创建您的Maven项目。
.  Studio为您的项目添加一个新的`pom.xml`文件。双击`pom.xml`文件以查看Studio中的内容。 +
+

[NOTE]
如果您手动编辑您的pom.xml文件，Studio会使用任何新的依赖关系更新项目的类路径。换句话说，Mule在后台运行`studio:studio`目标以保存项目的任何更改。
+

. 在Studio中构建并保存Maven项目。
. 要将您的应用程序作为Maven项目运行，请在包资源管理器中右键单击您的项目名称，然后选择*Run As*> *Mule Application with Maven*。
. 或者，您可以通过执行以下语法将命令行中的Mule项目打包：+
`mvn package` +
Mule将该项目打包在。`zip`文件中。将目标文件夹中的`.zip`文件部署到您的Mule ESB实例以运行该应用程序。 +

== 禁用Studio中的Maven支持

您可以调整Studio首选项，以便Studio不会为新项目自动生成`pom.xml`文件。以下过程概述了在您的Studio实例中禁用Maven支持的步骤。

. 转到*Mule Studio*> *Preferences*（或Windows中的Windows>首选项）。
. 在*Preferences*面板中，点击展开*Mule Studio*，然后选择*Maven Settings*。
. 点击即可取消选择*Enable Maven support in Mule Studio*和**Enable automatic maintenance of pom.xml**。
. 点击*OK*，保存对首选项的更改。

当您在Studio中创建新项目时，无法在新建项目向导的第三个面板中单击*Create POM file for project and maintain with Maven*。

== 禁用单个Studio项目中的Maven支持

如果您在Studio中创建了Maven项目并希望禁用该项目的Maven支持，请右键单击*Package Explorer*中的项目名称，然后选择*Maven Support in Studio*> *Disable Support*。尽管它不会删除`pom.xml`文件，但Studio无法为该项目维护该文件。

如果_did不删除`pom.xml`文件，则可以通过Studio菜单项重新支持Maven支持。右键点击*Package Explorer*中的项目名称，然后选择*Maven Support in Studio*> *Enable Support*。

[WARNING]
如果您在Studio项目中停用*Maven support*并删除`pom.xml`文件，则无法通过Studio菜单项中的Maven支持重新启用该文件。要将Studio项目转换为Maven，请参阅 link:/mule-user-guide/v/3.4/converting-studio-into-maven[将Studio转换为Maven]文档。


== 另请参阅

*  link:/mule-user-guide/v/3.4/converting-studio-into-maven[将现有的Maven项目转换为Studio]。导入项目，然后直接在Studio中将其作为Maven项目运行。
*  link:/mule-user-guide/v/3.4/converting-studio-into-maven[将您的Studio项目转换为Maven]用于导出。
* 探索如何使用 link:/mule-user-guide/v/3.4/using-subversion-with-studio[Studio和Subversion]。
