=  Mule DataSense

*Mule DataSense*使用消息元数据来促进应用程序设计。有了这个功能，Mule Studio可以主动获取关于数据的信息，例如数据类型和结构，以便规定如何准确地映射或使用应用程序中的数据。

Mule智能地发现这些信息，并用它来提出应用程序设计建议，而不是强迫你手动发现内部和外部资源所使用的数据信息。例如，如果您的应用程序必须连接到Twitter，则Mule DataSense将捕获有关Twitter所使用的数据的类型和结构的信息，然后使用该信息向您建议您应发送给的数据类型或期望从Twitter接收的数据类型。

== 假设

本文档假定您熟悉可用于在Studio中创建应用程序的 link:/anypoint-studio/v/5/[Mule Studio中的可视化编辑器]， link:/mule-user-guide/v/3.4/anypoint-connectors[Anypoint连接器]和 link:/anypoint-studio/v/5/datamapper-user-guide-and-reference[Anypoint DataMapper]转换器。此外，本文档引用 link:/mule-user-guide/v/3.4/connecting-using-transports[连接器]和 link:/mule-user-guide/v/3.4/global-elements[全球元素]。查看 link:/anypoint-studio/v/5/[Mule Studio入门]一章，以了解更多关于使用Mule ESB图形用户界面进行开发的内容。

==  DataSense功能

作为分阶段实施DataSense的一部分，*Mule ESB with Studio 3.4*引入了两项功能，可以从外部资源主动发现元数据：

. 连接测试
. 感知流程设计

==== 连接测试

该功能使您能够测试与外部资源的连接。在Studio中对应用程序进行建模时，您有机会在配置连接器时测试其与服务或数据库的连接功能。与其等待您运行应用程序来测试连接，您可以在继续之前尽早测试以确认功能。

例如，如果要配置Anypoint Connector与Salesforce进行通信，则可以输入所需的配置值（登录凭据，主机和端口，代理设置），然后只需单击即可测试连接。 Mule向Salesforce提交一个调用来确认连接是否存在并且正常工作。

==== 感知流程设计

通过建立连接测试所确定的确定性，Mule采用了更多的步骤，使Perceptive Flow Design能够更轻松地设计您的应用程序。如果您对一个流进行建模以包含一个Anypoint Connector，在Anypoint DataMapper转换器之前或之后，Mule会使用与资源的工作连接（例如SaaS提供程序）来检索有关消息负载和属性的元数据。捕获SaaS采用的数据类型和结构，Mule将该数据馈送到DataMapper中，从而通知DataMapper期望的输入或输出。此功能有助于将数据从一种数据格式和结构映射到另一种数据，从而为您节省开发时间，否则您将花费​​时间尝试发现自己的结构和格式。

例如，假设您的任务是将您组织的Salesforce帐户与Twitter连接起来，以宣传特定的绩效指标。您的首要任务之一是检查两个SaaS提供商提供的可用文档，以确定其使用的数据结构类型，以便最终确定如何将一个结构映射到另一个结构。您可以利用感知流程设计，而不是通过疲惫的练习。将两个连接器拖放到您的Mule Studio画布上 -  Salesforce和Twitter  - 然后配置它们并测试它们的连接。确认连接后，只需在连接器之间放置一个DataMapper Transformer即可。打开DataMapper，发现Mule智能地捕获了每个SaaS提供商的数据类型和结构信息，并为您的数据映射规定了输入和输出。随着处方的到位，您所需要做的就是配置映射。

==  DataSense最佳实践

要充分利用DataSense所提供的功能，设计时的最佳实践表明您应该按照以下顺序构建应用程序：

. 首先将端点和连接器放入您的流中，通过它将数据流入和流出应用程序。例如，首先配置一个HTTP端点，然后是一个Anypoint连接器。
. 配置端点和连接器 - 以及它们引用的全局连接器 - 以便在可能的情况下，建立连接并使用DataSense从外部源中提取有关预期输入或输出的元数据。
. 在您的流程中插入其他元素以丰富消息，设置，复制或删除变量或属性，路由消息等。
. 最后，将DataMapper转换器插入到您的流中，以调整消息的格式或结构，以便每个连接器都能接收到它所期望的输入。

此设计时策略的目标是设置集成难题的各个部分，然后使用DataMappers "glue them together"。这种类型的"align, then glue together"策略不是顺序设计流程，而是确保您在任何可能的情况下都利用DataSense将输入或输出数据的结构和格式信息预先填充到DataMapper中。

例如，如果您在应用程序中配置Salesforce连接器，然后将DataMapper放在其后面，则DataMapper使用DataSense提取的信息预先填充输入值以进行映射，以便您只需确认（或调整）输入选择，然后继续映射到所需的输出。换句话说，DataSense确保DataMapper确定它必须工作的数据格式和结构，因此您不必手动将其解决。无论何时您可以使用DataSense，您都会采取一种开发捷径，消除手动发现消息中所含数据格式和结构的麻烦。

== 另请参阅

* 了解如何向外部资源提供 link:/mule-user-guide/v/3.4/testing-connections[测试连接]。
* 请参阅 link:/mule-user-guide/v/3.4/testing-connections[启用了DataSense的连接器的列表]。
* 了解如何利用 link:/mule-user-guide/v/3.4/using-perceptive-flow-design[DataSense感知流程设计]。
* 请参阅DataSense的行动！检查使用DataSense构建的两个示例应用程序： link:/mule-user-guide/v/3.4/connect-with-salesforce-example[与Salesforce示例连接]。
