= 剖析Mule
:keywords: anypoint studio, esb, profiling, yourkit, monitoring, performance, memory, cpu, tuning

Mule Profiler Pack使用YourKit 9.0提供CPU和内存分析，帮助您识别定制Mule ESB扩展中的内存泄漏。要使用不同版本的YourKit，而不是使用Profiler Pack，请参阅YourKit文档以获取相应版本，以获取有关如何配置Java应用程序的说明。当使用独立Mule进行此操作时，请注意，任何JVM标志都必须以-M开头，以便它们影响Mule进程而不是包装进程。

== 安装Profiler Pack

Profiler Pack包含在Mule企业版下载中。如果您使用图形安装程序安装Mule企业版，只需在安装产品时选择Profiler复选框。

如果您正在安装Mule Community Edition，请转到下载页面，并在最新的稳定社区版本下展开*Downloads*部分。然后，您可以单击指向Profiler包的.zip，.tar或.gz版本的链接。下载后，将其解包到Mule安装的顶部。

设置以下环境变量：

[source, code, linenums]
----
LD_LIBRARY_PATH=$MULE_HOME/lib/native/profiler
----

== 启用Profiler代理

Profiler代理将YourKit Profiler公开给JMX以提供CPU和内存分析。您使用`<management:yourkit-profiler/>`元素配置Profiler代理。有关更多信息，请参阅 link:/mule-user-guide/v/3.6/jmx-management[JMX管理]。

== 运行Profiler

要运行Profiler，您需要使用*-profile*开关以及多个以逗号分隔的多个参数的额外 http://www.yourkit.com/docs/90/help/startup_options.jsp[YourKit启动选项]来运行Mule。 **-profile onlylocal,onexit=memory**。该集成包将自动处理Java 1.4.x和5.x / 6.x的配置差异。

例如：

[source, code, linenums]
----
./mule -profile
----

== 嵌入式Mule

如果您将Mule嵌入到Web应用程序中，则Profiler配置会完全委派给拥有的容器。启动YourKit分析器，*Tools -> Integrate with J2EE server...*并按照说明进行操作。通常，修改服务器的启动脚本以支持分析，然后使用此修改后的启动脚本代替原始脚本。
