= 关于负载平衡器（CloudHub）

本主题提供有关CloudHub中负载平衡器的一般信息。 CloudHub提供后端负载均衡服务，可自动配置基础架构组件。

CloudHub提供两种类型的负载平衡器：

* 共享负载平衡器：提供基本的负载平衡功能。
* 专用负载均衡器：使您能够在VPC中部署和配置一个或多个自定义负载均衡器。

== 共享负载平衡器

CloudHub提供了可在所有环境中使用的默认共享负载均衡器。共享负载平衡器提供基本功能，包括TCP负载平衡和SSL证书传递。共享负载平衡器不允许您配置自定义SSL证书或配置代理规则。

此外，共享负载均衡器具有较低的速率限制，有助于确保平台的稳定性。 MuleSoft会定期监控并根据需要调整这些限制。根据地区应用共享负载均衡器的速率限制。因此，如果您正在向多个地区的工作人员部署应用程序，则每个地区的费率限制可能会有所不同。

如果应用程序超出共享负载平衡器的速率限制，则负载平衡器会返回503服务不可用响应。

要执行自定义负载平衡器配置或具有更高的速率限制阈值，您必须使用专用负载平衡器。

== 专用负载平衡器

专用负载均衡器使您能够：

* 处理运行应用程序的不同CloudHub工作负载之间的负载平衡。
* 定义SSL配置以提供自定义证书，并可以选择实施双向SSL客户端身份验证。
* 配置将您的应用程序映射到自定义域的代理规则。这使您可以在单个域下托管您的应用程序。

专用负载平衡器是Anypoint平台的可选组件。要在您的环境中使用专用负载平衡器，您必须运行Anypoint虚拟私有云（VPC）。您可以将多个环境关联到同一个VPC。这使您可以在不同的环境中使用相同的专用负载平衡器。

您可以在API门户中查看Anypoint Platform组织中的负载平衡器和VPCS端点。

== 另请参阅

*  link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API门户]
*  link:/runtime-manager/cloudhub[CloudHub]
*  link:/runtime-manager/virtual-private-cloud[虚拟私有云]
*  link:/runtime-manager/lb-architecture[关于负载平衡器体系结构]
