专用负载均衡器中的= 证书验证

如果为SSL端点提供了至少一个CA证书，则负载均衡器使用以下HTTP标头将客户端证书数据传递给API：

====  X-​​SSL-客户验证

此标题返回`SUCCESS`，`FAILED`或`NONE`
只有在`SUCCESS`之后，客户端才会被验证。 +
它在证书不存在时返回`NONE`，当发生其他验证问题时返回`FAILED`。

====  X-​​SSL的客户端-DN

包含客户端证书的完整专有名称。

====  X-​​SSL-发行人

包含颁发证书的完整专有名称。

====  X-​​SSL-客户串行

包含CA用于识别客户端的序列号。

=== 添加吊销列表

CloudHub负载平衡器可以根据证书吊销列表（CRL）选择性地验证客户端请求。所有的CRL文件需要连接成一个_pem_编码的文件进行上传。订购并不重要。

您可以在 link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-create[负载平衡器创建]命令中使用' -  crl'选项创建负载平衡器时添加吊销列表。

此外，如果您的负载平衡器已经创建，您可以使用 link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/8617/versions/85955[REST API]进行更新。 +
您可以向添加了`revocationList`元素的`/organizations/{orgid}/vpcs/{vpcId}/loadbalancers/{lbId}`端点发送`PATCH`请求：

[source,json,linenums]
----
[
  {
    "op": "replace",
    "path": "/sslEndpoints/0/revocationList",
    "value": "-----BEGIN X509 CRL-----\nMIIBTTCBtwIBATANBgkqhkiG9w0BAQUFADBXMQswCQYDVQQGEwJBVTETMBEGA1UE\nCBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRk\nMRAwDgYDVQQDEwdvcmcuY29tFw0xNjAzMTUwOTI2MThaFw0xODAzMTUwOTI2MTha\nMBwwGgIJAIBvvO4dJHjhFw0xNjAzMTUwODUwMTZaoA4wDDAKBgNVHRQEAwIBBjAN\nBgkqhkiG9w0BAQUFAAOBgQCCAbGXW+Hnzmd1bXqWsFXfogOsJScoxkJOhhmjui3I\nhTUyO5plGHUBLjBnDkypM+iLfn0W4wPcNj7FZdz4Hu/WLntxwrTtR5YOcfIhEGcq\nwvJq/1+WKUPC6eqGwx0iKOOBIWsaf5CNOOUQMo6RaeTeu8Uba2EGFk1Vu/SoZYAK\nsw==\n-----END X509 CRL-----\n"
  }
]
----

[NOTE]
--
建议使用CloudHub REST API以编程方式更新撤销列表。 +
为了从CLI获取必要的vpcId和loadbalancerId，可以分别使用 link:/runtime-manager/anypoint-platform-cli#cloudhub-vpc-describe-json[vpc JSON描述]和 link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-describe-json[负载平衡器JSON描述]命令。
--

您可以向您的负载平衡器的端点发送PATCH请求以更新任何其他属性。


=== 证书密码

下面是一个推荐的密码套件列表，其中您的SSL端点的兼容性和安全性之间具有良好的平衡
除了支持Internet Explorer 8的RC4-SHA之外，它们都提供前向保密。

----
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES128-GCM-SHA256
ECDHE-RSA-AES256-SHA384
ECDHE-RSA-AES128-SHA256
ECDHE-RSA-AES256-SHA
ECDHE-RSA-AES128-SHA
DHE-RSA-AES256-SHA256
DHE-RSA-AES128-SHA256
DHE-RSA-AES256-SHA
DHE-RSA-AES128-SHA
ECDHE-RSA-DES-CBC3-SHA
EDH-RSA-DES-CBC3-SHA
AES256-GCM-SHA384
AES128-GCM-SHA256
AES256-SHA256
AES128-SHA256
AES256-SHA
AES128-SHA
DES-CBC3-SHA
----

ClourHub的专用负载均衡器支持TLSv1.1和TLSv1.2。另外，您可以配置TLS v1.0，但请记住，由于其严重的漏洞，此类协议不再被PCi合规伙伴接受。

== 另请参阅

*  link:/runtime-manager/lb-cert-upload[关于上传证书]
*  link:/runtime-manager/lb-whitelists[关于白名单]
*  link:/runtime-manager/lb-mapping-rules[关于映射规则]

