= 关于专用负载均衡器映射规则

负载平衡器配置由*Mapping Rules*列表定义，该列表描述了如何将输入URL转换为对不同CloudHub应用程序的调用。 +
映射规则是负载均衡器的SSL端点的属性。 +
当您创建映射规则时，您需要指定一个证书CN。省略`[certificateName]`参数会将映射添加到默认端点。

当创建一个简单的匹配规则时，一个输入地址与定义的输出字面上相匹配：一个应用程序的端点。 +
您也可以使用*Pattern*将类似变量的输入文本与端点进行匹配，而不是使用文字匹配。

通过使用代理规则，您可以将域或子域映射到在CloudHub中运行的其中一个Mule应用程序

== 在映射规则中使用模式

模式是一个字符串，它定义了用于匹配输入文本的模板。无论放入大括号（`{   }`）如何被视为变量。
这些变量只能包含字母（a-z），不能包含任何其他字符，如数字，斜杠等。变量值可以包含以下字符'a-z0-1。＆？-_'，但不包含斜杠。

例如，您可以从字面上绑定两个主机名进行重定向：

[source,Example,linenums]
----
‘app.example.com’ ->  application: `app` URI: `/example’
----

或者你可以定义一个模式来保存输入值：

[source,Example,linenums]
----
‘example.com/{mypattern}’ -> application: `app-{mypattern}` URI: /data
----

上面的示例导致“example.com/bookings”和“example.com/sales”分别与`app-bookings/data`和`app-sales/data`匹配，因为变量`mypattern`拥有这些值。 +
对于input =“bookings.example.com”，可通过分配`_mypattern_=”bookings” and for input=` sales.example.com `, the pattern is resolved to assign ` _ mypattern _ =“sales”来解决该模式。

根据您的设计，您可以选择利用模式或简单文字映射来将内部重定向用于端点。

请注意，应用程序URI中的当前模式不受支持。

== 创建映射规则

映射规则是一组定义*Input URL*的字段，以及一组描述*Output URL*的字段。

*  _input URL_使用可由用户指定的URI参数进行描述：
.  *URI*  - 描述输入URI的字符串或模式。
+
[NOTE]
--
输入URL位于主负载均衡器的域之后（对于相同的负载均衡器，此值应保持不变）
--
+
*  _Output URL_由两个字段指定。
.  *appName*  - 输出将请求转发到的应用程序名称。
.  *appURI*  - 传递给已解析应用程序的URI字符串。

输入和输出URL都可以使用模式或字符串来定义。

映射规则是负载平衡器SSL端点的属性，由证书名称标识。 +
当您创建映射规则时，您需要指定一个证书CN。省略`[certificateName]`参数会将映射添加到默认端点。

如果您的SSL端点设置了 link:https://en.wikipedia.org/wiki/Wildcard_certificate[通配符证书]，并且您希望在映射规则中使用子域部分，则可以使用预定义的`{subdomain}`变量。

首先定义的规则相对于之后定义的其他规则具有高优先级。这意味着将应用第一个匹配的规则。 +
您可以分别使用 link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-add[映射添加]， link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-describe[映射描述]和 link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-remove[映射删除]命令创建，查看和删除现有规则。

== 映射规则示例

下表包含一些映射规则示例：

[NOTE]
假定外部负载均衡器域名取决于您为其指定的唯一名称，则假定这些示例中的负载均衡器为`lb-demo`。

[CAUTION]
--
默认情况下，您的负载均衡器通过HTTPS侦听外部请求，并通过HTTP与您的工作人员进行内部通信。如果您在VPC内配置Mule应用程序以侦听HTTPS，请确保在使用 link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-add[负载平衡器映射添加]命令创建映射列表时将`upstreamProtocol`设置为`HTTPS`。
--

=== 网址映射

您可以将应用名称作为输入URI传递，并将其直接映射到CloudHub中的应用名称：

[%header,cols="10a,20a,20a,10a"]
|===
|规则＃ |输入URL 2 + ^ | 输出URL
|    |     *URI*    |        *appName*    |    *appURI*
|  {0 {1}} / {应用} /     |  {应用}              |  /
|===

此规则将`lb-demo.lb.anypointdns.net/{app}`映射到`{app}.cloudhub.io`。 +
{app}是您选择通过的应用程序名称的模式。

=== 主机映射

如果您有通配符证书（如`*.example.com`），则可以使用'subdomain'变量映射任何子域：

[%header,cols="10a,20a,20a,10a"]
|===
|规则＃ |输入URL 2 + ^ | 输出URL
|    |   *URI*    |        *appName*     |   *appURI*
|  {0 {1}} /         |  {子域}    |  /
|===
此规则自动将任何传递给example.com子域的请求映射到相应的appName。例如：

* 传递`api.example.com`将重定向到`api.cloudhub.io` +
* 传递`application.example.com`映射到`application.cloudhub.io`。

这同样适用于您的SSL端点的 link:https://en.wikipedia.org/wiki/Subject_Alternative_Name[使用替代名称]（SAN）。 +
如果您为证书的通用名称配置了不同的SAN，则可以使用“子域名”变量将域名的子域部分映射到您的应用程序。然而，为了这个工作，你的应用程序需要与你的域名的公共部分具有相同的名称。

例如，具有：

* 两个已部署的应用程序：
**  dev的应用内
**  QA-应用
* 以及一个带有主题备选名称的SSL端点：
**  dev.example.com
**  qa.example.com
* 映射规则：
+
[%header,cols="10a,20a,20a,10a"]
|===
|规则＃ |输入URL 2 + ^ | 输出URL
|    |   *URI*    |        *appName*     |   *appURI*
|  {0 {1}} /         |  {子域} -app    |  /
|===

然后，这个规则会将您域名的子域部分映射到应用程序名称：

* 将`dev.example.com`重定向到`dev-app.cloudhub.io`。
* 将`qa.example.com`重定向到`qa-app.cloudhub.io`。


===  1：1映射

如果您只有一个应用程序，则可以映射文字应用程序名称。

[%header,cols="10a,20a,20a,10a"]
|===
|规则＃ |输入URL 2 + ^ | 输出URL
|    |   *URI*   |    *appName*  |    *appURI*
|  {0 {1}} /        |    对myApp     |  /
|===
这会将您的默认负载平衡器`lb-demo.lb.anypointdns.net`直接映射到Cloudhub `myApp.cloudhub.io`中的应用。

== 索引规则的优先级

创建_mapping规则_时，您需要为其指定一个索引来定义规则的优先顺序。 +
首先在索引`0`中定义的规则相对于其后定义的其他规则具有更高的优先级。分配的索引越高，映射规则的优先级越低。

每个规则都必须定义一个优先级。强烈建议在创建它们时注意每个规则的顺序，并且多条规则可能会相互覆盖。

=== 订购和优先规则

您可以通过指定索引值，在Anypoint-CLI中使用 link:https://docs.mulesoft.com/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-add[cloudhub负载平衡器映射添加]命令创建映射规则时设置映射规则的顺序。

使用API​​创建规则时，您无法指定优先级顺序，但可以稍后向负载平衡器端点`anypoint.mulesoft.com/cloudhub/api/organizations/{orgid}/loadbalancers/{loadbalancerId}`发送`PATCH`请求，并使用顺序索引将您的规则表达式更新为根据上面解释的顺序逻辑匹配您的需求。

[NOTE]
--
负载均衡器ID在您创建时提供给您。 +
您还可以对您的端点/组织/ {orgid}} /负载平衡器执行`GET`请求以获取该ID。
--

== 另请参阅

*  link:/runtime-manager/lb-cert-upload[关于上传证书]
*  link:/runtime-manager/lb-whitelists[关于白名单]
*  link:/runtime-manager/lb-mapping-rules[关于映射规则]
