= 关于VPC防火墙规则

在CloudHub的默认配置中，所有应用程序都托管在多租户云中，并由可公开访问的负载均衡器进行平衡。 +
在创建自己的隔离网络时，您可以使用自己的防火墙规则来允许特定的IP范围和端口到达您的工作人员。

[注意]
====
请记住，您在VPC中配置的防火墙规则仅检查入站连接的工作人员，而不检查VPC，专用负载平衡器或可公开访问的负载平衡器。
====

除非在防火墙规则中允许，否则所有到VPC的流量都会被阻止。
创建VPC时，默认情况下会创建4个防火墙规则：

*  2规则允许您的本地VPC通过端口8091和8092进行入站连接：
+
[source,json,linenums]
----
{
  "CIDR Block": "10.111.0.0/24", // (Local VPC)
  "Protocol": "TCP",
  "From port": 8092,
},

{
  "CIDR Block": "10.111.0.0/24", // (Local VPC)
  "Protocol": "TCP",
  "From port": 8091,
},
----
+
这些防火墙规则允许来自VPC的流量通过端口8091和8092到达您的工作人员。这些是您的CloudHub专用负载平衡器用于将所有外部通信代理给您的工作人员的唯一端口。

*  2规则允许通过端口8081和8082从任何地方进行入站连接：
+
[source,json,linenums]
----
{
  "CIDR Block": "0.0.0.0/0", // (Anywhere)
  "Protocol": "TCP",
  "From port": 8082,
},

{
  "CIDR Block": "0.0.0.0/0", // (Anywhere)
  "Protocol": "TCP",
  "From port": 8081,
}
----
+
[注意]
====
这些规则允许来自任何主机的流量通过端口8081和8082到达您的工作人员。
CloudHub的共享负载平衡器使用这些端口将外部请求代理给您的工作人员。
如果您不希望公共访问的负载均衡器访问您的内部工作人员，则可以删除这些规则。
====

== 另请参阅

*  link:/runtime-manager/cloudhub-networking-guide[Cloudhub网络指南]
*  link:/runtime-manager/dedicated-load-balancer-tutorial[关于负载平衡器（CloudHub）]
*  link:/runtime-manager/cloudhub-dedicated-load-balancer[关于Cloudhub专用负载均衡器]
*  link:/runtime-manager/cloudhub-architecture[CloudHub架构]
