= 关于配置VPC

为您的组织提供VPC包含两个主要步骤：

. 创建VPC。 +
这是一个自助服务流程。您可以使用运行时管理器UI或Anypoint Platform CLI创建VPC。
. 连接到您的VPC。 +
这需要由MuleSoft代表完成。

有关这些过程的详细信息，请参阅下面的“另请参阅”部分中的教程和任务。 +
但是，在创建VPC之前，您需要知道某些设置只能在第一次设置时配置：

* 您网络的地址空间。 +
这决定了您的VPC的大小。
* 您的VPC的位置。 +
为了使VPC能够托管您的工作人员，它需要绑定到业务组和特定的CloudHub区域。
+
** 您的VPC的组织或业务组。
** 您的VPC的CloudHub地区。

在创建VPC之后编辑这些设置，需要您删除所有工作人员，并在更改完成后重新部署这些设置。在开始时定义这些设置对于避免不必要的停机时间至关重要。 +
请注意以下FAQ以了解如何规划成功的VPC设置。

== 常见问题解答：如何调整我的VPC大小

在创建VPC时，需要使用CIDR表示法以无类别域间路由（CIDR）块的形式指定此网络的IP地址范围。 +
该地址空间是为Mule工作人员保留的，因此如果您想要与您的VPC进行同步，它就不能与数据中心中使用的任何地址空间重叠。

为了计算VPC的适当大小，首先需要了解的是，专用IP地址的数量与您部署的工作人员数量不同。 +
对于部署到CloudHub的每个工作人员，执行以下IP分配：

* 为了获得更好的容错性，VPC子网可以分为最多4个可用区。
* 几个IP地址被保留用于基础设施。
* 每个工作人员至少要有两个IP地址在零停机时间执行。

由于这种结构，您可为VPC分配的最小网络子网块为/ 24，最大/ 16。 +
A / 24 CIDR表示法子网有256个IP地址。 +
为网络保留一个IP地址，为广播保留一个IP地址，您的工作人员拥有254个主机，每个主机分为4个可用区域，每个主机有62个主机。考虑到每个工作人员可能需要两个IP地址来实现零停机时间，这就是大约30个IP地址分配给您的员工。 +
还要考虑VPC中需要的环境。例如，f需要Dev，QA和UAT中的每个实例需要300个实例，至少需要1024个实例。

确定VPC子网大小的安全经验法则是"10 times the maximum number of expected apps to deploy in the VPC"。

== 常见问题解答：在我的组织内放置VPC的位置

作为组织管理员，您可以创建VPC并与主组织内的任何业务组共享。 +
但是，一旦VPC被业务组继承，只有该业务组的管理员才能操作VPC。例如，CloudHub组织管理员或业务组所有者可以创建或更新现有VPC（拥有或继承），以使其成为区域，环境或两者的默认值。 +
但是，如果此类关联已存在，则会被请求的VPC覆盖。

如果未指定业务组关联，或者您的组织没有任何业务组，则VPC所有权仍与主要组织相关联。创建VPC的组织是VPC所有者，并且此组织的管理员是唯一可以共享VPC的人员。 +
VPC只能从主要组织直接共享到其中一个业务组，或者从业务组到其子业务组之一。 +
您不能共享由业务组创建的VPC与另一个较高层级的VPC。

建议您在主组织中创建VPC，并与其他业务组共享。

== 常见问题解答：在哪个区域创建VPC

您可以在任何可用的CloudHub区域内创建VPC。 +
推荐使用的区域可能会有所不同，具体取决于您如何连接到VPC。如果您正在使用VPN隧道，则可能需要选择距离数据中心最近的CloudHub区域。 +
但是，如果您正在与您的私人AWS VPC对接，则需要在同一个AWS区域中创建CloudHub VPC。

== 另请参阅

*  link:/runtime-manager/to-request-vpc-connectivity[向网络请求VPC连接]
