= 管理控制台的体系结构

当IT组织部署Mule ESB进行生产时，操作人员必须能够管理和监控ESB基础架构和相关服务。引入到基础设施中的每个附加系统，应用程序或服务都会增加复杂程度，同时还需要查看和控制系统性能和正常运行时间。

使用Mule ESB管理控制台，您可以管理所有Mule ESB实例以及已部署的应用程序包。管理控制台提供一个集中，方便且直观的基于Web的界面，用于监视，管理和管理企业服务总线的运行时间方面。借助这款高性能和安全的工具，您可以通过快速识别，诊断和调解中心位置的问题，从而节省时间并减少错误。

== 架构

管理控制台需要以下组件：

*  Mule ESB的正确版本
* 管理控制台服务器
* 管理控制台代理

管理控制台仅适用于企业版Mule ESB，并且与以前版本的Mule ESB向后兼容。

管理控制台通过管理控制台代理与Mule ESB进行通信。这个代理是一个Mule应用程序;它会自动安装在Mule ESB 3.1中。

Mule ESB Enterprise 3.3自动安装并与管理控制台和管理控制台代理进行互操作。

安装时，代理程序包将放置在Mule ESB \ apps目录中，然后在启动时自动解压缩并由ESB实例部署。

管理控制台可以直接部署到Mule ESB，就像评估分发一样;但是，这不建议用于监视多个Mule ESB实例的部署。

一旦Mule实例通过认证并注册到管理控制台服务器，通信就通过使用证书和HTTPS得到保护。每个Mule实例都可以在单个管理控制台服务器上注册。

管理控制台服务器是一个打包为WAR文件的Web应用程序，可从您的Web容器中执行。因此，它必须正确部署在容器上，例如将WAR文件放在Web容器安装中的适当位置。例如，对于Apache Tomcat安装，可以使用MuleSoft Tcat Server或通过将其复制到Tomcat `/webapps`目录来部署mule管理控制台WAR（`mmc.war`）文件。

== 主要功能

以下是管理控制台的主要功能：

=== 集中管理和监控

* 检查ESB资源的健康状况，并将其显示在易于导航的可视界面中
* 提供可直观显示系统性能和资源消耗的图表
* 管理多个运行时环境，按位置，业务功能或其他条件进行分组
* 定义和订阅Mule警报

=== 细粒度的ESB控制

* 启动，停止并重新启动ESB资源
* 远程访问，更新或替换Mule ESB服务器上的任何文件或配置
* 查看资源消耗并实时动态调整流量
* 动态配置线程池

=== 企业级安全

* 企业认证（LDAP）
* 细粒度的基于角色的访问控制
* 使用证书和HTTPS保护运行时通信

=== 深入诊断和审核

* 查看有关内存利用率，线程，系统资源和服务器配置的详细信息
* 审计消息流量和流的入站和出站两端的相关属性
* 打开或关闭流量级别审计以捕获足够的数据，以在不影响性能的情况下诊断问题

=== 智能提醒

* 当关键指标超过阈值时接收通知
* 监控单个服务器级别或系统级别的事件
* 将警报升级到管理员或外部监控系统
* 使用警报脚本自定义警报

=== 灵活的集群管理

* 根据条件的要求创建，解散或向节点添加节点
* 监控群集状态 - 获取有关基于群集的流量和内存使用情况的详细信息
* 将应用程序部署到群集以提高可用性，可伸缩性和性能。

=== 深入事件可视化

* 跟踪业务事务流中的关键事件
* 分析业务事务中特定消息的流动和处置
* 钻入事件数据以识别故障点或瓶颈
* 测试流程符合业务流程和标准

== 优点

管理控制台提供以下好处：

* 通过基于组的管理和控制降低管理成本
* 通过快速访问最相关的信息来简化故障排除
* 通过群集增强可用性，可伸缩性和性能
* 通过分析突出显着变化的实时指标来提高可见性和理解度
* 通过智能的主动式警报和补救工具提高应用程序的正常运行时间和性能
* 借助深入的诊断和审核功能，减少停机时间和解决时间
* 对ESB基础架构的运行时性能影响极小
* 通过受控访问运行时诊断信息来改善运营与开发之间的协作
* 深入了解关键业务相关事件
