= 常见任务

下面列出了Mule ESB和管理控制台的常见任务。每节介绍如何完成特定任务，并在需要时提供更多信息的链接。

== 启动Mule ESB服务器

运行位于解压缩Mule ESB EE软件包的下方`\bin`目录中的`mule`文件。例如，在Windows平台上，打开命令窗口，导航到Mule安装`\bin`目录。从命令行中输入`\bin`目录中的`mule`。 （您也可以键入`mule.bat`启动服务器。）

命令窗口显示一系列启动消息。完成后，您可以登录到控制台。

== 打开管理控制台并登录

将浏览器指向URL“+ http://localhost:8585/mmc+` (if you are using the evaluation version of the software) to display the login screen. Otherwise, for a production version, point your browser to the URL `http://localhost:8080/mmc`. Login with the user name `admin` and the password `admin`. For more information, see link:/mule-management-console/v/3.3/how-to-run-the-management-console[如何运行管理控制台]”。

== 注册服务器

对于评估版本，服务器会自动注册到控制台。

如果需要，注册服务器的最简单方法是使用控制台的自动发现功能：控制台会自动感知Mule服务器正在运行，并且可以轻松注册任何"discovered"服务器。单击服务器选项卡，然后单击左侧导航窗格中的未注册节点。该窗口列出所有已联机且尚未注册的服务器。选择要注册的服务器，然后单击注册按钮。您不必指定服务器的URL，因为自动发现功能会执行此操作。

要手动注册服务器，请单击服务器选项卡，然后单击新建服务器按钮。在打开的对话框中，输入服务器的名称和服务器的URL地址。 （请参阅 link:/tcat-server/v/7.1.0/register-a-server[注册服务器]。）

== 查找示例应用程序

[WARNING]
如果您将Mule和管理控制台作为软件包下载，则示例应用程序将预先加载到服务器存储库中。

Mule服务器软件包附带一组示例应用程序，位于`\examples`文件夹中的Mule安装文件夹下。当您打开`\examples)) folder you should see a set of folders, such as {{\hello`，`\loanbroker-simple`，`\stockquote`等等。

`\examples`中的每个文件夹都包含该特定示例应用程序所需的所有文件，以及包含该示例特定说明的README.txt文件。最简单的示例应用程序是`hello`应用程序。如果您刚开始使用，您可能需要使用此`hello`应用程序进行尝试。 （请参阅 link:/mule-management-console/v/3.3/quick-start-guide-to-mule-esb-server-and-the-management-console[找到示例应用程序]。）

== 部署应用程序

要运行应用程序，您必须首先将其部署到注册的服务器。您可以通过单击控制台的“应用程序”选项卡来部署示例应用程序，例如hello应用程序，然后在“所有部署”窗口中单击新建以创建新的部署。

如果应用程序尚未添加到服务器存储库，请单击上载新应用程序按钮以将应用程序上载到服务器存储库并进行部署。请注意，您上传示例应用程序的存档或zip文件。这些存档文件包含部署和运行示例应用程序的所有必需文件。

有关完整说明，请参阅 link:/mule-management-console/v/3.3/deploying-applications[部署应用程序]。

== 运行已部署的应用程序

一旦将应用程序部署到Mule服务器，就可以从任何浏览器窗口运行它。您应该参考每个示例应用程序文件夹中的README.txt文件，以获取有关运行该应用程序的具体说明。

例如，要运行hello示例应用程序，请打开一个新的浏览器窗口或选项卡，然后输入URL `+http://localhost:8888/?name=Simon+`。 （请随意使用"Simon"以外的名称。）

浏览器运行已部署的hello示例应用程序，该应用程序只需使用name参数并将其插入到简单的文本行中。浏览器显示应用程序的输出，例如：Hello Simon，你好吗？

== 审核正在运行的应用程序

运行应用程序后，使用控制台中的Flows和Flow Analyzer选项卡分析应用程序的处理。流程表示应用程序中进行的所有处理的总和，包括路由器，变换器和过滤器。您可以看到有关应用程序流的高级详细信息，以及停止和启动流。

有关更多信息，请参阅 link:/mule-management-console/v/3.3/working-with-flows[使用流程]。

== 分析应用程序消息流

单击流量分析器选项卡打开流量分析器屏幕，使您可以查看有关消息流的详细信息。对于给定的应用程序，您可以看到消息流和消息有效载荷，包括沿着消息处理路由的不同点处的有效载荷之前和之后。

快速入门指南中的 link:/mule-management-console/v/3.3/quick-start-guide-to-mule-esb-server-and-the-management-console[分析应用程序中的消息流]部分说明了如何使用此控制台功能。有关完整的详细信息，请参阅 link:/mule-management-console/v/3.3/analyzing-flow-processing-and-payloads[分析流量处理和有效载荷]。

== 管理SLA和警报

警报使您能够检查服务器上的潜在问题，或监视可能稍后导致服务器问题的情况。您可以通过“警报”窗格定义条件（称为SLA）。这些情况稍后可能会触发控制台显示警告消息，警告消息或提醒您有关问题的情况。

有关使用警报的快速概述，请参阅 link:/mule-management-console/v/3.3/quick-start-guide-to-mule-esb-server-and-the-management-console[添加和管理警报和SLA]。

== 设置用户

首次设置服务器和控制台时，请使用用户名`admin`登录。包`admin`默认提供给用户。您很可能会想要添加额外的用户，尤其是在生产环境中使用Mule ESB的情况下。

使用控制台中的“管理”选项卡来管理用户和角色。您可以定义用户并将这些用户分配给角色，这些角色被称为组。您还可以创建组并为其授予执行特定任务的权限。

有关设置和管理用户的完整信息，请参阅 link:/mule-management-console/v/3.3/managing-users-and-roles[管理用户和角色]。
