= 服务器组

== 关于本文档

本文档以及组成 link:/mule-management-console/v/3.4/rest-api-reference[Mule管理控制台REST API参考指南“]的其他文档仅为技术参考。本文档不提供诸如说明，用例或方案之类的上下文信息。要理解本文档，您应该熟悉Mule运行时，服务器组和 link:/mule-management-console/v/3.4/using-the-management-console-api[REST API]


[%autowidth.spread]
|===
| *Assumptions:*  | *Host*  |本地主机 |  | *Port*  | 8080 {{11 }} | *Deployed app*  | mmc.war  |  | *User/Password*  |管理/管理
|===

有关本文档中使用的格式的详细说明，请参阅 link:/mule-management-console/v/3.4/rest-api-reference[内容组织和公约]。

[source, code, linenums]
----
/api/serverGroups
----

[%autowidth.spread]
|===
| *POST*  |  | *CREATE*
|  |  |
|===

创建一个新的服务器组。

[tabs]
------
[tab,title="-> Request"]
....
== JSON

[source, code, linenums]
----

{
  "name": "NewGroupName"
}
----

[%header%autowidth.spread]
|===
|Key |Type |Summary |Child of
|name |string |Name of the Server Group to be created |--
|===

=== Using CURL on Windows

[source, code, linenums]
----
curl --basic -u admin:admin -d "{ \"name\" : \"NewGroupName\" }" --header "Content-Type: application/json" http://localhost:8080/mmc/api/serverGroups
----

=== Using CURL on Linux

[source, code, linenums]
----
curl --basic -u admin:admin -d '{ "name" : "NewGroupName" }" --header 'Content-Type: application/json' http://localhost:8080/mmc/api/serverGroups
----
....
[tab,title=" <- Response"]
....
== JSON

[source, json, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[%header%autowidth.spread]
|===
|Key |Type |Summary |Child of
|name |String |Name of the created Server Group |--
|id |String |MMC ID for the Server Group |--
|serverCount |String |Number of servers assigned to the Server Group |--
|href |String |Full link to the Server Group resource on which you can perform an operation |--
|===
....
[tab,title="⬇️ Common Return codes"]
....
[%autowidth.spread]
|===
|*201* |The request has been fulfilled and resulted in a new Server Group being created.
|*409* |A server group with that name already exists
|*500* |Error while creating a Server Group
|===
....
[tab,title="MMC version"]
....
[%autowidth.spread]
|===
|*From* |3.2.2
|===
....
------

[%autowidth.spread]
|===
| *GET*  |  | *LIST ALL*
|  |  |
|===

列出所有可用的服务器组。

[tabs]
------
[tab,title="-> Request"]
....
== Using CURL

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/serverGroups
----
....
[tab,title=" <- Response"]
....
== JSON

[source, json, linenums]
----
{
  "total": 1,
  "data": [
    {
      "name": "NewGroupName",
      "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
      "serverCount": 0,
      "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
    }
  ]
}
----

[%header%autowidth.spread]
|===
|Key |Type |Summary |Child of
|total |Integer |The total number of Server Groups |--
|data |Array |An array of server group types |--
|name |String |The identifying name of the server group |data
|id |String |The server group identifier |data
|serverCount |Integer |The number of servers in the server group |data
|href |String |Full link to the Server Group resource to which you can perform an operation |data
|===
....
[tab,title="⬇️ Common Return codes"]
....
[%autowidth.spread]
|===
|*200* |The operation was successful
|===
....
[tab,title="MMC version"]
....
[%autowidth.spread]
|===
|*From* |3.2.2
|===
....
------

[source, code, linenums]
----
/api/serverGroups/{serverGroupId}
----

[%autowidth.spread]
|===
| *GET*  |  | *LIST*
|  |  |
|===

列出特定服务器组的详细信息。

[tabs]
------
[tab,title="-> Request"]
....
== SYNTAX

[source, code, linenums]
----
GET http://localhost:8080/mmc/api/serverGroups/{serverGroupId}
----

[%header%autowidth.spread]
|===
|Key |Type |Summary |Child of
|serverGroupdId |String |ID of the server group to be listed. Invoke link:/mule-management-console/v/3.4/server-groups[LIST ALL] to obtain it |--
|===

== Using CURL

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/serverGroups/37f6cd27-98b3-44b1-97e6-50b75e47f8c1
----
....
[tab,title=" <- Response"]
....
== JSON

[source, json, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[%header%autowidth.spread]
|===
|Key |Type |Summary |Child of
|name |String | |--
|id |String |Id of the Server Group |--
|serverCount |Number of servers belonging to the Server Group | |--
|href |String |Full link to the Server Group resource |--
|===
....
[tab,title="⬇️ Common Return codes"]
....
[%autowidth.spread]
|===
|*200* |The operation was successful
|*404* |A server with that ID was not found
|===
....
[tab,title="MMC version"]
....
[%autowidth.spread]
|===
|*From* |3.2.2
|===
....
------

[%autowidth.spread]
|===
| *PUT*  |  | *RENAME*
|  |  |
|===

重命名特定的服务器组。

[tabs]
------
[tab,title="-> Request"]
....
== JSON

[source, json, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[%header%autowidth.spread]
|===
|Key |Type |Summary |Child of
|name |String |Name of the Server Group to be created |--
|id |String |MMC ID of the Server Group |--
|serverCount |String |Number of servers assigned to the Server Group |--
|href |String |Full link to the Server Group resource on which you can perform an operation |--
|===

=== Using CURL on Windows

[source, code, linenums]
----
curl --basic -u admin:admin -X PUT -d "{\"name\":\"NewName\",\"id\":\"330d9139-4462-4e36-b76c-569776cc3da9\",\"href\": \"http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9\",\"serverCount\":0}" --header "Content-Type:application/json" http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9
----

=== Using CURL on Linux

[source, code, linenums]
----
curl --basic -u admin:admin -X PUT -d '{"name":"NewName","id":"330d9139-4462-4e36-b76c-569776cc3da9","href": "http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9","serverCount":0}' --header 'Content-Type:application/json' http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9
----
....
[tab,title=" <- Response"]
....
== JSON

[source, json, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[%header%autowidth.spread]
|===
|Key |Type |Summary |Child of
|name |String |Name of the Server Group to be created |--
|id |String |MMC ID of the Server Group |--
|serverCount |String |Number of servers assigned to the Server Group |--
|href |String |Full link to the Server Group resource on which you can perform an operation |--
|===
....
[tab,title="⬇️ Common Return codes"]
....
[%header%autowidth.spread]
|===
|*200* |The operation was successful
|*500* |Error while renaming a Server Group
|===
....
[tab,title="MMC version"]
....
[%autowidth.spread]
|===
|*From* |3.2.2
|===
....
------

[%autowidth.spread]
|===
| *DELETE*  |  | *REMOVE*
|  |  |
|===

删除特定的服务器组

[tabs]
------
[tab,title="-> Request"]
....
== SYNTAX

[source, code, linenums]
----
DELETE http://localhost:8080/mmc/api/serverGroups/{serverGroupId}
----

[%header%autowidth.spread]
|===
|Key |Type |Summary |Child of
|serverGroupdId |String |ID of the server group to be listed. Invoke link:/mule-management-console/v/3.4/server-groups[LIST ALL] to obtain it |--
|===

== Using CURL

[source, code, linenums]
----
curl --basic -u admin:admin -X DELETE http://localhost:8080/mmc/api/serverGroups/37f6cd27-98b3-44b1-97e6-50b75e47f8c1
----
....
[tab,title=" <- Response"]
....
== JSON

[source, code, linenums]
----
200 OK
----
....
[tab,title="⬇️ Common Return codes"]
....
[%autowidth.spread]
|===
|*200* |The operation was successful
|===
....
[tab,title="MMC version"]
....
[%autowidth.spread]
|===
|*From* |3.2.2
|===
....
------
