=  MUnit Maven支持
：版本信息：3.7.0和更新
:keywords: munit, testing, unit testing

MUnit提供了一个Maven插件，它允许您将MUnit测试作为持续集成环境的一部分运行。

== 基本设置

=== 设置您的pom.xml文件

MUnit是由几个模块组成的，所有这些模块都是运行MUnit测试所必需的。 Maven提供了尽可能多的灵活性。

为了让MUnit正确运行Maven，您需要在您的`pom.xml`文件中添加几个部分。

提示：如果您使用的是Anypoint Studio，Maven集成已经为您解决了。有关详细信息，请参阅 link:/anypoint-studio/v/6/using-maven-in-anypoint-studio[在Anypoint Studio中使用Maven]。

[NOTE]
--
本文档假定您拥有`pom.xml`中的`<munit.version>`和`<mule.munit.support.version>`属性。 +
例如：

[source,xml,linenums]
----
<munit.version>1.3.5</munit.version>
<mule.munit.support.version>3.7.5</mule.munit.support.version>
----
--


不要组合不同版本的MUnit模块。也就是说，`munit.version`应该与您的`pom.xml`中的所有MUnit构件相同，例如插件或跑步者。

关于Mule MUnit支持模块，`mule.munit.support.version`应该匹配`mule.version`。例如，支持模块的`3.7.0`版本将与`3.7.0`，`3.7.1`，`3.7.2`和其他版本的Mule兼容，但不一定与`3.6.0`兼容。

==  MUnit Maven插件

MUnit Maven插件允许您从Maven运行MUnit测试。要启用该插件，请将以下部分添加到您的`pom.xml`。

[source, xml, linenums]
.MUnit Maven插件
----
<build>
  <plugins>
  ...

    <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-maven-plugin</artifactId>
      <version>${munit.version}</version>
      <executions>
        <execution>
          <id>test</id>
          <phase>test</phase>
          <goals>
            <goal>test</goal>
          </goals>
        </execution>
      </executions>
    </plugin>

  ...
  </plugins>
</build>
----

要了解如何配置插件，请关注我们的 link:/munit/v/1.3/munit-maven-plugin-configuration[Maven插件配置指南]。 +
使用细则可以在 link:/munit/v/1.3/munit-maven-plugin[MUnit Maven插件文档]找到。

====  MUnit文件夹

所有MUnit测试套件文件都位于`src/test/munit`中。你需要告诉Maven将这个文件夹添加到类路径中。

[source, xml, linenums]
.MUnit文件夹
----
<build>
...

  <testResources>
    <testResource>
      <directory>src/test/munit</directory>      // <1>
    </testResource>
    <testResource>
      <directory>src/test/resources</directory>  // <2>
    </testResource>
  </testResources>

...
</build>
----
<1>实际的MUnit测试文件夹。
<2>普通资源文件夹，通常用于存储其他文件。

===  MUnit依赖关系

下面列出了使MUnit能够从Maven运行所需的_minimal artifacts_。

[source, xml, linenums]
.MUnit相关性
----
<dependencies>
...

  <dependency>
    <groupId>com.mulesoft.munit</groupId>
    <artifactId>mule-munit-support</artifactId>
    <version>${mule.munit.support.version}</version>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>com.mulesoft.munit</groupId>
    <artifactId>munit-runner</artifactId>
    <version>${munit.version}</version>
    <scope>test</scope>
  </dependency>

...
</dependencies>
----

===  MUnit存储库

Mueit工件部署在Mule Maven仓库中，您可能已经见过。

[source, xml, linenums]
.Repositories
----
<repositories>
  <repository>
    <id>mulesoft-releases</id>
      <name>MuleSoft Releases Repository</name>
      <url>http://repository.mulesoft.org/releases/</url>
      <layout>default</layout>
    </repository>
</repositories>
----

您还需要添加插件存储库。

[source, xml, linenums]
.Plugin存储库
----
<pluginRepositories>
  <pluginRepository>
    <id>mulesoft-release</id>
    <name>mulesoft release repository</name>
    <layout>default</layout>
    <url>http://repository.mulesoft.org/releases/</url>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </pluginRepository>
</pluginRepositories>
----

提示：如果您使用Java编写MUnit测试代码，则不需要MUnit Maven插件或插件存储库。

==  Surefire支持

MUnit内置了Surefire支持，无需额外配置。

这些报告可以在`target/surefire-reports`中找到。

