= 认证方法

API通常使用几种常见的认证协议。在大多数情况下，您将在Anypoint DevKit连接器中至少实现一种身份验证方法。为帮助您决定使用哪种方法，本文档提供了每种最常用方法的简要说明。

== 基本授权

实质上，这种认证方法要求客户通过输入用户名和密码来证明其真实性。例如，应用程序可能设计为访问用户的Facebook帐户，并检查用户的任何朋友"like"是否拥有自己的帖子。为了使其发挥作用，应用程序必须能够访问用户账户中的私人信息，并且可以通过要求最终用户提供他或她的用户名和密码来实现。

虽然这种身份验证方法可以满足应用程序的需求，但它也为应用程序开启了大量工作，而不仅仅是检查"self-liked"帖子。考虑到这一点，这种方法可能是不可接受的，因为提供用户名和密码凭据可能会导致恶意活动。

== 的OAuth

用户名密码身份验证的一个广泛使用的替代方法是 http://oauth.net/[OAuth的]（授权的开放标准）。 OAuth协议允许第三方应用程序通过备用和受限令牌来限制对资源的访问。通过这种方式，应用程序可以访问用户的帐户，例如，无需知道用户的实际登录凭据，从而限制应用程序执行所选操作。

与其他协议不同，OAuth在Cookie中保留了一个状态（例如，已连接），因此无需在提交每个请求时发送令牌信息。通常，API使用两种版本的OAuth中的一种： http://oauth.net/core/1.0a/[OAuth 1.0a]和 http://tools.ietf.org/html/rfc6749[Oauth 2.0];连接到每个这些是微妙的不同。

有关如何连接到使用OAuth的API的更多详细信息，请访问 link:/anypoint-connector-devkit/v/3.4/implementing-oauth-1.0-authentication[实施OAuth 1.0身份验证]或 link:/anypoint-connector-devkit/v/3.4/implementing-oauth-2.0-authentication[实施OAuth 2.0身份验证]。

== 其他协议

[%header,cols="4*"]
|===
|方法 |描述 |连接器 |何时使用
| *SAML*  |当已知客户联系时，服务会向Id Provider提供密码;客户永远无法访问它们。 | link:/mule-user-guide/v/3.4/saml-module[SAML模块]  |使用 http://saml.xml.org/federated-identity[联合身份]对服务器进行身份验证。
| *Kerberos*  |客户端直接向Id Provider进行身份验证。然后给客户端提供密码，但在只有Web服务可以破解的密钥下编码。客户端将此编码密码发送给Web服务，该服务相信如果它可以破解它，则客户端将得到IdP的认可。 |  *-*  |网络架构允许服务器的不安全网络和客户访问关键提供商。
| *NTLM*  |客户端发送请求; NTLM服务器回应挑战消息，并且客户端回应认证消息。身份验证基于两个散列密码值。 NTLM是一种旧协议，不会实现任何更新的加密方法。 |通过NTLM进行身份验证是可能的，方法是在 link:/mule-user-guide/v/3.4/http-endpoint-reference[HTTP端点]。 |客户端中配置NTLM代理，使用Kerberos或域控制器不可用的网络。
| *LDAP*  |用户名和密码存储在LDAP服务器上的数据库中，而不是服务提供商。确切的认证方法各不相同。有几种可用的方法，包括使用证书和使用传输层安全性（TLS）进行加密。 | http://www.mulesoft.org/connectors/ldap-connector[LDAP连接器]  |只能从服务器访问专用网络（因为它允许存储凭据在客户端无法访问的网络中）。
|===

===  SAML

http://saml.xml.org/[SAML]（安全声明标记语言）是一种XML开放标准，允许第三方提供身份提供服务。在这种模式下，用户的密码位于身份提供商（IdP）服务器中。无论用户何时请求登录Web服务，Web服务都会转向IdP以获取适当的凭据。此解决方案的好处包括最大限度地降低安全风险（减少钓鱼机会）以及简化用户的登录过程。在上面的Facebook示例<<Basic Authorization >>中，应用程序不会知道用户的密码，因为Facebook会从外部IdP请求密码。

=== 的Kerberos

http://web.mit.edu/kerberos/[Kerberos的]是一个开放，复杂的协议，由MIT开发，并由许多其他Active Directory使用。相对于SAML来说，正确设置会更具挑战性，但它非常适合通过非安全网络进行通信，因为身份信息在每个阶段都会进行加密。 IdPs和服务提供商很难在此协议中直接互相交流;他们通过用户向对方发送加密信息。在上面的例子中，应用程序未知用户的密码;虽然它处理密码，但它不能解密它。

===  NTLM

http://msdn.microsoft.com/en-us/library/cc236621.aspx[NTLM]（NT LAN Manager）是Microsoft为Windows网络设计的一套安全协议。它在挑战 - 响应结构中使用三条消息，其中NTLM服务器提供身份验证。客户发送一个谈判请求来宣传其能力; NTLM服务器用挑战消息进行响应，并且客户端用认证消息进行响应。身份验证基于两个哈希密码值：NT哈希和LM哈希。

NTLM是一种旧协议，它没有实现任何更新的加密方法;因此，微软不再推荐它。它用于无法实现Kerberos的客户端，或者用于域控制器不可用的网络。在Active Directory中，NTLM已被Kerberos取代为默认身份验证协议。

===  LDAP

轻量级目录访问协议（LDAP）是一种通过互联网协议（IP）实现分布式目录信息（例如网络用户特权信息）的公共标准。使用LDAP身份验证时，用户名和密码存储在LDAP服务器上的数据库中。您希望对其进行身份验证的实体（无论是服务器，应用程序还是Web服务）查询LDAP服务器，然后授予或拒绝基于响应的身份验证。这可以避免将实体本身的用户名和密码存储在LDAP服务器的数据库中。

严格来说，身份验证发生在您连接的实体和LDAP服务器之间。确切的身份验证方法因实体和LDAP服务器的配置而异。有几种可用的方法，包括使用传输层安全性（TLS）的证书和加密。

== 另请参阅

*  **NEXT:** link:/anypoint-connector-devkit/v/3.4/implementing-connection-management[实施连接管理]。
* 在我们的 link:https://blogs.mulesoft.com/dev/mule-dev/authentication-resource-sharing-over-the-web-oauth-protocol/[MuleSoft博客]上阅读OAuth的基本介绍。
* 详细了解OAuth如何在我们的 link:https://blogs.mulesoft.com/dev/mule-dev/how-to-protect-your-apis-with-oauth/[MuleSoft博客]上运作。
