使用@RestCall注释示例的= 到RESTful API的连接器

为了便于实现连接器的干净设计的RESTful Web服务，DevKit合并了`@RestCall`客户端框架。

`@RestCall`注释可以应用于连接器的`@Connector`类中的方法，这些方法以声明方式描述API上公开的资源的URL。在编译时，DevKit为所有操作生成客户端代码，并为这些方法提供大部分功能。对于特别定义良好的RESTful API，这可以成为快速生成连接器的便捷解决方案。

本文讨论了基于`@RestCall`的连接器的体系结构，介绍了`@RestCall`注释及其用法，最后介绍了一个用于实现一些基本操作的示例Facebook连接器。



== 假设

* 您熟悉RESTful API
* 您熟悉DevKit连接器体系结构，如 link:/anypoint-connector-devkit/v/3.4/anypoint-connector-concepts[Anypoint连接器概念]所述

基于==  `@RestCall`的连接器体系结构

DevKit具有内置的客户端功能，可以处理许多"well-behaved" REST风格的Web服务，需要干净的URL，正确的HTTP动词使用等。

客户端通过您应用于您的`@Connector`类及其方法的一组注释（`@RestCall`注释）公开。

与大多数连接器相比，创建这些连接器需要编写很少的代码

* 您仍然使用属性和方法定义一个`@Connector`类，但在这种情况下，`@Connector`类及其方法都是抽象的。 （与其他连接器类型一样，传递给操作的实体类仍然是具体类。）
* 对于每个操作，应用`@RestCall `注释以提供：+
** 目标资源的URI模板
** 请求的HTTP动词
** 将任何参数替换为URI或发送查询/ POST主体以对请求进行参数化

DevKit在实现抽象方法的子类中生成整个REST客户端。你作为开发人员永远不会看到这个类。

这种简单性是可能的，因为访问定义良好的RESTful API的模式非常一致。

== 关于`@RestCall`客户端和注释

DevKit提供了一组注释来简化使用RESTful API的工作。这些注释处理所有必要的操作，生成每个REST调用并合并每个REST调用参数。

生成的代码基于传递给`@RestCall`注释的参数创建URI，并使用由`@RestCall.`的`method`参数指定的动词发出请求

每个使用`@RestUriParam`批注注释的项目填充URI。在下面的示例中，大括号之间指示的URI的`bucket`部分将替换为`bucketName`的内容，如最后一行的`@RestUriParam`注释中所指定的那样。 （以下示例基于Amazon S3连接器。）

[source, java, linenums]
----
@Processor
@RestCall(uri = "http://{bucket}.s3.amazonaws.com/?max-keys=0", method = HttpMethod.HEAD)
    public abstract Object bucketExists(@RestUriParam("bucket"),
         String bucketName);
----

如下所述，您可以在连接器的`@Processor`方法参数或`@Configurable`字段上使用`@RestUriParam`注释以及其他相关注释。

当生成请求调用时，DevKit包含一个未注释的参数和一个用`@Payload`注释的参数作为调用的主体。

==  `@RestCall`注释参考

以下各节详细介绍了针对RESTful API实现连接器的全套注释。

===  `@RestCall`

与`@Processor`注释一起使用。指示调用时，处理器将发出RESTful请求。

===== 必需的参数：

*  `uri`：要查询的REST资源的URI
*  `method`：使用的HTTP方法

[source, java, linenums]
----
@Processor
@RestCall(uri = "http://mybucket.s3.amazonaws.com/?max-keys=0",
   method = HttpMethod.HEAD)
   public abstract Object bucketExists("mybucket")
   String bucketName);
----

上面的例子使用了一个静态URI。有关使用动态生成的URI的详细信息，请参阅 link:/anypoint-connector-devkit/v/3.4/connector-to-restful-api-with-restcall-annotations-example#code-resturiparam-code[@RestURIParam]。

===  `@RestQueryParam`

指定URI查询参数，这些参数在`?`或`&`符号之后附加到URI的路径中。您可以将此注释应用于`@Processor`方法参数或标记为`@Configurable`的连接器字段。这使您可以将动态生成的参数用作查询参数。

===== 必需的参数：

* 要附加的参数的名称的字符串表示形式

[source, java, linenums]
----
@RestCall(uri = ("http://myservice.com/standard?id=1234",
   method = org.mule.api.annotations.rest.HttpMethod.GET)
   ...
   Public abstract String getID(@RestQueryParam("id")
   String numID)
----

===  `@RestURIParam`

允许您插入属于URI路径本身的URI参数，这是一些URI所必需的。与`@RestQueryParam`批注一样，您可以将此批注应用于`@Processor`方法参数或标记为`@Configurable`的连接器区域。这使您可以使用动态生成的参数作为URI参数。

===== 必需的参数：

* 将用URI参数替换消息处理器的参数

要使用`@RestURIParam`注释，您必须在URI中指定参数，然后使用大括号将其包含在注释中。在下面的例子中，参数是`{path`}。

[source, java, linenums]
----
@RestCall(uri = "http://myservice.com/{path}", method = HttpMethod.HEAD)
----

引用`@RestURIParam`注释中的参数：

[source, code, linenums]
----
...
Public abstract String setPath(@RestURIParam String path ...
----

===  `@RestHeaderParam`

允许您在呼叫中插入自定义标题。您可以将此注释应用于`@Processor`方法参数或注释中标记的HTTP标头的`@Configurable`字段。这使您可以将动态生成的参数用作查询参数。

===== 必需的参数：

* 要包含在呼叫中的标题的名称。

[source, java, linenums]
----
@RestHeaderParam("AuthorizationCode")
@Configurable private String authorizationCode;
@Processor
@RestCall(uri = "http://\{bucket\}.s3.amazonaws.com/?max-keys=0",
   method = HttpMethod.HEAD)
   public abstract Object bucketExists(@UriParam("bucket")
   String bucketName);
----

===  `@RestPostParam`

允许您在Post方法调用的主体中设置参数。您可以将此批注应用于`@Processor`个方法参数或标记为`@Configurable`的连接器字段。 DevKit确保您仅将此注释应用于Post方法。

使用`@RestPostParam`注释的处理器方法不能使用未注释的参数或带有`@Payload`注释的参数。

== 实施`@RestCall`连接器

本文档的其余部分将引导您完成`@RestCall`连接器。您可以按照逐字逐句构建此示例，或者您可以应用相同的过程为您自己的API构建连接器。

=== 示例`@RestCall`连接器：Facebook Graph API

Facebook Graph API是应用程序将数据导入和导出Facebook社交图并与Facebook平台进行交互的主要方式。请参阅Facebook的https://developers.facebook.com/docs/getting-started/graphapi/[Getting Started：Graph API]以了解背景。

本讨论是围绕使用OAuth身份验证的Facebook Graph API的示例连接器构建的，并提供两种操作：

* 以用户对象的形式检索指定用户的配置文件信息
* 在指定用户的Facebook时间轴上发布更新

准备：设置Facebook图形API访问权限。=== 

Graph API支持读取公共信息的未经身份验证的访问，但需要OAuth2身份验证才能进行写入访问。对Graph API的OAuth2访问要求您：

* 注册Facebook开发者帐户
* 创建Facebook应用程序（将Facebook客户端应用程序与Facebook服务器上的开发者帐户标识关联起来）

有关设置经过身份验证的API访问权的Facebook文档， http://developers.facebook.com/docs/samples/meals-with-friends/register-facebook-application/[到这里]。 Facebook将生成*Consumer Key*和*Consumer Secret*，您需要完成该练习。

== 实现`@Connector`类

RestCall客户端可以与`@OAuth`认证注释或连接管理框架一起使用。在这种情况下，Facebook连接器使用OAuth 2.0身份验证。抽象`@Connector`类`FacebookConnector`在类上获得`@RestCall`注释和与OAuth相关的注释。

以下代码片段摘自`@Connector`类`FacebookConnector`：

[source, code, linenums]
----
/**
 * Facebook oauth2 connector
 *
 */
@OAuth2(accessTokenUrl = "https://graph.facebook.com/oauth/access_token",
        authorizationUrl = "https://graph.facebook.com/oauth/authorize",
        accessTokenRegex = "access_token=([^&]+?)&", expirationRegex = "expires=([^&]+?)$")
@Connector(name = "facebook-connector")
public abstract class FacebookConnector {
 
    /**
     * Your application's client identifier (consumer key in Remote Access Detail).
     */
    @Configurable
    @OAuthConsumerKey
    private String consumerKey;
 
 
    /**
     * Your application's client secret (consumer secret in Remote Access Detail).
     */
    @Configurable
    @OAuthConsumerSecret
    private String consumerSecret;
 
    //@RestQueryParam("access_token")
    @OAuthAccessToken
    private String accessToken;
 
 
    @OAuthCallbackParameter(expression = "#[json:id]")
    private String userId;
 
    @OAuthAccessTokenIdentifier
    public String getUserId() {
        return userId;
    }
 
 
    /* ...getters and setters omitted */
}
----

注意：

* 类`FacebookConnector`是一个抽象类，如RestCall连接器所需。
*  OAuth2注释用于相关方法和属性，如 link:/anypoint-connector-devkit/v/3.4/implementing-oauth-2.0-authentication[实施OAuth 2.0身份验证]中所述。
现在* 操作代码被省略。

== 实现数据模型实体类

您将必须定义任何实体类，这些实体类表示传递给Web服务请求并从Web服务请求返回的数据，以及JSON文档如何映射到与连接器一起使用的Java类。

如果为该服务提供了JSON模式或示例文档，则可以使用工具*JSONSchema2POJO*生成类， http://www.jsonschema2pojo.org/. (The https://github.com/joelittlejohn/jsonschema2pojo/wiki[Github上的Wiki]中提供了该工具，并开始使用JSONSchema2POJO的参考文档。）

一旦创建了数据模型类，将它们添加到您的项目并将它们导入到您的`@Connector`类中。

=== 示例：Facebook用户类

对于我们的示例，类User是用于将有关Facebook用户的数据传递给API的实体类。必须先定义并添加到项目中，然后才能实施使用它的操作。

User.java的完整定义如下：

[source, java, linenums]
----
package com.fb;
import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.codehaus.jackson.annotate.JsonAnyGetter;
import org.codehaus.jackson.annotate.JsonAnySetter;
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.annotate.JsonPropertyOrder;
import org.codehaus.jackson.map.annotate.JsonSerialize;
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "id",
    "name",
    "first_name",
    "last_name",
    "link",
    "username",
    "gender",
    "locale"
})
public class User {
    /**
     * the user id
     *
     */
    @JsonProperty("id")
    private String id;
    /**
     * the user name
     *
     */
    @JsonProperty("name")
    private String name;
    /**
     * the user first name
     *
     */
    @JsonProperty("first_name")
    private String first_name;
    /**
     * the user last name
     *
     */
    @JsonProperty("last_name")
    private String last_name;
    /**
     * the user last name
     *
     */
    @JsonProperty("link")
    private String link;
    /**
     *
     *
     */
    @JsonProperty("username")
    private String username;
    /**
     *
     *
     */
    @JsonProperty("gender")
    private String gender;
    /**
     *
     *
     */
    @JsonProperty("locale")
    private String locale;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();
    /**
     * the user id
     *
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }
    /**
     * the user id
     *
     */
    @JsonProperty("id")
    public void setId(String id) {
        this.id = id;
    }
    /**
     * the user name
     *
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }
    /**
     * the user name
     *
     */
    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }
    /**
     * the user first name
     *
     */
    @JsonProperty("first_name")
    public String getFirst_name() {
        return first_name;
    }
    /**
     * the user first name
     *
     */
    @JsonProperty("first_name")
    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }
    /**
     * the user last name
     *
     */
    @JsonProperty("last_name")
    public String getLast_name() {
        return last_name;
    }
    /**
     * the user last name
     *
     */
    @JsonProperty("last_name")
    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }
    /**
     * the user last name
     *
     */
    @JsonProperty("link")
    public String getLink() {
        return link;
    }
    /**
     * the user last name
     *
     */
    @JsonProperty("link")
    public void setLink(String link) {
        this.link = link;
    }
    /**
     *
     *
     */
    @JsonProperty("username")
    public String getUsername() {
        return username;
    }
    /**
     *
     *
     */
    @JsonProperty("username")
    public void setUsername(String username) {
        this.username = username;
    }
    /**
     *
     *
     */
    @JsonProperty("gender")
    public String getGender() {
        return gender;
    }
    /**
     *
     *
     */
    @JsonProperty("gender")
    public void setGender(String gender) {
        this.gender = gender;
    }
    /**
     *
     *
     */
    @JsonProperty("locale")
    public String getLocale() {
        return locale;
    }
    /**
     *
     *
     */
    @JsonProperty("locale")
    public void setLocale(String locale) {
        this.locale = locale;
    }
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }
    @Override
    public int hashCode() {
        return HashCodeBuilder.reflectionHashCode(this);
    }
    @Override
    public boolean equals(Object other) {
        return EqualsBuilder.reflectionEquals(this, other);
    }
    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }
    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }
}
----

注意：

*  `@Generated("com.googlecode.jsonschema2pojo")`注释表示该类是使用https://github.com/joelittlejohn/jsonschema2pojo/wiki/Getting-Started#the-maven-plugin[JSONSchema2POJO]工具生成的，该工具托管于http://www.jsonschema2pojo.org/。
* 来自包`org.codehaus.jackson.annotate`的多个导入以及所使用的特定注释（例如`@JsonProperty, @JsonAnySetter, @JsonAnyGetter`）反映了RestCall客户端在内部使用Jackson对与服务交换的JSON数据进行序列化和反序列化的事实。务必在Jackson模式下使用JSONSchema2POJO。

== 将操作添加到`@Connector`类

在`@Connector`类上实现操作时，请注意，对于RESTCall连接器，操作方法（如类本身）是抽象的。方法的注释指定：

*  REST网址的模板，带有参数占位符
* 值为：+
** 替换网址中的占位符
** 附加为GET查询参数，
** 在POST正文中发送
* 期望作为返回值的类
* 要使用的HTTP请求方法（例如，GET，POST或PUT）

[WARNING]
====
*Apply a Test-Driven Approach*

当涉及到向连接器添加操作时，许多成功的项目都遵循类似于测试驱动开发的周期。

首先，确定操作的详细要求：

* 实体（POJO或具有特定内容的地图）可以将其作为输入接受或作为响应返回
* 针对一系列有效和无效输入的预期响应
* 操作在服务不可用时可能引发的异常，例如：+
** 身份验证失败
** 输入无效

然后，重复以下循环，直到完成所有计划的功能：

* 创建覆盖预期行为的JUnit测试，如 link:/anypoint-connector-devkit/v/3.4/developing-devkit-connector-tests[开发DevKit连接器测试]中所述
* 实现功能以满足这些要求，如下所示：+
** 定义所需的任何新实体类（并根据需要对它们进行注释以映射到/来自JSON）
** 创建或增强客户端类中的方法和`@Connector`类中的`@Processor`方法以添加功能
** 使用必要的代码段评论更新您的`@Connector`类
** 运行Maven构建以运行JUnit测试并修复所有错误，直到所有测试通过

继续操作，直到涵盖所有操作的所有功能。完成之后，您将为连接器提供完整的验证套件，以便在目标服务，连接器本身，Mule ESB或DevKit发生更改时捕获任何回退。

您可能会问，"When do I try my connector in Studio? Why can't I just test manually?"。除了自动化的JUnit测试外，随时随地手动测试每个操作也很有用（也是令人欣慰的）：

* 您可以在工作中看到基本的操作功能
* 您可以查看连接器在Studio用户界面中的显示方式，这些自动化单元测试无法显示给您

在Studio中进行测试将提供机会来优化连接器的可用性，通过合理的默认设置改进体验，并通过更好的Javadoc注释来填充工具提示等等。

但是，这并没有削弱测试驱动方法的价值。许多连接器开发项目由于未能提供精心策划的测试套件而陷入困境或产生难以使用或不可靠的连接器 - 它更多的是前期工作，但它确实带来了更快，更好的结果。

有关如何开发连接器测试的详细信息，请参阅 link:/anypoint-connector-devkit/v/3.4/developing-devkit-connector-tests[开发DevKit连接器测试]。
====

=== 示例：`FacebookConnector`操作方法

该连接器将公开以下定义的`getUser()`和`publishWall()`操作。

[source, code, linenums]
----
/**
     * GET a user profile.
     * {@sample.xml ../../../examples/Facebook.default.xml.sample facebook-connector:default}
     *
     * @param user
     *     Represents the ID of the user object.
     * @param metadata
     *     The Graph API supports introspection of objects, which enables you to see all of the connections an
     *                         object has without knowing its type ahead of time.
     * @return  a User object.
     * @throws IOException
     *      when the call fails
     */
    @Processor
    @RestCall(uri = "https://graph.facebook.com/{user}", method = HttpMethod.GET)
    public abstract User getUser(
        @RestUriParam("user") String user,
        @RestQueryParam("metadata") String metadata)
        throws IOException
    ;
 
 
    /**
     * post a message on a user's wall
     * {@sample.xml ../../../examples/Facebook.default.xml.sample facebook-connector:default}
     *
     * @param message
     *     message to be published
     * @param user
     *     user id
     * @return  No return information available
     * @throws IOException
     *      when the call fails
     */
    @OAuthProtected
    @Processor
    @RestCall(uri = "https://graph.facebook.com/{user}/feed", method = HttpMethod.POST, contentType = "application/json")
    public abstract String publishWall(
        @RestUriParam("user") String user,
        @RestPostParam("message") String message)
        throws IOException
    ;
----

注意：

*  `getUser()`没有`@OAuthProtected`注释。 Facebook允许即使没有身份验证也可以获得一些用户信息（尽管根据经过身份验证的用户与所请求用户的关系，所请求用户的隐私设置等，可能会通过身份验证返回更完整的响应。
* 发布到墙上需要身份验证，所以它被注释@OAuthProtected。

== 另请参阅

一旦你有一个连接器可以很好地安装在Studio中并通过基本的单元测试，你可以：

* 继续通过上述迭代过程添加操作，直到您拥有所需的操作和测试用例来验证所有期望的行为。
* 按 link:/anypoint-connector-devkit/v/3.4/customizing-connector-integration-with-esb-and-studio[定制连接器与ESB和Studio集成]中所述，通过更多注释优化连接器对话框和XML元素的外观。
* 您也可以返回到 link:/anypoint-connector-devkit/v/3.4/devkit-shortcut-to-success[DevKit成功的捷径]。
