= 自定义连接器与ESB和Studio的集成

默认情况下，DevKit从Java文件中的方法，参数，JavaDoc注释和实例变量名称推断Studio对话框的名称和标签。不过，您也可以使用注释来定制组件外观的许多方面，以改善用户体验。

* 参数如何在XML中公开
* 数据如何传入和传出连接器
*  Studio调色板和流程中连接器的外观
*  Studio中连接器属性对话框的布局



[NOTE]
包` org.mule.api.annotations.display `定义了允许您执行这些自定义的注释。

[TIP]
====
为确保这些注释的添加能够被构建正确反映，请重新构建您的连接器。在包含项目`pom.xml`的目录中运行以下命令：

[source, code, linenums]
----
mvn clean package -Ddevkit.studio.package.skip=false
----

这将清除任何可能干扰正确处理这些注释的旧版本产品。
====

==  @展示位置：字段顺序，分组和选项卡

将此注释应用于实例变量和方法参数。它接受以下参数：

*  *order*  - 组内注释元素的相对顺序。如果提供的值是重复的，那么这些元素的顺序是任意定义的。价值是相对的;具有顺序10的元素具有比具有值25的元素更高的优先级。
*  *group*  - 一种显示一个或多个变量的逻辑方法。如果你没有指定一个组，那么Mule会默认一个默认组。要将多个元素放置在同一组中，请为此属性分配相同的值。
*  *tab*  - 将注释元素分组在一起的合理方法。此属性指定要在其中显示注释元素的选项卡的名称。如果没有指定标签，那么Mule将采用默认标签。要在同一选项卡中显示多个参数，请为此属性分配相同的值。

==  @友好名称：字段标签

将此注释应用于实例变量和方法参数，以提供覆盖`@Configurable`变量或`@Processor` / `@Source` / `@Transformer`方法参数的默认推断昵称的方法。

==  @密码：屏蔽字段内容

应用此批注将字段或方法参数标识为密码，或者更一般地说，将其作为包含不应以纯文本显示的数据的变量。

==  @总结：简短说明

将此注释应用于实例变量和方法参数，以提供覆盖`@Configurable`变量或`@Processor` / `@Source` {`@Transformer`方法参数的默认推断描述的方法。

==  @图标：自定义调色板和流程编辑器图标

将`@Icons`注释应用于连接器类以覆盖一个或多个所需图标的默认位置。路径需要相对于`/src/main/java`。
