= 在连接器上定义@Configurable属性

与所有Mule元素一样，连接器具有可以在Mule配置XML文件中分配的属性，并可以在元素的属性对话框中进行设置。 `@Configurable` DevKit注释定义了使用连接器时可以设置的连接器上的属性。 `@Connector`可以具有任意数量的简单或复杂的`@Configurable`属性。



== 假设

您熟悉用于配置元素的Mule XML语法。

== 创建@Configurable属性

`@Configurable`注释指示生成器通过XML语法或连接器配置对话框为您的连接器的每个实例创建一个可配置的属性。除了`@Configurable`注释之外，您还需要一个公共getter和一个公共setter。

例如：

[source, java, linenums]
----
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Connector;
 
@Connector(name = "myconnector")
public class MyConnector {
 
    @Configurable
    private String key;
 
    public String getKey(){
        return this.key;
    }
    public void setKey(String key) {
       this.key = key;
    }
----

然后按如下方式配置模块或连接器：

[source, xml, linenums]
----
<myconnector:config key="myKey" />
----

== 制作属性@可选

`@Configurable`属性是强制性的，除非用`@Optional`注释标记。使用连接器时，可以省略`@Optional` `@Configurable`个属性。

例如：

[source, java, linenums]
----
@Module(name = "mymodule")
public class MyModule {
  
    @Configurable
    @Optional
    private String key;
  
    public String getKey(){
        return this.key;
    }
    public void setKey(String key) {
       this.key = key;
    }
----

然后按如下所示配置连接器：

[source, xml, linenums]
----
<myconnector:config key="myKey" />
----

 以下内容也是有效的，因为赋值是可选的：

[source, xml, linenums]
----
<myconnector:config />
----

== 添加@Default属性值

对于`@Optional`可配置属性，如果省略属性，则使用`@Default`注释指定默认值。

例如：

[source, java, linenums]
----
@Module(name = "mymodule")
public class MyModule {
  
    @Configurable
    @Optional
    @Default("testKey")
    private String key;
  
    public String getKey(){
        return this.key;
    }
    public void setKey(String key) {
       this.key = key;
    }
----

然后连接器可以配置如下：

[source, xml, linenums]
----
<myconnector:config key="myKey" />
----

如果`key`属性不存在，则将按照`@Default`注释的定义隐式分配值`testKey`：

[source, xml, linenums]
----
<myconnector:config />
----

== 自定义属性以提高可用性

您可以（也应该）使用多个注释来控制属性在Studio中的属性对话框和连接器文档中的显示方式：

*  `@FriendlyName`设置属性对话框中显示的属性名称
*  `@Placement`会影响属性对话框中的位置
*  `@Summary`为操作提供了一个简短描述（在Studio中用作工具提示）

有关这些注释的更多信息，请参阅 link:/anypoint-connector-devkit/v/3.4/customizing-connector-integration-with-esb-and-studio[定制连接器与ESB和Studio集成]。

== 复杂数据类型和可配置属性

DevKit支持复杂类型的可配置属性，例如枚举类型和集合。有关更多详情，请参阅 link:/anypoint-connector-devkit/v/3.4/handling-data-types-for-configurable-properties[处理可配置属性的数据类型]。

== 下一步

根据您的使用案例选择一种客户实施风格：

*  link:/anypoint-connector-devkit/v/3.4/connector-to-java-client-library-example[连接到Java客户端库示例]
*  link:/anypoint-connector-devkit/v/3.4/connector-to-soap-service-via-cxf-client-example[通过CXF客户端示例连接到SOAP服务]
*  link:/anypoint-connector-devkit/v/3.4/connector-to-restful-service-with-jersey-client-example[使用Jersey客户端示例连接到RESTful服务]
*  link:/anypoint-connector-devkit/v/3.4/connector-to-restful-api-with-restcall-annotations-example[使用RESTCall注释示例连接到RESTful API]
