= 检查生成的连接器项目

本文档描述了Maven在 link:/anypoint-connector-devkit/v/3.4/creating-a-connector-project[创建你的连接器项目]时为您生成的文件夹结构和文件。

== 假设

本文档假设您 link:/anypoint-connector-devkit/v/3.4/creating-a-connector-project[创建一个新的连接器项目]。

== 源文件夹

*Source Folder*收集最终构建目标文件夹所需的所有输入。您运行的第一个Maven命令使用Mule连接器原型在源文件夹中生成一个框架，该框架包含下表中描述的四条路径。

[%header%autowidth.spread]
|===
| {夹{1}}说明
| `src/main/java`  |包含连接器的源Java文件，包括连接器的骨架Java文件。在添加其他类时，项目将它们存储在此文件夹中。
| `src/main/resources`  |包含您的连接器访问的非代码资源。最初创建项目时，该文件夹为空。
| `src/test/java`  |包含连接器测试文件的Java源代码，包括骨架JUnit测试用例。
| `src/test/resources`  |包含您的测试访问的非代码资源。该文件夹包含用于运行测试的骨架Mule配置文件。
|===

== 连接器类

打开`src/main/java/org/hello/HelloConnector.java`文件。该类定义连接器的主类，并包含重要的`@Connector`注释。

DevKit已经创建了一个类和几个方法，并用*annotations*标记。注释告诉Mule如何以特定的，预定义的方式调用和处理你的类，方法或参数。他们是你需要管理的与Mule联系的唯一联系人。

`@Connector`

适用于连接器类本身的连接器的顶级注释是`@Connector`。该注释通知DevKit Java类将用作连接器。

[source, code, linenums]
----
/**
* Cloud Connector
*
* @author MuleSoft, Inc.
*/
@Connector(name="myConnector", schemaVersion="1.0-SNAPSHOT")
public class myConnector
{
 
    /**
    * Configurable
    */
    @Configurable
    private String myProperty;
 
    [...]
 
}
 
[...]
----

`@Connector`注释包含多个参数，其中两个参数是由原型`name`和`schemaVersion`自动生成的。您可以定义其他参数，如下表所述。

[%header%autowidth.spread]
|===
|注释类型元素 |描述 |是否必需？ |默认值
| *`name`*  |连接器的名称。此值必须是简单的字符串，不得有空格。  |✓ | 
| *`schemaVersion`*  |由DevKit生成的模式版本。 |   | `1.0-SNAPSHOT`
| *`friendlyName`*  |这是连接器的人类可读名称。它可以包含空格。 Mule仅用它来标记调色板Studio中的连接器。  |   | 
| *`description`*  |描述连接器及其操作的较长文本字符串。 Mule Studio将描述显示为工具提示。 |   | 
| *`namespace`*  |连接器的名称空间。 |   | `+http://www.mulesoft.org/schema/mule/name+`
| *`schemaLocation`*  |写入`spring.schemas`文件的模式文件的位置。 |   a | `+http://www.mulesoft.org/schema/mule/name/schemaVersion/mule-name.xsd+`

和

`http://www.mulesoft.org/schema/mule/name/current/mule-name.xsd`
| *`minMuleVersion`*  |连接器可以使用的最小Mule版本。 Mule在运行时检查版本，并在版本不兼容时引发错误。 |   |当前版本的DevKit
|===

以下限制适用于`@Connector`注释。

*  `@Connector`不能应用于接口
*  `@Connector`不能应用于最终类
*  `@Connector`不能应用于参数化类
*  `@Connector`不能应用于非公共类
具有`@Connector`的类* 必须只包含一个用`@Connect`注释的方法
具有`@Connector`的类* 必须只包含一个用`@Disconnect`注释的方法

== 连接器测试

打开`src/test/java/org/hello/HelloConnectorTest.java`文件。 DevKit创建一个类，几个方法和一个可配置属性，并用注释标记它们。在本课程的方法中，您可以编写适合您测试需求的自己的测试。每次编译代码时都会评估这些测试。您也可以通过从控制台运行以下Maven命令来运行这些测试，而无需构建连接器。

[source, code, linenums]
----
mvn test
----

有关为连接器开发测试的更多详细信息，请参阅 link:/anypoint-connector-devkit/v/3.4/developing-devkit-connector-tests[开发DevKit连接器测试]。

==  POM文件

基于用于创建项目的原型，Maven生成项目对象模型（POM）文件。 Maven使用`pom.xml`文件来跟踪构建项目所需的所有依赖项，包括依赖项的版本号和位置。您可能必须在连接器开发过程中将项目添加到POM文件，以便拉入其他库并向构建过程添加步骤。

有关POM文件角色的更多详细信息，请参阅 http://maven.apache.org/pom.html[在maven.apache.org上的POM参考]。

== 图标文件夹

`icons`文件夹包含Mule Studio用来在调色板和画布上表示连接器的视觉效果。您可以轻松地将这些文件与您选择的其他文件交换。你也可以从其中Mule获取它们的 link:/anypoint-connector-devkit/v/3.4/customizing-connector-integration-with-esb-and-studio[修改文件夹]。

== 许可和自述文件

如果您决定与Mule社区共享您的连接器，您的项目将包含基本的许可协议。您可以免费使用 link:/anypoint-connector-devkit/v/3.4/packaging-your-connector-for-release[更改此许可协议]。使用README文件为用户提供有关连接器的初始信息。这些文件是用https://help.github.com/articles/github-flavored-markdown[Github-Flavored Markdown]格式（`.md` `)`）编写的。

== 目标文件夹

当构建过程成功并且`test`文件夹中定义的测试全部通过时，Maven构建过程会在目标文件夹中创建多个构件。如果您运行构建过程并且没有在包资源管理器中看到该文件夹​​，请右键单击项目名称，然后选择**Refresh **查看以下新元素：

*  `hello-connector-1.0-SNAPSHOT.jar`，连接器JAR
*  `hello-connector-1.0-SNAPSHOT.zip`，Mule插件，您可以将它放入Mule独立版的`plugins`目录
*  `apidocs`，为您的连接器自动生成安装说明，Javadoc和Mule API文档
*  `update-site`，您导入到Mule Studio中的文件，用于安装和更新连接器

== 参考文档

构建还会为您的连接器自动生成Javadoc。 Maven生成的框架文件已包含占位符注释（包含在`/**`和`*/`之间），您可以进一步更新。在向连接器添加功能时，确保在代码中严格添加JavaDoc注释，因为Mule会在构建过程中自动将注释合并到自动生成的文档中。

要查看文档，请在Web浏览器中打开`target/apidocs/index.html`。

[source, code, linenums]
----
/**
     * Connect
     *
     * @param username A username
     * @param password A password
     * @throws ConnectionException
     */
    @Connect
    public void connect(@ConnectionKey String username, String password)
        throws ConnectionException {
        /*
         * CODE FOR ESTABLISHING A CONNECTION GOES IN HERE
         */
    }
 
 
    /**
     * Custom processor
     *
     * {@sample.xml ../../../doc/hello-connector.xml.sample hello:my-processor}
     *
     * @param content Content to be processed
     * @return Some string
     */
    @Processor
    public String myProcessor(String content)
    {
        /*
         * MESSAGE PROCESSOR CODE GOES HERE
         */
 
        return content;
    }
----

=== 文档最佳实践

DevKit强制评论你的代码。对于您编写的每种方法，请添加相应的注释部分，以便在构建连接器时立即记录连接器的功能。在这些注释部分中，列出注释`@param`和`@return`的方法的每个参数和每个输出。

DevKit将上述示例代码中的`@param`和`@return`内容拖放到Javadoc中，自动对其进行组织，格式化并包含额外的标准内容。

   

== 另请参阅

连接器上的*  *NEXT STEP:* link:/anypoint-connector-devkit/v/3.4/authentication-and-connection-management[实施认证]。
* 详细了解 link:/anypoint-connector-devkit/v/3.4/installing-and-testing-your-connector[安装和测试连接器]。
* 查看完整的DevKit构建的 link:/anypoint-connector-devkit/v/3.4/devkit-connector-examples[连接器示例]以查看更完整开发的代码，文档和测试套件。
