= 实施OAuth 1.0身份验证

本页面详细讨论了DevKit对OAuth 1.0身份验证的支持，以及如何在连接器中实现OAuth 1.0支持。

== 假设

本文假设您在Mule Studio中有 link:/anypoint-connector-devkit/v/3.4/creating-a-connector-project[创建一个连接器项目]， link:/anypoint-connector-devkit/v/3.4/installing-and-testing-your-connector[安装和测试]，并准备在您的连接器上实施身份验证。它假定您熟悉各种 link:/anypoint-connector-devkit/v/3.4/authentication-methods[认证方法]并将 link:/anypoint-connector-devkit/v/3.4/authentication-and-connection-management[比较DevKit中的认证支持选项]和选定的OAuth 1.0作为您的选择。

本文档还假定您已经对 link:/anypoint-connector-devkit/v/3.4/anypoint-connector-concepts[Anypoint连接器概念]中提供的连接器体系结构有一般的了解，尤其是将连接器分为@Connector类和客户端类。实现OAuth 1支持需要向每个类添加代码。另外，您应该熟悉OAuth 1.0，如 http://oauth.net/core/1.0/[OAuth Core 1.0文档]中所述。

==  @OAuth注释的概述

要实现OAuth 1.0，您需要在@Connector类中使用`@OAuth`注释。此注释触发DevKit对OAuth 1的支持。

用@OAuth注释的连接器会获得另外两个称为`authorize`和`unauthorize`的@Processor方法。这些消息处理器启动并结束OAuth会话。

下表介绍了`@OAuth`批注的所有参数。

[%header,cols="4*"]
|===
一个|
*Parameter*

 为|
*Description*

 为|
*Required?*

 为|
*Default Value*

| `messageSigner`  |在+中使用的签名方法
  OAuth 1.0a流程;此方法包含在`auth_signature_method`参数中。 |   | `HMAC_SHA1`
| `signingStrategy`  |定义应包含OAuth 1.0a参数的位置。 |   | `AUTHORIZATION_HEADER`
| `requestTokenUrl`  |服务提供商定义的URL用于获取未经授权的请求令牌。 |✓ | 
| `accessTokenUrl`  |服务提供商为获取访问令牌而定义的网址。 |✓ | 
| `authorizationUrl`  |由服务提供商定义的网址，其中资源所有者被重定向以授予用户授权。 |✓ | 
| `verifierRegex`  |在资源所有者授权使用者后，Java正则表达式用于从服务提供者响应中提取验证者。 | { {1}}
| `callbackPath`  |如果服务提供商只接受已知的重定向网址。将此参数分配给域中的路径（由`fullDomain`环境变量表示），该路径将作为重定向URL在服务提供商处注册。如果留空（表示服务提供商接受任何URL作为重定向URL），Mule将使用随机路径。 |   | `<random path>`
|===

== 实施OAuth 1.0a支持

以下讨论总结了@Connector和客户端类中为支持OAuth 1所需的更改。有关使用Jersey客户端实现RESTful Web Service的OAuth 1.0a支持的更详细的演练，请参见 link:/anypoint-connector-devkit/v/3.4/connector-to-restful-service-with-jersey-client-example[使用Jersey客户端示例连接到RESTful服务];本讨论的重点在于示例LinkedIn连接器中提供的OAuth功能。

===  Maven项目依赖项

要使用DevKit实现对OAuth 1.0的授权，您必须将以下依赖项添加到您的Maven `pom.xml`文件中：

[source, xml, linenums]
----
<dependency>
       <groupId>oauth.signpost</groupId>
       <artifactId>signpost-core</artifactId>
       <version>1.2.1.1</version>
</dependency>
----

=== 所需的API信息

从服务提供商的API文档中，获取下表中列出的变量的值。这些变量引用授权过程中使用的URL;有关此过程的这些步骤的详细信息，请参阅 http://oauth.net/core/1.0a/[OAuth 1.0a规范]的{​​{0}}部分。

[%header%autowidth.spread]
|===
| {变量{1}}说明
| `requestTokenUrl`  |从中获取请求令牌的URL
| `accessTokenUrl`  |从中获取访问令牌的URL
| `authorizationUrl`  |来自URL以获取资源访问权限
|===

您还必须安排访问该服务的API。该过程针对每个API提供者。 link:/anypoint-connector-devkit/v/3.4/preparing-api-access-or-a-sandbox-environment[准备API访问或沙箱环境]中介绍了此过程的典型步骤。

=== 在@Connector类中添加@OAuth注释

将@OAuth注释添加到@Connector类中，如下所示：

[source, java, linenums]
----
@Connector(name = "rest-jersey", schemaVersion = "1.0", friendlyName = "REST Jersey Example")
@OAuth(
        requestTokenUrl = "https://api.dropbox.com/1/oauth/request_token",
        accessTokenUrl = "https://api.dropbox.com/1/oauth/access_token",
        authorizationUrl = "https://www.dropbox.com/1/oauth/authorize",
        verifierRegex = "oauth_token=([^&]+)")
 
 
// If an Exception with message "OAuth authorization code could not be extracted from:" is thrown after authenticate, check the parameter returned in the response
// By default is looking for a "oauth_verifier=([^&]+)" verifierRegex
// Example of one of my responses "http://localhost:8090/callbackresponse?uid=SOME_ID&oauth_token=SOME_TOKEN"
public class RestJerseyConnector {
....
----

=== 添加与OAuth相关的@Connector类属性

您的@Connector类需要与OAuth相关的@Configurable实例属性（使用公共getter和setter）来保存OAuth使用者密钥（使用@OAuthConsumerKey注释）和使用者密码（使用@OAuthConsumerSecret注释）。这些将允许用户在使用连接器时指定他们的使用者密钥和秘密。

[source, java, linenums]
----
@Configurable @OAuthConsumerKey private String consumerKey;
 @Configurable @OAuthConsumerSecret private String consumerSecret;
----

它还需要String属性来保存访问令牌和访问令牌的秘密，公共getter和setter（未显示），注释如下所示：

[source, java, linenums]
----
@OAuthAccessToken private String accessToken;
    @OAuthAccessTokenSecret private String accessTokenSecret;
----

=== 添加@Processor方法注释

对于任何要保护的@Processor方法，请添加@OAuthProtected注释，如下所示：

[source, java, linenums]
----
@OAuthProtected @Processor
    public void logInfo() {
        logger.info(String.format("OAuthAccessToken=%s", getAccessToken()));
        logger.info(String.format("OAuthAccessTokenSecret=%s", getAccessTokenSecret()));
    }
----

调用时，@OAuthProtected @Processor方法启动以下活动：

. 首次访​​问受保护资源时，用户将被重定向到服务提供商的授权URL，以授予或拒绝消费者访问受保护资源。
. 在随后的访问请求中，Mule在请求服务提供者的请求中包含*access token*和*access token secret*（包含在用`@OAuthAccessToken`和`@OAuthAccessTokenSecret`标注的参数中） 。有关更多详细信息，请参阅 http://oauth.net/core/1.0/[OAuth 1.0a规范]。

=== 在客户端类中包含OAuth标题

大多数OAuth 1.0实现将使用Jersey Client来访问RESTful API;有些会使用特定于应用程序的Java客户端库。但是无论您使用哪种客户端，您都必须在客户端级别添加代码，以便随请求一起发送使用者密钥，使用者密钥，访问令牌和访问令牌密钥。

在我们的Jersey客户端示例中，这是通过客户端类上的助手方法`addSignHeader()`执行的，如下所示：

[source, code, linenums]
----
private WebResource addSignHeader(WebResource webResource) {
        OAuthParameters params = new OAuthParameters();
        params.signatureMethod("PLAINTEXT");
        params.consumerKey(getConnector().getConsumerKey());
        params.setToken(getConnector().getAccessToken());
 
        OAuthSecrets secrets = new OAuthSecrets();
        secrets.consumerSecret(getConnector().getConsumerSecret());
        secrets.setTokenSecret(getConnector().getAccessTokenSecret());
        OAuthClientFilter filter = new OAuthClientFilter(client.getProviders(), params, secrets);
 
        webResource.addFilter(filter);
        return webResource;
    }
----

连接器通过此方法将所有调用传递给Dropbox API，以添加由OAuth 1标准指定的身份验证标头。由于这是特定于使用Jersey客户端的，因此此处不介绍此方法的详细演练以及它如何适用于客户端类。有关Jersey客户端示例的详细信息，请参阅Connector to RESTful Service。

== 使用您的OAuth 1连接器

一旦建立并安装了连接器，就可以在流程中使用它，如以下各节所述。

=== 授权连接器

在使用者可以执行任何需要授权的操作之前，资源所有者必须授予对连接器的受保护资源的访问权限。当它收到授权请求时，Mule将资源所有者的浏览器重定向到服务提供商授权页面。任何后续访问受保护资源的尝试都会填充使用`@OAuthAccessToken`和`@OAuthAccessTokenSecret`注释的参数。 Mule在对服务提供商的请求中包含访问令牌和令牌机密。见下面的例子。

[source, xml, linenums]
----
<linkedin:config apiKey="${api.key}" apiSecret="${api.secret}"/>
 
...
 
    <flow name="authorize">
        <http:inbound-endpoint host="localhost" port="8080" path="/authorize"/>
        <linkedin:authorize/>
    </flow>
----

=== 在流中配置连接器

. 通过为服务提供商提供的应用程序传递*consumer key*和*consumer secret*来配置扩展。下面的代码示例说明了这种配置的一个例子。
+
[source, xml, linenums]
----
<linkedin:config apiKey="${api.key}" apiSecret="${api.secret}"/>
 
...
 
    <flow name="sampleFlow">
        <linkedin:get-profile-for-current-user />
    </flow>
----

. 配置尝试访问受保护资源的简单流。如果连接器未被OAuth授权，则使用者操作会抛出`NotAuthorizedException`。

=== 自定义回拨

当用户授予访问受保护资源的权限时，服务提供商发出 link:/anypoint-connector-devkit/v/3.4/http-callbacks[HTTP回调]。该回调传递一个授权代码，Mule稍后使用它来获取访问令牌。为了处理回调，Mule动态地创建一个HTTP入站端点，然后将该端点的URL传递给服务提供者。因此，你不需要完成任何特定的配置来进行HTTP回调。

默认情况下，Mule使用主机和端口（由`fullDomain`环境变量和`http.port`确定）来构建一个URL以发送给服务提供商。在需要使用主机和端口的非默认值的情况下，请根据下面的代码示例添加配置。

[source, xml, linenums]
----
<linkedin:config apiKey="${api.key}" apiSecret="${api.secret}">
<linkedin:oauth-callback-config domain="SOME_DOMAIN" remotePort="SOME_PORT" />
</linkedin:config>
----

有关Mule如何处理回调的详细信息，请参阅 link:/anypoint-connector-devkit/v/3.4/http-callbacks[HTTP回调]。

=== 添加安全套接字层（SSL）

当Mule自动启动HTTP入站端点来处理OAuth回调时，它默认使用HTTP连接器。如果服务提供商要求*HTTPS*，则可以配置Mule以传递您自己的HTTPS连接器。看下面的示例代码。

[source, code, linenums]
----
...
 
<https:connector name="httpsConnector">
<https:tls-key-store path="keystore.jks" keyPassword="mule2012" storePassword="mule2012"/>
</https:connector>
 
...
 
    <linkedin:config apiKey="${api.key}" apiSecret="${api.secret}">
    <linkedin:oauth-callback-config domain="localhost" localPort="${http.port}" remotePort="${http.port}" async="true" connector-ref="httpsConnector"/>
    </linkedin:config>
...
----

[TIP]
有关配置*HTTPS connector,*的更多信息，请参阅 link:/mule-user-guide/v/3.4/https-transport-reference[HTTPS传输参考]。

== 另请参阅

* 要详细了解本次讨论中使用的Dropbox示例，请参阅https://github.com/mulesoft/devkit-documentation-rest-jersey/tree/master/src/main/java/org/mule / examples / restjerseyconnector [Github中的源代码]以及在 link:/anypoint-connector-devkit/v/3.4/connector-to-restful-service-with-jersey-client-example[使用Jersey Client示例连接到RESTful服务示例，亚线库]中构建示例的漫游。
* 了解如何在连接器中实现 link:/anypoint-connector-devkit/v/3.4/implementing-oauth-2.0-authentication[OAuth 2.0]。
* 详细了解OAuth身份验证过程中使用的 link:/anypoint-connector-devkit/v/3.4/http-callbacks[HTTP回调]。
