= 将连接器与Mule生命周期集成

[WARNING]
不推荐这种做法。请参阅 link:/anypoint-connector-devkit/v/3.4/implementing-connection-management[实施连接管理]以获取更健壮的方法。

可以让连接器充分了解Mule的生命周期，并在可用注释的Mule Initialize，Start，Stop和Dispose阶段触发特定的方法。

如果一个方法用这些注释中的一个注释，它将在关联的Mule生命周期阶段被调用，如下所述。



== 限制

* 生命周期注释不能应用于：+
* 静态方法
* 非公开方法
需要参数的** 个方法
不返回无效的** 方法
* 每个生命周期注释最多可以在`@Connector`类中应用一次。

== 初始化阶段：`@PostConstruct`

要在初始化阶段调用方法，请应用`@PostConstruct`注释。

[source, code, linenums]
----
import javax.annotation.PostConstruct;
 
@Connector(name = "myconnector")
public class MyConnector {
 
    ...
 
    @PostConstruct
    public void anyMethodName() {
        // your code here
    }
 
    ...
----

== 开始阶段：`@Start`

要在开始阶段调用方法，请应用`@Start`注释。

[source, java, linenums]
----
import org.mule.api.annotations.Module;
import org.mule.api.annotations.lifecycle.Start;
 
@Module(name = "myconnector")
public class MyConnector {
 
    ...
 
    @Start
    public void anyMethodName() {
        // your code here
    }
 
    ...
----

== 停止阶段：`@Stop`

要在停止阶段调用方法，请应用`@Stop`注释。

[source, java, linenums]
----
import org.mule.api.annotations.Module;
import org.mule.api.annotations.lifecycle.Stop;
 
@Module(name = "myconnector")
public class MyConnector {
 
    ...
 
    @Stop
    public void anyMethodName() {
        // your code here
    }
 
    ...
----

== 处置阶段：`@PreDestroy`

要在Dispose阶段调用方法，请应用`@PreDestroy`注释。

[source, java, linenums]
----
import org.mule.api.annotations.Module;
import org.mule.api.annotations.lifecycle.Dispose;
 
@Module(name = "myconnector")
public class MyConnector {
 
    ...
 
    @PreDestroy
    public void anyMethodName() {
        // your code here
    }
 
    ...
----

== 示例

以下代码片段取自Twilio连接器。在开始阶段，会创建`@TwilioClient`类的实例。

[source, java, linenums]
----
package org.mule.module.twilio;
 
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Module;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.lifecycle.Start;
import org.mule.api.annotations.param.Optional;
import org.mule.api.callback.HttpCallback;
 
@Module(name = "twilio")
public class TwilioConnector {
 
    /**
     * The account sid to be used to connect to Twilio.
     */
    @Configurable
    private String accountSid;
    /**
     * The authentication token to be used to connect to Twilio
     */
    @Configurable
    private String authToken;
 
    private TwilioClient twilioClient;
 
    @Start
    public void createTwilioClient() {
        twilioClient = new TwilioClient(accountSid, authToken);
    }
----

在Rest Jersey客户端示例中也使用了与Mule生命周期的集成。

== 另请参阅

阅读更多关于可以为连接器添加功能的其他高级主题：

*  link:/anypoint-connector-devkit/v/3.4/http-callbacks[HTTP回调]
*  link:/anypoint-connector-devkit/v/3.4/handling-data-types-for-configurable-properties[处理可配置属性的数据类型]
*  link:/anypoint-connector-devkit/v/3.4/architectural-considerations-with-connectors-and-the-mule-container[连接器和Mule容器的体系结构考虑]
*  link:/anypoint-connector-devkit/v/3.4/injecting-mule-managers-into-anypoint-connectors[将Mule管理器注入Anypoint连接器]
*  link:/anypoint-connector-devkit/v/3.4/supporting-datasense-with-dynamic-data-models[支持DataSense与动态数据模型]
*  link:/anypoint-connector-devkit/v/3.4/implementing-datasense-query-language-support[实施DataSense查询语言支持]
