= 设置DevKit开发环境

本文档介绍了如何准备一个包含开发Anypoint连接器所需的所有组件的开发环境。您必须在本地环境中安装并使用以下组件：

* 在其中为您的连接器编写代码的Java IDE
*  http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java开发工具包7（JDK 7）]来编译和构建Java代码
*  http://maven.apache.org/download.cgi[Maven的]来管理您的项目构建
*  http://www.mulesoft.org/download-mule-esb-community-edition[骡子工作室]作为测试连接器的IDE

以下各节介绍设置连接器开发环境所需的具体细节。

== 假设

本文档假定您熟悉Java IDE（Eclipse或IntelliJ），并熟悉用于Java的Maven构建管理器。此外，它假定您知道如何在您的平台（Windows，Mac或Linux）上安装JDK 7的实例。


==  Java IDE要求

要为Mule构建Anypoint连接器，您需要一个支持 http://maven.apache.org/[Maven的]的Java IDE。尽管您可以在Maven支持中使用任何Java IDE，但开发人员通常会使用以下内容：

支持安装Maven的 http://eclipse.org/m2e/[m2eclipse的] *  http://www.eclipse.org/downloads/moreinfo/java.php[蚀]
* 作为Mule Studio的一部分安装了Eclipse，并安装了 http://eclipse.org/m2e/[m2eclipse的]
*  http://www.jetbrains.com/idea/index.html[IntelliJ IDEA]，它内置了Maven集成

[NOTE]
虽然*IntelliJ IDEA*和*m2eclipse*提供了IDE和Maven之间的集成，但每个IDE都依赖于您环境中独立Maven实例的存在。

或者，您可以安装下列其中一项来代替IDE：

* 独立的Eclipse安装是针对Anypoint连接器开发环境的一个易于配置的基础。安装 http://www.eclipse.org/downloads/packages/release/juno/sr2[Eclipse 3.8（Juno）]，然后添加Eclipse的 http://eclipse.org/m2e/[m2e Maven]工具，以将Eclipse插入连接器团队的日常开发周期。
*  http://www.jetbrains.com/idea/index.html[IntelliJ IDEA]是另一种常见的流行的IDE for Java，为其提供免费的 http://www.jetbrains.com/idea/free_java_ide.html[社区版]。 IntelliJ IDEA在连接器开发方面的最大优势是Maven支持内置于IntelliJ IDEA中，这消除了设置环境中的配置工作。

==  JDK 7

Oracle使JDK 7免费提供给所有支持的平台，包括Windows，Mac OS X和Linux。为您的平台下载最新的 http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java开发工具包7（JDK）]并进行安装。

==  Maven Build Manager

在构建连接器时，您可以使用Maven构建管理器来生成新的连接器项目，并在连接器开发过程中进行正在进行的构建活动。如果您对Maven不熟悉， http://maven.apache.org/guides/getting-started/maven-in-five-minutes.html[Maven在五分钟内]会简要介绍这些概念和基本命令。

. 从 http://maven.apache.org/download.cgi[Maven下载页面]下载Maven发行版。
. 将下载内容解压缩到本地驱动器上的文件夹。
. 创建名为`M2_HOME`的环境变量，然后将其设置为解包Maven的文件夹。
. 更新`PATH`环境变量以包含Maven二进制文件的路径。 +
*  *Windows*：将以下行添加到PATH变量中：`%M2_HOME%\bin `
*  *Mac*或*Linux*：将以下行添加到PATH变量中：`$M2_HOME/bin`

有关更多详细说明和安装选项，请参阅Maven下载页面;下载链接下方提供了针对不同平台的说明。

Eclipse的===  Maven工具

Eclipse的** ** `m2e` ** **插件使Eclipse能够导入Maven项目并更新它们的元信息。 `m2e`还包含Maven的依赖管理功能，因此在导入或更新项目时，Eclipse中的任何必需库都会在Eclipse中正确下载和配置。

按照以下过程在Eclipse 4.3或更高版本中将** m2e **作为插件安装。

. 在Eclipse中，在*Help*菜单下，选择*Install New Software*。
. 在*Install*面板的*Work with*字段中，使用下拉菜单选择以下网址：
+
`m2eclipse Update Site - http://download.eclipse.org/technology/m2e/releases`
+
[TIP]
====
如果m2eclipse更新网站在下拉菜单中未显示为选项，则可以点击*Add*，然后手动输入网址。

此外，如果使用较早版本的Eclipse，则可能需要下载相应的以前版本的m2e。在Eclipse中，转到Eclipse Marketplace（*Help*> **Eclipse Marketplace...**）以查找需要安装的m2e版本。
====
+
. 在表格中，选择*Maven Integration for Eclipse*，然后点击*Next*。
. 在*Install Details*窗口中，点击*Next*继续安装。
. 在*Review Licenses*窗口中，接受许可协议的条款，然后点击*Finish*。
.  Eclipse完成`m2e`插件的安装后，请点击*Restart Now*完成安装并重新启动Eclipse。

==  Mule Studio

作为DevKit开发者，您需要 http://www.mulesoft.org/download-mule-esb-community-edition[骡子工作室]来测试您的连接器。如果您尚未安装Mule Studio，请按照 link:/mule-user-guide/v/3.4/downloading-and-launching-mule-esb[详细的说明]进行安装。要快速了解Mule Studio，请查看 link:/anypoint-studio/v/5/index[Mule Studio Essentials]。

您还可以使用安装了m2eclipse的Mule Studio作为您的DevKit IDE（运行第二个实例，与测试环境一起）来构建连接器。

=== 另请参阅

*  **NEXT:**继续进行下一步 link:/anypoint-connector-devkit/v/3.4/preparing-api-access-or-a-sandbox-environment[准备API访问或沙箱环境]。
* 渴望开始编码？使用 link:/anypoint-connector-devkit/v/3.4/devkit-shortcut-to-success[DevKit成功的捷径]快速浏览整个开发流程。
