= 通过LDAP启用身份验证

管理控制台可以使用LDAP服务器来管理用户和角色。要使用LDAP，请完成以下步骤：

.  mmc：收集LDAP服务器连接参数
.  mmc：设置管理控制台角色
.  mmc：将LDAP JAR添加到您的类路径中
.  mmc：添加LDAP配置文件

== 收集LDAP服务器连接参数

要开始配置管理控制台以根据LDAP对用户进行身份验证，请从LDAP服务器管理员处收集以下信息：

*  LDAP服务器主机名和端口号
* 管理控制台用来访问LDAP服务器并在其中执行查询的用户帐户。此LDAP用户帐户需要具有*READ ONLY*特权才能读取子树下方的条目，即拥有用户和组的基本专有名称（DN）。
* 用户和组的基本DN
* 有关用户和组的结构信息（用于构建DN的objectClass和属性）。

== 设置管理控制台角色

如果用户在LDAP服务器上有一个角色（也称为"group"），并且您希望使用同一角色管理管理控制台中的权限，则还必须在管理控制台内创建该角色，并设置适当的权限。例如，如果将"Developers"角色添加到LDAP服务器，则还必须在管理控制台的“管理”面板上使用该名称创建角色，并配置适当的权限。

您可以通过以下两种方式之一来完成此操作：

* 在LDAP服务器上创建一个名为Administrators的角色。管理控制台为具有管理员角色的用户提供一组默认权限。确保您的用户名具有管理员角色，然后登录到管理控制台。然后，您可以创建其他角色，分配适当的权限，并从LDAP服务器中删除原始的管理员角色。

* 在未启用LDAP的情况下启动管理控制台。在管理控制台中创建与LDAP服务器上的角色相对应的角色，然后按照以下说明启用LDAP。

== 将LDAP JAR添加到您的类路径中

管理控制台LDAP支持JAR文件包含管理控制台对LDAP服务器进行认证所需的类。您可以下载 link:_attachments/galaxy-ldap-2.2.2.jar[星系LDAP-2.2.2.jar]文件并将其存储在MMC Web应用程序（`<TomcatHome>/webapps/console/WEB-INF/lib`）下的`/WEB-INF/lib`目录中。

== 添加LDAP配置文件

您必须有一个名为`ldap.xml`的LDAP配置文件，该文件需要放在`/WEB-INF/classes`中。 `galaxy-ldap.jar`文件（下载的mmc：以上）包含默认的`ldap.xml`文件，其中LDAP属性设置为mmc：默认值。您可以按原样使用该文件。或者，您可以通过提供`ldap.properties`文件或通过将属性指定为Java属性来重写某些LDAP属性值（如下面的mmc所示）。如果您需要更复杂的配置，则应考虑提供自己的`ldap.xml`文件（请参阅mmc：创建LDAP配置文件）并手动修改`galaxy-ldap.jar`文件以使用您的自定义版本。

默认的`ldap.xml`文件包含设置为这些默认值的以下属性：

[%header,cols="2*",width=10%]
|===
| LDAP属性 |默认值
| {providerURL {1}}的ldap：//本地主机：62009 /
| userDn  | uid = admin，ou = system
| {密码{1}}秘密
| {userSearchBaseContext {1}} OU =系统
| {userSearchFilterExpression {1}} UID = \ {0}
| {userSearchBase {1}} OU =系统
| {userSearchAttributeKey {1}}对象类
| {userSearchAttributeValue {1}}人
| roleDn  | ou = groups，ou = system
| {groupSearchFilter {1}} uniqueMember = \ {0}
|===

有关这些LDAP属性的更多信息，请参见下面的mmc：。

以下代码示例显示如何使用`ldap.properties`文件中的值配置`ldap.xml`属性。如果`ldap.properties`文件不存在，则根据作为参数传递给代码的任何键/值对来配置属性。属性值仅针对`ldap.properties`文件中的这些属性或作为参数传入并通过键名标识进行更改。当找不到属性的匹配项时，这些属性值保留默认值。

[source, xml, linenums]
----
<bean id="propertyPlaceholder"  class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">  <property name="systemPropertiesModeName" value="SYSTEM_PROPERTIES_MODE_OVERRIDE" /> <!-- Existing system properties override local ones -->  <property name="location" value="ldap.properties" />  <property name="ignoreResourceNotFound" value="true" /> <!-- Do not fail if ldap.properties does not exist -->  <property name="localOverride" value="false" /> <!-- local properties override ldap.properties ones -->  <property name="properties"> <!-- Local properties -->   <props>    <prop key="key">value</prop>   </props>  </property> </bean>
----

=== 创建一个LDAP配置文件

您可以创建自己的`ldap.xml`配置文件。以下是一个`ldap.xml`配置文件的示例。该文件中设置的LDAP属性说明遵循该示例。

[source, xml, linenums]
----
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">
  <bean id="initialDirContextFactory"          class="org.springframework.security.ldap.DefaultSpringSecurityContextSource">
    <constructor-arg value="ldap://host:port/"/>
    <property name="userDn">
      <value>cn=Manager,dc=acme,dc=org</value>
    </property>
    <property name="password"><value>password</value></property>
  </bean>
  <bean id="userSearch" class="org.springframework.security.ldap.search.FilterBasedLdapUserSearch">
    <constructor-arg value="ou=People,dc=acme,dc=org"/>
    <constructor-arg value="(uid={0})"/>
    <constructor-arg ref="initialDirContextFactory" />
    <property name="searchSubtree" value="true"/>
  </bean>
  <bean id="userManager"class="org.mule.galaxy.security.ldap.LdapUserManager"        init-method="initialize">
    <property name="initialDirContextFactory" ref="initialDirContextFactory"/>
    <property name="persisterManager" ref="persisterManager" />
    <property name="userSearch" ref="userSearch"/>
    <property name="userMapper" ref="userDetailsMapper"/>
      <!-- Configure these two properties -->
      <property name="userSearchBase" value="ou=People,dc=acme,dc=org"/>
      <property name="userSearchAttributes">
      <map>
        <entry key="objectclass" value="inetOrgPerson"/>
      </map>
    </property>
  </bean>
  <bean id="ldapAuthoritiesPopulator" class="org.mule.galaxy.security.ldap.LdapAuthoritiesPopulator">      <constructor-arg ref="initialDirContextFactory" />
    <constructor-arg value="ou=Groups,dc=acme,dc=org" />
    <property name="groupSearchFilter" value="uniqueMember={0}"/>
    <property name="searchSubtree" value="true"/>
    <property name="rolePrefix" value=""/>
    <property name="convertToUpperCase" value="false"/>
    <property name="accessControlManager" ref="accessControlManager"/>
  </bean>
</beans>
----

以下是在此文件中设置的属性：

*  `initialDirContextFactory` bean的`userDn`属性。
这是登录到LDAP服务器的用户的DN。
*  `initialDirContextFactory` bean的`password`属性。
这是登录到LDAP服务器的用户的密码。
*  `userSearch` bean的第一个`<constructor-arg>`。
这是管理控制台搜索用户的基本上下文。
*  `userSearch` bean的第二个`<constructor-arg>`。
这是一个过滤器表达式，用于查找与特定用户名匹配的条目。例如，（uid = \ {0}）指示搜索`uid`属性与用户名匹配的条目。
*  `userManagerTarget` bean的`userSearchBase`属性。
这是管理控制台搜索用户的基本上下文。
*  `userManagerTarget` bean的`userSearchAttributes`属性。
这些属性用于在LDAP服务器中搜索用户。
*  `ldapAuthoritiesPopulator` bean的第二个`<constructor-arg>`。
这是用于搜索用户所属角色的上下文的DN。
*  `ldapAuthoritiesPopulator` bean的`groupSearchFilter`属性。
这是一个发现角色的表达式。例如，"(uniqueMember=\{0})"
指导搜索`groupSearchBase`中具有某个角色的角色
属性"uniqueMember"其中一个值是用户名。

== 使用Active Directory

您可以使用Active Directory（基于LDAP的目录服务）和管理控制台来管理用户和角色。要在管理控制台中使用Active Directory，您需要按照本页上前面介绍的相同方式启用身份验证。但是，您需要自定义ldap.xml文件。以下是定制的ldap.xml文件看起来像使用Active Directory的示例。该文件中设置的LDAP属性说明遵循该示例。

[source, xml, linenums]
----
<beans xmlns="http://www.springframework.org/schema/beans"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">
  <bean id="initialDirContextFactory"            class="org.springframework.security.ldap.DefaultSpringSecurityContextSource">
    <constructor-arg value="ldap://IP:3268/"/>
    <property name="userDn">
      <value>cn=CN,dc=DC, ...</value>
    </property>
    <property name="password">
    <value>PASSWORD</value></property>
  </bean>
  <bean id="userSearch" class="org.springframework.security.ldap.search.FilterBasedLdapUserSearch">
    <constructor-arg value="cn=CN,dc=DC, ..."/>
    <constructor-arg value="(sAMAccountName={0})"/>
    <constructor-arg ref="initialDirContextFactory" />
    <property name="searchSubtree" value="true"/>
  </bean>
  <bean id="userDetailsMapper" class="org.mule.galaxy.security.ldap.UserLdapEntryMapper">
    <property name="usernameAttribute" value="sAMAccountName"/>
  </bean>
  <bean id="userManager"class="org.mule.galaxy.security.ldap.LdapUserManager"        init-method="initialize">
    <property name="initialDirContextFactory" ref="initialDirContextFactory"/>
    <property name="persisterManager" ref="persisterManager" />
    <property name="userSearch" ref="userSearch"/>
    <property name="userMapper" ref="userDetailsMapper"/>
    <property name="ldapUserMetadataDao" ref="ldapUserMetadataDao"/>
    <!-- Configure these two properties -->
    <property name="userSearchBase" value="cn=CN,dc=DC,..."/>
    <property name="userSearchAttributes">
    <map>
    <entry key="objectclass" value="person"/>
    </map>
    </property>
  </bean>
  <bean id="ldapAuthoritiesPopulator" class="org.mule.galaxy.security.ldap.LdapAuthoritiesPopulator">
    <constructor-arg ref="initialDirContextFactory" />
    <constructor-arg value="dc=DC, ..." />
    <property name="groupSearchFilter" value="member={0}"/>
    <property name="searchSubtree" value="true"/>
    <property name="rolePrefix" value=""/>
    <property name="convertToUpperCase" value="false"/>
    <property name="accessControlManager" ref="accessControlManager"/>
  </bean>
</beans>
----

以下是在此文件中设置的属性：

*  `initialDirContextFactory` bean的`<constructor-arg>`。这指定了LDAP服务器的主机和端口。标准LDAP端口是389.但是，建议您指定Active Directory全局端口（3268）。
*  `initialDirContextFactory` bean的`userDn`属性。这是登录到LDAP服务器的用户的DN。
*  `initialDirContextFactory` bean的`password`属性。这是登录到LDAP服务器的用户的密码。
*  `userSearch` bean的第一个`<constructor-arg>`。
这是管理控制台搜索用户的基本上下文。
*  `userSearch` bean的第二个`<constructor-arg>`。这是一个过滤器表达式，用于查找与特定用户名匹配的条目。 ActiveDirectory使用`sAMAccountName`属性作为唯一的用户标识。例如，`(sAMAccountName={0})`引导搜索其`sAMAccountName`属性与用户名匹配的条目。
*  `userManager` bean的`userSearchBase`属性。这是管理控制台搜索用户的基本上下文。
*  `userManager` bean的`userSearchAttributes`属性。这些属性用于在LDAP服务器中搜索用户。
*  `ldapAuthoritiesPopulator` bean的第二个`<constructor-arg>`。这是用于搜索用户所属角色的上下文的DN。
*  `ldapAuthoritiesPopulator` bean的`groupSearchFilter`属性。这是一个发现角色的表达式。例如，`(member={0})`指导对具有属性"member"的`groupSearchBase`内的角色进行搜索，其中一个值是用户名。

link:/mule-management-console/v/3.2/validating-the-license[<<上一页：*验证许可证*]

link:/mule-management-console/v/3.2/customizing-the-dashboard[下一步：*自定义仪表板* >>]

