= 使用REST API管理服务器

[ <<Managing Servers>> ] [ <<Working with Server Groups>> ]

管理控制台提供了REST API，您可以通过它编程访问控制台的大部分功能。您可以通过REST API请求的操作包括与管理服务器相关的操作。这包括注册新服务器，管理现有服务器，启动和重启服务器以及管理服务器组。

[NOTE]
有关REST API的概述，请参阅 link:/mule-management-console/v/3.2/using-the-management-console-api[使用管理控制台API]，其中包括使用的基本示例以及返回的状态代码和错误处理代码的摘要。

本页概述了用于管理服务器，服务器组和文件的REST API。此外，还介绍了在查询或更新服务器，服务器组和文件时可以指定的属性。您会在下面找到汇总每个REST API的表格。您还可以找到嵌入在API汇总表中的链接，以获取有关每种API方法的更多详细信息。

*Note:*符号\ {mmc base}指向控制台基址。

== 管理服务器

您可以使用服务器API来查找，创建，更新和删除服务器。另外，您还可以执行与管理服务器相关的其他操作，例如重新启动服务器或将文件上载到服务器。您可以在所有服务器，单个服务器和与服务器相关的文件上执行操作。

下面的三个表格总结了您可以在服务器上执行的操作以及您指定调用每个操作的资源。这些表格分为可在所有服务器上执行的操作，特定于单台服务器的操作以及对文件进行操作的操作。点击特定任务的链接以获取有关使用其REST API执行该任务的更多详细信息。

请注意，根据用于调用它的HTTP命令，相同的资源可能执行不同的操作。例如，如果使用GET命令调用资源，则资源/ mmc / api / servers会列出所有服务器。如果使用POST命令调用它，则相同的资源将注册一个服务器。

*APIs for All Servers* +
这些API可以在所有服务器上执行。

[%header%autowidth.spread]
|===
|任务 |资源 |描述 | HTTP调用方法
| link:/mule-management-console/v/3.2/list-all-servers[列出所有服务器]  | \ {mmc base} / api / servers  |列出资源 |中的所有服务器
|===

*APIs for Individual Servers* +
使用这些API在单个服务器上执行操作。请注意，<myServerId>是标识特定服务器的URL的占位符。

[%header%autowidth.spread]
|===
|任务 |资源 |描述 | HTTP调用方法
| link:/mule-management-console/v/3.2/get-a-server[获取服务器] +  | \ {mmc base} / api / servers / <myServerId>  |获取服务器标识符 | GET
| link:/mule-management-console/v/3.2/register-a-server[注册一个服务器] +  | \ {mmc base} / api / servers  |注册新服务器 | POST
| link:/mule-management-console/v/3.2/restart-a-server[重新启动服务器] +  | \ {mmc base} / api / servers / <myServerId> / restart  |重新启动服务器 | POST
| link:/mule-management-console/v/3.2/update-a-server[更新服务器] +  | \ {mmc base} / api / servers / <myServerId>  |更新服务器 | PUT
| link:/mule-management-console/v/3.2/delete-a-server[删除服务器] +  | \ {mmc base} / api / servers / <myServerId>  |删除服务器 | DELETE
|===

*APIs for Actions on Files* +
使用这些API对位于指定服务器上的文件执行操作。请注意，<myServerId>是标识特定服务器的URL的占位符。另请注意，<myFile.xml>是文件路径的占位符。

[%header%autowidth.spread]
|==========
|任务 |资源 |描述 | HTTP调用方法
| link:/mule-management-console/v/3.2/get-a-file[获取文件] +  | \ {mmc base} / api / servers / <myServerId> / files / <myFile.xml>  |获取位于指定的服务器 | GET
| link:/mule-management-console/v/3.2/get-file-metadata[获取文件元数据] +  | \ {mmc base} / api / servers / files / <myServerId> / \ <myFile.xml>？metadata = true  |获取位于指定服务器 | GET上的文件的元数据
| link:/mule-management-console/v/3.2/create-or-update-a-file[创建或更新文件] +  | \ {mmc base} / api / servers / files / <myServerId> / \\ <myFile.xml>  |更新或创建文件位于指定的服务器 | POST上
| link:/mule-management-console/v/3.2/update-a-file[更新文件] +  | \ {mmc base} / api / servers / files / <myServerId> /  |更新位于指定服务器上的文件{{5 }}放
| link:/mule-management-console/v/3.2/delete-a-file[删除文件] +  | \ {mmc base} / api / servers / files / <myServerId> / \ <myFile.xml>  |删除位于在服务器上 |删除
|==========

例如，以下是列出所有服务器的请求。

[source, code, linenums]
----
GET http://{mmc base}/api/servers
----

这是响应可能的样子。

[source, json, linenums]
----
200 OK
Content-Type: application/json
Server: Apache-Coyote/1.1
Date: Sun, 08 Nov 2009 00:12:55 GMT
{
  "total" : 1,
  "data" : [
    {
      "name" : "Test",
      "id" : "local$b15ecba1-9f97-4b16-8127-9b137cdbb2e1",
      "href" : "http://localhost:9003/mmc/api/servers/local$b15ecba1-9f97-4b16-8127-9b137cdbb2e1",
      "agentUrl" : "https://localhost:7777/mmc-support",
      "hostIp" : "192.168.0.13",
      "muleServerId" : "d9505d40-2c5c-11df-b832-a32a5a09ec4e",
      "started" : "Wed Mar 10 16:51:59 CET 2010",
      "version" : "2.2.5",
      "agents": [
        {
          "name" : "mmc-support",
          "description" : "Mule Management Console Support (0.0.0.0:7777)"
        },
        {
          "name" : "jmx-agent",
          "description" : "JMX Agent"
         }
       ],
      "groups" : [
        {
          "name" : "Development",
          "href" : "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
        }
      ],
      "status": "STOPPED",
      "runningServices" : 3,
      "pausedServices" : 0,
      "stoppedServices": 0
    }
  ]
}
----

请记住，除非另有说明，否则所有返回或接受类型的资源（方法）都使用服务器JSON类型，如上面显示的从`/mmc/api/servers` API收到的响应中所示。

=== 服务器属性

要成功请求服务器操作，您需要知道服务器属性。本节提供了您传递给服务器特定方法的属性的简要列表。所有方法调用都要求您为这些属性中的至少一些设置值。返回的响应包括方法调用时的属性和值。

除了说明JSON类型之外，前面的代码示例还演示了响应可能为一组服务器属性返回的值，如`name,`和`agentUrl`。 JSON对象包含在调用服务器属性时设置的所有值。下表显示了服务器属性。

[%header%autowidth.spread]
|===
|属性 |说明
|名称 |服务器的名称
| id  |服务器的唯一ID
| href  |服务器所在的URL
| agentUrl  |用于控制台和Mule服务器之间通信的URL。这是完整的URL指定。
| hostIp  | Mule服务器的主机IP，例如192.168.0.13
| muleServerId  | Mule服务器ID
|开始 |服务器上次启动的日期和时间
|状态 |服务器的状态（例如STOPPED，OK等）
|版本 |正在使用的Mule版本，例如2.2.5
|座席 |在服务器上运行的座席列表。其他代理属性如下所示。
|组 |此服务器所属的组的列表。其他组属性如下所示。
| runningServices  |运行服务的数量
| pausedServices  |已暂停服务的数量
| stoppedServices  |已停止服务的数量
|===

代理属性。=== 

下表显示了`agents`属性的子属性。您可以在上面的JSON代码示例中看到这些属性的示例。

[%autowidth.spread]
|===
|名称 |代理的名称，例如`jmx-agent`
|描述 |代理的描述，例如JMX-Agent
|===

=== 服务器组属性

下表显示了`groups`服务器属性的子属性。以前的JSON代码示例提供了这些属性值的示例。

[%autowidth.spread]
|===
|名称 |服务器组的名称
| href  |服务器组所在的URL
|===

== 使用服务器组

与服务器一样，您可以一次或在单个服务器组上执行所有服务器组上的操作。返回或接受类型的所有资源/方法（除非另有说明）均使用服务器组JSON类型。以下是针对与服务器组相关的请求返回的服务器组JSON类型的示例：

[source, code, linenums]
----
{
  "name" : "renamed",
  "id" : "c4f7d8ce-21a7-4730-9447-37d8a7f8aab0",
  "serverCount" : 0,
  "href" : "http://localhost:8080/mmc/api/serverGroups/c4f7d8ce-21a7-4730-9447-37d8a7f8aab0"
}
----

=== 服务器组属性

以下属性适用于服务器组。当您检索服务器组时，这些属性会显示在响应中。在执行诸如创建新服务器组等操作时指定服务器组`name`属性。

[%header%autowidth.spread]
|======
|属性 |说明
|名称 |组的名称
| id  |组的唯一ID
| href  |服务器组所在的URL
| serverCount  |当前在该组中的服务器的数量
|======

服务器组的===  API

下表总结了您可以在单个服务器组或所有服务器组上执行的操作。这些表格指示您为每个操作指定的资源以及用于调用资源的HTTP命令。

*All Server Groups*

[%header%autowidth.spread]
|============
|任务 |资源 |描述 | HTTP调用方法
| link:/mule-management-console/v/3.2/list-all-server-groups[列出所有服务器组] +  | \ {mmc base} / api / serverGroups  |列出资源 |中的所有服务器组
|============

*Individual Server Groups* +
使用这些资源在单个服务器组上执行操作。请务必将特定服务器组的标识替换为<serverGroupId>。

[%header%autowidth.spread]
|============
|任务 |资源 |描述 | HTTP调用方法
| link:/mule-management-console/v/3.2/create-a-server-group[创建一个服务器组] +  | \ {mmc base} / api / serverGroups  |创建新的服务器组 | POST
| link:/mule-management-console/v/3.2/get-a-server-group[获取服务器组] +  | \ {mmc base} / api / serverGroups / <serverGroupId>  |获取服务器组 | GET
| link:/mule-management-console/v/3.2/update-a-server-group[更新服务器组] +  | \ {mmc base} / api / serverGroups / <serverGroupId>  |更新服务器组 | PUT
| link:/mule-management-console/v/3.2/delete-a-server-group[删除服务器组] +  | \ {mmc base} / api / serverGroups / <serverGroupId>  |删除服务器组 | DELETE
|============

link:/mule-management-console/v/3.2/using-the-management-console-api[<<上一页：*使用管理控制台API *]

link:/mule-management-console/v/3.2/managing-clusters-using-rest-apis[Next：*使用REST API管理群集*] >>
