= 使用REST API管理集群中的流程

管理控制台提供了REST API，您可以通过它编程访问控制台的大部分功能。您可以通过REST API请求的操作包括与管理群集中的流相关的操作。这包括查找集群中的流程，以及启动和停止流程的端点。

[NOTE]
有关REST API的概述，请参阅 link:/mule-management-console/v/3.2/using-the-management-console-api[使用管理控制台API]，其中包括使用的基本示例以及返回的状态代码和错误处理代码的摘要。

此页面提供了用于管理群集中的流的每个REST API的简要说明，调用API的HTTP方法以及用法示例。这些示例显示了如何使用命令行HTTP工具 http://curl.haxx.se/[卷曲]调用API。

注意：符号\ {mmc base}指的是控制台基址。示例中使用的控制台基址为http：// localhost：8080 / mmc，并使用默认用户名和密码（admin：admin）进行配置。

下表总结了用于管理部署的REST API：

[%header%autowidth.spread]
|===
|任务 |资源 |描述 | HTTP调用方法
|获取流 | \ {mmc base} / api / clusters / <cluster> / flows  |列出集群中的所有流 | GET
|获取流终点 | \ {mmc base} / api / clusters / <cluster> / flows / <flowName> / <application> / endpoints  |列表流 | GET的所有端点
|开始或停止终结点 | \ {mmc base} / api / clusters / <cluster> / flows / <flowName> / <applicationName> / endpoints / {{3} } / start（或stop） |启动（或停止）流 | POST的端点
|开始或停止流 | \ {mmc base} / api / clusters / <cluster> / flows / <flowName> / <applicationName> /开始（或停止）  |开始或停止一个流 | POST
|===

本页面上的所有示例都使用如下所示的集群和数据：

[source, code, linenums]
----
{
    "data": [
        {
            "clusterStatus": "OK",
            "deployments": [],
            "groupIds": [],
            "id": "fb044ee2-f097-43e1-8e1f-4b446f703cac",
            "lastRestarted": 1314982582819,
            "location": "N/A",
            "name": "ClusterXY",
            "nodeServerIds": [
                "local$191630af-3cfa-4535-87f8-420f7eb03c0f",
                "local$2364843f-dd47-4556-97e0-105e0011ee2d"
            ],
            "nodesUpCount": 2,
            "pausedServices": 0,
            "runningServices": 0,
            "status": "2 of 2 nodes online",
            "stoppedServices": 0,
            "totalServices": 0,
            "version": "3.2.0-RC3"
        }
    ],
    "total": 1
}
----

== 获取流量

列出集群中的所有流。

*HTTP Method:*

得到

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/clusters/{cluster}/flows
----

*Parameters:*

群集：列出的流的群集的名称或ID。

*Example:*

以下示例显示如何列出ID为fb044ee2-f097-43e1-8e1f-4b446f703cac的群集的流量：

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/clusters/ClusterXY/flows
----

JSON响应：

[source, code, linenums]
----
{
    "data": [
        {
            "asyncEventsReceived": 0,
            "auditStatus": "DISABLED",
            "averageProcessingTime": -1,
            "executionErrors": 0,
            "fatalErrors": 0,
            "favorite": false,
            "flowId": {
                "application": "mule-example-echo-3.2.0-RC3",
                "definedInApplication": true,
                "fullName": "EchoFlow [mule-example-echo-3.2.0-RC3]",
                "name": "EchoFlow"
            },
            "id": "fb044ee2-f097-43e1-8e1f-4b446f703cac/EchoFlow",
            "inboundEndpoints": [
                "http://localhost:65082/services/EchoUMO"
            ],
            "maxProcessingTime": 0,
            "minProcessingTime": 0,
            "processedEvents": 0,
            "clusterId": "fb044ee2-f097-43e1-8e1f-4b446f703cac",
            "status": "RUNNING",
            "syncEventsReceived": 0,
            "totalEventsReceived": 0,
            "totalProcessingTime": 0,
            "type": "flow"
        }
    ],
    "total": 1
}
----

== 获取流终端

列出流的所有端点。

*HTTP Method:*

得到

*URL:*

[source, code, linenums]
----
{mmc base}/api/clusters/{cluster}/flows/{flowName}/{applicationName}/endpoints
----

*Parameters:*

*  cluster：集群的ID。
*  applicationName：流程的应用程序名称。
*  flowName：流的名称。

*Example:*

以下示例显示如何列出ID为fb044ee2-f097-43e1-8e1f-4b446f703cac的群集中名为EchoFlow的流的端点，其应用程序名称为test-app：

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/clusters/ClusterXY/flows/EchoFlow/test-app/endpoints
----

JSON响应：

[source, code, linenums]
----
{
    "data": [
        {
            "address": "http://localhost:65082/services/EchoUMO",
            "connector": "connector.http.mule.default",
            "filtered": false,
            "id": "endpoint.http.localhost.65082.services.EchoUMO",
            "routedMessages": 0,
            "status": "started",
            "synchronous": true,
            "tx": false,
            "type": "http"
        }
    ],
    "total": 1
}
----

== 开始/停止终结点

启动或停止指定流程的端点。

*HTTP Method:*

POST

*URL:*

开始：

[source, code, linenums]
----
http://{mmc base}/clusters/{cluster}/flows/{flowName}/{applicationName}/endpoints/{endpointId}/start
----

停止：

[source, code, linenums]
----
http://{mmc base}/clusters/{cluster}/flows/{flowName}/{applicationName}/endpoints/{endpointId}/stop
----

*Parameters:*

* 集群：集群的名称或标识。
*  applicationName：流程的应用程序名称。
*  flowName：流名称的名称。
*  endpointId：要启动或停止的端点的名称。

*Example:*

请求：

启动一个端点：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/clusters/ClusterXY/flows/EchoFlow/test-app/endpoints/endpoint.http.localhost.65082.services.EchoUMO/start
----

停止一个端点：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/clusters/ClusterXY/flows/EchoFlow/test-app/endpoints/endpoint.http.localhost.65082.services.EchoUMO/stop
----

JSON响应：

已成功启动或停止的端点列表。

[source, code, linenums]
----
["endpoint.http.localhost.65082.services.EchoUMO"]
----

== 开始/停止流程

启动或停止群集中的流程。

*HTTP Method:*

POST

*URL:*

开始：

[source, code, linenums]
----
http://{mmc base}/api/clusters/{cluster}/flows/{flowName}/{applicationName}/start
----

停止：

[source, code, linenums]
----
http://{mmc base}/api/clusters/{cluster}/flows/{flowName}/{applicationName}/stop
----

*Parameters:*

* 集群：集群的名称或标识。
*  applicationName：流程的应用程序名称。
*  flowName：流的名称。

*Example:*

请求：

开始流程：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/clusters/ClusterXY/flows/EchoFlow/test-app/start
----

停止流动：

[source, code, linenums]
----
url --basic -u admin:admin -X POST http://localhost:8080/mmc/api/clusters/ClusterXY/flows/EchoFlow/test-app/stop
----



响应：

[source, code, linenums]
----
The flow started or stopped successfully
----

link:/mule-management-console/v/3.2/managing-flows-in-a-server-using-rest-apis[<<上一页：*使用REST API管理服务器中的流*]

link:/mule-management-console/v/3.2/using-the-management-console-for-performance-tuning[下一步：*使用管理控制台进行性能调整*] >>
