= 使用REST API管理应用程序

管理控制台提供了REST API，您可以通过它编程访问控制台的大部分功能。您可以通过REST API请求的操作包括与管理存储库中的应用程序相关的操作。这包括在存储库中查找，上传和删除应用程序。

[NOTE]
有关REST API的概述，请参阅 link:/mule-management-console/v/3.2/using-the-management-console-api[使用管理控制台API]，其中包括使用的基本示例以及返回的状态代码和错误处理代码的摘要。

该页面提供了每个用于应用程序管理的REST API的简要说明，一个调用该API的HTTP方法以及一个用法示例。这些示例显示了如何使用命令行HTTP工具 http://curl.haxx.se/[卷曲]调用API。

注意：符号\ {mmc base}指的是控制台基址。示例中使用的控制台基址为http：// localhost：8080 / mmc，并使用默认用户名和密码（admin：admin）进行配置。

下表总结了用于应用程序管理的REST API：

[%header%autowidth.spread]
|===
|任务 |资源 |描述 | HTTP调用方法
|获取有关应用程序的信息 | \ {mmc base} / api / repository  |返回有关存储库中应用程序的信息 | GET
|上传应用程序 | \ {mmc base} / api / repository  |将应用程序上传到存储库 | POST
|删除应用程序 | \ {mmc base} / api / repository / <applicationId>  |从存储库中删除特定应用程序 | DELETE
|===

== 获取有关应用程序的信息

返回有关存储库中应用程序的信息。

*HTTP Method:*

得到

*URL:*

[source, code]
----
http://{mmc base}/api/repository
----

*Parameters:*

path：一个可选参数，用于指定在存储库中查找应用程序的路径。默认路径是`/Applications/`。

*Example: Get information about applications*

请求：

[source, code]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/repository
----

JSON响应：

[source, code, linenums]
----
{
    "data": [
        {
            "href": "http://localhost:8080/mmc/api/repository/local$c70fe77e-293c-4fd0-a47b-9da85501171a",
            "id": "local$c70fe77e-293c-4fd0-a47b-9da85501171a",
            "name": "test-app",
            "versions": [
                {
                    "id": "local$09440704-2654-4301-bd35-a0b2ae706313",
                    "name": "1.0",
                    "parentPath": "/Applications/test-app"
                }
            ]
        }
    ],
    "total": 1
}
----

*Example: Get information about a specific application*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/repository/'local$c70fe77e-293c-4fd0-a47b-9da85501171a'
----

JSON响应：

[source, code, linenums]
----
{
    "data": [
        {
            "id": "local$09440704-2654-4301-bd35-a0b2ae706313",
            "name": "1.0",
            "parentPath": "/Applications/test-app"
        }
    ],
    "total": 1
}
----

== 上传应用程序

将应用程序上传到存储库。

*HTTP Method:*

POST

*URL:*

[source, code]
----
http://{mmc base}/api/repository
----

*Parameters:*

以下参数在cURL命令中被指定为表单参数：

文件：要上传的文件流。 +
名称：要上传的应用程序的名称。 +
版。一个字符串，指定应用程序的版本ID（默认情况下为日期和时间）。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -F file=@my-zipped-app.zip -F name=test-app -F version=2.0 --header 'Content-Type: multipart/form-data' http://localhost:8080/mmc/api/repository
----

注意：确保你的当前文件夹中有你的压缩应用，否则curl将无法创建formpost数据。

响应：

[source, code, linenums]
----
{
    "applicationId": "local$c70fe77e-293c-4fd0-a47b-9da85501171a",
    "versionId": "local$75e22cd7-ce94-422a-9987-aa0403713e3e"
}
----

要查看关于上传的应用程序的信息，请执行以下命令：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/repository/'local$c70fe77e-293c-4fd0-a47b-9da85501171a'
----

[source, code, linenums]
----
{
    "data": [
        {
            "id": "local$09440704-2654-4301-bd35-a0b2ae706313",
            "name": "1.0",
            "parentPath": "/Applications/test-app"
        },
        {
            "id": "local$75e22cd7-ce94-422a-9987-aa0403713e3e",
            "name": "2.0",
            "parentPath": "/Applications/test-app"
        }
    ],
    "total": 2
}
----

== 删除应用程序

从存储库中删除应用程序。

*HTTP Method:*

POST

*DELETE:*

[source, code]
----
http://{mmc base}/api/repository/<applicationId>
----

*Parameters:*

applicationId：要删除的应用程序的ID。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X DELETE http://localhost:8080/mmc/api/repository/'local$09440704-2654-4301-bd35-a0b2ae706313'
----

要查看有关已删除应用程序的信息，请执行以下命令：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/repository/'local$c70fe77e-293c-4fd0-a47b-9da85501171a'
----

[source, code, linenums]
----
{
    "data": [
        {
            "id": "local$75e22cd7-ce94-422a-9987-aa0403713e3e",
            "name": "2.0",
            "parentPath": "/Applications/test-app"
        }
    ],
    "total": 1
}
----

link:/mule-management-console/v/3.2/managing-clusters-using-rest-apis[<<上一页：*使用REST API管理群集*]

link:/mule-management-console/v/3.2/managing-deployments-using-rest-apis[Next：*使用REST API管理部署*] >>

