= 使用REST API管理部署


管理控制台提供了REST API，您可以通过它编程访问控制台的大部分功能。您可以通过REST API请求的操作包括与管理部署相关的操作。这包括在服务器或集群内部署，取消部署，创建，更新和删除部署。

[NOTE]
有关REST API的概述，请参阅 link:/mule-management-console/v/3.2/using-the-management-console-api[使用管理控制台API]，其中包括使用的基本示例以及返回的状态代码和错误处理代码的摘要。


此页面提供了用于管理部署的每个REST API的简要说明，调用API的HTTP方法以及用法示例。这些示例显示了如何使用命令行HTTP工具 http://curl.haxx.se/[卷曲]调用API。

注意：符号\ {mmc base}指的是控制台基址。示例中使用的控制台基址为http：// localhost：8080 / mmc，并使用默认用户名和密码（admin：admin）进行配置。

下表总结了用于管理部署的REST API：

[%header%autowidth.spread]
|===
|任务 |资源 |描述 | HTTP调用方法
|获取所有部署 | \ {mmc base} / api / deployments  |获取所有部署 | GET
|获得一个部署 | \ {mmc base} / api / deployments / <deploymentId>  |获取一个部署 | GET
|创建部署 | \ {mmc base} / api / deployments  |创建部署 | POST
|添加应用程序/服务器 | \ {mmc base} / api / deployments / <deploymentId> / add  |将应用程序或服务器添加到部署 | PUT
|删除应用程序/服务器 | \ {mmc base} / api / deployments / <deploymentId> / remove  |从部署 |中删除应用程序和服务器PUT
|删除部署 | \ {mmc base} / api / deployments / <deploymentId>  |删除整个部署 | DELETE
|部署部署 | \ {mmc base} / api / deployments / <deploymentId> / deploy  |部署一个或多个指定部署 | POST
|重新部署 | \ {mmc base} / api / deployments / <deploymentId> /重新部署 |重新部署一个或多个指定部署 | POST
|取消部署 | \ {mmc base} / api / deployments / <deploymentId> /取消部署 |取消部署一个或多个指定部署 | POST
|===

== 获取所有部署

返回指定服务器上所有部署的列表。如果未指定服务器，则API将返回所有服务器上所有部署的列表。

*HTTP Method:*

得到

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/deployments
----

*Parameters:*

serverId：一个可选参数，用于指定从中列出部署的服务器的ID。如果未指定，则此参数设置为`all`。如果指定的ID不是有效的服务器ID，则返回的JSON是一个空列表。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/deployments
----

JSON响应：

返回的JSON包含以下字段：

总共* ：部署数量。
*  data：包含每个部署信息的列表。
* 名称：部署的名称。
*  id：部署的ID。
*  lastModified：指示上次部署被修改的日期。日期格式为：`%day, %dayNumber %month %year %hour:%minutes:%seconds %timeZone`。
* 状态：部署的当前状态。可能的状态值为：`DEPLOYED`，`UNDEPLOYED`，`IN_PROGRESS`，`SUCCESSFUL`，`FAILED`和`DELETING`。
*  href：链接到管理控制台中的当前部署屏幕。
* 个服务器：列出分配给部署的所有服务器的ID。
* 群集：列出分配给部署的所有群集的ID。
*  clustersNames：列出分配给部署的所有集群的所有名称。
* 协调：布尔值，指示部署的协调状态。
* 个应用程序：列出分配给部署的所有应用程序的ID。

响应：

[source, code, linenums]
----
{
    "data": [
        {
            "applications": [
                "local$1b8ee6e2-043c-403c-b404-af3aa74d6f92"
            ],
            "clusterIds": [],
            "clusterNames": [],
            "href": "http://localhost:8080/mmc/api/deployments/local$97e3c184-09ed-423e-a5a5-9b94713a9e36",
            "id": "local$97e3c184-09ed-423e-a5a5-9b94713a9e36",
            "lastModified": "Mon, 5 Sep 2011 12:19:15 GMT-03:00",
            "name": "Example",
            "reconciled": false,
            "servers": [
                "local$3a99adfe-e942-4b52-b082-1a351de01420"
            ],
            "status": "UNDEPLOYED"
        }
    ],
    "total": 1
}
----

== 获取单个部署

返回有关特定部署的信息。

*HTTP Method:*

得到

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/deployments/{deploymentId}
----

*Parameters:*

部署ID：部署的ID。

*Example:*

以下示例显示如何列出ID为本地的部署$ 06d1e159-7297-475f-b84e-d83cc6d0540c：

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/deployments/'local$06d1e159-7297-475f-b84e-d83cc6d0540c'
----

响应：

返回的JSON包含以下字段：

* 名称：部署的名称。
*  id：部署的ID。
*  lastModified：指示上次部署被修改的日期。日期格式为：`%day, %dayNumber %month %year %hour:%minutes:%seconds %timeZone`。
* 状态：部署的当前状态。可能的状态值为：`DEPLOYED`，`UNDEPLOYED`，`IN_PROGRESS`，`SUCCESSFUL`，`FAILED`和`DELETING`。
*  href：链接到管理控制台中的当前部署屏幕。
* 个服务器：列出分配给部署的所有服务器的ID。
* 协调：布尔值，指示部署的协调状态。
* 个应用程序：列出分配给部署的所有应用程序的ID。

[source, code, linenums]
----
{
    "applications": [
        "local$1b8ee6e2-043c-403c-b404-af3aa74d6f92"
    ],
    "clusterIds": [],
    "clusterNames": [],
    "href": "http://localhost:8080/mmc/api/deployments/local$97e3c184-09ed-423e-a5a5-9b94713a9e36",
    "id": "local$97e3c184-09ed-423e-a5a5-9b94713a9e36",
    "lastModified": "Mon, 5 Sep 2011 12:19:15 GMT-03:00",
    "name": "Example",
    "reconciled": false,
    "servers": [
        "local$3a99adfe-e942-4b52-b082-1a351de01420"
    ],
    "status": "UNDEPLOYED"
}
----

== 创建一个部署

使用指定的部署名称，指定的服务器和应用程序创建部署，并将部署保存在控制台上。输入值是使用JSON指定的。返回的JSON包含有关新创建的部署的信息。

*HTTP Method:*

POST

[source, code, linenums]
----
http://{mmc base}/api/deployments
----

*JSON Input Fields:*

*  name：要创建的部署的名称。
* 服务器：服务器有效标识的列表。如果服务器ID无效，则会返回错误消息和无效ID。
* 群集：有效群集ID的列表。如果群集ID无效，则返回错误消息并附带无效ID。
*  serversNames：服务器名称列表。
*  clusterNames：集群名称列表。 +
应用程序：要分配给新部署的有效应用程序ID的列表。如果应用程序ID无效，则返回错误消息并附带无效ID。 +
applicationsNames：应用程序名称列表。

关于JSON请求的唯一限制是必须是指定的名称和至少一个目标（服务器，serverName，集群或clusterName）和至少一个应用程序（applications，applicationsNames）。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -d  '{"name" : "Example" , "serversNames": [ "mule0" ], "applications": [ "local$75e22cd7-ce94-422a-9987-aa0403713e3e" ]  }' --header 'Content-Type: application/json' http://localhost:8080/mmc/api/deployments
----

响应：

[source, code, linenums]
----
{
    "applications": [
        "local$1b8ee6e2-043c-403c-b404-af3aa74d6f92"
    ],
    "clusterIds": [],
    "clusterNames": [],
    "href": "http://localhost:8080/mmc/api/deployments/local$97e3c184-09ed-423e-a5a5-9b94713a9e36",
    "id": "local$97e3c184-09ed-423e-a5a5-9b94713a9e36",
    "lastModified": "Mon, 5 Sep 2011 12:19:15 GMT-03:00",
    "name": "Example",
    "reconciled": false,
    "servers": [
        "local$3a99adfe-e942-4b52-b082-1a351de01420"
    ],
    "status": "UNDEPLOYED"
}

----

返回的JSON包含以下字段：

* 名称：刚创建的部署名称。
*  id：新部署的ID。
*  lastModified：创建部署的日期。日期格式为：`%day, %dayNumber %month %year %hour:%minutes:%seconds %timeZone`。
* 状态：部署的当前状态，为`UNDEPLOYED`。
*  href：链接到管理控制台中的当前部署屏幕。
* 个服务器：列出分配给部署的所有服务器的ID。
* 协调：布尔值，指示部署的协调状态。
* 个应用程序：列出分配给部署的所有应用程序的ID。

== 添加应用程序/服务器

将已在存储库中的应用程序或服务器添加到部署中。输入值是使用JSON指定的。生成的JSON包含有关部署的更新信息。请注意，生成的部署具有与原始部署不同的ID。

*HTTP Method:*

放

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/deployments/{deploymentId}/add
----

*JSON Input Fields:*

*  name：（可选）部署的新名称。如果未指定名称字段，则部署名称保持不变。
*  servers：要分配给指定部署的服务器ID列表。如果列表包含一个不存在的ID，则返回错误消息和无效ID。
* 应用程序：要分配给指定部署的应用程序ID列表。如果列表包含一个不存在的ID，则返回错误消息和无效ID。

以下是JSON输入的示例：

[%autowidth.spread]
|===
| {"applications"："appId1"，"appId2" ..]，"servers"："serverId1" ..]， "name"："new example name"}
|===

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X PUT -d '{"applications": [ "local$51928b35-778b-4bcb-9190-340c2bb5fe59" ], "servers": [ "local$2796fd32-10f3-44ea-809b-f06ebbeeb2ad" ]}' --header 'Content-Type: application/json' http://localhost:8080/mmc/api/deployments/'local$97e3c184-09ed-423e-a5a5-9b94713a9e36'/add
----

响应：

返回的JSON包含以下字段：

* 名称：更新部署的名称。如果在输入JSON中没有输入名称字段，则名称与更新之前的名称保持不变。
*  id：更新部署的ID。
*  lastModified：部署更新的日期。日期格式为：`%day, %dayNumber %month %year %hour:%minutes:%seconds %timeZone`。
* 状态：部署的当前状态。
*  href：链接到管理控制台中的当前部署屏幕。
* 个服务器：列出更新后分配给部署的所有服务器的ID。
* 协调：布尔值，指示部署的协调状态。
* 个应用程序：列出在更新后分配给部署的所有应用程序的ID。

== 删除应用程序/服务器

从部署中删除应用程序或服务器。生成的JSON包含修改后的部署信息。请注意，生成的部署将具有与操作之前不同的ID。

*HTTP Method:*

删除

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/deployments/{deploymentId}/remove
----

*JSON Input Fields:*

* 个服务器：将从指定部署中删除的服务器标识列表。如果列表包含未分配给部署的服务器标识，则该服务器标识将被忽略。
* 个应用程序：将从指定部署中删除的应用程序ID列表。如果列表包含未分配给部署的应用程序标识，则应用程序标识将被忽略。

以下是JSON输入的示例：

[%autowidth.spread]
|===
| {"applications"：["appId1"，"appId2" ..]，"servers"：["serverId0"，"serverId1" ..]}}
|===

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X PUT -d '{"servers": ["local$4c9b276a-86f8-4553-b5d3-759a5b915891"], "applications":["local$ed4f9df8-a937-4bd4-8cc4-c32e78edb0cb"]}' --header 'Content-Type: application/json' http://localhost:8080/mmc/api/deployments/'local$97e3c184-09ed-423e-a5a5-9b94713a9e36'/remove
----

响应：

返回的JSON包含以下字段：

* 名称：已修改部署的名称。
*  id：修改后的部署的新ID。
*  lastModified：部署的最后修改日期。格式是："%day, %dayNumber %month %year %hour:%minutes:%seconds %timeZone"。
* 状态：部署的当前状态。
*  href：链接到管理控制台中的当前部署屏幕。
* 个服务器：在删除指定的服务器和应用程序后分配给部署的所有服务器标识的列表。
*  reconcilied：布尔值，用于部署的协调状态。
* 个应用程序：在删除指定的服务器和应用程序后仍然分配给部署的所有应用程序ID的列表。

== 部署部署

重新部署一个或多个指定的部署。

*HTTP Method:*

POST

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/deployments/{deploymentId}/deploy
----

*Parameters:*

*  id：要部署的部署（或多个部署）的ID。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/deployments/'local$97e3c184-09ed-423e-a5a5-9b94713a9e36'/deploy
----

响应：

指定的部署已重新部署。

== 重新部署部署

重新部署一个或多个指定的部署。

*HTTP Method:*

POST

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/deployments/{deploymentId}/redeploy
----

*Parameters:*

*  id：要重新部署的部署（或多个部署）的ID。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/deployments/'local$97e3c184-09ed-423e-a5a5-9b94713a9e36'/redeploy
----

响应：

指定的部署已重新部署。

== 取消部署

取消部署一个或多个指定的部署。

*HTTP Method:*

POST

*URL:*

*Parameters:*

*  id：要部署的部署（或多个部署）的ID。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/deployments/'local$97e3c184-09ed-423e-a5a5-9b94713a9e36'/undeploy
----

响应：

指定的部署已取消部署。

== 删除部署

删除一个或多个指定的部署。

*HTTP Method:*

删除

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/deployments/{deploymentId}
----

*Parameters:*

*  id：要删除的部署（或多个部署）的ID。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X DELETE http://localhost:8080/mmc/api/deployments/'local$97e3c184-09ed-423e-a5a5-9b94713a9e36'
----

响应：

指定的部署被删除。

link:/mule-management-console/v/3.2/managing-applications-using-rest-apis[<<上一页：*使用REST API管理应用程序*]

link:/mule-management-console/v/3.2/managing-flows-in-a-server-using-rest-apis[Next：*使用REST API管理服务器中的流*] >>
