= 使用REST API管理群集

管理控制台提供了REST API，您可以通过它编程访问控制台的大部分功能。您可以通过REST API请求的操作包括与管理群集相关的操作。这包括创建，删除和获取有关群集的信息以及在群集中启动，停止和重新启动应用程序。

[NOTE]
有关REST API的概述，请参阅 link:/mule-management-console/v/3.2/using-the-management-console-api[使用管理控制台API]，其中包括使用的基本示例以及返回的状态代码和错误处理代码的摘要。

此页面提供了有关群集管理的每个REST API的简要说明，调用API的HTTP方法以及用法示例。这些示例显示了如何使用命令行HTTP工具 http://curl.haxx.se/[卷曲]调用API。符号\ {mmc base}指的是控制台的基地址。

注意：符号\ {mmc base}指的是控制台基址。示例中使用的控制台基址为http：// localhost：8080 / mmc，并使用默认用户名和密码（admin：admin）进行配置。

下表总结了用于集群管理的REST API：

[%header%autowidth.spread]
|===
|任务 |资源 |描述 | HTTP调用方法
|获取群集 | \ {mmc base} / api / clusters  |返回所有群集的列表 | GET
|获取有关群集 | \ {mmc base} / api / clusters / <cluster>  |的信息返回有关特定群集 |的信息GET
|创建群集 | \ {mmc base} / api / clusters  |创建由指定服务器组成的群集 | POST
|停止群集 | \ {mmc base} / api / clusters / <cluster> / stop  |停止群集 | POST
|重新启动群集 | \ {mmc base} / api / clusters / <cluster> / restart  |重新启动群集 | POST
|解散集群 | \ {mmc base} / api / clusters / <cluster>  |解散集群 | DELETE
|列出群集中的应用程序 | \ {mmc base} / api / clusters / <cluster> / applications  |列出集群中运行的应用程序 | GET
|在群集中启动应用程序 | \ {mmc base} / api / clusters / <cluster> / applications / <application> / start  |启动应用程序群集 | POST
|停止应用程序集群 | \ {mmc base} / api / clusters / <cluster> / applications / <application> / stop  |停止应用程序群集 | POST
|在群集中重新启动应用程序 | \ {mmc base} / api / clusters / <cluster> / applications / <application> / restart {{4}群集 | POST
|===

== 获取群集

返回所有群集的列表。

*HTTP Method:*

得到

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/clusters
----

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/clusters
----

响应：

[source, code, linenums]
----
{
    "data": [
        {
            "clusterStatus": "OK",
            "deployments": [],
            "groupIds": [],
            "id": "6ab68dd4-1777-4681-ab22-e1f2e291b2d5",
            "lastRestarted": 1314980993138,
            "location": "N/A",
            "name": "rel",
            "nodeServerIds": [
                "local$cf6e2ba3-eb96-4d93-822a-9314acf36d32",
                "local$af7dbb22-bad8-4334-9f65-e42b597c23fb"
            ],
            "nodesUpCount": 2,
            "pausedServices": 0,
            "runningServices": 0,
            "status": "2 of 2 nodes online",
            "stoppedServices": 0,
            "totalServices": 0,
            "version": "1"
        }
    ],
    "total": 1
}
----

== 获取有关群集的信息

返回有关特定群集的信息。

*HTTP Method:*

得到

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/clusters/<cluster>
----

*Parameters:*

cluster：指定的集群ID或名称。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/clusters/rel
----

要么

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/clusters/'6ab68dd4-1777-4681-ab22-e1f2e291b2d5'
----

响应：

[source, code, linenums]
----
{
    "clusterStatus": "OK",
    "deployments": [],
    "groupIds": [],
    "id": "6ab68dd4-1777-4681-ab22-e1f2e291b2d5",
    "lastRestarted": 1314980993138,
    "location": "N/A",
    "name": "rel",
    "nodeServerIds": [
        "local$cf6e2ba3-eb96-4d93-822a-9314acf36d32",
        "local$af7dbb22-bad8-4334-9f65-e42b597c23fb"
    ],
    "nodesUpCount": 2,
    "pausedServices": 0,
    "runningServices": 0,
    "status": "2 of 2 nodes online",
    "stoppedServices": 0,
    "totalServices": 0,
    "version": "1"
}
----

== 创建一个群集

创建由指定服务器组成的集群。

*HTTP Method:*

POST

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/clusters
----

*Parameters:*

名称：新群集的名称。 +
版本：新群集的版本号。 +
节点：要由新集群集成的节点列表。

*Input Fields (JSON):*

name：要创建的集群的名称。 +
节点：将分配给新集群的服务器标识列表。此字段至少需要一个有效的服务器ID，否则会显示消息错误。如果ID不存在，操作将返回带有无效ID的错误消息。 +
版本：集群的版本号。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -d '{"name":"rel","version":"1","nodes":["local$cf6e2ba3-eb96-4d93-822a-9314acf36d32", "local$af7dbb22-bad8-4334-9f65-e42b597c23fb"]}' --header 'Content-Type: application/json' http://localhost:8080/mmc/api/clusters
----

== 停止或重新启动群集

停止或重新启动指定的群集。

*HTTP Method:*

POST

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/clusters/<cluster>/stop
----

要么

[source, code, linenums]
----
http://{mmc base}/api/clusters/<cluster>/restart
----

*Parameters*

cluster：要停止或重新启动的群集的名称或ID。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/clusters/rel/stop
----

要么

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/clusters/rel/restart
----

== 解散群集

*HTTP Method:*

删除

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/clusters/<cluster>
----

*Parameters:*

cluster：群集的名称或ID。

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X DELETE  http://localhost:8080/mmc/api/clusters/rel
----

响应：

没有反应。

== 列出群集中的应用程序

列出指定群集中的所有应用程序及其状态。

*HTTP Method:*

得到

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/clusters/<cluster>/applications
----

*Example:*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/clusters/rel/applications
----

响应：

[source, code, linenums]
----
{
    "data": [
        {
            "name": "test-app",
            "status": "STOPPED"
        }
    ],
    "total": 1
}
----

== 启动，停止或重新启动群集中的应用程序

*HTTP Method:*

POST

*URL:*

开始：

[source, code, linenums]
----
http://{mmc base}/api/clusters/<cluster>/applications/<application>/start
----

停止：

[source, code, linenums]
----
http://{mmc base}/api/clusters/<cluster>/applications/<application>/stop
----

重启：

[source, code, linenums]
----
http://{mmc base}/api/clusters/<cluster>/applications/<application>/restart
----

*Parameters:*

cluster：群集的名称或ID。

应用程序：应用程序的名称。

*Example (similar for starting and restarting):*

请求：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST  http://localhost:8080/mmc/api/clusters/Mule/applications/test-app/stop
----

响应：

[source, code, linenums]
----
{
    "data": [
        "test-app"
    ],
    "total": 1
}
----

要检查实际状态：

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/clusters/Mule/applications
----

响应：

[source, code, linenums]
----
{
    "data": [
        {
            "name": "test-app",
            "status": "STOPPED"
        }
    ],
    "total": 1
}
----

link:/mule-management-console/v/3.2/managing-servers-using-rest-apis[<<上一页：*使用REST API管理服务器*]

link:/mule-management-console/v/3.2/managing-applications-using-rest-apis[Next：*使用REST API管理应用程序*] >>
