= 管理Mule高可用性HA集群

管理控制台可让您管理服务器群集。群集是一组紧密合作的链接服务器。一旦将服务器添加到群集中，它们以多种方式运行，就好像它们是单个服务器一样。

[NOTE]
有关群集的概述（包括收益和最佳做法），请参阅 link:/mule-management-console/v/3.2/mule-high-availability-ha-clusters[Mule高可用性（HA）集群]。

您可以使用控制台执行以下与集群相关的任务：

*  link:/mule-management-console/v/3.2/creating-or-disbanding-a-cluster[创建一个集群]
*  link:/mule-management-console/v/3.2/deploying-redeploying-or-undeploying-an-application-to-or-from-a-cluster[将应用程序部署，重新部署或从群集中取消部署]
*  link:/mule-management-console/v/3.2/monitoring-a-cluster[监视群集，包括确定其状态]
*  link:/mule-management-console/v/3.2/creating-or-disbanding-a-cluster[“解散”或删除群集]

您还可以使用REST API以编程方式创建和管理集群。请参阅 link:/mule-management-console/v/3.2/managing-clusters-using-rest-apis[使用REST API管理群集]。

由于集群表示链接的服务器，因此您可以使用“服务器”选项卡提供的功能创建和管理集群您还可以使用通过“应用程序”选项卡提供的功能将应用程序部署到群集，这与将应用程序部署到单个服务器的方式大致相同。

link:/mule-management-console/v/3.2/mule-high-availability-ha-clusters[<<上一页：* Mule高可用性（HA）群集*]

link:/mule-management-console/v/3.2/creating-or-disbanding-a-cluster[下一步：*创建或解散群集* >>]
