= 使用REST API管理服务器中的流程

管理控制台提供了REST API，您可以通过它编程访问控制台的大部分功能。您可以通过REST API请求的操作包括与管理服务器中的流相关的操作。这包括查找服务器中的流程，以及启动和停止流程的端点。

[NOTE]
有关REST API的概述，请参阅 link:/mule-management-console/v/3.2/using-the-management-console-api[使用管理控制台API]，其中包括使用的基本示例以及返回的状态代码和错误处理代码的摘要。

此页面提供了用于管理服务器中的流的每个REST API的简要说明，调用API的HTTP方法以及用法示例。这些示例显示了如何使用命令行HTTP工具 http://curl.haxx.se/[卷曲]调用API。

注意：符号\ {mmc base}指的是控制台基址。示例中使用的控制台基址为http：// localhost：8080 / mmc，并使用默认用户名和密码（admin：admin）进行配置。

下表总结了用于管理部署的REST API：

[%header%autowidth.spread]
|===
|任务 |资源 |描述 | HTTP调用方法
|获取流 | \ {mmc base} / api / servers / <serverId> / flows  |列出服务器中的所有流 | GET
|获取流终端 | \ {mmc base} / api / servers / <serverId> / flows / <flowName> / <application> / endpoints  |列表流 | GET的所有端点
|开始或停止终结点 | \ {mmc base} / api / servers / <serverId> / flows / <flowName> / <applicationName> / endpoints / {{3} } / start（或stop） |启动（或停止）流 | POST的端点
|启动或停止流 | \ {mmc base} / api / servers / <serverId> / flows / <flowName> / <applicationName> /开始（或停止）  |开始或停止一个流 | POST
|===

此页面上的所有示例都使用服务器和数据，如下所示：

[source, json, linenums]
----
{
    "data": [
        {
            "agentUrl": "https://localhost:7777/mmc-support",
            "agents": [
                {
                    "description": "Mule ESB Enterprise Support (0.0.0.0:7777)",
                    "name": "mmc-support"
                },
                {
                    "description": "Clustering Agent",
                    "name": "_muleClusterSupportAgent"
                },
                {
                    "description": "JMX Agent",
                    "name": "jmx-agent"
                }
            ],
            "groups": [],
            "hostIp": "192.168.1.116",
            "href": "http://localhost:8585/mmc/api/servers/local$a6064a19-6bd9-477f-be68-5a7b83e8bd7f",
            "id": "local$a6064a19-6bd9-477f-be68-5a7b83e8bd7f",
            "muleServerId": "00_mmc-agent",
            "name": "Mule3.2",
            "pausedServices": 0,
            "runningServices": 4,
            "started": "Thu Sep 01 12:06:33 GMT-03:00 2011",
            "status": "OK",
            "stoppedServices": 0,
            "version": "3.2.0-RC3"
        }
    ],
    "total": 1
}
----

== 获取流量

列出服务器中的所有流。

*HTTP Method:*

得到

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/servers/{serverId}/flows
----

*Parameters:*

serverId：从中列出流的服务器的ID。

*Example:*

以下示例显示如何列出ID为本地$ a6064a19-6bd9-477f-be68-5a7b83e8bd7f的服务器的流量：

请求：

[source, code, linenums]
----
l --basic -u admin:admin http://localhost:8080/mmc/api/servers/'local$a6064a19-6bd9-477f-be68-5a7b83e8bd7f'/flows
----

JSON响应：

[source, code, linenums]
----
{
    "data": [
        {
            "asyncEventsReceived": 0,
            "auditStatus": "DISABLED",
            "averageProcessingTime": 0,
            "executionErrors": 0,
            "fatalErrors": 0,
            "favorite": false,
            "flowId": {
                "application": "test-app",
                "definedInApplication": true,
                "fullName": "EchoFlow [test-app]",
                "name": "EchoFlow"
            },
            "id": "local$a6064a19-6bd9-477f-be68-5a7b83e8bd7f/EchoFlow",
            "inboundEndpoints": [
                "http://localhost:65082/services/EchoUMO"
            ],
            "maxProcessingTime": 0,
            "minProcessingTime": 0,
            "processedEvents": 0,
            "serverId": "local$a6064a19-6bd9-477f-be68-5a7b83e8bd7f",
            "status": "RUNNING",
            "syncEventsReceived": 0,
            "totalEventsReceived": 0,
            "totalProcessingTime": 0,
            "type": "flow"
        }
    ],
    "total": 1
}
----

== 获取流终端

列出流上的所有端点。

*HTTP Method:*

得到

*URL:*

[source, code, linenums]
----
http://{mmc base}/api/servers/{serverId}/flows
----

*Parameters:*

*  serverId：服务器的ID。
*  applicationName：流程的应用程序名称。
*  flowName：流的名称。

*Example:*

以下示例显示如何在ID为本地$ a6064a19-6bd9-477f-be68-5a7b83e8bd7f的服务器中列出名为EchoFlow的流中的端点，该流的应用程序名称为test-app：

请求：

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/servers/'local$a6064a19-6bd9-477f-be68-5a7b83e8bd7f'/flows/EchoFlow/test-app/endpoints
----

*JSON Response*

[source, code, linenums]
----
{
    "data": [
        {
            "address": "http://localhost:65082/services/EchoUMO",
            "connector": "connector.http.mule.default",
            "filtered": false,
            "id": "endpoint.http.localhost.65082.services.EchoUMO",
            "routedMessages": 0,
            "status": "started",
            "synchronous": true,
            "tx": false,
            "type": "http"
        }
    ],
    "total": 1
}
----

== 开始/停止终结点

启动或停止指定流程的端点。

*HTTP Method:*

POST

*URL:*

开始：

[source, code, linenums]
----
http://{mmc base}/servers/{serverId}/flows/{flowName}/{applicationName}/endpoints/{endpointId}/start
----

停止：

[source, code, linenums]
----
http://{mmc base}/servers/{serverId}/flows/{flowName}/{applicationName}/endpoints/{endpointId}/stop
----

*Parameters:*

*  serverId：服务器的ID。
*  applicationName：流程的应用程序名称。
*  flowName：流的名称。
*  endpointId：要启动或停止的端点的名称。

*Example:*

请求：

启动一个端点：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/servers/'local$a6064a19-6bd9-477f-be68-5a7b83e8bd7f'/flows/EchoFlow/test-app/endpoints/endpoint.http.localhost.65082.services.EchoUMO/start
----

停止一个端点：

[source, code, linenums]
----
4a19-6bd9-477f-be68-5a7b83e8bd7f'/flows/EchoFlow/test-app/endpoints/endpoint.http.localhost.65082.services.EchoUMO/stop
----

JSON响应：

已成功启动/停止的端点列表。

[source, code, linenums]
----
["endpoint.http.localhost.65082.services.EchoUMO"]
----

== 开始/停止流程

开始或停止服务器中的流程。

*HTTP Method:*

POST

*URL:*

开始：

[source, code, linenums]
----
http://{mmc base}/api/servers/{serverId}/flows/{flowName}/{applicationName}/start
----

停止：

[source, code, linenums]
----
http://{mmc base}/api/servers/{serverId}/flows/{flowName}/{applicationName}/stop
----

*Parameters:*

*  serverId：服务器的ID。
*  applicationName：流程的应用程序名称。
*  flowName：流的名称。

*Example:*

请求：

开始流程：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/servers/'local$a6064a19-6bd9-477f-be68-5a7b83e8bd7f'/flows/EchoFlow/test-app/start
----

停止流动：

[source, code, linenums]
----
curl --basic -u admin:admin -X POST http://localhost:8080/mmc/api/servers/'local$a6064a19-6bd9-477f-be68-5a7b83e8bd7f'/flows/EchoFlow/test-app/stop
----

响应：

[source, code, linenums]
----
The flow started or stopped successfully
----

link:/mule-management-console/v/3.2/managing-deployments-using-rest-apis[<<上一页：*使用REST API管理部署*]

link:/mule-management-console/v/3.2/managing-flows-in-a-cluster-using-rest-apis[Next：*使用REST API管理群集中的流*] >>
