= 认证方法
:keywords: devkit, authentication, oauth, saml, kerberos, ntlm, ldap

API通常使用几种常见的认证协议。在大多数情况下，您可以在Anypoint Connector中至少实现一种身份验证方法。为帮助您理解这些方法之间的差异，本文档提供了每种最常用方法的简要说明。

== 基本认证

此认证方法要求客户通过输入用户名和密码来证明其真实性。例如，应用程序可能设计为访问用户的Facebook帐户，并检查用户的任何朋友"like"是否拥有自己的帖子。为此，应用程序必须能够访问用户帐户中的私人信息，并且可以通过要求最终用户提供他或她的用户名和密码来实现。

虽然这种身份验证方法可以满足应用程序的需求，但它也为应用程序开启了大量工作，而不仅仅是检查"self-liked"帖子。考虑到这一点，这种方法可能是不可接受的，因为提供用户名和密码凭据可能会导致恶意活动。

在DevKit中，使用连接管理框架启用基本身份验证。

==  OAuth 1.0＆2.0

用户名密码身份验证的一个广泛使用的替代方法是 http://oauth.net/[OAuth的]（授权的开放标准）。 OAuth协议允许第三方应用程序通过备用和受限令牌来限制对资源的访问。例如，使用OAuth，应用程序可以访问用户的帐户，而无需知道用户的实际登录凭据，从而限制应用程序执行选定的操作。

与其他协议不同，OAuth在Cookie中保留了一个状态（例如，已连接），因此无需在提交每个请求时发送令牌信息。通常，API使用两种版本的OAuth中的一种： http://oauth.net/core/1.0a/[OAuth 1.0a]和 http://tools.ietf.org/html/rfc6749[Oauth 2.0];连接到每个这些是微妙的不同。

有关详情，请参阅 link:/anypoint-connector-devkit/v/3.6/oauth-v1[OAuth V1]或 link:/anypoint-connector-devkit/v/3.6/oauth-v2[OAuth V2]。

==  HTTP基本认证

在HTTP事务的上下文中，基本访问身份验证是HTTP用户代理在提出请求时提供用户名和密码的方法。

有关更多信息，请参阅 link:/anypoint-connector-devkit/v/3.6/http-basic-authentication[HTTP基本认证]。

===  SAML

http://saml.xml.org/[SAML]（安全声明标记语言）是一种XML开放标准，允许第三方提供身份提供服务。在这种模式下，用户的密码驻留在身份提供商的（IdP）服务器中。每当用户请求登录到Web服务时，Web服务都将转向IdP以获取适当的凭据。此解决方案的好处包括最大限度地降低安全风险（减少钓鱼机会）以及简化用户的登录过程。

=== 的Kerberos

http://web.mit.edu/kerberos/[Kerberos的]是一个开放，复杂的协议，由MIT开发，并由许多其他Active Directory使用。相对于SAML来说，正确设置会更具挑战性，但它非常适合通过非安全网络进行通信，因为身份信息在每个阶段都会进行加密。 IdPs和服务提供商很难在此协议中直接互相交流;他们通过用户向对方发送加密信息。

客户端直接向Id Provider进行身份验证。然后给客户端提供密码，但在只有Web服务可以破解的密钥下编码。客户端将此编码密码发送给Web服务，该服务相信如果它可以破解它，则该客户端由IdP认可。

===  NTLM

http://msdn.microsoft.com/en-us/library/cc236621.aspx[NTLM]（NT LAN Manager）是Microsoft为Windows网络设计的一套安全协议。它在挑战 - 响应结构中使用三条消息，其中NTLM服务器提供身份验证。客户发送一个谈判请求来宣传其能力; NTLM服务器用挑战消息进行响应，并且客户端用认证消息进行响应。身份验证基于两个哈希密码值：NT哈希和LM哈希。

NTLM是一种旧协议，它没有实现任何更新的加密方法;因此，微软不再推荐它。它用于无法实现Kerberos的客户端，或者用于域控制器不可用的网络。在Active Directory中，NTLM已被Kerberos取代为默认身份验证协议。

===  LDAP

轻量级目录访问协议（LDAP）是一种通过互联网协议（IP）实现分布式目录信息（例如网络用户特权信息）的公共标准。使用LDAP身份验证时，用户名和密码存储在LDAP服务器上的数据库中。您希望对其进行身份验证的实体（无论是服务器，应用程序还是Web服务）查询LDAP服务器，然后授予或拒绝基于响应的身份验证。这可以避免将实体本身的用户名和密码存储在LDAP服务器的数据库中。

严格来说，身份验证发生在您连接的实体和LDAP服务器之间。确切的身份验证方法因实体和LDAP服务器的配置而异。有几种可用的方法，包括使用传输层安全性（TLS）的证书和加密。

用户名和密码存储在LDAP服务器上的数据库中，而不是服务提供商。确切的认证方法各不相同。有几种可用的方法，包括使用传输层安全性（TLS）的证书和加密。

==  DevKit身份验证方法

[%header,cols="2*"]
|===
|方法 |更多信息
|基本身份验证 | link:/anypoint-connector-devkit/v/3.6/connection-management[连接管理]
| OAuth 1.0  | link:/anypoint-connector-devkit/v/3.6/oauth-v1[OAuth V1]
| OAuth 2.0  | link:/anypoint-connector-devkit/v/3.6/oauth-v2[OAuth V2]
| HTTP基本身份验证 | link:/anypoint-connector-devkit/v/3.6/http-basic-authentication[HTTP基本认证]
| SAML  | link:/anypoint-connector-devkit/v/3.6/connection-management[连接管理]
|的Kerberos  | link:/anypoint-connector-devkit/v/3.6/connection-management[连接管理]
| NTLM  | link:/anypoint-connector-devkit/v/3.6/connection-management[连接管理]
| LDAP  | link:/anypoint-connector-devkit/v/3.6/connection-management[连接管理]
|===

== 另请参阅

link:/anypoint-connector-devkit/v/3.6/defining-attributes-operations-and-data-model[定义属性操作和数据模型]
