= 定义属性，操作和数据模型
:keywords: devkit, attributes, operations, data, model, static, dynamic

一旦你的身份验证工作，你可以开始添加功能到你的连接器。添加功能需要以下步骤：

* 添加可在连接器上提供可用于操作的状态信息的可配置属性
* 实现连接器上可用的操作
* 为传入和传出连接器操作的对象定义数据模型

本文档概述了选择数据模型的各种方法，并介绍了API访问的主要类型。您将学习在随后的页面中为其中的每个人建立连接器。

== 属性

连接器上的属性与任何Mule元素中的属性相似，并且它们在连接器的全局配置对话框中公开。在内部，它们是带有getter和setter的主`@Connector`类上的实例变量，因此可以在连接器的代码中引用和操作它们。

属性的一个常见用途是为连接器提供端点详细信息 - 例如，指定是否连接到开发沙箱端点或生产系统端点。
更多详细信息可以在 link:/anypoint-connector-devkit/v/3.6/defining-connector-attributes[定义连接器属性]中找到。

== 静态与动态数据模型

您连接的API的基础数据模型通常会推动设计决策，以表示数据出入连接器的最佳方式。总体目标是选择适合基础数据的表示形式，同时仍支持必要的元数据以处理 link:/mule-user-guide/v/3.6/datasense[DataSense]。

*  *Static data models*修复了目标支持的所有对象及其属性的定义。大多数服务，特别是相对简单的服务实现静态数据模型。对于使用静态数据模型的API，建议创建与通过连接器操作公开的对象相对应的普通旧Java对象（PO​​JO）。在对目标API进行修订之后，这些类不需要在单个部署中进行更改。
*  *Dynamic data models*启用应用程序对象及其属性的自定义。复杂的ERP应用程序通常实施动态数据模型，以便可以从一个客户到另一个客户进行定制。在动态数据模型的情况下，建议您使用Java键值映射来表示Mule中的应用程序对象。

有关更多详细信息，请参阅本文档中关于 link:/anypoint-connector-devkit/v/3.6/adding-datasense[添加DataSense]的静态数据模型和动态数据模型示例。

==  API访问方法和客户端实现样式

您为连接器编写的大部分Java代码都涉及调用目标上的操作，并在这些操作和Mule之间传递数据。这是连接器中变化最大的区域，并且包含大多数特定于目标的代码。

服务可以以多种方式公开操作。下表总结了最常见的结果，以及Mule推荐的用于与它们进行接口的客户端技术。

[%header,cols="3*a"]
|===
|服务API样式
|建议的方法
|注意事项
|预构建的Java客户端库
|使用客户端库
| *如果可用，这通常是调用远程服务的最简单方法。
| SOAP API
| Apache CXF
| *发布和使用SOAP Web服务的事实标准。
| REST API
|泽西客户端
| *可以处理几乎所有的REST API。
| RestCall注释
| * DevKit内置"pure" RESTful API的客户端
| *大多数REST风格的API不足"pure";在实践中，泽西客户更有效
|===

选择多种访问方法的=== 

一些服务暴露了多个API，可以通过不同的风格来适应不同的用例。例如，应用程序可能具有适合最常见用例的Java客户端库，以及使用不同模型公开更完整功能的较低级REST或SOAP API。选择适合您情况的投注。

== 另请参阅

*  *NEXT:*继续 link:/anypoint-connector-devkit/v/3.6/defining-connector-attributes[定义连接器属性]。
* 您也可以跳到您的特定用例中，检查 link:/anypoint-connector-devkit/v/3.6/anypoint-connector-examples[例子]。
