= 代理安全性：禁用弱密码
:keywords: configuration, agent, mmc

代理程序接收来自 link:/mule-management-console/v/3.7[Mule管理控制台]的连接请求，这是您可以用来监视和控制Mule ESB服务器和应用程序的图形工具。出于安全原因，从3.3.1开始，Mule代理拒绝使用弱密码的连接。即使代理只接受来自授权管理控制台的连接，如果环境受到安全审核（如 http://www.pcicomplianceguide.org/aboutpcicompliance.php[PCI合规性]的自动审核），禁用的弱密码也是非常有用的功能。

== 禁用密码

默认情况下禁用以下密码：

SSL_RSA_WITH_RC4_128_MD5 +
SSL_RSA_WITH_RC4_128_SHA +
SSL_RSA_WITH_3DES_EDE_CBC_SHA +
SSL_DHE_RSA_WITH_DES_CBC_SHA +
SSL_DHE_DSS_WITH_DES_CBC_SHA +
SSL_RSA_WITH_DES_CBC_SHA +
SSL_DHE_RSA_WITH_DES_CBC_SHA +
SSL_DHE_DSS_WITH_DES_CBC_SHA +
SSL_RSA_EXPORT_WITH_RC4_40_MD5 +
SSL_RSA_EXPORT_WITH_DES40_CBC_SHA +
SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA +
SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA

== 添加或删除已禁用的密码

禁用的密码在文件`mmc-support-app/WEB-INF/web.xml`中配置。该文件位于jar文件`$MULE_HOME/lib/mule/mmc-agent-impl-3.4.jar`中。

要添加或删除密码，请将`mmc-agent-impl-3.4.jar`解压缩到文件夹结构中，然后编辑`web.xml`。

配置由`excludedCipherSuites`参数控制：

[source, xml, linenums]
----
<context-param>
        <param-name>excludedCipherSuites</param-name>
        <param-value>
            SSL_RSA_WITH_RC4_128_MD5,
            SSL_RSA_WITH_RC4_128_SHA,
            SSL_RSA_WITH_3DES_EDE_CBC_SHA,
            SSL_DHE_RSA_WITH_DES_CBC_SHA,
            SSL_DHE_DSS_WITH_DES_CBC_SHA,
            SSL_RSA_WITH_DES_CBC_SHA,
            SSL_DHE_RSA_WITH_DES_CBC_SHA,
            SSL_DHE_DSS_WITH_DES_CBC_SHA,
            SSL_RSA_EXPORT_WITH_RC4_40_MD5,
            SSL_RSA_EXPORT_WITH_DES40_CBC_SHA,
            SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA,
            SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
        </param-value>
    </context-param>
----

修改`web.xml`后，将文件夹和文件重新打包为`mmc-agent-mule3-impl-3.3.x.jar`，覆盖原始.jar文件。然后，重新启动Mule以使更改生效。

== 测试密码

要测试代理是否接受弱密码，可以使用 http://www.openssl.org/[OpenSSL的]，这是SSL和TLS的开源工具包。

从终端运行以下命令：

[source, code, linenums]
----
openssl s_client -connect <host>:<port> -cipher LOW
----

如果代理不接受弱密码，则该命令应返回类似于以下内容的错误：

[source, code, linenums]
----
CONNECTED(00000003)
1679:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:/SourceCache/OpenSSL098/OpenSSL098-47/src/ssl/s23_clnt.c:607:
----
