= 连接传输和连接器
:keywords: anypoint, studio,  connectors, transports

本主题概述了连接器和传输的一般情况 - 它们是什么，如何使用它们，甚至提供一个关于如何开发它们的提示。

==  Anypoint连接器

Anypoint连接器的主要目的是为您提供一种简单的方法，连接到成千上万的软件即服务（SaaS）平台，而无需使用传输或处理每个API使用的不同协议。

MuleSoft的目标是促进连接器的创建，并为此我们开发了一个Web工具包。连接器本质上就是Java POJO，它与我们的套件一起工作，并被转换为Mule ESB的全功能组件。

=== 如何使用它们

要使用具有Mule流的连接器，可以将它们直接添加到您的Mule应用中，如下所示：

[source,xml, linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-module-s3</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>
----

或者，您可以将我们的套件生成的JAR部署到lib / user文件夹中，以共享多个应用程序之间的连接器。

一旦你部署了连接器JAR，在你的Mule应用配置中引用模式。以下是S3连接器的示例：

[source,xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
    xmlns:s3="http://www.mulesoft.org/schema/mule/s3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
       http://www.mulesoft.org/schema/mule/s3 http://www.mulesoft.org/schema/mule/s3/1.0/mule-s3.xsd
       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.1/mule.xsd
       ">
----

如何使用每个连接器取决于特定的连接器。您可以在https://www.anypoint.mulesoft.com/exchange/?type=connector[Anypoint Exchange]中找到可用连接器的列表。

=== 开发一个连接器

开发连接器与使用它们一样简单。详细了解开发连接器。

=== 限制

虽然发展仍在继续，但连接器尚未达到其全部潜力，尽管不断取得进展。以下是一些连接器不能完成的任务。

*  **Request-Reponse Only**：连接器被设计为请求 - 响应消息处理器。因此消息处理器内的每个操作都必须有一个请求来产生响应。你不能使用端点。

*  **Non-Dynamic Instancing**：虽然您可以在Mule应用程序中定义多个连接器，甚至可以在同一连接器的多个实例中定义多个连接器，但您无法在流中创建新的连接器。

*  *Global Configuration*：连接器只能全局配置，并且该配置适用于连接器支持的所有操作。您无法覆盖流程中的配置。

