= 分布式文件轮询
:keywords: file polling, cluster

*_Enterprise Edition_*

某些端点（例如 link:/mule-user-guide/v/3.6/file-connector[文件端点]或 link:/mule-user-guide/v/3.6/ftp-connector[FTP端点]）会定期轮询目录并读取在轮询的目录中创建的某些文件。这些文件可能驻留在远程文件系统上，包括属于 link:/mule-user-guide/v/3.6/mule-high-availability-ha-clusters[Mule高可用性（HA）群集]的节点的文件系统。

直到Mule 3.3.x，发送到集群的所有文件轮询请求都通过该集群中的单个节点进行传送。这通过避免文件系统同步问题的可能性来确保文件一致性，但具有引入瓶颈的缺点，降低了群集的性能。

Mule 3.4引入了对集群分布式文件系统的文件轮询，这使得可以在所有集群节点中轮询文件。默认情况下启用，此功能由以下端点使用：

*  link:/mule-user-guide/v/3.6/file-connector[文件端点]
*  link:/mule-user-guide/v/3.6/ftp-connector[FTP端点]
*  link:/mule-user-guide/v/3.6/sftp-connector[SFTP端点]

=== 要求

要使用分布式文件轮询，流程的 link:/mule-user-guide/v/3.6/flow-processing-strategies[处理策略]必须是同步的。如果处理策略是异步的，Mule将自动禁用分布式文件轮询，并恢复到旧的行为。

[TIP]
====
您可以使用 link:/mule-management-console/v/3.3[Mule管理控制台]中提供的图形界面创建和配置群集，也可以使用 link:/mule-management-console/v/3.6/creating-or-disbanding-a-cluster[编辑群集配置文件。]手动创建群集有关其他配置选项（包括群集网络参数），请参阅 link:/mule-user-guide/v/3.6/creating-and-managing-a-cluster-manually[手动创建和管理群集]。
====
