=  DotNet连接器常见问题
:keywords: dotnet connector, dotnet, dot net, microsoft, c#, c sharp, visual studio, visual basic

== 什么是DotNet连接器？

DotNet连接器允许应用程序从Mule流中调用.NET代码。

== 组件使用哪些版本的.NET Framework？

在调用.NET代码的Mule服务器上安装.NET 4.5（至少目前）的先决条件。 .NET组件本身可以为任何.NET框架版本编写。

== 远程计算机上安装的.NET程序集是否可以从DotNet组件中调用？

不，您必须安装您在本地Mule服务器上调用的.NET程序集。

==  Java平台（如Mule ESB）如何调用.NET代码？

MuleSoft使用允许Mule流桥接Java虚拟机和公共语言运行时（.NET CLR）的JNI桥。该连接器包含大量的工具代码，允许Mule执行代码的序列化和反序列化。

== 我可以在Linux或CloudHub上使用DotNet连接器吗？

目前，也没有支持的情况。 DotNet连接器依赖于.NET CLR，它目前仅在Windows机器上可用。 Mono项目目前不受支持。

== 为什么我应该对DotNet连接器感兴趣？

许多组织已经使用.NET Framework编写代码进行了标准化。此组件允许它们继续使用.NET构建接口，而无需将当前代码重写到Java中。 .NET开发人员可以继续使用他们的首选语言编写代码，同时还可以与Anypoint Platform集成。

== 如果我现有的.NET代码使用app.config文件来存储配置，DotNet连接器仍然可以利用此代码吗？

是的，这个代码仍然可以被利用。

== 与类似的Java组件相比，使用DotNet连接器的性能影响是什么？

在大多数Mule集成场景中，性能影响可以忽略不计。

== 我可以利用.NET 4.0 / .Net 4.5中提供的.NET异步功能吗？

当Mule ESB调用.NET代码时，它会以同步方式执行。你不能直接从Mule ESB调用异步方法。但是，您可以在.NET代码中异步调用其他方法。建议您不要使用这些.NET功能启动异步消息传递，而是实施Mule ESB的核心消息传递功能，如Scatter-Gather。

== 我的程序集是否必须强命名或签名？

不，程序集不必强命名或签名。

== 我能在Visual Studio中调试.NET程序集吗？

是的，可以通过手动将Visual Studio附加到Java进程来调试.NET程序集。

== 我能够在.NET中访问Mule消息属性吗？

是的，额外的Mule工具包括一个支持Mule消息的消息传递API。流量变量可以通过实现`Callable`来访问。

== 我可以使用.NET连接器调用任何DLL吗？

您可以在任何基于.NET的DLL中调用方法，无论是现有的二进制文件还是专门用于处理Mule应用程序中的消息的新构建的二进制文件。这些DLL可以使用任何.NET语言构建，包括托管的C ++，但它必须是.NET程序集。如果你需要调用本地C库，你可以在.NET中构建一个使用DllImport公开本地方法的包装器。
