= 测试Mule简介
:keywords: mule, tests, qa, quality assurance, verify, functional testing, unit testing, stress testing

本页面涵盖了您的Mule项目的测试选项。

通常，现有的捆绑测试可以满足您的许多测试需求。每个Mule ESB Maven项目中的`src/test/`目录都包含单元测试和功能测试。包含的Maven `tests`项目包含其他有用的功能和集成测试。

== 测试类型

配置和定制Mule时，您可以利用以下捆绑测试：

* 对您的简单扩展和自定义进行单元测试
* 对Mule配置和设置进行功能测试
* 对您的自定义模块和传输进行功能和单元测试
* 多个模块，传输和变换器等的集成测试
* 连接到嵌入式或外部服务的传输的系统测试
* 压力和性能测试

Mule在`org.mule.tck`和`org.mule.tck.functional`包中提供的功能测试类便于测试Mule系统配置以及自定义模块和传输。有关详情，请参阅 link:/mule-user-guide/v/3.6/functional-testing[功能测试]。

此外，Mule测试JAR文件包含抽象测试用例，可以对简单扩展（例如`AbstractTransformerTestCase`和`AbstractOutboundRouterTestCase`）以及您的自定义模块和传输进行单元测试（例如，{{3 }}，`AbstractReceiverTestCase`，`AbstractDispatcherTestCase`和`AbstractEndpointTestCase`）。有关详情，请参阅 link:/mule-user-guide/v/3.6/unit-testing[单元测试]。

== 性能测试

在确保您的设置和配置正确并且您的自定义功能正常工作之后，请确认您的系统正按预期运行。 link:/mule-user-guide/v/3.6/profiling-mule[骡轮廓包]可以识别您的定制中的内存泄漏。

== 持续集成测试

您可以利用持续集成测试来提高项目的可靠性。源代码的典型构建频率是每30分钟一次，而快照构建频率是每天一次。

== 使用IDE

您可以使用集成开发环境（IDE），如Anypoint Studio（基于Eclipse），Eclipse和IntelliJ来快速开发Mule应用程序。有关Anypoint Studio的更多信息，请参阅 link:/anypoint-studio/v/6/index[Anypoint Studio Essentials]。

通常，只需将Mule发行版附带的`src.zip`文件附加到项目中的Mule JAR中，以便在开发类时可以浏览源代码。

== 另请参阅

* 想要更多选项来测试您的Mule应用程序？尝试使用Mule测试框架 link:https://docs.mulesoft.com/munit/v/1.2.0/[MUnit]。




