#%RAML 1.0 Library
uses:
  odata: libraries/odataLibrary.raml

types:
  orders:
    (odata.remote): Orders
    properties:
      OrderID:
        type: number
        (odata.key): true
        (odata.nullable): false
        format: int32
        required: false
      ShipName:
        type: string
        (odata.nullable): false
        (odata.key): true
        maxLength: 40
      ShipAddress:
        type: string
        (odata.nullable): true
        (odata.key): false
        maxLength: 60
      OrderDate:
        type: date-only
        (odata.nullable): true
        (odata.key): false
      Freight:
        type: number
        (odata.nullable): true
        (odata.key): false
        (odata.precision): 3
        (odata.scale): 3
      Price:
        type: number
        (odata.nullable): true
        (odata.key): false
        format: float
      Priority:
        type: number
        (odata.nullable): true
        (odata.key): false
        format: int16
  customers:
    (odata.remote): Customers
    properties:
      CustomerID:
        type: string
        (odata.key): true
        (odata.nullable): false
        maxLength: 5
      CompanyName:
        type: string
        (odata.nullable): true
        (odata.key): false
        maxLength: 40
      ContactName:
        type: string
        (odata.nullable): true
        (odata.key): false
        maxLength: 30
      ContactTitle:
        type: string
        (odata.nullable): true
        (odata.key): false
        maxLength: 30