= 扩展Mule的参考
:keywords: customize, extend components, custom

Mule提供了大量可用于实现的默认功能。如果你需要不同的功能，你可以按照这个页面的描述来扩展Mule。

== 创建扩展

您可以为Mule创建五种基本类型的扩展：项目，模块，传输，示例和企业模式。

*  A *project*是一个独立的Mule应用程序。

*  A *module*是Mule中的一个相关功能包，例如XML模块，它提供了基于XML的实用程序，如过滤器和路由器。有关您可以使用的可用模块列表，请参阅 link:/mule-user-guide/v/3.9/modules-reference[模块参考]。

*  A *{{0}}*是一种通过特定协议在Mule流之间传输消息的模块。有关可以使用的可用传输列表，请参阅 link:/mule-user-guide/v/3.9/transports-reference[传输参考]。

*  *example*是您创建的示例应用程序，可帮助用户更快速地启动和运行。 Mule提供了几个例子。

*  *catalog*是Mule创建的Maven原型，用于帮助Mule用户创建自定义配置模式。

Mule提供了Maven原型，可以在几秒钟内为这些类型的功能创建模板，包括配置文件，单元测试和软件包。

原型充当向导，提示您提供输入，然后创建模板配置，源代码和单元测试文件。此外，如果您在创建的现有项目或模块上运行原型，Maven会为您更新它。

使用传输时，请注意，您可以 link:/mule-user-guide/v/3.9/configuring-a-transport[配置现有的传输]，或者您可以 link:/mule-user-guide/v/3.9/creating-transports[创建一个新的]。建议的方法是先尝试使用和配置现有的运输工具。

*  link:/mule-user-guide/v/3.9/extending-components[扩展组件]
*  link:/mule-user-guide/v/3.9/custom-message-processors[自定义消息处理器]
*  link:/mule-user-guide/v/3.9/creating-example-archetypes[创建示例原型]
*  link:/mule-user-guide/v/3.9/creating-a-custom-xml-namespace[创建一个自定义的XML命名空间]
*  link:/mule-user-guide/v/3.9/creating-module-archetypes[创建模块原型]
*  link:/mule-user-guide/v/3.5/creating-catalog-archetypes[创建目录原型]
*  link:/mule-user-guide/v/3.9/creating-project-archetypes[创建项目原型]
*  link:/mule-user-guide/v/3.9/creating-transports[创建传输]
*  link:/mule-user-guide/v/3.9/creating-custom-routers[创建自定义路由器]

== 开发您的扩展

在使用Maven原型开始之后，推荐的做法是使用诸如Eclipse或IntelliJ的集成开发环境（IDE）来开发您的Mule项目，传输，模块或示例。 Mule IDE允许您快速启动并运行Eclipse中的Mule进行开发。


== 促进您的扩展

创建新扩展后，您可以将其作为GitHub上的项目提交。这使您可以与Mule社区分享，以便在模块投入生产之前获得关于模块质量和设计的反馈。

== 国际化Mule

如果你在不讲英语的国家使用Mule，你可以通过国际化消息和例外中的字符串来扩展Mule。另外，您应该考虑一些准则，以确保您的代码处理不同的区域设置。有关更多信息，请参阅 link:/mule-user-guide/v/3.9/internationalizing-strings[国际化字符串]。

== 创建配置模式

通过创建自定义配置模式，您可以使用Mule达到新的生产力水平。按照本教程 link:/mule-user-guide/v/3.5/creating-catalog-archetypes[现在开始创建你自己的模式]进行操作。
