= 测试Mule简介
:keywords: munit, testing, unit testing

本页提供了Mule测试的简要概述，将测试概念链接到可用于测试Mule应用程序的工具，以及更深入的页面，详细介绍每个概念。

注：有关Java信息，请参阅 link:https://www.mulesoft.org/docs/site/3.8.1/testapidocs/[Mule Kernel 3.8.1测试API]。


== 测试类型

有几种类型的测试。可能的话，您可以根据您的特定需求（如特定上下文或产品）专注于一种或多种类型。

从Mule应用程序开发人员的角度来看，公平地说，在验证Mule应用程序的行为时，您应该关注两种主要类型的测试：

*  <<unit,"Unit testing">>
*  <<integration,"Integration testing">>

[[unit]]
=== 单元测试

_unit test_的概念可能会根据您正在编写的编程范例而有所不同，但它始终围绕着相同的核心概念：_验证单个源代码单元的正确性。

在单元测试的情况下，我们认为code_的_unit是应用程序中最小的可测试部分。应用程序的最小可测试部分究竟构成什么取决于应用程序。在Mule应用的情况下，我们认为最小的可测试部分是Mule流（`sub-flow`）;因此这是我们的代码单元。

理想情况下，每个测试用例应该相互独立。

提示：确保测试相互独立性是开发人员的工作。

您测试的代码可能与其他代码或组件单元交互，并且在设计单元测试时应考虑到这种可能性。良好的单元测试应确保隔离正在测试的代码单元，以避免由于被测代码单元发生故障而导致其他组件发生错误。

要隔离目标代码单元，请使用诸如<<MUnit>>提供的`mock`消息处理器之类的工具。


[[integration]]
=== 集成测试

代码单元在它们之间协作以创建实际的应用程序。您使用单元测试测试单个代码单元，然后使用_integration tests_测试代码单元之间的协作方式。

_Integration test_的目标是_验证代码和模块的不同单元如预期的一样工作。

理想情况下，集成测试应聚合已成功通过单元测试的代码模块单元。出于这个原因，你应该在你的单元测试之后运行你的集成测试。

根据您的应用程序的性质，集成测试可能需要沙箱，也就是您的应用程序要连接到的环境。在使用沙箱时，请注意确保沙箱中的数据状态正确，以便测试产生预期的结果。在运行集成测试之前和之后执行此操作。

== 使您的代码可测试

本节定义创建更容易测试的流程的指​​导原则。通常，编写可测试代码意味着创建更具可配置性，可扩展性和可读性的应用程序。

*  *Modularize your code:*
在不同文件中分解代码有助于提高可读性。通常的做法是对有助于实现共同目标的流程进行分组，或根据特定功能标准对代码进行分组。
+
对代码进行模块化，可以只加载实际希望测试的那部分代码，避免在测试过程中加载不必要的配置。

*  *Write short flows:*
长流量很难遵循，有时甚至更难以编码;当然他们很难维持。从单元测试的角度来看，长流程提供了可以由单个点触发的太多场景。长流量可能会迫使您执行非常复杂的评估来验证单个场景，并且最好避免。

*  *Define execution environments:*
使用占位符参数化您的代码。正常使用情况包括出站端点的地址，例如数据库或HTTP。使用占位符允许您在运行测试（单元或集成）时修改实际地址，并且更容易在环境之间推广您的代码（DEV / QA / UAT / PROD）。

=== 编写测试的一个词

就像你让你的代码可测试的一样，你应该把你的测试编码为可读和可维护的。

有帮助的是你给测试的名字。测试失败时按照看到的内容命名测试。该规则也适用于失败时由测试引发的错误。很难理解的东西比错误编写或模棱两可的错误信息更难理解。如前所述，避免长时间流动，因为它们难以遵循。编写测试代码，以便覆盖场景并明确故障条件。

==  MUnit

link:/munit/v/1.3[MUnit]是一个Mule测试框架，可以让您轻松使用单元测试和集成测试来自动测试Mule应用程序。 MUnit还提供了一套工具，例如消息处理器嘲讽框架，可让您在实际隔离中测试代码单元。

[NOTE]
在Mule Runtime v3.8及更新版本中运行的Mule应用程序只能使用MUnit v1.2.0或更高版本进行测试。



== 测试Mule定制组件 - 用于测试的传统工具

Mule提供使用Java代码测试自定义Mule应用程序的传统工具。这些工具提供测试功能，但缺少MUnit提供的某些功能，例如 link:/munit/v/1.2.0/mock-message-processor[嘲讽]。

link:/mule-user-guide/v/3.9/functional-testing[功能测试]

*  link:https://www.mulesoft.org/docs/site/3.8.1/testapidocs/org/mule/tck/AbstractMuleTestCase.html[AbstractMuleTestCase]

Mule还提供像 link:/mule-user-guide/v/3.9/profiling-mule[分析器包]这样的工具，用于帮助识别您定制的Mule扩展中的内存泄漏。

== 另请参阅

有关Mule测试的更多详细信息，请参阅以下页面：

*  link:/mule-user-guide/v/3.9/unit-testing[单元测试]
*  link:/mule-user-guide/v/3.9/functional-testing[功能测试]
*  link:/mule-user-guide/v/3.9/testing-strategies[测试策略]
*  link:/munit/v/1.3[MUnit v1.3]
*  link:/mule-user-guide/v/3.9/profiling-mule[剖析Mule]
