= 创建消息处理器

消息处理器是Mule的关键概念之一。为了在Mule中提供可用的Java方法，必须使用特殊的注释。 `@Processor`注解是方法注释，它将提示注释处理器可以将特定方法作为消息处理器来使用。

快速示例：

[source, java, linenums]
----
@Module(name = "myextension")
public class MyExtension {
 
   @Processor
   public void myMethod() {
       // code here
   }
----

方法`myMethod`可以通过以下方式从Mule调用：

[source, xml]
----
<myextension:myMethod />
----

==  @Processor Annotation

任何公共实例方法都可以使用`@Processor`进行注释，然后从Mule中调用。这些方法可以接收任何数量和类型的参数并具有任何返回类型。

[%header,cols="2*"]
|===
| {参数{1}}说明
|名称 | *Optional.*将调用此处理器的元素的xml名称。如果未指定，则为+
该名称将从该方法的名称派生。
|拦截 | *Optional.*将此值设置为true将触发拦截消息处理器的生成，而不是消息处理器。
|===

===  @可选

与`@Optional`带注释的实例变量相似，在方法参数上使用`@Optional`意味着从Mule调用此方法时不需要为此参数提供值。

例：

[source, java, linenums]
----
@Module(name = "optional")
public class OptionalModule {
 
    @Processor
    public double division(int sum1, int sum2, @Optional int divisor) {
        return (sum1 + sum2) / divisor;
    }
----

由于`divisor`参数不是必需的，因此执行以下操作将导致异常，因为它将尝试除以零（零为int的默认值）。

[source, xml]
----
<optional:division sum1="40" sum2="10"/>
----

===  @默认

如果未明确设置，则使用`@Default`注释的参数将采用此值。使用前面的例子：

[source, java, linenums]
----
@Module(name = "optional")
public class OptionalModule {
 
    @Processor
    public double division(int sum1, int sum2, @Optional @Default("1") int divisor) {
        return (sum1 + sum2) / divisor;
    }
----

由于`divisor`参数现在具有默认值`1`，因此以下内容正常执行并将有效负载设置为`50`。

[source, xml]
----
<optional:division sum1="40" sum2="10"/>
----

== 截取消息处理器

[CAUTION]
此功能已在3.0.3中重新编制。在3.0.3之前，它需要一个InterceptCallback。 InterceptCallback接口已被替换为SourceCallback。 SourceCallback提供了更大的灵活性，并支持更广泛的场景，如分离器。

拦截消息处理器处理拦截另一个侦听器消息处理器的Mule事件。拦截消息处理器负责决定处理是否应该继续，也就是说，是否应该调用链中的下一个消息处理器。

将`intercepting`参数设置为true时，该方法必须具有类型为`org.mule.api.callback.SourceCallback`的参数。

例：

[source, java, linenums]
----
@Processor(intercepting = true)
    public Object shouldContinue(SourceCallback afterChain, ...) throws Exception {
        if (...) {
            return afterChain.process();
        }
 
        ...
    }
----

== 限制

一些限制适用于可以使用`@Processor`进行注释的方法：

* 不能是静态的
* 不能是非公开的
* 不能有以`name`这个单词命名的参数
* 重载不受支持

== 更多信息

*  link:/mule-user-guide/v/3.2/message-sources-and-message-processors#message-processors[消息处理器]
