= 自定义Mule Studio集成

*Mule DevKit*使您能够将连接器与*Mule Studio*应用程序集成。

== 自定义Mule Studio

. 在存储连接器的`pom.xml`文件的目录中运行以下命令。 +
+
----
 mvn clean package -Ddevkit.studio.package.skip=false
----

. 默认情况下，DevKit会从Java方法，参数和实例变量名称以及JavaDoc注释中推断名称。

以下各节介绍了定制Mule Studio对话的注释并覆盖推断的值。 +
 +

===  @Placement注释

将此注释应用于实例变量和方法参数。它包含以下参数：

*  *order*  - 顺序是组内注释元素的相对顺序。所提供的价值可能会重复，在这种情况下，订单不能得到保证。该值是相对的，这意味着具有顺序10的元素优先于具有值25的元素。
*  *group*  - 组合是一种合理显示一个或多个变量的方式。如果没有指定组，则Mule会默认一个默认组。要在同一组中放置多个元素，请为该属性使用完全相同的值。
*  *tab*  - 标签是将注释元素分组在一起的合乎逻辑的方式。此属性指定应在其中显示注释元素的选项卡的名称。如果没有指定标签，那么Mule将采用默认标签。要在同一选项卡中显示多个参数或字段，请为每个参数使用完全相同的值。

===  @FriendlyName注释

将此注释应用于实例变量和方法参数，以提供覆盖`@Configurable`变量或`@Processor` / `@Source` {`@Transformer`方法参数的默认推断短名称的方法。 +
 +

===  @Summary注释

将此注释应用于实例变量和方法参数，以提供覆盖`@Configurable`变量或`@Processor` / `@Source` {`@Transformer`方法参数的默认推断描述的方法。 +
 +

===  @Password注释

应用此批注将字段或方法参数标识为密码，或者更一般地说，将其作为包含不应以纯文本显示的数据的变量。 +
 +

===  @Icons注释

应用这是一个类级注释来覆盖一个或多个所需图标的默认位置。路径需要相对于`/src/main/java`。 +
 +

== 提供许可协议的文本

当用户从存储库下载连接器时，他们必须接受您提供的许可协议。 `LICENSE.md`文件的默认位置与`pom.xml`文件位于同一目录中。 DevKit访问此目录以首先搜索`LICENSE.md`文件;如果它找不到，它会从别处获取许可证文本，然后创建一个新的`LICENSE.md`文件。以下序列描述了DevKit在搜索许可协议文本时的活动。

1.如果在与`pom.xml`相同的目录中存在`LICENSE.md`，DevKit将使用该文件并且不再搜索。

2.如果在与`pom.xml`相同的目录中存在`license.txt`，DevKit将使用该文件并不再搜索。

3.如果`pom.xml`文件包含*Licenses*部分，则DevKit会尝试从许可证的URL下载文本，然后将下载的内容另存为新的{{LICENSE.md} {文件并搜索否further￼。

4.如果所有尝试查找许可协议文本失败，则构建失败。 +
