=  DevKit概述

要了解*DevKit*，您只需了解Mule应用程序由 link:/mule-user-guide/v/3.3/mule-application-architecture[*流*]组成，并且根据_Pipes，*endpoints*之间的流程组件 link:/mule-user-guide/v/3.3/mule-studio-essentials[*消息处理器*]串联在一起和Filters_设计模式。消息处理器都实现了相同的简单Java接口，并且端点实现了类似但略有不同的接口。 （有关Mule应用程序体系结构的详细说明，请参阅 link:/mule-user-guide/v/3.3/mule-application-architecture[Mule应用程序架构]）。

除了消息处理器和端点之外，Mule还认识到另一种称为**{{0}}**的构建块。这些为特定的包或标准提供可插入的功能，例如RSS提要，PGP安全性或XML。

在内部，所有这些构建块都由包装在实现外部接口的Java类中的业务逻辑组成。为了实现这一点，业务逻辑必须具有一定的结构并提供一定的内部资源。

== 的devkit

*DevKit*旨在使您能够将业务逻辑作为简单的旧Java对象（PO​​JO）提供，并带有注释，用于标识要创建的消息处理器或端点类型所需的内部资源。 link:/anypoint-connector-devkit/v/3.3/how-the-devkit-works[DevKit如何工作]提供了关于此的详细信息。 DevKit生成符合某些Mule接口的代码，但您不必了解这些接口或生成的代码以使用DevKit。您只需要了解如何使用与您创建的各种构建块相关的注释。

定义构件块类型的注释属于课堂级别。 link:/anypoint-connector-devkit/v/3.3/writing-custom-modules[编写自定义模块]和 link:/anypoint-connector-devkit/v/3.3/creating-message-processors[创建消息处理器]描述如何使用`@Module`和`@Processor`注释。

因为它们与Mule应用程序之外的实体进行交互，所以使用`@Connector`注释构建块（称为*Cloud Connectors*，尽管它们可以连接到Mule应用程序之外的任何实体）往往比其他构建块更复杂。 link:/anypoint-connector-devkit/v/3.3/writing-custom-cloud-connectors[编写自定义云连接器]描述了如何使用`@Connector`注释。
