= 处理复杂类型

*Mule DevKit*支持以下类型：

[cols="2*a",frame=none,grid=none]
|===
|
*  INT
* 浮
* 长
* 字节
* 短
* 双
* 布尔
* 炭
*  java.lang.Integer中
*  java.lang.Float中
*  java.lang.Long中
*  {java.lang.Byte中{1}}
*  java.lang.Short中
*  java.lang.Double中
*  java.lang.Boolean的
*  java.lang.Character中
*  java.lang.String中
* 的java.math.BigDecimal
*  java.math.BigInteger中
*  java.util.Date
*  java.lang.Class中
* 的java.net.URL
*  java.net.URI中
|===

您可以通过引用传递其他类型，如下例所示：

[source, java, linenums]
----
@Processor
public void receiveAComplexType(MyComplexType myComplexType) { ... }
----

Mule DevKit 3.3使您能够使用处理器，特别是在Anypoint（TM） link:/anypoint-studio/v/6/datamapper-user-guide-and-reference[* *的DataMapper]使用该模块时。 DataMapper友好的模块倾向于在bean中传递信息，因为DataMapper可以从XML中提取Java bean的元数据。 DevKit 3.3还标准化了Mule传递参考的方式。

== 启用对复杂类型结构的支持

当`@Processor`方法接收到复杂类型时，DevKit将解构对象，然后构造可用于重建对象的模式。例如，不是像下面的例子那样编写代码，而是按照下面的示例，可以更快地编写代码。

[source, xml, linenums]
----
<bean-builder-transformer beanClass="MyComplexType">
  <bean-property property-name="color" value="red"/>
</bean-builder-transformer>
<ns:receive-a-complex-type myComplexType-ref="#[payload]"/>
----

[source, xml, linenums]
----
<ns:receive-a-complex-type>
    <ns:my-complex-type color="red"/>
</ns:receive-a-complex-type>
----

您可以在复杂类型中使用以下注释来控制模式生成：

*  `@Optional`
*  `@Default`

此外，复杂类型可以具有其他复杂类型的内部列表或映射。

== 标准化引用传递

DevKit 3.3标准化了通过引用传递对象的方式。列表和映射通过引用在子元素的`ref`属性中传递对象，如下例所示。

[source, java, linenums]
----
@Processor
public void receiveAList(List<String> strings) { ... }
----

[source, xml, linenums]
----
<ns:receive-a-list>
  <ns:strings ref="#[payload]"/>
</ns:receive-a-list>
----

在DevKit 3.3中，传递复杂对象的子元素也使用`ref`属性，如下例所示：

[source, xml, linenums]
----
<ns:receive-a-complex-type>
    <ns:my-complex-type ref="#[payload]"/>
</ns:receive-a-complex-type>
----

== 忽略复杂类型中的字段

`@Ignore`注释告诉DevKit忽略复杂对象内的字段，如下例所示

[source, java, linenums]
----
public class MyComplexType
{
    private String color;
     
    @Ignore
    private String description;
}
 
@Processor
public void receiveAComplexType(MyComplexType myComplexType) { ... }
----

DevKit从生成的模式中省略描述字段。例如，下面的代码片段失败了，因为注释处理器忽略了描述。

[source, xml, linenums]
----
<ns:receive-a-complex-type>
    <ns:my-complex-type color="red" description=""/>
</ns:receive-a-complex-type>
----
