= 管理连接

*Mule DevKit*可以围绕POJO生成自动连接管理。特殊注释会触发DevKit生成自动管理连接的代码。您注释了处理连接，断开连接和验证连接以及获取会话标识符的方法; Mule DevKit的*Annotation Processor*管理其余部分。

例如，如果第三方API由于会话过期而失败，则Mule DevKit会自动删除连接，建立一个新连接，然后重试该操作（请参阅下面的代码）。

[source, java, linenums]
----
@Connector(name = "saas")
public class SaaSConnector
{
    @Connect
    public void connect(@ConnectionKey String username, String password) { ... }
 
    @Disconnect
    public void disconnect() { ... }
 
    @ValidateConnection
    public boolean isConnected() { ... }
 
    @ConnectionIdentifier
    public boolean getSessionId() { ... }
}
----

==  `@Connect`注释

此注释指示负责创建连接的`@Connector`中的方法。连接器的连接管理器调用此`@Connect`注释。必须只有一个用`@Connect`注释的方法，否则编译失败。

用`@Connect`注释的方法必须：

* 为`public`
* 抛出`org.mule.api.ConnectionException`异常（DevKit不允许其他异常）
* 有一个`void`返回类型

==  `@Disconnect`注释

此注释指示负责处理连接的`@Connector`中的方法。连接器的连接管理器调用此`@Disconnect`注释。必须只有一个用`@Disconnect`注释的方法，否则编译失败。

用`@Disconnect`注释的方法必须：

* 为`public`
* 拒绝接收参数
* 有一个`void`返回类型

==  `@ValidateConnection`注释

此注释指示`@Connector`中的方法检查连接器是否实际连接。必须只有一个用`@ValidateConnection`注释的方法，否则编译失败。

用`@ValidateConnection`注释的方法必须：

* 为`public`
* 拒绝接收参数
* 返回`boolean`或`java.lang.Boolean`

==  `@ConnectionIdentifier`注释

此注释指示负责识别连接的`@Connector`中的方法。连接器的连接管理器为调试目的调用此`@Disconnect`注释。必须只有一个用`@ConnectionIdentifier`注释的方法，否则编译失败。

用`@ConnectionIdentifier`注释的方法必须：

* 为`public`
* 不是`static`
* 不接受参数
* 返回`java.lang.String`

==  `@InvalidateConnectionOn`注释

将此注释附加到包含`@Processor`或`@Source`注释的任何方法。 `@InvalidataeConnectionOn`接收一个参数，它是要捕获的异常的类。如果处理器/源引发异常，则`@InvalidateConnectionOn`会自动使连接失效。有关更多详细信息，请参阅 link:/mule-user-guide/v/3.3/configuring-reconnection-strategies[重新连接策略文档]。
