=  Mule DevKit

网络已经推出了数千种用于商业，IT，协作，社交媒体，电子商务和生产力的新应用程序。许多Web应用程序公开Web API以整合和自动使用这些应用程序及其管理的数据。

Mule包含许多连接器，可以很容易地将Mule应用程序连接到外部API。但是，您可能需要连接到目前不在Mule的武器库中的应用程序API。因此，我们引入了*Mule DevKit*以使开发人员能够构建自己的连接器。

除了创建连接器之外，DevKit还可以帮助您构建变压器，滤波器，传输等等。

=== 我应该从哪里开始？

审核 link:/anypoint-connector-devkit/v/3.3/devkit-overview[DevKit概述]，然后开始构建 link:/anypoint-connector-devkit/v/3.3/your-first-cloud-connector[您的第一个云连接器]。

=== 需要帮助？

如果您在开发云连接器时需要帮助，请访问 link:http://forums.mulesoft.com/[MuleSoft论坛]并将问题发布到社区。

=== 参考指南

使用左侧边栏中的导航树浏览Mule DevKit的文档。以下列表中的材料与新用户特别相关。

*  link:/anypoint-connector-devkit/v/3.3/writing-mule-extensions[写作骡子扩展]解释了如何使用Mule DevKit对Mule扩展进行编码，文档和打包。
*  link:/anypoint-connector-devkit/v/3.3/publish[发布]解释了如何与Mule社区共享Mule扩展。
*  link:/anypoint-connector-devkit/v/3.3/contribute[有助于]解释了该社区如何帮助改善Mule DevKit。 Mule DevKit项目源代码对整个Mule社区开放。
*  link:/anypoint-connector-devkit/v/3.3/how-the-devkit-works[DevKit如何工作]提供有关Mule DevKit的深入信息。
*  link:/anypoint-connector-devkit/v/3.3/devkit-glossary[DevKit词汇表]定义了Mule DevKit文档中使用的关键术语。
