= 必需的JavaDoc

为了正确生成文档，我们定义了一组最小的JavaDoc注释和标签。记得在文档中提供尽可能多的细节，以帮助用户更好地理解如何使用Mule扩展。

== 记录`@Module`和`@Connector`带注释的类

每个使用`@Module`或`@Connector`注解的类都必须具有类级别的JavaDoc注释，并对扩展进行高级别概述。还需要包含`@author`标签。

来自Zuora连接器的示例：

[source, code, linenums]
----
/**
 * Zuora is the leader in online recurring billing and payment solutions for SaaS and subscription businesses.
 * <p/>
 * This connector provides full access to the Z-Commerce platform API.
 *
 * @author MuleSoft, Inc.
 */
@Connector(name = "zuora")
public class ZuoraModule {
----

== 记录`@Configurable`带注释的字段

用`@Configurable`注释的每个字段都需要有一个JavaDoc注释，以简要解释该属性用于何种用途。

来自https://github.com/mulesoft/magento-connector [Magento连接器]的示例：

[source, code, linenums]
----
/**
     * The user name to access Magento Web Services
     */
    @Configurable
    private String username;
 
    /**
     * The password to access Magento Web Services
     */
    @Configurable
    private String password;
 
    /**
     * The address to access Magento Web Services
     */
    @Configurable
    private String address;
----

== 记录`@Processor`和`@Source`方法

每个用`@Processor`和`@Source`注释的方法都必须有一个JavaDoc注释。还需要这些方法的每个参数都有说明。另外，如果方法的返回类型不同于`void`，那么它应该带有`@return` JavaDoc标签和一个描述。

DevKit已经引入了一个自定义标签`@sample.xml`来提供如何使用Mule中每种方法的示例。当使用DevKit的自定义doclet生成文档时，此标记指向的示例将得到特殊处理。

来自Mongo连接器的示例：

[source, code, linenums]
----
/**
     * Creates a new collection. If the collection already exists, a MongoException
     * will be thrown.
     * <p/>
     * {@sample.xml ../../../doc/mongo-connector.xml.sample mongo:create-collection}
     *
     * @param collection the name of the collection to create
     * @param capped if the collection will be capped
     * @param maxObjects the maximum number of documents the new collection is able
     *            to contain
     * @param size the maximum size of the new collection
     */
    @Processor
    public void createCollection(String collection,
                                 @Optional @Default(CAPPED_DEFAULT_VALUE) boolean capped,
                                 @Optional Integer maxObjects,
                                 @Optional Integer size)
    {
        client.createCollection(collection, capped, maxObjects, size);
    }
----

请注意`@sample.xml`是如何使用的：在大括号内部放置他的标记，从src / main / java到示例所在的文件的相对路径，以及示例的逻辑名称。对于示例的逻辑名称，我们建议使用符号`myconnector:my-method-name`或`myconnector:myMethodName`。

`@sample.xml`标签指向的示例文件必须具有以下结构：

----
<!-- BEGIN_INCLUDE(myconnector:method-a) -->
// example here
<!-- END_INCLUDE(myconnector:method-a) -->
<!-- BEGIN_INCLUDE(myconnector:method-b) -->
// example here
<!-- END_INCLUDE(myconnector:method-b) -->
...
...
----

例如，SalesForce连接器示例文件如下所示：

[%header,cols="1*a"]
|===
^ | *examples file*
|
----
<!-- BEGIN_INCLUDE(sfdc:create) -->
<sfdc:create type="Account">
    <sfdc:objects>
        <sfdc:object>
            <Name>MuleSoft</Name>
            <BillingStreet>30 Maiden Lane</BillingStreet>
            <BillingCity>San Francisco</BillingCity>
            <BillingState>CA</BillingState>
            <BillingPostalCode>94108</BillingPostalCode>
            <BillingCountry>US</BillingCountry>
        </sfdc:object>
    </sfdc:objects>
</sfdc:create>
<!-- END_INCLUDE(sfdc:create) -->
<!-- BEGIN_INCLUDE(sfdc:upsert) -->
<sfdc:upsert type="Account" externalIdFieldName="InternalAccountCode">
    <sfdc:objects>
        <sfdc:object>
            <InternalAccountCode>A01596</InternalAccountCode>
            <Name>MuleSoft</Name>
            <BillingStreet>30 Maiden Lane</BillingStreet>
            <BillingCity>San Francisco</BillingCity>
            <BillingState>CA</BillingState>
            <BillingPostalCode>94108</BillingPostalCode>
            <BillingCountry>US</BillingCountry>
        </sfdc:object>
    </sfdc:objects>
</sfdc:upsert>
<!-- END_INCLUDE(sfdc:upsert) -->
...
...
----
|===
