= 关于Mule组件

组件决定了Mule事件在Mule应用中的处理逻辑。与连接器和模块一起，组件是Mule应用程序中流程的主要构建块。例子包括Scheduler，Scatter-Gather和For Each组件。

= 关于Mule组件

Mule应用程序模仿传统的程序化编程，其优点是数据映射被替换为DataWeave脚本（或可视化映射），而不是复杂的Java类和代码。但是，核心构建块是相同的。

//，产品语言应该与Studio对齐。

Mule应用程序是通过连接器（或在Studio的情况下，通过私有流和子流）将流组合在一起而构建的。

连接器和调度程序通过传入事件来触发流程。其他组件然后通过一系列链接步骤来转换和处理事件。

这些事件处理组件包括单独的事件处理器（如Logger或Transform组件）或其他出站连接器，这些连接器请求在流中稍后与其中的现有事件合并其他数据。

为了帮助组合和转换数据，事件处理器可以组合在一起执行其他常见的处理任务。这些分组被分类为路由器或范围。

范围（设计中心中的蓝色）将一系列事件处理器组合在一起，以将某些编程行为应用于该单独的事件处理器序列。

例如，一个Try范围可以让你隔离和处理特定流程序列中发生的任何错误。因此，您可能会在Try范围中封装出站HTTP请求连接器（也可能包含HTTP请求连接器之前和之后的某些其他周边组件），因此如果出现错误，您可以应用日志或补偿逻辑特定于该组分组。

A For每个作用域都会获取通常从当前输入事件中提取的数据集合，并将相同的事件处理器序列应用于集合中的每个项目。例如，可以使用For Each范围来处理从数据库查询返回的每个单独行或CSV文件中的每个单独行。

路由器（Design Center中的黄色）接受输入事件并将其路由到一个或多个单独的Mule组件序列。例如，Choice路由器应用DataWeave逻辑来选择多个路由中的一个，其中每个路由都是一个单独的事件处理器序列。 Scatter-Gather路由器将输入事件复制到每个路由，并且每个路由独立处理该事件。在每条路线处理完事件之后，所有路线的结果一起组合成一个输出事件。

Anypoint Studio和Anypoint Design Center都提供了可视化的方式来构建这些类别的Mule组件的流程。

== 仅在Anypoint Studio中添加Mule组件

Anypoint Studio提供更多更复杂的组件，以及在单个Mule应用程序中编写更复杂的行为和逻辑的能力。

首先，Anypoint Studio项目可以有多个流程，并可以在多个Mule配置文件之间划分这些流程。要在Design Center中实现相同的目标，您必须编写并部署单独的Mule应用程序。

Anypoint Studio流程可以相互引用，即使在其他Mule配置文件中也是如此。这避免了需要使用诸如Anypoint MQ，HTTP，FTP或其他连接器类型的连接器将流连接在一起。

其他事件处理器包括解析模板和用于显式设置和删除部分Mule事件的专用组件，例如设置变量，移除变量和设置有效负载。

并不是说您可以在Design Center中设置和删除变量并设置有效载荷，但是您可以在其他组件中执行此操作，而不是在独立组件中执行此操作。

其他路由器包括Scatter-Gather，Round Robin和First Successful路由器。

其他范围包括异步，缓存，流，子流和直到成功。


//注意：新的Splitter-Aggregator模块与For-Each范围相似，计划用于将来的版本。


Anypoint Studio项目还可以包含自定义Java Spring bean或其他脚本语言来构建自定义组件。


== 另请参阅

*  link:/connectors/index[连接器和模块]
