= 常见问题解答：如何在批处理作业中处理故障

在处理批处理作业实例时，批处理步骤中的处理器可能会失败或引发错误。在记录级别处理错误有三种选择：

.  *Finish processing*停止当前作业实例的执行。完成当前正在运行的记录的执行，但不要从队列中提取更多记录，并将作业实例设置为`FAILURE`状态。 On Complete阶段被调用。
使用`acceptExpression`和`acceptPolicy`属性指示后续批处理步骤如何处理失败的记录，而不考虑任何失败的记录.  *Continue processing*批处理
（`acceptExpression`和`acceptPolicy`属性指示后续批处理步骤如何处理失败的记录），直到批处理作业累积为止.  *Continue processing*批处理*maximum number of failed records*在这一点上执行将停止，就像在选项1中一样。

默认情况下，Mule的批处理作业遵循第一个错误处理策略，该策略暂停批处理实例的执行。上述行为通过`maxFailedRecords`属性进行控制

[%header,cols="30a,40a,30a"]
|===
|记录处理​​失败选项2 + ^ |批处理作业
|  |  *Attribute*  |  *Value*
| 找到失败的recod时停止处理
|  `maxFailedRecords` | `0`
无论失败记录的数量如何，| 无限期地继续处理
|  `maxFailedRecords`  | `-1`
| 继续处理，直到达到最大失败记录数
|  `maxFailedRecords`  |  `integer`
|===

[source, xml, linenums]
----
<batch:job jobName="Batch1" maxFailedRecords="0">
----

=== 跨越最大失败阈值

当批处理作业累积足够的失败记录以跨越`maxFailedRecords`阈值时，Mule会中止所有剩余批处理步骤的处理，直接跳至“完成”阶段。

例如，如果将`maxFailedRecords`的值设置为"10"，并且批量作业在三个批处理步骤中的第一个步骤中累计了10个失败记录，则Mule不会尝试通过剩余的两个批处理步骤处理批处理。相反，它将中止进一步处理并直接跳到On Complete以报告批作业失败。

如果批处理作业_没有_累积足够的失败记录以跨越`maxFailedRecords`阈值，则_all_记录 - 成功和失败 - 继续从批步骤到批步骤;使用过滤器来控制每个批次步骤处理的记录。

== 另请参阅

*  link:filter-records-batch-faq[常见问题解答：如何在批处理步骤中筛选记录]
