= 常见问题解答：了解批处理作业性能

在传统的在线处理模型中，每个请求通常映射到工作者线程。无论处理类型如何（同步，异步，单向，请求 - 响应，或即使请求在被处理之前暂时缓冲），服务器通常都会在请求和正在运行的线程之间以1：1的关系结束。 +
当涉及批处理作业时，所有记录都将在处理阶段开始之前首先存储在持久队列中，因此传统线程模型将不适用。

为了提高性能，运行时以100条记录的块为单位排队并安排批处理记录。这减少了I / O请求的数量并改善了操作的负载。 +
运行时的默认线程配置文件是每个作业16个线程。因此，在默认配置的批处理作业中，16个线程中的每一个处理一个由100条记录组成的块。 +
每个线程遍历该块处理每条记录，然后每个块都排队返回，并且过程继续。

考虑将一百万条记录放入一个3步批处理作业的队列中。在运行时，每个记录在进入作业阶段时都会收到并请求每条记录，至少会发生三百万次I / O操作。 +
性能需要有足够的可用内存来并行处理16个线程，这意味着将1600条记录从持久存储器移动到RAM中。记录和数量越大，批处理所需的内存就越多。 +

// [小费]
//您可以更改线程配置文件元素中每个作业的线程数量。

尽管16个线程的标准模型（每个批处理作业有100条记录适用于大多数用例），但可以考虑三种用例，您可能需要增加或减少块大小：

* 假设您有200条记录要通过批处理作业进行处理。使用默认的100个记录块大小，Mule一次只能并行处理两个记录。如果您请求的记录少于101条，则您的处理将变为顺序。如果您需要处理真正沉重的有效载荷，则排队处理一百条记录需要大量的工作内存。

* 考虑一个需要处理图像的批处理作业，平均图像大小为3 MB。然后您有100个有效负载为3 MB的块，正在处理16个线程。因此，您的默认线程配置文件设置将需要大约4.6 GB的工作内存，才能使这些块保持队列。您应该设置较小的块大小，以便通过更多作业分配每个有效负载，并减轻可用内存的负载。

* 假设有500万条记录的有效载荷如此之小，以至于您可以毫无问题地适应内存中的500条记录块。设置更大的块大小可以在不牺牲工作内存负载的情况下提高批处理作业时间。

要充分利用此功能，您需要了解块大小如何影响您的批处理作业。使用不同的值和测试性能进行比较测试有助于您在将此更改投入生产之前找到最佳块大小。

请记住，修改批处理块大小是可选的。如果您不应用更改，则默认值为每个块100个记录。

== 另请参阅

*  link:batch-job-concept[关于批处理作业]
