= 启用商业活动
:keywords: anypoint, studio, esb, business events

事件跟踪需要一些处理和网络开销来聚合和存储Mule服务器生成的事件，因此默认情况下，不支持跟踪支持它的连接器或消息处理器。但是，启用默认事件跟踪非常简单。您只需要显式配置跟踪默认事件的范围。您可以配置范围：

* 在流量级别。
* 在消息处理器（连接器或组件）级别上，该级别优先于流级别设置。

////
[NOTE]
====
消息处理器或连接器级别配置优先于流量级别配置。

* 如果您想为特定流启用所有默认事件：

* 如果要为特定的消息处理器启用默认事件（在本例中为全部路由器）：

* 如果要为特定流启用所有默认事件，但不为特定消息处理器启用（在本例中为全部路由器）：
====
////

[events_tracking_flow_level]
== 启用流量级别的事件跟踪

为流中允许事件跟踪的元素启用默认事件跟踪。

请注意，您可以禁用特定处理器或连接器的跟踪以覆盖流级启用。

. 从Mule应用程序中，单击以打开流程组件。
. 通过选择以下选项启用默认业务事件：
+
* 使用以下选项之一启用默认事件跟踪：
+
* 在用户界面中，您可以选中启用默认事件跟踪复选框。
* 在Studio XML中，您可以将此属性添加到`flow`元素，例如：
+
`<flow name="testFlow" tracking:enable-default-events="true">`
+
. （可选）为与此流相关的所有跟踪事件设置标识符，以便为事务显示有意义的信息，例如订单号。
+
* 在用户界面中，您可以选中使用交易ID并提供一个ID。
* 在Studio XML中，您可以将子元素添加到`flow`元素，如下所示：
+
[source, xml, linenums]
----
<flow name="flow">
  ...
  <tracking:transaction id="#[expression]" />
  ...
</flow>
----
+
. 保存您的设置。

[event_tracking_processor_level]
== 在消息处理器级别启用事件跟踪

您可以在支持事件跟踪的单个连接器和组件上启用事件跟踪。并非所有处理器都支持默认事件跟踪如果复选框不存在于消息处理器或连接器中，则不支持默认跟踪。

. 点击打开骡流中的消息处理器。
. 选择启用默认事件跟踪。
+
请注意，您还可以通过组件的Studio XML启用跟踪，例如：
+
[source, xml, linenums]
----
<flow name="flow">
  ...
    <choice doc:name="Choice" tracking:enable-default-events="true"/>
  ...
</flow>
----

[events_transaction_id]
== 自定义交易ID

您可以定义一个事务ID，以便在运行时分析跟踪事件时为事务显示有意义的信息（如订单号）。如果您没有自定义交易ID，Mule会默认分配一个数字交易ID。要使ID更符合用户的业务需求，您可以通过DataWeave表达式进行自定义。

确保您的自定义ID对于应用程序中的每个事务都是唯一的，这是很好的做法。以下示例基于从有效内容中提取的唯一订单ID设置唯一ID。

//标签在这里

[source, xml, linenums]
----
<flow name="flow">
...
  <tracking:transaction id="#[payload.orderId]" />
...
</flow>
----

== 另请参阅

link:business-events[关于商业活动]

////
== 代码摘要

*Namespace*：

[source, xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    ...
    xmlns:tracking="http://www.mulesoft.org/schema/mule/ee/tracking"
    xsi:schemaLocation="
        ...
        http://www.mulesoft.org/schema/mule/ee/tracking http://www.mulesoft.org/schema/mule/ee/tracking/current/mule-tracking-ee.xsd">
   ...
</mule>
----

*Example of custom event tracking*：

[source, xml, linenums]
----
<flow name="flow">
...
  <tracking:custom-event event-name="Retrieved Employee" doc:name="Retrieved Employee">
    <tracking:meta-data key="Employee Id" value="#[payload['ID']]"/>
    <tracking:meta-data key="Employee First Name" value="#[payload['FIRST_NAME']]"/>
    <tracking:meta-data key="Employee Last Name" value="#[payload['LAST_NAME']]"/>
    <tracking:meta-data key="Employee Email" value="#[payload['EMAIL']]"/>
    <tracking:meta-data key="Employee Git ID" value="#[payload['GITHUB_ID']]"/>
  </tracking:custom-event>
...
</flow>
----


*Example of default event tracking at the flow level*：

[source, xml, linenums]
----
<flow name="flow">
...
  <tracking:custom-event event-name="Retrieved Employee" doc:name="Retrieved Employee">
    <tracking:meta-data key="Employee Id" value="#[payload['ID']]"/>
    <tracking:meta-data key="Employee First Name" value="#[payload['FIRST_NAME']]"/>
    <tracking:meta-data key="Employee Last Name" value="#[payload['LAST_NAME']]"/>
    <tracking:meta-data key="Employee Email" value="#[payload['EMAIL']]"/>
    <tracking:meta-data key="Employee Git ID" value="#[payload['GITHUB_ID']]"/>
  </tracking:custom-event>
...
</flow>
----

*Example of default event tracking at the message processor level*：

[source, xml, linenums]
----
<flow name="flow">
  ...
  <all tracking:enable-default-events="true" />
  ...
</flow>
----

*Example of customized transaction Id*：


[source, xml, linenums]
----
<flow name="flow">
...
  <tracking:transaction id="#[groovy:payload.orderId]" />
...
</flow>
----

////
