= 配置自定义商户活动

您可以使用自定义业务事件（`tracking:custom-event`）组件向您的流中添加元数据和关键绩效指标（KPI）。

. 在您的Mule应用中，将自定义业务事件组件添加到流中。
. 点击打开组件。
. 输入显示名称和事件名称的值。
. 或者，添加关键绩效指标（KPI）以捕获来自消息有效负载的信息：
+
* 名称（`key`）用于PKI（`tracking:meta-data`元素）。
+
输入一个可以在Runtime Manager的搜索界面中使用的名称，以及一个可能是任何Mule表达式的值。
+
* 表达式/值（`value`）用于PKI。
+
PKI列表示例：
+
[%header,cols="2*a"]
|===
| {名称{1}}的表达/值
|员工ID  | `#[payload['ID']]`
|员工电子邮件 | `#[payload['Email']]`
|员工Git ID  | `#[payload['GITHUB_ID']]`
|===

请注意，键/值对可以根据您的业务需求而有所不同。其他示例：

[%header,cols="2*a"]
|===
| {名称{1}}的表达/值
| `price`  | `700`
|价格后折 | `#[groovy:payload.price]`
|价格后折 | `'The price for the item is: ' #[groovy:payload.price]``
|===

== 另请参阅

link:business-events[关于商业活动]

////
// TODO：4.0是否允许？
== 共享PKI

在Studio中，您可以创建一个

[source, xml, linenums]
----
<tracking:custom-event-template name="template">
  <tracking:meta-data key="tier-level" value="platinum" />
  <tracking:meta-data key="price-after-discount" value="#[groovy:payload.price]" />
</tracking:custom-event-template>

<flow name="flow">
  <tracking:custom-event event-name="event1" inherits="template" />
  <tracking:custom-event event-name="event2" inherits="template" />
</flow>
----

你可以定义如何激发条件自定义事件。下面的代码显示了如何执行此操作：

[source, xml, linenums]
----
<choice>
  <when expression="INVOCATION:debugflag = on" evaluator="header">
    <tracking:custom-event event-name="success" />
  </when>
  <otherwise>
    <tracking:custom-event event-name="failure" />
  </otherwise>
</choice>
----

在最后一个示例中，如果在调用消息处理器时打开调试标志，则会触发事件名称为"success"的自定义事件。否则，会触发事件名称为"failure"的自定义事件。
////

////
// TODO：这真的需要吗？它在3.9 DOCS中不可见。

`tracking:custom-event`：自定义业务事件组件的顶级元素。

[source, xml, linenums]
----
<flow name="flow">
...
  <tracking:custom-event event-name="Retrieved Employee">
  </tracking:custom-event>
...
</flow>
----

定义自定义事件时，您还可以添加元数据。在该值中使用DataWeave从信息有效载荷中捕获信息。

[source, xml, linenums]
----
include::_sources/business-events_1.xml[]
----

您甚至可以将文本添加到表达式语言中，如以下示例所示：

[source, xml, linenums]
----
include::_sources/business-events_2.xml[lines="15..18"]
----
////

////
// TODO：这个需要被解释得更好或被删除
您还可以设置流程，以便可以在事件之间共享元数据。有关如何在流程中设置`tracking:custom-event-template`全局元素的详细信息，请参阅XML选项卡。

您还可以触发条件自定义事件来帮助跟踪消息在您的流程中的处理方式。例如，你可以在你的流程中设置一个选择路由器。
////
