= 关于缓存范围
:keywords: cache, anypoint, studio

Cache作用域用于存储和重用经常调用的数据。您可以使用Cache作用域来减少Mule实例的处理负载，并提高流中消息处理的速度。这对于这些任务特别有效：

* 处理对相同信息的重复请求。

* 处理涉及大量非消耗性有效负载的信息请求。

当Mule应用程序中的消息处理器向缓存作用域发送消息时，父流预期会有输出。 Cache范围处理消息负载，将输出传递给父流，并保存输出（即缓存响应）。 Cache范围下一次接收到相同类型的消息负载时，范围可以提供缓存响应，而不是再次调用可能耗时的过程。

例如，您可以使用缓存范围来管理客户的航班信息请求。许多客户可能会要求有关从旧金山飞往布宜诺斯艾利斯的航班的相同定价信息。您可以使用高速缓存作用域，以更少的时间安排向数据库发送请求，例如每十分钟一次向数据库发送请求，而不是使用大量处理能力向多个航空公司数据库发送单独请求，高速缓存的航班定价信息。数据的及时性不重要，Cache范围可以节省时间和处理能力。

请注意，您可以将任意数量的消息处理器（例如连接器或组件）放入高速缓存范围，并配置高速缓存策略以存储范围内发生的处理所产生的响应（其中包含响应消息的负载）。

== 缓存过程

缓存作用域仅缓存非消耗性有效负载。它不缓存消耗性有效载荷（例如流式载荷），它们在丢失前只能读取一次。

通常，缓存过程遵循以下顺序：

. 消息进入缓存作用域。
. 高速缓存范围确定消息有效负载是否可用。
. 缓存范围生成一个密钥来标识消息的有效负载。
+
默认情况下，Mule使用SHA256KeyGenerator和SHA256摘要为消息负载生成唯一密钥。但是，您可以通过自定义缓存策略设置自己的密钥。
+
. 缓存范围将新生成的密钥与先前处理的缓存响应进行比较，并将其保存在您设置的ObjectStore（推荐）或默认的`InMemoryObjectStore`中。
+
* 如果没有缓存的响应事件（_cache miss_），缓存作用域会处理新消息并产生响应。
+
它还将结果响应保存在对象存储中（如果响应是非消耗性的）。
+
* 如果存在缓存的响应事件（_cache hit_），则缓存策略会生成一个响应，将来自新请求和缓存响应的数据组合起来。
+
请注意，如果生成的响应具有可消耗的有效负载，则不会缓存响应。
+
. 缓存范围将响应推送到父流中以供继续处理。

==  缓存策略

缓存策略定义了缓存作用域在消息进入其子流时所采取的操作。默认情况下，缓存作用域使用缓存策略，将数据存储在InMemoryObjectStore中而不是ObjectStore中。 MuleSoft建议您仅将默认用于非生产目的，例如测试。对于生产环境，您应该设置使用ObjectStore的缓存策略。

您的缓存策略也可以引用这些自定义设置：

ObjectStore的* 事件密钥，它是一个DataWeave表达式或Java对象，用于创建用于在ObjectStore中存储有效内容的密钥。
您的策略的* 响应生成器，它是对Java对象的引用，用于创建缓存策略返回的响应。
针对可变数据或不可变数据的* 事件复制策略。
////
删除：
* 消耗性消息过滤器，它是对Java对象的引用，用于确定消息是否包含消耗性有效内容。
////

== 过滤器

基于DataWeave表达式，缓存作用域可以从缓存作用域流中排除特定的有效载荷，而不是处理它接收到的所有消息有效载荷。

== 另请参阅

link:cache-scope-to-configure[配置缓存范围]

link:cache-scope-strategy[设置缓存策略]
