= 示例：将函数传递为参数
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

它在接收两个参数的头文件中定义了一个基本函数：一个函数和一个应用它的元素。基函数将接收到的函数应用到接收到的元素的键上，也递归地应用于其每个子元素。在这种情况下，发送的功能将所有的键设置为小写。

该示例使用以下内容：

* 递归应用的自定义函数，即：它为其最初接收的元素中的每个子元素自动调用。
*  `mapObject`来排序元素的每个子元素。
来自字符串库的*  `lower`，使输入小写字母中的每个键成为可能。
*  `is`来检查传递的元素是否为`Object`类型（因此具有子元素）。
*  `if`和`else`只有当条件满足时才会调用自己的函数，否则会终止该分支的递归循环。



.DataWeave
[source,dataweave, linenums]
----
%dw 2.0
import * from dw::core::Strings
output application/xml
fun applyToKeys(element, func) =
    if (element is Object)
        element mapObject (value, key) -> {
        (func(key)) : applyToKeys( value, func)
        }
    else element
---
applyToKeys(payload, (key) -> lower(key))
----

。输入XML
[source,xml, linenums]
----
<CATALOG>
  <CD>
    <TITLE>Empire Burlesque</TITLE>
    <ARTIST>Bob Dylan</ARTIST>
    <COUNTRY>USA</COUNTRY>
    <COMPANY>Columbia</COMPANY>
    <PRICE>10.90</PRICE>
    <YEAR>1985</YEAR>
  </CD>
  <CD>
    <TITLE>Hide your heart</TITLE>
    <ARTIST>Bonnie Tyler</ARTIST>
    <COUNTRY>UK</COUNTRY>
    <COMPANY>CBS Records</COMPANY>
    <PRICE>9.90</PRICE>
    <YEAR>1988</YEAR>
  </CD>
</CATALOG>
----

。输出XML
[source,xml, linenums]
----
<?xml version='1.0' encoding='US-ASCII'?>
<catalog>
  <cd>
    <title>Empire Burlesque</title>
    <artist>Bob Dylan</artist>
    <country>USA</country>
    <company>Columbia</company>
    <price>10.90</price>
    <year>1985</year>
  </cd>
  <cd>
    <title>Hide your heart</title>
    <artist>Bonnie Tyler</artist>
    <country>UK</country>
    <company>CBS Records</company>
    <price>9.90</price>
    <year>1988</year>
  </cd>
</catalog>
----


== 相关示例

*  link:dataweave-cookbook-define-a-custom-addition-function[定义自定义添加功能]

*  link:dataweave-cookbook-map-based-on-an-external-definition[基于定义的动态映射]

*  link:dataweave-cookbook-define-function-to-flatten-list[定义在列表中展平数据的函数]

*  link:dataweave-cookbook-conditional-list-reduction-via-function[通过函数有条件地减少列表]


== 另请参阅


// * link:dw-functions-core[DataWeave核心功能]

*  link:dataweave-selectors[DataWeave选择器]

*  link:dataweave-cookbook[DataWeave食谱]
