= 示例：使用DataWeave映射数据
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, as

此示例使用DataWeave `map`函数遍历书籍数组，并对每个书籍执行一系列任务。

它使用这些DataWeave函数：

*  `map`遍历`books`数组中的每个对象。
*  `as`将价格数据强制转换为数字类型，以确保转换为每个元素生成正确的类型。


.DataWeave
[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
items: payload.books map (item, index) -> {
      category: "book",
      price: item.price as Number,
      id: index,
      properties: {
        title: item.title,
        author: item.author,
        year: item.year as Number
      }
}
----




。输入JSON
[source, json, linenums]
----
{
    "books": [
      {
        "-category": "cooking",
        "title": {
          "-lang": "en",
          "#text": "Everyday Italian"
        },
        "author": "Giada De Laurentiis",
        "year": "2005",
        "price": "30.00"
      },
      {
        "-category": "children",
        "title": {
          "-lang": "en",
          "#text": "Harry Potter"
        },
        "author": "J K. Rowling",
        "year": "2005",
        "price": "29.99"
      },
      {
        "-category": "web",
        "title": {
          "-lang": "en",
          "#text": "XQuery Kick Start"
        },
        "author": [
          "James McGovern",
          "Per Bothner",
          "Kurt Cagle",
          "James Linn",
          "Vaidyanathan Nagarajan"
        ],
        "year": "2003",
        "price": "49.99"
      },
      {
        "-category": "web",
        "-cover": "paperback",
        "title": {
          "-lang": "en",
          "#text": "Learning XML"
        },
        "author": "Erik T. Ray",
        "year": "2003",
        "price": "39.95"
      }
    ]
}
----

。输出JSON
[source, json, linenums]
----
{
  "items": [
    {
      "category": "book",
      "price": 30.00,
      "id": 0,
      "properties": {
        "title": {
          "-lang": "en",
          "#text": "Everyday Italian"
        },
        "author": "Giada De Laurentiis",
        "year": 2005
      }
    },
    {
      "category": "book",
      "price": 29.99,
      "id": 1,
      "properties": {
        "title": {
          "-lang": "en",
          "#text": "Harry Potter"
        },
        "author": "J K. Rowling",
        "year": 2005
      }
    },
    {
      "category": "book",
      "price": 49.99,
      "id": 2,
      "properties": {
        "title": {
          "-lang": "en",
          "#text": "XQuery Kick Start"
        },
        "author": [
          "James McGovern",
          "Per Bothner",
          "Kurt Cagle",
          "James Linn",
          "Vaidyanathan Nagarajan"
        ],
        "year": 2003
      }
    },
    {
      "category": "book",
      "price": 39.95,
      "id": 3,
      "properties": {
        "title": {
          "-lang": "en",
          "#text": "Learning XML"
        },
        "author": "Erik T. Ray",
        "year": 2003
      }
    }
  ]
}
----

[TIP]
请注意，当一本书有多个作者时，`item.author`将评估整个作者数组而不是单个名称。


== 使用默认值


以下示例执行与上述相同的转换，但未明确定义属性"item" ad "index"。相反，它会分别通过默认名称`$`和`$$`来调用它们。


.DataWeave
[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
items: (payload.books map {
      category: "book",
      price: $.price as Number,
      id: $$,
      properties: {
        title: $.title,
        author: $.author,
        year: $.year as Number
      }
})
----



== 相关示例

*  link:dataweave-cookbook-extract-data[提取数据]

*  link:dataweave-cookbook-perform-basic-transformation[执行基本转换]

*  link:dataweave-cookbook-rename-keys[重命名密钥]

*  link:dataweave-cookbook-map-object-elements-as-an-array[将对象元素映射为数组]

*  link:dataweave-cookbook-map-an-object[映射一个对象]

== 另请参阅

*  link:dataweave-types[DataWeave值类型]

// * link:dw-functions-core[DataWeave核心功能]

*  link:dataweave-selectors[DataWeave选择器]

*  link:dataweave-cookbook[DataWeave食谱]
