DataWeave中可用的= 外部函数
:keywords: lookup, properties, functions

除了由DataWeave提供的功能之外，还提供了许多功能
你的应用中的Mule运行时和模块/连接器。 。
这些函数可以在DataWeave脚本中使用，并在功能上提供超越
语言，特定于暴露它们的组件。

==  Mule运行时函数

这些功能始终可用，因为它们是由Mule Runtime注入的。

=== 访问属性

`p`函数提供对属性的访问，无论它们是：

*  Mule属性占位符
* 系统属性
* 环境属性

您可以阅读关于配置属性及其处理方式的更多信息 link:configuring-properties[这里]。

以下示例将记录属性`some.property`的值。

。示例：属性函数用法
[source,xml, linenums]
----
<flow name="simple">
  <logger message="#[p('some.property')]"/>
</flow>
----

=== 执行流程

`lookup`函数允许在您的应用程序中执行流程并检索
生成有效负载，将流的名称和输入有效负载作为参数。

指定的流程将使用当前属性，变量和
错误，只能替换参数1的有效负载，该参数必须是Java
类型。

详细了解`lookup` link:dataweave-lookup[这里]。

=== 按类型匹配错误

`causedBy`函数允许将错误类型作为错误处理程序进行匹配
将。当需要通过超类型进行匹配时，这是非常有用的，但是特定的子类型
还需要逻辑，或处理包含子项的`COMPOSITE_ROUTING`错误
不同类型的错误。

匹配的错误可能是隐含的，但类型始终是必需的参数。

在以下示例中，将设置一个全局错误处理程序来处理`SECURITY`
以一般方式出现错误，但为`HTTP:UNAUTHORIZED`设置了特定操作
和`HTTP:FORBIDDEN`错误。

。示例：错误匹配器函数用法
[source,xml, linenums]
----
<error-handler name="securityHandler">
  <on-error-continue type="SECURITY">
    <!-- general error handling for all SECURITY errors -->
    <choice>
      <when expression="#[error causedBy 'HTTP:UNAUTHORIZED']">
        <!-- specific error handling only for HTTP:UNAUTHORIZED errors -->
      </when>
      <when expression="#[causedBy('HTTP:FORBIDDEN')]">
        <!-- specific error handling only for HTTP:FORBIDDEN errors -->
      </when>
    </choice>
  </on-error-continue>
</error-handler>
----

请注意，显式和隐式都使用了错误参数。

== 连接器和模块功能

模块或连接器提供的功能仅在所述组件提供时才会被注入
在应用程序中使用。与运行时功能不同，使用它们需要提供
一个命名空间，通常会匹配组件名称。

例如，在使用批处理的应用中，可以使用以下表达式：`#[Batch::isSuccessfulRecord()]`。

检查每个组件文档以获取公开功能的列表。

== 另请参阅

*  link:dw-functions[DataWeave核心功能]
