= 示例：通过函数减少条件列表
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

// TODO：示例不工作，更改为if时。

这个例子将输入变得更简单。对于输入中的每个元素，只有在具有任何值时才有条件地包含"contentTypes"字段。然后它将这些内容重新排列成更可读的形状。


该示例使用这些函数：

*  `map`遍历输入数组中的每个元素。
*  `reduce`将"tags"数组中的多个元素聚合到一个字段中。
*  `splitBy`解析"tags"数组中的值，以便仅选择每个字符串的第一部分（通过`[0]`）并丢弃第二部分。
*  `++`将这些元素连接成一个单独的字符串，并用逗号作为分隔符。
*  `if`仅当"contentTypes"数组大于0时才包含最后一个字段。

.DataWeave
[source,dataweave, linenums]
----
%dw 2.0
output application/json
fun
reduceMapFor(data) data reduce(($$ splitBy ":")[0] ++ "," ++ ($ splitBy ":")[0])
---
payload.results map
    {
        email: $.profile.email,
        name: $.profile.firstName,
        tags: reduceMapFor($.data.interests.tags[0]),
        (contenttypes: reduceMapFor($.data.interests.contenttypes[0])) if (sizeOf($.data.interests.contenttypes[0])) > 0
    }
----

。输入JSON
[source,json, linenums]
----
{
  "results": [
    {
      "profile": {
        "firstName": "john",
        "lastName": "doe",
        "email": "johndoe@demo.com"
      },
      "data": {
        "interests": [
          {
            "language": "English",
            "tags": [
              "digital-strategy:Digital Strategy",
              "innovation:Innovation"
            ],
            "contenttypes": []
          }
        ]
      }
    },
    {
      "profile": {
        "firstName": "jane",
        "lastName": "doe",
        "email": "janedoe@demo.com"
      },
      "data": {
        "interests": [
          {
            "language": "English",
            "tags": [
              "tax-reform:Tax Reform",
              "retail-health:Retail Health"
            ],
            "contenttypes": [
              "News",
              "Analysis",
              "Case studies",
              "Press releases"
            ]
          }
        ]
      }
    }
  ],
  "objectsCount": 2,
  "totalCount": 2,
  "statusCode": 200,
  "errorCode": 0,
  "statusReason": "OK"
}
----

。输出JSON
[source,json, linenums]
----
[
  {
    "email": "johndoe@demo.com",
    "name": "john",
    "tags": "digital-strategy,innovation"
  },
  {
    "email": "janedoe@demo.com",
    "name": "jane",
    "tags": "tax-reform,retail-health",
    "contenttypes": "News,Analysis,Case studies,Press releases"
  }
]
----

== 相关示例

*  link:dataweave-cookbook-exclude-field[从输出中排除字段]

*  link:dataweave-cookbook-output-a-field-when-present[出现时输出字段]

*  link:dataweave-cookbook-use-constant-directives[使用常量指令]

*  link:dataweave-cookbook-define-function-to-flatten-list[定义在列表中展平数据的函数]

*  link:dataweave-cookbook-pass-functions-as-arguments[将函数作为参数传递]


== 另请参阅


// * link:dw-functions-core[DataWeave核心功能]

*  link:dataweave-selectors[DataWeave选择器]

*  link:dataweave-cookbook[DataWeave食谱]
