= 通过DataWeave调用Java方法
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping


从DataWeave语句中，您可以从Mule项目中的任何Java类中调用Java方法。请注意，只能通过DataWeave调用静态方法（属于Java类的方法，而不属于某个类的特定实例的方法）。


== 调用Java方法


在调用方法之前，必须先将它所属的类导入到DataWeave代码中。您可以像导入DataWeave模块一样导入Java类，方法是在语句中包含`java!`。

例如，下面是一个简单的Java类，它带有一个在字符串末尾附加随机数的单一方法。假设您将该类创建为您Mule项目的`src/main/java`文件夹中名为"utils"的Java包的一部分。

[source,java,linenums]
----
package utils;

import java.util.Random;

public class MyUtils {

	public static String appendRandom(String base) {
		return base + new Random().nextInt();
	}

}
----

您可以从DataWeave代码中调用此类中的方法`appendRandom()`，方法是首先导入该类，然后引用该方法，如下所示：

[source,DataWeave,linenums]
----
%dw 2.0
import java!utils::MyUtils
output application/json
---
{
	a: MyUtils::appendRandom("myString"),
}
----

这应该输出以下内容：

[source,json,linenums]
----
{
  "a":"myString969858409"
}
----

[TIP]
与导入DataWeave模块一样，您可以从类或所有方法中导入单个方法，而不是导入类。

== 实例化一个Java类

通过DataWeave代码，您可以实例化任何类的新对象。请注意，创建实例后，您无法通过DataWeave调用其实例方法，但可以引用其变量。


下面是一个简单的Java类，该类有一个方法和一个变量。

[source,java,linenums]
----
package utils;
public class MyClass {

	private String foo;
	 public MyClass(String foo) {
		 this.foo = foo;
	}

	 public String getFoo() {
		return foo;
	}

}
----

下面的DataWeave示例首先导入"MyClass"类，然后创建它的新实例并调用其实例变量"foo"。请注意，即使对象具有方法"getFoo()"，也不能通过DataWeave调用它。


[source,DataWeave,linenums]
----
%dw 2.0
import java!utils::MyClass
output application/json
---
{
	a: MyClass::new("myString").foo
}
----

这应该输出以下内容：

[source,json,linenums]
----
{
  "a":"myString"
}
----




== 另请参阅

*  link:dataweave-import-module[导入DataWeave模块]
// * link:dw-functions-core[DataWeave核心功能]
*  link:dataweave-formats[DataWeave格式]
