=  MapObject的

// * <<mapobject1>>
// * <<mapobject2>>


[[mapobject1]]
=====  mapObject（{（K）？：V}，（V，K，Number） - > Object）：Object

迭代对象中的键值对并返回对象。您
可以检索对象中任何键值对的键，值或索引。

此功能与`map`类似。但是，不是只处理值
对象`mapObject`将键和值作为元组处理。也，
而不是返回一个数组与处理这些值的结果
通过函数，它返回一个对象，它由一个列表组成
通过处理对象的键和值而产生的键值对
通过函数（lambda）。

该函数由三个参数调用：`value`，`key`和`index`。
第三个参数`index`是可选的。

。转变
[source,DataWeave,linenums]
----
%dw 2.0
output application/json
var conversionRate=13
---
priceList: payload.prices mapObject(value, key, index) -> {
  (key) : {
       dollars: value,
       localCurrency: value * conversionRate,
       index_plus_1: index + 1
   }
}
----

[[input_mapobject]]
。输入
[source,XML,linenums]
----
<prices>
    <basic>9.99</basic>
    <premium>53</premium>
    <vip>398.99</vip>
</prices>
----

[[output]]
.OUTPUT
[source,JSON,linenums]
----
{
  'priceList': {
    'basic': {
      'dollars': '9.99',
      'localCurrency': 129.87,
      'index_plus_1': 1
    },
    'premium': {
      'dollars': '53',
      'localCurrency': 689,
      'index_plus_1': 2
    },
    'vip': {
      'dollars': '398.99',
      'localCurrency': 5186.87,
      'index_plus_1': 3
    }
  }
}
----

对于示例中输入中的每个键值对，键都被保留，
并且该值成为具有两个属性的对象：原始值和
将原始值乘以常数的结果，即`var`
定义为DataWeave脚本标题中的指令。

重要：
当您使用参数来填充输出的其中一个键时，您必须
将参数括在括号内（例如，`(key)`）或
您需要在`&#36;`前面加上引号（for）
例如，`'&#36;key'`，如上所示）。否则，该属性的名称是
视为文字串。

如果您不指定参数的名称，则需要引用它们
占位符：`&#36;`为该键的`&#36;&#36;`和索引的`&#36;&#36;&#36;`，
例如：

。转变
----
%dw 2.0
output application/xml
---
{ 'price' : 9 } mapObject('$$' : $)
----

.OUTPUT
----
<?xml version='1.0' encoding='UTF-8'?>
<price>9</price>
----

下一个示例合并了// * <<input_mapobject, price input>>的每个索引
以上，以及输入键和值。

。转变
----
%dw 2.0
output application/json
---
priceList: payload.prices mapObject(
 ($$) : { '$$$' : $ }
)
----

请注意，索引被引号（`'&#36;&#36;&#36;'`）包围，因为此数字
键必须强制为一个字符串，不能是一个数字。或者，你
可以将`'&#36;&#36;&#36;'`写为`(&#36;&#36;&#36; as String)`。

当前面的脚本收到上面的// * <<input_mapobject, price input>>时，它就是
产生以下输出：

.OUTPUT
----
{
  'priceList': {
    'basic': {
      '0': '9.99'
    },
    'premium': {
      '1': '53'
    },
    'vip': {
      '2': '398.99'
    }
  }
}
----

下一个示例返回与第一个// * <<输出`mapObject`相同的输出
示例>>上面，它显式调用了命名参数
`(value, key, index)`。

。转变
----
%dw 2.0
output application/json
var conversionRate=13
---
priceList: payload.prices mapObject(
 ($$): {
   dollars: $,
   localCurrency: $ * conversionRate,
   index_plus_1: $$$ + 1
 }
)
----

当您使用参数来填充输出的其中一个键时，
与`&#36;&#36;`的情况一样，您必须将其用引号括起来
（例如`'&#36;&#36;'`）或括号（例如`(&#36;&#36;)`）。都
同样有效。



[[mapobject2]]
=====  mapObject（Null，（Any，Any，Number） - > Any）：Null

Helper函数允许`mapObject`使用空值。

