=  ++

// * <<plusplus1>>
// * <<plusplus2>>
// * <<plusplus3>>
// * <<plusplus4>>
// * <<plusplus5>>
// * <<plusplus6>>
// * <<plusplus7>>
// * <<plusplus8>>
// * <<plusplus9>>
// * <<plusplus10>>
// * <<plusplus11>>
// * <<plusplus12>>
// * <<plusplus13>>


[[plusplus1]]
=====  ++（Array <S>，Array <T>）：Array <S | T>


将两个数组的元素连接成一个新的数组。

如果两个数组包含不同类型的元素，则返回结果数组
是`Array<S>`的所有`S`类型元素，后跟所有`T`类型元素
的`Array<T>`。任何一个数组都可以有混合类型的元素。

该示例将`Array<Number>`与`Array<String>`连接起来。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  result: [0, 1, 2] ++ ["a", "b", "c"]
}
----

.OUTPUT
[source,JSON,linenums]
----
{
  "result": [0, 1, 2, "a", "b", "c"]
}
----

请注意，数组可以包含任何受支持的数据类型，例如：

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  a: [0, 1, true, "my string"] ++ [2, [3,4,5], {"a": 6}]
}
----

.OUTPUT
[source,JSON,linenums]
----
{
  "a": [0, 1, true, "my string", 2, [3, 4, 5], { "a": 6}]
}
----



[[plusplus2]]
=====  ++（String，String）：String

连接两个字符串的字符。

字符串被视为字符数组，因此`++`运算符连接在一起
每个String的字符就好像它们是单个字符String的数组一样。
在这个例子中，String'Mule'被视为`Array<String> ['M', 'u', 'l', 'e']`。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  name: 'Mule' ++ 'Soft'
}
----

.OUTPUT
[source,JSON,linenums]
----
{
  'name': MuleSoft
}
----


[[plusplus3]]
=====  ++（Object，Object）：Object

连接两个输入对象并返回一个扁平对象。

`++`运算符从每个对象中提取所有键值对，
然后将它们组合成一个结果对象。

。转变
[source,DataWeave,linenums]
----
%dw 2.0
output application/xml
---
concat: {aa: 'a', bb: 'b'} ++ {cc: 'c'}
----

.OUTPUT
[source,XML,linenums]
----
<?xml version='1.0' encoding='UTF-8'?>
<concat>
  <aa>a</aa>
  <bb>b</bb>
  <cc>c</cc>
</concat>
----

如果将输出保留为`application/dw`，则将上面的示例连接起来
来自两个对象`{aa: 'a', bb: 'b'} ++ {cc: 'c'}`和的每个键值对
返回单个对象`{aa: 'a' , bb: 'b', cc: 'c'}`。


[[plusplus4]]
=====  ++（Date，LocalTime）：LocalDateTime

用`Date`对象追加`LocalTime`并返回更精确的
`LocalDateTime`值。

`Date`和`LocalTime`实例是用标准的Java表示法编写的，
被管道（`|`）符号包围。结果是一个`LocalDateTime`对象
采用标准的Java格式。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  a: |2003-10-01| ++ |23:57:59|,
  b: |2003-10-01| ++ |23:57:59Z|
}
----

.OUTPUT
[source,JSON,linenums]
----
{
    'a': '2003-10-01T23:57:59',
    'b': '2003-10-01T23:57:59Z'
}
----

请注意，两个对象连接的顺序是不相关的，所以
在逻辑上，`Date` + `LocalTime`产生与`LocalTime` + `Date`相同的结果。



[[plusplus5]]
=====  ++（LocalTime，Date）：LocalDateTime

用`Date`对象追加`LocalTime`并返回更精确的
`LocalDateTime`值。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  a: |23:57:59| ++ |2003-10-01|,
  b: |23:57:59Z| ++ |2003-10-01|
}
----

.OUTPUT
[source,JSON,linenums]
----
{
    'a': '2003-10-01T23:57:59',
    'b': '2003-10-01T23:57:59Z'
}
----

请注意，两个对象连接的顺序是不相关的，所以
在逻辑上，`LocalTime` + `Date`产生与`Date` + `LocalTime`相同的结果。



[[plusplus6]]
=====  ++（日期，时间）：DateTime

追加`Date`到`Time`对象并返回更精确的`DateTime`
值。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  a: |2003-10-01| ++ |23:57:59|,
  b: |2003-10-01| ++ |23:57:59Z|
}
----

.OUTPUT
[source,JSON,linenums]
----
{
    'a': '2003-10-01T23:57:59',
    'b': '2003-10-01T23:57:59Z'
}
----

请注意，两个对象连接的顺序是不相关的，
因此在逻辑上，`Date` + `Time`产生与`Time` + `Date`相同的结果。



[[plusplus7]]
=====  ++（时间，日期）：DateTime

将`Date`附加到`Time`对象以返回更精确的`DateTime`值。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  a: |23:57:59| ++ |2003-10-01|,
  b: |23:57:59Z| ++ |2003-10-01|
}
----

.OUTPUT
[source,JSON,linenums]
----
{
    'a': '2003-10-01T23:57:59',
    'b': '2003-10-01T23:57:59Z'
}
----

请注意，两个对象连接的顺序是不相关的，
因此在逻辑上，`Date` + `Time`与`Time` + `Date`产生相同的结果。



[[plusplus8]]
=====  ++（Date，TimeZone）：DateTime

将`TimeZone`追加到`Date`类型值并返回`DateTime`结果。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
a: |2003-10-01T23:57:59| ++ |-03:00|
----

.OUTPUT
[source,JSON,linenums]
----
{
  'a': '2003-10-01T23:57:59-03:00'
}
----



[[plusplus9]]
=====  ++（TimeZone，Date）：DateTime

将`Date`追加到`TimeZone`类型值并返回`DateTime`结果。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
a: |-03:00| ++ |2003-10-01T23:57:59|
----

.OUTPUT
[source,JSON,linenums]
----
{
  'a': '2003-10-01T23:57:59-03:00'
}
----



[[plusplus10]]
=====  ++（LocalDateTime，TimeZone）：DateTime

将`TimeZone`附加到`LocalDateTime`类型值并返回`DateTime`
结果。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
a: |2003-10-01T23:57:59| ++ |-03:00|
----

.OUTPUT
[source,JSON,linenums]
----
{
  'a': '2003-10-01T23:57:59-03:00'
}
----


[[plusplus11]]
=====  ++（TimeZone，LocalDateTime）：DateTime

将`LocalDateTime`附加到`TimeZone`类型值并返回`DateTime`
结果。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
a: |-03:00| ++ |2003-10-01T23:57:59|
----

.OUTPUT
[source,JSON,linenums]
----
{
  'a': '2003-10-01T23:57:59-03:00'
}
----


[[plusplus12]]
=====  ++（LocalTime，TimeZone）：Time

将`TimeZone`追加到`LocalTime`类型值并返回`Time`结果。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
a: |2003-10-01T23:57:59| ++ |-03:00|
----

.OUTPUT
[source,JSON,linenums]
----
{
  'a': '2003-10-01T23:57:59-03:00'
}
----



[[plusplus13]]
=====  ++（TimeZone，LocalTime）：时间

将`LocalTime`追加到`TimeZone`类型值并返回`Time`结果。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
a: |-03:00| ++ |2003-10-01T23:57:59|
----

.OUTPUT
[source,JSON,linenums]
----
{
  'a': '2003-10-01T23:57:59-03:00'
}
----


