=  DataWeave函数参考

DataWeave函数被打包在模块中。 Core（`dw::Core`）模块中的函数会自动导入到您的DataWeave脚本中。要使用其他模块，您需要通过将import指令添加到DataWeave脚本的头部来导入要使用的模块或函数，例如：

*  `import dw::core::Strings`
*  `import camelize, capitalize from dw::core::Strings`
*  `import * from dw::core::Strings`

导入模块的方式会影响您需要从DataWeave脚本调用其功能的方式。如果指令未列出导入或使用`* from`从功能模块导入所有功能的特定功能，则需要在从脚本调用功能时指定模块。例如，此导入指令不会标识要从String模块导入的任何函数，因此它会调用`pluralize`函数，如下所示：`Strings::pluralize("box")`。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
import dw::core::Strings
output application/json
---
{ 'plural': Strings::pluralize("box") }
----

下一个示例标识要从String模块导入的特定函数，因此它可以调用此方法：`pluralize("box")`。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
import pluralize from dw::core::Strings
output application/json
---
{ 'plural': pluralize("box") }
----

下一个示例从String模块导入所有函数，因此它可以像这样调用方法：`pluralize("box")`。

。转变
[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Strings
output application/json
---
{ 'plural': pluralize("box") }
----

[[dw_modules]]
=====  DataWeave模块

*  link:dw-arrays[数组（dw :: core :: Arrays）]

*  link:dw-binaries[二进制文件（dw :: core :: Binaries）]

*  link:dw-core[核心（dw :: Core）]

*  link:dw-crypto[加密（dw :: Crypto）]

*  link:dw-diff[Diff（dw :: util :: Diff）]

*  link:dw-objects[对象（dw :: core :: Objects）]

*  link:dw-runtime[运行时（dw :: Runtime）]

*  link:dw-strings[字符串（dw :: core :: Strings）]

*  link:dw-system[系统（dw :: System）]

*  link:dw-url[网址（dw :: core :: URL）]

[[see_also]]
===== 另请参阅

link:dataweave[关于DataWeave]

link:dataweave-functions-lambdas[在DataWeave中使用函数和Lambdas]
