=  Mule 4简介：转换和流媒体

考虑Mule 4数据的方式在Mule 3中有根本的不同。在Mule 3中，你
通常需要了解底层的Java类型，如何管理InputStreams
有效载荷大于内存，以及如何将数据转换为Java对象，以便MEL可以访问它们。

对于Mule 4，推荐这些最佳实践：

* 避免对Java数据类型进行不必要的转换，并直接处理数据。
* 让运行时为您处理流式传输。
* 除非您正在执行与定制Java代码的直接集成，否则不要将二进制数据类型转换为`String`，`byte[]`或`InputStream`。

== 透明流媒体

link:intro-expressions[Mule 4：DataWeave表达式语言简介]展示了如何直接使用DataWeave处理数据。这种访问不同数据格式以及Mule 4流功能的能力意味着您不再需要先将数据转换为Java对象。这种改进极大地简化了运行时对数据的处理，因为：

* 数据可以多次读取，也可以使用DataWeave表达式语言随机访问，无副作用。
* 可以将数据发送到多个位置，而无需先将这些数据缓存到内存中。
* 您可以透明地访问大于内存的数据。

有关如何在Mule 4中使用流媒体的更多信息，请参阅 link:streaming-about[关于在Mule 4.0流媒体]。

== 数据类型和对象的字符串/字节/ InputStream变形金刚

由于Mule现在为您管理数据流，数据访问变得更简单。无论是`byte[]`，`InputStream`，`String`还是某种其他格式，您都不需要关心该类型的基础Java表示。

在Mule 3应用程序中观察到的一种常见模式是用户将事物转换为字符串以便记录或通过某些传输发送它们。这是必要的，因为流不能被消耗两次，所以需要一台变压器：

[source,xml,linenums]
----
<http:listener ... /> <!-- Obtains an InputStream payload -->
<object-to-string/> <!-- consume the stream and convert it to a String -->
<logger message="#[payload]"/> <!-- log the String -->
<http:request .../> <!-- send the String somewhere else-->
----

在Mule 4中，您可以简单地记录或发送数据，而不必担心底层类型或流消耗的次数。不要考虑`InputStream`，您应该将有效负载看作二进制数据。或者，如果您知道内容类型，则可以直接将其视为JSON，XML，
或者任何数据类型与内容类型相对应。

[source,xml,linenums]
----
<http:listener ... /> <!-- payload is JSON document -->
<logger message="#[payload]"/> <!-- log the JSON document -->
<http:request .../> <!-- send the JSON document somewhere else-->
----

== 另请参阅

*  link:streaming-about[关于在Mule 4.0流媒体]
