=  Mule 4：包装应用程序简介

== 应用程序结构
对Mule应用程序如何打包在Mule 4中几乎没有重要的改变。Mule应用程序是
现在打包成JAR并具有不同的结构。您可以使用Mule Maven插件轻松将您的源代码打包到这个结构中。

[%header,cols="3,2"]
|===
| {位置{1}}说明

| `META-INF/mule-artifact/mule-artifact.json`
您的Mule应用程序的|描述符（请参阅<<mule-artifact.json>>）。

| `META-INF/mule-src/yourapp/`
|您的源代码的可选位置。

| `repository`
| Maven布局中所有应用程序依赖项的存储库。这包括您的应用程序的所有连接器。例如，`repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar`

| `yourapp.xml`
|您的Mule XML代码。|
|===

== 骡artifact.json
Mule 4应用程序在`META-INF/mule-artifact/`中包含`mule-artifact.json`文件。这里描述你的应用程序，配置设置，
所需的Mule版本以及类加载器配置。

[source,json,linenums]
----
{
  "configs": [
    "ch-usage-sync.xml"
  ],
  "redeploymentEnabled": true,
  "name": "ch-usage-sync",
  "minMuleVersion": "4.0.0",
  "requiredProduct": "MULE_EE",
  "classLoaderModelLoaderDescriptor": {
    "id": "mule",
    "attributes": {
      "exportedResources": []
    }
  },
  "bundleDescriptorLoader": {
    "id": "mule",
    "attributes": {}
  }
}
----

==  Mule Maven插件
Mule 4中的Mule Maven Plugin将您的应用程序打包为所需的格式，并使您能够将其部署到目标环境中。 Studio 7会自动将插件添加到您的`pom.xml`。请参阅Mule Maven插件
文档以获取有关如何使用它来部署应用程序的信息。

== 另请参阅
 *  link:package-task-mmp[关于Mule Maven插件]
 *  link:mmp-deployment-concept[关于部署Mule应用程序（Mule Maven插件）]
