=  Mule 4：DataWeave表达式语言简介

在Mule 3中，你必须学习Mule表达语言（MEL）和DataWeave。 MEL强迫您将二进制数据（如XML或JSON文档）中的有效负载转换为Java对象，以便您可以编写访问该数据的表达式，例如，在路由到特定位置时。

在Mule 4中，DataWeave是默认的表达式语言。结合内置的流媒体功能，此更改简化了许多常见任务：

* 可以根据有效内容数据来路由事件，而无需转换为Java对象。
* 可以轻松地从流中的任何位置查询二进制数据，例如在日志记录时查询。
* 现在流式传输是透明的。您不再需要担心大于内存的数据流或关于消耗流两次。

DataWeave 2.0还具有许多改进功能，这些改进在 link:intro-dataweave2[DataWeave 2.0]部分进行了介绍。

在核心，表情继续像以前一样工作。您可以使用它们来提取数据，记录数据或决定在何处路由数据。和MEL一样，访问数据属性的语法非常简单。

[source,xml,linenums]
----
<logger message="#[payload]"/>
<set-variable variableName="httpResponseStatus" value="#[attributes.statusCode]"/>
----

与MEL不同，您可以使用DataWave轻松访问流中任何位置的数据，而无需担心将其转换为中间对象。在Mule 3中考虑这个例子：
[source,xml,linenums]
----
<http:listener path="/hello"/> <!-- receives a JSON HTTP Body -->
<json:json-to-object/> <!-- convert to Java objects -->
<choice> <!-- route data based on the data -->
  <when expression="#[payload.customer == 'Acme, Inc']">
    <!-- do some logic -->
  </when>
</choice>
----
在Mule 4中，您不再需要将JSON转换为中间格式。您可以直接通过表达式直接访问数据，而不会丢失原始基础数据，Mule 4可以透明地处理所有数据流和随机访问。
[source,xml,linenums]
----
<http:listener path="/hello"/> <!-- receives a JSON HTTP Body -->
<choice> <!-- route data based on the data -->
  <when expression="#[payload.customer == 'Acme, Inc']">
    <!-- do some logic -->
  </when>
</choice>
----

== 另请参阅

link:intro-transformations[转换和流媒体]

link:migration-dataweave[从DataWeave 1.0迁移到2.x]

link:dataweave[关于DataWeave]
// * TODO  - 脚本模块
