//联系人/中小企业：Ana Felissati，Pablo La Greca
= 迁移变形金刚

Mule 4不再需要`transformers`。既然DataWeave是默认的表达式语言，并且支持可重复流功能，则大多数（如果不是全部的话）需要变压器的场景不再存在。

== 迁移型变压器

在Mule 3中，可以使用不同的类型表示相同的数据。例如，可以使用`String`，`InputStream`，`OutputHandler`或`ByteArray`来存储JSON。同样，XML可以用相同类型或Java DOM文档表示。

在Mule 4中，每个不是二进制的格式都由Mule自动处理。因此，您不需要担心携带内容的类型。

===  InputStream到字符串转换

在Mule 3中，通常使用`<object-to-string-transformer>`，以便由`InputStream`保存的数据可以被多个处理器使用。由于Mule 4具有可重复流的概念，因此不再需要。

JSON和XML的=== 对象模型表示形式

要访问Mule 3中的XML或JSON文档的内容，需要转换为Java对象表示模型，以便稍后使用Java代码或MEL。在Mule 4中，运行时的表达式语言完全支持JSON和XML（以及许多其他格式），因此不再需要此转换。您只需使用DataWeave表达式来访问数据。

== 迁移自定义变形金刚

很可能，您用来处理DataWeave支持的格式的任何自定义转换器都不再需要，因此可以将它们迁移到使用表达式语言。如果需要在多个地方进行相同的转换，DataWeave脚本可以外化为文件。

对于以DataWeave不支持的方式转换数据的情况，应该使用Java模块或Scripting模块并使用自定义代码来执行转换。

== 另请参阅

link:dataweave[关于DataWeave]

link:/connectors/scripting-module[脚本模块]

link:/connectors/java-module[Java模块]

link:streaming-about[关于在Mule 4.0流媒体]

https://blogs.mulesoft.com/dev/mule-dev/why-dataweave-main-expression-language-mule-4/ [为什么DataWeave是Mule 4 Beta中的主要表达式语言]
