//作者：冈萨雷斯
= 迁移到AMQP连接器

//一般地解释Mule 3和Mule 4之间如何以及为什么会发生变化。
与其他情况一样，AMQP连接器完全重新塑造，并从Mule 3传输模型演变为基于操作的连接器，并具有简化的UX和完全支持DataSense的消息信息。
这意味着使用AMQP现在不仅可以提供与任何其他连接器相同的连接和配置体验，还可以根据结构化的消息信息更简单地发布和使用消息。

////
这些在Doc asciidoc文档中无法正确解析，并且它们也列在右侧的导航区域中

本节涵盖的内容：

*  <<Configuring The Connector>>
*  <<Connecting To A Broker>>
*  <<Sending Messages>>
*  <<Listening For New Messages>>
*  <<Consuming Messages>>
*  <<Responding To Incomming Messages>>
*  <<Doing Request-Reply>>
*  <<Using Transactions>>

////

[[ConfiguringTheConnector]]
== 配置连接器

从Mule 4中的3.x传输配置转换到AMQP Connector配置意味着基本上使用大部分相同的参数，但是以更紧密的方式声明它们。 Mule 4 AMQP Connector中的一些参数已更改。
这意味着例如用于消费消息的参数在'consumer-config'组中声明，而一般认证参数在General组中配置。此外，影响连接器（存在于配置中）行为的参数与仅影响建立连接的方式（连接级别存在）之间存在分离：

.Mule 3示例：配置连接器
[source, xml, linenums]
----
<amqp:connector name="AMQP_Config"
     fallbackAddresses="192.168.0.1,192.168.0.2"
     virtualHost="/"
     username="guest"
     password="guest"
	 deliveryMode="TRANSIENT"
	 priority="1"
	 ackMode="AUTO"
	 activeDeclarationsOnly="false"
	 mandatory="false"
	 immediate="false"
	 prefetchSize="16"
	 prefetchCount="16"
	 noLocal="false"
	 exclusiveConsumers="false"
	 requestBrokerConfirms="false"
	 numberOfChannels="10"
	  />
----

在Mule 4中实现相同的配置，在实际应用的环境中设置相同的参数：

.Mule 4示例：配置连接器
[source, xml, linenums]
----
<amqp:config name="AMQP_Config">
	<amqp:connection host="localhost" port="5672"
		virtualHost="/" username="guest" password="guest" />
	<amqp:consumer-config numberOfConsumers="10" exclusiveConsumers="false" noLocal="false" ackMode="AUTO"/>
	<amqp:publisher-config requestBrokerConfirms="false" mandatory="false" immediate="false" priority="1" deliveryMode="TRANSIENT"/>
	<amqp:quality-of-service prefetchSize="16" prefetchCount="16" />
</amqp:config>
----

请注意，`fallbackAddresses`不再受支持。


[[SendingMessages]]
== 发送消息

采用新的Mule 4方法，AMQP的“发布”操作仅依赖其输入参数来完成AMQP消息的发布。

例如，如果我们想发送一个高优先级的AMQP消息，并且只包含正文中的一部分负载，并将该消息关联到一个组，我们需要：
<1>）使用`transform`将有效负载设置为消息正文所期望的内容。
<2>）将生成的流转换为一个字符串以将其作为文本消息发送。
<3>）将`priority`设置AMQP属性作为设置AMQP消息优先级的关键。

.Mule 3示例：发送优先消息作为组的一部分
[source, xml, linenums]
----
<flow name="AmqpTransportOutbound">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/orders"/>
    <dw:transform-message> // <1>
        <dw:set-payload><![CDATA[%dw 1.0
%output application/json
---
{
order_id: payload.id,
supplier: payload.warehouse
}]]></dw:set-payload>
    </dw:transform-message>
    <object-to-string-transformer/> <2>
    <amqp:outbound-endpoint exchangeName="testExchange" connector-ref="AMQP_Conector" >
      <message-properties-transformer scope="outbound">
          <add-message-property key="priority" value="9"/> // <3>
      </message-properties-transformer>
    </amqp:outbound-endpoint>
</flow>
----

使用AMQP连接器的Mule 4具有以下配置可以实现相同的结果：

.Mule 4示例：发送优先消息作为组的一部分
[source, xml, linenums]
----
<flow name="AMQPConnectorPublish">
		<http:listener config-ref="HTTP_Listener_config" path="/orders"/>
		// <2>
		<amqp:publish config-ref="AMQP_Config" exchangeName="targetExchange> 
			<amqp:message> // <1>
				<amqp:body>#[output application/json --- 
        {
          order_id: payload.id,
          supplier: payload.warehouse
        }]</amqp:body>
        			<amqp:properties priority="3"/> // <3>
			</amqp:message>
		</amqp:publish>
	</flow>
----

差异要注意：

1）不需要`transform`组件，因为消息的`body`是内联创建的，因此有效负载保持不变。
2）`object-to-string`变压器也被移除，因为连接器可以自动处理变换输出。
3）优先级在AmqpMessage操作中被设置为属性，并且不依赖于用户知道确切的密钥。

作为总结，当使用AMQP传输在3.x中发布消息时，我们依靠AmqpMessage负载和出站属性来配置AMQP消息的创建，这意味着更深入地了解传输如何工作。在4.x中，AMQP Connector将每个可配置元素公开为它所属范围中的一个参数，从而以更清晰的方式公开所有AMQP功能。

[[ListeningForNewMessages]]
== 收听新邮件

AMQP传输`inbound-endpoint`允许您等待给定队列上的新AMQP消息。此侦听器的输出将包含有效内容中的消息正文，以及`AMQP Attributes`中包含的所有AMQP头和属性。

.Mule 3示例：收听消息
[source, xml, linenums]
----
<flow name="AMQPTransportInbound">
  <amqp:inbound-endpoint connector-ref="AMQP_Connector" queueName="in" />
  <dw:transform-message> // <2>
      <dw:set-payload><![CDATA[%dw 1.0
        %output application/json
        ---
        {
        items: payload,
        costumer: message.inboundProperties.'costumer_id'
        }]]></dw:set-payload>
  </dw:transform-message>
  <object-to-string-transformer/>  // <3>
  <amqp:outbound-endpoint exchangeName="v2/prime/orders" connector-ref="AMQP_Connector"/>  // <4>
</flow>
----

在这种情况下，我们正在侦听消息，然后将它们调整为所需的新格式：

1）使用包含在inboundProperties元数据转换MuleMessage使有效载荷，我们需要新的API的新JSON格式相匹配。
2）将转换后的有效内容转换为JSON字符串。
3）将有效载荷发布到定义的交换机。

在Mule 4中执行相同的操作如下所示：

.Mule 4示例：收听消息
[source, xml, linenums]
----
<flow name="AMQPConnectorPublish">
  <amqp:listener config-ref="AMQP_Config" queueName="in" /> // <1>
  <amqp:publish config-ref="AMQP_Config" exchangeName="ordersExcahnge"> // <2>
    <amqp:message>
      <amqp:body>#[output application/json ---
      {
        items: payload,
        costumer: attributes.properties.userProperties.costumer_id, // <3>
        type: attributes.headers.type
      }]</amqp:body>
    </amqp:message>
  </amqp:publish>
</flow>
----

现在，流的组件数量较少，不需要修改消息有效负载以使用不同的格式发布：

<1>新消息的定义是内联完成的，所以它只为新消息主体创建JSON。
<2>我们使用消息'attributes'POJO而不是'inboundProperties'，它现在区分AMQP Messsage的'标题'和'属性'。


[[ConsumingMessages]]
== 消费邮件

从给定的目标消费消息中等流动不是由骡子的3 AMQP运输支撑，要走的路还加入了“骡子请求者模块”您的应用程序，然后将处理中等流动的消息消耗。

所以，举个例子，如果你想公开你的AMQP队列，你的应用程序可能与此类似：

.Mule 3示例：消费中间流消息
[source, xml, linenums]
----
<flow name="ordersFromAMQP">
  <http:inbound-endpoint exchange-pattern="request-response" path="orders" host="localhost" port="8081"/>
  <scripting:transformer doc:name="AMQP Message Listening">
    <scripting:script engine="Groovy"><![CDATA[
org.mule.api.MuleMessage message = new org.mule.module.client.MuleClient(muleContext).request('amqp://recordsyntactic_exchange/amqp-queue?connector=AMQP_0_9_Connector&exchangeType=direct&queueDurable=true&exchangeDurable=true&queueAutoDelete=true', 10000L);
]]></scripting:script>
</flow>
----

这里需要注意的一些事情是：

* 有关AMQP消息的所有元数据完全丢失，因此记录CorrelationId依赖于您知道获取标题的语法。
* 我们需要AMQP和请求中队列的配置。

通过使用“消费”操作，Mule 4可以通过消费中间流量的功能开箱即用。这个操作与我们之前看到的监听器非常相似，区别在于它可以在流程中的任何地方使用：

.Mule 4示例：消费中等流量消息
[source, xml, linenums]
----
<flow name="ordersFromAMQP">
  <http:listener config-ref="HTTP_Listener_config" path="/orders"/>
  <amqp:consume config-ref="config"  queueName="Orders" />
  <logger level="INFO" message="#['CorrelationId: ' ++ attributes.properties.correlationId]"/>
</flow>
----

== 做请求 - 回复

AMQP允许您使用`reply_to`属性来执行RPC模式的实现。这可以通过由客户机动态创建的临时临时排他回复队列来完成，也可以使用已经存在的队列来完成。

=== 使用临时自动删除私人回复队列的请求回复

在Mule 3中，对于第一种情况，即回复队列是一个临时专用队列，一旦消息到达，它将被丢弃，我们在出站端点中有"request-response"交换模式：

.Mule 3示例：使用临时答复目标执行请求 - 答复
[source, xml, linenums]
----
<flow name="amqpRequestReplyTemporaryDestination">
  <http:inbound-endpoint exchange-pattern="request-response" host="localhost" port="8080" path="invoices"/>
  <dw:transform-message>
      <dw:set-payload><![CDATA[%dw 1.0
        %output application/xml
        ---
        {
        data: payload,
        costumer: message.inboundProperties."http.query.params".costumer_id
        }]]></dw:set-payload>
  </dw:transform-message>
  <object-to-string-transformer/> 
  <amqp:outbound-endpoint exchange-pattern="request-response" queueName="invoiceProcessor" connector-ref="AMQP_Connector"/>
  <logger level="INFO" message="Status: #[payload]">
</flow>
----

相反，在Mule 4中，您有一个名为`publish-consume`的全新操作，旨在解决此特定用例：

.Mule 4示例：使用临时答复目标执行请求 - 答复
[source, xml, linenums]
----
<flow name="amqpRequestReplyTemporaryDestination">
  <http:listener config-ref="HTTP_Listener_config" path="/invoices"/>
  <amqp:publish-consume config-ref="AMQP_Config" exchangeName="invoiceProcessor">
    <amqp:message>
      <amqp:body>#[output application/xml ---
      {
        data: payload,
        costumer: attributes.queryParams.costumer_id
      }]</amqp:body>
    </amqp:message>
  </amqp:publish-consume>
  <logger level="INFO" message="#['Status: ' ++ payload]">
</flow>
----

您可能会再次看到，消息的构建是在操作的内部完成的`message`元素中进行的，并且影响外发消息的任何转换或配置都将作为该元素的一部分完成。


=== 显式答复队列请求答复

用明确的`reply-to`队列做请求 - 回复可以通过replyTo属性在Mule 4中完成：

.Mule 4示例：使用显式答复执行请求 - 答复
[source, xml, linenums]
----
<flow name="amqpRequestReplyTemporaryDestination">
  <http:listener config-ref="HTTP_Listener_config" path="/invoices"/>
  <amqp:publish-consume config-ref="AMQP_Config" exchangeName="targetExchange">
    <amqp:message>
      <amqp:body>#[output application/xml ---
      {
        data: payload,
        costumer: attributes.queryParams.costumer_id
      }]</amqp:body>
      <amqp:properties replyTo="replyToQueue" />
    </amqp:message>
  </amqp:publish-consume>
  <logger level="INFO" message="#['Status: ' ++ payload]">
</flow>
----


[[UsingTransactions]]
== 使用事务

当从3.x移动到4.x时，交易支持在配置上非常相似，预期的变化将在`inbound-endpoint`和`outbound-endpoint`中配置为针对操作和来源的规范化Mule 4方法：

.Mule 3示例：使用事务
[source, xml, linenums]
----
<flow name="transactedAmqpFlow">
    <amqp:inbound-endpoint queue=Name"${in}">
        <amqp:transaction action="ALWAYS_BEGIN" /> //<1> 
    </amqp:inbound-endpoint>
    <set-variable variableName="originalPayload" value="#[payload]"/> //<2> 
    <dw:transform-message> //<3>
        <dw:set-payload><![CDATA[%dw 1.0
          %output application/xml
          ---
          payload
          ]]></dw:set-payload>
    </dw:transform-message>
    <object-to-string-transformer/>
    <amqp:outbound-endpoint exchangeName="${out}"> //<4>
        <amqp:transaction action="ALWAYS_JOIN"/>
    </amqp:outbound-endpoint>
    <default-exception-strategy>
        <commit-transaction exception-pattern="*"/> //<5>
        <set-payload value="#[flowVars.originalPayload]"/> //<6>
        <amqp:outbound-endpoint queue="dead.letter"> //<7>
            <amqp:transaction action="JOIN_IF_POSSIBLE"/>
        </amqp:outbound-endpoint>
    </default-exception-strategy>
</flow>
----

需要注意的是：

<1>事务由具有`ALWAYS_BEGIN`的入站端点启动
<2>我们确保不会丢失原有的有效负载
<3>有效负载被转换，因此可以通过出站端点发送
<4>出站端点被配置为`ALWAYS_JOIN`
<5>我们设置了异常策略来捕获所有异常
<6>原始有效内容已恢复，因此原始消息将发布到dead.letter
<7>最后，我们将原始邮件发送给尝试加入当前事务的dead.letter。


同样的情况可以通过以下方法在Mule 4中实施：

.Mule 4示例：使用事务
[source, xml, linenums]
----
<flow name="transactedAmqpFlow">
    <amqp:listener config-ref="AMQP_Config" queueName="${in}" transactionalAction="ALWAYS_BEGIN"/> //<1>
    <amqp:publish config-ref="AMQP_Config" destination="${out}" transactionalAction="ALWAYS_JOIN"> //<2>
        <amqp:message>
            <amqp:body>#[output application/xml --- payload</amqp:body>
        </amqp:message>
    </amqp:publish>
    <error-handler>
        <on-error-continue type="ANY"> //<3>
          <amqp:publish config-ref="AMQP_Config" exchangeName="dead.letter" transactionalAction="JOIN_IF_POSSIBLE"> //<4>
          	<amqp:routing-keys>
				<amqp:routing-key value="dead.letter" />
			</amqp:routing-keys>
          </amqp:publish>
        </on-error-continue>
    </error-handler>
</flow>
----

<1>交易由具有`ALWAYS_BEGIN`的`listener`发起
<2>以XML格式发布有效内容由`publish`操作完成，无需修改当前有效内容，也可以将事务与`ALWAYS_JOIN`结合
<3>捕获发生的任何错误的错误处理程序用于确保消息不会丢失
<4>由于当前有效负载仍然是接收到的原始消息，因此我们只需使用`JOIN_IF_POSSIBLE`事务操作将其发布到死信中

== 另请参阅

// link:migration-examples[迁移示例]

link:migration-patterns[迁移模式]
