// sme：afelisatti，作者：fer？
= 将异常策略迁移到Mule错误处理程序

以下示例将指导您完成不同异常的迁移
Mule 3的策略考虑了Mule 4中的新错误处理组件。

=== 捕获异常策略

// TODO：清理，漂亮

Catch Exception策略相当于一个包含一个`on-error-continue`的错误处理程序
接受所有错误的组件，这是默认配置：

.Mule 3示例
[source,xml,linenums]
----
<flow name="catch">
  <!-- flow logic -->
  <catch-exception-strategy>
    <!-- error handling logic -->
  </catch-exception-strategy>
</flow>
----

.Mule 4示例
[source,xml,linenums]
----
<flow name="catch">
  <!-- flow logic -->
  <error-handler>
    <on-error-continue>
      <!-- error handling logic -->
    </on-error-continue>
  </error-handler>
</flow>
----

=== 回滚异常策略
一个简单的（不重传）回滚异常策略相当于一个错误
处理程序具有接受所有错误的单个`on-error-propagate`组件，
这是默认配置：
// TODO：清理，漂亮

.Mule 3示例
[source,xml,linenums]
----
<flow name="rollback">
  <!-- flow logic -->
  <rollback-exception-strategy>
    <!-- error handling logic -->
  </rollback-exception-strategy>
</flow>
----

.Mule 4示例
[source,xml,linenums]
----
<flow name="rollback">
  <!-- flow logic -->
  <error-handler>
    <on-error-propagate>
      <!-- error handling logic -->
    </on-error-propagate>
  </error-handler>
</flow>
----

=== 随着Redelivery

// TODO：清理，漂亮

*  `idempotent-redelivery-policy`被重命名为`redelivery-policy`
*  `org.mule.runtime.core.api.exception.MessageRedeliveredException`已移至`org.mule.runtime.core.exception.MessageRedeliveredException`
`rollback-exception-strategy`中的*  `maxRedelivery`不再受支持。必须在`message-source`内部创建`<redelivery-policy>`元素`maxRedelivery`。

== 选择例外策略

具有内部捕获/回滚异常策略的选择异常策略是
相当于具有错误组件的错误处理程序继续/传播
到异常策略类型，如上所述：

// TODO：清理，漂亮

.Mule 3示例
[source,xml,linenums]
----
<flow name="choice">
  <!-- flow logic -->
  <choice-exception-strategy>
      <rollback-exception-strategy when="#[exception.causedBy(java.lang.IllegalStateException)]">
          <!-- error handling logic -->
      </rollback-exception-strategy>
      <catch-exception-strategy/>
    </choice-exception-strategy>
</flow>
----

.Mule 4示例
[source,xml,linenums]
----
<flow name="choice">
  <!-- flow logic -->
  <error-handler>
    <on-error-propagate when="#[exception.causedBy(java.lang.IllegalStateException)]">
      <!-- error handling logic -->
    </on-error-propagate>
    <on-error-continue/>
  </error-handler>
</flow>
----

== 参考例外策略

考虑到引用的异常策略已经根据
根据上述准则，迁移实际引用仅仅是添加引用`error-handler`。

// TODO：清理，漂亮

.Mule 3示例
[source,xml,linenums]
----
<flow name="reference">
  <!-- flow logic -->
  <exception-strategy ref="referencedHandler"/>
</flow>
----

.Mule 4示例
[source,xml,linenums]
----
<flow name="reference">
  <!-- flow logic -->
  <error-handler ref="referencedHandler"/>
</flow>
----

== 另请参阅

link:error-handling[关于错误处理]

https://blogs.mulesoft.com/dev/mule-dev/how-to-error-handling-mule-4-beta/[Blog：在Mule 4 Beta中查看错误处理]

////

link:migration-patterns[迁移模式]

link:migration-components[迁移组件]
////
