=  Mule 4组件更改参考
:keywords: studio, server, components, connectors, elements, palette, global elements, configuration elements

==  Mule核心变更

下表显示了Mule 3.x组件和表达式以及如何在Mule 4.0中替换它们。一些替代品可能仍在开发中并被标记为这样。

[%header,cols="30,70"]
|===
Mule 3.x组件| Mule 4.0替换|
所有路由器 |使用分散聚集，或者使用不同的目标属性依次执行操作，然后使用DW合并结果。|
async ['processingStrategy'] |非阻塞执行引擎不再需要异步处理策略。如果您希望它们异步行为，请使用包装所有组件的“异步”作用域。|
异步处理策略|非阻塞执行引擎不再需要异步处理策略。如果您希望它们异步行为，请使用包装所有组件的“异步”作用域。|
桥|移除。使用流量。|
catch-exception-strategy |使用错误处理程序和错误继续策略。|
choice-exception-strategy |在使用错误类型选择或属性时使用不同策略的错误处理程序。|
combine-collections-transformer |不再需要简化的消息模型。将MuleMessageCollections替换为Mule消息数组，可以通过使用任何Mule组件（如DataWeave或foreach）进行合并或迭代。|
组件|使用Java模块（开发中）。|
composite-source |为每个源创建一个流，并使用flow-ref为通用功能|
调用私有流
配置['defaultExceptionStrategy-ref'] |新名称是defaultErrorHandler-ref |
配置['flowEndingWithOneWayEndpointReturnsNull'] |不再需要新的执行引擎。|
配置[“useExtendedTransformations”] |移除。|
配置[enricherPropagatesSessionVariableChanges] |移除。|
复制附件|使用转换组件和DataWeave。|
copy-properties |使用转换组件和DataWeave。|
定制试剂|移除。|
自定义聚合器|在开发中进行替换以消除对自定义聚合器的需求。|
自定义连接器|使用SDK构建自定义连接器|
自定义异常策略{0}}不再需要。使用错误处理程序。|
自定义生命周期适配器工厂|无需替换。|
custom-object-store |使用对象存储模块扩展来创建自定义商店|
定制处理器|使用DataWeave，脚本组件，Mule SDK（开发中）或Java模块（开发中）。|
custom-queue-store |使用新的VM连接器（正在开发中）。|
定制路由器解析器|移除。|
定制路由器|移除。|
自定义服务|使用流|
custom-source |使用Mule SDK（开发中）编写新的事件源。|
custom-splitter |在开发中进行替换以消除对自定义分割器的需求。|
custom-transaction-manager |替换开发中。|
定制事务|移除。|
default-exception-strategy |使用带错误传播策略的错误处理程序。|
默认存储器队列存储|使用新的VM连接器（正在开发中）。|
default-persistent-queue-store |使用新的VM连接器（正在开发中）。|
default-service-exception-strategy |将错误处理程序与错误传播策略一起使用。|
端点|使用连接器。|
例外策略|使用错误处理程序。|
表达式组件|使用DataWeave，脚本组件，Mule SDK（开发中）或Java模块（开发中）。|
file-queue-store |使用新的VM连接器（正在开发中）。|
流[“processingStrategy”] |移除。非阻止执行引擎可确保用户无需调整此设置。|
idempotent-message-filter |替换开发中。|
idempotent-redelivery-policy |新名称是redelivery-policy。|
idempotent-secure-hash-message-filter |在有效负载上应用散列的函数可以用作idempotent-redelivery-message的id表达式属性值。|
内存中商店|使用对象商店模块扩展来创建自定义商店。|
入站端点|使用连接器。|
include-entry-point |使用Java模块（开发中）。|
拦截器堆栈|替换开发中。|
调用|使用Java模块（开发中）。|
jndi-transaction-manager |替换开发中。|
jrun-transaction-mamanger |替换开发中。|
legacy-abstract-exception-strategy |使用新的错误处理程序。|
托管商店|使用对象商店模块扩展来创建自定义商店|
message-properties-transformer |使用Transform组件和DataWeave |
模型|移除。改为使用流量。 |
骡[“版本”]
outbound-endpoint |元素从核心名称空间移动到newtransports名称空间|
解析模板
轮询 - >水印|使用对象存储模块手动设置水印值|
轮询|替换为调度程序源|
pooling-profile ['disabled'] |新属性|
处理器|使用DataWeave，脚本组件，Mule SDK（开发中）或Java模块（开发中）。|
prototype-object |使用Java模块或Spring模块|
队列轮廓|移除。|
队列店内|移除。|
收件人列表|移除。|
重新连接-定制通知|移除。|
重新连接-定制通知|移除。|
重新连接定制策略|移除。|
重新连接定制策略|移除。|
reconnect-notifier |替换开发中。|
remove-attachment |不再需要。附件可以存储为变量。|
remove-property |新消息模型中不再存在属性。您可以将来自Mule消息的属性存储在变量中。|
响应|移除。不再需要。|
request-reply | Mule 4将不再支持所有连接器的请求 - 应答。具有“请求 - 回复”行为的连接器将提供内置的“请求 - 回复”操作，例如JMS消费操作。|
resin-transaction-mamanger |替换开发。|
rollback-exception-strategy |使用错误处理程序和错误传播策略。|
scatter-gather ['threading-profile'] |现在不再需要Mule 4非阻塞。 |
seda-model | Mule 4中没有更多的SEDA队列。Mule 4中的执行引擎是非阻塞的。|
服务|使用流|
set-attachment |不再需要。附件可以存储为变量。|
set-property |新消息模型中不再存在属性。您可以将来自Mule消息的属性存储在变量中。|
set-session-variable |会话变量已被删除。用户必须明确地通过传输边界传递标头。|
内存中简单存储队列存储|使用新的VM连接器（正在开发中）。|
简单服务|使用流量。|
simple-text-file-store |使用对象存储模块扩展来创建自定义商店|
singleton-object |使用Java模块或Spring模块|
spring-object |使用Java模块或Spring模块|
同步处理策略|与流程组件执行相关的行为与4.x中的流程相同，但并不总是与3.x中的相同线程执行。|
交易范围|替换为“尝试”范围。|
username-password-filter |替换开发中。|
验证|移除。|
weblogic-transaction-manager |开发中的替换。|
websphere-transaction-manager |替换开发中。|
*  - 所有策略|移除。|
* -entry-point-resolver |使用Java模块（正在开发中）。|
* -filter |替换开发中。|
* -interceptor |替换开发中。|
* -message-info-mapping |替换开发中。|
* -point-resolver-set |使用Java模块（正在开发中）。|
* -router |移除。|
* -threading-profiled |现在它们属于传输命名空间|
* -transformer |替换开发中。|
|===

==  Mule模块和连接器

Mule 4包含Mule 3所有可用连接器的一个子集。下表显示了不推荐/删除的Mule 3.x模块以及如何在Mule 4.0中替换它们。所有其他Select和Premium连接器都在开发中。

[%header,cols="30,70"]
|===
Mule 3.x模块|  Mule 4.0替换
| Ajax 	| 使用API​​kit +标准REST。
| Atom 	| 替换为HTTP + DataWeave
| Axis 	| 使用WS Consumer / APIkit进行SOAP
| {Drools的{1}}移除。
| BPM | MuleSoft现在提供与Pega或Appian的BPM连接。
| {EJB {1}}移除。
| {吉斯{1}}移除。
| jBPM | MuleSoft现在提供与Paga或Appian的BPM连接。
| Jetty 	| 使用新的HTTP模块。
| OGNL 	| 在兼容性模块中替换了DataWeave表达式语言或MEL。
| {模式{1}}移除。改用流程。
| Quartz 	| 使用<poll>
| RSS 	| 使用HTTP + DataWeave
| SXC 	| 使用DataWeave。
| Tomcat  	| 开发中的新嵌入模式。
| Servlet 	| 开发中的新嵌入模式。
| {STDIO {1}}移除。
| UDP 	| 使用套接字。
| {XMPP {1}}移除。
|===

== 另请参阅

*  link:mule-runtime-updates[骡子有什么新鲜事4]
*  link:about-event-source[关于事件源]
*  link:about-event-processors[关于事件处理器]
