=  Mule的新功能4
:keywords: news, updates, mule ESB, mule runtime, 4.0, Mule 4.0, Mule 4.0 for mule 3 developers, what's new Mule 4

Mule 4的简化语言和降低的管理复杂性使您能够加快升级过程并更快地交付应用程序。

如果您熟悉以前版本运行时的概念，请查看下面的部分，以了解Mule Runtime v4.0中的变化。

== 简化的事件和消息模型

Mule 4包括一个简化的Mule事件和消息模型。在Mule 4中，流量由事件触发。一个事件有一个消息和与之相关的变量。消息由有效负载及其属性（元数据，如文件大小）组成。变量包含任意信息，例如消息，有效载荷数据或属性。这种简化的消息模型使跨连接器以一致的方式处理数据变得更加容易，而不会覆盖信息。

==  DataWeave 2.0：新的Mule表达式语言

在Mule 3中，用户不得不同时学习Mule表达语言（MEL）和DataWeave。 MEL强迫用户将其有效载荷从二进制数据（如XML或JSON文档）转换为Java对象，以便他们可以编写访问该数据的表达式，例如在路由到特定位置时。

在*Mule 4*中，DataWeave现在是默认的表达式语言。结合内置的流媒体功能，可以简化许多常见任务：

* 事件可以根据有效负载数据进行路由，而无需首先将它们转换为Java对象。
* 可以轻松地从流中的任何位置查询二进制数据，例如在日志记录时查询。
* 大于内存访问数据透明地发生。

DataWeave 2.0还具有许多改进功能：

* 语言简化。现在一切都是功能。
DataWeave脚本现在可以通过新的导入和模块功能进行打包和重用。
* 支持多行注释。
* 支持直接从DataWeave调用静态Java函数。

有关详情，请参阅指向<<see_also, DataWeave documentation>>的链接。

== 流式管理

// COMBAK  - 链接到文档中的流媒体部分
//当前草稿：https://github.com/mulesoft/mulesoft-docs/blob/streaming-patchstreaming-about.adoc（需要审核）。
Mule 4自动处理用户的数据流。这极大地简化了运行时对数据的处理，因为：

* 可以多次读取数据，也可以使用DataWeave表达式语言随机访问数据，且无副作用。
* 可以将数据发送到多个位置，而无需用户先将数据缓存到内存中。
* 用户可以透明地访问大于内存数据。
* 用户可以使用流策略自定义数据是否存储在磁盘上。

== 非阻塞自调整运行时

Mule 4包含一个基于非阻塞运行时的新执行引擎。这是一个面向任务的执行模型，它允许您利用非阻塞IO调用，并避免由于错误的处理策略配置而导致的性能问题。

作为这种新引擎的结果，您不再需要配置交换模式。相反，流程始终同步运行。如果您希望实现异步类型模式（如fire和forget），则可以使用`<async>`处理器。

现在，每个Mule事件处理器都可以通知运行时是CPU密集型，CPU灯还是IO密集型操作。这有助于运行时动态自动调整不同的工作负载，无需手动管理线程池。结果，Mule 4删除了复杂的调谐要求以实现最佳性能。

== 直接从连接器/模块丰富事件

对于任何给定的模块操作，现在可以定义一个目标（或目标变量），它将结果保存在一个变量中：

[source,XML,linenums]
----
<httpn:request target="myVar" config-ref="requestConfig" method="GET" url="http://mulesoft.com"/>
----

这将Mule消息保存在稍后要访问的`myVar`变量中。这通过消除对浓缩器的需求来降低流动复杂性。

您还可以使用targetValue属性控制变量中存储的内容。例如，如果您只想存储来自HTTP请求的响应代码，则可以执行以下操作：

[source,XML,linenums]
----
<httpn:request target="myVar" targetValue="#[attributes.statusCode]" .../>
----

== 简化的连接器和模块体验

Mule 4在模块和连接器方面引入了更多的一致性，为如何与Mule组件交互创造了一个统一的体验。

运输已被Mule模块完全取代。模块和连接器可以使用Mule SDK创建和管理，Mule SDK提供了一种扩展Mule的方法。

// COMBAK：智能连接器不能用于BETA
//介绍智能连接器：使用XML来设计连接的模块。 +
//用户可以定义模块，设置配置并定义稍后可以在mule应用程序中调用以操纵连接的操作。

//审查：需要确认私人流量消失。

== 简化的错误处理和新的尝试范围

Mule 4包含一个简化的错误管理方式。现在不用直接处理Java异常，而是直接在Mule中构建一个Error概念。此外，Mule模块和连接器声明任何给定操作可能发生的错误。这可以让您在设计时发现可能的错误并轻松捕捉它们。

异常策略由错误处理程序取代，允许您根据类型和任意表达式捕获错误。

您可以配置错误处理程序来捕获错误，以便流可以继续处理，或者可以重新传播它们。

还有一个新的Try Scope，它可以让您在流程中捕获错误，而无需创建新流程，特别是捕捉错误。

== 批量更易于使用，现在成为范围

在Mule 3中，批量作业是最高层次的关注点，类似的流程。但是我们已经简化了它，所以它现在成为一个可以存在于流程中的范围 - 使其更容易理解，动态调用并与其他Mule组件交互。批处理也不再有一组特殊的变量（即recordVars）。您现在可以直接使用流量变量;这样可以降低复杂性并使学习如何编写批量作业变得更加容易。

==  Mule API

Mule 4包含新的，明确定义的API。这些让你更容易地扩展Mule，并提供适当扩展点的清晰度。

运行时暴露了三个主要的API，允许您在顶层构建并扩展运行时功能：

* 核心API：Mule消息。
* 扩展API：允许您创建模块，消息处理器，变换器等来扩展运行时的API。
* 工具API：所有DataSense元数据和传播现在都是运行时的一部分，并且可以作为与Mule代理捆绑在一起的工具API的一部分进行访问。

== 利用Classloader隔离改进了可升级性

Mule 4将每个模块加载到它自己的类加载器中，将模块与内部Mule代码隔离开来，通过保护您免受运行时或连接器的更改，使运行时升级变得更加简单：

* 连接器现在分布在运行时间外部，从而可以：
** 获取连接器增强功能并进行修复，而无需升级您的运行时。
** 升级您的运行时版本而不破坏与其他模块的兼容性。
* 现在有一个定义良好的Mule API，因此您可以确定您使用的是受支持的API。
* 应用程序，运行时和连接器之间存在类加载器隔离，以便在内部发生的任何库更改都不会影响您的应用程序。

== 改进了对配置的支持
Mule 4提供了一种更简单的方法来配置特定于环境的属性，这是Spring可选的。有了它，现在可以在应用程序中的YAML文件中定义特定于应用程序的属性。这些将是您的应用程序的默认属性，您可以使用系统属性覆盖它们。将来，我们还将使用此元数据从运行时管理器提供改进的配置管理UI。

== 连接器和模块更新

数据库连接器=== 
数据库连接器已经过小的更新：

* 批量操作已分开，以便操作不会根据收到的有效负载更改行为
* 执行静态和动态查询有单一的经验。
*  DataWeave转换可以嵌入到插入/更新操作中，以便您可以构建要发送到数据库的数据集，而不会对消息产生副作用或使用组件
* 连接器将使用Mule的新流式框架来处理大型数据集。

=== 文件和FTP连接器
文件和FTP连接器已得到改进，因此它们基于操作并共享相同的一组操作。这启用了许多新功能：

* 与旧传输（仅提供轮询入站端点）不同，可以按需读取文件或完全列出目录的内容，
* 对常用文件系统操作（如复制，移动，重命名，删除，创建目录等）提供顶级支持
* 支持锁定文件系统级别的文件
* 高级文件匹配功能
* 支持本地文件，FTP，SFTP和FTPS

===  JMS连接器
JMS连接器已更新，以利用新的简化连接器体验。除了JMS侦听器和发送者之外，您还可以使用JMS消费操作来消费流中的消息。

=== 脚本模块
脚本模块现在更新为Mule 4，使您现在可以将Groovy，Ruby，Python或JavaScript脚本嵌入到Mule流中。您可以使用新的参数配置属性将来自Mule消息的数据注入到您的代码中。

[source,XML,linenums]
----
<script:execute engine="groovy">
    <script:code>
         return "$payload $prop1 $prop2"
    </script:code>
    <script:parameters>
         #[{prop1: "Received", prop2: "A-OK"}]
    </script:parameters>
</script:execute>
----

===  Spring模块
Mule 4将来自Spring的Mule内部解耦，确保用户不需要知道Spring来学习Mule，并且使Spring用户能够选择他们运行的弹簧版本。要使用Spring bean，现在将Spring模块添加到应用程序中，并简单地导入Spring bean文件。

[source,XML,linenums]
----
<spring:config name="springConfig" files="beans.xml"/>
----

===  VM连接器
VM连接器已更新为使用新的简化连接器体验。除了VM侦听器和发送者之外，您还可以使用虚拟机消耗操作在流的中间使用消息

=== 其他模块和连接器
已更新的所有其他模块和连接器已更新为与整体Mule 4体验相一致，但除非在发行说明中明确指出，否则不会发生功能更改。

==  Mule SDK
Mule SDK是Anypoint Connector Devkit的继任者。它使开发人员能够轻松地扩展Mule并创建可在Exchange中共享的新Mule模块。与Mule 3不同，Mule 3有多种创建扩展的方式，Mule 4 SDK提供了一种扩展Mule的方法，确保了组件的一致性和可升级性。它被用来构建所有Mule 4模块和连接器。

虽然在许多方面与DevKit相似，但它具有许多改进之处：

*  SDK不生成代码，使扩展程序无需重新发布即可获得新的运行时功能
* 交易支持
* 请求 - 响应消息源支持
* 动态配置
* 路由器支持
* 非阻止操作
* 类加载隔离

// ==兼容性模块
//
//为了帮助你迁移到Mule 4，有一个新的兼容模块，它为Mule 3的许多功能提供向后兼容性，包括：
//
// *传输：HTTP，JMS，数据库。
// * Mule表达式语言。
// * set-payload，set-variable，set-property，remove-property，copy-properties。
// *民意调查。
//
// COMBAK链接到迁移指南

[[see_also]]
== 另请参阅

*  link:about-mule-event[关于骡子事件]
*  link:dataweave[关于DataWeave]
*  link:migration-dataweave[从DataWeave版本1迁移到2]
*  link:about-components[关于组件]
*  link:try-scope-concept[关于尝试范围]
