= 重新连接策略参考

本节介绍通过编辑Mule应用程序的XML配置文件来配置的重新连接策略。

== 重新连接

重新连接策略允许用户配置尝试重新连接的次数以及尝试之间的等待时间。

=== 重新连接的属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| `blocking`  |布尔值 |否 | true  |如果为false，则重新连接策略在单独的非阻塞线程中运行
| `frequency`  | long  |否 | 2000  |重新连接的频率（以毫秒为单位）
| `count`  |整数 |否 | 2  |多少次重新连接尝试
|===

重新连接的=== 子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
| `abstract-reconnect-notifier`  | 0..1  |重新连接通知程序元素的占位符。 RetryNotifier接口是一个回调，允许在每次重新连接尝试后执行操作，例如，成功或失败时触发服务器通知事件。
|===

例如：

[source, xml, linenums]
----
<jms:activemq-connector name="AMQConnector">
    <reconnect count="5" frequency="1000"/>
</jms:activemq-connector>
----

== 重新连接Forever

重新连接策略，以指定频率重试无限次。

=== 重新连接的属性永远不变

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明
| `blocking`  |布尔值 |否 | true  |如果为false，则重新连接策略将在单独的非阻塞线程中运行。
| `frequency`  |长 |否 | 2000  |重新连接的频率（以毫秒为单位）。
|===

== 重新连接自定义策略

用户定义的重新连接策略。

<reconnect-custom-strategy...>的{​​{0}}属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |缺省 |说明 |
| `blocking`  |布尔值 |否 | true  |如果为false，则重新连接策略将在单独的非阻塞线程中运行。
| `class`  |类名 |是 |
|===

一个实现了`RetryPolicyTemplate`接口的类。

重新连接 - 自定义策略的=== 子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数 |说明
| `abstract-reconnect-notifier`  | 0..1  |重新连接通知程序元素的占位符。 RetryNotifier接口是一个回调，允许在每次重新连接尝试后执行操作，例如，成功或失败时触发服务器通知事件。
| `spring:property`  | 0 .. *  |
|===

例如：

[source, xml, linenums]
----
<jms:activemq-connector name="AMQConnector">
    <reconnect-custom-strategy class="org.mule.retry.test.TestRetryPolicyTemplate">
        <spring:property name="fooBar" value="true"/>
        <spring:property name="revolutions" value="500"/>
    </reconnect-custom-strategy>
</jms:activemq-connector>
----

== 重新连接通知程序

为每次重新连接尝试调用重新连接通知程序，并且还可以进行配置。您可以创建实现`org.mule.api.retry.RetryNotifier`界面的自定义重新连接通知程序。

每次重新连接尝试时，重连器通知器元素都会触发一次`ConnectionNotification`。
notifier元素没有属性或子元素。

例如：

[source, xml, linenums]
----
<jms:activemq-connector name="AMQConnector">
    <reconnect>
        <reconnect-notifier/>
    </reconnect>
</jms:activemq-connector>
----

== 重新连接自定义通知程序

用户定义的重新连接通知程序。

=== 重新连接自定义通知程序的属性

[%header%autowidth.spread]
|===
| {名称{1}}输入 |必 |说明
| `class`  |类名 |是 |实现RetryNotifier接口的类。没有默认值。
|===

重新连接自定义通知程序的=== 子元素

[%header%autowidth.spread]
|===
| {名称{1}}基数
| `spring:property`  | 0 .. *
|===

例如：

[source, xml, linenums]
----
<jms:activemq-connector name="AMQConnector">
    <reconnect>
        <reconnect-custom-notifier class="org.mule.retry.test.TestRetryNotifier">
            <spring:property name="color" value="red"/>
        </reconnect-custom-notifier>
    </reconnect>
</jms:activemq-connector>
----
