= 调度程序端点（触发器）

计划程序组件允许您在满足基于时间的条件时触发流程。您可以将其配置为定期触发或为其提供更灵活的cron表达式。例如，调度程序可能会触发一个事件，每5秒启动一次流程。

调度程序遵循Mule运行时运行的机器使用的时区。在部署到CloudHub工作人员的情况下，其时区对应于工作人员的区域。

//增强请求：MULE-14930
请注意，在Mule运行时群集或多工作者CloudHub部署中，调度程序仅在主节点上运行（或触发）（即仅在一个Mule运行时中）。


== 固定频率

您可以设置一个调度程序，以便定期触发您的流程。这是设置它的最简单方法。为此，您可以选择时间单位，触发之间的时间量和第一次触发发生之前的初始延迟时间。


==  Cron表达式

Cron是描述时间和日期信息的广泛使用的标准。它可以用来表示仅发生一次的特定事件，或者可能是年度，月度，每周，每日，每小时等的经常性事件。

每当时间改变（每秒）时评估条件，并在真实时产生触发。

该表达式由6或7个项目组成，它们按顺序代表以下内容：

* 秒
* 分钟
* 小时
* 月
* 一个月中的某天
* 星期几
* 年份（可选）

以下是几个示例Cron表达式：

[%header,cols="2*"]
|====
| {式{1}}行为
| 0 15 10 * * *  |每天上午10:15运行
| 0 15 10 * *？ 2005年 | 2005年每天上午10:15运行
| 0 * 14 * *？ |每分钟从下午2点开始，每天下午2点59分结束
| 0 0/5 14 * *？ |每天5分钟从下午2点开始，每天结束于下午2点55分
| 1 1 1 1,7 *？ |每年运行一月的第一天和六月的第一天（在第一小时的第一分钟的第一秒钟）+
|====

请注意，有许多免费的在线工具可以帮助您通过填写表单来构建cron表达式，而无需学习语法。

使用调度程序调试流程时，调度频率将被忽略。这可以防止事件在您逐步通过流程时堆积起来。 +
您可以单击画布中调度程序组件底部的绿色箭头图标来触发轮询。

== 另请参阅

*  link:scheduler-xml-reference[调度程序XML参考]

//不存在孤独者，没有明显的替代：
// * link:/connectors/database-schedule-scan-task[示例：安排数据库扫描]
