= 交易管理
:keywords: transaction, management, demarcation, jms, jdbc, vm, database, resource

事务是Mule应用程序中的操作，其结果不能保持不确定。当流中的一系列步骤必须作为一个单元成功或失败时，Mule会使用事务来划分单元。例如，您可以使用事务来封装流中的几个步骤，以便将信息提交到数据库。在这种情况下，提交（或事务）要么完全成功，要么不完整，要么失败。即使部分完成，提交失败。当交易失败时，穆勒回滚交易中的操作，这样没有一个部分会导致部分完成。

Try范围提供了一种从常规选项卡配置事务的方法。这个配置的XML如下所示：

.XML示例：Try范围中的事务配置

在此示例中，Try范围划分了一个包含数据库操作和VM操作的事务。如果在Try范围内发生错误，则两者都将被应用，否则都不会应用。

[source,xml,linenums]
----
include::_sources/transaction-management_1.xml[]
----

也可以从消息源开始事务。在这种情况下，整个流程就是一个交易。当处理邮件连接器时，如果在处理邮件时出现问题，以便稍后重试（由于回滚），可以防止邮件消耗，这非常有用。

.XML示例：消息源中的事务配置

[source,xml,linenums]
----
include::_sources/transaction-management_2.xml[]
----

在Studio中，这些连接器中的操作提供了用于设置交易的高级选项卡：

*  JMS
 **  Listener支持Local和XA事务类型。设置时，整个流程将被视为交易。
 ** 消费，发布和确认操作支持交易。
*  VM
 **  Listener支持Local和XA事务类型。设置时，整个流程将被视为交易。
 ** 消费，发布和发布消费操作支持事务。
* 数据库
 ** 所有数据库操作都支持事务。

连接器的特定事务配置可以在连接器文档中找到。

对于JMS Ack：

* 手动：这是JMS `{@link Session#CLIENT_ACKNOWLEDGE}`模式。您必须在流程中手动配置Ack。
*  DUPS_OK：JMS消息会自动Acked，但会以一种懒惰的方式导致重复。
*  IMMEDIATE：Mule自动在接收时确认消息。

请注意，Mule流可以从需要流内事务的非事务性连接器（如HTTP）开始。例如，Mule流可能接受来自外部Web服务的信息，然后在收取信用卡并将发票信息保存到数据库之前转换数据。在这种情况下，您可以使用Try范围通过在交易中包装信用卡费用和数据库提交操作来设置交易，以确保完成成功或完全失败并回滚。

== 交易行为

事务性操作（`transactionalAction`）

*  ALWAYS_BEGIN  - 收到消息时始终开始新的交易。如果事务已经存在，则会引发异常。支持交易的听众有这种选择。

*  ALWAYS_JOIN  - 总是希望在收到消息时进行交易。如果没有事务，则抛出异常。支持交易的操作有这个选项。

*  BEGIN_OR_JOIN  - 如果收到消息时交易已在进行中，请尽可能加入交易。否则，开始一个新的交易。支持交易的范围提供了此设置。

*  JOIN_IF_POSSIBLE：加入当前交易（如果有）。否则，不会创建事务。支持交易的操作提供了此设置。

* 不相容：不要将操作视为交易。支持交易的范围提供了此设置。

* 无 - 从不参与交易。支持交易的听众提供此设置。

*  NOT_SUPPORTED：在任何存在的事务之外执行。支持交易的操作提供了此设置。支持交易的范围提供了此设置。

== 交易类型

Mule支持单一资源（本地，默认）和扩展架构（`XA`）事务类型（`transactionType`）。下表描述了每种类型的特征。

* 单一资源交易（本地）
 ** 只接收或发送消息到一个资源。
 ** 比XA执行得更好。

*  XA交易
 ** 接收或发送消息给多个资源。
 ** 涉及使用两阶段提交算法。
 ** 连接器必须启用XA。
 ** 比本地更慢但更可靠。

////
去做：
== 另请参阅

link:transactions-single-resource.adoc[单一资源（本地）事务]

link:transactions-xa.adoc[XA交易]
////
