= 尝试范围XML参考

Try范围遵循下面描述的结构。


* 单个根元素`<try>`

* 根据由。定义的错误处理规则执行的组件
Try范围被定义为`try`元素的子元素。你可以在这里放置一个或多个。

* 单个`<error-handler>`元素包含范围的所有错误处理策略。

* 在错误处理程序中，一个或多个`on-error-continue`和`on-error-propagate`定义各种策略。其中至少有一个必须存在。

* 发生匹配错误时执行的组件被定义为`on-error`元素的子元素。你可以在这里放置一个或多个。

[source,xml,linenums]
----
<try>
  <!-- COMPONENTS TO TRY TO USE -->
  <error-handler>
    <on-error-continue>
      <!-- COMPONENTS TO USE IN CASE OF ERROR -->
    </on-error-continue>
    <on-error-propagate>
      <!-- COMPONENTS TO USE IN CASE OF ERROR -->
    </on-error-propagate>
  </error-handler>
</try>
----

Try范围（`on-error-*`）中的每个错误处理策略都遵循一个条件。这种情况通常是一种错误类型（或几个列表），它们必须与当前错误相匹配。您还可以将此条件定义为自由书写的表达式，例如`error.cause.message.contains("fatal")`。

[NOTE]
请注意，条件按顺序进行评估，只执行第一个匹配策略。







以下是一个包​​含两个错误处理策略的示例，每个策略执行一个记录器组件：


[source,xml,linenums]
----
<try>
  <http:request config-ref="HTTP-config" method="GET" path="/" />
  <error-handler>
    <on-error-continue enableNotifications="true" logException="true" type="CONNECTIVITY">
      <logger level="INFO" doc:name="Logger" message="Connectivity Error"/>
    </on-error-continue>
    <on-error-propagate enableNotifications="true" logException="true" doc:name="On Error Propagate" type="EXPRESSION">
      <logger level="INFO" doc:name="Logger" message="Expression error" />
    </on-error-propagate>
  </error-handler>
</try>
----

==  Try的属性

[%header,cols="20a,20,60a"]
|===
|属性 | 缺省 |说明
| `transactionalAction`  | 不相关 | 定义作用域中的内容是否被视为事务。可能的值：

* 不同：范围内的内容不被视为交易。

*  ALWAYS_BEGIN：每次执行作用域时，新的事务处于开始状态。

*  BEGIN_OR_JOIN：如果流的当前处理已经开始了一个事务，则加入它。否则，开始一个新的。 （仅在执行顺序可能不同时有关）。

| `transactionalType`  |  LOCAL  | 定义要使用的事务类型。可能的值：

*  "LOCAL"
*  "MULTI"
*  "XA"

|===





== 另请参阅

*  link:try-scope-concept[尝试范围概念]

*  link:error-handling[关于错误处理]

*  link:scopes-concept[关于范围]
