= 关于设置变量
:keywords: anypoint studio, studio, mule, variable transformer, variables, set variable, edit variable, remove variable

Set Variable（`set-variable`）组件用于创建或更新一个变量，以存储在Mule应用程序流中使用的值。您可以存储简单的文字值，如字符串或消息，消息负载或属性对象。例如，您可以存储消息的原始有效内容（在处理消息之前），以便稍后在流程中或错误处理程序中使用它。

`set-variable`组件不建议用于复杂的表达式或转换。您应该将其用于简单的选择，例如选择，并使用 link:transform-component-about[变换组件]
适用于复杂场景。


[%header,cols="20a,20a,60a"]
|===
| {字段{1}}使用 | 说明

| 变量名称（`variableName`）
| 必
| 变量的名称。名称只能包含数字，字符和下划线。例如，名称中不允许使用连字符。

| 值（`value`）
| 必
| 变量的值，可以是字符串或DataWeave表达式。

|  MIME类型（`mimeType`）
| 可选
| 设置变量MIME类型，例如`text/plain`或`application/json`。

| 编码（`encoding`）
| 可选
| 设置变量编码，例如`ISO 10646/Unicode(UTF-8)`。

|===

[WARNING]
--
`mimeType`和`encoding`属性不会影响用作`value`的DataWeave表达式。它们只影响存储的输出值。如果需要转换，DataWeave表达式必须包含一个显式的输出指令。
--

== 示例

本示例将该变量设置为一个字符串：

* 名称= `myVar`
* 值= `my first variable`

本示例通过使用导致值为`5`的DataWeave操作来设置变量：

* 名称= `myVar`
Anypoint Studio中的* 值= `#[max([1,2,3] ++ [3,4,5])]`。

本示例将该变量设置为消息负载：

* 名称= `myVar`
设计中心内的* 值= `payload`，Anypoint Studio中的`#[payload]`。

此示例将该变量设置为消息属性：

* 名称= `myVar`
设计中心内的* 值= `attributes`，Anypoint Studio中的`#[attributes]`。

本示例将该变量设置为整个消息：

* 名称= `myVar`
设计中心内的* 值= `message`，Anypoint Studio中的`#[message]`。

这个XML示例设置了一个将地图作为值的变量：
`<set-variable variableName="employee" value="{ 'name' : 'Ana', 'office' : 'BA' }" mimeType="application/json" encoding="UTF-8/>`

本示例使用DataWeave脚本中的选择器设置相同的变量。它假定`name`属性可用作设置变量的输入：
`<set-variable variableName="employee" value="#[output application/java --- payload.name]"/>`


== 在其他事件处理器中访问变量
Set Variable在当前Mule事件中设置一个变量，然后这些变量随Mule事件一起传送到下游事件处理器。您可以使用`vars`使用DataWeave访问任何变量。因此，如果您设置名为lastMessage的变量，则可以将其作为`vars.lastMessage`进行访问。您可以在变换消息组件中设置变量，而且许多连接器和事件处理器都有一个可以在“高级”选项卡中设置的目标。这些所有设置流变量，并通过关键字`vars.`以相同的方式访问它们。


== 另请参阅

*  link:about-mule-variables[关于Mule事件中的变量]
*  link:target-variables[利用目标变量丰富数据]
