=  Exchange 2常见问题

本主题列出了常见问题并提供了答案。

== 期望的审核和审批工作流程是什么？

Exchange提供了一个草稿功能。组织可以为撰稿者和发布者创建两个角色，并共享
与发布者角色中的页面等待发布的网页的网址。您可以在Anypoint Platform>中创建角色
访问管理>角色。草稿中的内容在草稿发布前一直隐藏。

== 最新版本的Developer Portal在哪里？

MuleSoft Developer Portal位于https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/。

== 如何创建API门户？

如果您是Anypoint Platform组织管理员或Exchange管理员，那么当您首次登录到Exchange时，
Exchange为您创建一个公共门户。到门户的链接出现在
左侧导航栏。将API资产添加到门户后，它变得可见
到互联网。有关如何将资产添加到门户网站的信息，请参见xref：whynoinpp [为什么我的资产不会显示在我的公共门户中？]。

您的门户网址的格式为`+https://anypoint.mulesoft.com/exchange/portals/YOUR_LOGIN_NAME/+`。

[[whynoinpp]]
== 为什么我的资产不出现在我的公共门户中？

您可以通过单击共享按钮并单击添加到公共门户添加SOAP API，HTTP API和OAS或RAML REST API资产到公共门户。当您将资产共享到公共门户网站时，该资产将随后公开，并由互联网上的任何人通过您的公共门户网站的URL公开显示。

== 如何从公共门户中删除资产？

点击Exchange中的资源，然后点击共享。点击添加到公共门户。点击
API版本字段复选框取消选中该字段。点击共享。在Exchange中，刷新
浏览器屏幕，您可以看到资产概览中的可见性设置
改为私人。

== 当我重命名资产时，为什么Exchange使用旧名称？

更改资产的名称后，请按键盘上的Return（或Enter）键。如果你不这样做
按回车键，Exchange将资产名称恢复到您更改之前的状态。

== 我可以将JSON片段添加到Exchange并引用其他JSON模式的片段吗？

您可以使用RAML数据类型，但不能使用另一个JSON模式引用的JSON。

== 为什么使用Studio 6的Windows 7中的Exchange资产缺少CSS？

Exchange仅适用于带有Chrome，Firefox和Internet Explorer 11最新版本的Windows。IE 9不受支持，并且显示错误。

== 当我通过Maven将自定义连接器推送到Exchange时，如何定义自定义图标？

您可以使用PUT将Exchange图标分类器上传SVG图标到Exchange REST API。 Exchange在图标周围添加圆形边框。您需要将授权标头与承载和访问令牌一起传递。

例如，将图标文件添加到HTTP正文并使用PUT，例如：

[source]
----
https://maven.anypoint.mulesoft.com/api/v1/organizations/:organizationId/maven/:groupId/:assetId/:version/:assetId-:version-icon.svg
----

== 我可以将资源发布作为CI和CD管道的一部分整合到Exchange吗？

您可以使用https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-experience-api/[Exchange Experience API]以检测差异是否存在，以便在没有更改时不重新发布到Exchange。

== 是否有API从Exchange下载RAML文件？

您可以使用https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-graph-http/[Graph API（首选） ]或https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-experience-api/ [交流体验API]。

== 如何更改API的所有者？

您可以使用这个REST API命令：

[source,xml,linenums]
----
curl -X POST \
https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/<org-id>/apis/<api-id>/permissions \
-H 'authorization: Bearer <OMMITED>' \
-H 'content-type: application/json' \
-d '{"userId":"<user-id>"}'
----

== 另请参阅

*  https://forums.mulesoft.com [MuleSoft论坛]。
*  https://support.mulesoft.com [联系MuleSoft支持]。

