= 自定义Exchange公共门户

如果您具有Exchange管理员或组织所有者访问权限，则可以自定义Exchange公共门户的外观。

访问公共门户并点击导航栏右侧的自定义。

== 横幅文本

单击“自定义”后，单击横幅文本并删除要更改的文本，
并添加新的文本。

== 顶部栏自定义

以下可让您更改顶部导航栏的设置。

=== 徽标图片

选择一个徽标图像文件。最大徽标高度为60像素，宽度成比例。

图像文件格式可以是.svg，.png，.jpg或.gif。

浏览器选项卡的===  Favicon

选择一个收藏夹图片以显示在公共门户的浏览器标签中。图像的最大尺寸取决于
浏览器要求。 favicon.ico文件最多可以包含5个大小，例如16x16,32x32,64x64,128x128和512x512。

=== 背景颜色

为顶部任务栏的颜色选择一个RGB十六进制值。

=== 文字颜色

指定顶部栏文本的十六进制红绿蓝色。黑色的颜色范围为#FFFFFF，黑色的范围为＃000000。至少必须指定3个十六进制字符，例如，指定＃F42生成值＃FF4422。该字段不区分大小写。

=== 活动文字颜色

当使用鼠标悬停选择文本时，为顶栏文本指定十六进制的红绿蓝色。黑色的颜色范围为#FFFFFF，黑色的范围为＃000000。至少必须指定3个十六进制字符，例如，指定＃F42生成值＃FF4422。该字段不区分大小写。

== 英雄形象横幅

选择公共门户横幅的图像。英雄图像文件格式可以是.png，.jpg或.gif。
横幅图像的最大文件大小为2 MB。横幅图像也可以是动画GIF文件。

您指定的图像被拉伸以适应浏览器窗口大小确定的窗口大小。高度固定为220px。

=== 横幅文本颜色

指定横幅文本的十六进制红绿蓝色。黑色的颜色范围为#FFFFFF，黑色的范围为＃000000。至少必须指定3个十六进制字符，例如，指定＃F42生成值＃FF4422。该字段不区分大小写。

== 自定义页面

自定义页面显示为公共门户顶部的选项卡。使用Exchange Visual或Markdown编辑器将文本，图像或视频添加到页面。

要删除自定义页面，请单击删除页面。如果此按钮不可见，请调整公共门户浏览器窗口的大小以显示“删除页面”按钮。

== 另请参阅

*  link:/anypoint-exchange/to-describe-an-asset[描述资产]
*  https://stackoverflow.com/questions/4014823/does-a-favicon-have-to-be-32x32-or-16x16 [Stack Overflow Favicon discussion]
