= 使用Maven发布和部署Exchange资产
:keywords: maven, publish, deploy, facade
：imagesdir：./_images

Anypoint Exchange提供了https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[Maven Facade]，使Maven客户可以使用Maven发布和使用资产。

== 先决条件

本文假定您熟悉Maven，编程概念和命令行
您的计算机或服务器上的操作。

注意：您必须拥有唯一的工件名称和组织标识才能发布您的资产。

== 查看您的组织ID

. 登录到Anypoint Platform并单击访问管理。
. 单击顶级或业务组的组织名称，然后在组织信息屏幕中查看您的组织ID。
. 复制组织标识并将其添加到下面的示例中，以了解如何设置项目的POM文件。

== 使用Maven将资产发布到Exchange

您可以使用本主题中的信息发布Mule 3和Mule 4资产，包括连接器。

. 将Maven项目的groupId修改为您项目的POM文件中的组织ID：
+
[source,xml,linenums]
----
 ...
 <groupId>ORGANIZATION_ID</groupId>
 ...
----
+
如果您将资产发布到主组织，则组ID与组织ID相同。
网址格式为：
+
`+https://maven.anypoint.mulesoft.com/api/v1/organizations/ORGANIZATION_ID/maven+`
+
如果您将资产发布到业务组，则组ID与业务组ID相同。
网址格式为：
+
`+https://maven.anypoint.mulesoft.com/api/v1/organizations/BUSINESS_GROUP_ID/maven+`
+ 
. 将资产类型添加到您项目的POM文件中的属性部分。例如：
+
[source,xml,linenums]
----
 ...
 <properties>
  ...
  <mule.version>3.9.0</mule.version>
  <mule.tools.version>1.2</mule.tools.version>
  <type>template</type>
 </properties>
 ...
----
+
*Notes:*
+
{0}}对于Mule 3资产，如果您未包含`<type>`元素，则您的上传可能会成功，但不会在Exchange中显示。
** 对于Mule 3资产，请将<type>设置为以下值之一：`extension`，`template`，`example`，`rest-api`，{{6 }}，`http-api`，`raml-fragment`，`custom`。
** 对于Mule 3或Mule 4连接器，请不要指定`<type>`值。
** 对于Mule 4资产，请不要指定<type>元素。
+
. 将Maven Facade作为存储库添加到项目POM文件的分发管理部分中：
+
[source,xml,linenums]
----
 ...
  <distributionManagement>
    <repository>
      <id>Repository</id>
      <name>Corporate Repository</name>
      <url>https://maven.anypoint.mulesoft.com/api/v1/organizations/ORGANIZATION_ID/maven</url>
      <layout>default</layout>
    </repository>
  </distributionManagement>
  ...
----
+
*Note:* <id>和<name>元素是您创建的用于标识存储库和任何其他组织标识符的任意名称。在〜/ .m2 / settings.xml文件中，<id>值必须与pom.xml文件中的相同。 <id>连接pom.xml文件和登录到组织URL的信息。
+
. 更新Maven .m2目录中的settings.xml文件。在安装Maven之后，`mvn clean`命令将创建.m2目录。在Mac或Linux上，目录位于`~/.m2`，而在Windows下，目录位于`<default-drive>\Users\YOUR_USER_NAME\.m2`，其中包含您的Anypoint Platform凭据。当Maven运行时，Maven客户端读取设置文件。
+
示例settings.xml文件：
+
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>Repository</id>
      <username>myusername</username>
      <password>mypassword</password>
    </server>
  </servers>
</settings>
----
+
. 使用此Maven命令将资产发布到Exchange：
+
[source,xml]
----
mvn deploy
----
. 您可以使用以下URL语法来共享资产的位置：
+
[source,xml]
----
https://anypoint.mulesoft.com/exchange/api/v1/assets/ORGANIZATION_ID/ASSET_ID
----
+
将ORGANIZATION_ID替换为Exchange的组织标识，将ASSET_ID替换为资产ID。

== 发布联合资产

. 通过登录到Anypoint Platform并将此URL复制到浏览器地址栏来获取访问令牌：
+
[source]
----
https://anypoint.mulesoft.com/accounts/api/profile
----
+
. 在显示的值中搜索`access_token`。
. 将访问令牌添加到`+~/.m2/settings.xml+`（Mac或Linux）或`C:\Users\YOUR_USER_NAME\.m2\settings.xml`（Windows）文件：
+
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
          http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>Repository</id>
      <username>~~~Token~~~</username>
      <password>ACCESS_TOKEN</password>
    </server>
  </servers>
</settings>
----

== 使用Maven消费Exchange资产

将资产的组ID，artifactID和版本添加到项目的pom.xml文件的`dependencies`部分，
并在`repositories`部分添加Maven Facade作为存储库。

[source,xml,linenums]
----
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
 ...

  <dependencies>
    <dependency>
      <groupId>org.mule.modules</groupId>
      <artifactId>mule-module-metoo</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>

 ...

  <repositories>
    <repository>
      <id>Repository</id>
      <name>Corporate Repository</name>
      <url>https://maven.anypoint.mulesoft.com/api/v1/organizations/ORG_ID/maven</url>
      <layout>default</layout>
    </repository>
  </repositories>
 ...
</project>
----

将ORG_ID替换为您的组织标识。

您可以将`+https://maven.anypoint.mulesoft.com/api/v1/maven+`用作`+<url>+`值的有效网址，因为这是发布到主组织的默认网址。

== 另请参阅

*  https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/ [ Maven Facade API]
*  https://maven.apache.org/ [Apache Maven]
