= 使用图形API进行搜索
:keywords: query, exchange, exchange2, graph, api, graph api

Exchange图形API允许您在Exchange资产中搜索字符串值。你可以指定什么值
在每次搜索中接收。

由于Graph API访问Anypoint Exchange和Anypoint Platform，查询应该如此
如果您想在私人交易所访问资产，则拥有访问令牌。如果您只搜索MuleSoft公共资产，则不需要访问令牌。

== 获取访问令牌

如果您正在搜索不是由MuleSoft创建的资产，则只需要访问令牌。

访问令牌有时会在15到180分钟之间过期（询问您的组织管理员），因此您可能需要在执行搜索时获取新的令牌。

. 登录Anypoint平台。
. 使用curl命令获取访问令牌，如下所示。您还可以使用Postman或其他应用程序发送HTTP命令。
+
[source,json,linenums]
----
curl -X POST \
  https://anypoint.mulesoft.com/accounts/login \
  -H 'content-type: application/json' \
  -d '{
  "username": "YOUR_ANYPOINT_PLATFORM_USER_NAME",
  "password": "YOUR_ANYPOINT_PLATFORM_PASSWORD"
}'
----

== 图表API访问网址

您可以通过`+https://anypoint.mulesoft.com/graph/api/v1/graphql+`网址访问Graph API。寻找
使用API​​，发送包含搜索字符串的POST命令。

例如：

[source,xml,linenums]
----
curl -X POST \
  https://anypoint.mulesoft.com/graph/api/v1/graphql \
  -H 'content-type: application/json' \
  -d ' {
      assets(asset: {
        groupId: "some-group-id",
        assetId: "some-asset-id",
        version: "some-version-1.2.3"
      })
      {
      # Possible Search Options:
        groupId,
        assetId,
        version,
        description,
        name,
        type,
        tags { value, key, mutable },
        createdBy { id, userName, firstName, lastName },
        files { classifier, packaging, externalLink, md5 },
        rating,
        numberOfRates,
        createdAt,
        organizationId,
        assetLink,
        runtimeVersion,
        productAPIVersion,
        dependencies { groupId, assetId, version, name, type },
        related(relationshipType: OtherVersions) { groupId, assetId, version, name, type, 
        runtimeVersion, productAPIVersion }
      }
}'
----

== 仅搜索私人交易所

. 通过点击您的私人交易所中的资产，获取专用交易所的组织标识。
+
示例URL是：
+
[source,xml]
----
https://anypoint.mulesoft.com/exchange/42424242/product-api/1.0.0/
----
+
`42424242`是组织标识。
+
. 使用organizationIds字段添加组织标识。
+
一个单一的组织ID将是：
+
`organizationIds: ["42424242"]`
+
[source,json,linenums]
----
{
  assets(
    query: {
      searchTerm: "product",
      organizationsIds: ["4141141", "32322", "2342345"]
    },
    latestVersionsOnly: true
  ) {
    assetId,
    description
  }
}
----
+
这个例子的输出是：
+
[source,json,linenums]
----
{
  "data": {
    "assets": [
      {
        "assetId": "product-datatype",
        "description": "Product Datatype Asset"
      },
      {
        "assetId": "product-api",
        "description": "Product API Asset"
      }
    ]
  }
}
----

== 参考：查询过滤器参数

您可以指定过滤器来显示有关每个资产的其他信息。

以下过滤器可让您优化查询输出：

[%header%autowidth.spread]
|===
| {参数{1}}说明
| assetId  |每个资产的资产ID。
| createdAt  |创建资产的日期和时间，例如2017-08-11T04：48：20.585Z。
| createdBy {id，userName，firstName，lastName}  |显示创建资产的人员。
|依赖项{groupId，assetId，版本，名称，类型}  |返回列出的资产所依赖的资产。
|文件{分类器，打包，externalLink，md5}  |文件信息。
|名称 |资产名称
| numberOfRates  |资产的星级评分数。
| organizationId  |资产的组织标识。
|评分 |资产的星级评分值。
| runtimeVersion  | Mule运行时版本。
|标签{value，key，mutable}  |资产标签。在用户界面中创建的标签以及发布时只有`value`标签（它们没有密钥）。在用户界面中创建的标签是可变的，而其他标签是不可变的。带有键和值的标签是由Exchange创建的用于描述资产的特殊标签。
对应于“Exchange所有类型”菜单的|类型 |小写值：连接器，模板，示例，rest-api，soap-api，raml-fragment和自定义。
资产的|版本 |版本。
| groupId  |资产的组ID。
|===

== 另请参阅

*  https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/2559c34c-bbc7-4a5a-b078-bc1154594906/apis/8788430/versions/117434 [Exchange图形API]
*  https://www.anypoint.mulesoft.com/exchange/ [Anypoint Exchange]
*  link:/anypoint-exchange/[交换文档]
