= 在Anypoint平台私有云中配置LDAP

以下过程介绍了如何使用LDAP版本3为Anypoint Platform的私有云版配置用户管理。通过LDAP的用户管理仅适用于私有云版本。

. 从Anypoint Platform中，单击访问管理>外部身份。
+
出现配置LDAP的表单。
+
. 在LDAP配置表单中，为您的LDAP服务设置连接设置。
+
* 主机
+
您的LDAP服务器的主机名。如果您在您的ldap服务器中使用TLS，请使用`ldaps://mulesoft.com`使用此主机名：`ldap://mulesoft.com`
+
* 端口
+
用于与您的LDAP服务器通信的端口。默认的ldap端口是`389`。默认的ldaps端口是`636`。
+
* 自签名证书
+
如果您在LDAP服务器上使用自签名证书，请选中此复选框。使用自签名证书来测试与LDAP服务器的连接。
+
* 绑定DN
+
进行LDAP查询的用户的专有名称。例如，`uid=admin,ou=people,dc=mulesoft,dc=com`。
+
* 密码
+
LDAP服务器的密码。例如，`examplepassphrase`。
+
* 连接超时
+
连接的超时帧（以秒为单位）。例如，`10`。
+
* 操作超时
+
操作的超时帧（以毫秒为单位）。例如，`30000`。
+
. 设置搜索基础和过滤器
+
* 用户
+
用户搜索基础对象的基本级别。例如，`uid=admin,dc=mulesoft,dc=com`。
+
组
+
您的群组搜索基础对象的基本级别。例如，`ou=groups,dc=mulesoft,dc=com`。
+
. 为您的用户和组设置专有名称
+
* 用户
+
用户搜索基础对象的专有名称。例如，`uid={{username}},ou=people.dc=mulesoft,dc=com`。
* 组
+
您的群组搜索基础对象的专有名称。例如，`ou=groups,dc=mulesoft,dc=com`。
+
* 搜索过滤器
+
用户名** 
+
搜索过滤器通过用户名查找用户。例如，`(&(objectClass=inetOrgPerson)(uid={{username}}))`。
+
用户通过电子邮件发送** 
+
搜索过滤器通过电子邮件查找用户。例如，`(&(objectClass=inetOrgPerson)(mail={{email}}))`。
+
** 按组名称分组
+
搜索过滤器通过groupName查找组。例如，`(&(objectClass=groupOfNames)(cn={{groupName}}))`。
+
用户按用户组分组** 
+
搜索过滤器，通过userName查找用户组。例如，`(&objectClass=GroupOfNames)(member=uid={{username}},ou=people,dc=mulesoft,dc=com))`。
+
. 映射用户字段
* 用户名
+
表示用户名的字段。例如，`johndoe`。
+
* 电子邮件
+
代表电子邮件的字段。例如，`jdoe@gmail.com`。
+
* 名字
+
代表名字的字段。例如，约翰。
+
姓
+
代表姓氏的字段。例如，`doe`。
+
*  ID
+
您的用户的ID。例如，`2EH`。
+
. 映射组字段
* 组名称
+
代表您的团体名称的字段。例如，`cn`。
*  ID
+
代表您的群组ID的字段。例如，`bcd6b4c4-aec5-4493-be1b-8e2e8eecf662`。
+
. 保存配置。
