= 管理权限
:keywords: anypoint platform, permissions, configuring, accounts, roles

本节介绍权限如何在Anypoint Plaform管理的不同产品和API中使用。

== 假设

此页面假设您在组织中具有组织管理员角色，您已被指定为组织的某个业务组的管理员，或者您拥有API版本所有者权限并且您希望管理用户的权限API版本，业务组或整个组织。

== 权限在Anypoint平台中如何工作

在Anypoint平台中，用户属于一个组织，并拥有一组*roles*和*permissions*。

每个角色都包含一个_permissions_列表，用于定义拥有该角色的用户可以使用其范围内的特定资源执行的操作。 +
某些角色带有一组默认权限。作为组织管理员，您可以创建自定义角色并分配您认为合适的权限，也可以根据产品直接向特定用户添加权限，而无需角色。

=== 了解权限

根据您在Anypoint Platform中拥有的产品数量，首次创建时，您会在每个新组织和业务组中看到一组默认类型的_permissions_。但是，在权限类型之间有一个区别：

.  *Product Permissions*
* 每个Anypoint Platform产品（运行时管理器，数据网关等）的默认权限。它们是*environment specific*  - 它们授予您在特定环境中执行某项操作的能力，但不能授予整个组织。 +
产品权限可以分配给自定义角色或分配给CloudHub角色。
+
[NOTE]
通过*Exchange Administrators*，*Exchange Contributors*和*Exchange Viewers* link:/access-management/roles[角色]处理对Exchange的访问。无法将单个Exchange权限授予其他角色。请参阅 link:/anypoint-exchange/to-set-permissions[产品文档]以了解更多信息。

.  *API Permissions*
从Anypoint Platform管理的每个API的* 默认权限。它们可以是API特定版本，也可以扩展到所有API版本 - 您可以根据特定的API版本管理用户访问权限，但不能将这些权限扩展到整个组织。为了授予用户*all APIs*的权限，请将其添加到*API Versions Owner*和*Portals Owner* link:/access-management/roles[角色]。
* 您可以分配用户权限，以使用*API Version Owner*和*Portal Viewer*权限编辑或查看各个API版本或API门户。
+
[NOTE]
--
这两个API权限授予与*API Versions Owner*和*Portals Viewer*角色相同的范围，但仅限于您定义的API和版本。 +
了解 link:/access-management/roles#permission-scopes-for-default-roles[角色文章]中的这些特定范围。
--

由于_API versions_和_Products部署环境_分组在组织（也可以在业务组下），因此要访问它们，您需要拥有拥有必要权限并属于其相应组织或业务组的帐户（如果存在此类资源） 。

在主组织级别分配的角色只能引用处于主组织级别的资源，属于业务组的角色只能引用该业务组中的资源。

[NOTE]
--
拥有任何业务组角色的用户将被隐式授予该业务组中的成员资格。 +
一旦用户属于组织内的业务组，将权利分配给不同业务组中的同一用户的唯一方法是在该第二业务组内为其分配角色。
--
