= 使用SAML声明获取API承载令牌

本主题介绍如何从Anypoint Platform获取不记名令牌。如果您使用的是配置为使用SAML 2.0的身份提供程序，则组织内的联合用户可以使用不记名令牌访问平台API。

不记名令牌提供对用户有权访问的平台API的访问。每个不记名令牌都与被授予API角色和权限的特定用户相关联。如果用户尝试访问其无权访问API的API，则会返回`401 Unauthorized`错误。

不记名令牌的有效性由为默认会话超时属性定义的值确定。这是在主组织属性中配置的。有关更多信息，请参阅 link:/access-management/organization#organization-settings[组织设置]。

使用SAML断言来获取API持票人标记：

. 按照 link:/access-management/troubleshoot-saml-assertions-task[在浏览器中查看SAML响应]中所述为您的身份提供商获取SAML响应。
+
记录此响应以用于以下步骤。

. 通过运行以下`curl`命令来获取不记名令牌。将本例中的{{2}替换为您在上一步中获得的SAML响应。
+
----
curl -X POST \
  https://anypoint.mulesoft.com/accounts/login/receive-id \
  -H 'Content-Type: application/json' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -d '{
    "SAMLResponse": "<SAML_RESPONSE>"
}'
----

获得持票人令牌后，组织内的联合用户可以使用它来访问API。例如，您可以使用以下方法之一访问API：

*  *Anypoint CLI*：用户可以通过向`anypoint-cli`命令提供`-bearer`选项来访问平台API。有关更多信息，请参阅 link:/runtime-manager/anypoint-platform-cli#logging-in[Anypoint CLI]。
*  *curl*：用户可以在访问API端点时通过传递持票人标记来访问平台API，如下所示：
+
----
curl -X GET \
  https://anypoint.mulesoft.com/accounts/api/me \
  -H 'Authorization: Bearer <BEARER_TOKEN>'
----

== 另请参阅

*  link:/access-management/organization#organization-settings[组织设置]
*  link:/runtime-manager/anypoint-platform-cli#logging-in[Anypoint CLI]
*  link:/access-management/troubleshoot-saml-assertions-task[在浏览器中查看SAML响应]
