= 解决Anypoint平台访问问题
:keywords: anypoint platform, permissions, configuring

== 常见问题解答Anypoint平台访问问题

=== 我可以拥有多个具有相同电子邮件地址的帐户吗？

是的，您可以为同一组织或多个不同的组织使用同一电子邮件地址的多个帐户。您的用户名对于每个帐户必须是唯一的。

=== 我创建了一个帐户，但我需要加入现有组织。

要加入现有组织，请联系您需要加入的组织的组织管理员，并要求他们向该组织发送邀请。收到邀请后，您可以创建一个新帐户来接受邀请并将您的帐户与组织关联。您输入到自己创建的组织中的任何数据都与您的旧组织保持关联。

=== 我收到了邀请，但它说我应该使用现有帐户登录 - 我应该使用哪个帐户？

如果您有一个或多个现有的MuleSoft社区帐户绑定到您收到邀请的电子邮件地址，MuleSoft会提示您使用现有帐户登录并接受邀请。您也可以选择按照表格底部的注册链接创建一个新帐户。

=== 我收到了组织的邀请，但我想为我的帐户使用其他电子邮件地址。

帐户邀请与发送邀请的电子邮件地址绑定。如果您需要使用其他电子邮件地址，请接受邀请，然后访问您的个人资料以更改您的电子邮件地址。

=== 我收到了组织的邀请，但是当我按照电子邮件中的链接收到错误时。

您的邀请可能已过期或已被取消。请联系您的组织管理员以获取新的邀请。

=== 我有一个帐户，但该平台无法识别我的登录信息。

请检查您是否使用了正确的URL登录到您的组织。如果您的组织使用外部身份管理系统，则您的登录URL使用以下模式：*anypoint.mulesoft.com/accounts/login/yourorganizationname*

如果您的组织未使用外部身份管理系统并且您的登录凭证无效，请重置您的密码或咨询您的组织管理员以确保您的帐户仍处于活动状态。

=== 我接受了邀请并登录了，但在平台中看不到任何内容。

如果您已登录并且无法在组织的Developer Portal上看到任何内容，则意味着：

* 组织中没有人添加任何API，因此没有可显示的API门户
* 您尚未被授予Portal Viewer访问任何私人API门户的权限（并且没有公开API门户可显示）

=== 我是API版主，我想让其他人访问我的API版本。我该怎么办？

转到您的API版本详细信息页面，然后点击*Permissions*标签。您可以在此邀请其他用户访问您的API。请注意，您要邀请的用户必须已经是您的同一组织的成员。添加用户后，您可以使用“权限”列中的下拉菜单来管理您分配的权限性质（Portal Viewer访问权限或API版权所有者访问权限）。此选项卡还允许您查看当前已被授予API直接权限的所有用户。请注意，此选项卡不显示具有基于自定义角色的权限的任何用户，因为无法从API版本详细信息页面管理角色。有关您的API版本的基于角色的权限的信息，请联系您的组织管理员。

=== 我无法访问我的帐户的结算信息。

请直接与我们联系以获取结算信息。

=== 我收到了一条通知，说我的审讯即将到期。帮帮我！

请联系您的客户代表或mailto：info@mulesoft.com [联系我们]为您的本地Mule Runtime实例申请企业许可证，或者在CloudHub上创建订阅帐户。

=== 我的组织使用外部身份管理。我如何登录？

如果您的组织正在使用外部身份管理，请登录*anypoint.mulesoft.com/accounts/login/yourorganizationname*。

=== 如何访问其他组织的Developer Portal？ +

从您的帐户注销以浏览其他组织的开发人员门户。在您登录自己的组织时，只能访问您自己组织的Developer Portal。请注意，如果您希望请求访问其他组织的API，则需要获取该组织的Anypoint Platform帐户。

=== 我找到了一个我想使用的API，但我不是该API所属组织的成员。我如何请求访问此API？

要请求访问API，您必须使用该API所属的组织中的帐户登录。如果您没有该组织的帐户，请查看API门户中的文档以获取有关如何申请帐户的信息。

=== 如何删除我的帐户？

请提交https://support.mulesoft.com [支持票证]以进行帐户删除或迁移。
