= 使用IDE

本文档提供了在*Mule Studio*，*Eclipse*或*IntelliJ IDEA*中导入和处理Mule源代码的提示。您用来开发Mule的集成开发环境的类型没有限制，我们只是选择将上面列出的三个作为常见的IDE进行讨论。

==  Mule Studio

*Mule Studio*是一个开源的基于Eclipse的图形用户界面，您可以使用它来访问Mule ESB的功能。不仅仅是一个用于使用Mule构建项目的GUI界面，您可以使用Mule Studio作为IDE来处理Java中的Mule源代码。

=== 导入

. 按照 link:/mule-user-guide/v/3.4/downloading-and-launching-mule-esb[说明]下载，安装并启动Mule Studio。
. 关注 link:/mule-user-guide/v/3.4/converting-maven-into-studio[步骤]，在您的Maven `settings.xml`文件中添加*`studio:studio`*插件。
. 在您克隆Mule源代码的目录中，通过运行以下命令来解决所有库依赖性并生成IDE项目文件：`mvn studio:studio`
. 在Studio中，选择*File*> *Import*。
. 在*Import*向导中，单击以展开*General*文件夹，然后选择*Existing Projects into Workspace*，然后单击** Next**。
. 在*Select root directory*字段中，使用*Browse*按钮导航到您从Github帐户下载克隆的Mule源代码的目录。
. 确保所有*Projects*都已选中，然后点击*Finish*。 Studio导入mule源代码。
. 当您需要编辑或添加内容时，打开源代码文件。
. 点击*Save*图标保存到本地。

=== 调试

. 在Studio中，选择*Window*> *Open Perspective*> **Other...**，然后选择*Java*打开Java透视图。
.  {选择{1}}> *New*> *Java Project*。您正在创建一个新项目，仅用于启动Mule。
. 在*New Java Project*向导中，为您的项目选择*Name*，例如`Mule Launcher`，然后点击*Next*。
. 在向导的*Java Settings*面板中，选择*Projects*选项卡，然后点击*Add*。
. 点击*Select All*，然后点击*OK*，然后点击** Finish**。
. 在包资源管理器中，右键单击您的启动器项目名称，然后选择*Debug As*> *Debug Configurations...*
. 在*Debug Configurations*向导中，双击*Java Application*。
. 在*Main class*字段中，输入以下内容：`org.mule.MuleServer`
. 点击*Arguments*标签。在*Program Arguments*字段中，输入以下内容：`-config <path to a Mule config>`
. 点击*Apply*，然后点击*Debug*。
.  Studio请求切换到*Debug Perspective*的权限;点击*Yes*接受并打开。

现在，您可以在工作区的任何Mule项目中的任何Java文件中的任何位置设置断点。链接：*When you change java files and rebuild, the debugger hot swaps the rebuilt Java class file to the running Mule server.*请注意，您只需按照上述步骤设置您的调试配置一次;之后，只需右键单击项目名称，然后选择*Debug As*> *Java Application*以进行后续调试。

=== 远程调试

.  *From the command line, edit the `JPDA_OPTS` variable in the Mule startup script and specify the debugger port.*
.  *Start the Mule server with the `-debug` switch. The server waits until a debugger attaches.*
. 在studio的Package Explorer中，右键单击您的Mule源代码项目名称，然后选择*Debug*> *Debug Configurations...*
. 双击*Remote Java Application*。
. 在*Connection Properties*下输入*Host*和*Port*的值，然后点击*Apply*。
. 点击*Debug*。 Studio请求切换到*Debug Perspective*的权限;点击*Yes*接受并打开。

=== 测试

使用Maven使用以下命令在您的项目上运行单元测试：`mvn test`

除了每个子项目的单元测试之外，Mule父项目还有一个包含集成测试的独立子项目。这些测试验证了"macroscopic"的功能，这些功能无法单独由任何一个子项目进行测试。

== 的Eclipse

一个开源的集成开发平台，使用Eclipse来修改或添加到您的克隆版本的Mule源代码。

=== 导入

. 在本地驱动器上下载并安装 http://www.eclipse.org/downloads/[蚀]。
. 在命令行中，在您下载Mule源代码的目录中，输入以下命令为每个子项目生成类路径和项目文件：`mvn eclipse:eclipse`。
.  _在启动Eclipse_之前，使用以下命令在Eclipse中使Maven存储库已知：+
`mvn -Declipse.workspace=/path/to/eclipse/workspace eclipse:configure-workspace`
. 启动Eclipse，选择您只需"mavenized"的工作区。
. 在*Project*菜单下，选择*Build Automatically*为_disable_ it;这一行动加快了进口过程。
. 选择*File*> *Import*。
. 在*Import*向导中，单击以展开*General*文件夹，然后选择*Existing Projects into Workspace*，然后单击** Next**。
. 在*Select root directory*字段中，使用*Browse*按钮导航到您从Github帐户下载克隆的Mule源代码的目录。
. 确保所有*Projects*都已选中，然后点击*Finish*。 Eclipse导入mule源代码。
. 再次选择**Project > Build Automatically**以重新启用构建自动化。
. 当您需要编辑或添加内容时，打开源代码文件。
. 点击*Save*图标保存到本地。

=== 调试

. 在Eclipse中，选择*Window*> *Open Perspective*> **Other...**，然后选择*Java*打开Java透视图。
.  {选择{1}}> *New*> *Java Project*。您正在创建一个新项目，仅用于启动Mule。
. 在*New Java Project*向导中，为您的项目选择*Name*，例如`Mule Launcher`，然后点击*Next*。
. 在向导的*Java Settings*面板中，选择*Projects*选项卡，然后点击*Add*。
. 点击*Select All*，然后点击*OK*，然后点击** Finish**。
. 在包资源管理器中，右键单击您的启动器项目名称，然后选择*Debug As*> **Debug Configurations...**
. 在*Debug Configurations*向导中，双击*Java Application*。
. 在*Main class*字段中，输入以下内容：`org.mule.MuleServer`
. 点击*Arguments*标签。在*Program Arguments*字段中，输入以下内容：`-config <path to a Mule config>`
. 点击*Apply*，然后点击*Debug*。
.  Eclipse请求切换到*Debug Perspective*的权限;点击*Yes*接受并打开。

现在，您可以在工作区的任何Mule项目中的任何Java文件中的任何位置设置断点。 *When you change java files and rebuild, the debugger hot swaps the rebuilt Java class file to the running Mule server.*请注意，您只需按照上述步骤设置您的调试配置一次;之后，只需右键单击项目名称，然后选择*Debug As*> *Java Application*以进行后续调试。

=== 远程调试

.  *From the command line, edit the `JPDA_OPTS` variable in the Mule startup script and specify the debugger port.*
.  *Start the Mule server with the `-debug` switch. The server waits until a debugger attaches.*
. 在studio的Package Explorer中，右键单击您的Mule源代码项目名称，然后选择*Debug*> **Debug Configurations...**
. 双击*Remote Java Application*。
. 在*Connection Properties*下输入*Host*和*Port*的值，然后点击*Apply*。
. 点击*Debug*。 Eclipse请求切换到*Debug Perspective*的权限;点击*Yes*接受并打开。

=== 测试

使用Maven使用以下命令在您的项目上运行单元测试：`mvn test`

除了每个子项目的单元测试之外，Mule父项目还有一个包含集成测试的独立子项目。这些测试验证了"macroscopic"的功能，这些功能无法单独由任何一个子项目进行测试。

=== 设置Eclipse启动参数

如果您愿意，下表列出了许多可用于更改Eclipse启动行为的命令行参数。

[%header,cols="2*"]
|===
| {参数{1}}操作
| `-clean`  |启用插件的干净注册（某些插件在重新启动后不会始终自行注册）
| `-nosplash`  |不会显示Eclipse或插件启动画面
| `-showLocation`  |将工作区的完整路径放在窗口标题中
| `-vm`  |允许您明确设置要使用的JDK
| `-vmargs`  |允许您传入标准VM参数
|===

==  IntelliJ IDEA

使用IntelliJ的IDEA集成平台修改或添加到您的克隆Mule源代码。

=== 导入

.  http://www.jetbrains.com/idea/download/[下载]并安装IntelliJ IDEA。
. 打开IDEA，然后选择*File*> *Open...*
. 浏览到您下载Mule源代码的目录，然后选择`pom.xml`文件。
. 点击*OK*。 IDEA需要一段时间来处理所有`pom.xml`文件。
. 在本地驱动器上为JDK设置正确的源。右键点击**mule-transport-jdbc**目录，然后选择*Module Settings*> *Sources*> **src > main > jdk6**或*jdk7*。重复此步骤作为测试来源。

*Troubleshooting* +
如果IDEA在创建项目时在CXF模块的测试类中显示任何编译错误，则忽略它们是安全的。这些类依赖于Maven构建在执行期间生成的一些测试类。右键单击错误消息，然后选择*Exclude from compile*。或者，您可以从命令行运行`mvn install`以修复错误。

=== 远程调试

. 使用`-debug`开关启动Mule服务器。服务器等待调试器连接。
. 在IDEA中，选择*Run*> *Edit Configurations...*打开*Run/Debug Configurations*窗口。
. 点击*Add New Configuration*（加号），然后选择*Remote*。
. 为配置输入*name*，然后根据需要更新*host*和*port*值（您可以使用默认值`localhost:5005`来调试本地骡子实例）。
. 点击*OK*开始调试会话。

=== 测试

使用Maven使用以下命令在项目上运行单元测试：`mvn test`

除了每个子项目的单元测试之外，Mule父项目还有一个包含集成测试的独立子项目。这些测试验证了"macroscopic"的功能，这些功能无法单独由任何一个子项目进行测试。
