= 入站标题

`@InboundHeaders`注释标记了`@Processor`方法参数，该参数将用于传入入站范围中收到的一个或多个头。此注释值可以定义单个标头，一个逗号分隔的标头名称列表* to denote all headers, or a comma-separated list of wildcard expressions such as 'MULE_', 'X-*'。默认情况下，如果当前消息中没有指定的头部，则会抛出异常。但是，如果标头名称是用'？'定义的后期修复，它将被标记为可选。在定义多个标题名称或使用通配符时，参数可以是`java.util.Map`或`java.util.List`。如果使用`java.util.Map`，则会传入标题名称和值。如果使用`java.util.List`，则只使用标题值。如果定义了单个标题名称，则可以使用标题类型作为参数类型，但也可以使用`java.util.List`或`java.util.Map`。

入站标头集合是不可变的，所以传入的标头`Map`或`List`也是不可变的。试图写入`Map`或`List`将导致`UnsupportedOperationException`。

`@InboundHeaders`注释支持以下参数：

[%header%autowidth.spread]
|===
| {参数{1}}说明
|值+  | *Required*。定义应该注入参数的头文件。
|===

== 限制

用`@Processor`注释的方法可以用`@Payload`，`@InboundHeaders`，`@InvocationHeaders`或`@OutboundHeaders`注释一个参数*at most*。

例如，这是不可能的：

[source, java, linenums]
----
@Processor
    public Object myMethod(@Payload Object payload, @InboundHeaders("*") Map<?, ?> headers) {
----

== 示例

从入站范围注入`url`标头值：

[source, java, linenums]
----
@Processor
    public Object myMethod(@InboundHeaders("url") URL url) {
----

如果存在，则从入站范围注入标头`faz`的值：

[source, java, linenums]
----
@Processor
    public Object myMethod(@InboundHeaders("faz?") String faz) {
----

从入站范围注入`foo`和`bar`标题及其值：

[source, java, linenums]
----
@Processor
   public Object myMethod(@InboundHeaders("foo, bar") Map<?, ?> myHeaders) {
----

从入站范围注入所有标头及其值：

[source, java, linenums]
----
@Processor
    public Object myMethod(@InboundHeaders("*") Map<?, ?> headers) {
----

从入站范围注入名称以`MULE_`或`ba`开头的所有标头

[source, java, linenums]
----
@Processor
    public Object myMethod(@InboundHeaders("MULE_*, ba*") Map<?, ?> headers) {
----

注入`foo`和`bar`标头的值，并且如果出现`baz`标头值，则全部来自入站范围：

[source, java, linenums]
----
@Processor
    public Object process(@InboundHeaders("foo, bar, baz?") List<?> headers) {
----
