=  Anypoint连接器DevKit

Anypoint Connector DevKit提供用于构建用于Mule Runtime的自定义 link:/mule-user-guide/v/3.4/anypoint-connectors[Anypoint连接器]的工具和界面。作为可从集成开发人员那里隐藏API复杂性的可重用组件，自定义连接器便于与SaaS和内部部署Web服务，应用程序和数据源集成。在Mule Studio和Mule运行环境中使用DevKit函数构建的连接器作为核心产品的扩展。 +

本文档包含构建自定义Anypoint连接器所需的全部信息，其中包括：

* 访问基于SOAP，RESTful和Java客户端库的API
* 支持OAuth和基本身份验证，以及其他身份验证方法
* 提供先进的设计时功能，例如Mule link:/mule-user-guide/v/3.4/mule-datasense[DataSense]支持
* 支持连接池，实例池和多租户等运行时属性（需要在CloudHub中运行）

*{{0}}*

== 假设

DevKit文档假定您一般具有Mule，Mule Studio和Java开发的工作知识。它还假定您已经探索了一些https://www.anypoint.mulesoft.com/exchange/?type=connector[existing连接器]并熟悉如何使用它们。它还假定您可以访问目标系统或源的沙箱环境以及它公开的Web服务的文档。尽管本文档提供了需要Maven的任务的操作方法信息，但您理想的情况是熟悉使用 http://eclipse.org/[蚀]或 http://www.jetbrains.com/idea/[的IntelliJ]的Java开发， http://maven.apache.org/guides/getting-started/maven-in-five-minutes.html[Maven的]构建管理器以及基本的Maven概念。

除了熟悉Java语言外，您还需要了解Java注释的用法。 DevKit的功能通过Java注释向连接器开发人员公开，这些注释将代码注入到连接器类中。注入的代码提供了连接器和Mule之间的接口，否则需要每个连接器开发者包含大量的样板代码。本文档通过示例解释了每个DevKit特定的注释。

== 开始使用

* 从 link:/anypoint-connector-devkit/v/3.4/anypoint-connector-concepts[Anypoint连接器概念]开始。
* 如果您急于跳入并立即开始编写代码，请随时提取概念，从 link:/anypoint-connector-devkit/v/3.4/devkit-shortcut-to-success[DevKit成功的捷径]开始。

[TIP]
====
*Problem already solved!*

在挖掘DevKit之前，要考虑到现在已经有数十个与Mule集成的现有连接器。浏览我们的 http://www.mulesoft.org/connectors[图书馆]社区建立和公司建立的连接器，看看是否有人已经解决了您面临的集成挑战。
====
