= 调用标题

`@InvocationHeaders`参数标注标记将用于在调用范围中接收的一个或多个标头中传递的方法参数。此注释值可以定义单个标头或逗号分隔的标头名称列表。为了表示所有标题，值应该是*, or a comma-separated list of wildcard expressions such as 'MULE_, X-*'。默认情况下，如果当前消息中没有指定的头部，则会抛出异常。但是，如果标头名称是用'？'定义的后期修复，它将被标记为可选。在定义多个标题名称或使用通配符时，参数可以是`java.util.Map`或`java.util.List`。如果使用`java.util.Map`，则会传入标题名称和值。

如果使用`java.util.List`，则仅使用标题值。如果定义了单个标题名称，则可以使用标题类型作为参数类型，但也可以使用`java.util.List`或`java.util.Map`。 Invocation头文件集合是不可变的，所以传入的头文件Map或List也是不可变的。尝试写入地图或列表将导致`java.lang.UnsupportedOperationException`。

`@InvocationHeaders`注释支持以下参数：

[%header,cols="10a,90a",width=60%]
|===
| {参数{1}}说明
|的值 | *Optional*。定义应该注入参数的头文件。
|===

== 限制

用`@Processor`注释的方法可以用`@Payload`，`@InboundHeaders`，`@InvocationHeaders`或`@OutboundHeaders`注释一个参数*at most*。

例如，这是不可能的：

[source, java, linenums]
----
@Processor
  public Object myMethod(@Payload Object payload, @InvocationHeaders("*") Map<?, ?> headers) {
----

== 示例

从调用范围注入`url`标头值：

[source, java, linenums]
----
@Processor
 public Object myMethod(@InvocationHeaders("url") URL url) {
----

如果存在，则从调用范围注入标头`faz`的值：

[source, java, linenums]
----
@Processor
  public Object myMethod(@InvocationHeaders("faz?") String faz) {
----

从调用作用域中注入`foo`和`bar`标头及其值：

[source, java, linenums]
----
@Processor
 public Object myMethod(@InvocationHeaders("foo, bar") Map<?, ?> myHeaders) {
----

从调用范围中注入所有标题及其值：

[source, java, linenums]
----
@Processor
public Object myMethod(@InvocationHeaders("*") Map<?, ?> headers) {
----

注入名称以`MULE_`或`ba`开头的所有标头

[source, java, linenums]
----
@Processor
   public Object myMethod(@InvocationHeaders("MULE_*, ba*") Map<?, ?> headers) {
----

注入`foo`和`bar`标头的值，如果出现`baz`标头值，则全部来自调用范围：

[source, java, linenums]
----
@Processor
  public Object process(@InvocationHeaders("foo, bar, baz?") List<?> headers) {
----
