= 管理连接

DevKit可以围绕POJO生成自动连接管理。通过添加特殊的注释，DevKit将生成自动管理连接的代码。有必要标记将处理连接，断开连接，验证连接，获取会话标识符的方法，DevKit的注释处理工具将负责处理剩下的事情。这是真正区分来自`@Module`的{​​{0}}注释扩展名的原因。

例如，如果第三方API由于会话过期而失败，DevKit将自动删除连接，建立一个新连接并重试该操作。

例：

[source, java, linenums]
----
@Connector(name = "saas")
public class SaaSConnector
{
    @Connect
    public void connect(@ConnectionKey String username, String password) { ... }

    @Disconnect
    public void disconnect() { ... }

    @ValidateConnection
    public boolean isConnected() { ... }

    @ConnectionIdentifier
    public boolean getSessionId() { ... }
}
----

==  `@Connect`注释

此注释将`@Connector`中的方法标记为负责创建连接。它将被连接器的连接管理器调用。必须只有一个方法用`@Connect`注释，否则编译将失败。

用`@Connect`注释的方法必须遵循一定的规则：

* 它必须是`public`
* 它必须声明它抛出`org.mule.api.ConnectionException`，不允许其他异常
* 它不能具有与`void`不同的返回类型

==  `@Disconnect`注释

此注释将`@Connector`中的方法标记为负责处理连接。它将被连接器的连接管理器调用。必须只有一个方法用`@Disconnect`注释，否则编译将失败。

用`@Disconnect`注释的方法必须遵循一定的规则：

* 它必须是`public`
* 它无法接收任何参数
* 它不能具有与`void`不同的返回类型

==  `@ValidateConnection`注释

此注释将`@Connector`中的方法标记为负责验证连接器是否实际连接。必须只有一个方法用`@ValidateConnection`注释，否则编译将失败。

用`@ValidateConnection`注释的方法必须遵循一定的规则：

* 它必须是`public`
* 它无法接收参数
* 它不能具有与`boolean`或`java.lang.Boolean`不同的返回类型

==  `@ConnectionIdentifier`注释

此注释将`@Connector`中的方法标记为负责识别连接。它将被连接器的连接管理器调用以进行调试。必须只有一个方法用`@ConnectionIdentifier`注释，否则编译将失败。

用`@ConnectionIdentifier`注释的方法必须遵循一定的规则：

* 它必须是`public`
* 它不能是`static`
* 它无法接收参数
* 它必须返回`java.lang.String`

==  `@InvalidateConnectionOn`注释

此注释可以附加到也由`@Processor`或`@Source`注释的任何方法。它收到一个单独的参数，它是要捕获的异常的类。如果处理器/源引发异常，它将自动使连接失效。
