= 应用程序部署
:keywords: deploy, cloudhub, on premises, on premise

== 开始Mule运行时

运行`<MULE_HOME>/bin/mule`或将Mule作为服务启动，启动Mule。默认情况下，部署`<MULE_HOME>/apps`目录中的所有应用程序。

== 应用程序热部署

Mule应用程序（压缩或分解）可以放入*$MULE_HOME/apps*中。如果Mule运行时已经启动，应用程序将动态部署。

[NOTE]
在运行时解开Mule中的所有应用程序，并删除原始压缩文件。例如，这意味着将zip文件放入'apps'目录会创建一个具有相同名称（不带'zip'扩展名）的新文件夹并删除该zip文件。

成功的应用程序部署由以下方面确认

* 在应用目录中有一个解压缩的应用程序文件夹。例如，对于`stockTrader.zip`  -  `$MULE_HOME/apps/stockTrader`。

* 为正在运行的应用创建的锚文件，例如`$MULE_HOME/apps/stockTrader-anchor.txt`

如果您希望将应用程序存储在其他位置，则可以在基于Unix的系统上执行此操作，方法是从`$MULE_HOME/apps`创建到您的应用程序目录的符号链接。

== 启动Mule运行时并部署特定的应用程序

您还可以在启动Mule运行时时包含*-app*标志。该标志指定要启动的应用程序（用冒号分隔 -  *:*）。

例如：

[source]
----
mule -app foo
----

`foo`是`$MULE_HOME/apps/foo`中的一个Mule应用程序。
在这种情况下，Mule运行时将在启动应用程序时遵守指定的顺序，并且只启动指定的应用程序。

[source]
----
mule -app first:second
----

`first`和`second`都是`$MULE_HOME/apps/`中的Mule应用程序文件夹。

== 取消部署应用程序

不要直接删除应用程序文件夹，而只应删除应用程序的定位文件：

只删除应用的定位文件：

* 防止来自热部署层的干扰，并且不会为并发冲突操作留出空间。
* 避免某些操作系统上潜在的应用程序jar锁定问题，并允许清理关闭和取消部署。

例如，如果`stockTrader`应用程序正在运行（应用程序文件夹和`$MULE_HOME/apps/stockTrader-anchor.txt`文件一样，只需删除锚文件以便在运行时从Mule实例中删除该应用程序。应用程序终止后。

*Note:*取消部署一个Mule应用程序后，直到LoggerContext停止为止，超时时间为15秒。在超时过期后，应用程序的日志文件才会释放。这些信息在Windows中非常重要，您无法删除其他进程正在使用的文件。

== 应用程序热重新部署

将Mule应用程序部署到Mule运行时后，Mule运行时每三秒轮询`$MULE_HOME/apps`文件夹以更新`$MULE_HOME/apps/<appname>/mule-config.xml`（或应用程序的mule-deploy.properties文件中指定的任何config.resources文件）。您可以更新或替换应用程序文件夹内容，并触摸/修改应用程序的配置文件，让Mule重新加载配置并自动重新部署应用程序。

== 在运行时热部署应用程序更新

在运行时更新Mule应用程序可能是一个复杂的更改，涉及类修改，端点修改，端口更改和重新配置的流程。因此，应用程序更新会引起优雅的应用程序关闭并重新进行自我重新配置。在实践中，这对用户是透明的，并在几秒钟内发生。

有几种方法可以更新应用程序：

* 通过在现有分解应用程序文件夹中删除修改，并触摸默认情况下在应用程序根目录中的“主”配置文件（`mule-config.xml`）。

* 将该应用程序的新*zipped*版本放入`$MULE_HOME/apps`目录（具有相同的名称）。 Mule将此检测为现有应用程序更新并确保对应用程序进行干净的重新部署。请注意，对旧应用程序文件夹的任何修改都会被丢弃 - 新的应用程序文件夹是来自zip的干净的分解应用程序。

正如你所看到的，两者都与现有的构建工具相结合，相互之间的偏好确实只取决于既定的开发实践。

注：热重新部署在生产环境中可能很危险。首先取消部署生产应用程序可能会更安全，然后替换Mule应用程序可部署归档文件。对于某些应用程序更改（例如应用程序类路径中的修改文件），您可能还需要在部署新的应用程序版本之前重新启动Mule运行时。

== 共享资源

如果您将多个应用程序部署到同一地点，并且这些应用程序共享相同的资源，则可以创建一个通用的*domain*，您可以在其中定义可由多个项目引用的通用配置。例如，这允许您通过相同的HTTP主机和端口在不同的项目中公开不同的服务，并且能够部署所有内容而没有任何冲突。请参阅 link:/mule-user-guide/v/3.7/shared-resources[共享资源]。

== 禁用Mule容器模式

如果您想运行传统的2.x方式运行Mule 3，请编辑`$MULE_HOME/conf/wrapper.conf`文件并替换以下几行：

[source, java, linenums]
----
# Java Main class
wrapper.java.mainclass=org.mule.module.reboot.MuleContainerBootstrap
----

附：

[source, java, linenums]
----
# Java Main class
wrapper.java.mainclass=org.mule.module.boot.MuleBootstrap
----

在旧模式下运行时，新应用程序部署功能均不适用。

== 嵌入式Mule

当Mule嵌入到应用程序服务器，Java应用程序，单元测试，IDE等中并以编程方式启动时，部署功能被禁用，Mule遵循传统应用程序模型。

== 故障处理

如果应用程序无法启动，比如提供了破损的配置文件，Mule会*not*监控应用程序的更改（因为没有应用程序正在运行）。要更新这样的应用程序，只需通过将更新后的存档放入应用程序文件夹重新部署应用程序即可。

