= 配置Maven以使用Mule
:keywords: anypoint, studio, maven

在Anypoint Studio之外使用Maven和Mule时，您需要配置Maven安装以成功使用Mule。本页介绍如何维护您的POM文件以添加或调整依赖关系并指向正确的MuleSoft存储库，以及如何修改Maven {0}文件以包含Enterprise存储库的凭证和配置文件。

修改完Maven安装后，您可以安装Mule插件并开发引用Mule开源或企业存储库的应用程序。

link:/mule-user-guide/v/3.7/maven-tools-for-mule-esb[Male的Maven工具]插件提供了用于构建Mule应用程序的Maven原型，大大简化了Maven开发过程。

*Note:* https://www.anypoint.mulesoft.com/exchange/?type=connector[Anypoint Exchange]提供了Maven依赖关系信息。
单击连接器资源并单击Dependency Snippets列出Maven pom.xml文件依赖项。

== 先决条件

本文档假设您正在使用Maven以外的Anypoint Studio，因此将使用原型来构建Mule应用程序。请参阅 link:/mule-user-guide/v/3.7/using-maven-with-mule[和Mule一起使用Maven]，了解如何使用Maven管理您的Mule项目。本文档还假定您已经安装了https://maven.apache.org/download.cgi[Apache Maven]。

[NOTE]
====
请注意，如果您是 link:/mule-user-guide/v/3.7/using-maven-with-mule[通过Studio与Maven合作]，则通常不需要修改settings.xml文件，因为Studio会跟踪您需要的依赖关系，并尝试在应用程序的关联POM文件中为您进行管理。如果发生依赖性错误，您可能需要手动调整POM文件，并且在某些情况下，可以在settings.xml中进行调整。有关具体说明，请参阅Maven文档中的 link:http://maven.apache.org/pom.html[的pom.xml]和 link:http://maven.apache.org/settings.html[的settings.xml]。
====

== 设置概述

在开始使用Maven从命令行使用原型创建新的Mule项目之前，您需要：

. 确保目录中的 link:https://maven.apache.org/download.cgi[Maven已安装]不包含空格。

. 为您的应用程序创建或维护您已创建的`pom.xml`文件，以包含对MuleSoft开放源代码库以及任何需要包含在每个应用程序中的连接器，模块或其他扩展的引用。

.  _仅限企业用户：_修改`settings.xml`文件以指向企业客户存储库并提供您的凭据。

== 为您的Male配置您的Maven安装

=== 启用MuleSoft插件

要启用MuleSoft插件，您可以修改您的项目文件（POM）或您的`settings.xml`文件。编辑所需的配置文件以包含以下内容：

[source, xml, linenums]
----
<settings>
    <pluginGroups>
        <pluginGroup>org.mule.tools</pluginGroup>
    </pluginGroups>
    ...
</settings>
----

=== 引用开源MuleSoft存储库

编辑您的`settings.xml`或项目文件以包含以下内容：

[source, xml, linenums]
----
<repositories>
...
    <repository>
        <id>mulesoft-releases</id>
        <name>MuleSoft Repository</name>
        <url>http://repository.mulesoft.org/releases/</url>
        <layout>default</layout>
    </repository>
    <repository>
        <id>mulesoft-snapshots</id>
        <name>MuleSoft Snapshot Repository</name>
        <url>http://repository.mulesoft.org/snapshots/</url>
        <layout>default</layout>
    </repository>
...
</repositories>
----

如果您需要的依赖关系尚未存在，请按所示添加它们。

[source, xml, linenums]
----
<dependencies>
...
    <dependency>
        <groupId>GROUP ID OF DEPENDENCY</groupId>
        <artifactId>ARTIFACT ID OF DEPENDENCY</artifactId>
        <version>VERSION OF DEPENDENCY</version>
    </dependency>
...
<dependencies>
----

例如，如果您要添加Salesforce连接器的依赖项，请执行以下操作：

[source, xml, linenums]
----
<dependencies>
...
    <dependency>
        <groupId>org.mule.modules</groupId>
        <artifactId>mule-module-sfdc</artifactId>
        <version>LATEST</version>
    </dependency>
...
<dependencies>
----

不确定您需要的连接器的依赖性详细信息是什么？请参阅 link:http://www.mulesoft.org/connectors[连接器网站]上特定于连接器的Maven说明。

=== 引用MuleSoft的企业存储库

*_Enterprise_*

本节假定您已获得 link:https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/[MuleSoft Enterprise Maven客户存储库]的{​​{0}}和凭证，从而允许您访问Mule Enterprise模块，连接器以及未包含在试用版或社区版中的其他组件。如果您是MuleSoft客户并且无法访问存储库，请联系 link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft支持]。

要配置Maven访问MuleSoft客户信息库，您需要对`settings.xml`配置文件进行添加。您的`.m2`目录可能已经包含名为`settings.xml`的配置文件。请注意，该文件不是强制性的。如果文件不存在，Maven将使用默认参数。如果您根本没有`settings.xml`文件，请在`~/.m2`文件夹中创建它。详细了解 link:http://maven.apache.org/settings.html[Maven文档]中的`settings.xml`文件。

. 打开文件`<USER_HOME>/.m2/settings.xml`进行编辑。

. 将以下内容添加到`servers`部分。
+
[source, xml, linenums]
----
<server>
 
    <id>MuleRepository</id>
    <username>YOUR_ID</username>
    <password>YOUR_PASSWORD</password>
 
</server>
----

. 将以下内容添加到`profiles`部分：
+
[source, xml, linenums]
----
<profile>
 
    <id>Mule</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <repositories>
        <repository>
            <id>MuleRepository</id>
            <name>MuleRepository</name>
            <url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
 
</profile>
----

== 另请参阅

* 了解 link:/mule-user-guide/v/3.7/maven-tools-for-mule-esb[Male的Maven工具]，这是一款在Maven中开发Mule应用程序的Mule插件。
* 使用 link:/mule-user-guide/v/3.7/mule-esb-plugin-for-maven[Maven的Mule插件]来控制Mule的实例。
* 请参阅 link:https://maven.apache.org/settings.html[关于设置的Maven文档]以从settings.xml文件配置服务器和存储库访问权限。
