= 将Mule部署到WebLogic
:keywords: deploy, deploying, weblogic

这些说明假定您已经下载并安装了WebLogic Application Server 10.3版。请注意，WebLogic 8.x和9.x也受支持，但这些说明仅适用于Oracle WebLogic 10.3版。

*Note:*有关在WebLogic下运行web应用程序中的Mule示例，请从独立分发中获取webapp示例并进行上述更改。

== 在WebLogic中使用Mule部署Web应用程序

执行以下步骤，详细解释如下：

. 使用您的应用程序创建一个WAR文件。
.  _必填._通过向*weblogic.xml*文件添加元素来修改您的<<Modify your WebLogic Configuration>>。
. 按照<<Configuring Logging>>中所述配置日志记录。

=== 创建一个WAR文件

在将Mule应用程序部署到WebLogic之前，您必须将其准备为Web应用程序。这包括为您的Mule应用程序创建一个`web.xml`文件，配置服务器的`weblogic.xml`文件以及创建所有支持文件的`.war`文件。

`web.xml`文件通过指定Mule配置文件和用于在WebSphere容器中启动Mule的其他选项来将Mule应用程序配置为Web应用程序。根据下面的示例为您的Mule应用程序创建一个`web.xml`文件。

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app id="WebApp_ID" version"2.4">
  <!--Mule configuration (Mule format)-->
  <context-param>
    <param-name>org.mule.config</param-name>
    <param-value>mule-config.xml</param-value>
  </context-param>
  <listener>
    <listener-class>org.mule.config.builders.MuleXmlBuilderContextListener</listener-class>
  </listener>
  <servlet-mapping>
        <servlet-name>muleServlet</servlet-name>
        <url-pattern>/app-path/*</url-pattern>
    </servlet-mapping>
  <!--Mule configuration ends-->
</web-app>
----

=== 修改您的WebLogic配置

在*weblogic.xml*文件中包含这些行以优先考虑Mule库：

[source, xml, linenums]
----
<container-descriptor>
   <prefer-web-inf-classes>true</prefer-web-inf-classes>
</container-descriptor> 
----

相反，如果要覆盖更细粒度的包，可以参考单个包，如下所示：

[source, xml, linenums]
----
<container-descriptor>
   <prefer-application-packages>
      <package-name>org/apache/commons/lang</package-name>
   </prefer-application-packages>
</container-descriptor>
----

[TIP]
====
在Oracle的 link:http://docs.oracle.com/cd/E23943_01/web.1111/e13706/classloading.htm#WLPRG282[了解WebLogic Server应用程序类加载]中阅读有关WebLogic Classloading的更多信息。
====

=== 配置日志记录

Mule使用 link:http://logging.apache.org/log4j/2.x/index.html[Log4j2]。可以对WebLogic进行配置，以便WebLogic和Mule的日志记录都使用log4j。

. 将`<WLHOME>/wlserver_10.3/server/lib/wllog4j.jar`复制到`<WLHome>/user_projects/domains/<yourdomain>/lib`。
.  link:http://logging.apache.org/log4j/1.2/download.html[下载] Log4j日志文件。
. 解压缩文件并将`log4j.jar`复制到`<WLHome>/user_projects/domains/<yourdomain>/lib`。
.  link:http://commons.apache.org/downloads/download_logging.cgi[下载] Commons记录文件。
. 解压缩文件并将`commons-loggin.jar`复制到`<WLHome>/user_projects/domains/<yourdomain>/lib`。
. 启动您的WebLogic域并登录到控制台。
. 在左侧导航窗格中，展开*Environment*，然后选择*Servers*。
. 在Servers表中，单击要配置其日志记录的服务器实例的名称。
. 选择*Logging*> *General*，然后点击页面底部的*Advanced*。
. 在日志记录实施列表框中，选择*Log4j*。
. 点击*Save*。
. 重新启动WebLogic域以激活更改。

== 部署Mule

这些说明通过管理控制台演示了部署。请注意，此部分在部署将Mule嵌入到WebLogic的EAR或WAR时也适用，在这种情况下，您将部署EAR或WAR。

==== 使用管理控制台部署Mule

从管理控制台部署Mule：

. 启动WebLogic服务器。例如，在Windows上选择*Start*> *BEA Products*> *WebLogic Server*。
. 为您的域启动管理服务器。例如，在Windows上，您可以选择*Start*> *BEA Products*> * User Projects*> *<yourdomain>*> *Start Admin Server for WebLogic Server Domain*。
. 提示时，使用您在创建域时指定的用户名和密码登录到控制台。如果您关闭控制台并稍后需要重新启动它，则可以转到网址`http://localhost:7001/console/console.portal`。
. 在左侧的域结构中，点击*Deployments*。
. 点击*Install*，然后导航至您下载Web应用程序EAR文件的位置。
. 选择EAR文件并点击*Next*。
. 选择*Install this deployment as an application*
. 选择*Next*。
. 选择*Finish*。
. 在左侧的更改中心中，点击*Activate Change*。

