= 流程参考和属性。
:keywords: anypoint studio, esb, flow processing, synchronous, asynchronous, sync, async, flow

[NOTE]
不要与 link:/mule-user-guide/v/3.7/flow-reference-component-reference[流量参考组件]混淆。 +
本文旨在介绍流的属性以及它如何在XML和可视化编辑器中表示。

== 流属性
流程有三个不同的属性：

=== 名
用于标识流的强制nonBlankString值。

+ name +值将用于引用应用程序中的流程。

===  processingStrategy
确定用于处理启动流程的已组态消息处理器的策略。
此属性接受具有默认配置选项的枚举策略之一或对全局定义策略的引用。

.  +同步+ +
使用同步模型作为处理策略。这允许您在收到它们的同一个线程中处理消息。 +
该属性在 link:/mule-user-guide/v/3.7/flow-processing-strategies#synchronous-flow-processing-strategy[处理策略设置]页面及其中的特定部分进行了完整说明
link:/mule-user-guide/v/3.7/flows-and-subflows#sts=synchronous%20Flows[流量和子流量]页面。

.  +异步+ +
使用异步模型作为处理策略。异步流将在每次被另一个流触发时处理消息，并且可以与其触发流同时处理，因为它不需要返回任何值。 +
该属性在 link:/mule-user-guide/v/3.7/flow-processing-strategies#synchronous-flow-processing-strategy[处理策略设置]页面中进行了完整说明，异步处理策略如何工作的详细示例可以在 link:/mule-user-guide/v/3.7/flows-and-subflows#sts=asynchronous%20Flows[流量和子流量]页面的特定部分找到。

.  +非阻止+ +
使用一个公开的非阻塞模型作为处理策略。这使得请求和响应阶段都可以在不同的线程中执行。 +
有关此属性如何在Mule内工作的更详细说明可以在 link:/mule-user-guide/v/3.7/flow-processing-strategies#non-blocking-processing-strategy[处理策略设置]页面中找到。

.  +排队异步+ +
 使用队列管理的接收器模型作为处理策略。它放置一个队列，将流的接收器与流中的其余步骤通过 link:/mule-user-guide/v/3.7/vm-transport-reference[VM传输组件]分开。 +
有关此属性如何在Mule内工作的更详细说明可以在 link:/mule-user-guide/v/3.7/flow-processing-strategies#queued-asynchronous-flow-processing-strategy[处理策略设置]页面中找到。

.  +每个处理器的线程数+ +
使用每线程处理器模型作为处理策略。尽管它并不适用于大多数用例，但该策略只是在新线程中运行流程范围中的每个处理器。

.  +排队每线程处理器+ +
使用队列管理模型来处理每线程处理器策略。该策略不适用于大多数用例，但实质上只是将消息发布到队列中，然后流程作用域中的每个处理器都运行在新线程中。


=== 的初始化状态
流的初始状态。 +
该属性有两个可用选项：+开始+和+停止+

通常情况下，流程自动为"started"并且默认情况下设置了此值，但通过将此属性设置为"stopped"，可以使用此属性禁用初始启动。

[TIP]
====
您可以定义"stopped"初始状态，以便在某个事件触发它之前暂停流程。 +
假设您想在从外部系统收到通知后立即开始流程。
您可以将initialState属性设置为在等待通知的流程中停止，并让另一个流程接收通知（使用您想要的任何传输）并以编程方式从该活动流程开始第一个流程。
====

== 子流

子流是一系列同步处理的消息处理器，可以通过 link:/mule-user-guide/v/3.7/flow-reference-component-reference[流量参考组件]进行引用和重用。

流可以引用多个子流来完成同步处理任务，并且子流可以具有多个触发流。

子流节点可以使用的唯一属性是+ name +。这是一个强制的nonBlankString值，用于标识子流以便从流参考组件中引用它。

[tabs]
------
[tab,title="XML Editor or Standalone"]
....

A representation of a subflow in XML looks something like this.

[source,xml, linenums]
----
<flow name="mainFlow">
<flow-ref name="subFlow" doc:name="Flow Reference"/>
</flow>

<sub-flow name="subFlow">
</sub-flow>
----

Note that the Flow Reference connector points to the +sub-flow+ node named "subFlow"
....

------

有关Studio和XML中有关如何使用子流的详细示例，请务必在我们的 link:/getting-started/content-based-routing[基于内容的路由]中检查_Adding Subflow_部分。


== 另请参阅

*  *NEXT STEP*：了解 link:/mule-user-guide/v/3.7/flow-processing-strategies[流程处理策略]。

link:/mule-user-guide/v/3.7/flows-and-subflows[流量和子流量]

link:/mule-user-guide/v/3.7/flow-processing-strategies[流程处理策略]

link:/mule-user-guide/v/3.7/elements-in-a-mule-flow[骡子流中的元素]
