=  JBoss jBPM模块参考
:keywords: mule, studio, jboss, bpms

link:http://www.jboss.org/jbpm[JBoss jBPM]是同类最佳的开源BPMS，与Mule很好地结合在一起。 jBPM的一个优点是它直接嵌入到Mule运行时中，可以提高性能。有关jBPM的一般信息以及如何配置它，请参阅 link:http://docs.jboss.org/jbpm/v4/userguide/html_single/[jBPM用户指南]。

[WARNING]
该模块为JBoss jBPM提供了一个用于Mule的BPM支持的"Plug-in"。如果您还没有阅读Mule的 link:/mule-user-guide/v/3.7/bpm-module-reference[BPM支持]的一般文档，请先阅读并随后返回此页面。

== 命名空间和语法

XML名称空间：

[source]
----
xmlns:bpm "http://www.mulesoft.org/schema/mule/bpm"
----

XML架构位置：

[source]
----
http://www.mulesoft.org/schema/mule/bpm/3.7/mule-bpm.xsd
----

句法：

[source, xml, linenums]
----
<bpm:jbpm />

<bpm:process processName="myProcess" processDefinition="my-process.jpdl.xml" />
----

== 特点

* 使用合理的默认值，将jBPM作为Mule配置中的BPMS进行简单声明。
*  jBPM流程定义语言（jPDL）的自定义元素，可让您轻松将Mule集成到业务流程中。

有关Mule BPM支持提供的一般功能列表，请参阅 link:/mule-user-guide/v/3.7/bpm-module-reference[BPM模块参考]。

[NOTE]
jBPM库与Mule发行版捆绑在一起。 jBPM 4.4是最新的支持版本。

== 用法

在Mule中使用jBPM由几件事组成：

* 配置jBPM
* 配置Hibernate和用于存储进程状态的数据库
* 声明jBPM为您在Mule配置中使用的BPMS
* 从流程定义中与Mule进行交互

===  jBPM配置

jBPM的默认配置文件称为`jbpm.cfg.xml`。你需要把这个文件作为你的Mule应用程序的一部分。如果默认值对你来说可以，那么它可以像下面这样简单。

*jBPM Configuration (jbpm.cfg.xml)*

[source, xml, linenums]
----
<jbpm-configuration>
    <import resource="jbpm.default.cfg.xml" />
    <import resource="jbpm.jpdl.cfg.xml" />
    <import resource="jbpm.tx.hibernate.cfg.xml" />

    <process-engine-context>
        <object class="org.mule.module.jbpm.MuleMessageService" /> //<1>
    </process-engine-context>
</jbpm-configuration>
----

<1>请注意，您需要在`<process-engine-context>`中定义MuleMessageService，否则jBPM不能"see" Mule。

有关更多配置选项，请参阅 link:http://docs.jboss.org/jbpm/v3/userguide/configuration.html[jBPM文档]。

=== 数据库配置

jBPM使用Hibernate来持久化进程的状态，所以你需要提供一个 link:http://community.jboss.org/wiki/SupportedDatabases[数据库由Hibernate支持]并且包含任何客户端jar作为你的Mule应用程序的一部分。您还需要为所选数据库提供适当的Hibernate设置的文件`jbpm.hibernate.cfg.xml`。

例如，简单的内存数据库 link:http://db.apache.org/derby/[德比]可能会使用这些设置：

*Derby settings*

[source, xml, linenums]
----
<property name="hibernate.dialect">org.hibernate.dialect.DerbyDialect</property>
  <property name="hibernate.connection.driver_class">org.apache.derby.jdbc.EmbeddedDriver</property>
  <property name="hibernate.connection.url">jdbc:derby:memory:muleEmbeddedDB</property>
  <property name="hibernate.hbm2ddl.auto">create-drop</property>
----

Oracle数据库使用这些设置：

*Oracle settings*

[source, xml, linenums]
----
<property name="hibernate.dialect">org.hibernate.dialect.OracleDialect</property>
<property name="hibernate.connection.driver_class">oracle.jdbc.driver.OracleDriver</property>
<property name="hibernate.connection.url">jdbc:oracle:thin:user/pass@server:1521:dbname</property>
----

需要注意的一个非常重要的Hibernate设置是`hibernate.hbm2ddl.auto`。如果设置为`create`，那么Hibernate会在启动时自动为jBPM创建数据库模式，前提是数据库中尚不存在该模式。如果它设置为`create-drop`，那么架构在关闭时也会被删除，这在测试环境中很有用。

有关更多配置选项，请参阅 link:http://docs.jboss.org/jbpm/v4/devguide/html_single/#configuration[jBPM文档]和/或 link:http://docs.jboss.org/hibernate/core/3.6/reference/en-US/html_single/#configuration-xmlconfig[Hibernate文档]。

===  Mule配置

在Mule配置中使用jBPM就像包含`<bpm:jbpm>`元素一样简单。默认配置文件假定为`jbpm.cfg.xml`，否则您可以使用`configurationResource`属性指定它。

*Default config*

[source, xml]
----
<bpm:jbpm />
----

*Custom config*

[source, xml]
----
<bpm:jbpm name="jBPM" configurationResource="custom-jbpm-config.cfg.xml"/>
----

=== 流程定义（jPDL）

由于缺乏BPM社区的良好标准，jBPM传统上使用自己的DSL来处理名为 link:http://docs.jboss.org/jbpm/v4/userguide/html_single/#jpdl[jPDL中]的流程定义。学习起来非常简单，并且有一个称为图形流程设计器的 link:http://docs.jboss.org/jbpm/v4/userguide/html_single/#graphicalprocessdesigner[Eclipse插件]，它允许您以可视方式创建流程定义。

[WARNING]
在将来的版本中，首选定义语言可能是 link:http://community.jboss.org/wiki/jBPMBPMN[BPMN 2.0]，现在它已成为BPM社区中被广泛接受的标准。 Mule目前通过Activiti BPM模块支持BPMN定义的流程。

Mule为jBPM的流程定义语言（jPDL）提供了两个自定义元素。您可以在流程定义中将这些与其他 link:http://docs.jboss.org/jbpm/v4/userguide/html_single/#jpdl[标准jPDL元素]一起使用，例如`<state>, <java>, <script>, <decision>`。

[%header,cols="20a,80a"]
|===
|元素 |说明
| <mule-send>  |将有效载荷*`expr`*发送到Mule *endpoint*的消息。如果*exchange-pattern* =请求响应（缺省值），则发送块和响应消息存储在*var*中。如果消息不是*type*，则抛出异常。 *expr*可以是引用流程变量的文字值或 link:http://java.sun.com/javaee/5/docs/tutorial/doc/bnahq.html[表达]。唯一的必需属性是*expr*和*endpoint*，其余是可选的。

*Usage*：

[source]
----
<mule-send expr="" endpoint="" exchange-pattern="" var="" type="">
----
| <mule-receive>  |等待预期消息从Mule *endpoint*到达并将其存储到*var*中的状态。如果消息不是*type*，则抛出异常。 `<mule-receive>`可以将`<start>`替换为进程的第一个状态，这样您可以将启动进程的消息存储到变量中。这些属性都是可选的。


*Usage*：

[source]
----
<mule-receive var="" endpoint="" type="">
----
|===

== 配置示例

*Example Mule Configuration*

[source, xml, linenums]
----
<mule ...cut...
    xmlns:bpm="http://www.mulesoft.org/schema/mule/bpm"
    xsi:schemaLocation="...cut...
       http://www.mulesoft.org/schema/mule/bpm http://www.mulesoft.org/schema/mule/bpm/3.2/mule-bpm.xsd"> //<1>

    <bpm:jbpm name="jbpm" /> //<2>

    <flow name="ToBPMS">
        <composite-source>
            <inbound-endpoint ref="CustomerRequests" /> //<3>
            <inbound-endpoint ref="CreditProfiles" />
        </composite-source>
        <bpm:process processName="LoanBroker" processDefinition="loan-broker-process.jpdl.xml" /> //<4>
    </flow>
    ...cut...
</mule>
----

<1>导入BPM模式。
<2>声明jBPM作为要使用的BPMS实现。
<3>这些端点上的传入消息启动/推进流程并作为流程变量进行存储。
<4> loan-broker-process.jpdl.xml中定义的流程在启动时会部署到jBPM。

*Example jPDL Process Definition*

[source, xml, linenums]
----
<process name="LoanBroker" xmlns="http://www.jbpm.org/4.3/jpdl">

    <mule-receive name="incomingCustomerRequest" endpoint="CustomerRequests" type="foo.messages.CustomerQuoteRequest" var="customerRequest">
        <transition to="sendToCreditAgency" />
    </mule-receive> //<1>

    <mule-send name="sendToCreditAgency"
          expr="#{customerRequest.customer}" endpoint="CreditAgency" exchange-pattern="one-way">
        <transition to="sendToBanks" />
    </mule-send> //<2>

    <decision name="sendToBanks"> //<3>
        <transition to="sendToBigBank">
            <condition expr="#{customerRequest.loanAmount >= 20000}" /> //<4>
        </transition>
        <transition to="sendToMediumBank">
            <condition expr="#{customerRequest.loanAmount >= 10000}" />
        </transition>
        ...cut...
    </decision>

    ...cut...
    <end name="loanApproved" />
</process>
----

<1>传入消息需要`foo.messages.CustomerQuoteRequest`类型的端点`CustomerRequests`存储到过程变量`customerRequest`中。
<2>将新消息发送到端点`CreditAgency`，端点的有效负载是使用过程变量`customerRequest`的表达式。
<3> `<decision>`是一个标准的jPDL元素。
<4>决策逻辑使用过程变量`customerRequest`。

[source, xml, linenums]
----
<mule ...cut...
  <bpm:jbpm name="jbpm" />

  <model>
    <service name="ToBPMS"> //<1>
        <inbound>
            <inbound-endpoint ref="CustomerRequests" />
            <inbound-endpoint ref="CreditProfiles" />
        </invound>
        <bpm:process processName="LoanBroker" processDefinition="loan-broker-process.jpdl.xml" />
    </service>
    ...cut...
  </model>
</mule>
----
<1>建议使用新的实现流程，但Mule 2.x用户将更加熟悉服务。

=== 配置参考

==  Jbpm的

<jbpm...>的{​​{0}}属性

[%header,cols="20a,80a"]
|=========
| {名称{1}}说明
| name  |此BPMS的可选名称。如果您有多个BPMS可用，请从您的流程的"bpms-ref"字段中参考此处。

*Type*：名称（不包含空格）+
*Required*：否+
*Default*：无
| configurationResource  | jBPM的配置文件，如果未指定，则默认为"jbpm.cfg.xml"。

*Type*：string +
*Required*：否+
*Default*：无
| processEngine-ref  |对已经初始化的jBPM ProcessEngine的引用。如果你使用Spring来配置你的jBPM实例，这很有用。请注意，在这种情况下，"configurationResource"属性将被忽略。

*Type*：string +
*Required*：否+
*Default*：无
|=========

无<jbpm...>的子元素


==  XML架构

该模块使用来自 link:/mule-user-guide/v/3.7/bpm-module-reference[BPM模块]的模式。它没有自己的模式。

导入BPM架构如下：

[source, xml, linenums]
----
xmlns:bpm="http://www.mulesoft.org/schema/mule/bpm"
xsi:schemaLocation="http://www.mulesoft.org/schema/mule/bpm  http://www.mulesoft.org/schema/mule/bpm/3.6/mule-bpm.xsd"
----

有关BPM模式元素的详细信息，请参阅 link:/mule-user-guide/v/3.7/bpm-module-reference[BPM模块参考]。

== 的Maven

如果您使用Maven构建应用程序，请使用以下groupId和artifactId将此模块作为依赖项包含在内：

[source, xml, linenums]
----

<dependency>
  <groupId>org.mule.modules</groupId>
  <artifactId>mule-module-jbpm</artifactId>
</dependency>
----

