= 码头运输
:keywords: mule, studio, jetty, SSL

Jetty传输通过嵌入轻量级Jetty服务器为通过HTTP公开应用程序提供支持。 link:/mule-user-guide/v/3.7/jetty-ssl-transport[Jetty SSL Transport]的工作方式与SSL相同。您只能使用此传输来定义入站端点。

这个运输的Javadoc可以在下面找到：

http://www.mulesoft.org/docs/site/3.7.0/apidocs/org/mule/transport/servlet/jetty/JettyHttpConnector.html[码头运输Javadoc]

该连接器允许Mule使用Jetty HTTP服务器通过HTTP公开Mule服务。为每个连接器实例创建一个Jetty服务器。一个连接器可以服务于许多端点。用户应该很少需要有多个Jetty连接器。 Jetty连接器可以使用Jetty XML配置文件进行配置，但对于大多数情况，默认配置已足够。

连接器的== 属性

这些属性适用于可选的全局连接器jetty：connector。

[%header,cols="30a,70a"]
|===
| {名称{1}}说明
| name  |可在流中引用的连接器的名称。

*Type*：string +
*Required*：是+
*Default*：Jetty
| configFile  |用于配置此连接器的Jetty配置文件的位置。

*Type*：string +
*Required*：否+
*Default*：无
|接受者 |接受者线程的数量。

*Type*：整数+
*Required*：否+
*Default*：1
| resourceBase  |指定提供文件的本地路径。本地路径直接映射到'serverUrl'上的路径。

*Type*：string +
*Required*：否+
*Default*：无
| useContinuations  |是否在高负载情况下使用延续来释放连接。

*Type*：布尔+
*Required*：否+
*Default*：无
| doc：name  |连接器的描述性名称。在Mule独立配置中不需要。

*Type*：string +
*Required*：仅适用于Studio配置+
*Default*：Jetty
|===

连接器的== 子元素

[%header,cols="20a,20a,60a"]
|===
| {名称{1}}基数 |说明
| webapps  | 0..1  |允许配置包含由Jetty提供的WAR文件的目录。
|===

== 端点

Jetty端点的配置方式与 link:/mule-user-guide/v/3.7/file-transport-reference[FTP端点]相同。请注意，Jetty传输只能用于入站端点。

例如：

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns:jetty="http://www.mulesoft.org/schema/mule/jetty" xmlns:file="http://www.mulesoft.org/schema/mule/file" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:spring="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
http://www.mulesoft.org/schema/mule/jetty http://www.mulesoft.org/schema/mule/jetty/current/mule-jetty.xsd">
    <flow name="somethingFlow1" doc:name="somethingFlow1">
        <jetty:inbound-endpoint exchange-pattern="request-response" address="http://localhost:8081/path" doc:name="Jetty"/>
    </flow>
</mule>
----

