用于Mule ESB的=  Maven工具
:keywords: studio, maven, esb, version control, dependencies, libraries, maven tools

适用于Mule的Maven工具ESB是Maven的插件，允许您使用Maven工具开发Mule应用程序。该插件提供的套件包括用于构建常规Mule应用程序，Mule域和Mule域捆绑的原型。

== 假设

本文档假定您熟悉Maven，管理pom.xml文件以及使用Maven插件。 （如果您刚开始使用Maven，我们建议您遵循 link:http://maven.apache.org/guides/getting-started/[Maven的入门教程]。）此外，本文档假定您熟悉在Maven中开发Mule应用程序。有关Mule和Maven的更多信息，请参阅 link:/mule-user-guide/v/3.7/using-maven-with-mule[和Mule一起使用Maven]。

== 将插件添加到Maven

=== 为插件添加Maven依赖项

要使插件生效，您需要在`settings.xml`文件中添加一些条目，如下所示。

. 编辑`settings.xml`，添加一个包含以下`repositories`和`pluginRepositories`的新配置文件。
+
[source, xml, linenums]
----
<profiles>
     ...
     <profile>
        <id>mule-extra-repos</id>
        <activation>
            <activeByDefault>true</activeByDefault>
        </activation>
        <repositories>
            <repository>
                <id>mule-public</id>
                <url> https://repository.mulesoft.org/nexus/content/repositories/public </url>
            </repository>
        </repositories>
        <pluginRepositories>
            <pluginRepository>
                <id>mule-public</id>
                <url> https://repository.mulesoft.org/nexus/content/repositories/public </url>
            </pluginRepository>
        </pluginRepositories>
     </profile>
     ...
 </profiles>
----
+
. 添加一个新的`pluginGroup`，如下所示。
+
[source, xml, linenums]
----
<pluginGroups>
    ...
    <pluginGroup>org.mule.tools</pluginGroup>
    ...
 </pluginGroups>
----


=== 为应用程序或域指定Mule服务器

构建应用程序或域后，可以使用`-Dmule.home`参数将其安装到所需的Mule ESB实例。如果此参数未设置，则该插件将安装到`$MULE_HOME`。

== 创建一个Mule应用程序

用于Mule ESB的Maven工具通过使用几个简单的参数运行Maven使得创建Mule应用程序非常容易，如下所示。

[source, code, linenums]
----
mvn archetype:generate -DarchetypeGroupId=org.mule.tools.maven -DarchetypeArtifactId=maven-archetype-mule-app -DarchetypeVersion=1.1 -DgroupId=org.mycompany.app -DartifactId=mule-app -Dversion=1.0.0-SNAPSHOT -DmuleVersion=3.7.0 -Dpackage=org.mycompany.app -Dtransports=http,jms,vm,file,ftp -Dmodules=db,xml,jersey,json,ws
----

使用的参数：

[source, code, linenums]
----
archetypeGroupId
archetypeArtifactId
archetypeVersion
groupId
artifactId
version
muleVersion
package
transports
modules
----

有关这些参数的描述以及所有可用参数的列表，请参见下表。

要将您的应用程序定义为属于Mule域，请添加域规范参数：

[source, code, linenums]
----
-DdomainGroupId=org.mycompany.domain -DdomainArtifactId=mule-domain -DdomainVersion=1.0-SNAPSHOT
----

使用的参数：

[source, code, linenums]
----
domainGroupId
domainArtifactId
domainVersion
----

有关这些参数的描述以及所有可用参数的列表，请参见下表。

== 创建一个Mule域

Mule应用程序可以属于一个域组。域允许在应用程序之间共享资源，例如连接器或库。

要创建域，请运行以下命令：

[source, code, linenums]
----
mvn archetype:generate -DarchetypeGroupId=org.mule.tools.maven -DarchetypeArtifactId=maven-archetype-mule-domain -DarchetypeVersion=1.1 -DgroupId=org.mycompany.domain -DartifactId=mule-domain -Dversion=1.0.0-SNAPSHOT -Dpackage=org.mycompany.domain
----

使用的参数：

[source, code, linenums]
----
archetypeGroupId
archetypeArtifactId
archetypeVersion
groupId
artifactId
version
package
----

有关这些参数的描述以及所有可用参数的列表，请参见下表。

== 创建一个完整的Mule域项目

几个Mule应用程序可以使用特定的Mule域来共享资源;因此将所有应用程序和域集中在一个项目中是有意义的。

要创建一个Maven项目，其中包含域以及将使用该域部署的所有应用程序，可以使用Mule域捆绑包原型，如下所示。

[source, code, linenums]
----
mvn archetype:generate -DarchetypeGroupId=org.mule.tools.maven -DarchetypeArtifactId=maven-achetype-mule-domain-bundle -DarchetypeVersion=1.1 -DgroupId=com.mycompany -DartifactId=mule-project -Dversion=1.0.0-SNAPSHOT -Dpackage=com.mycompany
----

该命令使用以下模块创建一个Maven多模块项目：

* 域：此项目与使用Mule域原型创建的任何项目完全相同。此项目的工件ID为​​`${artifactId}-domain`（在本例中为`mule-api-domain`）
* 个应用程序：此项目是Mule应用程序的一个捆绑项目，该应用程序展示给此域。在这里，您可以使用Mule应用程序原型创建Mule应用程序
*  domain-bundle：此项目会为应用程序的域plust创建一个捆绑产品。此捆绑项目可以部署为任何域，并且还将部署域应用程序

如果您使用的是企业版（EE）发行版，请将`EE`标志设置为`true`：

[source, code, linenums]
----
-DEE=true
----

使用的参数：

[source, code, linenums]
----
archetypeGroupId
archetypeArtifactId
archetypeVersion
groupId
artifactId
version
package
EE
----

有关这些参数的描述以及所有可用参数的列表，请参见下表。

== 可用参数

下表列出了可用参数以及说明及其默认值（如果有）。

[%header,cols="34,33,33"]
|===
| {参数{1}}说明 |缺省
| `archetypeGroupId`  |原型的组ID。 |此值必须始终设置为`org.mule.tools.maven`。
| `archetypeArtifactId`  |原型的工件ID。一个|
这个值取决于你是否正在创建一个Mule应用程序，一个Mule域或一个Mule域项目。

* 对于Mule *application*：始终设置为`mule-archetype-project`
* 对于Mule *domain*：始终设置为`maven-archetype-mule-domain`
* 对于Mule *domain project*：始终设置为`maven-archetype-mule-domain-bundle`

| `archetypeVersion`  |原型的版本。随着我们发布原型的新版本，此值可能会发生变化。始终使用最新的非SNAPSHOT版本。 | 
| `groupId`  |您正在创建的应用程序，域或域包的组ID。好的价值是您公司域名的反向名称，例如`com.mycompany.domain`或`org.mycompany.domain`。 | 
| `artifactId`  |您要创建的应用程序，域或域包的工件标识。如果创建域包，请尽量不要将域字包含在工件ID中。 | 
| `version`  |您的应用程序或域包的版本。通常1.0-SNAPSHOT。部署到Mule的域名将为**artifactId-version**。 | `1.0-SNAPSHOT`
| `muleVersion`  |您将要使用的Mule运行时版本。请注意，Mule 2.2.x不再支持 | `3.5.0`
| `transports`  |您要在应用程序中使用的传输的逗号分隔列表。 | `http,jms,vm,file,ftp`
| `modules`  |您将在应用程序中使用的模块的逗号分隔列表。 | `db,xml,jersey,json,ws`
| `EE`  | *Boolean.*导入您正在使用的传输/模块的EE副本。 | `false`
| `domainGroupId`  |应用程序所属域的组ID。 |空
| `domainArtifactId`  |应用程序所属域的工件ID。 |空
| `domainVersion`  |应用程序所属的域的版本。 |空
| `package`  |在创建完整的Mule域名项目时，Maven原型是必需的，但未使用。 | 
|===

== 另请参阅

* 有关使用Maven开发Mule应用程序的更多信息，请参阅 link:/mule-user-guide/v/3.7/using-maven-with-mule[和Mule一起使用Maven]中的概述以及 link:/anypoint-studio/v/5/building-a-mule-application-with-maven-in-studio[在Studio中使用Maven构建一个Mule应用程序]和 link:/mule-user-guide/v/3.7/using-maven-in-mule-esb[在Mule ESB中使用Maven]中的指南。
* 了解如何使用 link:/mule-user-guide/v/3.7/mule-esb-plugin-for-maven[Maven的Mule ESB插件]从Maven环境控制Mule ESB实例
* 了解如何 link:/anypoint-studio/v/5/importing-a-maven-project-into-studio[将现有的Maven项目导入Anypoint Studio]。
* 访问其他Maven link:/mule-user-guide/v/3.7/maven-reference[Maven参考]和 link:/mule-user-guide/v/3.7/configuring-maven-to-work-with-mule-esb[配置Maven以使用Mule ESB]信息。
