=  Mule端点URI
:keywords: anypoint studio, esb, connector, endpoint

Mule端点URI是任何有效的 link:http://java.sun.com/j2se/1.5.0/docs/api/java/net/URI.html[URI]，并描述如何连接到底层传输。 Mule中的大多数连接器都可以从端点URI创建，除非没有足够的连接信息可以在URI中明确表示，例如JMS连接属性。端点URI在 link:/mule-user-guide/v/3.7/endpoint-configuration-reference[Mule端点]上设置，用于管理其他连接实例信息，例如过滤器和事务。

Mule端点URI通常以下列形式之一出现，但其他提供者实现可以引入它们自己的方案。

==== 方案：//主机[：端口] [？PARAMS] // [地址]

该方案必须始终设置。主机和端口是为使用TCP，UDP，HTTP或多播等基于套接字通信的端点设置的。

----
udp://localhost:65432
----

==== 方案：// [用户名] [：密码] @host [：端口] [？PARAMS]

用户名和密码用于登录主机和端口参数指定的远程服务器。 POP3和SMTP连接器使用此格式或URI。

----
pop3://ross:secret@pop3.mycompany.com

smtp://ross:secret@smtp.mycompany.com
----


==== 方案：//地址[PARAMS？]

这里我们只定义一个协议和一个地址。这告诉Mule获取处理指定方案的连接器，或者根据需要创建一个连接器，并使用指定地址创建新端点。

----
vm://my.queue
----

==  URI参数

您可以在URI上设置两种类型的参数：

. 已知Mule参数，用于控制端点的配置方式，例如端点的变换器。
. 要在连接器上设置的属性或与传输关联的属性。这使您可以在此端点使用的连接器上设置属性。此外，所有属性都将与运输相关联，因此您可以混合使用连接器和运输属性。有关更多信息，请参阅 link:/mule-user-guide/v/3.7/endpoint-configuration-reference[端点配置参考]。

=== 已知参数

[%header,cols="2*"]
|===
|属性 |说明
|连接器 |用于此端点URI的现有连接器的名称
|转换器 |定义要在端点上配置的以逗号分隔的转换器列表
|地址 |将端点地址明确设置为指定的值，并忽略URI中的所有其他信息。
|===

例如：

----
file:///C:/temp?transformers=FileToString,XmlToDom

jms://jmsEndpoint/topic:my.topic?connector=WMQConnector
----

=== 其他参数

如果连接器已创建，并且在端点本身上将其设置为属性，则将在连接器上设置URI上设置的任何其他参数。

== 端点编码

使用XML配置时，需要将 link:http://www.w3.org/TR/REC-html40/sgml/entities.html[W3C SGML规范]中定义的某些字符实体转义为其SGML代码。这里列出最相关的。不要忘记删除''之前的空格。''。

对于诸如> <“％＃的字符，该符号将被解析并导致URI的构造函数抛出异常。要使用这些字符中的一个，可以指定％HEXNUMBER

[%header,cols="4*"]
|===
|文本代码 |数字代码 |看起来像 |描述，演员
|％22  |＃34  |“ |引号= APL引用，U + 0022 ISONEW
|＆amp;  |＃38  |＆ |＆号，U + 0026 ISOnum
|％3C  |＃60  | < |小于号，U + 003C ISOnum
|％3E  |＃62  |>  |大于符号，U + 003E ISOnum
|％25  |＃37  |％ |百分号，U + 0023 ISOnum
|％23  |＃35  |＃ |散列符号，U + 0025 ISOnum
|===

此外，对于连接器（如Axis，FTP和电子邮件连接器），如果您的登录凭证包含`@`，则必须使用`%40`将其转义。例如，而不是这些URI：

----
axis:http://wsuser@username:password@localhost/services/services/Version?method=getVersionftp://username:password@ftpserversmtp://'sender@mydomain.com':'123456'@mailserver?address=QA
----

你必须使用这些：

----
axis:http://wsuser%40username:password%40localhost/services/services/Version?method=getVersionftp://username:password%40ftpserversmtp://'sender%40mydomain.com':'123456'%40mailserver?address=QA
----
