= 使用Mule发布和使用API
:keywords: anypoint studio, esb, apis

使用Mule应用程序，您可以发布和使用API​​。根据您使用的是REST还是SOAP，以及您是在公开还是在使用API​​，Mule会提供不同的工具来帮助您的用例。从下面的矩阵中选择，以阅​​读更多关于Mule为每个目标提供的选项。

[NOTE]
本文档仅使用术语“API”，而不是同时使用"API"和"Web service"来引用编写为与其他代码接口的代码。尽管在技术上这些术语在各种情况下都不可互换，但为了保持一致性和清晰度，这些Mule文档仅使用术语"API"。

== 假设

您正在阅读本文档，因为您想要使用Mule发布或使用Web服务或API。本文假定您对API的REST和SOAP体系结构风格都非常熟悉。本文档还假定您熟悉Mule ESB，并且使用Mule可以轻松构建应用程序。阅读 link:/mule-user-guide/v/3.7/mule-fundamentals[骡子基础]以熟悉Mule。

<<Publishing SOAP APIs>>，<<Consuming SOAP APIs>>

<<Publishing REST APIs>>，<<Consuming REST APIs>>

== 发布SOAP API

Mule使用CXF框架为发布SOAP API提供支持，实现 http://incubator.apache.org/cxf/[Apache CXF]。 Apache CXF是一个灵活的开源服务框架，可帮助您使用前端编程API（如JAX-WS）构建Web服务。

您可以在Mule应用程序中使用CXF以使用以下三种方式之一公开SOAP Web服务：

. 使用*proxy service pattern*构建一个WSDL优先API
. 使用*JAX-WS service pattern*构建采用JAXB数据绑定的标准JAX-WS批注的代码优先API
. 使用SOAP组件中的*simple service pattern*从POJO生成一个API

==== 开始使用：

* 使用CXF详细了解 link:/mule-user-guide/v/3.7/publishing-a-soap-api[发布一个SOAP API]

== 使用SOAP API

使用*Web Service Consumer*来使用任何SOAP API。这个新的Anypoint Connector提供了一套简化的功能，用于在Mule应用程序中使用Web服务。使用API​​ WSDL中包含的信息，该连接器使您能够配置一些细节，以便建立从Mule应用程序中使用服务所需的连接。首先，确定Web服务的WSDL文件的位置，然后要求Web服务使用者从WSDL  - 主机，端口，地址配置自身。

==== 开始使用：

* 有关此新连接器的更多信息，请参阅 link:/mule-user-guide/v/3.7/web-service-consumer[Web服务使用者]。
* 有关完整的配置参考，请参阅 link:/mule-user-guide/v/3.7/web-service-consumer-reference[Web服务消费者参考]。

[TIP]
考虑一下，可能已经为您希望连接的API开发了一个连接器。如果是这样，请在Anypoint Exchange中查找并​​将其下载到Studio中。

== 发布REST API

您可以添加到Anypoint Studio实例的工具模块*APIkit*是一个开源的声明性工具包，专门用于实现API优先REST API实现。 APIkit通过自动化流程创建并提供用于快速测试和迭代的嵌入式控制台来强制实施良好的API实施并简化API开发。

APIkit接受RAML（RESTful API Modeling Language）API定义，并生成一个带有HTTP端点的Mule应用程序，异常策略和后端钩子。此外，它还提供一个API控制台，为您的API公开自动生成的完全可测试的文档。

==== 开始使用：

* 按照 link:/apikit/apikit-tutorial[APIkit教程]发布基于RAML的示例API。
* 通过观看视频演示，阅读规范并查看文档，熟悉 link:http://raml.org[肾错构瘤]。

== 使用REST API

有两种使用Mule来使用REST API的方法：

* 配置HTTP连接器向Mule应用程序发送请求，并接受来自API的响应
* 使用Anypoint Connector DevKit构建连接器以对API执行操作

轻量级选项是使用配置了MEL表达式的HTTP连接器将必要的信息传递给您的API。如果存在一个描述您要使用的API的 link:http://raml.org[肾错构瘤]文件，那么您可以在HTTP连接器中简单地引用它，它会在设计时向您公开API的结构，使您不必查找参考资料以了解您需要包含在您的请求中的内容以及这些内容返回的内容。请注意，如果您的API没有RAML文件，则需要了解要调用的API的结构，包括任何身份验证要求，要访问的资源的名称，以及每种资源所支持的方法。

您可能需要考虑为此API编写RAML文件（如果其不存在，并且您计划重复使用该文件）。

在下列情况下，您可能需要考虑为API构建连接器，而不是配置HTTP端点：

* 您将非常频繁地使用此API，并且您不希望每次连接都需要通过HTTP配置连接
* 您需要连接到由任何比HTTPS或基本身份验证更复杂的授权标准保护的REST API

如果其中一个或两个描述了您的用例，请访问 link:/anypoint-connector-devkit/v/3.7[的devkit]文档以了解有关构建连接器的过程的更多信息。

==== 开始使用：

*  link:/mule-user-guide/v/3.7/consuming-a-rest-api[使用REST API]与HTTP
* 使用 link:/anypoint-connector-devkit/v/3.7[Anypoint连接器DevKit]构建连接器

[TIP]
考虑一下，可能已经为您希望连接的API开发了一个连接器。如果是这样，请在Anypoint Exchange中查找并​​将其下载到Studio中。

== 另请参阅

*  https://www.anypoint.mulesoft.com/exchange/?type=connector [探索Anypoint连接器]。
*  https://blogs.mulesoft.com/ [查看MuleSoft博客文章]。
