= 脚本模块参考
:keywords: anypoint studio, component, legacy code, script, java, javascript, python, ruby, groovy, custom code

脚本模块为在Mule中使用脚本语言提供了便利。任何支持 link:http://www.jcp.org/en/jsr/detail?id=223[JSR-223]的脚本语言都可以在Mule中使用。脚本可以用作组件或变换器的实现。此外，脚本可用于表达式评估，这意味着可以使用当前消息的脚本评估来控制消息路由。你甚至可以从脚本配置Mule实例。

== 元器件

定义由符合JSR-223的脚本引擎（如Groovy，JavaScript或Ruby）支持的脚本组件。脚本允许您直接将脚本嵌入到XML配置中，或使用 link:http://docs.spring.io/autorepo/docs/spring-framework/4.1.6.RELEASE/spring-framework-reference/html/dynamic-language.html[Spring的动态语言支持]引用脚本。

*Note*：Mule 3.7和更新的版本使用Spring 4.1.6。

。<component...>的属性
[%header,cols="30a,70a"]
|===
| {名称{1}}说明
| script-ref  |对脚本对象bean的引用，即`<script:script...>`定义。

*Type*：string +
*Required*：否+
*Default*：无
|===

。<component...>的子元素
[%header,cols="30a,20a,50a"]
|===
| {名称{1}}基数 |说明
|脚本 | 0..1  |脚本由符合JSR-223的脚本引擎执行，如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell。
| java-interface-binding  | 0 .. *  |绑定将Mule端点与注入的Java接口相关联（这就像使用Spring注入bean一样，而不是调用一个消息发送给端点的bean上的方法）。脚本绑定仅适用于基于Java的脚本语言。目前还没有验证语言何时支持Java绑定，因为有这么多的脚本语言。
|===

== 配置内联脚本

以下示例演示如何使用内联脚本配置Groovy脚本组件：

[source,xml,linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:script="http://www.mulesoft.org/schema/mule/scripting"
      xmlns:vm="http://www.mulesoft.org/schema/mule/vm"
      xsi:schemaLocation="
       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
       http://www.mulesoft.org/schema/mule/scripting
       http://www.mulesoft.org/schema/mule/scripting/current/mule-scripting.xsd
       http://www.mulesoft.org/schema/mule/vm http://www.mulesoft.org/schema/mule/vm/current/mule-vm.xsd">
 
    <vm:connector name="vmConnector"/>
 
    <script:script name="myScript" engine="groovy">
        return "$payload Received"
    </script:script>
 
    <flow name="inlineScript">
      <vm:inbound-endpoint path="vm:in1"/>
        <script:component>
          <script:script engine="groovy">
            return "$payload Received"
          </script:script>
        </script:component>
      <vm:outbound-endpoint path="out1"/>
    </flow>
</mule>
----

使用绑定的== 消息流

以下示例演示如何使用绑定编排消息流。该示例调用两个不同的流程并将结果传递给出站路由器：

[source,xml,linenums]
----
<flow name="scriptWithBindings">
  <inbound>
    <inbound-endpoint ref="client_request"/>
  </inbound>
  <script:component>
    <script:script engine="groovy">
      msg = CalloutService.doSomething(payload)
      return CalloutService.doSomethingElse(msg)
    <script:java-interface-binding interface="org.mule.components.script.CalloutService" method="doSomething">
      <outbound-endpoint ref="callout_1" synchronous="true"/>
    </script:java-interface-binding>
    <script:java-interface-binding interface="org.mule.components.script.CalloutService" method="doSomethingElse">
      <outbound-endpoint ref="callout_2" synchronous="true"/>
    </script:java-interface-binding>
  </script:component>
  <outbound>
    <pass-through-router>
      <outbound-endpoint ref="client_response"/>
    </pass-through-router>
  </outbound>
</flow>
<flow name="Callout1">
  <inbound>
    <inbound-endpoint ref="callout_1"/>
  </inbound>
  <test:component appendString=" Received by #[mule:context.serviceName]"/>
</flow>
<flow name="Callout2">
  <inbound>
    <inbound-endpoint ref="callout_2"/>
  </inbound>
  <test:component appendString=" Received by #[mule:context.serviceName]"/>
</flow>
----


== 脚本模块

脚本模块为在Mule中使用脚本语言提供了便利。任何支持 link:http://www.jcp.org/en/jsr/detail?id=223[JSR-223]的脚本语言都可以在Mule中使用。脚本可以用作服务组件或变换器的实现。此外，脚本可用于表达式评估，这意味着可以使用当前消息的脚本评估来控制消息路由。你甚至可以从脚本配置Mule实例。

=== 元器件

定义由符合JSR-223的脚本引擎（如Groovy，JavaScript或Ruby）支持的脚本组件。脚本允许您直接将脚本嵌入到XML配置中，或使用 link:http://docs.spring.io/autorepo/docs/spring-framework/4.1.6.RELEASE/spring-framework-reference/html/dynamic-language.html[Spring的动态语言支持]引用脚本。

。<component...>的属性
[%header,cols="30a,70a"]
|===
| {名称{1}}说明
| script-ref  |对脚本对象bean的引用，即`<script:script ...>`定义。

*Type*：string +
*Required*：否+
*Default*：无
|===

。<component...>的子元素
[%header,cols="30a,20a,50a"]
|===
| {名称{1}}基数 |说明
|脚本 | 0..1  |脚本由符合JSR-223的脚本引擎执行，如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell。
| java-interface-binding  | 0 .. *  |绑定将Mule端点与注入的Java接口相关联（这就像使用Spring注入bean一样，而不是调用一个消息发送给端点的bean上的方法）。脚本绑定仅适用于基于Java的脚本语言。目前，由于有这么多的脚本语言，因此语言不支持Java绑定，所以没有验证。
|===

=== 脚本上下文绑定

在Mule中运行时，脚本在脚本上下文中有许多可用的对象。这些是：

[%header,cols="20a,80a"]
|===
| {名称{1}}说明
| log  |可用于写入Mule日志文件的记录器。
| muleContext  |对MuleContext对象的引用。
| eventContext  |对eventcontext的引用。这使您可以从脚本程序中派发事件
|消息 |当前消息。
在任何转换之前| originalPayload  |当前消息的有效载荷。
|有效载荷 |如果在服务上配置了转换器，则转换当前消息的有效载荷。否则，这与_originalPayload_的值相同。
| src  |与_payload_相同，保持向后兼容。
|服务 |对当前服务对象的引用。
| id  |当前事件ID。
|结果 |可以写入脚本结果的占位符对象。通常最好从脚本中返回一个值，除非脚本方法没有返回值。
|===

=== 变压器

运行脚本以对当前消息执行转换。

没有<transformer...>的属性

。<transformer...>的子元素
[%header,cols="30a,20a,50a"]
|===
| {名称{1}}基数 |说明
|脚本 | 0..1  |脚本由符合JSR-223的脚本引擎执行，如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell。
|===

=== 过滤

运行脚本以对当前消息执行过滤。

没有<filter...>的属性

。<filter...>的子元素
[%header,cols="30a,20a,50a"]
|===
| {名称{1}}基数 |说明
|脚本 | 0..1  |脚本由符合JSR-223的脚本引擎执行，如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell。
|===

=== 脚本

表示可用作服务或变换器组件的脚本。脚本文本可以从脚本文件中提取，也可以嵌入到此元素中。脚本可以通过任何符合JSR-223的脚本引擎执行，例如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell。

。<script...>的属性
[%header,cols="20a,80a"]
|===
| {名称{1}}说明
|名称 |用于标识此脚本对象的名称。当你想从一个组件或变换器引用这个脚本对象时使用它。

*Type*：string +
*Required*：否+
*Default*：无
|引擎 |正在使用的脚本引擎的名称。所有支持JSR-223的脚本语言都有一个脚本引擎名称，例如groovy，ruby，python等。如果未设置此值，但配置了脚本文件，则Mule会尝试根据脚本文件加载正确的脚本引擎延期。

*Type*：string +
*Required*：否+
*Default*：无
|文件 |为此对象加载的脚本文件。该文件可以位于类路径或本地文件系统上。

*Type*：string +
*Required*：否+
*Default*：无
|===

。<script...>的子元素
[%header,cols="30a,20a,50a"]
|===
| {名称{1}}基数 |说明
| text  | 0..1  |用于在XML中嵌入脚本代码。这对简单的脚本来说很有用，因为你只是在嘲笑一个快速应用程序。
|===

===  Groovy可刷新

组件对象的包装器，允许在运行时重新加载底层对象。这使得可以在不重新启动的情况下热部署新的组件逻辑。

。<groovy-refreshable...>的属性
[%header,cols="30a,70a"]
|===
| {名称{1}}说明
| name  |这个可刷新的groovy bean包装的名称。

*Type*：string +
*Required*：是+
*Default*：无
| refreshableBean-ref  |对此组件使用的`groovy.lang.Groovy`对象的引用。

*Type*：string +
*Required*：否+
*Default*：无
| methodName  |在接收到对象的消息时调用的入口点方法。

*Type*：string +
*Required*：否+
*Default*：无
|===

无<groovy-refreshable...>的子元素


=== 郎

该元素允许嵌入 link:http://www.springframework.org/schema/lang[春天朗]名称空间。在这个元素中，开发人员可以包含Spring `lang`命名空间。

没有<lang...>的属性

无<lang...>的子元素


=== 脚本配置生成器 - 已弃用

（已弃用，将从Mule 4.0中删除）

link:http://www.mulesoft.org/docs/site/3.7.0/apidocs/org/mule/module/scripting/builders/ScriptConfigurationBuilder.html[ScriptConfigurationBuilder]允许开发人员从符合JSR-223的脚本创建Mule实例。从Groovy加载管理器：

[source,java,linenums]
----
ConfigurationBuilder builder = new ScriptConfigurationBuilder("groovy", "../conf/mule-config.groovy");
MuleContext muleContext = new DefaultMuleContextFactory().createMuleContext(builder);
----

或者从命令行启动服务器：

[source,code,linenums]
----
mule -M-Dorg.mule.script.engine=groovy
-builder org.mule.module.scripting.builders.ScriptConfigurationBuilder
-config ../conf/mule-config.groovy
----

=== 脚本上下文绑定

在Mule中运行时，脚本在脚本上下文中有许多可用的对象：

[%header,cols="20a,80a"]
|===
| {名称{1}}说明
| `id`  |当前消息ID。
| `log`  |可用于写入Mule日志文件的记录器。
| `message`  |当前消息。
| `muleContext`  |对MuleContext对象的引用。
| `originalPayload`  |在进行任何转换之前，当前消息的有效载荷。
| `payload`  |如果在流上配置了变换器，则转换当前消息的有效载荷。否则，这与`originalPayload`的值相同。
| `result` a |
可以写入脚本结果的占位符对象。通常最好从脚本中返回一个值，除非脚本方法没有返回值。

[WARNING]
如果您的脚本需要返回null，则必须设置result = null，而不是简单地返回null。

| `service`  |对当前服务的引用。
|消息属性 |任何消息属性都可以用作脚本的变量。
|===

=== 脚本配置生成器

[NOTE]
已弃用，将在Mule 4.0中删除。

link:http://www.mulesoft.org/docs/site/3.7.0/apidocs/org/mule/module/scripting/builders/ScriptConfigurationBuilder.html[ScriptConfigurationBuilder]允许您从符合JSR-223的脚本创建Mule实例。

从Groovy加载管理器：

[source,java,linenums]
----
ConfigurationBuilder builder = new ScriptConfigurationBuilder("groovy", "../conf/mule-config.groovy"); 
MuleContext muleContext = new DefaultMuleContextFactory().createMuleContext(builder);
----

或者从命令行启动服务器：

[source]
----
mule -M-Dorg.mule.script.engine=groovy -builder org.mule.module.scripting.builders.ScriptConfigurationBuilder -config ../conf/mule-config.groovy 
----

==== 变压器

运行脚本以对当前消息执行转换。

没有<transformer...>的属性

。<transformer...>的子元素
[%header,cols="30a,20a,50a"]
|===
| {名称{1}}基数 |说明
|脚本 | 0..1  |脚本由符合JSR-223的脚本引擎执行，如Groovy，JavaScript（Rhino），Python，Ruby或Beanshell。
|===

以Groovy为例，以下变换器配置将逗号分隔的一串值转换为`java.util.List`。

[source,xml,linenums]
----
<script:transformer name="stringReplaceWithParams">
        <script:script engine="groovy">
            <property key="oldStr" value="l"/>
            <property key="newStr" value="x"/>
            <script:text>
                return payload.toString().replaceAll("$oldStr", "$newStr")
            </script:text>
        </script:script>
    </script:transformer>
----

====  Groovy可刷新

组件对象的包装器，允许在运行时重新加载底层对象。这使得可以在不重新启动的情况下热部署新的组件逻辑。

。<groovy-refreshable...>的属性
[%header,cols="30a,70a"]
|===
| {名称{1}}说明
| name  |这个可刷新的groovy bean包装的名称。

*Type*：string +
*Required*：是+
*Default*：无
| refreshableBean-ref  |对此组件使用的`groovy.lang.Groovy`对象的引用。

*Type*：string +
*Required*：否+
*Default*：无
| methodName  |在接收到对象的消息时调用的入口点方法。

*Type*：string +
*Required*：否+
*Default*：无
|===

无<groovy-refreshable...>的子元素


==== 郎

该元素允许嵌入 link:http://www.springframework.org/schema/lang[春天朗]名称空间。在这个元素中，开发人员可以包含Spring `lang`命名空间。

没有<lang...>的属性

无<lang...>的子元素

