=  Servlet传输参考
:keywords: anypoint studio, connector, endpoint, sap

Servlet传输提供了与servlet实现的集成。实现Servlet负责接收请求，然后Servlet传输将请求转交给任何注册的接收方。这个连接器没有调度器的概念，因为它是由请求触发的，可能会或可能不会返回响应。您将servlet URL指定为连接器配置的一部分，然后像任何其他 link:/mule-user-guide/v/3.7/file-transport-reference[FTP端点]一样指定端点。

== 访问Servlet端点

您可以在Web应用程序中定义一个servlet，将来自客户端的请求连接到Mule servlet端点。

例如在web.xml中：

[source, xml, linenums]
----
<servlet>
<servlet-name>muleServlet</servlet-name>
<servlet-class>org.mule.transport.servlet.MuleReceiverServlet</servlet-class>
<load-on-startup>1</load-on-startup>
</servlet>
 
<servlet-mapping>
<servlet-name>muleServlet</servlet-name>
<url-pattern>/services/*</url-pattern>
</servlet-mapping>
----

使用具有以下模式的URL访问Servlet端点：+
`http://host:port/webapp-contextname/servlet-mapping-URL/path`

哪里：

*  _ host_和_port_  - 您访问应用程序服务器的URL和端口
*  _ webapp-contextname_  - 部署Mule ESB的Web应用程序的上下文名称
*  _ servlet-name _-在web.xml中定义的Mule servlet URL
*  _ path_  - 端点中的路径属性

== 的Javadoc

该运输的Javadoc是：

http://www.mulesoft.org/docs/site/3.7.0/apidocs/org/mule/transport/servlet/ServletConnector.html[Mule Servlet运输Javadoc]

http://www.mulesoft.org/docs/site/current3/schemadocs/namespaces/http_www_mulesoft_org_schema_mule_servlet/namespace-overview.html[架构描述]

有关在servlet容器中使用Mule的更多信息，请参阅 link:/mule-user-guide/v/3.7/embedding-mule-in-a-java-application-or-webapp[将Mule嵌入到Java应用程序或Web应用程序中]。

== 参考

=== 连接器

Servlet连接器是Mule和servlet引擎之间的通道适配器。它允许MuleReceiverServlet查找对通过servlet容器接收到的请求感兴趣的组件。

。<connector...>的属性

[%header,cols="30a,70a"]
|===
| {名称{1}}说明
| servletUrl  | servlet容器绑定的真实URL。如果没有设置，当使用绑定到servlet端点的CXF时，可能无法正确生成WSDL。

*Type*：string +
*Required*：否+
*Default*：无
| useCachedHttpServletRequest  |是否使用缓存的http servlet请求。

*Type*：布尔+
*Required*：否+
*Default*：false
|===

无<connector...>的子元素

例如：

[source, xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:spring="http://www.springframework.org/schema/beans"
       xmlns:servlet="http://www.mulesoft.org/schema/mule/servlet"
    xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.6/mule.xsd
       http://www.mulesoft.org/schema/mule/servlet
       http://www.mulesoft.org/schema/mule/servlet/current/mule-servlet.xsd">
 
    <servlet:connector name="servletConnector" servletUrl="http://localhost:8888" />
...
----

您还可以将servlet URL指定为端点的一部分：

[source, xml]
----
<servlet:inbound-endpoint path="http://localhost:8888" />
----

Servlet端点接受与HTTP端点相同的属性和子元素。有关更多信息，请参阅 link:/mule-user-guide/v/3.7/file-transport-reference[FTP传输参考]。

=== 端点

。<endpoint...>的属性
[%header,cols="30a,70a"]
|===
| {名称{1}}说明
|路径 |将服务绑定到的servlet路径。

*Type*：string +
*Required*：是+
*Default*：无
|===

无<endpoint...>的子元素

==  Servlet传输

Servlet传输允许Mule组件监听通过servlet请求接收到的事件。

=== 连接器

Servlet连接器是Mule和servlet引擎之间的通道适配器。它允许MuleReceiverServlet查找对通过servlet容器接收到的请求感兴趣的组件。

。<connector...>的属性
[%header,cols="30a,70a"]
|===
| {名称{1}}说明
| servletUrl  | servlet容器绑定的真实URL。如果没有设置，当使用绑定到servlet端点的CXF时，可能无法正确生成WSDL。


*Type*：string +
*Required*：否+
*Default*：无
| useCachedHttpServletRequest  |是否使用缓存的http servlet请求。

*Type*：布尔+
*Required*：否+
*Default*：false
|===

无<connector...>的子元素


=== 入站端点

。<inbound-endpoint...>的属性
[%header,cols="30a,70a"]
|===
| {名称{1}}说明
|路径 |将服务绑定到的servlet路径。

*Type*：string +
*Required*：是+
*Default*：无
|===

无<inbound-endpoint...>的子元素


=== 端点

。<endpoint...>的属性
[%header,cols="30a,70a"]
|===
| {名称{1}}说明
|路径 |将服务绑定到的servlet路径。

*Type*：string +
*Required*：是+
*Default*：无
|===

无<endpoint...>的子元素

== 变压器

这些是这种运输特有的变压器。请注意，这些会在启动时自动添加到Mule注册表中。当进行自动转换时，这些将在搜索正确的变压器时包含在内。

[%header,cols="2*"]
|====
| {名称{1}}说明
| http-request-to-parameter-map  | <http-request-to-parameter-map>转换器返回通过HTTP请求发送的参数的简单地图。如果多次给定相同的参数，则只有第一个值会在Map中。
| http-request-to-input-stream  | <http-request-to-input-stream>转换器将HttpServletRequest转换为InputStream。
| HTTP请求到字节数组 | <http-request-to-byte-array>转换器通过提取请求的有效负载将HttpServletRequest转换为字节数组。
|====

