=  SMTP传输参考
:keywords: email, transport, smtp

SMTP传输可用于使用`javax.mail` API通过SMTP发送邮件。该实现支持CC / BCC / ReplyTo地址，附件和自定义标题属性。它还为`javax.mail.Message`转换提供支持。 SMTPS连接器使用`javax.mail` API启用基于SSL的SMTP。它支持SMTP传输的所有元素和属性，以及为SSL连接设置客户端密钥存储和信任存储的一些必需属性。

TLS / SSL连接代表实体进行，实体可以是匿名的或由证书标识。 _key store_提供识别建立连接的实体所需的证书和相关私钥。此外，连接到可信系统。受信任系统的公用证书存储在_trust store_中，用于验证与远程系统建立的连接是否与期望的身份匹配。

== 命名空间和语法

XML名称空间：

[source, xml, linenums]
----
xmlns:smtp="http://www.mulesoft.org/schema/mule/smtp"
xmlns:smtps="http://www.mulesoft.org/schema/mule/smtps"
----

XML架构位置：

[source, xml, linenums]
----
http://www.mulesoft.org/schema/mule/smtp http://www.mulesoft.org/schema/mule/smtp/current/mule-smtp.xsd
http://www.mulesoft.org/schema/mule/smtps http://www.mulesoft.org/schema/mule/smtps/current/mule-smtps.xsd
----

连接器语法：

[source,xml, linenums]
----
<smtp:connector name="smtpConnector" bccAddresses="abc@example.com" ccAddresses="bcd@example.com" contentType="foo/bar"
fromAddress="cde@example.com" replyToAddresses="def@example.com"
subject="subject">
  <smtp:header key="foo" value="bar" />
  <smtp:header key="baz" value="boz" />
</smtp:connector>
 
<smtps:connector name="smtpsConnector" bccAddresses="abc@example.com" ccAddresses="bcd@example.com" contentType="foo/bar"
fromAddress="cde@example.com" replyToAddresses="def@example.com"
subject="subject">
  <smtps:header key="foo" value="bar" />
  <smtps:header key="baz" value="boz" />
  <smtps:tls-client path="clientKeystore" storePassword="mulepassword" />
  <smtps:tls-trust-store path="greenmail-truststore" storePassword="password" />
</smtps:connector>
 
<smtp:gmail-connector name="smtpGmailConnector"  bccAddresses="abc@example.com" ccAddresses="bcd@example.com" contentType="foo/bar"
fromAddress="cde@example.com" replyToAddresses="def@example.com"
subject="subject">
  <smtp:header key="foo" value="bar" />
  <smtp:header key="baz" value="boz" />
</smtp:gmail-connector>
----

端点语法：+
 您可以通过两种不同的方式来定义您的端点：

. 前缀端点：
+
[source,xml, linenums]
----
<smtp:outbound-endpoint host="localhost" port="65437" from="steve@mycompany.com"
                            to="bob@example.com" subject="Please verify your account details"/>
<smtps:outbound-endpoint host="localhost" port="65437" from="steve@mycompany.com"
                            to="bob@example.com" subject="Please verify your account details"/>
----

. 没有前缀的URI：
+
[source, code, linenums]
----
smtp://muletestbox:123456@smtp.mail.yahoo.co.uk?address=dave@mycompany.com
smtps://muletestbox:123456@smtp.mail.yahoo.co.uk?address=dave@mycompany.com
----

有关更多信息，请参阅下面的部分。

== 特点

* 在出站端点上配置电子邮件访问很简单
* 轻松配置TLS安全+


== 用法

如果您想在您的配置中包含SMTP电子邮件传输，那么这些是您需要定义的命名空间：

[source, code, linenums]
---- <?xml version="1.0" encoding="UTF-8"?>
<mule xmlns = "http://www.mulesoft.org/schema/mule/core"
       的xmlns：的xsi = "http://www.w3.org/2001/XMLSchema-instance"
       的xmlns：弹簧= "http://www.springframework.org/schema/beans"
       的xmlns：SMTP = "http://www.mulesoft.org/schema/mule/smtp"
       的xsi：的schemaLocation =”
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
        http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/smtp http://www.mulesoft.org/schema/mule/smtp/current/mule-smtp.xsd“>
...
----

Secure version:

[source,xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns = "http://www.mulesoft.org/schema/mule/core"
       的xmlns：的xsi = "http://www.w3.org/2001/XMLSchema-instance"
       的xmlns：弹簧= "http://www.springframework.org/schema/beans"
       的xmlns：SMTPS = "http://www.mulesoft.org/schema/mule/smtps"
       的xsi：的schemaLocation =”
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
        http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/smtps http://www.mulesoft.org/schema/mule/smtps/current/mule-smtps.xsd“>
----

Then you need to configure your connector and endpoints as described below.

=== Configuration Example

Say your CFO wants an email notification of all processed orders. The following configuration will pick up any files in the 'processed' directory, convert them to a string, and send it as the email body to the CFO.

[source,xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns = "http://www.mulesoft.org/schema/mule/core"
       的xmlns：的xsi = "http://www.w3.org/2001/XMLSchema-instance"
       的xmlns：弹簧= "http://www.springframework.org/schema/beans"
       的xmlns：SMTPS = "http://www.mulesoft.org/schema/mule/smtps"
       的xmlns：VM = "http://www.mulesoft.org/schema/mule/vm"
       的xmlns：文件= "http://www.mulesoft.org/schema/mule/file"
       的xmlns：电子邮件= "http://www.mulesoft.org/schema/mule/email"
       的xsi：的schemaLocation =”
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
        http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
        http://www.mulesoft.org/schema/mule/smtps http://www.mulesoft.org/schema/mule/smtps/current/mule-smtps.xsd
        http://www.mulesoft.org/schema/mule/email http://www.mulesoft.org/schema/mule/email/current/mule-email.xsd
        http://www.mulesoft.org/schema/mule/vm http://www.mulesoft.org/schema/mule/vm/current/mule-vm.xsd“>
 
     <smtp:connector name="smtpConnector"  />
     
     <flow name="processed-orders">
         <file:inbound-endpoint path="/tmp/processed">❶
             <file:file-to-string-transformer/>❷
         </file:inbound-endpoint>
         <smtps:outbound-endpoint host="smtpsServer" port="25" from="bob" subject="processed order" to="cfo@example.com">❸
             <email:string-to-email-transformer/>❹
         </smtps:outbound-endpoint>
     </flow>
</mule>
----

This configuration defines a inbound file endpoint which looks in the '/tmp/processed' directory (❶) and converts any files found to a string (❷). An outbound smtp server is defined on ❸. A string-to-email-transformer (❹) will convert the string to email format before the email is sent. The string-to-email-transformer will set the current string payload of the message as the email body.

Secure version:

[source,xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns = "http://www.mulesoft.org/schema/mule/core"
       的xmlns：的xsi = "http://www.w3.org/2001/XMLSchema-instance"
       的xmlns：弹簧= "http://www.springframework.org/schema/beans"
       的xmlns：SMTPS = "http://www.mulesoft.org/schema/mule/smtps"
       的xmlns：VM = "http://www.mulesoft.org/schema/mule/vm"
       的xmlns：文件= "http://www.mulesoft.org/schema/mule/file"
       的xmlns：电子邮件= "http://www.mulesoft.org/schema/mule/email"
       的xsi：的schemaLocation =”
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
        http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
        http://www.mulesoft.org/schema/mule/smtps http://www.mulesoft.org/schema/mule/smtps/current/mule-smtps.xsd
        http://www.mulesoft.org/schema/mule/email http://www.mulesoft.org/schema/mule/email/current/mule-email.xsd
        http://www.mulesoft.org/schema/mule/vm http://www.mulesoft.org/schema/mule/vm/current/mule-vm.xsd“>
 
     <smtps:connector name="smtpsConnector">❶
         <smtps:tls-client path="clientKeystore" storePassword="mulepassword" />
         <smtps:tls-trust-store path="greenmail-truststore" storePassword="password" />
     </smtps:connector>
     
     <flow name="processed-orders">
         <file:inbound-endpoint path="/tmp/processed">❷
             <file:file-to-string-transformer/>❸
         </file:inbound-endpoint>
         <smtps:outbound-endpoint host="smtpsServer" port="25" from="bob" subject="processed order" to="cfo@example.com">❹
             <email:string-to-email-transformer/>❺
         </smtps:outbound-endpoint>
     </flow>
</mule>
----

The smtps connector has a TLS client and server keystore information as defined on ❶. An inbound file endpoint looks in the '/tmp/processed' directory (❷) and converts any files found to a string (❸). An outbound smtp server is defined on ❹. A string-to-email-transformer (❺) will convert the string to email format before the email is sent. The string-to-email-transformer will set the current string payload of the message as the email body.

== Configuration Reference

=== Connectors

The SMTP connector supports all the link:/mule-user-guide/v/3.7/configuring-a-transport[common connector attributes and properties] and the following optional elements and attributes:

[%header,cols="4*"]
|===
|Attribute |Description |Default |Required
|bccAddresses |Comma separated list of addresses for blind copies. |  |False
|ccAddresses |Comma separated list of addresses for copies. |  |False
|contentType |Mime type for the outgoing message. |  |False
|fromAddress |The from address for the outgoing message. |  |False
|replyToAddresses |The reply-to address for the outgoing message. |  |False
|subject |The default subject for the outgoing message if none is set in the message. |  |False
|===

[%header,cols="2*"]
|===
|Element |Description
|header |Additional header name and value, added to the message.
|===

For the secure version, the following elements are also required:

[%header,cols="2*"]
|===
|Element |Description
|tls-client a|
Configures the client key store with the following attributes:

* path: The location (which will be resolved relative to the current classpath and file system, if possible) of the keystore that contains public certificates and private keys for identification
* storePassword: The password used to protect the keystore
* class: The type of keystore used (a Java class name)

|tls-trust-store a|
Configures the trust store. The attributes are:

* path: The location (which will be resolved relative to the current classpath and file system, if possible) of the trust store that contains public certificates of trusted servers
* storePassword: The password used to protect the trust store

|===

For example:

[source,xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns = "http://www.mulesoft.org/schema/mule/core"
       的xmlns：的xsi = "http://www.w3.org/2001/XMLSchema-instance"
       的xmlns：弹簧= "http://www.springframework.org/schema/beans"
       的xmlns：SMTP = "http://www.mulesoft.org/schema/mule/smtp"
       的xsi：的schemaLocation =”
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
        http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/smtp http://www.mulesoft.org/schema/mule/smtp/current/mule-smtp.xsd“>
...
<smtp：连接器名称= "smtpConnector" bccAddresses = "abc@example.com" ccAddresses = "bcd@example.com" contentType = "foo/bar"
fromAddress = "cde@example.com" replyToAddresses = "def@example.com"
受试者= "subject">
   <smtp:header key="foo" value="bar" />
   <smtp:header key="baz" value="boz" />
</smtp:connector>
----

Secure version:

[source,xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns：smtps = "http://www.mulesoft.org/schema/mule/smtps" xmlns：vm = "http://www.mulesoft.org/schema/mule/vm" xmlns：jms = "http://www.mulesoft.org/schema/mule/jms" xmlns = "http://www.mulesoft.org/schema/mule/core" xmlns：doc = "http://www.mulesoft.org/schema/mule/documentation" xmlns：spring = { {5}} version = "CE-3.3.0" xmlns：xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi：schemaLocation =“
http://www.mulesoft.org/schema/mule/vm http://www.mulesoft.org/schema/mule/vm/current/mule-vm.xsd
http://www.mulesoft.org/schema/mule/smtps http://www.mulesoft.org/schema/mule/smtps/current/mule-smtps.xsd
http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/jms http://www.mulesoft.org/schema/mule/jms/current/mule-jms.xsd“>
     <smtps:connector name="SMTP" validateConnections="true">
         <smtps:tls-client path="clientKeystore" storePassword="mulepassword"/>
         <smtps:tls-trust-store path="greenmail-truststore" storePassword="password"/>
     </smtps:connector>

     <flow name="relay">
         <vm:inbound-endpoint exchange-pattern="one-way" path="send"/>
         <smtps:outbound-endpoint host="localhost" port="65439" to="bob@example.com" responseTimeout="10000" connector-ref="SMTP"/>
     </flow>
</mule>
----

The gmail-connector connector supports all of the above.

For example:

[source,xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns = "http://www.mulesoft.org/schema/mule/core"
       的xmlns：的xsi = "http://www.w3.org/2001/XMLSchema-instance"
       的xmlns：弹簧= "http://www.springframework.org/schema/beans"
       的xmlns：SMTP = "http://www.mulesoft.org/schema/mule/smtp"
       的xsi：的schemaLocation =”
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
        http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/smtp http://www.mulesoft.org/schema/mule/smtp/current/mule-smtp.xsd“>
...
<smtp：gmail-connector name = "smtpGmailConnector" bccAddresses = "abc@example.com" ccAddresses = "bcd@example.com" contentType = "foo/bar"
fromAddress = "cde@example.com" replyToAddresses = "def@example.com"
受试者= "subject">
   <smtp:header key="foo" value="bar" />
   <smtp:header key="baz" value="boz" />
</smtp:gmail-connector>
----

=== Endpoints

SMTP endpoints describe details about the SMTP server and the recipients of messages sent from the SMTP endpoint. You link:/mule-user-guide/v/3.7/endpoint-configuration-reference[configure the endpoints] just as you would with any other transport, with the following additional attributes:

[%header,cols="2*"]
|==============
|Attribute |Description
|user |The user name of the mailbox owner
|password |The password of the user
|host |The IP address of the SMTP server, such as www.mulesoft.com, localhost, or 127.0.0.1
|port |The port number of the SMTP server
|to |The destination for the email. You can provide multiple addresses separated by commas.
|from |The address of the sender of the email
|subject |The email subject
|cc |A comma-separated list of email addresses to copy on this email
|bcc |A comma-separated list of email addresses to blind-copy on this email
|replyTo |The address used by default if someone replies to the email
|==============

For example:

[source,xml, linenums]
----
<outbound>
   <pass-through-router>
     <smtp：outbound-endpoint host = "localhost" port = "65437" from = "steve@mycompany.com"
                             to = "bob@example.com" subject = "Please verify your account details" />
   </pass-through-router>
</outbound>
----

Secure version:

[source,xml, linenums]
----
<outbound>
   <pass-through-router>
     <smtps：outbound-endpoint host = "localhost" port = "65437" from = "steve@mycompany.com"
                             to = "bob@example.com" subject = "Please verify your account details" />
   </pass-through-router>
</outbound>
----

You can also define the endpoints using a URI syntax:

[source,xml, linenums]
----
<outbound-endpoint address="smtp://muletestbox:123456@smtp.mail.yahoo.co.uk?address=dave@mycompany.com"/>
<outbound-endpoint address="smtps://muletestbox:123456@smtp.mail.yahoo.co.uk?address=dave@mycompany.com"/>
----

This will send mail using `smtp.mail.yahoo.co.uk` (using the default SMTP port) to the address `dave@mycompany.com`. The SMTP request is authenticated using the username `muletestbox` and the password `123456`.

For more information about transformers, see the link:/mule-user-guide/v/3.7/email-transport-reference[Transformers] section in the Email Transport Reference.

For more information about filters, see the link:/mule-user-guide/v/3.7/email-transport-reference[Filters] section in the Email Transport Reference.

== Exchange Patterns / Features of the Transport

See the link:/mule-user-guide/v/3.7/transports-reference[transport matrix].

== Schema Reference

You can view the full schema for the SMTP email transport http://www.mulesoft.org/docs/site/current3/schemadocs/namespaces/http_www_mulesoft_org_schema_mule_smtp/namespace-overview.html[here]. The secure version is http://www.mulesoft.org/docs/site/current3/schemadocs/namespaces/http_www_mulesoft_org_schema_mule_smtps/namespace-overview.html[here].

== Maven Module

The email transports are implemented by the mule-transport-email module. You can find the source for the email transport under transports/email.

If you are using Maven to build your application, use the following dependency snippet to include the email transport in your project:

[source,xml, linenums]
----
<dependency>
   <groupId> org.mule.transports </groupId>
   <artifactId>骡传输的电子邮件</artifactId>
</dependency>
----

== Limitations

For more information about the limitations, see the link:/mule-user-guide/v/3.7/email-transport-reference[Limitations] section in the Email Transport Reference.

So far, all configuration has been static, in that you define all the information in the configuration of the endpoint. However, you can set the connector properties to control the settings of the outgoing message. These properties will override the endpoint properties. If you always want to set the email address dynamically, you can leave out the `to` attribute (or the `address` parameter if you're using URIs) on the SMTP endpoint.
