= 从TLS 1.0迁移
:keywords: tls, trust, store, https, ssl, secure messages, encryption, trust store, key store, keystore, truststore

由于PCL合规性不再接受TLS 1.0，并且考虑到此协议版本的重大漏洞，我们强烈建议您迁移到TLS v1.1和更高版本。

自Studio 5.4.3以来，您可以编辑Studio和API网关运行时的TLS配置文件。

== 从Studio编辑运行时的TLS配置文件

从Studio安装文件夹中，导航到`plugins`目录。在那里，您需要找到服务器运行时和Studio版本的文件夹。 +
文件夹的名称应该遵循以下形式：

[source]
----
org.mule.tooling.server.3.7.3.ee_5.4.x.yyy.mm.dd
----

在其中，转至`mule` / `conf`目录并打开`tls-default.conf`文件以编辑您的TLS配置。 +
您可以在`enabledProtocols`字段中找到启用的配置协议。

如果需要，您还可以在与您的站点的安全策略对应的enabledCipherSuites中注释或取消注释行。

== 从Studio中编辑您的API网关的TLS配置文件

从Studio安装文件夹中，导航到`plugins`目录。在那里，您需要找到服务器的API Gateway和Studio版本的文件夹。 +
文件夹的名称应该遵循以下形式：

[source]
----
org.mule.tooling.apigateway.x.x.x_x.x.x.yyyymmdd
----

在其中，转至`mule` / `conf`目录并打开`tls-default.conf`文件以编辑您的TLS配置。 +
您可以在`enabledProtocols`字段中找到启用的配置协议。

如果需要，您还可以在与您的站点的安全策略对应的enabledCipherSuites中注释或取消注释行。

[NOTE]
--
API网关2.1.1,2.0.4和2.2.0版本的TLS 1.0默认支持*disabled*。 +
您可以选择通过将`TLSv1`添加到`tls-default.conf`文件的`enabledProtocols`字段来手动重新启用它。

API网关版本1.3.2,2.0.3和2.1.0默认情况下仍启用TLS 1.0。
--

== 另请参阅

* 详细了解维基百科中的 link:http://en.wikipedia.org/wiki/Transport_Layer_Security[TLS]
* 了解如何配置 link:/mule-user-guide/v/3.8/http-connector[HTTP连接器]
* 了解如何处理 link:/mule-user-guide/v/3.8/tls-configuration#global-tls-configuration[全局TLS配置]
