= 在Spring中使用Mule
:keywords: anypoint studio, studio, mule, spring

Mule利用Spring框架开发Java应用程序。中号

== 支持的Spring版本

*  Mule 3.8：Spring 4.1.9和Spring Security 4.0.4
*  Mule 3.7.5：Spring 4.1.9和Spring Security 4.0.4
*  Mule 3.7.0  -  3.7.4：Spring 4.1.6和Spring Security 4.0.1
*  Mule 3.6及更早版本：Spring 3.2和Spring Security 3.0

另请参阅： link:http://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-xml.html[Spring Security迁移3到4]

==  Mule App XML配置文件

link:/mule-user-guide/v/3.8/about-the-xml-configuration-file[关于XML配置文件]

配置Mule最常用的方法是使用自定义Mule命名空间的Spring XML文件。

在你的弹簧框架模式中使用Mule中的两个命名空间之一：

*  `+http://www.springframework.org/schema/beans+` `+http://www.springframework.org/schema/beans/spring-beans-current.xsd+`
*  `+http://www.springframework.org/schema/beans+` `+http://www.springframework.org/schema/beans/spring-beans-current.xsd+`

==  Spring应用程序上下文

[TIP]
查看 link:/mule-user-guide/v/3.8/spring-application-contexts[Spring应用程序上下文]

Mule为您的应用程序创建和管理Spring应用程序上下文提供了多种选择。

* 单个应用程序上下文
* 多个应用程序上下文
* 现有的应用程序上下文
* 现有应用程序上下文作为父项

link:/mule-user-guide/v/3.8/using-spring-beans-as-flow-components[使用Spring Beans作为流程组件]

构建Spring bean来定义Mule应用程序可以引用的组件行为。

==  Spring Bean定义配置文件

Mule的配置文件利用了Spring 4.1创建*bean definition profiles*的能力。您可以使用Spring bean定义配置文件为不同的目标环境注册不同的bean，而不是在所有目标环境中使用一个bean。有关bean定义配置文件的更多信息，请参阅 link:http://docs.spring.io/spring/docs/4.1.6.RELEASE/spring-framework-reference/htmlsingle/[Spring的博客发布]。

