= 关于防火墙访问
:keywords: firewall, mixed content, cors, proxy, same-origin, anypoint, api console, api designer, api notebook

以下Anypoint Platform浏览器工具默认通过_reverse proxy_将呼叫路由到您的API：

*  API控制台
*  API设计器
*  API Notebook

然后，浏览器可以从您的API和Anypoint Platform浏览器工具获取资源，这些工具不受同源限制策略的影响。

当浏览器向域发送HTTP请求并且该域返回页面时，该页面就是_origin域_。在该页面中运行的任何脚本都只允许向原始域发出附加请求。如果脚本尝试向另一个域请求或加载资源，通常会阻止该响应，以防止脚本访问您访问的其他站点。

如果您的API位于阻止入站请求的防火墙之后，则该API无法访问。除非您使用Anypoint Platform跨源资源共享（CORS）策略来允许用户和/或客户端请求访问其资源位于您的外部的工具，否则您将无法使用API​​控制台，API Designer或API Notebook起源域。

或者，出于测试目的，您可以使用以下方法之一来避免同源限制：

* 绕过代理
* 在浏览器中禁用同源限制。

如果没有正确处理安全模型以处理跨源资源，将API发布到生产环境可能会导致危险的跨站点请求伪造（CSRF）攻击，以及可能损害客户端和用户访问资源的其他威胁。

如果您设置了API代理，则需要为您的浏览器实施并应用CORS策略，以便能够将防火墙后面的API和Anypoint Platform的浏览器工具中的资源加载到该API中。

如果您要在本地或测试环境中测试您的实施，则可以禁用浏览器中的同源限制以访问Anypoint Platform提供的在线浏览器工具。

不要在您的浏览器中使用禁用相同来源限制来实施您的实施版本。

== 禁用混合内容禁止

当HTTPS网页从不安全的HTTP端点检索资源时，安全和不安全内容的结果混合称为_mixed content_。由于安全隐患，浏览器会阻止这种混合内容并显示错误。例如，混合内容引入了中间人攻击者可能在请求和响应期间注入恶意站点资源（例如脚本）的可能性。使用API​​ Manager时可能会遇到此问题，了解如何减轻此问题非常重要。

API Manager浏览器工具（API Console，API Designer和AP​​I Notebook）托管在HTTPS端点上。您的浏览器和平台服务器之间发送的所有请求和响应均使用SSL进行加密。另外，如果您使用由工具生成的默认服务器端代理而不是绕过代理，代理会向您的API发出请求并通过SSL加密响应，以便它们可以在浏览器中显示，而不会触发混合内容错误。

如果您禁用了平台的服务器端代理，那么您的API的任何请求都不再通过此代理进行路由，而是直接发送给它。如果您的API驻留在HTTPS端点，则这种情况不会成为问题，因为浏览器和请求的资源之间的所有通信均使用SSL进行加密。但是，如果您的API具有HTTP端点，则API Manager浏览器工具向不安全的HTTP端点发出请求，并且您的浏览器会阻止产生的"mixed content"  - 浏览器工具的HTTPS（安全）内容与您的API的HTTP （无担保）的内容。

== 另请参阅

*  link:/api-manager/v/1.x/cors-policy[应用CORS策略]

