= 关于OAuth 2.0
：meta-audience：开发者
：元作业阶段：实施
：元的工作：
：meta-exp-level：Expert
：元功能：oauth
：meta-keywords：oauth，oauth提供者，认证
：元同义词：
：元产品：API Manager，Studio，Mule
：元适用到：

在Anypoint平台中，您可以在服务器和客户端使用OAuth解决方案：

* 从客户端应用访问受OAuth保护的服务器
+
示例：在应用程序中配置HTTP或Salesforce连接器以访问受OAuth保护的服务器。
+
* 保护API免受来自客户端应用程序的未经授权的调用
+
示例：应用OAuth 2.0策略，并且您配置的OAuth提供程序拒绝访问未经身份验证的客户端应用程序。

您可以使用以下OAuth提供程序和策略对：

[%header,cols="40a,60a"]
|===
| 提供者 | 政策名称
|  PingFederate  |  PingFederate OAuth令牌执行
|  OpenAM  |  OpenAM OAuth令牌执行
| 符合动态客户端注册的身份提供商  |  OpenID Connect访问令牌执行
|  Mule OAuth 2.0  | 使用外部提供商的OAuth 2.0访问令牌实施
|===

符合动态客户端注册的身份提供商需要符合OpenID Connect Client注册1.0，其中包含勘误表集1。

您应用OAuth 2.0策略的API支持使用Mule OAuth 2.0提供程序的HTTPS通信。提供程序验证OAuth 2.0凭据的有效性。

建议使用PingFederate，OpenAM或符合动态客户端注册的提供商。如果你不想与这样的提供商签约，你需要建立一个Mule OAuth提供商。您可以下载并导入由MuleSoft Consulting开发的定制Mule OAuth提供程序到Anypoint Studio中，而不是从头开始构建提供程序。

== 迁移到Mule OAuth提供程序

如果您在非生产环境中使用已弃用的AES OAuth策略提供程序，则原样的策略正在为您工作，并且可以接受通过HTTP（而非HTTPS）交换的令牌，不需要进行更改;否则，迁移到Mule OAuth提供程序如下：

* 自定义Mule OAuth提供程序来替换弃用的提供程序。
+
在Exchange上，您可以下载一个支持用户/密码的提供程序或另一个支持LDAP的提供程序。
+
* 从受影响的API中移除策略。
* 重新应用政策。

您现有的注册应用程序，客户端ID和客户端机密可继续使用。

== 另请参阅

*  link:https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client注册1.0包含勘误表集1]
*  link:/api-manager/v/1.x/external-oauth-2.0-token-validation-policy[使用外部提供者的OAuth 2.0访问令牌实施]
*  link:/access-management/external-identity[SAML 2.0和OpenID Connect提供商]
