= 关于自定义政策
:keywords: policy, pointcut, yaml, xml

如果您需要未包含在默认策略集中的API策略，则可以创建自己的自定义策略。自定义策略需要以下文件：

* 策略定义 - 描述策略及其可配置参数的YAML文件
* 策略配置 - 带有实施策略的后端进程的XML文件

自定义策略还必须包含切入点声明。有关更多信息，请参阅下面的切入点参考。

如果您使用以下某个运行时，则可以创建自定义策略：

*  Mule 3.8或更高版本统一运行时
*  API网关运行时2.x​​或更高版本

在Studio 6.1和更高版本中，您可以使用Studio自定义策略编辑器（Beta）。

== 限制

自定义政策必须是独立的。从定制策略中，不要引用另一个依赖策略，应用程序上的连接器，共享连接器或可能在运行时或外部库中可用的任何其他依赖项。

您可以通过使用Mule Runtime中的元素来评估和处理HTTP调用和响应来创建自定义策略。策略过滤对API的调用，并将请求中的某个查询参数与可配置的正则表达式相匹配。不匹配的请求被拒绝。只要请求与过滤器的条件不匹配，就可以将HTTP状态和有效负载设置为指示错误。

== 应用自定义政策

要为用户提供自定义策略，请将策略添加到API Manager中的Anypoint Platform。在API的API版本详细信息页面上，用户可以选择策略，从列表中选择自定义策略，并将策略应用于API。

如果使用从Anypoint Platform下载的.zip文件在专用服务器上部署API，则新策略可供本地用户应用。即使在创建策略之前已经部署了代理，也无需重新下载或重新部署任何内容。新策略会自动下载到安装了API Gateway或Mule 3.8统一运行时的位置的`/policies`文件夹。在`wrapper.conf`文件中配置您组织的客户端ID和令牌。

== 失败的政策

在Mule Runtime 3.8和更高版本以及API Gateway Runtime 2.1及更高版本中，当联机策略格式错误并引发解析异常时，它存储在`policies`目录内的`failedPolicies`目录下，等待审查。在下一次策略轮询中，它不会被解析。如果您删除该策略，它也会从该文件夹中删除。如果该文件夹没有策略，则会被删除。

=== 使用现有政策

您可以修改或合并默认存在的现有策略。您可以查看XML源代码，并在自定义策略配置中使用它。

在本地运行时安装中，搜索文件夹`examples>policies`以查找现有策略。

== 另请参阅

*  link:/api-manager/v/1.x/pointcuts-reference[切入点参考]
*  link:/anypoint-studio/v/6/studio-policy-editor[Studio自定义策略编辑器]
*  link:/release-notes/api-manager-release-notes#april-2016-release[权益]
