= 构建一个Mule OAuth 2提供程序
:keywords: oauth

：meta-audience：开发者
：元作业阶段：实施
：元的工作：
：meta-exp-level：Expert
：元功能：oauth
：meta-keywords：oauth，oauth提供者，认证
：元同义词：
：元产品：API Manager，Studio，Mule
：元适用于：PingFederate，OpenAM



要从MuleSoft Consulting在Mule Runtime 3.8.x中构建提供者，请执行此任务。

. 通过创建Maven `settings.xml`文件或通过添加凭据来设置Mule EE存储库中的凭证。该文件通常位于Linux或Mac OSX上的`~/.m2/settings.xml`中：
+
[source,xml,linenums]
----
...
  <servers>
    <server>
      <id>MuleRepository</id>
      <username>mule.username</username>
      <password>mule.password</password>
    </server>
  </servers>
...
  <profiles>
    <profile>
      <id>Mule</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>MuleRepository</id>
          <name>MuleRepository</name>
          <url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
...
        </repository>
      </repositories>
    </profile>
  </profiles>
----
+
. 使用本主题底部的链接下载OAuthProviderStudioArchive。
. 启动Studio，然后选择“文件”>“导入”。
{选择}中，展开Anypoint Studio，然后选择Anypoint Studio生成的可部署存档。
. 浏览至您下载的`OAuthProviderStudioArchive.zip`，然后点击完成。
. 登录到您的Anypoint平台帐户。
. 访问您用于创建提供商应用程序的帐户的客户端ID和客户端密钥。
. 在Anypoint Studio>首选项> Anypoint Studio> API的Anypoint Platform中输入您的客户端ID和客户端密钥。
+
此步骤对测试本地提供商是必需的。
. 在Project Explorer中，右键单击项目名称并选择Run As> Mule Application with Maven。
. 在配置Maven中，输入您的Maven安装主目录，然后单击测试Maven配置。
+
假设测试成功，请单击确定;否则，请解决Maven问题。控制台报告已部署应用程序。接下来，测试本地提供商。

== 下载

link:https://docs.mulesoft.com/api-manager/v/1.x/_attachments/OAuthProviderStudioArchive.zip[OAuthProviderStudioArchive]

////
或者，如果您使用Mule命令行，请按照以下步骤启动Mule：
+
----
${MULE_HOME}/bin/mule -M-Danypoint.platform.client_id=client_ID -M-Danypoint.platform.client_secret=client_secret start
----
////

== 另请参阅

*  link:/api-manager/v/1.x/to-test-local-provider[测试提供者]
*  link:/api-manager/v/1.x/external-oauth-2.0-token-validation-policy[使用外部提供者策略访问令牌执行]
*  link:/api-manager/v/1.x/aes-oauth-faq#about-oauth-provider-models[关于外部OAuth 2.0提供商]
*  link:/access-management/external-identity[外部身份（设置PingFederate和OpenAM提供程序）]
*  link:/access-management/organization#client-id-and-client-secret[访问客户端ID和客户端密钥]
