= 自定义策略属性参考

在自定义策略的配置XML中，您可以访问Policy Template YAML文件中定义的策略定义和属性的默认属性集。要引用属性，请按如下方式在两个大括号中输入其名称：

----
{{propertyName}}
----

本主题介绍`order`和`requiresContracts`属性。

策略标签中的== 订单属性

您可以使用`order`属性设置策略的执行顺序，但是在消息处理器中设置策略执行的顺序优先于设置策略标签中的执行顺序。将顺序设置为大于2的整数，因为顺序值0  -  2分别保留用于CORS，节流和速率限制策略。这些政策必须先于其他人执行。以下示例显示如何设置`<policy>`标记中的`order`属性：

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<policy id="7777"
        policyName="A"
        order="3"
        xmlns="http://www.mulesoft.org/schema/mule/policy"
        xmlns:mule="http://www.mulesoft.org/schema/mule/core"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:api-platform-gw="http://www.mulesoft.org/schema/mule/api-platform-gw"
        xsi:schemaLocation="http://www.mulesoft.org/schema/mule/policy http://www.mulesoft.org/schema/mule/policy/current/mule-policy.xsd
              http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
              http://www.mulesoft.org/schema/mule/api-platform-gw http://www.mulesoft.org/schema/mule/api-platform-gw/current/mule-api-platform-gw.xsd">

    <before>
         <mule:logger level="INFO" message="POLICY A" />
    </before>

    <pointcut>
        <api-platform-gw:api-pointcut apiName="Leagues API" apiVersion="1.0.0"/>
    </pointcut>
</policy>

----

== 在标签之前或之后订购属性

或者，您可以在<before> </before>和<after> </after>个标签中设置政策的执行顺序。设置`before`和`after`标签中的`order `属性优先于策略标签中的任何订单设置。将顺序设置为大于2的整数。例如：

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<policy id="2"
       ...

    <before order="4">
       <mule:set-payload value=" before cust2 "/>
       <mule:logger level="INFO" message="#[payload]" />
    </before>

    <before order="3">
       <mule:set-payload value=" before cust2.1 "/>
       <mule:logger level="INFO" message="#[payload]" />
    </before>
----

== 需要策略标签中的合同

以下版本支持配置XML的策略标记中的`requiresContracts`属性：

*  API网关运行时2.2.0或更高版本
*  Mule Runtime 3.8或更高版本

在早期版本中，您不需要此属性，因为默认情况下API Gateway Runtime会缓存客户端凭据。

*Important*：启用`requiresContracts`属性对于客户端验证至关重要。如果Anypoint Platform发生故障，则策略可以继续验证客户端。验证检查发生在内存中，这比在网络上涉及HTTP请求的检查更自然。

验证客户端ID的自定义策略通常是MuleSoft提供的对客户端进行身份验证（如客户端ID实施或基于SLA的策略）的策略的变体。

在验证客户端ID的自定义策略中，包含`requiresContracts`并将此布尔值属性设置为true，如以下示例代码片段所示。

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<policy id="{{policyId}}"
        policyName="Custom Client Id Enforcement"
        online="true"
        requiresContracts="true"
        xmlns="http://www.mulesoft.org/schema/mule/policy"
...
----

将API客户端身份和身份验证凭据下载到API Gateway Runtime或Mule Runtime并存储。验证发生在运行时间内，无需出站HTTP请求进行验证。

下载和检索客户端信息在后台进行，默认情况下每15秒发生一次。您可以使用`anypoint.platform.poll_clients_freq`属性配置轮询频率。在CloubHub属性选项卡或`<MULE_HOME>/conf`文件夹中的`wrapper.conf`文件中配置此属性。

== 另请参阅

*  link:/api-manager/v/1.x/custom-policy-reference[自定义策略参考]
*  link:/api-manager/v/1.x/cust-pol-exception-blocks-reference[自定义策略例外块参考]
*  link:/api-manager/v/1.x/pointcuts-reference[切入点参考]

