= 关于策略管理体系结构
:keywords: policy, policy management architecture

通过这些组件之间的协调沟通实施政策：

*  API管理器
* 一个或多个API网关运行时或Mule 3.8.0运行时或更高版本
* 一个或多个API代理应用程序

您可以从特定的Anypoint Platform帐户和特定组织在API Manager中配置和应用策略。您将策略应用于特定的API版本。一个特定的API版本也可以绑定到特定的API实现端点，然后可以自动生成API代理应用程序。然后，您可以将每个API代理应用程序部署到一个或多个API网关运行时或Mule运行时3.8.0或更高版本。 Mule Runtime 3.8.0或更高版本包含所有旧版 link:/api-manager/v/1.x/api-gateway-runtime-archive[API网关]运行时功能。

每个API代理应用程序都会通过API指定的HTTP或HTTPS URL接收请求。通常，请求会被转发到相应的API实施端点URL，然后响应会通过API代理应用程序返回到请求客户端应用程序。

== 策略注入和执行

将特定API版本的API代理应用程序部署到传统API Gateway Runtime或Mule Runtime 3.8.0或更高版本时，运行时/策略文件夹中的任何应用策略都将被注入到API代理中。这改变了应用程序的行为。

当代理应用程序接收到新的请求时，将应用所有注入的策略来决定是否以及如何将请求转发给API实施端点。

通过这种方式，实际的策略实施发生在代理应用程序本身内部，从而最大限度地减少处理接收到的请求的API代理，Anypoint Platform代理和在线API Manager之间的串扰。 API代理应用程序不需要与运行时中运行的Anypoint Platform代理进行任何通信，也不需要与API Manager进行任何通信。

但是，Anypoint Platform代理仍然连接到API Manager。在策略重新配置或从API Manager中删除之后，这些策略会下载到任何连接的API Gateway或Mule运行库，它们会更新每个运行时/策略文件夹。然后策略更改再次注入到每个API代理应用程序中。这允许动态更改策略，而无需重新部署API代理应用程序，也无需重新启动API Gateway或Mule运行时。
