=  LDAP安全管理器
:keywords: ldap, api, gateway, authentication, http, security

LDAP安全管理器策略为您为企业设置的Open LDAP或Active Directory LDAP建立配置详细信息。要强制执行LDAP安全管理器策略，还需要创建并应用HTTP基本身份验证策略，该策略会提示代理使用LDAP策略中建立的配置强制执行凭证访问。

== 先决条件

本文档假设您是要管理的API版本的API版本所有者，或者您是组织管理员角色的成员。

== 配置LDAP安全管理器

配置LDAP安全管理器以连接到您的LDAP或Active Directory。各个领域都需要。这些文字字符串值支持属性占位符。输入密码作为安全值，该值是输入后不可见或可检索的值。


*  LDAP服务器URL
+
您的LDAP服务器的URL，包括端口号。

*  LDAP用户DN
+
有权访问LDAP的用户或用户组的名称。
+
*  LDAP用户密码
+
用户或用户组的密码
+
*  LDAP搜索库
+
在目录树中搜索的起点。
+
*  LDAP搜索过滤器
+
Active Directory或OpenLDAP模型的筛选条件，如下面的示例所示。


===  Active Directory安全管理器的示例配置

[%header,cols="3*a"]
|===
|字段 |示例字符串值 |示例安全属性占位符
| *LDAP Server URL*  | `ldap://174.19.33.17:389/`  | `${ldap.server.url}`
| *LDAP Server User DN*  | `CN=Administrator,CN=Users,DC=my-company,DC=com`  | `${ldap.user.dn}`
| *LDAP User Password*  | `somePassword`  | `${ldap.password}`
| *LDAP Search Base*  | `CN=Users,DC=my-company,DC=com`  | `${ldap.search.base}`
| *LDAP Search Filter*  | `(sAMAccountName={0})`  | `${ldap.search.filter}`
|===

请注意，上面给出的搜索过滤器字符串是Active Directory应用程序特有的。

===  OpenLDAP安全管理器的示例配置

[%header,cols="3*a"]
|===
|字段 |示例字符串值 |示例安全属性占位符
| *LDAP Server URL*  | `ldaps://my-company-ldap.cloudhub.io:1010/`  | `${ldap.server.url}`
| *LDAP Server User DN*  | `cn=Manager,dc=my-company,dc=com`  | `${ldap.user.dn}`
| *LDAP User Password*  | `somePassword`  | `${ldap.password}`
| *LDAP Search Base*  | `ou=people,dc=my-company,dc=com`  | `${ldap.search.base}`
| *LDAP Search Filter*  | `(uid={0})`  | `${ldap.search.filter}`
|===

*Note*：上面给出的搜索过滤器字符串是OpenLDAP应用程序特有的。


如果在配置LDAP策略时使用安全属性占位符，请在命令行中或在Mule运行时或API网关运行时`wrapper.conf`文件中指定占位符的值作为系统变量。

例如：

[source, code, linenums]
----
# OpenLDAP properties definitions
wrapper.java.additional.7=-Dldap.password=<password here>
wrapper.java.additional.8=-Dldap.user.dn=cn=Manager,dc=my-company,dc=com
wrapper.java.additional.9=-Dldap.search.base=ou=people,dc=my-company,dc=com
wrapper.java.additional.10=-Dldap.search.filter=(uid={0})
wrapper.java.additional.11=-Dldap.server.url=ldaps://my-company-ldap.cloudhub.io:1010/
----



== 应用您的LDAP安全管理器和基本身份验证策略

按照以下步骤在运行时将这些策略应用于端点。

. 导航到API管理器，然后单击您要应用策略的API版本。
. 单击“策略”选项卡将其打开。
. 应用LDAP安全管理器策略并将其配置为连接到您的LDAP。
. 应用HTTP基本身份验证策略来执行您的安全管理器策略。
. 验证安全策略现在是否生效 - 您的API的端点现在应该需要验证。


请注意，即使您的目标服务版本或端点已配置了安全管理器，您也可以应用LDAP安全管理器策略并使用HTTP基本身份验证策略强制执行此策略。由API管理器执行的安全管理覆盖您已应用的任何其他安全管理器策略。

{0}}不应用LDAP安全管理器和基本身份验证策略

要从您的服务版本或端点中取消应用由LDAP安全管理器支持的HTTP基本验证，请一次只应用一项策略。

. 不应用HTTP基本身份验证策略。
. 不应用LDAP安全管理器策略。
. 点击终端以确认您的API不再需要验证。
