= 切入点参考

自定义策略必须包含切入点声明。切入点控制策略应用程序的范围，并使用正则表达式来指示应用程序中的流量受策略的影响。

如果您将策略应用于在Anypoint Platform中部署的API，请将您的切入点设置为默认属性`apiName`和`apiVersion`。此操作可确保您的策略仅适用于您要激活策略的API。这就是你的切入点应该是这样的：

[source,xml,linenums]
----
<pointcut>
   <api-platform-gw:api-pointcut apiName="{{ apiName }}" apiVersion="{{ apiVersionName }}"/>
</pointcut>
----

将切点设置为广泛的正则表达式（例如`regex=”.*”`）可能会产生不良影响。

通过该平台将此策略应用于单个API，可能实际上也会影响您正在部署的其他API。

如果您在现场部署中使用您的策略，那么您可能需要修改切入点以将您的策略​​同时应用于多个API。

== 启用资源级别策略

如果您的API在Mule 3.8.4及更高版本上运行，请使用以下代码来包含资源级别策略：

[source,xml,linenums]
----
  {{#pointcutData}}
    <pointcut>
      <api-platform-gw:api-pointcut apiName="{{apiName}}" apiVersion="{{apiVersionName}}"/>
      <resource methodRegex="{{methodRegex}}" uriTemplateRegex="{{uriTemplateRegex}}"/>
    </pointcut>
  {{/pointcutData}}

{{^pointcutData.length}}
  <pointcut>
    <api-platform-gw:api-pointcut apiName="{{apiName}}" apiVersion="{{apiVersionName}}"/>
  </pointcut>
{{/pointcutData.length}}
----

另外，在YAML中包含以下属性：`resourceLevelSupported: true`

== 自定义切入点

在切入点中，您可以引用以下几种元素：

* 端点
* 应用
* 资源

如果在单个切入点内指定了多个元素，那么它们就像您使用AND表达式一样实施。

[source,xml,linenums]
----
<pointcut>
   <resource uriTemplateRegex="/items/.*" />
   <resource methodRegex="GET" />
</pointcut>
----

如果在不同的切入点父元素中指定了几个元素，则它们的实现方式与您使用OR表达式一样。

== 参考应用

[source,xml,linenums]
----
<pointcut>
   <app regex=".*" />
</pointcut>
----

== 参考端点

[source,xml,linenums]
----
<pointcut>
   <endpoint regex=".*" />
</pointcut> 
----

以下示例使用来自属性的值：

[source,xml,linenums]
----
<pointcut>
    <endpoint regex="http://localhost:${http.port}/gateway/.*" />
</pointcut>
----

这个例子也是有效的：

[source,xml,linenums]
----
<pointcut>
   <endpoint regex="http\:\/\/localhost:${http.port}\/gateway\/.*" />
</pointcut>
----

对于前面两个示例的工作，您必须在启动Mule或在wrapper.conf文件中定义`http.port`，定义如下所示：

`wrapper.java.additional.4=-Dhttp.port=8081`

如果在应用程序级别定义`http.port`，则在应用策略时会发生分析异常。

== 参考资源

[source,xml,linenums]
----
<pointcut>
   <resource methodRegex=".*" />
</pointcut>
----

您可以引用特定的方法（GET，POST，PUT等）。

例如：`<resource methodRegex=”P.*” />`适用于所有POST，PUT和PATCH方法。 +

使用默认值的示例：

[source,xml,linenums]
----
<pointcut>
   <resource uriTemplateRegex=".*" />
</pointcut>
----

在这个例子中，你可以指定路径为RAML文件中指定的baseUri。

第一级资源的示例过滤：

[source,xml,linenums]
----
<pointcut>
    <resource uriTemplateRegex="/items/.*" />
</pointcut>
----


您只能使用由Mule提供的Java类。

虽然可以使用Mule中提供的任何消息处理器来构建自定义策略，但只能使用由Mule提供的Java类。与构建Mule应用程序不同，构建自定义策略时无法定义和调用自定义Java类，因为您无法将自定义Java类与您的策略捆绑在一起。

== 另请参阅

*  link:/api-manager/v/1.x/custom-policy-reference[自定义策略参考]
*  link:/api-manager/v/1.x/custom-pol-config-xml-props-reference[自定义策略属性参考]
*  link:/api-manager/v/1.x/cust-pol-exception-blocks-reference[自定义策略例外块参考]
