= 政策参考

添加，删除和应用策略的先决条件是：

* 角色：组织管理员或API版本所有者
* 一个API网址
+
要设置API URL，请在API版本详细信息页面的状态中单击配置端点，然后设置实施URI。

如果您想使用速率限制和限制策略，请使用HTTP端点而不是Jetty。由于Jetty传输限制，速率限制和限制策略不适用于使用Jetty入站端点的API。

要在私有服务器上使用策略，可以在API Manager中应用策略，通过运行时Anypoint Platform代理将策略下载到API网关运行时或Mule 3.8.0或更高版本的运行时。策略存储在每个运行时/策略文件夹中。每个运行时都配置了API Manager帐户的客户端ID和客户端密钥。这定义了Anypoint Platform代理和Anypoint Platform帐户之间的连接。

== 应用和删除策略

在为API版本设置API URL后，您可以在“应用程序”，“策略”和SLA层中使用控件。当您单击Apply New Policy（应用新策略）时，出现由您的组织添加的MuleSoft提供的策略列表和任何自定义策略。

不可用应用表示以下情况之一：

* 另一项应用政策满足要求。

* 在应用此政策之前，需要制定另一项政策

== 订购政策
如果您正在使用以下版本之一，则可以设置策略的执行顺序：

用于创建的*  Studio 6.0或更高版本，通过自动发现部署到Anypoint Platform
*  Mule 3.8统一运行时或更高版本
*  API网关运行时2.2.0或更高版本

== 默认政策执行顺序

在API版本详细信息页面上，选择策略时会显示策略的默认顺序，然后单击>展开策略的控件。在MuleSoft提供的策略之后执行未配置订单的自定义策略。

== 策略日志

日志显示策略的顺序：

----

INFO  2015-09-28 15:37:54,214 [[leagues-rest].httpListenerConfig.worker.01] org.mule.api.processor.LoggerMessageProcessor: POLICY A
INFO  2015-09-28 15:37:54,214 [[leagues-rest].httpListenerConfig.worker.01] org.mule.api.processor.LoggerMessageProcessor: POLICY B
----

== 与政策相关的通知

当组织所有者定义策略执行的顺序时，如果现有API所有者已在其API上设置策略，则可能发生冲突。发生冲突时，API Manager会通知双方。 API所有者需要更新策略并解决任何冲突。

== 配置策略轮询时间

默认策略轮询时间是60秒。现在，从UI应用策略的时间到策略生效的时间之间现在会出现至少60秒的延迟时间。禁用或编辑策略时会发生相同的延迟。您可以使用以下系统属性配置延迟的长度：

`anypoint.platform.poll_policies_freq`

通过更改wrapper.conf文件，以秒为单位配置新值。例如：

`wrapper.java.additional.30=-Danypoint.platform.poll_policies_freq=45”`

== 为策略配置APIkit控制台

您可以将策略应用于API和控制台，或仅应用于API。

控制台的配置决定了如何配置基于RAML的自动生成代理。

== 另请参阅

*  link:/api-manager/v/1.x/tutorial-manage-an-api[应用策略和SLA层]
*  link:/api-manager/v/1.x/resource-level-policies-about[关于资源级别策略]
*  link:/api-manager/v/1.x/disable-edit-remove-task[禁用，编辑或删除策略]
*  link:/api-manager/v/1.x/reorder-policies-task[重新排列策略]
*  link:/apikit/apikit-using#working-with-the-apikit-console[使用API​​kit控制台]
