= 关于部署代理
:keywords: proxy, api, rest, raml, soap, cloudhub

在Mule Runtime 3.8和更高版本中合并的API Gateway是承载Mule代理应用程序的服务器。要从API Manager部署API，您通常会创建一个代理应用程序，用于阻止针对实际服务器的攻击。此代理应用程序有时称为自动生成的代理。

//在API Manager中部署代理之前，您可以使用API​​ Designer，AnyPoint Studio或Mule运行时来设计，运行和调试代码。

部署API后，您可以使用策略来管理API。您可以设置API警报以发送有关条件的通知，例如返回特定HTTP错误代码的API。

== 部署先决条件

您需要满足以下先决条件，具体取决于部署类型：

*General Prerequisites*

*  API Manager中存在API版本
该API的*  API版本所有者权限或组织管理员角色中的成员资格
* 运行API的服务器的URL

*Deployment to your server*

访问Mule 3.8.0 Runtime或更高版本的实例或已配置为与您的组织配对的API网关实例。如果使用早于3.8.0版本的Mule，请配置API网关。

*Automatic deployment to your server*

运行时管理器和组织的API管理器的有效权限。另外，私人服务器必须注册。

*Automatic CloudHub deployment*

组织的运行时管理器和API管理器的权限。

*Manual CloudHub deployment*

Anypoint Platform帐户和Anypoint Platform客户端ID和客户端密钥，以将部署与组织配对。

您需要组织的运行时管理器和API管理器有效的权限才能部署代理。

使用API​​的===  HTTPS

. 在“配置终端”菜单中，将实现URI提供给HTTPS地址。指定HTTPS地址会修改代理以支持HTTPS。默认情况下，代理使用JVM的默认HTTPS凭证对请求进行签名。
. 如果您想要包含其他HTTPS凭证，请下载代理并相应地进行修改。
+
如果您计划将代理应用程序导入Studio 6.x或更高版本，则可以在API Manager中选择是否将应用程序链接到域。
+
. 修改代理的`proxy.xml`文件中的http：request-config元素，以包含指向所需信任库/密钥库的TLS配置元素。

== 另请参阅

*  link:/api-manager/v/1.x/api-gateway-domain[链接到域]
*  link:/access-management/users[API版本所有者权限]
*  link:/api-manager/v/1.x/api-auto-discovery#configuration[配置与您的组织配对]
*  link:/api-manager/v/1.x/configuring-an-api-gateway[配置API网关]

