= 关于设计基本RAML API
:keywords: raml, api, designer

您可以在Anypoint Platform中使用API​​ Designer来设计RAML API以使用REST服务。设置API后，API管理页面上将存在项目名称和项目版本。单击项目版本会将您带到API版本详细信息页面，最终到达RAML编辑器API Designer。

== 先决条件

要在Anypoint Platform中使用API​​ Designer，您需要以下帐户和角色：

*  Anypoint平台帐户
+
如果您没有帐户，则可以在互联网上注册：
+
`+https://anypoint.mulesoft.com+`
+
如果您注册了一个帐户，那么您将获得组织管理员角色。
+
*  API创建者或组织管理员的成员 link:/access-management/roles[角色]
+
如果您不是这些角色之一的成员，则无法看到用于访问API Designer的*Add new API*按钮。

== 创建一个API项目

选择“项目”>“新建文件”，选择RAML规格版本和计划包含在.raml文件中的内容类型。根据您提供的API的标题和版本显示几行代码：

[source,yaml,linenums]
----
#%RAML 1.0
title: placeholder
version: 1.0.development
description: This API consumes the JSONPlaceholder REST Service.
----

除了这个生成的代码之外，您还可以将以下内容添加到RAML API定义中：

*  RAML文档根目录下的可选baseURI节点
*  API资源，例如收集所有客户或特定客户
每个资源上都允许使用*  HTTP方法，例如GET，POST，PUT和DELETE
* 每种方法的请求和响应消息的表示形式，例如`GET /customer/1 -> response: application/json`。

选项baseUri充当API的标识符，并形成资源URL的基础。配置此URL不会部署该API，也不保证可以通过该URL访问该API。要部署API，您需要 link:/api-manager/v/1.x/setting-up-an-api-proxy[配置端点]。

如果您没有提供baseUri，则仍然可以使用API​​ Console中模拟服务提供的baseUri来测试API。您需要包含示例响应来以这种方式测试API。

== 包含示例响应

模拟对API的调用是一项关键设计任务，可以帮助您排除问题并在即将实施之前向潜在用户演示API。可以通过演示获得有价值的反馈，并帮助您改进API。要模拟对API的调用，请包括以下内容：

* 数据的JSON示例将返回API的实际实现
*  HTTP状态代码API返回成功或失败消息。

您可以在API控制台中使用模拟服务为未实现的API提供基本URI。当您成功调用API时，模拟服务将返回状态码200和示例。

以下示例显示响应的语法和缩进：

----
...
    description: Retrieve a list of all the users
    responses:
      200:
        body:
          application/json:
            example: |
              [{
              "id": 1,
              "name": "Leanne Graham",
              "username": "Bret",
              "email": "Sincere@april.biz",
              "address": {
                "street": "Kulas Light",
                "suite": "Apt. 556",
                "city": "Gwenborough",
                "zipcode": "92998-3874",
                "geo": {
                  "lat": "-37.3159",
                  "lng": "81.1496"
                }
              },
              "phone": "1-770-736-8031 x56442",
              "website": "hildegard.org",
              "company": {
                "name": "Romaguera-Crona",
                "catchPhrase": "Multi-layered client-server neural-net",
                "bs": "harness real-time e-markets"
              } }]
----

== 使用！include

为了模块化API定义，RAML提供了几种机制，其中之一就是`!include`属性。为了保持API定义的简洁性，可以在定义本身之外包含外部内容，例如文档，模式和常用模式。解析器将`!include`解释为好像外部托管的文件或URL的内容是在线声明的。

----
...
      application/json:
        example: !include user-example.json
----

== 另请参阅

*  link:/api-manager/v/1.x/designing-your-api#accessing-api-designer[API Designer参考]。
*  link:/api-manager/v/1.x/designing-your-api#using-hints-raml-editor-shelf-and-autocompletion[API Designer架构]
*  link:http://jsonplaceholder.typicode.com[JSONPlaceholder免费REST服务]
*  link:/api-manager/v/1.x/designing-your-api#using-hints-raml-editor-shelf-and-autocompletion[API Designer架构]
*  link:/api-manager/v/1.x/setting-up-an-api-proxy[配置端点并部署API]
