= 关于API警报
:keywords: alerts,api, api alerts

API警报是标记以下问题之一的警报：

*  API请求违反了一项政策。
*  API收到的请求在一段时间内超过给定的数字。
*  API返回指定的HTTP错误代码。
*  API响应时间超过一定数量。

运行时管理器警报在性质上与API警报有所不同。运行时管理器标记CPU使用率，安全数据网关上/下，部署成功/失败等等。另一方面，API警报涉及API请求或响应。

您可以将以下某种警报添加到API中：

* 违反政策
+
管理API的一个或多个策略的违规发生。
+
* 请求计数
+
用户请求访问API的次数超过指定时间段内允许的次数。
+
* 响应代码
+
API在接收到请求时返回这些HTTP代码之一：400,401,403,404,408,500,502或503
+
* 响应时间
+
API的响应时间超过了指定的时间段。

请求计数警报条件与使用速率限制策略的策略警报类似。请求计数的时间间隔选项的有效条目范围为1  -  999999999.指定的这些时间间隔是作为滑动窗口实现的，而不是绝对的微小边界，以防止由数据突发导致的问题。

您可以通过将警报添加到API Manager中的已部署版本来创建和配置API警报。

== 添加和查看API Manager警报的先决条件

要添加警报，您需要属于以下角色之一：

*  API版本所有者
*  API创作者
* 组织管理员

要查看提醒，您需要满足以下条件之一：

* 您被分配给组织目标API的组织管理员角色。
+
作为组织管理员，您只能在组织内看到与API相关的警报。
+
* 您拥有目标API版本。
+
作为API版本所有者，您只能看到添加到您拥有的版本的警报。

组织管理员或API所有者以外的用户（例如，从API门户请求并接收API访问权的Portals查看者角色的成员）无法看到警报。

== 警报通知

当警报触发时，API Manager会向您发送电子邮件通知，如果已配置，则会向其他人发送电子邮件通知

设置警报时，您可以选择业务组中可以接收有关警报的电子邮件通知的用户。该通知包含有关触发警报的事件的信息，如严重级别所指定的。用户收到两封电子邮件：

* 一封电子邮件介绍了警报。例如：
+
`Your API Version, jsonplaceholderapi - 1.0.development, has received greater than 1 requests within 1 consecutive periods of 1 minutes.`
+
* 另一封电子邮件会在警报解决时通知您。
+
`Your API Version, jsonplaceholderapi - 1.0.development, is no longer in an alert state. The number of policy violations was not greater than 1 in the last 1 consecutive periods of 1 minutes.`

警报触发后，API Manager将发送第一组两个通知电子邮件，并在下一个警报期开始之前停止侦听警报。这项技术可以防止重复的通知电子邮件。


== 另请参阅

*  link:/runtime-manager/alerts-on-runtime-manager[运行时管理器警报]
*  link:https://www.techopedia.com/definition/869/sliding-window[滑动窗户]
