= 加密MMC LDAP密码

*_Enterprise Edition_*

默认情况下，管理控制台配置为 link:/mule-management-console/v/3.4/setting-up-and-managing-users-via-ldap[使用LDAP进行用户认证]时，会将未加密的LDAP凭据存储在纯文本配置文件中。为避免此安全风险，您可以配置管理控制台以存储加密的LDAP密码，并使用 http://www.jasypt.org/download.html[Jasypt]加密库对其进行解密。

实施此配置需要执行以下任务：

*  <<Downloading And Installing the Encryption Library>>
*  <<Encrypting the Password>>
*  <<Configuring the Management Console>>

您使用Jasypt加密密码，并将加密值和其他参数提供给管理控制台。在用户认证时，管理控制台将使用Jasypt解密用户密码。

[TIP]
如果您希望加密用户密码，但不要使用LDAP进行用户认证，请参阅 link:/mule-management-console/v/3.4/encrypting-mmc-user-passwords[加密MMC用户密码]。

[TIP]
此页面中介绍的配置将解密参数存储在Management Console配置文件中。有权访问这些文件的攻击者可以使用这些参数解密用户密码。为了避免这种安全风险，您可以将Jasypt与Spring 3.0集成并将解密参数存储为环境变量。有关详情，请参阅 http://www.jasypt.org/springsecurity.html[整合Jasypt和Spring 3.0]。

== 下载并安装加密库

http://www.jasypt.org/download.html[Jasypt]是一个易于使用的Java库，提供基本的加密功能。它是免费软件，在 http://www.jasypt.org/license.html[Apache软件许可证]下许可。

要在管理控制台中安装Jasypt，请完成以下步骤：

. 从Jasypt的 http://www.jasypt.org/download.html[下载页面]下载最新版本（当前为1.9.0）。 Jasypt下载为一个名为`jasypt-1.9.0-dist.zip`的.zip文件。
. 解压文件`jasypt-1.9.0-dist.zip`，该文件展开到`jasypt-1.9.0`目录。
. 将文件`jasypt-1.9.0.jar`和`jasypt-spring3-1.9.0.jar`复制到目录`<MMC installation path>/WEB-INF/lib`。您会在`jasypt-1.9.0/lib`目录中找到这些文件。

== 加密密码

要加密密码，请在Windows系统上运行脚本`encrypt.sh`（或`encrypt.bat`）。您可以在`jasypt-1.9.0`目录的`bin`子目录中找到该脚本。

[source, xml, linenums]
----
<path to file>/encrypt.sh input="valueToEncrypt" password=MYPASS algorithm=PBEWithMD5AndDES
----

[%header,cols="15,75"]
|===
|脚本参数 |描述
| `input`  |要加密的值。这是您希望加密的实际LDAP密码。
| `password`  |用于加密`input`的字符串。这不是LDAP密码，而是用于加密密码的短语。密码本身在`input`参数中提供。
| `algorithm`  |用于加密的算法。
|===

该脚本在标准输出上显示加密的密码，如下例所示。

[source, code, linenums]
----
pedro@xubuntu: /home/pedro/jasypt-1.9.0/bin/encrypt.sh input="valueToEncrypt" password=MYPASS algorithm=PBEWithMD5AndDES
 
----ENVIRONMENT-----------------
 
Runtime: Sun Microsystems Inc. OpenJDK 64-Bit Server VM 20.0-b12
 
----ARGUMENTS-------------------
 
algorithm: PBEWithMD5AndDES
input: valueToEncrypt
password: MYPASS
 
----OUTPUT----------------------
 
NdPn1skzduJFjGaIOY53pMALTgped0zX
 
pedro@xubuntu:bin$
----

Note that if on a Unix or Unix-based system, you need to set execute permissions for `encrypt.sh` to be able to run it.

[TIP]
====
*How to apply execute permissions on Unix systems*

To set execute permissions for the `encrypt.sh` script, run the following command:

[source, code, linenums]
----
chmod a+x <path to file>encrypt.sh
----

For example:

[source, code, linenums]
----
chmod a+x /home/mary/jasypt-1.9.0/bin/encrypt.sh
----

This command adds execute permission for all users (file owner, file owner's group, and other users).
====

Copy the encrypted output and store it in a convenient location, such as a text file of your choosing. You will need to copy this value to the `mmc-ldap.properties` file, as detailed in the <<File mmc-ldap.properties>> section.

For more information about `encrypt.sh`, including other usage samples, see Jasypt's http://www.jasypt.org/cli.html[CLI Tools] page.

== Configuring the Management Console

=== File applicationContext.ldap.xml

Locate the file `<MMC Home>/WEB-INF/classes/META-INF/applicationContext.ldap.xml`, then add to it the bean listed below. Note that this bean must be the first bean in the file.

[source, xml, linenums]
----
<bean id="propertyConfigurer" class="org.jasypt.spring3.properties.EncryptablePropertyPlaceholderConfigurer">
    <constructor-arg ref="configurationEncryptor" />
    <property name="locations">
      <list>
          <value>/WEB-INF/classes/mmc-ldap.properties</value>
      </list>
   </property> 
   <property name="ignoreUnresolvablePlaceholders" value="true"/>
</bean>
----

=== File ldap.xml

Locate the file `<MMC Home>/WEB-INF/classes/META-INF/ldap.xml`, then add to it the beans listed below. Note that the value for property `password` must be the same you gave to the `encrypt.sh` script as the `password` parameter. In the example provided in the <<Encrypting the Password>> section, the value is `MYPASS`.

[source, xml, linenums]
----
<bean id="encryptorConfig" class="org.jasypt.encryption.pbe.config.SimplePBEConfig">
    <property name="algorithm" value="PBEWithMD5AndDES" />
    <property name="password" value="MYPASS" />
 </bean>
  <bean id="configurationEncryptor" class="org.jasypt.encryption.pbe.StandardPBEStringEncryptor">
    <property name="config" ref="encryptorConfig" />
</bean>
----

=== File mmc-ldap.properties

Locate the file `<MMC Home>/apps/mmc/webapps/mmc/WEB-INF/classes/mmc-ldap.properties`. Edit this file to include the output of the `encrypt.sh` script as the value of the `password` parameter, as shown below.

[source, code, linenums]
----
password=ENC(NdPn1skzduJFjGaIOY53pMALTgped0zX)
----

Note that the encrypted value is surrounded by `ENC()`. This indicates that the value is encrypted, and must be processed by the Jasypt library while Spring constructs the bean.

The `mmc-ldap.properties` file will be similar to the code shown below.

[source, code, linenums]
----
providerURL=ldaps://192.168.1.14:636/
userDn=cn=sb,ou=people,dc=example,dc=com
password=ENC(NdPn1skzduJFjGaIOY53pMALTgped0zX)
usernameAttribute=cn
userSearchBaseContext=ou=people,dc=example,dc=com
userSearchFilterExpression=(cn={0})
userSearchBase=ou=people,dc=example,dc=com
userSearchAttributeKey=objectclass 
userSearchAttributeValue=person
roleDn=ou=groups,dc=example,dc=com
groupSearchFilter=(uniqueMember={0})
----

After completing the preceding steps, restart the Management Console for the changes to take effect.

[TIP]
To avoid storing the passphrase on the Management Console configuration files, you can integrate Jasypt with Spring 3.0 and store decryption parameters as environment variables. For details, see http://www.jasypt.org/springsecurity.html[integrating Jasypt with Spring 3.0].

[TIP]
====
For details on configuring the Management Console to use LDAP for user authentication, see link:/mule-management-console/v/3.4/setting-up-and-managing-users-via-ldap[Setting Up and Managing Users via LDAP].

If you wish to encrypt user passwords, but do not use LDAP for user authentication, see link:/mule-management-console/v/3.4/encrypting-mmc-user-passwords[Encrypting MMC User Passwords].
====
