= 加密MMC用户密码

＃*_Enterprise Edition_*＃

管理控制台以纯文本形式将用户名和密码存储在`mmc-data`目录中的持久性信息数据库中。为避免以纯文本存储用户名和密码，可以加密用户名和密码。

本页面上的说明详细说明如何运行提供的Groovy脚本来加密现有的用户密码，并相应地更新数据库。

[NOTE]
此方法不适用于LDAP身份验证，但仅适用于管理控制台的默认身份验证配置。如果您希望在LDAP认证配置中加密用户密码，请参阅加密MMC LDAP密码。

== 配置管理控制台

本节详细介绍如何配置管理控制台以加密其持久数据库中的现有用户密码。

[NOTE]
在修改下面列出的配置文件之前，请确保管理控制台未运行。

=== 文件applicationContext-spring-security.xml

找到文件`<MMC Home>/WEB-INF/classes/META-INF/applicationContext-spring-security.xml`。在这个文件中，找到bean `passwordEncoder`，然后编辑它，如下所示。

[source, xml, linenums]
----
<bean id="passwordEncoder" class="org.springframework.security.authentication.encoding.ShaPasswordEncoder"/>
----

[TIP]
上例使用SHA密码编码器;如果需要，您可以使用其他编码。 Spring包含几个选项，例如Md5PasswordEncoder。

=== 文件applicationContext-core.xml

找到文件`<MMC Home>/WEB-INF/classes/META-INF/applicationContext-core.xml`。在这个文件中，找到bean `userManager`，编辑如下所示。

[source, xml, linenums]
----
<bean id="userManager" class="com.mule.support.EncryptedUserManagerImpl" init-method="initialize">
    <property name="sessionFactory" ref="sessionFactory" />
    <property name="passwordEncoder" ref="passwordEncoder" />
    <property name="salt" value="" />
</bean>
----

修改配置文件后，请完成以下步骤：

//无法下载以下文件。克里斯7/2/2017

. 下载并解压文件`mmc-encrypter-1.0.jar`和`autorun.groovy.script`。
. 将文件`mmc-encrypter-1.0.jar`复制到`<MMC_HOME>/WEB-INF/lib`。
. 将脚本`autorun.groovy.script`复制到您正在运行管理控制台的目录。例如，如果使用Tomcat，请将脚本复制到`<Tomcat home>/bin`。
. 启动管理控制台。

[NOTE]
启动管理控制台将运行，然后自动删除`autorun.groovy.script`。

Groovy脚本将所有纯文本用户密码迁移到其加密值，并使用这些值更新数据库。

要确保更新成功完成，请在日志中搜索以下条目：

`>>>>>>>>>>> Passwords updated successfully`

在启动管理控制台之后，Groovy脚本应该已被自动删除。如果该脚本尚未删除，请手动删除它。
