= 升级管理控制台

MMC代理和.war文件可通过 http://www.mulesoft.com/support-login[MuleSoft客户门户]获取。 MMC.war文件与以前版本的Mule ESB向后兼容，因此建议下载最新的`.war`文件。

[NOTE]
从Mule ESB 3.4.0开始，MMC代理捆绑了Mule ESB Enterprise运行时下载。

== 确定您的MMC版本

您可以通过登录控制台并点击屏幕右下方的*About Mule ESB Enterprise*来确定当前运行的MMC .war文件的版本。

[NOTE]
在所有情况下，强烈建议升级到最新版本的管理控制台。

== 升级到管理控制台3.4.1

如果您将.war升级到版本3.4.1，并且您的Mule ESB版本早于3.4.1，则可能需要升级您的Management Console代理，如下所述。

[%header%autowidth.spread]
|===
|您的Mule ESB版本 |您当前的MMC代理版本 |您需要将代理至少升级到 |代理文件名
| 3.1.X  | {3.1.X {3}} 3.1.4  | `mmc-agent-mule3-app-3.1.4.zip`
| 3.2.x中 | {3.2.x中{3}} 3.2.4  | `mmc-agent-mule3-app-3.2.4.zip`
| 3.x  | 3.3.2或以上 |无需采取任何行动 | 
| 3.4.x  |任何 |不需要采取任何行动 | 
|===

[WARNING]
如果升级到管理控制台3.4，则不需要，但强烈建议采取与升级到Management Console 3.4.1相同的步骤（即按照上表）。

== 升级到管理控制台3.4.2

===  Mule Agent

如果您将.war升级到版本3.4.2，并且您的Mule ESB版本早于3.4.1，则可能需要升级您的Management Console代理，如上表所述（MMC 3.4.1的相同表）。

===  MMC 3.4.2 .war文件

MMC 3.4.2有两个版本，分别在两个独立的.war文件中发布：

*  `mmc-console-3.4.2.war`
*  `mmc-console-sqlserver-3.4.2.war`  - 包括对MS-SQL Server的支持

有关要下载哪个.war文件的完整详细信息，请咨询 link:/mule-management-console/v/3.4/installing-or-upgrading-mule-management-console-3.4.2[安装或升级Mule管理控制台3.4.2]。

=== 数据迁移

MMC 3.4.2的.war文件与以前版本的MMC的.war文件*_not_*兼容，在以下情况下：

* 如果旧版本的MMC使用LDAP进行用户身份验证
* 如果旧版本的MMC持久保存环境或将数据跟踪到外部数据库

在上述两种情况下，您都需要迁移配置数据以保留您的设置。

如果您当前的MMC安装不使用LDAP进行用户身份验证，也未配置为将数据保存在外部数据库上，则无需采取进一步操作即可升级到MMC 3.4.2。

以下文档页面提供了将数据迁移到MMC 3.4.2所需的步骤：

*  link:/mule-management-console/v/3.4/installing-or-upgrading-mule-management-console-3.4.2[安装或升级Mule管理控制台3.4.2]
*  link:/mule-management-console/v/3.4/upgrading-to-mmc-3.4.2-with-ldap[使用LDAP升级到MMC 3.4.2]
*  link:/mule-management-console/v/3.4/upgrading-to-mmc-3.4.2-with-an-external-database[使用外部数据库升级到MMC 3.4.2]
