=  OAS / RAML导入和导出参考

_Requires November 2017 Release_

在为API规范或API片段创建项目后，可以访问“文件”下拉菜单以导入单个或多个压缩的RAML，OAS或OAS规范。您还可以导入除.raml以外的扩展名的文件，例如user-examples.json，以及ZIP格式的压缩RAML和JSON文件。

Design Center支持高达10MB的文件。

您可以压缩并将所有Design Center项目文件导出到外部位置。您可以将该zip文件导入到Design Center或Studio中。

==  OAS / RAML转换限制

*  OAS 2.0不支持所有RAML 1.0功能。
* 导入包含在zip中的引用JSON文件的主OAS不受支持。
+
主OAS转换为RAML。其他引用的文件夹和JSON文件按原样复制到项目中（未转换）。请参阅下面的解决方法。
* 您无法将RAML片段导出到OAS。您只能导出用`#%RAML 1.0`定义的RAML规范。

要导入具有对JSON文件的引用的主OAS，请使用以下解决方法之一：

* 在压缩主OAS和相关文件之前，将相关的JSON文件转换为RAML格式，然后导入压缩文件。
* 首先，导入仅具有主OAS文件的OAS zip。接下来，将依赖的JSON文件一次一个地导入到API设计项目中。

=== 将OAS导入RAML

当您将OAS 2.0导入到RAML 1.0时，该过程定义了注释以防止丢失任何没有RAML对等物的语义。

=== 将RAML导出到OAS

在将RAML文档转换为OAS 2.0之前，转换器解析了以下语义：

* 性状

* 资源类型

* 包括

* 库

在RAML到OAS 2.0转换期间，该工具不会保留所有语义数据。有关更多信息，请参见RAML 1.0→OAS Complete Functional Specification中的“翻译之间的丢失语义”一节：

`+https://github.com/mulesoft/oas-raml-converter+`

完成转换后，输出结果是单个OAS文档。

== 导入OAS 2.0规范

Design Center支持从文件系统导入JSON或ZIP格式的OAS 2.0规范。异常：不支持导入在JSON文件中嵌入引用的OAS zip。有关更多信息，请参阅上面的限制和解决方法。您还可以从互联网导入OAS 2.0规范。在尝试将文档导入Design Center项目之前，首先使用以下URL中的验证器验证OAS文档：

`+http://bigstickcarpet.com/swagger-parser+`

接下来，使用“文件”面板中的下拉菜单导入OAS 2.0。在导入中，从下拉列表中选择OAS File或OAS Url。最后，选择要上传的OAS `.zip`或`.json`文件，或者在文本输入框中输入网址。转换后的OAS代码出现在编辑器面板的RAML中。

由于导入OAS验证器验证的OAS文档，用户报告了问题。 RAML验证要求比Swagger解析器更严格。另外，当您将OAS 2.0导入到RAML 1.0时，将定义注释以防止丢失任何没有RAML对象的语义。注释可能不受支持。

== 另请参阅

*  link:/design-center/v/1.0/designing-api-about[关于设计基于RAML的API]
*  link:/design-center/v/1.0/design-import-oas-task[导入OAS]





