= 配置Maven POM文件和设置

本页面包含有关配置Maven安装以成功使用Mule的说明。它涵盖了如何维护您的POM文件以添加或调整依赖关系，并指向正确的MuleSoft存储库，以及如何使用Enterprise Repo的凭证和配置文件访问和调整您的settings.xml文件。

== 假设

本文档假定您正在使用Anypoint™Studio之外的Maven，因此将使用原型来构建Mule应用程序。请参阅 link:/mule-user-guide/v/3.5/using-maven-with-mule[和Mule一起使用Maven]，了解如何使用Maven管理您的Mule项目。

[NOTE]
请注意，如果您是 link:/mule-user-guide/v/3.5/using-maven-with-mule[通过Studio与Maven合作]，则通常不需要修改settings.xml文件，因为Studio会跟踪您需要的依赖关系，并尝试在应用程序的关联POM文件中为您进行管理。如果发生依赖性错误，您可能需要手动调整POM文件，并且在某些情况下，可以在settings.xml中进行调整。有关具体说明，请参阅Maven文档中的 http://maven.apache.org/pom.html[的pom.xml]和 http://maven.apache.org/settings.html[的settings.xml]。

== 设置步骤

在开始使用Maven从命令行使用原型创建新的Mule项目之前，您需要：

. 确保Maven安装在不包含空格的目录中。
. 为您的应用程序创建或维护您已创建的`pom.xml`文件，以包含对MuleSoft开放源代码库以及任何需要包含在每个应用程序中的连接器，模块或其他扩展的引用。
.  _仅限企业用户：_修改`settings.xml`文件以指向企业客户存储库并提供您的凭据。

=== 检查您的安装

默认情况下，您的本地Maven安装将配置文件存储在Unix和Mac上的`$HOME/.m2`（`~/.m2`目录中; Windows中的`C:\Documents and Settings\<user>\.m2`）。请记住，在Linux或Mac中`.m2`是一个隐藏文件夹。

如果您要在Studio外部构建项目，则需要手动添加一些无法通过Maven公开访问的必需JAR。但是，在您的`$MULE_HOME/bin`目录中可用的命令行工具`populate_m2_repo`可以获取所有关联的文件。注意：避免在项目中重复导致类加载错误的jar。

. 导航到`%MULE_HOME%\bin`目录（Windows），`$MULE_HOME/bin`文件夹（Linux / Unix）。
. 执行以下命令之一：

 ** `./populate_m2_repo <my-test-m2-repository>` (Linux/Unix)
**  `populate_m2_repo.cmd <my-test-m2-repository>`（Windows）

（请注意，`my-m2-test-repository`不得在当前目录中存在。）

请注意，如果您的`MULE_HOME`设置为包含空格的路径，则可能会遇到错误。建议您选择不包含空格的`MULE_HOME`位置。

=== 管理您的POM文件

每个Maven项目都有一个POM（项目对象模型）文件，它由项目的XML表示组成。详细了解 http://maven.apache.org/pom.html[Maven文档]中的POM文件。

在创建Maven项目时，无论是使用Studio还是通过使用Maven原型的命令行，都会生成POM文件。导航到该POM文件并打开它以检查其内容或进行手动调整（如有必要）。

如果它们不存在，请添加对开源MuleSoft存储库的引用。

[source, xml, linenums]
----
<repositories>
...
    <repository>
        <id>mulesoft-releases</id>
        <name>MuleSoft Repository</name>
        <url>https://repository-master.mulesoft.org/releases/</url>
        <layout>default</layout>
    </repository>
    <repository>
        <id>mulesoft-snapshots</id>
        <name>MuleSoft Snapshot Repository</name>
        <url>https://repository-master.mulesoft.org/snapshots/</url>
        <layout>default</layout>
    </repository>
...
</repositories>
----

如果您需要的依赖关系尚未存在，请按所示添加它们。

[source, xml, linenums]
----
<dependencies>
...
    <dependency>
        <groupId>GROUP ID OF DEPENDENCY</groupId>
        <artifactId>ARTIFACT ID OF DEPENDENCY</artifactId>
        <version>VERSION OF DEPENDENCY</version>
    </dependency>
...
<dependencies>
----

例如，如果您要添加Salesforce连接器的依赖项，请执行以下操作：

[source, xml, linenums]
----
<dependencies>
...
    <dependency>
        <groupId>org.mule.modules</groupId>
        <artifactId>mule-module-sfdc</artifactId>
        <version>LATEST</version>
    </dependency>
...
<dependencies>
----

不确定您需要的连接器的依赖性详细信息是什么？请参阅 http://www.mulesoft.org/connectors[连接器网站]上特定于连接器的Maven说明。

=== 引用MuleSoft的企业存储库

＃*_Enterprise_*＃

本节假定您已获得https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/ [MuleSoft Enterprise Maven客户资源库]的 http://www.mulesoft.com/mule-esb-support-esb-license-subscription[企业许可证]和凭据，该凭据允许您访问Mule Enterprise模块，连接器以及未包含在试用版或社区版本中的其他组件。如果您是MuleSoft客户并且无权访问存储库，请联系https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft支持]。

要配置Maven访问MuleSoft客户信息库，您需要对`settings.xml`配置文件进行添加。您的`.m2`目录可能已经包含名为`settings.xml`的配置文件。请注意，该文件不是强制性的。如果文件不存在，Maven将使用默认参数。如果您根本没有`settings.xml`文件，请在`~/.m2`文件夹中创建它。详细了解 http://maven.apache.org/settings.html[Maven文档]中的`settings.xml`文件。

. 打开文件<`USER_HOME> /。m2 / settings.xml进行编辑。
. 将以下内容添加到`servers`部分。
+

[source, xml, linenums]
----
<server>
 
    <id>MuleRepository</id>
    <username>YOUR_ID</username>
    <password>YOUR_PASSWORD</password>
 
</server>
----

. 将以下内容添加到`profiles`部分：
+

[source, xml, linenums]
----
<profile>
 
    <id>Mule</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <repositories>
        <repository>
            <id>MuleRepository</id>
            <name>MuleRepository</name>
            <url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
 
</profile>
----

== 另请参阅

* 详细了解 link:/mule-user-guide/v/3.5/using-maven-with-mule[和Mule一起使用Maven]。
* 跟随 link:/mule-user-guide/v/3.5/building-a-mule-application-with-maven-in-studio[在Studio中使用Maven构建一个Mule应用程序]一起演示使用Maven创建，管理和部署Mule项目的端到端体验。
* 详细了解 link:/apikit/creating-an-apikit-project-with-maven[用Maven创建一个APIkit项目]。
