= 手动创建和管理群集

_ *Enterprise Edition* _

有两种方法可以创建和管理群集：

* 使用管理控制台的图形界面
手动使用配置文件* 

本页介绍手动创建和配置群集。如果要使用管理控制台的图形界面创建和管理群集，请参阅 link:/mule-management-console/v/3.7/creating-or-disbanding-a-cluster[创建或解散群集]。

[CAUTION]
*Do not attempt mixed management of clusters* +
 +
如果您手动创建集群，请勿尝试通过管理控制台进行管理。管理控制台无法识别您手动创建的群集，并覆盖群集配置。

[NOTE]
集群中的所有节点必须具有相同的代理版本。

== 手动创建群集

按照以下过程使用配置文件手动创建群集。

. 确保节点未运行，即Mule ESB Server已停止。
. 在节点的`$MULE_HOME/.mule`目录内创建一个名为`mule-cluster.properties`的文件。
. 使用参数=值对编辑文件，每行一个。看下面的例子。
+
[source, code, linenums]
----
...
mule.cluster.nodes=192.168.10.21,192.168.10.22,192.168.10.23
mule.cluster.multicastenabled=false
...
----

. 对您希望在群集中的所有Mule服务器重复此过程。
. 启动节点中的Mule服务器。

有关可用参数的完整列表，请参阅<<Cluster Configuration Parameters>>。

== 手动管理群集

手动管理群集仅适用于手动创建的群集，这些群集不由Mule管理控制台管理。

要手动更改群集节点的配置，请按照下列步骤操作：

. 停止节点的Mule ESB服务器。
. 根据需要编辑节点的`mule-cluster.properties`，然后保存该文件。
. 重新启动节点的Mule ESB服务器。

[CAUTION]
*Ensure consistency across nodes* +
 +
确保您在配置文件中应用的选项对所有群集节点均有效。如果不这样做，可能会导致您中断群集配置并无意中禁用群集。


== 群集配置参数

下表列出了`mule-cluster.properties`文件的参数。

[%header,cols="2*"]
|===
|属性名称 |说明
一个| `mule.clusterId`
| *Mandatory.*集群的唯一标识符。它可以是任何字母数字字符串。
一个| `mule.clusterNodeId`
| *Mandatory.*集群中节点的唯一标识。它可以是1到集群中节点数量之间的任何整数。
| `mule.cluster.networkinterfaces` a |
由Hazelcast使用的逗号分隔的接口列表。通配符支持，如下所示。 +
[source, code, linenums]
----
192.168.1.*,192.168.100.25
----
| `mule.cluster.nodes` a |属于集群的节点，格式为`<host:port>`，例如`172.16.9.24:9000`。只指定一个IP地址可以使服务器加入群集。

端口号是可选的;如果未设置，则默认值为5701.要包含多个主机，请创建一个以逗号分隔的列表。

该选项使用指定的固定IP地址配置群集。如果您不依赖多播进行集群节点发现，请使用此选项。如果使用此选项，请将`mule.cluster.multicastenabled`设置为`false`（请参阅此表中的下一项）。

例子：

监听端口9000的两个节点：

[source, code, linenums]
----
172.16.9.24:9000,172.16.9.51:9000
----

侦听端口5701的两个节点：

[source, code, linenums]
----
192.168.1.19,192.168.1.20
----

| `mule.cluster.multicastenabled`  | *(Boolean)*启用/禁用多播。如果使用固定IP地址进行集群节点发现，请设置为`false`（请参阅上面的选项`mule.cluster.nodes`）。
| `mule.cluster.multicastgroup`  |要使用的多播组IP地址。
| `mule.cluster.multicastport`  |要使用的多播端口号。
|===

