使用Mule了解配置模式= 
:keywords: anypoint studio, studio, mule esb, configuration patterns

== 流和配置模式

在Mule 3中，创建消息处理流程有两种选择：

*  Mule 3中的新功能是最强大和灵活的选择。您可以从Mule提供的所有消息处理器中进行选择，包括过滤器，变换器，路由器，组件和其他，以及创建自己的，并将它们组合起来，但是您希望实现您所需的逻辑。

* 配置模式，在设计上不如其他模式。他们改为易于使用而设计。今天存在的四种配置模式使得人们始终做到简单，易于理解和快速创建。

简而言之，如果其中一种配置模式解决了您的问题，请使用它。这就像使用一个库类来解决编程问题，而不是编写一个与之重复的新类。如果您的问题与某个配置模式不匹配，请使用流程。

== 配置模式：

Mule目前有四种配置模式。所有这些都在模式名称空间中。

=== 桥

网桥模式用于桥接入站和出站端点。以下是一个桥接http和vm端点的示例：

[source,xml, linenums]
----
<pattern:bridge name="request-response-bridge"
        inboundAddress="http://localhost:8080/orderService"
        outboundAddress="jms://orderQueue" />
----

这个例子说明了最小配置的目标：除了绝对需要的东西外，什么都不需要配置。要详细了解桥接模式的功能，请参阅 link:/mule-user-guide/v/3.5/bridge-pattern[桥梁模式]，

=== 简单服务

简单的服务模式用于将组件公开为请求响应服务。支持几种类型的组件：

* 的POJO
*  JAX-WS服务
*  JAX-RS服务
*  JAXB和XPath处理组件

下面是一个简单的例子，它再次显示了最小配置，在这种情况下将POJO作为服务公开：

[source,xml, linenums]
----
<pattern:simple-service name="maths-service"
                address="vm://maths.in"
                component-class="org.mule.tck.services.SimpleMathsComponent" />
----

要详细了解简单服务模式的功能，请参阅 link:/mule-user-guide/v/3.5/simple-service-pattern[简单的服务模式]，

=== 验证器模式

Validator模式的工作是确保消息在发送之前被格式化。这种模式不仅展示了最小配置，还展示了关注点分离：不同的配置对象负责

* 验证输入
* 定义返回给调用者的正面和负面状态消息
* 声明发送格式正确的消息的位置。

这里有一个简单的例子来说明所有这些：

[source,xml, linenums]
----
<pattern:validator name="integer-validator"
           inboundAddress="vm://validator.in"
           ackExpression="#[string:GOOD:#[message:payload]@#[context:serviceName]]"
           nackExpression="#[string:BAD:#[message:payload]@#[context:serviceName]]"
           outboundAddress="vm://test-service.in">
  <payload-type-filter expectedType="java.lang.Integer"/>
</pattern:validator>
----

过滤器验证消息是一个整数，ack和nack表达式定义正面和负面状态消息，并且地址声明有效消息发送的位置。要详细了解验证程序模式的功能，请参阅 link:/mule-user-guide/v/3.5/validator-pattern[验证器模式]。

===  Web服务代理

Web服务代理模式在由Mule服务的端点上为Web服务创建代理。此端点将为该服务通告WSDL，并将服务的地址重写为指向代理。这里有一个简单的例子：

[source,xml, linenums]
----
<pattern:proxy name="weather-forecast-ws-proxy"
          inboundAddress="http://localhost:8090/weather-forecast"
          outboundAddress="http://ws.acme.com:6090/weather-forecast" />
----

可以从“ http:/ /localhost:8090/weather-forecast?wsdl` will make the service appaer to be at `http:/ /localhost:8090/weather-forecast`. To learn more about the capabilities of the web service proxy pattern, see link:/mule-user-guide/v/3.5/web-service-proxy-pattern[Web服务代理模式]”获取的WSDL
