= 升级管理控制台

*_Enterprise_*

*_* MMC版本3.5.0 *_*

MMC代理和.war文件可通过 http://www.mulesoft.com/support-login[MuleSoft客户门户]获取。强烈建议升级到最新版本的MMC。

[NOTE]
从Mule ESB 3.4.0开始，MMC代理捆绑了Mule ESB Enterprise运行时下载。

== 概述

升级到MMC 3.5.0的最简单和推荐的方法是进行干净安装。根据您当前的MMC版本进行干净安装可以避免跟踪迁移路径。

如果您没有执行全新安装的选项，升级到MMC 3.5.0所需的步骤取决于您当前的MMC版本。

MMC 3.4.2引入了一种新的简化配置，用于保存外部数据库的数据并通过LDAP管理用户。这个新的配置也被MMC 3.5.0使用。这意味着如果您的当前MMC版本早于3.4.2，并且您使用外部数据库进行数据持久性和/或使用LDAP来管理MMC用户，则需要将当前配置迁移到3.4中引入的新配置。 2。

此外，如果从MMC 3.4.0或3.4.1升级，则可能需要升级MMC代理。

MMC 3.5.0引入了对存储Business Events数据的其中一个表的更改。升级到MMC 3.5.0之前，您需要在数据库上运行迁移脚本，以保留Business Events数据。如果您的当前MMC版本是3.4.2，并且您在MS SQL Server上保留Business Events数据，则这不适用。

下表提供了每个MMC版本的详细信息。

[%header,cols="2*"]
|===
|当前MMC版本 |升级到3.5.0所需的步骤
| *Clean install* a |
* 如果要在外部数据库上保留MMC数据，请编辑MMC配置文件以包含数据库连接信息，例如用户，主机等。有关详细信息，请参阅 link:/mule-management-console/v/3.5/persisting-mmc-data-on-external-databases[在外部数据库上保留MMC数据]
* 如果通过LDAP管理MMC用户，请编辑MMC配置文件以包含LDAP信息，例如主机，连接参数等。有关详细信息，请参阅 link:/mule-management-console/v/3.4/setting-up-and-managing-users-via-ldap[通过LDAP设置和管理用户]

| *Earlier than 3.4.x* a |
* 按照升级MMC代理所需的步骤进行操作
* 如果使用外部数据库，请按照 link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-an-external-database[使用外部数据库升级到MMC 3.5.0]所需的步骤进行操作
* 如果在MMC的H2默认内部数据库或外部数据库上保留Business Events，请运行相关的 link:/mule-management-console/v/3.5/migration-scripts-for-business-events[Business Events的迁移脚本]
* 如果通过LDAP管理MMC用户，请按 link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-ldap[使用LDAP升级到MMC 3.5.0]中所述迁移您的MMC LDAP配置

| *3.4.0 and 3.4.1* a |
* 如果使用外部数据库，请按照 link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-an-external-database[使用外部数据库升级到MMC 3.5.0]所需的步骤进行操作
* 如果在MMC的H2默认内部数据库或外部数据库上保留Business Events，请运行相关的 link:/mule-management-console/v/3.5/migration-scripts-for-business-events[Business Events的迁移脚本]
* 如果通过LDAP管理MMC用户，请按 link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-ldap[使用LDAP升级到MMC 3.5.0]中所述迁移您的MMC LDAP配置

| *3.4.1 for MS SQL Server* a |
* 按照 link:/mule-management-console/v/3.5/upgrading-from-mmc-3.4.1-for-ms-sql-server-to-mmc-3.5.0-for-ms-sql-server[从MS-SQL Server的MMC 3.4.1升级到MS-SQL Server的MMC 3.5.0]所需的步骤进行操作
* 如果通过LDAP管理MMC用户，请按 link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-ldap[使用LDAP升级到MMC 3.5.0]中所述迁移您的MMC LDAP配置

| *3.4.2* a |
* 如果将数据保存在外部数据库上，请将包含数据库连接信息的文件复制到3.5.0安装中
* 如果在MMC的H2默认内部数据库或MS SQL Server以外的外部数据库上保留Business Events，请运行相关的 link:/mule-management-console/v/3.5/migration-scripts-for-business-events[Business Events的迁移脚本]
* 如果通过LDAP管理MMC用户，请将相关的配置文件复制到您的3.5.0安装中

| *3.4.2 for MS SQL Server* a |
* 将包含数据库连接信息的文件复制到3.5.0安装中
* 如果通过LDAP管理MMC用户，请将相关的配置文件复制到您的3.5.0安装中

|===

[TIP]
====
*If using LDAP or External DBs* +

如果您当前的MMC版本<3.4.2，并且您：

* 使用LDAP来管理MMC用户，或
* 使用外部数据库来保存MMC数据，

您可以访问描述 link:/mule-management-console/v/3.5/configuration-files-for-ldap-and-external-dbs-in-mmc-before-and-after-3.4.2[用于LDAP和MMC 3.4.1和MMC 3.4.2或更高版本中的外部DB的配置文件]的快速指南。或者，您可以访问以下步骤中的分步说明：

*  link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-an-external-database[使用外部数据库升级到MMC 3.5.0]
*  link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-ldap[使用LDAP升级到MMC 3.5.0]
====

== 确定您的MMC版本

您可以通过登录控制台并点击屏幕右下方的*About Mule ESB Enterprise*来确定当前运行的MMC .war文件的版本。

[NOTE]
在所有情况下，强烈建议升级到最新版本的管理控制台。

== 升级

本节包含与早期版本MMC相关的升级信息：

*  <<MMC 3.4.0 and 3.4.1 to MMC 3.5.0>>
*  MMC 3.4.1修补MS SQL Server到MMC 3.5.0
*  <<MMC 3.4.2 for MS SQL Server to MMC 3.5.0>>

===  MMC 3.4.0和3.4.1到MMC 3.5.0

如果将.war升级到版本3.5.0，并且Mule ESB版本早于3.4.1，则可能需要升级Management Console代理，如下所述。

如果您要将.war升级到版本3.5.0，并且您的Mule ESB版本是3.4.1或更高版本，则无需升级Management Console代理。

[%header%autowidth.spread]
|===
|您的Mule ESB版本 |您当前的MMC代理版本 |您需要将代理至少升级到 |代理文件名
| {3.1.X {1}} 3.1.X  | {3.1.4 {3}} mmc-agent-mule3-app-3.1.4.zip
| {3.2.x中{1}} 3.2.x中 | {3.2.4 {3}} mmc-agent-mule3-app-3.2.4.zip
| 3.x  | 3.3.2或以上 |无需采取任何行动 | 
| 3.4.x  |任何 |不需要采取任何行动 | 
|===

===  MMC 3.4.1用于MS SQL Server到MMC 3.5.0

MMC 3.4.2引入了一个新的大大简化的配置，用于保存外部数据库的数据。因此，为了从MMC 3.4.1升级到3.5.0，您需要先将您的配置文件迁移到3.4.2中引入的新格式。

link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-an-external-database[使用外部数据库升级到MMC 3.5.0]中介绍了迁移您的配置文件。升级到3.4.2和3.5.0的过程是相同的。

迁移配置文件后，您需要在目标MS SQL数据库上运行迁移脚本。此过程在 link:/mule-management-console/v/3.5/upgrading-from-mmc-3.4.1-for-ms-sql-server-to-mmc-3.5.0-for-ms-sql-server[从MS-SQL Server的MMC 3.4.1升级到MS-SQL Server的MMC 3.5.0]中进行了介绍。

最后，如果您通过LDAP管理MMC用户，则需要按照 link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-ldap[使用LDAP升级到MMC 3.5.0]中所述迁移MMC LDAP配置。

完整的步骤顺序是：

. 下载MMC 3.5.0。
. 停止您的MMC 3.4.1 MS SQL服务器。
. 在MMC 3.5.0中，修改外部数据持久性的配置，如 link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-an-external-database[使用外部数据库升级到MMC 3.5.0]中所述。
. 如果通过LDAP管理MMC用户，请按照 link:/mule-management-console/v/3.5/upgrading-to-mmc-3.5.0-with-ldap[使用LDAP升级到MMC 3.5.0]中所述修改LDAP的配置。如果不是通过LDAP管理MMC用户，请跳过此步骤。
. 在MS SQL服务器上的目标数据库上，按照 link:/mule-management-console/v/3.5/upgrading-from-mmc-3.4.1-for-ms-sql-server-to-mmc-3.5.0-for-ms-sql-server[从MS-SQL Server的MMC 3.4.1升级到MS-SQL Server的MMC 3.5.0]中所述运行SQL迁移脚本。
. 启动MMC 3.5.0。

===  MMC 3.4.2用于MS SQL Server到MMC 3.5.0

您需要将数据库连接信息（数据库主机，用户凭证等）从3.4.2复制到3.5.0安装。有关详细信息，请参阅使用外部数据库的MMC 3.4.2至3.5.0。

===  MMC 3.4.2到MMC 3.5.0

如果从MMC 3.4.2升级到3.5.0，如果满足以下两个条件之一，则需要在用于存储Business Events数据的数据库上运行SQL迁移脚本：

* 您在MMC的内部H2数据库中保留Business Events数据（默认值）
* 您正在将Business Events数据保存在除MS SQL Server以外的任何外部数据库中

您必须在首次运行MMC 3.5.0之前运行此脚本。有关说明和要运行的SQL脚本，请参阅 link:/mule-management-console/v/3.5/migration-scripts-for-business-events[商业活动迁移脚本]。

带有外部数据库的MMC 3.5.2到MMC 3.5.0的===  MMC

MMC 3.4.2引入了一个新的配置来保存外部数据库上的数据。 MMC 3.5.0也使用此配置，因此如果从3.4.2升级到3.5.0，则不需要迁移到新配置。但是，您需要执行两个步骤：

. 在`<MMC_HOME>/WEB-INF/web.xml`中激活外部数据库的Spring配置文件
. 将数据库连接信息（主机，用户凭证等）复制到3.5.0安装。为此，您可以复制3.4.2安装中的文件`<MMC_HOME>/WEB-INF/classes/META-INF/databases/<your_database_file>`。此文件的实际名称取决于您所持有的数据类型（环境或跟踪）以及您正在使用的外部数据库。例如，如果将环境数据保存到Oracle，则正确的文件是`mmc-oracle.properties`。

有关这两个文件的详细信息，请参阅以下部分。

==== 文件：`<MMC_HOME>/WEB-INF/web.xml`

此文件定义了MMC用来存储其数据的内部或外部数据库。该定义存储在`spring.profiles.active`部分，其默认值如下所示。

[source, xml, linenums]
----
<context-param>
    <param-name>spring.profiles.active</param-name>
    <param-value>tracking-h2,env-derby</param-value>
</context-param>
----

要在MMC 3.5.0中为外部数据库激活配置文件，可以手动将值添加到上面显示的部分，或从3.4.2安装中复制整个`web.xml`文件。

==== 文件：`<MMC_HOME>/WEB-INF/classes/META-INF/databases/<type of data>-<database name>.properties`

数据类型可以是`mmc`（适用于MMC环境数据）或`tracking-persistence`（适用于Business Events）。下面显示了可用文件的完整列表。

[source, code, linenums]
----
mmc-db2.properties
mmc-derby.properties
mmc-mssql.properties
mmc-mysql.properties
mmc-oracle.properties
mmc-postgres.properties
tracking-persistence-db2.properties
tracking-persistence-h2.properties
tracking-persistence-mssql.properties
tracking-persistence-mysql.properties
tracking-persistence-oracle.properties
tracking-persistence-postgres.properties
----

例如，文件`mmc-oracle.properties`定义了用于在外部Oracle数据库上保留MMC环境数据的配置;文件`tracking-persistence-postgres.properties`定义了用于在外部Postgres数据库中保留Business Events数据的配置等。

您可以将整个相关文件从MMC 3.4.2复制到3.5.0。

===  MMC 3.4.2到MMC 3.5.0使用LDAP

MMC 3.4.2引入了一个用于通过LDAP管理用户的新配置。 MMC 3.5.0也使用此配置，因此如果从3.4.2升级到3.5.0，则不需要迁移到新配置。但是，您需要执行两个步骤：

. 在`<MMC_HOME>/WEB-INF/web.xml`中激活LDAP Spring配置文件
. 将LDAP连接信息（LDAP主机，MMC凭证等）复制到3.5.0安装。为此，您可以复制3.4.2安装中的文件`<MMC_HOME>/WEB-INF/classes/META-INF/mmc-ldap.properties`

下面提供了有关LDAP配置的详细信息。

==== 文件：`<MMC_HOME>/WEB-INF/web.xml`

此文件定义了LDAP配置文件是否处于活动状态。定义存储在`spring.profiles.active`部分，如下所示。

[source, xml, linenums]
----
<context-param>
...
    <param-name>spring.profiles.active</param-name>
    <param-value>tracking-h2,env-derby,ldap</param-value>
</context-param>
----

您可以在MMC 3.5.0中手动将`ldap`参数添加到此文件，或者将整个文件从MMC 3.4.2复制到3.5.0。

==== 文件：`<MMC_HOME>/WEB-INF/classes/META-INF/mmc-ldap.properties`

这是MMC的LDAP配置文件。它除以`LDAP CONNECTION`，`MMC AUTHENTICATION`等部分，并包含广泛的评论。从MMC 3.4.2升级到3.5.0时，您可以简单地将文件从3.4.2复制到3.5.0。

== 另请参阅

* 访问用于为外部数据库配置MMC 3.4.2及更高版本的 link:/mule-management-console/v/3.5/configuring-mmc-for-external-databases-quick-reference[快速参考]
* 了解如何在MMC 3.4.2及更高版本中 link:/mule-management-console/v/3.5/encrypting-ldap-and-database-passwords-in-mmc[加密LDAP和数据库密码]
