= 关于作用域之前/之后

与其他测试框架一样，MUnit提供了围绕测试套件概念的特定功能。 +
特别是，它提供了一组范围，允许您添加要在整个MUnit测试或MUnit Suite执行之前和/或之后运行的处理或操作：

套件范围之前和之后* 。
测试范围之前和之后* 。

每个组件的ID空间在所有应用程序中必须是唯一的。 +
这意味着在作用域之前和之后无法在它们之间共享相同的名称，也没有与应用程序中的任何流相同的名称。


== 关于套件范围之前

MUnit Before Suite包含旨在在整个套件之前执行的代码。
Before Suite有一个执行规则：在所有测试之前运行，只运行一次。

例如，假设您有一个包含四个测试的MUnit测试套件文件。 MUnit Before Suite中的代码只运行一次，然后进行四次测试。

[NOTE]
每个MUnit测试套件只能使用一个Before Suite范围。

[source, xml, linenums]
在Suite例子之前
----
<munit:before-suite name="before-suite" description="Executes a before suite">
  <!-- some mule code here -->
</munit:before-suite >

<munit:test name="munit.test" description="Test">
  <!-- some more mule code here -->
</munit:test>
----

请注意，`before-suite`位于MUnit测试之外。 +
在MUnit Before Suite有用的一个实例中，您需要在所有测试运行之前设置测试环境。

当您将套件放入Anypoint Studio画布中时，示波器位于MUnit测试之外。


== 关于After Suite范围

MUnit After Suite是一个范围。它可以包含在整个套件之后执行的代码。 +
After Suite有一个执行规则：在所有测试之后运行，只运行一次。

例如，假设您有一个包含四个测试的MUnit测试套件文件。 MUnit After Suite中的代码在所有测试之后运行一次。

[NOTE]
每个MUnit测试套件只能使用一个After Suite范围。

[source, xml, linenums]
.After Suite例子
----
<munit:before-suite name="before.suite" description="A description">
  <!-- some mule code here -->
</munit:before-suite >

<munit:test name="munit.test" description="Test">
  <!-- some more mule code here -->
</munit:test>

<munit:after-suite  name="after.suite" description="A description">
  <!-- some Mule code here -->
</munit:after-suite >
----

请注意，套件位于MUnit测试之外。 +
MUnit After Suite有用的一个实例是在整个测试运行后需要拆除测试环境时。

当您将套件放入Anypoint Studio画布中时，示波器位于MUnit测试之外。

== 关于测试范围之前

测试范围之前的MUnit包含旨在在每次测试之前执行的代码。 +
每个测试前的范围遵循相同的执行规则：在每次测试之前运行。

例如，假设您有一个包含四个测试的MUnit测试套件文件。 MUnit Before测试中的代码在四个测试中的每一个之前运行;它运行四次。

[NOTE]
每个MUnit测试套件只能使用一个Before Test范围。

[source, xml, linenums]
在测试例子之前
----
<munit:before-test name="before.test" description="A description">
  <!-- some mule code here -->
</munit:before-test>

<munit:test name="munit.test" description="Test">
  <!-- some more mule code here -->
</munit:test>
----

请注意，`before.test`位于MUnit测试之外。 +
在MUnit Before Suite有用的一个实例中，您需要在整个测试运行后设置测试环境。


在Anypoint Studio画布中放置预测试时，范围位于MUnit测试之外。

== 关于测试范围之后

测试范围之后的MUnit包含旨在在每次测试后执行的代码。
每个测试后的范围遵循相同的执行规则：每次测试后运行。

例如，假设您有一个包含四个测试的MUnit测试套件文件。 MUnit After Test后面的代码在四次测试之后运行;它运行四次。

[NOTE]
每个MUnit测试套件只能使用一个“测试后”范围。

[source, xml, linenums]
。测试后的例子
----
<munit:before-test name="before.test" description="A description">
  <!-- some mule code here -->
</munit:before-test>

<munit:test name="munit.test" description="Test">
  <!-- some more mule code here -->
</munit:test>

<munit:after-test  name="after.test" description="A description">
  <!-- some mule code here -->
</munit:after-test>
----

请注意，`after.test`位于MUnit测试之外。 +
其中MUnit After测试有用的一个实例是在整个测试运行后需要拆除测试环境时。

在Anypoint Studio画布中放置后续测试时，范围位于MUnit测试之外。

== 另请参阅

**  link:/munit/v/2.1/munit-suite[关于测试套件]
***  link:/munit/v/2.1/before-after-scopes-reference[范围参考前/后]
