= 可匹配的匹配器参考


==  GREATERTHAN（比较）

[NOTE]
`Comparable`是一个DataWeave类型，它表示所有可以相互比较的类型。 +
允许的原语是String，Number，Boolean，DateTime，LocalDateTime，LocalTime，Time和TimeZone，您可以传递任何原始值（如整数或日期）。

检查表达式是否大于指定值。

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::greaterThan(|2017-08-09|)]"/>
----

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::greaterThan(20)]"/>
----


==  greaterThanOrEqualTo（比较）

[NOTE]
`Comparable`是一个DataWeave类型，它表示所有可以相互比较的类型。 +
允许的原语是String，Number，Boolean，DateTime，LocalDateTime，LocalTime，Time和TimeZone

检查表达式是否大于或等于指定的值。

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::greaterThanOrEqualTo(20)]"/>
----

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::greaterThanOrEqualTo(|2017-08-09|)]"/>
----

== 每种不超过（比较）

[NOTE]
`Comparable`是一个DataWeave类型，它表示所有可以相互比较的类型。 +
允许的原语是String，Number，Boolean，DateTime，LocalDateTime，LocalTime，Time和TimeZone

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::lessThan(20)]"/>
----

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::lessThan(|2017-08-09|)]"/>
----

==  lessThanOrEqualTo（比较）

[NOTE]
`Comparable`是一个DataWeave类型，它表示所有可以相互比较的类型。 +
允许的原语是String，Number，Boolean，DateTime，LocalDateTime，LocalTime，Time和TimeZone

检查表达式是否小于或等于指定值。

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::lessThanOrEqualTo(20)]"/>
----

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::lessThanOrEqualTo(|2017-08-09|)]"/>
----

==  closeTo（Number，Number）

检查表达式是否接近第一个数字，将第二个数字用作增量值。 +
换句话说，检查表达式是否属于第一个数字+/-第二个数字定义的范围。


。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::closeTo(1, 0.01)]"/>

<!--
  This evaluates if the expression is between 0.99 (1 - 0.01) and 1.01 (1 + 0.01)
-->
----

==  equalTo（对象）

检查表达式是否等于特定值。

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::equalTo(0)]"/>
----

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[payload]"
is="#[MunitTools::equalTo('example')]"/>
----

这个匹配器也接受Dataweave对象。

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[{example1: 1 , example2: 2}]"
is="#[MunitTools::equalTo({example1: 1 , example2: 2})]"/>
----

匹配器验证键和它们各自的值是否相同。 +
匹配器中的顺序必须与表达式中的顺序相同或断言失败。

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[{example1: 1 , example2: 2}]"
is="#[MunitTools::equalTo({example2: 2 , example1: 1})]"/>

<!-- This assertion fails -->
----

。例
[source,xml,linenums]
----
<munit-tools:assert-that
expression="#[[1, 2, 3]]"
is="#[MunitTools::equalTo([3, 2, 1])]"/>

<!-- This assertion fails -->
----

== 另请参阅

*  link:/mule4-user-guide/v/4.1/dataweave-types#dw_type_comparable[DataWeave类比]
*  link:/munit/v/2.1/munit-matchers[关于MUnit Matchers]
*  link:/munit/v/2.1/core-matchers-reference[核心竞争者参考]
*  link:/munit/v/2.1/string-matchers-reference[字符串匹配器参考]
*  link:/munit/v/2.1/iterable-map-matchers-reference[Iterable和Map Matchers参考]
