= 关于Maven中的覆盖率

自MUnit 2.x以来，覆盖率报告的目标已正确地与Maven报告部分整合在一起。

[source,xml,linenums]
----
<plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <version>${project.version}</version>
    <executions>
        <execution>
            <id>test</id>
            <phase>test</phase>
            <goals>
                <goal>test</goal>
                <goal>coverage-report</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <coverage>
            <runCoverage>true</runCoverage>
            <failBuild>false</failBuild>
            <requiredApplicationCoverage>0</requiredApplicationCoverage>
            <requiredResourceCoverage>0</requiredResourceCoverage>
            <requiredFlowCoverage>0</requiredFlowCoverage>
            <formats>
                <format>console</format>
                <format>html</format>
            </formats>
        </coverage>
    </configuration>
</plugin>
----

覆盖率报告是在Maven的网站生命周期中生成的。 +
自MUnit 2.x以来，覆盖率报告生成在"coverage-report"目标期间单独运行。

启用MUnit Coverage时，您只能在控制台中看到摘要报告。 +
默认情况下，不会采取其他操作，因此它只是提供信息。

这是一个总结报告的样子：

[source,console,linenums]
----
[INFO] ===============================================================================
[INFO] 				MUnit Coverage Report
[INFO] ===============================================================================
[INFO]
[INFO] -------------------------------------------------------------------------------
[INFO] Resource File: mule-app.xml - Flows: 1 - Weight: 100.00 -  Coverage: 100.00%
[INFO] -------------------------------------------------------------------------------
[INFO]   * Flow: muleFlow - Covered (MP): 2 - Total (MP): 2 - Coverage: 100.00%
[INFO]
[INFO] ===============================================================================
[INFO] 					Summary
[INFO] ===============================================================================
[INFO]   * CMPs: 2
[INFO]   * MPs: 2
[INFO]   * Flows: 1
[INFO]   * Resources: 1
[INFO] ===============================================================================
[INFO] 				** Application Coverage: 100.00% **
[INFO] ===============================================================================
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.462 s
[INFO] Finished at: yyyy-mm-ddThh:mm:ss
[INFO] Final Memory: 20M/379M
[INFO] ------------------------------------------------------------------------
----

But a console report is not your only option.
MUnit Coverage offers three types of reports:

* Console
* HTML
* JSON

The *Console* report is printed in the console. It works with the summary report and
shows details of each resource, flow, sub-flow, and batch, and its coverage level.

The *HTML* report shows the same information, which you can view in any web browser.
To access the *HTML* report, browse your application folder structure:

* `${application.path}/target/site/munit/coverage/`

Locate the file *summary.html*, which is the starting point of the report and lets you navigate through all the data.

The *JSON* report shows the same information as the _HTML_ report, in a JSON format. +
To access the JSON report file, browse your application folder structure:

----
${application.path}/target/site/munit/coverage/munit-coverage.json
----

To enable the report generation, add the following configuration:

[source,console,linenums]
.MUnit Coverage - Report Configuration
----
<coverage>
  <runCoverage>true</runCoverage>

  <formats>
    <format>console</format>  //<1>
    <format>html</format>     //<2>
    <format>json</format>     //<3>
  </formats>
</coverage>
----
<1> Console report
<2> HTML report
<3> JSON report

TIP: You can have none, one, or all the report types added to your configuration.

To configure, for example, the JSON report generation, you need to add the following configuration in your `pom.xml` file:

[source,xml,linenums]
----
<coverage>
<runCoverage>true</runCoverage>
  <formats>
    <format>json</format>
  </formats>
</coverage>
----

One of the features of MUnit Coverage is to fail the build if a certain coverage level is not reached.

MUnit Coverage handles three different levels:

* Application
* Resource
* Flow

Here is how to define the required coverage level:

[source,xml,linenums]
.MUnit Coverage - Require Coverage
----
<coverage>
  <runCoverage>true</runCoverage>
  <failBuild>true</failBuild>

  <requiredApplicationCoverage>20</requiredApplicationCoverage>
  <requiredResourceCoverage>10</requiredResourceCoverage>
  <requiredFlowCoverage>5</requiredFlowCoverage>
</coverage>
----

TIP: Each value represents a percentage.

If you define coverage levels, but set the property `failBuild` to *false*, and if the levels are not reached, a warning shows up in the MUnit Coverage summary.

Something like this:

[source,console,linenums]
----
[INFO] ===============================================================================
[INFO] MUnit Coverage Summary
[INFO] ===============================================================================
[INFO]  * Resources: 1 - Flows: 1 - Processors: 2
[INFO]  * Application Coverage: 00.00%
[INFO]
[WARNING] ----------------------------- WARNING --------------------------------------
[WARNING]  * Application coverage is below defined limit. Required: 50.0% - Current: 00.00% //<1>
[INFO] ====================================================================================
----
<1> Warning detailing which coverage level wasn't met

TIP: If no level is defined, -1 is assumed, which indicates that the build won't fail due to low coverage.

Another feature is the ability to ignore either a flow or a file. This way, the ignored resource:

* Doesn't count as coverage data.
* Doesn't affect the overall number of message processors.
* Doesn't cause a build to fail if the flow is not tested or if the flow doesn't reach coverage metrics.

== See Also

*  link:/munit/v/2.1/munit-coverage-report[About Coverage Report]
*  link:/munit/v/2.1/coverage-studio-concept[About Coverage Report in Anypoint Studio]
