= 操作MUnit Maven插件

本部分旨在向您展示如何使用插件运行测试。

== 为Mule应用程序运行MUnit测试（MUnit Maven插件）

[source,console]
。运行单个资源Mule项目中的MUnit测试。
----
mvn clean test
----

如果您的应用程序是一个多模块应用程序：

. 确保你的mule-domain依赖项被标记为在应用程序的POM文件中提供。
+
。添加你的Mule域作为你Mule应用程序POM文件中的一个依赖项。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. 运行`mvn install`，而不是`mvn test`。
+
[source,console]
----
mvn clean install
----

== 运行特定的MUnit测试套件（MUnit Maven插件）

您可以指示MUnit Maven Plugin仅运行属于特定测试套件的测试。

为此，我们使用属性`munit.test`。

[source,console]
----
mvn clean test -Dmunit.test=<regex-test-suite>
----

如果您的应用程序是一个多模块应用程序：

. 确保你的mule-domain依赖项被标记为在应用程序的POM文件中提供。
+
。添加你的Mule域作为你Mule应用程序POM文件中的一个依赖项。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. 运行`mvn install`，而不是`mvn test`。
+
[source,console]
----
mvn clean install -Dmunit.test=<regex-test-suite>
----

属性`munit.test`接受正则表达式。该表达式应用于MUnit测试套件文件的名称。正则表达式语言是Java实现。 +
该路径相对于src / test / munit。

以下是一个有效的例子：
[source,console]
----
mvn clean test -Dmunit.test=.*my-test.*
----

您可以通过将命名约定添加到MUnit测试套件来利用此功能。

== 运行特定的MUnit测试（MUnit Maven插件）

就像你指示MUnit运行一个测试套件一样，你也可以告诉它在该测试套件中运行一个特定的测试。为此，我们再次使用属性`munit.test`，并添加一个：

[source,console]
----
mvn clean test -Dmunit.test=<regex-test-suite>#<regex-test-name>
----

如果您的应用程序是一个多模块应用程序：

. 确保你的mule-domain依赖项被标记为在应用程序的POM文件中提供。
+
。添加你的Mule域作为你Mule应用程序POM文件中的一个依赖项。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. 运行`mvn install`，而不是`mvn test`。
+
[source,console]
----
mvn clean install -Dmunit.test=<regex-test-suite>#<regex-test-name>
----

添加是特殊字符`#`。在它的右边，你应该输入测试名称。它也接受正则表达式。该表达式应用于MUnit Test的属性`name`。

以下是一个有效的例子：
[source,console]
----
mvn clean test -Dmunit.test=.*my-test.*#.*test-scenario-1.*
----

[TIP]
--
MUnit Test Suite中与正则表达式不匹配的测试被标记为*ignored*。
--

== 使用特定标记运行测试（MUnit Maven插件）

您可以选择仅运行您在一个特定标记下分组的测试。

[source,console]
----
mvn clean test -Dmunit.tags=<munit-tag>
----

如果您的应用程序是一个多模块应用程序：

. 确保你的mule-domain依赖项被标记为在应用程序的POM文件中提供。
+
。添加你的Mule域作为你Mule应用程序POM文件中的一个依赖项。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. 运行`mvn install`，而不是`mvn test`。
+
[source,console]
----
mvn clean install -Dmunit.tags=<munit-tag>
----


== 跳过所有测试（MUnit Maven插件）

在构建应用程序时，您可能想要阻止测试运行。 MUnit使用与Maven相同的机制，因此如果您想跳过测试，可以使用参数`skipTests`。

[source,console]
。滑雪测试示例
----
mvn clean package -DskipTests
----

如果您的应用程序是一个多模块应用程序：

. 确保你的mule-domain依赖项被标记为在应用程序的POM文件中提供。
+
。添加你的Mule域作为你Mule应用程序POM文件中的一个依赖项。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. 运行`mvn install`，而不是`mvn test`。
+
[source,console]
----
mvn clean install -DskipTests
----

// _COMBAK：现在没有Java测试。
// ==只跳过MUnit测试（MUnit Maven插件）
//
// MUnit还附带了另一个仅阻止MUnit测试运行的属性。
//同时允许任何其他测试（如JUnit测试）继续运行。
//
//如果您只想跳过MUnit测试，则可以使用参数`skipMunitTests`。
//
// [来源，控制台]
//跳过MUnit测试示例
// ----
// mvn clean package -DskipMunitTests
// ----
//
//如果您的应用程序是一个多模块应用程序：
//
//。确保你的mule-domain依赖被标记为你的应用程序的POM文件中提供的。
// +
//添加你的Mule域作为你Mule应用程序POM文件的一个依赖项。
// [source，xml，linenums]
// ----
// <dependency>
//     <groupId>org.mule.app</groupId>
//     <artifactId>domain-project</artifactId>
//     <version>1.0.0-SNAPSHOT</version>
//     <classifier>mule-domain</classifier>
//     <scope>provided</scope>
// </dependency>
// ----
//。运行`mvn install`，而不是`mvn test`。
// +
// [来源，控制台]
// ----
// mvn clean install -DskipMunitTests
// ----
//
//提示：属性`skipMunitTests`仅适用于基于XML的MUnit测试。

== 另请参阅

*  link:/munit/v/2.1/faq-how-to-read-munit-test-results[FAQ：如何阅读MUnit测试结果]
