= 加密MMC中的LDAP和数据库密码

＃**_Enterprise Edition** _＃

管理控制台允许您在开箱时加密MMC使用的以下密码：

用于环境数据的数据库* 
* 用于跟踪数据的数据库（Business Events）
用于MMC访问LDAP服务器的*  LDAP密码

以前版本的MMC要求您下载外部库以便加密密码并更改MMC配置文件以修改Java Bean。在MMC中，您只需通过运行提供的脚本来加密密码，并将加密结果包含在相关配置文件中。

== 假设

本文档假定您熟悉基本的 link:/mule-management-console/v/3.7/architecture-of-the-mule-management-console[Mule管理控制台的架构]。它还假定您已安装MMC版本3.5.0。 （如果您需要升级到此版本，请从 link:http://www.mulesoft.com/support-login[客户门户]下载。）

== 概述

MMC将密码存储在配置文件中，默认情况下为纯文本。在这种情况下，访问MMC所在文件系统的攻击者可以轻松读取存储的密码。加密密码可以避免这种安全风险。

MMC使用 link:http://www.jasypt.org[Jasypt]加密库进行密码加密。您可以通过运行MMC安装中包含的脚本来加密密码，如下所述。

== 加密密码

要加密密码，请在系统终端中运行相应的脚本：

*  *Unix:* `<MMC_HOME>/encrypt/encrypt.sh`
*  *Windows:* `<MMC_HOME>\encrypt\encrypt.bat`

该脚本接受几个参数，格式为`<parameter>=<value>`。

[%header%autowidth.spread]
|===
|脚本参数 |描述
| `input`  |要加密的值。这是您希望加密的实际LDAP或数据库密码。
| `password`  |用于加密`input`的字符串。这不是LDAP或数据库密码，而是用于加密密码的短语。密码本身在`input`参数中提供。
| `algorithm`  |（可选）用于加密的算法。
|===

==== 示例

[source, code, linenums]
----
./encrypt.sh input=mypassword password=mykey algorithm=PBEWithMD5AndDES
----

[WARNING]
====
MMC使用`DEFAULTPASS`作为加密密钥的默认值（您可以使用`password`参数提供此值，如上例所示）。如果更改此值，则需要使用以下参数启动MMC：

[source, code, linenums]
----
-DMMC_ENCRYPTION_KEY=<your key>
----

例如，如果在Tomcat上运行MMC，则可以修改`catalina.sh`文件以包含该参数。

有关使用自定义参数启动Mule的更多信息，请参阅 link:/mule-user-guide/v/3.8/starting-and-stopping-mule-esb[启动和停止Mule ESB]。
====

请注意，如果在Unix或基于Unix的系统上，您需要为`encrypt.sh`设置执行权限才能运行它。

[TIP]
====
*How to apply execute permissions on Unix systems*

要为`encrypt.sh`脚本设置执行权限，请完成以下步骤：

. 打开终端并以文件所有者身份或以root用户身份（根据您的系统配置使用`su`或`sudo`命令）登录系统。

. 运行以下命令：

[source, code, linenums]
----
chmod a+x <path to file>encrypt.sh
----

这将为系统上的所有用户分配执行权限。如果您希望仅为文件所有者分配权限，请改用`chmod u+x`。

*Note about Tomcat installations on some systems*

作为安全措施，在某些系统上，Tomcat用户不允许运行命令（用户的登录shell设置为`/bin/false`）。在这种情况下，您有多种选择来运行加密脚本：

* 为脚本设置全局执行权限，然后以另一个用户身份运行脚本。

* 仅为Tomcat用户设置权限，然后以root身份运行脚本。

* 作为另一个用户，复制脚本，然后运行它。

有关`chmod`命令的更多信息，请运行`man chmod`，查阅手册页。
====

运行脚本时，它将在标准输出上显示加密的密码，如下例所示。

[source, code, linenums]
----
./encrypt.sh input="mmc123" password=DEFAULTPASS

----ENVIRONMENT-----------------
Runtime: Sun Microsystems Inc. OpenJDK 64-Bit Server VM 20.0-b12

----ARGUMENTS-------------------
input: mmc123
password: DEFAULTPASS

----OUTPUT----------------------
kB0xirnPDlRXeCcHUjP7NQ==
----

Copy the encrypted output (the last line displayed above) and store it in a convenient location, such as a text file of your choosing. You will need to copy this value to the appropriate configuration file, as explained in the next section.

For more information about `encrypt.sh`, including other usage examples, see Jasypt's link:http://www.jasypt.org/cli.html[CLI Tools] page.

== Modifying the Configuration File

=== Determining Which File to Modify

MMC stores passwords in the files and directories listed below:

LDAP:

[source, xml, linenums]
----
<MMC_HOME>/WEB-INF/classes/META-INF/mmc-ldap.properties
----

Databases for persistent and tracking data:

[source, xml, linenums]
----
<MMC_HOME>/WEB-INF/classes/META-INF/databases
----

The `databases` directory contains one configuration file per supported database engine (see note below). There are two types of configuration files:

* Files for supported database engines to store MMC persistent data (created alerts, deployments, etc.) These files are named in the format `mmc-<database engine name>.properties`. For example, `mmc-postgres.properties`.

* Files for supported database engines to store transaction data (Business Events). These files are named in the format `tracking-persistence-<database engine name>.properties`. For example, `tracking-persistence-postgres.properties`.

Click to see a complete listing of the databases directory

[source, code, linenums]
----
mmc-db2.properties
mmc-derby.properties
mmc-mssql.properties
mmc-mysql.properties
mmc-oracle.properties
mmc-postgres.properties
tracking-persistence-db2.properties
tracking-persistence-h2.properties
tracking-persistence-mssql.properties
tracking-persistence-mysql.properties
tracking-persistence-oracle.properties
tracking-persistence-postgres.properties
----

[TIP]
====
By default, MMC stores persistent and transaction data on internal databases. However, you can store this data on external databases (see link:/mule-management-console/v/3.8/persisting-mmc-data-on-external-databases[Persisting MMC Data On External Databases] for details and supported database servers). If you are using MMC's internal databases, in order to encrypt your password you will need to modify the following configuration files:

* For persistent data: `mmc-derby.properties`

* For transaction data: `tracking-persistence-h2.properties`
====

=== Modifying the File

For each file that you need to modify, open it and locate one of the following lines, according to the type of data whose password you wish to encrypt:

For the _persistent data_ password:

[source, code, linenums]
----
env.password=mmc123
----

For the _transaction data_ password:

[source, code, linenums]
----
mmc.tracking.db.password=mmc123
----

For the LDAP password:

[source, code, linenums]
----
password=mmc123
----

Comment the line by adding a hash symbol (#) to the beginning of the line, for example:

[source, code, linenums]
----
# env.password=mmc123
----

Add a new line with the variable declaration (in this example, `env.password` for the password for environment data) and the encoded value of your password in the following format:

[source, code, linenums]
----
ENC("<your encoded password>")
----

For example:

[source, code, linenums]
----
env.password=ENC("kB0xirnPDlRXeCcHUjP7NQ==")
----

=== Examples of File Selections

Encrypting the password for tracking data stored on MMC's default tracking database: modify the file `<MMC_HOME>/WEB-INF/classes/META-INF/databases/tracking-persistence-h2.properties` (parameter `mmc.tracking.db.password`).

Encrypting the password for persistent data stored on MMC's default persistent data database: modify the file `<MMC_HOME>/WEB-INF/classes/META-INF/databases/mmc-derby.properties` (parameter `env.password`).

Encrypting the password for persistent data stored on an external Oracle database: modify the file `<MMC_HOME>/WEB-INF/classes/META-INF/databases/mmc-oracle.properties` (parameter `env.password`).

Encrypting the password for LDAP: modify the file `<MMC_HOME>/WEB-INF/classes/META-INF/``mmc-ldap.properties `(parameter `password`).

== See Also

* Learn how to link:/mule-management-console/v/3.8/encrypting-mmc-user-passwords[encrypt MMC User Passwords]
* Learn about link:/mule-management-console/v/3.8/persisting-mmc-data-on-external-databases[persisting MMC Data On External Databases]
* Learn how to link:/mule-management-console/v/3.3/enabling-ldap-authentication[enable LDAP Authentication] for MMC
