= 使用LDAP升级到MMC

如果要升级到最新版本的MMC，并且当前MMC安装配置为 link:/mule-management-console/v/3.8/setting-up-and-managing-users-via-ldap[通过LDAP管理用户]，则需要将现有的LDAP配置迁移到新的MMC安装。

== 迁移LDAP配置

MMC将其LDAP配置设置存储在文件`<MMC_HOME>/WEB-INF/classes/mmc-ldap.properties`中。该文件包含连接到LDAP服务器以及搜索该服务器上的用户所需的信息。

要迁移您的LDAP配置，请按照下列步骤操作：

. 展开新的MMC .war文件（例如，将其复制到Tomcat安装的`webapps`目录中），但不要运行新的MMC。
. 从旧的MMC安装中，将文件`<OLD_MMC_HOME>/WEB-INF/classes/mmc-ldap.properties`复制到`<NEW_MMC_HOME>/WEB-INF/classes/META-INF`。例如，如果您的新安装位于`/var/lib/tomcat6/mmc-console`，请将该文件复制到`/var/lib/tomcat6/mmc-console-/WEB-INF/classes/META-INF`。
+

[NOTE]
====
如果您的旧MMC安装配置为LDAP，但不包含`mmc-ldap.properties`文件，那么您通过`ldap.xml`文件配置了LDAP（这不应该是这种情况，因为此XML文件不应该是编辑）。在这种情况下，请参阅下面的<<Troubleshooting>>部分以了解有关如何继续操作的详细信息。
====

. 在新的MMC安装中，打开文件`<MMC_HOME>/WEB-INF/web.xml`并找到以下部分：
+

[source, xml, linenums]
----
<param-name>spring.profiles.active</param-name>
<param-value>tracking-h2</param-value>
----

. 将第二行修改为：
+

[source, xml, linenums]
----
<param-value>tracking-h2,ldap</param-value>
----

. 保存并关闭文件。

您现在已经迁移了您的LDAP配置，并可能启动新的MMC。

==== 故障处理

所有LDAP配置都应驻留在`mmc-ldap.properties`文件中，但即使MMC配置为使用LDAP，您也可能会发现该文件在您的安装中不存在。在这种情况下，LDAP设置驻留在文件`<MMC_HOME>/WEB-INF/classes/META-INF/ldap.xml`中。

要迁移您的LDAP设置，请执行以下步骤：

. 在您的旧MMC安装中，打开文件`<OLD_MMC_HOME>/WEB-INF/classes/META-INF/ldap.xml`。
. 在`ldap.xml`中，找到bean `propertiesLDAP`。在这个bean中，找到以下部分：
+

[source, xml, linenums]
----
<property name="properties">
            <props>
                <prop key="providerURL">ldap://192.168.1.14:389/</prop>
                <prop key="userDn">cn=mmc,dc=company,dc=com</prop>
                <prop key="password">mmcadmin</prop>
                <prop key="userSearchBaseContext">ou=ou=people,dc=company,dc=com</prop>
                <prop key="userSearchFilterExpression">(uid={0})</prop>
                <prop key="userSearchBase">ou=people,dc=company,dc=com</prop>
                <prop key="userSearchAttributeKey">objectclass</prop>
                <prop key="userSearchAttributeValue">person</prop>
                <prop key="roleDn">ou=groups,dc=company,dc=com</prop>
                <prop key="groupSearchFilter">(member={0})</prop>
                <prop key="usernameAttribute">uid</prop><!-- Set to 'SAMAccountName' for ActiveDirectory integration. -->
            </props>
        </property>
----
+

如您所见，本节包含连接到LDAP服务器并在其中搜索的设置。
. 如果需要，请将上一步中列出的设置复制到方便的位置，例如新的文本文件，因为您将在下一步中将这些设置调整为新的配置文件。
. 在新的MMC安装中，找到文件`<MMC_HOME>/WEB-INF/classes/META-INF/mmc-ldap.properties`，然后打开它进行编辑。
.  `mmc-ldap.properties`文件包含具有默认值的所有必需设置。将默认值替换为您的安装值。 （您可以在下面的可展开部分中看到随MMC提供的默认`mmc-ldap.properties`文件。）
+

*Default mmc-ldap.properties file:*
+

[source, code, linenums]
----
################ LDAP CONNECTION ########################
#change providerURL, cn, ou and dc to match your ldap tree.
#Configure the MMC user/password to use for MMC to authenticate users on login
providerURL=ldap://localhost:389
userDn=cn=mmc,ou=people,dc=mycompany,dc=com
#If you want to encrypt your password, set the value to ENC("encodedPassword").
#For encoding your password open a console and cd into the MMC install directory, cd encrypt folder
#and issue the command ./encrypt.sh input="mmc123" password=DEFAULTPASS
#where password refers to the encryption key to use and input is the value you want to encrypt.
#DEFAULTPASS is the default value set by MMC, refer to MMC docs at www.mulesoft.com for information on how
#to change that configuration value.
#password=ENC("HZe9CewttfG/PlAJSL8+KA==")
password=mmc123



################### MMC AUTHENTICATION ##################
#base context to search for users within the LDAP tree (search subtree is in true)
userSearchBaseContext=ou=people,dc=mycompany,dc=com

#A filter expression used to find entries in the LDAP database that match a particular user.
#For example, (uid={0}) looks for an entry whose uid attribute matches the user name as it was
#supplied to the console in the Username field at login
userSearchFilterExpression=(uid={0})


############### USER LISTING #############################
#The base context in the LDAP database in which the console will search for users to list in the admin pages.
#change ou and dc to match your ldap tree.
userSearchBase=ou=people,dc=mycompany,dc=com

#key-value will determine how to search for users. In the default scenario, will look for objectclass=person
#The attribute used to search for users on the LDAP server
userSearchAttributeKey=objectclass

#This is the value of the attribute used to search for users on the LDAP server.
userSearchAttributeValue=person


######### GROUP DEFINITIONS #######################
#The DN of the context used to search for groups to which the user belongs
#change ou and dc to match your ldap tree.
roleDn=ou=groups,dc=mycompany,dc=com
#groupSearchFilter=(memberUid={1})
groupSearchFilter=(member={0})
usernameAttribute=uid
----


. 保存文件`mmc-ldap.properties`。
. 在新的MMC安装中，打开文件`<MMC_HOME>/WEB-INF/web.xml`并找到以下部分：
+

[source, xml, linenums]
----
<param-name>spring.profiles.active</param-name>
<param-value>tracking-h2</param-value>
----

. 将第二行修改为：
+

[source, xml]
----
<param-value>tracking-h2,ldap</param-value>
----

. 保存并关闭文件。

您现在已经迁移了您的LDAP配置，并可能启动新的MMC。

== 另请参阅

* 阅读 link:/mule-management-console/v/3.8/configuring-mmc-for-external-databases-quick-reference[为外部数据库配置MMC]的概述，其中包括指向每个支持的数据库服务器的详细说明的链接。
* 了解如何 link:/mule-management-console/v/3.8/upgrading-to-mmc-with-an-external-database[用外部数据库升级到MMC]。
