= 使用管理控制台API

管理控制台提供了REST API，您可以通过它编程访问控制台的大部分功能。使用这些REST API，您可以：

* 注册新服务器并管理现有服务器，包括重新启动服务器。
* 管理服务器组。
* 访问和管理服务器上的文件。

有关可通过REST执行的所有操作（包括使用和输出示例）的完整详细信息，请参阅 link:/mule-management-console/v/3.8/rest-api-reference[REST API参考]。

另外，您可以使用REST API来：

* 创建或删除群集并获取有关群集的信息，以及在群集上启动，停止和重新启动应用程序
* 查找，上传和删除存储库中的应用程序
* 在服务器或集群内部署，取消部署，创建，更新和删除部署
* 管理流程，包括查找，启动和停止流程以及查找，启动和停止流程的端点

有关这些操作的详细信息，请参阅 link:/mule-management-console/v/3.8/rest-api-reference[REST API参考]。

== 概述

具象状态传输（REST）是一种软件体系结构。 REST中的一个重要概念是资源的存在，每个资源都可以使用全局标识符来引用。具体而言，数据和功能都被视为资源。通过使用REST API，您可以通过指定该功能的URL或链接来访问功能，这通常也称为方法。数据表示形式以JavaScript对象表示法（JSON）对象的形式传递给REST API方法。

简而言之，以下是您如何使用REST API：

* 设置可能需要传递给API的任何参数。您可以在JSON对象中设置参数值。
* 构建请求。该请求包含资源的完整URL，以及任何参数及其值的名称。
* 使用适当的HTTP方法调用请求：GET，PUT，DELETE或POST。
* 获取回复。如果您检索信息，请解析您所需数据的响应。如果需要，您可以将响应数据用于进一步的API请求。

您可以使用任何HTTP客户端来访问这些API。请注意，所有管理控制台API都使用JSON而不是XML作为数据格式。

如果您使用Java编程，建议您使用 link:https://wikis.oracle.com/display/Jersey/Main[泽西岛客户]。或者，对于JSON支持，请使用带有 link:https://github.com/FasterXML/jackson[杰克逊]的高性能JSON处理器的 link:http://hc.apache.org/httpclient-3.x/index.html[HttpClient的]。

[TIP]
====
link:/mule-management-console/v/3.8/rest-api-reference[REST API参考]包含管理控制台REST API上所有可用操作的完整详细信息，包括输入数据和结果的示例。
====
