= 将自定义模块添加到项目（Anypoint Studio）

您可以将您的自定义Mule模块添加到Anypoint Studio中的Mule项目中。

这些说明假设您使用Mule SDK对您的Mule模块进行了编码，并且您遵循了正确的设置步骤。 +
有关更多详细信息，请参阅 link:/mule-sdk/v/1.1/getting-started[Mule SDK介绍性说明]。

Mule模块是作为Maven项目开发的，因此您的自定义Mule模块必须安装在本地或在线Maven存储库中。

. 在您的Anypoint Studio项目中，使用groupId，artifactId和您的Mule模块版本编辑`pom.xml`文件。 +
该信息可在您的模块的`pom.xml`文件中找到。例如：
+
[source,xml,linenums]
----
<parent>
    <groupId>org.mule.extensions</groupId>
    <artifactId>mule-ee-core-modules-parent</artifactId>
    <version>1.1.0-SNAPSHOT</version>
</parent>

<groupId>com.mulesoft.mule.modules</groupId>
<artifactId>mule-secure-configuration-property-module</artifactId>
<packaging>mule-extension</packaging>
<version>1.0.0-SNAPSHOT</version>

<name>Mule Secure Configuration Property Extension</name>
<description>Mule extension for loading encrypted properties</description>
----
+
它也反映在安装Mule模块的文件夹结构中（`$MAVEN_REPOS_HOME/groupID_path/artifactId/version`）。
+
对于上面的示例，您的Anypoint Studio pom.xml文件应添加以下依赖项：
+
[source, xml, linenums]
----
<dependency>
	<groupId>com.mulesoft.mule.modules</groupId>
	<artifactId>mule-secure-configuration-property-module</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<classifier>mule-plugin</classifier>
</dependency>
----
+
请注意，`<classifier>`元素被设置为mule-plugin。这会自动将mule插件安装到项目的调色板中。
. 将您的更改保存到您的Studio项目的`pom.xml`文件中。

在Anypoint Studio下载新的依赖项后，您将在Studio调色板中看到新的Mule模块。在这个例子中，Mule Palette视图中列出了一个安全属性模块。 +
全局元素编辑器中还有一个新的安全属性配置元素，XML配置文件编辑器中提供了新的XML名称空间和xml标签。

== 另请参阅

*  link:/anypoint-studio/v/7.1/add-modules-in-studio-to[将模块添加到项目（Anypoint Studio）]
*  link:/mule-sdk/v/1.1/getting-started[开始使用Mule SDK]
