= 将Mule应用部署到CloudHub（Anypoint Studio）

==  Prerequesites

要成功地将您的Mule应用程序部署到CloudHub，请考虑以下要求：

*  HTTP侦听器流源的主机和端口号已正确配置。 +
::如果您使用HTTP侦听器作为流的源，则需要将其主机设置为*0.0.0.0*，并将其端口设置为*${http.port}*。 +
然后CloudHub在部署时动态分配端口。
* 您的所有外部类和资源都已在您的Mule应用程序的`mule-artifact.json`文件中正确声明。 +
::由于Mule 4.x类加载隔离机制，在打包和部署应用程序之前，必须在mule-artifact.json文件的"exportedPackages"和"exportedResources"字段中明确声明所有外部类和资源。 +
+
请参阅 link:/mule4-user-guide/v/4.1/how-to-export-resources[如何导出资源]任务以了解有关在Mule应用程序中使用外部资源的更多信息。

== 部署到CloudHub

. 右键单击Package Explorer视图上的项目文件夹。
. 选择Anypoint Platform，然后部署到CloudHub。 +
::如果您没有在Anypoint Studio中配置Anypoint Platform凭证，则需要在继续之前提供登录信息。
. 配置您的应用程序正在部署到的CloudHub实例。 +
:: Anypoint Studio将您的软件包名称用作CloudHub上应用程序的名称。此名称是您部署的应用程序域的一部分。 +
例如，命名您的应用程序"deployment-1"会使您的应用程序的公有领域"deployment-1.cloudhub.io"。 +
您也可以配置运行时版本。默认情况下，Studio在开发过程中使用您在项目中使用的应用程序版本。 +
为了减少兼容性风险，您应该始终部署到创建Mule项目的运行时版本或最接近的替代方案。
+
此外，您可以为将要使用的CloudHub实例配置工作者和工作人员大小的数量，为应用程序启用Insight，静态IP，配置日志级别和属性占位符。

== 重新部署到CloudHub

从Anypoint Studio首次部署应用程序之后，您可以不断修改应用程序的代码并重复上述步骤1和2来重新部署更新的应用程序。 +
当您进入CloudHub实例配置窗口时，已经为您选择了"Overwrite Existing Application"选项。这使您可以重新部署应用程序。

== 另请参阅

*  link:/anypoint-studio/v/7.1/set-credentials-in-studio-to[配置Anypoint平台凭证（Anypoint Studio）]
// _TODO：在4.1 Release之后添加到运行时管理器的链接。
