= 在调试模式下启动Mule服务器

. 要以调试模式启动服务器，请使用以下参数：+
+
[%header,cols="2*"]
|======
| {参数{1}}说明
一个|
----
-M-Dmule.debug.enable=true
----
  | *Mandatory*。在Mule中设置调试模式。首先发出这个参数。
一个|
----
-M-Dmule.debug.port=<port number>
----
  | *Optional*。设置来自Studio的传入连接的侦听端口。如果未设置，监听端口将是6666。
一个|
----
-M-Dmule.debug.suspend=true
----
  | *Optional*。在Mule中设置"suspend"模式。在暂停模式下，Mule将启动，然后立即挂起应用程序执行，直到它在调试端口上收到连接。
|======
. 要将参数传递给服务器，请遵循下面列出的两种方法之一。 +
..  *Method 1*：按照适当的顺序将参数传递给命令行上的Mule，如下例所示。
+

[source, code, linenums]
----
<$MULE_HOME>/bin/mule -M-Dmule.debug.enable=true -M-Dmule.debug.port=1234
----
+
上面显示的命令在前台启动Mule。要在前台运行时退出Mule，请按`Ctrl+C`。
+
要在后台以调试模式启动Mule，请将`start`作为`mule`命令的第一个参数，如下所示。
+

[source, code, linenums]
----
<$MULE_HOME>/bin/mule start -M-Dmule.debug.enable=true -M-Dmule.debug.port=1234
----

..  *Method 2*：将参数包含在包装器配置文件`$MULE_HOME/conf/wrapper.conf`中，如下所示。

[source, code, linenums]
----
wrapper.java.additional.4=-Dmule.debug.enable=true
wrapper.java.additional.5=-Dmule.debug.port=1234
----

在上面显示的代码中，替换参数号以反映配置文件中活动参数的数量。

在远程服务器上访问和调试应用程序之前，必须先将应用程序导出并部署到所需的Mule服务器。

. 在Studio中，单击调试图标旁边的箭头（以小昆虫表示），然后选择*Debug Configurations*。 Studio将显示*Debug Configurations*窗口。
. 在窗口的左侧窗格中，点击*Remote Mule Application*。
. 单击新配置图标（用带黄色加号的空白页表示）以添加新配置。
. 输入配置所需的参数：

此配置的*  *Name:*名称
*  *Host:*指示远程Mule服务器的位置
*  *Port:*指示远程Mule服务器的侦听端口

您可以使用*Remote Mule Application*在远程Mule服务器上调试应用程序。为此，您必须以调试模式启动Mule服务器，然后从Studio连接到服务器。

[NOTE]
====
* 当您在调试模式下启动Mule时，您在该服务器中启动的_all_应用程序将以调试模式运行。
* 远程调试不适用于群集。
====


== 另请参阅

*  link:/anypoint-studio/v/7.1/debugger-perspective-concept[关于Mule调试器的观点]
*  link:/anypoint-studio/v/7.1/to-set-breakpoints[设置断点]
