=  Anypoint访问管理发行说明
:keywords: release notes, access management, anypoint platform, permissions, entitlements, roles, users, administrator, gear icon

2017年11月18日== 
*_Version 0.29.0_*

Access Management v0.29.0允许外部Anypoint用户在公共API门户上创建客户端应用程序。这些外部用户将显示在Access Management UI用户部分的外部用户的新选项卡下。此版本还包括改进平台性能的基础结构更改。

=== 硬件和软件要求

不用找了。

=== 兼容性

NA

=== 已弃用的功能或功能

没有。

=== 已解决的问题

没有。

=== 移民指导

不需要迁移。

2017年10月7日== 
*_Version 0.27.0_*

Access Management v0.27.0支持符合用于API客户端管理的OpenID Connect动态客户端注册协议的身份提供商，如Okta。您现在可以使用这些提供程序通过通用访问令牌实施策略来保护API网关。此版本还包括基础架构改进以帮助提升性能。有关更多信息，请参阅 link:/access-management/managing-api-clients[客户管理文件]。

2017年6月24日== 
*_Version 0.23.1_*

Access Management v0.23.1增强了用户通过工具提示和表单验证机制配置外部身份表单的体验。它提供了多项基础设施改进MuleSoft还通过Okta，OpenAM和Ping Federate验证了我们的OpenID Connect SSO解决方案。

=== 硬件和软件要求

不用找了。

=== 兼容性

NA

=== 已弃用的功能或功能

没有。

=== 已解决的问题

没有。

=== 移民指导

不需要迁移。

2017年5月6日== 
*_Version 0.22.0_*

Access Management v0.22支持单一登录到Anypoint平台的OpenID Connect兼容身份提供商（IdP）。通过一个新的用于外部身份配置的UI，此版本还将PingFederate和OpenAM的客户端UI配置表单带入平台。

=== 硬件和软件要求

不用找了

=== 兼容性

N / A

=== 已弃用的功能或功能

OAuth客户端管理配置过程现在通过访问管理的“外部标识”部分提供的表单进行自助服务。 OpenAM和PingFederate配置的Google表单现在已被弃用。

=== 已解决的问题

没有

=== 移民指导

不需要迁移

2017年1月14日== 
*_Version 0.18.0_*

访问管理v0.18在我们的 link:/access-management/managing-your-account#how-to-create-your-account[注册过程]中添加了 link:https://www.google.com/recaptcha/intro/index.html[没有CAPTCHA reCAPTCHA]验证步骤。

=== 硬件和软件要求

不用找了。

=== 兼容性

NA

=== 已弃用的功能或功能

没有。

=== 已解决的问题

没有。

=== 移民指导

不需要迁移。



==  2016年11月19日
*_Version 0.17.0_*

Access Management v0.17是一个次要版本，可以解决我们平台中的一些市场需求。

=== 硬件和软件要求

不用找了。

=== 兼容性

NA

=== 已弃用的功能或功能

没有。

=== 已解决的问题

没有。

=== 移民指导

不需要迁移。


==  2016年10月22日
*_Version 0.16.0_*

访问管理v0.16允许*Organization administrators*和*Audit Log Viewers*从 link:/access-management/audit-logging[审计日志UI]查看其组织的权利更改。

此外，Access Management现在支持 link:/access-management/external-identity[外部身份]的Ping Federate v8.2.1.1。


=== 硬件和软件要求

不用找了。

=== 兼容性

NA

=== 已弃用的功能或功能

没有。

=== 已解决的问题

没有。

=== 移民指导

不需要迁移。



==  2016年9月24日
*_Version 0.15.0_*

Access Management v0.15改进了用户邀请体验，并允许用户使用现有的Anypoint用户名接受组织邀请。

如果用户具有与电子邮件地址相关联的不同用户名并接收到新组织的邀请，则用户现在可以选择接受与其任何一个现有帐户的邀请，从而将所选用户名与该新组织关联。 +
如果所选用户名已与另一个Anypoint组织关联，则用户可以选择将此用户名与现有组织分离。如果她是该组织中的唯一用户，则她也有权删除该组织，因为用户名必须在所有Anypoint组织中保持唯一。在邀请过程的任何阶段，她都可以选择创建新的用户名。

=== 硬件和软件要求

不用找了。

=== 兼容性

NA

=== 已弃用的功能或功能

没有。

=== 已解决的问题

没有。

=== 移民指导

不需要迁移。


==  2016年8月27日
*_Version 0.14.0_*

Access Management V0.14.0版本对Anypoint Platform关于试用订阅期的通知进行了小幅改进。

如果您在30天的试用期内，可以在Access Management UI的*Subscription*部分查看到期日期。试用期到期后，您的帐户将转换为“免费”订阅层，您将无法在Anypoint Platform内部署应用程序和API以及其他企业功能。 +
您仍然可以登录到您的帐户。

=== 硬件和软件要求

不用找了。

=== 兼容性

NA

=== 已弃用的功能或功能

没有。

=== 已解决的问题

没有。

=== 移民指导

不需要迁移。

==  2016年6月25日发布
*_Version 0.13.0_*

Access Management V0.13.0是一个次要版本，它修复了一些改善平台性能的错误。

=== 硬件和软件要求

不用找了。

=== 兼容性

NA

=== 已弃用的功能或功能

没有。

=== 已解决的问题

没有。

=== 移民指导

不需要迁移。

==  2016年5月14日发布
*_Version 0.12.0_*

Access Management V0.12.0是一个次要版本，可使审计日志UI成为GA功能。使用此用户界面，用户可以查询和过滤审核日志。

=== 硬件和软件要求

不用找了。

=== 兼容性

NA

=== 功能和功能

审计日志Anypoint Platform的UI：通过审计日志记录服务记录Anypoint Platform组织内用户所做的更改。您现在可以通过访问管理下的审核日志用户界面或通过利用审核日志记录查询API来访问数据日志。请参阅审计日志。

=== 已弃用的功能或功能

没有。

=== 已解决的问题

没有。

=== 移民指导

不需要迁移。
