=  Anypoint数据网关版本说明
:keywords: release notes, data gateway

==  2016年8月27日发布

*_Version 1.4.3_*

这个新版本的Anypoint Data Gateway包含了DataGateway Designer和DataGateway的几个bug修复和运行时升级。

=== 已知限制

v1.4.2的相同限制适用于此版本。

有关更多信息，请参阅产品 link:https://www.mulesoft.com/press-center/anypoint-data-gateway[公告]。


==  2016年5月14日发布

*_Version 1.4.2_*

API数据网关已更新，以便将其UI设计适应Anypoint Platform的新导航栏。

=== 已知限制

v1.4.1的相同限制适用于该版本。


==  2016年4月9日发布

*_Version 1.4.1_*

我们很自豪能够推出Anypoint Data Gateway的新版本，其中包含DataGateway Designer和DataGateways两种新功能，例如一组新的Data Gateway角色和运行时升级。此外，还支持一种新的自由格式字符串作为基于JDBC的DataGateways的连接参数。

=== 功能和功能

*New Roles for DataGateway*

除了现有的组织所有者之外，还创建了两个新的DataGateway Admin和DataGateway查看器角色来管理对DataGateway Designer的访问。

*Connection String for JDBC DataGateways*

DB2，Oracle和MySQL DataGateways现在可以使用自由格式的连接字符串，从而允许在数据库连接URL中引入自定义参数。

*New Runtimes for the Designer and the DataGateways*

Designer现在运行在最新的Mule 3.7.3上，并且DataGateways已升级到在API Gateway 1.3.2上运行

=== 已知限制

v1.4.0的相同限制适用于此版本。
也：

* 使用连接字符串设置DB2，Oracle或MySQL DataGateway时，Cloud Extender将被禁用。 Cloud Extender需要定义的初始主机和端口来打开隧道，并且这些不能从连接字符串安全地派生。连接字符串可以与公共数据库一起使用，也可以通过VPC使用。


==  2016年1月9日发布

*_Version 1.4.0_*

Anypoint Data Gateway的这个新版本包括两项新功能：与Anypoint Platform完全集成，并支持通过单个API端点连接到Salesforce。

=== 功能和功能

*Full integration with the Anypoint Platform*

Anypoint Data Gateway现在是一个完整的Anypoint Platform应用程序，可通过Anypoint Platform主要管理中心访问。在接下来的一个月里，它将为所有API解决方案客户启用。对于那些使用嵌入式体验的用户，Anypoint Data Gateway仍然可以通过Salesforce获得。

*Single OData API endpoint for Salesforce*

Anypoint Data Gateway现在可以在Salesforce的单个OData API上发布所有网关。这意味着每个环境都需要一个Salesforce Lightning Connect许可证，从而降低成本并简化集成。

=== 已知限制

v1.3.1的相同限制适用于这个版本。
也：

* 由于Salesforce API中存在已知问题，可以通过转到设置>开发>外部数据源，选择已发布的数据源并单击验证和同步（在Salesforce中）轻松修复任何发布或同步问题。
* 如果要向Salesforce发布超过100个对象，则需要为其他网关创建单独的环境，因为Salesforce每个端点只允许有100个对象。
* 由于环境中的所有对象现在都是通过单个OData API发布的，因此在给定环境中，数据网关中不得有重复的对象名称。
* 任何先前存在的DataGateway都必须通过左侧导航栏中的Salesforce链接进行重新发布，以确保它使用新的单一OData API。
* 为了在数据映射中使用最新的修补程序，必须创建新的数据网关，以便用blob，double和datetime字段问题替换旧数据网关。


==  2015年12月5日发布

*_Version 1.3.1_*

我们很高兴宣布Anypoint Data Gateway的下一个版本。该版本增加了与Anypoint Platform的紧密集成，增加了试用版和企业用户控件。它还具有许多UI改进功能，包括全新的复制对象功能。

=== 功能和功能

==== 复制对象功能

数据网关允许您将一个对象从一个网关复制到另一个网关。此功能在您希望以类似状态维护的多个环境（例如开发环境和生产环境）下工作时尤其有用。

Cloud Extender认证的代理支持。==== 

Cloud Extender已得到增强，可支持通过身份验证或透明的代理，使您可以通过Data Gateway以简单友好的方式公开内部数据源。

====  UI改进

最新版本包括几个UI改进，例如：

* 空状态指示器。
* 环境下拉更改。
* 链接到订阅页面。

==== 自助服务

现在用户可以通过左侧导航栏中的链接请求订阅。

==== 链接到支持

顶部导航栏中包含了一个新的请求支持链接，只需点击一下，企业用户就可以通过支持门户请求支持。

=== 已知限制

v1.2.1的相同限制适用于此版本。

有关更多信息，请参阅产品 link:http://www.mulesoft.com/press-center/anypoint-data-gateway[公告]。


==  2015年5月13日发布

*_Version 1.1.0_*

=== 功能和功能

====  Cloud Extender

Cloud Extender是一种代理程序，可让您在试用期间连接到您的本地数据源，而无需进行VPC配置以评估产品。 Cloud Extender通过HTTP over HTTP隧道在Data Gateway和专用网络内的数据源之间传递数据。 Cloud Extender的优势在于，它不需要在防火墙中打开端口并自动进行自我配置 - 您只需运行它即可。

{/ 0}} UX / UI改进

一些次要的UI / UX修复和改进：

* 对象版本按钮已移入对象详细信息视图
* 仅针对分配给当前用户的配置文件执行针对Salesforce的同步
* 改进了连接创建体验

==== 支持Mule ESB 3.6.1

该版本在Mule ESB的最新版本上运行。

==== 已知限制

<<February 25, 2015 Release>>的相同限制适用于此版本。

有关更多信息，请参阅产品 http://www.mulesoft.com/press-center/anypoint-data-gateway[公告]。

==  2015年3月11日发布

*_Version 1.0.1_*

在2月25日首次发布Anypoint Data Gateway之后（1.0.0），我们发布了1.0.1版本，包含用户反馈，小错误修复和增强功能，其中包括：

* 改进对象的创建和管理：
** 支持在主键不存在时将主键分配给对象
** 修复在Oracle DB上构建对象时识别主键的问题
** 新的验证逻辑可防止创建具有相同名称的2+对象（这会在Salesforce Lightning Connect中导致错误）
* 改进的连接管理：
** 能够删除连接
** 修复Oracle数据库连接问题

对于所有其他已知问题，先决条件和产品功能，请参阅下一节。

==  2015年2月25日发布

*_Version 1.0.0_*

我们很高兴发布为 link:https://www.youtube.com/watch?v=OZWneVt_1Mk[Salesforce Lightning Connect]构建的第一版Anypoint Data Gateway！您可以从 link:https://appexchange.salesforce.com[Salesforce AppExchange]安装本产品。

== 硬件和软件要求

*  Salesforce Lightning Connect集成 -  Winter '14版本

== 兼容性

*  Salesforce元数据API版本34+

== 功能和功能

* 通过远程函数调用（RFC）实现SAP R / 3数据的只读连接和虚拟化
*  OracleDB，SQL Server，DB2和MySQL的只读连接和虚拟化
*  Anypoint Gateway Designer：用于以下操作的浏览器界面：
** 配置与应用程序和数据库源的连接。
** 创建连接到Salesforce的网关。
** 设计外部对象以用于Salesforce表单，搜索，工作流和报告。
* 在Salesforce Lightning Connect管理设置中自动配置外部数据源和外部对象。
* 通过使用虚拟私有云（VPC），支持与本地数据源的无缝安全连接。
* 通过集成到MuleSoft Anypoint Platform和API管理功能来保护和限制数据网关服务

== 已知问题 - 所有版本

有关已知问题，请参阅 link:/anypoint-data-gateway/troubleshooting-data-gateway[数据网关故障排除]。
