=  Anypoint连接器DevKit 3.9.x发行说明
:keywords: devkit, release notes, jdk8, connector

link:/anypoint-connector-devkit/v/3.8[Anypoint连接器DevKit指南]

== 版本3.9.5  -  2018年5月2日

=== 已修复问题

* 轮询来源用于共享相同的*Polling Period*交叉来源
相同应用中的相同类型，现在可以单独配置这些类型。

=== 兼容性

DevKit版本3.9.5与以下软件版本兼容。

[%header,cols="2*a"]
|===
| {软件{1}}版本
| Mule运行时| 3.5.0或更高版本
| Anypoint Studio  |  6.0.0或更高版本
|===


== 版本3.9.4  -  2017年12月4日

=== 已修复问题

* 在流程发生异常之后，轮询源停止工作。

=== 兼容性

DevKit版本3.9.4与以下软件版本兼容。

[%header,cols="2*a"]
|===
| {软件{1}}版本
| Mule运行时| 3.5.0或更高版本
| Anypoint Studio  |  6.0.0或更高版本
|===

=== 附加信息

在这个版本中，DevKit开始使用*Mule 3.9.0*作为编译Mule版本。
这不会更改基于DevKit的连接器的兼容性范围。

== 版本3.9.1  -  2017年2月2日

=== 已修复问题

*  *@Summary*不起作用的是一些场景。
* 嵌入的POJO属性在Studio中不可用。

=== 兼容性

DevKit版本3.9.1与以下软件版本兼容：

[%header,cols="2*a"]
|===
| {软件{1}}版本
| Mule运行时| 3.5.0或更高版本
| Anypoint Studio  |  6.0.0或更高版本
|===

== 版本3.9.0  -  2016年6月21日

Anypoint Connector DevKit 3.9.0支持DevKit内置连接器的两项新功能，以及针对早期版本的多项修补程序。

=== 特点

使用DevKit 3.9.0构建连接器（即，在连接器项目的`pom.xml`中指定此版本号）允许连接器的最终用户检索Mule Debugger中连接器的`@Processor`（s）的信息Anypoint Studio。

对于Studio 6.0.2及更高版本，此版本允许开发人员根据连接器最终用户的Studio UI偏好将多套连接器图标打包在Studio Visual Editor中。

通过3.9.0，您可以通过首先在连接器中创建两个不同的文件夹来支持每个Studio UI主题的两组图标：

*  *`theme.light`* _（新外观）_
*  *`theme.classic`* _（旧外观）_

=== 兼容性

DevKit版本3.9.0兼容于：

[%header,cols="2*a"]
|===
| {软件{1}}版本
| Mule运行时| 3.5.0或更高版本
| Anypoint Studio  | *Debugging support for DevKit-built connector*：

*  Studio 6.0.0及更高版本

*Support for Light and Classic Studio themed icons*：

* 适用于Studio 6.0.2及更高版本
|===


==== 图标文件夹结构

----
   icons/
            /theme.light
                                /icon.png
            /theme.classic
                                /icon.png
----

[INFO]
====
新的灯光主题图标必须具有以下尺寸：

-  16 x 16用于小图标
-  26 x 26适用于大图标
====

==== 图标命名约定



*Old Look Icon Naming Convention Changes*

- 以前是`<connectorName>-connector-​*48x24*​.png`，现在是`<connectorName>-connector-​*large*​.png`
- 以前是`<connectorName>-connector-​*24x16*​.png`，现在是`<connectorName>-connector-​*small*​.png`

*New Look Icon Naming Convention Changes*

- 以前是`<connectorName>-connector-​*26x26*​.png`，现在是`<connectorName>-connector-​*large*​.png`
- 以前是`<connectorName>-connector-​*16x16*​.png`，现在是`<connectorName>-connector-​*small*​.png`


=== 已修复问题

此版本包含几个修补程序：

* 当从`MetaDataKey`构建`DefaultComposedMetaDataKey`时，DevKit现在可以正确设置类别，而不是将其设置为`DEFAULT`
* 支持Anypoint Studio的"Light"主题以及"Classic"主题的连接器图标
