=  Anypoint平台自动升级通知（11月发布）
：imagesdir：./_images

11月版本包括API Designer，API Portal和API Manager中的许多改进。

除非您的平台管理员选择退出（<<opt_out>>），否则MuleSoft会在Crowd（七月发行版）中自动升级具有二十（20）个或更少API和客户的客户。自动升级按照滚动时间表进行。其他客户可以使用自助式升级流程。

*Note:*升级之后和分类API之前，请彻底测试您的API，笔记本和门户。将API分类后，如果遇到与升级相关的问题，则无法回滚您的组织。

升级计划取决于组织中的API数量：

*  4月30日 -  5月1日：在Crowd（7月发布）中拥有二十（20）个或更少API和客户的客户将自动升级。
* 所有其他客户都将获得自助服务体验。

== 发布中有什么内容？

* 全新体验（YouTube上的视频）：https：//www.youtube.com/watch？v = oL827WlMmfM&feature=youtu.be [NO。 2017发布：现有用户的UI更新]
* 更改和功能： link:anypoint-november-release[Anypoint Platform 7月和11月发行版：发行说明]

由于许多新产品具有新功能和不同UX，请考虑以下事项：

* 对于API门户，外观和感觉正在改变。对于暴露给外部开发人员的公共API门户，此更改尤其重要。
*  API生命周期略有不同，因此如果您处于大型版本中，请务必与您的团队进行沟通。
{0}}您或您单位的其他开发人员使用的其他Anypoint帐户可能会保留相同的“旧”Anypoint Platform体验。

升级后== 

API Manager中的所有API都将位于未分类的环境中。

要访问您的API：

. 转到API管理器。
. 选择未分类的环境。
+
在未分类的环境中，您可以按照您在11月发行版之前的相同方式管理您的API。
+
. 当您准备好11月发行版的新环境功能时，将您的API分类到环境中，或者在其中创建新的API。

== 新增和更改的功能

什么是新的：

* 使用现有API Manager创建的所有API均会在升级后出现在Unclassified Environment中。
在此过程之后，Unclassified环境中的*  API可以分类到相应的环境中。
* 升级后新API的自动发现元素应按以下方式进行配置（所有值均可从API和UI获取）：
**  `name=”groupId:{{groupId}}:assetId:{{assetId}}”`
**  `version=”{{version}}:{{instanceId}}”`
*  API Manager API（v3.x）的新版本可用于利用所有新的API Manager功能。
* 用户的权限模型已在环境级别更改为基于操作，与管理中心的其余部分保持一致。升级后，管理员应该为所有用户设置环境级权限。默认的环境级别管理员角色可用。未分类环境中的权限模型与移植前API Manager权限模型的工作方式相同。在未分类环境中为API分配的权限在升级过程中也保持不变。

===  API设计器

* 要更改正在运行或发布的API的RAML，用户需要重新发布Exchange中具有版本的任何规范。
*  Design Center项目没有像旧API Manager项目这样的标签。
来自Studio 6和7的*  API同步仅支持拉取。

Exchange中的===  API门户

* 导航面板中的外部链接分组在Exchange中的“帮助”链接部分下。
* 现有门户网站URL将重定向到新Exchange中的相应API门户。
* 不可视网页已弃用，并替换为Exchange的草稿功能。升级完成后，所有不可见页面都将变为草稿。
{0}} API门户级别的品牌建议已被弃用，并替换为全局品牌控制。这意味着所有API门户页面都会继承全局样式。
* 要更新Exchange中提供的或API Manager中的API代理使用的API规范，用户需要使用API​​设计器向Exchange发布新版本的API规范。
* 内部API使用者可以通过他们有权​​访问的API门户查看所有API端点和版本。现有的API管理器控制每个API版本的权限。
* 简化了API公共门户入职的外部用户的访问，并且无需邀请外部用户为他们使用API​​并请求API密钥。
* 当API迁移到Exchange时，Exchange调用REST Connect为Mule 4和Mule 3生成连接器。由于REST Connect仅支持RAML v1.0，因此基于RAML v0.8的API规范的所有者会收到电子邮件通知并显示连接器创建失败的消息。他们仍然可以使用Design Center打开和编辑这些API规范，但这些规范不能用作Design Center，Studio 6和Studio 7中的连接器。

升级后API Manager中的===  API更改

利用自动发现元素的*  API现在使用API​​管理器。
*  API管理器API可以与未分类环境中的API一起使用，但有一些限制（请参阅下文）。
* 由于升级到最新软件会移动所有门户，因此升级后不能使用RAML进行修改，创建或删除它们。升级之后，API Manager API v2.x将按照以下方式更改其行为：
** 与管理RAML相关的以下资源返回400.改为使用Design Center API。
+
[source,xml,linenums]
----
/organizations/{organizationId}/apis/{apiId}/versions/{apiVersionId}/addRootRaml
/organizations/{organizationId}/apis/{apiId}/versions/{apiVersionId}/files/*
----
+
** 与管理门户（包括权限设置）相关的以下资源返回400.请改为使用Exchange API。
+
[source,xml,linenums]
----
/organizations/{organizationId}/apis/{apiId}/portals
/organizations/{organizationId}/apis/{apiId}/versions/{apiVersionId}/portal/*
/organizations/{organizationId}/portals/*
organizations/{organizationId}/public/*
----
+
需要首先在Exchange中完成**  API创建，然后使用API​​ Manager API创建API返回400。
在升级之前导出的*  API无法在升级后导入。

== 在此处了解更多信息

*  link:/api-manager/manage-exchange-api-task[从Exchange管理API]
*  link:/api-manager/environment-permission-task[授予访问环境的权限]
*  link:/api-manager/classify-api-task[分类API]

[[opt_out]]
== 想要退出？

如果您想从自动升级中排除，请向我们发送包含您的组织ID的电子邮件至crowd@mulesoft.com。您可以通过导航到访问管理>组织> _your_organization_，然后在组织信息窗口中找到组织ID，从Anypoint Platform中找到该ID。

请注意，所有客户都需要在2018年进行升级。

如果您在Anypoint Platform的新体验方面遇到问题，可以从https://support.mulesoft.com/s/[MuleSoft支持]打开支持服务单。
