=  Anypoint Analytics版本说明
:keywords: analytics, release, notes

== 兼容性

Anypoint Analytics与 link:/mule-user-guide/v/3.9/hardware-and-software-requirements[硬件和软件要求]中描述的所有硬件和软件以及API Manager v1.0和更新版本兼容。

==  Mule兼容性

Anypoint Analytics与Mule 3.9兼容;但是，您需要将以下属性添加到您的项目中，以便API与Mule 3.9中的Analytics兼容：

[source,xml,linenums]
----
anypoint.platform.analytics_base_uri=https://analytics-ingest.anypoint.mulesoft.com
anypoint.platform.platform_base_uri=https://anypoint.mulesoft.com/apiplatform
anypoint.platform.coreservice_base_uri=https://anypoint.mulesoft.com/accounts
anypoint.platform.contracts_base_uri=https://anypoint.mulesoft.com/apigateway/ccs
----
== 版本2.3.0  -  2017年1月27日

此版本包含度量可视化，不仅关注由MuleSoft网关保护的API服务的视图，还关注网关返回的结果。此功能可以在概览仪表板，自定义字符和API Manager报告中公开。

== 版本2.2.0  -  2017年1月13日
此版本是维护版本，包括UI改进和缺陷修复。

* 固定导航面板可视化
* 聊天Y轴数字可视化自动精确调整
* 更好地调整浏览器字体调整大小
* 图表标签呈现在底部，以避免与图表重叠

== 版本2.1.0  -  2017年11月18日

本发行版包含若干改进，以将API分析与作为Crowd发行版一部分引入的新概念相结合：

* 支持环境
+
报告和自定义仪表板是按照环境生成的。
*  API已更新为可识别环境。
**  Events API支持使用一组新资源路径的环境，同时保持当前资源路径的正常运行，从而保持向后兼容性。
** 数据根据当前环境或"Unclassified"伪环境进行过滤。
现在*  API消费者分析出现在Exchange中。
* 针对Events API的100个请求/秒的实施现已到位。

该版本还解决了API消费者和API分析的UI可视化问题。

== 版本2.0.0  -  2017年10月21日

本版本引入了错误修复：
 -  API事件报告创建使用浏览器时区来定义时间选择范围。
 - 解决在仪表板创建过程中阻止"average"指标持续存在的问题。

此版本还包含API事件后端的重要构架。从此版本开始，从事件开始就有效，Analytics Event API提供一个月保留策略，而不是3个月的事件，并且每个请求强制实施最多20,000个事件。

== 版本1.21.1  -  2017年6月3日

此版本引入了可用性和UI布局改进以及错误修复。

== 版本1.21.0  -  2017年5月6日

Google Analytics版本引入了以下功能：

* 仪表板功能和显着改善的用户体验以及API消费者分析图表
* 能够下载消费者分析图表，更改仪表板布局并有选择地比较所选API的指标


== 版本1.20.1  -  2016年12月3日

Analytics 1.20.1版本使警报引擎能够提供API警报功能。 API告警功能在 link:/api-manager/using-api-alerts[API管理器]页面进行了描述。

此版本还包括以下UX改进和错误修复：

*  AS-659：在API管理页面访问API版本时更正子组织的权限。

== 版本1.20.0  -  2016年11月19日

Analytics 1.20.0版本引入了用于API警报功能的警报引擎。

此版本还包括以下UX改进和错误修复：

*  AP-2677：在API访问状态被撤销时纠正错误报告
*  AP-2638：在API消费者图表上显示API版本
*  AP-2676,2667,2678：在API列表或API名称很长的情况下，UX的改进可以改进渲染
*  AP-2672：请求更改层时删除多余的API调用

== 版本1.18.0  -  2016年10月11日

此版本引入了API消费者分析功能，该功能允许应用程序所有者查看与应用程序进行的API调用相关的API指标。
此版本还包括对API管理页面中的Google Analytics图表的错误修正。在API Analytics图表的“热门应用程序”选项卡中，用户现在可以查看调用所选API版本的前5个应用程序对所选API的API请求的细分。

== 版本1.17.1  -  2016年8月11日

此版本包括以下功能增强和错误修复：

*  API报告的日期范围选择
** 将API Analytics数据的*Data available from*日期添加到Anypoint Analytics *Manage Reports*和*Create Report*页面，以指示可生成API Analytics报告的日期范围。
** 现在，如果为报告选择的时间段超出API Analytics数据可用时间段，则会显示*No API data available for this data source*警告消息。
* 报告参数选择改进：
** 在生成API报告时，已将90天的报告期添加为下拉选项之一。
已添加** 界面改进和修复功能，以在生成API Analytics报告时启用滚动浏览API的完整列表。
*  Anypoint Analytics数据存档时间段更新：
** 存档超过90天的数据。
**  API Analytics数据报告暂时限制在90天内。有关更多信息，请参阅 link:https://support.mulesoft.com/s/article/Service-Interruption-07-27-2016-Error-Retrieving-API-Analytics-Data[服务中断07/27/2016  - 检索API分析数据时出错]。


内部错误修复版本的*Note:*版本从1.12.1到1.17.0。

== 版本1.12.0  -  2016年4月23日

此版本包含若干后端基础架构和功能增强功能，以支持即将发布的产品版本的分析和使用情况跟踪。

== 版本1.11.0  -  2016年2月27日

本版本包括以下功能增补：

* 基础架构增强和优化。
* 限制报告API根据可配置的行数提供结果。

本版本中已修复=== 

*  AS-585  - 为大客户提供运营准备

== 版本1.10.1  -  2016年1月23日

此版本包括以下功能增补：

除JWT之外，现在还支持*  OAuth令牌来调用Anypoint Analytics Query和Reports API。
* 无需验证令牌即可直接访问分析主页，现在可将用户重定向到Anypoint Platform登录页面。

=== 已修复问题

*  AS-254  - 当用户未登录时，Analytics（分析）页面无法加载并作出相应反应。
*  AS-560  - 允许使用OAuth令牌进行API调用（不推荐使用JWT令牌。）

== 版本1.10  -  2015年12月19日

* 为了允许Anypoint Analytics和第三方系统之间的关联，`event_id`属性
由API网关设置（来自`message.id`）现在通过系统传播。
* 从Anypoint平台的Google Analytics部分执行注销现在可以正确注销并重定向到登录页面。
除JWT之外，现在还支持*  OAuth令牌来调用Anypoint Analytics Query和Reports API。

== 版本1.9  -  2015年12月12日

* 摄取系统中的性能调整，提供更强大的处理API网关突发负载的能力。
* 针对API分析图表改进了空白数据范围的显示，使数据在没有可用数据时更为明显。






