=  Anypoint平台私有云版本1.1.0发行说明
:keywords: release notes, devkit


*December 16, 2015*

== 说明

Anypoint Platform私有云版采用MuleSoft为云开发的平台的所有功能，并使公司能够在其数据中心内部运行该平台。在此版本中，我们将发布API，运行时管理和Exchange解决方案。

== 特点

*Anypoint Platform for APIs*：
用于API的Anypoint平台是用于企业API设计，实施，管理和参与的多租户端到端平台。

*Anypoint Runtime Manager*：
Anypoint Runtime Manager（V1.2）私有云版使用户能够轻松地将其本地Mule服务器和API网关与第三方的监控工具（如Splunk和ELK）集成以监控，分析，和治理。

*Anypoint Exchange*：
Anypoint Exchange使用户能够在他们自己的组织内发布和访问与Mule相关的内容，从而提高跨组织的可视性和重用性。

*Anypoint Access Management*：
Anypoint访问管理是一种底层平台解决方案，允许客户无缝集成现有的身份验证提供程序以进行集中式用户管理。

*Multi Host On-Premises Management*
您可以在多台主机上运行内部部署管理平台，以启用系统的高可用性。

*Business Groups*
您可以创建业务组，并委派每个组内的资源管理，并轻松划分范围，角色和权限。

== 系统要求

[cols="2*a"]
|===
| 操作系统
|
*  RHEL 7.1或更高版本
*  CentOS 7.1或更高版本

| 存储
|
对于var / lib / docker，* 为20 GB
用于主目录的*  1 GB

| 泊坞
|
*  Docker引擎1.6.2或更高版本
*  Docker Compose 1.3.1或更高版本

| 身份管理提供商
|
*  OpenAM 11.0或更高版本
*  PingFederate 6.10,7.1或7.2
*  LDAP v3

|网络端口
| 80,8080,8081,443,8443

| Mule运行时代理
|版本1.3.2

| Anypoint运行时管理器
| link:/release-notes/runtime-manager-1.2.0-release-notes[版本1.2]
|===

== 释放Cadence

我们预计从现在起大约6个月后将发布新版本的Anypoint Platform新功能。

鉴于On-Premis的Anypoint Platform是我们云解决方案的快照，它将很可能不包含为这个云开发的所有最新功能，直到新版本推出为止。我们无法保证所有云平台功能都可用于On Premises，因此我们将会突出显示这些差异。

== 与云版本的当前差异

目前的本地版本与Anypoint平台的云版本之间存在一些差异，详情如下：

*CloudHub/Applications*：
在On Premises版本中，CloudHub名称已更改为*Applications*，因为您将通过Anypoint Runtime Manager管理应用程序和服务器。

*Anypoint Exchange*：
这是Anypoint Exchange的私人版本，因此您将无法查看云版本中的公开内容。

*Anypoint Platform for APIs*
On Premises版本不包含API分析。

*Anypoint Runtime Manager*
On Premises版本不包含审核登录功能。

== 已知问题

AGW-695目前，在Java 7上运行的API Gateway 2.1.0或更早版本将默认为TLS 1.0，这会导致将问题与Anypoint Platform私有云版一起使用。如果您在Java 8上运行该问题，则不会出现此问题，或者应用为此问题创建的修补程序。
