=  Anypoint Object Store v2发行说明
:keywords: osv2, release notes, object store v2, object, store, v2

*May 2018*

Anypoint Object Store v2发行版允许应用程序和用户在批处理，Mule组件和多个分布式应用程序之间共享数据和共享状态。

== 版本2.4.0  -  2018年5月5日

此版本的Object Store为云对象存储V2服务添加了完整的分区支持。

== 版本2.4.0  - 已在此版本中修复

* 通过改进的分区支持更新OSv2后端服务。 （MQ-1123）
* 更新OSv2 Mule插件以使用分区。 （MQ-1128）
* 使用分区支持更新OSv2 UI。 （MQ-1122）

== 版本2.3.3  -  2018年4月20日

Anypoint Object Store v2已将欧盟爱尔兰列为欧盟控制平面的新地区。

== 版本2.3.2  -  2018年3月13日

此版本的Object Store v2添加了一项新功能，其中storeId和键值的最大长度现在是256个字符，而不是旧的128个字符。

== 版本2.3.0  -  2018年1月27日

Object Store v2现在是GA，适用于测试和生产应用程序。这项新服务是当前Runtime Manager对象存储的重新架构，重点关注性能，可伸缩性和数据隐私。客户现在可以选择在运行时管理器应用程序部署设置中选择Object Store v2作为配置选项。

Object Store v2在以下位置受支持。

注意：如果区域中不支持OSv2，则OSv2将透明地映射到最近的位置。

支持的区域：

*  AP-东北-1
*  AP-东南-1
*  AP-东南-2-
*  CA-中央-1
*  EU-中央-1
*  EU-西-1
*  EU-西-2-
*  SA  - 东 -  1
* 美东 -  1
* 美西2

=== 版本2.3.0  - 兼容性

Anypoint Object Store v2适用于Mule 3.7.3及更高版本，以及Mule 4及更高版本。

Anypoint Object Store v2适用于以下浏览器版本：

*  Chrome版本34或更高版本
*  Firefox  - 版本29或更高版本
*  Internet Explorer  - 版本10或更高版本
*  Safari  - 版本7或更高版本

== 另请参阅

*  link:/object-store/index[对象存储v2]
*  link:/release-notes/objectstore-release-notes[对象存储连接器发行说明]
