=  CloudHub R40迁移指南
:keywords: release notes, cloudhub, cloud hub


对于2014年10月的CloudHub发行版40，API Manager和CloudHub具有统一的单点登录体验和用户界面。请阅读以下迁移指南，以了解如何受到这些更改的影响。

== 访问管理控制台

CloudHub现在可以从 link:https://anypoint.mulesoft.com/[anypoint.mulesoft.com]网址访问。展望未来，如果您访问 link:http://cloudhub.io[cloudhub.io]登录，您将被重定向到 link:https://anypoint.mulesoft.com/[anypoint.mulesoft.com]。所有应用程序仍将在cloudhub.io的各自域中提供。

== 帐户迁移

如果您拥有API Manager和CloudHub的相同用户名的用户，则可能会更改您的用户名。

如果您有一个CloudHub组织和一个拥有相同管理员组的API管理组织，我们将合并您的帐户，以便拥有完全统一的帐户。

但是，如果它们不匹配，那么我们不会合并帐户，因为这可能会导致无意中授予组织中部分访问权限给未经授权的用户。在这种情况下，我们将使用后缀`_cloudhub`为您创建第二个帐户。例如，如果您的用户名是`joe`，并且您在API Manager和CloudHub中都有帐户，则将使用用户名`joe_cloudhub`创建另一个帐户。如果此条件适用于您的用户名，您将收到一封电子邮件，通知您此更改。

如果您因上述条件（例如`joe`和`joe_cloudhub`）而拥有两个组织，可以通过邀请所有用户加入单个组织并手动迁移您的应用程序或API来合并这些组织。如果您是客户并希望这样做，请在 link:https://support.mulesoft.com[https://support.mulesoft.com]处打开支持案例，以便可以禁用旧组织。

== 角色和权限

平台中的基础角色和权限模型变得更加强大。因此，用户会注意到他们现在对每个环境都有单独的角色。

例如，如果您在CloudHub，Production和QA中有两个环境，那么您将获得以下一组角色：CloudHub管理（生产），CloudHub管理员（QA），CloudHub开发人员（生产），CloudHub开发人员（QA） ，CloudHub支持（生产）和CloudHub支持（QA）。

有关角色和权限如何工作的更多信息，请参阅 link:/access-management[访问管理]指南。

== 更多信息

除上述内容外，请参阅 link:/release-notes/cloudhub-release-notes[发行说明]以查看新功能和勘误表的完整列表。
