=  Microsoft Service Bus连接器发行说明
:keywords: release notes

*February 2018*

_选择_

== 版本1.3.2  -  2018年2月9日

修正：定义的异常策略未被`<microsoftservicebus:queue-receive>`正确使用。
当一个流程使用`microsoftservicebus:queue-receive`和同步处理策略时，
连接器没有使用适当的异常策略来处理错误。

如果存在，则从1.3.2开始，在流上设置的异常策略被调用。

== 版本1.3.1  -  2017年6月9日

Microsoft Service Bus连接器 - 版本1.3.1已发布修补程序。
包含在此版本中：

* 修正了通过更改连接器处理这些策略的方式处理同步和异步流策略时遇到的几个线程和同步问题。对于同步方案，仅当流程成功完成时才会确认该消息。如果发生错误，消息不会被确认，并且会一直消耗直到成功。对于异步场景，消息永远不会自动确认，因此无论流失败还是成功，消息都会被重新使用。为了确认消息，必须在流程中使用新的*Acknowledge Message*处理器。该处理器接收AmpqMessage作为输入并进行确认。
- 有关如何使用*Acknowledge Message*处理器的示例，请转至*Synchronous and asynchronous behavior*部分
的用户手册

== 版本1.3.0  -  2017年4月4日

包含在此版本中：

* 连接器现在支持通过Azure服务总线队列发送/接收大量消息（超过256KB）。要启用此功能，需要Azure存储帐户，并且必须在Azure服务总线连接策略下指定此帐户的连接凭据。如果指定了这些凭证，那么存储将被用于将通过使用特定连接策略的队列发送的每个消息主体存储为blob。如果您希望接收大邮件，则还必须指定存储凭证，以便连接器可以从Blob存储中检索邮件正文并在之后删除该Blob。
* 改进连接管理以防止潜在的死锁问题。
* 修正在异步处理策略下运行流时的消息丢失问题。
* 通过DataSense公开额外的元数据
* 改进的演示包，包括Web表单以将新消息发布到队列或主题。


== 版本1.2.0  -  2016年11月30日

包含在此版本中：

* 添加了自定义逻辑来处理邮件属性中的不重要类型。
* 添加了跳过连接器启动时的连接测试的选项。
* 使用基于SAS的身份验证发送邮件时性能得到改进。
* 提高高负载下的可靠性和稳定性。

== 版本1.1.0  -  2016年10月4日

包含在此版本中：

* 增加了对基于SAS的验证的支持（即，避免在配置设置中提供用户名/密码）。
* 修复消息处理和确认以确保零消息丢失的高可靠性（即至少一次交付）。

== 版本1.0.4  -  2016年4月7日

Microsoft Service Bus连接器 - 版本1.0.4已发布修补程序。

此版本中的更改：

* 修复了分区主题消息的消耗。
* 针对无效的属性类型改进了错误消息。
* 通过缓存连接来改进消息的生产性能。

== 版本1.0.3  -  2015年10月9日

Microsoft Service Bus Connector  - 版本1.0.3已发布修补程序。

此版本中的更改：

* 添加了对发送mule出站属性作为AMQP消息中的自定义属性的支持。

== 版本1.0.2  -  2015年9月15日

Microsoft Service Bus Connector  - 版本1.0.2已发布修补程序。

此版本中的更改：

* 将qpid依赖升级到0.3.2

== 版本1.0.1  -  2015年9月9日

服务总线连接器 - 版本1.0.1已发布修补程序。

在此版本中已修复：

* 连接器在Mule应用程序停止或取消部署后继续出现消息。这已被修复，连接器现在停止在Mule应用程序停止或取消部署时出现消息。

== 版本1.0  -  2015年1月21日

我们很高兴为Service Bus推出新的连接器。 ServiceBus连接器v1.0支持Windows Service Bus内部部署或Azure Service Bus云托管的可靠消息集成方案。提供对队列，主题和事件中心的支持，并通过AMQP 1.0传输发送或接收消息。通过内置的管理API可以动态发现和配置服务总线对象。

*Connector Guide*： link:/mule-user-guide/v/3.8/microsoft-service-bus-connector[Microsoft Service Bus连接器]

=== 版本1.0兼容性

[%header,cols="2*"]
|===
|应用/服务 |版本
| Mule运行时 | 3.5+
| Anypoint Studio  | 2015年1月
|服务总线a |
*  Microsoft Azure服务总线（云）
*  Microsoft Windows Service Bus（本地） -  1.1+
|===

== 另请参阅

*  link:/mule-user-guide/v/3.8/microsoft-service-bus-connector[Microsoft Service Bus连接器]
*  link:/mule-user-guide/v/3.8/microsoft-service-bus-connector-faq[Microsoft Service Bus连接器常见问题]
*  link:http://forums.mulesoft.com[论坛]
