= 将Mule 3.1移植到3.2
:keywords: release notes, esb


==  Java运行时级别

从Mule 3.2.0开始，构建和运行Mule都需要Java 6。用早期版本的Java编译的用户和第三方JAR将继续与Mule合作。

==  Maven级别

从Mule 3.2.0开始，构建Mule需要 http://maven.apache.org/download.html[Maven版本3]。

===  Acegi模块

Acegi模块被Spring安全模块所取代，并且已被弃用。从Mule 3.2开始，Acegi模块不再包含在任何Mule发行版中。有关迁移安全模块的详细信息，请参阅 link:/mule-user-guide/v/3.7/upgrading-from-acegi-to-spring-security[从Acegi升级到Spring Security]。

== 配置更改

分组消息处理器和调用流程的语法已经阐明：

*  <processor-chain>只能用于在其他结构（如路由器）中对消息处理器进行分组。全局配置的处理器链已弃用，并将在未来版本中删除。
已引入*  <sub-flow>来表示全局配置的消息处理器组，这些消息处理器将通过<flow-ref>同步调用。
* 当使用<flow-ref>进行调用时，流程遵循其指定的处理策略。如果未指定，则处理策略默认为`asynchronous-queued`。这是从以前的行为发生的变化，如果使用<flow-ref>进行调用，则会同步处理流。为了让私有流默认同步行为，就像它们在以前的版本中一样，它们必须被重新定义为子流
*  <flow>不再将线程配置文件作为子元素。改用<processing-strategy>。

== 行为更改

如<<Configuration Changes>>中所述，<flow-ref>不再强制引用流的同步处理。要获得同步行为，请在目标流上指定`processingStrategy="synchronous"`或使用子流。

==  API更改

*  `org.mule.construct.SimpleFlowConstruct`类已重命名为`org.mule.construct.Flow`。
*  `org.mule.exception.DefaultServiceExceptionStrategy`类已被拆分为以下新类：`org.mule.exception.DefaultMessagingExceptionStrategy`和`org.mule.exception.DefaultSystemExceptionStrategy`
*  `org.mule.module.pgp.LazyInputStream`类已重命名为`org.mule.module.pgp.LazyTransformedInputStream`
*  `org.mule.module.pgp.OutputStreamWriter`类已重命名为`org.mule.module.pgp.StreamTransformer`

== 架构更改

=== 架构位置更改

应该在模式位置中使用的版本是**3.2**。从这个版本开始，您也可以使用*current*  - 这应该简化从旧版Mule到更新的版本。

*Mule 3.2 Schema Location*
[source,xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:cxf="http://www.mulesoft.org/schema/mule/cxf"
  xsi:schemaLocation="
    http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/3.2/mule.xsd
    http://www.mulesoft.org/schema/mule/cxf http://www.mulesoft.org/schema/mule/cxf/3.2/mule-cxf.xsd">

</mule>
----
*Mule current Schema Location*
[source,xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:cxf="http://www.mulesoft.org/schema/mule/cxf"
  xsi:schemaLocation="
    http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
    http://www.mulesoft.org/schema/mule/cxf http://www.mulesoft.org/schema/mule/cxf/current/mule-cxf.xsd">

</mule>
----

[NOTE]
*current*模式位置将被解析为在运行应用程序的Mule ESB运行时在本地捆绑的模式。

== 弃用/删除

[%header,cols="2*"]
|===
| {影响{1}}更改
| EJB传输 |已弃用
| iBeans Transport  |已移除。云连接器是iBeans的新化身。今后只支持云连接器。
| `mule-cluster-ee.xsd`  |移除。请参阅<<Schema Changes>>。 Mule ESB 3.2中不存在特定于群集的配置
|===
