API网关2.0.0或更高版本的= 迁移指南
:keywords: migration, api gateway, http, connector

API网关版本2.0引入了重要的更改，这些更改需要转换为先前的网关版本构建的任何代理。主要变化是采用新的高性能 link:/mule-user-guide/v/3.7/migrating-to-the-new-http-connector[HTTP连接器]，为代理定义的属性也不同。

如果您的代理是由Anypoint Platform自动生成的，并且代码没有被修改，那么所提供的迁移工具应该使这个更改变得容易。另一方面，如果您在下载代理后修改了代理 - 要包括HTTPS凭证或任何其他更改 - 那么您必须手动修改您的项目。

对于这些情况，我们建议您从最新版本的API网关平台下载代理，然后复制您所做的更改。

要从较早版本的API网关进行迁移，您必须首先正确配置您的API网关2.0，并使用所有代理，然后才能关闭旧API网关并启动新网关。由于端口重叠，两个版本无法同时运行。

== 使用API​​ Gateway 2.0迁移工具

如果您使用的是已由Anypoint Platform自动生成的代理，并且自从您下载代理后未对其进行修改，则可以运行此迁移工具：

. 点击 link:_attachments/api-gateway-migration-tool-2.0.4.jar.zip[这里。]下载迁移工具
. 转到API网关2.0独立分发文件夹。
. 从命令行运行以下脚本：

[source,java,linenums]
----
java -jar <path-to-migration-tool>/api-gateway-migration-tool-2.0.4.jar -DagwSourceFolder=<gateway-1.x-folder> -DagwTargetFolder=<gateway-2.0-folder>
----

您必须提供：

** 系统中的位置以及执行迁移的JAR文件的名称
*  DagwSourceFolder：您的API Gateway 1.x独立发行版的父文件夹。在此文件夹下方，您会找到应用程序和域文件夹，存储要转换的文件。
**  DagwTargetFolder：您的API Gateway 2.0独立发行版的父文件夹。在此文件夹下方，您会找到已转换的应用程序和域文件夹。

该工具可以在一次扫描中将您的所有应用程序和域名迁移到您的文件夹中。任何从Anypoint Platfrom下载以来以任何方式修改的应用程序或域都将被该工具忽略，这些必须手动迁移。

== 手动迁移您的代理或API网关应用程序

从API网关2.0.0或更高版本开始，端点模型不再受支持。这意味着您可以继续使用HTTP端点和连接器（这不是建议的做法），但是您将无法管理与其关联的任何策略，并且不会获得任何使用情况统计信息。此外，使用API​​ Gateway 2.0.0及更高版本时，任何使用自动发现的入站端点将在将应用程序/代理部署到API网关时导致分析异常。

如果您使用的是较早的自动生成的代理，建议您使用Anypoint Platform自动生成一个新的代理，然后配置所需的额外功能，复制之前在旧代理上执行的更改。

如果您使用API​​Kit插件，请确保您使用的是1.7.0或更高版本。 API Gateway 2.0.0不支持此插件的早期版本。

这些是需要考虑的两个主要变化：

=== 非阻塞策略

API Gateway 2.0.0针对非阻塞处理策略进行了优化，当应用程序/代理在高负载系统中运行时，可为您提供明显的性能优势。为API Gateway 2.0构建的所有代理都设置了一个标志来启用此功能。要启用此功能，只需在代理的XML开头包含以下代码行，以及任何流之外的其他配置元素。

`<configuration defaultProcessingStrategy="non-blocking" />`

=== 使用监听器

与Mule 3.7一起提供的新交换机取代了旧的入站端点模型，是政策管理和统计数据生成的唯一支持。您必须替换新的HTTP侦听器连接器的HTTP入站端点的每个实例，还必须将相应的XSD架构添加到应用程序。

[TIP]
====
要将对旧HTTP连接器所做的更改复制到新的高性能HTTP连接器上，请使用 link:/mule-user-guide/v/3.7/migrating-to-the-new-http-connector[迁移到新的HTTP连接器]作为参考。
====
