=  Anypoint MQ连接器发行说明
:keywords: mq, connector, release, notes

*April 2018*

_选择_

为了正确支持Exchange 2.0，Anypoint MQ Connector的功能ID已更改。在下载 link:https://www.mulesoft.com/exchange/org.mule.tooling.messaging/mule-module-anypoint-mq-ee-studio/[来自Exchange 2.0的v1.2.0和更高版本]之前，请在Studio中卸载此连接器的现有版本。

Anypoint MQ Connector的这个版本允许您添加对Anypoint Studio应用程序的Anypoint MQ队列和交换的消息访问。

也可以看看：

*  link:/release-notes/mq-release-notes[Anypoint MQ云版本说明]
*  link:/anypoint-mq[Anypoint MQ文档]

== 版本1.3.3  -  2018年4月26日

版本1.3.3包含以下修复和更改：

* 改进的调试日志记录 - 记录来自MQ的响应时间，提供了有关从MQ接收到的响应的更多信息。
* 在MQ服务器端队列配置中使用默认锁定TTL作为MQ连接器中的缺省acknowledgementTimeout时，默认情况下，MQ连接器不会让它重写为2分钟。 （SE-7951）

=== 版本1.3.3  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule Runtime  | 3.7.4及更高版本
| Anypoint Studio  | 5.4.n及更高版本
|===

== 版本1.3.2  -  2018年2月15日

此版本提供了一个错误修复。

=== 版本1.3.2  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule Runtime  | 3.7.4及更高版本
| Anypoint Studio  | 5.4.n及更高版本
|===

=== 版本1.3.2  - 已在此版本中修复

* 运行MUnit测试用例时，向Anypoint MQ发布消息失败。 （SE-6804）

== 版本1.3.1  -  2017年12月11日

此版本允许使用属性占位符来进行pollingTime，reconnectionWaitTime，reconnectionAttempts和acknowledgementTimeout，并修复了一个问题。

=== 版本1.3.1  - 在此版本中已修复

* 任何点MQ REST客户端在"AUTHORIZE AGAINST BROKER"之后停止。 （SE-7294）

== 版本1.3.0  -  2017年12月1日

此版本添加了这些功能：

* 预取配置提供了新选项，可以让您决定预取在停止前重试其操作的次数，以及每次重试之间等待的时间。

* 现在可以在Mule流中配置MQ连接器时使用以下属性的属性占位符：轮询时间（pollingTime），重新连接等待时间（reconnectionWaitTime），重新连接尝试次数（重新连接尝试次数）和确认超时acknowledgementTimeout）。

=== 版本1.3.0  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule Runtime  | 3.7.4及更高版本
| Anypoint Studio  | 5.4.n及更高版本
|===

=== 版本1.3.0  - 修正了问题

* 修复连接器预取onError方法，以便在未找到队列时停止轮询（MQ-909）
*  Anypoint MQ未使用系统属性来配置pollingTime。 （SE-7176）
* 修复了轮询邮件时可能导致频繁超时的问题。 （MQ-876，SE-6811，SE-6353，SE-5670）

== 版本1.2.3  -  2017年10月5日

Anypoint MQ连接器现在提供https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[_Select_]连接器支持策略。

在此版本中已修复 - 将MQ连接器移至Select支持策略。 （MQ-752）

== 版本1.2.0  -  2017年8月23日

为了支持Exchange 2.0，Anypoint Studio中连接器的ID更改为org.mule.tooling.ui.extension.mule-transport-amqp-tooling.3.5.0.feature.group  - 由于此更改，版本3.7.2不会在连接器更新站点中显示为更新，而会显示为新的连接器。在安装v1.2.0之前，如果版本是v1.1.3或更早版本，请卸载现有的Anypoint MQ Connector


== 版本1.1.3  -  2017年7月28日

此版本用于内部错误修复并解决此问题：

* 当针对包含MQ端点的项目运行时，MUnit会给出空指针异常。 （SE-4976）

== 版本1.1.2  -  2017年5月9日

本版本修复了这些问题：

*  Anypoint MQ连接器中的默认clientMode仍然将MULE设置为默认值。 （SE-5739）
* 任意点MQ服务不可用。 （SE-5700）
*  Anypoint MQ订户不遵守计划服务中的scheduleAtFixedRate。 （SE-5680）

== 版本1.1.1  -  2017年3月27日

*Important:*由于影响MQ平台的错误，此版本已从我们的存储库中删除。如果您使用此版本，则应尽快升级到新版本，以避免影响您或其他MQ客户。

Anypoint MQ连接器版本1.1.1更改了默认连接模式。
当前的*Client Mode*（或XML `clientMode`）会更改
在此版本中默认为*SYNC*。 MULE值已在版本1.1.1中弃用，并且正在被删除
在下一个版本中 - 直到下一个版本，MULE值仍然可用。

* 在发布到Anypoint MQ时失败时优化错误消息。 （SE-5503）
*  MQ订户超时。 （SE-5286）
*  AbstractCourierRestClient.getAccessToken阻止所有线程。 （SE-5221）
*  MQ用户在发生多次504错误后断开连接。 （SE-5167）

== 版本1.1.0  -  2016年12月6日

Anypoint MQ连接器1.1.0版发布包括以下错误修复和改进：

* 修复了在使用Anypoint MQ连接器时支持“无”确认模式的情况。 （MQ-564）
* 修复了MQ连接器以“手动”确认模式纠正错误。 （SE-4433）
* 修复以支持Anypoint MQ连接器的 link:/munit/v/1.3.0/using-munit-in-anypoint-studio[MUnit测试套件]。 （SE-4189）
* 修复以确保ACK超时期限。 （SE-4575）
* 使用Mule Runtime 3.8.1修复消息重新传送异常。 （SE-4378）
* 修复由于重负载下的授权令牌上竞争条件导致的MQ代理错误。 （SE-4468）
* 修复了重复用户代理和授权标题。 （SE-4793）

已知问题：

使用Anypoint Exchange下载连接器时，Anypoint MQ连接器不会安装
窗口从Anypoint Studio启动。请使用帮助>安装新软件>使用>
`Anypoint Connectors Update Site`。单击社区> Anypoint MQ下载并安装Anypoint MQ连接器。

== 版本1.0.2  -  2016年9月10日

NONE的ACK现在可以正常工作。有关更多信息，请参阅 link:/anypoint-mq/mq-ack-mode[确认模式]。

== 版本1.0.1  -  2016年4月5日

在此版本中已修复：

* 工具提示已添加到Anypoint Studio for Anypoint MQ连接器。 （MQ-383）
* 修复了有多个MQ配置时MQ连接器的问题。 （MQ-379）
* 最大重新传输计数的默认值设置为-1（无限重试）。 （MQ-378）
* 允许设置超时中等流量。 （MQ-365）
* 应用程序流中使用的无效MQ订阅服务器导致应用程序抛出错误并阻止应用程序的启动。 （MQ-364）
* 应用程序流中使用的无效MQ目标会导致应用程序抛出错误并阻止应用程序的启动。 （MQ-363）
* 发布操作会覆盖所有Mule事件内容。 （MQ-353）
* 修复了连接器问题，导致MQ订阅服务器在包含慢速实例和队列的情况下随机停止检索消息而没有任何消息。 （SE-3473）

== 已知问题

*  Anypoint MQ连接器当前不支持跟踪。
+
跟踪示例：
+
[source,xml,linenums]
----
<flow name="customers-all-get" tracking:enable-default-events="true">
  <anypoint-mq:subscriber config-ref="Anypoint_MQ_Configuration" destination="testQueue" acknowledgementMode="AUTO"/>
  <tracking:transaction id="customers-all-get"/>
</flow>
----
+
这与删除订阅者跟踪语句的例子相同：
+
[source,xml,linenums]
----
<flow name="customers-all-get">
  <anypoint-mq:subscriber config-ref="Anypoint_MQ_Configuration" destination="testQueue" acknowledgementMode="AUTO"/>
</flow>
----

