=  MSMQ连接器发行说明
:keywords: release notes, msmq

*January 2018*

_选择_

Microsoft消息队列连接器。

*Guides:*

*  link:/mule-user-guide/v/3.8/msmq-connector[MSMQ连接器]
*  link:/mule-user-guide/v/3.8/windows-gateway-services-guide[Windows网关服务指南]
*  link:/release-notes/windows-gateway-services-release-notes[Windows网关服务发行说明]

[NOTE]
*Important*：在安装和配置MSMQ之前先安装 link:/mule-user-guide/v/3.8/windows-gateway-services-guide[Windows网关服务]。

== 版本1.9.1  -  2018年1月22日

包含在此版本中：

* 修正：执行MSMQ receive（）的线程卡在SocketInputStream.socketRead（）中，
  它需要重启应用程序才能从问题中恢复。

== 版本1.9.0  -  2016年7月11日

包含在此版本中：

* 改进：通过网关的请求/响应来更新合同。
* 修正了构建安全上下文时的模拟问题。

== 版本1.8.0  -  2016年6月17日

包含在此版本中：

* 已添加：支持新的消息传递工作模式（现在有两种模式：不确认和至少一次）。
* 改进：无效凭证和相关事宜的错误消息。
* 改进：当网关不可用时，某些情况下的连接重试。
* 改进：内存使用和资源处置。
* 修正：加载用户配置文件时发生错误时测试连接。

== 版本1.7.0  -  2016年1月28日

包含在此版本中：

* 已添加：新属性`mule-msmq-queue-override-authenticate`，以允许连接到已验证的队列。
* 已添加：新属性`mule-msmq-queue-override-transactional`，允许发送到标记为事务性的远程队列。
* 改进：对高CPU和低内存条件的恢复能力。
* 改进：出现MSMQ邮件出现错误时的弹性。
* 修正：MSMQ服务不可用时从处理失速中恢复。
* 修正：连接池清理，以防止在压力条件下由于内部泽西例外泄漏。

== 版本1.6.1  -  2015年12月11日

本版本新增功能：

* 修复了HTTP连接在使用后未正确关闭的问题。
* 添加连接池以重用现有的HTTP连接。
* 增加了新的"cleanup-delay"设置，以避免负载平衡方案中的并发问题。

== 版本1.6.0  -  2015年11月4日

在这个版本中：

* 修复了无法读取Active Directory中的公共MSMQ队列的问题。
* 增加了对支持在负载平衡配置中运行Windows网关服务以支持容错功能的支持。
* 有关最新的安装软件，请参阅 link:/mule-user-guide/v/3.7/windows-gateway-services-guide[Windows网关服务指南]。

== 版本1.5  -  2015年4月28日

本版本新增功能：

* 将Jersey库升级到2.11以防止与Mule服务器使用的内部版本冲突。
* 修复了网关中的出列服务不符合用户界面中指定的轮询间隔的问题。
* 调整性能以在重负载下提供一致的响应时间。

== 版本1.4  -  2015年3月12日

=== 版本1.4兼容性

Microsoft消息队列（MSMQ）连接器兼容：

[%header,cols="2*"]
|===
一个|
应用程序/服务

 为|
版

| Mule运行时 | 3.5和3.6
| Anypoint Studio a |
*  Mule 3.6  -  2015年1月Studio，版本5.0.n
*  Mule 3.5  -  2014年10月Studio

| .NET Framework  | 4.0
| JRE  | 1.6如果使用Mule 3.5和JRE 1.7，如果使用Mule 3.6
|===

本版本中已修复=== 版本1.4

作为MSMQ连接器和Windows网关服务更新的一部分，以下问题在MSMQ连接器的1.4版中得到修复：

* 如果未在全局元素级别指定队列名称，即使连接器实例定义了覆盖此全局队列设置的队列名称，也会重复报告错误消息，指出`org.mule.modules.msmq.MsmqException: Queue not found:"null"`。如果全局元素未指定要使用的队列名称，则不再运行队列连接测试。

* 在Studio 5.0.2和ESB 3.6中，测试连接报告错误，指出由于`java.lang.NoClassDefFoundError: com/sun/jersey/api/client/config/ClientConfig. `而导致测试失败。这是由于连接器中的Jersey版本与Studio不同步导致的， ESB服务器。

* 如果在Studio或ESB服务器中热重新部署Mule应用程序，则MSMQ连接器将报告一个错误，指出` Receiving Thread ERROR org.mule.modules.msmq.MsmqConnector - Error while trying to process response. Cannot process event as "applicationName" is stopped (org.mule.api.lifecycle.LifecycleException).`这是由于始终未调用停止回调引起的。

[IMPORTANT]
此版本需要升级到适用于Windows的Anypoint Gateway Service 1.4版。有关更多信息，请参阅 link:/mule-user-guide/v/3.8/windows-gateway-services-guide[Windows网关服务指南]。

=== 版本1.4下载网站

从 link:https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/modules/anypoint-windows-gateway-service/1.4.0/anypoint-windows-gateway-service-1.4.0.zip[这里]下载Anypoint Gateway for Windows安装程序，解压缩软件分发包，然后按照 link:/mule-user-guide/v/3.7/msmq-connector[MSMQ连接器]中的说明进行操作。

== 版本1.3  -  2015年2月4日

=== 版本1.3兼容性

Microsoft消息队列（MSMQ）连接器兼容：

[%header,cols="2*"]
|===
一个|
应用程序/服务

 为|
版

| Mule运行时 | 3.5和3.6
| Anypoint Studio a |
*  Mule 3.6  -  2015年1月Studio
*  Mule 3.5  -  2014年10月Studio

| .NET Framework  | 4.0
| JRE  | 1.6如果使用Mule 3.5和JRE 1.7，如果使用Mule 3.6
|===

=== 版本1.3下载网站

从 link:https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/modules/anypoint-windows-gateway-service/1.3.0/anypoint-windows-gateway-service-1.3.0.zip[这里]下载Anypoint Gateway for Windows安装程序，解压缩软件分发包，然后按照 link:/mule-user-guide/v/3.7/msmq-connector[MSMQ连接器]中的说明进行操作。

按照 link:/mule-user-guide/v/3.8/msmq-connector[MSMQ连接器]中的说明从Studio下载MSMQ连接器。

本版本中的=== 版本1.3更改

* 性能调优：对于邮件有效负载超过1kB的高事务量，连接器的性能得到了改进。
* 默认端口更改：提供MSMQ连接的Anypoint Gateway服务的默认侦听器端口已更改为9333，以防止与在端口9000上运行的Service Bus冲突。

=== 版本1.3错误修复

没有。

=== 版本1.3已知问题

没有。

== 版本1.2  -  2014年11月12日

=== 版本1.2兼容性

Microsoft消息队列（MSMQ）连接器兼容：

[%header,cols="2*"]
|===
一个|
应用程序/服务

 为|
版

| Mule运行时a |
*  3.5.x的
*  3.4.1

| Anypoint Studio  | 2014年10月
| .NET Framework  | 4.0
| {JRE {1}} 1.6
|===

=== 版本1.2下载网站

从 link:https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/modules/anypoint-windows-gateway-service/1.2.0/anypoint-windows-gateway-service-1.2.0.zip[这里]下载Anypoint Gateway for Windows安装程序。

解压缩软件分发。有关更多信息，请参阅 link:/mule-user-guide/v/3.8/msmq-connector[MSMQ连接器]。

=== 版本1.2新功能

没有。

=== 版本1.2错误修复

远程队列可靠消息传递支持：修复了由于与使用子队列的可靠消息传递功能进行交互而导致从远程队列中成功消除队列的错误。

对于远程队列，从MSMQ 1.1开始支持FormatName队列地址表示法。以前，如果尝试在连接到远程队列时尝试使用DIRECT或另一个FormatName，则会引发异常。

=== 版本1.2已知问题

没有报告的问题在此版本中未解决。

== 版本1.1  -  2014年10月7日

=== 版本1.1兼容性

Microsoft消息队列（MSMQ）连接器兼容：

[%header,cols="2*"]
|===
一个|
应用程序/服务

 为|
版

| Mule运行时a |
*  3.5.x的
*  3.4.1

| Anypoint Studio  | 2014年10月
| .NET Framework  | 4.0
| {JRE {1}} 1.6
|===

=== 版本1.1下载网站

从 link:https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/modules/anypoint-windows-gateway-service/1.1.0/anypoint-windows-gateway-service-1.1.0.zip[这里]下载Anypoint Gateway for Windows安装程序。

解压缩软件分发。有关更多信息，请参阅 link:/mule-user-guide/v/3.8/msmq-connector[MSMQ连接器]。

=== 版本1.1功能

MSMQ连接器现在支持：

*   *Message exception management*：在发送或接收排队消息的过程中发生的错误现在会直接在流中引发异常。这允许Mule内置的日志记录和错误路由支持自动调整。在没有定义异常管理策略的情况下，根据实例配置中指定的消息或目标队列所在机器的系统死信队列将消息返回到死信队列。
*   *Exactly-once in-order support:*当一个流的`message-processing-strategy`被设置为同步时，从MSMQ队列处理的消息将保证按照它们发送的顺序呈现给流，并且只能收到一次。

*   *CloudHub support*：MSMQ连接器现在必须经过认证才能在CloudHub上使用。您可以将您的Mule应用程序部署到CloudHub。确保连接器配置指向本地运行的Anypoint Gateway Windows服务。 Anypoint Gateway Windows Service将接口提供给企业中的MSMQ基础架构，因此它必须在部署之前安装并验证为工作。

*   *Message timeouts*：您现在可以设置*timeToBeReceived*和*timeToReachQueue*属性设置的秒数。当发生这些超时中的任何一个时，消息被移动到作为原点的子队列存在的死信队列中。您可以使用连接器的实例属性自定义死信队列的位置。这两个属性默认为零（0），这表明该属性永远不会超时。

*   *Message acknowledgement*：通常不是MSMQ消息的消息现在出现在流中，允许替代子流处理诸如ACK上的相关性或NACK上的重试等条件。这些消息可以通过消息属性来标识。您可以使用自定义恢复或日志逻辑来设置选择控制流的形状。
*   *Zero-message-loss to bus*：当使用事务队列时，MSMQ连接器现在保证消息在传递到总线时为零消息丢失。只有在Mule成功接收到消息后，才能将其从原始队列中删除。除了选择标记为事务性的MSMQ队列之外，用户不需要执行其他配置。骡在后台管理可靠的出队队列。


=== 版本1.1错误修复

现在远程队列支持FormatName队列地址表示法。以前，如果尝试在连接到远程队列时尝试使用DIRECT或另一个FormatName，则会引发异常。

=== 版本1.1已知问题

没有报告的问题在此版本中未解决。

== 版本1.0  -  2014年7月23日

=== 版本1.0兼容性

MSMQ连接器兼容：

[%header,cols="2*"]
|===
|应用/服务 |版本
| Mule运行时a |
*  3.5.x的
*  3.4.1

| Anypoint Studio  | 2014年7月
| .NET Framework  | 4.5
|===

此版本中已修复=== 版本1.0

此版本中没有错误修复。

=== 版本1.0已知问题

没有报告的问题在此版本中未解决。

== 另请参阅

*  https://forums.mulesoft.com [MuleSoft论坛]。
*  https://support.mulesoft.com [联系MuleSoft支持]。

