=  Mule 2.2.0发行说明
:keywords: release notes, esb

*  <<Enhanced Expression Support>>
*  <<Support for Spring Security 2.0>>
*  <<Support for Spring-first Deployments for Mule Embedded in a Webapp>>
*  <<Simplified Message Styles>>
*  <<Additional Improvements>>
* 解决了2.2.0的问题

Mule 2.2.0社区版现在可用。这个版本包括几个新功能，使Mule更强大，更易于使用。

== 增强的表达式支持

表达式允许您从当前消息中提取信息或确定如何处理消息。表达式对路由器和过滤器非常有用，用于定义路由逻辑和过滤不需要的消息。在Mule 2.2中，您现在可以使用强大的新Mule表达式语言，它提供了查询消息属性，附件有效负载，Mule上下文信息（如当前服务或端点）以及访问注册表的统一语言。另外，您现在可以在全局声明一个名称空间，以便Mule中的XPath表达式可以使用它。 +
例如，以下Jaxen过滤器会声明一个名为"e"的名称空间，然后在过滤器表达式中使用它：

[source, xml, linenums]
----
<outbound>
  <filtering-router>
    <outbound-endpoint address="vm://echo" synchronous="true"/>
    <mule-xml:jaxen-filter pattern="/e:purchaseOrder/e:shipTo/@country" expectedValue="US">
      <mule-xml:namespace prefix="e" uri="http://www.example.com"/>
    </mule-xml:jaxen-filter>
  </filtering-router>
....
</outbound>
----

有关更多信息，请参阅Mule运行系统中的 link:/mule-user-guide/v/3.2/using-expressions[使用表达式]。

== 支持Spring Security 2.0

您现在可以使用Spring Security 2.0作为Mule的安全管理器。 Spring Security是Acegi的下一个版本，提供了许多身份验证和授权提供程序，如JAAS，LDAP，CAS（耶鲁中心身份验证服务）和DAO。您可以使用Mule的任何图书馆安全提供商。有关更多信息，请参阅Mule Runtime文档中的 link:/mule-user-guide/v/3.2/configuring-security[配置安全性]。

== 支持在Webapp中嵌入Mule的Spring-first Deployments

作为Mule社区用户的补丁提供，该功能让Mule可以使用现有的应用程序上下文（WebApplicationContext）（如果它已经由Spring创建）作为Mule配置生成器的父应用程序上下文。这让Mule可以轻松访问您在Spring应用程序上下文中配置的所有bean。有关更多信息，请参阅Mule Runtime文档中的 link:/mule-user-guide/v/3.2/spring-application-contexts[Spring应用程序上下文]。

== 简化的邮件风格

现在，同步消息传递风格固有地支持远程同步模式，因此不再需要在端点上设置`remoteSync`属性。另外，您可以在每个同步端点上明确指定同步属性（默认值为false，创建异步端点），这使您的配置更易于解释和控制。有关更多信息，请参阅Mule Runtime文档中的 link:/mule-user-guide/v/3.2/service-messaging-styles[消息样式]。

== 其他改进

* 新的XPath提取器转换器，BeanBuilderTransformer转换器，XPath过滤器和模式验证过滤器
* 修复了示例并彻底改变了Bookstore示例以使用Web服务
* 支持可扩展的SQL策略
*  CXF Web服务代理现在支持附件
*  CXF客户端现在可以将自定义的Mule消息属性正确传递给服务器
* 如果JMS服务器支持原生JMS重新传递计数器（回退到旧式手动计数）
* 改进了对SunMQ / OpenMQ的JMS主题订阅支持
* 改进名称中带有斜杠的JMS目标的JNDI查找
* 在连接器/端点级别上显式控制JMS临时回复目标的创建
* 每个入站汇聚路由器现在都支持部分汇总的`timeout`和`failOnTimeout`
* 现在，每个连接器都有一个`validateConnections`配置属性，充当性能优化提示
* 修复了某些IBM J9和JRockit版本在启用专有JVM优化时的故障
* 澄清并清理消息属性范围和优先级
* 清理使用OSGi重新绑定的依赖关系
* 改进和扩展文档
* 修复了许多错误并增加了测试覆盖率

有关从Mule 2.1迁移到Mule 2.2的更多详细信息和信息，请点击 link:/mule-user-guide/v/3.2/release-and-migration-notes[这里]。

