=  Mule IDE 1.4.3发行说明
:keywords: release notes

请参阅IDE主页以获取安装说明以及如何创建和运行示例项目。

Mule IDE使用在Java 5 JRE上运行的 link:http://www.eclipse.org/downloads/[面向Java开发人员的Eclipse IDE]的Europa版本进行测试。

新项目向导无法成功创建包含在1.4.3 Mule分发中的几个示例项目，并将其从示例项目选项中排除：贷款代理BPM示例和Web应用程序示例。

当在Mule Libraries Configure对话框中添加Mule模块和传输时，Mule IDE将尝试自动将所有依赖库添加到项目构建路径。然而，某些第三方jar可能不包含在Mule发行版中，并且/或者可能不会在发行版中的jar清单类路径中引用。这些库需要手动添加。在项目菜单中，选择属性。转至Java Build Path属性页面，单击Libraries选项卡并使用"Add External Jars..."将jar添加到项目中。

默认的Mule启动配置将应用程序工作目录设置为Eclipse项目根目录。因此，在从Eclipse运行示例项目之前，可能需要编辑配置文件中的相对路径。例如，在Error Handler示例项目中，需要将conf目录添加到email.properties和error-beans.xml路径中：

[source, xml, linenums]
----
<environment-properties>
        <file-properties location="conf/email.properties" />
    </environment-properties>

    <container-context className="org.mule.extras.spring.SpringContainerContext">
        <properties>
            <property name="configFile" value="conf/error-beans.xml"/>
        </properties>
    </container-context>
----


MULEIDE-41：Mule IDE的配置文件验证器没有正确解析mule-descriptor实现属性中的bean引用。例如，在Error Handler示例项目中，可以忽略在"errorManager"和"businessErrorManager" bean引用上标记的类未找到的错误。它们不影响运行应用程序的能力。

MULEIDE-38：Mule IDE的配置文件验证器不会在对项目的构建路径进行更改后自动运行。添加Mule模块或传输或引用库后，使用项目 | 清理...刷新错误标记。

MULEIDE-27：在首选项对话框中更改Mule分布将不会重新计算类路径。
