=  Mule 2.0发行说明
:keywords: release notes, esb


由于没有关键问题，我们很自豪地宣布Mule 2.0的最终/ GA版本。我们要特别感谢所有在里程碑和发布候选人中提供反馈并报告错误的用户。

== 发布候选人3

自2.0.0-RC2以来，已有157个问题关闭。

link:https://docs.mulesoft.com/[文件]正在进行中。本用户指南包括从核心，模块和传输模式自动生成的XML配置文档。

在2.0.0-RC3中解决了几个与性能相关的问题，并进行了一些性能测试，以确保2.0.0性能与1.4.3一样好，并且实施了以下重大更改：

*API*

* 我们完成了软件包的重新组织工作，但更改仅限于示例和模块，因此与RC2中的大量更改相比，影响应该很小。
* 有一些Service / Component API更改，但这些更改仅影响模块开发人员，不会影响用户。

*Expression evaluation framework* +
允许以通用的方式在mule中使用表达式。表达式值在运行时使用表达式评估器进行解析。实现存在消息头属性，消息有效载荷，消息附件，xpath表达式，脚本表达式。这些表达式可用于变换器，过滤器，端点选择器路由器和文件名解析器等。

*CXF replaces XFire* +
XFire运输在主要发行版中已被弃用，以支持CXF。这是因为CXF是构建Web服务的更强大的解决方案（它可以被认为是下一代XFire），并且由于分发CXF和XFire在类路径中创建了冲突。使用XFire的Mule示例已被迁移到使用CXF。您将需要Java 5来编译和运行使用CXF的示例。

*XML Configuration*

*  mule-core模式注释几乎是完整的，因此您在创建/编辑xml配置时将获得更多上下文相关的文档。
* 对实施的模式进行了一些小的改进。
* 我们改进了使用<component>和对象工厂：i）您现在可以池包括spring beans在内的任何组件对象，ii）通过<pooled-component>元素显式使用池。 iii）<pooled-object>对象工厂已被删除，应该使用<pooled-component>。
* 模型元素不再需要名称，如果没有指定名称，则自动生成名称。
* 代理元素不再需要名称，它们具有固定的内置名称。
*  XML配置语法已更新为使用"Expression evaluation framework"。
* 服务器标识和工作目录不能再在xml配置中进行配置，如果需要覆盖默认值，则应通过系统属性对其进行配置。

== 发布候选人2

自RC1以来，共有102个问题关闭，Mule 2.0的第二个候选版本变得更加稳定。

此版本首次包含Mule CXF Transport，它是Mule的XFire Transport通过 link:http://cxf.apache.org/[Apache CXF]进行Web服务集成的演变。

RC2值得一提的其他重大变化或改进如下：

*API* +
此版本包含大量的API重组。这种重新组织涉及接口的移动和重命名以及少量整理。接口不再以'UMO'为前缀，现在使用'org.mule.api'包而不是'org.mule.umo'。 'ManagementContext'也被重新命名为'MuleContext'和'org.mule.providers'为'org.mule.transport'。我们希望利用2.0作为主要版本来介绍这些变化，但不幸的是，这并没有使它成为RC1。

*ConfigurationBuilder + MuleContextFactory* +
ConfigurationBuilder API得到了改进，现在只是配置一个mule实例，而不是创建MuleContext并对其进行配置。新的MuleContextFactory用于创建MuleContext，并且提供了一个DefaultMuleContextFactory，它的方法允许以类似于旧的MuleXMLConfigurationBuilder的方式创建和配置MuleContext。

*XML Configuration* +
使用Spring的Mule 2.0的配置现在已经被抽象为'spring-config'模块，'mule-core'不再依赖于Spring。为了使用XML配置，你现在需要在你的类路径中包含'spring-config'模块。 'mule-core'中的MuleXMLConfigurationBuilder被移动到'spring-config'模块并重命名为'SpringXMLConfigurationBuilder'。

*XML Configuration Syntax* +
我们修改并简化了此版本的XML模式。这是最终版本，未来的RC版本将更加稳定。主要变化是：

* 响应端点现在只是入站端点
* 主要服务结构不再使用"-router"（因为容易混淆的是"router collections"）。现在是：+
  <service> +
    <inbound/> +
    <component/> +
    <outbound/> +
    <async-reply/> +
  </service> +
 （为了保持一致性，其他地方的"response"已更改为"async-reply"）
* 事务是单个元素（无工厂）
* 添加了入口点解析器并删除了"no args call wrapper"
 （有关许多详细示例，请参阅EntryPointResolverTestCase）
*  Transformer现在将"-transformer"中的*end*命名为与其他元素一致
* 组件配置稍微清理一下

== 发布候选人1

Mule开发团队非常高兴地宣布推出2.0版的第一个候选版本，这是Mule ESB的下一代产品，并且相信我们甚至还有一些文档可用！

首先查看 link:/mule-user-guide/v/3.2/about-mule-configuration[Mule 2.0配置指南]，了解2.0 Mule配置与1.4配置的对比。

对于那些有兴趣为自定义模块/传输创建XML命名空间的人（或者只是想知道其工作原理的细节），请阅读 link:/mule-user-guide/v/3.2/creating-a-custom-xml-namespace[如何创建一个XML命名空间]。

许多工作已经进入Mule 2.0（例如，请参阅下面列出的425个问题），所以我们真的希望您尝试一下，让我们知道它是如何发展的。

还有一点值得一提的是，我们一直在不断合并来自1.x的修复，所以任何针对1.4.4解决的问题都应该在2.0中解决

== 里程碑/ "Technology Preview"第2版

自从最后一个里程碑以来，我们一直在努力开展Mule 2.0开发工作，并且我们希望将这项工作提供给感兴趣的社区成员预览。还有一段路要走，但是我们正在逐渐接近最终的2.0版本。随时来看看，让我们听到您的意见。

== 里程碑/ "Technology Preview"发布1

Mule开发团队正在努力开发Mule的下一个主要版本，并很高兴地宣布，可以下载并试用Mule 2.0的第一个里程碑。请注意，尽管取得了很大进展，但还有很多工作要做，所以这个里程碑仅仅是一个工作进程中的"Technology Preview"。

我们鼓励Mule用户有兴趣了解未来，尝试新的配置风格（最好在您最喜欢的Java IDE中，它应该允许通过XML模式自动完成，这在Eclipse和IDEA中已经过测试）。我们非常希望听到您的想法和任何建议，以便我们能够更好地满足您作为Mule用户的需求。并且，像往常一样，保留那些有用的错误报告！

