=  Mule 0.8发行说明

自0.7.1版本开始，Mule就经历了一次重大改革。重新架构的目的是简化使用和开发，提高可扩展性，并创建更灵活，更强大的企业服务总线服务器。进行了以下更改。

=== 零码入侵

UMO组件不需要扩展MuleUMO或任何其他抽象类或接口。任何对象，bean或其他框架组件都可以通过mule进行管理。

===  IoC或依赖注入器支持

骡子现在有外部容器支持。这意味着您的UMO组件和/或任何支持对象可以存在于外部Ioc容器（如Spring或 http://picocontainer.com/[PicoContainer的]）中。 Mule还提供了一个简单的界面来添加你自己的容器支持。

=== 生命周期管理

UMO组件可以具有可配置的生命周期支持。因此，由Mule管理的现有组件仍然会触发其生命周期方法，即init（），start（），stop（）等。

=== 拦截

拦截器基于与使用命令模式的Servlet过滤器相同的原理。拦截器可以链接在一起执行定时，分析，安全/权限检查，装饰或任何其他调用的每个umo。您也可以在配置中定义标准拦截器堆栈，并将堆栈应用到您的UMO组件。 +
拦截器替换之前版本Mule中的链。

=== 示例应用程序

添加了两个示例应用程序以开始使用Mule。请参阅示例了解更多信息。另外，计划参考应用程序来测试Mule的所有功能。

=== 测试兼容性工具包

Mule有一个测试兼容性工具包（TCK），它提供一系列用于骡子中常见组件的抽象测试案例，例如提供者，变换器和组件解析器。有关更多信息，请参阅TCK（http：/www.muleumo.org/tck.html）。

=== 变压器

消息转换器现在可以链接在一起以允许更精细的变压器实现，即

----
JMS TextMessage -> String (XML) -> BeanBean -> String (XML) -> XSL Transform -> Email Message
----

细粒度的变压器实现更具可重用性。

=== 提供商

提供者现在与Mule项目分开打包和记录。这将删除Mule项目中的所有提供者依赖关系，并允许对提供者进行选择和使用。这也让第三方提供商更容易与Mule进行分销。 _src / providers / template_目录中有新提供者的项目模板。

=== 文档

所有网站文档已更新，并添加了新的文档，如“体系结构指南”。

== 下一步是什么？

很明显，Mule有很多根本性的变化，这意味着没有时间来添加任何新的组件，而且我认为Mule中仍然需要一些突出的功能：

* 事务支持需要透明地构建到提供程序中，并通过配置进行控制。这是名单上的下一个。 +
Mule需要更好的安全性，无论是在端点之间加密数据（需要类似于压缩转换器的变压器实现）以及通过提供者访问总线的应用程序的凭证检查。
* 嗨，Web服务提供商发生了什么？我担心它会摔倒在地，需要重新拾起。没有它就发布了这个版本，因为不是所有的ESB实现都使用WS。 WS提供商将很快发布。
* 供应商清理。提供者被排除在重构之外，因为我认为他们的界面不需要改变以便清理它们。目前有些执行线程，有些则不执行。我认为Mule应该为所有提供者提供线程框架。还需要添加对许可检查（通过提供者发送和接收）和事务管理的支持。同样，这些功能应该是透明的，不应该影响当前的API。
* 综合配置模型。 Mule的当前配置实现并不是非常灵活或可扩展的，尽管它确实有效，所以不需要着急。
* 一个新的Mule图标会很好。我认为目前的一个有点跛脚！

== 路线图上有什么？

这些是我希望Mule拥有的东西。其中一些，如果不是全部是子项目。如果任何人有兴趣提取这些，我会很乐意与您交谈。

* 配置GUI会很棒。关于mule最难的事情之一是它的配置，用户界面真的有帮助。
* 基于Web的管理/监控GUI也是非常理想的。我想我需要将JMX支持添加到Mule中，并且还要深入研究JMX，以便您可以执行诸如将命令发送到组件（如停止处理）的操作。
* 更多供应商！有了所有的重构，我没有时间写更多的提供者。现在最重要的是Web服务提供者和JDBC提供者/ OR映射提供者。
* 持久性/序列化/反序列化模板策略。基本上提供一个骨架持久层，您可以插入持久性和对象序列化策略。
