=  Mule 0.9.2发行说明

有此版本中的新东西，包括Spring集成的事件，一个新的Servlet提供商，强大的骡子客户，提高路由支持，常规变压器的支持和更多的整个负载。更不用说很多错误修复和改进。

Spring中的===  Mule事件

骡经理现在可以作为Spring事件代理服务器。的Spring bean可以发送和通过JMS，SMTP，POP3，HTTP或使用Spring事件API的任何其他骡子运输收到骡子事件。阅读更多...

用于REST样式服务的===  Servlet提供程序

是通过servlet发送和接收事件的新提供者。还有一个servlet实现使用Servlet提供程序来启用REST风格的服务访问。

===  Mule客户端

<<Mule Client>>是一个简单但功能强大的客户端，可与mule服务器进行通信。它允许任何客户端（如Jsp，脚本或纯Java）通过Mule服务器发送和接收事件。

=== 改进了路由支持

添加标准的入站和出站路由器实现方式，路由得到了改进，例如 - 

* 选择性消费者 - 基于过滤器的消息消费
{0}}幂等接收者 - 确保收到的每条消息都是唯一的
* 基于内容的路由器 - 使用过滤器基于内容路由消息。
* 消息分配器 - 将消息部分路由到不同的收件人
* 收件人列表 - 将同一邮件路由到多个收件人
* 广播路由器 - 通过多个传输+路由相同的消息
当然，这很容易实现你自己的。

===  Spring自动装配配置

使用弹簧自动布线功能简化Mule配置。阅读更多...

=== 改进的Jms同步支持

现在，来自同步调用的事件链使用replyTo功能在Jms服务器上传播。

=== 细化的线程池调优

更多控制连接器和组件的线程选项。消息接收器和调度程序的线程现在可以单独控制每个连接器。 +
线程池现在使用oswego并发库。

=== 示例webapp

示例mule webapp是如何将mule嵌入到webapp中的简单演示。它还提供了使用Servlet提供程序的示例。

===  Groovy支持

感谢Ian de Beer，您现在可以使用Mule的新Groovy变形金刚改变讯息。

=== 支持多个配置文件

您现在可以将您的骡子配置分成更小的单元，即每个组件一个配置文件。

=== 支持通配符端点

现在可以使用通配符端点接收事件，例如，下面将匹配“mule.event.queue”  - 

*  *。event.queue
* 骡。*
*  \ *.event.*

=== 每个事件可以控制同步

现在可以混合同步和异步事件调用。即使Mule服务器异步运行，现在也可以进行同步事件调用。
