=  Mule 0.9.1发行说明
:keywords: release notes


Mule 0.9.1服务器看到了Mule Extras模块的介绍，该模块承载了所有Spring Framework，PicoContainer和其他扩展，webbapp支持，为您自己的扩展提供了改进的测试兼容性工具包，以及众多错误修复和其他改进。


*New Mule-Extras Module*

Mule Extras包含所有不属于mule核心服务器的框架扩展。这些包括：+
Spring扩展 -  Spring容器组件解析器和Spring配置生成器+
Pico扩展 -  Pico容器组件解析器和Pico组件池支持+
XStream变换器 -  Java到xml和xml到Java变换器+
泰瑞克斯交易工厂


*Webapp Support*

Mule现在可以被嵌入到一个web应用程序中，这样你的web应用程序就可以使用Mule来与其他应用程序进行网络通信。


*Tck Improvements*
添加了新的Tck测试用例，以提供对所有Mule可扩展对象的几乎完整覆盖。


*Distribution Restructure*

骡服务器罐子现在分解成+
mule-core-0.9.1.jar  -  Mule核心服务器和UMO api +
mule-tck-0.9.1.jar  -  Mule Test兼容工具包api +
mule-provider-xxx-0.9.1.jar  - 个人Mule提供商，其中xxx是jms，电子邮件，文件等。+
mule-extras-xxx-0.9.1.jar  - 单独的Mule Extras子项目，其中xxx是spring，picocontainer，xstream等。+
mule-0.9.1.jar  - 所有上述罐子的集合


== 错误修复和其他改进

MULE-37 TCK：project.xml包含错误的版本信息（Tck重构）+
MULE-36 TransactionCounter可以降至零以下
MULE-35删除UMOComponent +上的ExceptionStrategy
MULE-34从UMODescriptor +中删除选择器方法
MULE-33将Jms提供商deliveryMode重命名为确认模式+
MULE-32拦截器使用MuleXmlconfigurationBuilder +以相反的顺序初始化
MULE-31复制类XmlToBean和BeanToXml +
MULE-30定义UMODescriptorAware反转接口+
MULE-28在webapp +中嵌入Mule
连接器中的MULE-27提供者覆盖属性仍在使用名称空间+
MULE-26 MuleXmlConfigBuilder不会在提供者+上设置属性
MULE-25使编程的事件调度更直观+
MULE-23为Mule扩展+设置Mule Extras子项目
使用弹簧配置+时，UMOProviderDescriptor上的MULE-22 setProperties不起作用
MULE-21支持指定SMTP和POP3连接器使用的端口+
MULE-18向变压器公开供应商
