=  Mule Maven Plugin 2.0发行说明

MuleSoft很高兴宣布发布Mule Maven Plugin 2.0，这是一款Maven插件，用于部署Mule应用程序，支持持续部署和运行集成测试。此版本提供了一种统一的方式将Mule应用程序部署/取消部署到不同的部署目标。它包括对部署到Mule独立实例，Mule群集实例，CloudHub，Anypoint Runtime Manager *和运行时管理器代理的支持。

（*）Anypoint Runtime Manager是即将用于所有部署和管理功能的名称，也是通过Anypoint Platform部署内部应用程序的一般框架。 Anypoint Runtime Manager的名称将在未来几个月内在产品和文档中进行更名。

== 硬件和软件要求

*  *JDK*：JRE 1.7.0（推荐JRE 1.7.0_79 / 80），JRE 1.8
*  *Maven*：Maven 3.2，Maven 3.3

== 兼容性

* 与Mule 3.5.x，3.6.x，3.7.x兼容

== 功能和功能
=== 新功能或功能

* 支持部署到Mule独立实例，Mule群集实例，CloudHub，Anypoint Runtime Manager和Runtime Manager Agent
* 支持附加到Maven的不同生命周期阶段，因此您可以将插件用于集成测试和持续部署
* 所有部署类型的单一目标
*  CPAL 1.0许可证

=== 已弃用的功能或功能
* 弃用`muleDistribution`参数来配置Mule分配Maven工件（现在使用官方的Maven坐标）

== 已解决的问题

* 修复了CloudHub的部署

== 迁移指南
该插件现在只支持两个目标：`deploy`和`undeploy`。要配置您要部署的位置，您需要指定部署类型，例如`<deploymentType>cloudhub</deploymentType>`。

默认情况下，插件现在部署到本地Mule服务器，从配置的Maven存储库下载分发。

只部署一个应用程序。对于多个应用程序，您需要为每个应用程序配置一个插件执行。

该软件包已移至`org.mule.tools.maven.mule.plugin`。

== 已知问题

* 本地Mule群集在Windows中无法正常工作

== 支援

* 访问 link:http://forums.mulesoft.com[MuleSoft论坛]提出问题，并从MuleSoft广泛的用户社区获得帮助。
* 要访问MuleSoft的专家支持团队 link:mailto:sales@mulesoft.com[订阅Mule ESB Enterprise]并登录MuleSoft的客户门户。
