=  Mule Runtime 4.0 RC发行说明
:keywords: mule, 4.0, runtime, release notes

*September 29, 2017*

Mule 4测试版显着改进了Mule 3，使开发人员能够以更少的步骤完成常见任务，更少的概念获得成功，简化升级并支持新的基于Web的工具，例如Design Center中的Flow Designer。 +
要详细了解Mule 4的新功能，请参阅 link:/mule4-user-guide/v/4.1/mule-runtime-updates[什么是Mule 4指南的新功能]。

除了在Mule Runtime 4.0 Beta上推出的更​​新之外，这个RC版本还包括：

* 设置有效负载和设置变量已被添加以提供更简单的方式来控制数据流。
* 每个连接器现在都有一个targetValue属性，它允许用户控制存储在由target属性指定的变量中的内容。可以使用消息，属性，有效载荷或任何表达式来控制存储的内容。
已添加* 脚本组件
* 已经添加了散点图集合以及改进的输出结构，使您能够在设计时清楚地了解每条路线的数据类型。
*  ObjectStore模块现在允许用户定义他们自己的定制存储，控制TTL，持久性和其他选项。还有支持列表键和值的新操作。
现在支持* 批处理。在Mule 3中，批量作业是最高层次的关注点 - 就像流程一样。但是我们已经简化了这个，所以一个范围可以存在于一个流中 - 使其更容易理解，动态调用并与其他Mule组件交互。另外，我们不再为批处理提供一组特殊的变量（a.k.a. * recordVars）。您现在可以直接使用流变量，降低复杂性并使其更易于学习。
现在支持*  VM连接器
*  DataWeave现在支持平面文件，COBOL，固定宽度，表单，url编码
* 现在支持XA Transactions
* 新的Spring模块在运行时内部使用Spring和用户之间提供了更清晰的分离。用户现在可以完全控制运行哪个Spring版本。要使用Spring bean，请将Spring模块添加到您的应用程序中，然后导入Spring bean文件。
* 有一个新的<configuration-properties>语法，使用户无需添加Spring模块或学习Spring即可将配置属性加载到其应用程序中。
{0}}在Mule 4 Beta中，当应用程序启动时，连接性已在所有连接器上进行测试，并且如果未成功建立，则部署可能会失败。现在，连接已经过测试，但如果失败，默认行为是记录警告消息并继续部署。有一个选项*但是如果用户需要强制应用程序失败。
* 连接器操作现在可以具有与连接器配置中不同的重新连接策略。
现在，WS消费者返回包含正文，标题和附件的单个对象
* 电子邮件连接器现在返回包含正文和附件的单个对象
* 对变量的绑定已从“变量”重命名为“vars”，并且不通过绑定的引用变量不再可能。

== 已修复问题

[%header,cols="20,80"]
|===
| 问题 | 说明
|  MULE-12930  | 没有DataSense支持JMS
|  MULE-12884  |  deleteAfterRetrieve仅删除列出的一半电子邮件
|  MULE-12786  | 文件/ FTP读取和列表不应接收MediaType作为参数
|  MULE-12774  | 当bulkInputParameters为null时，Db连接器批量插入操作会引发NPE
|  MULE-12747  |  @查询文本不允许使用动态值。
|  MULE-12703  | 表达式语言不支持访问系统属性
|  MULE-12355  |  OAuth操作始终以阻止方式执行
|  MULE-12321  | 当具有OAuth客户端凭证的应用程序不能在部署时连接时，它不会像3.x中那样显示HTTP请求者响应
|  MULE-12284  |  NPE在尝试序列化MultiPartPayload时
|  MULE-11897  | 当过滤器抛出异常时，处理程序会丢失对过滤器的引用
|  MULE-11484  |  ParameterGroup的顺序未自动填充，因为未手动配置值
|  MULE-10375  |  MuleArtifactClassLoader配置失败
|  MULE-10878  |  HTTP不支持多个标题/查询参数（同名）
|  MULE-9196  |  JAXBMarshallerTransformer无法转换为字节数组
|  MULE-9142  | 转换服务必须在消耗完有效负载后始终更新消息
|===

== 已知问题

[%header,cols="20,80"]
|===
| 问题 | 说明

|===

来自测试版的== 更新

=== 目标和TargetValue

在mule 4 beta中，所有非void操作都有一个target属性。如果提供，输出消息将放入变量中而不是事件中。请注意，整个消息都放在那里，而不仅仅是有效载荷。

在RC中，我们添加了一个targetValue，它允许自定义要准确放入该流量变量的内容。 targetValue参数默认为＃[有效载荷]，但仅在提供目标属性时才考虑。

例如：

[source,xml,linenums]
----
<file:read path="readme.txt" target="myVar" />
----

readme.txt的内容被放入myVar变量中。 FileAttributes和消息中的其他内容都将丢失


[source,xml,linenums]
----
<file:read path="readme.txt" target="myVar" targetValue="#[message]" />
----

整个消息进入变种。相当于beta行为

[source,xml,linenums]
----
<file:read path="readme.txt" target="size" targetValue="#[attributes.size]" />
----

只是文件大小使它进入变种。

[source,xml,linenums]
----
<file:read path="readme.txt" target="size" targetValue="#[vars.someOtherVar]" />
----

错误：只有负载，消息和属性关键字在targetValue表达式中可用

=== 重新连接和连接测试

在Mule Beta（以及Mule 3.x）中，当应用程序启动时，所有连接器的连接都已经过测试。如果任何连接器上的连接测试失败，则会中止部署。

这种行为在RC上发生变化。连接已经过测试，但如果失败，默认行为是记录警告消息并继续部署。有一个选项可以强制应用程序失败。

[source,xml,linenums]
----
<ftp:config name="ftp">
  <ftp:connection host="localhost" user="me">
                <reconnect count="2">
         </ftp:connection>
</ftp:config>
----

此BETA配置重新尝试连接测试2次，如果不成功，则会导致部署失败。

如果你想让它不失败，你必须这样做：

[source,xml,linenums]
----
<ftp:config name="ftp">
  <ftp:connection host="localhost" user="me">
                <reconnect count="2" blocking="false">
         </ftp:connection>
</ftp:config>
----

在RC中，这改变为：

[source,xml,linenums]
----
<ftp:config name="ftp">
  <ftp:connection host="localhost" user="me">
<reconnection>
<reconnect count="2">
<reconnection>
         </ftp:connection>
</ftp:config>
----

如果您希望部署失败：

[source,xml,linenums]
----
<ftp:config name="ftp">
  <ftp:connection host="localhost" user="me">
<reconnection failsDeployment="true">
<reconnect count="2">
<reconnection>
         </ftp:connection>
</ftp:config>
----

如您所见，重新连接元素不再具有阻止属性。


=== 操作


另一个新功能是允许操作具有不同于连接器配置中的重新连接策略。

[source,xml,linenums]
----
<ftp:read path="bleh.txt" config-ref="ftp">
  <reconnect count="10" />
</ftp:read>
----

该操作没有定义重新连接策略，那么将使用在配置中配置的那个策略。如果配置没有定义任何，则不应用重新连接。

===  Web服务使用者


==== 删除Multipart Payload和Soap Connect Extensions

基于WSC和SC的扩展用于返回包含信封正文和附件（如果有的话）的内容的MultipartPayload，或者如果没有涉及附件，则只是简单的XML，有利于从所有连接器中移除MultipartPayload。消费操作总是返回一个对象结构如下：

输出+
|   -  body +
|   - 标题+
|   - 附件

请注意，有效负载现在携带肥皂标题，之前被捆绑在属性中（这是因为我们希望整个SOAP信封在有效负载中表示）

==== 输出迁移

*Soap Body*

以前访问机构有两种方式：
* 附件＃[payload.body]的操作。
* 无附件＃[有效载荷]的操作。

现在有或没有附件只是＃[payload.body]

*Soap Headers*

Soap Headers曾经居住在属性中，现在它们已经被移动到有效载荷中。

[#attributes.headers] -> #[payload.headers]

*Attachments*

要访问附件没有任何改变。 ＃[payload.attachments.myAtt]获取名为"myAtt"的附件。


=== 电子邮件连接器

==== 删除多部分负载

电子邮件扩展程序用于在响应中包含附件时返回MultipartPayload，从而导致访问主体时出现混淆。 +
新检索的电子邮件内容结构如下所示：

输出+
|   -  body +
|   - 附件

==== 输出迁移

*Body*

以前访问机构有两种方式：

* 附件＃[payload.body]的操作。
* 无附件＃[有效载荷]的操作。

现在有或没有附件只是＃[payload.body]

*Attachments*

可以像以前一样访问附件[＃payload.attachments.myAttachment]

===  HTTP连接器

表达式语言==== 

对变量的绑定已从“变量”更名为“变量”，并且不再通过绑定的引用变量不再可能。这意味着必须更新所有表达式和脚本以将任何“variables.myVar”重命名为“vars.myVar”，并将任何“myVar”重命名为“vars.myVar”。

====  DSL杂项

*Scripting*

脚本模块已转换为可供Mozart / Studio使用的扩展名。由于SDK框架的原因，它还需要对XML结构进行更改，但迁移可能是自动的。

主要变化是：

* 除了允许指定脚本的文件路径外，仅有一个文本内容字段可与属性占位符文件扩展结合使用。
* 可以通过Dataweave声明参数。

之前：

[source,xml,linenums]
----
<script:component>
  <script:script file="test.py">
    <scripting:property key="one" value="1"/>
    <scripting:property key="two" value="2"/>
  </script:script>
</script:component>
----

后：

[source,xml,linenums]
----
<script:execute engine="python">
  <script:code>
    ${file::test.py}
  </script:code>
  <script:parameters>
    #[{one: "1", two: "2"}]
  </script:parameters>
</script:execute>
----

如果内联脚本`<script:text>return "hello"</script:text>`可以用`<script:code>return "hello"</script:code>`替换，如上所示。
