=  Mule ESB 3.7.1发行说明

MuleSoft很高兴地宣布发布Mule Runtime Engine 3.7.1，这是一个Enterprise Only维护版本。此版本包含DataWeave中的重要修复，还包含20多个错误修复。

有关MMC 3.7.1发行说明，请参阅<<MMC 3.7.1 Release Notes>>。

== 兼容性信息

[%header,cols="30a,70a"]
|===
| {软件{1}}版本
| ESB运行时| 3.7.1
| Anypoint™Studio | 2015年6月更新站点1
| {MMC {1}} 3.7.0
|任意点DevKit | 3.7.0
| APIkit | 1.5.1及更高版本
|===

== 硬件和软件建议

骡3.7被验证了以下;但是早期的操作系统版本可以工

*  Java：JRE 1.7.0（推荐的JRE 1.7.0_79 / 80），JRE 1.8
+
注意：Mule 3.7允许JRE，而Anypoint Studio需要JDK
+
* 操作系统：MacOS 10.10.3，HP-UX 11i V3，AIX 7.1，Windows 2012 R2 Server，Windows 8.1，Solaris 11.2，RHEL 7.0，Ubuntu Server 15.04
* 设备：
**  2 GHz，双核CPU或虚拟化环境中的2个虚拟CPU
**  2 GB RAM
**  4 GB的存储空间
** 应用服务器：Tomcat 7，Tomcat 8，Weblogic 12c，Enterprise 6.1，社区8，Websphere 8，Jetty 8，Jetty 9
** 数据库：Oracle 11g，MySQL 5.5 +，DB2 10，PostgreSQL 9，Derby 10，Microsoft SQL Server 2014

== 硬件和软件系统要求

MuleSoft建议在开发人员工作站上至少配备4 GB RAM。随着应用程序变得复杂，请考虑添加更多RAM。如果您有任何关于系统要求的问题，可以联系MuleSoft。

== 捆绑的运行时管理器代理

此版本的Mule ESB捆绑了Runtime Manager Agent Plugin版本1.1.0。

请参阅 link:/release-notes/runtime-manager-agent-release-notes[运行时管理器代理发行说明]。

== 企业版已修复问题

[%header,cols="30a,70a"]
|===
|问题|说明
| MULE-8804 | CXF不会设置正确的mimeType
| MULE-8798 |当没有数据类型设置有效载荷时，必须重置消息MIME类型/编码
| MULE-8779 |主机名验证无法正确使用HTTPS代理
| MULE-8776 |如果收件箱中有7个或更多的阅读电子邮件，电子邮件传输将无法阅读新电子邮件
| MULE-8771 |同步直到成功应重试原始邮件
| MULE-8769 |修复MULE-8635后，记录器内存泄漏
| MULE-8755 |当使用NB proessingStrategy时，HTTP客户端在预期之前关闭连接时发生UnsupportedOperationException异常
| MULE-8754 | BUILD.md中的链接损坏
| MULE-8751 |缺少用于非阻塞处理策略的NamespaceHandler条目
| MULE-8724 |扩展api中的操作状态处理
使用Oracle JDBC Driver的| MULE-8707 |类加载器泄漏
| MULE-8678 | HTTP请求程序不应使用主机属性。
| MULE-8677 | HTTP请求程序应该忽略'Transfer-Encoding'属性，因为它是一个逐跳标头
| MULE-8676 | HTTP侦听器应该忽略'Transfer-Encoding'属性，因为它是一个逐跳报头
| MULE-8626 |连接和保持活动消息属性不应该影响监听器/请求器连接重用行为。
| MULE-8484 |成功的取消部署未在控制台中显示
| MULE-8480 |考虑将@ImplementationOf重命名为@ExtensionOf
| MULE-8478 |使用@Operation注解的类不应强制依赖配置对象
| MULE-8328 | HTTp删除主体不被允许
| MULE-8163 |使用NPE的请求会随机失败（1M中的1），即使在低并发率情况下也是如此。 50
| EE-4563 |限制延迟会导致请求挂起
| EE-4541 |在缓存范围内使用非阻塞HTTP请求时，请求响应流程不响应。
| EE-4539 | Cloudhub 3.6.0 / 3.6.1 AMI不允许设置调试日志记录
| EE-4529 | Hazelcast锁没有被破坏
| EE-4498 | bti：xa-caching-connection-factory不使用凭据来验证JMS会话
|===

== 企业已知问题

[%header,cols="30a,70a"]
|===
|问题|说明
| MULE-8814 |不在多部分响应上发送边界
| MULE-8813 |多部分内容类型标题在复制附件时发送两次
| MULE-8806 |新的HTTP侦听程序不能使用某种附件
| MULE-8787 |无法从丰富的属性中设置数组元素。
具有基本身份验证的| MULE-8786 WSC通过超时抛出异常来包装"error"的HTTP状态代码
| MULE-8780 |由于类加载器的高使用率，导致xpath转换缓慢。
| MULE-8761 |使用非阻塞处理策略时，流程在richher之后不会继续处理。
| MULE-8743 | Mule注册表无法查找子流
| MULE-8720 |争用访问变压器。
| MULE-8719 |执行操作时发现死锁。
在HTTP监听器的线程配置文件中使用时，| MULE-8714 | DISCARD或DISCARD_OLDEST策略无法按预期工作
| MULE-8704 |在Mule Shutdown Hook中抛出异常
| MULE-8703 |记录器类别无法正常工作
| MULE-8700 |为使用扩展API构建的扩展生成的XSD不正确
| MULE-8697 |类org.mule.routing.EventGroup有一个可能导致聚合失败的静态字段（hasNoCommonRootId）
| MULE-8652 | MuleContext的ExpressionLanguage没有正确启动
| MULE-8605 |在新的HTTP模块中使用抢先式基本身份验证时，使用两个请求，其中用户/密码无效
| EE-4545 |由于新的weave-plugin，加载类的速度可能会较低。
| EE-4544 |请求回复将引发意外错误
| EE-4528 |设置不正确处理DataWeave转换器输出的附件组件
|===

==  MMC 3.7.1发行说明

MMC 3.7.1版本主要包括错误修复和性能改进。请参阅下面的固定JIRA列表：

。固定项目
[%header,cols="30a,70a"]
|===
|问题|说明
| MMC-1822 |使maxExecutionTime警告可配置
| MMC-1823 |创建新部署版本后删除旧的部署版本
| MMC-1824 |不要试图从服务器上取下应用程序
| MMC-1825 |提高发现工件的性能
| MMC-1826 |确保在删除部署前取消部署成功
| MMC-1827 |更好地处理孤立链接
|===



== 迁移指南

必须执行从3.7.0迁移的操作。

===  DataMapper插件

从3.7.0开始DataMapper现在是一个可选插件，必须安装在使用它的应用程序的Mule运行时内部。

要迁移DataMapper应用程序，请按照以下步骤手动安装DataMapper插件：

. 从"Customer Portal"下载DataMapper插件
. 将DataMapper插件添加到您的<MULE_HOME>目录中的"plugins"文件夹中

===  Mule中的其他更改3.7.1

[%header,cols="30a,70a"]
|===
|问题|说明
| EE-4333 |骡运输轴已从独立和嵌入式EE发行版中移除。以下库也被删除，因为它们不再是必需的：axis-1.4.jar，commons-discovery-0.4.jar和geronimo-jaxrpc_1.1_spec-1.1.jar
| SEC-240 | Mule ESB 3.7.0要求Anypoint Enterprise Security版本为1.5.0或更高版本
| EE-4441 | wrapper.conf文件现在包含默认垃圾回收和内存设置，这些设置被配置为在具有2 GB +内存的环境中提高性能。如果您需要使用小于2 GB的RAM运行Mule，请编辑wrapper.conf文件。
|===

=== 注释和注册表更改

注解现在是推荐依赖关系的推荐方式。通过Mule上下文注册表手动查找仍然受支持，但不推荐。

初始化现在应用于依赖性顺序，这意味着如果对象'A'依赖于'B'和'C'，Mule保证当'A'被初始化时，'B'和'C'已经被初始化。请注意，为了使其工作，依赖项必须通过javax.inject.Inject注释或通过Spring配置来显式表达。

TransientRegistry已被弃用，不再被运行时使用。 SpringRegistry现在是运行时默认使用的唯一注册表。 AbstractMuleContextTestCase使用新的SimpleRegistry。
已弃用MuleContext的addRegistry（）和removeRegistry（）方法。手动添加的注册表不能参与依赖注入。

org.mule.api.registry.Registry.registerObject（key，Object，metadata）方法已被弃用。元数据不再使用。

RegistryBroker和RegistryBrokerLifecycleManager类已被弃用。
SimpleRegistryBootstrap已被弃用，不再被运行时使用。使用SpringRegistryBootstrap来代替。

PreInjectProcessor，InjectProcessor，ObjectProcessor及其所有实现已被弃用，不再被运行时使用。改用Spring BeanPostProcessor。

=== 春天的变化

在定义实现任何Mule生命周期接口（初始化，可启动，可停止，一次性）的Spring bean时，不再推荐Spring的init方法和destroy方法。

将org.mule.config.bootstrap.SimpleRegistryBootstrap.ArtifactType类移至org.mule.config.bootstrap.ArtifactType

Spring Bean定义解析器不再自动调用initialise（）和dispose（）方法。如果你想在自定义解析器中保持这种行为，你必须明确地自己做。
这样做的一个例子是：

[source,java,linenums]
----
private void setInitAndDisposeMethods(BeanDefintionBuilder builder, Class<?> parsedObjectType) {

   if (Initialisable.class.isAssignableFrom(parsedObjectType)) {
      builder.setInitMethodName(Initialisable.PHASE_NAME);
   }

   if (Disposable.class.isAssignableFrom(parsedObjectType)) {
       builder.setDestroyMethodName(Disposable.PHASE_NAME);
   }
}
----

有关更多技术细节，您可以阅读 link:https://github.com/mulesoft/mule/wiki/[骡-3.7.0-M1％5D-注册表的整合，-lifecycle修复，-and-依赖注入]的完整规范

===  Mule迁移更改

[%header,cols="15a,85a"]
|===
|问题|说明
| MULE-8340 | TLS配置不再映射到默认的JVM系统属性。为了保持这种行为，请定义以下系统属性：mule.tls.disableSystemPropertiesMapping = false
| MULE-8367 |属性http.relative.path已添加到HTTP侦听器的入站属性中。该属性反映了http.request.path属性的值，而不包含相应侦听器的basePath部分。
| MULE-7588 |生命周期已得到修复。注意事项：

只有在注册表实例化了所有对象并成功向其中注入了依赖关系之后，才能调用可初始化的对象。 initialise（）不再被急切地调用。

| JSR-330 |请参阅上面的注释部分。
| MULE-8430 |
在以前版本的Mule中，域主文件夹是相对于当前工作目录而不是相对于<MULE_HOME>文件夹创建的。

现在这个问题已解决，如果您的Mule实例是从<MULE_HOME>以外的文件夹启动的，那么文件夹<WORKING_DIRECTORY> /。mule / <DOMAIN_NAME>必须移至<MULE_HOME> /。mule / <DOMAIN_NAME>
| MULE-8457 | set-payload元素现在使用简单的MessageProcessor实现，而不是使用MessageTransformer。这意味着<set-payload>继续像以前一样工作，除非它用作变压器。 （例如，在一个端点内。）

要将Mule配置文件中的SetPayloadTransformer用作变换器，请将其定义为<custom-transformer>，如下所示：

[source,xml,linenums]
----
<custom-transformer class="org.mule.transformer.simple.SetPayloadTransformer">
    <spring:property name="value" value="someValue"/>
</custom-transformer>
----

| MULE-8469 |如果在转换过程中未更换有效负载，则应用消息转换器不会更改消息的数据类型。

特别是，这种更改会影响消息属性变量的使用，如下所示：

[source,xml,linenums]
----
<message-properties-transformer name="setResponseType" mimeType="text/baz" encoding="UTF-16BE"/>
----

现在必须以这种方式进行配置：

[source,xml,linenums]
----
<message-properties-transformer name="setResponseType">
<add-message-property key="Content-Type" value="text/baz;charset=UTF-16BE"/>
</message-properties-transformer>
----

或者像这样：

[source,xml,linenums]
----
<set-property propertyName="Content-Type" value="text/baz;charset=UTF-16BE"/>
----

| MULE-8498 |应用消息转换器来更改消息的有效负载来更新消息数据类型，但不是使用转换器的输出数据类型，而是使用有效负载和变换器数据类型之间的合并。

如果转换器的输出数据类型不提供MIME类型和/或编码，则使用原始有效负载数据类型MIME类型和/或编码。这可能会导致升级后不同的变换器应用于应用程序。如果发生故障，请使用<set-payload>设置编码和MIME类型，同时保持相同的有效负载。
| MULE-7990 |通过ObjectSerializer接口添加了用于对象序列化的新API。使用以下注意事项：

如果您在自定义组件，脚本或流中手动使用org.mule.util.SerializationUtils类，则应该使用此API。

以同样的方式，在捕获org.apache.commons.lang.SerializationException之前，您现在应该期待org.mule.api.serialization.SerializationException

您现在可以指定哪个是您希望应用程序使用的ObjectSerializer的默认实现。 Mule使用这些实例（尽管您可以在自定义代码中自由使用其他实例）。默认情况下，ObjectSerializer实现使用默认的Java序列化，其行为与之前的版本完全相同。

要将自定义序列化器配置为默认值，您可以使用<configuration>标记：

`<configuration defaultObjectSerializer-ref="myCustomSerializer" />`

有很多方法可以获得ObjectSerializer。推荐的方法是通过依赖注入。以下显示如何获取已配置为默认值的ObjectSerializer：

[source,java,linenums]
----
public class MyClass {

@Inject
@DefaultObjectSerializer
private ObjectSerializer objectSerializer;

}
----

相反，如果你想要一个特定的序列化器（不管它是否是默认的），你也可以这样做：

[source,java,linenums]
----
public class MyClass {

@Inject
@Named("mySerializer")
private ObjectSerializer objectSerializer;

}
----

最后，你总是可以从muleContext中取出它，但首选依赖注入：

[source,java,linenums]
----
// returns the default object serializer
 muleContext.getObjectSerializer();

 // returns a named object serializer
 muleContext.getRegistry().get("mySerializer")
----

| MULE-8510 |当NullPayload消息的有效负载设置消息属性/变量时，将删除给定的属性/变量而不是存储NullPayload。
在消息编码或mimeType更新时，{} {MU}不会在出站范围中添加MULE-8483 | MULE_ENCODING和Content-Type属性。这是为了保持MuleMessage数据类型和属性的一致性。
如果需要这些属性，请使用<set-property>指示期望值。
| MULE-8592 |	默认的最大永久生成时间已增加到256 MB。该属性仅在使用Java 7时使用。使用Java 8时，该属性可能会导致警告。在这种情况下，它可以在wrapper.conf文件中注释掉。
| MULE-8569 |
对于具有类org.mule.config.spring.SpringXmlConfigurationBuilder的自定义实现的人员，已做出一些重要更改：

createApplicationContext（MuleContext，ConfigResource []）方法现在是私有的。如果要覆盖它，请改为使用doCreateApplicationContext（MuleContext，ConfigResource []，OptionalObjectsController）。
如果要截取并更改要加载的资源列表，请覆盖新的addResources（List <ConfigResource>）方法
| MULE-8645 |	由于检测到漏洞，jasper-jdt-6.0.29不再包含在Mule分布中。如果需要此工件，例如在使用Drools时，请手动将其添加到<MULE_HOME> / lib / opt
| MULE-8641 |	 wrapper.conf文件现在包含默认垃圾回收和内存设置，这些设置被配置为在具有2 GB +内存的环境中提高性能。如果你需要用更少的内存运行Mule，编辑这个文件。
| MULE-8628 |
HTTP连接器现在在发送请求和响应时忽略自己的自定义属性（http。* ones），而不是将它们转换为标题。

这意味着：

* 侦听器生成的属性不会影响后续请求
* 该请求生成的属性不会影响侦听器响应
如果需要这些属性，则应使用响应/请求构建器将它们显式添加为标题

| MULE-8660 |	如果端点交换模式是单向的，则AbstractMessageReceiver.routeMessage（..）不会返回空值。它总是返回流的结果，所以如果事务提交失败，则使用流执行的消息结果执行异常策略。自定义消息接收器实现可能需要更新。


有关从以前版本迁移到此版本时需要考虑的完整详细列表，请参阅位于Mule ESB根文件夹中的MIGRATION.txt文件。
|===

== 另请参阅

*  link:https://developer.mulesoft.com/anypoint-platform[骡社区版]
*  link:http://studio.mulesoft.org[Anypoint Studio]
*  link:http://forums.mulesoft.com/[MuleSoft论坛]

