=  Mule企业管理控制台安全更新
:keywords: release notes, mmc, security


2014年10月22日发布

== 发生了什么？

今天早些时候，独立云安全公司Packet Storm引起了Mule企业管理控制台（MMC）中潜在的安全漏洞。

Mule企业管理控制台（MMC）可以对运行时资源（如服务器，集群，流和端点）进行精细管理。借助MMC，MuleSoft客户可以查看和控制SLA，服务级别指标和运行时间性能。 MMC还允许通过身份验证的用户执行管理操作，例如为其他用户提供基于角色的访问以及远程控制资源。

原始披露在 http://seclists.org/fulldisclosure/2014/Oct/98[完整披露邮件列表]中进行了报告。在一个 http://packetstormsecurity.com/files/128799[博客帖子]中，Packet Storm重申了以下几点：

"MuleSoft ESB Runtime 3.5.1 allows any arbitrary authenticated user to create an administrator user due to a lack of permissions check in the handler/securityService.rpc endpoint. The following HTTP request can be made by any authenticated user, even those with a single role of Monitor."



== 这个漏洞的含义是什么？

该漏洞允许经过身份验证的用户通过向MMC控制台发出特制的请求来提升他们的权限，以添加具有管理权限的新用户。它起源于管理添加新用户的代码，它们遗漏了凭证验证检查。

注意：博客文章的标题和对Mule ESB 3.5.1的引用都是误导性的，因为唯一受影响的产品是MMC。该漏洞不会影响Mule ESB 3.5.1。



== 针对此漏洞的缓解因素有哪些？

此漏洞需要成功的用户验证。 MMC通常由管理员在管理环境中使用，而不是由普通用户使用。

MMC通常部署在安全的网段中，只有受信任的用户才能访问。此漏洞需要先前被授予合法访问权限的内部用户（“可信用户”）发起攻击。



== 这方面正在做些什么？

MuleSoft已经确定了产品中存在此漏洞的MMC产品中的源代码，并且正在开发补丁来解决这个问题。

MuleSoft已经确定了产生此漏洞的MMC产品中的源代码，并且已经为此问题创建了一个热修复程序。现在可以从客户门户网站下载此修复程序。



== 如果我受到影响，我可以在此期间做些什么？

客户可以从所有非管理员用户的MMC实施中删除所有非管理员用户，直到有补丁可用


