=  Mule ESB 3.3.0发行说明
:keywords: release notes, esb


跳至*<<Migrating from Mule ESB 3.2 to 3.3>>*

2012年6月26日

MuleSoft很高兴宣布发布*Mule ESB 3.3*，它为我们业界领先的ESB软件引入了强大的新功能和改进。

这些发行说明适用于Mule ESB 3.3的社区版和企业版。在适当的情况下，我们应用了*_Enterprise Edition_*标记来标识仅在企业版中可用的功能或功能。

在这个版本中，我们集中精力扩展了Mule ESB的Studio图形界面的特性和功能，并解决了以前版本中已知的问题。我们已经解决了数百个问题并强化了我们的产品，以确保进一步的稳定性并改善易用性。

我们强烈建议升级到Mule ESB 3.3，以利用Anypoint DataMapper和统一的Mule Expression语言，我们新的迭代处理器和我们的“内存中”数据缓存。

== 文档修订历史记录

2012年6月26日，初始发布

== 当前版本

[%header,cols="34,33,33"]
|===
|   | Mule ESB 3.3.0 +
 企业版 | Mule ESB 3.3.0 +

  社区版

| ESB  |版本3.3.0 +
  Build 19919  |版本3.3.0 +
 构建24524
| Studio  | Build 201206220448  | Build 201204251946
|管理+
 控制台 |构建f56e9aa  |不适用
| SAP Enterprise +
 连接器 |版本1.2  |不适用
| CMIS连接器 |版本1.6  |版本1.6
| Magento Connector  |版本1.5  |版本1.5
| MongoDB连接器 |版本2.1  |版本2.1
| Salesforce Connector  |版本4.3  |版本4.3
| Twilio Connector  |版本1.2  |版本1.2
| Twitter连接器 |版本2.6  |版本2.6
|===

== 新功能和新功能

我们很高兴在Mule ESB 3.3中推出一系列新工具，旨在进一步提高系统集成的速度和效率。

===  Mule ESB和Studio

*  *Cache*：*_Enterprise Edition_*通过“内存中”缓存消息（如服务调用的结果）来提高性能。有关更多详细信息，请参阅 link:/mule-user-guide/v/3.3/cache-scope[高速缓存]文档。

*  *Anypoint DataMapper*：使用图形界面将数据从一种格式转换为另一种格式。这个强大的新功能甚至可以映射消息结构中的特定字段，并支持与以下数据格式之间的转换：XML，JSON，CSV，POJO，POJO集合和EXCEL。有关更多详细信息，请参阅 link:/anypoint-studio/v/5/datamapper-user-guide-and-reference[的DataMapper]文档。 +
 +
  DataMapper仅在Mule ESB Enterprise Edition中可用。 *_Enterprise Edition_*使用Mule ESB Community Edition中的DataMapper来评估Studio中的这个强大的新工具;下载Mule ESB Enterprise以运行应用程序并查看DataMapper的实际运行情况。

*  *Improved error handling*：将新的异常策略整合到Studio中。这些包括：Catch和Rollback异常策略，以及Choice异常策略，它根据抛出的异常类型有条件地处理错误。有关更多详细信息，请参阅 link:/mule-user-guide/v/3.3/error-handling[错误处理]文档。

*  *Iterative processing using Foreach*：允许在保持原始消息上下文的同时对消息有效载荷或属性进行循环式处理。有关更多详细信息，请参阅 link:/mule-user-guide/v/3.3/foreach[的foreach]文档。

*  *Simplified expressions*：统一表达式语言以提高消息验证，过滤，路由或转换的一致性和易用性。有关更多详细信息，请参阅 link:/mule-user-guide/v/3.3/mule-expression-language-mel[Mule表达语言MEL]文档。

*  *SAP Endpoint*：*_Enterprise Edition_* +
 在Studio中提供了一种高效的全新SAP Endpoint，可促进无缝SAP集成（包括SAP与SalesForce的集成）。此外，Mule现在可以以SAP iDocs格式发送和接收消息。请参阅 link:/mule-user-guide/v/3.3/sap-endpoint-reference[SAP端点]文档以了解在Studio中启用SAP Endpoint所需的附加库。

*  *Business events*：*_Enterprise Edition_*在Studio中启用业务事件和关键绩效指标的配置和跟踪。有关更多详细信息，请参阅 link:/mule-management-console/v/3.3/business-events-use-cases[商业活动]文档。

*  *SCM support*：通过支持流行的软件配置管理工具来控制Studio项目的发展：Git和Subversion。安装SCM插件来跟踪和控制Studio项目中的更改。有关更多详细信息，请参阅Git和 link:/anypoint-studio/v/5/using-subversion-with-studio[颠覆]文档。

*  *Maven support*：允许将在Maven框架中构建的项目导入到Studio中，并将Studio构建的项目导出到Maven。安装Maven的插件可以在构建工具之间来回移动项目。有关更多详细信息，请参阅 link:/mule-user-guide/v/3.3/importing-maven-into-studio[导入和导出]文档。

===  MuleSoft管理控制台

_企业版_

*  *High availability support*：支持管理系统的主动/被动（即冷备用）配置。有关更多详细信息，请参阅 link:/mule-management-console/v/3.3/persisting-environment-data[坚持环境数据]。

*  *Persistence alternatives*：正式支持Oracle和PostgreSQL数据库选项，以保持管理配置，部署和业务事件数据。有关更多详细信息，请参阅 link:/mule-management-console/v/3.3/persisting-transaction-data[持久交易数据]和 link:/mule-management-console/v/3.3/persisting-environment-data[坚持环境数据]文档。

*  *Audit log*：提供一个审核日志，用于搜索用户登录活动，例如添加服务器注册/注销。有关更多详细信息，请参阅 link:/mule-management-console/v/3.3/audit-logs[审计日志]文档。

== 值得关注的改进

以下是MuleSoft在3.3 GA中引入并提供的主要改进列表。

===  Mule ESB和Studio

*  **Spring 3.1 upgrade**：包含对Spring Bean定义配置文件和更新命名空间的支持：`spring-beans-3.1`和`spring-beans-current`。

*  **Apache CXF 2.5.1 upgrade**：支持CXF Web服务框架中的最新错误修复和增强功能。

*  **WS-Security access**：_ *Enterprise Edition* _在Studio中的SOAP组件上启用WS-Security，为Web服务提供应用程序层安全性。有关更多详细信息，请参阅 link:/mule-user-guide/v/3.3/enabling-ws-security[启用WS-Security]文档。

*  *Message property improvements*：作用域，副本，并持续存储会话和调用消息属性。

*  *Message and variable transformer addition*：简化属性，变量和附件的管理;替换现在已弃用的消息属性转换器。有关更多详细信息，请参阅 link:/mule-user-guide/v/3.3/transformer-reference[变形金刚]文档。

*  *HTTP improvements*：扩展一组HTTP特定的消息属性，并使其行为更加一致。此外，还添加了特定的组件和变换器以便于创建HTTP响应元素。

*  *Mule application publication*：允许将Mule Studio应用程序发布到Mule管理控制台和/或Mule iON（现在称为CloudHub）的存储库中。

*  *New templates*包含几个新的项目模板，用于构建新的Studio项目。有关更多详细信息，请参阅https://www.anypoint.mulesoft.com/exchange/[Anypoint Exchange]。

*  *Java 7 support*：Mule ESB 3.3已通过认证并经过测试以支持Java 7。

===  Mule管理控制台

_企业版_

*  *Enhanced LDAP support*：利用新的工具和模板，促进基于LDAP的认证和授权的实施。有关更多详细信息，请参阅LDAP认证文档。

*  *REST API server management*：提供REST API来访问控制台的大部分功能，包括服务器管理。有关更多详细信息，请参阅REST API文档。

*  *Performance*：提高控制台对线程，线程池，部署和应用程序的性能。

== 硬件和软件系统要求

对于大多数使用情况，Mule ESB 3.3不会改变Mule ESB 3.2建立的硬件和软件系统要求。

mailto：sales@mulesoft.com [联系MuleSoft]，您可能会对系统要求有任何疑问。

== 此版本中的重要注意事项和已知问题

本列表涵盖了Mule ESB 3.3的一些已知问题。请在报告任何可能发现的问题之前阅读此列表。

===  Mule ESB

[%header%autowidth.spread]
|===
|问题 |说明
| MULE-6273  |在具有Ajax入站端点的流程中不会调用异常策略。 +
 解决方法：将流逻辑封装在VM调用的流中。
| MULE-6258  |请求 - 应答出站端点将响应发送给调用者临时队列，而不是自我临时队列+
 解决方法：无
| MULE-6209  |如果没有抛出异常，则在groovy脚本中引用"exception"应该返回null。
 解决方法：使用exceptionPayload。
| MULE-6165  | Null'既用作消息处理器的响应，也不用结果并表示由过滤器丢弃的消息+
 解决方法：无
| MULE-6094  | RestServiceWrapper +
 解决方法：已应用修补程序来解决问题。
| MULE-6060  |不要总是序列化Mule会话安全上下文+
 解决方法：无
| MULE-6058  |无法覆盖JsonTransformerResolver +
 解决方法：无
| MULE-6046  |在DefaultMuleMessage +中错误地检查支持的转换器类型
 解决方法：无
| EE-2756  |缓存存储聚合器的中间有效负载，而不是最终有效负载内容+
 解决方法：无
| EE-2700  |群集上的HTTP轮询：所有节点都独立轮询+
 解决方法：使用Quartz进行轮询。
| EE-2699 a |
当JMS消息回滚时，对回复的响应仍然被发送+
 解决方法：添加调用属性将避免回复处理。在发生故障的端点之后，您可以使用以下变压器：


| EE-2695  |在短时间内重复创建/解散群集会导致群集关机+
 解决方法：避免重复重新创建群集。
|===

===  Mule Studio

[%header%autowidth.spread]
|===
|问题 |说明
| STUDIO-1217  |配置任何JDBC数据源（MySQL，Oracle等）时，不会添加驱动程序。 +
 解决方法：通过右键单击项目根目录> Build Path> Add External Libraries> Browse来手动添加驱动程序;然后添加相应的。 jar文件。
| STUDIO-1077  | HTTP或HTTPS轮询连接器都不能使用消息流视图中的属性窗格来引用。 +
 解决方法：使用XML配置视图添加以下参数：ref = "HTTP_Polling"。
| STUDIO-866  |在消息流视图中删除请求响应端点或将其替换为单向端点时，不会从XML配置文件中删除响应元素。 +
 解决方法：使用XML编辑器从配置文件手动删除Response元素。
| STUDIO-459  |在单个.mflow文件中创建第二个流时无法添加响应元素。 +
 解决方法：在XML配置中手动添加响应元素。
|   |对于嵌入子流内复合源的请求响应端点，图标不显示正确的交换模式。 +
 解决方法：这只是图形界面中视觉美学的问题;如果通过“属性”窗格设置了正确的交换模式，则流程应该按预期工作，尽管消息流画布上显示了该模式。
| STUDIO-162  |在消息流和XML配置视图之间来回切换时，“描述”字段不会保留。此问题可能会出现在Mule Studio中包含的捆绑示例中。目前，无法使用图形界面填充“说明”字段。 +
 解决方法：应用程序完成后，您确定不再需要使用消息流视图，请复制描述并使用XML编辑器将其插入到配置文件中。
|   |从现有模板创建项目时，“问题”窗格可能会显示以下错误：+
 “无法在项目order_f的构建路径中找到类型'org.ordermgmt.OrdersView'+
 解决方法：从主菜单导航到\ {\ Project> Clean ...}}，然后选择清理所有项目。这将重新编译您的所有项目，以避免出现这些错误。
|   |当您使用IBM JDK安装Windows 64位版本的Mule Studio时，使用Order Discounter模板创建项目，问题窗格可能会显示以下错误：+
  "Attribute key is not defined as a valid property of object Element:Objects is not allowed to be child of element Object" +
 解决方法：忽略错误并运行您的应用程序。它会成功运行。
| STUDIO-1212  | Composite Source中的响应部分未反映在画布中。 +
 解决方法：无
| STUDIO-280  |使用eGit并提交Mule项目时，通常`src/(main and test)`或`(java and resources)`中的一个或多个将为空，因此被git忽略。 +
 解决方法：重新加载工作区/重新启动Studio。 Studio将以这种方式生成丢失的目录（并显示为未跟踪文件）。
| STUDIO-1835  |在SOAP组件中生成WSDL与CXF版本2.1.3一起使用，而不是使用2.5.1。这可能会导致部分WSDL生成的丢失。 +
 解决方法：无
| STUDIO-1920  |使用表达式时，评估程序属性存在向后兼容性问题，因为STUDIO仅支持最新版本的ESB V3.3。如果您尝试使用表达式评估程序属性，它将被标记为错误。 +
 解决方法：使用新的MEL（Mule表达式语言）格式，在表达式之前添加评估者前缀。
| STUDIO-1953  | DataMapper  - 复杂的XML。需要能够处理XML中的嵌套元素和循环元素。 +
 解决方法：无
| STUDIO-1954  | DataMapper  - 需要支持自定义Java函数。 +
 解决方法：无
| STUDIO-1955  | DataMapper  - 需要支持映射到多个输出源的多个输入源。 +
 解决方法：无
| STUDIO-2001  | DataMapper  - 需要能够映射XML.Any元素。 +
 解决方法：无
|===

===  Mule管理控制台

_企业版_

[%header%autowidth.spread]
|===
|问题 |说明
|  -  1237  |业务事件分析器：如果使用HttpRequestToNameString，则仅在事务详细信息上显示自定义事件。 +
 解决方法：将“Doc：name”更改为与流名称不同的内容。 +
  <flow name="HelloWorld" doc:name="HelloWorld2" tracking:enable-default-events="true">。 +
 根据需要启用变形器元素上的事件，并可选择删除doc：name（以避免覆盖流程文档名称）：+
  <transformer ref="HttpRequestToNameString" tracking:enable-default-events="true"/>
|  -  1234  |重新启动一个群集将重新启动已配置的所有群集。 +
 解决方法：无
|  -  1208  |如果所有节点都在运行，则只能解散群集。 +
 解决方法：无
|  -  1205  |群集的流信息在每个群集都使用相同应用程序时相同。 +
 解决方法：要查看正确的流量信息，请通过左侧菜单面板单独选择每个群集。
|  -  1199  |创建群集时，并未将所有部署到服务器组的应用程序都正确删除。 +
 解决方法：在创建群集之前，从群集节点取消部署所有应用程序，然后从服务器组中删除节点。
|  -  1198  | "one-way"端点的发布进程通知未被注册，这导致Business Events被标记为失败。 +
 解决方法：无
|  -  1165  |在Business Events跟踪器中，错误地报告与给定例外策略关联的流的名称。特别是，当消息从流程A跳转到子流程B时，然后返回到流程A，并且组件在流程A中引发异常，即业务事件列表流程A的异常消息在流程B的名称下。 +
 解决方法：无
|===

////
DOCS-35和40：
////

已知的问题：

. 如果一个输入流被用作一个有效载荷并与聚类结合使用，当处理从一个节点到另一个节点时，在Mule 3.3.0中，流将被截断，并且在Mule 3.3.1中抛出一个异常。
. 在Mule 3.3.1和Mule 3.2.1之间发送JMS消息不起作用，因为Mule会话头编码在两者之间不兼容。添加一个 link:https://www.mulesoft.org/docs/site/3.3.0/apidocs/org/mule/session/LegacySessionHandler.html[LegacySessionHandler]来完成这项工作。


===  Mule SAP端点

_企业版_

[cols="1*"]
|===
|非JCo属性被添加到目标配置中。 +
 解决方法：无
|端点类型在架构文件中具有默认值。 +
 解决方法：无
|调用JCoServer.stop（）指示服务器停止，但实际上并未停止服务器。 +
 解决方法：无
|===

本版本中已修复== 

===  Mule ESB

查看已解决的问题

[%header%autowidth.spread]
|===
|问题 |说明
| MULE-6275  | on-redelivery-attempts-exceeded不支持doc：name属性
| MULE-6248  |如果使用浓缩器，会话变量会丢失
| MULE-6247  |自定义转换器未在mule上下文中注册
| MULE-6240  | TransactionalQueueManager加载所有ListableObjectStore中的所有键以填充内部消息队列
| MULE-6236  |无法在RestServiceWrapper上设置内容类型
| MULE-6234  |无法在UntilSuccessful上使用QueuePersistenceObjectStore
| MULE-6203  |传输原型使用不推荐的方法创建测试
| MULE-6199  |基本功能的属性名称是可选的，但应该是必需的
| MULE-6189  |无法初始化应用程序。 MBean异常。
如果CXF MP是客户端，| MULE-6182  | WS-Security元素不应该支持验证器和安全管理器
| MULE-6176  |可用于过滤器的表达式评估程序仅在没有有效的地方使用时才会显示模糊的错误消息
| MULE-6169  |表达式组件不允许变量声明
| MULE-6163  |当端点没有响应时，不应处理端点响应消息处理器
| MULE-6162  |即使端点交换模式是单向的，AbstractMessageReceiver也会返回值
| MULE-6159  |当WSDL定义了故障时，代理服务将与NPE一起失败
| MULE-6156  | AttributeEvaluator不支持表达式中的括号
| MULE-6146  |子流中的过滤器不会按预期进行过滤，而应该（而不是仅仅充当子流“返回”）
| MULE-6137  |缺少转换器的隐式转换
| MULE-6128  | DefaultInboundEndpoint flowConstruct有setter但没有getter
| MULE-6127  |默认的mule应用程序mule上下文是私有的
| MULE-6102  |虚拟机队列不会拾取之前在queuestore中直接保存的消息
| MULE-6082  |应用程序部署描述符未正确关闭
| MULE-6066  | CXF组件忽略了默认的例外策略
| MULE-6051  | XA事务导致ActiveMQ使用者增加
| MULE-6050  |当Mule对象（应用程序，连接器，流，端点等）停止多次时，第二次及以后的停止不起作用
| MULE-6047  |将变压器链应用于mule消息可以产生不同的返回类型
| MULE-6028  |一旦断开连接，activemq-xa连接器不会重新连接到JMS提供程序
| MULE-6019  |单向vm队列上的事务导致CPU变热
| MULE-6017  | spring.handlers和spring.schema在嵌入式发行版中未正确生成
| MULE-6007  |使用持久ObjectStore直到成功路由器时，应用程序无法启动
| MULE-6004  |提交异常策略JMS，FILE和FTP都是传输不消息的消息
| MULE-6003  | CXF吞吐流中的异常，防止异常策略处理异常
| MULE-5998  |从3.2开始，聚合器不再维护创建MuleMessageCollection时收到的顺序事件
| MULE-5997  |一些表达式评估者的定义不一致
如果存在不可序列化的属性，则在使用SessionHandler序列化MuleSession期间，| MULE-5988  | ConcurrentModificationException
| MULE-5981  |密钥库类型配置不正确
| MULE-5965  | Mule在队列存储中发现空消息时抛出EOFException
| MULE-5919  |回复不适用于WMQ传输
| MULE-5907  | ReplyTo属性丢失，因为在事件之间传播不正确
| MULE-5884  | ActiveMQ Web文档应该解释lib目录中的activemq jar包含
| MULE-5827  | 3.2.0中的文件连接器忽略＃[header：originalFilename]并且不写入文件
| MULE-5825  | JDBC DataStore要求JDBCConnector将queryTimeout设置为可用
| MULE-5797  | TransactionalQueueManager仅在入站端点/源之后启动 - 重复事件可能出现在SEDA队列中
| MULE-5617  | Javadoc不再使用Maven 3构建生成
| MULE-5415  | Http传输不适用于第一次调用
| MULE-5379  | http端点端口属性不支持表达式
| EE-2747  | Hazelcast群集在节点重新启动后停止消费消息
| EE-2738  |未能创建2个或更多变形金刚的隐含链
| EE-2737  | Mule不应将默认的用户公开对象存储用于内部目的。
| EE-2727  |独立分发中的默认应用配置引用3.2 xml模式
| EE-2725  | 15分钟到25分钟后，测试失败，多个资源锁定到ActiveMQ资源
| EE-2724  |当不需要时，批量更新强制映射有效负载
| EE-2721  |配置缓存消息处理器的可使用过滤器文档丢失
| EE-2720  | muleContext.getClusterNodeId（）始终为0
| EE-2701  | NPE同时升级节点
| EE-2697  |轮询+更新JDBC数据库引发连接关闭的异常在使用服务时总是失败
| EE-2691  |应用程序的生命周期应用于全局服务器的对象
TransactionalQueueManager中的| EE-2681  | recover（）方法应检查对象存储中的空keySet
| EE-2658  |无法使用JDBC EE模式引用JDBC对象存储
| EE-2657  |无法使用JDBC EE模式引用JDBC数据源
| EE-2631  | spring.handlers和spring.schema在嵌入式发行版中未正确生成
| EE-2609  | Mule在队列存储中发现空消息时抛出EOFException
| EE-2577  | Mule无法在HP-UX上启动
| EE-2221  |一旦断开连接，activemq-xa连接器不会重新连接到JMS提供程序
|===

===  Mule Studio

查看已解决的问题

[%header%autowidth.spread]
|===
|问题 |说明
| STUDIO-821  |请求回复（流量控制）必须通过UI添加入站和出站端点
| STUDIO-991  |在MuleMQ和ActiveMQ小部件对话框的MuleMQ属性选项卡中，检查"XA Support mode"将导致对话框一秒钟空白
| STUDIO-1157  | Spring导入架构没有doc：Name属性
| STUDIO-1546  | VM端点的事务对话框太大
| STUDIO-1549  | WMQ端点：Exchange模式应放置在显示名称后面
| STUDIO-1550  | Quartz：重复的作业属性
| STUDIO-1561  | HTTP出站端点：从HTTP方法属性中删除空白选项
| STUDIO-1518  |无法创建bean  - 尝试在JDBC连接器中创建bean时获取空指针异常
| STUDIO-1406  |安装更新的Studio版本并使用旧的工作区（默认工作区）会导致错误，并且运行时会丢失
| STUDIO-1388  |添加CC并引用它们时获取并发修改异常
| STUDIO-1394  |双向编辑问题：Salesforce和Twitter流式传输端点被解析为无效配置，并从画布移除，然后移除XML
| STUDIO-1386  |重新连接策略：添加“不使用重新连接策略”选项
| STUDIO-1332  |应将WMQ XA连接器视为WMQ内的复选框，以便启用而不是单独的连接器
| STUDIO-1454  |在部署到iON（现在称为CloudHub）时未取得项目时获取JNPE
|===

===  Mule管理控制台

_企业版_

查看已解决的问题

[%header%autowidth.spread]
|===
|问题 |说明
|  -  1226  |即使使用单个mule实例，Server Metrics图表的加载速度也很慢
|  -  1222  |部署新版本的应用程序无法按预期工作
|  -  1195  |使用3.3 / 2.2.8代理无法启动Mule 2.2.8，-agent-mule2-impl-3.3.0-RC2-full.jar
|  -  1111  |尝试保存cron作业时，UI变得无响应。
|  -  1107  |在业务事件上，当代理处于繁重负载（如果负载减少，情况恢复正常）时，查询不会显示新生成的事件。
|  -  1059  |显示部署时间过长（Tab和Portlet）
|  -  1022  |在事件分析器上，处理时间允许使用m作为时间单位，但系统不处理它。
|  -  1016  |在服务器选项卡上，如果在左侧树面板中单击了群集项，则不会打开群集视图。
|===

== 第三方连接器和其他模块

目前，并非所有可能用于Mule ESB以前版本的第三方模块都已升级到Mule ESB 3.3。 mailto：sales@mulesoft.com [联系MuleSoft]如果您有关于特定模块的问题。

== 从Mule ESB 3.2迁移到3.3

以下小节提供了Mule ESB 3.3引入的改进和改进行为的详细信息。有关如何从以前版本的Mule ESB迁移的更多详细信息，请访问迁移指南库。

系统变量+
  <<Message Properties>> +
  <<Transformation Changes>> +
  <<Spring Framework Upgrade>> +
 流程行为+
 消息Enricher +
 错误处理+
  Web服务+
  API更改

=== 环境变量

无论是MULE_HOME还是MULE_BASE都不需要或推荐运行Mule 3.3。如果这些变量中的任何一个存在于安装Mule 3.3的系统上，MuleSoft建议您将其删除。

=== 消息属性

Mule ESB 3.3解决了涉及消息属性的几个问题，并包含两个改进。有关Mule Studio新变压器的更多详细信息，请参阅 ink:/mule-user-guide/v/3.3/transformer-reference[变形金刚]文档。

*  *Fixed*：Mule不会失去包含请求 - 响应出站端点的流中的调用属性。 （也在Mule版本3.1.4和3.2.2中修复。）
*  *Fixed*：Mule在分流器和路由器的流中正确传播调用属性。 （也在Mule版本3.1.4和3.2.2中修复。）
*  *Fixed*：Mule的Collection Aggregator正确地聚合了调用属性。 （也在Mule版本3.1.4和3.2.2中修复。）
*  *Fixed*：`</request-reply>`路由器可以正确保留会话属性。 （也在Mule版本3.1.4和3.2.2中修复。）
*  *Fixed*：Mule可以正确地在分流器和路由器中传播流中的会话属性。 （也在Mule版本3.1.4和3.2.2中修复。）

*  *Improved*：如果Mule遇到带有无法序列化会话属性的消息 - 迫使它将消息写入队列 -  Mule会发出警告，但不会引发异常。此行为与端点收到具有无法序列化的会话属性的消息时警告Mule问题一致。
*  *Improved*：Mule使用一个调用属性映射来分割每个流（不包括异步）的消息。此外，当Mule将消息发送到多个路由进行处理时，所有路由器共享相同的一组调用属性。

=== 转换更改

Mule 3.3引入了三种与消息从一种数据格式转换为另一种格式相关的新行为（例如，从文件到字符串）：

[%header%autowidth.spread]
|===
|行为 |改进的行为 |旧行为
|强制转换 |转换器产生预期类型的​​消息负载;该流必须准备好仅管理一种类型的输出。 |变换器产生几种可能类型的消息有效载荷中的一种;转换的有效载荷类型是未知的，并且流程必须准备好管理几个不同的输出。
|隐式转换 |如果存在一个转换器来将消息有效载荷从B类型更改为C，并且它接收到消息有效载荷类型A，则Mule将隐式地查找可将消息有效载荷从A转换为B，在将消息有效载荷引入到B到C变换器之前。 |如果变换器接收到意外类型的消息有效载荷，则会引发异常。
|扩展转换器查找 |如果转换器存在将消息有效载荷从B类型更改为C，并且它接收到消息有效载荷类型A，则Mule将隐式地查找可将消息有效载荷从A到B，在将消息有效载荷引入到B到C变压器之前。如果Mule_cannot_找不到A到B的转换器，它将扩展它的搜索范围来查找转换器的组合，这将产生一个消息有效载荷类型B.例如，它可能会将消息有效载荷从A转换为F，然后使用另一个转换器在将其引入B-to-C转换器之前，将其从F更改为B.  |如果转换器接收到意外类型的消息负载，并且找不到单个转换器以匹配其转换需求，则会引发异常。
|===

如果你不希望在应用程序中使用这些新的转换器行为 - 例如，如果行为与应用程序的配置方式不兼容，则可以通过将以下代码片段添加到Mule ESL 3.3中来禁用这些行为您的应用程序的配置：

[source, xml]
----
<configuration useExtendedTransformations="false"/>
----

===  Spring框架升级

Mule的配置机制中的一个关键部分Spring最近发布了其新框架。 Spring 3.1.0  - 从3.0.3升级 - 修复了错误并增加了Mule ESB 3.3支持的新功能。要详细了解Spring 3.1中的新功能和修复，请参阅Spring的参考文档。

==== 命名空间

要利用Spring 3.1中的新功能和错误修复，请使用以下两个新的相应命名空间之一：

*  http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.1.xsd
*  http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd

[TIP]
使用`spring-beans-current`指示您的应用程序使用Mule中提供的最新版本的Spring。当Spring发布新版本时，您不需要手动更新应用程序中的命名空间。

====  Bean定义配置文件

Mule的配置文件利用了Spring创建*bean definition profiles*的新功能。您可以使用Spring bean定义配置文件为不同的目标环境注册不同的bean，而不是在所有目标环境中使用一个bean。有关bean定义配置文件的更多信息，请参阅 link:http://spring.io/blog/2011/02/11/spring-framework-3-1-m1-released/[Spring的博客发布]。

作为示例，您可以使用bean定义配置文件为不同配置文件创建和使用唯一的连接器。

. 创建bean配置文件并将其配置为单独的配置文件。
+
[source, xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core" ...>
         <spring:beans profile="one">
         <mule>
             <stdio:connector name="stdioConnector" messageDelayTime="10"  outputMessage="profile 1: " promptMessage="prompt message 1"/>
         </mule>
         </spring:beans>

        <spring:beans profile="two">
        <mule>
            <stdio:connector name="stdioConnector" messageDelayTime="10"
outputMessage="profile 2: " promptMessage="promtp message 2"/>
        </mule>
        </spring:beans>

        <flow name="service">
             <stdio:inbound-endpoint name="in" system="IN" connector-ref="stdioConnector"
exchange-pattern="one-way" />
             <stdio:outbound-endpoint name="out" system="OUT" connector-ref="stdioConnector"
exchange-pattern="one-way" />
       </flow>
</mule>
----

. 当启动一个Mule实例时，使用JVM参数来设置配置文件系统属性来标识Mule应该使用哪个bean配置文件。您的设置适用于部署在Mule实例上的所有应用程序。 +
  `$MULE_HOME/bin -M-Dspring.profiles.active="one"`

=== 流行为

Mule ESB 3.3引入了旨在优化流动行为的更改。虽然它们提供了很多改进和一致性的方法，但这些更改仅影响少量的用例。以下是对这些变化的总结，以及有关如何确保Mule ESB 3.2应用程序在Mule ESB 3.3中继续按预期行事的信息。

==== 滤波

在Mule ESB 3.3中，您可以将过滤器添加到流或子流中，并期望它们在两者中的行为可靠且一致。

在以前的Mule ESB 3.x版本中，根据是否将其添加到流或子流中，过滤器的行为有所不同。

* 流中的过滤器丢弃了失败的消息，但未放弃该文件（请参见下面的示例1）
* 子流程中的筛选器以无提示的方式丢弃了失败的消息，丢弃了该文件，并允许消息继续进入主流程进行处理（请参见下面的示例2）。

在Mule ESB 3.3中，过滤器的行为在所有流，子流和子流中都是一致的：它会丢弃失败的消息，但不会丢弃该文件。 （请参见下面的示例3）。这样可以更轻松地将错误跟踪到源并解决过滤器或流的任何问题。

*Example 1, file NOT discarded*
[source, xml, linenums]
----
<flow name="flowWithFilter>
  <http:inbound-endpoint address="http://localhost"/>
  <expression-filter expression="0 == 1">
  <file:outbound-endpoint path="/tmp" />
</flow>
----

*Example 2, file discarded*
[source, xml, linenums]
----
<flow name="flowWithFilter>
  <http:inbound-endpoint address="http://localhost"/>
  <flow-ref name="filteringSubFlow" />
  <file:outbound-endpoint path="/tmp" />
</flow>

<sub-flow name="filteringSubFlow">
  <expression-filter expression="0 == 1">
</sub-flow>
----

*Example 3, file NOT discarded*
[source, xml, linenums]
----
<flow name="flowWithFilter>
  <http:inbound-endpoint address="http://localhost"/>
  <flow-ref name="filteringSubFlow" />
  <file:outbound-endpoint path="/tmp" />
</flow>

<sub-flow name="filteringSubFlow">
  <expression-filter expression="0 == 1">
</sub-flow>
----

具有单向出站端点的==== 请求响应入站端点。

在Mule ESB 3.3中，您可以将单向出站端点添加到以请求 - 响应入站端点开始的流程的中间或结尾，并期望它在两个位置都可以可靠且一致地运行。

在之前的Mule ESB 3.x版本中，单向出站端点的行为根据您将其放入流中的位置而有所不同。在Mule ESB 3.3中，单向出站端点的行为已经一致，因此它永远不会向调用者返回`null`值。

在Mule ESB 3.3中，例如下面例1中所示的流程，向调用方发送`request message`响应而不是`null`响应。这种“永不为空”的行为在流程中保持不变，例如示例2，其中包含流程中间的单向出站端点。无论您将它放在以请求 - 响应入站端点开始的流中，单向出站端点永远都不会返回Mule ESB 3.3中的`null`响应。

*Example 1*
[source, xml, linenums]
----
<flow name="flowWithFilter>
  <http:inbound-endpoint address="http://localhost" exchange-pattern="request-response/>
  <file:outbound-endpoint path="/tmp" exchange-pattern="one-way"/>
</flow>
----

*Example 2*
[source, xml, linenums]
----
<flow name="flowWithFilter>
  <http:inbound-endpoint address="http://localhost" exchange-pattern="request-response/>
  <file:outbound-endpoint path="/tmp" exchange-pattern="one-way"/>
  <file:outbound-endpoint path="/other" exchange-pattern="one-way"/>
  <logger/>
</flow>
----

如果您不希望在您的应用程序中强制执行此端点行为 - 例如，如果行为与您的应用程序配置方式不兼容，则可以通过将以下代码片段添加到Mule配置中来禁用Mule ESB 3.3中的行为您的应用程序：

[source, xml]
----
<configuration flowEndingWithOneWayEndpointReturnsNull="true" />
----

或者，您可以修改您的应用程序以防止Mule ESB 3.3应用此新的端点行为。您可以通过以下两种方式之一完成修改：

. 将您的流程中入站端点的交换模式从*request-response*更改为**one-way**。这可以确保Mule不会将响应返回给调用者。 （例外：单向入站HTTP端点向状态代码为“OK”的调用方返回空响应。）
. 在您的流程中插入一个转换器以显式定义消息的响应有效负载类型。将变压器插入流量中的两个位置之一：
紧跟在单向出站端点之后的* 
入站端点的响应块（在Mule XML配置中）中的* 

=== 消息Enricher

Mule ESB 3.3纠正了*Message Enricher*的行为，以便它不会将会话变量更改传播到主流。 Mule现在将Message Enricher的处理流程与其所在的主流程隔离开来。换句话说，Mule在Message Enricher范围内对消息会话变量所做的任何更改都不会在消息重新进入主流程时携带。

如果您不希望在您的应用程序中实施这种新的Message Enricher行为 - 例如，如果行为与您的应用程序配置方式不兼容，则可以通过将以下代码片段添加到您的应用程序中来禁用Mule ESB 3.3中的行为应用：

[source, xml]
----
<configuration enricherPropagatesSessionVariableChanges="true" />
----

或者，您可以修改您的应用程序以防止Mule ESB 3.3应用此新的Message Enricher行为。为了确保Message Enricher对会话变量所做的所有更改都传播到主流，请向Message Enricher触及的每个会话变量（即添加或修改）添加一个子`<enrich>`元素。请参考下面这种修改的例子。

[source, xml, linenums]
----
<enricher>
    <flow-ref name="otherFlow"/>
    <enrich source="#[sessionVars['newSessionVar']]" target="#[sessionVars['newSessionVar']]" />
    <enrich source="#[sessionVars['modifiedSessionVar']]" target="#[sessionVars['modifiedSessionVar']]" />
</enricher>
----

=== 错误处理

Mule ESB 3.3通过使用异常策略改进了错误处理。当通过Mule流处理的消息抛出异常时，正常流程执行将停止，并且处理将转移到异常策略中的消息处理器序列。您可以将任意数量的消息处理器（在一种情况下是其他异常策略）合并到异常策略中，以便按照您的意愿处理异常。

此外，Mule ESB 3.3改进了私人流程处理错误的方式。在Mule ESB 3.x中，如果私有流遇到错误并引发异常，它将调用它自己的异常策略，产生`NullPayload`的异常策略结果消息，并允许Mule继续处理父消息流。

在Mule ESB 3.3中，父流程的异常策略 - 默认，catch，回滚，选择或ref  - 处理在私有流程中抛出的所有异常。

如果您不希望在您的应用程序中为私有流执行这种新的错误处理行为 - 例如，如果行为与您的私有流的配置方式不兼容，则可以禁用Mule ESB 3.3中的行为与另一个私有流程一起流动，您在其中配置了一个捕获异常策略。

[source, xml, linenums]
----
<flow name="parentFlow">
   <flow-ref name="privateFlowProxy"/>
   <logger/>
   <default-exception-strategy/>
</flow>

<flow name="privateFlowProxy">
   <flow-ref name="privateFlow"/>
   <catch-exception-strategy/>
</flow>

<flow name="privateFlow">
   <test:component throwException="true"/>
   <default-exception-strategy/>
</flow>
----

请参阅 link:/mule-user-guide/v/3.3/error-handling[错误处理]文档以了解关于Mule ESB 3.3异常策略的更多信息。

===  Web服务

以下小节概述了Mule ESB 3.3适用于涉及Web服务的应用程序的更改和改进。

====  CXF版本升级

Mule ESB利用Apache的CXF框架来构建和配置Web服务。最近，Apache已将CXF升级到版本*2.5.1*，该版本修复了大量错误并提供了更高的稳定性。 Apache还将他们的 http://ws.apache.org/wss4j/[WSS4J]产品（Web服务的安全标准实施）从1.5.8升级到**1.6.1**。 Mule ESB 3.3支持CXF和WSS4J的最新版本。

请参阅 link:http://cxf.apache.org/docs/24-migration-guide.html[CXF 2.4]， link:http://cxf.apache.org/docs/25-migration-guide.html[CXF 2.5]和WSS4J 1.6迁移指南以了解Apache对其Web服务框架所作的改进。

CXF中的==== 错误处理

Mule ESB 3.3对其处理涉及CXF Web服务的流程中发生的错误的方式进行了以下改进。

. 当消息在CXF Web服务流中引发异常时，Mule会调用您为该流定义的异常策略。根据您定义的异常策略的类型以及CXF Web服务是发布，使用还是代理信息，Mule可以：
* 向调用者返回一个SOAP Fault消息
* 在流中传播错误的原因
. 当Mule向调用者返回SOAP错误时，它将HTTP状态代码设置为500“内部服务器错误”。
. 每当发生异常时，CXF都会传播正确的异常。
.  Mule ESB3.3已从CXF入站消息处理器中删除了`onException`属性。 （之前，Mule ESB 3.x使用`onException`作为解决方法，以便能够将SOAP错误返回给调用者或调用和异常策略。）

有关Web服务和错误处理的更多详细信息，请参阅 link:/mule-user-guide/v/3.3/cxf-error-handling[CXF错误处理]。

==== 的WS-Security

_企业版_

在Mule ESB 3.3中，您可以通过在Web服务上启用WS-Security（CXF配置）来实现应用程序层安全性。 WS-security定义了一个新的SOAP头，它能够携带各种安全令牌，系统用它来识别Web服务调用者的身份和特权。有关如何在Web服务上启用它的详细说明，请参阅 link:/mule-user-guide/v/3.3/enabling-ws-security[启用WS-Security]。

在Studio中工作，您可以将键值对添加到SOAP组件，以便创建与WSHandlerConstants和WSConstants中的CXF WSS4J安全配置文本字符串对应的键值对的映射。在XML中，您在ws-security元素的ws-config子元素内添加一个键值对。

此外，您可以添加自定义令牌验证器来验证您的Web服务传输或接收的消息凭证。您可以通过引用应用，替换或扩展与特定安全令牌关联的默认行为的现有bean来自定义令牌验证程序。

[source, xml, linenums]
----
<cxf:ws-security>
    <cxf:ws-config>
        <cxf:property key="action" value="UsernameToken"/>
        ...
    </cxf:ws-config>
    <cxf:ws-custom-validator>
        <cxf:username-token-validator ref="validatorRef"/>
    </cxf:ws-custom-validator>
</cxf:ws-security>
----

====  Mule安全管理员

由于最新版本的Apache WSS4J已经改变了它处理UserNameTokens的方式，并且因为Mule支持最新版本的WSS4J，所以Mule ESB 3.3引入了一种配置 link:/mule-user-guide/v/3.3/security-manager-configuration-reference[Mule安全经理]以与CXF集成的新方法。

要在Mule ESB 3.2中配置CXF中的Mule Security Manager，可以将安全管理器回调添加为WSS4J映射配置中的密码回调，并且CXF将WSS4J配置注入到WSS4J拦截器中。但是，在最新版本的WSS4J中，回调处理程序不再执行验证活动;相反，他们只是在回调中设置密码。换句话说，认证和验证任务已从WSS4J处理器中删除并转移到 link:http://coheigea.blogspot.com/2011/04/wss4j-16-introducing-validators.html[令牌验证器]。这个WSS4J的变化促成了Mule ESB 3.3配置Mule Security Manager与CXF协同工作的修改方式。

*Mule ESB 3.2 Mule Security Manager Integration*
[source, xml, linenums]
----
<spring:bean name="wss4jInConfiguration"
    class="org.springframework.beans.factory.config.MapFactoryBean">
    <spring:property name="sourceMap">
        <spring:map>
            <spring:entry key="action" value="UsernameToken" />
            <spring:entry key="passwordCallbackRef">
                <cxf:security-manager-callback id="serverCallback"/>
          </spring:entry>
        </spring:map>
    </spring:property>
</spring:bean>
----

因此，Mule ESB 3.3配置Mule Security Manager的新方法可能与您现有的Mule ESB 3.x应用程序不兼容。为确保您的Mule ESB 3.x应用程序在Mule ESB 3.3中正常运行，请在Web服务流程的`<cxf:ws-security>`元素内添加一个`<cxf:mule-security-manager>`子元素。

*Mule ESB 3.3 Mule Security Manager Integration*

[source, xml, linenums]
----
<cxf:jaxws-service>
    <cxf:ws-security>
        <cxf:mule-security-manager/>
        <cxf:ws-config>
            <cxf:property key="action" value="UsernameToken" />
        </cxf:ws-config>
    </cxf:ws-security>
</cxf:jaxws-service>
----

====  JiBX数据绑定

在CXF框架的上下文中， link:http://cxf.apache.org/docs/data-binding-architecture.html[数据绑定]是将数据从XML文档映射到Java对象的操作。除了aegis，jaxb和自定义数据绑定之外，Mule ESB 3.3还引入了将*JiBX databinding*应用于Web服务的功能。

===  API更改

 查看由Mule ESB 3.3 API引入的更改

[%header,cols="34,33,33"]
|======
|受影响 |迁移到3.3后，更改 |
| org.mule.module.cxf.support.MuleSecurityManagerCallback处理程序 | *Removed*  |使用org.mule.module.cxf.support.MuleSecurityManagerValidator
| org.mule.api.MuleSession.setProperty（String，Object） | *Deprecated*  |使用org.mule.api.MuleSession.setProperty（String，Serializable）
| org.mule.api.MuleSession.getProperty（Object） | *Deprecated*  |使用org.mule.api.MuleSession.getProperty（String）
| org.mule.api.MuleSession.removeProperty（Object） | *Deprecated*  |使用org.mule.api.MuleSession.removeProperty（String）
| org.mule.expression.MuleExpressionEvaluator  | *Deprecated*  |使用默认表达式计算器。请参阅 link:/mule-user-guide/v/3.3/mule-expression-language-mel[表达式配置参考]了解更多信息。
| org.mule.module.cxf.CxfComponentExceptionStrategy  | *Deprecated*  | Mule ESB 3.3引入了改进的错误处理，因此，CXF自定义异常策略不再增加价值。
| org.mule.module.cxf.component.WebServiceWrapper组件 | *Deprecated*  | Mule ESB 3.3允许您将Web服务调用的结果发送到另一个端点，使用流量。
|======

==== 对Mule ESB 3.3中的org.mule.session.DefaultMuleSession / org.mule.DefaultMuleEvent构造函数的更改


[%header%autowidth.spread]
|===
| {影响{1}}更改 |迁移
| *DefaultMuleSession*（_ MuleContext _） | *Deprecated*  |使用DefaultMuleSession（）
| *DefaultMuleSession*（_ FlowConstruct，MuleContext _） | *Deprecated*  |使用DefaultMuleSession（）
| *DefaultMuleSession*（_ MuleSession，MuleContext _） | *Deprecated*  |使用DefaultMuleSession（_MuleSession session_）
| *DefaultMuleSession*（_ MuleSession，FlowConstruct _） | *Deprecated*  |使用DefaultMuleSession（_MuleSession session_）
| *DefaultMuleSession*（_ MuleMessage，SessionHandler，FlowConstruct，MuleContext _） | *Removed*  |。
| *DefaultMuleSession*（_ MuleMessage，SessionHandler，MuleContext _） | *Removed*  |。
|===

在Mule ESB 3.3中，====  DefaultMuleEvent构造函数被FlowConstruct参数替代

*  *DefaultMuleEvent*（_ MuleMessage消息，MessageExchangePattern exchangePattern，MuleSession session_）
*  *DefaultMuleEvent*（_ MuleMessage消息，MessageExchangePattern exchangePattern，MuleSession会话，ResponseOutputStream outputStream_）
*  *DefaultMuleEvent*（_ MuleMessage消息，MessageExchangePattern exchangePattern，MuleSession会话，int超时，Credentials凭证，ResponseOutputStream outputStream_）
*  *DefaultMuleEvent*（_ MuleMessage消息，URI messageSourceURI，MessageExchangePattern exchangePattern，MuleSession session_）
*  *DefaultMuleEvent*（_ MuleMessage消息，URI messageSourceURI，MessageExchangePattern exchangePattern，MuleSession会话，ResponseOutputStream outputStream_）
*  *DefaultMuleEvent*（_ MuleMessage消息，URI messageSourceURI，MessageExchangePattern exchangePattern，MuleSession会话，int超时，Credentials凭证，ResponseOutputStream outputStream_）
*  *DefaultMuleEvent*（_ MuleMessage消息，InboundEndpoint端点，MuleSession session_）
*  *DefaultMuleEvent*（_ MuleMessage消息，InboundEndpoint端点，MuleSession会话，ReplyToHandler replyToHandler，ResponseOutputStream outputStream_）
*  *DefaultMuleEvent*（_ MuleMessage消息，URI messageSourceURI，String messageSourceName，MessageExchangePattern exchangePattern，MuleSession会话，int超时，凭证凭证，ResponseOutputStream outputStream，字符串编码，布尔事务处理，布尔同步，Object replyToDestination，ReplyToHandler replyToHandler_）

== 支持资源

请参考以下资源以获得使用Mule ESB 3.3的帮助。

=== 文档

有关如何使用Mule ESB 3.3中的新功能和改进功能的说明，请参阅 link:https://docs.mulesoft.com/mule-user-guide/v/3.3/[MuleSoft文件]中的MuleSoft联机文档。

=== 获得帮助

访问MuleSoft的 link:http://forums.mulesoft.com/[论坛]提出问题并从Mule广泛的用户社区获得帮助。

_企业版_要访问MuleSoft的专家支持团队，请https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[subscribe]到Mule ESB Enterprise Edition并登录到MuleSoft的{{0 }}。
