=  Mule Studio发行说明 -  2012年3月21日
:keywords: release notes, anypoint studio


== 介绍

Mule Studio是Mule的图形设计工具。这是构建集成应用程序的最简单和最容易访问的方式。

Mule Studio捆绑了Mule 3.2.2，企业版。该版本结合了新功能，如支持与JDBC，WMQ和FTP相关的企业级功能。

== 当前版本

[%header,cols="34,33,33"]
|===
|   |企业版 |社区版
| {ESB {1}} | 
| Mule管理控制台 |   | 
| {工作室{1}} X  | 
|===

== 新功能和新功能

* 此版本具有新的JDBC，FTP和WMQ端点（以及连接器），以及通常与JDBC和WMQ一起使用的新变换器。
* 弹出窗口会告诉您，您的项目是否包含一个或多个有错误的流程。无论如何，您仍然可以在本地和Mule iON（现在称为CloudHub）上部署项目，错误和所有项目。
* 当您尝试运行Mule实例时，Mule现在会通知您是否有另一个Mule实例已在运行，以便您在不知道第一个运行实例的情况下不启动新实例。
*  Salesforce连接器属性窗格已得到改进。
* 所有端点窗格的“参考”选项卡属性都使用新的变量参考部分进行了增强，以便您可以添加和引用全局变换器。
*  Echo模板已更新。
* 整个Studio界面中都引入了新的和改进的图标。
* 该发行版与Mule EE 3.2.2运行时服务器模块捆绑在一起，不打算部署到生产环境。它连续运行12小时，然后关闭。 Studio界面（包括两个编辑器）继续工作，您可以随时重新启动服务器并再运行12小时。
* 此版本修复了50多个错误。

此版本中的== 已知问题

问题：无法在Studio Enterprise中配置数据源（STUDIO-1375）。 +
解决方法：此问题有两种解决方法：如果要从全局元素窗格配置数据源，可以使用Studio CE。如果您不想更改为Studio CE，只需使用Studio Enterprise创建一个bean即可。 +
问题：您可以在Jetty全局端点中使用重新连接策略，但不能在Jetty连接器中使用重新连接策略，因为在运行流程（MULE-6112）时会这样做会引发错误。 +
解决方法：如果您需要在Jetty中使用重新连接策略，请创建Jetty全局终端并在此处配置重新连接策略。 +
问题：对于重新连接策略，Mule Studio（STUDIO-1385）中尚未提供重新连接通知程序和重新连接自定义通知程序。 +
解决方法：通过手动编辑XML配置文件添加重新连接通知程序或重新连接自定义通知程序。 +
问题：位于上下文相关帮助系统中的链接对于在Mac OS X上运行的Studio不一致（STUDIO-1288）。 +
解决方法：复制您感兴趣的页面的链接并将其粘贴到新的浏览器中。 +
问题：配置任何JDBC数据源（例如，MySQL，Oracle等）时，不会添加驱动程序。 （STUDIO-1217）+
解决方法：通过右键单击项目根目录>构建路径>添加外部库>浏览，然后添加相应的.jar文件来手动添加驱动程序。 +
问题：对于某些JDBC数据源，Mule要求不在URL中配置'user'和'password';相反，它们必须通过单独的属性来指定。尽管这些属性不是必需的，并且从技术上讲，至少应该可以通过URL配置凭据，但无论如何都必须通过属性来设置它们。 +
解决方法：如果您的密码为空，则必须打开Studio的XML配置视图并编辑密码属性，以使password = ""。 +
问题：HTTP / HTTPS轮询连接器不能使用消息流视图中的属性窗格引用。 （STUDIO-1077）+
解决方法：您需要使用Studio的XML配置视图手动插入参考，方法是添加以下内容：

[source, xml]
----
ref="HTTP_Polling"
----

问题：在消息流视图中删除请求响应端点或将其替换为单向端点时，不会从XML配置文件中删除响应元素。 （STUDIO-866）+
解决方法：使用Studio的XML配置编辑器手动从配置文件中删除Response元素。 +
问题：在单个mflow文件中创建第二个流时无法添加响应元素。 （STUDIO-459）+
解决方法：在XML配置文件中手动添加响应元素。 +
问题：对于嵌入子流内复合源中的请求响应端点，图标不显示正确的交换模式。 +
解决方法：这只是图形界面中视觉美学的问题;如果通过“属性”窗格设置了正确的交换模式，则该流程应按预期工作，消息流画布上的外观不受影响。 +
问题：在消息流和XML配置视图之间来回切换时，“描述”字段不会保留。这个问题可能会出现在与Mule Studio捆绑在一起的例子中。 （STUDIO-162）。目前，无法使用图形界面填充“说明”字段。 +
解决方法：一旦您的应用程序完成并且您确定不再需要使用消息流视图，请复制描述并使用XML编辑器将其插入到配置文件中。 +
问题：从现有模板创建项目时，“问题”窗格可能会显示以下错误：+
"Unable to find type 'org.ordermgmt.OrdersView' on build path of project order_f." +
解决方法：从主菜单导航到\ {\ Project> Clean ...}}，然后选择*clean all projects*。这将重新编译您的所有项目，以避免出现这些错误。 +
问题：当您使用IBM JDK安装Windows 64位版本的Mule Studio时，使用Order Discounter模板创建项目时，问题窗格可能会显示以下错误：+
"Attribute key is not defined as a valid property of object Element:Objects is not allowed to be child of element Object"。 +
解决方法：忽略错误并运行您的应用程序。它会成功运行。
