=  NetSuite OpenAir连接器发行说明
:keywords: openair, netsuite, release notes

用于NetSuite OpenAir的Anypoint连接器是一种封闭源企业连接器，可在OpenAir和第三方软件之间提供连接。

link:/connectors/netsuite-openair-connector[NetSuite OpenAir连接器用户指南]

== 版本2.0.0  - 未发布

=== 兼容性

[width="100%", cols=",", options="header"]
|===
| {软件{1}}版本
| Mule Runtime  |  4.1.0
|===

=== 特点

* 增加了对*Mule 4*的支持，并移除了对*Mule 3*的支持。

本版本中已修复=== 

没有。

=== 已知问题

*  **Metadata in Flow Designer**  - 尽管元数据在Anypoint Studio下运行，但Flow Designer显示的是不完整的结构。连接器仍然可以使用，但元数据不能用作指导。

== 版本1.0.2  -  2017年3月3日

本版本中已修复=== 

*  **Metadata is correctly generated in Studio**  - 之前，在选择任何操作时，**oaObject**下拉菜单显示重复条目，并且在某些情况下，输入/输出元数据不完整或被截断。现在，连接器显示oaObjects列表和关联的元数据。
*  **Connector compatibility with Windows**  - 在某些情况下，用户在尝试在Windows下的Mule环境中使用连接器时会收到`Illegal character in path`错误消息。这是固定的。
*  **Disable chunking on HTTP requests**  - 当连接器发出的请求包含相对较大的有效负载时，OpenAir将无法解析它。这已不再是这种情况。
*  **Token refresh**  - 当身份验证令牌失效时，连接器不会始终正确刷新它。
*  **Namespace URI in requests**  - 传出的SOAP消息包含`bodyPrefix`属性中的非法`||`个字符。尽管这没有引起任何问题，但SOAP Envelopes在技术上是无效的。

== 版本1.0.1  -  2016年12月14日

=== 兼容性

[cols=",",options="header",]
|===
| {软件{1}}版本
| Mule运行时 | 3.7.0
|===

[NOTE]
OpenAir连接器需要*Enterprise*许可证。 MuleSoft在 link:/mule-user-guide/v/3.7/anypoint-connectors#connector-categories[_选择_]支持策略下维护此连接器。

=== 特点

没有。

本版本中已修复=== 

XML外部实体（XML External Entities，XXE）漏洞 - 默认情况下，XML解析器配置较弱，从而在应用程序解析XML输入时启用XML外部实体攻击（例如泄露机密数据，拒绝服务和服务器端请求伪造）。为了防止XXE，DTD（外部实体）已在连接器使用的所有XML解析器中完全禁用。

== 版本1.0.0  -  2016年4月14日

=== 兼容性

[cols=",",options="header",]
|===
| {软件{1}}版本
| Mule运行时 | 3.7.0
|===

[NOTE]
OpenAir连接器需要*Enterprise*许可证。 MuleSoft在 link:/mule-user-guide/v/3.7/anypoint-connectors#connector-categories[_选择_]支持策略下维护此连接器。

=== 特点

*  WSDL是从用户的OpenAir实例动态检索的
* 支持OpenAir自定义字段
* 基于XML的请求
会话过期时* 自动重新连接
* 支持的操作：
** 添加
** 的createAccount
**  CREATEUSER
** 删除
**  Getcrystalinfo
**  Makeurl
** 修改
** 阅读
**  Runreport
**  Servertime
**  Servertimewithtimezone
** 提交
** 的Upsert
** 版本
**  WHOAMI

本版本中已修复=== 

* 选定的OpenAir对象被添加到处理器的元数据中。

== 另请参阅

*  NetSuite link:http://www.openair.com/download/NetSuiteOpenAirSOAPAPIGuide.pdf[OpenAir SOAP API指南]
*  https://forums.mulesoft.com [MuleSoft论坛]。
*  https://support.mulesoft.com [联系MuleSoft支持]。
