=  NetSuite连接器发行说明
:keywords: release notes, netsuite, connector

*March 2017*

*Note:* NetSuite版本与SuiteTalk API版本不同。您的帐户可能正在运行与您所使用的API版本不同的NetSuite版本。

link:/connectors/netsuite-about[连接器用户指南]

== 版本7.6.1  -  2018年3月23日

=== 版本7.6.1  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5
| API | SuiteTalk 2017.1
|===

[NOTE]
NetSuite版本与SuiteTalk API版本不同。您的帐户可能在与您使用的API版本不同的NetSuite版本上运行。

=== 版本7.6.1  - 功能

* 基于请求级别令牌的身份验证的多租户支持 - 用户无法动态定义帐户ID以利用DevKit提供的多租户支持。这是固定的。

=== 版本7.6.1  - 在此版本中已修复

* 改善启动性能和内存消耗 - 进行了内部更改，以便首次调用连接器的延迟时间更短，并且内存消耗得到改善。
* 获取Deleted Records处理器不按类型过滤 -  Get Deleted Records处理器忽略"type"参数。这是固定的，现在它的输出将应用类型过滤器。

=== 版本7.6.1  - 已知问题

没有。

////
用于NetSuite的Anypoint连接器可同步数据并自动执行NetSuite和第三方应用程序之间的业务流程，无论是在本地还是在云中。

== 版本8.0.0  -  2017年7月29日

此版本提供对Anypoint平台>设计中心和Mule 4的访问

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 4.0
| Anypoint Studio  |仅适用于Studio 7.0.0及更高版本
| API | SuiteTalk 2017.1预览
|===

=== 版本8.0.0已知问题

* 虽然为一组操作返回对象数组，但元数据将响应显示为对象。
////

== 版本7.6.0  -  2017年8月4日

此版本为SuiteTalk API版本2017.1 GA提供支持，并且不提供新的Web服务。

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5
| API | SuiteTalk 2017.1 GA
|===

=== 特点

有关更改的详细列表，请登录到NetSuite，打开帮助中心并导航到新版本>发行说明> NetSuite 2017.1发行说明> SuiteTalk（Web服务）集成。

本版本中已修复=== 

没有。

=== 已知问题

没有。

== 版本7.5.2  -  2017年7月25日

此版本提供了内部错误修复。

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5
| API | SuiteTalk 2017.1预览
|===

=== 特点

没有。

本版本中已修复=== 

* 带有`recordType=ITEM_FULFILLMENT`的添加记录值。在V7.5.1中，当尝试使用recordType = ITEM_FULFILLMENT的添加记录和项目执行记录包含_package_时，连接器抛出`java.lang.NoSuchFieldException: package`错误。目前，它按预期工作。

* 连接器不解析CustomFieldList。在以前的版本中，连接器不解析CustomFieldList，因此当名称与customFieldList不同时，它不会被包含在对Netsuite的SOAP请求中。现在它按预期工作。

=== 已知问题

没有。

== 版本7.5.1  -  2017年7月6日

此版本提供了内部错误修复。

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5
| API | SuiteTalk 2017.1预览
|===

=== 特点

没有。

本版本中已修复=== 

* 动态端点解析在沙箱帐户中存在问题。这在当前版本中已修复。但是，用户在使用非生产帐户时仍需手动定义Web服务和RESTlet的端点。

=== 已知问题

没有。

== 版本7.4.3  -  2017年7月6日

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5
| API | SuiteTalk 2016.2
|===

=== 特点

没有。

本版本中已修复=== 

* 动态端点解析在沙箱帐户中存在问题。这在当前版本中已修复。但是，用户在使用非生产帐户时仍需手动定义Web服务和RESTlet的端点。

=== 已知问题

没有。

== 版本7.5.0  -  2017年6月1日

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5
| API | SuiteTalk 2017.1预览
|===

=== 特点

* 对SuiteTalk API版本2017.1预览的支持 -  SuiteTalk API 2017.1中未添加新的Web服务，但"getConsolidatedExchangeRate"已被删除。有关更改的详细列表，请登录到NetSuite，打开帮助中心并导航到新版本>发行说明> NetSuite 2017.1发行说明> SuiteTalk（Web服务）集成。

=== 已知问题

没有。

== 版本7.4.2  -  2017年6月1日

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5
| API | SuiteTalk 2016.2
|===

=== 特点

* 动态发现URL  -  NetSuite域可以更改，因为帐户托管在多个数据中心中。出于这个原因，NetSuite建议动态解析Web服务和RESTlet的域URL。在以前版本的连接器中，用户必须明确定义端点的URL或使用默认值。当前版本实现了以动态方式获取这些URL的逻辑。不过，用户可以选择在连接器配置中声明它们。
* 参数"Internal ID"错误地定义了默认值 - 操作"Get Record"接受参数"Internal ID"和"External ID"，这两个参数都是可选的（尽管其中至少有一个必须提供）。但是，以前版本的连接器将`\#[payload]`定义为"Internal ID"的默认值，强制用户删除有效内容或使用`#[null]`。在当前版本中，默认值不再存在。

=== 已知问题

没有。

== 版本7.4.1  -  2017年4月28日

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5
| API | SuiteTalk 2016.2
|===

=== 特点

没有。

本版本中已修复=== 

* 更新缺少属性的记录请求 - 当`Update Record`操作的有效负载设置了`replaceAll`标志时，它未正确映射到Web服务请求。现在，与其他布尔值一起，将被正确映射。

=== 已知问题

没有。


== 版本7.4.0  -  2016年12月22日

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5
| API | SuiteTalk 2016.2
|===

=== 特点

* 支持SuiteTalk API版本2016.2  - 无新的Web服务。有关更改的详细列表，请登录NetSuite，打开*Help Center*并导航至*New Release*  - > *Release Notes*  - > *NetSuite 2016.2 Release Notes*  - > *SuiteTalk (Web Services) Integration*。

本版本中已修复=== 

* 自定义字段未在搜索结果中正确映射。
当响应是JSON数组时，*  RESTlet调用失败。

=== 已知问题

没有。

=== 从旧版本迁移

*  GET，PUT和POST RESTlet调用现在总是返回一个列表。如果RESTlet返回单个JSON对象，则它将被包装在单个元素列表中。如果响应是JSON数组，则连接器将返回一个包含其所有元素的列表。
* 从2016.2端点开始，externalId的值将作为外部属性返回。在2016.1和更早版本的端点中，externalId的值将作为internalId属性返回。您可以从 link:https://system.na1.netsuite.com/app/help/helpcenter.nl?fid=section_N3950559.html[NetSuite 2016.2发行说明]找到更多信息（需要NetSuite登录）



== 版本7.3.0  -  2016年9月7日

=== 版本7.3.0  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本

| Mule运行时间
| 3.5及更高版本

| API
| SuiteTalk 2016.1
|===

=== 版本7.3.0  - 功能

* 增加了调用RESTlets的功能。 -  NetSuite RESTlet允许您使用JavaScript和SuiteScript为您的NetSuite帐户开发定制的RESTful Web服务。 RESTlets是标准SuiteTalk基于SOAP的API的替代品。

=== 版本7.3.0  - 已在此版本中修复

没有。

=== 版本7.3.0  - 已知问题

没有。

== 版本7.2.0  -  2016年8月12日

=== 版本7.2.0  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本

| Mule运行时间
| 3.5及更高版本

| API
| SuiteTalk 2016.1
|===

=== 版本7.2.0  - 功能

* 升级连接器以使用SuiteTalk API版本2016.1。

=== 版本7.2.0  - 已在此版本中修复

* 在NetSuite帐户中使用大量自定义获取元数据时出错。

=== 版本7.2.0  - 已知问题

没有。

== 版本7.1.0  -  2016年3月8日

=== 版本7.1.0  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本

| Mule运行时间
| 3.5及更高版本

| API
| SuiteTalk 2015.2
|===

=== 版本7.1.0  - 功能

* 升级连接器以使用SuiteTalk API版本2015.2，包括2016年1月20日的每周更新。
* 支持基于请求级别令牌的身份验证。

本版本中已修复=== 

* 自定义事务类型在检索元数据时不再导致问题。
搜索ITEM时，`returnSearchColumns`中的* 错误。

=== 版本7.1.0  - 已知问题

没有。

== 版本7.0.0  -  2015年12月11日

=== 版本7.0.0  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本

| Mule运行时间
| 3.5及更高版本

| API
| SuiteTalk 2015.2
|===

=== 版本7.0.0  - 功能

* 升级连接器以使用SuiteTalk API 2015.2版。
* 为"Search"操作添加了分页支持（删除了其他搜索处理器，请参阅下面的迁移）。

=== 版本7.0.0  - 已在此版本中修复

* 支持"Get Record"和"Get Custom Record"操作的DataSense支持。
* 改进了自定义字段的元数据。此外，还添加了对"Other Custom Fields"的支持。对自定义字段放置有显着更改的记录类型是：
** 帐户
**  BIN
**  CASH_SALE
** 分类
** 客户
** 矿床
** 估计
**  EXPENSE_CATEGORY
**  EXPENSE_REPORT
** 的发票
**  ITEM_DEMAND_PLAN
**  ITEM_FULFILLMENT
**  ITEM_RECEIPT
**  ITEM_SUPPLY_PLAN
**  JOURNAL_ENTRY
**  LOCATION
**  MANUFACTURING_COST_TEMPLATE
**  MANUFACTURING_ROUTING
** 注意
**  PROMOTION_CODE
**  PURCHASE_REQUISITION
** 附属
**  VENDOR_BILL
**  VENDOR_CREDIT
**  VENDOR_PAYMENT
**  VENDOR_RETURN_AUTHORIZATION

=== 版本7.0.0  - 已知问题

没有。

=== 版本7.0.0  - 从旧版本迁移

对元数据进行了更改，因此升级到*NetSuite Connector 7.0.0*时，在设计时重新加载元数据。

本版本使用*SuiteTalk API version 2015.2*，其中NetSuite引入了一个名为*"Integration Record"*的新概念。这需要使用应用程序ID。因此，所有三种连接策略配置现在都有一个名为`applicationId`的新参数。
包含应用程序标识的集成记录可以通过导航到*Setup*> *Integration*> *Manage Integrations*在您的NetSuite环境中进行设置。全球元素现在看起来如下：

* 新的全局配置（从版本7.0.0开始）：

[source,xml,linenums]
----
<netsuite:config-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" applicationId="${applicationId}" />

<netsuite:config-request-level-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" applicationId="${applicationId}" />

<netsuite:config-sso-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" applicationId="${applicationId}" />
----

由于DataSense的介绍，`getRecord`和`getCustomRecord`的配置略有改变。此外，`@Default`现在在`internalId`上设置，默认值为`#[payload]`。

7.0.0之前的配置：

[source,xml,linenums]
----
<netsuite:get-record config-ref="">
	<netsuite:record-ref internalId="" externalId="" type="" />
</netsuite:get-record>
----

* 新配置（从版本7.0.0开始）：

[source,xml]
----
<netsuite:get-record config-ref="" internalId="" externalId="" type="" />
----

由于添加了分页来搜索，我们删除了现在多余的处理器`searchNext`，`searchMore`和`searchMoreWithId`。

此外，我们希望将搜索功能统一在一个处理器下，并且我们认为，随着迄今所做的改进以及对DataWeave的越来越多的使用，*`search`*应该成为前进的操作。此外，`searchWithExpression`和`query`操作在涉及某些复杂性时受到限制。因此，我们决定删除处理器`searchWithExpression`，`queryAsNativeResult`和`queryRecords`。

*`search`*现在总是会返回整组结果，而不仅仅是第一页。这将以地图列表的形式进行检索，这些地图列出了符合条件的所有找到的记录。可以设置新的参数fetchSize来控制分页支持使用的页面大小。

以下是`search`配置的示例：

[source,xml,linenums]
----
<netsuite:search config-ref="NetSuite__Login_Authentication" searchRecord="EMPLOYEE_BASIC" criteria-ref="#[payload]" fetchSize="5" />
----

如果您从`searchWithExpression`或`query`进行切换，以下是一些示例。使用DataWeave可以轻松构建搜索条件，为您生成脚本并仅要求填写值（如果您愿意，也可以使用Java组件或DataMapper）。

*  `searchWithExpression`到`search`：
+
[source,xml,linenums]
----
<netsuite:search-with-expression config-ref="NetSuite__Login_Authentication" searchRecord="EMPLOYEE_BASIC" expression="is(email, '#[map-payload:email]'), contains(address, '#[map-payload:address]')"/>
----
+
[source,xml,linenums]
----
<dw:transform-message doc:name="Transform Message">
	<dw:set-payload><![CDATA[%dw 1.0
%output application/java
---
{
	email: {
		operator: "IS",
		searchValue: payload.email
	} as :object {
		class : "com.netsuite.webservices.platform.core.SearchStringField"
	}
	address: {
		operator: "CONTAINS",
		searchValue: payload.address
	} as :object {
		class : "com.netsuite.webservices.platform.core.SearchStringField"
	}
} as :object {
	class : "com.netsuite.webservices.platform.common.EmployeeSearchBasic"
}]]></dw:set-payload>
</dw:transform-message>
<netsuite:search config-ref="NetSuite__Login_Authentication" searchRecord="EMPLOYEE_BASIC" fetchSize="50" doc:name="NetSuite"/>
----

*  `query`到`search`：
+
[source,xml,linenums]
----
<netsuite:query-records config-ref="NetSuite__Login_Authentication" query="dsql:SELECT * FROM EMPLOYEE WHERE firstName=#[message.inboundProperties.'http.query.params'.firstName]" fetchSize="50" doc:name="Query EMPLOYEE record"/>
----
+
[source,xml,linenums]
----
<dw:transform-message doc:name="Transform Message">
	<dw:set-payload><![CDATA[%dw 1.0
%output application/java
---
{
	firstName: {
		operator: "IS",
		searchValue: inboundProperties.'http.query.params'.firstName
	} as :object {
		class : "com.netsuite.webservices.platform.core.SearchStringField"
	}
} as :object {
	class : "com.netsuite.webservices.platform.common.EmployeeSearchBasic"
}]]></dw:set-payload>
</dw:transform-message>
<netsuite:search config-ref="NetSuite__Login_Authentication" searchRecord="EMPLOYEE_BASIC" fetchSize="50" doc:name="NetSuite"/>
----

最后，`getDeletedRecords`也进行了重新设计。现在，该操作将期望有效负载上的`SearchDateField`作为其`@Default`值，并与之前的pageIndex和type一起使用。 `SearchDateField`也可以手动定义。这里有些例子：

[source,xml,linenums]
----
<netsuite:get-deleted-records config-ref="NetSuite__Login_Authentication" type="ACCOUNT">
    <netsuite:deleted-date ref="#[payload]"/>
</netsuite:get-deleted-records>

<netsuite:get-deleted-records config-ref="NetSuite__Login_Authentication" type="EMPLOYEE">
    <netsuite:deleted-date operator="ON" searchValue="#[java.util.Calendar calendar = new GregorianCalendar(); calendar.set(2015, 10, 01); return calendar;]"/>
</netsuite:get-deleted-records>

<netsuite:get-deleted-records config-ref="NetSuite__Login_Authentication" type="CUSTOMER" doc:name="NetSuite">
    <netsuite:deleted-date operator="BEFORE" predefinedSearchValue="THIS_MONTH"/>
</netsuite:get-deleted-records>
----

== 版本6.0.1  -  2015年7月30日

=== 版本6.0.1  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本

| Mule运行时间
| 3.5及更高版本

| API
| SuiteTalk 2015_1
|===

=== 版本6.0.1  - 功能

没有。

=== 版本6.0.1  - 已在此版本中修复

* 修复了在web服务请求上只传递一个自定义字段的问题。
* 修复了搜索类别的DataSense元数据类别密钥重复的问题。

=== 版本6.0.1  - 已知问题

没有。

=== 版本6.0.1  - 从旧版本迁移

对元数据进行了更改，因此升级到*NetSuite Connector 6.0.1*时，在设计时重新加载元数据。

在这个版本中，用户现在可以看到多个全局元素，每个元素代表了一种向NetSuite进行身份验证的不同方式。

* 以前的全局配置：

[source,xml,linenums]
----
<netsuite:config name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" authenticationType=${authenticationType} />
----

* 新的全球配置：

[source,xml,linenums]
----
<netsuite:config-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />

<netsuite:config-request-level-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />

<netsuite:config-sso-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />
----

== 版本6.0.0  -  2015年7月10日

=== 版本6.0.0  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本

| Mule运行时间
| 3.5及更高版本

| API
| SuiteTalk 2015_1
|===

=== 版本6.0.0  - 功能

* 支持HTTP代理。
* 开始使用元数据类别，从而使得搜索和异步搜索操作能够识别元数据。
* 添加了允许单点登录登录的新身份验证类型。
* 将连接器迁移到CXF 2.7.15。

本版本中已修复=== 

* 记录类型属性使用*Calendar*而不是*XMLGregorianCalendar*处理。
* 用于定制的元数据键（自定义记录类型除外）不再以internalId作为键的一部分生成。
* 操作"Get Saved Search"现在显示适当的记录类型。
* 自定义字段的元数据已得到改进。对自定义字段放置有显着更改的记录类型是：
**  ASSEMBLY_BUILD
**  EXPENSE_REPORT
**  ITEM_FULFILLMENT
**  ITEM_RECEIPT
**  JOURNAL_ENTRY
**  sales_order的
** 机会
**  PURCHASE_ORDER
**  TRANSFER_ORDER
**  WORK_ORDER
* 添加了AssemblyItem实体上缺少的字段，例如intercoIncomeAccount和intercoCogsAccount。

=== 版本6.0.0  - 已知问题

没有。

=== 版本6.0.0  - 从旧版本迁移

对元数据进行了更改，因此升级到*NetSuite Connector 6.0.0*时，在设计时重新加载元数据。

在此版本中，我们已将连接器升级到DevKit 3.6.1并引入了连接策略。用户现在可以看到多个全局元素，每个元素代表对NetSuite进行身份验证的不同方式。

* 以前的全局配置：

[source,xml,linenums]
----
<netsuite:config name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" authenticationType=${authenticationType} />
----

* 新的全球配置：

[source,xml,linenums]
----
<netsuite:config-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />

<netsuite:config-request-level-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />

<netsuite:config-sso-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />
----


== 版本5.0.0  -  2015年4月15日

=== 版本5.0.0  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本

| Mule运行时间
| 3.5及更高版本

| API
| SuiteTalk 2015_1
|===

=== 版本5.0.0  - 功能

* 将连接器升级到SuiteTalk API 2015_1版。
* 操作"Get Deleted Records"不再限制要检索的记录数。此操作现在使用根据对SuiteTalks API的新更改的页面索引。

=== 版本5.0.0  - 已在此版本中修复

已将*  WSDL和XSD从连接器分发中排除。

=== 版本5.0.0  - 已知问题

没有。

== 版本4.0.11  -  2014年11月28日

=== 版本4.0.11  - 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本

| Mule运行时间
| 3.5.2

| Anypoint Studio
| 2014年10月

| API
| SuiteTalks 2014_1
|===

=== 版本4.0.11  - 功能

* 添加了一个选项，可以从登录验证切换到每个请求发送验证信息，以实现并发。使用此连接器的旧版本构建的任何现有应用程序在更新到新版本时都不会失败，因为为此类应用程序的登录验证配置了默认值。 +

=== 版本4.0.11  - 已在此版本中修复

本版本中已解决以下问题：

[%header%autowidth.spread]
|===
| {修复{1}}说明

|取代了依赖关系
|用来自DevKit父级的更新依赖关系替换了pom.xml文件中的一些不必要的依赖项。

|替换演示
|将现有示例演示替换为NetSuite CRUD操作的新演示。

|修复空点异常
|修复当检索元数据时避免空点异常。
|===

=== 版本4.0.11  - 已知问题

没有。

== 资源

*  https://forums.mulesoft.com [MuleSoft论坛]。
*  https://support.mulesoft.com [联系MuleSoft支持]。
