= 早期访问RAML 1.0

借助最新版本的工具和Anypoint平台，MuleSoft引入了基于官方 link:https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md[RAML 1.0规范]的早期访问。新版本引入了RAML.org link:https://github.com/raml-org/raml-spec/wiki/RAML-1.0-RC1-vs-RC2[发布的比较]中列出的许多新功能。

经过几个月与RAML工作组紧密合作后，MuleSoft正在将MuleSoft产品版本与RAML 1.0 GA版本同步。 MuleSoft客户可以使用RAML候选版本在Anypoint Platform中探索1.0概念。在大多数情况下，尽管本文档描述的早期访问版本存在已知的空白，但客户应该能够使用RAML 1.0编写API定义而不出现问题。

注意：Mule 3.8.1和更高版本提供完整的RAML 1.0支持。

== 迁移通知

由于RAML 1.0是早期访问，工具中使用的默认版本是0.8。要尝试版本1.0，您必须更改版本。

要从RAML 0.8迁移到RAML 1.0，请参见RAML 0.8和RAML 1.0之间的 link:https://github.com/raml-org/raml-spec/wiki/Breaking-Changes[突破变化]列表。

[IMPORTANT]
基于使用1.0版本编写的RAML文件的RAML代理仅适用于Mule 3.8.0运行时。以前的网关版本不支持RAML 1.0。

== 基础解析器和已知的差距

对于RAML 1.0，已经实现了 link:https://github.com/raml-org/raml-js-parser-2/tree/0.2.10[JavaScript的]和https://github.com/raml-org/raml-java-parser/tree/v2[Java]分析器的新版本。 MuleSoft工具依赖于这些解析器来验证RAML并公开所需的API。下表显示了解析器实现的工具依赖关系：

[%header,cols="30a,70a"]
|================
| {分析器{1}}工装
.5 + |  JavaScript  |  * API Designer
|  *嘲笑服务
|  * API控制台
|  *笔记本
Studio中的|  * API控制台
.4 + |  Java  |  * Mule 3.8.0
|  * APIkit 3.8.0
Studio中的|  * RAML编辑器
|  * HTTP连接器
|================

==  JavaScript解析器已知的差距

目前的JavaScript解析器100％符合规范，没有任何已知的差距。

==  Java分析器已知的差距
目前的Java解析器还不完全符合规范。下表列出了功能差距：

[%header,cols="30a,70a"]
|================
| {文本{1}}参数
| 使用密钥 |  link:https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#applying-libraries[规范]支持任何片段中的`uses`节点。目前，解析器只允许根级RAML文档和库中的`uses`节点。
| 标量字段的注释 | 除了某些映射节点之外， link:https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#annotating-scalar-valued-nodes[规范]允许将标注应用于标量节点。不支持标量级别的注释。
| 叠加限制 | 叠加应用程序未执行所有必需的限制。 Overlays强制执行与扩展的额外限制未经验证。
.2 + | 安全方案缺口 |  * OAuth 1.0 `signatures`设置不受支持
|  * OAuth 2.0 `authorizationUri`始终是可选的，无论授权是否授予。
|  XML针对YAML类型的示例验证 | 不支持针对YAML中定义的类型验证XML示例。 XML验证仅支持以XSD格式定义的模式。
.8 + | 类型系统差距 | 与定义相关的这些功能不受支持：
|  *原始类型的继承
|  * `discriminator`字段
|  *嵌套在值中的示例
|  * Xml Facet字段
|  *其他属性
|  * `null`类型
|  *以尾部问号命名的属性
|================

请参阅 link:https://github.com/raml-org/raml-java-parser/blob/0.1.0-alpha-2/MISSING.md[“RAML 1.0功能差距”]以获取最新列表。

按产品支持差距== 

===  API控制台和模拟服务

API控制台和Mocking Service依赖于JavaScript解析器来解析数据类型和整体API行为。 API控制台和模拟服务目前不支持 link:https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#annotations[注释]。在API控制台中使用RAML 1.0注释运行RAML文件时，注释不会出现在控制台文档和试用标签中。注释仅在API Designer的RAML定义中可见，并且在API Console和Mocking Service工具中不起作用。

===  API Notebook

API Notebook支持RAML 1.0，但有以下限制：

* 数据类型在此上下文中无意义。
* 叠加在这种情况下没有意义。

===  APIkit

APIkit依赖于Java分析器来验证和支撑RAML文件，因此它继承了上面在“Java Parser Known Gaps”一节中列出的Java分析器的限制。当您尝试对包含尚未被Java解析器支持的元素的RAML文件进行搭建时，验证将失败，并且不会生成流。

OData APIkit扩展测试版不支持RAML 1.0或Studio 6.0中集成的新APIkit。使用OData扩展的客户应推迟升级并继续使用Studio 5.4。 Studio版OData实现功能的GA版本将在近期发布。

=== 工作室

Studio的嵌入式RAML编辑器依赖于Java分析器来验证和建议RAML 1.0语法。嵌入式APIkit也依赖于脚手架功能的Java解析器（见下文）。嵌入式API控制台依赖于JavaScript解析器，并与独立的API控制台保持一致：

* 对于RAML 1.0的提示器不支持没有标题的RAML类型或RAML文件。用户可能无法完全从编辑推荐某些标签和自动完成。
* 嵌入式RAML 1.0编辑器验证功能与Java解析器具有同等功能。使用与“Java Parser Known Gaps”部分中列出的RAML 1.0相关的语法可能导致不正确的验证。
*  MUnit RAML-to-Test自动生成功能不支持RAML 1.0。我们正在积极努力发展该功能。
*  DataSense目前不支持RAML 1.0类型。当客户使用RAML 1.0时，DataSense不会传递和利用元数据。

===  API管理器

Mule 3.8.0依赖于Java解析器。 API Manager依靠Mule 3.8.0支持基于RAML 1.0的自动生成代理。在大多数情况下，代理生成功能在API Manager for RAML 1.0定义的API上运行良好。但是，如果用户尝试基于RAML 1.0文件自动生成代理，并且定义中存在已知间隙（未在API Manager上由Java分析程序覆盖），则部署的代理将失败。

== 产品间已知验证差异的详细信息

API Designer支持基于JavaScript（JS）解析器的RAML 1.0，而Studio RAML编辑器和APIkit则使用Java解析器。由于RAML 1.0中Java解析器的不完全支持，用户可能会看到产品之间的差异。

以下部分描述了验证行为中的已知差异。

=== 甲。注释标量注释

除了某些映射节点之外， link:https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#annotating-scalar-valued-nodes[规范]允许将标注应用于标量节点。如果用户指定以下内容：

----
baseUri:
  value: http://www.example.com/api
  (redirectable): true
----

* 在当前的RAML规范中：有效
* 在JavaScript解析器（即API Designer）中：有效
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：INVALID

=== 乙。用于任何片段

link:https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#applying-libraries[规范]允许在任何片段中使用用途。 Java解析器仅允许其在根级别的RAML文档和库中使用。

----
#%RAML 1.0 ResourceType
# This file is located at files-resource.raml
uses:
  files: libraries/files.raml
get:
  is: files.drm
----

* 在当前的RAML规范中：有效
* 在JavaScript解析器（即API Designer）中：有效
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：INVALID

=== ℃。空类型

RAML 1.0引入了null类型。如果用户指定以下内容：

----
annotationTypes:
  deprecated: null
  testHarness: null | string
  badge: string? # equivalent to ‘null | string’
----

* 在当前的RAML规范中：有效
* 在JavaScript解析器（即API Designer）中：有效
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：INVALID

===  d。示例/示例

RAML 1.0放宽了示例/示例的语法要求，并将“content”替换为“value”。如果用户指定以下内容：

----
types:
  Org:
    type: object
    properties:
      name: string
      address?: string
    examples:
      acme:
        name: Acme
      softwareCorp:
        value:
          name: Software Corp
          address: 35 Central Street

-----
example:
  height: 12
  width: 4

-----
example:
  (pii): true
  strict: false
  value:
    height: 12
    width: 4
----

* 在当前的RAML规范中：有效
* 在JavaScript解析器（即API Designer，API Console）中：有效
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：INVALID

=== 如其他属性（模式属性）

这是从RC1到RC2的一种变化，它将语法从`[]`更改为`//`，因为它引入了与YAML的冲突。如果用户指定以下内容：

----
types:
  Person:
    properties:
      a: string
      [a]: number
----

* 在当前的RAML规范中：INVALID
* 在JavaScript解析器（即API Designer，API Console）中：INVALID
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：VALID

如果用户指定以下内容：

----
types:
  Person:
    properties:
      a: string
      //: number
----

* 在当前的RAML规范中：有效
* 在JavaScript解析器（即API Designer，API Console）中：有效
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：INVALID

===  F。问号

如果用户指定以下内容：

----
types:
  profile:
    properties:
      preference?:
        required: true
----

* 在当前的RAML规范中：有效
* 在JavaScript解析器（即API Designer，API Console）中：有效
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：INVALID

===  -G。原始价值的继承

如果用户指定以下内容：

----
types:
  Number1:
   type: number
   minimum: 4
  Number2:
   type: number
   maximum: 10
  Number3: [ Number1, Number2]
----

* 在当前的RAML规范中：有效
* 在JavaScript解析器（即API Designer，API Console）中：有效
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：INVALID

=== 小时。鉴别

如果用户指定以下内容：

----
application/json: 
   type: Phone | Notebook
   discriminator: kind
----

* 在当前的RAML规范中：INVALID
* 在JavaScript解析器（即API Designer，API Console）中：INVALID
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：VALID

=== 我。在类型中键入

如果用户指定以下内容：

----
types:
  Next:
    type:
      properties:
        another: string
    properties:
      name: string
----

* 在当前的RAML规范中：有效
* 在JavaScript解析器（即API Designer，API Console）中：有效
* 在Java解析器（即Studio，APIkit中的RAML编辑器）中：INVALID

