= 运行时管理器代理1.6.0发行说明
:keywords: mule, agent, release notes

_企业版_

*November 19, 2016*

Runtime Manager Agent 1.6.0提供了一个新的可下载的zip文件，可轻松更新Runtime Manager Agent。从以下URL下载Runtime Manager代理。

https://support.mulesoft.com/s/downloads

您必须提供您的Anypoint登录名和密码才能访问此页面。

*Runtime Manager Agent Install Guide*： link:/runtime-manager/installing-and-configuring-runtime-manager-agent[安装和配置Runtime Manager Agent]

== 兼容性

[%header,cols="2*a",width=70%]
|===
| {软件{1}}版本
| Mule运行时| 3.6.n，3.7.n，3.8.n
| API网关| 2.n及以上
|运行时管理器 |  V2.0 +用于完整的服务器仪表板和流程管理
|===

[NOTE]
====
此版本（至少）用于访问作为Runtime Manager Cloud V2.0 +的一部分发布的功能。
它还需要访问Anypoint Platform私有云版本V1.0和V1.5中的运行时管理器

Onprem V1.5目前不包含监控功能，Flow Management或Insight，但将在未来版本中提供。
====

== 硬件和软件要求

不用找了。

== 改进并解决问题

* 支持 link:/runtime-manager/flow-management[流量管理]
* 支持仪表板中的新服务器指标


== 已知问题

没有

== 迁移指南

请参阅 link:/runtime-manager/installing-and-configuring-runtime-manager-agent#updating-a-previous-installation[更新Runtime Manager代理]。

== 另请参阅

*  link:/runtime-manager/runtime-manager-agent[运行时管理器代理]
*  https://support.mulesoft.com [联系MuleSoft]
