:keywords: arm, runtime manager, release notes

=  Anypoint Runtime Manager发行说明

[NOTE]

此页面中列出的版本是指在混合部署方案中对Runtime Manager所做的更改，这使您可以在用户托管的服务器上部署Mule应用程序，但通过MuleSoft的基于云的平台继续管理和监视它们。

== 版本2.8.4  -  2018年5月19日

查看 link:/release-notes/runtime-manager-2.8.4-release-notes[Runtime Manager v2.8.2发行说明]

== 版本2.8.3

仅限内部发布。没有面向客户的变化。

== 版本2.8.2  -  2018年3月24日

查看 link:/release-notes/runtime-manager-2.8.2-release-notes[Runtime Manager v2.8.2发行说明]

== 版本2.8.1  -  2018年2月22日

查看 link:/release-notes/runtime-manager-2.8.1-release-notes[Runtime Manager v2.8.1发行说明]

== 版本2.8.0  -  2018年1月25日

查看 link:/release-notes/runtime-manager-2.8.0-release-notes[Runtime Manager v2.8.0发行说明]

== 版本2.7.0  -  2018年1月13日

查看 link:/release-notes/runtime-manager-2.7.0-release-notes[运行时管理器v2.7.0发行说明]

== 版本2.6.1  -  2017年11月19日

查看 link:/release-notes/runtime-manager-2.6.1-release-notes[Runtime Manager v2.6.1发行说明]

== 版本2.6.0  -  2017年10月20日

请参阅 link:/release-notes/runtime-manager-2.6.0-release-notes[Runtime Manager 2.6.0发行说明]。

== 版本2.5.0  -  2017年9月9日

请参阅 link:/release-notes/runtime-manager-2.5.0-release-notes[Runtime Manager 2.5.0发行说明]。

== 版本2.4.3  -  2017年8月26日

请参阅 link:/release-notes/runtime-manager-2.4.3-release-notes[运行时管理器2.4.0发行说明]。

== 版本2.4.0  -  2017年6月24日

* 使运行时管理器能够显示有关远程服务器的附加信息。

请参阅 link:/release-notes/runtime-manager-2.4.0-release-notes[运行时管理器2.4.0发行说明]。

== 版本2.3.1  -  2017年6月3日

* 在混合部署方案中启用服务器的重新启动和关闭。

请参阅 link:/release-notes/runtime-manager-2.3.1-release-notes[Runtime Manager 2.3.1发行说明]。

== 版本2.3.0  -  2017年5月20日

本版本引入了以下功能：

* 对混合安装中支持的功能的增强。

请参阅 link:/release-notes/runtime-manager-2.3.0-release-notes[Runtime Manager 2.3.0发行说明]。

== 版本2.2.0  -  2017年4月8日

本版本引入了以下功能：

* 流量监控：用户现在可以随时监控每个Mule流量中的关键指标。这将有助于可视化应用程序的演变并比较它们的流程。

请参阅 link:/release-notes/runtime-manager-2.2.0-release-notes[Runtime Manager 2.2.0发行说明]。


== 版本2.1.0  -  2017年3月11日

此版本引入了以下功能：

* 改进了对用户界面环境之间混合应用程序推广的支持

* 能够在部署时启用和禁用混合应用程序的洞察

* 能够在部署时为混合应用程序配置日志级别

此版本还包含重要的后端改进以提高性能并缩短响应时间。

查看完整的 link:/release-notes/runtime-manager-2.1.0-release-notes[Runtime Manager 2.1.0发行说明]。

== 版本2.0  -  2016年11月19日

本版本包含以下新功能：

*  link:/runtime-manager/insight[眼光]为混合用户。
* 流程管理
* 监控V2.0

查看完整的 link:/release-notes/runtime-manager-2.0-release-notes[Runtime Manager 2.0发行说明]。

== 版本1.5.1  -  2016年8月27日

本版本包含一些小改进。


查看完整的 link:/release-notes/runtime-manager-1.5.1-release-notes[Anypoint Runtime Manager 1.5.1发行说明]。

== 版本1.5  -  2016年7月21日

此版本包含以下新功能：

适用于本地应用程序和服务器的*  link:/runtime-manager/monitoring-dashboards[仪表板]以及链接到这些指标的新 link:/runtime-manager/alerts-on-runtime-manager[警报]
*  link:/runtime-manager/insight[洞察]部署在本地的应用程序
* 自动迁移部署的迁移工具 - 很快将被弃用 -  Mule管理控制台（MMC）迁移到运行时管理器

查看完整的 link:/release-notes/runtime-manager-1.5.0-release-notes[Anypoint Runtime Manager 1.5.0发行说明]。

== 版本1.4.1  -  2016年5月6日

此版本包含以下新功能：

适用于本地应用程序和服务器的*  link:/runtime-manager/alerts-on-runtime-manager[警报]
* 支持 link:/runtime-manager/installing-and-configuring-mule-agent#ports-ips-and-hostnames-to-whitelist[静态IP地址]

查看完整的 link:/release-notes/runtime-manager-1.4.1-release-notes[Anypoint Runtime Manager 1.4.1发行说明]。


== 版本1.4.0  -  2016年4月23日

此版本包含以下新功能：

运行时管理器事件的*  link:/access-management/audit-logging[审计日志记录]
* 主页上的名称更改，以前称为CloudHub的控制台现在称为运行时管理器。

+
[NOTE]
从现在起，CloudHub的名称仅用于引用运行时管理器的功能，这些功能涉及将应用程序部署到云工作者，VPC和负载平衡。

查看完整的 link:/release-notes/runtime-manager-1.4.0-release-notes[Anypoint Runtime Manager 1.4.0发行说明]。


== 版本1.3.1

此版本包含以下新功能：

* 对 link:/runtime-manager/sending-data-from-arm-to-external-analytics-software[发送数据到Splunk]处理程序的增强
*  JMX处理程序增强功能

查看完整的 link:/release-notes/anypoint-runtime-manager-1.3.1-release-notes[Anypoint Runtime Manager 1.3.1发行说明]。


== 版本1.3.0

此版本包含以下新功能：

* 针对 link:/runtime-manager/managing-servers#create-a-cluster[聚类]的可用性增强
*  RDBMS支持（测试版）


查看完整的 link:/release-notes/anypoint-runtime-manager-1.3-release-notes[Anypoint Runtime Manager 1.3发行说明]。


== 版本1.2.0

此版本包含以下新功能：

Splunk和通用日志的*  link:/runtime-manager/sending-data-from-arm-to-external-analytics-software[代理插件集成]

*  API网关运行时集成


查看完整的 link:/release-notes/runtime-manager-1.2.0-release-notes[Anypoint Runtime Manager 1.2.0发行说明]。
