=  Runtime Manager 2.0发行说明
:keywords: arm, runtime manager, release notes

Anypoint Runtime Manager V2.0计划于11月19日发布。 +
此版本包含针对混合用户的*Insight*，*flow management*和更精细的监控图表等全新的细化问题排查功能，以便用户更快速地检测问题的根源。

== 硬件和软件要求

不用找了。

== 兼容性

代理插件集成与以下运行时版本兼容：

[cols="2*a"]
|===
| Mule  |  3.6.x及以上。
|可用性 | 仅云。
API Analytics的| API GateWay  |  2.x及以上版本
适用于Insight的|运行时管理器代理 |  link:/release-notes/runtime-manager-agent-1.5.0-release-notes[1.5.0及以上]， link:/runtime-manager/flow-management[流量管理]和 link:/runtime-manager/insight[所有指标图表]的 link:/release-notes/runtime-manager-agent-1.6.0-release-notes[1.6.0及以上]
|===


== 功能和功能

*  *Insight for Hybrid Users*： link:/runtime-manager/insight[眼光]使用户能够针对性能和健康相关问题对其应用程序进行细粒度级别的故障排除，从而使用户能够快速高效地确定问题的根本原因。这现在可供所有用户使用。
*  *Flow Management*：用户将能够在运行时管理其有问题的流程。他们现在可以在不中断整个应用程序的情况下禁用流程。
*  *Monitoring V2.0*：此版本包含适用于本地服务器的度量标准的粒度监控图表，因此可供混合用户使用。 +
新图表包括：

** 垃圾收集
** 堆/非堆
** 加载平均值
** 线程数。

此外，还设置了负载平均和线程数警报。

[NOTE]
--
流量管理和监控V2.0功能仅适用于部署在本地的集成应用程序，但管理通过云控制台进行。
--

== 已弃用的功能或功能

没有。
