= 运行时管理器代理1.6.2发行说明
:keywords: mule, agent, release notes

_企业版_

*February 24, 2017*

Runtime Manager Agent 1.6.2提供了一个新的可下载的zip文件，以轻松更新Runtime Manager Agent。从以下URL下载Runtime Manager代理。

https://support.mulesoft.com/s/downloads

您必须提供您的Anypoint登录名和密码才能访问此页面。

*Runtime Manager Agent Install Guide*： link:/runtime-manager/installing-and-configuring-runtime-manager-agent[安装和配置Runtime Manager Agent]

== 兼容性

[%header,cols="2*a",width=70%]
|===
| {软件{1}}版本
| Mule运行时| 3.6.n，3.7.n，3.8.n
| API网关| 2.n及以上
|运行时管理器 |  V2.0
|===

[NOTE]
====
要访问作为Runtime Manager Cloud V2.0 +的一部分发布的功能，需要1.6.0版（至少）。
还需要访问Anypoint Platform内部版本V 1.0和V1.5中的运行时管理器

Onprem V1.5目前不包含监控功能，流量管理或Insight。
====

== 硬件和软件要求

不用找了。

== 改进并解决问题

*  [CHHYBRID-2531]启用事件跟踪并修改消息类型时，Payload已损坏


== 已知问题

没有

== 迁移指南

请参阅 link:/runtime-manager/installing-and-configuring-runtime-manager-agent#updating-a-previous-installation[更新Runtime Manager代理]。

== 另请参阅

*  link:/runtime-manager/runtime-manager-agent[运行时管理器代理]
*  https://support.mulesoft.com [联系MuleSoft]
