=  Runtime Manager Agent 1.4.0发行说明
:keywords: mule, agent, 1.3, release notes

_企业版_

*April 04, 2016*

Runtime Manager Agent 1.4.0提供了一个新的可下载的zip文件，以轻松更新Runtime Manager Agent。从以下URL下载Runtime Manager代理。

https://support.mulesoft.com/s/downloads

您必须提供您的Anypoint登录名和密码才能访问此页面。

*Runtime Manager Agent Install Guide*： link:/runtime-manager/installing-and-configuring-mule-agent[安装和配置Runtime Manager Agent]

== 兼容性

[%header,cols="2*a",width=70%]
|===
| {软件{1}}版本
| Mule运行时| 3.6.n和3.7.n
| API网关| 2.n
|===

== 硬件和软件要求

不用找了。

本版本中的== 功能

* 支持静态IP地址：代理现在可以支持特定的静态地址。

* 添加外部处理程序来管理监视服务跟踪的bean

== 已弃用的功能和功能

没有。


== 已修复问题

AGENT-275  - 删除/ mule / agent / ping端点，因为它没有被使用并导致mule退出

AGENT-277  - 为统一的Mule Runtime 3.8.0检索正确的Mule和GW版本

AGENT-278  - 跟踪测试失败，未找到org / apache / http / ssl / TrustStrategy类错误

AGENT-284  -  Runtime Manager Agent未检测到3.8.0-M1 Mule Runtime是统一运行时

AGENT-297  - 使用自定义密钥存储配置REST传输不使用给定的文件

AGENT-286  - 在统一运行时服务器注册时将运行时报告为Mule


== 已知问题

没有。

== 另请参阅

*  link:/runtime-manager/runtime-manager-agent[运行时管理器代理]
*  https://support.mulesoft.com [联系MuleSoft]
