=  Salesforce Marketing Cloud连接器发行说明
:keywords: release notes, salesforce, marketing, cloud, connector

*January 2018*

_选择_

Salesforce Marketing Cloud连接器允许您使用Exact Target API连接到Salesforce Marketing Cloud Web服务。该连接器提供了用于管理由Exact Target API（也称为Salesforce Marketing Cloud）提供的对象和调用服务的便捷方法。

==  2.0.0

*January 19, 2018*

Salesforce Marketing Cloud连接器的发行说明。

=== 兼容性

Salesforce Marketing Cloud连接器与以下产品兼容：

[%header%autowidth.spread]
|===
|应用/服务 |版本
| Mule运行时 | 4.0及更高版本
| Anypoint Studio  | 7及更高版本
|准确的目标API  | v145.3
|===

=== 特点

* 配置创建 - 连接到Marketing Cloud SOAP Web服务时，将带"Create"的"Configure"命令作为操作属性。
* 配置删除 - 连接到Marketing Cloud API SOAP Web服务时，调用"Configure"命令作为操作属性"Delete"。
* 配置更新 - 连接到Marketing Cloud API SOAP Web服务时，将"Update"调用"Configure"命令作为操作属性。
* 创建 - 在Marketing Cloud API Web服务器上创建一个新对象。
* 删除 - 删除Marketing Cloud API Web服务器上的现有对象。
* 执行get max count  - 连接到Marketing Cloud API SOAP Web服务时，将"GetMaxCount"用作操作属性调用"Perform"命令。
* 执行开始 - 当连接到Marketing Cloud API SOAP Web服务时，发送"Start"的"Perform"命令作为操作属性。
* 执行stop  - 连接到Marketing Cloud API SOAP Web服务时，发送"Stop"的"Perform"命令作为操作属性。
* 检索 - 以类似于SQL查询的方式从Marketing Cloud API Web服务器检索对象。
* 计划开始 - 连接到Marketing Cloud API SOAP Web服务时，将带有"Start"的"Schedule"命令作为操作属性进行调用。
* 更新 - 更新Marketing Cloud API Web服务器上的现有对象。
*  Upsert  - 如果对象尚不存在，或者删除Marketing Cloud API Web服务器上的现有对象，则创建一个对象。此操作通过使用Marketing Cloud API SOAP API的"Create"方法实现。

本版本中已修复=== 

这是连接器的第一个版本，因此不需要修复;只有新功能。

=== 已知问题

==== 将子类作为类型提供给复杂字段

某些对象具有复杂的字段，表示Salesforce Marketing的基类。因此，如果不是基类，而是想将它的子类作为值传递给该字段，那是不可能的
因为连接器无法识别不属于基类的字段。您必须在Transform Message中手动映射这些字段，并将名为"concreteClassType"的字段添加为子类的名称作为值。有关更多信息和示例，请阅读连接器指南。

==== 不可能从层次结构中检索字段

API不支持在层次结构中查询低于级别1的字段。例如，像`Select Attributes.Name from Subscriber`这样的查询，因为Name在层次结构中处于级别2。

包含自动化对象结构的==== 服务器结果导致异常被抛出

在对Automation对象执行操作时，操作的结果会导致抛出异常，因为响应中有一个API无法解析的字段。为了绕过这一点，使这些类型的操作异步。

== 另请参阅

*  https://forums.mulesoft.com [MuleSoft论坛]
*  https://support.mulesoft.com [联系MuleSoft支持]

