=  Salesforce Analytics云连接器版本说明
:keywords: release notes, salesforce, analytics, cloud, connector

*February 2018*

_选择_

用于Salesforce Analytics Cloud的Anypoint连接器可让您使用Salesforce外部数据API连接到Salesforce Analytics Cloud应用程序。该连接器提供了创建数据集并将其填充到Salesforce Analytics Cloud系统的便捷方法。

== 版本2.2.0  -  2018年2月20日

此版本增加了新功能。

=== 版本2.2.0  - 兼容性

Salesforce Analytics云连接器与以下产品兼容：

[%header%autowidth.spread]
|===
|应用/服务 |版本
| Mule Runtime  |  3.5.0及更高版本
|外部数据API  |  v36.0
|===

=== 版本2.2.0  - 功能

* 增加了对允许OAuth 2.0 JWT承载和OAuth 2.0 SAML承载通配符元数据/ *。json的支持。
+
配置连接器的全局基本身份验证时，通配符现在可用于元数据文件名称字段。
* 增加了对禁用会话失效的支持。
+
认证配置现在允许您通过选中禁用会话失效复选框来禁用会话失效。

=== 版本2.2.0  - 已在此版本中修复

没有。

== 版本2.1.1  -  2018年1月11日

Salesforce Analytics云连接器版本2.1.1的发行说明。

=== 版本2.1.1  - 兼容性

Salesforce Analytics云连接器与以下产品兼容：

[%header%autowidth.spread]
|===
|应用/服务 |版本
| Mule Runtime  |  3.5.0及更高版本
|外部数据API  |  v36.0
|===

==== 版本2.1.1  - 功能

没有。

=== 版本2.1.1  - 已在此版本中修复

* 修正了不支持TLS版本时的异常消息。
+
错误消息"Failed logging in into Salesforce system"未反映TLS版本不支持的根本原因。
+
* 同时使用连接器时记录重复。
* 添加了元数据字段：
+
**  canTruncateValue  - 指示当值超过精度时是否截断值。默认值是true。 canTruncateValue布尔否：如果为true，则截断值。如果为false，则该行被拒绝。
+
示例：`"canTruncateValue": true`
+
**  decimalSeparator  - 仅适用于数字字段。用十进制数字分隔数字的字符。可用于处理小数点分隔符为“，”的国际数字格式。默认值是“。”。
+
示例：`decimalSeparator String No "decimalSeparator": ","`
+
**  isYearEndFiscalYear  - 仅适用于日期字段。指示会计年度是财政年度结束还是开始的年份。因为会计年度可以从一个isYearEndFiscalYear开始布尔没有日历年，并且在另一个年份结束，请指定哪个年份用于会计年度。如果属实，那么财年就是财年结束的一年。默认值是true。如果不成立，那么财年就是财年开始的那一年。
+
示例：`"isYearEndFiscalYear": true`  - 仅当fiscalMonthOffset大于0时，此字段才有用。
+
firstDayOfWeek  - 仅限日期字段。**  firstDayOfWeek  - 仅限日期字段。日历年的第一天以及适用情况下的财政年度。使用0将第一天设置为星期日，1设置firstDayOfWeek数字第一天为星期一，依此类推。使用-1将第一天设置为1月1日。默认值为-1。
+
例如：`"firstDayOfWeek": 0`  - 另请参阅数据集中的日期处理。
+
**  isSkipped  - 指示数据上传时是否跳过该字段。示例：isSkipped布尔否"isSkipped"：true
+
* 为基本身份验证创建安全令牌字段可选。
+
即使连接器是可选的，连接器仍在强制使用安全令牌。

=== 版本2.1.1  - 已知问题

没有。

== 版本2.1.0  -  2016年10月5日

Salesforce Analytics Cloud连接器版本2.0.4的发行说明。

=== 版本2.1.0兼容性

Salesforce Analytics云连接器与以下产品兼容：

[%header%autowidth.spread]
|===
|应用/服务 |版本
| Mule运行时 |  3.5.0及更高版本
|外部数据API  |  v36.0
|===

==== 版本2.1.0功能

支持多个元数据文件。在配置的"Metadata File Name"上，您可以提供一个文件（例如metadata / meatadata.json）或通配符（例如metadata / *。json）

此版本中已修复=== 版本2.1.0

没有。

=== 版本2.1.0已知问题

没有。

== 版本2.0.3  -  2016年6月3日

Salesforce Analytics云连接器版本2.0.3的发行说明。

=== 版本2.0.3兼容性

Salesforce Analytics云连接器与以下产品兼容：

[%header%autowidth.spread]
|===
|应用/服务 |版本
| Mule运行时 |  3.5.0及更高版本
|外部数据API  |  v36.0
|===

==== 版本2.0.3功能

没有。

=== 版本2.0.3已在此版本中修复

通过添加`https.protocols` VM选项（例如`-Dhttps.protocols=TLSv1.1,TLSv1.2`），可以为JWT指定TLS版本配置的支持，SAML认证的指定方式与JVM相同。

=== 版本2.0.3已知问题

没有。

== 版本2.0.2  -  2016年4月4日

Salesforce Analytics云连接器版本2.0.2的发行说明。

=== 版本2.0.2兼容性

Salesforce Analytics云连接器与以下产品兼容：

[%header%autowidth.spread]
|===
|应用/服务 |版本
| Mule运行时 |  3.5.0及更高版本
|外部数据API  |  v36.0
|===

==== 版本2.0.2特性
* 将外部数据API升级到版本36.0。

本版本中已修复=== 版本2.0.2
没有。

=== 版本2.0.2已知问题
没有。

== 版本2.0.1  -  2015年11月6日

Salesforce Analytics云连接器2.1版的发行说明。这些发行说明伴随着
link:/mule-user-guide/v/3.9/salesforce-analytics-cloud-connector[Salesforce Analytics云连接器用户指南]。

=== 版本2.0.1兼容性

Salesforce Analytics云连接器与以下产品兼容：

[%header%autowidth.spread]
|===
|应用/服务 |版本
| Mule运行时 |  3.5.0及更高版本
|外部数据API  |  v34.0
|===

==== 版本2.0.1特性
这是一个小版本，它只包含修复程序。

本版本中已修复=== 版本2.0.1
* 当元数据发送到服务器时，"fiscalMonthOffset"作为字符串发送，而不是整数，这是服务器所期望的。
* 修复了以前版本的连接器中的问题，其中登录错误响应的分析不正确。

=== 版本2.0.1已知问题
没有。

== 版本2.0  -  2015年8月28日

Salesforce Analytics云连接器2.0版的发行说明。

=== 版本2.0兼容性

Salesforce Analytics云连接器与以下产品兼容：

[%header%autowidth.spread]
|===
|应用/服务 |版本
| Mule运行时 |  3.5.0及更高版本
|外部数据API  |  v34.0
|===

请注意，这是一个主要版本，它打破了向后兼容性。

==== 版本2.0功能

* 在"Create data set" / "Upload external data into new data set and start processing"个操作中添加了新的字段"Operation"，可以选择对数据集执行的操作。接受的值：OVERWRITE，APPEND，UPSERT，DELETE。
* 在"Create data set" / "Upload external data into new data set and start processing"次操作中添加了新的字段"Notification Sent"，可根据处理结果选择何时获取电子邮件通知。接受的值：始终，失败，警告，永远不会。
* 在"Create data set" / "Upload external data into new data set and start processing"个操作中添加了新的字段"Notification Email"，可以选择要发送通知的电子邮件地址。

本版本中已修复=== 版本2.0
* 为"Basic Authentication"配置添加了"Authorization URL"，以提供更改登录服务器的功能。所以现在您可以将连接器指向您选择的Salesforce环境
* 为"OAuth 2.0 SAML Bearer" / "OAuth 2.0 JWT Bearer"配置添加了"Token Endpoint"，以便能够更改令牌提供程序服务器。
* 删除了对多种格式元数据文件的支持，因此从所有配置中删除了"Metadata File Type"。
* 当提供给批量提交步骤的数据大于最大允许大小（10 MB）以使用InsightsExternalDataPart对象将一个块上传到Analytics Cloud时，添加了一条警告消息。这将有助于用户最大限度地提高连接器的性能。有关更多详细信息，请参阅API文档 link:https://developer.salesforce.com/docs/atlas.en-us.bi_dev_guide_ext_data.meta/bi_dev_guide_ext_data/bi_ext_data_add_data.htm[添加数据]。

=== 版本2.0已知问题
没有。

== 版本1.1  -  2015年4月17日

Salesforce Analytics云连接器版本1.1的发行说明。

=== 版本1.1兼容性

Salesforce Analytics云连接器与以下产品兼容：

[%header%autowidth.spread]
|===
|应用/服务 |版本
| Mule运行时 |  3.5.0及更高版本
|外部数据API  |  v31.0
|===

=== 版本1.1功能

=== 版本1.1功能

*  *Create data set*  - 此操作提供了在Google Analytics云中为数据摄入创建模式的功能
*  *Upload external data*  - 此操作会将数据上传到Analytics Cloud中的现有数据集。
*  *Start processing data*  - 此操作与Salesforce通信以开始处理上传的数据，以启用Wave中的数据可视化和其他功能。
*  *Upload external data into new data set and start processing*  - 该操作将上述三种操作合并为一项操作。

本版本中已修复=== 版本1.1
第一版。

=== 版本1.1已知问题
没有。

== 另请参阅

*  link:/mule-user-guide/v/3.9/salesforce-analytics-cloud-connector[Salesforce Analytics云连接器用户指南]。
*  link:https://developer.salesforce.com/docs/atlas.en-us.bi_dev_guide_ext_data.meta/bi_dev_guide_ext_data/[Salesforce外部数据API]。
*  https://forums.mulesoft.com [MuleSoft论坛]。
*  https://support.mulesoft.com [联系MuleSoft支持]。
