=  Salesforce Marketing Cloud连接器发行说明
:keywords: release notes, salesforce, marketing, cloud, connector

*March 2018*

_选择_

*Connector Guide*： link:/mule-user-guide/v/3.8/salesforce-marketing-cloud-connector[Salesforce Marketing Cloud连接器]

Salesforce Marketing Cloud连接器允许您使用https://developer.salesforce.com/docs/atlas.en-us.mc-apis.meta/mc-apis/index-api连接到Salesforce Marketing Cloud Web服务。 htm [Salesforce Marketing Cloud API]。该连接器提供了管理Salesforce Marketing Cloud提供的对象和调用服务的便捷方法。

== 版本1.1.0  -  2018年3月15日

此版本提供了新功能和错误修复。

=== 版本1.1.0  - 兼容性

Salesforce Marketing Cloud Connector版本1.1.0与以下产品兼容：

[%header,cols="2*a"]
|===
|应用/服务|版本
| Mule运行时| 3.5.2和更新版本
| Marketing Cloud API | v145.3
|===

=== 版本1.1.0  - 已在此版本中修复

* 修正了尝试获取数据传感时的NullPointerException。

=== 版本1.1.0  - 功能

* 添加了OAuth2身份验证支持。检查连接器指南了解更多详情。
* 在连接器指南中添加了关于如何设置系统代理的文档。

=== 版本1.1.0  - 已知问题

* 没有已知问题。

== 版本1.0.0  -  2016年2月12日

Salesforce Marketing Cloud连接器版本1.0.0的发行说明。这些发行说明伴随着 link:/mule-user-guide/v/3.8/salesforce-marketing-cloud-connector[Salesforce Marketing Cloud连接器用户指南]。

=== 版本1.0.0  - 兼容性

版本1.0.0 Salesforce Marketing Cloud连接器与以下产品兼容：

[%header,cols="2*a"]
|===
|应用/服务|版本
| Mule运行时| 3.5.2和更新版本
|准确的目标API | v145.3
|===

=== 版本1.0.0  - 功能

*  *Configure Create*  - 连接到Marketing Cloud Web服务时，调用"Configure"命令作为操作属性"Create"。
*  *Configure Delete*  - 连接到Marketing Cloud Web服务时，调用"Configure"命令作为操作属性"Delete"。
*  *Configure Update*  - 连接到Marketing Cloud Web服务时，调用"Configure"命令作为操作属性"Update"。
*  *Create*  - 在Marketing Cloud Web服务器中创建一个新对象。
*  *Delete*  - 删除Marketing Cloud Web服务器中的现有对象。
*  *Perform get max count*  - 连接到Marketing Cloud Web服务时，调用"Perform"命令作为操作属性"GetMaxCount"。
*  *Perform start*  - 连接到Marketing Cloud Web服务时，调用"Perform"命令作为操作属性"Start"。
*  *Perform stop*  - 将具有"Stop"的"Perform"命令作为Marketing Cloud SOAP Web服务的操作。
*  *Retrieve*  - 以类似时尚的SQL查询方式从Marketing Cloud Web服务器中检索对象。
*  *Schedule start*  - 连接到Marketing Cloud Web服务时，调用"Schedule"命令作为操作属性"Start"。
*  *Update*  - 更新Marketing Cloud Web服务器中的现有对象。
*  *Upsert*  - 当对象尚不存在时创建对象，或从Marketing Cloud Web服务器内删除现有对象时创建对象。此操作通过使用Marketing Cloud API中的"Create"方法完成。

=== 版本1.0.0  - 已在此版本中修复

* 这是连接器的第一个版本，因此不需要修复;只有新功能。

=== 版本1.0.0  - 已知问题

=== 将子类作为类型提供给复杂字段

* 一些对象具有复杂的字段，它们表示Salesforce Marketing的基类。因此，如果不是基类，而是想将它的子类作为值传递给该字段，那是不可能的
因为连接器无法识别不属于基类的字段。您必须在Transform Message中手动映射这些字段，并将名为"concreteClassType"的字段添加为子类的名称作为值。有关更多信息和示例，请阅读用户指南。

==== 不可能从层次结构中检索字段

*  API中不支持查询层次结构中低于级别1的字段。例如，像"Select Attributes.Name from Subscriber"这样的查询是因为"Name"在层次结构中处于第2级。

包含自动化对象结构的==== 服务器结果导致异常被抛出

* 在对Automation对象执行操作时，操作的结果会导致抛出异常，因为响应中有一个无法由API解析的字段。为了绕过这一点，使这些类型的操作异步。有关此问题的更多信息和示例，请阅读用户指南。

== 另请参阅

*  https://forums.mulesoft.com [MuleSoft论坛]。
*  https://support.mulesoft.com [联系MuleSoft支持]。
