=  SAP连接器发行说明
:keywords: java connector, jco, release notes, sap

*October 2017*

_Premium_

Mule Runtime通过我们的Anypoint Connector for SAP支持SAP集成，这是SAP认证的利用SAP Java Connector（JCo）库的Java连接器。

link:/mule-user-guide/v/3.8/sap-connector[SAP连接器用户指南]

== 版本3.2.0  -  2017年10月3日

[%header%autowidth]
|===
| {软件{1}}版本
| Mule运行时| 3.5.x
| Anypoint Studio | 6.3
| Java | 7,8
| SAP Solution |  ECC 6.0或更高版本
|支持的模块| SAP CRM，SAP ERP，SAP SRM，SAP SCM以及与NetWeaver平台兼容的任何其他模块。
|===

=== 特点

没有。

本版本中已修复=== 

*  *Transaction ID (TID) not copied to the outbound scope*  - 使用*Mule Runtime 3.8.x EE*进行出站呼叫时会发生此问题，该问题在影响连接器的事务管理实施中引入了修改。 SAP事务组件不会初始化事务，导致执行`#[message.outboundProperties.sapTid]`时出现空TID。现在问题已经解决，交易再次与Mule Runtime 3.5.x至3.8.x一起工作。除了目前的补丁之外，还可以通过将SAP组件包装在事务范围中来提供解决方法。

*  *NoSuchMethodError `getDefaultEncoding()`*  - 解决了编码问题导致的SAP 3.1.1中引入的回归错误。此异常仅在*Mule Runtime 3.5.x EE*中出现，因为该版本中不存在方法`getDefaultEncoding()`。它是在3.6.x中引入的。

*  *IDocs containing negative numbers fail to be parsed*  - 使用数据类型为NUMC的字段将IDOC发送给SAP时，转换失败。例如，如果将未知字段添加到IDoc中，则会出现类似的情况。 JCo可以通过配置一系列解析选项而不是SAP连接器来处理此内容。在当前版本中，这些选项通过系统属性`mule.sap.idoc.parserOptions`公开。可以使用逗号（","）分隔符组合多个选项，例如：`mule.sap.idoc.parserOptions=PARSE_WITH_FIELD_VALUE_CHECKING,PARSE_IGNORE_UNKNOWN_FIELDS`。以下是支持的选项：
    **  PARSE_WITH_FIELD_VALUE_CHECKING
    **  PARSE_IGNORE_UNKNOWN_FIELDS
    **  PARSE_IGNORE_INVALID_CHAR_ERRORS
    **  PARSE_WITHOUT_FIELD_DATATYPE_CHECKING
    **  PARSE_REFUSE_UNKNOWN_XMLVERSION
    **  PARSE_REFUSE_XMLVERSION_10
    **  PARSE_REFUSE_XMLVERSION_11
    **  PARSE_ACCEPT_ONLY_XMLVERSION_10
    **  PARSE_ACCEPT_ONLY_XMLVERSION_11
    **  PARSE_ACCEPT_ONLY_XMLVERSIONS_10_TO_11

*Note:*选项`PARSE_WITH_IGNORE_UNKNOWN_FIELDS`已弃用。

=== 已知问题

在热重新部署应用程序后（即修改`mule-config.xml`），* 目标提供程序引用会丢失



== 版本3.1.1  -  2017年7月31日

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5.x
| Anypoint Studio | 6.3
| Java | 7,8
| SAP Solution |  ECC 6.0或更高版本
|支持的模块| SAP CRM，SAP ERP，SAP SRM，SAP SCM以及与NetWeaver平台兼容的任何其他模块。
|===

=== 特点

没有。

本版本中已修复=== 

*  *Failure to refresh metadata*  - 这与先前修复的问题_ "Incomplete disposal of JCo classloader" _有关，但这次它在Mule应用程序级别（从全局配置）加载JCo库时会影响元数据。在这个版本中，问题已经解决，JCo可以在共享环境和独立环境中使用。
*  *DataSense cannot display metadata for extended IDocs*  -  IDoc（和BAPI）名称可能包含`/PACKAGE/IDOC_TYPE`，`PACKAGE-IDOC_TYPE`，`PACKAGE1-/PACKAGE2/IDOC_TYPE`等形式的名称空间。在以前版本的连接器，在为DataSense构建元数据时，这些名称空间被错误地转义，导致截断的XML。在当前版本中，此问题已修复，并且适用于任何化合物IDoc或BAPI名称的XML都已正确生成。
*  *Wrong encoding for XML output*  - 在此版本之前，如果在端点中设置了编码属性，但流中存在消息转换器（即DataWeave），并放置在SAP组件之前，{{2} }，后者将应用于XML输出。这不是正确的行为。现在，如果编码属性在端点中定义，并且与系统的默认值不同，它将优先于之前配置的任何其他编码。

=== 已知问题

在热重新部署应用程序后（即修改`mule-config.xml`），* 目标提供程序引用会丢失



== 版本3.1.0  -  2017年3月10日

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5.x
| Anypoint Studio | 6.2
| Java | 7,8
| SAP Solution |  ECC 6.0或更高版本
|支持的模块| SAP CRM，SAP ERP，SAP SRM，SAP SCM以及与NetWeaver平台兼容的任何其他模块。
|===

=== 特点

*  *Enhanced IDoc Metadata*  - 为DataSense / DataWeave和XML模板添加了其他信息：
** 对于每个细分受众群，可选/必需的细分受众群以及允许的细分受众群数量（最小和最大出现次数）。例如：E1LFA1M [段，必需，最小。 1，最大。 1]。
** 对于控制记录中的每个段字段和每个字段，字段位置现在都存在。例如：TABNAM [char，10，pos。 1]
*  *Repository Cache Invalidation*  - 当客户修改SAP功能模块或BAPI的结构时，无论该更改是否已应用于SAP实例。重新部署调用FM或BAPI的应用程序也不会产生任何影响，因为存储库是通用的，并且由在同一Mule运行时中运行的所有应用程序共享。 JCo提供了从缓存中删除当前FM / BAPI信息的功能。但是，*this feature is transparent to the user*。在进行任何出站或入站呼叫之前触发处理高速缓存。

本版本中已修复=== 

*  *Incomplete disposal of JCo classloader when sharing JCo dependencies between several applications*  - 用户在共享JCo环境中执行测试连接，刷新元数据或功能/ IDoc搜索，`Destination XX could not be created: java.lang.RuntimeException: File XX.jcoDestination does not exist`或`Destination XX does not exist`异常被抛出。发生这种情况是因为JCo目标引用未正确从DestinationDataProvider注销。但是，在将JCo库安装在Mule应用程序的本地类路径中时存在*not*问题。
*  *Failure to send outbound IDoc of type ByteArrayInputStream*  - 以前，从版本3.0.0开始，当试图转换由ByteArrayInputStream构建的IDoc时，转换因`IllegalArgumentException`失败，因为有效内容是以NULL值传递的。现在，问题得到解决，转换正确执行。

=== 已知问题

在热重新部署应用程序后（即修改`mule-config.xml`），* 目标提供程序引用会丢失


== 版本3.0.1  -  2016年12月2日

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5.x或更高版本
| Anypoint Studio | 5.x及更高版本
| Java | 7,8
| SAP Solution |  ECC 6.0或更高版本
|支持的模块| SAP CRM，SAP ERP，SAP SRM，SAP SCM以及与NetWeaver平台兼容的任何其他模块。
|===

=== 特点

* 针对IDoc的增强型DataSense  - 对于每个IDoc字段，附加信息都会显示为UI标签的一部分：数据类型，其长度和说明。

本版本中已修复=== 

*  *XML External Entities (XXE) vulnerability*  - 默认情况下，XML解析器配置较弱，因此在应用程序解析XML输入时容易受到XML外部实体攻击（例如披露机密数据，拒绝服务，服务器端请求伪造） 。为了防止XXE，DTD（外部实体）已在连接器使用的所有XML解析器中完全禁用。
*  *Metadata retrieval results in timeout*  - 这是在3.0.0版中显示的用于增强DataSense的附加信息的结果。实现已经改进，超时不再被触发。但是，元数据生成需要比以前的版本更长一些。
+
注意：由于元数据检索超时修复，DataSense UI中的“输入”和“输出”选项卡显示相同的信息（导入，导出，表格等）。使用DataWeave时，请确保您选择正确的Input / Ouptut参数。
+
*  *IDoc attributes "BEGIN" and "SEGMENT" not displayed in DataSense*  - 版本3.0.0中引入的回归问题。现在DataSense UI和DataWeave都正确显示这些属性，这些属性是正确构建给定IDoc的XML所需的属性。
+
注：DataSense将显示不需要的字段，例如：@begin和@segment。这是处理XML数据时的DS默认行为。使用DataWeave绑定数据时跳过这些。
*  `Redundant XSD attribute names`  - 为了提高可读性，已将`sap`前缀从XSD / XML模板中移除。属性`sapOptional`，`sapType`，`sapLength`和`sapDescription`已重命名为`optional`。 `dataType`，`length`和`description`。
*  *Parameters of type XSTRING are passed as String*  -  XSTRING表示ABAP中的一个字节数组。此数据类型未由连接器处理。该值未经任何转换就通过了。在此版本中，XSTRING参数作为Base64字符串接收（用户负责对其进行编码）并转换为字节数组。
*  *Connector hangs when application is redeployed*  - 当部署在*Mule EE Standalone*发行版中使用*Inbound endpoint*的应用程序时发生。当解除部署应用程序并执行第二次重新部署尝试时，Mule运行时会卡住，并且无法完全部署它（日志将以_New应用程序'my-sap-app'_而不是_Started应用程序'结尾'my- SAP-app'_）。作为*workaround*，`operationTimeout`的默认值已从*0 (zero)*更改--Mule会永久阻止，直到执行*30 (thirty) seconds*的JCo服务器操作。对于连接器的*previous versions*，默认值为0时，解决方法是*explicitly declare* `operationTimeout`的值大于0，与以下示例类似：
```XML
<sap:inbound-endpoint connector-ref="SAP" operationTimeout="5" type="idoc" ... />
```

=== 已知问题

* 虽然连接器在重新部署应用程序时挂起，但在上一节中已提供*workaround*。根本问题依然存在，并将在未来的版本中解决。
在热重新部署应用程序后（即修改`mule-config.xml`），* 目标提供程序引用会丢失

== 版本3.0.0  -  2016年5月17日

SAP连接器3.0.0版已发布并与Anypoint Studio 6.0.0打包在一起。

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5.x或更高版本
| Anypoint Studio | 5.x及更高版本
| Java | 7,8
| SAP Solution |  ECC 6.0或更高版本
|支持的模块| SAP CRM，SAP ERP，SAP SRM，SAP SCM以及与NetWeaver平台兼容的任何其他模块。
|===

=== 特点

* 支持使用MEL定义SAP JCo客户端扩展属性。
*  SAP入站端点生成的元数据现在由输入和输出组织。
* 增强型数据感知，显示更多信息：
** 对于函数和BAPI，现在可以识别表和结构，可选和必填字段，与其关联的“真实”数据类型（如Char，Number），它们的长度和描述。对于IDoc，分段也有明确的标签。

本版本中已修复=== 

* 对*XML Version 1*的支持对于函数/ BAPI是*removed*。这意味着属性`xmlVersion`不推荐使用，并且V1的模板不再可以导出。
* 出站请求的连接池在从连接器全局配置配置时不起作用，因为它缺少`jcoExpirationTime`属性，需要`jcoPeakLimit`和`jcoPoolCapacity`来建立连接池。
** 设置为"0"以上的值时，连接器应支持连接池。

=== 已知问题

在热重新部署应用程序（即修改mule-config.xml）后，* 目标提供程序引用会丢失。

== 版本2.2.8  -  2016年1月28日

=== 兼容性

MuleSoft Enterprise Java Connector for SAP连接器与以下产品兼容：

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5.x或更高版本
| Anypoint Studio | 5.x
| {的Java {1}} 7
| SAP R / 3 |版本3.1或更高版本
| SAP ERP | 6.0 EhP 7（SAP_APPL 607）或更高版本
|===

=== 特点

* 交易ID（TID）已被添加为Mule消息的属性。因此，在发送或接收IDoc时，用户将能够在SAP（`INBOUND_IDOCS_FOR_TID`和`OUTBOUND_IDOCS_FOR_TID`）上调用启用RFC的功能模块来检索IDoc编号。

本版本中已修复=== 

*  Java的UTF-8编码没有识别出初始字符BOM（字节顺序标记）。

*  DataSense for BAPI名称中包含斜杠（"/"）的元数据检索，例如"/DSD/ME_GETLIST_TR"已修复。

=== 已知问题

在热重新部署应用程序（即修改mule-config.xml）后，* 目标提供程序引用会丢失。

== 版本2.2.7  -  2015年7月1日

=== 兼容性

MuleSoft Enterprise Java Connector for SAP连接器与以下产品兼容：

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5.x或更高版本
| Anypoint Studio | 5.x
| {的Java {1}} 7
| SAP R / 3 |版本3.1或更高版本
| SAP ERP | 6.0 EhP 7（SAP_APPL 607）或更高版本
|===

=== 特点

* 无

本版本中已修复=== 

* 与Anypoint Studio 5.2的兼容性问题：在进行BAPI调用或发送IDoc时，SAP出站端点无法分析使用DataWeave Message Transformer构建的XML输入。

{2} XML定义记录类型时，XML版本2解析器显示混淆错误消息。

*  "MINIMAL"元数据模式现在为表生成示例行。

=== 已知问题

在热重新部署应用程序（即修改mule-config.xml）后，* 目标提供程序引用会丢失。

== 版本2.2.6  -  2015年6月17日

=== 兼容性

MuleSoft Enterprise Java Connector for SAP连接器与以下产品兼容：

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5.x或更高版本
| Anypoint Studio | 5.x
| {的Java {1}} 7
| SAP R / 3 |版本3.1或更高版本
| SAP ERP | 6.0 EhP 7（SAP_APPL 607）或更高版本
|===

=== 特点

* 向公开网站添加了演示示例，可在 http://mulesoft.github.io/mule-sap-connector/[SAP连接器演示]处下载

* 支持所有连接参数（jcoAsHost，jcoUser，jcoLang，jcoClient，jcoPasswd和jcoSysnr）的扩展多租户支持，以便可以在运行时动态定义连接。这样，连接器现在可以用于Data Gateway中的真正多租户方案。

* 将有效负载的正确mimeType设置为由SAP传输创建的每条消息，以便与新的数据框架完全兼容。

本版本中已修复=== 

* 无法为SAP入站端点配置操作超时。

* 从Studio GUI删除后，XML定义不会从配置文件中删除。

* 使用可缩放节点控制器（SNC）并且密码属性为空时的NullPointerException。 SNC连接模式使用数字证书来执行认证，因此不需要用户名和密码。

* 升级到SAPJCo 3.0.13和SAPidoc 3.0.12后IDoc转换为XML不良。

=== 已知问题

在热重新部署应用程序（即修改mule-config.xml）后，* 目标提供程序引用会丢失。

== 版本2.2.5  -  2014年11月28日

=== 兼容性
MuleSoft Enterprise Java Connector for SAP连接器与以下产品兼容：

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时| 3.5.x或更高版本
| Anypoint Studio | 5.x
| {的Java {1}} 7
| SAP R / 3 |版本3.1或更高版本
| SAP ERP | 6.0 EhP 7（SAP_APPL 607）或更高版本
|===

=== 特点

* 功能齐全的SAP编辑器 -  SAP编辑器提供了更多浏览SAP对象（IDoc和函数）的选项，显示所选SAP对象元数据（XML模板和/或XSD）的完整详细信息，并将数据导出到所需目录。无论何时出现以下任何更改，DataSense也得到了改进：SAP对象，类型（IDoc / Function），输出XMl，XML版本。

* 支持IDoc扩展 - 现在可以为自定义IDoc生成元数据结构。

* 对XML版本2的支持 - 它被设置为默认的XML版本来配置BAPI请求。

* 改进的DataSense元数据发现 - 针对SAP对象，类型（IDoc /功能），输出XML和XML版本。它还提供了更好的故障消息覆盖范围。

本版本中已修复=== 

* 对IDR的入站端点支持不适用于IDOC。

* 尝试从XML转换为JCoFunction时，无法分析嵌套的BAPI结构。

* 使用XML版本2解析具有空表的JCo响应时，会在其中附加一个空行。

* 未能将BAPI结果转换为XML。

* 对象查找程序不会返回入站IDoc，只能出站。

*  XML解析器无法处理名称中带有斜杠（/）字符的IDoc或BAPI。

* 无法处理具有无名称字段的BAPI表。

* 入站端点在某些Mule群集配置中失败。

*  JCo库会生成类加载器泄漏（仅当JCo依赖项和SAP连接器库位于应用程序库目录中且后者被重新部署时）。

=== 已知问题

* 无法为SAP入站端点配置操作超时。

在热重新部署应用程序（如修改mule-config.xml）后，* 目标提供程序引用会丢失。

== 另请参阅

*  https://forums.mulesoft.com [MuleSoft论坛]。
*  https://support.mulesoft.com [联系MuleSoft支持]。
