=  SuccessFactors连接器发行说明
:keywords: release notes, connector, sap, successfactors

_选择_

*Connector Guide:* link:/mule-user-guide/v/3.8/successfactors-connector[SuccessFactors连接器]

用于SuccessFactors的Anypoint Connector提供对使用SuccessFactors公开的SFAPI API查询，创建，更新和删除实体的全面支持。有关该产品的更多信息，请访问 link:https://help.sap.com/cloud4hr[SuccessFactors HCM Suite网站]。


== 版本2.2.0  -  2017年12月22日

=== 版本2.2.0兼容性

[%header%autowidth]
|===
| {软件{1}}版本
| Mule运行时 | 3.7
| SuccessFactors API  |  SFAPI（SOAP API）
|===

=== 版本2.2.0功能

* 自定义超时 - 连接超时和接收超时现在包含在要设置的可选配置属性中。
* 不安全的查询分页 - 当获取大量数据（记录）时，默认的分页实现可能会出现错误。为了克服这个限制，可以通过将标志`Use unsafe query pagination`设置为true来使用新的分页选项。这种类型的分页可以处理大量的记录，但是如果在查询运行时数据发生更改，则可能返回不一致的结果。

本版本中已修复的=== 版本2.2.0

获取元数据时的*  NPE  - 在以前的版本中，在全局配置中选择“获取所有实体”选项时，测试连接和元数据计算都会导致NullPointerException。这也影响了查询操作的功能，使查询生成器显示一个空的实体列表。
{0}}增量查询 - 执行增量查询时，SuccessFactors有时会返回映射到空字符串的空`<previous/>`标记。在当前版本中，该标签不再是连接器响应的一部分。
* 分页超时 - 在之前的版本中，如果在执行分页查询时由于网络问题而导致连接超时，会话将会丢失，并且由于SuccessFactors方面的问题而无法恢复。解决方案是检查配置中的不安全查询分页框。此设置预计在执行查询时值不会发生更改。
在使用HTTP代理时，*  UnknownHostException  - 在某些情况下，当使用HTTP代理时，用户在应用程序启动时将获得UnknownHostException。这不再发生。

=== 版本2.2.0已知问题

由于API限制，为所有实体提取元数据是一个缓慢的过程。为了缩短等待时间，请确保未取消选中“取所有实体”复选框，并使用删除的实体名称列表填写实体列表。如果您需要组织中所有可用实体的列表来执行此操作，则可以使用列表实体操作来获取它。

== 版本2.1.0  -  2017年1月9日

=== 版本2.1.0兼容性

|===
|应用/服务|版本
| Mule运行时间 | 3.7或更高
| {的Java {1}} 7
|===

=== 版本2.1.0功能

* 支持复合员工API和增量传输 - 现在支持使用复合员工API进行查询。
*  HTTP代理配置 - 您现在可以将连接器配置为在拨打电话时使用HTTP代理。

=== 版本2.1.0在此版本中已修复

没有。

=== 版本2.1.0已知问题

由于API限制，为所有实体提取元数据是一个缓慢的过程。为了缩短等待时间，请确保未取消选中“取所有实体”复选框，并使用删除的实体名称列表填写实体列表。如果您需要组织中所有可用实体的列表来执行此操作，则可以使用列表实体操作来获取它。


== 版本2.0.0  -  2015年12月29日

SuccessFactors Connector版本2.0.0的发行说明伴随着 link:/mule-user-guide/v/3.8/successfactors-connector[SuccessFactors连接器指南]。

=== 版本2.0.0兼容性

SuccessFactors连接器兼容：

|===
|应用/服务|版本

| *Mule Runtime*  | 3.7.0或更高版本
| *Anypoint Studio*  | 5.3.1或更高版本
| *Java*  | 7
|===

=== 版本2.0.0功能

- 列出您公司实例中的所有实体。
- 获取实体元数据。
- 插入/更新/上拉/删除实体。
- 使用SFQL查询SuccessFactors平台（SuccessFactors查询语言）。
- 提交，列出并取消异步查询作业，获取它们的状态和结果。

=== 版本2.0.0已知问题

由于API限制，为所有实体提取元数据是一个缓慢的过程。为了缩短等待时间，请确保未取消选中“取所有实体”复选框，并使用删除的实体名称列表填写实体列表。如果您需要组织中所有可用实体的列表来执行此操作，则可以使用列表实体操作来获取它。

== 另请参阅

*  https://forums.mulesoft.com [MuleSoft论坛]
*  https://support.mulesoft.com [联系MuleSoft支持]
