=  Object Store v2常见问题
：imagesdir：./_images

==  OSv2在哪里可用？

亚太地区：东京（ap-northeast-1），新加坡（ap-southeast-1）和悉尼（ap-southeast-2）。
欧盟：法兰克福（欧盟中心1），爱尔兰（欧洲西部1）和伦敦（欧洲西部2）。
北美：加拿大中部（ca-central-1），弗吉尼亚北部（us-east-1）和俄勒冈（us-west-2）。
南美洲：圣保罗（sa-east-1）。

==  OSv2是否与worker保持相同的区域？

是。例如，如果您部署到新加坡地区，对象商店仍然存在于新加坡地区。

== 数据在OSv2中保存多久？

如果密钥中的数据没有变化，则为30天。默认值是14天。
生存时间（TTL）是每个对象存储应用程序。
如果未指定TTL，Object Store将应用程序的TTL设置为14天。您可以从中设置TTL
ObjectStore连接器的Entry Ttl字段或来自REST API。每次输入一个密钥的数据
更新，到期日期延长TTL值。
如果数据未更新，则在TTL持续时间后，数据将被删除。

== 可以在OSv2中保留的最大密钥数量是多少？

在OSv2中，每个应用程序的密钥数量没有限制。在对象存储v1中，限制为100,000个密钥，并尝试存储更多被拒绝。

==  OSv2 REST API门户在哪里？

该API可在https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Anypoint Platform Developer's门户网站。

==  Object Store连接器在哪里？

Anypoint Exchange为https://www.anypoint.mulesoft.com/exchange/org.mule.modules/mule-module-objectstore/[Mule 3对象存储连接器]和https：//www.anypoint.mulesoft提供资源.com / exchange / org.mule.connectors / mule-objectstore-connector / [Mule 4 Object Store connector]。在Mule 4中，OSv2是预装在Mule 4和Anypoint Studio 7中的核心连接器。注意：Mule 3 Object Store连接器写入一个键值对，而Mule 4 Object Store连接器写入一个键列表对。

== 我是否需要一个用于Object Store v2和Object Store v1的不同Object Store连接器？

Mule 3 Object Store连接器适用于OSv1和OSv2。 Mule 4 Object Store连接器仅适用于OSv2。

==  OSv2是否有费率限制？

免费账户的费率限制为每个应用程序每秒10次交易。购买Object Store SKU的高级客户没有费率限制;然而，优质客户可以获得的API请求数量受其订阅价值限制。如果免费帐户应用程序超出速率限制，则会生成429 HTTP状态代码。

==  OSv2可以在工作人员之间共享吗？

一个对象存储及其内容（键，值）可供所有定义的Mule应用程序的所有CloudHub工作人员访问，并因此拥有该对象存储。但是，其他Mule应用程序和它们执行的CloudHub工作人员无法访问此Object Store及其内容。如果需要，您可以使用REST API从一个应用程序读取并存储到另一个应用程序。

////
== 对象存储是否通过CloudHub工作人员复制缓存的数据？

存储在Object Store V1或V2中的数据位于可访问的单独服务中
到单个应用程序中的任何CloudHub工作人员，并在工作人员之间共享。数据
如果您设置了`objectStore-ref="_defaultUserObjectStore"`，则只会转到Object Store V2
在你的Mule XML流程中。如果未设置，Object Store引用会保留在内存中
单身工作者。

Mule 3示例XML流程：

[source,xml,linenums]
----
<objectstore:config name="ObjectStore__Connector" partition="mypartition"
 objectStore-ref="_defaultUserObjectStore" doc:name="ObjectStore: Connector"/>
----

////

==  OSv2是否可以在场所中使用？

否，但在本地运行的应用程序可以使用OSv2 REST API将数据存储在OSv2中并检索它。

==  OSv2数据如何得到保护？

Object Store v2使用TLS进行安全传输。静态数据使用符合FIPS 140-2标准的加密标准进行存储。

== 如何在Object Store中隐藏敏感数据？

我们建议您在将敏感数据写入Object Store之前对其进行加密。

== 对象是否存储缓存数据或为每个读写操作执行I / O操作？

对于每个读写操作，Object Store V2都会执行I / O操作。使用Object Store V2时，API调用被本地化为
与运行时管理器应用程序相同的数据中心。

== 另请参阅

*  https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/ [Anypoint Exchange Object Store V2]。
*  https://www.anypoint.mulesoft.com/exchange/org.mule.modules/mule-module-objectstore/ [Mule 3 Object Store Connector]。
*  https://www.anypoint.mulesoft.com/exchange/org.mule.connectors/mule-objectstore-connector/ [Mule 4 Object Store Connector]。
*  link:/object-store/[对象存储文档]。
*  https://forums.mulesoft.com [MuleSoft论坛]。
*  https://support.mulesoft.com [联系MuleSoft支持]。
