=  REST API：Object Store v2
:keywords: osv2, os2, object store, store, rest, apis

Anypoint Object Store v2（OSv2）提供了一个REST API，可让您获取和存储`key,list`值。

对象存储使用单个应用程序临时存储应用程序数据。
要验证访问权限，您需要应用程序的客户端ID和客户端密钥，即Object Store
显示在Anypoint Platform的运行时管理器中。

对象存储允许键/列表对象在存储中默认持续长达14天。
如果列表值更新，对象可以保留14天。
您可以使用REST API指定更长的生存时间（TTL）值长达30天。
请参阅 link:/object-store/osv2-faq#how-long-can-data-persist-in-osv2[数据在OSv2中可以持续多久？]。

您在每个GET操作中可以获得的最大密钥数量为25。

请参阅：<<To View the App Client ID and Secret>>

== 关于Object Store v2操作

ObjectStore连接器以键/值格式读取和写入;而OSv2 API读取和写入键/列表值。

*Note:*如果应用程序使用REST接口写入对象存储并使用
Mule 3对象存储连接器来自同一个键，读取只能检索元素0处的值
列表。因此，使用REST API时，只能使用API​​编写和阅读内容
来自Object Store。或者，您可以使用API​​仅写入索引0.此限制确实如此
不适用于Mule 4和Anypoint Studio对象存储连接器。

下表将Object Store REST API操作与Object Store连接器操作进行了比较：

[%header,cols="20a,50a,30a"]
|===
| OSv2 API  | OSv2 REST API操作 | ObjectStore连接器操作

| {POST {1}}

* 对象存储：
对象存储的** 秒TTL  - 默认情况下，TTL为1,209,600秒（14天）。最大TTL为2592,000秒（30天）。请参阅 link:/object-store/osv2-faq#how-long-can-data-persist-in-osv2[数据在OSv2中可以持续多久？]。
** 持久性属性。
** 每个应用程序或环境的使用限制，包括基于密钥或大小进行限制的选项以及如何实施它们。
* 键和列表（项目）值。

|商店
| {GET {1}}

* 获取密钥
* 获取物品
* 获取项目
* 获取所有项目
* 获取组织的地区

|包含+检索+检索所有键+检索并存储（检索部分）
| {PUT {1}}

* 将项目设置为字符串
* 将项目编号为
* 将项目设置为可确认的字符串
* 放置商店

|双商店*&#8224;* +商店
| {DELETE {1}}

* 删除对象存储
* 删除密钥
* 删除项目

|删除
|===

*&#8224;*对象存储连接器中的双存储操作包含两个存储键和值的操作，然后将值颠倒过来。双存储操作与两个OSv2 "Put item as String"调用的作用相同，以实现这些结果：

.  `objectStore.store(key, value);`
.  `objectStore.store(value, key);`

== 关于Object Store v2 API工作流程

在部署对象库应用程序之前，请登录到Anypoint Platform> Runtime Manager以减少允许的工作者数量，以便添加新的应用程序。

访问对象存储2 API的工作原理如下：

* 部署应用程序
* 访问REST API
* 查看应用程序客户端ID和密码

== 部署应用程序

. 登录Anypoint平台。
. 单击运行时管理器。
. 如果您有现有应用程序，请单击它并单击管理应用程序。
+
如果这是您的第一次使用，请在Anypoint Studio中创建一个应用程序。完成开发后，右键单击包资源管理器中的项目名称
单击Anypoint平台>部署到云。
+
. 在运行时管理器部署应用程序菜单中：
+
.. 如果应用程序名称具有红色X，请更改名称，以便在名称后面显示绿色复选标记。
+
您选择的应用程序名称将成为用户访问您的应用程序的名称。
例如，如果您命名您的应用程序mydemo，则用户可以访问您的应用程序
`+http://mydemo.cloudhub.io/+`。
+
.. 忽略部署目标和应用程序文件字段 -  Anypoint Studio
为您填写这些信息。
.. 如果需要，请从下拉列表中更改Mule Runtime版本字段。
.. 如果需要，更改工作人员大小字段。
.. 点击部署应用程序。

== 访问REST API

设置像Postman这样的应用程序来访问对象存储。
获取access_token值：

. 将对象存储访问URL配置为：+
`{{osBaseUrl}}/api/v1/organizations/:ORGANIZATION_ID/environments/:environmentId/stores/myTestStoreId/objects`
. 使用HTTP标头和正文配置应用程序以获取要存储或读取的值
对象存储。
. 将操作发送到对象存储API。

== 查看App客户端ID和密码

如果您是Anypoint Platform的组织管理员
帐户，您可以从Object Store菜单查看应用程序的客户端ID和客户端密钥。

客户端ID和密钥需要对用于Object Store v2 REST API的应用程序进行身份验证。

. 登录到Anypoint Platform> Runtime Manager。
. 单击具有对象存储访问权限的应用程序，然后单击管理应用程序。该应用程序可以运行或取消部署。
. 如果应用程序尚未与Object Store V2关联，请单击该复选框并应用更改。
. 单击左侧导航区域中的“对象存储”菜单，然后单击“显示客户端凭据”。
. 单击“复制到剪贴板”图标，然后将客户端ID或秘密值粘贴到用于验证REST API的curl应用程序中。

== 查看承载令牌

在获得应用程序的客户端ID和密钥后，可以使用curl命令获取承载ID：

[source,bash,linenums]
----
curl -X POST \
  https://anypoint.mulesoft.com/accounts/oauth2/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=CLIENT_ID_VALUE&client_secret=CLIENT_SECRET_VALUE&grant_type=client_credentials'
----

将客户端ID和秘密替换为CLIENT_ID_VALUE和CLIENT_SECRET_VALUE。

输出显示为：

[source,json,linenums]
----
{
    "access_token": "42424242-5454-4242-5454-425442544254",
    "token_type": "bearer"
}
----

== 示例：检索对象库列表

以下过程假定您已经创建了一个应用程序并授予它访问Object Store v2的权限。

*Note:*按<<To View the App Client ID and Secret>>中所述获取客户端ID和秘密。

=== 获取环境和组织ID

在“访问管理”>“环境”中，单击应用程序所在的环境。复制
来自URL的环境ID，例如：

`+https://anypoint.mulesoft.com/accounts/#/cs/core/environments/edit/badd09f00f004242badd0942+`

在“访问管理”>“组织”中，复制组织标识。

=== 查看对象库的列表

提交此命令，将BEARER_ID替换为您的承载标识，将ORG_ID替换为您的组织标识，将ENV_ID替换为您的环境标识。

[source,xml,linenums]
----
curl -X GET \
> -H 'authorization: bearer BEARER_ID' \
> 'https://object-store-us-east-1.anypoint.mulesoft.com/api/v1/organizations/ORG_ID/environments/ENV_ID/stores'
----

输出值类似于：

[source,xml,linenums]
----
{"values":[{"storeId":"APP_demo-aug12_DEFAULT_USER_STORE","encrypted":true,"permanentOsFlag":false,
  "persistent":true,"defaultTtlSeconds":1209600,"defaultConfirmationTtlSeconds":600},
{"storeId":"APP_objectstore42_DEFAULT_USER_STORE","encrypted":false,"permanentOsFlag":false,
  "persistent":true,"defaultTtlSeconds":1209600,"defaultConfirmationTtlSeconds":600},
{"storeId":"APP_objectstore42_mypartition","encrypted":false,"permanentOsFlag":false,
  "persistent":true,"defaultTtlSeconds":1209600,"defaultConfirmationTtlSeconds":600}],"nextPageToken":null}
----

== 另请参阅

*  https://docs.mulesoft.com/connectors/object-store-connector [Mule 4对象存储连接器文档]
*  https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/public/apis/16510/versions/17620/files/root [Object Store  - api.raml]
*  https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/ [对象存储在任意点交换]。
*  link:/mule-user-guide/v/3.9/object-store-connector[对象存储连接器]。
