= 关于Pivotal Cloud Foundry的Anypoint平台
:keywords:pcf, pivotal cloud foundry,

Pivotal Cloud Foundry（PCF）组件的Anypoint平台是一个完全集成的解决方案，使组织能够在Pivotal Cloud Foundry提供的基础架构内设计，开发，部署，管理和操作API，连接应用程序和微服务。

用于PCF解决方案的Anypoint平台使您能够：

* 使用运行时管理器UI将Mule应用程序部署到PCF。
* 为PCF创建并部署Mule代理应用程序。代理应用程序拦截到非Mule应用程序的流量，使您能够应用策略并查看使用情况指标。

如果您正在为PCF使用Anypoint Platform并且您有多个PCF安装，则每个安装都必须链接到其自己的Anypoint Platform私有云版的单独安装。

如果您有多个空格的PCF安装，则必须在每个这些空格上运行*Space Configuration Tool*。如果您的Anypoint Platform组织使用多个环境，建议您为每个环境分配一个PCF空间。

PCF的Anypoint平台使用以下服务：

*  **Runtime Manager Service**：将PCF作为Anypoint Runtime Manager中的部署目标公开，并允许您将Mule应用程序部署到PCF以及其他部署目标。

*  **API Gateway Service**：使您能够创建和部署Mule API代理，该代理截取到在PCF上运行的非Mule应用程序的流量。这使您可以使用MuleSoft界面在API和PCF界面上应用策略来查看使用情况和策略指标。

*  **Anypoint Metering Service**：提供了一个API，使您可以查看部署到PCF的Mule应用程序的使用情况指标。您可以查看生产，预生产，分段和开发环境的使用情况指标。


== 安装和配置

有关为PCF安装和配置Anypoint Platform的过程，请参阅 link:pcf-workflow[工作流程：安装，配置和使用PCF的Anypoint平台]。

== 另请参阅

*  link:https://pivotal.io/platform[Pivotal Cloud Foundry]
*  link:/runtime-manager/deployment-strategies[部署策略]

