= 工作流程：安装，配置和使用PCF的Anypoint平台
:keywords: pcf, pivotal cloud foundry,

1.安装和配置Pivotal Cloud Foundry（PCF）
+
PCF为Anypoint Platform运行平面提供基础架构。有关正在安装的受支持PCF版本，请参阅安装文档：
+
*  link:http://docs.pivotal.io/pivotalcf/1-10/installing/index.html[PCF版本1.10]
*  link:http://docs.pivotal.io/pivotalcf/1-9/installing/index.html[PCF版本1.9]
*  link:http://docs.pivotal.io/pivotalcf/1-8/installing/index.html[PCF版本1.8]


1.安装Anypoint平台私有云版。
+
[WARNING]
要安装Anypoint平台私有云版，您必须联系您的MuleSoft客户成功代表以获取PCF特定许可证。在下一步中，需要此许可证才能安装PCF的Anypoint Platform Service Brokers。
+
Anypoint平台私有云版提供Anypoint平台管理平面的基础架构。有关更多信息，请参阅 link:/anypoint-private-cloud/v/1.5/index[Anypoint平台私有云版]：
+

1.为PCF磁贴安装Anypoint Platform Service Brokers。
+
请参阅 link:https://docs.pivotal.io/partners/mulesoft/index.html[用于PCF的Anypoint Platform Service Brokers]中的Pivotal文档。


1.安装Mule Runtime Buildpack
+
Mule Runtime buildpack是PCF Java buildpack的自定义版本，其中包含Mule Runtime以及支持库，服务和应用程序组件。请参阅 link:pcf-mule-runtime-buildpack[自定义Mule运行时BuildPack]。
+


1.运行PCF空间配置工具
+
PCF空间配置工具在PCF空间中安装Anypoint平台服务。您必须为PCF安装中的每个空间运行此工具。有关更多信息，请参阅 link:pcf-space-config[运行PCF空间配置工具]。


1.（可选）配置Hazelcast服务器
+
只有在应用策略或在集群PCF环境中扩展API时才需要Hazelcast服务器。有关更多信息，请参阅 link:pcf-mule-hazelcast[配置Mule Hazelcast服务器]。


1.将Mule应用程序部署到PCF。
+
安装和配置以前的组件后，可以使用以下方法将Mule应用程序部署到PCF安装中：
+
-  cf CLI
-  Anypoint运行时管理器

1.使用PCF Metering API访问使用数据。
+
在Mule应用程序运行后，您可以通过PCF Metering API监视PCF的使用情况。有关更多信息，请参阅 link:pcf-metering[使用PCF计量API访问使用数据]。
