= 运行PCF空间配置工具
:keywords: pcf, pivotal cloud foundry,

Pivotal Cloud Foundry（PCF）利用空间为开发，舞台和生产创建不同的环境。 Anypoint Platform还使用PCF空间来报告使用情况指标。

空间配置工具在PCF空间中创建以下服务：

*  API网关服务
* 运行时管理器服务
*  PCF计量服务

空间配置工具还创建了一个名为：`cloudmanager-<uuid>`的云安装程序应用程序。 `uuid`的值是PCF空间的唯一标识符。

空间配置工具的每个实例都链接到单独的PCF空间。如果您需要管理多个PCF空间，则必须在每个PCF空间中运行空间配置工具。

== 安装空间配置工具

要安装空间配置工具：

1.确保您已安装cf CLI。
1.下载空间配置工具 link:https://s3-us-west-1.amazonaws.com/anypoint-anywhere/1.5.2-GA/PCF+Installers/space_configuration_tool_1.5.2.zip[这里]。
1.打开`space_settings.yml`文件并编辑属性以反映您的环境。
1.在PCF环境中运行以下脚本：
+
----
python space_configuration_tool.py -i space_settings.yml
----

== 配置space_settings.yml文件

在`space_settings.yml`文件中，根据需要配置`pcf-services`和`pcf-cloud-params`属性。您必须为您正在配置的每个PCF空间创建并配置此文件的单独版本。

===  PCF-服务

该对象包含对PCF Anypoint Platform所需的每个服务的引用。 `space_settings.yml`中定义的默认值为：

[source, yaml, linenums]
----
pcf-services:
   - servicename: 'runtime-manager-service'
     serviceplan: 'runtime-manager-plan-v1'
     serviceinstancename: 'runtime-manager-service'
   - servicename: 'API-gateway-service-v1'
     serviceplan: 'API-gateway-plan-v1'
     serviceinstancename: 'api-gateway-service'
   - servicename: 'anypoint-metering-service'
     serviceplan: 'production'
     serviceinstancename: 'anypoint-metering-service'
----

确保在`space_settings.yml`中指定的值与安装PCF磁贴的Anypoint Platform Service Brokers时提供的值相对应。有关更多信息，请参阅 link:https://docs.pivotal.io/partners/mulesoft/configuring.html#services-config[配置运行时管理器和API网关服务代理]。

要查看安装在PCF空间中的服务，请运行以下命令：

----
cf marketplace
----

===  PCF-云-PARAMS

空间配置工具使用`pcf-cloud-params`中定义的属性在Anypoint Platform组织中注册空间。使用这些属性，它会直接将API调用到Anypoint运行时管理器。

在`space_settings.yml`中配置以下每个属性。您在此处定义的值对于您正在配置的每个PCF空间必须是唯一的。

[%header%autowidth.spread]
|===
| 属性 |说明
| Anypoint-org  |  Anypoint Platform组织的组织。有关更多信息，请参阅 link:https://docs.mulesoft.com/access-management/organization[组织]。
| anypoint-env  | 您的Anypoint平台安装的ID。
| anypoint-url  | 用于访问Anypoint平台安装的URI。
|内存 | 分配给`cloudmanager`应用程序的内存量。
|个实例 | 云安装程序服务的实例数量。
| COM_MULESOFT_CLOUD_MANAGER_PCF_APIURL  | 您的PCF Apps Manager实例的URL
| COM_MULESOFT_CLOUD_MANAGER_PCF_DOMAIN  | 您的PCF安装的域名
| COM_MULESOFT_CLOUD_MANAGER_PCF_USERNAME  | 您的PCF管理员用户名
| COM_MULESOFT_CLOUD_MANAGER_PCF_PASSWORD  | 您的PCF管理员密码
| COM_MULESOFT_CLOUD_MANAGER_PCF_SPACE  | 您正在运行空间配置工具的PCF空间的名称。
| COM_MULESOFT_CLOUD_MANAGER_PCF_ORG  | 您正在运行空间配置工具的PCF组织的名称。
| COM_MULESOFT_CLOUD_MANAGER_PCF_SKIPSSLVALIDATION  | 跳过PCF SSL验证。只有在PCF部署没有有效的HTTPS证书时才将其设置为false。
|用于访问Anypoint平台的masterorg `clientId`的COM_MULESOFT_ARMSERVICES_CLIENT_CLIENTID  |  。
用于访问Anypoint平台的| COM_MULESOFT_ARMSERVICES_CLIENT_CLIENTSECRET  |  masterorg `clientSecret`。
| {COM_MULESOFT_ARMSERVICES_CLIENT_BASEURL {1}}
连接到运行时管理器时，| COM_MULESOFT_ARMSERVICES_CLIENT_INSECURE  | 跳过SSL验证。只有当您的Anypoint Platform安装没有有效的HTTPS证书时，才将其设置为false。
| AUTHENTICATION_URL  |  Anypoint平台安装的身份验证URL。
| {AUTHENTICATION_INSECURE {1}}
|===
  


== 验证空间配置工具安装

运行空间配置工具后，验证是否创建了不同的组件。

1.查看PCF空间中安装的服务实例：
+
----
cf services
----
+
您应该看到列出的以下服务：
+
*  anypoint计量服务
*  API网关服务
* 运行经理服务

1.查看安装在空间中的应用程序列表：
+
----
cf apps
----
+
您应该看到类似于以下的应用程序：
+
----
cloud-manager-xxxxxxxxx-xxxxx-xxxxx-xxxx-c2c8882f6d65.mydomain.com
----
+
“uuid”是空间和Anypoint平台组织的独特价值。您不得删除`cloud-manager`，因为它被Anypoint Platform用于将应用程序部署到PCF空间。
