=  APIkit OData扩展参考
:keywords: apikit, apikit extension, odata, apikit odata reference

您使用RAML创建的实体数据模型（EDM）是构建OData API的基础。如本参考资料中所述，您可以使用EDM兼容的数据类型来创建文件，并将文件命名为odata.raml。在使用API​​kit OData扩展生成流程之后，您需要实现API端点。

== 实体数据模型

APIkit OData Extension基于odata.raml文件构建OData API，该文件描述使用支持的EDM类型的OData实体数据模型（EDM）。 odata.raml是一个RAML库。每个DataType表示一个EntityModel。例如：

----
#%RAML 1.0 Library
uses:
  odata: !include libraries/odata.raml
types:
  Employee:
    properties:
      id:
        type: integer
        (odata.key): bool
        (odata.nullable): bool
      name:
        type: string
----

使用注释（odata.key）在每个实体上注释至少一个属性。

以下注释属于每个属性：

----
(odata.precision): int
(odata.scale): int
----

使用可选的（odata.remote）注释来提供远程数据源中实体的名称。

----
types:
  Employee:
  (odata.remote): SAP_VBAK
    properties:
      ...
----

== 支持的EDM数据类型

APIkit OData Extension支持除Edm.Sbyte以外的所有EDM类型。在您的模型中，您将映射到以下受支持的EDM类型列表中显示的EDM类型的RAML类型：

===  Edm.String

字符串类型表示固定或可变长度的字符数据。

RAML `type: string`

===  Edm.Boolean

布尔数据类型用于表示二进制值逻辑的数学概念。这种类型没有适用的方面。

RAML `type: boolean`

===  Edm.Double

Double类型表示具有15位精度的浮点数，可以表示±2.23e -308至±1.79e +308范围内的值。

RAML `type: number`

===  Edm.Single

Single类型表示一个具有7位数精度的浮点数，可以表示大约范围为±1.18e -38到±3.40e +38的值

RAML `type: number`

RAML `format: float`

===  Edm.Binary

二进制数据类型用于表示固定或可变长度的二进制数据。

RAML `type: file`

===  Edm.DateTime

DateTime类型表示日期和时间，其值从12:00:00午夜，1753年1月1日至9999年12月31日11:59:59 P.M。

RAML `type: datetime-only`

===  Edm.Int32

Int32类型表示一个带符号的32位整数值。

RAML `type: integer`

===  Edm.Int64

Int64类型表示一个有符号的64位整数值。

RAML `type: integer`

RAML `format: int64`

===  Edm.Int16

Int16类型表示一个有符号的16位整数值。

RAML `type: integer`

RAML `format: int16`

===  Edm.Byte

字节类型表示一个无符号的8位整数值。

RAML `type: integer`

RAML `format: int8`

===  Edm.Decimal

Decimal类型表示具有固定精度和比例的数值。可以使用可选的精度和比例属性来指定所需的精度和比例。这种类型可以描述范围从负数10 ^ 255 + 1到正数10 ^ 255 -1的数值。

RAML `type: number`

RAML `(odata.precision): 3`

RAML `(odata.scale): 3`

===  Edm.Guid

此 link:https://www.ietf.org/rfc/rfc4122.txt[RFC4122]中指定的Guid类型表示一个16字节（128位）的唯一标识符值。

RAML `type: string`

RAML `(odata.type): guid`

===  Edm.Time

时间类型表示一天中的时间，其值范围从0：00：00.x到23：59：59.y，其中x和y取决于精度。

RAML `type: time-only`

===  Edm.DateTimeOffset

DateTimeOffset类型表示日期和时间，以距GMT格林尼治标准偏移量为单位，其值为从1753年1月1日午夜12:00:00至1999年12月9日11:59:59 A.D.

RAML `type: datetime`





