= 部署项目

在Studio中，您准备用于自动发现的API。您需要设置多个自动发现全局元素，其中一个用于您要指示请求的每个流。在自动发现全局配置中，您可以选择一个包含项目中流程名称的下拉列表。

最后，您将该项目作为Mule应用程序运行。 Studio将流作为单独的API部署到Anypoint Platform，并使用API​​ Manager注册API。注册API后，您可以应用策略。

*To deploy an APIkit project to Anypoint Platform*：

. 在Studio中，选择Anypoint Studio>首选项> Anypoint Studio> API的Anypoint Platform，然后输入您的客户端ID和客户端密钥。
. 在全局元素对话框中，通过输入全局元素的设置来配置自动发现，如下所示：
+
*  API名称：自动售货机
+
*  API版本：1.0开发
+
* 流名称：api-main
+
. 为第二个全局元素输入自动发现设置，如下所示：
+
*  API名称：test-policy
+
*  API版本：1.0开发
+
* 流名称：apiFlow
+
. 在Project Explorer中，右键单击APIkit项目名称，然后选择Run As> Mule Application。
+
Studio连接API平台中的API Manager。 Studio控制台表明该项目已部署：
+
----
INFO  2016-08-20 12:54:28,564 [main] com.mulesoft.module.client.autodiscovery.AutoDiscoveryDeploymentListener: Successfully created API named vending with version 1.0development
INFO  2016-08-20 12:54:28,774 [main] com.mulesoft.module.client.autodiscovery.
...
AutoDiscoveryDeploymentListener: Successfully registered source http://192.168.1.127:8081/remote-vending/test-policy to API test-policy with version 1.0development
...
----
+
. 登录到Anypoint Platform，或者如果您已经登录，请刷新浏览器。
. 转到API管理器。
+
自动售货和测试策略API出现在API Manager中。

使用实现URI，您现在可以使用API​​控制台模拟对API的调用。例如：

`+http://192.168.127:8081/console+`

您也可以将策略应用于API。

