= 实现OData示例的端点

使用Studio，您可以实现API端点，如`get:/customers:config`和`get:/orders:config`流程。流的输出必须采用JSON格式。有关更多信息，请参阅 link:/apikit/v/3.x/creating-an-odata-api-with-apikit#odata-mysql-example[完整功能的例子]。

== 为GET声明输入变量

. 为APIkit OData Service入站属性声明一个变量，该变量包含字符串列表中的实体字段（List <String>）。例如：
+
`%var entityFields = inboundProperties['odata.fields']`
+
. 为过滤到“http.query.params”的APIkit OData Service入站属性声明一个变量。例如：
+
`%var filters = inboundProperties['http.query.params']`
+
. 为包含实体键的APIkit Odata Service入站属性声明一个变量。例如：
+
`%var keys = inboundProperties['odata.keyNames']`
+
. 为包含表名称的APIkit Odata Service入站属性声明一个变量。例如：
+
`var remoteEntityName = inboundProperties['odata.remoteEntityName']`

== 为POST声明输入变量

. 为包含实体名称的APIkit Odata Service入站属性声明一个变量：
+ 
`%var remoteEntityName = inboundProperties['odata.remoteEntityName']`
+
. 声明一个变量来将你的有效载荷转换成如下形式：{myKey1：'myValue1'，myKey2：'myValue2'}。
+
----
%var valuesFromPayload = {
  keys: payload pluck $$,
  values: payload pluck "'$'"
}
----
+
. 声明列和值变量，并使用joinBy将您的键和值转换为逗号分隔值（CSV）。例如：
+
----
%var columns = ( (valuesFromPayload.keys map "`$`" ) joinBy ", ") // myKey1, myKey2
%var values = (valuesFromPayload.values joinBy ", ") // 'myValue1', 'myValue2'
----

== 格式化输出

每个流的输出必须符合以下格式：
`{"entries": [{<entry1>},{<entry2>},{<entryN>}]}`



