= 使用GUI安装程序安装Anypoint私有云

本主题介绍如何运行Anypoint Platform私有云版的基于GUI的安装程序。此安装程序提供了一个向导，引导您完成配置运行Anypoint Platform私有云版所需的大部分基础架构的过程。它会自动安装Kubernetes并创建托管平台组件的多个Docker容器。

[WARNING]
====
在运行安装程序之前，请确保您的系统满足最低系统要求。
====

安装程序会自动验证磁盘空间，磁盘速度，网络速度和操作系统版本的要求。您必须在一个会话中运行安装程序而不会中断。重新启动安装程序可能会导致安装问题。


== 运行安装程序

. 从您的客户成功代表获取`anypoint-1.7.0-installer.tar.gz`档案。

. 解压缩gzip压缩文件：
+
----
tar xvf anypoint-1.7.0-installer.tar.gz
----

. 从解压缩存档的位置开始，运行以下命令：
+
----
./install
----
+

. 选择您要使用的IP地址并确认。
+
根据您的选择，安装程序将显示类似于以下内容的消息：
+
----
OPEN THIS IN BROWSER: https://{HOST}:61009/web/installer/new/gravitational.io/anypoint/{VERSION}?install_token={TOKEN}
----

. 在浏览器中打开此URL。
+
安装程序在内部IP上运行，您可以使用它从网络中访问。要从网络外部访问URL，您必须使用公有IP地址替换URL中的主机名。
+
启动安装向导后，执行以下步骤安装Anypoint Platform Private Cloud Edition：

. 输入您的Anypoint Platform许可证密钥，然后单击继续。
+
您必须从您的MuleSoft客户代表获取许可证密钥。申请新许可证后，安装人员可能需要一段时间才能识别许可证。

. 为集群部署输入一个名称。
+
这个名字应该是你的公司所独有的。例如：`anypoint.yourcompany`。您在此处提供的名称不会更改Anypoint Platform中的网络地址或组织名称。

. 选择一个提供商，然后点击继续。

. 使用滑块，选择要创建的服务器节点的数量。
+
支持以下配置：
+
	*  **1-node configuration**：安装在单个节点上运行的所有平台组件。此配置仅用于演示目的，并具有较低的硬件要求。它在开发或生产环境中不受支持。演示安装包含用于测试的自己的LDAP服务器。
	*  **3-node configuration**：安装并注册所有服务器为*General Purpose Nodes*。
	*  **6-node configuration**：安装并注册三个节点*App-only*和三个节点*Data Store*。
+
安装后，您可以使用Ops Center根据需要添加或删除节点。根据您选择的节点数量，安装程序将显示一个或多个`curl`命令。

. 从安装中每个节点的命令行运行'curl'命令。
+
如果您正在运行3节点配置，则必须在环境中的每台服务器上运行相同的命令。如果您正在运行6节点配置，则必须在应用程序和数据节点上运行不同的`curl`命令。
+
您必须具有管理员权限才能运行此命令。该命令应具有以下结构，但取决于所选的安装风格和节点的类型：
+
----
curl -s --tlsv1.2 --insecure "https://{HOST}:443/t/{TOKEN}/node" | sudo bash
----
+
在节点上运行`curl`命令后，节点将出现在安装程序UI中。

. 单击验证，确保每台服务器满足最低磁盘和系统要求。
+
这可能需要几分钟才能完成。如果系统符合所有要求，安装程序将显示一个绿色复选标记。

. 从下拉列表中选择一个IP地址。
+
该IP地址用于在集群内进行通信。

. 从下拉列表中选择一个Docker设计，或手动指定您自己的路径。确保在每个节点上，两个设备都配置了足够的空间。
+
这是Docker用于卷管理的设备。

. 输入存储Anypoint平台数据的位置。
+
这是数据库和对象存储的位置。默认情况下，此位置是`/var/lib/data`。您必须确保您指定的位置具有足够的磁盘空间。

. 在所有节点可见并配置完毕后，单击开始安装。
+
安装程序通过几个不同的阶段。等待这个过程完成。

. 输入关于贵组织和Anypoint Platform管理员的以下信息：
+
* 组织名称
* 管理员电子邮件
* 管理员用户名
* 管理员密码
+
平台用户登录到属于您在此提供的组织名称或其中的业务组的帐户。


