= 工作流程：验证物理服务器的先决条件

本主题描述验证您的环境是否满足在物理服务器上安装Anypoint Platform Private Cloud Edition的最低系统要求的工作流程。

. 请联系您的客户成功代表获取Anypoint Platform私有云版的产品许可证。

.  link:/anypoint-private-cloud/v/1.7/prereq-hardware[关于Anypoint私有云的硬件和设备要求]
+
查看Anypoint Platform私有云版的最低硬件和设备要求。
+
[警告]
如果您的系统不符合所有最低系统要求，则无法安装Anypoint Platform私有云版。

.  link:/anypoint-private-cloud/v/1.7/prereq-network[关于私有云版网络要求]
+
查看运行Anypoint Platform私有云版所需的最低网络要求。

.  link:/anypoint-private-cloud/v/1.7/prereq-verify-disk[验证硬件要求]
+
执行这些过程来验证您的磁盘和网络性能是否满足最低要求。

.  link:/anypoint-private-cloud/v/1.7/prereq-gravity-check[验证物理服务器上Anypoint私有云的系统要求]
+
运行`gravity check`脚本以验证您的系统是否满足安装Anypoint Platform Private Cloud Edition所需的最低要求。

. （可选）创建一个虚拟机
+
如果要在物理服务器上安装Anypoint Private Cloud，则必须安装并配置虚拟机。仅支持运行RHEL的VMware和Bare Metal。有关更多信息，请参阅供应商的文档。

.  link:./prereq-firewalld-forwarding[使用firewalld时启用转发]
+
如果您使用firewalld运行Red Hat Enterprise Linux（RHEL）7.3，则必须启用转发。

. 确保所有服务器上的时钟都已同步。不同步的时钟可能会导致平台通信问题。


安装并验证这些先决条件后，即可开始安装。请参阅 link:install-workflow[关于Anypoint平台私有云版安装]。
