= 迁移到Anypoint平台私有云版本1.7.1

本主题提供有关将Anypoint Platform私有云版升级到最新版本的信息。该版本支持以下迁移路径：

[%header%autowidth.spread]
|===
| 基础版本 | 中级版本 | 目标版本 | 评论
|  1.7.0  | 不适用 |  1.7.1  | 支持直接迁移
|  1.6.1  | 不适用 |  1.7.1  | 支持直接迁移
|  1.6.0  | 不适用 |  1.7.1  | 支持直接迁移
|  1.5.2  |  1.6.1  |  1.7.1  | 必须先升级到1.6.1
|  1.5.1  |  1.6.1  |  1.7.1  | 必须先升级到1.6.1
|===

有关升级到版本1.6.1的信息，请参阅 link:/anypoint-private-cloud/v/1.6/upgrade[关于迁移Anypoint平台私有云版]。

[WARNING]
在迁移过程中，每更新一个节点都会有一些停机时间。


== 先决条件

在迁移之前，请确保您已经完成并满足以下先决条件：

* 按照 link:backup-and-disaster-recovery[关于备份和恢复]中所述执行系统备份。

* 确保您的环境满足 link:/anypoint-private-cloud/v/1.7/prereq-workflow[工作流程：安装和验证物理服务器的先决条件]中描述的所有系统和网络要求

* 启用TCP端口`53`，`3011`，`3012`节点以允许与数据库群集通信。

* 确保您有权在启动迁移工具的节点上运行`sudo`命令。

* 确保`kubectl`命令在您执行迁移的节点中可用。要验证是否安装了`kubectl`，请运行以下命令：
+
----
$ sudo gravity enter
$ kubectl
----

== 升级Anypoint私有云

. 从您的客户成功代表处获取安装程序的链接。

. 使用`ssh`登录到群集的主节点。
+
在3节点环境中，所有节点都是主节点。要在6节点环境中查找主节点，请运行以下命令：
+
----
kubectl get node --show-labels | grep gravitational.io/k8s-role=master
----
+
通过从主节点执行这些过程，升级脚本能够更新整个平台。

. 解压缩应用程序存档。
+
----
tar -xvf anypoint-1.7.1-installer.tar.gz
----

. 转到`anypoint-1.7.1`目录，然后运行上传脚本。
+
----
cd anypoint-1.7.0
sudo ./upgrade
----
+
此命令将平台更新为当前版本并重新启动群集中的每个群集。
+
----
$ sudo ./upgrade
-> initializing upload
-> uploading update package
importing anypoint:1.7.1
synchronizing anypoint:1.7.1 with Docker registry at 172.31.0.26:5000
synchronizing anypoint:1.7.1 with Docker registry at 172.31.0.45:5000
synchronizing anypoint:1.7.1 with Docker registry at 172.31.0.5:5000
anypoint:1.7.0 has been uploaded
updating anypoint from 1.6.1 to 1.7.1
update operation (bae00abf-98a7-4ca9-b0d2-06f3bfea3024) has been started
the cluster is updating in background
----
+
根据您的网络配置，此命令可能需要一段时间才能完成。等到命令完成后再继续下一步。

. 通过执行以下操作之一来验证迁移是否成功：
+
* 从执行升级的节点运行以下命令：
+
----
$ sudo gravity enter
$ kubectl get pods
----
+
* 通过以下URL登录Ops Center：
+
----
https://{platform-host}:9500
----

