= 安排测试和监测

此过程介绍如何使用默认计划以及如何使用cron作业更改计划，从而在Anypoint Platform中计划，运行和监视API测试。当您执行bat login命令时，BAT默认部署在Anypoint Platform的生产环境中。部署BAT后，您可以执行`bat schedule <options>`命令。默认情况下，如果在命令中未包含可选的cron表达式，则测试每15分钟运行一次。此过程的最后一步将默认设置更改为使用每天运行一次测试一个月的cron表达式。

运行该命令后，BAT在Anypoint Platform中创建一个监视器。监视器收集有关计划执行测试的信息。要获得此信息，您需要按链接主题中所述设置第三方报告工具。

. 使用BAT登录Anypoint平台。例如：
+
`bat login --username=<value> --password=<value>`
+
. 使用默认值每15分钟创建一个计划并监视测试。提供一个任意的端点URL，并通过使用--init-folder存储调度信息来指定当前目录。例如：
+
`+bat schedule endpoint http://www.example.com --init-folder+`
+
日程表使用默认的登录配置文件发布到Exchange。
+
Mac OSX中的输出如下所示：
+
----
BAT Version: 1.0.51
#  File: ./tests/step.0.dwl

    api-mon
      ✓ GET http://apimon.cloudhub.io/users (1316.85ms)
        ✓ 200 must equal 200
#  File: ./tests/step.1.dwl
...
            ✓ 10 must equal 10
#  Reporter: bat/Reporters/JSON.dwl >> /var/folders/w5/_cc_5_z12pq3qnymf3f0zh840000gq/T/bat_report_20180226111256.json
#  Reporter: bat/Reporters/HTML.dwl >> /var/folders/w5/_cc_5_z12pq3qnymf3f0zh840000gq/T/bat_report_20180226111256.html
#Creating artifact...
  + exchange.json
  + .DS_Store
  + tests/step.0.dwl
  + tests/step.1.dwl
  + main.dwl
  + bat.yaml
# Creating artifact...OK
# Uploading 88f362bd-2092-4dbf-b9f2-db5624d7b4ab:www.telhill.com-ncQRvDwc:0.0.1
# Version 0.0.1 published
scheduleId: 99c24a04-b82b-4366-b02b-4682fa405ead
----
+
. 转到输出中列出的其中一个本地记者的路径，以查看有关执行测试的信息。例如，在Mac OSX上，请转到`/var/folders/w5/_cc_5_z12pq3qnymf3f0zh840000gq/T/bat_report_20180226111256.html`。
. 转到Exchange并查看以`bat schedule endpoint`命令提供的任意网址`+http://www.example.com+`之后的资产。
. 列出测试时间表。
+
`bat schedule list [--profile=<value>]`
+
. 安排测试以使用cron表达式重复运行。例如，每天中午12点运行测试一个月：
+
`bat schedule create --cron="0 0 12 1/1 * ? *"`

接下来，配置并查看测试报告。

== 另请参阅

*  link:/api-functional-monitoring/bat-reporting-task[配置和查看测试报告]
*  link:/api-functional-monitoring/bat-command-reference[BAT命令参考]
