=  BAT CLI参考

BAT命令行界面允许您在本地运行测试并安排监视器进行连续的API测试。您可以使用CLI-xAPI在云中安排测试。 BAT CLI与Anypoint Platform集成。

此参考涵盖了您可以与*bat*命令一起使用的语法和键选项。使用*bat*命令，您可以调试和运行测试，获得用于计划测试的凭据，计划测试，列出测试计划并执行其他操作。

== 蝙蝠命令

*bat*命令提供了API功能监视命令行界面。

=== 语法

`bat [<file> ... | <option> ...]`

`bat [login --username=<value> [--profile=<value>] --host=<value>]`

该选项显示密码的交互式命令。

`password for user [username]: <password>`

或者，您可以在登录命令中包含选项`--password=<password>`。

哪里：

* 文件是路径和文件名的相对路径。该文件必须具有以下基本名称之一和以下扩展名之一：
+
** 基本文件名：main，bat
** 个扩展名：.yaml或.yml
+
当您执行没有任何参数的bat时，BAT会读取当前目录中的YAML并运行指定的测试。
您可以创建`config`文件夹，并在`config`中为环境添加不同的配置文件。

----
test-project
├── bat.yaml
├── tests
└── config
    ├── default
    ├── devx
    ├── qax
    ├── stgx
    └── prod
----

== 命令行选项

*  `bat ~/path/to/folder/` +
执行所需的文件夹。 BAT搜索并执行`bat.yaml`和`main.dwl`个文件。
*  `bat ./folder/file.dwl` +
执行所需的文件。该项目的根目录是当前文件夹。
该项目的根目录用于解析导入，并加载库和文件。
**  `--config=<name>`
+
选择配置文件（来自`config`文件夹）并将结果注册为全局变量。
+
**  `--version`
+
打印到标准输出安装的BAT和包装的版本号。如果未安装最新版本，则下载该版本。
+
**  `--bat-version=1.0.51`
+
使用指定的版本执行BAT。
+
**  `--update`
+
安装最新的BAT CLI。
+
**  `--validate`
+
验证文件或文件夹。也可以与`--config`一起验证特定的配置。
+
**  `get_token`
+
返回凭证文件中用于访问Anypoint Platform的令牌。要求您首先运行`bat login`以生成配置文件。
+
**  `worker register`
+
用机器名称生成一个帖子并创建一个虚拟目标。
+
**  `target ls list`
+
列出配置文件组织中的所有目标信息。
+
**  `schedule create [--cron="<expression>"]`
+
使用cron表达式创建一个调度程序并生成一个包含测试和所有文件的zip文件。默认情况下，如果未输入cron表达式，则测试计划每15分钟运行一次。
+
**  `schedule endpoint <arbitrary-URL> [--cron="<cron>"] [--name=<suiteName>] [--target=<targetId>] [--new-relic-license-key=<newRelicLicenseKey>] [--slack-webhook=<slackWebHook>] [--sumo-endpoint=<sumoEndpoint>] [--pager-duty-routing-key=<pagerDutyRoutingKey>] [--custom-report-url=<customReportUrl>] [--custom-report-headers=<header1,header2,...,headerN>] [--custom-report-transformation=<pathToDwlFile>][--init-folder]`
+
在使用任意网址的Exchange中创建监视器，例如`+http://example.com+`。或者，您可以添加命令来生成具有不同参数的bat.yaml。
+
***  `[--cron="<cron>"]`默认情况下，测试计划每15分钟运行一次。您可以使用cron表达式进行更改
+
+
***  `[--name="<suiteName>"]`设置套件的名称
+
+
***  `[--target="<targetId>"]`为监视器设置特定的目标
+
+
***  `[--new-relic-license-key="<newRelicLicenseKey>"]`将新的文物报告添加到bat.yaml。
+
+
***  `[--slack-webhook="<slackWebHook>"]`将松散报告添加到bat.yaml。
+
+
***  `[--sumo-endpoint="<sumoEndpoint>"]`将相扑报告添加到bat.yaml。
+
+
***  `[--pager-duty-routing-key="<pagerDutyRoutingKey>"]`将寻呼机值班报告添加到bat.yaml。
+
+
***  `[--custom-report-url="<customReportUrl>"] [--custom-report-headers="<header1,header2,...,headerN>"] | [--custom-report-transformation="<pathToDwlFile>"]`将自定义报告添加到bat.yaml文件，并可以选择添加转换文件。
+
+
***  `[--init-folder]`将生成的exchange.json，bat.yaml和main.dml存储在当前目录中。
+
**  `schedule ls list`
+
列出配置文件组织中的所有调度程序信息。
+
**  `schedule rm | remove <scheduleId>`
+
通过其ID删除时间表。
+
**  `--username=<value>`
+
Value是Anypoint Platform用户名。
+
**  `--password=<value>`
+
值是Anypoint Platform用户名的密码。

**  `--profile=<value>`
+
简介是：
+
*** 用于访问Anypoint Platform位置并保留BAT会话之间的登录信息的配置文件的名称。使用此选项无需在会话之间重新登录。可选的。
*** 用于调度端点的配置文件的名称，可以与您使用的BAT登录配置文件不同。默认情况下，BAT使用登录配置文件进行计划。可选的。
+
**  `--init-folder`
+
存储通过在当前目录中创建监视器生成的文件exchange.json和main.dwl。可选的。
**  `--init`
+
与设置基本项目文件夹的`bat init`命令相同。该文件夹包含以下文件：
+
----
bat.yaml
tests/
tests/HelloWorld.dwl
config/
config/default.dwl
config/prod.dwl
config/dev.dwl
----

==  BAT命令示例

* 从bat.yaml文件运行多个测试文件。
+
`bat bat.yaml`
+
* 运行一个文件。
+
`bat ./test/myFile.dwl`
* 确定安装的版本。
+
`bat --version`
+
如果您没有最新版本，输出示例如下：
+
----
Updating Version: You have an older BAT version.
The new version will be downloaded in /Users/<username>/.bat/bat-cli-1.0.51
Downloading version 1.0.51. Please wait`.......................
BAT Wrapper: 1.0.53
BAT Version: 1.0.51
----

== 另请参阅

*  link:/api-functional-monitoring/bat-schedule-test-task[安排测试]
