= 听取回复
:keywords: amqp, connector, publish, consume, request, reply
：TOC：
：TOC标题：

请求/回复是应用程序之间非常常见的模式，因此新的AMQP Connector提供了专门为此设计的操作，称为`publish-consume`。 `publish-consume`操作允许您将消息发布到任何交换机，然后等待不同目的地的回复。

使用此操作时，传出消息的replyTo属性将包含应用程序将等待响应的队列的ID。这个目的地可能是一个众所周知的目的地，或者它可能是一个临时队列，仅用于接收单个响应消息。

最后，操作的结果将是收到的消息作为响应，具有与调用`consume`操作完全相同的结构。

== 等待临时队列的回复

使用临时队列等待响应非常简单，只需配置发送的消息，操作就会自动等待临时队列中的响应：
[source, xml, linenums]
----
<amqp:publish-consume config-ref="config" exchangeName="targetExchange" maximumWait="20" maximumWaitUnit="SECONDS"/>
----

在此示例中，操作将`publish`消息的当前`payload`作为其*body*，并将消息的*replyTo property*配置为临时目标，将{{4 }}。
然后，它将自动尝试使用该临时队列的响应，直到消息被使用或达到`maximumWait`（在这种情况下，它将失败并出现`AMQP:TIMEOUT`错误）。

接收已知队列上的回复== 

在许多情况下，您不希望根据请求创建回复队列，而是使用众所周知的队列来回复。对于这种情况，您只需在外发消息中配置`reply-to`参数：
[source, xml, linenums]
----
<amqp:publish-consume config-ref="config" exchangeName="targetExchange">
    <amqp:message>
    		<amqp:properties reply-to="replyToQueue" />
    </amqp:message>
</amqp:publish-consume>
----

现在，该操作会将`publish`消息传递给`targetExchange`，其中`payload`为*body*，`replyTo` *property*为{{1} 6}}。
然后，它将自动尝试消费来自`replyToQueue`队列的响应，直到消息被消耗或达到`maximumWait`（在这种情况下，它将失败并出现`AMQP:TIMEOUT`错误）。

== 另请参阅

*  link:amqp-publish[发布消息]
