=  Anypoint MQ连接器
:keywords: mq, connector

_选择_

Anypoint MQ连接器使用Anypoint MQ云服务在云端或内部部署中为Mule应用程序提供发布 - 订阅消息。

Anypoint MQ支持广泛的消息传递用例：企业消息传递模式，微服务，物联网等之间的异步通信。 Anypoint MQ还有一个REST api，用于使用任何框架（如node.js，Java，Go和devops bash脚本）发布或使用消息。

== 先决条件

要使用此连接器，您应该熟悉Anypoint Studio，Anypoint连接器和Mule流程。 Anypoint MQ连接器是免费的，但连接到Anypoint Platform中的服务需要许可证。

*Note:*如果没有Anypoint MQ许可证，您无法完成本文档中的配置信息。联系MuleSoft销售获得试用许可。

=== 兼容性

[%header%autowidth.spread]
|===
| {软件{1}}版本
| Mule运行时 | 4.0.0及更高版本
| Anypoint Studio  | v7及更高版本
|===

== 安装此连接器

. 在Anypoint Studio中打开您的Mule项目。
. 将连接器添加为pom.xml文件中的依赖项：
+
[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>anypoint-mq-connector</artifactId>
  <version>2.0.0</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

== 使用Studio Visual Editor进行配置

. 在Studio中，单击文件>新建> Mule项目。
. 搜索"http"并将HTTP连接器拖到Studio画布上。单击HTTP连接器，然后单击连接器配置右侧的绿色加号。单击确定以接受默认设置。在HTTP属性窗口中，将路径设置为`/mq/{messageId}`。
. 搜索"mq"并将*Anypoint MQ*连接器拖到画布上。如果找不到此连接器，请返回
<<To Install This Connector>>并确保您安装了连接器。
. 单击连接器配置右侧的绿色加号。
. 在全局元素属性窗口中：
.. 指定您希望MQ队列和交易所驻留的区域的URL。
+
可能的值是：
+
** 美国东部（弗吉尼亚北部）：`+https://mq-us-east-1.anypoint.mulesoft.com/api/v1+`
** 美国西部（俄勒冈州）：`+https://mq-us-west-2.anypoint.mulesoft.com/api/v1+`
** 欧盟（爱尔兰）：`+https://mq-eu-west-1.anypoint.mulesoft.com/api/v1+`
** 亚太地区（新加坡）：`+https://mq-ap-southeast-1.anypoint.mulesoft.com/api/v1+`
** 亚太地区（悉尼）：`+https://mq-ap-southeast-2.anypoint.mulesoft.com/api/v1+`
+
FIFO队列可以驻留在美国东部，美国西部和欧盟爱尔兰。
+
.. 在Anypoint Platform中，单击MQ>客户端应用程序。如果需要，创建一个客户端应用
.. 将Anypoint平台> MQ>客户端应用程序>客户端应用程序ID值复制到Studio的客户端ID字段。
.. 将客户端应用程序>客户端密钥值复制到Studio的客户端密钥字段。您可以忽略其他设置来测试连接器。
.. 点击*OK*。
. 单击*Operation*字段并指定诸如发布或使用的操作。
. 如果使用发布或使用操作，请将*Destination*指定为您在Anypoint Platform中设置的队列或消息交换的名称。
. 对于发布操作，您可以将消息ID字段留空，或者如果要发布特定的消息标识，请指定消息标识。如果未设置消息标识，则MQ自动为发送到队列的每条消息生成唯一的消息标识。发布到FIFO队列时，如果指定了一个消息ID，并且消息ID在多个消息中相同，则具有相同消息ID的消息不会重新发送。

有关所有其他配置字段的列表，请参阅 link:/connectors/anypoint-mq-connector-reference[Anypoint MQ连接器参考]。

==  MQ模式和端点

如果您正在创建一个XML或独立应用程序，请将此依赖项添加到您的pom.xml文件中：

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>anypoint-mq-connector</artifactId>
  <version>2.0.0</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

*Note:*如果您使用Anypoint Studio创建应用程序，那么当您安装MQ连接器时，将依赖于MQ
在pom.xml文件中为你更新。

Gradle，EBT和Ivy的其他依赖项在https://www.anypoint.mulesoft.com/exchange/org.mule.tooling.messaging/mule-module-anypoint-mq-ee-studio/中的Anypoint Exchange中列出。 [Anypoint MQ连接器]资产。单击依赖片段获取完整列表。

终点：

`+http://www.mulesoft.org/schema/mule/anypoint-mq+`

==  XML和独立配置

有关XML字段的列表，请参阅 link:/connectors/anypoint-mq-connector-reference[Anypoint MQ连接器参考]。

==  Anypoint MQ XML示例

本节提供了以下主题：

*  <<Example 1: MQ and DataWeave>>
*  <<Example 2: MQ and Object Store>>

=== 示例1：MQ和DataWeave

以下示例说明了使用DataPoint的Anypoint MQ连接器进行转换
向JSON发送Mule消息：

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:dw="http://www.mulesoft.org/schema/mule/ee/dw"
	xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:spring="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/ee/dw http://www.mulesoft.org/schema/mule/ee/dw/current/dw.xsd
http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/anypoint-mq http://www.mulesoft.org/schema/mule/anypoint-mq/current/mule-anypoint-mq.xsd">
  <anypoint-mq:default-subscriber-config name="Anypoint_MQ_Configuration" doc:name="Anypoint MQ Configuration">
      <anypoint-mq:connection url="https://mq-us-east-1.anypoint.mulesoft.com/api/v1" clientId="<id>" clientSecret="<secret>"/>
  </anypoint-mq:default-subscriber-config>
<flow name="producerFlow">
  <poll doc:name="Poll">
    <dw:transform-message doc:name="Create Customer">
    <dw:set-payload><![CDATA[%dw 1.0
%output application/json
---
{
    "firstName" : "Joe",
    "lastName" : "Schmoe",
    "company" : "Acme, Inc"
}]]></dw:set-payload>
    </dw:transform-message>
  </poll>
        <anypoint-mq:publish config-ref="Anypoint_MQ_Configuration" destination="MyExchange" messageId="mq42" doc:name="Anypoint MQ">
            <anypoint-mq:body >#[payload]</anypoint-mq:body>
        </anypoint-mq:publish>
</flow>
</mule>
----

=== 示例2：MQ和Object Store

以下示例显示了使用Anypoint MQ连接器进行使用
来自对象商店的信息。

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq"
    xmlns:objectstore="http://www.mulesoft.org/schema/mule/objectstore"
    xmlns:dw="http://www.mulesoft.org/schema/mule/ee/dw"
    xmlns:http="http://www.mulesoft.org/schema/mule/http"
    xmlns:tracking="http://www.mulesoft.org/schema/mule/ee/tracking"
    xmlns="http://www.mulesoft.org/schema/mule/core"
    xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:spring="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/objectstore http://www.mulesoft.org/schema/mule/objectstore/current/mule-objectstore.xsd
http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/dw http://www.mulesoft.org/schema/mule/ee/dw/current/dw.xsd
http://www.mulesoft.org/schema/mule/ee/tracking http://www.mulesoft.org/schema/mule/ee/tracking/current/mule-tracking-ee.xsd
http://www.mulesoft.org/schema/mule/anypoint-mq http://www.mulesoft.org/schema/mule/anypoint-mq/current/mule-anypoint-mq.xsd">

    <objectstore:config name="ObjectStore_Configuration" partition="employees" doc:name="ObjectStore: Configuration"/>
    <http:listener-config name="HTTP_Listener_Configuration" host="0.0.0.0" port="8081" doc:name="HTTP Listener Configuration"/>
    <anypoint-mq:default-subscriber-config name="Anypoint_MQ_Configuration" doc:name="Anypoint MQ Configuration">
        <anypoint-mq:connection url="https://mq-us-east-1.anypoint.mulesoft.com/api/v1" clientId="<ID>" clientSecret="<SECRET>"/>
    </anypoint-mq:default-subscriber-config>
    <flow name="objectstore-store-flow">
        <http:listener config-ref="HTTP_Listener_Configuration" path="/store" doc:name="HTTP"/>
        <objectstore:store config-ref="ObjectStore_Configuration" key="#[message.inboundProperties.'http.query.params'.key]" value-ref="#[message.inboundProperties.'http.query.params'.value]" doc:name="ObjectStore"/>
        <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration" destination="MyDemoQueue" doc:name="Anypoint MQ"/>
        <set-payload value= "OK" doc:name="Set Payload"/>
    </flow>
    <flow name="objectstore-retrieve-employee-flow">
        <http:listener config-ref="HTTP_Listener_Configuration" path="/retrieve" doc:name="HTTP"/>
        <objectstore:retrieve config-ref="ObjectStore_Configuration" key="#[message.inboundProperties.'http.query.params'.key]" doc:name="Retrieve"/>
        <logger message="Value: #[payload]" level="INFO" doc:name="Log"/>
        <set-payload value="Value : #[payload]" doc:name="Show"/>
    </flow>
</mule>
----


== 另请参阅

*  link:/connectors/anypoint-mq-connector-reference[Anypoint MQ连接器参考]
*  https://www.anypoint.mulesoft.com/exchange/org.mule.tooling.messaging/mule-module-anypoint-mq-ee-studio/ [Anypoint MQ连接器]
