= 创建Java KeyStore和信任证书

在此过程中，您将生成公钥和私钥。您为包含私钥的KeyStore指定一个别名。接下来，只生成一个自签名证书。最后，您从证书颁发机构生成自签名证书和证书。大多数客户需要证书来验证公钥。使用TLS的HTTPS连接需要这些东西。

. 打开终端，然后在命令行上输入Java keytool命令以在KeyStore中创建密钥：
+
`keytool -genkey -alias serverkey -keyalg RSA -keystore httplistener.jks`
. 响应提示输入KeyStore的密码。以下输出显示示例响应：
+
* 输入密钥库密码：*mule123*
* 重新输入新密码：*mule123*
+
. 回应提示输入其他值。您可以输入任意值。以下输出显示示例响应：
+
* 你的名字和姓氏是什么？ [未知]：*max*
* 您组织单位的名称是什么？ [未知]：*MuleSoft*
* 贵组织的名称是什么？ [未知]：*MuleSoft Inc*
* 您的城市或地区的名称是什么？ [未知]：*San Francisco*
* 您的州或省的名称是什么？ [未知]：*CA*
* 这个单位的双字母国家代码是什么？ [未知]：*01*
+
. 为了响应以下提示，请输入*yes*。
+
是CN = kahn，OU = MuleSoft，O = MuleSoft公司，L =旧金山，ST = CA，C = 01是否正确？ [no]：*yes*
+
. 回应以下提示。例如，通过输入RETURN来使用相同的密码。
+
输入<serverkey>的密钥密码（如果与密钥存储密码相同，则返回）：
+
. 输入命令以导出验证公钥的自签名证书。
+
----
keytool -export -alias serverkey -keystore httplistener.jks -file server_cert.cer
----
+
. 响应提示输入您为与证书关联的KeyStore设置的密码。
+
输入密钥库密码：*mule123*
. 或者，不要仅导出自签名证书，而是使用单个命令同时生成来自证书颁发机构的证书和自签名证书：
+
----
keytool -genkeypair \
    -keystore httplistener.jks \
   -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown" \
   -keypass mule123 \
   -storepass mule123 \
   -keyalg DSA \
   -sigalg SHA1withDSA \
   -keysize 1024 \
   -alias mulekey \
   -ext SAN=DNS:localhost,IP:127.0.0.1 \
   -validity 9999
----

== 另请参阅

*  link:https://docs.oracle.com/javase/6/docs/technotes/tools/windows/keytool.html[Oracle keytool文档]
*  link:/connectors/common-about-tls[关于TLS]
