= 通过TLS建立安全连接
:keywords: email, http, sockets, connector, configuration
：TOC：
：TOC标题：

TOC :: []

Anypoint Studio，设计中心：*Email*，*HTTP*，*Web Service Consumer*和_？插座？_连接器
_TODO，VERIFY完整性，来自JUANI_的信息
_TODO，看，如果克里斯已经提供了一些可以发送电子邮件的链接
_TODO，问题，我们是否正在使用Java安全套接字扩展（JSSE）？_
_TODO，问题，TLS 1.0还是什么？

[[short_description]]
要通过诸如IMAPS，POP3S，SMTPS，HTTPS等协议提供安全连接，您需要将传输层安全性（TLS）配置为您的整体配置的一部分。
_TODO，验证，更改_

[[set_up_tls]]
. 将TLS配置区域用于使用安全协议（如SMTPS）的操作。
+ 例如，对于Design Center中的电子邮件操作（例如*Send*），您可以点击电子邮件操作顶部的*Set Up*。 （在Anypoint Studio中，您可以在为操作提供常规配置时添加（*+*）*Extension configuration*，也可以使用*Connections Explorer*添加（*+*）添加配置。）
. 选择使用TLS的连接类型（或提供商），例如用于电子邮件连接器的SMTPS。
. 查找*TLS Configuration*选项。
. 选择或添加（*+*）TLS配置。
. 提供或编辑所有必填字段的值。

_TODO，使用注意事项
_TODO，问题，所有领域都需要，但都适用于电子邮件？_
_TODO，如何获得这些有效值？下面的例子真的完成了吗？_
TLS配置

* 启用的协议，例如`TLSv1.2,SSLv3`
* 启用密码套件，例如`ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256`
* 信任存储设置（用于证书_TODO，问题，自签名和/或由CA机构签名？_，客户信任）：
  ** 路径，例如`/path/to/my.jks`
  ** 密码，例如`somepassword`
  ** 类型（其中之一）：
    ***  *jks*（用于Java密钥库）
    ***  *jceks*（用于Java加密扩展密钥库）
    ***  *pkcs12*（用于加密对象的公钥加密标准格式）
  ** 算法，例如`RSA` _TODO，更多？_
  ** 不安全_TODO，？对于完全遗留的重新谈判，这意味着易受MITM攻击？查看http://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html_
* 密钥存储设置（用于私钥和相关证书或证书链）：
  ** 路径
  ** 输入
    *** 别名，例如`client`
密钥密码。    *** 
    *** 关键
    *** 算法

[[see_also]]
== 另请参阅

_TODO，需要4.0版 link:https://docs.mulesoft.com/mule-user-guide/v/3.8/tls-configuration[（关于）TLS配置元素] _

link:email-connector[关于电子邮件连接器]

link:email-documentation[Email Connector技术参考]

////
谈判密码套件：
SSL会话始于客户端和服务器之间关于他们将使用哪个密码套件的协商。密码套件是计算机可用于加密数据的一组加密算法和密钥大小。密码套件包括有关公钥交换算法或密钥协商算法以及加密散列函数的信息。客户端通知服务器它有哪些密码套件，并且服务器选择最佳的双方可接受的密码套件。

////
