数据库连接器= 

发行说明： link:/release-notes/connector-db[数据库连接器发行说明]

数据库连接器在您的Mule应用程序和关系数据库之间建立通信。在Studio中，您需要按 link:common-add-module-task[将连接器添加到Studio]中所述添加数据库连接器。将连接器添加到Studio后，连接器及其操作将出现在Mule Palette中。

//去做？什么关于设计中心/流程设计师？

== 数据库听众和操作
数据库连接器提供了一个侦听器，用于从流中Source部分的数据库中读取数据。其他操作还允许您在Process部分的任何位置读取和写入数据库。批量操作不是将单个记录写入数据库，而是允许您通过简单地提供SQL修改每条记录来修改记录集合。其他操作允许您执行数据定义语言（DDL）操作，执行存储过程或一次执行整个SQL脚本。

== 数据库连接器功能

* 改进的操作：简化操作以便与单个或批量操作进行数据库交互。
* 动态查询很容易：执行静态和动态查询有一个经验。
嵌入式转换：您可以在插入和更新操作中嵌入DataWeave转换，以构建要发送到数据库的数据集，而不会对消息产生副作用或需要使用聚合器。
* 流支持：连接器使用Mule的流式框架自动且透明地处理流式传输。您甚至可以执行Select语句并异步处理结果，而不必担心连接泄漏。

== 支持的数据库类型
数据库连接器为以下数据库提供专门的支持：

* 德比
* 的MySQL
* 的Oracle
*  Microsoft SQL Server

您可以使用通用JDBC配置来设置其他JDBC数据库。您还可以引用XA事务所需的JDBC `DataSource`对象或`XADataSource`对象。您通常使用Spring在Studio中创建对象。



== 另请参阅

// * link:[骡4流]

*  link:db-configure-connection[配置到数据库的连接]
*  link:db-connector-query[查询数据库中的数据]
*  link:db-connector-trigger[触发表中每一行的流程]
*  link:db-connector-insert-update-delete[在数据库中插入，更新和删除数据]
*  link:db-connector-transactions-ref[在数据库中使用事务]
*  link:db-connector-execute-script-ref[执行数据库脚本]
*  link:db-connector-datatypes-ref[使用数据库定制类型]
*  link:db-connector-ddl[在数据库中创建表，触发器，过程和其他模式对象]
*  link:database-documentation[数据库接口技术参考]
*  link:/mule4-user-guide/v/4.1/migration-connectors-database[迁移数据库连接器]
