= 为表格中的每一行触发一个流程
:keywords: db, connector, SQL, Database, query, trigger, poll
：TOC：
：TOC标题：
*Available since version 1.3*

一个常见的用例是为表中的每一行触发一个流。尽管通过将`<scheduler>`与`<db:select>`操作相结合可以轻松实现，但`<db:listener>`组件可以自动简化以下操作：

* 生成查询
* 处理水印（可选）
* 处理并发请求的幂等性

[TIP]
Studio和Flow Designer中的`<db:listener>`元素显示为`On Table Row`

[source,xml,linenums]
----
<flow name="onEachRow">
  <db:listener table="EVENTS" config-ref="dbConfig"> // <1>
    <scheduling-strategy>
      <fixed-frequency frequency="60000"/>
    </scheduling-strategy>
  </db:listener>
  
  <flow-ref name="doProcess"> // <2>
  
  <db:delete config-ref="dbConfig"> // <3>
    <db:sql>DELETE FROM EVENTS WHERE ID = :id</db:sql>
    <db:input-parameters>#[{'id': payload.id]</db:input-parameters>
  </db:delete>
</flow>
----

<1>将`<db:listener>`配置为每分钟检查一次`EVENTS`表中的行。它会自动运行`SELECT * FROM EVENTS`查询
<2>流将按每行执行，并且在本示例中，通过流参考进行处理
<3>最后，处理后的行会被删除，以确保它在下一次轮询中不会再次拾起

== 水印

并非所有情况下删除该行都是有意义的。在很多情况下，您只需确保在下一轮投票中不再选取该行。一个经典的选择是使用水印：

[source,xml,linenums]
----
<flow name="onEachRow">
  <db:listener table="EVENTS" watermarkColumn="TIMESTAMP" config-ref="dbConfig">
    <scheduling-strategy>
      <fixed-frequency frequency="60000"/>
    </scheduling-strategy>
  </db:listener>
  
  <flow-ref name="doProcess">
</flow>
----

这个例子与之前几乎相同，除了现在我们使用`TIMESTAMP`列作为水印。在每轮投票中，组件将遍历所有获得的行并存储获得的最大值。在下次投票中，查询将如下所示：`SELECT * FROM EVENTS WHERE TIMESTAMP > :watermark`

== 幂等性

如果轮询时间间隔很短，或者行数很大，或者处理一个单独的行花费的时间过长，则可能会遇到在更新水印或删除行之前执行新轮询的风险。

为了帮助你，这个组件允许你指定一个ID列。该列将被视为该行的唯一标识符，并且侦听器将确保该行如果已经被找到并且其处理尚未完成，则该行不会再被拾取。例如：

[source,xml,linenums]
----
<flow name="onEachRow">
  <db:listener table="EVENTS" watermarkColumn="TIMESTAMP" idColumn="ID" config-ref="dbConfig">
    <scheduling-strategy>
      <fixed-frequency frequency="60000"/>
    </scheduling-strategy>
  </db:listener>
  
  <flow-ref name="doProcess">
</flow>
----

[TIP]
请注意，`watermarkColumn`和`idColumn`都是可选的并且是分开的。您可以将它们分开使用，也可以根本不使用。这取决于你的用例

==  DataSense

DataSense可用于侦听器的输出。 Studio和Flow Designer将自动为您提供表格结构，使您可以轻松编写表达式和映射。

