= 使用电子邮件连接器发送电子邮件
:keywords: email, connector, configuration, smtp, send, smtps
：TOC：
：TOC标题：

TOC :: []

电子邮件连接器可以通过SMTP和SMTPS发送消息。

== 配置连接器

单独的配置类型可用于列出存储在服务器中的电子邮件：

*  SMTP
*  SMTPS（由TLS保护）


===  SMTP配置类型

这是一个SMTP配置的例子：

.SMTP配置
[source, xml, linenums]
----
<email:smtp-config name="smtp">
    <email:stmp-connection host="smtp.gmail.com" port="995" user="pablo.musumeci@mulesoft.com" password="#netherlands!"/>
</email:smtp-config>
----

=== 安全配置类型

SMTPS连接类型提供了一个TLS配置字段，您可以在其中设置TLS上下文。该配置启用SSL / TLS加密，并通过SMTP协议SMTPS的安全版本发送加密的消息。

这是一个SMTPS的例子：

。使用TLS进行SMTP配置
[source, xml, linenums]
----
<email:smtp-config name="smtp">
    <email:stmps-connection host="pop.gmail.com" port="995" user="pablo.musumeci@mulesoft.com" password="#netherlands!"/>
        <tls:context enabledProtocols="TLSv1.2,SSLv3">
            <tls:key-store path="aKeystore" password="password"/>
            <tls:trust-store path="aTruststore.jks" password="changeit"/>
        </tls:context>
    </email:smtps-connection>
</email:smtp-config>
----

== 发送电子邮件

这个发送电子邮件的例子：

[source, xml, linenums]
----
<email:send config-ref="smtp" subject="IMPORTANT!" fromAddress="musumeci@mulesoft.com">
    <email:to-addresses>
        <email:to-address value="ale.gamarra@mulesoft.com"/>
        <email:to-address value="agustin.celentandios@mulesoft.com"/>
    </email:to-addresses>
    <email:body contentType="text/html">
        <email:content>"<h1>Hello this is an important message</h1>"</email:content>
    </email:body>
</email:send>
----

在上面的示例中，`to-addresses`包含的主要收件人地址
传出电子邮件`fromAddress`属性是电子邮件发件人地址，`subject`是电子邮件主题。

`body`由`content`文本和指定该文本的`contentType`组成
内容的MIME类型（例如，`text/xml`或`text/plain`）。如果未指定`body`，则默认使用消息负载的内容。如果该有效负载不是`text`，则该操作将失败并出现`EMAIL:SEND`错误。


== 发送附件

通过SMTP发送附件时，您需要使用DataWeave处理附件。

在此示例中，流程使用文件连接器读取JSON文件，然后使用电子邮件连接器通过SMTP将文件内容作为附件发送：

[source, xml, linenums]
----
<flow name="attachment">
  <file:read path="/file.json"/>
  <email:send config-ref="config">
      <email:to-addresses>
          <email:to-address value="agusto.celentandios@mulesoft.com"/>
      </email:to-addresses>
      <email:body>
          <email:content>Sending attachments!</email:content>
      </email:body>
      <email:attachments>
        #[{
          'json-attachment' : payload
        }]
      </email:attachments>
  </email:send>
</flow>
----

如您所见，`email:attachments`需要一个DataWeave表达式
每个元素都是一个附件。例如，上面的例子添加了一个新的附件
名为`json-attachment`。请注意，`payload`是由File连接器读取的JSON文件的内容。
