= 消费JMS消息
:keywords: jms, connector, consume, message
：TOC：
：TOC标题：

JMS连接器中的“使用”操作提供了在任何给定时间使用来自任何给定目标的消息的功能。

== 消费一条消息
从队列中使用消息的语法是：

[source, xml, linenums]
----
<jms:consume config-ref="JMS_config" destination="#[vars.destination]"/>
----

上述操作使用目标所标识的队列中的第一条可用消息，然后将其转换为`MuleMessage`，从而产生以下结构：

* 邮件的内容为有效内容。
* 消息的消息属性中的元数据。

一旦收到，默认情况下，该消息将立即得到确认。如果您想在某些处理后控制消息的确认，则应将`ackMode`设置为`MANUAL`
有关消息确认的更多信息，请查看 link:jms-ack[如何处理消息确认]。

== 等待消息

默认情况下，最长等待时间配置为10秒，如果该时间段内没有可用消息，则会产生`JMS:TIMEOUT`错误。
如果为了配置更适合您的用例的超时，请自定义`maximumWait`和`maximumWaitUnit`参数。

为了无限期地等待消息到达，必须将`maximumWait`值设置为`-1`。在这种情况下，不会引发`TIMEOUT`错误。

== 轮询消息

当以特定频率轮询消息时，您不希望消费者阻止等待消息，而只是尝试消费它，如果有消息。
在这种情况下，可以将`maximumWait`设置为`0`，表示不应该发生等待，并且如果目标中没有消息可用，则不应该抛出`JMS:TIMEOUT`。
当没有消息存在消耗并且没有错误发生时，`consume`操作的输出将为`null`。

== 过滤传入消息

JMS连接器完全支持基于标准*JMS selector language*过滤应消费哪些消息。

例如，如果您的消息优先队列需要比其他消息更快处理，我们可以这样做：

[source, xml, linenums]
----
<jms:consume config-ref="JMS_config" destination="openTickets" selector="JMSPriority=8"/>
----

如果配置了选择器，则只会接收与其匹配的消息，而忽略目标中是否有其他消息。

==  MIME类型和编码

JMS连接器尽力根据`MM_MESSAGE_CONTENT_TYPE`属性自动确定消息的MIME类型（`contentType`）。但是，有些情况下最好的猜测还不够，而且您需要第一手了解Message的内容。

在这种情况下，您可以使用`contentType`参数将该内容类型强制为特定值。

相同的过程适用于编码。默认情况下，如果没有提供其他信息，连接器将假定运行时的默认编码与Message中的编码相匹配。您可以使用`encoding`参数进行设置。

使用主题订阅消费消息== 

使用来自Topic目标的消息与从Queue使用它们非常相似，但具有可以使用Topic预订在消费者之间共享状态的额外功能。
从Topic中消费消息的语法是：

[source, xml, linenums]
----
<jms:consume config-ref="JMS_config" destination="#[vars.destination]">
    <jms:consumer-type>
        <jms:topic-consumer/>
    </jms:consumer-type>
</jms:consume>
----

所有`consume`操作参数保持不变，但现在您可以在`topic-consumer`参数中处理订阅配置。

有关如何配置主题订阅的详细信息，请转到 link:jms-topic-subscription[使用主题订阅]。


== 接收消息元数据

如前所述，收到的每封邮件将由两部分组成：

* 有效内容，包含消息的内容
* 这些属性包含有关消息的元数据

此元数据有三个部分，它们映射JMS消息中可用的所有信息：

*  AckId
* 集管
* 属性

检查 link:jms-documentation[JMS参考]以了解关于属性结构的详细信息。

== 另请参阅

*  link:jms-topic-subscription[使用主题订阅]
*  link:jms-listener[收听新消息]
