= 听取回复
:keywords: jms, connector, publish, consume, request, reply
：TOC：
：TOC标题：

Request / Reply是应用程序之间非常常见的模式，因此新的JMS Connector提供了专门为此设计的操作，称为`publish-consume`。通过`publish-consume`操作，您可以将消息发布到任何目标，然后等待另一个目标上的回复。

使用此操作时，传出消息的_JMSReplyTo_头将包含我们的应用程序将等待响应的目标的ID。这个目的地可能是一个众所周知的目的地，或者它可能是一个临时目的地，只能接收一个响应消息。

最后，操作的结果将是收到的消息作为响应，具有与调用`consume`操作完全相同的结构。

== 等待临时队列的回复

使用临时队列等待响应非常简单，只需配置发送的消息，操作就会自动等待临时队列中的响应：
[source, xml, linenums]
----
<jms:publish-consume config-ref="config" destination="targetDestination" maximumWait="20" maximumWaitUnit="SECONDS"/>
----

在此示例中，操作将`publish`将当前`payload`作为其*body*且将*JMSReplyTo header*配置为临时目的地的消息发送到`targetDestination`。
然后，它将自动尝试使用该临时队列的响应，直到消息被使用或达到`maximumWait`（在这种情况下，它将失败并出现`JMS:TIMEOUT`错误）。

接收已知队列上的回复== 

在许多情况下，您不希望根据请求创建回复队列，而是使用众所周知的队列来回复。对于这种情况，您所要做的就是在外发消息上配置`reply-to`参数：
[source, xml, linenums]
----
<jms:publish-consume config-ref="config" destination="targetDestination">
    <jms:message>
        <jms:reply-to destination="replyToDestination"/>
    </jms:message>
</jms:publish-consume>
----

现在，该操作会将`publish`消息传递给`targetDestination`，其中`payload`为*body*，`JMSReplyTo` *header*为{{1} 6}}。
然后，它将自动尝试消费来自`replyToDestination`队列的响应，直到消息被消耗或达到`maximumWait`（在这种情况下，它将失败并出现`JMS:TIMEOUT`错误）。

== 另请参阅

*  link:jms-publish[发布消息]
