=  Microsoft Dynamics 365连接器
:keywords: microsoft, dynamics, 365, crm, connector, oauth

_选择_

Anypoint平台的Microsoft Dynamics 365连接器支持与Microsoft Dynamics 365 Web API集成。

该连接器可让您执行以下操作：

* 授权或未授权服务器访问。
* 创建，更新和删除实体。
* 检索单个实体或查询多个实体。
* 关联和取消关联实体。
* 执行操作。

== 先决条件

本文档假定您熟悉Mule，Anypoint连接器，
Anypoint Studio基本要素，骡流中的元素以及全局元素。

登录portal.azure.com上的Microsoft Azure Active Directory门户，获取您的应用的客户端ID和密码。

在开始之前：

* 您需要访问由Azure Active Directory利用的Microsoft Dynamics 365实例（联机或内部部署）;也就是说，Azure Active Directory是提供对应用程序访问的身份提供者。

== 关于连接器术语

* 操作 - 允许副作用（如数据修改）的操作，不能进一步组合以避免非确定性行为。
* 复杂类型 - 由一组属性组成的无钥匙命名结构化类型。复杂类型通常用作模型实体中的属性值，或用作操作的参数或返回值。
* 实体 - 实体类型的实例，例如帐户或机会。
* 实体集 - 实体的命名集合，例如，帐户是包含帐户实体的实体集。实体的密钥唯一标识实体集内的实体。
* 实体类型 - 用键命名结构化类型。实体类型定义实体的命名属性和关系，并且可以通过来自其他实体类型的单一继承来派生。
* 枚举类型或枚举类型 - 命名的基本类型，其值被命名为具有基础整数值的常量。
* 功能 - 没有副作用并可能支持进一步合成的操作，例如，使用附加的过滤器操作，功能或操作。

== 安装和配置连接器

. 在Anypoint Studio中，点击Studio任务栏中的Exchange图标。
. 点击Anypoint Exchange中的登录。
. 搜索连接器，然后单击安装。
. 按照提示安装连接器。

Studio有更新时，会在右下角显示一条消息，您可以单击该消息来安装更新。

== 使用Anypoint Studio可视化编辑器创建新的Mule项目

. 在Anypoint Studio中，单击文件>新建> Mule项目。
. 指定一个项目名称并单击完成。
. 搜索"http"并将HTTP连接器拖到画布上。点击绿色
连接器配置旁边的加号，然后单击菜单中的确定以接受默认值。
. 搜索"365"并将Microsoft Dynamics 365连接器拖到画布上。
单击连接器配置旁边的绿色加号，然后指定您的访问凭据。
. 单击用于身份验证的连接策略：
+
**  Microsoft Dynamics 365 OAuth 2.0连接
**  Microsoft Dynamics 365 OAuth 2.0用户名 - 密码

=== 配置OAuth 2.0连接

此配置提供对Microsoft Dynamics 365 Web API的访问。

=== 配置OAuth 2.0用户名 - 密码

. 单击连接器配置右侧的绿色加号。
. 提供以下凭据以启用对Microsoft Dynamics 365服务器的访问：
+
* 在常规标签下

** 客户端ID  - 在您向Azure Active Directory注册时分配给您的应用程序的应用程序ID。你可以在Azure Portal中找到它。单击Active Directory，单击该目录，选择该应用程序，然后单击配置。
** 客户端秘密 - 您在应用程序注册门户中为您的应用程序创建的应用程序秘密。这不应该在本机应用程序中使用，因为客户机密不能可靠地存储在设备上。这对于Web应用程序和Web API来说是必需的，它们能够在服务器端安全地存储客户机密钥。
** 用户名 - 用于初始化会话的用户名。
** 密码 - 用于验证用户的密码。
** 资源 -  Web API的应用程序标识URI（受保护的资源）。这必须是根URI，而不指定CRM版本。例如：`+https://YOUR_ORG.crm.dynamics.com/+`
** 令牌请求端点 - 用于获取访问令牌的令牌端点。示例：`+https://login.windows.net/TENANT_ID/oauth2/token+`其中TENANT_ID是Azure Active Directory标识。

* 在高级选项卡下

** 读取超时 - 消费者之前等待响应的持续时间（以毫秒为单位）
超时。零（0）意味着永远等待。
** 连接超时 - 指定用户在超时之前尝试建立连接的持续时间（以毫秒为单位）。零（0）意味着永远等待。
+
. 单击测试连接以确保您的凭证在服务器端点处被接受。
. 如果存在，请单击启用DataSense以让应用程序从服务器获取元数据。

== 运行流程

. 在包资源管理器中，右键单击您的项目名称，然后单击运行方式> Mule应用程序。
. 检查控制台以查看应用程序何时启动。如果没有错误发生，您应该看到这些消息：

[source,xml,linenums]
----
************************************************************
INFO  2017-05-14 22:12:42,003 [main] org.mule.module.launcher.DeploymentDirectoryWatcher:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Mule is up and kicking (every 5000ms)                    +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2017-05-14 22:12:42,006 [main] org.mule.module.launcher.StartupSummaryDeploymentListener:
**********************************************************
*  - - + DOMAIN + - -               * - - + STATUS + - - *
**********************************************************
* default                           * DEPLOYED           *
**********************************************************

************************************************************************
* - - + APPLICATION + - -   * - - + DOMAIN + - -  * - - + STATUS + - - *
************************************************************************
* myapp                     * default             * DEPLOYED           *
************************************************************************
----


== 示例：Microsoft Dynamics 365

此示例演示了使用Microsft Dynamics 365连接器。

要构建和运行此演示项目，您需要：

具有至少Mule 4.0运行时的*  Anypoint Studio。
*  Microsft Dynamics 365 Connector v2.0.0或更高版本。
*  Azure Active Directory利用Dynamics 365。

=== 测试流程

. 使用Anypoint Exchange或使用“文件”菜单中的“导入”命令将演示项目导入工作区。
. 在`/src/main/app/mule-app.properties`文件中为OAuth 2用户名 - 密码配置指定您的OAuth 2凭据：
+
**  dynamics365.username  - 用于初始化会话的用户名。
**  dynamics365.password  - 用于验证用户的密码。
**  dynamics365.resource  -  Web API的App ID URI，它是一种安全资源。该资源必须是不指定CRM版本的根URI。例如：`+https://YOUR_ORG.crm.dynamics.com/+`
**  dynamics365.clientId  - 在您向Azure Active Directory注册时分配给您的应用程序的应用程序ID。你可以在Azure Portal中找到它。单击Active Directory，单击该目录，选择该应用程序，然后单击配置。
**  dynamics365.clientSecret  - 您在应用程序注册门户中为您的应用程序创建的应用程序秘密。这不应该在本地应用程序中使用，因为客户机密钥不能可靠地存储在设备上。 Web应用程序和Web API需要客户机密，它们能够在服务器端安全地存储客户机密钥。
**  dynamics365.tokenRequestEndpoint  - 调用来获取访问令牌的令牌端点。 +
示例：`+https://login.windows.net/TENANT_ID/oauth2/token`其中TENANT_ID是Azure Active Directory标识。
+
. 在Studio中运行项目。
. 在浏览器中输入`localhost:8081`以访问演示的选择菜单。
. （可选）您可以配置连接超时和读取超时。
连接超时是与服务器进行初始连接的超时时间。
读取超时是等待从服务器读取数据的超时时间。

您可以使用`+http://localhost:8081+`中的选择菜单来测试流程，也可以使用卷曲工具或其他任何工具（Chrome / Mozilla Firefox扩展）来发布JSON，以便在调用URL时发布主体。


=== 示例XML流

[source,xml,linenums]
----
<?xml version="1.0"?>

<mule xmlns:dynamics="http://www.mulesoft.org/schema/mule/dynamics"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
http://www.mulesoft.org/schema/mule/dynamics http://www.mulesoft.org/schema/mule/dynamics/current/mule-dynamics.xsd">

	<configuration-properties file="mule-artifact.properties" />
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="2e53345d-33af-42cc-9c35-737ef41266e4" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<dynamics:dynamics-config name="Dynamics_365_config" doc:name="Dynamics 365 Dynamics 365" doc:id="823ca5ed-f274-47d7-a054-25d8a8da3eb5" >
		<dynamics:oauth-user-pass-connection username="${config-oauth-user-pass.username}" password="${config-oauth-user-pass.password}"
			resource="${config-oauth-user-pass.resource}" clientId="${config-oauth-user-pass.clientId}"
			clientSecret="${config-oauth-user-pass.clientSecret}" tokenRequestEndpoint="${config-oauth-user-pass.tokenRequestEndpoint}" />
	</dynamics:dynamics-config>
	<flow name="PARSE_DEMO_TEMPLATE">
        <http:listener config-ref="HTTP_Listener_config" doc:name="HTTP" path="/"/>
        <parse-template location="form.html" doc:name="Parse Template"/>
    </flow>
    <flow name="CREATE_EMPTY_CONTACT_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/createContact" doc:name="HTTP"/>
        <logger message="Requested 'Create Contact Operation'" level="INFO" doc:name="Logger"/>
		<dynamics:create config-ref="Dynamics_365_config" logicalName="contact" doc:name="Microsoft Dynamics 365">
			<dynamics:attributes ><![CDATA[#[{}]]]></dynamics:attributes>
		</dynamics:create>

        <logger message="#['Received Response from &quot;Create Contact Operation&quot;:' ++ payload]" level="INFO" doc:name="Logger"/>
    </flow>
    <flow name="CREATE_EMPTY_OPPORTUNITY_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/createOpportunity" doc:name="HTTP"/>
        <logger message="Requested 'Create Opportunity Operation'" level="INFO" doc:name="Logger"/>
		<dynamics:create config-ref="Dynamics_365_config" logicalName="opportunity" doc:name="Microsoft Dynamics 365">
			<dynamics:attributes ><![CDATA[#[{}]]]></dynamics:attributes>
		</dynamics:create>
        <logger message="#['Received Response from &quot;Create Opportunity Operation&quot;: ' ++ payload]" level="INFO" doc:name="Logger"/>
    </flow>
    <flow name="CREATE_ACCOUNT_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/createAccount" doc:name="HTTP"/>
        <logger message="Requested 'Create Account Operation'" level="INFO" doc:name="Logger"/>
        <ee:transform doc:name="Transform Message">
            <ee:message>
            	<ee:set-payload>
            <![CDATA[%dw 2.0
output application/java
---
{
	name: payload.AccountName,
	creditonhold: payload.CreditOnHold,
	creditlimit: payload.CreditLimit,
	"primarycontactid@odata.bind": "/contacts(" ++ payload.ContactID ++ ")"
}]]></ee:set-payload>
			</ee:message>
		</ee:transform>
        <dynamics:create config-ref="Dynamics_365_config" logicalName="account" doc:name="Microsoft Dynamics 365">
            <dynamics:attributes>#[payload]</dynamics:attributes>
        </dynamics:create>
        <logger message="#['Received Response from &quot;Create Account Operation&quot; : ' ++ payload]" level="INFO" doc:name="Logger"/>
    </flow>
    <flow name="CREATE_MULTIPLE_ENTITIES_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/createMultipleAccounts" doc:name="HTTP"/>
        <logger message="Requested 'Create Multiple Accounts Operation'" level="INFO" doc:name="Logger"/>
        <ee:transform doc:name="Transform Message">
            <ee:message>
            	<ee:set-payload><![CDATA[%dw 2.0
input payload application/json
output application/java
---
payload map {
      name: $.AccountName,
      creditlimit : $.CreditLimit,
      creditonhold : $.CreditOnHold
}]]></ee:set-payload>
			</ee:message>
        </ee:transform>
        <dynamics:create-multiple config-ref="Dynamics_365_config" logicalName="account" doc:name="Microsoft Dynamics 365">
            <dynamics:entities-attributes>#[payload]</dynamics:entities-attributes>
        </dynamics:create-multiple>
        <logger message="Received Response from 'Create Multiple Entities Operation'" level="INFO" doc:name="Logger"/>
        <ee:transform doc:name="Response to JSON" doc:id="5be799cf-e01a-416b-a3bb-084f945f9da8" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
    </flow>
    <flow name="UPDATE_ENTITY_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/updateAccount" doc:name="HTTP"/>
        <logger message="Requested 'Update Entity Operation'" level="INFO" doc:name="Logger"/>
        <ee:transform doc:name="Transform Message">
            <ee:message>
            	<ee:set-payload><![CDATA[%dw 2.0
output application/java
---
{
	entityId: payload.EntityId,
	attributes: {
		creditlimit: payload.CreditLimit,
		name: payload.AccountName
	}
}]]></ee:set-payload>
			</ee:message>
        </ee:transform>
        <dynamics:update config-ref="Dynamics_365_config" logicalName="account" doc:name="Microsoft Dynamics 365">
            <dynamics:attributes>#[payload]</dynamics:attributes>
        </dynamics:update>
        <logger message="'Update Entity Operation' has ended with success" level="INFO" doc:name="Logger"/>
        <ee:transform doc:name="Response to JSON" doc:id="9d1bc853-e9eb-4c4a-a323-f9b171583c76" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
    </flow>
    <flow name="UPDATE_MULTIPLE_ENTITIES_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/updateMultipleAccounts" doc:name="HTTP"/>
        <logger message="Requested 'Update Multiple Entities Operation'" level="INFO" doc:name="Logger"/>
        <ee:transform doc:name="Transform Message">
            <ee:message>
            	<ee:set-payload><![CDATA[%dw 2.0
input payload application/json
output application/java
---
payload map {
	entityId: $.EntityId,
	attributes: {
		name: $.AccountName
	}
}]]></ee:set-payload>
			</ee:message>
        </ee:transform>
        <dynamics:update-multiple config-ref="Dynamics_365_config" logicalName="account" doc:name="Microsoft Dynamics 365">
            <dynamics:entities-attributes>#[payload]</dynamics:entities-attributes>
        </dynamics:update-multiple>
        <logger message="Received Response from 'Update Multiple Entities Operation'" level="INFO" doc:name="Logger"/>
        <ee:transform doc:name="Response to JSON" doc:id="b8d51b91-b280-42b4-8ed4-43004fd94afb" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
    </flow>
    <flow name="DELETE_ENTITY_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/deleteAccount" doc:name="HTTP"/>
        <logger message="Requested 'Delete Entitiy Operation'" level="INFO" doc:name="Logger"/>
        <dynamics:delete config-ref="Dynamics_365_config" logicalName="account" doc:name="Microsoft Dynamics 365">
			<dynamics:id>#[payload.EntityId]</dynamics:id>
		</dynamics:delete>
        <logger message="'Delete Entity Operation' has ended with success" level="INFO" doc:name="Logger"/>
    </flow>
    <flow name="RETRIEVE_ENTITY_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/retrieveAccount" doc:name="HTTP"/>
        <logger message="Requested 'Retrieve Entitiy Operation'" level="INFO" doc:name="Logger"/>
        <dynamics:retrieve config-ref="Dynamics_365_config" logicalName="account" doc:name="Microsoft Dynamics 365">
			<dynamics:id>#[payload.EntityId]</dynamics:id>
		</dynamics:retrieve>
        <logger message="Received Response from 'Retrieve Entitiy Operation'" level="INFO" doc:name="Logger"/>
        <ee:transform doc:name="Response to JSON" doc:id="3da385b1-b9fe-4f25-b8b0-a0e0521cc0cf" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
    </flow>
    <flow name="RETRIEVE_ENTITIES_BY_URL_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/retrieveAccountsByURL" doc:name="HTTP"/>
        <logger message="Requested 'Retrieve Multiple Operation'" level="INFO" doc:name="Logger"/>
        <dynamics:retrieve-multiple config-ref="Dynamics_365_config" doc:name="Microsoft Dynamics 365">
        	<dynamics:data-query-url>${config-oauth-user-pass.resource}/api/data/v8.2/accounts?$select=name,accountnumber&amp;$top=3</dynamics:data-query-url>
        </dynamics:retrieve-multiple>

        <logger message="Received Response from 'Retrieve Multiple Operation'" level="INFO" doc:name="Logger"/>
        <ee:transform doc:name="Response to JSON" doc:id="708cf0f5-14e5-47d9-9e2a-0e8c656898e6" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
    </flow>
    <flow name="RETRIEVE_ENTITIES_BY_QUERY_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/retrieveAccountsByQuery" doc:name="HTTP"/>
        <logger message="Requested 'Retrieve Multiple By Query Operation'" level="INFO" doc:name="Logger"/>
        <dynamics:retrieve-multiple-by-query config-ref="Dynamics_365_config" doc:name="Microsoft Dynamics 365">
        	<dynamics:query>dsql:SELECT accountid,accountnumber,name FROM accounts LIMIT 2</dynamics:query>
        </dynamics:retrieve-multiple-by-query>

        <logger message="Received Response from 'Retrieve Multiple By Query Operation'" level="INFO" doc:name="Logger"/>
		<ee:transform doc:name="Response to JSON" doc:id="c6d79b71-1667-44b9-b39b-7a4ce2c6638d">
			<ee:message>
				<ee:set-payload><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
    </flow>
    <flow name="DISASSOCIATE_ENTITIES_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/disassociateEntities" doc:name="HTTP"/>
        <logger level="INFO" doc:name="Logger" message="Requested 'Dissasociate Entities Operation'"/>
        <ee:transform doc:name="Transform Message">
            <ee:message>
            	<ee:set-payload><![CDATA[%dw 2.0
output application/java
---
{
	entityId: payload.EntityId,
	attributes: payload.EntityLinkKeys
}]]></ee:set-payload>
			</ee:message>
        </ee:transform>
        <dynamics:disassociate config-ref="Dynamics_365_config" logicalName="account" doc:name="Microsoft Dynamics 365">
            <dynamics:attributes>#[payload]</dynamics:attributes>
        </dynamics:disassociate>
        <logger level="INFO" doc:name="Logger" message="Finished 'Dissasociate Entities Operation' with success"/>
    </flow>
    <flow name="DO_ACTION_DEMO">
        <http:listener config-ref="HTTP_Listener_config" path="/doAction" doc:name="HTTP"/>
        <logger message="Requested 'Do Action Operation'" level="INFO" doc:name="Logger"/>

		<ee:transform doc:name="Transform Message">
            <ee:message>
            	<ee:set-payload><![CDATA[%dw 2.0
output application/java
---
{
	OpportunityClose: {
		subject: payload.Subject,
		"opportunityid@odata.bind": "/opportunities(" ++ payload.OpportunityId ++ ")"
	},
	Status: payload.Status
}]]></ee:set-payload>
			</ee:message>
        </ee:transform>
        <dynamics:do-action config-ref="Dynamics_365_config" actionName="WinOpportunity" doc:name="Microsoft Dynamics 365"/>
        <logger message="Finished 'Do Action Operation'" level="INFO" doc:name="Logger"/>
    </flow>
</mule>
----

== 另请参阅

*  https://msdn.microsoft.com/en-us/library/mt607990.aspx [Web API术语]
*  https://msdn.microsoft.com/en-us/library/mt607875.aspx [Web API  - 关联实体]
*  https://msdn.microsoft.com/en-us/library/mt607719.aspx [Web API  - 批量请求]
*  https://msdn.microsoft.com/en-us/library/gg328090.aspx [Web API  - 创建新实体]
*  https://msdn.microsoft.com/en-us/library/mt607664.aspx [Web API  - 删除实体]
*  https://msdn.microsoft.com/en-us/library/mt607875.aspx [Web API  - 取消关联实体]
*  https://msdn.microsoft.com/en-us/library/mt628816.aspx [Web API  - 限制]
*  https://msdn.microsoft.com/en-us/library/gg334767.aspx [Web API  - 使用Web API查询数据]
*  https://msdn.microsoft.com/en-us/library/mt607871.aspx [Web API  - 检索实体]
*  https://msdn.microsoft.com/en-us/library/mt607664.aspx [Web API  - 更新实体]
*  https://msdn.microsoft.com/en-us/library/mt607600.aspx [Web API  - 使用Web API操作]
