= 对象存储连接器
:keywords: object store, object, store, connector

*Reference:* link:object-store-connector-reference[对象存储连接器参考]

一个对象存储是一个允许简单的键值存储的Mule组件。尽管它可以服务于各种各样的用例，它主要设计用于：

* 存储同步信息，例如水印。
* 存储时间信息，如访问令牌。
* 存储用户信息。

另外，Mule Runtime使用Object Stores来支持一些自己的组件，例如：

* 缓存模块使用对象存储来维护所有缓存的数据。
*  OAuth模块（以及每个启用OAuth的连接器）使用对象存储来存储访问和刷新令牌。
*  `<until-successful/>`组件使用对象存储来存储所有必须重试的消息。所以，如果Mule崩溃，那些消息不会丢失，并且可以在恢复时继续处理。

== 对象存储限制

对象存储不是数据存储的通用解决方案。它们不会替换数据库，并且不适合每个用例。最重要的是，它们不支持事务访问或修改。对于需要 link:https://en.wikipedia.org/wiki/ACID[酸]语义的用例，或者对于期望同时更新相同密钥的情况，请考虑另一种解决方案。

== 使用默认对象存储

默认情况下，每个Mule应用程序都有一个对象存储，该对象存储是持久的，并且始终可用于应用程序_而无需任何配置_。流可以用它来坚持和共享数据。

如果要使用默认对象存储，则可以为对象存储指定`key`，而无需为对象存储操作选择或创建对象存储引用，也无需在XML中指定`objectStore`属性Object Store组件的元素。

请注意，Mule应用程序通过Anypoint Platform Runtime Manager部署到CloudHub工作人员中，Mule应用程序的默认对象存储的内容在运行时管理器中可见，位于Mule应用程序的“应用程序数据”选项卡中。

了解运行时管理器应用程序数据选项卡中显示的唯一对象存储是默认对象存储很重要。

== 使用自定义对象存储

自定义对象库必须指定一个`objectStore`属性。这些对象存储可以配置为与默认对象存储不同。例如，您可以指示对象存储是持久存储（以便对象存储数据在Mule运行时崩溃中存活）或瞬时存储（数据不会在Mule运行时崩溃中存活）。以下是定义对象存储的一些常见原因：

* 您想通过将信息存储在不同的对象库中来对信息进行分区。
* 您想要使用高级对象存储库功能，例如：
** 瞬态/持久存储。
** 指定生存时间（TTL）。
** 指定最大容量。
* 您希望通过向不同的对象库提供不同的组件来共享状态。
* 您希望不同的组件通过将信息提供给相同的对象库来共享信息。

== 另请参阅

link:object-store-to-define-a-new-os[定义对象存储]

link:object-store-to-store-and-retrieve[从对象存储中存储和检索信息]

link:object-store-to-watermark[例如：水印]
