= 关于Apex设置和调用操作
:keywords: salesforce connector, inbound, outbound, streaming, poll, dataweave, datasense
：imagesdir：_images
：图标：字体

调用Apex REST方法（在版本6.2.0中引入）和调用Apex Soap方法（在6.1.0中引入）使用Apex类名称设置。连接到Salesforce时，Salesforce连接器将获取可以调用的属于它们的Apex类和方法的名称。

所有Salesforce连接配置都支持这些Apex设置：

* 获取所有Apex SOAP元数据 - 获取所有Apex SOAP类的元数据。优先于Apex类名称设置。
* 获取所有Apex REST元数据 - 获取所有Apex REST类的元数据。优先于Apex类名称设置。
*  Apex类名称 -  Apex类名称列表，用于限制您提取的类集以及它们公开的方法。如果有很多不需要获取的类，此设置可以加快获取过程。

////
对两个Invoke Apex操作的输入默认设置为所选方法的`payload`。对于基于SOAP的操作，还可以使用Map将输入格式转换为不同的输出格式。
////

== 另请参阅

link:/connectors/salesforce-about[关于Salesforce连接器]

link:/connectors/salesforce-connector-tech-ref[Salesforce连接器技术参考]

////
不需要采取更多行动：
这些选项可用吗？ 07/18通知BOGDAN。
.  Apex类名称：
.. 无 - 没有提到DataSense要获取Apex类名称。
.. 来自消息 - 允许您从MEL表达式中指定类名称。
.. 手动创建对象 - 用户创建列表并将类名添加到列表中 - 只有这些类及其方法由DataSense获取。
+
////

////
不需要采取更多行动：
这些选项可用吗？ 07/18通知BOGDAN。
 可以在Apex Class Method Name参数的下拉菜单中找到。选择一种方法和DataSense来获取该方法的输入和输出。
////

////
无需更多操作：客户不需要XMLStreamReader。
我们应该注意到XMLStreamReader？ BOGDAN ON 07/18问道。
对操作的输入是一个`XMLStreamReader`，它从XML中创建，表示所选方法的输入（类似于SOAP操作的输入）：
+
[source, xml, linenums]
----
<soap:testSOAPMethod>
    <soap:name>John</soap:name>
    <soap:someNumber>54</soap:someNumber>
</soap:testSOAPMethod>
----
////

////
不需要采取更多行动：
BOGDAN ON 07/18问道。不确定如何说与REST映射。看起来像选项是指定键/值对。
////
