=  SAP连接器

_Premium_

SAP连接器支持基于SAP NetWeaver和外部系统的数据集成。

注意：此连接器仅在Studio 7中可用，并且在Anypoint Platform的Design Center功能中不可用。

该连接器需要单独的许可证。联系MuleSoft评估或使用此连接器的生产。

Mule运行时支持通过我们的Anypoint Connector for SAP进行SAP集成，这是SAP认证的Java连接器，它利用SAP Java连接器（JCo）库，从而允许Mule应用程序执行以下操作：

* 通过RFC协议执行BAPI功能，支持以下类型：
** 同步RFC（sRFC）
** 事务性RFC（tRFC）
** 队列RFC（qRFC）
* 充当JCo服务器，作为通过sRFC，tRFC和qRFC的BAPI。
* 通过tRFC和qRFC发送IDoc。
* 通过tRFC和qRFC接收IDoc。
* 将SAP对象（JCo函数/ BAPI和IDocs）转换为XML。

== 先决条件

本文档假定您熟悉Mule，Anypoint连接器和
Anypoint Studio。

本文档还假设您拥有：

* 熟悉SAP业务环境，尤其是SAP R / 3 Business Suite。
* 从管理角度对SAP NetWeaver平台的基本理解。
*  ABAP语言的一些基本知识。
* 登录凭据来测试您的连接到您的目标资源。

针对硬件和软件要求以及兼容性
信息，请参阅SAP连接器发行说明。

== 此连接器的新增功能

该版本的连接器不再支持Mule 3.x，并增加了对Mule 4.x的支持。除此之外，没有添加或删除功能。

== 在Design Center中进行连接

设计中心不支持此连接器版本。

== 在Studio中进行配置

要在Mule应用程序中使用SAP连接器，请配置全局SAP元素。

SAP连接器对象包含允许您连接到SAP服务器的配置属性。

要为SAP连接器创建配置，请完成以下步骤：

. 转到全局元素部分，然后点击创建。
. 在连接器配置部分选择SAP入站或SAP出站
. 在常规选项卡窗格中，输入用于定义SAP系统管理员应提供的SAP连接所需的参数。

SAP全局元素配置允许您定义连接属性以及轻松地将所需的SAP依赖项添加到您的项目中。

为了便于使用，SAP连接器仅将最常见的属性显示为连接器参数。要配置未在“属性”面板中列出的属性，请参阅本指南中的"Extended Properties"部分。

要定义的最低要求属性是：

[%header%autowidth.spread]
|===
| {字段{1}}说明
|应用程序服务器主机|  SAP端点
|用户名 | 授权的SAP用户的用户名。
|密码| 授权SAP用户的密码凭证。
|系统编号| 用于连接到SAP系统的系统编号。
|客户端| 用于连接SAP系统的SAP客户端ID（通常是一个数字）。
|登录语言| 用于SAP连接的语言。例如，英语为EN。
|===

作为最佳实践，使用属性占位符语法以更简单且可重用的方式加载凭证。

单击Test按钮验证与SAP实例的连接是否成功。如果凭证正确，您应该收到测试连接成功消息。

== 为此连接器添加库

. 转到连接器的全局配置。
. 单击添加依赖项以添加每个必需的驱动程序。

如果您想在本地Maven仓库中安装依赖项，请运行以下命令：

[source, linenums]
----
mvn install:install-file -DgroupId=com.sap.conn.idoc -DartifactId=com.sap.conn.idoc.sapidoc3 -Dversion=3.0.16 -Dpackaging=jar -Dfile=sapidoc3.jar

mvn install:install-file -DgroupId=com.sap.conn.jco -DartifactId=com.sap.con.jco.sapjco3 -Dversion=3.0.15 -Dpackaging=jar -Dfile=lib/com/sap/conn/jco/sapjco3/3.0.15/sapjco3-3.0.15.jar

# This is to install the Mac version of libsapjco3
mvn install:install-file -DgroupId=com.sap.conn.jco -DartifactId=com.sap.conn.jco.libsapjco3 -Dversion=3.0.15 -Dclassifier=external-library -Dpackaging=jnilib -Dfile=src/test/resources/lib/3.0.15/darwinintel64/libsapjco3.jnilib
----

确保您使用的是正确版本的SAP JCO库。他们必须匹配操作系统和体系结构（64位与32位）。

== 扩展属性

要为SAP连接器全局元素定义扩展属性，请完成以下步骤：

. 导航到常规窗格上的高级选项卡。
. 找到窗口顶部的扩展属性部分。
. 选择编辑内联选项。
. 点击加号按钮（'+'）添加新的扩展属性。

为此，您必须在您的配置中设置由SAP定义的属性名称。

===  SAP入站

此配置没有特殊的高级属性。

===  SAP出站

[%header%autowidth.spread]
|===
|字段 | XML属性 |描述 |默认值
|显示名称 |名称 | Mule配置内部使用的端点的引用名称。 |
|默认idocument版本 | defaultIdocumentVersion  |发送IDoc时使用此版本。 IDoc版本的值对应于com.sap.conn.idoc.IDocFactory中的IDOC_VERSION_xxxx常量。|
|禁用函数模板缓存标志 | disableFunctionTemplateCacheFlag  |指示是否禁用函数模板缓存。| false
|评估响应标志 | evaluateResponseFlag  |指示错误响应是否应引发异常或让用户将其作为另一个结果处理。 | false
|日志跟踪标志 | logTraceFlag  |指示是否应在Mule服务器上记录跟踪。| false
|===

== 配置XML和Maven

要在Maven中使用此连接器，请查看中的pom.xml依赖关系信息
任意点Exchange中的依赖项片段。

对于Maven依赖管理，请将此XML片段包含在您的pom.xml文件中。

[source,xml,linenums]
----
<dependency>
  <groupId>org.mule.connectors</groupId>
  <artifactId>mule-sap-connector</artifactId>
  <version>4.0.0</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

在`<version>`标签内部放置所需版本号，RELEASE为最新版本，或SNAPSHOT为最新版本。可用的版本是：4.0.0。

== 用例：将IDocument发送给SAP

该用例描述了如何创建一个Mule应用程序来将IDocument发送到SAP。

. 在Anypoint Studio中创建一个新的Mule项目。
. 创建一个新的HTTP侦听器全局元素配置，并保留默认值。
. 将HTTP端点拖放到画布上并配置以下参数：
+
[%header%autowidth.spread]
|===
| {参数{1}}值
|连接器配置|  HTTP_Listener_Configuration
| {路径{1}} / sendIDoc
|===
+
. 创建新的SAP出站全局元素配置并填写环境值。
. 点击测试确认Mule可以连接SAP实例。如果连接成功，请单击确定以保存配置。否则，请查看或更正任何无效参数并再次测试。
. 选择SAP模块并在HTTP旁边添加发送IDoc操作，然后在扩展配置字段中选择上一节中创建的配置。
. 使用以下值配置操作：
+
[%header%autowidth.spread]
|===
| {参数{1}}值
|显示名称 |发送IDoc（或您喜欢的任何其他名称）
|连接器配置 | SAP_Outbound（您创建的全局元素的名称）
|键 | MATMAS01
|内容 |＃[有效载荷]
|===
+
. 在SAP连接器之前拖动一个Transform Message组件，然后单击该组件打开其属性编辑器。一旦检索到元数据，为员工选择相应的字段以填充。转换脚本应类似于以下内容：
+
[source,dataweave,linenums]
----
%dw 2.0
output application/xml
---
read('<?xml version="1.0"?>
<MATMAS01>
    <IDOC BEGIN="1">
        <EDI_DC40 SEGMENT="1">
             <TABNAM>EDI_DC40</TABNAM>
            <MANDT>800</MANDT>
        </EDI_DC40>
    </IDOC>
</MATMAS01>
',"application/xml")
----
+
. 在SAP端点之后添加一个记录器，以查看日志中的连接器负载。
. 保存并运行为Mule应用程序。
. 测试应用程序：
.. 在Web浏览器中，以下列查询参数的形式输入员工的internalId，第一个姓名和姓氏：
+
[source]
----
http://localhost:8081/sendIDoc
----
+
..  Mule执行查询，并将员工记录添加到NetSuite。

== 用例：XML

[source, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core" xmlns:sap="http://www.mulesoft.org/schema/mule/sap"
	  xmlns:http="http://www.mulesoft.org/schema/mule/http"
	  xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd

http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/sap http://www.mulesoft.org/schema/mule/sap/current/mule-sap.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd">
	<configuration-properties file="mule-artifact.properties"/>
	<sap:outbound-config name="SAP_Outbound" doc:name="SAP Outbound" doc:id="73ce221f-c68c-4b2b-a50f-f60c6cda46f8" >
		<sap:simple-connection-provider-connection applicationServerHost="${sap.jcoAsHost}" username="${sap.jcoUser}" password="${sap.jcoPasswd}" systemNumber="${sap.jcoSysnr}" client="${sap.jcoClient}" language="${sap.jcoLang}" />
	</sap:outbound-config>
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="058070a7-92ec-4316-a7fd-97e03e4ac822" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<flow name="demo-idoc-clientFlow" doc:id="4fd4e3bd-35a2-4fa9-8524-d722992bc6a7" >
		<http:listener config-ref="HTTP_Listener_config" path="/idoc" doc:name="Listener" doc:id="71361ae7-31a4-4f14-83e0-725031dbf7e9" />
		<ee:transform doc:name="Transform Message" doc:id="3e19acb5-a4b9-440c-8f13-dfd0a7024004" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/xml
---
read('<?xml version="1.0"?>
<MATMAS01>
    <IDOC BEGIN="1">
        <EDI_DC40 SEGMENT="1">
             <TABNAM>EDI_DC40</TABNAM>
            <MANDT>800</MANDT>
        </EDI_DC40>
    </IDOC>
</MATMAS01>
',"application/xml")
]]></ee:set-payload>
			</ee:message>
		</ee:transform>
		<sap:send config-ref="SAP_Outbound" doc:name="Send IDoc" doc:id="5b8c5850-5988-495c-92cf-79a0c8a09bb4" key="MATMAS01"/>
		<logger level="INFO" doc:name="Logger" doc:id="67d19205-f5c8-4770-a843-47e59ec1c3d2" message="#[payload]"/>
	</flow>
</mule>
----

===  SAP JCo架构

SAP JCo促进SAP后端系统和Java应用程序之间的通信。它允许Java程序连接到SAP系统并调用远程功能模块。它还允许解析IDoc（SAP中间文档）以及其他对象类型。支持入站和出站通信。

*  Java API：处理动态元数据查找和缓存。它实现JCO.Function，它是Java中SAP功能模块（BAPI）的参数和/或表的容器。 Java应用程序构建在Java API之上。

*  JNI（Java本地接口）：最初，SAP使用C语言创建了库，允许直接对SAP调用RFC，以便使用数据进行操作。 JCo将C库封装在Java中以提供对SAP系统的平台本地访问。 RFC中间件通过（JNI）层使用RFC库。

*  RFC（远程函数调用）：通过RFC协议执行与SAP系统的通信。 RFC意味着调用BAPI或触发在另一个系统中运行的IDoc处理作为调用程序。 RFC接口支持两个SAP系统之间或SAP与外部系统之间的函数调用。

*  RFC库：用于访问SAP系统的基于C语言的函数库。 RFC库由JNI解决。

*  RFC层：处理RFC调用的SAP组件。

*  SAP Java IDoc类库：提供Java中SAP IDocs的结构化，高级解释和导航。它由以下附加软件包组成：
**  SAP Java Base IDoc类库：一个独立于中间件的库，为依赖中间件的Java IDoc类库实现提供一组通用基类和接口。
**  SAP Java连接器IDoc类库：用于创建，发送和接收IDoc的独立于中间件的库。

*  FM（功能模块）：功能模块是在SAP的ABAP语言中定义的过程。它允许在SAP系统中封装和重用全局功能。

*  BAPI（业务应用程序编程接口）：是满足特定设计标准的功能模块，例如：
** 实现SAP业务对象的方法。
** 通过不同版本的SAP系统维护一个静态接口。
** 启用了远程功能。
** 运行或不运行用户交互时完成。
** 处理错误。

*  IDoc（中级文档）：用于SAP系统之间电子数据交换的标准SAP格式。不同的消息类型（例如交货单或采购订单）通常对应于不同的特殊格式，称为IDoc类型。但是，具有相关内容的多种消息类型可以分配给单个IDoc类型。

*  ALE（应用程序链接启用）：用于设置和操作分布式应用程序的技术。 ALE促进SAP系统的分布式集成安装。这涉及在松散链接的SAP应用程序之间使用一致数据进行业务驱动的消息交换。应用程序通过同步和异步通信进行集成，而不是通过使用中央数据库。

*  SAP NetWeaver：SAP解决方案使用的主要技术和应用程序平台之一。其主要组件是SAP Web应用程序服务器（WebAS），它为ERP，CRM，SCM，PLM，SRM，BI等SAP应用程序提供运行时环境。其他组件包括企业门户，交换基础架构，主数据管理和移动基础架构。 SAP NetWeaver是这些技术组件的总称。

*  SAP NetWeaver在Java和ABAP堆栈上运行。

*  ABAP（高级商业应用程序编程）：这是SAP专有的编程语言，也是构建业务应用程序的NetWeaver平台的一部分。

== 另请参阅

*  SAP连接器使用RFC协议连接到NetWeaver应用程序服务器（NWAS）。与其他SAP解决方案一样， http://www.cipherbsc.com/solutions/sap-erp-central-component-erp-ecc/[ECC]和https://help.sap.com/viewer/p/SAP_CUSTOMER_RELATIONSHIP_MANAGEMENT[CRM]在NWAS之上运行，因此使用该连接器的任何客户都可以访问这些系统。

