= 示例：获取ServiceNow事件记录
:keywords: anypoint studio, connector, endpoint, servicenow, http
：imagesdir：./_images

这个例子创建一个Mule流程，它根据一个事件编号检索一条记录。

. 创建一个Mule应用程序作为一个项目。
. 添加并配置一个HTTP侦听器作为您的流程的触发器，并设置一个如下所示的路径：
+
`/incident/get`
+
您可以使用Listener连接的默认配置。
+
. 在HTTP侦听器之后，将来自ServiceNow连接器的Invoke操作添加到您的流程中。
. 为与ServiceNow服务器的连接设置并测试ServiceNow配置，例如：
+
* 配置名称：`My ServiceNow Config`
* 用户名：`my_user_name`
* 密码：`my_password`
* 服务地址：`+https://my_account.service-now.com+`
* 服务版本：`Istanbul`
+
如果连接测试不成功，则应更正任何无效的连接参数，然后重新测试连接。
+
. 在ServiceNow配置的传输选项卡中，使用您在常规选项卡中提供的相同用户名和密码设置，测试并保存基本身份验证HTTP消息分发器提供程序，例如：
+
* 用户名：`my_user_name`
* 密码：`my_password`
+
如果连接测试不成功，则应更正任何无效的连接参数，然后重新测试连接。
+
. 为ServiceNow连接器选择Web服务配置值，例如：
+
* 服务：`incident`
* 操作：`getRecords`
+
您需要确保这些值可用作“服务”和“操作”字段中的菜单项。一旦连接器为它们加载元数据，名称就可用。不要手动输入名称。
+
. 为连接器提供转换脚本。
+
在设计中心的Invoke操作中，单击Body的Map按钮，然后单击Body窗口底部的Script选项卡，然后粘贴如下所示的Transformation脚本：
+
----
%dw 2.0
output application/xml
ns inc http://www.service-now.com/incident
---
{
    inc#getRecords: {
        inc#number: "INC0012345"
    }
}
----
+
请注意，此示例将`output`数据类型更改为`application/xml`。
+
. 将记录器添加到以`payload`为消息的流程末尾。
. 部署，同步或运行应用程序。
. 要测试该应用，请从浏览器或邮局等应用中打开`+http://url.for.your.app:8081/incident/get+`。
+
答案应该看起来像这样（为简洁起见，省略了许多字段）：
+
----
<getRecordsResponse xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <getRecordsResult>
    <active>1</active>
    <additional_assignee_list/>
    <approval>not requested</approval>
    <business_stc>0</business_stc>
    <calendar_duration/>
    <calendar_stc>0</calendar_stc>
    <caller_id>6816f79cc0a8016401c5a33be04be441</caller_id>
    <category>inquiry</category>
    <escalation>0</escalation>
    <knowledge>0</knowledge>
    <made_sla>1</made_sla>
    <notify>1</notify>
    <number>INC0021195</number>
    <opened_at>2017-07-27 03:13:54</opened_at>
    <opened_by>6816f79cc0a8016401c5a33be04be441</opened_by>
    <order>0</order>
    <priority>5</priority>
    <short_description>Server outage</short_description>
    <state>1</state>
    <sys_class_name>incident</sys_class_name>
    <sys_created_by>admin</sys_created_by>
    <sys_created_on>2017-07-27 03:14:52</sys_created_on>
    <sys_domain>global</sys_domain>
  </getRecordsResult>
</getRecordsResponse>
----

== 另请参阅

link:/connectors/servicenow-about[关于ServiceNow连接器]

link:/connectors/servicenow-reference[ServiceNow连接器技术参考]

////
. 在HTTP组件后面添加一个Transform（或Transform Message）组件，并将该值设置为：
. 在HTTP连接器之后添加一个Transform组件，并提供一个如下所示的转换脚本：
+
----
output application/json
---
['description': 'Get Keys Demo']

<getRecordsResult>
  <active>1</active>
  <activity_due/>
  <additional_assignee_list/>
  <approval>not requested</approval>
  <approval_set/> <assigned_to/> <assignment_group/>
  <business_duration/> <business_service/>
  <business_stc>0</business_stc>
  <calendar_duration/>
  <calendar_stc>0</calendar_stc>
  <caller_id>6816f79cc0a8016401c5a33be04be441</caller_id>
  <category>inquiry</category>
  <caused_by/>
  <child_incidents>0</child_incidents>
  <close_code/> <close_notes/> <closed_at/> <closed_by/> <cmdb_ci/> <comments_and_work_notes/> <company/> <contact_type>phone</contact_type>
  <correlation_display/> <correlation_id/> <delivery_plan/> <delivery_task/> <description/> <due_date/>
  <escalation>0</escalation>
  <expected_start/> <follow_up/> <group_list/> <impact>3</impact>
  <incident_state>1</incident_state>
  <knowledge>0</knowledge>
  <location/>
  <made_sla>1</made_sla>
  <notify>1</notify>
  <number>INC0021195</number>
  <opened_at>2017-07-27 03:13:54</opened_at>
  <opened_by>6816f79cc0a8016401c5a33be04be441</opened_by>
  <order>0</order>
  <parent/> <parent_incident/>
  <priority>5</priority>
  <problem_id/>
  <reassignment_count>0</reassignment_count>
  <reopen_count>0</reopen_count>
  <resolved_at/> <resolved_by/> <rfc/>
  <severity>3</severity>
  <short_description>Server outage</short_description>
  <sla_due/>
  <state>1</state>
  <subcategory/>
  <sys_class_name>incident</sys_class_name>
  <sys_created_by>admin</sys_created_by>
  <sys_created_on>2017-07-27 03:14:52</sys_created_on>
  <sys_domain>global</sys_domain>
  <sys_domain_path>/</sys_domain_path>
  <sys_id>3a6a07000fd84300a8144f8ce1050e1b</sys_id>
  <sys_mod_count>0</sys_mod_count>
  <sys_updated_by>admin</sys_updated_by>
  <sys_updated_on>2017-07-27 03:14:52</sys_updated_on>
  <time_worked/>
  <upon_approval>proceed</upon_approval>
  <upon_reject>cancel</upon_reject>
  <urgency>3</urgency>
  <user_input/> <watch_list/> <work_end/> <work_notes_list/> <work_start/>
</getRecordsResult>
</getRecordsResponse>
----
+
请注意，该脚本将输出转换为XML输入中的JSON。
+
////
