=  VM连接器
:keywords: VM, queues, connector
////
*Reference:* link:vm-connector-reference[VM连接器参考]
////

* 发行说明： link:/release-notes/connector-vm[VM连接器发行说明]

VM连接器用于通过异步队列进行应用内和应用程序间通信，这些异步队列可以是暂时的或持久的。

* 瞬时队列比持久队列更快，但在系统崩溃的情况下它们不可靠。
* 持久队列较慢但可靠。

在单个实例上运行时，持久队列通过序列化并将内容存储在磁盘上起作用。

在集群模式下运行时，持久队列由内存网格支持。这意味着当流使用VM连接器将内容发布到队列时，Mule运行时将确定是在相同的源节点中处理该消息，还是将其发送到群集以供其他节点进行拾取。所以使用VM模块可以轻松地在集群中分配负载。

无论哪种方式，交易总是受支持的。

== 何时使用VM连接器

在以下情况使用VM连接器：

* 您希望通过排队机制将消息从一个流传递到另一个流，而不是直接使用`<flow-ref />`。
* 当您想要跨群集分配工作时。
* 当您想与在同一个Mule域中运行的不同应用进行通信时。
* 当您需要简单的排队时，无法证明完整的JMS代理。

== 定义队列

VM `config`定义连接器在其上运行的队列。您可以定义任意数量的配置，每个配置都有自己的一组`queues`，例如：

[source, xml, linenums]
----
<vm:config name="vm">
    <vm:queues>
        <vm:queue queueName="transientQueue" queueType="TRANSIENT" />
        <vm:queue queueName="persistentQueue" queueType="PERSISTENT" />
    </vm:queues>
</vm:config>
----

需要注意的是，在给定`config`内定义的每个`queue`只能被引用特定`config`的操作使用。队列名称（`queueName`不能跨配置重复，并且同一个应用程序或域中不能存在具有相同名称的两个队列。

== 持久队列的限制

使用持久队列时，消息要么写入磁盘，要么分布在集群中，这需要通过网络发送消息。无论哪种情况，消息都需要被序列化。这意味着您发送的内容必须是可序列化的。即使您可以启用Kryo序列化以获得更大范围的可序列化值，但Kryo确实有一些限制。所以，当使用持久队列时，尝试：

* 保持您的值简单。过于复杂的结构可能会导致序列化错误或性能问题，如果它们不容易序列化。
* 使用复杂的Java对象时，请确保它们实现了`Serializable`接口并且符合Java Bean合同。
* 只要相关值符合上述建议，流，JSON对象，地图等通常都可以。

== 另请参阅

link:vm-publish-listen[示例：通过VM连接器发布和收听消息]

link:vm-dynamic-routing[示例：使用VM连接器进行动态路由]

link:vm-publish-response[示例：在VM连接器中发布并获取响应]

link:vm-publish-across-apps[示例：跨不同应用发送消息]

link:vm-reference[VM连接器文档参考]
