= 配置Web服务使用者
:keywords: core, connector, web service consumer, WSS, service, consumer, wsdl, soap

要使用SOAP Web服务操作，您需要创建一个指向您要使用的服务的配置。

Web服务使用者（WSC）连接器具有单一配置。最重要的配置参数是WSDL位置（`wdslLocation`），服务（`service`）和端口（`port`）。如果没有设置任何配置，配置将无效。

WSDL位置是WSDL所在的路径或URL（本地或远程），服务和端口是指定可使用配置执行哪些SOAP操作的参数。

另一个重要的参数是服务地址（`address`），其中指示调度请求的位置。此参数通常在指定服务和端口时自动填充，但有时服务端口对不会指示地址，您需要提供正确的参数。

这是一个简单的配置示例：

。简单的Web服务使用者配置
[source,xml,linenums]
----
<wsc:config name="wsc">
  <wsc:connection
   wsdlLocation="http://www.webservicex.com/globalweather.asmx?WSDL"
   service="GlobalWeather"
   port="GlobalWeatherSoap"/>
</wsc:config>
----

请注意，上面的配置不包含`address`参数，因为`service`和`port`对声明了有效的地址。示例中的WSDL用于全球天气服务，一种公共服务。

== 设置自定义HTTP传输配置

默认情况下，连接器使用简单的非保护HTTP配置来分派所有传出的SOAP消息。对于需要更高级的HTTP配置的情况，可以使用HTTP连接器配置对Web服务使用者进行参数化
这将用于发送消息。看看下面的例子：

。自定义传输Web服务使用者配置
[source,xml,linenums]
----
<http:request-config name="basic-auth">
    <http:request-connection host="www.someplace.com" port="8182" protocol="HTTP">
        <http:authentication>
            <http:basic-authentication username="alejandro.garcia" password="nariz"/>
        </http:authentication>
    </http:request-connection>
</http:request-config>

<wsc:config name="with-custom-transport">
    <wsc:connection wsdlLocation="http://www.host.com?WSDL" service="Service" port="Port">
        <wsc:custom-transport-configuration>
            <wsc:http-transport-configuration requesterConfig="basic-auth"/>
        </wsc:custom-transport-configuration>
    </wsc:connection>
</wsc:config>
----

在此示例中，声明了具有HTTP基本身份验证的HTTP Requester配置，然后在WSC配置中的`custom-transport-configuration`元素中引用该配置。
现在，WSC将使用所提供的高级配置分派每个请求。

请注意，Web服务使用者配置也支持WSS安全策略。有关更多信息，请参阅下面的技术参考链接。

== 设置Web服务安全性

WS-Security（WSS）协议指定了如何对消息实施完整性和机密性，并允许各种安全令牌格式的通信。其主要重点是使用XML Signature和XML Encryption来提供端到端的安全性。

WS-Security描述了三种主要机制：

* 如何签署SOAP消息以确保完整性。签名的消息也提供不可否认性。
* 如何加密SOAP消息以确保机密性。
* 如何附加安全令牌以确定发件人的身份。

Web服务使用者支持以下机制：

* 时间戳
* 签名/签名验证
* 用户名
* 加密/解密

具有用户名WSS状态的配置示例：

[source,xml,linenums]
----
<wsc:config name="with-custom-transport">
    <wsc:connection wsdlLocation="http://www.host.com?WSDL" service="Service" port="Port">
        <wsc:web-service-security>
            <wsc:username-token-security-strategy username="admin" password="textPassword" addCreated="true" addNonce="true"/>
        </wsc:web-service-security>
    </wsc:connection>
</wsc:config>
----

请参阅： link:web-service-consumer-reference[Web服务消费者技术参考]了解如何配置每个WSS策略并查看与其关联的每个参数的描述。


== 另请参阅

*  link:web-service-consumer-consume[消费Web服务]
*  link:http-connector[HTTP连接器文档]
*  link:web-service-consumer-reference[Web服务消费者技术参考]
