= 示例：将基金添加到财务管理服务
:keywords: anypoint studio, connector, workday, wsdl

本示例使用Workday连接器中的Invoke操作将资金插入财务管理服务。

. 创建一个Mule应用程序作为设计中心或Studio 7 Mule项目。
+
. 为您的应用中的流添加并配置触发器，例如HTTP侦听器或计划程序。
+
您可以接受HTTP侦听器或调度程序的默认设置并提供任何所需的值。
. 为您的流添加一个Transform组件，并使用Script选项卡中的字段添加DataWeave转换脚本。
+
例：
+
[source,dataweave,linenums]
----
%dw 2.0
output application/xml
ns ns0 urn:com.workday/bsvc
---
{
  ns0#Put_Fund_Request @(ns0#Add_Only: true, ns0#version: "v28.0"): {
    ns0#Fund_Data: {
      ns0#Fund_Name: "I.M.F",
      ns0#Fund_Type_Reference: {
        ns0#ID @(ns0#'type': 'Fund_Type_ID'): "FUND_TYPE-6-3"
      }
    }
  }
}
----
+
. 在Transform组件之后添加Workday-Invoke操作。
. 从Invoke操作中，配置，测试并保存与Workday服务器的连接。
+
配置示例：
+
* 配置名称：`My Workday Connection`
* 用户名：`my_workday_username`
* 密码：`my_workday_password`
* 租户名称：`my_workday_tenant_name`
* 主机名称：默认为`impl-cc.workday.com`
+
. 在调用操作的常规侧面选项卡中，提供Web服务配置参数。
+
例：
+
* 服务：`Financial Management`
* 操作：`Put_Fund`
+
. 添加记录器到您的流的末端，需要一个`payload`（或`#[payload]`）作为消息。
. 部署或运行​​您的应用。
. 一旦状态为运行，请检查响应。
+
如果您使用的是HTTP侦听器，则可以浏览到您的侦听器URL，例如：`http://<app_url>:8081/fund`。
+
如果您使用调度程序，则可以在日志中找到响应。
+
您应该收到类似于以下代码段的XML响应：
+
[source,xml,linenums]
----
<wd:Put_Fund_Response xmlns:wd="urn:com.workday/bsvc" wd:version="v28.0">
    <wd:Fund_Reference wd:Descriptor="I.M.F">
        <wd:ID wd:type="WID">THE_WID_ID_NUMBER</wd:ID>
        <wd:ID wd:type="Fund_ID">FUND-6-399</wd:ID>
    </wd:Fund_Reference>
</wd:Put_Fund_Response>
----

== 另请参阅

link:/connectors/workday-about[关于Workday连接器]

link:/connectors/workday-reference[工作日连接器参考]

////

字段说明
用户名
登录Workday的用户名。
密码
用户名的工作日密码。
租户名称
工作日租户ID。它通常附加pt_1（例如，acme_pt1）。
主机名
主机名称Workday Cloud Server。默认：impl-cc.workday.com。
运输

+
可选 - 支持用户定义的HTTP请求配置，用于设置代理连接。
高级
可选 - 用于调整重新连接策略和连接池配置文件。
配置Workday操作。
+

Workday Connector Reference提供配置详细信息。

////
