= 示例：在Workday中创建职位申请
:keywords: anypoint studio, connector, endpoint, workday, http
：imagesdir：./_images

这个例子创建了一个产生Workday位置请求的Mule流。

. 创建一个Mule应用程序作为一个项目。
. 添加并配置一个HTTP侦听器作为您的流程的触发器，并设置一个如下所示的路径：
+
`/create_position`
+
您可以使用Listener连接的默认配置。
+
. 在HTTP侦听器之后，将Workday连接器的Invoke操作添加到您的流程中。
. 为与Workday服务器的连接设置，测试和保存Workday配置，例如：
+
* 配置名称：`My Workday Config`
* 用户名：`my_user_name`
* 密码：`my_password`
* 租户名称：`my_tenant_name`
* 主持人姓名：`impl-cc.workday.com`
+
如果连接测试不成功，则应更正任何无效的连接参数，然后重新测试连接。
+
. 选择Workday连接器的Web服务配置值，例如：
+
* 服务：`Staffing`
* 操作：`Create_Position`
+
您需要确保这些值可用作“服务”和“操作”字段中的菜单项。一旦连接器为它们加载元数据，名称就可用。不要手动输入名称。
+
. 为连接器提供转换脚本。
+
在设计中心的Invoke操作中，单击Body的Map按钮，然后单击Body窗口底部的Script选项卡，然后粘贴如下所示的Transformation脚本：
+
----
%dw 2.0

ns ns0 urn:com.workday/bsvc


output application/xml
---
{
  ns0#Create_Position_Request: {
    ns0#Business_Process_Parameters: {
      ns0#Auto_Complete: true,
      ns0#Run_Now: true
    },
    ns0#Create_Position_Data: {
      ns0#Supervisory_Organization_Reference: {
        ns0#ID @("ns0:type": "Organization_Reference_ID"): "SUPERVISORY_ORGANIZATION-6-226"
      },
      ns0#Position_Data: {
        ns0#Job_Posting_Title: "General Manager"
      },
      ns0#Position_Group_Restrictions_Data: {
        ns0#Availability_Date: "2017-07-06",
        ns0#Earliest_Hire_Date: "2017-07-08"
      },
      ns0#Edit_Assign_Organization_Sub_Process: {
        ns0#Business_Sub_Process_Parameters: {
          ns0#Skip: true
        }
      },
      ns0#Request_Default_Compensation_Sub_Process: {
        ns0#Business_Sub_Process_Parameters: {
          ns0#Skip: true
        }
      },
      ns0#Assign_Pay_Group_Sub_Process: {
        ns0#Business_Sub_Process_Parameters: {
          ns0#Skip: true
        }
      },
      ns0#Assign_Costing_Allocation_Sub_Process: {
        ns0#Business_Sub_Process_Parameters: {
          ns0#Skip: true
        }
      }
    }
  }
}
----
+
请注意，此示例将`output`数据类型更改为`application/xml`。
+
. 将记录器添加到以`payload`为消息的流程末尾。
. 部署，同步或运行应用程序。
. 要测试该应用，请从浏览器或邮局等应用中打开`+http://url.for.your.app:8081/create_position+`。
+
答案应该是这样的：
+
----
<wd:Create_Position_Response xmlns:wd="urn:com.workday/bsvc" wd:version="v28.0">
  <wd:Event_Reference>
  <wd:ID wd:type="WID">3cacb7ed3b2101980a03da33b32afe63</wd:ID>
  </wd:Event_Reference>
  <wd:Position_Reference>
    <wd:ID wd:type="WID">3cacb7ed3b210131334ede33b32a0664</wd:ID>
    <wd:ID wd:type="Position_ID">P-11158</wd:ID>
  </wd:Position_Reference>
</wd:Create_Position_Response>
----
+
记录器产生这样的消息：
+
----
{Create_Position_Response={Event_Reference={ID=3cacb7ed3b2101980a03da33b32afe63}, Position_Reference={ID=P-11158}}}
----

== 另请参阅

link:/connectors/workday-about[关于Workday连接器]

link:/connectors/workday-reference[Workday连接器技术参考]
