=  X12 EDI模式语言参考

X12 EDI模块使用名为ESL（用于EDI模式语言）的YAML格式来表示EDI模式。基本ESL根据结构，段，组合和元素定义EDI消息的结构。 ESL支持X12，EDIFACT，TRADACOMS和HL7。

==  ESL文档的组件

ESL文档中的顶层定义给出了正在使用的EDI标准（支持X12，EDIFACT，HL7和TRADACOMS），该标准的版本，导入ESL的可选列表，以及任何结构，段列表的组合，复合和元素定义。以下是`/x12/005010/850.esl`模式中这些顶级定义的样子：

[source,yaml, linenums]
----
form: X12
version: '005010'
imports: [ '/x12/005010/basedefs.esl' ]
structures:
- id: '850'
  name: Purchase Order
  class: PO
  ...
----

该模块包含每个X12和EDIFACT版本名为`basedefs.esl`的ESL，该版本提供标准段，复合和元素定义。 850采购订单的这个例子导入这些采购订单以重新定义定义采购订单结构的定义。

== 结构定义

结构定义表示X12事务集或EDIFACT消息，由标准特性的键值对和组成实际结构的段列表组成。细分列表被组织到标题，细节和摘要部分。分段可以被进一步组织为由潜在重复的分段序列组成的组。

以下是样本结构定义的一部分，同样来自`/x12/005010/850.esl`模式：

[source,yaml, linenums]
----
- id: '850'
  name: Purchase Order
  class: PO
  heading:
  - { idRef: 'ST', position: '0100', usage: M }
  - { idRef: 'BEG', position: '0200', usage: M }
  - { idRef: 'CUR', position: '0400', usage: O }
  - { idRef: 'REF', position: '0500', usage: O, count: '>1' }
  - { idRef: 'PER', position: '0600', usage: O, count: 3 }
  - { idRef: 'TAX', position: '0700', usage: O, count: '>1' }
  - { idRef: 'FOB', position: '0800', usage: O, count: '>1' }
  - { idRef: 'CTP', position: '0900', usage: O, count: '>1' }
  - { idRef: 'PAM', position: '0950', usage: O, count: 10 }
  - { idRef: 'CSH', position: '1100', usage: O, count: 5 }
  - { idRef: 'TC2', position: '1150', usage: O, count: '>1' }
  - groupId: 'SAC'
    usage: O
    count: 25
    items:
    - { idRef: 'SAC', position: '1200', usage: O }
    - { idRef: 'CUR', position: '1250', usage: O }
  - { idRef: 'ITD', position: '1300', usage: O, count: '>1' }
  - { idRef: 'DIS', position: '1400', usage: O, count: 20 }
  ...
----

基本的结构值是：

[%header, cols="20a,80a"]
|===
|结构键/部分 |说明
| id  |结构标识符
|名称 |结构名称
|类 |类结构，等同于X12功能组标识符 - 在EDIFACT结构定义中被忽略
|标题 |结构标题部分中的部分和组列表
|详细信息 |结构详细信息部分中的部分和组列表
|摘要 |结构标题部分中的部分和组列表
|===

结构不同部分的分段列表都使用相同的形式。列表中的每个项目都是段引用或组定义。段引用使用紧凑的YAML语法显示，其中每个引用的值都以逗号分隔的键值对的形式给出，并用大括号括起来。

这些值是：

[%header, cols="20a,80a"]
|===
|细分属性 |说明
| idRef  |引用的段ID
|位置 |段中的段位置（通过EDI约定，这些是可能包含前导零的数值，因此被引用和处理为字符串）
|用法 |使用代码，可能是：

有条件的*  C
*  M为强制性
*  O代表可选
*  U代表未使用
|计数 |最大重复计数值，可能是数字或特殊值`>1`，表示任意重复次数（可选，如果未指定，则使用计数值1）
|===

组定义以展开的形式显示，其中键值对位于不同的行上。组定义中的值是：

[%header, cols="20a,80a"]
|===
|值| 说明
| groupId  |组标识符
|用法 |使用代码，可能是：

有条件的*  C
*  M为强制性
*  O代表可选
*  U代表未使用
|计数 |最高重复计数值，可能是一个数字或特殊值`>1`，表示任意重复次数（可选，如果未指定，则使用计数值1）
|项 |构成组的分段列表（以及潜在的嵌套组）
|===

== 细分定义

段定义再次由标准特性的一些键 - 值对以及组成实际段的值列表（元素和组合）组成。以下是来自`/x12/005010/basedefs.esl`架构的样本段定义的一部分 - 用法：M是强制性的，O是可选的：

[source,yaml, linenums]
----
- id: 'BAK'
  name: Beginning Segment for Purchase Order Acknowledgment
  values:
  - { idRef: '353', usage: M }
  - { idRef: '587', usage: M }
  - { idRef: '324', usage: M }
  - { idRef: '373', usage: M }
  - { idRef: '328', usage: O }
  - { idRef: '326', usage: O }
----

分段定义值是：

[%header, cols="20a,80a"]
|===
| {节{1}}说明
| ID  |段标识符
|名称 |段名称
|值 |段中的元素和合成列表
|===

值列表通过ID引用元素和组合，使用紧凑的YAML语法显示，其中每个引用的值都以逗号分隔的键值对的形式给出，并用大括号括起来。这些参考值是：

[%header, cols="20a,80a"]
|===
| {节{1}}说明
| idRef  |被引用的元素或复合ID
|位置 |段中的值位置（可选，通常不使用;默认情况下，位置从1开始，每个连续值增加1）
|名称 |段中的值的名称（默认情况下使用的可选，元素或复合名称）
|用法 |使用代码，可能是：

有条件的*  C
*  M为强制性
*  O代表可选
*  U代表未使用
| count  |最大重复计数值，可以是任意数字或特殊值'> 1'，表示任意重复次数（可选，如果未指定，则使用计数值1）
|===

== 复合定义

复合定义与段定义非常相似，同样由标准特性的一些键 - 值对以及构成实际复合的值列表（元素和组合）组成。以下是来自`/x12/005010/basedefs.esl`模式的示例复合定义的一部分：

[source,yaml, linenums]
----
- id: 'C022'
  name: 'Health Care Code Information'
  values:
  - { idRef: '1270', usage: M }
  - { idRef: '1271', usage: M }
  - { idRef: '1250', usage: C }
  - { idRef: '1251', usage: C }
  - { idRef: '782', usage: O }
----

复合定义值是：

[%header, cols="20a,80a"]
|===
| {名称{1}}说明
| id  |合成标识符
|名称 |合成名称
|为组合内的元素和合成列表 |列表
|===

值列表通过ID引用元素和组合，使用紧凑的YAML语法显示，其中每个引用的值都以逗号分隔的键值对的形式给出，并用大括号括起来。这些参考值是：

[%header, cols="20a,80a"]
|===
| {名称{1}}说明
| idRef  |被引用的元素或复合ID
|位置 |组合中的值位置（可选，通常不使用;默认情况下，位置从1开始，每个连续值增加1）
|用法 |使用代码，可能是：

有条件的*  C
*  M为强制性
*  O代表可选
*  U代表未使用
|===

== 元素定义

元素定义非常简单，由标准特性的基本键值对组成。

以下是来自`/x12/005010/basedefs.esl`模式的几个元素定义：

[source,yaml, linenums]
----
elements:
  - { id: '1', name: 'Route Code', type: AN, minLength: 1,
      maxLength: 13 }
  - { id: '100', name: 'Currency Code', type: ID, minLength: 3,
      maxLength: 3 }
  - { id: '1000', name: 'Service Characteristics Qualifier',
      type: AN, minLength: 2, maxLength: 3 }
----

元素定义值是：

[%header, cols="20a,80a"]
|===
| {名称{1}}说明
| id  |元素标识符
|名称 |元素名称
|类型 |值类型代码，可能是（当前不支持Binary数据类型）：

*  N为整数
*  N0-N9代表在指定位置有隐含小数点的数字（N0相当于N）
*  R为十进制数字
标识符的*  ID
*  AN用于字母数字字符串
*  DT代表日期
* 一段时间

| minLength  |值中有效字符的最小数量
| maxLength  |值中有效字符的最大数量
|===
